### ISSUE TITLE
Release 2.6.5 pending urgent fixes (should hopefully be the last beta before production)

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#1001]
Unfortunately, we have discovered two pretty big issues with the current beta:

- [ ] My last fix for sending logs only to private Google group forum was overridden at some point (re-sent PR, see #1000 )
- [ ] The crash that Tobias mentioned at #998 

Seems like pushing to production will not be wise with both of the above. Pending these fixes, we will release 2.6.5 which should hopefully FINALLY be sent to production.

**Comment by maskaravivek** [comment]
@misaochan Can this be now closed?

**Comment by misaochan** [comment]
Yes, thanks for pointing out!
