### ISSUE TITLE
Black background on details and categories screen

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#1004]
A student with an Android 4.2.2 Samsung Galaxy GT-S7583T always gets a black background at the details and categories screens:
![](https://github.com/commons-app/apps-android-commons/blob/master/design/screenshots/Hebrew%20iw-IL/car-description.png?raw=true)
More screenshots with 3 different pictures: https://github.com/commons-app/apps-android-commons/tree/master/design/screenshots/Hebrew%20iw-IL
Might be due to relatively low RAM (0.75 GB). Black background is better than crashing, so it is not high-priority. That phone should definitely be able to load the picture though, so we are probably trying to load it in a memory-inefficient way (I assume the same pictures show up fine at the same size in the Android stock gallery). Actually I got this same problem when trying to upload a very heavy picture.

> I left it sitting on the category search for hours once, and the picture never showed up there...

**Comment by superplane39** [comment]
I'm the student who encountered the problem; I'd be interested in helping out, if possible, and help test issues :)

**Comment by harisankerPradeep** [comment]
I feel that downsampling and resizing functions of fresco, given [here](http://frescolib.org/docs/resizing.html), can solve this issue. For example, my screen resolution is 720x1280 and the maximum resolution of my camera is 3280x2160. Knowing this I should be able to resize the image without any loss in quality of the displayed picture, right? Or am I getting this wrong somewhere?

Thanks in advance!

**Comment by nicolas-raoul** [comment]
Resizing is definitely the best way to solve this problem, indeed.
This background image feature *might* be removed in the future (see #1044), but if it is easy and safe then feel free to implement it @harisankerPradeep  :-)

**Comment by harisankerPradeep** [comment]
@nicolas-raoul  From what I can see in the fresco docs it seems simple and safe. I'll post some updates soon enough.
