### ISSUE TITLE
Revamp UI of About page and add our FB page link to it

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#1005]
Now that we have a somewhat active [Facebook page](https://www.facebook.com/WikimediaCommonsApp/) , it might be a good idea to add it to the app in a non-intrusive way so that users can follow for updates if they want to (also good for fostering a community around the app). The absolute most non-intrusive way would be to add it to the About activity, though that would be a bit obscure. If we can figure out a nice layout, adding it to the nav drawer instead (via the 'f' icon) could be an idea - though I am always open to opposition. ;)

This could be made a beginner-friendly task once we decide what exactly we want to do.

**Comment by nicolas-raoul** [comment]
My vote goes to the About page :-) I think that's the right place for it, and people who would be interested in the content of the Facebook page are the same people who are likely to check the About dialog.

**Comment by misaochan** [comment]
About page sounds good to me. It may be a good idea to organize it a little bit perhaps, have little icons for "GitHub", "Facebook", "Google groups forum" etc instead of just a lot of text links?

**Comment by VojtechDostal** [comment]
I'd love this :-)

**Comment by tshradheya** [comment]
I would like to work on this.

**Comment by maskaravivek** [comment]
@tshradheya Feel free to take it up. :)

**Comment by tshradheya** [comment]
Is there any mock up of the UI that you would like to follow, or going with the current style is fine? 

I thought of following @misaochan 's idea but I am not sure where to place the text that already exists

**Comment by VojtechDostal** [comment]
I guess going with the current style can't hurt - any overhaul should be systematic and not just in 1 place :-)

You're probably gonna have to remove a sentence and add icons instead :-) Be creative.

**Comment by misaochan** [comment]
Happy to hear that you would like to take this task up, @tshradheya . :)

We need to preserve the first paragraph verbatim ("The Wikimedia Commons app is an...." to "...maintenance of the app.") as this is a legal requirement for us. Aside from that, feel free to be creative, haha. If you like, you can post a mockup here before doing the actual coding, this may save time for you as people can give you feedback on your proposed design before you start coding.

**Comment by tshradheya** [comment]
![layout-2018-01-20-010236](https://user-images.githubusercontent.com/12574756/35162519-998cddaa-fd7e-11e7-837b-39bea2e02b1d.png)

Here is what I made

**Comment by misaochan** [comment]
Looks good to me. :) @neslihanturan @nicolas-raoul what do you think?

**Comment by maskaravivek** [comment]
@tshradheya Awesome!

**Comment by tshradheya** [comment]
Great. I will create a PR by tonight then :+1
