### ISSUE TITLE
Use EXIF date rather than upload date

### ISSUE THREAD

**Issue by Abbe98** [commons-app/apps-android-commons#1013]
The file below automatically got the date 2017-12-10 during upload but in the meta data field the date is set to 29 October 2017. 

https://commons.wikimedia.org/wiki/File:Fågelskyddsområde_skylt_1.jpg

**Expected result** the date parameter would be set to 2017-10-29 not the date of the upload.

**Comment by nicolas-raoul** [comment]
Thanks for the feedback!
Make sense indeed!

**Comment by deydebaditya** [comment]
I would like to try out developing the patch for this.

**Comment by KatyaTulit** [comment]
Hi, I may sound stupid but I don't get how I can debug this issue. When I upload a photo using 2.6.7. version, the date that I see on the website is actually the date of creation (which is already an expected result) https://commons.wikimedia.org/wiki/File:Tanneries_in_Fes.jpg 

However, when I use Beta Commons and post the same picture using the most current version of the code - I can't see the date (it says Template:According to EXIF data) 
https://commons.wikimedia.beta.wmflabs.org/wiki/File:Tanneries_Fes.jpg

**Comment by nicolas-raoul** [comment]
@KatyaTulit Don't worry too much about beta (where various things are missing), feel free to experiment by uploading on the real Commons. A week after please just remember to nominate your test pictures for deletion. Or I can send you good images that I haven't uploaded yet, if you want?

**Comment by KatyaTulit** [comment]
@nicolas-raoul Thanks. I will just nominate pictures for deletion afterwards. 

I will try uploading different images in the released version (2.6.7) in hope to reproduce the issue. So far, I haven't been able to reproduce the behaviour (upload date instead of creation date visible on the website). Maybe the bug has been fixed already (Abbe98 faced this issue using 2.6.3 version)

**Comment by misaochan** [comment]
Is anyone currently working on this?

**Comment by ondro2208** [comment]
I would like to work on this issue.

**Comment by nicolas-raoul** [comment]
No news from @deydebaditya , so feel free to work on this @ondro2208 :-)

**Comment by sank20** [comment]
Hi, I'd like to look into this issue.

**Comment by ondro2208** [comment]
I am already started, so may be you can choose different one

**Comment by ondro2208** [comment]
I am little bit concern about which date should be changed. As you can see there is more than one place where date is used. Could someone tells me exactly which date should be changed?
![topofpage](https://user-images.githubusercontent.com/22798209/48300217-add12080-e4d9-11e8-8aab-09cdc018200f.png)
![downofpage](https://user-images.githubusercontent.com/22798209/48300220-b295d480-e4d9-11e8-8dfd-043558688e86.png)

**Comment by ashishkumar468** [comment]
@maskaravivek and I have already added a fix for the same, and the PR will soon be merged in master. I would suggest to wait for a few days before taking up this issue, master may already have the fix for the same

**Comment by domdomegg** [comment]
@ashishkumar468 Did that fix you were talking make it in? Can this be closed?

**Comment by ondro2208** [comment]
> @ashishkumar468 Did that fix you were talking make it in? Can this be closed?

I think so. There is nothing to do.
