### ISSUE TITLE
Team Chat / Discussion Tool

### ISSUE THREAD

**Issue by psh** [commons-app/apps-android-commons#1015]
I've noticed that we use Github issues to chat / discuss things.  I live my life on both Slack and Discord - would it help to make use of one of those kinds of tools?

**Comment by nicolas-raoul** [comment]
A problem with these tools is that (as far as I know) they make it difficult for newcomers and lurkers to read where an issue comes from, what people thought about it, and what has been tried before.

**Comment by misaochan** [comment]
As Nicolas said, we generally try and keep most of the project-related and technical discussions on GitHub itself. However, we do have a Google Hangouts group that we use for general chatting and stuff like "new beta out, please help test!". :) If anyone is interested in joining, feel free to email me and I'll add you!

**Comment by mithlesh4257** [comment]
I agree to @misaochan and @nicolas-raoul , It will be too difficult for newcomers to join open source community.
