### ISSUE TITLE
With transparent files have an option to turn the background white

### ISSUE THREAD

**Issue by domdomegg** [commons-app/apps-android-commons#102]
Transparent files that are mostly black/near black are hard to see:
![screenshot_20160531-121414](https://cloud.githubusercontent.com/assets/4953590/15672554/4477e22e-2729-11e6-8067-8639e0fc0b01.png)
![screenshot_20160531-120845](https://cloud.githubusercontent.com/assets/4953590/15672500/e80b21e0-2728-11e6-8194-78a3d338948c.png)

It would be good to have an option to toggle background between black/white.
![20160531_121119](https://cloud.githubusercontent.com/assets/4953590/15672499/e800e3a6-2728-11e6-82a3-b77f49b82f26.jpg)

(The first image is this one: https://upload.wikimedia.org/wikipedia/commons/d/df/Linear_Potential_Sweep.svg)

**Comment by nicolas-raoul** [comment]
Thanks for the feedback!
Just being curious: Do you make these images on Android?
Or do you upload them with Android?
Or do you upload them otherwise, and then want (or need?) to see them using Upload To Commons?
Cheers!

**Comment by domdomegg** [comment]
Nah, I make them on Inkscape on my desktop, and usually upload them via desktop. Just for viewing purposes it would be good to see the images (I don't really need to see them, but it would be good to have).

But then again it works fine just to press 'view in browser', I don't really know how hard it would be to implement.

**Comment by YoCoB** [comment]
Hi,

I'd like to work on this issue !

**Comment by nicolas-raoul** [comment]
Sorry I believe Sam's team is working on it already... Sam's team, please post a comment here so that we can label the issue as assigned, so that other people like YoCoB are not left disappointed. Thanks! :-)

**Comment by SamuelleMollard** [comment]
Yes, they are, YoCoB is part on my team.
Sorry for the misunderstanding

**Comment by nicolas-raoul** [comment]
@SamuelleMollard OK I understand now haha
@YoCoB It is yours :-)

**Comment by SamuelleMollard** [comment]
My team should have done that, I have integrated it in the PR

**Comment by Rishavgupta12345** [comment]
is this issue still needed to be done? I don't find it relevant anymore.

**Comment by nicolas-raoul** [comment]
@Rishavgupta12345 Still relevant, still needed.

**Comment by XxBrezxX** [comment]
is someone working on this? I could work on this

**Comment by nicolas-raoul** [comment]
@XxBrezxX Please focus on one issue at a time :-) Thanks for your enthusiasm!

**Comment by praveen7512** [comment]
Can i work on this issue?

**Comment by Pierre-Monier** [comment]
@praveen7512 Any news on this ?

**Comment by Pierre-Monier** [comment]
Since there is more than a month that the latest assigned person has asked to work on that, and since there is no news, I made a pull request related to that issue. I think it doesn't break the code of conduct, but I apologize if I'm wrong.
