### ISSUE TITLE
Filter out irrelevant categories

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#1029]
![screenshot_20171125-235725](https://user-images.githubusercontent.com/99590/34403428-8b33a1d4-ebeb-11e7-8157-a1f05b814586.png)
This was an experiment that has been abandoned, but the 300 categories remain: https://commons.wikimedia.org/wiki/Commons:Image_classification_system

Tip for newcomers: https://github.com/achalshant/apps-android-commons/commit/3681176f54d1fbd00408216a4ed5641b583d3054

**Comment by nicolas-raoul** [comment]
We can skip all "in the XXXXs" categories except 2000s and 2010s, as people should not use the app to upload very old pictures.
![screenshot_20171205-154359](https://user-images.githubusercontent.com/99590/34404630-1fded974-ebf2-11e7-9651-0b360c1ed507.png)

**Comment by janani-sridhar** [comment]
Hi, I'll start working on this issue!

**Comment by janani-sridhar** [comment]
Hi there, 

I have forked achalshant's branch and added my code here: https://github.com/janani-sridhar/apps-android-commons/blob/master/app/src/main/java/fr/free/nrw/commons/category/PrefixUpdater.java

I'm not sure how to create a pull request for this fix, considering that I was working off of achalshant's branch. Hope to hear some feedback and advice soon!

**Comment by nicolas-raoul** [comment]
Please merge master into your branch, then rebase. Thanks! 🙂

**Comment by junkiattan** [comment]
@nicolas-raoul 

This issue seems to be open! can I take this up?

**Comment by misaochan** [comment]
@janani-sridhar Could you please let you know if you are still working on this? We would like to give the issue to @junkiattan if you aren't. :) Thanks!

**Comment by junkiattan** [comment]
@misaochan @nicolas-raoul 
Can I take this issue? Ill try to submit a PR soon!

**Comment by nicolas-raoul** [comment]
OK!

**Comment by neslihanturan** [comment]
@junkiattan handled some parts of this issue recently, however it requires more effort. So, I wont close this now.

**Comment by neslihanturan** [comment]
Currently we filtered out before 2000s as it has written as XXXX format. But can we describe what do we exactly want to filter out?

**Comment by junkiattan** [comment]
@neslihanturan @nicolas-raoul 

I can further extend the part of the code I touched to exclude the YY.MM.DD formats that do not pass a certain year. However the years are expressed in 2 digits, hence it is a little tricky to set a cut off year (e.g. should 99 now be defined as old?)

**Comment by misaochan** [comment]
I would personally consider 99 to be "old" in the context of smartphones. But indeed the 2 digit years are a problem. I guess we could go with allowing '1x' and '0x' through and filter out the others?

**Comment by junkiattan** [comment]
@misaochan 
That can be done! Actually I was thinking of including 2x too, since 201x is coming to an end. What do you think?

**Comment by misaochan** [comment]
@junkiattan We've got a good 2 years before that happens, so IMO not necessary, we can make that change when it happens. ;)

**Comment by nicolas-raoul** [comment]
@junkiattan Please do not filter based on the "YY.MM.DD" format. I guess you got confused because of my "Image class" screenshot, which is unrelated. I should probably have created separate issues.

Only filter out categories that end with the string " in the XYZ0s" (X being a digit, and YZ being either a digit or nothing).
Thanks!

**Comment by junkiattan** [comment]
@nicolas-raoul 

I have already done this in my first PR for this issue. Can this be closed now then? If so then I will close my second PR

**Comment by neslihanturan** [comment]
Yes @junkiattan maybe you can close your second PR and I can close the issue. Thanks for quick responses.
