### ISSUE TITLE
Spinning wheel overlaps on text input, when using Hebrew locale

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#1030]
Even though the phone's locale is in Hebrew, categories all use Latin characters I believe.

As seen below, the blue spinning wheel overlaps the entered text "mochi":

![screenshot_ -](https://user-images.githubusercontent.com/99590/34404210-e012a50c-ebef-11e7-80ef-64cf714c046d.png)

**Comment by Nickthemaster13** [comment]
Hello,I would like to contribute to this project by fixing this issue

**Comment by tanvidadu** [comment]
I unable to reproduce the same error.
Please help me with the this so I start working on this.

**Comment by neslihanturan** [comment]
Changing phone local would work. However I can suggest to focus on one issue at a time. Since you are working on #1040 we prefer to get your other PR first. Then if you still want to take this, I will label it as assigned. But currently this task is open for everyone.

**Comment by rjb2179** [comment]
Hi, I sent a PR for #1065 the other day. I could work on this. @neslihanturan

**Comment by neslihanturan** [comment]
I write a comment on the PR @rjb2179 and this issue is yours, happily scope of this task is defined better.

**Comment by rjb2179** [comment]
@neslihanturan what exactly are you suggesting when you say change the phone locale? Should Categories not accept the Hebrew locale?

**Comment by nicolas-raoul** [comment]
Unfortunately categories are only in English (this is outside of our control. There is a plan to make them multilingual, but that will probably take 5 years or more, maybe it will never happen).

But to reproduce the error, you must change your phone to the Hebrew locale (if you have not done it already). This means Android will display all system menus/etc in Hebrew. Just remember visually the procedure to change back afterwards, and you should be fine.

**Comment by rjb2179** [comment]
@neslihanturan I'm not working on this anymore. 
sorry :(

**Comment by neslihanturan** [comment]
Don't worry @rjb2179 . This task is free for new beginners from now on:)

**Comment by diddypod** [comment]
This error arises for any locale which uses language read from right to left. Since category search is implemented only in English, it is expected that the user will use English in category search. The simplest fix is to force the EditText gravity to the left and the ProgressBar gravity to the right, instead of letting it adapt to the locale, as the keyboard input in English doesn't adapt to the locale's reading direction.

**Comment by neslihanturan** [comment]
Thanks for clarification @diddypod

**Comment by diddypod** [comment]
I have implemented this fix. If it's acceptable, may I send a PR for the same, @neslihanturan?

**Comment by neslihanturan** [comment]
@diddypod yes there is no PR for this task according to my last check. So please share your PR, I will be here yo test it:)

**Comment by diddypod** [comment]
@neslihanturan, thank you. I've made a PR ([#1162](https://github.com/commons-app/apps-android-commons/pull/1162)). Please check :)

**Comment by RiccardoGrigoletto** [comment]
Hello everyone! I am here to pick up an easy issue in order to prove my skill to Vivek Maskara for the GSoC 2018 edition. Can I try to resolve this one?

**Comment by nicolas-raoul** [comment]
@neslihanturan has merged a pull request for this, so I guess the issue has been fixed already?
Sorry @RiccardoGrigoletto I close the issue now, would you mind choosing another one? Thanks! :-)
