### ISSUE TITLE
Revamp the Settings page

### ISSUE THREAD

**Issue by sivaraam** [commons-app/apps-android-commons#1039]
- [ ] Categorize the items so that user is able to get what he wants quickly. Possible categories for the currently available content are *Appearance, General, Feedback*
 - [ ] Clarify why disabling "Use Wikidata" would cause huge data consumption. This could be done possibly by using a 'Learn more' link to a page that explains the reason.
 - [ ] The heading 'License' isn't clear enough. 'Default license' would possibly be better
 - [ ] Use [toggle buttons](https://material.io/guidelines/components/buttons.html#buttons-toggle-buttons) instead of [checkboxes](https://material.io/guidelines/components/selection-controls.html#selection-controls-checkbox) as toggle buttons are more suitable for two state settings like "Night mode".

It would be nice if the [material design guidelines for Settings](https://material.io/guidelines/patterns/settings.html) was considered while doing this. I find their suggestion to be one that aims for an intuitive interface.

**Comment by misaochan** [comment]
Agreed completely with the revamp, especially with using material design guidelines and categorization of items.

**Comment by afswift** [comment]
If this issue isn't being worked on currently, I would love to tackle this issue. I've been working with android studio for a few months now. 

If this is needed for parsing through:

I start working on this

**Comment by misaochan** [comment]
@afswift Go for it. :)

**Comment by sivaraam** [comment]
@misaochan Sorry for the off-topic question. Why do you actually use the #assigned tag instead assigning the task to the concerned person?

**Comment by misaochan** [comment]
@sivaraam Because GitHub doesn't allow us to assign tasks to someone who hasn't yet contributed to the repo I believe. The option just isn't available.

**Comment by madhurgupta10** [comment]
Hi, if the issue is still not resolved, may I please work on it?

**Comment by misaochan** [comment]
@madhurgupta10 I think you can go for it, as @afswift hasn't been around for a couple months now. :)

**Comment by madhurgupta10** [comment]
@misaochan on it

**Comment by madhurgupta10** [comment]
@sivaraam Hi, could you please provide me the link for "Learn More" to "Use Wikidata" would cause huge data consumption

**Comment by misaochan** [comment]
Actually, I think "use Wikidata" can be removed entirely. We have migrated completely to Wikidata and do not even use the CSV anymore.(see #981 ).

**Comment by misaochan** [comment]
I noticed that you are missing "become a beta tester" and "send log file" - are they present but just not in your screenshot?

**Comment by madhurgupta10** [comment]
@misaochan It is present, but not in the screenshot

**Comment by madhurgupta10** [comment]
@misaochan Is there any code apart from the one in **preference.xml** which is related to "use Wikidata", that should be removed?

**Comment by nicolas-raoul** [comment]
@madhurgupta10 I guess all CSV code has been removed, but f you find any such code please remove it, thanks :-)

**Comment by madhurgupta10** [comment]
@nicolas-raoul I made the necessary changes but one of the tests is failing, could you please help me debug!

**Comment by maskaravivek** [comment]
@madhurgupta10's PR fixes all the issues listed in @sivaraam's opening comment. Closing this issue. Thanks everyone for participating in the discussion and helping us improve our UI. :)
