### ISSUE TITLE
Hide Keypad on clicking outside the EditText

### ISSUE THREAD

**Issue by tanvidadu** [commons-app/apps-android-commons#1040]
The user experience will be improved if keypad is closed/hidden each time the user clicks outside the EditText , in the Common Activity.

**Comment by misaochan** [comment]
Agreed, thanks for the suggestion. :)

**Comment by tanvidadu** [comment]
I will like to work on the issue

**Comment by tshradheya** [comment]
Since there is no progress on this, I would like to take it up

**Comment by tanvidadu** [comment]
I am still working on it

**Comment by neslihanturan** [comment]
Since @tanvidadu emailed she still working on it, I am labeling this issue as assigned. Look forward to your PR @tanvidadu :)
