### ISSUE TITLE
Keypad overlaps on Wikimedia Commons policies Link

### ISSUE THREAD

**Issue by tanvidadu** [commons-app/apps-android-commons#1041]
The keypad in the Commons Activity overlaps with the Wikimedia Commons Links . 
![commons app](https://user-images.githubusercontent.com/29161745/34470950-8b223a1e-ef62-11e7-8e0d-fe1c59ab09d7.jpeg)

**Comment by tanvidadu** [comment]
I will like to work on the issue.

**Comment by neslihanturan** [comment]
@tanvidadu , thanks:)

**Comment by nicolas-raoul** [comment]
@tanvidadu Any progress? :-) How do you plan to fix it?

**Comment by mithlesh4257** [comment]
Can I start working on this issue #1041?

**Comment by mithlesh4257** [comment]
There is only one way fix this. 
Sir @nicolas-raoul I have to keep the button ("USE PREVIOUS TITLE/DESCRIPTION") below of the TextView containing Wikimedia Commons policies.

**Comment by nicolas-raoul** [comment]
Actually after re-reading this I am not sure what @tanvidadu is trying to achieve.
To me, it seems unavoidable that part of the screen is hidden when the keyboard is visible.
@tanvidadu could you please explain a bit more? Thanks!

**Comment by mithlesh4257** [comment]
Sir @nicolas-raoul , I have an idea , If I adjust  the views I can be able to make the user to see the links.
One of the possible way is to 
1. Bring the spinner to the top
2. Bring the TextView containing Attribution text to just below of spinner
3. Bring the Button to bottom.

This might be helpful. Is it ?

**Comment by tanvidadu** [comment]
Sorry for not being a little specific earlier. We can adjustResize the Xml components each time the keypad is opened so the Wikimedia Commons policies Links is visible.
Please refer these resources 
https://android-developers.googleblog.com/2009/04/updating-applications-for-on-screen.html
https://stackoverflow.com/questions/3295672/android-soft-keyboard-covers-edittext-field

**Comment by nicolas-raoul** [comment]
Not being able to see the field you are typing in would be a problem, but I don't see why the keyboard overlapping the policy link is a problem.
We can not show everything at all times, otherwise things will become painful for people with very small screens.

**Comment by sivaraam** [comment]
Closing per https://github.com/commons-app/apps-android-commons/issues/1041#issuecomment-356782907
