### ISSUE TITLE
No categories found in Commons beta servers?

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#1042]
When running the beta product flavor, I cannot seem to find any categories regardless of what my search term is. Is this an inherent limitation of the Commons beta servers (they don't have categories), or is it due to an issue with our implementation?

**Comment by whym** [comment]
Beta Commons has categories. There is [Category:Nature](https://commons.wikimedia.beta.wmflabs.org/wiki/Category:Nature) for example. Most of existing ones are for maintenance categories or categories for user pages, though. https://commons.wikimedia.beta.wmflabs.org/wiki/Special:AllPages?from=&to=&namespace=14

Did you try creating categories you want to test?
