### ISSUE TITLE
Introduce Room DB abstraction layer to our app

### ISSUE THREAD

**Issue by maskaravivek** [commons-app/apps-android-commons#1043]
For starters, heres an article explaining room 
https://medium.com/google-developers/7-steps-to-room-27a5fe5f99b2

I recently used Room in one of the projects and found the following advantages. 

- making testing upgrade/functionality of db easier
- cleaner code, removing boilerplate code
- prepare for using livedata/flowables with RxJava
- verifies queries at runtime

It would be great to have thoughts from others. @psh @misaochan

**Comment by psh** [comment]
The **TL;DR** - yes, I like Room but I think there are some fundamental things to address on the path toward using it.

Most of the advantages you cite can be derived from any modern ORM - I (and my team) evaluated 

* [sqlbrite](https://github.com/square/sqlbrite) / [sqldelight](https://github.com/square/sqldelight)
* [GreenDAO](http://greenrobot.org/greendao/)
* [OrmLite](http://ormlite.com/)
* [Room](https://developer.android.com/topic/libraries/architecture/room.html)

I really liked the generated code from **GreenDAO** - very efficient and by far the best performance - and the RxJava integration of **sqlbrite** got our attention too.  I ended up recommending **Room** to our client based on a sense of *longevity* it brings and its small size - it adds very little to the app (method count or physical size) and smoothly integrates with our app's legacy Sqlite database installed on user's devices (precluding [Object box](http://objectbox.io/) and [Realm](https://realm.io/products/realm-database) from our team's evaluation)

Back to the Commons App again - we have a couple of PR - #1023 ("Extracted and tested the database interactions from Category") and #1022 ("Extracted and tested the database interactions from ModifierSequence") - that start us on the road toward using a tool like Room.  Note: #1026 ("Extracted and tested the database interactions from Contribution") has already been merged.

Bugs like #894 ("Media details lost on device rotation") tell me that we need to address some core architecture.  The contributions activity and the nearby activity both have complex models attempting to be shared across multiple fragments and activities.  The `ContributionsActivity` relies on the somewhat *arcane* notification mechanism from Content Providers, Cursors and content URIs.  There's complexity to address and bugs to fix.

**Room** is a very pretty band-aid being applied to a broken leg - definitely great at what it does, but only part of the overall picture.

**Comment by chrisdebian** [comment]
It looks like this has been broken down in to two tasks, one open and one closed. Could we close this issue, as 3127 documents the work that still needs doing?

Chris.
