### ISSUE TITLE
Unable to login with valid Wikimedia account

### ISSUE THREAD

**Issue by easkerov** [commons-app/apps-android-commons#1052]
I've cloned the sources (commit 64ad93725842ae404e9db830158bf50d380dd7c3 in master branch) to my local machine, built and deployed the App, but unable to login with invalid password error. If I try to login to App installed from Google Play Store then authentication is successful with the same credentials. I've tried to debug, in getErrorCodeToReturn method (ApacheHttpClientMediaWikiApi class), the value of status variable is FAIL, and error code is "wrongpassword".

Any ideas what I am doing wrong?

**Comment by misaochan** [comment]
Could you check which product flavour you are building? You need to be running the prodDebug variant to be able to login with your Wikimedia account. If you run the betaDebug variant you will have to sign up for a beta account.

**Comment by easkerov** [comment]
@misaochan Thanks for response.

Could you please clarify how I can check this? Do I need use another branch or run/debug configuration? I've double checked developer documentation, but did not find anything related to this.

**Comment by misaochan** [comment]
Are you using Android Studio for development? If you are, you can check the "build variants" toolbar on the middle left side of the screen.

**Comment by easkerov** [comment]
@misaochan 
Thanks a lot, I've figured out and managed to build and install prodDebug and then log in successfully. I am going to contribute to project, experienced in Java, but beginner in Android Development.

**Comment by misaochan** [comment]
Wonderful! Very happy to hear that. :)
