### ISSUE TITLE
"Forgot password" link on login screen

### ISSUE THREAD

**Issue by mithlesh4257** [commons-app/apps-android-commons#1063]
![screenshot_20180114-163647](https://user-images.githubusercontent.com/22450186/34916232-d6043670-f95a-11e7-879c-ecd4cba17145.jpg)

There should be Password Reset Option here.

**Comment by nicolas-raoul** [comment]
@mithlesh4257  Could you please provide a screenshot of a popular app that has " Reset Option" in its login screen?
Cheers!

**Comment by mithlesh4257** [comment]
@nicolas-raoul Sorry Sir for labeling wrong It should be "Reset Password Option",

![reset](https://user-images.githubusercontent.com/22450186/34919775-8146f648-f98e-11e7-834d-22bf9f6561d3.jpeg)

**Comment by psh** [comment]
@nicolas-raoul Some other notable examples - 

| **LinkedIn** | **Slack** |
|---|---|
![device-2018-01-14-153300](https://user-images.githubusercontent.com/407647/34921026-f82ca462-f941-11e7-9167-5eaa6865a4bc.png) | ![device-2018-01-14-153604](https://user-images.githubusercontent.com/407647/34921037-3c65bdb2-f942-11e7-91dd-2247019757dc.png)
| **Pandora** | **Papa Johns Pizza** |
![device-2018-01-14-153740](https://user-images.githubusercontent.com/407647/34921038-3eb4ad9e-f942-11e7-988d-032d38f53c15.png) | ![device-2018-01-14-155150](https://user-images.githubusercontent.com/407647/34921079-ebfb6cc2-f942-11e7-855d-e8e74d3c3319.png)

The exact text varies between "forgot password" and "reset password" but the intent is the same.

I think it would be enough to launch an external browser if the user taps on a "forgot password" link.  We could move the "privacy policy" link out to another spot on the screen and drop "forgot password?" in its place.

**Comment by misaochan** [comment]
Looks good to me, thanks for the suggestion and mockup! :)

**Comment by Mustahai** [comment]
Hello, I am a CS student tasked with helping solve an issue on an open source project and this seems like the perfect issue me. I would therefore like to work on solving it.

**Comment by neslihanturan** [comment]
Hi @Mustahai , go for it:)

**Comment by madhurgupta10** [comment]
Hi, I would love to work on this issue.

**Comment by nicolas-raoul** [comment]
@maskaravivek What is the current status of this? Thanks! :-)
