### ISSUE TITLE
Switched to Wikimedia maps server instead of Mapbox ??

### ISSUE THREAD

**Issue by sivaraam** [commons-app/apps-android-commons#1064]
The release notes of v2.6.5 does say that the app has switched to using the Wikimedia maps server instead of the Mapbox. But, I still see the Mapbox watermark in the Nearby screen. So, hasn't Mapbox been removed completely?

![screenshot_2018-01-14-19-01-14](https://user-images.githubusercontent.com/12448084/34918333-dcac6f44-f976-11e7-9cdb-03f44668c1f0.png)

**Comment by misaochan** [comment]
As mentioned at #590 (initially written by dbrant):

> Our app uses Mapbox (the SDK) in the sense that we use it to render the map, the markers, the user's location, etc. on the screen. This is perfectly fine, since the SDK is open-source.
> 
> However, we do not use Mapbox (the corporation) for providing the tile data. Instead, we configure the SDK to fetch the tiles from our own tile server. This way, none of the users' data or requests are sent to Mapbox (the corporation)'s servers.

So what you are seeing is just the SDK. No user information is sent to the Mapbox map server.

**Comment by sivaraam** [comment]
@misaochan Nice. But I think others would be confused on seeing the Mapbox watermark just as I was confused. Is it possible to remove that watermark just in case users don't get confused just like I was? I guess it should be possible to remove the watermark (I don't see any watermark in Wikipedia app's Nearby but I guess they use the mapbox SDK too).

If the watermark shouldn't be removed, maybe this detail should be clarified somewhere (blog).

**Comment by nicolas-raoul** [comment]
I am also in favor of removing the watermark.
If we just use their software (as opposed to their tiles) then no need for a watermark. We can include any needed attribution into the About screen.
A few things are suggested at https://stackoverflow.com/questions/30320079/how-to-remove-mapbox-logo-from-bottom-left-corner

**Comment by misaochan** [comment]
@sivaraam and @nicolas-raoul Good point, sounds like a plan. :)

**Comment by neslihanturan** [comment]
I am coming from related SOF post. But there is not a clarity about license terms among answers. 

>If we just use their software (as opposed to their tiles)

Under these circumstances, don't we violate their license terms by removing their logo?

**Comment by nicolas-raoul** [comment]
> Under these circumstances, don't we violate their license terms by removing their logo?

I believe https://github.com/mapbox/mapbox-gl-native/blob/master/LICENSE.md is the license for the Mapbox software we are using. It only requires us to include a short text in our source code and About menu. Actually, if it required a watermark it would probably not be considered open source.

**Comment by sivaraam** [comment]
> If we just use their software (as opposed to their tiles) then no need for a watermark.

This makes me wonder, *Who's adding the watermark in the first place and how is it being done?* Is the app doing it specifically?
