### ISSUE TITLE
Nearby doesn't recognize when location changed with Fake GPS

### ISSUE THREAD

**Issue by neslihanturan** [commons-app/apps-android-commons#1066]
As mentioned #1065 by @nicolas-raoul : 

> Not sure if related, but recently I had the following problem:
> 1. I was using Nearby with my real location, with items showing normally
> 2. I launched Fake GPS and set my location to somewhere else
> 3. I opened Nearby again
> 4. Got the toast "Location has not changed"
> Even though it is obvious that my location had actually changed.

I also recognized this issue rarely, however, I suspect it is related with a latency of FakeGPG app. Does anyone else experience this isssue on real location changes too?

**Comment by chrisdebian** [comment]
Has anybody got any recent experience with this situation? Is is still problematic?

Chris.

**Comment by nicolas-raoul** [comment]
Nearby is still incredibly slow to update to a new location.

**Comment by nicolas-raoul** [comment]
The symptoms are very different so better create a new issue though.
