### ISSUE TITLE
TestCommonsApplication's compilation errors

### ISSUE THREAD

**Issue by whym** [commons-app/apps-android-commons#1068]
It looks like since #1062 TestCommonsApplication has been broken. For example, it tries to override injector() which was removed by the patch.

To quote some of the errors:

```
/home/travis/build/commons-app/apps-android-commons/app/src/test/java/fr/free/nrw/commons/TestCommonsApplication.java:66: error: method does not override or implement a method from a supertype
    @Override
    ^
/home/travis/build/commons-app/apps-android-commons/app/src/test/java/fr/free/nrw/commons/TestCommonsApplication.java:71: error: method does not override or implement a method from a supertype
                        @Override
```

**Comment by misaochan** [comment]
@whym , do you know if this should block the current release (to fix the Dagger crash)? I am leaning towards just doing the release first while we fix this, as the issue seems to lie with the tests.

**Comment by whym** [comment]
It appears only about tests not the main code, yes. I should also mention that I'm not really familiar with Dagger yet, though.
