### ISSUE TITLE
For ''multiple uploads'' you can't specify descriptions in the app, and specify after uploading

### ISSUE THREAD

**Issue by Triplec85** [commons-app/apps-android-commons#1074]
=== English ===
For ''multiple uploads'' you can't specify descriptions in the app, only categories. This (specify descriptions) is only possible with ''single uploads''. It would also be nice if you could edit descriptions of the images with the Commons app even after an upload. Greets -- [[User:Triplec85|Triplec85]]  10:15, 16 January 2017 (UTC)

=== German ===
Bei Mehrfach-Uploads kann man bei der App auch keine Beschreibungen angeben, nur Kategorien. Dies geht nur bei Einfach-Uploads. Schön wäre es auch, wenn man mit der Commons-App auch noch nach einem Upload Beschreibungen der Bilder editieren könnte. Gruß
-- [[User:Triplec85|Triplec85]]  10:15, 16. Januar 2017 (UTC)

**Comment by mithlesh4257** [comment]
Thanks @Triplec85 :-), I will be fixing it.

**Comment by neslihanturan** [comment]
@Triplec85 Thanks for the feedback:)
- Your first request (Enabling description input on multiple uploads) is related with #604 . We will be implemented it soon:)
- Second is a discussion here #161 . This will be implemented after first one, but still it is on our schedule.

@mithlesh4257 this tasks isn't beginner friendly and they need to be discussed more before they get implemented. They are not ready yet, I guess.

**Comment by nicolas-raoul** [comment]
@mithlesh4257 Your enthusiasm is wonderful, but could you please concentrate on one task at a time? That would allow you to deeply study and understand the technology and functionality related to a particular issue. Thanks! :-)

**Comment by nicolas-raoul** [comment]
Both implemented now. 🙂
