### ISSUE TITLE
Get listed in "Apps Using Fresco"

### ISSUE THREAD

**Issue by sivaraam** [commons-app/apps-android-commons#1084]
If I'm correct in assuming that the app uses the [facebook/fresco](https://github.com/facebook/fresco) library as I see it in the build.gradle file, how about letting them know about it?

See "Apps Using Fresco" section of http://frescolib.org/

NOTE: I find this to be an opportunity to increase the users of the app.

**Comment by psh** [comment]
Yes, the app uses Fresco - the contributions grid view uses `SimpleDraweeView`, as does the share, upload and media details.

**Comment by sivaraam** [comment]
It seems that to get the [PR](https://github.com/facebook/fresco/pull/2031) merged into [facebook/fresco](https://github.com/facebook/fresco) the person has to sign the Facebook CLA. I'm not so interested in reading/signing the CLA for this trivial change. So, is there anyone else who has already signed the CLA who could possibly do this instead of me?

**Comment by tshradheya** [comment]
I think this can be closed, since I my PR on `fresco` repo to add the WikiMedia app is [merged](https://github.com/facebook/fresco/pull/2032).

**Comment by nicolas-raoul** [comment]
Great thanks! :-)

**Comment by nicolas-raoul** [comment]
Don't hesitate to look for other libraries having the same kind of page :-)
