### ISSUE TITLE
Signup/Login wih Social Network Account

### ISSUE THREAD

**Issue by Sylvia23** [commons-app/apps-android-commons#1095]
Most of the apps have this very useful and commom feature to login/signup with social network acoount. Social network APIs or SDKs can be intergrated in the android app which makes it very easy to login/signup and share your actions. So, I think it should be there in this app as well.
For example,
![screenshot from 2018-01-23 11-43-57](https://user-images.githubusercontent.com/23060217/35260930-e88b9ea2-0033-11e8-8546-2ed4fc03044c.png)![signup_socialacc](https://user-images.githubusercontent.com/23060217/35260931-e8f2ab10-0033-11e8-8826-0e81882e1dfd.png)

**Comment by nicolas-raoul** [comment]
I think we can not provide more login options than what is available at https://commons.wikimedia.org/w/index.php?title=Special:UserLogin&returnto=Main+Page

While Mediawiki has extensions for this (such as https://www.mediawiki.org/wiki/Extension:Facebook) I am not sure whether they are enabled on Commons or not.

**Comment by whym** [comment]
On the server side the possibility of enabling social media login seems to be slim: https://phabricator.wikimedia.org/T61631 - it's more of a policy issue than a technical issue.

We could perhaps create a UI that helps users to create a Wikimedia Commons account using information pulled from their social media accounts, though. It would have to be carefully implemented to avoid creating duplicate accounts.

Somewhat related: https://phabricator.wikimedia.org/T30085 is an open issue about enabling email login.

**Comment by chrisdebian** [comment]
I think some single sign on options are now implemented, can anyone confirm?

Chris.

**Comment by whym** [comment]
As far as I know, no. Social media login is not available. (Accounts are unified within Wikimedia wikis, but that' s different from what's requested here.)

This is declined in upstream ([T61631](https://phabricator.wikimedia.org/T61631) mentioned above). We can close this as well accordingly, or we can keep it open, waiting for upstream to reconsider.
