### ISSUE TITLE
Add section in wiki for Dagger usage in our app

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#1096]
Just realized that we have a section for Butterknife usage in our [wiki](https://github.com/commons-app/apps-android-commons/wiki/Code-style), but not Dagger. IMO while Dagger is very useful, it can be difficult to get on board with. A section in our wiki might help newcomers (or even oldcomers who are unfamiliar with Dagger, like myself) to get started with using Dagger injections appropriately in our app. 

I don't think we need to write an entire guide, but perhaps we could link to a general guide (I liked https://github.com/codepath/android_guides/wiki/Dependency-Injection-with-Dagger-2 ), and then give a step-by-step example of adding Dagger injections to a newly-created class?

**Comment by psh** [comment]
We already have 

https://github.com/commons-app/apps-android-commons/blob/master/dependency-injection.md

I am happy to flesh things out more if other people have questions.

**Comment by misaochan** [comment]
Ah, I had no idea that was there! It would have been quite helpful. :)

Shall we move it into the wiki to consolidate things?

**Comment by psh** [comment]
I wrote that document before we did the recent refactoring so it might not be entirely accurate.  It should be checked before we add it to the wiki.  I linked to the Dagger user guide in the document but is there more we (ourselves) should say to help people?  Do you have questions that haven't been answered?

If you think that getting the document into the wiki would make it more accessible to people then by all means, let's put it up there.  I'd like new developers to have the best possible chance to understand what is going on!

**Comment by misaochan** [comment]
I think what could help would be to provide a step-by-step example from start to finish.

So for instance, if I want to create a new class, DaggerExample.java that will use a LocationServiceManager. What I should do would be to:

1. Check if one of the methods annotated with `@Provides` in CommonsApplicationModule.java already returns a LocationServiceManager. 
2. If it does, then I can use this method by calling `@Inject LocationServiceManager locationServiceManager` in DaggerExample.java
3. Check how DaggerExample.java should be added to the Dagger configuration. As it isn't a Fragment, Service, or Activity, it should be added in CommonsApplicationModule by _______?

Is this correct?

By the way, should we rename the 'di' package to 'dagger' or something that is more intuitive?

**Comment by psh** [comment]
I pulled together a first draft based on the existing file and your question here.

https://github.com/psh/apps-android-commons/wiki/Dependency-Injection

Thoughts?

**Comment by psh** [comment]
I feel like the codepath link you shared would be better than simply linking to the Dagger user guide. I'll find a way to get it in there. Thanks for the link @misaochan!

**Comment by misaochan** [comment]
Thanks for the new wiki draft! I'll take a look ASAP. :)

**Comment by misaochan** [comment]
@psh I went through the new wiki draft, as an accompanying guide for my work on the Nearby List direct uploads. While the new draft was a huge help, I still found myself with an unanswered question:

- What do you do when you need to inject dependencies into a class that is not a Fragment, Service, Activity, or ContentProvider? 

The "Dagger configuration in Commons app" section mentions how to add all of the above. For instance, for a Service you would make your class extend DaggerService, then add the `@ContributesAndroidInjector abstract UploadService bindUploadService();` configuration to ServiceBuilderModule.

However, lets say I want to inject SharedPreferences into PlaceRenderer.java (actually, this is exactly what I'm trying to do :) ). This class already extends Renderer<Place>, so I cannot modify it to descend from a class that provides Dagger functionality like DaggerService. And there is no module in the 'di' package that I can add this class to. 

How do I set up PlaceRenderer.java so that I can inject dependencies into it?

(Sorry for the newbie question, but I think other newbies might come across the same issue ;)).

**Comment by misaochan** [comment]
I think I may have found the answer to my question (implemented in #1121 ). Classes that are not Fragments etc apparently can have injection performed directly in them? So the steps I used to inject SharedPreferences into PlaceRenderer.java were:

- Check if one of the methods annotated with `@Provides` in CommonsApplicationModule.java already returns a SharedPreferences named ("direct_nearby_upload_prefs")
- If it does, then I can use this method by calling `@Inject @Named("direct_nearby_upload_prefs") SharedPreferences directPrefs;` in PlaceRenderer.java
- Before this dependency is used, I need to create an injector in PlaceRenderer.java by invoking
 `((CommonsApplication) getContext().getApplicationContext()).injector().inject(this);`
- And I also need to add `void inject(PlaceRenderer placeRenderer);` to the interface in CommonsApplicationComponent.java

Is this correct? I get that the instructions above are not standalone and are very dependent on how the Dagger configuration in our app is set up, but I think they could be helpful as an example at the bottom of the wiki, just to get newbies kickstarted.

If you could copy your wiki over to ours, @psh (probably best that you author it because you authored the original), I can add my example to the bottom if needed. :)

**Comment by psh** [comment]
I've made the edits to our wiki - https://github.com/commons-app/apps-android-commons/wiki/Dependency-Injection

**Comment by misaochan** [comment]
Thanks @psh !

**Comment by misaochan** [comment]
I've added the examples to the wiki, please feel free to modify if needed. I guess we can close this task as the basics have been completed. :)
