### ISSUE TITLE
Start category edit with capital letter

### ISSUE THREAD

**Issue by neslihanturan** [commons-app/apps-android-commons#1098]
Since almost all categories starts with capital, I generally have problem to find category even if I wrote exactly same word except using lower case at first. Sometimes xxxx did not match with Xxxxx, so I think making first letter of keyboard on category search input uppercase would increase user experience.

**Comment by tanvidadu** [comment]
I start working on this.

**Comment by neslihanturan** [comment]
Thanks @tanvidadu :)

**Comment by tanvidadu** [comment]
Are there any more changes required in this issue?
