### ISSUE TITLE
Add swipe-to-refresh

### ISSUE THREAD

**Issue by mithlesh4257** [commons-app/apps-android-commons#1103]
Here is screenshot.
There should be swipe-to-refresh the image uploaded. 
![swipe-down](https://user-images.githubusercontent.com/22450186/35388274-2257f358-01f9-11e8-8af4-24f19b69eb92.jpeg)

**Comment by knightcube** [comment]
Can you please tell me where can i make the changes for the swipe-to-refresh to work?It would be helpful if you could tell me the package name to work inside

**Comment by neslihanturan** [comment]
@mithlesh4257 I don't think this is necessary for our app. Since we already fetch whenever an image is uploaded, there is nothing to fetch on swipe down. So closing this for now, you can always reopen it. @knightcube you can look at beginner friendly tasks and pick one:)
