### ISSUE TITLE
Completely overhaul app's User Interface

### ISSUE THREAD

**Issue by sivaraam** [commons-app/apps-android-commons#1106]
This is a discussion thread similar to #1092. This was initially a comment in the same thread.

I have long been thinking of suggesting a similar issue for the UI. Though the recent overhaul had made some significant improvements, I still thinks it would be better to completely overhaul the UI as I could still see some dominance of legacy UI even after some overhaul.

As an motivator for why I think of a complete overhaul, consider the login screen. It was recently modified. The new design definitely seems better than the old one except for one thing the **dynamism**. The login page (username and password input fields) seems to shifting itself to remain in the center with respect to the available screen height. This movement doesn't seem to be a big deal if it only happens when the users keyboard pops in and pops out. In some cases the user's keyboard might suggest things as he types. These suggestions pop in and pop out above the keyboard itself as and when required. This results in the login page moving when the user types his username. This seems to be disturbing to the user as he notices something moving on his screen which generally doesn't happen in case of login screens.

I find this to be a consequence of trying to revamp over the legacy UI. This is why I suggest a complete UI overhaul. I guess that comes to a "rewrite the app completely" to some extent :)

**Screen shots**
![screenshot_20180123-214313](https://user-images.githubusercontent.com/12448084/35294165-e9c8a450-009b-11e8-9c7f-2f42fe915954.png)
![screenshot_20180123-214311](https://user-images.githubusercontent.com/12448084/35294223-ff10b14a-009b-11e8-8b42-8c3866df8214.png)

**Comment by neslihanturan** [comment]
Thanks @sivaraam for sharing this UI improvement idea. I think we can collect UI improvement ideas under this thread with references. To get back to rewriting hole UI, we have to start from some point:)

**Comment by nicolas-raoul** [comment]
@sivaraam Is this still relevant? 🙂

**Comment by sivaraam** [comment]
It indeed does seem stale. Let's close this.
