### ISSUE TITLE
Avoid "form movements" in the login screen

### ISSUE THREAD

**Issue by sivaraam** [commons-app/apps-android-commons#1107]
By "dynamism", I mean trying to keep the username and password fields always at the center of the available screen space. This distracts the user when he fills in the fields.

From #1106,
>The login page (username and password input fields) seems to shifting itself to remain in the center with respect to the available screen height. This movement doesn't seem to be a big deal if it only happens when the users keyboard pops in and pops out. In some cases the user's keyboard might suggest things as he types. These suggestions pop in and pop out above the keyboard itself as and when required. This results in the login page moving when the user types his username. This seems to be disturbing to the user as he notices something moving on his screen which generally doesn't happen in case of login screens.
>
>...
>
>**Screen shots**
>![screenshot_20180123-214313](https://user-images.githubusercontent.com/12448084/35294165-e9c8a450-009b-11e8-9c7f-2f42fe915954.png)
>![screenshot_20180123-214311](https://user-images.githubusercontent.com/12448084/35294223-ff10b14a-009b-11e8-8b42-8c3866df8214.png)

**Comment by noahwalugembe** [comment]
@sivaraam @neslihanturan I am an outreachy applicant who would like to work on this as my contribution

**Comment by nicolas-raoul** [comment]
@noahwalugembe It is yours! Please let us know know about your progress :-)

**Comment by noahwalugembe** [comment]
> @noahwalugembe It is yours! Please let us know know about your progress :-)

Thanks Mr @nicolas-raoul

**Comment by noahwalugembe** [comment]
> @noahwalugembe It is yours! Please let us know know about your progress :-)

Hi @nicolas-raoul i have Avoided "dynamism/movements" of username and password fields in the login screen. Pleas check my remo {https://github.com/noahwalugembe/apps-android-commons} to see my contribution

**Comment by nicolas-raoul** [comment]
Would you mind sending a pull request? :-)
https://help.github.com/en/articles/creating-a-pull-request
Thanks!

**Comment by sivaraam** [comment]
It looks like this is fixed now.
