### ISSUE TITLE
Hide Keypad when EditText out of focus

### ISSUE THREAD

**Issue by tanvidadu** [commons-app/apps-android-commons#1109]
In order to increase the user experience the keypad should be hidden each time the editText is out of focus.

Activity and fragment that include this feature: 
 1) fragment_single_upload

Activities or fragments that need this change: 
1)  activity_login
2) fragment_categorization
3) fragment_multiple_upload_lists

**Comment by liormic** [comment]
I start working on this :)

**Comment by gupta-meghna64** [comment]
Hi, Is @liormic still working on this issue? If not, Can I please start working on this? 
Thanks

**Comment by nicolas-raoul** [comment]
@gupta-meghna64 : No news from @liormic since a week, so yes you can take it! Be sure to report your progress every few days at least. Thanks! :-)

**Comment by liormic** [comment]
Sorry guys .Yes gupta been working on another thing...Better if you take it 
Tnx

**Comment by gupta-meghna64** [comment]
Cool! I'll start working on it :)

**Comment by maskaravivek** [comment]
Awesome @gupta-meghna64. Am marking this task as assigned.
