### ISSUE TITLE
Location template not added in MultipleShareActivity

### ISSUE THREAD

**Issue by Aschroet** [commons-app/apps-android-commons#1110]
Although my previous uploads contain GPS coordinates the location template was not added. Seems to be a regression. I uploaded as a bulk upload.

Example: https://commons.wikimedia.org/wiki/File:Eternal_Alphabet_Yerevan_-_12.jpg

**Comment by misaochan** [comment]
Thanks for reporting this! I tested and have also found that image coordinates are not saved when uploading via MultipleShareActivity (and probably not checked at all, as category suggestions based on geolocation are not offered). 

@Aschroet Does it work for you when uploading via the app, as a single file?

**Comment by Aschroet** [comment]
@misaochan, for single files it works as expected.

**Comment by mithlesh4257** [comment]
Now I am more prepared. I can handle this.

**Comment by misaochan** [comment]
@mithlesh4257 Sure, go for it. :)

**Comment by mithlesh4257** [comment]
Hi @maskaravivek  :), I have compared both files "ShareActivuty.java" and this files. I like learn more about LocationTemplate ? Can you help me?

**Comment by Aschroet** [comment]
Just for information: The problem still existed with my last upload.

**Comment by misaochan** [comment]
I don't think this fix was ever implemented, and AFAIK @mithlesh4257 is not currently active. @neslihanturan @maskaravivek do you guys know if the PR pertaining to this was ever merged? I don't see it linked here.

If it hasn't, I think we can open this up to other contributors.

**Comment by kamilya35231** [comment]
Hello, I would like to try to work on this issue if it's available. Can you assign me?

**Comment by neslihanturan** [comment]
I couldn't ind either, if problem persists I assign @kamilya35231

**Comment by misaochan** [comment]
All yours @kamilya35231 ! :)

**Comment by kamilya35231** [comment]
It seems to work with the images that have proper geotags. If it is possible to view the location from the info of the image in the gallery, app will recognize it.

**Comment by Aschroet** [comment]
Just made another upload including this file: https://commons.wikimedia.org/wiki/File:Kriegerdenkmal_M%C3%BChlberg_Drei_Gleichen_-_5.jpg with the same result, i. e. no location. Or is this related to the smartphone i am using which is a Samsung A3 2017.

**Comment by VojtechDostal** [comment]
Uploading from my Samsung J7 never adds location template either. I wonder if I can do something about the phone settings (?)

**Comment by VojtechDostal** [comment]
OK I just tried enabling "Location Tags" on my camera. That could work :-)

**Comment by kamilya35231** [comment]
@VojtechDostal just make sure that you can view the location info in the details of the image like here on the screenshot
![image_info](https://user-images.githubusercontent.com/35804101/39399877-c43ce45c-4b47-11e8-88ee-3393f41b1be1.jpeg)

**Comment by misaochan** [comment]
Location tags definitely need to be enabled on your phone's camera. :) Maybe we should add this note to an information icon somewhere.

**Comment by misaochan** [comment]
@kamilya35231 Sorry for not getting back to you earlier. Currently there is no way to invoke MultipleShareActivity directly from the app. However, we are starting work soon on #1091 which will change that (and likely fix the problem along with it). Have you made significant progress on this task? If not, it may be a better idea to pick another task. Apologies for the inconvenience!

**Comment by ashishkumar468** [comment]
Can someone, probably @misaochan  confirm if this is still happening?

**Comment by misaochan** [comment]
Nope, this seems to have been fixed in the overhaul.
