### ISSUE TITLE
Fix string resource values with '%s'

### ISSUE THREAD

**Issue by whym** [commons-app/apps-android-commons#1112]
It looks like the values with '%s' in https://github.com/commons-app/apps-android-commons/commit/28a6a3b71d73bdd14c93d27689d171e871420e69 caused compilation errors in https://github.com/commons-app/apps-android-commons/commit/72cddbf684ace2e5681a2404bbcfdba7eeaae95b . The problem is that apparently translatewiki.net cannot preserve the 'formatted="false"' attribute.

However, even if translatewiki.net supports it, should they be replaced with positional arguments anyway? I think sometimes translation may break the ordering of arguments. (I mean argument_index in https://developer.android.com/reference/java/util/Formatter.html by 'positional arguments'.)

**Comment by cfva14** [comment]
Working on it.

**Comment by whym** [comment]
I thought it was fixed but apparently it wasn't. https://travis-ci.org/commons-app/apps-android-commons/builds/336021170

It looks like the recent translation update brought new entries with the same problem.

**Comment by cfva14** [comment]
I think the problem was that I forgot to clean and rebuild before merging. Because I don't see any of these complaints in the XML files.

**Comment by whym** [comment]
In fact there were new entries made after you sent your PR: https://github.com/commons-app/apps-android-commons/commit/f8527e6b4f9bc99983a3da3aae20f81414985939#diff-ab4db9feb3f7075f514c574b1c7410a4R211

**Comment by maskaravivek** [comment]
Is someone working on this issue? This task fails while trying to build.

```
./gradlew :app:processBetaDebugResources
```

**Comment by maskaravivek** [comment]
Am not sure if anyone is fixing it currently. Am taking this up.
