### ISSUE TITLE
Tech-improvement: Remove hard-coded column indexes from queries

### ISSUE THREAD

**Issue by psh** [commons-app/apps-android-commons#1119]
Currently the code makes assumptions about the order of columns that are returned from database queries.  For instance,
```java
Category fromCursor(Cursor cursor) {
    // Hardcoding column positions!
    return new Category(
            CategoryContentProvider.uriForId(cursor.getInt(0)),
            cursor.getString(1),
            new Date(cursor.getLong(2)),
            cursor.getInt(3)
    );
}
```
Android's `Cursor` class provides a method to look up a column index based on a name so instead of `cursor.getString(1)` I can use a much safer
```java
cursor.getString(cursor.getColumnIndex(Table.COLUMN_NAME))
```
The code will end up a little more verbose but long term it will be robust against column order changes.

This issue isn't limited to just categories, its present in other locations where we extract data from cursors - contributions, modifier sequence, etc.

**Comment by hismaeel** [comment]
Hello. I can start working on this. I am new to the community and OSS in general; I would love to get going. 
Best :)

**Comment by nicolas-raoul** [comment]
@hismaeel It's yours, looking forward to your pull request :-)

**Comment by hismaeel** [comment]
Great. Just made a pull request :-)  @nicolas-raoul

**Comment by domdomegg** [comment]
Done in #1176
