### ISSUE TITLE
Request for CONTRIBUTING.md file

### ISSUE THREAD

**Issue by hismaeel** [commons-app/apps-android-commons#1125]
Hi fellow enthusiasts. I, just like many others, usually look for a CONTRIBUTING.md file. While currently there are instructions in the readme file, and in the wiki, I think there should be more details, and instructions should be coalesced into one conventional file. Also, since this is an android app, contributions can have two routes, and both should be detailed:

- directly use terminal/(GitBash or power-shell for windows users) to commit and push the repo
- use Android Studio to commit and push

I can make a draft of the CONTRIBUTING.md file and pull for the owners to review. 
Best :-)

**Comment by misaochan** [comment]
Thanks for the suggestion, @hismaeel ! Is this really the standard for most open source repos? I'm okay with adding a new file, but I'm concerned about duplication and maintenance (for instance, if we change any of our workflows or policies, we would need to edit BOTH the wiki and the .md file).

Thoughts, anyone?

**Comment by hismaeel** [comment]
Hmm. We could just add more details to the wiki page, and create a CONTRIBUTING.md file that just says: "Please see our guidelines in the wiki: https://github.com/commons-app/apps-android-commons/wiki/Volunteers-welcome%21".
Mozilla does this for a few of their repos.

**Comment by misaochan** [comment]
Sounds good to me! The task is yours if you want it. ;)

**Comment by hismaeel** [comment]
Yup, on it

**Comment by hismaeel** [comment]
Done. Cleared some details in Setting up dev environment page. And added more details to the wiki.

Best!

**Comment by nicolas-raoul** [comment]
Thanks!
