### ISSUE TITLE
Open map of place where picture was taken

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#1126]
I often want to check on Google Maps what is the exact name of a building, or find out what is that thing in the background, or determine whether I was technically in North-Kilda or South-Kilda.
This could be another button in the description screen, but actually I often need it in the categories screen, when two proximity categories appear and I need to choose the right one.
It should open the default map app.

**Comment by misaochan** [comment]
Sounds good to me! Where do you think the button could be in the categories screen?

**Comment by nicolas-raoul** [comment]
Hard question!
To help us think, here are the description and categories screens:
![school-description](https://user-images.githubusercontent.com/99590/35963915-96244fba-0cf9-11e8-8897-f4e99ffcc85e.png)
![school-categories](https://user-images.githubusercontent.com/99590/35963882-85ff7042-0cf9-11e8-8404-02435974fb18.png)

A map icon in the title bar would be relatively easy to implement and consistent (same position in the two screens) but it would make it even less obvious than now what is the next step (I am sure some people already don't realize you have to press the floppy icon).

**Comment by misaochan** [comment]
Yeah, I would be very much against having it in the action bar.

Perhaps on the left side of the text field? But it wouldn't be very intuitive for users I think, they might wonder what a map icon is doing there and what it has to do with categories...

**Comment by nicolas-raoul** [comment]
Putting it only at least on the description screen (where it is the most useful) could be a good first start, until we get a good idea for the categories screen.

**Comment by tanvidadu** [comment]
Sound like a good idea. I will like to work on this feature.

**Comment by nicolas-raoul** [comment]
@tanvidadu It's yours! Please submit a mockup early so that we can give feedback before you are too far into development already, thanks! :-)

**Comment by tanvidadu** [comment]
<img width="192" alt="map_in_description_layout" src="https://user-images.githubusercontent.com/29161745/37563745-c00b5cfc-2aad-11e8-8e42-5ababbf60451.png">

This is the mockup of layout with icon to open map.
I was thinking of using the coordinates already present in the imageObj in the shareActivity to get the latitude and longitude and then open the map at that specific location. 
@nicolas-raoul @misaochan  what are your opinion?

**Comment by neslihanturan** [comment]
I am not sure about showing icon next to description @tanvidadu

**Comment by tanvidadu** [comment]
I can change its location to toolbar next to arrow icon which will be visible only when user starts typing in Description/Title EditText ? 
This way it would be intuitive for user to know that map icon has something to do with description/title.

**Comment by nicolas-raoul** [comment]
Personally I would put a "Show location on map" button at the bottom, after
the license.
Everything above is user input.

Better not add an icon near the arrow icon, it would make it even less
visible.

**Comment by tanvidadu** [comment]
@nicolas-raoul this is screenshot of fragment_single_upload with the button 
![location on map](https://user-images.githubusercontent.com/29161745/37810866-b07c0e08-2e7c-11e8-99c7-6774958cef0a.jpeg)

with zoom being added in #1300 I was thinking of adding map as one of  floating button inside nested FAB like https://github.com/futuresimple/android-floating-action-button/issues/22.

@nicolas-raoul @misaochan @neslihanturan please let me know your opinion.

**Comment by nicolas-raoul** [comment]
To me it looks like the best available solution, thanks! :-)
