### ISSUE TITLE
Can we update minSdkVersion?

### ISSUE THREAD

**Issue by psh** [commons-app/apps-android-commons#1131]
Google's [version dashboard](https://developer.android.com/about/dashboards/index.html) is reporting very small numbers for certain versions of Android.  Particularly,

| API Level | Distribution |
| ---- | ----- |
| API 15 (Ice Cream Sandwich) | **0.4 %** |
| API 16 (Jelly Bean) | **1.7%** |
| API 17 (Jelly Bean) | **2.6%** |
| API 18 (Jelly Bean) | **0.7%** |

Does the Google Play Store give insight to our actual users and the versions in use?

In the absence of hard numbers from actual users, could we move up to API 19 (KitKat) or at the very least, API 16?

**Comment by nicolas-raoul** [comment]
What would be the merits of moving to API 16?
And the further merits of moving to API 19?
Below are our actual numbers, not counting F-Droid and direct APK downloads.
Cheers! :-)
![screenshot from 2018-02-13 00-09-50](https://user-images.githubusercontent.com/99590/36103307-5abdbba8-1052-11e8-963c-7099db97a859.png)

**Comment by dbrant** [comment]
A year ago (per above screenshot) the total number of installs on API <19 was just **92**. Today, that number is **35**, while the total installs have increased by 50%.

These devices are going away, and no longer need to be supported. Please consider prioritizing this issue, so that we can remove a number of fragile API-dependent conditional statements, as well as ease the unnecessary QA burden.

**Comment by misaochan** [comment]
After the discussion at #888 , I think I would be on board with increasing the minSDK to 19. If users with phones lower than 19 are still able to access the last available version of the app via the Play Store even after we increase the minSDK, IMO that should be OK - it would be a reasonable compromise between reducing tech debt and maintaining inclusiveness.

@nicolas-raoul @maskaravivek @ashishkumar468 ?

**Comment by maskaravivek** [comment]
Yes, I am also in favor of increasing the `minSDK` version.

**Comment by nicolas-raoul** [comment]
If you think it makes development easier, do as you wish.

**Comment by ilgazer** [comment]
Can this issue be closed?
