### ISSUE TITLE
Wishing to contribute an application as Wiktionary with interative UI and Hybrid Application.

### ISSUE THREAD

**Issue by NirmalKumarJoshi** [commons-app/apps-android-commons#1132]
It can be done by developing an application with more features such as offline dictionary as it will be an offline web application as well as progressive Web Application.

**Comment by nicolas-raoul** [comment]
Cool!
Please create a new Github project for that new app by clicking here: https://github.com/new
Cheers! :-)

**Comment by NirmalKumarJoshi** [comment]
Okay sure I will share the repo with you so that you can keep an eye on it. I truly want to develop this application and contribute to the organizaton.
