### ISSUE TITLE
Adding Login/Signup using Social Media and also annonymous login in Wiki Commons app

### ISSUE THREAD

**Issue by NirmalKumarJoshi** [commons-app/apps-android-commons#1133]
We can use the email of user as the username as will be a better user experience because it is difficult for the user to remember his/her username for different applications.

**Comment by nicolas-raoul** [comment]
Does the desktop Commons website allow all of this?

**Comment by NirmalKumarJoshi** [comment]
We can add this Oauth feature in the website as well.

**Comment by pradhulstha** [comment]
Hello, the best solution would be to allow them to signup using their emails and keep them signed in.
And, can I to contribute to the project?

**Comment by misaochan** [comment]
This is similar to #1095 - I believe the answer to both is "unlikely, due to WMF policies".

**Comment by VojtechDostal** [comment]
Yep, unlikely.

**Comment by misaochan** [comment]
Closing this, then. I suppose we can leave #1095 up for now.
