### ISSUE TITLE
Korean translation in values causes Android Studio to fail building

### ISSUE THREAD

**Issue by Moseco** [commons-app/apps-android-commons#1135]
I was looking into contributing to this project and when I cloned and built the project I ran into a problem.
Gradle tells me that values-ko-kp is an invalid directory. Travis also seems to output the same error. 
Looking into the language and resource section of the Android [documentation](https://developer.android.com/guide/topics/resources/providing-resources.html#AlternativeResources) the Korean letter code "ko" is the accepted one. 

Is there something I am missing to get this to build correctly or should that folder not be there when it was added in [this commit](https://github.com/commons-app/apps-android-commons/commit/fc61836bc12516ecdfcf1a4cbdeef8d1d2d6dfd4).

**Comment by Moseco** [comment]
Looking further into it, it seems that adding the additional language code "kp" requires it to have a proceeding "r". Changing the directory from "values-ko-kp" to "values-ko-rkp" makes the build work and follows the documentation on additional language codes.

Ive made a pull request [here](https://github.com/commons-app/apps-android-commons/pull/1136)

**Comment by misaochan** [comment]
Thanks for reporting this! We will probably need to get @Nikerabbit to review your PR before we patch it. AFAIK if the appropriate changes are not made on translatewiki's side, future commits will continue to introduce the error.

**Comment by Nikerabbit** [comment]
Shouldn't it be ko-rKP to match zh-rTW?

Also, why is there zh-rCN? No such language is configured from our side. zh-hans maps to zh

**Comment by Moseco** [comment]
For consistency rKP would probably be better. rkp does work though.

**Comment by Nikerabbit** [comment]
I've set codemap to use ko-rKP.

**Comment by ujjwalagrawal17** [comment]
I think it should be closed now.
