### ISSUE TITLE
[Project Started] Developing a new version of Wiktionary for Android/ IOS with better UX and interactive UI

### ISSUE THREAD

**Issue by NirmalKumarJoshi** [commons-app/apps-android-commons#1137]
As the Wiktionary App on Play Store states that "This app is no longer supported" so I have started developing a hybrid application as of Wiktionary which will run completely natively. It will be a mobile application for Android and IOS. I will take the application to a new level with interactive UI and a better UX.

Please let me know how to share it with the organization and get reviews for the same and also please kindly let me know should I continue developing it? Will it be recognized?

**Comment by ujjwalagrawal17** [comment]
Why not make the app native. Hybrid apps lack performance and UI.

**Comment by nicolas-raoul** [comment]
@NirmalKumarJoshi The present Github project is only about the Commons app, so it is not the place to ask general questions about other apps. In particular, the recognition is not done by us, but by WMF (by the way, WMF will probably not recognize the app until you have at least a few thousand users).
Good luck!
