### ISSUE TITLE
Change LoginActivity Textview to Snackbar

### ISSUE THREAD

**Issue by ujjwalagrawal17** [commons-app/apps-android-commons#1138]
**Summary**
In Login Activity when the user clicks on Login Button.Instead of showing error or success message in a textview we should show a snackbar as the error message (textview) does not disappear. Snackbar will look good.

**Whould you like to work on Issue**
Yes

**Comment by ujjwalagrawal17** [comment]
I start working on this.

**Comment by misaochan** [comment]
Could you please elaborate on why you feel the error/success message should be shown in a snackbar instead of our current textview? As far as I have seen, snackbars are not usually used for this purpose in most other Android apps.

**Comment by ujjwalagrawal17** [comment]
Check out this: https://ux.stackexchange.com/questions/108995/material-design-how-to-display-a-log-in-error
It is just a suggestion. If you will approve it I will work on it.

**Comment by ujjwalagrawal17** [comment]
Should I start working on it?

**Comment by misaochan** [comment]
Sorry, I'm not entirely convinced about this. AFAIK our current login screen conforms to material design guidelines, and there wasn't any other reason mentioned on the StackExchange thread regarding the benefits of switching to a snackbar. @nicolas-raoul @psh thoughts?

**Comment by nicolas-raoul** [comment]
I don't think this SE thread has received enough attention to be considered
a reference.
The only answer gives 3 different solutions and no references.
