### ISSUE TITLE
Option to Change Recent Uploads Design

### ISSUE THREAD

**Issue by ujjwalagrawal17** [commons-app/apps-android-commons#1140]
**Summary**
When too many images are uploaded by the user it becomes difficult for the user to scroll till the end. We should give an Option to Change Linear Layout manager to Grid Layout Manager(2 items in a row). It will be a button on Toolbar from which user can change the view type.

**Comment by mithlesh4257** [comment]
Yes @ujjwalagrawal17, we can created 2 column grid for it.

**Comment by misaochan** [comment]
Hi, thanks for the suggestion. However, this is currently already planned for the near future and the task has already been allocated to @neslihanturan (see #725 ). There are other UI improvements that are open though, please see https://github.com/commons-app/apps-android-commons/labels/UX%20-%20user%20experience
