### ISSUE TITLE
Change webviews to Chrome Custom Tabs in App

### ISSUE THREAD

**Issue by ujjwalagrawal17** [commons-app/apps-android-commons#1143]
**Description**
We should use chrome custom tabs instead of webview because of good UI and many more things.
You can check here more advantages - https://developer.chrome.com/multidevice/android/customtabs

**Comment by ujjwalagrawal17** [comment]
Also, we can make this a parent issue and have more child issues for each activity or fragment to keep things simple and give an opportunity to new Developers.

**Comment by maskaravivek** [comment]
I agree with the usage of custom tabs across the application. @ujjwalagrawal17 It would be great if you could jot down some points in favour of its usage so that we get more support for it. :)

**Comment by nicolas-raoul** [comment]
How does it work with people who don't have Chrome installed?
For instance LineageOS or maybe Amazon devices.
Does it work on all Android versions that we support?
Thanks! :-)

**Comment by ujjwalagrawal17** [comment]
If you do not have Chrome installed, the intent will launch the default browser installed on the device.
Source- https://guides.codepath.com/android/Chrome-Custom-Tabs.
Also, some advantages we can use are -
1. Setting Toolbar color
2. Enable pre-starting and pre-fetching(this will reduce loading time)

**Comment by misaochan** [comment]
Sounds good to me. :)

**Comment by ujjwalagrawal17** [comment]
Should I start working on this ?

**Comment by maskaravivek** [comment]
Yeah feel free to start working on it. :)
