### ISSUE TITLE
Change MediaDetailFragment Design

### ISSUE THREAD

**Issue by ujjwalagrawal17** [commons-app/apps-android-commons#1147]
**Description**
We need an image viewer in our app to view (zoom) the image(contribution).
We will open it on click of image in contribution Details Page

**Comment by ujjwalagrawal17** [comment]
@nicolas-raoul  Can we have this feature in our app?

**Comment by nicolas-raoul** [comment]
The app is more for uploading than for viewing, but why not! :-)
It should probably reuse the code that is being written for https://github.com/commons-app/apps-android-commons/issues/1044#issuecomment-365541079

**Comment by ujjwalagrawal17** [comment]
Can we have the UI like this?
Just the details will contain our details like title,desription,cordinates etc.
<table>
<tr>
<td>

![screenshot_20180224-164529](https://user-images.githubusercontent.com/19607555/36629905-0a1d2d8e-1983-11e8-9f0e-c965ac60e635.png)

</td>
<td>

![screenshot_20180224-164534](https://user-images.githubusercontent.com/19607555/36629904-09b5be56-1983-11e8-87ff-c2ee19e8c689.png)

</td>
</tr>
</table>

**Comment by ujjwalagrawal17** [comment]
@maskaravivek Sir what are your suggestions?

**Comment by ujjwalagrawal17** [comment]
@nicolas-raoul @misaochan What are your suggestions on this?

**Comment by nicolas-raoul** [comment]
The details view already exists:
![screenshot_20180227-154832](https://user-images.githubusercontent.com/99590/36714554-06508002-1bd6-11e8-9856-12ee9d771f9c.png)
When the user clicks on the picture in the screen above, it should open full-screen.

**Comment by ujjwalagrawal17** [comment]
Closing it since this feature is already added.
