### ISSUE TITLE
Build error in getBuildVersion function in gitutils.gradle file.

### ISSUE THREAD

**Issue by csk1827** [commons-app/apps-android-commons#1157]
A try-catch block is missing int getBuildVersion function in the file gitutils.gradle : https://github.com/commons-app/apps-android-commons/blob/master/gitutils.gradle, due to which following error is occurring `Gradle sync failed: CreateProcess error=2, The system cannot find the file specified`

A try-catch block is used in the function getBranchName which is declared exactly below the getBuildVersion function, but I think it's not declared here by mistake.

**Comment by maskaravivek** [comment]
This error never happens with me. What version of the studio are you using?

**Comment by SaiKrishna1827** [comment]
I am using Studio 3.0.1 

This error occurred only when I first pulled the project from Github and tried to build the gradle in my system. For the first time, gradle built successfully only after I have added try-catch block there.

Now it's not showing any error even if I remove try-catch block. However, its a good practice to introduce try-catch block there.

**Comment by maskaravivek** [comment]
I am not sure if it actually a good practice to have a try catch here. A `try catch` will let any errors happen silently and then any real issues would not be surfaced. 

Open for discussion.

**Comment by neslihanturan** [comment]
@maskaravivek what is your opinion for this discuttion?

**Comment by maskaravivek** [comment]
As I said, 

> A `try catch` will let any errors happen silently and then any real issues would not be surfaced.

We should rather debug issues which come because of these util methods. :)

**Comment by neslihanturan** [comment]
Closing it then
