### ISSUE TITLE
Bug: Reinstall of app and using an existing account causes a different imageurl to be saved

### ISSUE THREAD

**Issue by Moseco** [commons-app/apps-android-commons#1169]
**Summary:** 

When making a contribution the imageUrl variable of Media.java is set correctly so that it can be entered in a browser and the image appears. If the app is then uninstalled or the data is cleared and you log into the same account the imageUrl of the same Media is set to a different link that leads to a 404. 

**Steps to reproduce:** 

1) Make a contribution and get the string stored in imageUrl.
2) Reinstall app.
3) Log into same account as before.
4) Load the same contribution as before and get the imageUrl
5) The urls are different, and the new one is a 404

**Expected behavior:** 

The urls should be the same

**Observed behavior:** 

The current code does not cause this to lead to a bad result. But further changes could depend on the imageUrl to be constant. I discovered this while trying to implement Glide for image loading

**Device and Android version:** 

Pixel 2 XL emulator running Oreo
 
 **Commons app version:** 

2.6.7

**Comment by Moseco** [comment]
@knight-shade Are you meaning the url is correct because it loads the image or are you checking something like the following:

System.out.println(contribution.getImageUrl);

Because under the current implementation the image still can be loaded because the code fetches the correct url based on the filename. So even if the imageurl gets set incorrectly between a data clear or uninstall the app works in its current form.

**Comment by knight-shade** [comment]
@Moseco Yes, I checked with Timber.d(). I have logged both the urls, the one which is used when download image option is selected and other one, "View in Browser" is selected.

![whatsapp image 2018-02-27 at 9 10 02 pm 2](https://user-images.githubusercontent.com/20313518/36738168-e633da6c-1c02-11e8-9325-493d1599a46a.jpeg)

Both the urls are different, just for example in case of image I uploaded:

View in Browser url : 
https://commons.m.wikimedia.beta.wmflabs.org/wiki/File:Madhugiri_fort.jpg

Download url: 
https://upload.beta.wmflabs.org/wikipedia/commons/6/64/File%3AMadhugiri_fort.jpg

The Download url is the one which leads to 404 error you have mentioned.

Correct me If I am wrong.

**Comment by gupta-meghna64** [comment]
@Moseco @knight-shade Both the download URL being generated is different only in the case when the image name contains a space.
Ideally, it should be of the form: https://upload.beta.wmflabs.org/wikipedia/commons/x/xy/filename.jpg where if filename consists of spaces, then spaces should be replaced by a blank string.
If the upload url gets fixed for this particular case, then #1216 gets solved too for all the future uploads.

**Comment by Moseco** [comment]
@gupta-meghna64 That explains why @knight-shade and myself are getting different results. Thanks for letting us know about the other issue!

**Comment by maskaravivek** [comment]
This got fixed after our backend overhaul.
