### ISSUE TITLE
Images fail to upload

### ISSUE THREAD

**Issue by dehrenha** [commons-app/apps-android-commons#1170]
_Before creating an issue, please search the existing issues to see if a similar one has already been created. You can search issues by specific labels (e.g. `label:nearby `) or just by typing keywords into the search filter._

**Summary:** 

Two of nine images failed to upload despite changing network and restarting app.

**Steps to reproduce:** 

How can we reproduce the issue?

Issue occurred after uploading 7 other images in the course of about 45 minutes. 

**Add System logs:**

Add logcat files here (if possible).

**Expected behavior:** 

What did you expect the App to do?
Upload images as usual.

**Observed behavior:** 

What did you see instead?  Describe your issue in detail here.
Two images simply failed to upload despite numerous attempts, using both mobile and wi-fi connections, and restarting the app.

**Device and Android version:** 

What make and model device (e.g., Samsung J7) did you encounter this on?  What Android
version (e.g., Android 4.0 Ice Cream Sandwich or Android 6.0 Marshmallow) are you running?  Is it
 the stock version from the manufacturer or a custom ROM ?
The device is a Motorola Droid Turbo 2. It is running the stock Android 7.0
 
 **Commons app version:** 

You can find this information by going to the navigation drawer in the app and tapping 'About'
This is version 2.6.7 of the Commons app.

**Screen-shots:** 

![screenshot_20180219-214049](https://user-images.githubusercontent.com/35645365/36406608-bc6a984c-15bd-11e8-998c-3944a52fd23f.png)

Can be created by pressing the Volume Down and Power Button at the same time on Android 4.0 and higher.

**Comment by misaochan** [comment]
Hi @dehrenha , thanks so much for reporting this! A few questions:

- Did you ever experience this before version 2.6.7? Or alternatively, did you experience multiple crashes with 2.6.6 instead?
- If you get another failed upload in the future, could you please go to Settings > Send log file, and have the logs sent to us? This will help us hugely in debugging your problem.

Thanks!

**Comment by hismaeel** [comment]
@dehrenha  True, I uploaded 7 very random photos and it says "4 uploads" at the top; I think maybe the "My recent Uploads" count at the top only count the ones that were approved. 

#175 

Best!

**Comment by dehrenha** [comment]
Josephine,
     I just started testing this app so I have had no experience at all
with the previous versions. I will send the log today. Thanks for the heads
up.

Don

**Comment by misaochan** [comment]
@dehrenha Hmm, interesting. I took a look at your log file and it seems that there is very little in the file. :/ Did you send it immediately after a failed upload, or at a different time?

@hismaeel Yeah, AFAIK we only count the images that have not been deleted. But what happened to the other photos for you - were they deleted on Commons or did the app fail to upload them (in which case it would say "Failed" as in @dehrenha 's screenshot)? (Also, if you are testing on betaDebug, there is a bug with the number of uploads displayed, but we haven't been to fussed with that since users will never receive that build variant)

**Comment by hismaeel** [comment]
@misaochan It happened only in the beta version! It's all well in the release version.

**Comment by dehrenha** [comment]
@JosephineLim I sent it a few hours after the failed upload.

**Comment by misaochan** [comment]
Hi @dehrenha ,

The way the "Send log file" feature works is that it pulls the existing logs from your phone at the time you send it. Unfortunately Android logs scroll VERY fast (and AFAIK are also cleared when you restart your phone), so generally it is best to submit **immediately** after the bug happened. Apologies that I didn't clarify that in my request. :)

**Comment by ashishkumar468** [comment]
As we have no logs and considering uploads have been refactored to handle such errors, closing this issue
