### ISSUE TITLE
App displays images which have been deleted

### ISSUE THREAD

**Issue by domdomegg** [commons-app/apps-android-commons#118]
App displays entries for images that have been deleted, not sure what exactly we want to do about this.

I'd suggest just not showing them at all, however some may disagree saying it might be useful to see some info e.g. a much smaller bar with the file name followed by "(deleted)" or something.

404 responses are received when trying to get the images / their thumbnails (best to check image though, as thumbnail may just be wrong like #119)

**Comment by domdomegg** [comment]
Screenshot of current behaviour:
![screenshot_20160607-215458](https://cloud.githubusercontent.com/assets/4953590/15874337/92d98720-2cfa-11e6-888f-6d50a64693e6.png)

**Comment by nicolas-raoul** [comment]
I am fine either way.
Indeed, people who keep uploading selfies (there are not many such people, but there are sometimes) might benefit from learning that their image has been deleted.

**Comment by misaochan** [comment]
I'm not sure if this has been done? And if not, do we want deleted contributions shown?

What about if we have an overlay that says "Deleted"?

**Comment by maskaravivek** [comment]
I think the app is trying to skip deleted images. `ContributionsSyncAdapter:onPerformSync`

```
for (LogEventResult.LogEvent image : logEvents) {
                if (image.isDeleted()) {
                    // means that this upload was deleted.
                    continue;
                }
            ...
```
