### ISSUE TITLE
Orientation change in NearbyActivity causes it to reinitialise NearbyListFragment.

### ISSUE THREAD

**Issue by knight-shade** [commons-app/apps-android-commons#1180]
**Summary:** 

When there occurs a orientation change in NearybyActivty, it reinitialise the NearbyListFragment and reloads the data again. 

**Steps to reproduce:** 

1. Go Nearby Places activity from navigation drawer.
2. Load the list of nearby places as shown below:

![nearby places list](https://user-images.githubusercontent.com/20313518/36594302-977c0206-18c3-11e8-9aee-0b1a42df6a55.png)

3. Change the orientation of phone.

**Expected behavior:** 

Change in orientation should check whether there already exists a instance of NearbyListFragment,
if not, then only a new instance of NearbyListFragment should be created.

**Observed behavior:** 

During orientation change in NearybyActivty, it reinitialise the NearbyListFragment.

**I am working on the issue.**

**Update**
Issue has been fixed.

**Comment by neslihanturan** [comment]
This seems solved
