### ISSUE TITLE
Add ItemDivider in NotificationActivity 

### ISSUE THREAD

**Issue by ayushin78** [commons-app/apps-android-commons#1186]
**Summary:** 

Currently, There is no ItemDivider used in the NotificationActivity. Since we are displaying description as well as the title in the listItem, Adding an ItemDivider will make it look cleaner and will help users to understand how the content is organized.

 **Screen-shots:** 

Current Display
![1](https://user-images.githubusercontent.com/18305466/36629674-21806aee-197f-11e8-950f-e00d808da4c6.png)

Suggested Display
![2](https://user-images.githubusercontent.com/18305466/36629679-40df65ca-197f-11e8-9908-7baba8ff452f.png)

**Comment by knight-shade** [comment]
Looks good @ayushin78 .
