### ISSUE TITLE
Change toolbar color to primary color

### ISSUE THREAD

**Issue by ujjwalagrawal17** [commons-app/apps-android-commons#1189]
**Summary:** 

According to guidelines by Google 
Toolbar background color should be the primary color.
Statusbar background color should be primary Dark color.

**Steps to reproduce:** 

Change toolbar background to primary color in toolbar.xml

**Expected behavior:** 

Toolbar background color should be the primary color.

**Observed behavior:** 

Toolbar background color is primary dark color.

**Screen-shots:** 
<table>
<tr>
<td>

![screenshot_20180224-180318](https://user-images.githubusercontent.com/19607555/36630519-7a6143c8-198d-11e8-939f-02def108be12.png)

</td>
<td>

![screenshot_20180224-180552](https://user-images.githubusercontent.com/19607555/36630522-872a86a0-198d-11e8-8b6d-9d4efde2d09a.png)

</td>
</tr>
</table>
Image 1->Before

Image 2->After

**Comment by maskaravivek** [comment]
Sounds good! @ujjwalagrawal17 can you include a link to Google's guideline for reference. :)

**Comment by SaiKrishna1827** [comment]
It's the correct way to use colorPrimaryDark on status bar and colorPrimary on toolbar as suggested by @ujjwalagrawal17
 
@maskaravivek  you can find it in Google's Android studio developer manual [here](https://developer.android.com/guide/topics/ui/look-and-feel/themes.html#CustomizeTheme)  

> <resources>
    
    <color name="colorPrimary">#3F51B5</color>

    
    <color name="colorPrimaryDark">#303F9F</color>

    
    <color name="colorAccent">#FF4081</color>
</resources>

**Comment by psh** [comment]
Dropping our primary / dark blue colors into Google's material design [Color Tool](https://material.io/color/#!/?view.left=0&view.right=1&primary.color=0c609c&secondary.color=0c609c) shows how the colors should be used visually.

<img width="199" alt="01" src="https://user-images.githubusercontent.com/407647/36678206-c899c166-1ad5-11e8-910b-06ca25e2fdba.png"> <img width="197" alt="02" src="https://user-images.githubusercontent.com/407647/36678217-cc8daca6-1ad5-11e8-8d24-c289a1d1dfa9.png"> <img width="199" alt="03" src="https://user-images.githubusercontent.com/407647/36678221-d0019eec-1ad5-11e8-964c-6bd4e52b3866.png">

<img width="196" alt="04" src="https://user-images.githubusercontent.com/407647/36678226-d2a29fd4-1ad5-11e8-806b-26aabc0b1f24.png"> <img width="197" alt="05" src="https://user-images.githubusercontent.com/407647/36678234-d662db0c-1ad5-11e8-852f-e3a732c09cf7.png"> <img width="197" alt="06" src="https://user-images.githubusercontent.com/407647/36678252-dd2e642e-1ad5-11e8-9ffe-97123c0b85f4.png">

**Comment by ujjwalagrawal17** [comment]
how is primary dark color selected?

<table>
<tr>
<td>

![screenshot_20180228-010941](https://user-images.githubusercontent.com/19607555/36750712-3d3f593c-1c24-11e8-842c-96cb84e4f391.png)

</td>
<td>

![screenshot_20180228-010819](https://user-images.githubusercontent.com/19607555/36750714-3d722d58-1c24-11e8-8434-279118645d35.png)

</td>
</tr>
</table

I had attached 2 combinations 

Image 1 has our Primary color and Primary Dark color 2 shades darker than primary color 
Image 2 has our Primark Dark color and primary color 2 shades lighter than primary dark color

Shades are selected from https://coolors.co/0c609c-0a4f80-2e5b87-00376d-685044

I want feedback from you so that we can change any one color.

**Comment by ujjwalagrawal17** [comment]
@nicolas-raoul  @maskaravivek  what do you think?

**Comment by misaochan** [comment]
@neslihanturan ?

**Comment by misaochan** [comment]
Pinging @neslihanturan , as the current color scheme was created by her.

**Comment by nicolas-raoul** [comment]
If I had to choose between Image 1 and Image 2 in your comment two days ago, I guess I would choose Image 2 :-)

**Comment by ujjwalagrawal17** [comment]
Should I close this issue?
