### ISSUE TITLE
Give toast when trying to upload image without giving a Title

### ISSUE THREAD

**Issue by hismaeel** [commons-app/apps-android-commons#1195]
small issue. When uploading a new image, if I click on the next button at top right without filling in a title, it does nothing. A toast that reads "Please give a Title to proceed" would be helpful. I can start working on this :)
![shot](https://user-images.githubusercontent.com/25305892/36636763-ff9fc566-199a-11e8-8d3d-929f2955d427.png)

**Comment by psh** [comment]
I count three open PR from you right now @hismaeel ... I appreciate your enthusiasm for the project but maybe it would be worth letting someone else work on the issue and get their chance to participate?

**Comment by hismaeel** [comment]
@psh Sure Thing!

**Comment by tshradheya** [comment]
Can I take this up?

**Comment by maskaravivek** [comment]
Sure @tshradheya. Feel free to take it up. :)
