### ISSUE TITLE
Text isn't formatted properly in Tutorial PageViews

### ISSUE THREAD

**Issue by gupta-meghna64** [commons-app/apps-android-commons#1196]
## Summary
Formatting the text properly in the tutorial page views would enhance the UI of the application. Instead of a '-', a bullet point should be used, and the line wraps should be properly indented.

## Steps to Reproduce
Changes will be made to the following pages:
1) welcome_do_upload.xml(landscape too)
2) welcome_dont_upload.xml(landscape too)
3) welcome_image_details.xml(landscape too)

## Observed Screenshots
![whatsapp image 2018-02-25 at 12 38 44 pm 1](https://user-images.githubusercontent.com/20908024/36639044-36fe3b08-1a29-11e8-8530-70e9c2fb9038.jpeg)

## Expected Screenshots
![whatsapp image 2018-02-25 at 12 38 44 pm](https://user-images.githubusercontent.com/20908024/36639046-4028cc8e-1a29-11e8-984e-a1444b327f06.jpeg)

**Comment by maskaravivek** [comment]
Looks good to me. It might be a good idea to let others pitch in too. @neslihanturan your thoughts on this?

@gupta-meghna64 There are a lot of other beginner friendly tasks as well that you could take up. :)

**Comment by nicolas-raoul** [comment]
Looks good to me! :-)
