### ISSUE TITLE
[Discussion] Announce the app on Wikimedia Commons Mobile

### ISSUE THREAD

**Issue by Steinsplitter** [commons-app/apps-android-commons#1197]
Wikimedia Commons Mobile (https://commons.m.wikimedia.org/wiki/Main_Page) is the mobile site for the webbrowsers, but it is imho alpha. it does not support gadgets, the improved upload form is not supported, no real mobile upload client, etc. etc. 

I am inclined to announce the app somewhere there.

Maybe on the (Mobile) Main Page?
Or we could add it somewhere to he interface (for example to the navbar or footer) using https://commons.wikimedia.org/wiki/MediaWiki:Mobile.js

**Comment by VojtechDostal** [comment]
I think that would really be cool. Who should be involved in such decision?

**Comment by Steinsplitter** [comment]
I thought something like this:

![bildschirmfoto vom 2018-02-25 um 12 53 14](https://user-images.githubusercontent.com/6726292/36641154-503c013e-1a2b-11e8-9418-4a8edf7b4fcf.png)


```
// Quick test
mw.loader.using( 'mediawiki.user', function () {
 var isAndroid = /(android)/i.test(navigator.userAgent);
 // is logged in and using android
 if ( !mw.user.isAnon() && isAndroid ) {
  ComApp = document.getElementById("mw-mf-page-left");
  ComAppC = document.createElement("div");
  ComAppC.innerHTML = '<p><a href="https://play.google.com/store/apps/details?id=fr.free.nrw.commons" rel="nofollow"><img alt="Android.png" src="https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Android.png/90px-Android.png" srcset="https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Android.png/135px-Android.png 1.5x, https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Android.png/180px-Android.png 2x" data-file-width="300" data-file-height="100" width="90" height="30"></a> <a href="https://f-droid.org/repository/browse/?fdid=fr.free.nrw.commons" rel="nofollow"><img alt="Get it on F-Droid.svg" src="https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Get_it_on_F-Droid.svg/90px-Get_it_on_F-Droid.svg.png" srcset="https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Get_it_on_F-Droid.svg/135px-Get_it_on_F-Droid.svg.png 1.5x, https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Get_it_on_F-Droid.svg/180px-Get_it_on_F-Droid.svg.png 2x" data-file-width="512" data-file-height="177" width="90" height="31"></a></p>';
  ComApp.insertBefore(ComAppC, ComApp.firstChild);
 }
});
```

**Comment by VojtechDostal** [comment]
It seems great. It will definitely improve the awareness of the app. @misaochan Is it OK for you?

**Comment by misaochan** [comment]
That would be wonderful, thanks so much @Steinsplitter ! :)

**Comment by misaochan** [comment]
Oh, one minor edit suggestion - F-Droid and Google Play are both app repositories for Android. I presume the first link will be to https://play.google.com/store/apps/details?id=fr.free.nrw.commons , in which case we would usually say "Download on Google Play" instead of "Download for Android" if there is simultaneously an F-Droid download present, and it would usually use the Google Play icon ([example](https://github.com/commons-app/apps-android-commons)). But it's a minor issue, I'm fine either way.

**Comment by Steinsplitter** [comment]
@misaochan Okay, i changed the icon. The change is live now :)

**Comment by misaochan** [comment]
@Steinsplitter Thanks! I could not see the buttons until I logged in, though - was that intended?

**Comment by Steinsplitter** [comment]
>>was that intended?
Yes.

**Comment by misaochan** [comment]
Looks good to me in that case. :) Shall we close this issue?

**Comment by VojtechDostal** [comment]
@Steinsplitter could you please look at #1213 ? I think you might be an admin of the relevant page :-)
