### ISSUE TITLE
Feedback Feature shows unsupported clients

### ISSUE THREAD

**Issue by ayushin78** [commons-app/apps-android-commons#1203]
**Summary:** 

Instead of showing only the email clients, The Feedback feature is showing multiple unsupported clients (WhatsApp, Bluetooth etc.). 

**Steps to reproduce:** 
1. Install some apps which can be used for sharing. ( e.g. WhatsApp, Bluetooth)
2. In the Navigation Drawer, press on Feedback.

**Observed Behaviour**
Multiple unsupported clients being displayed.

**Expected Behaviour**
Show the email clients only, not all the other available sharing apps. Not only will it reduce the chances of running into an error upon the selection of an unsupported app, but User's time will also be saved.

**Device and Android version:** 
Samsung A8
Android 6.0 Marshmallow

 **Commons app version:** 
2.6.7

**Screen-shots:** 
![screenshot_20180226-031109 2](https://user-images.githubusercontent.com/18305466/36647056-bdc05ce4-1aa5-11e8-8eec-bc1b3a830b77.png)

**Comment by knight-shade** [comment]
Ya @ayushin78 , even I was wondering what's wrong with feedback feature. Nice :+1:
