### ISSUE TITLE
Add ItemDivider in NearbyListFragment

### ISSUE THREAD

**Issue by knight-shade** [commons-app/apps-android-commons#1205]
**Summary:**

Currently, There is no ItemDivider used in the NearbyListFragment. adding an ItemDivider will make it look cleaner and will help users to understand how the content is organized.

**Steps to reproduce:** 
1. Go to nearby from navigation drawer.
2. Select list mode.

**Expected behavior:** 
![after](https://user-images.githubusercontent.com/20313518/36649424-fb728176-1ac2-11e8-968c-de8f8db15ccb.jpeg)

**Observed behavior:** 
![before](https://user-images.githubusercontent.com/20313518/36649427-00faa61e-1ac3-11e8-9ba4-10083e7ae1bf.jpeg)

**I have made a fix, creating PR very soon.**

**Comment by maskaravivek** [comment]
@knight-shade Really appreciate your enthusiasm but @ayushin78 had already raised a PR for the same issue. That PR is now merged. 

Closing this PR. Please feel free to take up other issues. :)
