### ISSUE TITLE
"Use App" at Wikimedia Commons official Facebook page should go to our download page

### ISSUE THREAD

**Issue by VojtechDostal** [commons-app/apps-android-commons#1213]
There is a nice blue button here:
https://www.facebook.com/WikiCommons/

that goes to a meta page, which seems useless to me. 

I'd like to ask the WMF Social team to change this to our app download page. 
Or should it go to our website? https://commons-app.github.io/ ?

**Comment by misaochan** [comment]
This would be wonderful if possible! I think going to our Google Play download page would make the most sense for most users. F-Droid users will likely know how to work around it.

**Comment by VojtechDostal** [comment]
OK, I will try :-)

**Comment by VojtechDostal** [comment]
I asked WMF Social and they seem to have no problem. They redirected me to admins of the page.

**Comment by Steinsplitter** [comment]
CC: @NahidSultan

**Comment by NahidSultan** [comment]
Done :)
Added our Commons page: https://commons.wikimedia.org/wiki/Commons:Mobile_app

**Comment by VojtechDostal** [comment]
Thank you
