### ISSUE TITLE
Add missing space between Licence and Coordinates in MediaDetailFragment

### ISSUE THREAD

**Issue by ayushin78** [commons-app/apps-android-commons#1215]
**Summary:** 
In MediaDetailFragment, space is missing between Licence and Coordinates

**Steps to reproduce:** 
1. Click on home, to see 'My Recent Uploads'
2. Scroll the Detail Pane up.

**Device and Android version:** 
Samsung A8
Android 6.0 Marshmallow

 **Commons app version:** 
2.6.7

**Screen-shots:** 

Observed Display            |  Expected Display
:-------------------------:|:-------------------------:
![screenshot_20180227-011146](https://user-images.githubusercontent.com/18305466/36695263-d5969ec0-1b66-11e8-934a-0595e8d2b14c.png) |  ![screenshot_20180227-021405](https://user-images.githubusercontent.com/18305466/36695273-d9f5cafe-1b66-11e8-8a86-871f641fcf26.png)

**Note: I am not working on it.  New Contributors may use it as their first contribution :)**

**Comment by gupta-meghna64** [comment]
Hi! I'd like to work on this issue. Can I please start working on this? 
Thanks!

**Comment by nicolas-raoul** [comment]
Good catch!
OK it's yours :-)

**Comment by tshradheya** [comment]
@nicolas-raoul I think the note on the issue description states that she isn't working on it.
Can I take a stab at this?

**Comment by nicolas-raoul** [comment]
@tshradheya Ah yes I misread, it's yours then ;-) Thanks!
