### ISSUE TITLE
Add password visibility toggle to login screen.

### ISSUE THREAD

**Issue by knight-shade** [commons-app/apps-android-commons#1218]
**Summary:** 
There is no password visibility toggle option at login screen. Its definitely good for newcomer to android and user having long passwords, and strangely it is explicitly set to false in code. 

**Screen-shots:** 
Before
![before 1](https://user-images.githubusercontent.com/20313518/36734061-72dbb990-1bf8-11e8-97f8-bde4691c3626.jpeg)

After
![after 1](https://user-images.githubusercontent.com/20313518/36734065-75ea1ca8-1bf8-11e8-890f-6dbad658930b.jpeg)

**Comment by nicolas-raoul** [comment]
I have no strong opinion on this.
Indeed some users might want it, so why not.
