### ISSUE TITLE
Extra padding in uploaded media categories section

### ISSUE THREAD

**Issue by gupta-meghna64** [commons-app/apps-android-commons#1222]
### Summary 
An extra bottom padding is present after the media detail category container, which makes it inconsistent with the rest of the containers.

### Steps to reproduce 
1) Open the details of the uploaded media
2) Scroll down to media category container

### Expected behavior
![new](https://user-images.githubusercontent.com/20908024/36748225-3aa5b54c-1c1d-11e8-8632-c3f990af9f6f.jpeg)

### Observed behavior 
![old](https://user-images.githubusercontent.com/20908024/36748247-4aa1e4ca-1c1d-11e8-800b-b33bea5ccf52.jpeg)

### Device and Android version 
Redmi Note 3
6.0.1 MMB297

### Commons app version
2.6.7 

#### I'd like to work on this issue. Thanks :-)

**Comment by maskaravivek** [comment]
@gupta-meghna64 I really can't find out the difference between the two screenshots. Am I missing something?

**Comment by maskaravivek** [comment]
Aah! Spotted it. Very subtle. Good catch. :P

**Comment by gupta-meghna64** [comment]
Thanks xD
I've referenced a PR. Please review!

**Comment by maskaravivek** [comment]
Approved! Will merge once the tests pass. 

Thanks for the contribution :)
