### ISSUE TITLE
Show complete text of welcome notification

### ISSUE THREAD

**Issue by ayushin78** [commons-app/apps-android-commons#1224]
**Summary:**
Welcome Notification doesn't redirect the user to any link. As a user, I would like to know the complete information displayed in the notification. So, Either it should redirect the user to an external link containing the full information or it should show the complete text of the notification.

**Steps to reproduce:** 
1. After Login, click on Notifications.
2. Check the welcome notification.

**Device and Android version:** 
Samsung A8
Android 6.0 Marshmallow
 
 **Commons app version:** 
2.6.7

**Screen-shots:** 
![2](https://user-images.githubusercontent.com/18305466/36746213-b9d98736-1c17-11e8-8151-1712be1213ec.png)

**How will I proceed on this issue**
Since the API itself doesn't provide any link for welcome notifications. Removing the maxLines limit of title can be a quick fix. @maskaravivek please let me know if this approach is okay, will open the PR accordingly.
Thanks. :)

**Comment by maskaravivek** [comment]
Am not sure how the notifications would look if the message is too long. Instead of removing the `maxLines` limit we can probably just increase it. 
Moreover:
- It would be great if we could reduce the padding and size of the image. That would give us some more space for the notification text.

**Comment by Jatin0312** [comment]
Can't we include a button in notification to completely see the notification, so whenever a user clicks on that notification button complete text will be displayed something like see more, see fewer buttons in LinkedIn, Facebook.
Example:
![bug](https://user-images.githubusercontent.com/17095817/36805691-1726d6ba-1ce4-11e8-9b47-0b22998a3bf4.gif)

**Comment by maskaravivek** [comment]
The see more option actually makes sense and it would be great if we could implement that.

**Comment by Jatin0312** [comment]
I would like to work on this issue

**Comment by maskaravivek** [comment]
Sure, please feel free to pick this up. :)

**Comment by Jatin0312** [comment]
@maskaravivek  I have created a fix. Please review it, I will create a pull request accordingly. Thanks :)
Screenshot showing what changed.
![solved3](https://user-images.githubusercontent.com/17095817/36934781-671ff782-1f14-11e8-95a7-f222ad2a00ec.gif)

**Comment by maskaravivek** [comment]
@Jatin0312 I couldn't find the PR for this. Can you attach a link for it.

**Comment by Jatin0312** [comment]
Ya sure, I will send a PR soon.
