### ISSUE TITLE
Replacement of tutorial icon in navigation drawer

### ISSUE THREAD

**Issue by gupta-meghna64** [commons-app/apps-android-commons#1226]
### Summary
The icon used for tutorials in the navigation drawer is the same as the about icon. As an enhancement to the User Interface, a different icon should be used.

### Steps to reproduce
1) Launch the application
2) Open the navigation drawer

### Device and Android version
Redmi Note 3
MIUI 6.0.1 MMB29M

### Commons app version
2.6.7

### Screenshots 
Before:
![whatsapp image 2018-02-28 at 4 06 59 pm 1](https://user-images.githubusercontent.com/20908024/36783393-dcc1ebbe-1ca1-11e8-8dd0-57adecba5f85.jpeg)
After:
![whatsapp image 2018-02-28 at 4 06 55 pm 1](https://user-images.githubusercontent.com/20908024/36783409-ea4ea9b6-1ca1-11e8-9ce1-5724357a5a25.jpeg)

Can the help icon be used instead of the info icon? Please give your inputs!
I would really like to work on this issue.  
Thanks

**Comment by knight-shade** [comment]
@gupta-meghna64 How about this one?
![6-512](https://user-images.githubusercontent.com/20313518/36784416-4a8c4e8e-1ca5-11e8-9d2c-22b1f94ce5fd.png)

**Comment by neslihanturan** [comment]
Not this one @gupta-meghna64 :) I would prefer something simpler. Actually your screenshots looks nice

**Comment by gupta-meghna64** [comment]
Cool @neslihanturan 
I'll reference a PR with this issue then with the result as the above screenshot :-)
