### ISSUE TITLE
Add re-center button to Nearby map (in feature branch)

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#1228]
After testing the Nearby feature in `directNearbyUploads` branch for a bit, I really think that we need to provide a way for users to re-center the map on their current location. Users will be swiping a lot to switch between the list and the map - and if they swipe wrongly and move the map away, they have to reload Nearby or manually go back to their location.

I do recall that we discussed this somewhere else and it was mentioned that the Material guidelines recommend not having more than 1 FAB in the screen. However, I think that a small re-center icon on the upper right would not be amiss, especially given that our other FAB is actually in the bottom sheet and not on the map itself. For reference, Google Maps also uses 3 FABs, 1 of which is the re-center button.

Thoughts?

**Comment by misaochan** [comment]
Thanks for the feedback, guys. :) If anyone is interested in implementing this, please remember to work from (and submit the PR to) the `directNearbyUploads`  feature branch, and not master.

**Comment by Jatin0312** [comment]
I would like to work on this issue. Thanks :)

**Comment by neslihanturan** [comment]
Solved.
