### ISSUE TITLE
Ability to change Media Title, Description, and Category 

### ISSUE THREAD

**Issue by hismaeel** [commons-app/apps-android-commons#1229]
Would be great if users are allowed to rename Image Titles, and change Image Descriptions, and Categories. One might learn something new about the picture/item, or about it's details/description, and would then like to update it. Will also help those writing Wikipedia articles get more refined/relevant results. 

![edit](https://user-images.githubusercontent.com/25305892/36820189-a4a5c0c0-1cba-11e8-97f9-9fc080cbdc5a.png)

Any thoughts?

**Comment by nicolas-raoul** [comment]
Nice! Sounds like #161 though?
If duplicate could you please close this one and post your design there? Thanks! :-)

**Comment by nicolas-raoul** [comment]
Editing the title is currently usually discouraged but, but hopefully that will change with Structured Commons captions.

**Comment by hismaeel** [comment]
Ah missed that. 
Great 👍
