### ISSUE TITLE
Add showcase feature in the app for new users

### ISSUE THREAD

**Issue by ujjwalagrawal17** [commons-app/apps-android-commons#1230]
**Summary:** 

We can add showcase feature in our app to provide ease to new users.

**Steps to reproduce:** 

Use Material Showcase view in the app to tell the user how to upload images and more 
Link -https://github.com/deano2390/MaterialShowcaseView

**What did you expect the App to do?**

The app should have showcase/tooltip feature.

**What did you see instead?**

No showcase/tooltip feature is present.

**Screen-shots:** 

![showcase](https://user-images.githubusercontent.com/19607555/36826120-5ed21982-1d31-11e8-8d80-11588002a97f.png)

**Comment by nicolas-raoul** [comment]
Could you please write down above what features should be showcased?
Thanks!
