### ISSUE TITLE
Add Option to donate to Wikimedia Foundation

### ISSUE THREAD

**Issue by ujjwalagrawal17** [commons-app/apps-android-commons#1231]
**Summary:** 

we can have a button that redirects to the webpage of Wikimedia Foundation may be in about page

**Steps to reproduce:** 

we Can  have a button that redirects to the webpage of Wikimedia Foundation 
 Link - https://wikimediafoundation.org/wiki/Ways_to_Give

**Expected behavior:** 

No donation option is available.

**Observed behavior:** 

donation option should be available.

**Comment by nicolas-raoul** [comment]
Since the app is partly funded by WMF, I agree that sounds right.
The label should make it clear that donation do not go to the app specifically, but to WMF as a whole.
How about a "Donate to the Wikimedia Foundation" link in the "About" menu?

**Comment by gupta-meghna64** [comment]
Hi! Can I please work on this issue? 
Thanks :-)

**Comment by ujjwalagrawal17** [comment]
@gupta-meghna64 ok you work on it.

**Comment by misaochan** [comment]
@nicolas-raoul Do you think we should ask WMF Legal first? I mean, I don't see any reason why they'd say no, but given that they requested us to make a very clear disclaimer about the app not being maintained by WMF, it might be somewhat misleading to have this button around.

**Comment by VojtechDostal** [comment]
I thought about this and I'm rather against. WMF is not actively maintaining the app and we are only financially supported. Adding the link might set a precedent for other projects financially supported by WMF and I don't think that's a good idea.

**Comment by gupta-meghna64** [comment]
@misaochan @VojtechDostal @ujjwalagrawal17 Should I close the referenced PR in that case? 
Thanks

**Comment by misaochan** [comment]
Probably best to wait for @nicolas-raoul to get back so we can come to a consensus. I wouldn't spend any more time on this until then though. :)

**Comment by misaochan** [comment]
Probably best to close this, then. Thanks everyone!
