### ISSUE TITLE
Skip option in the Welcome screen for beta debug builds

### ISSUE THREAD

**Issue by maskaravivek** [commons-app/apps-android-commons#1239]
**Summary:** 

Skip option in the Welcome screen. There are 5 pages in this screen and as a regular user, whenever i reinstall the app, i find it meaningless to swipe to get to the last screen. 

**Steps to reproduce:** 

![skip_welcome](https://user-images.githubusercontent.com/3069373/36916990-8f4d2d36-1e7b-11e8-95fa-9de08715fc51.png)

**Expected behavior:** 

Option to **Skip** the tutorial would be great.

**Comment by tanvidadu** [comment]
I agree @maskaravivek it's an additional task for users who are already familiar with the working of the app

**Comment by tanvidadu** [comment]
I will start working on this issue :)

**Comment by maskaravivek** [comment]
Yes, i also believe that it should be added in all the screens. Before you start working on it, it would be great to get a go ahead from someone else too. 

@misaochan @neslihanturan @nicolas-raoul

**Comment by neslihanturan** [comment]
It would be a lot easier for developers indeed:) We already display tutorial on nav bar so I think skip button is a good idea.

**Comment by misaochan** [comment]
This is a bit tricky unfortunately, I don't think I am on board with this change. Indeed it would be easier for users if we allowed them to skip, however, the tutorial was a big part of the reason why WMF funded my initial grant to begin with. :) It is really important to them that new users MUST go through it.

I can think of a few in-between alternatives:

- Only allow skipping in the betaDebug build variant. This will allow devs to skip, not users
- Allow skipping if user has gone through it at least once before. However this might not be that easy to code.

**Comment by neslihanturan** [comment]
betaDebug build variant is a great idea @misaochan

**Comment by maskaravivek** [comment]
Yeah I agree with the skip option to be there just for the betaDebug version. Updating the issue title as well.
