### ISSUE TITLE
Gallery only shows latest 3 images

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#1243]
**Summary:** 

Gallery only shows latest 3 images, seemingly no way to see more.

**Steps to reproduce:** 

1. Open the app with an account that has 100+ uploads
2. Only the last 3 ones can be seen

**Expected behavior:** 

I expect to be able to see my past pictures too.

**Observed behavior:** 

Only 3 pictures visible.

**Device and Android version:** 

Android 7.1.2
 
 **Commons app version:** 

Commons app 2.6.7

**Comment by anudeep3998** [comment]
Working on this issue.

**Comment by anudeep3998** [comment]
I can't seem to reproduce this. Do you have `Set Recent Upload Limit` in settings on by chance?

**Comment by nicolas-raoul** [comment]
wow you're right I did not remember about this setting haha

I was reacting to this comment from a user:
> in the past the app allowed people to see a list of their own (latest) uploads. I restarted the app and now I can't even do that.
Maybe they did the same mistake as me?
