### ISSUE TITLE
Add FAQs page in Commons App

### ISSUE THREAD

**Issue by ujjwalagrawal17** [commons-app/apps-android-commons#1246]
**Summary:** 

We need to add a FAQs page in App.We can choose some FAQs from the website.
Link to FAQs - https://commons.wikimedia.org/wiki/Commons:FAQ#What_is_this_site_about?

**Steps to reproduce:** 

Add a new Activity /Fragment for FAQs Page.

**Expected behavior:** 

There should be a page for FAQs.

**Observed behavior:** 

There is no FAQ page in the app now.

**Screen-shots:** 
UI can be like this.
<table>
<tr>
<td>

![screenshot_20180303-155305](https://user-images.githubusercontent.com/19607555/36933222-5996c302-1efb-11e8-85d1-eed528541ae1.png)

</td>
<td>

![screenshot_20180303-155312](https://user-images.githubusercontent.com/19607555/36933221-59672dcc-1efb-11e8-9803-de2cfcce3cdb.png)

</td>
</tr>
</table>

or we can add a link in about page of the App.

**Comment by madhurgupta10** [comment]
Hi, I would like to work on this issue!

**Comment by ujjwalagrawal17** [comment]
@madhurgupta10 Hey I also want to work on it. 
You can work on some other issue if you want. Maybe: https://github.com/commons-app/apps-android-commons/issues/1230.
Sorry :)

**Comment by madhurgupta10** [comment]
@ujjwalagrawal17 can I implement [Photo Challenge](https://commons.wikimedia.org/wiki/Commons:Photo_challenge#Challenges_open_for_submission) to app?

**Comment by ujjwalagrawal17** [comment]
@madhurgupta10 Yes you can. You need to create an issue before working on it. It seems to be a big task so we can divide it into small issues and then work on it.

**Comment by maskaravivek** [comment]
@ujjwalagrawal17 IMO, it would be great if you could add a wiki page for the FAQs here on github. We can include a link to it in the app. That link could either be in the About page or in the hamburger menu. My vote would go for adding it in the about page.

**Comment by misaochan** [comment]
I agree, a link to the relevant wiki page in About would be the best way to go about it IMO. Feel free too add any questions you want; I have a few in mind and will add to it later. :)
