### ISSUE TITLE
Multiple instances of Notification Activity are being opened

### ISSUE THREAD

**Issue by Jatin0312** [commons-app/apps-android-commons#1250]
**Summary:** 
Multiple instances of Notification Activity are being created in Activity stack.

**Steps to reproduce:** 

Everytime a notification activity instance is being created when notifications is pressed in Navigation Drawer.

**Expected behavior:** 

What did you expect the App to do?

**Screenshot**

![solved5_2](https://user-images.githubusercontent.com/17095817/36939424-c53cff08-1f56-11e8-82e4-dcda24538b84.gif)

**Observed behavior:** 

Every time notifications are clicked on navigation drawer a new instance is being created, instead the activity should be resumed from activity stack.

Screenshot 
![bug5](https://user-images.githubusercontent.com/17095817/36939439-1a3fc74c-1f57-11e8-8284-d9cdd27487ec.gif)

**Device and Android version:** 

Moto g4 Plus
Android 7.0 Nougat
 
 **Commons app version:** 
2.6.7

I already have a fix only creating PR is left.

**Comment by maskaravivek** [comment]
@Jatin0312 can you create a PR for it :)

**Comment by Jatin0312** [comment]
Ya sure I will do it.
