### ISSUE TITLE
Details activity: Open category in-app

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#1252]
Once a form of category navigation is available, it would be great if it were accessible by clicking a category of an existing media.

**Comment by Jatin0312** [comment]
Can I get more insight into this issue. On what to actually do so that I can try working on this issue.
Thanks :)

**Comment by misaochan** [comment]
I don't think this can be implemented until we actually have category navigation?

**Comment by nicolas-raoul** [comment]
Yes, this can not start until #1221 is done, which will take at least a few months.
