### ISSUE TITLE
Privacy Policy in Login Page missing

### ISSUE THREAD

**Issue by gupta-meghna64** [commons-app/apps-android-commons#1255]
### Summary 
Privacy policy is missing in the Login Page. The privacy policy textview should be linked to the following website: https://github.com/commons-app/apps-android-commons/wiki/Privacy-policy

### Steps to reproduce 
1) Open the commons application.
2) Click on Privacy Policy.

### Expected behavior 
Clicking the privacy policy should redirect us to https://github.com/commons-app/apps-android-commons/wiki/Privacy-policy

### Observed behaviour 
Nothing happens on clicking privacy policy.

### Device and Android version
Xiaomi Redmi Note 3
Android Version 6.0.1 MMB29M

### Commons app version 
2.6.7

### Screenshots
![whatsapp image 2018-03-04 at 10 17 20 am 1](https://user-images.githubusercontent.com/20908024/36942490-4c58b15c-1f99-11e8-9553-2db66b742369.jpeg)

**Comment by maskaravivek** [comment]
Sure take it up @gupta-meghna64

**Comment by Roshan13046** [comment]
This issue should be closed as it's fixed.
