### ISSUE TITLE
Translation updates on hold

### ISSUE THREAD

**Issue by Nikerabbit** [commons-app/apps-android-commons#1258]
Hi, I've paused translation updates due to unresolved parsing issue I commented in https://github.com/commons-app/apps-android-commons/commit/96173e26cf07ef0d3f23cb8bb9ca4b21820eddf5#r27787891

Let's try to find a quick way to solve this.

**Comment by misaochan** [comment]
@Nikerabbit Do you think any of the solutions at https://stackoverflow.com/questions/10374847/is-there-a-way-to-store-a-string-with-markup-in-the-strings-xml would help?

**Comment by Nikerabbit** [comment]
The issue is that I am using PHP's `SimpleXML` and when I am trying to read the text value of something that contains other tags it seems to return null.

Escaping `<` and `>` would work, both using `CDATA` and using entities. For exported translations they would be escaped as `&lt;u&gt;`.

Third way would be to fix our file format parser to understand u/i/b tags which are allowed by the spec as far as I know, but I don't know any straightforward way to do it using SimpleXML. Maybe something like https://stackoverflow.com/questions/4145424/getting-the-xml-content-of-a-simplexmlelement but have to be careful not to break other things.

**Comment by misaochan** [comment]
Anyone, please feel free to submit a PR for this. Should be a fairly straightforward fix. :)

**Comment by knight-shade** [comment]
@misaochan  I would like to work on this issue :blush:

**Comment by Nikerabbit** [comment]
I missed this for today's exports, but next one will be on Thursday.

**Comment by misaochan** [comment]
Thanks @Nikerabbit !

**Comment by Nikerabbit** [comment]
I just noticed `<string name="about_rate_us"><u>Rate Us</u></string>` has the same problem by the way.

**Comment by misaochan** [comment]
Lets reopen then.

**Comment by knight-shade** [comment]
@misaochan seems @madhurgupta10 's [PR](https://github.com/commons-app/apps-android-commons/pull/1304) fixes it.

**Comment by madhurgupta10** [comment]
@Nikerabbit I just opened that issue #1303,  I was not aware that it was under this issue.

**Comment by Mansi449** [comment]
@Nikerabbit @misaochan  I would like to work on this issue!

**Comment by misaochan** [comment]
This can be closed I hope?

**Comment by Nikerabbit** [comment]
Still multiple messages having an issue:
```
[26-Mar-2018 04:51:36 UTC] No source text for Commons-android-strings-about_privacy_policy (commons-android-strings)
[26-Mar-2018 04:51:36 UTC] No source text for Commons-android-strings-about_credits (commons-android-strings)
[26-Mar-2018 04:53:29 UTC] No source text for Commons-android-strings-about_rate_us (commons-android-strings)
[26-Mar-2018 04:53:34 UTC] No source text for Commons-android-strings-about_translate (commons-android-strings)
```

What happened here? I thought they were fixed? I see it was reverted in a984a302 by @madhurgupta10 .

**Comment by misaochan** [comment]
Ah, snap.

As this is a fairly simple fix, I would recommend this to beginners looking for an issue to fix. :)

**Comment by neslihanturan** [comment]
This task waits some beginners to fix it:)

**Comment by Mansi449** [comment]
I would like to work on this issue...please assign it to me!

**Comment by nicolas-raoul** [comment]
@Mansi449 It's yours :-)

**Comment by Mansi449** [comment]
Please review my pull request

**Comment by misaochan** [comment]
@Nikerabbit , the recent PR should have solved the problem. Please do let us know if there are any further issues, thanks!
