### ISSUE TITLE
Nothing happens on clicking a notification

### ISSUE THREAD

**Issue by madhurgupta10** [commons-app/apps-android-commons#1260]
**Summary:** 

Nothing happens on clicking a notification

**Steps to reproduce:** 

Go to **Notifications > Click on any notification**

**Expected behavior:** 

Should display more information about the particular notification 

**Observed behavior:** 

Nothing happens on clicking a notification

**Device and Android version:** 

Android Oreo 8.0
Xiaomi Mi A1

 **Commons app version:** 

2.6.7-degub-b1~4c3513b4

**Screen-shots:** 

![ezgif-1-84b2eb514c](https://user-images.githubusercontent.com/30932899/36949610-b34c3204-2010-11e8-8d79-8827ea013121.gif)

**Comment by knight-shade** [comment]
@madhurgupta10  This behaviour is only for the welcome notification, tapping on other notification trigger specific actions. Eg. if you have uploaded a picture and then tap on it's notification you are directed to its webpage.

**Comment by gupta-meghna64** [comment]
@madhurgupta10 This issue is similar to #1224

**Comment by maskaravivek** [comment]
@gupta-meghna64 How is this issue similar?

**Comment by gupta-meghna64** [comment]
@maskaravivek the issue is similar in the context that since welcome notification do not have a new webpage linked to it, therefore the only improvisation that can be done to it is to show the full welcome notification text which is being achieved as of now by the idea of #1224.
