### ISSUE TITLE
App shows 0 uploads even after multiple pictures uploads.

### ISSUE THREAD

**Issue by knight-shade** [commons-app/apps-android-commons#1262]
**Summary:** 
In the toolbar, the apps shows number of uploads of the user, which is always 0 even after uploading multiple pictures.

**Steps to reproduce:** 

Login into your account in the app.

**Expected behavior:** 

The upload count should show the number of pictures uploaded by the user.

**Observed behavior:** 

The upload count is always 0.

**Device and Android version:** 

Android 7.0 MIUI Global V9

**Screen-shots:** 
![whatsapp image 2018-03-06 at 8 52 40 am](https://user-images.githubusercontent.com/20313518/37012726-16447a18-211c-11e8-8fdd-4526edaefa47.jpeg)

**I am working on the issue**
**Update**
Got a fix, will be creating a PR soon.

**Comment by ayushin78** [comment]
@knight-shade I guess the `"WIKIMEDIA_FORGE_API_HOST"` is same for both the versions and since it is the beta version, The tool `urbanecmbot` which is used here to determine the uploadCount returns zero. This works correctly on the live version of the app. 
Please let me know if I misunderstood it. :)

**Comment by nicolas-raoul** [comment]
I think this is a known problem of the beta app.
A fix would be very welcome, though :-)

**Comment by misaochan** [comment]
Yup, this is a known bug for the beta build variant of the app. It should not affect the prod variant. AFAIK it was mentioned to us that the changes required would involve upstream and would be quite difficult/complex, hence why we have been leaving it be.
