### ISSUE TITLE
Launch Ratings feature from AboutActivity

### ISSUE THREAD

**Issue by ayushin78** [commons-app/apps-android-commons#1263]
**Summary:** 

The rate us feature is added in Utils, but it is never launched from the AboutActivity. 

**Steps to reproduce:** 

1. Go to About, Click on 'Rate Us'

**Expected behavior:** 

Should lead the user to the play store.

**Observed behavior:** 

Nothing happens

**Device and Android version:** 

Samsung A8
Android 6.0 Marshmallow

**Comment by ujjwalagrawal17** [comment]
Hey i think it is already added in https://github.com/commons-app/apps-android-commons/pull/1188 .
May be you have not pulled the updated code :)

**Comment by ayushin78** [comment]
Hey, I checked it again. It is showing the same behavior.
