### ISSUE TITLE
Update libraries version to the latest stable version.

### ISSUE THREAD

**Issue by knight-shade** [commons-app/apps-android-commons#1268]
**Summary:** 

The project is using old version of libraries, for which already an update version have been released.
Following libraries are outdated:

- Gson from 2.8.1 to 2.8.2

- okHttp from 3.8.1 to 3.9.1

- Fresco from 1.3.0 to 1.5.0

- Leakcanary from 1.5.1 to 1.5.4

- Kotlin from 1.1.15 to 1.2.30

Should be also update buildToolsVersion and compileSdkVersion to 27?

**Comment by maskaravivek** [comment]
@knight-shade Can you briefly add a description about why each of these libraries needs to be updated? :)

**Comment by nicolas-raoul** [comment]
I think that a reason would only be needed for NOT updating a library :-)

2018/03/07 15:39 "Vivek Maskara" <notifications@github.com>:

**Comment by misaochan** [comment]
I'm okay with updating libraries (alongside buildToolsVersion etc), with the caveat that they need to be tested on a Release build variant (preferably ProdRelease) before merging. We have unfortunately had issues with library changes causing issues in a Release build but not a Debug build. :/

**Comment by tanvidadu** [comment]
We can also have commit per update as it might help in testing and isolation of possible errors, which else would be difficult to resolve. 
I will like to work on it but i might need help while testing it on Release Build Variant

**Comment by knight-shade** [comment]
@tanvidadu I am already working on the issue.

**Comment by maskaravivek** [comment]
My concern at updating all the libraries at once was exactly what @misaochan is pointing to. Extensive testing needs to be done if we update the libraries. 

Moreover unless updating the library fixes some issue that our app is currently facing or introduces a feature that we might be interested in using, this exercise will only add testing efforts from our side. :)

On the other hand I completely agree with keeping `buildToolsVersion` etc up to date. These updates come from Google and thus give much more confidence while updating.

**Comment by psh** [comment]
So, the `TL;DR` version - I think we might want to update **Fresco** but the other libraries can probably wait

The longer version:

* **Kotlin** is currently only being used in tests and isnt enabled for the core app codebase.  In that regard I dont think it really matters if it lags a little behind the latest version ... I dont see a lot of people writing tests for the project right now, nor people converting the Java tests over.

* I took a look at upgrading **OkHttp** this evening - the process was smooth but again, this isnt a library that is in wide use in the application as of yet; its a transitive dependency that was called out as the future direction of where we want to go with removing obsolete networking code.  Looking through the release notes for OkHttp there arent any changes that form a compelling reason to upgrade.

* We are actually a lot further behind the **Fresco** latest version than I expected, or this issue lead me to believe.  We are using a single class from the library (the `SimpleDraweeView`) and that's core to all of the image viewing in our app.  If anything should be the focus out of this list I'd look at this library out of all of them.  

* The release notes for **Gson** were vague - just talking about "bug fixes" - not sure if that really constitutes a compelling reason to move the version given such a minor version bump.  When we move to the JSON based Wikimedia API, Gson will become a much more important part of the picture and we should probably wrap its upgrade into testing of the new API layer.

* **Leak Canary** has some improvements but it only really benefits developers - we dont have it enabled in the production released app - probably safe to update as it brings some better reporting, assuming anyone really looks for memory leaks during development... ;)

**Comment by knight-shade** [comment]
@maskaravivek  @misaochan  Thank you @psh for a detailed report, Everybody knows this , although just wanted to make it little bit more explicit, upgrading buildToolsVersion ,etc will also update the support libraries and Leak Canary, Fresco needs to be updated.

**Comment by misaochan** [comment]
@knight-shade Sounds like a good plan, I would go with @maskaravivek and @psh 's suggestion of upgrading buildToolsVersion and Fresco. Please test this on Release build variant and provide the details (what features you tested) in your PR. You will likely need to create your own personal keys to use for Release build testing. :)

**Comment by knight-shade** [comment]
@misaochan By release build variant, you meant betaRelease or prodRelease ? I am currently testing with betaRelease.

**Comment by maskaravivek** [comment]
@knight-shade Awesome work. :)

Yes, please go ahead and create a PR if you have managed to resolve all the issues around updating the libraries.

**Comment by misaochan** [comment]
Thanks @knight-shade ! :)

betaRelease is fine this time, but in general wherever possible, testing on prodRelease is best. The beta variant is just there to assist in cases where many files that are "unsuitable" for Commons need to be uploaded for test purposes, so that we don't spam Commons with useless files. The prod variant is the variant that users will get.

**Comment by knight-shade** [comment]
Thank you @misaochan , yup will keep that in mind for next time. :smile: Guys @maskaravivek @misaochan all the tests pass on my PC, but the build fails on travis CI build is failing, and I am totally out of ideas and stackoverflow why it is happening. Any help is much appreciated.

**Comment by misaochan** [comment]
Pinging @whym for the Travis Q.

**Comment by whym** [comment]
re Travis: we need something like c11db21fc95fc for 'android-27', I believe. (And maybe that will make older entries redundant?)

**Comment by dbrant** [comment]
Closing in favor of newer task #2591
