### ISSUE TITLE
Remove Manual Nearby Updates

### ISSUE THREAD

**Issue by neslihanturan** [commons-app/apps-android-commons#1270]
**Summary:** 

Updating Nearby Markers manually shouldn't be available since there is no case when the position change recognized and nearby didn't updated.

**Steps to reproduce:** 

Every click on reload or swipe to refresh returns with "Location is not changed" message

**Expected behavior:** 

Location change being recognized by Location Service Manager and map should be refreshed automatically.

**Comment by 97balakrishnan** [comment]
We cannot make the nearby activity refresh too often.. that won't be optimal. In that case the time gap between which we look for location changes has to be significantly high . About 5-10 seconds atleast. In that case if a user needs to quickly refresh or check changes in location these options come in handy. I personally feel that there is no need to remove Manual Refresh functionality. Although i agree that Adding Automatic refresh is an advantage.

**Comment by nicolas-raoul** [comment]
@97balakrishnan Have you tried the current master implementation (with autorefresh) and found it to be refreshing "too often"? If yes, could you please post a short screencast showing why it is not "optimal"? Thanks! :-)

**Comment by 97balakrishnan** [comment]
I saw this code in the master implementation... I think that mean that the location is updated only for a two minute interval . If the user has to refresh the location before this interval he would definitely require the refresh button and swipe option; If we have to remove the refresh button we should decrease the time interval which in turn would make the app less optimal.
/
    public class LocationServiceManager implements LocationListener { 
    public static final int LOCATION_REQUEST = 1;
    private static final long **MIN_LOCATION_UPDATE_REQUEST_TIME_IN_MILLIS = 2 * 60 * 1000;** 
    private static final long MIN_LOCATION_UPDATE_REQUEST_DISTANCE_IN_METERS = 10;

**Comment by neslihanturan** [comment]
@97balakrishnan can you please check #1241 PR, since it checks users location in every two seconds. So manual refresh is not needed anymore.

**Comment by 97balakrishnan** [comment]
I checked the PR and went through the changes. But, I don't think checking for location updates every two seconds will be battery.  It will result in battery drain. I googled regarding this and i found that in some devices the GPS doesn't support automatic location updates less than 10 seconds. So I think that the refresh option is mandatory for the app.

https://developer.android.com/reference/android/location/LocationManager.html#requestLocationUpdates(java.lang.String,%20long,%20float,%20android.location.LocationListener)

> Choosing a sensible value for minTime is important to conserve battery life. Each location update requires power from GPS, WIFI, Cell and other radios. Select a minTime value as high as possible while still providing a reasonable user experience.
> 
>However it is more difficult for location providers to save power using the minDistance parameter, so minTime should be the primary tool to conserving battery life

**Comment by neslihanturan** [comment]
What is your suggestion to track users location without checking users location on every two seconds? What is your solution?

**Comment by 97balakrishnan** [comment]
Yeah now i can understand the need for  auto updating every 2 seconds is the only option. Sorry.

**Comment by wailbabou** [comment]
i tried before to use LocationListener , where i listen for user position changes , to change his marker position , this is the app [weHelp](https://play.google.com/store/apps/details?id=care.wehelp)
if this is the same case , i can handle it 
with :
- using locationlistener for every 10 or 20 / 50  meters to update the map without user intervention , and without testing every 2 seconds for example

**Comment by neslihanturan** [comment]
But in any case it will be dependent to meter or seconds, or both. Meter metric can be risky since speed can differ. So we have MIN update limit for meter and second. 
MIN 2 seconds and MIN 10 meters if location data changed.
```
    private static final long MIN_LOCATION_UPDATE_REQUEST_TIME_IN_MILLIS = 2 * 60 * 100;
    private static final long MIN_LOCATION_UPDATE_REQUEST_DISTANCE_IN_METERS = 10;
```

**Comment by 97balakrishnan** [comment]
Yeah .. think so @neslihanturan @misaochan

**Comment by misaochan** [comment]
Thanks @97balakrishnan
