### ISSUE TITLE
Provide intent to be easily callable from other apps

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#1273]
As Nemobis said at https://github.com/commons-app/apps-android-commons/issues/892 we won't get huge until we get integrated with apps that many people already use.

I believe that a first step towards that direction would be to implement an intent to let other apps open the Commons app.

Example scenario:
- While waiting at the airport, I stumble upon an Olympic player Li Jinyu, and take a picture
- I share it with my friends on the popular messaging app "Telegram" (open source), with the label "Just saw Li Jinyu at the Incheon airport!".
- After posting, Telegram shows me a button or something to post to Commons as well.
- I push that button, and Telegram launches an intent with the picture, the label, and potentially other useful info.
- The Commons app opens for that picture, with the image and label pre-filled.

I am sure there are better examples, please feel free to add more :-)
Intent design and naming ideas also welcome!

**Comment by misaochan** [comment]
Sounds like a great idea. Wouldn't the other apps need to voluntarily want to do this (by modifying their own code) in order for the intent to even be used though? How do we know what sort of intent other apps would want to use? That sounds like the trickiest part.

It would be amazing if we could be integrated somewhat with the Wikipedia app. For instance, if someone uses the Wikipedia app to edit an article, there could be an option to "take an image" for that article, which would open the Commons app.

**Comment by yashshah7197** [comment]
Hey @nicolas-raoul I'd like to take this up if its not yet assigned 😄 

What we could probably do for now is implement it such that we take the image URI and the label as intent extras from the third-party apps and then open the image with the label pre-filled using the intent extras that we receive. As for the third-party apps implementing these features, we could provide a standard contract as such with which they have to abide to pass the data into our app.

**Comment by nicolas-raoul** [comment]
@misaochan Yes, the other apps would need to voluntarily modify their own code. We can't force any app to implement a call to us, but at least we can make it possible for any potential app that might want to do it :-)

@yashshah7197 It's yours! Could you please first describe the intent you envision, using the syntax seen at the numerous examples of http://www.openintents.org/intentsregistry/ ? Thanks!

**Comment by yashshah7197** [comment]
@nicolas-raoul sure! Here is the one that I suggest we use - http://www.openintents.org/action/android-intent-action-send/

But instead of just having an intent to open the app, we would have a contract to pass in the image URI(or the image itself) and the label as intent extras.

**Comment by yashshah7197** [comment]
Hey @nicolas-raoul I've filed a PR (#1292) which has implemented this. Turns out the app already had a functionality to receive images shared by other apps. I just had to add checks for a title and/or description if the app wants to send one along with it. I created a test app which verifies this functionality too so everything works as expected! 😄

**Comment by nicolas-raoul** [comment]
@yashshah7197 Cool!
Could you please post the test app to Github? For instance you can call it "Commons-Mobile-app-intent-client-sample". Thanks a lot :-)

**Comment by yashshah7197** [comment]
@nicolas-raoul sure! Here is the repo link - 
https://github.com/yashshah7197/commons-intent-client-sample

Just a note though that've I've written the sample app in Kotlin since I've been learning the language these days. 👻

**Comment by nicolas-raoul** [comment]
Thanks!
Would you mind transfering the repo to the https://github.com/commons-app
organization? You can request the transfer in the settings of your repo.
This way, it would be easy to find and maintain :-)
Cheers!

**Comment by yashshah7197** [comment]
Sure! But I think I need to transfer the ownership to you first since I don't have rights to create repos in the commons-app organization. I tried and it gave me an error saying that I don't have rights to create a repo. 😢

**Comment by nicolas-raoul** [comment]
OK can you please transfer to me? Thanks a lot! :-)

**Comment by nicolas-raoul** [comment]
Ah, could you please first add an open source license, by the way?
For instance this file:
https://github.com/commons-app/apps-android-commons/blob/master/COPYING or
another license if you prefer another one.

Your name will stay in the namespace, by the way :-)

**Comment by yashshah7197** [comment]
Done! I've added the license file and requested the ownership transfer to you. You just have to accept it now! 👻 😄

**Comment by nicolas-raoul** [comment]
The repo now lives at
https://github.com/commons-app/commons-intent-client-sample and you are a
collaborator (with write permission) to it :-)

**Comment by yashshah7197** [comment]
@nicolas-raoul great! 👻 Now just waiting for my PR to be merged haha! 🤣

**Comment by neslihanturan** [comment]
Since we have implemented the first steps for this feature, should we communicate with other open source apps to inform that it is possible to do? How they will know that if we don't tell them:)

**Comment by yashshah7197** [comment]
@neslihanturan how about we create a new Wiki page to document this feature? This way any app that wants to use this feature can look at the Wiki pages on how to implement it in their app. We can also then reach out to popular open source apps requesting them to implement this feature simply by just contacting them with the link of the documentation. We can also edit the Wiki page [here](https://github.com/commons-app/apps-android-commons/wiki/Code-Structure) but that doesn't really feel the right place to me.

Let me know if I can start writing the documentation and I'll write it right away! 😄

**Comment by nicolas-raoul** [comment]
@yashshah7197 Yes please create a Wiki page about this, thanks a lot! :-)

Let's start gathering ideas of apps where the user shares an image + a description.

Snapchat:
Image + description : yes
Relevance of the content: Low (Commons has enough selfies with dog ears)
Probability that they integrate us: About zero :-)
Screenshot:
![screenshot_20180315-150918](https://user-images.githubusercontent.com/99590/37447002-1ae8631a-2863-11e8-90f5-4cfb0f1933c3.png)

**Comment by yashshah7197** [comment]
@nicolas-raoul On it! I'll have it up by night! 👍

**Comment by yashshah7197** [comment]
@nicolas-raoul @neslihanturan I've written the wiki page and it can be found [here](https://github.com/commons-app/apps-android-commons/wiki/Passing-an-image-to-the-app). Please let me know if any changes are to be made! 👻

**Comment by nicolas-raoul** [comment]
@yashshah7197 Wonderful thanks! :-)
