### ISSUE TITLE
Error while gradle build

### ISSUE THREAD

**Issue by pprathameshmore** [commons-app/apps-android-commons#1274]
**Summary:** 

Error while gradle build syncing.

**Steps to reproduce:** 

How can we reproduce the issue?

**Add System logs:**

![sketch 1](https://user-images.githubusercontent.com/17108186/37215072-eeb976ec-23dc-11e8-8771-baad773f3995.png)

**Expected behavior:** 

Gradle must be sync without any errors

**Observed behavior:** 

I am forked this project and clone with locally. When open it first time, it showing 'Error:Execution failed for task ':app:mergeBetaDebugResources'.
> G:\GSoC2018\apps-android-commons\app\src\main\res\values-ko-kp: Error: Invalid resource directory name'

How can I fix this issue!

**Device and Android version:** 

Android Studio 3.0.1
 
@misaochan Please review this issue!

**Comment by default911** [comment]
I just took a clone and built succesfully.
Actually that's 'values-ko-rKP' in my clone. Try running after changing directory name to this.

**Comment by pprathameshmore** [comment]
@default911 Which name should I give to this directory?

**Comment by default911** [comment]
rename this directory to 'values-ko-rKP'. Or I would suggest you take git pull as I guess since I got no errors, this might have been fixed.

**Comment by pprathameshmore** [comment]
@default911 Is it valid directory name?

**Comment by maskaravivek** [comment]
@pprathameshmore Are you still facing this issue? Can you make sure that you have the lastest master.

**Comment by pprathameshmore** [comment]
@maskaravivek No, Now the project is working fine!
