### ISSUE TITLE
Set proper width of Navigation drawer

### ISSUE THREAD

**Issue by knight-shade** [commons-app/apps-android-commons#1275]
**Summary:** 

The width of navigation drawer in portrait mode seems to be more then appropriate and creates feeling of emptiness or like something is missing in navigation drawer. This is more prominent in landscape mode where navigation drawer covers 70% of screen and most of it is empty.

**Screen-shots:** 

## Observed
**Portrait**
![pb](https://user-images.githubusercontent.com/20313518/37244640-f6c624e0-24b1-11e8-91c3-b6f6e0f329e0.jpeg)

**Landscape**
![lb](https://user-images.githubusercontent.com/20313518/37244644-000365b8-24b2-11e8-9f11-b1ced4666415.jpeg)

## Excepted
**Portrait**
![pa](https://user-images.githubusercontent.com/20313518/37244646-0b56e228-24b2-11e8-8075-fc470fff6315.jpeg)

**Landscape**
![la](https://user-images.githubusercontent.com/20313518/37244648-16f37ea2-24b2-11e8-8548-e6625e41e695.jpeg)

What do you think? @maskaravivek @nicolas-raoul

**Comment by maskaravivek** [comment]
Looks good to me. If you want to pick it up, please go ahead with it. :)

**Comment by knight-shade** [comment]
Sure @maskaravivek  I will create PR  for this issue.
