### ISSUE TITLE
Share log intent shows extra clients in Settings page

### ISSUE THREAD

**Issue by gupta-meghna64** [commons-app/apps-android-commons#1282]
### Summary
Share intent in the Settings page while sharing the log file should should show only mail clients. 

### Steps to reproduce
1) Go to settings
2) Click on "Send Log via email"

### Expected behavior 
Clicking this should show only the mailing clients
 
### Device and Android version
Redmi Note 3
MIUI 6

### Commons app version 
Commons 2.6.7

### Screen-shots 
![whatsapp image 2018-03-11 at 2 48 14 pm 1](https://user-images.githubusercontent.com/20908024/37251780-4b8c687e-253c-11e8-9b3a-acd4da233500.jpeg)

**Comment by maskaravivek** [comment]
Sure @gupta-meghna64 feel free to pick this up. :)
