### ISSUE TITLE
Tutorial is not available in landscape mode

### ISSUE THREAD

**Issue by kamilya35231** [commons-app/apps-android-commons#1287]
I am new to OSS and was thinking about contributing to this project. I came across this issue while familiarizing with the app. I couldn't find it in already reported issues. Can someone check it and assign this issue to me if fix is needed? 

Summary: 
App crashes if tutorial is selected from the menu when device is in landscape mode

Steps to reproduce:
- Change orientation of the device to landscape mode
- Try to view the tutorial from the menu

Tutorial window should open, but app crashes

Device: Xiomi Redmi 4A 
Android Version:  7.1.2 
Commons app version: 2.6.7-debug-master 
 
![logs](https://user-images.githubusercontent.com/35804101/37257056-fcc867ea-258d-11e8-9dd8-98f25ad67bcc.png)

**Comment by knight-shade** [comment]
Yup @kamilya35231 the app is crashing. Actually I already had a PR ready for this, and was about to create the issue before you did. Thanks for create the issue :+1:

**Comment by madhurgupta10** [comment]
@knight-shade Could I fix it?

**Comment by knight-shade** [comment]
@madhurgupta10 I already create a PR for this 2 days ago.

**Comment by madhurgupta10** [comment]
@knight-shade ok no problem :)
