### ISSUE TITLE
can not go back from the "Categories" to the "Commons" by pressing the back arrow

### ISSUE THREAD

**Issue by dinaraassan** [commons-app/apps-android-commons#1289]
Hello Everyone, I am new to the open source software projects and I wanted to contribute as a tester. I downloaded the Wikimedia Commons (Beta)  app from the Play Store and tried to test it and found some strange behavior. 

Summary: 
I uploaded several pictures and during that I wanted to go back from the "Categories" to the "Commons" in order to make some modifications to the description of the picture. However by pressing the back arrow it does not go back from "Categories" to the "Commons" . It just go to the "Home", actually to "My Present Uploads" list where I saw my picture that was automatically uploaded. And now I can not change the description of that picture anymore.

Does it really works like that? Can anybody confirm this issue, please.    

Expected behavior: 
I just expected that after pressing back arrow it will go back to the "Commons" and will let me to make modifications in the title and description of the picture 

Steps to reproduce:
1. Dowload the (Beta) app from the Play Store
2. Try to upload picture from your gallery
3. Fill in the title and description in "Commons"
4.  go next
5. when the "Categories" open, go back by pressing the back arrow on the top left 

Device: Sony Xperia XA Ultra 
Android version: 7.0
 
Commons app version: Version 2.6.7
Screen-shots:
![photo5274241207406536806](https://user-images.githubusercontent.com/17812648/37258961-05700a9e-25aa-11e8-98fd-2d393b510cef.jpg)
![photo5274241207406536805](https://user-images.githubusercontent.com/17812648/37258964-189063da-25aa-11e8-91b8-7d74b77be5fe.jpg)
![photo5274241207406536807](https://user-images.githubusercontent.com/17812648/37258970-25e511b6-25aa-11e8-9608-1fea7a593cdb.jpg)

**Comment by nicolas-raoul** [comment]
I was thinking the exact same thing an hour ago after making a very misleading error in the title. Titles are hard to correct.
Unfortunately this is not really easy to solve because we start uploading as soon as we have the title+description, and modifying the title can only be done by a Commons admin, I believe.

This problem should hopefully be solved by Structured Commons, when captions are editable by anyone.

**Comment by domdomegg** [comment]
Fixed in #1968
