### ISSUE TITLE
Does not save the chosen categories of the picture and show up as "None provided"

### ISSUE THREAD

**Issue by dinaraassan** [commons-app/apps-android-commons#1290]
Summary:
Does not save the chosen categories of the picture and show up as "None provided"

Steps to reproduce:
1. Dowload the Wikimedia Commons (Beta) app from the Play Store
2. Try to upload picture from your gallery
3. Fill in the title and description in "Commons"
4. Mark the Category
5. press next 
6. open the uploaded picture from the "My Present Uploads" 
7. Look at the "Categories", there will be written "None selected"

Expected behavior : I expected that category that I chose will be saved and showed up at the picture's information. 

Observed behavior: Categories showed up as "None selected" even if I selected it.

Device: Sony Xperia XA Ultra
Android version: 7.0
 Commons app version: Version 2.6.7 

Screen-shots:

![photo5274241207406536809](https://user-images.githubusercontent.com/17812648/37259481-1c660e36-25b1-11e8-8e63-fa3d15ca675d.jpg)

![photo5274241207406536812](https://user-images.githubusercontent.com/17812648/37259484-2caa0158-25b1-11e8-8f09-169c4a948dc9.jpg)

![photo5274241207406536813](https://user-images.githubusercontent.com/17812648/37259490-39c9d304-25b1-11e8-8be2-2bff22c41c75.jpg)

**Comment by knight-shade** [comment]
@dinaraassan Its working fine for me, not facing the issue. Might have been due to internet connectivity since app fetches data regarding the uploaded image from server.

**Comment by misaochan** [comment]
Categories are not submitted along with the image, but rather as a modification to the uploaded image, because the upload has already begun after the first upload step. Hence, it takes a bit of time for categories to be sent to the Commons server and consequently fetched in media details view.

Could you please check again now and see if they have been added?

**Comment by dinaraassan** [comment]
Yeah, you were right, the category has been added.

**Comment by neslihanturan** [comment]
Then closing the issue:)
