### ISSUE TITLE
Share Commons picture (Android intent)

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#1291]
Users who browse their own pictures or other people's pictures may want to share a given picture via email or Facebook or Twitter etc.

The Share button could appear at the bottom of the media details activity.

I am not really sure how sharing works, but it could include the following:
- URL to the media
- License and author, for instance "Copyright PopoLeChien, license CC-BY-SA"
- The image itself

**Comment by Jatin0312** [comment]
I think this is a nice feature.
If you want I can work on this issue.
Thanks.

**Comment by Jatin0312** [comment]
Also I think there should be option to edit image before uploading mainly cropping the image.

**Comment by nicolas-raoul** [comment]
@Jatin0312  It's yours! :-)
Cropping is the subject of another issue: #1192

**Comment by Jatin0312** [comment]
Ok Thanks :)

**Comment by Jatin0312** [comment]
There is a share button already present which shares the link of the photo.
![issue1](https://user-images.githubusercontent.com/17095817/37384599-d3595bdc-2775-11e8-8389-da0b2f3bdcec.jpg)

Including one more share button will become redundant.
Am I getting confused with some other share button?

**Comment by nicolas-raoul** [comment]
Oh I am sorry I did not remember it was implemented already!
So sorry for wasting your time :-/
