### ISSUE TITLE
Navigation Drawer too large for landscape mode 

### ISSUE THREAD

**Issue by madhurgupta10** [commons-app/apps-android-commons#1295]
**Summary:** 
Navigation Drawer too large for landscape mode. Width needs to wrap up just the content.

**Steps to reproduce:** 

Swipe from the left

**Device and Android version:** 
Xiaomi Mi A1 Oreo 8.0

 **Commons app version:** 
2.6.7-debug-master~2516445d

**Screen-shots:** 
![screenshot_20180313-095342](https://user-images.githubusercontent.com/30932899/37322807-d84d1ea6-26a5-11e8-8a98-0e90ab81ce3c.png)

**Comment by knight-shade** [comment]
@madhurgupta10 Same as issue #1275. Already solved. :+1:

**Comment by madhurgupta10** [comment]
@knight-shade cool, glad it was fixed :)
