### ISSUE TITLE
Widget

### ISSUE THREAD

**Issue by madhurgupta10** [commons-app/apps-android-commons#1296]
**Summary:** 
It would be great if there is a widget that shows the picture of the day from [website](https://commons.wikimedia.org/wiki/Main_Page) [Edited by misaochan: pic of the day has been implemented, but a more full-featured widget would be awesome!]

![screenshot-commons wikimedia org-2018 03 13-10-20-18](https://user-images.githubusercontent.com/30932899/37323234-6c3c1db8-26a8-11e8-9d2a-9d73ec9633ad.png)

**Comment by nicolas-raoul** [comment]
By widget, do you mean the Android feature to add dynamic content on the wallpaper, a bit like the software below?
![live-image-widget-android-widget1](https://user-images.githubusercontent.com/99590/37326115-fd3d543c-26d3-11e8-962a-48ed649174a3.jpg)

**Comment by madhurgupta10** [comment]
@nicolas-raoul yes, kinda like that

**Comment by nicolas-raoul** [comment]
Good idea, feel free to implement it!

First, how do you plan to get the URL of today's picture?

**Comment by madhurgupta10** [comment]
@nicolas-raoul If there is an API available then I can use it or I can scrape the website to get the link.

**Comment by madhurgupta10** [comment]
@nicolas-raoul I can either use [jsoup](https://jsoup.org/) to get src from [here](https://commons.wikimedia.org/w/api.php?action=parse&format=jsonfm&formatversion=2&text=%5B%5BFile%3A%7B%7BPotd%2F%7B%7BCURRENTYEAR%7D%7D-%7B%7BCURRENTMONTH%7D%7D-%7B%7BCURRENTDAY2%7D%7D%7D%7D%5D%5D&prop=images%7Ctext&contentmodel=wikitext&format=json) or I approch [this](https://stackoverflow.com/questions/9084442/wikipedia-api-cannot-query-picture-of-the-day-url) way.

**Comment by maskaravivek** [comment]
The answer to the StackOverflow question seems to be a suitable approach to me.

**Comment by madhurgupta10** [comment]
@maskaravivek Sure, I am on it 👍

**Comment by Steinsplitter** [comment]
>>I can either use jsoup to get src from here or I approch this way.
There is a RRS feed (with i18n) which could be used: https://commons.wikimedia.org/w/api.php?action=featuredfeed&feed=potd&feedformat=rss&language=en

https://commons.wikimedia.org/wiki/Special:ApiSandbox#action=featuredfeed&format=json&feedformat=rss&feed=potd

**Comment by madhurgupta10** [comment]
@Steinsplitter nice find, and XML Seems fine to me.
@maskaravivek @nicolas-raoul Sir should I go with [this](https://commons.wikimedia.org/w/api.php?action=featuredfeed&feed=potd&feedformat=rss&language=en) or should I continue the other way. I think [this](https://commons.wikimedia.org/w/api.php?action=featuredfeed&feed=potd&feedformat=rss&language=en) is one is better as one request is better than two.

**Comment by nicolas-raoul** [comment]
@madhurgupta10 Yes Steinsplitter's solution is definitely the best :-)
RSS is XML so it should be easy to parse.

By the way, how about opening the image's description page in the browser when the widget is tapped?

**Comment by madhurgupta10** [comment]
@nicolas-raoul Sure, I am adding this feature 👍

**Comment by madhurgupta10** [comment]
@misaochan I will try to implement that too :)

**Comment by madhurgupta10** [comment]
@nicolas-raoul Please be ensured that I am still working on the issue. Sorry for the delay, I am having some college exams :sweat:

**Comment by maskaravivek** [comment]
@madhurgupta10 Any update on this? If you are still working on it please post a status update, or else someone else can pick this up. :)

Am really hoping for this feature to be part of the app!

**Comment by madhurgupta10** [comment]
Hi @maskaravivek , I am extremely sorry 😓 for not solving the issue on time. I got involved into so many things, I was not able to devote time to it.
I really want to solve this issue, please allow me one more chance, I will try my best to resolve it by this weekend :relaxed:

**Comment by nicolas-raoul** [comment]
@madhurgupta10 Would you mind posting a screenshot? Thanks a lot :-)

**Comment by misaochan** [comment]
Hi @madhurgupta10 , thanks for adding the widget. :) Are you planning to do future work on this? Having a wikipedia link for the pic of the day and buttons to upload directly from the widget would be great! For the uploads, I think there should be a button for camera and gallery, and please try and reuse the existing code as far as possible, as the permission checks etc are included in it.

**Comment by madhurgupta10** [comment]
Hi @misaochan, I will definitely add more features to it and sure I will try to reuse the code :)

**Comment by misaochan** [comment]
For the hackathon this year, I think it would be nice to work on creating a more full-featured widget so people can check the nearest place that needs photos, and upload photos for it without firing up the app.

**Comment by madhurgupta10** [comment]
@misaochan Sure, I think a separate Home Screen Widget would be better as android support multiple types of home screen widget. The Pic of the Day Widget was supposed to be used by people who want to discover new commons every day, but for power users, a new fully featured would be better.

**Comment by misaochan** [comment]
Hmm, interesting. I was thinking of just adding the other features on to pic of the day, since the nearest place won't take up more space than 1 row. But perhaps a separate widget would be cleaner indeed.

**Comment by misaochan** [comment]
Reopening as per discussion at #2862
