### ISSUE TITLE
Change SignupActivity to an Activity from a WebView

### ISSUE THREAD

**Issue by diddypod** [commons-app/apps-android-commons#1298]
**Summary:** 

SignupActivity is currently a WebView, which is inconsistent with the res of the application and allows users to browse MediaWiki in the WebView without logging in

**Expected** 

SignupActivity should be an Android Activity

**Observed behavior:** 

It is a WebView.

**Device and Android version:** 

Xiaomi (Wingtech) Redmi 2 Prime
Xiaomi Redmi Note 4 

 **Commons app version:** 

2.6.7-debug

**Comment by diddypod** [comment]
This can be easily implemented using JavaScript injection in a WebView. I'd like to take this up.

**Comment by madhurgupta10** [comment]
Please allow me to work on this :)

**Comment by Ketharan** [comment]
Considering the signup process when a user signing up the checking for whether the username exists in the system is done currently after pressing the signup button. It is difficult to going for new user name again and again while retyping the password and responding to recaptcha...... It will be better the user existence test is done during onchange trigger of the username field.

**Comment by misaochan** [comment]
@diddypod Sorry we didn't get back to you about this. Are you still interested in working on it?

**Comment by diddypod** [comment]
Yes, please. May I take it up?

**Comment by nicolas-raoul** [comment]
@diddypod Yes feel free :-)

**Comment by diddypod** [comment]
JavaScript injection is a rather hacky implementation. I'll try to make it somewhat better by using the MediaWiki APIs for account creation.

**Comment by diddypod** [comment]
Hello

Really sorry for the inactivity and the lack of updates, I've been having evaluations in college. I've been tinkering away in my free time, though, and while the bulk of the process is working, I'm having a bit of trouble retrieving and displaying the captcha via APIs. Any help or insights?

**Comment by misaochan** [comment]
Hi @diddypod , no worries. :) I am afraid that I can't offer any help with the captcha because that is exactly where I got stuck the last time I tried to implement this. :/ Perhaps someone else can chime in?

**Comment by diddypod** [comment]
Hello

Again, sorry for the delay. I've been working on this for the past couple of days and I have found these tools
- https://www.mediawiki.org/wiki/Extension:ConfirmEdit  which will let you generate captchas
- https://www.mediawiki.org/wiki/API:Account_creation  to create accounts

API:Account Creation needs a CAPTCHA to work, but I haven't been able to use the Extension using the APIs.

The alternative is to create an Android layout and use JavaScript injection as I said earlier which seems hacky and pointless, since it does not improve or simplify functionality, instead adding more complexity to the current webview implementation.

I'd like to stop working on this issue, and take up some other issues.

**Comment by misaochan** [comment]
@diddypod Thanks for the effort that you put into this. I am inclined to agree with you - as mentioned, I also tried to implement this a couple of years ago and ran into the same roadblocks. An additional concern is futureproofing - if we use the WebView, any changes that WMF makes to the signup process will automatically be incorporated, whereas with our own implementation we would need to keep on top of things ourselves.

Please feel free to work on other issues. Would you like me to close this?

**Comment by diddypod** [comment]
Thank you. Please close this :)
