### ISSUE TITLE
Replace New Image Upload with Floating Action Button (Material Design)

### ISSUE THREAD

**Issue by madhurgupta10** [commons-app/apps-android-commons#1305]
**Summary:** 

To add a new image it is always nice to have a floating action button (fab), which is easy to reach on devices with larger screen size.
It is also great to follow material design language for the app :)

**Screen-shots:** 

![image](https://user-images.githubusercontent.com/30932899/37358820-09e90418-2712-11e8-9675-bd6cf1830db6.png)

![image](https://user-images.githubusercontent.com/30932899/37358890-3e62ced6-2712-11e8-867b-302365a4813e.png)

**Comment by madhurgupta10** [comment]
I want to work on this issue :)

**Comment by neslihanturan** [comment]
Since we have a #725 , probably this should wait.

**Comment by madhurgupta10** [comment]
@neslihanturan Sure!

**Comment by misaochan** [comment]
This is already planned as part of #725 :)
