### ISSUE TITLE
In aboutActivity about_uploads_to textView has no functionality

### ISSUE THREAD

**Issue by tanvidadu** [commons-app/apps-android-commons#1306]
**Summary:** 
In aboutActivity there is TextView with id about_uploads_to which has no implementations in the code. It has not been used anywhere. 

**Expected Behavior:**
Link TextView with appropriate urls. If necessary add different links depending upon flavour.

Observed this in betaDebug , proddebug.

![aboutactivity](https://user-images.githubusercontent.com/29161745/37387247-aaa7ea8a-2781-11e8-9835-5c03fb10a9f2.jpeg)

**would u like to work on it ?**
Yes!

**Comment by neslihanturan** [comment]
Can you explain the summary more briefly? @tanvidadu

**Comment by tanvidadu** [comment]
@neslihanturan I have updated the summary. thanks :)

**Comment by blue-atom** [comment]
I would like to work on it

**Comment by neslihanturan** [comment]
It is already assigned to @tanvidadu , @blue-atom . If she decides to leave it, you can start to work on it.

**Comment by misaochan** [comment]
Sorry, I'm a bit confused, what is the rationale for adding the "Upload" link to the browser-based Upload Wizard? Presumably the user is already on a mobile phone since they are in our app, and the Upload Wizard does not work on mobile.

**Comment by tanvidadu** [comment]
Sorry! I didn't consider it from this angle. 
I will modify my pr to remove the extra textView in about activity.
Thanks :)

**Comment by misaochan** [comment]
Thanks! :)
