### ISSUE TITLE
Extra space being displayed in Nearby info dialog.

### ISSUE THREAD

**Issue by Jatin0312** [commons-app/apps-android-commons#1310]
**Summary:** 
1. I think there is quite a space being displayed in nearby info dialog.
2. Colour of dialog sheet can be changed so that it can be distinguished from the list.
3. I think animation can be added when an item is clicked on the list.

**Steps to reproduce:** 
Go to Nearby Activity and click on list mode type and click on item.

**Device and Android version:** 
Moto g4 plus
Android 7.0.0
 
 **Commons app version:** 
2.6.7

**Screen-shots:** 
![whatsapp image 2018-03-14 at 11 12 58 pm](https://user-images.githubusercontent.com/17095817/37421961-5e992fd2-27e0-11e8-8968-2391a471ec90.jpeg)

**Would you like to work on the issue?**
Yes, I would like to work on this issue.

**Comment by neslihanturan** [comment]
@Jatin0312 please don't work on nearby related issues since we are changing nearby classes at all.

**Comment by Jatin0312** [comment]
Ok sure :)
