### ISSUE TITLE
instagram profil picture full size invalid url signature

### ISSUE THREAD

**Issue by yassbra** [commons-app/apps-android-commons#1311]
_
a few days ago I was able to fetch inta profile pic in my android app by removing the part from vp/ to /t51 {vp/...}/t51.. from the pic URL

https://scontent-mrs1-1.cdninstagram.com/vp/xxxxxxxx/t51....jpg

but it doesn't work !!

and change the resolution from s150x150 to s720x720, and it worked fine but now i still get "invalid url signature", so I think Instagram has added signature to their URL

I don't know what's happened with Instagram, so can someone help me to find a solution for this problem? Or an alternate method. Thanks

**Comment by nicolas-raoul** [comment]
Please ask on StackOverflow.
Cheers!
