### ISSUE TITLE
Dividing nav bar into sections.

### ISSUE THREAD

**Issue by Jatin0312** [commons-app/apps-android-commons#1317]
**Summary:** 

1. We can divide navbar into section as it would look better than the existing nav bar.

**Expected behavior:** 

![navbar2](https://user-images.githubusercontent.com/17095817/37507407-57448cf6-2914-11e8-919b-bd31e2d9ec2e.jpeg)

It's just a sample from fasthub application.

**Observed behavior:** 

![navbar](https://user-images.githubusercontent.com/17095817/37507520-e1bf9222-2914-11e8-9d88-e48c1e1d344c.jpeg)

**Device and Android version:** 

Moto g4 plus
Android 7.0.0
 
 **Commons app version:** 

2.6.7

**Would you like to work on the issue?**

Yes, I would like to work on this issue.

**Comment by nicolas-raoul** [comment]
What sections do you suggest?

**Comment by Jatin0312** [comment]
We can divide section into 3 parts
1. First section containing Home
2. Second section containing Nearby, Notification and Tutorial
3. Third section containing About, Settings, Feedback and logout

These are just suggestions we can change it accordingly.

**Comment by madhurgupta10** [comment]
@Jatin0312 I don't think it is required, the navigation bar looks good.

**Comment by misaochan** [comment]
How do you plan on organizing the current nav bar?

I am open to this if the organization makes sense. :) We should probably ask @neslihanturan though.

**Comment by neslihanturan** [comment]
I think organization is a good idea since we have several items. But I don't think suggested organisation is a good idea. My suggestion is:

- Our main features are home and nearby. 
- Account or app related things are notifications, settings and logout (Logout should be at the end of everything)
- Information and communication with developers things about, tutorial and feedback

**Comment by Jatin0312** [comment]
I think @neslihanturan organization suggestion given by you is really nice :)
Just in case for Logout we can create separate section since it should be kept at last.

**Comment by Jatin0312** [comment]
It would look something like this:

**Screenshots**
![nav5](https://user-images.githubusercontent.com/17095817/37516031-dd777a9a-2932-11e8-88b5-9cf4c5a19e84.jpeg)

**Comment by Jatin0312** [comment]
Hi @neslihanturan if this organisation is Ok should I create a PR for this.
Thanks :)

**Comment by neslihanturan** [comment]
Sorry, I missed this one somehow :( Waiting for your PR @Jatin0312
