### ISSUE TITLE
Direct nearby uploads fab buttons visibility problem

### ISSUE THREAD

**Issue by neslihanturan** [commons-app/apps-android-commons#1322]
**Summary:** 
On Direct Nearby Uploads New branch visibilities of FABs are problematic. 

**Steps to reproduce:** 

Get the code in directNearbyUploadsNew branch. 
- Go Nearby Activity. 
- Select a marker. 
- Click to plus fab
- Press back button until bottom sheet is hidden.
- You will see FABs on left upper corner for a moment.*
- If you try to click around naw draver icon FABs will appear again with their actions (Yes this happens :))

**Expected behavior:** 
- FABs shouldn't displayed on left corner for a moment
- FABs should stay hidden even if we touch on their position

**Observed behavior:** 
- FABs on the corner

**Device and Android version:** 
API 19

**Screen-shots:** 
![test](https://user-images.githubusercontent.com/3127881/37536982-39f961fa-295d-11e8-820e-3d76f681a9ee.gif)

**Would you like to work on the issue?**
I already did, twice... 
Firstly I learned I have to remove anchors to be able to hide FABs. We already do this in current code:
```
    private void hideFAB() {
        //get rid of anchors
        //Somehow this was the only way https://stackoverflow.com/questions/32732932/floatingactionbutton-visible-for-sometime-even-if-visibility-is-set-to-gone
        CoordinatorLayout.LayoutParams p = (CoordinatorLayout.LayoutParams) fabPlus
                .getLayoutParams();
        p.setAnchorId(View.NO_ID);
        fabPlus.setLayoutParams(p);
        fabPlus.hide();
        fabCamera.hide();
        fabGallery.hide();
    }

    private void showFAB() {
        CoordinatorLayout.LayoutParams p = (CoordinatorLayout.LayoutParams) fabPlus.getLayoutParams();
        p.setAnchorId(getActivity().findViewById(R.id.bottom_sheet_details).getId());
        fabPlus.setLayoutParams(p);
        fabPlus.show();
    }
```

There is similar complaints on the comments under this issue: https://stackoverflow.com/questions/31269958/floatingactionbutton-doesnt-hide 
However I couldn't find a solution yet. 
- Does anyone experienced this before?
- Do you able to reproduce this after lollipop?

**Comment by Jatin0312** [comment]
While I was adding recenter button I also faced problem in which fab button was not getting displayed in Android version 19.
I resolved it by adding fab button below linear layout in the relative layout.
I would like to work on this issue and see if I can resolve it.
Thanks :)

**Comment by neslihanturan** [comment]
Actually they are visible, our problem is a little different. But still I will be appreciated if you find a solution. However, I suggest not to assign this task to nobody (so that everyone can try to find a solution simultaneously) since it needs to be solved as soon as possible.

**Comment by Jatin0312** [comment]
Sure @neslihanturan it would be better not assigning to anyone since everyone can try :)

**Comment by neslihanturan** [comment]
- Checking visibility in action listeners solved wrong actions + 
- Currently working on being displayed very short moment before getting hidden

Then this issue will be done.

**Comment by wailbabou** [comment]
i was working on it , and i got this errors 
[issue](https://github.com/commons-app/apps-android-commons/issues/1339)

**Comment by neslihanturan** [comment]
Actually if you look at the referenced PR, you will see this issue is solved already.
