### ISSUE TITLE
Feedback navigation drawer

### ISSUE THREAD

**Issue by devaar100** [commons-app/apps-android-commons#1331]
**Summary:** 
The feedback should only show mail apps 

**Observed behavior:** 
All apps with messaging ability are listed and on selecting non-mail ones error is shown

**Comments:** 
Its a petty issue but i thought i should mention it

**Would you like to work on the issue?**
I would like to work on this

**Comment by gupta-meghna64** [comment]
Hi @devaar100 this issue is similar to #1203 and has already been worked upon :-)

**Comment by nicolas-raoul** [comment]
So I guess this can be closed?
@devaar100 feel free to reopen if you find something not covered yet, thanks :-)
