### ISSUE TITLE
"about rate us" message is empty

### ISSUE THREAD

**Issue by amire80** [commons-app/apps-android-commons#1333]
**Summary:** 

The message "Commons-android-strings-about rate us" is empty:
https://translatewiki.net/w/i.php?title=Special:Translations&message=Wikimedia%3ACommons-android-strings-about+rate+us%2Fhe

It should probably deleted, fixed, or ignored.

**Steps to reproduce:** 

See translatewiki.

**Expected behavior:** 

There must be no translatable messages in translatewiki that are empty strings.

**Comment by liuxinyu970226** [comment]
[Commons-android-strings-about translate](https://translatewiki.net/wiki/Wikimedia:Commons-android-strings-about_translate/en) too

**Comment by ArkadiyVoronov** [comment]
Can I deal with this issue?

**Comment by misaochan** [comment]
@ArkadiyVoronov it is yours. :)

**Comment by liuxinyu970226** [comment]
Found new one: [Commons-android-strings-nominated see more](https://translatewiki.net/wiki/Wikimedia:Commons-android-strings-nominated_see_more/en)

**Comment by liuxinyu970226** [comment]
Another one [Commons-android-strings-welcome help button text/zh-hans](https://translatewiki.net/w/i.php?title=Special:Translations&message=Wikimedia%3ACommons-android-strings-welcome+help+button+text%2Fzh-hans)

**Comment by liuxinyu970226** [comment]
@ArkadiyVoronov Commons-android-strings-nominated see more and Commons-android-strings-welcome help button text are still not fixed, please fix both!

**Comment by ArkadiyVoronov** [comment]
Hello! I will try to fix it

**Comment by ArkadiyVoronov** [comment]
Hello! I will try to fix it

**Comment by maskaravivek** [comment]
Thanks, @ArkadiyVoronov for picking this up. :)

**Comment by arshadkazmi42** [comment]
I can take this up if its still available. What exactly needs to be done here?

**Comment by maskaravivek** [comment]
There have been no updates from @ArkadiyVoronov for over a month. So @arshadkazmi42 please feel free to take this up. :)

**Comment by arshadkazmi42** [comment]
@maskaravivek I am new to this project, just wanted to understand what exactly needs to be done here?

**Comment by arshadkazmi42** [comment]
@misaochan Thanks for the detailed explanation I will look into it later today

**Comment by noloman** [comment]
hi! is anyone looking into this issue? @arshadkazmi42 are you going to check it out?

**Comment by arshadkazmi42** [comment]
@noloman  
I think this was taken care at #1772 

@Mansi449 was working on that issue.

**Comment by misaochan** [comment]
Yes this seems to have been fixed, thanks! :)
