### ISSUE TITLE
Refactor variable names of nearby_query.rq

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#1334]
**(Please don't work on this before June 2018, as the file is currently being worked on)**

Right now we have a mix of snake_case and camelCase at app/src/main/resources/queries/nearby_query.rq

Please note that refactoring must also be done in the Java source code, and tested.

**Comment by madhurgupta10** [comment]
@nicolas-raoul I can do this by the weekend, I am about to solve the previous issues that I was working on :)

**Comment by Ksaboor** [comment]
is this issue still open??? I would like to take it :)

**Comment by nicolas-raoul** [comment]
@Ksaboor  Yes, thanks! Please test it after refactoring.

**Comment by Ksaboor** [comment]
@nicolas-raoul
Had some technical difficulties on my end. But I finally got the project open.
For clarity I just want to make sure I'm doing this correctly.

* I am going into the nearby_query.rq and making changes to the variables names
* Making them either all snake_case or camelCase.
* While also going into the Java source code, refactoring them as well, and making all test pass.

I'm guess that problem I'm having is 
*  it looks like most of this file (nearby_query.rq) is in snake_case.
* and I am not sure where to look in the java source code to test.

Idk I just might be out of scope to get this done. most of my experience is in Java 8/ Spring Boot

**Comment by domdomegg** [comment]
Hi @Ksaboor.

It might be best to have a read through the developer documentation on the [wiki](https://github.com/commons-app/apps-android-commons/wiki#developer-documentation)

Also here is some information about Wikidata's SPARQL query service.
https://www.wikidata.org/wiki/Wikidata:SPARQL_query_service/Wikidata_Query_Help

However, if you think this is too much to start with have a look around at the [other beginner friendly issues](https://github.com/commons-app/apps-android-commons/labels/beginner%20friendly) :)

**Comment by FelixEder** [comment]
@Ksaboor Are you still working on this issue? Otherwise I would love to work on it :)

**Comment by Ksaboor** [comment]
@FelixEder I'm finished working with it. It's all yours to complete.

**Comment by FelixEder** [comment]
@Ksaboor Currently working on issue #395. If I have more time afterwards I'll try to work on this :)

**Comment by VitalyVPinchuk** [comment]
Hi!
Could I try to work on the issue?
But I'm new to android.

**Comment by nicolas-raoul** [comment]
@VitalyVPinchuk Are you done any programming with Java (or a similar language) before? :-)

**Comment by VitalyVPinchuk** [comment]
@nicolas-raoul Yes. Long time ago I had experience with C++ using MFC. And I've looked through "Advanced Android App Development" by Google at Udacity recently. So now seeking the opportunity to get my hands dirty.

**Comment by nicolas-raoul** [comment]
@VitalyVPinchuk  Cool!
This issue is yours :-)
Please be sure to:
- Before: Use the feature to understand how it works
- After your refactoring: Test to see whether it still works as intended.

Please report here about your progress every two days at least, thanks!
