### ISSUE TITLE
Improve our new feature "delete nomination"

### ISSUE THREAD

**Issue by neslihanturan** [commons-app/apps-android-commons#1335]
**Summary:** 
We have added nomination for deletion option after @diddypod 's contribution  #1297. Now there can be some improvments before release:
- Firstly the button can have a better UI
- User shouldn't be able to click delete button second time. Maybe disabling the button is a better option rather than displaying an alert after nomination message it accepted.

Other improvement ideas are welcome

**Steps to reproduce:** 

Go to media details activity and last red button.

**Comment by diddypod** [comment]
I'd like to finish this up. Is that okay, @neslihanturan?

**Comment by neslihanturan** [comment]
Assigned to you @diddypod , thanks!

**Comment by diddypod** [comment]
We can also display the ongoing deletion process, as @neslihanturan suggested. Some ways to do that would be
- an alert with a progress bar and the exact status of the deletion process
- a series of Toasts, as each part of the tasks is completed
- an notification with a progress bar and status of the deletion of the process

I prefer the first one.

**Comment by neslihanturan** [comment]
I really couldn't decide yet @diddypod , we really wouldn't want to block the user if we can work on background. But if we do so (what the PR does currently), everything become confusing according to my tests. 

My suggestion is such a flow:
- Displaying "nominate deletion" button as is
- When user clicked on that button, displaying a toast "your request taken" (with better english)
- Putting a progress bar next to "nominate deletion" button when button is disabled visually and functionally. 
- When the process is done displaying "succesfull nomination" toast 
- Then removing button and progress bar and displaying "This image is already nominated" view instead.

Since we sill indicate current nomination status with buttons and progress bar, we don't have to use alerts. Only toasts would work in this case I think. 

Besides user can go back to Contributions Activity without waiting nomination process, when she somes back, will see "progress bar" or "already nominated" view.

How is that sound to you @diddypod @maskaravivek?

**Comment by diddypod** [comment]
That seems fine, but the view with the progress-bar won't persist once the user goes to the ContributionsActivity and returns. I feel that using a notification to display progress is a better idea, if alerts block the workflow.

Using notifications-
- Visually and fuctionally dislable button on click
- Toast saying "Attempting to nominage "Image.jpg" for deletion
- Notification with a progress bar and exact status of nomination process ("Adding file to delete requests log" etc)
- Toast saying "Successfully nominated" of "Failed to nominate", and update the notification accordingly
- Replace button with "Image is already nominated" text

This won't interfere with the workflow of the user and give complete and persistent status of the process.

@neslihanturan, @maskaravivek is this acceptable?

**Comment by neslihanturan** [comment]
Yes, notifications are also a good option @diddypod

**Comment by diddypod** [comment]
I'll implement and push shortly, then.
