### ISSUE TITLE
Search button Contribution Fragment List

### ISSUE THREAD

**Issue by devaar100** [commons-app/apps-android-commons#1336]
**Summary:** 
Adding search facility for Contributions Fragment List

**Expected behavior:** 
Quick fetching desired contribution

**Observed behavior:** 
Scrolling through all contributions made till date

**Would you like to work on the issue?**
I would like to work on this

**Comment by neslihanturan** [comment]
Can you explain it more specifically @devaar100 ? 
- Search by what (title, category, date)?
- Do you have any mockups in your mind?
- How will we desire contributions? Do we have an input field?

Please re-edit your first post included more details, current status doesn't too much anything to me:/

**Comment by devaar100** [comment]
@neslihanturan 
Searching via title 
I was wondering if an expandable search bar button can be included in toolbar which on click expands to take input
The titles with the input as subsequence can then be filtered and shown in the contributions fragment list

**Comment by knight-shade** [comment]
@devaar This might vary from person to person, but how many pictures names do we remember exactly ? I have uploaded around just 10 images during development and hardly remember any names, but hey that's just me. :smile:

**Comment by devaar100** [comment]
@knight-shade the picture will be retrieved based on input being a substring so no need to remember full names 🙂

**Comment by neslihanturan** [comment]
@devaar100 I also never needed to search among my contributions. Let's ask if this is needed to our frequent contributors. Did you ever need such a feature @nicolas-raoul and @VojtechDostal ?

**Comment by VojtechDostal** [comment]
I don't consider myself a very prolific contributor but I've uploaded a few hundred pics and needed to search for them once or twice. And even then I wouldn't want to search them on my phone because I'd use the file name for some downstream applications which are not mobile friendly.

So in this case I'd be against complicating our app, keeping it lightweight and free of unneeded functions.

**Comment by neslihanturan** [comment]
Since general attitude is keeping our app simle, closing this issue. You can re-open it whenever you want
