### ISSUE TITLE
Nearby Activity Floating Action buttons  

### ISSUE THREAD

**Issue by wailbabou** [commons-app/apps-android-commons#1339]
**Summary:** 
1 ) I'm using **directNearbyUploadsNew** branch
By going to NearbyActivity i got the application stopped message 
it said :

`Attempt to invoke virtual method 'android.graphics.drawable.Drawable android.graphics.drawable.Drawable$ConstantState.newDrawable()' on a null object reference`

2 ) also after fixing that , and by choosing a marker from the map
there no icons inside [fab_galery,fab_camera]

**Steps to reproduce:** 
- Enter to NearbyActivity
- The app will crash 

**System logs:**
`Attempt to invoke virtual method 'android.graphics.drawable.Drawable android.graphics.drawable.Drawable$ConstantState.newDrawable()' on a null object reference`

**Device and Android version:** 
Galaxy note 3 : android 5 [ sdk 21 ]
 
 **Commons app version:** 
2.6.7-debug-directNearbyUploadsNews ~1e83d67c
**Screen-shots:** 
![29134732_2105593989468876_763814720_n](https://user-images.githubusercontent.com/17969012/37646457-0a7e2788-2c2a-11e8-8e6a-8fa4d258bba1.png)

**Would you like to work on the issue?**

1 ) i worked on it , and after searching i find that this error is because : 
because of `android:backgroundTint="@color/button_blue"`
which should be `app:backgroundTint="@color/button_blue"`
2) and the second one . i solved it by adding  `android:src="....."` too , but in 4.4 and below Android versions it causes a crash. so i changed the Vector Drawable to a png and it work

**Comment by neslihanturan** [comment]
Is it happening on emulator? If it crashes on activity start how did you managed to get screen shoots?

**Comment by wailbabou** [comment]
@neslihanturan  no , with real device 
and the screenshot is for the second issues ( because after changing `android` with `app` ) 
the app was working but there is no icons ( because of vector drawable )

**Comment by neslihanturan** [comment]
Plus, there are icons in the buttons but since you set button background to same color, they are not distinguishable I guess:) 

Because background of these buttons should be white.

Can you try your changes on a pre-lollipop emulaor? The reason for android:backgroundTint="@color/button_blue" was prelollipop devices.

**Comment by neslihanturan** [comment]
Also, it is great someone is testing our new branch since there can be several bugs waiting to be discovered. Thanks for your interest @wailbabou :)

**Comment by wailbabou** [comment]
<img width="336" alt="screen shot 2018-03-20 at 11 11 31 am" src="https://user-images.githubusercontent.com/17969012/37648513-7c42692e-2c2f-11e8-9636-82eb327bd757.png">
without [ android:backgroundTint=""]
by the way [ android:backgroundTint ] was used only with [fab_list] FAB , but the others use [app:backgroundTint]

**Comment by neslihanturan** [comment]
Can you explain your last screen shot more briefly please?

**Comment by wailbabou** [comment]
Just i used an emulator with pre-lollipop version , where i used  [app:backgroundTint] instead of  [android:backgroundTint] and it worked fine 

and when i put it back [ android:backgroundTint ]
i get this error : 
<img width="986" alt="screen shot 2018-03-20 at 11 27 01 am" src="https://user-images.githubusercontent.com/17969012/37649318-ac606e74-2c31-11e8-8cc9-42b5c33f4bd4.png">

____
and about the icon color , you are right , it wasn't a problem

**Comment by neslihanturan** [comment]
Can you please push your changes on a PR so that I can also test on a physical pre-lollipop device

**Comment by wailbabou** [comment]
done
