### ISSUE TITLE
Progressbar not visible 

### ISSUE THREAD

**Issue by 97balakrishnan** [commons-app/apps-android-commons#1345]
**Summary:** 

The progressbar while loading activities is not visible in some devices

**Steps to reproduce:** 

I opened nearby activity, I couldn't see the progressbar spinning in my phone.

**Screencast**
![link](https://media.giphy.com/media/8YyZVfjwyBAEHIiOo4/giphy.gif)

**Device and Android version:** 
Android 6.1

**Commons app version:** 

2.6.7-debug-master

**Comment by neslihanturan** [comment]
@97balakrishnan  please leave NearbyRelated tasks for now since we are changing whole Nearby classes currently.
