### ISSUE TITLE
Whole page map issue

### ISSUE THREAD

**Issue by neslihanturan** [commons-app/apps-android-commons#1354]
**Summary:** 
Map view adjusts to whole page. This happened after dNUnew branch is merged to master or re-center button is added.

**Steps to reproduce:** 
Open nearby activity

**Expected behavior:** 

![device-2018-03-22-143845](https://user-images.githubusercontent.com/3127881/37780832-9e7ad22e-2e00-11e8-8e23-5bffc8c6ea33.png)

**Observed behavior:** 

![device-2018-03-22-143532](https://user-images.githubusercontent.com/3127881/37780851-a598e4c4-2e00-11e8-91b0-f2d1fb51d68c.png)

**Device and Android version:** 
API level 19
 
 **Commons app version:** 

master

**Would you like to work on the issue?**
no

**Comment by neslihanturan** [comment]
@97balakrishnan seems like whole page map issue is related with master, not with your branch:)

**Comment by 97balakrishnan** [comment]
Oh thank you for letting me know @neslihanturan :)

**Comment by wailbabou** [comment]
Can i work on this ?
