### ISSUE TITLE
Circle Page indicator not visible correctly in Welcome Activity.

### ISSUE THREAD

**Issue by Jatin0312** [commons-app/apps-android-commons#1358]
**Summary:** 

Part of circle  page indicator in WelcomeActivity getting overlaped with view pager.

**Steps to reproduce:** 

Before first time login or from navigation drawer click on tutorial.

**Expected behavior:** 
![expected](https://user-images.githubusercontent.com/17095817/37852710-a304487a-2f09-11e8-94fc-fd0077c2335e.png)

**Observed behavior:** 
![observed](https://user-images.githubusercontent.com/17095817/37852721-a9d4b806-2f09-11e8-8909-ee10618e6765.png)

**Device and Android version:** 

Moto g4 plus Android 7.0.0
 
 **Commons app version:** 
2.6.7

**Would you like to work on the issue?**
Yes, I would like to work on this issue.

**Comment by misaochan** [comment]
Oh, wow, I never noticed that. Yes, please feel free! :)

**Comment by Jatin0312** [comment]
Ok sure I will create the PR :)

**Comment by neslihanturan** [comment]
How did you recognized this @Jatin0312 :D

**Comment by Jatin0312** [comment]
Was just checking App intro and got to see this luckily :)
