### ISSUE TITLE
Nearby places refresh issue

### ISSUE THREAD

**Issue by devaar100** [commons-app/apps-android-commons#1361]
**Summary:** 
There is an issue with manual refresh on nearby places activity

**Steps to reproduce:** 
1. Open nearby places from navigation drawer
2. Now open some other app from task manager
3. Turn off the internet
4. Open wikimedia app again
5. The list of places disappears 
6. Turn on the internet
7. Press refresh, a toast appears stating location has not changed and no refresh takes place

**Expected behavior:** 
A refresh should start

**Observed behavior:** 
No refresh and toast saying location has not changed

**Would you like to work on the issue?**
Yes I would like to work on it

**Comment by misaochan** [comment]
Please feel free to work on this, @devaar100 . :)

**Comment by neslihanturan** [comment]
Does it continues @devaar100 ?

**Comment by devaar100** [comment]
@neslihanturan sorry sir I didn't get you
Would you mind elaborating for my convenience

**Comment by neslihanturan** [comment]
Sorry, I meant does this problem still exist?

**Comment by devaar100** [comment]
@neslihanturan I fixed the issue and submitted a PR for the same :)
