### ISSUE TITLE
Place marker text screen overflow

### ISSUE THREAD

**Issue by devaar100** [commons-app/apps-android-commons#1362]
**Summary:** 
The place marker title on map seems to overflow for some place with large names

**Screen-shots:** 
![screenshot_2018-03-24-17-54-52-866_fr free nrw commons](https://user-images.githubusercontent.com/29582559/37864000-35f52544-2f8e-11e8-9040-fefdc1fae4f2.png)

**Would you like to work on the issue?**
Yes

**Comment by misaochan** [comment]
Hi, sorry for the slow response, but we have recently released a new version of Nearby with an entirely different UI. So this won't be an issue in the new UI.
