### ISSUE TITLE
Leaks needs to be solved before release

### ISSUE THREAD

**Issue by neslihanturan** [commons-app/apps-android-commons#1368]
**Summary:** 

Here are leak reports needs to be solved before release (means this week)

**Steps to reproduce:** 

Play with app, in general.

**Add System logs:**

![leaks](https://user-images.githubusercontent.com/3127881/37893044-81d866a6-30e2-11e8-9651-415d26e45ffd.png)

This issue can be solved by several people. Please use comments efficiently to assign it yourselves by using letters (A/B/C/D/E/F). 

Besides, this issue needs to be done in a week so help is appreciated :)

**Comment by yashshah7197** [comment]
I'll kick things off by taking up the the 'A' leak. I can try to fix all of them too if that's okay. 👍 @nicolas-raoul @neslihanturan

**Comment by neslihanturan** [comment]
Firstly you can start with 'A', since this issue is urgent and requires parallel working. If you are done with 'A' don't hesitate to get another one, after you wrote comment here @yashshah7197

**Comment by misaochan** [comment]
Thanks for volunteering to do "A", @yashshah7197 . :) If anyone else would like to take the others, please feel free to mention it here.

**Comment by yashshah7197** [comment]
@neslihanturan can you tell me how I could reproduce these leaks? LeakCanary doesn't seem to be detecting anything for me yet.

On a side note, sorry for the late updates. I'm down with a bit of fever and cough so can't really work on anything properly right now. 🙈

**Comment by neslihanturan** [comment]
@yashshah7197 just playing with app, I don't know either.

**Comment by neslihanturan** [comment]
I am working on B and C

**Comment by neslihanturan** [comment]
@yashshah7197 this issues needs to be done today, will you be able to make it up? If not I will give a try.

**Comment by neslihanturan** [comment]
It seems like E and F is something we can ignore: https://medium.com/@amitshekhar/android-memory-leaks-inputmethodmanager-solved-a6f2fe1d1348

**Comment by misaochan** [comment]
Closing, we can create a new issue if there are further leaks. :)
