### ISSUE TITLE
Fix Travis build failures due to Nearby tests

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#1371]
**Summary:** 

Travis has been failing ever since our Nearby overhaul, specifically due to Nearby tests failing. I would propose two steps to fix this problem:

1. First, temporarily remove all Nearby tests. This allows us to actually use Travis again for PR and build evaluation, instead of just assuming it will fail.

2. Then, re-create Nearby tests one by one.  Nearby has changed so significantly that I imagine we will need to rewrite the majority of the tests.

**Steps to reproduce:** 

Look at Travis builds and Nearby tests

**Would you like to work on the issue?**

Ideally, no :) Anyone, please feel free to take it up.

**Comment by yashshah7197** [comment]
I'd like to have a shot at this. I'll probably get to learn how to write tests properly too. 👍

**Comment by misaochan** [comment]
@yashshah7197 I think you currently already have an assigned task (memory leak A)? But feel free to ping me after that has been completed and I will assign this to you then. :)

**Comment by ujjwalagrawal17** [comment]
Can I work on this?

**Comment by ujjwalagrawal17** [comment]
I had completed step 1. Starting working on step 2 now.

**Comment by ujjwalagrawal17** [comment]
2nd part is left in this issue can we reopen it?

**Comment by misaochan** [comment]
@ujjwalagrawal17 it is yours. :)

**Comment by ujjwalagrawal17** [comment]
@misaochan yup I will complete it soon.
