### ISSUE TITLE
Fix whitespace and padding for Notifications

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#1380]
**Summary:** 

Notifications activity needs a bit of aesthetic improvement.

**Steps to reproduce:** 

Go to Notifications in nav drawer

**Expected behavior:** 

Whitespace needs to be stripped from the start of some types of notifications (although to simplify things we can probably strip from the start of all messages). 

Also, this may be personal preference, but I think we could increase the padding a bit to make it look less cluttered.

**Observed behavior:** 

![notifications_whitespace](https://user-images.githubusercontent.com/3611199/37984040-83ebc558-3238-11e8-97af-b95897d5c0a7.png)

**Device and Android version:** 

Nexus S API 25
 
 **Commons app version:** 

2.6.7

**Would you like to work on the issue?**

Ideally not, please feel free. ;)

**Comment by Jatin0312** [comment]
I would like to work on this issue. :)

**Comment by misaochan** [comment]
@Jatin0312 go for it. :)
