### ISSUE TITLE
Kotlin for the tests

### ISSUE THREAD

**Issue by psh** [commons-app/apps-android-commons#1389]
**Summary:**

It has been our stated strategy that we would evaluate the use of Kotlin by using it for writing tests.

**Expected behavior:** 

New tests would be written using Kotlin & our test coverage would increase.

**Observed behavior:** 

1. Very few tests seem to be created, whether Java or Kotlin.
2. We leave the CI build broken & don't actively maintain the test suite
3. We don't utilize Kotlin (cf #1371 - we could have / should have offered guidance that New tests be in Kotlin for the Nearby failures)

**Device and Android version:** 

One thing to note: we should update the version of Kotlin in our project.

**Would you like to work on the issue?**

I would be happy to Port the _entire_ suite to Kotlin, for sure, including new ones for Nearby **but** this needs to be a team buy-in ... are we "in" or "out" of the Kotlin game?  If we are "in" is there a more effective strategy for adoption?

**Comment by psh** [comment]
I ran across a blog post from Brian Button (an Agile leader based in the St Louis area) that talks about "Three Degrees of Unit Testing" that might be interesting to the current topic.

https://blog.brianbutton.io/index.php/2018/04/01/the-degrees-of-unit-testing/

I love his comment 

> Any amount of unit testing, done almost any way, adds value to a code base. Regardless of how and when the tests were written, as long as they are reliable and quick, and prove the code does what we think it does, I’m in favor of them.

**Comment by domdomegg** [comment]
Tests are now done in Kotlin, builds are passing, coverage is increasing and there's a nice CI pipeline to alpha releases. Thanks to everyone who helped with this :tada: :champagne:
