### ISSUE TITLE
Map orientation button gets overlapped by recenter button

### ISSUE THREAD

**Issue by 97balakrishnan** [commons-app/apps-android-commons#1395]
The directions symbol appears when the map is zoomed in or rotated , that symbol is overlapped by the recenter button.

![alt link](https://preview.ibb.co/b7zUx7/Screenshot_20180331_210950.png)

**Expected behavior:** 

The directions symbol not appearing at all or the recenter button has to be moved down

**Device and Android version:** 
Android 6.0.1

**Comment by misaochan** [comment]
Just to clarify, @97balakrishnan has mentioned that:

> It remains there even if i select the pin and expand. Note: I got the directions symbol only after i zoomed the map. It was not initially present.

@97balakrishnan could you please clarify if you are ever able to select a pin and view the bottom sheet? If you are, could you post a screenshot of how the bottom sheet looks like now?

Also, what device are you using?

Thanks!

**Comment by 97balakrishnan** [comment]
![alt link](http://i67.tinypic.com/24y5s7q.png)
![alt link](http://i63.tinypic.com/1zflkx2.png)
![alt link](http://i63.tinypic.com/10ekbjp.png)

**Comment by 97balakrishnan** [comment]
Yeah iam using version 2.7.0
My device moto g3 android 6.0.1

**Comment by misaochan** [comment]
Oh, okay! So the bottom sheet (and the "directions" symbol on the bottom sheet) works fine. It's just the orientation button (to align the map to North) that is being covered.

**Comment by wanderlustyc** [comment]
Hey, I can fix this. I just looked into the code. I think this problem can be fixed by assigning some margin values to the compass button when initializing the map.

**Comment by misaochan** [comment]
Hi @wanderlustyc , thanks! It is yours. :)

**Comment by neslihanturan** [comment]
@wanderlustyc are there any progress so far? Do you have any question about this task, I will be happy to answer.

**Comment by wanderlustyc** [comment]
@neslihanturan It went well. I've submitted PR. Thanks. : )
