### ISSUE TITLE
Enhancement : Dark themed map

### ISSUE THREAD

**Issue by 97balakrishnan** [commons-app/apps-android-commons#1396]
Dark styled map can be implemented for dark theme
BUT I don't know if this can be done with mapbox.
**Screen-shots:** 

![alt link](https://snazzy-maps-cdn.azureedge.net/assets/37-lunar-landscape.png)

**Comment by tanvidadu** [comment]
https://www.mapbox.com/help/android-runtime-styling-intro/
https://www.mapbox.com/android-docs/map-sdk/overview/runtime-styling/
 can be used to style the maps on run-time. 
Maybe we can change the language of map depending upon the language of the user ?

**Comment by misaochan** [comment]
We need to use the Wikimedia tile server for privacy reasons, and AFAIK this cannot be achieved with that (see #1002 ).

**Comment by nicolas-raoul** [comment]
How about leaving this issue open and marking it "upstream"?
In the future WMF might accept to add dark tiles, after they have solved their many more pressing issues.

**Comment by sivaraam** [comment]
I believe we already have a dark theme app in the latest version of the app. So, closing this. Feel free to re-open if I'm missing something.

**Comment by macgills** [comment]
@sivaraam it may have been a typo or a misread so I am just clarifying, this is for a dark theme _map_ not >app

**Comment by sivaraam** [comment]
@macgills Yeah, it was indeed a typo. Fixed it now :) The app does have a dark themed _map_.
