### ISSUE TITLE
Addition : Adding a link to Help page in Tutorial

### ISSUE THREAD

**Issue by 97balakrishnan** [commons-app/apps-android-commons#1397]
**Summary:** 

We can add a small button for more help in the last slide of tutorial to open a link to [Help page](https://commons.m.wikimedia.org/wiki/Help:Contents) of wikimedia commons. Here they can learn more about 
- licensing,
- Privacy policy
- copyrights and other related stuff.

**Comment by misaochan** [comment]
Sounds like a good plan IMO. :)

**Comment by tanvidadu** [comment]
I will start working on it !
Though I believe we should add this link in about page also. User might not go to tutorial each time in case they need information regarding license, privacy policy , copyrights etc.

**Comment by 97balakrishnan** [comment]
Sorry @tanvidadu I've already started working on this.

**Comment by misaochan** [comment]
@tanvidadu If you are looking for other issues to work on, feel free to try your hand at #1395 or #1401 :)
