### ISSUE TITLE
Deletion Button getting disabled after clicking on cancel button

### ISSUE THREAD

**Issue by Jatin0312** [commons-app/apps-android-commons#1398]
**Summary:** 
Nomination for deletion button getting disabled after clicking on cancel button in alert dialog box.

**Steps to reproduce:** 

Just go to any image click on nomination for deletion and click cancel on alert dialog box

**Expected behavior:** 

![solved7](https://user-images.githubusercontent.com/17095817/38168794-c275f55c-3574-11e8-8582-1954a2820f6b.gif)

**Observed behavior:** 

![bug7](https://user-images.githubusercontent.com/17095817/38168796-c967d358-3574-11e8-983c-5eb158fa42aa.gif)

**Device and Android version:** 

Moto g4 plus Android 7.0.0
 
 **Commons app version:** 
2.7.0

**Would you like to work on the issue?**

Yes, I would like to fix this issue.

**Comment by gabrielaradu** [comment]
Is this issue free to take?

**Comment by misaochan** [comment]
Oops, I think @Jatin0312 said they would like to work on it, but AFAIK Jatin already has a couple of other tasks assigned to them? Jatin, are you okay with @gabrielaradu taking this task?

**Comment by Jatin0312** [comment]
Ya sure no problem :)

**Comment by misaochan** [comment]
Thanks. :) The task is yours @gabrielaradu . I see you already have a PR up for it, we'll review it ASAP.
