### ISSUE TITLE
Place description getting overlapped with plus fab button Nearby Activity

### ISSUE THREAD

**Issue by Jatin0312** [commons-app/apps-android-commons#1399]
**Summary:** 

For some place description while clicking on the marker gets overlapped with plus fab button

**Steps to reproduce:** 
Click on any marker place which has a large description.

**Expected behavior:** 

It should not overlap.

**Observed behavior:** 

![bug 8](https://user-images.githubusercontent.com/17095817/38168867-f8355afa-3576-11e8-9083-eb967d33fd79.jpeg)

**Device and Android version:** 

Moto g4 plus Android 7.0.0
 
 **Commons app version:** 

2.7.0

**Would you like to work on the issue?**
Yes I would like to work on this issue.

**Comment by misaochan** [comment]
@Jatin0312 I agree. The issue is yours if you want it! :)

**Comment by Jatin0312** [comment]
Sure I will do it :)

**Comment by misaochan** [comment]
Thanks @Jatin0312 ! Please submit your PR to `2.7.x-release` branch :)
