### ISSUE TITLE
Make uploaders affirmatively select license

### ISSUE THREAD

**Issue by calliopejen** [commons-app/apps-android-commons#140]
I was able to upload a file without ever selecting or acknowledging the license to be used for my uploads.  I see there is a default, but I never chose this as far as I know.  This is potentially a _huge_ legal issue if someone later says that they never intended to agree to the license--it could threaten the viability of all photos uploaded using this app.  Please fix this issue!

**Comment by nicolas-raoul** [comment]
Do you suggest we should add a license choice dialog the first time, or every time?
We could put it below the title/description fields.
Would a link to the full text of said license be required too?

**Comment by calliopejen** [comment]
Now that I went through the process one more time, I see there is some text that states the license but it is small (easy to miss) below the title and description fields.  So I may have been overdramatic earlier, but I still think it could be clearer... It might be good to have a popup after the initial sign-in to acknowledge the default license?  Maybe just something like "As a default, all images are uploaded under the Creative Commons Attribution Share Alike 3.0 [linked] license. You can change this setting in your preferences, if desired." -- with an "Accept" button.  Then there wouldn't be any question that users understand the license.

**Comment by domdomegg** [comment]
Or maybe in those screens that turn when you first open app explaining what commons is it could be explained there!

**Comment by misaochan** [comment]
The tutorial screen the first time users open the app would be a good place for the explanation IMO, I think selecting a license every time would be far too tedious.

**Comment by misaochan** [comment]
@nicolas-raoul , what do you think about adding this to the tutorial?

**Comment by nicolas-raoul** [comment]
"As a default, all images are uploaded under the Creative Commons Attribution Share Alike 3.0 [linked] license. You can change this setting in your preferences, if desired."

... or similar sounds good for the tutorial. This would solve the present issue, I believe.

**Comment by misaochan** [comment]
Sounds good, I'll slot that into the tutorial overhaul (phase 2 of my project).

**Comment by domdomegg** [comment]
Is this solved in #383?

**Comment by misaochan** [comment]
Yup, thanks for pointing it out!
