### ISSUE TITLE
Wikidata image not set

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#1409]
**Steps to reproduce:** 

- Open Nearby
- Select a thing you took a picture of
- Touch the + and select gallery
- Select the picture of the thing
- Leave title/description as is, change license if you want
- Select categories
- Press the floppy icon

I have just tried once, will retry with another when I can.

**Add System logs:**

[logs (1).txt](https://github.com/commons-app/apps-android-commons/files/1868008/logs.1.txt)

**Expected behavior:** 

Wikidata item now has a property "image" that has the Commons image's title as a value.

**Observed behavior:** 

The Wikidata item still has no image: https://www.wikidata.org/wiki/Q1286686

**Device and Android version:** 

Nexus 5, Android 7.1.2
 
 **Commons app version:** 

2.7.0

**Screen-shots:** 

![screenshot from 2018-04-02 20-58-57](https://user-images.githubusercontent.com/99590/38195569-01d9204e-36b9-11e8-95be-11d294d07806.png)

**Comment by nicolas-raoul** [comment]
I tried again, same problem, with https://www.wikidata.org/wiki/Q49269017 and the user seen in the screenshot above.
Maybe because the user is not "registered"? Maybe that means this user has never opened Wikidata, and thus https://en.wikipedia.org/wiki/Wikipedia:Unified_login has not initialized something? Wild guess, someone familiar with Wikimedia login might want to comment (@VojtechDostal?)

**Comment by misaochan** [comment]
@nicolas-raoul We have not implemented Wikidata edits yet. :) That is the next planned step, but we wanted to get the direct uploads released first instead of saving all for a later release date.

**Comment by nicolas-raoul** [comment]
Ah sorry thanks, yes that's a good strategy.
Looking forward to Wikidata edits :-)
