### ISSUE TITLE
Allow user to retrieve data from server while upload is in process

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#1419]
**Summary:** 

Values in media details view are empty sometimes. So far, for me, this only happens when a different image is currently being uploaded.

**Steps to reproduce:** 

Upload an image, then quickly go to your contributions list and select a different image to view

**Expected behavior:** 

Display values appropriately

**Observed behavior:** 

Does not display values appropriately. I suspect we are blocking the network thread when uploading?

**Device and Android version:** 

API 26 Samsung Galaxy s7
 
 **Commons app version:** 

2.7.0 beta

**Screen-shots:** 

![screenshot_20180403-203152](https://user-images.githubusercontent.com/3611199/38244624-9dc2f726-377e-11e8-8eed-cea51f9247bb.png)

**Would you like to work on the issue?**

Preferably not

**Comment by ashishkumar468** [comment]
I would like to work on this fix, As i can see from the code, we have the data before the actual api call succeeds (in this this case i would propose to at least show the entire data available then), or we could show a progress bar while the api call succeeds. I am new to this thing and therefore I request the reviewer to help me come to a conclusion on this

**Comment by neslihanturan** [comment]
Thanks @ashishkumar468 , can you provide related class and code lines? It would be great if you insert that code part then we can discuss:)

**Comment by ashishkumar468** [comment]
`private void displayMediaDetails(final Media media) {
        //Always load image from Internet to allow viewing the desc, license, and cats
        image.setMedia(media);

        // FIXME: For transparent images
        // FIXME: keep the spinner going while we load data
        // FIXME: cache this data
        // Load image metadata: desc, license, categories
        detailFetchTask = new AsyncTask<Void, Void, Boolean>() {
            private MediaDataExtractor extractor;

            @Override
            protected void onPreExecute() {
                extractor = new MediaDataExtractor(media.getFilename(), licenseList);
            }

            @Override
            protected Boolean doInBackground(Void... voids) {
                try {
                    extractor.fetch();
                    return Boolean.TRUE;
                } catch (IOException e) {
                    Timber.d(e);
                }
                return Boolean.FALSE;
            }

            @Override
            protected void onPostExecute(Boolean success) {
                detailFetchTask = null;
                if (!isAdded()) {
                    return;
                }

                if (success) {
                    extractor.fill(media);

                    // Set text of desc, license, and categories
                    desc.setText(prettyDescription(media));
                    license.setText(prettyLicense(media));
                    coordinates.setText(prettyCoordinates(media));
                    uploadedDate.setText(prettyUploadedDate(media));

                    categoryNames.clear();
                    categoryNames.addAll(media.getCategories());

                    categoriesLoaded = true;
                    categoriesPresent = (categoryNames.size() > 0);
                    if (!categoriesPresent) {
                        // Stick in a filler element.
                        categoryNames.add(getString(R.string.detail_panel_cats_none));
                    }
                    rebuildCatList();
                } else {
                    Timber.d("Failed to load photo details.");
                }
            }
        };
        detailFetchTask.executeOnExecutor(AsyncTask.THREAD_POOL_EXECUTOR);

        title.setText(media.getDisplayTitle());
        desc.setText(""); // fill in from network...
        license.setText(""); // fill in from network...
    }`


This is the function which actually shows media details, we could maybe add a progress bar while the async task is executing

**Comment by neslihanturan** [comment]
Yes, it seems like that would solve the issue @ashishkumar468

**Comment by ashishkumar468** [comment]
Cool, have done the same :-)

**Comment by misaochan** [comment]
I would like to bump the priority of this bug, because it's pretty major. So far that I've seen, the user cannot do ANYTHING that requires a download, while an upload is in progress, it isn't just restricted to viewing media details. So they cannot use Browse (no images will load), they cannot load Achievements, etc.

**Comment by misaochan** [comment]
Note: This needs to be re-tested to see if 2.9 fixed the issue.

**Comment by neslihanturan** [comment]
I can verify that it is solved after 2.9
