### ISSUE TITLE
list icon allows user only to show the list , but not to make it disappear

### ISSUE THREAD

**Issue by dinaraassan** [commons-app/apps-android-commons#1436]
Summary:
I expected that by pressing the icon the list of nearby places will appear and if I will press this icon again the list will disappear. However, once the list appears future pressing on this icon will do nothing.

Steps to reproduce:
1. Download the (Beta) app from the Play Store
2. Go to Nearby
3. Press the icon for viewing the list

Expected behavior:
I expected that by pressing the icon the list of nearby places will appear and if I will press this icon again the list will disappear.

Observed behavior: 
I can press the icon for showing the list of nearby places, but once the list appears future pressing on this icon will do nothing. I was confused about how I can get rid of the list and go back to the full-screen map. It is not intuitively obvious to a user, that we need to slide the list downward in order to get rid of it. I think that it would be better if we will also add the icon feature that will allow a user not only to show the list but also to make it disappear.

Device: Sony Xperia XA Ultra
Android version: 7.0
Commons app version: 2.7.0

Screen-shots:
![img_20180413_223856_852](https://user-images.githubusercontent.com/17812648/38747110-8c85d36c-3f6b-11e8-9138-709f676eaf4e.jpg)

Would you like to work on the issue?
No, I am a Tester

**Comment by brok85** [comment]
I start working on this with @gshrock

**Comment by neslihanturan** [comment]
@dinaraassan actually it wasn't a bug, it was a feature:) you can always swipe down the list. Do you still think a button is needed to hide the list? If so I will test and merge @brok85 's PR.

**Comment by dinaraassan** [comment]
@neslihanturan Yeah, I understood that it is a feature, but still, I think that it would be better if we will have the additional way to close the list just by pressing the icon.  I already explained the reason in the description of the issue. It is not obvious that we can swipe down the list. Users will press the icon intuitively again in order to close the list and hence, will be confused if it will not work.  I mean, can we have two ways of closing the list instead of one?

**Comment by misaochan** [comment]
I agree with @dinaraassan that it would be good if tapping the list button again when the list is up could close it. :) If it isn't too much trouble, anyway.
