### ISSUE TITLE
button that opens Google Maps shows always only the coordinates of the first chosen mark

### ISSUE THREAD

**Issue by dinaraassan** [commons-app/apps-android-commons#1437]
Summary:
When you choose any mark from the map the corresponding button that opens  Google Maps shows always only the coordinates of the first chosen mark. 

How can we reproduce the issue?
1. Download the (Beta) app from the Play Store
2. Go to Nearby
3. Choose any mark on the map
4. Press the button for opening google map (labeled it on the screenshot)

Expected behavior: 
I expected that Google Maps will be opened and it will show me the right coordinates of the object that I chose on the application's map,

Observed behavior:
 however, it shows it correct only for the first time. When you will try to look at the coordinates of the other objects, it will always show you the coordinated of the first chosen mark. 

(By the way, the same button from the list of nearby objects works fine)

Device: Sony Xperia XA Ultra
Android version: 7.0
Commons app version: 2.7.0

Screen-shots:
![img_20180414_012231_405](https://user-images.githubusercontent.com/17812648/38754228-c3e418f2-3f82-11e8-928e-741ecd63f658.jpg)

Would you like to work on the issue?
No, I am a Tester

**Comment by neslihanturan** [comment]
Thanks for reporting this critical issue @dinaraassan :)
