### ISSUE TITLE
Case when the button that opens Google Maps do nothing

### ISSUE THREAD

**Issue by dinaraassan** [commons-app/apps-android-commons#1438]
Summary: 
In case if you first open the list of nearby places, and there chose the place and press the button that opens  Google Maps and then try to choose mark from the map and press there the same button it will do nothing. 

Steps to reproduce:
1. Download the (Beta) app from the Play Store
2. Go to Nearby
3. Open the list of nearby places
4. Choose place and press there the button that opens the Google Maps (it will always work fine)
5. Choose any mark on the map
6. Press the button for opening google map , it will do nothing 

Expected behavior:
I expected that Google Maps will be opened and it will show me the right coordinates of the object that I chose on the application's map,

Observed behavior: The button will do nothing

Device: Sony Xperia XA Ultra
Android version: 7.0
Commons app version: 2.7.0

Screen-shots:
Open the list of nearby places. Choose place and press there the button that opens the Google Maps (it will always work fine)
![img_20180414_014944_344](https://user-images.githubusercontent.com/17812648/38755109-5b7e08dc-3f86-11e8-8f4a-fdb3723bbe35.jpg)

Below is a screenshot of the button that does not work. Choose any mark on the map. Press the button for opening google map , it will do nothing 
![img_20180414_012231_405](https://user-images.githubusercontent.com/17812648/38755086-41feac36-3f86-11e8-937b-abc852e08580.jpg)

Would you like to work on the issue?
No, I am a Tester

**Comment by dinaraassan** [comment]
@neslihanturan Can you please take a look at this issue. I think it is important.

**Comment by neslihanturan** [comment]
This one is really important, thanks for reporting  @dinaraassan  , I will be working on it today.

**Comment by misaochan** [comment]
I tried to reproduce this but have been unable to - the Directions button always brings me to my map app, both in Nearby list and map. Does this issue happen for anyone else?

**Comment by nicolas-raoul** [comment]
I can reproduce the bug, with the exact steps described by @dinaraassan (it is only for the buttons that appear after touching a pin on the map and touching the white banner that appears at the bottom)
The Wikidata button next to it works fine.

**Comment by neslihanturan** [comment]
Yes, I am also able to reproduce this bug with the steps written by @dinaraassan . But weird thing is Wikidata button and Directions button and how they handle their actions are exactly same. My current investigation didn't bring any solution. If some of you have a theory, I would like to heard about:)

**Comment by misaochan** [comment]
@neslihanturan and @nicolas-raoul Does this happen for you with the current 2.7.x-release branch as well? That is the one that I am testing currently, with the steps mentioned in the first post. I guess if it doesn't happen on that branch, it will be solved in 2.7.1.

**Comment by nicolas-raoul** [comment]
Sorry I am using alpha (beta?).

**Comment by neslihanturan** [comment]
I am able to reproduce this on 2.7.x-release too @misaochan :/

**Comment by misaochan** [comment]
Copying my test results from my PR: 

How odd. It happens to me sometimes but not at other times. When it happens, I can never access Directions from the map at ALL (although I can from the list). The steps don't matter - it happens regardless of whether I have opened the list beforehand, or changed activity, or not.

When it doesn't happen, I can always access Directions from the map, and again the steps don't matter.

Will have to investigate further.

**Comment by ashishkumar468** [comment]
Not reproducible to me on the current master. Feel free to reopen if this happens again:)
