### ISSUE TITLE
Map centers camera to your current location marker at a random moment

### ISSUE THREAD

**Issue by dinaraassan** [commons-app/apps-android-commons#1439]
Summary: 
The center of the map goes back automatically to your location marker at random moment during your manipulations with the map

Steps to reproduce:
1. Download the (Beta) app from the Play Store
2. Go to Nearby
3. Center the camera of the map somewhere away from your location marker
4. Start continuously tapping the screen from marker to marker, or just tapping the screen of the map.(with a delay of 1-2 sec)
5. You will notice how the center of the map goes back automatically to your location marker
 
Expected behavior: 
Center the map to my location marker only in the case when I press the specific white circle button on the top right corner of the screen 

Observed behavior:
Center of the map goes back automatically to your location marker at random moment during your manipulations with the map, like tapping from marker to marker.  

Device: Sony Xperia XA Ultra
Android version: 7.0
Commons app version: 2.7.0

Would you like to work on the issue?
No, I am a Tester

**Comment by neslihanturan** [comment]
Thanks for reporting this issue @dinaraassan , actually it is normal if it centers you when location information is updated. As a user, do you think it is a bad experience?

**Comment by nicolas-raoul** [comment]
As a heavy user I don't find this annoying (rather useful), personally.

**Comment by neslihanturan** [comment]
Currently this feature should be disabled, the only possible way to recenter is using recenter button
