### ISSUE TITLE
Compass button hidden by bottom sheet

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#1441]
**Summary:** 

Compass button in `2.7.x-release` branch is hidden by bottom sheet when pin is selected

**Steps to reproduce:** 

Load Nearby map, select a pin, and swivel the map around a bit. Now you have a rotated map and no way to get it back to the original rotation. You can only access the compass button if you clear the bottom sheet.

**Expected behavior:** 

Have the compass button in a location where the bottom sheet wouldn't hide it.

**Device and Android version:** 

API 24 Samsung Galaxy s7
 
 **Commons app version:** 

2.7.x-release branch

**Would you like to work on the issue?**

I could. but the simplest fix I can think of - just putting the compass button in the upper left corner, might not be ideal?

**Comment by misaochan** [comment]
Ah, I see. Does it really look that asymmetrical to have it on the top left? I guess we can leave it for the time being, and change in the future if users complain. Maybe it is just me who always accidentally rotates maps. :)

**Comment by neslihanturan** [comment]
@misaochan yes:/ we couldn't find a better solution that time. So I am closing this issue
