### ISSUE TITLE
Uploading pictures from Gallery does not support descriptions

### ISSUE THREAD

**Issue by VojtechDostal** [commons-app/apps-android-commons#1442]
I uploaded a few pictures en mass by sharing them from the Gallery app. This is a great way to upload pictures (within a common category) but there is no way to provide a unified description. The pictures end up flagged as "description missing".

**Comment by misaochan** [comment]
Thanks for reporting this. :) Yeah, this is a known bug - lots of things are missing from this entry point, including saving geotagged locations. We intend to overhaul uploading in the near future (hopefully, after 2.7.1 is done). In that case, we would streamline multiple uploads - they would work the same way via "Share" and via the app, which should solve this problem. #1091

**Comment by VojtechDostal** [comment]
OK, largely duplicate with #604
