### ISSUE TITLE
Wikimedia Hackathon 2018 ideas

### ISSUE THREAD

**Issue by neslihanturan** [commons-app/apps-android-commons#1448]
**Summary:** 

As all you know Wikimedia Hackathon is a great opportunity for us to meet new contributors, designers, users and getting feedback from them. It would be great if we can be there prepared, do you have any ideas? You can also define how you would like to our app be presented on open ceremony too. I will be there, probably there will be others from team too:)

**Comment by nicolas-raoul** [comment]
I believe #780 is a good task for a hackathon because:

- Many people will have many different ideas about what it should do, look like, and what existent APIs/databases it could use
- A flimsy prototype can be implemented quickly, and be visually impressive even if not finished.
- Easy to understand. Review has always been understaffed, and it wastes a lot of time from experienced volunteers whose skills could be put to better use (for instance wikification, fact-checking, maintaining categories, or just writing articles), allowing people to casually review when they need to kill time might solve this problem. 
- Appeals to everyone, as all projects (Wikipedias/Wikivoyages/etc) need such a mobile peer review app (they just don't know it yet haha), and might even fork it on-the-spot to port it to their home wiki.

**Comment by knight-shade** [comment]
Hello guys @neslihanturan @nicolas-raoul Does anyone know why the deadline for scholarship was end of January, so early?

**Comment by misaochan** [comment]
@knight-shade I'm not attending this round, but I believe that part of the reason is that WMF is paying for your flight tickets, and the earlier flight tickets are booked, the cheaper they are. ;)

**Comment by misaochan** [comment]
@neslihanturan Thanks for starting this! I agree that #780 looks like a good idea. As you will likely be leading the team this time though, I would advise that you choose a task that you are relatively familiar and comfortable with personally.

I don't think we had much time to talk about the app during the open ceremony - last round we had a couple of sentences each I believe, haha.

**Comment by VojtechDostal** [comment]
By the way, Wikimedia Czech Republic is going to be very involved in Wikimedia Hackathon next year (2019) - and we plan to make this app one of the centerpieces of the event. More information is currently not public but an announcement will come out soon :-)

**Comment by misaochan** [comment]
> By the way, Wikimedia Czech Republic is going to be very involved in Wikimedia Hackathon next year (2019) - and we plan to make this app one of the centerpieces of the event. More information is currently not public but an announcement will come out soon :-)

Exciting! 👍

**Comment by neslihanturan** [comment]
#780 seems like a good idea! When it comes to our 1 or 2 sentence explanation, I would like to get team support about what should be said, which sides of the app need to be emphasized etc. 

On the other hand, do you think we should add our idea to here: https://phabricator.wikimedia.org/project/view/3260/

Event page: https://www.mediawiki.org/wiki/Wikimedia_Hackathon_2018/Program

**Comment by misaochan** [comment]
> When it comes to our 1 or 2 sentence explanation, I would like to get team support about what should be said, which sides of the app need to be emphasized etc.

How about saying that the app allows users to upload photos to Commons directly from their Android phones, and emphasizing the Nearby feature? I don't think you will get to demonstrate, but you can say that we have a map of nearby places that need pictures, and people can upload photos directly from it with titles and categories suggested based on the Wikidata item.

(Hopefully we should have 2.7 out in production by then, lol)

**Comment by psh** [comment]
My mind immediately went to an exercise our company does when spinning up a new project team - we use one of the well known "elevator pitch" frameworks to focus ourselves on the outcome of the project - its a quick "fill in the gaps" game

> **For** *[the individual or group]*
> **who** *[has an unmet need],*
> **the** *[product]*
> **is a** *[concise explanation of your product]*
> **that** *[high level description of what your product does].*
> **Unlike** *[your main competitors]*
> **our product** *[differentiator description].*

Following the pattern I came up with:

> **For** Android Phone Users **who** are on the go, **the** Wikimedia Commons App **is** [the] go-to solution **that** allows direct uploads from their phone.  **Unlike** the web interface to Commons, **our app** uses the phone’s location and offline storage capability to source and visualize a higher quality of categorized, localized images.

**Comment by neslihanturan** [comment]
A nice template  to  follow:)

**Comment by neslihanturan** [comment]
Team I decided to prepare a base branch for #780 . I am planning to include a new item as "review other images" to nav bar for now. After we implemented #1221 we can merge this two property into one screen I hope. But I might need your help to define the scope.
Until the hackathon I plan to prepare a "Display a random image to me" button and add "Send a public thank" to it, then during the hackathon we can handle sending other types of reviews and getting a random image according to category or place. What do you think about the scope?

I am not in favor to apply a fully featured search option since this already will be implemented for #1221 . (Besides I don't think we can finish it during limited hackathon time) Thats why I suggest to get photos random. After #1221 is implemented we can remove the part about _getting a random image_ and add our review option to let user review _images that they are currently browsing_.

**Comment by neslihanturan** [comment]
Up up, date is coming:)

**Comment by maskaravivek** [comment]
@neslihanturan Right now the wikidata edits are happening anonymously. If we are able to figure out the authentication bit for it then notifications would be linked to the commons account. It might not work out of the box and some changes might be needed to make those notifications appear but it can definitely be done once the authentication for wikidata is done. :)

**Comment by misaochan** [comment]
If I understand @neslihanturan 's suggestion correctly, I don't think it is necessary for Wikidata authentication to be done before this "used on Wikipedia" notification is implemented. AFAIK all we need to track is the picture itself, not the Wikidata edit, if we want to see whether the picture is added to a Wikipedia article or not. For instance, go to https://commons.wikimedia.org/wiki/File:Cyclone_aila_affected_area_-_11.jpg and see "File usage on other Wikis". 

However, I'm unsure if any notifications will be generated from it, or if there are any APIs to check a particular picture's usage. But Wikidata edits being authenticated will not make a difference in this regard, IMO.

**Comment by JeanFred** [comment]
> if there are any APIs to check a particular picture's usage. 

There is, at https://commons.wikimedia.org/wiki/Special:ApiSandbox#action=query&format=json&prop=globalusage&meta=&titles=File%3AExample.jpg :)

> any notifications will be generated from it,

Unfortunately, « Your file was used » is not (yet) part of the Echo Notifications :-( (cf. https://phabricator.wikimedia.org/T77154)

**Comment by misaochan** [comment]
Thanks @JeanFred ! :)

**Comment by maskaravivek** [comment]
@misaochan Thanks for clarifying @neslihanturan's point. Yes, tracking the usage of the particular image would let us show such notifications. 

Moreover, we can also show the wikidata edits notification in the app by enabling cross wiki notifications. 

https://commons.wikimedia.org/w/api.php?action=query&format=json&meta=notifications&notwikis=wikidatawiki|commonswiki|enwiki

IMO, it would be nice to let the user see a thank-you-edit notification in the app once the image he uploaded is linked to the wikidata entity.
