### ISSUE TITLE
Start a Medium dev blog and add it to Wikimedia publication?

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#1462]
I just found out about https://medium.com/freely-sharing-the-sum-of-all-knowledge/ from looking at the GSoC community bonding page. From what I can gather, it seems that Medium works by having "Collections" or "Publications" of relevant blogs, similar to [Planet Wikimedia](https://meta.wikimedia.org/wiki/Planet_Wikimedia). However, the Medium collection seems to have more traction and readers than Planet Wikimedia from what I can see.

I wonder if it would be worth starting a dev blog on Medium, and asking the Wikimedia curators if they wouldn't mind adding us? It feels a bit like duplication of effort, since I already post updates on my Wordpress blog, which is part of Planet Wikimedia. But it might be worth it. The [web dev team](https://medium.com/freely-sharing-the-sum-of-all-knowledge/why-it-took-a-long-time-to-build-that-tiny-link-preview-on-wikipedia-d5bd734df8fe) seems to do the same duplication.

Thoughts? From those familiar with Medium (@maskaravivek ?) as well as those familiar with Wikimedia publicity (@VojtechDostal and @nicolas-raoul ?).

**Comment by VojtechDostal** [comment]
I really support this but I worry about the duplication. Would it be possible to switch to medium completely and then aggregate to Planet Wikimedia from there?

**Comment by maskaravivek** [comment]
Sounds like a great idea to me. I would surely volunteer to help in writing few articles if we start such a blog. :)

Moreover, I won't worry too much about duplication as Medium offers a cool feature where it lets you import stories from other blogs. 

https://medium.com/p/import

It certainly supports Wordpress imports but we will have to check about Planet Wikimedia. Importing the story publishes the same story from your medium account keeping the links, images and another formatting intact. Try it out once to get a feel of how it works :)

**Comment by misaochan** [comment]
Thanks guys!

@maskaravivek So, basically, what I should do is to create a Medium blog for "Commons app", and then add a few of our accounts so that we can all contribute articles from our personal accounts... and then I should ask the person in charge of the Wikimedia publication if they could add our blog to it. Is that accurate?

Sorry, really new to this whole Medium thing. 😄

**Comment by misaochan** [comment]
Good point. It seems that unlike Wordpress, we cannot make a blog with multiple authors though? Every person seems to have their own "Stories" which may be included in a "publication", so since we don't want to be a publication ourselves, we can't really create a "Wikimedia Commons app" blog per se, right?

Does anyone know who the curator of https://medium.com/freely-sharing-the-sum-of-all-knowledge is, or how we can contact them? I tried poking around a bit but there doesn't seem to be any information on that.

**Comment by sivaraam** [comment]
> Does anyone know who the curator of medium.com/freely-sharing-the-sum-of-all-knowledge is, or how we can contact them?

You could give the [talk page of Wikimedia blog on meta](https://meta.wikimedia.org/wiki/Talk:Wikimedia_Blog). You'll possibly get the details you want.

**Comment by misaochan** [comment]
Thanks @sivaraam . That talk page seems to be for blog.wikimedia.org , not for the Medium blog (which has a separate URL and different articles), but maybe they could help point us in the right direction regardless.

**Comment by sdabhi23** [comment]
I would like to point out the you can import articles directly from wordpress to medium very easily. You can go to `stories > import story > enter the link to your wordpress article` and medium will import it for you along with all the images. This can help save a lot of duplication effort.

I have done that with my blog, haven't been able to come up with an automated solution for it though.

**Comment by misaochan** [comment]
I just created a @commons_android_app account (@commons_app was, strangely, taken....) and used the import feature to get the 2.9 beta post from my wordpress blog.

https://medium.com/@commons_android_app/version-2-9-beta-e16cc5aa5b6

Thoughts? If everything looks OK, I can start looking for how I can get us added to Wikimedia's collection. :)

I am not sure why a hash was added to the end of the url, btw. :/

**Comment by maskaravivek** [comment]
@misaochan The account looks a bit confusing. The account username is `@commons_android_app` but the profile displays your name. It would be more appropriate to have the display name set to "Commons Android App". :)

https://medium.com/@commons_android_app

Or else, were you trying to create a [publication](https://help.medium.com/hc/en-us/articles/115012095528-About-Medium-publications) instead?

**Comment by misaochan** [comment]
I don't think we want a publication, since we want to be included in Wikimedia's publication, right? I don't think we can have a publication in a publication.

I changed the display name. :)

**Comment by maskaravivek** [comment]
Yes right, a blog post can exist in just one publication at a time. 

I just followed the account. It looks great. :)

**Comment by misaochan** [comment]
Thanks @maskaravivek ! I'll contact Ed then. Fingers crossed they'll approve us. :)

**Comment by misaochan** [comment]
Ed got back to me:

> Most of what we've published has involved some larger-scoped topics, and so I'm not certain it's the best place to be posting app updates—certainly there would be a bit of a disconnect with the publication's audience! That said, we'd love to help promote larger updates from the @Wikimedia Twitter account, and I would recommend posting them to the Wikipedia Weekly Facebook group as well. 

I'll take him up on the offer for the Twitter and FB accounts. But it seems like our Medium blog will have to go it alone for now. :)
