### ISSUE TITLE
MediaDataExtractor is making inefficient (redundant) server calls

### ISSUE THREAD

**Issue by psh** [commons-app/apps-android-commons#1464]
**Summary:** 

`MediaDataExtractor` is making double calls to the mediawiki API to determine if a page (image) has been deleted.  Its not wrong, just inefficient.

**Steps to reproduce:** 

Take a look at the `fetch()` method 
```java
try{
    Timber.d("Nominated for deletion: " + mediaWikiApi.pageExists("Commons:Deletion_requests/"+filename));
    deletionStatus = mediaWikiApi.pageExists("Commons:Deletion_requests/"+filename);
}
catch (Exception e){
    Timber.d(e.getMessage());
}
```

**Expected behavior:** 

Only one call should be made, and then the request / result should be logged.  Calling `pageExists()` initiates a call to the server every time. 
 
 **Commons app version:** 

Current `master` branch.

**Comment by manparvesh** [comment]
@psh Hi,
I have submitted a PR (#1496) for this issue. Please take a look
