### ISSUE TITLE
0 uploads in beta app

### ISSUE THREAD

**Issue by gupta1anubhav** [commons-app/apps-android-commons#1465]
No. of uploads on Actionbar remains to 0 on logging in the app even when I have stored many images before.

How can we reproduce the issue?

1. Login to the app and make sure you have uploaded photos previously.
2. No. of uploads remains at zero.

Tested On: Xiaomi Redmi Note 4
Android Version: 7.0 
Commons app version: 2.7.1-debug-master~8a06aa5

Screen-shots: 

![screenshot_2018-04-27-00-27-00-559_fr free nrw commons debug](https://user-images.githubusercontent.com/31107831/39326330-41a88aaa-49b2-11e8-99e1-07ce9371f643.png)

Would you like to work on the issue?

I would love to work on this issue.

**Comment by gupta1anubhav** [comment]
betaDebug

**Comment by misaochan** [comment]
AFAIK, this is a known issue on beta due to incompatibility of the API that we use for obtaining number of uploads. :)

**Comment by domdomegg** [comment]
Fixed in #1265
