### ISSUE TITLE
Remove deprecated setDestination(Object)

### ISSUE THREAD

**Issue by gupta1anubhav** [commons-app/apps-android-commons#1472]
Steps to reproduce

1. Build project
2. Check build info.
We need to change ConfigurableReport.setDestination(Object) to ConfigurableReport.setDestination(File) as former method  is deprecated.

![2](https://user-images.githubusercontent.com/31107831/39444161-6c6a0672-4cd4-11e8-8c64-2f84e7b679c8.png)

Would you like to work on the issue?
Yes, I would love to work on this issue.

**Comment by gupta1anubhav** [comment]
Should I start working on this issue?

**Comment by nicolas-raoul** [comment]
@gupta1anubhav yes, thanks :-)

**Comment by gupta1anubhav** [comment]
@misaochan @nicolas-raoul plz review my pull request

**Comment by misaochan** [comment]
@gupta-meghna64 Could you please mention this issue number in your PR's description (e.g. "Fixes issue #")? Doing so will create a link here, and will auto-close the issue when it is merged.

**Comment by misaochan** [comment]
Eep, sorry, I tagged the wrong user! That tag should have been @gupta1anubhav . Sorry. :)

**Comment by gupta1anubhav** [comment]
@misaochan I have now changed the name of my pr but it still is not automatically referencing

**Comment by misaochan** [comment]
You need to change the description, not the title. Change the part that says "Deprecation removed"

**Comment by gupta1anubhav** [comment]
Thankyou @misaochan
