### ISSUE TITLE
Create video of people using the new Nearby feature for Play Store

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#1473]
I was thinking that it would be nice if we could create a video of people (preferably a diverse group of people) walking around on a photo trip around the area, using the new Nearby feature and uploading pictures through it. We could post this video on our Play Store listing, as well as on blogs etc.

Perhaps this year's hackathon would be a good place to do it? @neslihanturan what do you think? Is anyone else here attending? It would be great if we could rope in an experienced videographer to help, too, like John Lubbock did in the last hackathon. :)

**Comment by neslihanturan** [comment]
Great idea:) I am very excited actually. I can make the video work as soon as it is a simple video. But we need someone to record. Maybe John will be there?

**Comment by neslihanturan** [comment]
Another idea, not for play store but for our social media accounts: we can record ourselves while using nearby in some important places of our countries and then merge all of them with feeling collect and share knowledge of all world.

**Comment by misaochan** [comment]
> Great idea:) I am very excited actually. I can make the video work as soon as it is a simple video. But we need someone to record. Maybe John will be there?

Hopefully! But even if he isn't, if you mention this during the opening speech (where you invite participants to join you), someone might volunteer.

> Another idea, not for play store but for our social media accounts: we can record ourselves while using nearby in some important places of our countries and then merge all of them with feeling collect and share knowledge of all world.

This is a great idea! :) I am all for it.

**Comment by neslihanturan** [comment]
I recorded 4 video by the way, will share with you soon:)

**Comment by misaochan** [comment]
Great, looking forward to it!

Should we keep this open until we have the links up?

**Comment by neslihanturan** [comment]
Yes I think we can discuss under this thread instead of creating a new issue

**Comment by misaochan** [comment]
@neslihanturan Any news on the videos? :)

**Comment by misaochan** [comment]
@neslihanturan I mean, could you just send me the raw recording? I just need to see what we already have, as I am considering adding this task to our PG plans for next year.

**Comment by misaochan** [comment]
This would be a bit tricky with the Covid restrictions. I think I will email Chris and Marti and see if this counts as an "in person" event that must be cancelled, or not.
