### ISSUE TITLE
Error "path attribute should be defined"

### ISSUE THREAD

**Issue by gupta1anubhav** [commons-app/apps-android-commons#1479]
"external-path" in the red underlined text is the problem here.
Android lint: Android resources validation error in provider_paths.xml

the path attribute should be defined is the error description.

![4](https://user-images.githubusercontent.com/31107831/39479280-6945970a-4d82-11e8-88dd-5d0110a0648a.png)

Would you like to work on this issue?
Yes, I want to work on this issue.

**Comment by maskaravivek** [comment]
@gupta1anubhav can you provide some details on how you plan to fix the above. 

Moreover please detail where the above code is being used. :)

**Comment by gupta1anubhav** [comment]
As per by screenshot logs.txt file is stored in external directory + CommonsApp
Hence path is added as "CommonsApp" for name="logs".
I have created a pr for this issue.

![screenshot from 2018-05-22 16-46-24](https://user-images.githubusercontent.com/31107831/40359310-e7a3f5ac-5ddf-11e8-879c-c59bf5ceef13.png)
