### ISSUE TITLE
ButterKnife is not used every where in the project

### ISSUE THREAD

**Issue by ashishkumar468** [commons-app/apps-android-commons#1491]
**Summary:** 

Some of the activities and fragments have used ButterKnife and some have not. It should ideally be used everywhere.

**Steps to reproduce:** 

Lets compare AboutActivity and MediaDetailFragment

**Add System logs:**

NA

**Expected behavior:** 

Ideally all of the activities and fragments should use it

**Observed behavior:** 

As mentioned in the description, some of the activities and Fragment have used butterknife and some have not

**Device and Android version:** 

NA
 
 **Commons app version:** 

NA
**Screen-shots:** 

NA

**Would you like to work on the issue?**

Yes

**Comment by maskaravivek** [comment]
Please feel free to take it up. IMO it would be great to start using everywhere in our codebase but we don't want to restrict new contributors if they are not familiar with Butterknife. 

Refactoring code that doesn't use Butterknife would be more than welcome. :)

**Comment by ashishkumar468** [comment]
@maskaravivek Taking it up

**Comment by ashishkumar468** [comment]
@maskaravivek Can you review this ?

**Comment by domdomegg** [comment]
https://github.com/commons-app/apps-android-commons/issues/3530
