### ISSUE TITLE
Obsolete Gradle Dependencies

### ISSUE THREAD

**Issue by gupta1anubhav** [commons-app/apps-android-commons#1493]
AndroidLint: Correctness warning
Few issues
1.Obsolete Gradle dependencies
2.Restricted API should be suppressed(@SuppresLint) as there seems no workaround for it.
![6](https://user-images.githubusercontent.com/31107831/39621686-3e06692a-4fad-11e8-9458-c658054572cc.png)

Would you like to work on this issue?
Yes, I want to work on this issue.

**Comment by maskaravivek** [comment]
@gupta1anubhav Sure, go ahead!
