### ISSUE TITLE
Memory leak in Share Activity

### ISSUE THREAD

**Issue by maskaravivek** [commons-app/apps-android-commons#1515]
**Summary:** 

The location listener in share activity is leaking memory. 

**Steps to reproduce:** 

Leak canary logs

**Expected behavior:** 

No memory leaks

**Device and Android version:** 

Redmi Note 5 7.1.2 

 **Commons app version:** 

Latest master

**Screen-shots:** 

![device-2018-05-14-001447](https://user-images.githubusercontent.com/3069373/39970578-6dd63116-570b-11e8-9b51-d4278409a4a1.png)

**Would you like to work on the issue?**

It would be great, if someone else could pick it up. :)

**Comment by misaochan** [comment]
I'll take this up alongside failed uploads.

**Comment by nicolas-raoul** [comment]
This can be closed I guess?
