### ISSUE TITLE
"Nominate for deletion" only for own uploads

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#1516]
![screenshot_20180515-201528](https://user-images.githubusercontent.com/99590/40053612-e82b73b4-587c-11e8-89b8-fbcc38620700.png)

This button would lead to nothing more than misclicks, I believe.

**Comment by neslihanturan** [comment]
Oh do you mean this feature is not needed?

**Comment by nicolas-raoul** [comment]
This feature is intended for people who upload a picture without understanding that it is made public (without understanding what Commons is), and want to remove one of their upload from Commons.
I don't think it was meant for deleting other people's pictures. #1139

**Comment by neslihanturan** [comment]
I just recognized that this is Featured Activity. I agree we should hide it from Featured Activity.

**Comment by misaochan** [comment]
Yeah, this needs to be hidden in Featured.

**Comment by maskaravivek** [comment]
I will pick this up.
