### ISSUE TITLE
Swiping featured images limited to 10 images

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#1519]
Steps:
1. Go to featured images
2. Touch one featured image
3. Swipe right to see the next featured image
4. Swipe again many times
5. After the 10th image, swipe does not work anymore. Subsequent images do not get loaded.
![screenshot_20180515-214212](https://user-images.githubusercontent.com/99590/40057296-db94a2ae-5888-11e8-8084-6b4e2f91f455.png)

**Comment by maskaravivek** [comment]
IMO, this functionality could be supported for both featured images and user contributions. 

@nicolas-raoul Is there any particular reason for limiting the images to 10 in this fragment?

**Comment by nicolas-raoul** [comment]
There is no functional reason to limit the number of swipes to 10.
Technically, my guess is that there is there is a kind of 10-buffer somewhere, probably in the server query.
Instead, we should continue loading more items as soon as the user approaches the end of the results of the previous query.

(Same for the recent uploads indeed, we should remove the "Set Recent Upload Limit" settings and just load chunk by chunk as the user scrolls)
