### ISSUE TITLE
Make download button more visible?

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#1520]
The Download button of the media details activity is currently in the overflow menu, which is known to be a place users rarely see.

While it was perfect for an upload-centric application, now the app is getting more browsing features so downloading an image from Commons might become the most-common use case of the app.

So, I believe the download button should be made more visible.
What do you all think?

**Comment by ujjwalagrawal17** [comment]
Yup @nicolas-raoul, I agree with this. Maybe we can show download and share icon in the list itself.

**Comment by HectorRoblesWolf** [comment]
Is someone working on this?

**Comment by nicolas-raoul** [comment]
@HectorRoblesWolf No, feel free to implement it and send us a pull request! Should we assign you this task? :-)

**Comment by HectorRoblesWolf** [comment]
@nicolas-raoul yes please :-)

**Comment by HectorRoblesWolf** [comment]
Done, I just made a PR https://github.com/commons-app/apps-android-commons/pull/2005
