### ISSUE TITLE
Add search Images from commons feature 

### ISSUE THREAD

**Issue by ujjwalagrawal17** [commons-app/apps-android-commons#1521]
This is a child issue of #1221  

**Summary:** 

The users should be able to search images directly using name/description from commons.

**Screen-shots:** 

<table>
<tr>
<td>

![screenshot_20180515-141835](https://user-images.githubusercontent.com/19607555/40112180-d065fce4-5922-11e8-895a-5eb793268138.png)

</td>
<td>

![screenshot_20180515-140342](https://user-images.githubusercontent.com/19607555/40112181-d09393a2-5922-11e8-9fab-11790c67c9fb.png)

</td>
</tr>
</table>

**Would you like to work on the issue?**

Yes, I have started working on this issue. Will send a PR soon.

**Comment by ujjwalagrawal17** [comment]
@maskaravivek I am working on a separate search Activity which queries the data from servers. I am planning to open it from Featured Image Activity. Also, we can rename featured option to "explore" in the navigation drawer.

**Comment by maskaravivek** [comment]
IMO, you can very well use all the functionality of featured images activity as its totally generic but am not very sure about renaming it. 

You can init a separate instance of the featured images activity naming it **Explore** in the hamburger menu. 

Anyways if we have consensus on merging featured images with Explore then you can go ahead with it. :)

**Comment by nicolas-raoul** [comment]
Personally I am in favor of a single "Explore" item that shows featured images and a loop button to search.
The hamburger is already a bit crowded and might get more crowded with statistics, peer review, contests, etc.

**Comment by misaochan** [comment]
How about we have the search bar on top of Featured activity - when someone searches, they will initially be shown all the featured images that match their search. And when the results are displayed, we also have a "show non-featured images" button (similar to the "show more" button in other apps) where if they tap it, they can view the non-featured images as well for the same search term?

**Comment by maskaravivek** [comment]
Yes, I agree that the hamburger is already too crowded. So having a single **Explore** sounds good to me (Y). 

In addition to the search button, it would be great to have a filter button too. Right now the app shows all the featured images from Commons but there are further categories on Commons like Industry, History people etc. 

https://commons.wikimedia.org/wiki/Commons:Featured_pictures

It would be great to have people filter and see featured images from a particular category.

**Comment by nicolas-raoul** [comment]
The wide majority of searches return zero featured pictures, because only 0.024% of pictures are featured.
If there was a "show non-featured images" button it would be necessary to click every at pretty much every single search.
So, I suggest showing all images for now, and, in the second part of the GSoC, showing the featured images matching the search at the beginning of the results. That is actually what is planned in the GSoC schedule :-)

**Comment by misaochan** [comment]
Oh! Yep, that sounds good to me @nicolas-raoul .

**Comment by ujjwalagrawal17** [comment]
@nicolas-raoul @neslihanturan We can discuss here that we should make a new Activity for exploring or refactor the code of CategoryImagesActivity (featuredActivity). @nicolas-raoul Can you catchup the discussion at #1561 .

**Comment by neslihanturan** [comment]
Let's continue here: 
 **misaochan**

> @neslihanturan Can that issue not be solved by having existing text in the search bar that says "Search all images in Commons"?
> 
> I would personally prefer Browse and Featured to be united in a single activity if possible, as they are highly related and it reduces cluttering. I believe we were discussing this at #1521

**neslihanturan**

> I also meant we definitely should have them in same activity but maybe different tabs? Or your solution could also work. Under any case I think it is better to discuss on mockups. @ujjwalagrawal17 are you willing to create some mockups to find best solution? @nicolas-raoul I really wonder your opinion about this topic.

**Comment by ujjwalagrawal17** [comment]
I already made a few mock-ups. 
![](https://i.imgur.com/aIcCHcl.png)
![](https://i.imgur.com/yWZdGwd.jpg)
I thought We can start with only featured images. Later on we can integrate picture of the day and customise it more.
 
Yes I will share some more mock ups for explore feature tomorrow!

**Comment by nicolas-raoul** [comment]
I believe this would be the best:
- One single item in the left menu called "Explore"
- Touching "Explore" show the featured images and a search icon in the corner
- Touching the search icon brings the search screen as implemented in this request
In other words, like @ujjwalagrawal17 implemented looks great to me :-)

**Comment by neslihanturan** [comment]
Usage of tabs solved all unclarity for me. So for now I will merge @ujjwalagrawal17 's PR, then he can add other tabs on another PR.

**Comment by ujjwalagrawal17** [comment]
Also we can maybe add write some content in the page similar to website - 
**Highlights**
If you are browsing Commons for the first time, you may want to start with Featured pictures, Quality images or Valued images.

or maybe we can include main website link at the bottom too.[https://commons.wikimedia.org/wiki/Main_Page]

**Comment by nicolas-raoul** [comment]
Most Commons users do not know what is the difference between quality and valued images, and don;t really need to know.
They just want to see nice images.
So, how about hiding these technicalities, and just showing pictures in this order:

1. The picture of the day
2. All of the pictures for the first page (page in the meaning of query paging) of featured images
3. All of the pictures for the first page (page in the meaning of query paging) of quality images
4. All of the pictures for the first page (page in the meaning of query paging) of valued images
5. All of the pictures for the second page (page in the meaning of query paging) of featured images
6. All of the pictures for the second page (page in the meaning of query paging) of quality images
7. All of the pictures for the second page (page in the meaning of query paging) of valued images
8. etc

Advantages over showing a featured/potd/quality/valued menu:
- Content is shown as soon as you touch "Explore", which is more entertaining
- More user-friendly

**Comment by ujjwalagrawal17** [comment]
This feature is added so I am closing this issue :)

**Comment by neslihanturan** [comment]
Thanks!
