### ISSUE TITLE
Browse search field: Pressing Enter should launch search, rather than add newline character

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#1522]
Steps:
1. In the media search field, type "butterfly"
2. Touch the "Enter" key of your keyboard

Result: A newline character is added
Expected: The search is launched

Also: Some apps are able to change the Enter key into a loop symbol, that would be cool.

@ujjwalagrawal17

**Comment by ujjwalagrawal17** [comment]
@nicolas-raoul Yup Nicolas I also found this bug today. I will fix it.

**Comment by ujjwalagrawal17** [comment]
This issue is fixed and can be closed now.

**Comment by nicolas-raoul** [comment]
Thanks! :-)
