### ISSUE TITLE
Allow user to set any image as wallpaper using Commons app

### ISSUE THREAD

**Issue by maskaravivek** [commons-app/apps-android-commons#1525]
It would be great if we give the users an option to set an image as their phone's wallpaper. With exploring, featured images and picture of the day there would be plenty of good images that the user might want to use as a wallpaper. 

I can think of two places where this option could be there:
- media detail fragment, to allow the user to set that image as wallpaper
- Settings page: This could be a slightly different option that lets the user tick a checkbox and then every day we can update his wallpaper with that day's picture of the day.

**Comment by nicolas-raoul** [comment]
It would be interesting to know how other photo cloud apps (such as Flickr) implement this kind of feature, if they do.

**Comment by maskaravivek** [comment]
Its quite simple AFAIK. Android exposes a permission ie. `android.permission.SET_WALLPAPER` that lets the app access `WallpaperManager`

**Comment by neoliteconsultant** [comment]
I start working on this

**Comment by maskaravivek** [comment]
@neoliteconsultant a PR is already up for it. Please check for other tasks. :)
