### ISSUE TITLE
Duplicated category suggestions

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#1550]
**Summary:** 

Categories suggestion contains duplicates

**Steps to reproduce:** 

In the categories sggestions screen, search for "oculus go"
 
 **Commons app version:** 

2.7.1-debug-search_activity_mock~27e5e9c7

**Screen-shots:** 

![screenshot_20180510-201423](https://user-images.githubusercontent.com/99590/40482984-7132960e-5f91-11e8-96a8-ffe6f4669a3c.png)

**Would you like to work on the issue?**

Not especially

**Comment by gupta1anubhav** [comment]
@nicolas-raoul I have figured out the issue and I am working on it.

**Comment by nicolas-raoul** [comment]
Could you please post what the Mediawiki API sends?
I suspect that the API does not send duplicate, and the app has a kind of bug that creates duplicates.
If it is the case, then we should fix the bug rather than add de-duplication.
Thanks! :-)

**Comment by gupta1anubhav** [comment]
Sorry @nicolas-raoul I am not able to find what Mediawiki API sends if you could help that would be great
In my opinion, duplicates could be because we are merging results from search categories and all categories on the same string.

**Comment by whym** [comment]
@gupta1anubhav To make sure, you might want to try temporarily inserting ` Log.d("API.searchCategories", categories.toString());` into somewhere around
https://github.com/commons-app/apps-android-commons/blob/7f02524522b24fdabf3d9a144ad1264e39336292/app/src/main/java/fr/free/nrw/commons/mwapi/ApacheHttpClientMediaWikiApi.java#L335
(same goes for `allCategories`)

**Comment by nicolas-raoul** [comment]
Yes, some debug would be great to find out where the duplicates come from.
I understand that some duplicates may appear from time to time, but often it is the same long list of categories repeated exactly.

**Comment by nicolas-raoul** [comment]
Still happening in 2.9.0:
![screenshot_20181203-220219](https://user-images.githubusercontent.com/99590/49444003-41fc8200-f811-11e8-8dd5-70e7f3dcc6a8.png)

**Comment by ashishkumar468** [comment]
AFAIK, it was fixed in some previous releases, must have been brought back while introducing RX. Have added a fix, will raise a pr soon.
