### ISSUE TITLE
Allow users to easily re-upload failed uploads, and provide reasons for failure where possible

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#1556]
Suggestion on our FB page:

> Is it difficult to have the "failed" uploads easily re-uploadable? :)

Thoughts? This would be a useful enhancement IMO, but not sure how easy/feasible implementation will be since there are all sorts of reasons why uploads fail.

**Comment by neslihanturan** [comment]
Isn't it already one click?

**Comment by nicolas-raoul** [comment]
@neslihanturan One click on what? I have a failed upload and I don't know how to re-upload it. Is it the rounded "Back" arrow in the upper right? This icon usually means "Cancel", so I am afraid it would loose the image+metadata I entered.

**Comment by misaochan** [comment]
@neslihanturan Do we already have a method of reuploading failed images? This is news to me! 

To clarify, I think the suggestion meant a sort of "retry" button on the failed upload in Contributions screen.

**Comment by misaochan** [comment]
@neslihanturan Oh wow, I had no idea LOL! That's actually great, that means we can reuse the logic. I definitely think the button should be in contributions activity, not just in media details. Perhaps in the lower right corner of any failed upload?

**Comment by neslihanturan** [comment]
Actually current one looks like email redirect button to me:D So definitely we should change it. We should add it to contrib activity, I agree @misaochan . Besides, we should check functionality (as I said I never experienced it worked). Ideally it can give possible fail cause if we found any (such as your account blocked or weak internet connection snackbar) .

**Comment by misaochan** [comment]
@neslihanturan Agreed, we should try and display more informative messages when an upload fails. Although that does depend on how much information we can get from the server about the fail cause to begin with.

**Comment by VojtechDostal** [comment]
I remember this worked for me at least once. The reason behind the fail was loss of internet connection *during* upload.

**Comment by misaochan** [comment]
For this task, additionally, I think if a badtoken error is obtained, we can suggest to the user that they try logging out and in again. That seems to always work, and may help users who are stuck with failures.

(Of course, this isn't the ideal situation, but it could tide us over until we can overhaul the auth flow)
