### ISSUE TITLE
Dex archives: setting .DEX extension only for .CLASS files

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#1563]
**Summary:** 

I frequently encounter the error "Dex archives: setting .DEX extension only for .CLASS files" when trying to build in AS. Cleaning and rebuilding solves the issue, but wastes a lot of time as it happens so frequently.

**Steps to reproduce:** 

Build in AS from various branches with different build variants.

**Add System logs:**

Dex archives: setting .DEX extension only for .CLASS files

**Device and Android version:** 

All
 
 **Commons app version:** 

All recent ones including master

**Would you like to work on the issue?**

Preferably not

**Comment by domdomegg** [comment]
Does this still happen often in Android Studio 3.2.1?

**Comment by misaochan** [comment]
Has not happened recently, actually! Not sure if it's due to AS update or our own code changes. Tentatively closing. :)
