### ISSUE TITLE
Featured pictures: Show in recency or random order, rather than alphabetical order

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#1564]
Currently, featured pictures are shown in alphabetical order.

As a consequence, users will always see the same pictures.
In particular, nobody will ever see all of the featured pictures that do not start with a quote or digit character.
This is boring for users, they will not scroll featured pictures twice. Even in one year the pictures show will be the same, with 1 or 2 exceptions maybe among hundreds of pictures scrolled.

Solution: Rather than displaying in alphabetical order, show in either (only implement one, whichever you find easiest or have a personal preference for):
- Order of recent upload
- Order of recent nomination
- Or random

The order must be passed in the API request. Ordering results after receiving a result page is not a good solution.

**Comment by neoliteconsultant** [comment]
I start working on this

**Comment by nicolas-raoul** [comment]
@neoliteconsultant Thanks! :-)

**Comment by neoliteconsultant** [comment]
Hey @nicolas-raoul 

How do I get the featured images to show for the commons beta app? At the moment I am unable to test

**Comment by maskaravivek** [comment]
The featured images category on the commons beta site has no images, that’s why the list is showing as empty. Am not sure how to get an image featured for testing. :(

**Comment by misaochan** [comment]
Is there a need to test featured images on beta, though? Beta build variant is mostly only needed if you need to upload a lot of nonsensical pictures for testing, which doesn't appear to be necessary for this.

**Comment by nicolas-raoul** [comment]
I does not seem to work, unfortunately.
The featured images are still listed in alphabetical order.

**Comment by neoliteconsultant** [comment]
@nicolas-raoul did you check the upload times of the featured images?

**Comment by nicolas-raoul** [comment]
@neoliteconsultant Yes, here are the upload times of the first images that appear, in order:

1. 1 June 2016 https://commons.wikimedia.org/wiki/File:%22Broke,_baby_sick,_and_car_trouble!%22_-_Dorothea_Lange%27s_photo_of_a_Missouri_family_of_five_in_the_vicinity_of_Tracy,_California.jpg
2. 30 June 2016 https://commons.wikimedia.org/wiki/File:%22Chuveir%C3%A3o%22_na_Caverna_Timimina.jpg
3. 27 January 2005 https://commons.wikimedia.org/wiki/File:%22The_School_of_Athens%22_by_Raffaello_Sanzio_da_Urbino.jpg
4. 6 February 2015 https://commons.wikimedia.org/wiki/File:%27One_of_the_wards_in_the_hospital_at_Scutari%27._Wellcome_M0007724_-_restoration,_cropped.jpg
5. 1 December 2015 https://commons.wikimedia.org/wiki/File:0_A.D._Alpha_12_Loucetios.webm

As you can see, the upload dates do not impact how the images are ordered.

**Comment by neoliteconsultant** [comment]
@nicolas-raoul ok I will resolve it ASAP

**Comment by nicolas-raoul** [comment]
@neoliteconsultant Thanks a lot :-)

**Comment by nicolas-raoul** [comment]
This works great now, thanks :-)
