### ISSUE TITLE
Search Image History

### ISSUE THREAD

**Issue by ujjwalagrawal17** [commons-app/apps-android-commons#1569]
**Summary:** 
This is an enhancement to #1521 (Search Images feature)
When the user touches the search icon in explore tab they see a blank screen. Instead, we can show the search history on the screen.

 **Commons app version:** 
2.7.1-debug_rename_featured-df82383

**Screen-shots:** 

![screenshot_20180528-125309](https://user-images.githubusercontent.com/19607555/40700734-6f3e1920-63f8-11e8-80d3-fc1cd120878e.png)

**Would you like to work on the issue?**
Yes, I have already started working on this issue. I will send a PR soon for this feature.

**Comment by nicolas-raoul** [comment]
That would be great indeed :-)

**Comment by ujjwalagrawal17** [comment]
This feature is added.
