### ISSUE TITLE
"Error occurred while loading images" on empty search

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#1571]
**Steps to reproduce:** 

1. Open search
2. Type some long random word

**Expected behavior:** 

Empty results

**Observed behavior:** 

Error message is displayed.

Also, "null" should probably be the search string?

 **Commons app version:** 

2.7.1-debug-rename-featured

**Screen-shots:** 

![screenshot_20180531-210051](https://user-images.githubusercontent.com/99590/40781289-473ed922-6516-11e8-98f4-43c8ebd535b9.png)

**Comment by ujjwalagrawal17** [comment]
Yes, I also noticed this issue. I will fix this issue.

**Comment by nicolas-raoul** [comment]
null problem is fixed, thanks :-)

**Comment by nicolas-raoul** [comment]
@sivaraam Yes I switch branches and build every time.
There is a beta version but it is only updated every month or so. This could make beta more up-to-date: #1056
The current situation is even more complex since most development is taking place in two branches rather than on master. I think these two branches should be merged to master as often as possible, but that's sometimes not possible when they break things too much.

**Comment by ujjwalagrawal17** [comment]
@nicolas-raoul What should I show in snackbar? Do we need to show the same message at No Image text view?

**Comment by nicolas-raoul** [comment]
No snackbar is needed when no match is found.
The "No images [...] found" text view is enough :-)

**Comment by ujjwalagrawal17** [comment]
Ok I will fix it.

**Comment by ujjwalagrawal17** [comment]
@nicolas-raoul Issue is fixed so we can close this issue now.

**Comment by ujjwalagrawal17** [comment]
@nicolas-raoul.

**Comment by nicolas-raoul** [comment]
Thanks! :-)
