### ISSUE TITLE
"No images matching" message does not really disappear when performing new another search

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#1572]
**Steps to reproduce:** 

1. Open search
2. Type some long random word
3. As expected, the "No images matching" message appears
4. Now erase and type "nice"
5. Results appear
6. Scroll fast downward
7. Under the non-yet loaded images, you can see the error message left from step 3

 **Commons app version:** 

2.7.1-debug-rename-featured

**Screen-shots:** 

![screenshot_20180531-210925](https://user-images.githubusercontent.com/99590/40781543-3a91440c-6517-11e8-94db-2439ab5d2e28.png)

**Comment by ujjwalagrawal17** [comment]
Yup, I also tested this issue is there. thanks for telling I will fix it.

**Comment by nicolas-raoul** [comment]
Fixed, thanks!
