### ISSUE TITLE
Search results sometimes appear twice

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#1580]
It is hard to replicate, but I had this happen yesterday and today after editing the search string for 10 minutes.

Yesterday I got a search with 50 results, but the 25 last were the same as the 25 first.
Today I got the same result twice. Strangely the result does not even match the search string. Also I know that Commons contains an image that matches this search string, but it is not the image that appears.

**Comment by ujjwalagrawal17** [comment]
Umm, I am not sure about this issue but I am adding pagination in search now. So your second query of not finding image will be solved.

**Comment by ujjwalagrawal17** [comment]
@nicolas-raoul Pagination is added. Can you check if it still exists? I am unable to reproduce it.
