### ISSUE TITLE
Build failed: Could not find common.jar

### ISSUE THREAD

**Issue by dlsrks1021** [commons-app/apps-android-commons#1607]
**Summary:** 

Without change any code, I could not build android.

**Steps to reproduce:** 

I just clone and run 'gradlew.bat assembleDebug' on windows.

 **Commons app version:** 

2.7.1-debug-master~db5d732a

**Screen-shots:** 

![41192331-003a2df6-6c37-11e8-941c-9acad8c5c320](https://user-images.githubusercontent.com/26715094/41194114-d265cc4e-6c51-11e8-9b2a-64bb5cb1d24c.png)

**Would you like to work on the issue?**

I searched this problem and the answer of this problem is moving 'jcenter()' after maven in build.gradle file.
After moving 'jcenter()' I could build success.

I don't know how to build success without moving jcenter.

**Comment by domdomegg** [comment]
Try `cd`ing into the `/app` folder and running `gradlew.bat assembleDebug` from there. If this works tell me and I'll update [the wiki](https://github.com/commons-app/apps-android-commons/wiki/Build-Manually).

Also, it's usually much easier to use [Android Studio](https://github.com/commons-app/apps-android-commons/wiki/Develop-with-Android-Studio-or-IntelliJ)

**Comment by neslihanturan** [comment]
Seems like solved.
