### ISSUE TITLE
Change target API to 26

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#1611]
Needs to be done by Nov 2018. From Play Store developer console:

> Warnings
> Your app currently targets API level 25 and must target at least API level 26 to ensure it is built on the latest APIs optimised for security and performance.
> 
> From August 2018, new apps must target at least Android 8.0 (API level 26).
> From November 2018, app updates must target Android 8.0 (API level 26).
> 
> Tip: Change your app's target API level. Learn how.

**Comment by whym** [comment]
Any more details on how to do that?

It appears to be already 27 in the app's config. Am I looking at the wrong place? https://github.com/commons-app/apps-android-commons/blob/2cfbb67f1c67113fb0b37d141ca557c8a924fee7/app/build.gradle#L91
https://github.com/commons-app/apps-android-commons/blob/2a0b9d8a0bac0116fc442f4b43fcf0a09df5ae85/gradle.properties#L22

**Comment by domdomegg** [comment]
Think we have been using targetSdkVersion 27 since v2.7.0

Updated in [`2a0b9d8`](https://github.com/commons-app/apps-android-commons/commit/2a0b9d8a0bac0116fc442f4b43fcf0a09df5ae85#diff-503f218d646c10f484fdc9d6315bf2e3R22)

**Comment by misaochan** [comment]
Yep. :)
