### ISSUE TITLE
Redacting unwanted location information from file pages

### ISSUE THREAD

**Issue by whym** [commons-app/apps-android-commons#1613]
*This will not be done in Android code but a (Python) script that works on Wikimedia Commons. Comments are welcome. I plan to work on this alone, but if someone is interested, please contact me. (Since it's a one-off job and contains potentially sensitive data collected, I don't want to publish it in the repo.)*

In #1599 we agreed to redact file pages that contain location information published inadvertently. I'm working on redacting the information from file pages.

* [x] Create a list of the file pages whose first version contain a location template but no EXIF-embedded GPS data. (and categorized as uploaded via the app)
* [x] Create a list of the revisions where the first location information remains in those file pages
* [x] Prepare a sysop bot to perform the redaction (and get approval)
* [x] Edit and remove the first location information where it still remains in the latest version of the page
* [x] Redact the revisions from non-sysops
* [ ] Ask oversighters of Wikimedia Commons to redact the revisions from sysops (unnecessary?)
* [ ] Do above again for new (post-June) uploads
* [ ] Create a list of affected people and files and send a [mass message](https://www.mediawiki.org/wiki/Help:Extension:MassMessage).

So far, it appears to involve 938 pages, 3294 revisions and 351 users.

**Comment by whym** [comment]
I submitted https://commons.wikimedia.org/wiki/Commons:Bots/Requests/Whymbot. Inputs are welcome. (As always, this is not a vote and we don't exactly need a large number of "supports".)

**Comment by sivaraam** [comment]
Is this done now? I saw the related [incident wiki page](https://github.com/commons-app/documentation/blob/master/android/June-2018-incident.md) and found the status of this as "on going".

**Comment by whym** [comment]
Almost. But I never managed to work on the last item (mass message) mentioned above. It would have been nicer to do that, but after more than one year, I suspect it might be merely confusing than helpful to the receivers of such a message now. I can still try doing that, though.

**Comment by sivaraam** [comment]
@whym You are right. I too believe it would be merely confusing if we do it now.

Do you think we can just mention that we never did the mass message part in the [incident wiki page](https://github.com/commons-app/documentation/blob/master/android/June-2018-incident.md) and close this as done?

**Comment by misaochan** [comment]
@sivaraam I think that makes sense, and we can probably point to the discussion on this thread for the reason, too.

**Comment by sivaraam** [comment]
> @sivaraam I think that makes sense, and we can probably point to the discussion on this thread for the reason, too.

Done. I've created https://github.com/commons-app/documentation/pull/12 for this.

**Comment by whym** [comment]
@sivaraam Thanks a lot. I'll close this as well.

(Another thing - I never got a response from my request for oversight (which is like deletion of a higher level) by email. The last message I got was an automated one saying my email "awaits moderator approval". I think not oversighting is a reasonable outcome, as it's only for severe cases.)
