### ISSUE TITLE
Throbber visible below loaded images

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#1630]
Not a big problem, but if there was an easy way to fix that, it would be great :-)

1. Go to featured images activity
2. Touch a picture to see its details
3. Press Back
4. You can see the throbbler (blue circle rolling) in the interstice between the two images, for like 1 or 2 seconds.

![screenshot_20180614-171236](https://user-images.githubusercontent.com/99590/41399797-3691a9d4-6ff6-11e8-878d-f3ddc1cefc2e.png)

**Comment by ujjwalagrawal17** [comment]
@nicolas-raoul Should we show the progress bar above the images? That would be better.

**Comment by nicolas-raoul** [comment]
The problem is the blue circle that you can see between two images in the middle of the screenshot above.
We should do like other similar apps, for instance Facebook. I believe that a user who scrolls slowly never sees a throbber or progress bar. A throbber could be shown only if the user scrolls faster than images load.

**Comment by neslihanturan** [comment]
It is not visible anymore :)
