### ISSUE TITLE
Viewing a search result looses scroll position

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#1631]
People who are looking for an image will probably:

1. Search for a string
2. Scroll until they see an image they might like, then view it, maybe download it if it is good, or otherwise:
3. Continue scrolling until they see an image they might like, then view it, maybe go back to scrolling
4. Etc, until they have found enough good images to be satisfied.

Problem: Currently, after viewing an image and pressing "Back", you are sent again to the top of the searches. So you have to scroll again to the position you had reached before.

**Comment by seannemann21** [comment]
I can take this! Do you also want to save the scroll position within the Explore tab and my recent uploads?

**Comment by seannemann21** [comment]
I seem to have gotten it working with the search result scroll bar, but if you knew the name of the fragment/activity that contains the recycler view for the Explore tab then that would be very helpful! I'll keep looking

**Comment by nicolas-raoul** [comment]
It seems that the problem is not fixed unfortunately, at least on my Android 7.1.2.
In Explore:
- Scroll down
- Tap on a image
- Press Back
- Position is lost, now at top

**Comment by misaochan** [comment]
@seannemann21 Sorry for the lack of clarity - the browse-commons branch is actually a GSoC project currently being worked on by @ujjwalagrawal17 . It is probably best for you to work on issues that do not refer to this branch. :)

**Comment by seannemann21** [comment]
Whoops sorry I meant i had it fixed locally on my machine, and ok I'll look for something else!
