### ISSUE TITLE
Crash when clearing search history twice

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#1633]
Steps:

1. Go to the search activity
2. Press the X to remove history
3. Confirm
4. Again, press the X to remove history
5. Confirm
6. Crash

**Comment by juniaziz** [comment]
I tried going to the search activity but couldn't get to it. May I know the flow to get there? 

P.s. I have not started working on it yet. Checking if I can handle it or not.

**Comment by nicolas-raoul** [comment]
@juniaziz You have to install this APK: https://drive.google.com/file/d/1THe_I3PRixktLQcOSMMvzymLhHN6_ERq/view?usp=sharing

**Comment by ujjwalagrawal17** [comment]
@juniaziz You can checkout to browse-commons-via-app branch and built APK on your local PC as well.

**Comment by nicolas-raoul** [comment]
Tested, thanks :-)
