### ISSUE TITLE
Add search categories from commons feature

### ISSUE THREAD

**Issue by ujjwalagrawal17** [commons-app/apps-android-commons#1639]
This is a child issue of #1221  

**Summary:** 

The users should be able to search categories directly using name/description from commons.

**Screen-shots:** 

<table>
<tr>
<td>

![screenshot_20180619-135827](https://user-images.githubusercontent.com/19607555/41585893-f57961fe-73c8-11e8-9f8b-cd39d126f115.png)

</td>
<td>

![screenshot_20180619-135620](https://user-images.githubusercontent.com/19607555/41585898-fc42f2c0-73c8-11e8-91b0-ebfc36325b56.png)

</td>
<td>

![screenshot_20180619-135625](https://user-images.githubusercontent.com/19607555/41585896-fafcce4a-73c8-11e8-8170-d72a4fb69279.png)

</td>
</tr>
</table>

**Would you like to work on the issue?**
Yes, I have worked on this issue.

**Comment by nicolas-raoul** [comment]
Looks great!
Just a note: How about renaming "Images" to "Media", as it also includes sounds for instance? :-)
