### ISSUE TITLE
Add a category details page in app

### ISSUE THREAD

**Issue by ujjwalagrawal17** [commons-app/apps-android-commons#1642]
This is a child issue of #1221  
**Summary:** 
- The user should be able to view a category details page after searching categories / clicking on a particular category from a specific media.
- The details page should contain images, subcategories, (optional) link (icon to go to browser category page).

**Would you like to work on the issue?**
Yes, I will start working on this issue.

**Comment by nicolas-raoul** [comment]
What do you plan to show on a category details page?

I think it should at least contain:
- Child categories
- media in that category

Maybe the parent categories too? That is very useful when a category does not contain enough images.

**Comment by ujjwalagrawal17** [comment]
I was planning for child category, media inside the category. Yup getting parent category would be a good option. I need to think of a Good UI for this.

**Comment by ujjwalagrawal17** [comment]
This is added.
