### ISSUE TITLE
Category search does search for my whole string

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#1650]
1. I typed "apple"
2. I got the results for "app"
3. The "MEDIA" tab is OK, though, showing pictures of apples.
4. Adding another letter then removing it solves the problem

Difficult to reproduce. 

![screenshot_20180621-221817](https://user-images.githubusercontent.com/99590/41721747-bc305e72-75a1-11e8-9e9e-b5cbf9c2e977.png)

**Comment by ujjwalagrawal17** [comment]
The search works fine most of the time. I think this is a very rare issue. Maybe due to Searchview it is showing wrong sometimes.

**Comment by nicolas-raoul** [comment]
I have not seen this for a while, I will reopen if I observe it again.

**Comment by DeepaMalani** [comment]
Hi Nicolas,

I tried to reproduce this issue to figure out what is the reason and I found below reason for this issue.

When I want to search **apple**  but before finishing the writing **apple** loader starts to fetch the data from the server with just two or three letters (because of little dealy in my typing) it displays wrong results.

For example 
1. I typed **app**  and loader started to fetch the data because of little delay in typing **le**
2. Before finishing the loader(which fetching the data for **app**) I completed the text and wrote **apple **. 
3. Now the results will be wrong.

I wanted to work on this issue.
Could you please assign it to me?

Regards,
Deepa

**Comment by ashishkumar468** [comment]
Hi Deepa, Feel free to pick the issue. It is yours :-)

**Comment by DeepaMalani** [comment]
Thanks Ashish :)

**Comment by DeepaMalani** [comment]
Hi Ashish,

Below are the steps to reproduce it.
For example I want to get the result for Apple

1. Type **app** and let the loader starts
Here is the screen shot

![App_Screenshot](https://user-images.githubusercontent.com/24900514/68237732-8e6db600-ffbc-11e9-8acf-b3700bddc9ae.png)

2. Once loader starts **immediately** type remaining letters for example "le" in my case.

![Apple_Screenshot](https://user-images.githubusercontent.com/24900514/68237843-db518c80-ffbc-11e9-9614-9ec63e88146a.png)

3. Now see the result. The result is not for **Apple**

**Comment by nicolas-raoul** [comment]
@DeepaMalani Thanks for reproducing! Now please run the app in debug mode and see why the previous search is not aborted when the user type another letter :-)

**Comment by DeepaMalani** [comment]
Hi Nicolas,
I ran the app in debugging mode and figured out that the previous search will be aborted if the API call to fetch the results haven't started for the previous search, but once the API call starts we can not send the latest search text midway to API.  

The solution which I think will work is once the API call starts let it finish to fetch ing the data and after that send the latest search query to API.

**Comment by nicolas-raoul** [comment]
Thanks for the investigation!
Are you working on implementing the fix? 🙂

**Comment by DeepaMalani** [comment]
Hi Nicolas,

I have worked on this issue and already have submitted a pull request for this issue (#3200 ).

**Comment by Ayan-10** [comment]
@nicolas-raoul Is this issue still exists now? I tried several times but can't reproduce it.

**Comment by nicolas-raoul** [comment]
It is very hard to reproduce.
I haven't seen it for a long time, so I will close for now, but please anyone comment if you get this issue, thanks!
