### ISSUE TITLE
Ghost "No categories matching" message

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#1652]
explore categories branch

1. In category tab, search for "banana"
2. In category tab, search for "owrgowirg"
3. Message "No categories matching owrgowirg found" appears
4. Press X
5. Recent searches appear
6. Press "banana"
7. Message "No categories matching owrgowirg found" appears, with throbble on top of it

Expected: At step 7, the message should not appear

**Comment by ujjwalagrawal17** [comment]
Same issue was in image search.

**Comment by nicolas-raoul** [comment]
@ujjwalagrawal17 still  present with this latest commits:
![screenshot_20180622-200511](https://user-images.githubusercontent.com/99590/41773660-ce080b7a-7657-11e8-831e-13e270a21b6c.png)

**Comment by nicolas-raoul** [comment]
Thanks!
