### ISSUE TITLE
[browse-commons-via-app] Recent categories aren't added properly

### ISSUE THREAD

**Issue by neslihanturan** [commons-app/apps-android-commons#1656]
**Summary:** 

Correct recent categories aren't added without clicking back button first.

**Steps to reproduce:** 

Search for some categories, then they won't be added to recent list. Then click on back button on left top, click to search button again, you will see your recent categories there.

**Comment by ujjwalagrawal17** [comment]
They are getting added if you stay in search screen for at least 5 seconds. Otherwise, they are not getting added.

**Comment by neslihanturan** [comment]
But they appear after clicking back button and coming back to search field again. Ideally they should be added after we search, nothing to do with back button

**Comment by mandylk** [comment]
Hi @neslihanturan please may I work on this issue?

**Comment by neslihanturan** [comment]
Sure @mandylk , go for it:)

**Comment by nicolas-raoul** [comment]
@lkmandy Any progress on this issue? :-)
If you don't intend to work on it anymore, please let us know and we will unassign it.
Even if you don't have code to submit, your findings and ideas are welcome :-)

**Comment by neslihanturan** [comment]
This issue is outdated, now all of my searches are added immediately.
