### ISSUE TITLE
Setting text is truncated when space is not available

### ISSUE THREAD

**Issue by sivaraam** [commons-app/apps-android-commons#1670]
**Summary:** 
The settings text should not be truncated when space is not available as that leaves users with partial information which they cannot use to judge what the setting is actually for. This is especially a major issue for non-English languages where the translation might be longer and eventually gets truncated.

**Steps to reproduce:** 
1. Go to the Settings page on a small screen device

**Expected behavior:** 
The Settings text for 'Automatically get current location' should not be truncated.

**Observed behavior:** 
Part of the settings text is truncated.

**Device and Android version:** 
Samsung Galaxy j1 ace (5.1.1, 4.3")
 
**Commons app version:** 
2.7.2

**Screen-shots:** 
![screenshot_2018-06-27-19-38-15](https://user-images.githubusercontent.com/12448084/41979958-eeab5e42-7a42-11e8-94bb-a3636de73453.png)

**Would you like to work on the issue?**
No

**Note**
There was a [similar issue in the Wikipedia app](https://phabricator.wikimedia.org/T192637) which [recently got fixed](https://gerrit.wikimedia.org/r/#/c/apps/android/wikipedia/+/427907/).

**Comment by seannemann21** [comment]
I submitted a pull request! I didn't even notice the note at first, but still ended up fixing it the same way haha
