### ISSUE TITLE
Trim File: and Category: from filenames when displaying

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#1677]
Trim File: and Category: from filenames when displaying

**Comment by ujjwalagrawal17** [comment]
Yup nice. I will do it. Just a doubt should we trim only on search results or for details page also in media details and category details?

**Comment by nicolas-raoul** [comment]
Everywhere, I would say. 
Media and categories are always shown in a very different way (media have a thumbnail while categories do not) so there is no ambiguity.
