### ISSUE TITLE
Coordinates / no coordinates indicator on upload screen

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#1687]
When my camera takes a picture, there is a small globe indicating whether I currently have a GPS fix or not.

It would be great if such an indicator was present on the upload screen too.

Cases where it would be useful:
- I took 10 pictures of a building, and when I start writing the title I realize that GPS info is not available. So I choose another of the 10 picture, with GPS info (when taking 10 pictures very often some picture have GPS info and some not)
- I take a picture of a rare 17th century book I have at home. When I start writing the title I realize that GPS info has been recorded. So I go back and pass the picture through Scrambled Exif before sharing it to the Commons app.

**Comment by ilgazer** [comment]
We could even take this a step further and make it so that clicking the "Location data present" button opens some kind of interface to edit the EXIF data.

**Comment by nicolas-raoul** [comment]
Yes great idea!
That would allow people to remove location data if they desire.

Even better, when clicking the "Location data NOT present" icon, this could open a map where I can choose the point manually (see #8)

**Comment by NotSoImportant** [comment]
@nicolas-raoul as far as I see there is a map icon shown now when an image has coordinates.

**Comment by nicolas-raoul** [comment]
@NotSoImportant You are right, thanks for noticing! 🙂
