### ISSUE TITLE
"Finishing uploading" not finished after an hour

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#1688]
On @maskaravivek 's wikidataTest branch.
Two images were uploaded correctly (and the Wikidata properly set) but the third does not seem to finish. It is still running right now, so if there is any way I can give you more debug information please ask me :-)
All images uploaded via Nearby->Gallery

![screenshot_20180703-152009](https://user-images.githubusercontent.com/99590/42201951-bf314640-7ed4-11e8-951e-8ef1ccc413bd.png)

Actually the image has been uploaded but not categorized and not linked from Wikidata:
https://commons.wikimedia.org/wiki/File:%E8%AA%BF%E5%B8%83%E5%B8%82Green_Hall_3.jpg
https://www.wikidata.org/wiki/Q11631740

**Comment by livemusicbangla** [comment]
Media wiki uploaded file

**Comment by nicolas-raoul** [comment]
Reproduced again today (one year later!) on the GSoC 2019 branch, not sure if it is the same bug but it is the same symptom:
![adb-screenshot](https://user-images.githubusercontent.com/99590/59988970-07a4e600-9678-11e9-9e22-642a725c3903.png)
[logcat5.txt](https://github.com/commons-app/apps-android-commons/files/3319059/logcat5.txt)

**Comment by ashishkumar468** [comment]
The upload service has been refactored, the issue was the notifications not being updated properly, I verified that this does not happen on the master. Closing this issue, feel free to re-open if someone is able to reproduce this again
