### ISSUE TITLE
App crashes when storage permission is not given and user tries to share a single image from gallery

### ISSUE THREAD

**Issue by VaishSiddharth** [commons-app/apps-android-commons#1694]
**Summary:** 

App crashes when storage permission is not given and user tries to share a single image from gallery

**Steps to reproduce:** 

Do not give storage permission.
Open gallery
Share a single image using "commons" app

**Device and Android version:** 
Xiaomi Mi A1 (Android 8.0.0, API 26)
 
 **Commons app version:** 

2.7.2-debug-master~fa6353b3

**Screen-shots:** 

![screenshot_20180707-224539](https://user-images.githubusercontent.com/36266597/42413138-b0626d72-8237-11e8-9567-294f5fe5aa83.png)
![screenshot_20180707-224550](https://user-images.githubusercontent.com/36266597/42413142-b880d07a-8237-11e8-83a9-2ff5e0d9b510.png)
![screenshot_20180707-224620](https://user-images.githubusercontent.com/36266597/42413143-bc4cd6c2-8237-11e8-9129-828a37366562.png)

**Would you like to work on the issue?**

I want to work on this.

**Comment by ninad458** [comment]
I would like to take this one. I am a beginner contributor though. So a summary might help.

**Comment by VaishSiddharth** [comment]
@ninad458 This issue already has a pull request so I don't think you need to work on this.

**Comment by ashishkumar468** [comment]
Seems to be very old and handled in the latest commits, closing this issue
