### ISSUE TITLE
Use author's name from Preferences if available

### ISSUE THREAD

**Issue by Vesihiisi** [commons-app/apps-android-commons#1707]
In my Preferences on Commons I can set a personalized string to be used in the author field of my photos (Preferences → Upload wizard → Author's name). It would be nice if the app could apply it as well. I know some users prefer to use their full name there rather than their username.

**Comment by cvhariharan** [comment]
I would like to give it a try.

**Comment by maskaravivek** [comment]
It would be a nice little feature in the app. :)

**Comment by cvhariharan** [comment]
I have created  a pull request. #1856
