### ISSUE TITLE
Alignment of language selection dialog in About>Translate

### ISSUE THREAD

**Issue by VaishSiddharth** [commons-app/apps-android-commons#1713]
**Summary:** 

The drop down menu in translate does not looks good.

**Steps to reproduce:** 
1. Go to About
2. Tap on Translate
3. See the drop down menu

**Device and Android version:** 

Xiaomi Mi A1 (Android 8.0.0, API 26), with 2.7.2-debug-master~fa6353b3
 
**Screen-shots:** 

![screenshot_20180714-010003](https://user-images.githubusercontent.com/36266597/42710475-d3607926-8701-11e8-9098-6b01242df665.png)

**Would you like to work on the issue?**

I will try to fix this issue

**Comment by VaishSiddharth** [comment]
@nicolas-raoul This issue need to be worked on i hope.

**Comment by nicolas-raoul** [comment]
What do you suggest to make it look better?

**Comment by VaishSiddharth** [comment]
There is some text which is right aligned so it should be aligned to the left side.
![screenshot_20180715-231905](https://user-images.githubusercontent.com/36266597/42736485-c69c7dcc-8885-11e8-90dd-d86f2f663ba4.png)
The word (Kazakh) is not aligned properly. I mean its too much on the left side this should also be properly aligned.
![screenshot_20180715-231955](https://user-images.githubusercontent.com/36266597/42736486-c6d52654-8885-11e8-91d8-d11a6c832eca.png)

**Comment by VaishSiddharth** [comment]
@nicolas-raoul I think it looks synchronized if we align all languages LTR otherwise its looks as if its an issue rather than intentionally done. May be centrally aligned solves this confusion.

**Comment by nicolas-raoul** [comment]
I agree that centrally aligned may be the best.

**Comment by misaochan** [comment]
> If the app is currently in LTR, then align all language items (including the ones about languages that are usually RTL) to the left.

Sounds like the best solution to me. I agree with the poster who said that left-aligning RTL languages for very short phrases isn't usually an issue.

**Comment by VaishSiddharth** [comment]
@misaochan So should i align all the languages to the left?

**Comment by misaochan** [comment]
Lets wait for @nicolas-raoul to get back to us, shall we? :)

**Comment by nicolas-raoul** [comment]
@VaishSiddharth could you please implement as described in my comment https://github.com/commons-app/apps-android-commons/issues/1713#issuecomment-405823136 ? Thanks! :-)

**Comment by VaishSiddharth** [comment]
@nicolas-raoul @misaochan  Please have a look at the screenshots. Should i send a pull request?

![screenshot_20180719-224008](https://user-images.githubusercontent.com/36266597/42959016-f429dfe2-8ba4-11e8-92c6-f2128c6ad4e2.png)
![screenshot_20180719-224017](https://user-images.githubusercontent.com/36266597/42959017-f4672a6e-8ba4-11e8-8ea6-84b7b1aa234d.png)

**Comment by misaochan** [comment]
I think @nicolas-raoul meant that the alignment should depend on the alignment of the language that the user is currently using? However, IMO your current code is an improvement to the existing state anyway, as the lack of alignment makes scanning the dropdown list really difficult. So you could submit a PR with that first, but we can keep this issue open so that an enhancement for RTL languages can be put in later.

**Comment by VaishSiddharth** [comment]
@misaochan Ok

**Comment by VaishSiddharth** [comment]
@misaochan By mistake I have commited this improvement with a branch which I had already used in a Pull request previously #1695. Please tell me what to do. Should I make a new pull request now? Or add in the description of that pull request about this improvement.

**Comment by misaochan** [comment]
I would make a new PR, as they are fixing very different issues.

**Comment by VaishSiddharth** [comment]
@misaochan Do I have to do anything?

**Comment by misaochan** [comment]
Yes, please separate your PRs based on the issue they are solving. So these improvements should not be in #1695 . There are a number of ways to do this - for instance, you could use git cherry-pick on another branch and then resubmit your #1695 PR via that branch with only the relevant commits, and then do the same for the commits fixing this issue (with a different PR).

**Comment by VaishSiddharth** [comment]
@misaochan Ok I will do it.

**Comment by VaishSiddharth** [comment]
@misaochan I have created a new PR please have a look.
