### ISSUE TITLE
Prevent uploading media that already exists on Commons

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#1732]
The app currently allows to upload a picture twice. Actually, I have uploaded some pictures 3 times because I could not remember whether I had uploaded yet or not.

Before starting the upload (possibly when entering the title/description), the app should check whether the picture has been already uploaded or not, using [this](https://opendata.stackexchange.com/questions/5279/live-database-of-checksums-of-all-files-on-wikimedia-commons/7314#7314).

If the picture exists already on Commons, the app should tell the user and go back to the previous activity.

**Comment by AmineToualbi** [comment]
Hi, I'm new to open-source contributing. 

Do you think it'd be a nice task for a first-timer?

**Comment by nicolas-raoul** [comment]
If you know a bit of Android or Java programming then yes, I think so :-)

**Comment by nicolas-raoul** [comment]
@misaochan I certainly have uploaded many duplicates with recent versions of the app, for instance this one: https://commons.wikimedia.org/w/index.php?title=File:%E8%AA%BF%E5%B8%83%E5%B8%82Green_Hall_3.jpg&redirect=no
So I guess some investigation is needed, as you wrote.

**Comment by misaochan** [comment]
@nicolas-raoul By "recent versions" do you mean the Play Store versions, or only the builds from the repo?

**Comment by nicolas-raoul** [comment]
I meant build from the repo, in particular the browse branch, but I don't think the browse branch is different from 2.8-release in that respect.
The first thing would be to try and reproduce the problem using the 2.8-release branch from Git. @AmineToualbi

**Comment by misaochan** [comment]
Secondly I would test the Play Store version (2.7) to see if the problem exists there too. If it doesn't, then we know roughly when the issue was introduced. :)

**Comment by AmineToualbi** [comment]
So, [this](https://github.com/commons-app/apps-android-commons/pull/336/commits/b5ccc36a77cf8973725714dc95ceb42fc4747dc6) doesn't work?

**Comment by nicolas-raoul** [comment]
@AmineToualbi Apparently not, strangely. The best would be to download [a file that already exists](https://upload.wikimedia.org/wikipedia/commons/f/f9/%E8%AA%BF%E5%B8%83%E5%B8%82Green_Hall_2.jpg) and reupload it while debugging in Android Studio.

**Comment by ilgazer** [comment]
Would there be a way to compare files independent of their EXIF? #1712 modifies the EXIF tags of the photo which may cause 2 copies of the same picture to essentially have different hashes.

**Comment by misaochan** [comment]
The existing file dialog pops up for me in the current master. @nicolas-raoul would you mind trying on that?

@ilgazer I agree, but at the moment I'm not aware of a different method. :( I doubt it is possible without complicated AI processing.

**Comment by nicolas-raoul** [comment]
Yes I got warned about the duplicate, thanks! 🙂

**Comment by misaochan** [comment]
Thanks! Let's close this unless there are further reports.
