### ISSUE TITLE
"No categories matching" message does not disappear

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#1733]
**Steps to reproduce:** 

1. Search for a category that does not exist
2. Message "No categories matching" appears
3. Correct your input to match a category that exists
4. The correct category appears
5. Observe that the message is still there

Expected: The message should disappear at step 3

**Device and Android version:** 

Android 7.1.2
 
 **Commons app version:** 

Branch 2.8-release

**Screenshot:** 

![screenshot_20180719-134052](https://user-images.githubusercontent.com/99590/43032146-e3039b3a-8cea-11e8-9854-90397d7a97f0.png)

Low priority

**Comment by maskaravivek** [comment]
@nicolas-raoul I am unable to reproduce this issue on the `2.8-release` branch. I followed all the steps that you mentioned.

**Comment by nicolas-raoul** [comment]
Yes, it does not happen every time, I guess there is a kind of race condition.

**Comment by nicolas-raoul** [comment]
Fixed :-)
