### ISSUE TITLE
Conflicts while pulling localisation updates.

### ISSUE THREAD

**Issue by neslihanturan** [commons-app/apps-android-commons#1738]
**Summary:** 

Normally we never experience conflicts after pulling localization updates. Because we never edit someLanguage/string.xml files manually. But this time I experienced some conflicts, it comes from latest update. 

@Nikerabbit do you have any theory about reason of this situation? 

**Steps to reproduce:** 

Pull latest updates and merge them to your branch

 **Screen shoots**

![screenshot from 2018-07-23 13-35-09](https://user-images.githubusercontent.com/3127881/43072042-59ecd3a4-8e7d-11e8-8b24-47309827addb.png)
![screenshot from 2018-07-23 13-31-47](https://user-images.githubusercontent.com/3127881/43072043-5a190dca-8e7d-11e8-83bb-7e331d48aaad.png)

**Comment by maskaravivek** [comment]
@neslihanturan Is this issue still happening?

**Comment by domdomegg** [comment]
Don't think this is still happening - I can't reproduce and as there's been no more updates on this going to assume it kinda sorted itself. If it does reappear can always reopen.
