### ISSUE TITLE
Make achievements more prominent?

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#1745]
If I understand correctly, the only way to reach achievements is to click the small "user" icon at the right of the user name?
I believe most people may not find it. How about showing the level of the person instead of that icon?
For instance (with "level 5" being underlined to show it is clickable):
```
JoeFromHCMC - level 5
```
or maybe:
```
JoeFromHCMC
level 5
```

**Comment by tanvidadu** [comment]
Thanks @nicolas-raoul! I will send a PR to change the icon.

**Comment by misaochan** [comment]
I agree, IMO the "person" icon next to the username on the nav bar looks like it would lead to a user profile, not an Achievements screen. How about a trophy icon?

**Comment by misaochan** [comment]
It looks OK to me on the right side, but I could go either way I guess.

**Comment by tanvidadu** [comment]
I have no problem on either side :) , I will post screenshots of  both cases

**Comment by tanvidadu** [comment]
<img src ="https://user-images.githubusercontent.com/29161745/43357759-15b77948-92a4-11e8-9221-e871dd165976.jpeg" width="45%" height="45%" />   <img src ="https://user-images.githubusercontent.com/29161745/43357770-371acaea-92a4-11e8-8f0d-a210709f049f.jpeg" width="45%" height="45%" />

**Comment by misaochan** [comment]
Thanks @tanvidadu . I'm actually voting for icon on the right (with some padding added). But let's see what others say, haha.

**Comment by nicolas-raoul** [comment]
Personally I prefer the screenshot on the left (meaning the trophy is on the right)
A space would be welcome before the trophy though.
