### ISSUE TITLE
Strange animation when viewing any image

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#1746]
**Steps to reproduce:** 

1. Go to "My uploads" or "Explore" or browse a category
2. Press an image

Expected: The image just shows up
Actually: The previous image is briefly shown, and then a sliding happens before the image is shown

 **Commons app version:** 

Current master.
I just noticed that today, I don't think it happened with two days ago's master

**Comment by maskaravivek** [comment]
Yes, the same is happening for me as well. I have never seen such animation earlier. Could be because of recent changes for browsing. It would be nice to cross check with @ujjwalagrawal17 if he is aware of any such change.

**Comment by ujjwalagrawal17** [comment]
Actually there was an issue on opening media details from explore the adapted was getting null immediately so I added a 0.05sec delay using handler to stop the crash. Please see PR #1743 .

**Comment by ujjwalagrawal17** [comment]
I will search a better solution for the same to fix this issue.

**Comment by nicolas-raoul** [comment]
Another problem probably related to this issue:
1. Scroll to picture N
2. Double-tap it (not a super-fast double-tap, let about 0.5 second between the two taps)
3. Picture N-1 gets displayed instead of picture N

**Comment by ashishkumar468** [comment]
@nicolas-raoul  Does this issue still exists?

**Comment by maskaravivek** [comment]
@ashishkumar468 This refers to the old upload UI as far as I can remember. Feel free to reopen it if the issue persists.

**Comment by ashishkumar468** [comment]
Sure, Thanks @maskaravivek
