### ISSUE TITLE
Add a bookmark option in media Details

### ISSUE THREAD

**Issue by ujjwalagrawal17** [commons-app/apps-android-commons#1756]
**Summary:** 
When exploring feature will be available to everyone. A lot of people will download images uploaded by others. But they users will not get the same in an Organised manner. It would be nice if we can have a bookmark option in media details menu and store the bookmarked filenames in the local history and show a list of bookmarked images later may be in the drawer of somewhere.

**Comment by ujjwalagrawal17** [comment]
Maybe we can have a tab UI which contains bookmarked media, bookmarked nearby locations (#1499 ).

**Comment by misaochan** [comment]
I agree, this would be nice. :)

**Comment by R0ma1nG** [comment]
I'll start working on this :)

**Comment by misaochan** [comment]
@R0ma1nG welcome! It is yours. :)

As this is a fairly involved task, it might save you time if you write a detailed description of how you plan to implement it and how the UI will look. Then collaborators can provide feedback early in the process.

**Comment by R0ma1nG** [comment]
Yes sure, first I'll analyze the app to see what I can reuse. Then I'll work on a design document and on UI specs. After feedback provided, I'll implement the feature.

**Comment by R0ma1nG** [comment]
Hey, here are the screens for the bookmarks. I'll reuse components already implemented to respect the graphic chart, others (the star for example) will be material icons. If you have any suggestion or comment, it's time :)

<img width="337" alt="menu" src="https://user-images.githubusercontent.com/24422094/45767641-fb987d80-bc3a-11e8-82ef-c062ea7f8343.png">
<img width="327" alt="bookmark_screen_locations" src="https://user-images.githubusercontent.com/24422094/45767076-88423c00-bc39-11e8-8efb-3e0045268b54.png">
<img width="327" alt="bookmark_screen_pictures" src="https://user-images.githubusercontent.com/24422094/45767077-88423c00-bc39-11e8-905c-2d621db7a30b.png">
<img width="327" alt="picture_stared" src="https://user-images.githubusercontent.com/24422094/45767078-88dad280-bc39-11e8-8dae-2b9675e07d9a.png">
<img width="327" alt="picture_unstared" src="https://user-images.githubusercontent.com/24422094/45767079-88dad280-bc39-11e8-98e6-5b1e41225c8d.png">

**Comment by nicolas-raoul** [comment]
Looks great and very useful!
Any specific reason why the title of the activity is "Search" in the last two screenshots?

**Comment by R0ma1nG** [comment]
I didn't change the title in the screenshot, I used search functionality and it was the default title of the activity when I select the picture... Thinking it was the desired behavior

**Comment by nicolas-raoul** [comment]
Why not, it is not very important I guess :-)

**Comment by misaochan** [comment]
The UI looks great, thanks @R0ma1nG ! :) Where and how do you intend to store the bookmarked items?

**Comment by R0ma1nG** [comment]
To store the items my idea is to store only the link to the resource (if possible) locally, but I need enlightenments about the storage methods used in the application (and the good practices too). Thanks :)

**Comment by nicolas-raoul** [comment]
By "link to the resource" I guess you mean for instance `Carretera al monasterio Noravank, Armenia, 2016-10-01, DD 55-59 PAN.jpg`? Sounds good.

(Unfortunately sometimes files get renamed, I hope Structured Commons fixes that by using opaque identifiers, but for now that is probably the most convenient identifier we have)
