### ISSUE TITLE
Switch achievements button from "person" icon to trophy icon?

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#1757]
Minor issue - IMO the "person" icon next to the username on the nav bar looks like it would lead to a user profile, not an Achievements screen. To make it more explicit to users, how about a trophy icon? What do you guys think, anyone have any other suggestions? @nicolas-raoul @neslihanturan @tanvidadu @maskaravivek

**Comment by nicolas-raoul** [comment]
Related: #1745

**Comment by misaochan** [comment]
Oh, thanks, I didn't notice that! I will close this and copy my comment there. :)
