### ISSUE TITLE
Add the list of libraries in the Readme

### ISSUE THREAD

**Issue by knightcube** [commons-app/apps-android-commons#1764]
**Summary:** 
Please add the list of libraries being used in the app, to the Readme 
For eg)
- Glide
- RxJava
- Dagger
- Stetho
- Leak Canary ,etc

**Comment by Mansi449** [comment]
@knightcube I would like to take up this issue.

**Comment by nicolas-raoul** [comment]
@Mansi449 It is yours, looking forward to your pull request :-)
