### ISSUE TITLE
Use a library for checking various permissions

### ISSUE THREAD

**Issue by maskaravivek** [commons-app/apps-android-commons#1773]
**Summary:** 

Our app asks for runtime permissions in various places and in the past we have run into several issues/crashes because of missing permissions checks. The process of ensuring that permission is granted is cumbersome:
- check for permission
- request permission if not granted
- check if the user granted permission
- execute method or else handle failure

Making sure that all these steps are followed correctly is a tedious task. It might be fruitful if we start using a 3rd party library for checking and handling permissions. I have tried out these two libraries in the past and found both of them to be quite useful. 

-  https://github.com/permissions-dispatcher/PermissionsDispatcher
- https://github.com/Karumi/Dexter

The first library uses simple annotations and the second library provides callback. All the hassle of checking and requesting permissions is taken care by the library itself.

**Comment by misaochan** [comment]
This would be really useful! I'm not familiar with the libraries themselves, but at first glance they look good to me. Would you have any recommendations for which one would be preferable?

**Comment by ilgazer** [comment]
This looks very nice, especially for the Upload Screen overhaul. Which one should we use?

**Comment by maskaravivek** [comment]
I am currently using Dexter for one of my projects and its super simple to use. I would highly recommend its use for any permission checks in our app. 

```
Dexter.withActivity(this)
	.withPermission(Manifest.permission.CAMERA)
	.withListener(new PermissionListener() {
		@Override public void onPermissionGranted(PermissionGrantedResponse response) {/* ... */}
		@Override public void onPermissionDenied(PermissionDeniedResponse response) {/* ... */}
	}).check();
```

Moreover, these callbacks are optional and there's a default callback for both granted and denied situation. Also, it provides customizable UI(alert dialogs) for requesting permissions and showing an error message. It would definitely help us remove a lot of boilerplate and will also reduce the chances of crashes.

**Comment by maskaravivek** [comment]
@ilgazer IMO the best way forward would be to replace one existing check in the app using this library so that we can have the library merged in master first then others can use this for their feature development.

**Comment by ilgazer** [comment]
Sounds like a plan!

**Comment by ashishkumar468** [comment]
I'd like to take this up. Probably with a fix of https://github.com/commons-app/apps-android-commons/issues/1697

**Comment by domdomegg** [comment]
Done in #1855

Related: #2053
