### ISSUE TITLE
Gallery of contributors

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#1774]
While investigating for another issue, I stumble upon this project that shows its list of contributors:

https://github.com/Karumi/Dexter#contributors

![screenshot from 2018-08-01 16-56-53](https://user-images.githubusercontent.com/99590/43508848-f8b59c34-95ab-11e8-9921-3f9bd4888155.png)

How about having the same?

Merits:
- Show how diverse we are, which probably lowers the level of entry for most of the world's population
- Increased incentive to participate
- Uses GitHub avatar / name, for which people who don't like publicity use an empty icon already
Demerits:
- Takes space
- Requires a bit of initial effort and maintenance ever 6 months or so.

Source code:
```
# Contributors

Thank you all for your work!

| [<img src="https://avatars1.githubusercontent.com/u/3494156?v=4" width="100px;"/><br /><sub><b>Carlos Morera de la Chica</b></sub>](https://github.com/CarlosMChica) | [<img src="https://avatars0.githubusercontent.com/u/237122?v=4" width="100px;"/><br /><sub><b>Alex Florescu</b></sub>](https://github.com/anothem) | [<img src="https://avatars3.githubusercontent.com/u/416941?v=4" width="100px;"/><br /><sub><b>Pedro Veloso</b></sub>](https://github.com/pedronveloso) | [<img src="https://avatars3.githubusercontent.com/u/1636897?v=4" width="100px;"/><br /><sub><b>Dion Segijn</b></sub>](https://github.com/DanielMartinus) | [<img src="https://avatars0.githubusercontent.com/u/837104?v=4" width="100px;"/><br /><sub><b>Christian Panadero</b></sub>](https://github.com/PaNaVTEC) |
| :---: | :---: | :---: | :---: | :---: |
| [<img src="https://avatars3.githubusercontent.com/u/6309101?v=4" width="100px;"/><br /><sub><b>Vignesh</b></sub>](https://github.com/VigneshPeriasami) | [<img src="https://avatars0.githubusercontent.com/u/5009609?v=4" width="100px;"/><br /><sub><b>Andy French</b></sub>](https://github.com/AndyFrench) | [<img src="https://avatars2.githubusercontent.com/u/887462?v=4" width="100px;"/><br /><sub><b>Bernat Borrás Paronella</b></sub>](https://github.com/alorma) | [<img src="https://avatars0.githubusercontent.com/u/21121410?v=4" width="100px;"/><br /><sub><b>Bastien Paul</b></sub>](https://github.com/bastienpaulfr) | [<img src="https://avatars2.githubusercontent.com/u/4190298?v=4" width="100px;"/><br /><sub><b>Bas Broek</b></sub>](https://github.com/BasThomas) |
| [<img src="https://avatars2.githubusercontent.com/u/6371716?v=4" width="100px;"/><br /><sub><b>Bartek Lipinski</b></sub>](https://github.com/blipinsk) | [<img src="https://avatars0.githubusercontent.com/u/4202457?v=4" width="100px;"/><br /><sub><b>emmano</b></sub>](https://github.com/emmano) | [<img src="https://avatars1.githubusercontent.com/u/7110368?v=4" width="100px;"/><br /><sub><b>Konrad Morawski</b></sub>](https://github.com/Konrad-Morawski) | [<img src="https://avatars3.githubusercontent.com/u/18151375?v=4" width="100px;"/><br /><sub><b>Hrant Alaverdyan</b></sub>](https://github.com/rid-hrant) | [<img src="https://avatars2.githubusercontent.com/u/1730320?v=4" width="100px;"/><br /><sub><b>Carla</b></sub>](https://github.com/iriberri)
| [<img src="https://avatars1.githubusercontent.com/u/3470701?v=4" width="100px;"/><br /><sub><b>Pavel Stepanov</b></sub>](https://github.com/stefan-nsk) | [<img src="https://avatars2.githubusercontent.com/u/16154410?v=4" width="100px;"/><br /><sub><b>Emmett Wilson</b></sub>](https://github.com/EmmettWilson) | [<img src="https://avatars0.githubusercontent.com/u/16763485?v=4" width="100px;"/><br /><sub><b>Max</b></sub>](https://github.com/TheMaxCoder) | [<img src="https://avatars3.githubusercontent.com/u/18224621?v=4" width="100px;"/><br /><sub><b>Al B.</b></sub>](https://github.com/albodelu) | [<img src="https://avatars0.githubusercontent.com/u/578021?v=4" width="100px;"/><br /><sub><b>Vladislav Bauer</b></sub>](https://github.com/vbauer)
| [<img src="https://avatars2.githubusercontent.com/u/4047514?v=4" width="100px;"/><br /><sub><b>Jc Miñarro</b></sub>](https://github.com/JcMinarro) | [<img src="https://avatars0.githubusercontent.com/u/944957?v=4" width="100px;"/><br /><sub><b>handrenliang</b></sub>](https://github.com/handrenliang) | [<img src="https://avatars3.githubusercontent.com/u/19774257?v=4" width="100px;"/><br /><sub><b>jcruzsousa</b></sub>](https://github.com/jcruzsousa) | [<img src="https://avatars0.githubusercontent.com/u/18180559?v=4" width="100px;"/><br /><sub><b>lzdon</b></sub>](https://github.com/lzdon)
```

The list at https://github.com/commons-app/apps-android-commons/graphs/contributors is a good place to get a list of our contributors. Any volunteer to write a script (in your favorite language) that scraps that web page and turns it into a table like above?

**Comment by ashishkumar468** [comment]
@nicolas-raoul I'd like to take this up

**Comment by nicolas-raoul** [comment]
@ashishkumar468 It is yours :-)

**Comment by ashishkumar468** [comment]
@nicolas-raoul  Just to make sure everybody is on the same page, an item will be added to the nav drawer named as Contributors which on click would lead to a screen where the list of contributors from   https://github.com/commons-app/apps-android-commons/graphs/contributors would be shown.

**Comment by misaochan** [comment]
Sounds great! I probably need to get around to putting up a real avatar.... someday, haha.

I wonder if it would be a good idea to limit to those with >10 commits? Otherwise we would have a very long list. But I'm OK with either.

**Comment by neslihanturan** [comment]
> Sounds great! I probably need to get around to putting up a real avatar.... someday, haha.
 
This is what I exactly thought:)

**Comment by nicolas-raoul** [comment]
@ashishkumar0207 I was only talking about putting it as HTML code in https://github.com/commons-app/apps-android-commons/blob/master/README.md (or it could be in https://github.com/commons-app/apps-android-commons/wiki/Volunteers-welcome%21 actually).

If you really want to put it in the app:
- "About" is the best place, adding another item to the nav drawer would crowd it for no good reason
- Make sure that it does not become a crash cause, in particular make sure that it fails gracefully when no Internet access is available.

A long list is OK, I would say. If you want to cut, I would suggest "First X committers when ordering by number of commits" rather than a strict "all committers with Y commits", because it allows us to make a nice rectangular table :-)

**Comment by ashishkumar468** [comment]
@nicolas-raoul  I am not that great with html, will take me a lot of time to implement, I was hoping if someone more fluent in web ui can take it up, for the app @neslihanturan @misaochan @nicolas-raoul We have I think 100 people with at-least one commit, thats not a lot (which will be anyways sorted by the number of commits). We can show all of them if all of us agree or we can show top x contributors based on the number of commits. @nicolas-raoul Are you suggesting adding a filter based on the number of commits. ?

**Comment by misaochan** [comment]
I agree that the readme or wiki would be the ideal place for it. But if we do have it in the app, I think a separate fragment that is linked via About would be best.

I'm good either way, a complete list or "first 40 committers" (or other value) both sound OK to me. :)

**Comment by ashishkumar468** [comment]
@misaochan @nicolas-raoul @neslihanturan Lets clear a few things out
1.Do we need this feature in the app
2.If yes, How many contributors do we show (I will keep that configurable by a variable from where it could be easily updated)
One of you guys please confirm.

**Comment by nicolas-raoul** [comment]
How about we say at first:
- In the README, not in the app
- 40 biggest committers

But in open source a feature only gets implemented when a volunteer comes in and does it. So if you don't want to do HTML but rather want to implement it in the app instead, and send us a good pull request, we will probably accept it :-)

**Comment by ashishkumar468** [comment]
@nicolas-raoul @misaochan I actually did a bit of research. We cannot insert script in the readme file. @nicolas-raoul The repository which you have mentioned, Dexter, even that, if you see their readme file, you will find that  they have hardcoded the list, do we want the same in our readme ?

**Comment by nicolas-raoul** [comment]
@ashishkumar0207  We want a script (in any language, for instance Groovy) that generates that list. Writing it by hand would require too much maintenance.

**Comment by ashishkumar468** [comment]
@nicolas-raoul @misaochan I have actually written the script to generate the list of contributors in the required format. I had a few questions. 
* Where should we put show it ie. in  https://github.com/commons-app/apps-android-commons/blob/master/README.md or in https://github.com/commons-app/apps-android-commons/wiki/Volunteers-welcome%21
*The script which generates it is in python, so where do we want to put this file?

**Comment by nicolas-raoul** [comment]
Cool thanks!

Could you please create a new GitHub project for it called "maintenance", commit your script into it, and then transfer that repository (in settings) to the commons-app organization? Thanks a lot :-)

**Comment by ashishkumar468** [comment]
@nicolas-raoul Tried doing that, github needs two things for that
Type the name of the repository to confirm & New owner’s GitHub username or organization name. Can you help me with those ?

**Comment by nicolas-raoul** [comment]
Just enter the name of the repository you have created, and "commons-app" :-)

If it still does not make sense, please post a screenshot of that screen.

**Comment by ashishkumar468** [comment]
I am getting this "You don’t have the permission to create repositories on commons-app"

**Comment by nicolas-raoul** [comment]
Ah yes you are right.
I just forked it from the commons-app account, it achieved the same thing: https://github.com/commons-app/maintenance
Thanks! :-)

**Comment by ashishkumar0207** [comment]
Readme looks great :-)

**Comment by ashishkumar468** [comment]
Readme looks great :-)

**Comment by misaochan** [comment]
Looks great, thanks for working on it @ashishkumar0207 ! :)
