### ISSUE TITLE
Beta: Explore shows "No images found!"

### ISSUE THREAD

**Issue by VaishSiddharth** [commons-app/apps-android-commons#1777]
**Summary:** 

In explore No image found! is displayed. Without searching anything explore shows No image found! which looks like an error.

**Steps to reproduce:** 
1. Explore
2. Shows "No image found!"

An appropriate message should be displayed.

**Screen-shots:** 
![screenshot_20180801-235917](https://user-images.githubusercontent.com/36266597/43544027-626156ee-95ef-11e8-86c4-ffeab61dba6c.png)

**Would you like to work on the issue?**

I would like to work on this.

**Comment by nicolas-raoul** [comment]
Does it happen always?
Could you please post the logcat?
Thanks!

**Comment by nicolas-raoul** [comment]
I can not reproduce.
Please provide the steps that lead to this screen, thanks!

**Comment by VaishSiddharth** [comment]
Please have a look.
![gifeditor_20180802_135554](https://user-images.githubusercontent.com/36266597/43571977-f5d1f7fa-965b-11e8-9e83-affbcdaf134f.gif)

**Comment by nicolas-raoul** [comment]
Thanks for the screencast!
That's definitely a problem, featured images should appear here.
Please send your logcat, thanks!

**Comment by ujjwalagrawal17** [comment]
You are in which branch ?

**Comment by VaishSiddharth** [comment]
@ujjwalagrawal17 master branch

**Comment by ujjwalagrawal17** [comment]
Umm, I am unable to reproduce it.

**Comment by ujjwalagrawal17** [comment]
Can you share the logcat? It Would be helpful for reproducing the same.

**Comment by VaishSiddharth** [comment]
@ujjwalagrawal17 Please have a look.
08-02 23:43:33.889 10185-10185/? I/zygote64: Late-enabling -Xcheck:jni
08-02 23:43:34.729 10185-10185/fr.free.nrw.commons.debug I/MultiDex: VM with version 2.1.0 has multidex support
08-02 23:43:34.792 10185-10185/fr.free.nrw.commons.debug I/InstantRun: starting instant run server: is main process
08-02 23:43:34.877 10185-10185/fr.free.nrw.commons.debug D/NetworkSecurityConfig: No Network Security Config specified, using platform default
08-02 23:43:35.001 10185-10220/fr.free.nrw.commons.debug I/stetho: Listening on @stetho_fr.free.nrw.commons.debug_devtools_remote
08-02 23:43:35.804 10185-10185/fr.free.nrw.commons.debug I/AppCompatViewInflater: app:theme is now deprecated. Please move to using android:theme instead.
08-02 23:43:35.909 10185-10185/fr.free.nrw.commons.debug D/ContributionsListFragme: Last Sync Timestamp: 2018-08-02T18:05:00Z
08-02 23:43:36.023 10185-10192/fr.free.nrw.commons.debug I/zygote64: Do partial code cache collection, code=30KB, data=25KB
08-02 23:43:36.024 10185-10192/fr.free.nrw.commons.debug I/zygote64: After code cache collection, code=30KB, data=25KB
08-02 23:43:36.122 10185-10237/fr.free.nrw.commons.debug D/OpenGLRenderer: HWUI GL Pipeline
08-02 23:43:36.132 10185-10233/fr.free.nrw.commons.debug I/url: https://tools.wmflabs.org/urbanecmbot/commonsmisc/feedback.py?user=Sidvaish97&fetch=deletedUploads
08-02 23:43:36.185 10185-10237/fr.free.nrw.commons.debug I/Adreno: QUALCOMM build                   : 624c5bb, I109c45a694
08-02 23:43:36.186 10185-10237/fr.free.nrw.commons.debug D/vndksupport: Loading /vendor/lib64/hw/gralloc.msm8953.so from current namespace instead of sphal namespace.
08-02 23:43:36.191 10185-10237/fr.free.nrw.commons.debug I/Adreno: PFP: 0x005ff087, ME: 0x005ff063
08-02 23:43:36.197 10185-10237/fr.free.nrw.commons.debug I/zygote64: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
08-02 23:43:36.198 10185-10237/fr.free.nrw.commons.debug I/OpenGLRenderer: Initialized EGL, version 1.4
08-02 23:43:36.198 10185-10237/fr.free.nrw.commons.debug D/OpenGLRenderer: Swap behavior 2
08-02 23:43:36.410 10185-10185/fr.free.nrw.commons.debug D/UploadService: Set 0 uploads to failed
08-02 23:43:36.411 10185-10185/fr.free.nrw.commons.debug D/UploadService: Flags is 0 id is 1
08-02 23:43:36.427 10185-10241/fr.free.nrw.commons.debug D/ContributionsSyncAdapte: Max number of uploads set to 500
08-02 23:43:36.488 10185-10192/fr.free.nrw.commons.debug I/zygote64: Do partial code cache collection, code=39KB, data=57KB
08-02 23:43:36.767 10185-10192/fr.free.nrw.commons.debug I/zygote64: Do full code cache collection, code=101KB, data=77KB
08-02 23:43:36.768 10185-10192/fr.free.nrw.commons.debug I/zygote64: After code cache collection, code=95KB, data=61KB
08-02 23:43:36.832 10185-10237/fr.free.nrw.commons.debug D/vndksupport: Loading /vendor/lib64/hw/android.hardware.graphics.mapper@2.0-impl.so from current namespace instead of sphal namespace.
08-02 23:43:36.845 10185-10237/fr.free.nrw.commons.debug D/vndksupport: Loading /vendor/lib64/hw/gralloc.msm8953.so from current namespace instead of sphal namespace.
08-02 23:43:38.354 10185-10241/fr.free.nrw.commons.debug D/ApacheHttpClientMediaWi: 0 results!
08-02 23:43:38.372 10185-10241/fr.free.nrw.commons.debug D/ContributionsSyncAdapte: Last modified at 2018-08-02T18:05:00Z
08-02 23:43:38.373 10185-10241/fr.free.nrw.commons.debug D/ContributionsSyncAdapte: 0 results!
08-02 23:43:38.383 10185-10241/fr.free.nrw.commons.debug D/ContributionsSyncAdapte: Oh hai, everyone! Look, a kitty!
08-02 23:43:42.541 10185-10219/fr.free.nrw.commons.debug I/zygote64: Explicit concurrent copying GC freed 50074(3MB) AllocSpace objects, 18(424KB) LOS objects, 74% free, 4MB/16MB, paused 289us total 64.772ms
08-02 23:44:03.715 10185-10192/fr.free.nrw.commons.debug I/zygote64: Do partial code cache collection, code=124KB, data=85KB
08-02 23:44:25.455 10185-10185/fr.free.nrw.commons.debug I/AppCompatViewInflater: app:theme is now deprecated. Please move to using android:theme instead.
08-02 23:43:33.889 10185-10185/fr.free.nrw.commons.debug I/zygote64: Late-enabling -Xcheck:jni
08-02 23:43:34.729 10185-10185/fr.free.nrw.commons.debug I/MultiDex: VM with version 2.1.0 has multidex support
    Installing application
    VM has multidex support, MultiDex support library is disabled.
08-02 23:43:34.792 10185-10185/fr.free.nrw.commons.debug I/InstantRun: starting instant run server: is main process
08-02 23:43:34.877 10185-10185/fr.free.nrw.commons.debug D/NetworkSecurityConfig: No Network Security Config specified, using platform default
08-02 23:43:35.001 10185-10220/fr.free.nrw.commons.debug I/stetho: Listening on @stetho_fr.free.nrw.commons.debug_devtools_remote
08-02 23:43:35.804 10185-10185/fr.free.nrw.commons.debug I/AppCompatViewInflater: app:theme is now deprecated. Please move to using android:theme instead.
08-02 23:43:35.909 10185-10185/fr.free.nrw.commons.debug D/ContributionsListFragme: Last Sync Timestamp: 2018-08-02T18:05:00Z
08-02 23:43:36.023 10185-10192/fr.free.nrw.commons.debug I/zygote64: Do partial code cache collection, code=30KB, data=25KB
08-02 23:43:36.024 10185-10192/fr.free.nrw.commons.debug I/zygote64: After code cache collection, code=30KB, data=25KB
    Increasing code cache capacity to 128KB
08-02 23:43:36.122 10185-10237/fr.free.nrw.commons.debug D/OpenGLRenderer: HWUI GL Pipeline
08-02 23:43:36.132 10185-10233/fr.free.nrw.commons.debug I/url: https://tools.wmflabs.org/urbanecmbot/commonsmisc/feedback.py?user=Sidvaish97&fetch=deletedUploads
08-02 23:43:36.185 10185-10237/fr.free.nrw.commons.debug I/Adreno: QUALCOMM build                   : 624c5bb, I109c45a694
    Build Date                       : 05/22/18
    OpenGL ES Shader Compiler Version: EV031.22.00.01_06
    Local Branch                     : 
    Remote Branch                    : 
    Remote Branch                    : 
    Reconstruct Branch               : 
08-02 23:43:36.186 10185-10237/fr.free.nrw.commons.debug D/vndksupport: Loading /vendor/lib64/hw/gralloc.msm8953.so from current namespace instead of sphal namespace.
08-02 23:43:36.191 10185-10237/fr.free.nrw.commons.debug I/Adreno: PFP: 0x005ff087, ME: 0x005ff063
08-02 23:43:36.197 10185-10237/fr.free.nrw.commons.debug I/zygote64: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
08-02 23:43:36.198 10185-10237/fr.free.nrw.commons.debug I/OpenGLRenderer: Initialized EGL, version 1.4
08-02 23:43:36.198 10185-10237/fr.free.nrw.commons.debug D/OpenGLRenderer: Swap behavior 2
08-02 23:43:36.410 10185-10185/fr.free.nrw.commons.debug D/UploadService: Set 0 uploads to failed
08-02 23:43:36.411 10185-10185/fr.free.nrw.commons.debug D/UploadService: Flags is 0 id is 1
08-02 23:43:36.427 10185-10241/fr.free.nrw.commons.debug D/ContributionsSyncAdapte: Max number of uploads set to 500
08-02 23:43:36.488 10185-10192/fr.free.nrw.commons.debug I/zygote64: Do partial code cache collection, code=39KB, data=57KB
    After code cache collection, code=39KB, data=57KB
    Increasing code cache capacity to 256KB
    Compiler allocated 7MB to compile void android.widget.TextView.<init>(android.content.Context, android.util.AttributeSet, int, int)
08-02 23:43:36.767 10185-10192/fr.free.nrw.commons.debug I/zygote64: Do full code cache collection, code=101KB, data=77KB
08-02 23:43:36.768 10185-10192/fr.free.nrw.commons.debug I/zygote64: After code cache collection, code=95KB, data=61KB
08-02 23:43:36.832 10185-10237/fr.free.nrw.commons.debug D/vndksupport: Loading /vendor/lib64/hw/android.hardware.graphics.mapper@2.0-impl.so from current namespace instead of sphal namespace.
08-02 23:43:36.845 10185-10237/fr.free.nrw.commons.debug D/vndksupport: Loading /vendor/lib64/hw/gralloc.msm8953.so from current namespace instead of sphal namespace.
08-02 23:43:38.354 10185-10241/fr.free.nrw.commons.debug D/ApacheHttpClientMediaWi: 0 results!
08-02 23:43:38.372 10185-10241/fr.free.nrw.commons.debug D/ContributionsSyncAdapte: Last modified at 2018-08-02T18:05:00Z
08-02 23:43:38.373 10185-10241/fr.free.nrw.commons.debug D/ContributionsSyncAdapte: 0 results!
08-02 23:43:38.383 10185-10241/fr.free.nrw.commons.debug D/ContributionsSyncAdapte: Oh hai, everyone! Look, a kitty!
08-02 23:43:42.541 10185-10219/fr.free.nrw.commons.debug I/zygote64: Explicit concurrent copying GC freed 50074(3MB) AllocSpace objects, 18(424KB) LOS objects, 74% free, 4MB/16MB, paused 289us total 64.772ms
08-02 23:44:03.715 10185-10192/fr.free.nrw.commons.debug I/zygote64: Do partial code cache collection, code=124KB, data=85KB
    After code cache collection, code=124KB, data=85KB
    Increasing code cache capacity to 512KB
08-02 23:44:25.455 10185-10185/fr.free.nrw.commons.debug I/AppCompatViewInflater: app:theme is now deprecated. Please move to using android:theme instead.
08-02 23:44:33.247 10185-10194/fr.free.nrw.commons.debug I/zygote64: Debugger is no longer active

**Comment by maskaravivek** [comment]
I guess this happens just on beta app. @VaishSiddharth Can you try out the prod variant.

**Comment by VaishSiddharth** [comment]
@maskaravivek where can I find "prod variant"?

**Comment by misaochan** [comment]
If you are using Android Studio on default settings, there should be "build variant" on the left side of the screen, underneath project view and above event log.

**Comment by VaishSiddharth** [comment]
@misaochan ok thanks.

**Comment by misaochan** [comment]
I think it is probably not a concern if it happens on beta. There aren't many images (and certainly not many worth seeing!) on the Commons beta server, and there's no need to use it for debugging either, since the beta server is predominantly for test uploads.

Shall we close?

**Comment by nicolas-raoul** [comment]
I just got this with 2.9.0

1. Touch "Explore"
2. Following screen appear:

![screenshot_20181129-114435](https://user-images.githubusercontent.com/99590/49195966-75cc4780-f3cc-11e8-862f-b3a54600ea8d.png)

Maybe the network was unstable when I did this (switching from LTE to WiFi), but if it is a network problem then another error message would probably be more appropriate.

**Comment by misaochan** [comment]
Hi @nicolas-raoul , could you Send Logs please? :)

**Comment by domdomegg** [comment]
Sorry for title changing spam, kept changing my mind.

Let's have this as an issue for explore not showing anything in beta, which I will work on.

If you can reproduce it open up another issue for explore showing "No images found!" in prod.

**Comment by domdomegg** [comment]
See https://github.com/commons-app/apps-android-commons/pull/2216#issuecomment-473657312
