### ISSUE TITLE
Picture zoom (when uploading) is not full resolution

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#1778]
**Steps to reproduce:** 

1. Select a high resolution for upload
2. In the title/description activity, press the zoom button
3. Pinch to zoom into a detail, for instance to read what is written on a street sign
4. Expected: View the full details as if viewing the original image in Gallery. Actually: Low resolution, no details

![screenshot_20180725-141202](https://user-images.githubusercontent.com/99590/43558085-a3d6af36-9642-11e8-9293-612a51e165b1.png)

 **Commons app version:** 

Current master

**Comment by neslihanturan** [comment]
Solved.
