### ISSUE TITLE
In-app camera addition prefills title/description using previous Nearby addition

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#1779]
**Steps to reproduce:** 

1. Use Nearby to add a picture, upload it, fill title/description/category.
2. Explore various pictures (probably optional)
3. Press on the camera button within the app
4. Problem: Title/description are pre-filled with values from step 1

 **Commons app version:** 

Current master

**Comment by misaochan** [comment]
Thanks for this! We noticed it but haven't made an issue for it. :)

**Comment by VaishSiddharth** [comment]
@nicolas-raoul I will try to fix this issue.

**Comment by VaishSiddharth** [comment]
@nicolas-raoul I am facing an issue in uploading images from last 3 days. Please Help

**Comment by misaochan** [comment]
What issue are you experiencing specifically, @VaishSiddharth ?

**Comment by VaishSiddharth** [comment]
@misaochan The app crashes when the arrow button is pressed.

**Comment by misaochan** [comment]
Could you please create an issue for this, and paste your logcat there?

**Comment by VaishSiddharth** [comment]
@misaochan Ok i will do it.

**Comment by misaochan** [comment]
Sorry, I had to submit a PR for this, because we urgently need to fix it in anticipation for Monday's release. @VaishSiddharth please feel free to try your hand at other issues, thanks!

**Comment by VaishSiddharth** [comment]
@misaochan Ok no problem. :-)

**Comment by AhmedAliNaga** [comment]
Is this issue still not handled?

**Comment by misaochan** [comment]
Sorry, this is fixed!
