### ISSUE TITLE
Provide wikicode for easy image inclusion into wiki articles

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#178]
After I upload file S_Abe.jpg with description "Shinzo Abe", I should be able to easily copy the following text:

```
[[File:S_Abe.jpg|thumb|Shinzo Abe]]
```

While the Commons website's upload wizard shows this directly after upload, in a mobile app showing this extra screen is probably not a great idea as most people don't edit on mobile, and have more pictures to upload. Instead, this text could be shown in the details of that picture, accessed from the uploaded pictures gallery.

Syntax depends on the language of the wikipedia the user wants to contribute to. How about showing the syntax for the user's phone language + English?

By Arun Prakash (11 Jul):

> Way to add wiki code using description is missing

**Comment by chrisdebian** [comment]
@nicolas-raoul Nicolas, can this be closed, or is it still valid?

Thanks,

Chris.
