### ISSUE TITLE
"Skip" button feels unresponsive

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#1780]
skip_login branch

Seconds pass with no indication of progress. I had to press it several times.

**Comment by ujjwalagrawal17** [comment]
Ok. I will check and fix it.

**Comment by nicolas-raoul** [comment]
Maybe show a spinner or something that shows that the click has been understood and something is processing?

**Comment by ujjwalagrawal17** [comment]
Umm, we are inflating the dialog for skip onClick of text so I think it should display immediately. Nothing is processing in that time.
