### ISSUE TITLE
Share to Commons when not logged in: Redirect immediately to login screen, not title/description screen

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#1781]
skip_login branch

**Comment by ujjwalagrawal17** [comment]
Ok I am changing it now.

**Comment by maskaravivek** [comment]
IMO, the activities should be agnostic of whether the login is required or not. Any API call requiring authentication should itself invoke the login flow if it is not able to get the auth token. 

Taking the example of notifications screen, 

- the user opens the notification activity
- the activity loads and the notification adapter calls `getNotifications` method in `MediaWikiApi`. 
- `getNotifications` calls a method `getToken`
- this `getToken` method should be able to either return the token or else invoke login with a callback attached which can continue the original flow post login. 

This way all the views in our app will be agnostic of whether a login is required or not. 

For eg. ideally, we should let the user view the nearby places list and prompt for a token only if he goes ahead and tries to upload a picture.

Similarly, there's nothing wrong in letting the user enter title and description and meddle with the license options before he clicks the next button to actually upload the picture. The idea is to let the users explore as much of the app as possible without login. 

@nicolas-raoul Am i missing something here?

**Comment by misaochan** [comment]
@maskaravivek I believe this is for Ujjwal's GSoC project, specifically #1486 . I agree with your suggestion in general but I think it is too much to expect for a 1-week GSoC task. :) Maybe we can start a new issue for it.

**Comment by maskaravivek** [comment]
Yup, it should be part of the GSoC task. This would require a big overhaul and can probably be taken up later. Will open a new issue for the same. :)
