### ISSUE TITLE
Notifications sometimes fail to load

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#1782]
Not sure how to reproduce. I have been on the same stable wifi for an hour, and once it failed to load, once it loaded correctly.

When it fails to load the content is just white.

In case it was a network or Commons API error, an error message should be displayed.

**Comment by ashishkumar468** [comment]
Notification needs title, time and icon url, all of which are also extracted from some api result, and I could see that the decorator functions of those are returning "" or null in some cases, which might be leading to notification being blank

**Comment by ashishkumar468** [comment]
I could not see a library which would log events for me, and as you said that you are not able to reproduce it, if someone would let me know that does any library exists(in the app or do I need to add one) through which we could log the events, we could log the events for cases where any of the title, icon or time is null or blank, especially if all of them are null [empty]. Using the logs from that we would be able to find the scenario when this is happening

**Comment by ashishkumar468** [comment]
Is anyone still seeing this issue?

**Comment by maskaravivek** [comment]
@ashishkumar468  This issue apparently got fixed after backend overhaul.
