### ISSUE TITLE
Looking for a part-time Android dev to join our team

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#1785]
As mentioned at #1683, we intend to apply for a WMF-funded [Project Grant](https://meta.wikimedia.org/wiki/Grants:Project) to continue our work on the app, after successfully completing our current IEG grant renewal. In the new grant application, we'd like to expand our grantee team (currently consisting of myself, @maskaravivek and @neslihanturan) by one person.

### Role
- Development of our Android app, primarily fixing bugs and crashes. Currently, we are stuck in a cycle of needing to put new feature releases on hold every now and then to fix the inevitable bugs/crashes. We are hoping that with an additional team member focusing on bugfixes, we will be able to complete our next grant in a more timely manner and release new features regularly, while keeping the app bug-free and polished. We also have a backlog of existing bugs/crashes that need to be looked into.
- Additionally, you may need to test/debug implementations, and communicate with users who report problems on our google groups forum or GitHub to get more details about the issues they are facing.

### Details
- This will be a 10 hr/week role starting March 2019 (if our grant application is approved) and most likely lasting for 9 months, with potential for renewal. 
- Our grant application is due Nov 2018, and I usually prefer to complete the proposal and start requesting community feedback at least a month beforehand, so we would need to make our decisions on the new team member by Sep/Oct 2018 at the latest. Due to this, the deadline for your application is **25 Aug 2018**.
- You can work from home and on a schedule of your own choosing. We do not require fixed work hours, but we do expect to see work completed in a timely and quality manner.

### Criteria
- Proficiency in Android app development and open-source collaborative development
- Preference will be given to applicants who have made extensive, high-quality contributions to our repo
- Ability to manage your own time and work with a geographically-distributed team

### Remuneration
- This is definitely a paid role, however I will honestly state that we are limited in what we can offer. From my experience, the grants committee judges proposals rather strictly based on how much funding they are asking for, and whether or not they believe the amount is justified. We always do our best to pay everyone fairly, but you can get an idea of upper limits of pay based on our [current grant](https://meta.wikimedia.org/wiki/Grants:IEG/Improve_%27Upload_to_Commons%27_Android_App/Renewal#Budget_breakdown) . 
- Please also note that this is not a guaranteed job offer - we will include the successful applicant as a member of our team in our grant proposal, but the final decision of whether to approve or decline the proposal lies with WMF. That being said, 2/2 of our previous proposals have been approved, so we are hopeful.

### Benefits
It's not all doom and gloom. All of your work will be open source, and we are happy to provide any references needed. We are part of the Wikimedia ecosystem and are often offered scholarships to attend Wikimedia events. The improvements you make to our app will benefit 3000+ users who uploaded 12000+ images to Wikimedia Commons in the last quarter. I'd also like to think that we are fairly easygoing people who are fun to work with. 😉

This role would be well-suited to a final-year student or someone who is just starting out in their career and is looking for open-source work experience to add to their resume.

### If you are interested
Please apply [here](https://docs.google.com/forms/d/19FxiJlMUNFAKLyEAcDCTlSoqoQox-TFOmdF5nZbRgK4/) .

**Comment by VojtechDostal** [comment]
Always happy to help with promotion of this, if needed.

**Comment by misaochan** [comment]
Thanks Vojtech. :) We have had a few applicants already, so no need to promote further I guess. However, if anyone is reading this and thinking of applying, please bear in mind that applications are closing in 4 days, so now's the time! ;)

**Comment by misaochan** [comment]
Closing this as the deadline is past. Thank you to everyone who applied! We will be in contact with you shortly. :)
