### ISSUE TITLE
Use Wikidata-Toolkit?

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#1789]
Wikidata-Toolkit is now compatible with Android: https://github.com/Wikidata/Wikidata-Toolkit/issues/356#issuecomment-409900396
We should evaluate whether it is a good fit. In particular see whether it is too big in size or not.

**Comment by neslihanturan** [comment]
Related with #1531

**Comment by nicolas-raoul** [comment]
Oops I had not seen that one, thanks!
