### ISSUE TITLE
Improve description language selector in ShareActivity 

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#1793]
**Summary:** 

It isn't immediately obvious what the description language selector that is newly implemented in ShareActivity does, because it's blank by default. And even after explicitly selecting a language, it remains blank.

IMO, it would be a good idea to have a language displayed by default (perhaps the phone language?). The selected language also needs to be displayed. After the user selects a language once, maybe we should also save it and use it for the next upload?

**Device and Android version:** 

API 24, Nexus S emulator
 
 **Commons app version:** 

Current master, prodDebug

**Screen-shots:** 

![screenshot_1533374027](https://user-images.githubusercontent.com/3611199/43674884-abce1512-981d-11e8-92e4-c6146fc4c099.png)

**Would you like to work on the issue?**

Preferably not.

**Comment by VaishSiddharth** [comment]
@misaochan I would like to try this.

**Comment by misaochan** [comment]
@VaishSiddharth It is yours :)

**Comment by ashishkumar468** [comment]
@misaochan @VaishSiddharth Seems to be working fine for me. (Tried on one plus 3T)

**Comment by ashishkumar468** [comment]
@VaishSiddharth I was actually able to reproduce it on the device spec you mentioned, Seems like a ui issue. The first row is anyways by default the default device locale. The following rows sort the locales alphabetically. I have kind of fixed the thing. (A minor change (increased the weight of the language spinner)). If you have not yet started working on the issue. I can push my changes. Also any ui suggestions are welcome.

**Comment by VaishSiddharth** [comment]
@ashishkumar468 Ok you can work on it :) 👍

**Comment by ashishkumar468** [comment]
Thanks 👍
