### ISSUE TITLE
Media details view for Browse is lacking author field

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#1801]
**Summary:** 

The media details view for Browse (search > media/categories) is lacking the author field. I believe this needs to be added, otherwise we are infringing the license for images that are under an attribution license. Featured images have the author field.

@nicolas-raoul @ujjwalagrawal17 Can this be fixed urgently? I am hesitant to release the browse feature without this in place

**Steps to reproduce:** 

Browse > media > search for an image > select the image 

**Device and Android version:** 

API 24 Samsung Galaxy s7
 
 **Commons app version:** 

2.8-release 

**Screen-shots:** 

![screenshot_1533548365](https://user-images.githubusercontent.com/3611199/43709538-7633449c-99b0-11e8-946f-05cb34a40745.png)

**Would you like to work on the issue?**

No

**Comment by nicolas-raoul** [comment]
I had not noticed, thanks!
The field needs to be added indeed.

**Comment by misaochan** [comment]
@ujjwalagrawal17 could you please submit this fix directly to the 2.8-release branch? If you can do it in the next couple of days we will hold the release and wait for you. After your PR is merged I will push the changes to master. Thanks!

**Comment by ujjwalagrawal17** [comment]
@misaochan I just searched there is an extra param in API to resolve this issue. 
https://commons.wikimedia.org/w/api.php?action=query&generator=search&gsrsearch=butterflies&gsrnamespace=6&gsrwhat=text&prop=imageinfo&format=xml
I am facing some issues in getting XML nodes for the same. I will try to do it soon.

**Comment by misaochan** [comment]
@ujjwalagrawal17 I believe you can reuse the same methods as featured images? We are already fetching the author name for those, it should be fairly simple to reuse.

**Comment by ujjwalagrawal17** [comment]
@misaochan I tried to reuse that but the response we are getting is very different so I think we will not be able to reuse that.

**Comment by misaochan** [comment]
Ah I see, okay. Please do keep us updated! We'd like to be able to include browse in our release this week if possible. :)

**Comment by ujjwalagrawal17** [comment]
https://commons.wikimedia.org/w/api.php?action=query&list=search&srsearch=butterflies&srnamespace=6&srwhat=text&format=xml&srprop=size|wordcount|timestamp|snippet|titlesnippet|redirecttitle|redirectsnippet|sectiontitle|sectionsnippet|isfilematch|categorysnippet|extensiondata

**Comment by ujjwalagrawal17** [comment]
@misaochan @nicolas-raoul I have fixed the issue. Please review the PR once.

**Comment by misaochan** [comment]
Thanks for the quick fix @ujjwalagrawal17 ! :)
