### ISSUE TITLE
Nearby uploads occasionally fail

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#1804]
**Summary:** 

As mentioned at #1749 , occasionally uploads via Nearby fail. This happened once to me while testing #1749 and another time while testing #1800 . It does not happen for uploads via ContributionsActivity.

**Steps to reproduce:** 

Upload via Nearby map or list, several times.

**Add System logs:**

Unfortunately I did not manage to get logs for this. But it might be reproducible by others, as it appears to be random

**Device and Android version:** 

Android 8.0.0 Samsung Galaxy s7
 
 **Commons app version:** 

Current 2.8-release

**Would you like to work on the issue?**

Preferably not

**Comment by neslihanturan** [comment]
Do you think this can be related with #1878 ? Maybe some uploads occasionally fail?

**Comment by ashishkumar468** [comment]
Seems to be fixed as a part of upload/nearby refactor
