### ISSUE TITLE
Username in nav drawer should be centered

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#1806]
**Summary:** 

My username in the nav drawer is left-aligned. It should be centered under the Commons logo, IMO. @tanvidadu was there a reason for changing the alignment? I recall it used to be centered?

**Device and Android version:** 

Android 8.0.0 Samsung Galaxy s7
 
 **Commons app version:** 

2.8-release

**Screen-shots:** 

![screenshot_20180808-010018_commons](https://user-images.githubusercontent.com/3611199/43784727-17d949e8-9aa8-11e8-9236-b78faf6f252b.jpg)

**Would you like to work on the issue?**

Pref not

**Comment by VaishSiddharth** [comment]
@misaochan I would like to work on this.

**Comment by misaochan** [comment]
@VaishSiddharth It is yours. :)
