### ISSUE TITLE
 Make locale non dependent on phone OS settings, but choosable on app settings

### ISSUE THREAD

**Issue by neslihanturan** [commons-app/apps-android-commons#1821]
**Summary:** 

Quote from one of our user, Luistxo Fernandez

> Make locale non dependent on phone OS settings, but choosable on app settings. Why? for instance, this app could easily be localised in Basque, yet my Android phone cannot be put in Basque.

I agree with this issue, since I can not set my phone language to Turkish, I use the app in English.

**Comment by nicolas-raoul** [comment]
This open source app has this feature: https://github.com/ankidroid/Anki-Android
![screenshot_20180813-204047](https://user-images.githubusercontent.com/99590/44029761-6b1c1302-9f39-11e8-8020-8391e0af044d.png)
No need to log in so it is easy for test purposes.

**Comment by sdabhi23** [comment]
I would like to work on this one. Should we place the option on the login screen itself or in the settings?

**Comment by nicolas-raoul** [comment]
@sdabhi23 It is yours :-)
In the settings, because most users will just be happy with the default (their phone's locale).

**Comment by ioshomebrew** [comment]
So far I put an option in settings to change the locale, but it does nothing as of yet

**Comment by maskaravivek** [comment]
@ioshomebrew This issue is already assigned to @sdabhi23 so it might not worthwhile to duplicate the efforts. There are a lot of open issues that you can go through and pick up :)

**Comment by sdabhi23** [comment]
I have been trying to get names for the languages the app supports to put them in the language selector, but am not able to get the names of a few languages. Can someone help me out?

Also sorry for the very slow progress 🙁

**Comment by nicolas-raoul** [comment]
@sdabhi23 Have you checked how it is done in the source code of the "AnkiDroid" app above?

**Comment by sdabhi23** [comment]
@nicolas-raul yes I did. But I think they are creating the selector section programmatically. While the implementation of preferences in this app is through a custom component. So I think we cannot just replicate the same implementation.

**Comment by nicolas-raoul** [comment]
What is wrong with creating the selector section programmatically in the Commons app too?

**Comment by sdabhi23** [comment]
By creating it programmatically, we won't be able to use the custom component, which might lead to inconsistent styling and it will definitely lead to inconsistency in code. Will be difficult for new contributors to understand what's exactly happening here, because there won't be a single way in which everything has been implemented.

**Comment by sdabhi23** [comment]
@nicolas-raoul I have got the UI ready for the selector but it isn't functional yet. And from [this](https://github.com/ankidroid/Anki-Android/issues/4729) issue it looks like the folks at AnkiDroid are also facing a similar issue

**Comment by Ayan-10** [comment]
@nicolas-raoul Can I work on this issue?

**Comment by nicolas-raoul** [comment]
@Ayan-10 Sure, thanks!
