### ISSUE TITLE
Ask for nearby if photo has location in Exif, and possible nearby photo

### ISSUE THREAD

**Issue by neslihanturan** [commons-app/apps-android-commons#1822]
**Summary:** 

This issue is request of one of our user, Luistxo Fernandez: 

>  When picture location is in the Exif, prompt dialogue: 'Do you wish to add this image to some nearby wikidata item'? showing a list...

This can be very beneficial indeed. Ie. a user doesn't know how to use nearby feature, but uploading a photo from nearby list. We can directly ask to edit wikidata item too.

**Comment by nicolas-raoul** [comment]
Not a list, but we now suggest one Wikidata item if it is close enough. 🙂
