### ISSUE TITLE
Get ACRA crash reporting system working again

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#1833]
**Summary:** 

We used to have ACRA crash reports. Then we didn't. Then we fixed that. But now we don't have them again. These reports are very useful because they allow users to add comments to tell us what they were doing at the time of the crash

**Steps to reproduce:** 

Generate a crash. If ACRA reports were working, there would be an option to report the crash (not just close or reopen app).

**Device and Android version:** 

Several different ones, including API 21 and API 24
 
 **Commons app version:** 

Current master

**Would you like to work on the issue?**

Preferably not

**Comment by albendz** [comment]
Is this the same or different from: https://github.com/commons-app/apps-android-commons/issues/1882 ?

**Comment by misaochan** [comment]
The same! Thanks for pointing it out. :)
