### ISSUE TITLE
If no coordinates, ask where picture was taken

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#1848]
Often GPS does not work, or is not enabled, and the picture has no coordinates, making it probably useless, see for instance https://commons.wikimedia.org/wiki/File:%D8%B5%D9%88%D8%B1%D8%A9_%D9%84%D9%82%D8%B1%D9%8A%D8%AA%D9%8A_.jpg

In such cases, we should ask the user where the picture was taken.

**Comment by misaochan** [comment]
Why does this require Structured Commons?

**Comment by ioshomebrew** [comment]
And question, should I require users to enter a location in the event GPS is disabled?

**Comment by nicolas-raoul** [comment]
@misaochan : When Structured Commons gets implemented, there will be a location field which will take as a value a Wikidata item, for instance https://www.wikidata.org/wiki/Q200126 (Paris 18). If we implement it now, we have to take the Wikidata item's P373 (Commons category) property. Nothing bad enough to justify postponing if you feel this feature is important, though :-)

@ioshomebrew 
Thanks for volunteering!
Yes, even if GPS is disabled. Some people disable GPS for privacy reason, but they will probably be OK with specifying the location up to the level they are confortable with, for instance country or city.

Scenario:

1. Ahmed upload a picture showing police misconduct, after striping all EXIF information via for his privacy.
2. The app asks Ahmed for title/description/categories as usual.
3. The app figures that Ahmed has not entered any category linked to a location.
4. The app shows a list of continents, Ahmed chooses a continent.
5. The app shows a list of countries, Ahmed chooses one.
6. The app shows a list of regions, Ahmed chooses one.
7. Etc. The levels may differ, for instance non-countries and regions containing other regions. Continents are hard-coded (https://www.wikidata.org/wiki/Q15 https://www.wikidata.org/wiki/Q18 https://www.wikidata.org/wiki/Q46 https://www.wikidata.org/wiki/Q48 https://www.wikidata.org/wiki/Q49 https://www.wikidata.org/wiki/Q51 https://www.wikidata.org/wiki/Q538) Countries are found using the P30 ("continent") property of items that are an instance of country. Lower levels are found using P131 ("located in the administrative territorial entity") property. Each level has a "Choose this location" button. Ahmed chooses https://www.wikidata.org/wiki/Q200126
8. The app retrieves https://www.wikidata.org/wiki/Q200126 's P373 which is https://commons.wikimedia.org/wiki/Category:Paris_18e_arrondissement and adds that category to the picture.

Please let me know if you need help writing the SPARQL queries. [Here is an example](https://query.wikidata.org/#SELECT%20%3Fcountry%20%3FcountryLabel%20%0AWHERE%20%0A%7B%0A%20%20%3Fcountry%20wdt%3AP31%20wd%3AQ6256.%20%23%20Instance%20of%20country%0A%20%20%3Fcountry%20wdt%3AP30%20wd%3AQ15.%20%23%20Whose%20continent%20is%20Africa%20%0A%20%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22%5BAUTO_LANGUAGE%5D%2Cen%22.%20%7D%0A%7D).

**Comment by VojtechDostal** [comment]
The idea with continents/countries etc is nice but quite complex... why wouldnt we just ask the uploader to pin a place in a google map/default map viewer and save that position?

**Comment by misaochan** [comment]
Ah I see, thanks for the explanation @nicolas-raoul . I think this would be useful even before Structured Commons, probably. :) 

I agree that pinning a place in a map would be ideal, but not sure if we can utilize a 3rd party app for that purpose. We might potentially need to generate our own map (probably in a similar manner to how we call Mapbox for Nearby).

**Comment by ioshomebrew** [comment]
Progress Update: implemented location bar in upload page and requirement to add location

**Comment by nicolas-raoul** [comment]
Cool! Don't hesitate to post early screenshots, and push your commits to your GitHub repo :-)

**Comment by ioshomebrew** [comment]
https://github.com/ioshomebrew/apps-android-commons

**Comment by ioshomebrew** [comment]
Just discovered that in order to set the coordinates of a picture, I have to modify the metadata inside the image file itself

**Comment by nicolas-raoul** [comment]
@ioshomebrew Any progress on this since your last commit (Sep 5, 2018)? Don't hesitate to push anything, even if not finished :-)

**Comment by nicolas-raoul** [comment]
Re-reading this issue nearly a year later, I agree that putting a pin (or zooming/centering a place in the middle of the screen) sounds more developer-friendly and user-friendly.

At least for users who can read maps (before smartphones existed I remember walking around a city and asking local people where we are on a paper city map, many had no idea).

**Comment by NotSoImportant** [comment]
As there is a separate wikidata entry for coordinates now, it should be offered to add and edit it.
IMHO same as #8.

**Comment by nicolas-raoul** [comment]
Good news, there is now a location picker in the Upload Wizard, it is the map icon at the top of the caption/description step.

I suggest making this location picker a fully-fledged Upload Wizard step for pictures that have no location.

**Comment by NotSoImportant** [comment]
Latest 3.1.1 release does not have it

**Comment by Ayan-10** [comment]
@nicolas-raoul I would like to work on it.

**Comment by nicolas-raoul** [comment]
@NotSoImportant It is in master, so it will be in the next release 🙂

@Ayan-10 Thanks!

**Comment by Ayan-10** [comment]
> I suggest making this location picker a fully-fledged Upload Wizard step for pictures that have no location.

@nicolas-raoul That means for those images which have no location there should be an extra step after description/caption where users are forced to pick a location using the location picker. Right?

**Comment by nicolas-raoul** [comment]
@Ayan-10 Yes, exactly! Users should have a "Skip" button in case they do not want to pick a location, though.
