### ISSUE TITLE
Show media talk page

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#1850]
Each media on Commons has a talk page.

While not as active as on Wikipedia or Wikivoyage, they can still be useful.

We could include the media's talk page discussion (if any) at the bottom of the media details.

Not sure what is the bast way to include:
- Take the wikicode and show it as is?
- Take the wikicode and attempt to make it human-friendly?
- Take the HTML of the page and display the whole thing (that would probably include too much cruft, though)
- Find a Mediawiki API that gives us the rendered conversation part (best)

**Comment by Mansi449** [comment]
@nicolas-raoul I would like to give it a try.

**Comment by Mansi449** [comment]
@nicolas-raoul what exactly must be displayed in the talk section of media details?  Let, for example, consider the links that you added in the issue #1851 each contain two messages. So have we to show both the messages in the `Talk` section (to be added) in `Media Details`. 
Links:
https://commons.wikimedia.org/wiki/File_talk:Zhu_(Julian_Zhu).jpg
https://commons.wikimedia.org/wiki/File_talk:Concept_usages_technologie_identit%C3%A9_adapt%C3%A9_de_l%27%C3%A9cole_de_design_de_Nantes.jpg

And if there exists a media which has a good number of messages on its talk page, how must we go about displaying them?

Also, could you please elaborate where can the wikicode that you mentioned be found and how could we use it?

Thanks

**Comment by nicolas-raoul** [comment]
For https://commons.wikimedia.org/wiki/File_talk:Zhu_(Julian_Zhu).jpg here is the part that should be shown in the app:
![screenshot from 2018-08-27 12-18-19](https://user-images.githubusercontent.com/99590/44638734-65828600-a9f3-11e8-99db-55539a79ce10.png)
You can get the wikicode via the Mediawiki API, I don't remember the exact syntax. There might be an option for rendering templates that are contained within the wikicode.
This would still require some pattern replacing before being displayable.
I don't think any media talk page is longer than 1MB, and I am sure that 99.9% of them are less than 10KB, so no need to worry about that for now, I would say :-)

**Comment by Mansi449** [comment]
Thanks for the clarification @nicolas-raoul. 
Okay, I would browse the Mediawiki API for the wikicode if required.

**Comment by Mansi449** [comment]
@nicolas-raoul I found the WikiCode for the part that needs to be shown in the app. So, would you please tell me how can I render it on the app in the desired format?

For eg: 
The WikiCode for https://commons.wikimedia.org/wiki/File_talk:Zhu_(Julian_Zhu).jpg is:
`{{Ping|Exilexi}} Is it the same person as in this YouTube video? IL6ipX1QnZE?t=19 ? If yes please add more details saying why the person is notable, and add categories. Thanks! [[User:Syced|Syced]] ([[User talk:Syced|<span class=\"signature-talk\">{{int:Talkpagelinktext}}</span>]]) 11:23, 22 August 2018 (UTC)
:{{Ping|Syced}} yes it is! Sorry, I didn't work on the image after the mobile upload. Will add the details & categories right now. --[[User:Exilexi|Exilexi]] ([[User talk:Exilexi|<span class=\"signature-talk\">{{int:Talkpagelinktext}}</span>]]) 14:09, 22 August 2018 (UTC)
`

**Comment by Mansi449** [comment]
@nicolas-raoul I tried using `action=expandtemplates` with different parameters. 
For example, using [this](https://en.wikipedia.org/w/api.php?action=expandtemplates&text={{Ping|Exilexi}}%20Is%20it%20the%20same%20person%20as%20in%20this%20YouTube%20video?%20IL6ipX1QnZE?t=19%20?%20If%20yes%20please%20add%20more%20details%20saying%20why%20the%20person%20is%20notable,%20and%20add%20categories.%20Thanks!%20[[User:Syced|Syced]]%20([[User%20talk:Syced|%3Cspan%20class=\%22signature-talk\%22%3E{{int:Talkpagelinktext}}%3C/span%3E]])%2011:23,%2022%20August%202018%20(UTC)%20:{{Ping|Syced}}%20yes%20it%20is!%20Sorry,%20I%20didn%27t%20work%20on%20the%20image%20after%20the%20mobile%20upload.%20Will%20add%20the%20details%20&%20categories%20right%20now.%20--[[User:Exilexi|Exilexi]]%20([[User%20talk:Exilexi|%3Cspan%20class=\%22signature-talk\%22%3E{{int:Talkpagelinktext}}%3C/span%3E]])%2014:09,%2022%20August%202018%20(UTC)&prop=wikitext), I am getting an output amost similar to the wikicode that I had got earlier. But this can't be displayed in the app directly.
Is there any module in the code which can parse wikitext to displayable format? If not, how should I go about rendering it in the app?

**Comment by nicolas-raoul** [comment]
1. Display it in a WebView or similar.
2. Use regular expressions or String.replaceAll to replace things that did not get transformed by expandtemplates :-)

**Comment by maskaravivek** [comment]
Is there any module in the code which can parse wikitext to displayable format?

> https://www.mediawiki.org/wiki/Parsoid

The Wikipedia app uses Parsoid but its not clear how they have integrated it.

**Comment by Mansi449** [comment]
I have found out the way to render media talk in the app in a displayable format. I have tested it on some sample text and it is working perfectly fine :-)
Now I would be implementing the code for making API requests to get the required text from the corresponding pages.

**Comment by sp2710** [comment]
I would like to give it a try.
@Mansi449 are you still working on this issue?

**Comment by sp2710** [comment]
I would like work on this
@Mansi449 are you still working on this issue?

**Comment by maskaravivek** [comment]
@sp2710 You can pick up this issue. There have been no updates from @Mansi449 from the past few months. :)

**Comment by sp2710** [comment]
@maskaravivek I found the WikiCode and used https://www.mediawiki.org/w/api.php?action=help&modules=flow-parsoid-utils to convert it in html and parsed to displayable format
Now it is looking like this

>@Exilexi: Is it the same person as in this YouTube video? IL6ipX1QnZE?t=19 ? If yes please add more details saying why the person is notable, and add categories. Thanks! Syced (talk) 11:23, 22 August 2018 (UTC)\u00a0:@Syced: yes it is! Sorry, I didn't work on the image after the mobile upload. Will add the details 

Any suggestions on what should should be done with \u00a0 character?
Should I replace it with a new line or something else need to be done?

**Comment by nicolas-raoul** [comment]
@sp2710 Yes a newline or two would be the best here I guess :-)

**Comment by sp2710** [comment]
@nicolas-raoul @maskaravivek What should be the node or x-path to this api call for converting wikicode to html?
I got the following results in API Sandbox 

>{
    "flow-parsoid-utils": {
        "format": "html",
        "content": "<body data-parsoid='{\"dsr\":[0,525,0,0]}' lang=\"en\" dir=\"ltr\" parsoid-version=\"2.0.0\" base-url=\"//www.mediawiki.org/wiki/\"><section data-mw-section-id=\"0\" data-parsoid=\"{}\"><p data-parsoid='{\"dsr\":[0,525,0,0]}'><span about=\"#mwt1\" typeof=\"mw:Transclusion\" data-parsoid='{\"pi\":[[{\"k\":\"1\"}]],\"dsr\":[0,15,null,null]}' data-mw='{\"parts\":[{\"template\":{\"target\":{\"wt\":\"Ping\",\"href\":\"./Template:Ping\"},\"params\":{\"1\":{\"wt\":\"Thibdx\"}},\"i\":0}}]}'>@</span><a rel=\"mw:WikiLink\" href=\"./User:Thibdx\" title=\"User:Thibdx\" about=\"#mwt1\">Thibdx</a><span about=\"#mwt1\">:</span>: Est-ce toi qui as dessin\u00e9 cette image ? Ou tu l'as t\u00e9l\u00e9charg\u00e9e depuis un autre site ou autre ? Merci ! <a rel=\"mw:WikiLink\" href=\"./User:Syced\" title=\"User:Syced\" data-parsoid='{\"stx\":\"piped\",\"a\":{\"href\":\"./User:Syced\"},\"sa\":{\"href\":\"User:Syced\"},\"dsr\":[120,140,13,2]}'>Syced</a> (<a rel=\"mw:WikiLink\" href=\"./User_talk:Syced\" title=\"User talk:Syced\" data-parsoid='{\"stx\":\"piped\",\"a\":{\"href\":\"./User_talk:Syced\"},\"sa\":{\"href\":\"User talk:Syced\"},\"dsr\":[142,222,18,2]}'><span class=\"signature-talk\" data-parsoid='{\"stx\":\"html\",\"dsr\":[160,220,29,7]}'><span about=\"#mwt2\" typeof=\"mw:Transclusion\" data-parsoid='{\"pi\":[[]],\"dsr\":[189,213,null,null]}' data-mw='{\"parts\":[{\"template\":{\"target\":{\"wt\":\"int:Talkpagelinktext\",\"function\":\"int\"},\"params\":{},\"i\":0}}]}'>talk</span></span></a>) 11:38, 22 August 2018 (UTC)<span typeof=\"mw:DisplaySpace mw:Placeholder\" data-parsoid='{\"src\":\" \",\"isDisplayHack\":true,\"dsr\":[251,252,null,0]}'>\u00a0</span>:<span about=\"#mwt3\" typeof=\"mw:Transclusion\" data-parsoid='{\"pi\":[[{\"k\":\"1\"}]],\"dsr\":[253,267,null,null]}' data-mw='{\"parts\":[{\"template\":{\"target\":{\"wt\":\"Ping\",\"href\":\"./Template:Ping\"},\"params\":{\"1\":{\"wt\":\"Syced\"}},\"i\":0}}]}'>@</span><a rel=\"mw:WikiLink\" href=\"./User:Syced\" title=\"User:Syced\" about=\"#mwt3\">Syced</a><span about=\"#mwt3\">:</span>:Je confirme qu'elle est de moi. Dessin\u00e9e il y a plus de 10 ans pour un blog destin\u00e9 \u00e0 la sensibilisation sur le design. -- <a rel=\"mw:WikiLink\" href=\"./User:Thibdx\" title=\"User:Thibdx\" data-parsoid='{\"stx\":\"piped\",\"a\":{\"href\":\"./User:Thibdx\"},\"sa\":{\"href\":\"User:Thibdx\"},\"dsr\":[391,413,14,2]}'>Thibdx</a> (<a rel=\"mw:WikiLink\" href=\"./User_talk:Thibdx\" title=\"User talk:Thibdx\" data-parsoid='{\"stx\":\"piped\",\"a\":{\"href\":\"./User_talk:Thibdx\"},\"sa\":{\"href\":\"User talk:Thibdx\"},\"dsr\":[415,496,19,2]}' class=\"new\"><span class=\"signature-talk\" data-parsoid='{\"stx\":\"html\",\"dsr\":[434,494,29,7]}'><span about=\"#mwt4\" typeof=\"mw:Transclusion\" data-parsoid='{\"pi\":[[]],\"dsr\":[463,487,null,null]}' data-mw='{\"parts\":[{\"template\":{\"target\":{\"wt\":\"int:Talkpagelinktext\",\"function\":\"int\"},\"params\":{},\"i\":0}}]}'>talk</span></span></a>) 20:46, 22 August 2018 (UTC)</p></section></body>"
    }
}
`

**Comment by nicolas-raoul** [comment]
Just extract the text you can get easily, and ignore the rest.

**Comment by sp2710** [comment]
@nicolas-raoul I have made the changes and sent the PR
Kindly review the PR and share your feedbacks:)

**Comment by maskaravivek** [comment]
@sp2710 Nice work with extracting readable text from the wikitext. :)

I was wondering if we should show the talk page on the same page or should it open a separate activity. Theoretically, the discussions can be quite long(although I agree that it would be quite small for most images). 

Would it be better to launch a new activity ie `GenericTalkPageActivity`. Later the same can be used to show other talk pages.

**Comment by sp2710** [comment]
Thanks @maskaravivek :)
I also agree that it would be better to launch a new activity for showing the talk page

**Comment by maskaravivek** [comment]
@sp2710 it would be great if you could wait for  @nicolas-raoul @misaochan opinions before making the change. They have a better understanding of the Wikimedia world. :)

**Comment by sp2710** [comment]
Sure @maskaravivek.  I have not done any changes yet. Will wait for @nicolas-raoul @misaochan opinions :+1:

**Comment by nicolas-raoul** [comment]
I think there is no need to create a separate activity.

While Wikipedia talk pages can be extremely long, I have never seen a media talk page with more than a few lines.

**Comment by maskaravivek** [comment]
@nicolas-raoul I suggested a separate activity as this could be reused for other talk pages as well ie for any talk page. Some talk pages open from Notifications page as well. If we do it well, it can be reused(or extended) for those purposes as well. 

For the scope of this task, it might not be required but I feel the media detail page is already bloated with a lot of content. We can probably show the first couple of lines on the same page and launch a new activity if the content is bigger than that.

**Comment by ujjwalagrawal17** [comment]
Also if we want to add edit functionality later in media talk page it would be better to make a separate activity.
