### ISSUE TITLE
No of Uploads not updated 

### ISSUE THREAD

**Issue by gupta1anubhav** [commons-app/apps-android-commons#1853]
**Summary:** 
No of uploads doesn't increase after uploading the image.

**Steps to reproduce:** 
You can upload a new image and no of uploads count doesn't increase from the previous value.

**Device and Android version:** 

Tested On Redmi Note 4 (Nougat)

 **Commons app version:** 
 prodDebug.
 
**Screen-shots:** 
![screenshot_2018-08-24-20-36-48-482_fr free nrw commons debug](https://user-images.githubusercontent.com/31107831/44593568-5e842980-a7e1-11e8-97dd-1862bf212b8a.png)

**Would you like to work on the issue?**
 Yes, I would like to work on this issue.

**Comment by neslihanturan** [comment]
Recently, we have a similar report. So this issue can be alive.

**Comment by Prince-kushwaha** [comment]
@neslihanturan this issue present in latest master

**Comment by Prince-kushwaha** [comment]
@nicolas-raoul can i work on this issue
