### ISSUE TITLE
Open notification when touching any part of the notification item.

### ISSUE THREAD

**Issue by befrou** [commons-app/apps-android-commons#1862]
**Summary:** 
In Notifications when i touch the text of an item nothing happens. Thought it would be good if It was possible to click in any part of the item and it would do its given action.

**Steps to reproduce:** 

How can we reproduce the issue? 
Go to notifications and touch the text in the middle of the item related to the notification.

What did you expect the app to do, and what did you see instead?
Expected the app to open the notification.

**Device and Android version:** 
Zenfone 3 deluxe, Android 8.0.0
 
 **Commons app version:** 
2.8.2

**Would you like to work on the issue?**

Yes, I would like to give it a try even though I am fairly new to android development and it would be my first contribution to an open source project.

**Comment by nicolas-raoul** [comment]
Indeed that would be great!
Good luck with implementation, please let us know :-)

**Comment by misaochan** [comment]
Thanks for reporting this! To be clear, the app would open the notification if you tap the right side or the left side (the icon or date). We did not implement this for the middle part due to conflict with the "show more" link. Is it desirable to have the middle part work the same way as the others?

**Comment by befrou** [comment]
Just thought it would be good. The first time I used the app I insisted on clicking on the middle part out of habit.

**Comment by befrou** [comment]
I think it comes down to whether or not the onclick in the "middle text" conflicts with the "show more" as @misaochan mentioned. I will give it a try. 

If I have questions about the code where do I ask? In the issue or in the group? Thanks for your attention.

**Comment by misaochan** [comment]
Sounds good @befrou :) Please feel free to ask in this issue if you have any questions.

**Comment by befrou** [comment]
I used "SpannableString" to setup a 'ClickableSpan" in the "middle text" and it worked without conflict with the "See more". The only thing that bothers me is that the click on the "middle text" doesn't highlight the "Notification" as it does when you click the "date" at the right side or the "icon" at the left side.

**Comment by misaochan** [comment]
I think it should be OK in that case. Could you please submit your PR so we can try it out @befrou ? Thanks!

**Comment by domdomegg** [comment]
Fixed in #1872
