### ISSUE TITLE
[category browsing branch] Categories not added

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#1867]
In the Git ujjwalagrawal17:feat_issues_66 branch, it seems that categories are not added.
For instance, I selected 2 categories for https://commons.wikimedia.org/wiki/File:%E3%81%9F%E3%81%93%E3%82%84%E3%82%93.jpeg but none made it to the server.

**Comment by albendz** [comment]
@nicolas-raoul It looks like a word might have been missing from your description in the bug. Could you correct? Are there repro steps? Once I know how to reproduce I'll pick this up.

**Comment by nicolas-raoul** [comment]
@albendz Indeed I had forgotten a word, fixed, thanks! :-)

**Comment by albendz** [comment]
Thanks! I'll start taking a look at this. And to clarify, this happens when you select categories but on save, they are not persisted to server, right?

**Comment by albendz** [comment]
I'm on the browse-commons-via-app branch and I uploaded a photo with a "restaurants" category and I see that category appear at the bottom of the page on the website: https://commons.wikimedia.beta.wmflabs.org/wiki/File:Woodinville_cafe.jpg

Is this working correctly?

The last commit via git log is:
commit 11b13bed4897df05cc3ec5ef6e81bd793792e623 (HEAD, upstream/browse-commons-via-app)
Author: Ujjwal Agrawal <ujjwal@codenicely.in>
Date:   Mon Jul 23 16:53:39 2018 +0530

Perhaps this isn't the right branch?

**Comment by albendz** [comment]
@nicolas-raoul Is this still relevant?

**Comment by nicolas-raoul** [comment]
Sorry, it seems that I was wrong, and I guess this was related to this branch:
https://github.com/commons-app/apps-android-commons/pull/1784

**Comment by albendz** [comment]
Okay, since that hasn't been merged, is that something I should pick up or leave to the PR owner?

**Comment by nicolas-raoul** [comment]
The PR owner does not seem to be around anymore, maybe this can be closed and linked to from the PR.
