### ISSUE TITLE
"To-do list" for users

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#1870]
As suggested by @nicolas-raoul , it might be a good idea to display a to-do list for the user that contains:
 - images that they uploaded with no categories/descriptions, so that they can add them (after #161 is implemented)
- images that can be added to associated Wikipedia articles that have no pictures (for #872 )

Perhaps the user could filter their contributions list by 'action required' to show only these images. Even if the user doesn't filter, there should be an indicator (perhaps an icon on the bottom right of an image) for actions required. Maybe the 'W' icon for those that need to be added to Wikipedia articles, and a '!' icon for images with no categories/description?

**Comment by neslihanturan** [comment]
Hi @misaochan , I designed some mockups based on your definition. Waiting for feedbacks:)
Not: First and second icons are alternatives to each others

![missingInfoUI](https://user-images.githubusercontent.com/3127881/55476729-07202480-5620-11e9-8eb6-97c1a8ee3877.png)

**Comment by misaochan** [comment]
@neslihanturan Thanks for the mockups! To be honest I could not understand what the X symbol in the 2nd screenshot means, haha. The first one with the "i" icon looks OK to me but I'm not sure if it appropriately conveys a sense of "something is missing"? I would vote for a "!" symbol instead, to denote missing information.

I like the warning on the third screenshot. Maybe the text could say instead "You could improve the usability of this photo by adding: "

How do you reckon the filter for "action required" should be displayed?

**Comment by neslihanturan** [comment]
>I would vote for a "!" symbol instead, to denote missing information.
I thought I used an "!" sybmol indeed, sorry for the mistake:)

>How do you reckon the filter for "action required" should be displayed?
I am adding it to complete new UI mockups which I will be posting tomorrow.

**Comment by nicolas-raoul** [comment]
The band-aid idea is interesting, but a ! is probably more understandable indeed.

By the way, in the OpenStreetMap community, the icon for things to fix is the bug (even though it is not software bugs):

![Screenshot from 2019-04-04 17-40-47](https://user-images.githubusercontent.com/99590/55542335-cbf62200-5701-11e9-818d-67c256ef3f91.png)
![adb-screenshot](https://user-images.githubusercontent.com/99590/55542315-c8629b00-5701-11e9-8b1c-5c24650c9a6f.png)

**Comment by neslihanturan** [comment]
I liked the creative approach of this bugs, but it somehow scares me. I am not sure if it is a professional deformation or a regular user feeling though:)

**Comment by misaochan** [comment]
Ummm... another vote against the bugs here. Not good for us entomophobes... ^^;;
