### ISSUE TITLE
ACRA crash reports do not work again in 2.8.2

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#1882]
**Summary:** 

When the app crashes, there should be an option to "send feedback" so that users can send their stack trace to us along with comments about what they were doing at the time of the crash.

We already have ACRA for this purpose which used to work, but stopped working again at some point.

If anyone takes this up, please ensure that the logs are sent to the PRIVATE google group, not the public one, due to privacy concerns.

**Steps to reproduce:** 

Trigger a crash on 2.8.2. Not sure how far back this problem goes.

**Add System logs:**

**Device and Android version:** 

8.0 Samsung Galaxy s7
 
 **Commons app version:** 

2.8.2 Play Store version 

**Would you like to work on the issue?**

Pref not

**Comment by Bambam905** [comment]
Hello, 
I'm a bit rusty to java and would like to take a look at this issue.

**Comment by maskaravivek** [comment]
@Bambam905 thanks for showing interest. Am already working on a fix for this issue. :)

**Comment by maskaravivek** [comment]
I was unable to fix ACRA crash reporting but have made an attempt to migrate to the latest version and use a custom log sender in #1916. Anyone feel free to take up this task. It would be great if someone is able to reuse the changes made in #1916 as using a custom log sender will give us much more control on the crash reports.

**Comment by A-Hassan-M** [comment]
I will try to fix it i am a little bit busy but i can find some free time to put into this.

**Comment by misaochan** [comment]
It's yours, thanks @A-Hassan-M . :)

**Comment by A-Hassan-M** [comment]
sorry guys i have some problems with my laptop and i can't even run the project :''''D so anyone is free to take it.

**Comment by albendz** [comment]
I'll pick this up.

**Comment by albendz** [comment]
Is there a branch this is working on @misaochan so I can compare behavior?

**Comment by albendz** [comment]
Update: still working on this
