### ISSUE TITLE
Update Play Store screenshots

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#1890]
We should update the Play Store screenshots soon, as they are very outdated. :) I think only Nicolas or myself can do this. I'll try to sort it out after 2.8.3 is stable.

**Comment by sivaraam** [comment]
I just stumbled across the fact that the play store screenshots are stale (again!). Since the UI revamp, the app looks nothing like what one sees in the screenshot. So, it would be nice if we update them :)

I could help with getting the screenshots, if necessary. We've got to update the website too.

**Comment by misaochan** [comment]
Yikes, yes! If you could email me the updated screenshots I can update them in the Play Store, @sivaraam . Thanks a lot. :)

**Comment by sivaraam** [comment]
Sure! Right now the play store page has screenshots for the following:

- Screenshot of "Contributions" screen
- Uploads screen
- Categories screen
- A preview of an upload
- Menu page
- Nearby map
- Nearby list
- Another photo that shows categories screen

A few questions:
1. Do we really need to include a screenshot of the menu?
2. Regarding the upload screen, the one in the app store captures all content in one page but we have a multi-page upload flow now. Is it enough if I get a screenshot of the first page and categories page?
3. Do we really need two photos of categories screen?
4. I can help with the mobile screenshots. I'm not sure what to do about the tablet ones. I could spin-up an emulator but I'm not sure I have that many good uploads in my account to showcase :) It would be great if anyone else willing to take that up or suggest some ideas for that.

Apart from this, I believe we should include a screenshot of the explore screen. Any other suggestions for what screenshots we should showcase in the play store?

Also, the video content looks good but its otherwise super-stale w.r.t various screens shown in it. Should we do anything about it?

**Comment by misaochan** [comment]
> Do we really need to include a screenshot of the menu?

I don't think so now that we have bottom bar navigation.

> Regarding the upload screen, the one in the app store captures all content in one page but we have a multi-page upload flow now. Is it enough if I get a screenshot of the first page and categories page?

Yeah, I think that should be sufficient.

> Do we really need two photos of categories screen?

Nope. :)

> I can help with the mobile screenshots. I'm not sure what to do about the tablet ones. I could spin-up an emulator but I'm not sure I have that many good uploads in my account to showcase :) It would be great if anyone else willing to take that up or suggest some ideas for that.

I actually don't know if tablet screenshots are really necessary, what do you think? Granted the app does work on tablets, but the vast majority of users are using their phones (because who takes photos with tablets?). The main use case for tablets IMO would be someone who prefers to take the photo with their phone and then transfers it to their tablet.

> Apart from this, I believe we should include a screenshot of the explore screen. Any other suggestions for what screenshots we should showcase in the play store?

I think Leaderboard or Achievements would be nice (if it currently works well).

> Also, the video content looks good but its otherwise super-stale w.r.t various screens shown in it. Should we do anything about it?

Ah, yeah, I've been hesitant to replace that because it was made by a volunteer who was a professional videographer (John Lubbock from WMUK). It really is super stale by now, but I don't think anyone on the team has the video equipment to make anything similar in terms of quality. :/ If anyone is interested to take this up, that would be fantastic.

**Comment by sivaraam** [comment]
Thanks for the answers! I'll try to get the screenshots soon.

> I actually don't know if tablet screenshots are really necessary, what do you think?

I'm not sure either. I don't use a tablet often so I can't really comment. Maybe other tablet users might be able to comment?

>  Granted the app does work on tablets, but the vast majority of users are using their phones (because who takes photos with tablets?). The main use case for tablets IMO would be someone who prefers to take the photo with their phone and then transfers it to their tablet.

Right. Anyways, I'll try taking screenshots of tablet in case it isn't too much hassle setting it up via emulator :)

> Ah, yeah, I've been hesitant to replace that because it was made by a volunteer who was a professional videographer (John Lubbock from WMUK). It really is super stale by now, but I don't think anyone on the team has the video equipment to make anything similar in terms of quality. :/ If anyone is interested to take this up, that would be fantastic.

Ah, right. Thanks for the context. Looks like its better to leave it as it is unless we get anything better then 👍🏼 

You think we could ask if the user would be interested in doing another one for us?

> Might also be worth noting that due to a few pesky bugs that we've only just managed to solve, v3 is not out in production yet. It really should be within a few weeks though.

Ah, ok. So, I'll just take with screenshots of v3 anyway. I'll likely get those screenshots before v3 is pushed to production so you could also update the screenshots while releasing v3.

**Comment by misaochan** [comment]
> You think we could ask if the user would be interested in doing another one for us?

I haven't been in contact with him for years now (not even sure if he's still with WMUK) but we could try.

> Ah, ok. So, I'll just take with screenshots of v3 anyway. I'll likely get those screenshots before v3 is pushed to production so you could also update the screenshots while releasing v3.

Sounds good, thanks a lot. :)

**Comment by sivaraam** [comment]
> I think Leaderboard or Achievements would be nice (if it currently works well).

It looks like my user account doesn't that many uploads to showcase the leaderboard well. Also, Achievement appears to be broken, its showing any text in "Statistics" section (let me verify and open an issue for this if none exists). Also, there's a weird empty white bar shown above Achievement and Leaderboard tabs which kind of spoils the UI (ditto on the issue). An example:

![Screenshot_20210525-234559](https://user-images.githubusercontent.com/12448084/119547998-636fd080-bdb3-11eb-8717-241112124c92.jpg)

What can we do about this?

**Comment by sivaraam** [comment]
> Also, Achievement appears to be broken, its showing any text in "Statistics" section (let me verify and open an issue for this if none exists).

Looks like there's already PR #4416 for fixing the missing title issue at least :) That leaves us with the white bar issue. I'll open one for that.

**Comment by sivaraam** [comment]
I've sent the first version of screenshots to @misaochan via mail. I'm adding them here publicly for reference. Kindly take a look and let me know your feedback.

<details>
<summary>Commons app v3.0.0.1003 screenshots</summary>

**Single archive:** [Commons_app_v3.0.0.1003_screenshots.zip](https://github.com/commons-app/apps-android-commons/files/6566677/Commons_app_v3.0.0.1003_screenshots.zip)

<details>
<summary><b>In-line screenshots</b></summary>

![1_contributions](https://user-images.githubusercontent.com/12448084/120115036-8fb69300-c19f-11eb-89c4-270f4cc4288a.jpg)
![2_upload_screen_1](https://user-images.githubusercontent.com/12448084/120115037-9218ed00-c19f-11eb-842e-fc2e0877d655.jpg)
![3_upload_screen_2_depicts](https://user-images.githubusercontent.com/12448084/120115038-92b18380-c19f-11eb-8a03-0505f963fcde.jpg)
![4_upload_screen_3_categories](https://user-images.githubusercontent.com/12448084/120115039-92b18380-c19f-11eb-939b-2b471ddd0abb.jpg)
![5_media_details](https://user-images.githubusercontent.com/12448084/120115040-934a1a00-c19f-11eb-8c32-c313131efd26.jpg)
![6_nearby](https://user-images.githubusercontent.com/12448084/120115041-93e2b080-c19f-11eb-952e-bda8d46555a2.jpg)
![7_nearby_list](https://user-images.githubusercontent.com/12448084/120115043-9513dd80-c19f-11eb-9a1d-43ac06cb4a33.jpg)
![8_explore](https://user-images.githubusercontent.com/12448084/120115044-9513dd80-c19f-11eb-8e89-2457f8abcf8d.jpg)
![9_media_search](https://user-images.githubusercontent.com/12448084/120115045-95ac7400-c19f-11eb-92df-a3673a986ff3.jpg)
</details>

<details>
<summary><b>Rest of the screenshots</b></summary>
![Screenshot_20210525-232554_c](https://user-images.githubusercontent.com/12448084/120115073-b7a5f680-c19f-11eb-8d50-4a8405585647.jpg)
![Screenshot_20210525-232652_c](https://user-images.githubusercontent.com/12448084/120115076-b96fba00-c19f-11eb-8cad-6bd07517fda0.jpg)
![Screenshot_20210525-232701_c](https://user-images.githubusercontent.com/12448084/120115077-b96fba00-c19f-11eb-874e-f2919fa4ef58.jpg)
![Screenshot_20210525-233041_c](https://user-images.githubusercontent.com/12448084/120115078-ba085080-c19f-11eb-84f5-478313c7414a.jpg)

</details>


</details>

**Comment by misaochan** [comment]
Thanks a lot @sivaraam ! They look great. :) Looks like fixes are already in the works for both Achievements issues.

**Comment by sivaraam** [comment]
I had a passing thought, there are a few things that the set of screenshots above doesn't cover:

- Localization in multiple languages
- Exploring images without having to log in

Do we need to cover these possibly by replacing some other screenshots like reducing Nearby to just the map one or something like that?

Also, I managed to spin up the Tablet emulator. But I guess I wouldn't have too many good uploads to showcase for the tablet screenshot 😅  So, is it possible for someone else to take those screenshots? Or possibly have a test account that has good quality uploads that could be showcased which they could share with me? cc @nicolas-raoul

**Comment by nicolas-raoul** [comment]
@sivaraam

Indeed image exploration is one of the many things that appeared recently(?) and that screenshots are not covering right now.
Play screenshots are localized, so I believe that an Italian-locale user would see the few Italian screenshots we uploaded. We actually have screenshots of various quality in many languages: https://github.com/commons-app/marketing/tree/master/screenshots . I haven't found the time to upload them all unfortunately.

I just sent you an email about the last point.

I would gladly give you access to the Play console if it was still my account, but since I transferred the account to WMF I think we have not managed to get any new account, if I remember correctly. @misaochan Do you remember what is the situation on this? Should we ask for another Play Store account? As an argument, we can point out that accounts can still be delimited very finely (by app, by role), per this screenshot I took today when adding a user on another account:

<img width="787" alt="Screen Shot 2021-06-08 at 10 09 21" src="https://user-images.githubusercontent.com/99590/121106818-ba5cb780-c841-11eb-8025-84f06c81cc17.png">

**Comment by nicolas-raoul** [comment]
Screenshots should showcase perfect usage of the app. Sorry for the pedantry, but would you mind fixing these points that sound minor but would make most Commons veterans jump on their chair:
- Depiction: Please search for "bee" and select only https://www.wikidata.org/wiki/Q7391 . The heraldic symbol should not be selected because it is not what the image depicts. Nature should not be selected because it is a parent concept. I suggest selecting https://www.wikidata.org/wiki/Q506 (flower) too, or the more precise concept if you know the name of that flower.
- Same for categories
- Media details: How about showing for an image that has coordinates (even fake ones) and depictions?
- nearby map: How about having the blue circle showing your position (you can use a fake GPS app)? And how about having one pin selected, so that you can see possible actions?
- Nearby list: Maybe not needed? If you add it, please use fake GPS so that distance are not discouragingly far ;-)

"Rest of the screenshots" seems to be the same screenshots?

**Comment by misaochan** [comment]
> I would gladly give you access to the Play console if it was still my account, but since I transferred the account to WMF I think we have not managed to get any new account, if I remember correctly. @misaochan Do you remember what is the situation on this? Should we ask for another Play Store account? As an argument, we can point out that accounts can still be delimited very finely (by app, by role), per this screenshot I took today when adding a user on another account:

I think @sivaraam was requesting a "test Commons account" that already has a large number of good uploads so he could use it to take screenshots? IMO (if it's allowed by Commons policies) a shared Commons account would be great, removing a barrier for our volunteers. We can just load it with good pics and email the login to trusted volunteers who need it.

As for the WMF Play console account, unfortunately even getting new people added just for purely READ access has been extremely slow and tedious. For instance, I'm still in the process of getting Madhur access, after a month of emailing. Getting an additional account with some privileges for our app would be fantastic, especially because it means one of our core developers will be able to push hotfixes if I'm away, etc. I am however not holding my breath.

**Comment by sivaraam** [comment]
> I think @sivaraam was requesting a "test Commons account" that already has a large number of good uploads so he could use it to take screenshots?

Yes.

> IMO (if it's allowed by Commons policies) a shared Commons account would be great, removing a barrier for our volunteers. We can just load it with good pics and email the login to trusted volunteers who need it.

I was thinking Nicolas brought up the Play console account hinting at getting some volunteers to directly do screenshot uploads to play store. Particularly, the language specific screenshots in `marketing` folder. 🤔

**Comment by nicolas-raoul** [comment]
Great screenshots!
Only one more nitpick: The "Uploaded via mobile" screenshot has a watermarked (most probably copyrighted) picture, and the clouds picture is not really an example of what we want people to upload. Looking at recent mobile uploads right now, I think that all of the pictures seen in the screenshots below are much more exemplary, they have high chances of illustrating a Wikipedia article, they could not be taken easily by anyone not present at that place/moment, and they have a good caption. Would you mind using one of these sets? :-)
![adb](https://user-images.githubusercontent.com/99590/121450115-0f313700-c9d6-11eb-853f-df434fb7e776.png)
![adb](https://user-images.githubusercontent.com/99590/121450344-85359e00-c9d6-11eb-8dfe-fcc16fdc0005.png)
![adb](https://user-images.githubusercontent.com/99590/121450724-3f2d0a00-c9d7-11eb-92df-39dd0c777df6.png)

Jo: I actually had sent a test account already, and was thinking of Play accounts too, but I see that it has not gotten easier unfortunately. How about using the [API](https://developers.google.com/android-publisher) to upload these screenshots, as we already have API access to publish alphas? Anyone could send pull requests to suggest screenshots, any team member would check their quality (ideally with the help of another Wikimedian who can read the language), and a script would push them as soon as the commit is merged. We could also push Play descriptions this way.

**Comment by sivaraam** [comment]
Here's the first "Uploaded via mobile" screenshot from my [above comment](https://github.com/commons-app/apps-android-commons/issues/1890#issuecomment-858855406) with a rough header:

![9_explore_without_logging_in_with_header](https://user-images.githubusercontent.com/12448084/121578458-51935c00-ca48-11eb-84bd-617a23f26fa0.jpg)

If this header sounds like a good idea, I could try adding header text like this for other ones too. If not, no worries I could just drop the idea.

**Comment by nicolas-raoul** [comment]
I believe that a screenshot is not the best way to convey that browsing does not require logging in. The text description is a much better place for this. Most people probably already take for granted that exploring Commons is possible without logging in, so impact on readers is probably minimal, maybe even negative. We should better add screenshots for more visual&innovative features such as: review, achievements, leaderboard, privacy section of the settings and the few settings above it, place type selection in Nearby, items search.
Cheers!

**Comment by sivaraam** [comment]
> We should better add screenshots for more visual&innovative features such as: review, achievements, leaderboard, privacy section of the settings and the few settings above it, place type selection in Nearby, items search.

I could get screenshots of these too but @misaochan mentioned something about a play store limit. I read somewhere that the limit is eight but I'm not sure. So, I'm reluctant to get more screenshots. If someone could clarify what the limit is and what screenshots we could showcase within it, I could get those screenshots.

Assuming eight, one possible option I could think of is:

1. Contributions
2. Upload screen (first page)
3. Media details
4. Nearby
5. Explore
6. Peer Review
7. Achievements
8. Leaderboard

What do others think?

**Comment by sivaraam** [comment]
Ok. So, here's round 3. Let me know how it looks.

<details>
<summary>Screenshots v3</summary>

<details>
<summary>Main shots</summary>

![1_contributions](https://user-images.githubusercontent.com/12448084/121816924-12f5df80-cc9c-11eb-8f4b-a5e846339d7d.jpg)
![2_upload_screen_1](https://user-images.githubusercontent.com/12448084/121816925-15583980-cc9c-11eb-9b47-290586fbc3e8.jpg)
![3_media_details](https://user-images.githubusercontent.com/12448084/121816926-15f0d000-cc9c-11eb-873f-43be4c97c39f.jpg)
![4_nearby](https://user-images.githubusercontent.com/12448084/121816927-1721fd00-cc9c-11eb-9ce9-2a57e17c9b46.jpg)
![5_explore](https://user-images.githubusercontent.com/12448084/121816929-17ba9380-cc9c-11eb-88c0-8f68a5e84d9d.jpg)
![6_peer_review](https://user-images.githubusercontent.com/12448084/121816931-18532a00-cc9c-11eb-955c-037f20404dce.jpg)
![7_achievements](https://user-images.githubusercontent.com/12448084/121816932-18ebc080-cc9c-11eb-9e49-b6820fae7aa3.jpg)
![8_leader_board](https://user-images.githubusercontent.com/12448084/121816933-18ebc080-cc9c-11eb-8f52-9c097a001cac.jpg)

</details>

<details>
<summary>Some other contributions shot candidates</summary>

![contributions_rest_1](https://user-images.githubusercontent.com/12448084/121816951-3751bc00-cc9c-11eb-86ed-7643752dcbac.jpg)
![contributions_rest_2](https://user-images.githubusercontent.com/12448084/121816952-391b7f80-cc9c-11eb-9e63-5e33d39ddbdc.jpg)

</details>

</details>

I had to replace the contributions in the above to keep the contribution count consistent the one shown in the leaderboard screeenshot.

Archive of above shots: 
[Commons_app_v3.0.1_screenshots_v4.zip](https://github.com/commons-app/apps-android-commons/files/6644374/Commons_app_v3.0.1_screenshots_v4.zip)

Here's the first version for tablet:

<details>
<summary>Tablet screenshots</summary>

<details>
<summary>Main shots</summary>

![1_contributions](https://user-images.githubusercontent.com/12448084/121816991-6ff19580-cc9c-11eb-8dca-77b7270f8dbb.jpg)
![2_upload_screen](https://user-images.githubusercontent.com/12448084/121816995-71bb5900-cc9c-11eb-9871-31342af89195.jpg)
![3_media_details](https://user-images.githubusercontent.com/12448084/121816996-7253ef80-cc9c-11eb-9bfd-bf976536a6aa.jpg)
![4_explore](https://user-images.githubusercontent.com/12448084/121816998-73851c80-cc9c-11eb-8ec5-51c7e0581242.jpg)
![5_peer_review](https://user-images.githubusercontent.com/12448084/121816999-741db300-cc9c-11eb-9f3b-3b3f4e5e1b2a.jpg)
![6_achievements](https://user-images.githubusercontent.com/12448084/121817001-74b64980-cc9c-11eb-86de-d539cd48579b.jpg)
![7_leaderboard](https://user-images.githubusercontent.com/12448084/121817002-754ee000-cc9c-11eb-866b-a61b9138e73d.jpg)

</details>

<details>
<summary>A few other explore shot candidates</summary>

![explore_rest_1](https://user-images.githubusercontent.com/12448084/121817077-cd85e200-cc9c-11eb-9d3d-f656537a9d4c.jpg)
![explore_rest_2](https://user-images.githubusercontent.com/12448084/121817081-cf4fa580-cc9c-11eb-9126-4dce7b5e49d4.jpg)
![explore_rest_3](https://user-images.githubusercontent.com/12448084/121817084-cfe83c00-cc9c-11eb-80be-c4321104beb3.jpg)

</details>

</details>

Archive of the tablet shots: 
[Commons_tab_screenshots_3.0.1-debug-master_bd66218d3.zip](https://github.com/commons-app/apps-android-commons/files/6644378/Commons_tab_screenshots_3.0.1-debug-master_bd66218d3.zip)

I couldn't get the Nearby screenshot in tablet as for some reason the spinner keeps on spinning in the emulator. I'm yet to figure out why. I could share it when I get the issue sorted out.

On a side note, we really need to improve the tablet experience of the app. For instance, the preview of images in the Contributions screen doesn't look better than the old ones we could find in play store. The font size could use some improvement too. Not sure how much worth the effort is though.

**Comment by misaochan** [comment]
The screenshots look great to me. :)

> I could get screenshots of these too but @misaochan mentioned something about a play store limit. I read somewhere that the limit is eight but I'm not sure. 

This is the  requirement stipulated on the dev console:

Upload 2–8 phone screenshots
PNG or JPEG
16:9 or 9:16 aspect ratio
Each side between 320 px and 3,840 px
Up to 8 MB per screenshot

> I couldn't get the Nearby screenshot in tablet as for some reason the spinner keeps on spinning in the emulator. I'm yet to figure out why. I could share it when I get the issue sorted out.

Nearby is problematic in some emulators unfortunately, I'm not sure why either. I usually test Nearby on a real device for that reason.

> On a side note, we really need to improve the tablet experience of the app. For instance, the preview of images in the Contributions screen doesn't look better than the old ones we could find in play store. The font size could use some improvement too. Not sure how much worth the effort is though.

Tablet usage of our app is really low. We could still make some changes, but it is low priority IMO.

**Comment by misaochan** [comment]
v3 is out in production, and I have changed the Play Store screenshots to the ones from https://github.com/commons-app/apps-android-commons/issues/1890#issuecomment-860247149 . Thanks a lot @sivaraam and @nicolas-raoul ! :) It may take a while for the listing to be updated by Google.
