### ISSUE TITLE
Update the wiki to show the issues faced during the setup in Android Studio

### ISSUE THREAD

**Issue by konohakesh** [commons-app/apps-android-commons#1896]
We should update the wiki 'Develop-with-Android-Studio-or-IntelliJ' to show the issues newcomers face during the setup and how to fix them.  It will save a lot of time that goes in finding the fix by the first-timers if that issue is already witnessed by someone else.

I have attached the 'Develop-with-Android-Studio-or-IntelliJ.md' file in a zip which lists the issues I faced along with their fixes.

[Develop-with-Android-Studio-or-IntelliJ.zip](https://github.com/commons-app/apps-android-commons/files/2369460/Develop-with-Android-Studio-or-IntelliJ.zip)

**Comment by domdomegg** [comment]
Thank you very much! I've updated the wiki.
