### ISSUE TITLE
Empty screen if no upload

### ISSUE THREAD

**Issue by meditat** [commons-app/apps-android-commons#1912]
**Summary:** 
An empty screen on Landing page looks awkward.

**Steps to reproduce:** 
1. Sign up as a new user,
2. Login into your account
3. If you have no uploads you see an empty screen

**What did you expect the app to do, and what did you see instead?**
There should be an image or animation that say "No Uploads Yet" or "Nothing to explore"

**Screen-shots:** 
![whatsapp image 2018-10-02 at 10 20 34 pm](https://user-images.githubusercontent.com/20486279/46363719-7331c800-c691-11e8-8831-107d1f8c89a4.jpeg)

**Would you like to work on the issue?**
Yes, Assign this work to me.

**Comment by Rulino** [comment]
I will take this issue

**Comment by nicolas-raoul** [comment]
@Rulino OK it is yours! Please let us know about your progress every few days :-)

**Comment by nicolas-raoul** [comment]
For the text I would suggest:

> Welcome to Commons!
> Upload your first media by touching the camera or gallery icon above.
