### ISSUE TITLE
 Wiki techstorm (26th/27th October/The Netherlands) task ideas

### ISSUE THREAD

**Issue by neslihanturan** [commons-app/apps-android-commons#1913]
**Summary:** 

Hi team, there will be an event at the end of this month https://www.mediawiki.org/wiki/Wiki_Techstorm . I will be there to have a workshop for our app and there will be hackathon too. Do you propose any task to work on during hackathon?

**Comment by misaochan** [comment]
Do you have a rough idea of what skill level the participants will be at? Glancing at the program, it looks more like a short introductory event, where you would be teaching people how to contribute? In that case maybe fixing beginner-friendly bugs or small enhancements would be more appropriate than a large project.

**Comment by neslihanturan** [comment]
I agree about short time constraints. In that case, can we decide to scope of workshop? Should I require to have android studio and sdk before workshop?

**Comment by neslihanturan** [comment]
By the way "but we will also work with what we have called ‘practical projects’. These are projects in which participants and trainers/mentors can collaborate during the two day hackathon." they mentioned from two days practical project part. During workshop I can introduce our app development and then for 2 days, I still need your task ideas.

**Comment by nicolas-raoul** [comment]
Fixing a compilation warning might be an achievable task in two hours: #171 
Adding this intent is also achievable quickly by someone with Android experience: #537

For two days how about #1898 ? It is a "step-friendly" task, in that it is possible to implement a basic version of it in one day, a better version of it in two days, or even a wonderful version if you have 15 super-geniuses for two full days. Also, the benefit is easy to understand.
