### ISSUE TITLE
Description info dialog opens when tapped on the EditText in the blank space between hint and info icon. 

### ISSUE THREAD

**Issue by sank20** [commons-app/apps-android-commons#1914]
**Summary:** 

While uploading a single image/contribution, the user needs to input the Title and Description. The first description item in the list has the info icon to the right-end and it shows a dialog with the info on touch of the icon. But, it is showing the dialog on touches outside the icon too. 

**Steps to reproduce:** 

- Add a new contribution by selecting Take Photo/From Gallery actionbar-items
- In the next screen, you need to add title and details. 
- Tap on the portion outside the hint "Description" in the EditText. 

 
What did you expect the app to do, and what did you see instead?

**Device and Android version:** 

Moto G4 Plus, Android 7.0, Stock ROM.
 
 **Commons app version:** 

2.8.3- debug master. 

**Screen-shots:** 

![screenshot_20181004-202946](https://user-images.githubusercontent.com/7912239/46484146-caad7080-c816-11e8-9cef-b1d2ab58bed4.png)
![screenshot_20181004-203001](https://user-images.githubusercontent.com/7912239/46484149-cb460700-c816-11e8-8079-afc7da3a31d4.png)

**Would you like to work on the issue?**

I'm taking up this issue to solve it.

**Comment by domdomegg** [comment]
Was able to reproduce in `2.8.5-debug-master~178e5351` on `Samsung Galaxy S6` with API level `25`

Reviewing PR now
