### ISSUE TITLE
Code quality changes

### ISSUE THREAD

**Issue by egsavage** [commons-app/apps-android-commons#1926]
**Summary:** 

I'm making a general issue to address ongoing code quality issues.  Everyone please add your PRs to this issue so we can have a consolidated view of everyone's efforts.

**Would you like to work on the issue?**

I will be putting a couple of PRs forth initially to this effort and I'm hoping others will add to this effort.

**Comment by misaochan** [comment]
Thanks for this issue. :) I've merged one of your PRs, the others require testing so will take a bit longer.
