### ISSUE TITLE
About Us

### ISSUE THREAD

**Issue by ewuoso** [commons-app/apps-android-commons#1936]
If you would need someone to create and about us section for your project.  I can help you with that.

**Comment by nicolas-raoul** [comment]
We already have that, actually :-)

**Comment by ewuoso** [comment]
What about frequently asked questions.  I can write that also

**Comment by domdomegg** [comment]
Maybe check out improving the documentation on the [wiki](https://github.com/commons-app/apps-android-commons/wiki)
