### ISSUE TITLE
Inconsistent "Send Logs" message

### ISSUE THREAD

**Issue by amire80** [commons-app/apps-android-commons#1946]
**Summary:** 

The translatable string "log_collection_started" mentions a "Send Logs" button. I couldn't find such a strings elsewhere. The closest string is probably send_log_file, which says "Send log file" in English. The translatable strings must be consistent.
 
 **Commons app version:** 

This is correct for Git revision 2af57fc59421047c58a5bb9df007c170a570821d .

**Would you like to work on the issue?**

It's a trivial issue, so I can submit a patch as soon as somebody who takes responsibility for the design and the UI strings phrasing tells me what the strings should be :)

**Comment by misaochan** [comment]
"Send log file" is probably more technically correct (the users are sending a file via email), although we do colloquially use "send logs" to talk about it, which probably explains why the mix up happened. Thanks @amire80 . :)
