### ISSUE TITLE
Search feature is light in dark theme

### ISSUE THREAD

**Issue by Divyanshu2132** [commons-app/apps-android-commons#1948]
**Summary:** 

In explore section when we click on serch it is light even in dark mode

**Steps to reproduce:** 

- Go to settings

- Turn on Dark Theme

- Then in Explore click on search icon 
It is still light though it should be dark

**Device and Android version:** 

Asus Zenfone Max Pro M1 Android 8.1.0

 **Commons app version:** 

master and betaDebug/prodDebug

**Screen-shots:** 

![issue](https://user-images.githubusercontent.com/28994322/47444915-3a3ecc00-d7d5-11e8-949e-5f1c2476ae69.jpg)

**Would you like to work on the issue?**

Yes I would like to work on this issue

**Comment by domdomegg** [comment]
Related PR: #1951
