### ISSUE TITLE
What name for the app?

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#196]
We have had a few names for this app:
- Upload To Commons
- Wikimedia Commons
- Commons

What are our branding goals? Get downloaded by anyone, get spotted by experts, look good?
What name is the best?

Right now we are "Wikimedia Commons", as seen in the "More by Wikimedia Foundation" section of the page of Wikipedia on Google Play:

![screenshot_20160719-215424](https://cloud.githubusercontent.com/assets/99590/16950632/3f212ca0-4dfc-11e6-9fe5-695904c1c6f9.png)

**Comment by misaochan** [comment]
I vote for 'Wikimedia Commons'. :)

**Comment by whym** [comment]
For the name used in the Play Store (are the two separate?), "Wikimedia Commons" sounds good. "Commons" is harder to discover and ambiguous.

For the name under the launcher icon, though, "Wikimedia Commons" and "Upload to Commons" seem too long - the last few letters get omitted.

[![screenshot_20160721-221619](https://cloud.githubusercontent.com/assets/10674/17056089/0e3cb102-504c-11e6-8c84-f2c1bb8490c0.png)](https://commons.wikimedia.org/wiki/File:Commons-logo.svg)

**Comment by nicolas-raoul** [comment]
I agree that just "Commons" would be better for the launcher icon. In Japanese it is particularly bad:
![screenshot_20160803-153317](https://cloud.githubusercontent.com/assets/99590/17356174/d50ecfc0-5990-11e6-80a0-e780664bfd82.png)
Even in Japanese the alphabet name "Commons" would be the best I think.

**Comment by misaochan** [comment]
The launcher title is already 'Commons', AFAIK?

**Comment by nicolas-raoul** [comment]
The screenshot above shows the latest Git (1.23)

**Comment by nicolas-raoul** [comment]
Probably because of https://github.com/nicolas-raoul/apps-android-commons/blob/master/res/values-ja/strings.xml#L3
Should I fix it there?

**Comment by misaochan** [comment]
How odd, mine says 'Commons' and @string/app_name for the launcher icon also appears to be 'Commons'. Could be a translations issue?

Please do. :)

**Comment by misaochan** [comment]
May I close this? :)

**Comment by nicolas-raoul** [comment]
So, "Commons" in the manifest, and "Wikimedia Commons" on Play Store and F-Droid, right?

**Comment by misaochan** [comment]
That would be my preference, yep.
