### ISSUE TITLE
Idea on "explore" 

### ISSUE THREAD

**Issue by tykees** [commons-app/apps-android-commons#1963]
Hello, I have an idea to propose on the explore section in the application.
AFAIK, Random images comes up when the explore is accessed and there is a search function on the page to search "media and categories". Which images related to the search comes up. 
My idea is the implementation of a " favorite " function that will allow users to favorite images. All favorite images will be on a page and the original owner of the image we get a notification every time his/her images get favorite.

One of the benefit is that it will improve quality of images and user that shows quality in their photography work will know there work are indeed valued. 
I can add a pictorial illustrations of my suggestion if needed. ;))

**Comment by nicolas-raoul** [comment]
Related: #1756

**Comment by tykees** [comment]
Yeah, related but the overall idea is kinda different as the end result is not similar to the issue. Hoping to use the feature soon.;))

**Comment by misaochan** [comment]
I like the idea of notifying the owner of the image whenever their images get a favourite. :) However, that would require some form of server-side storage and handling for "favourites" I believe, as local storage would be insufficient for that. Currently we use local storage just to store favourites, but we can't process notifications or keep track of them with just local storage. (Anyone, please feel free to correct me if I'm wrong)

**Comment by tykees** [comment]
Wow! So, you guys going to have this feature implemented? I tend to like it so much.
Or it gonna be a future implementation?

**Comment by misaochan** [comment]
We can definitely keep this enhancement in mind. :) However, it may take a while before we get to it, unless a volunteer offers to do it sooner. Enhancements involving server-side storage/handling can be quite involved and take a lot of time.

**Comment by neslihanturan** [comment]
Closing this one, lets continue under #2016
