### ISSUE TITLE
Crash when rotating the app on Nearby mode

### ISSUE THREAD

**Issue by Pablohn26** [commons-app/apps-android-commons#1966]
**Summary:** 

Summarize your issue in one sentence (what goes wrong, what did you expect to happen)

Crash when rotating the app on Nearby mode

**Steps to reproduce:** 

I attach a video showing how to reproduce the error

![bug_result](https://user-images.githubusercontent.com/1228418/47806391-f51d1b80-dd39-11e8-8c21-5b51870b5ec7.gif)

How can we reproduce the issue? Go to Nearby mode and rotate several times opening the list of points.

What did you expect the app to do, and what did you see instead? No crash

**Add System logs:**

Sent by email using the app

**Device and Android version:** 

Xiaomi Mi MIX 2S
Android 9 PKQ1.180729.001
Stock ROM
 
 **Commons app version:** 

2.8.6

**Screen-shots:** 

![bug_result](https://user-images.githubusercontent.com/1228418/47806391-f51d1b80-dd39-11e8-8c21-5b51870b5ec7.gif)

**Would you like to work on the issue?**

I can provide testing support but I cannot fix the bug programming.

**Comment by VojtechDostal** [comment]
I can currently easily rotate the app in Nearby mode without any crashes. The Nearby map reloads normally each time I do that. I am on 2.8.6. , Huawei P10 Lite, Android 8.0

**Comment by neslihanturan** [comment]
Solved:)
