### ISSUE TITLE
Show more/less in notification row annoyances

### ISSUE THREAD

**Issue by domdomegg** [commons-app/apps-android-commons#1981]
**Summary** 

All the times it's turned up for me it's not been helpful - with the 'show more' taking up more space than if it wasn't there. Maybe need to be less aggressive with it? [item_notification.xml](https://github.com/domdomegg/apps-android-commons/blob/2884bd934ab7320ba0918fda937a6a817191e618/app/src/main/res/layout/item_notification.xml#L49)

As the target is small and the middle text link surrounds it, it's annoying to accidentally open the browser.

**Screen-shots** 

Example where it's not that useful

|  Hidden | Shown   |
|---|---|
|  ![screenshot_20181104-143014](https://user-images.githubusercontent.com/4953590/47965377-6876a400-e03e-11e8-9cb1-1a35fac9f986.png) |  ![screenshot_20181104-143018](https://user-images.githubusercontent.com/4953590/47965378-69a7d100-e03e-11e8-81fb-59b21b6a19b0.png) |

**Possible solution**

A solution that might solve all of this issue and #1980 is doing away with the "show more", and having the entire notification row be a link. Having a longer trimLength (I'm thinking like 280 chars) with an ellipsis if it's somehow over that should be okay. The user can view the commons website for the entire notification text if it's really long, if they're clicking through to the website anyways.

**Comment by HectorRoblesWolf** [comment]
Can I work on this issue?

**Comment by domdomegg** [comment]
@HectorRoblesWolf Please do :)

**Comment by HectorRoblesWolf** [comment]
It seems like the entire row it's a link right now. Please correct me if I'm wrong

**Comment by domdomegg** [comment]
@HectorRoblesWolf The entire row is a link apart from the "show more/less", however the middle bit doesn't affect the animation e.g. the slight darkening on tap (see #1980)

**Comment by HectorRoblesWolf** [comment]
Thanks @domdomegg got it, I'll work on that

**Comment by HectorRoblesWolf** [comment]
Done, here is the PR https://github.com/commons-app/apps-android-commons/pull/1998
