### ISSUE TITLE
Upload count does not get updated right away post successful upload

### ISSUE THREAD

**Issue by konohakesh** [commons-app/apps-android-commons#1984]
**Summary:** 

After a successful upload, when 'My Recent Uploads' activity is shown, then upload count in the header is not incremented. It still shows the old count. But when you close and re-open the application, it shows the correct count.

**Steps to reproduce:** 

1. Note the current upload count and then upload an image.
2. When you come back to 'My Recent Uploads' ,

Actual: You will see the upload count unchanged.
Expected: It should have incremented by one.

**System logs:**
NA

**Device and Android version:** 
Nexus 5X -  Android 7.1.1

**Commons app version:** 
2.8.5-debug-master
2.8.5 from Playstore

**Screen-shots:** 
![snap](https://user-images.githubusercontent.com/34960596/48058365-40bd4280-e1dc-11e8-9571-b1c4e6bef767.png)

**Would you like to work on the issue?**
Yes, if it is not a duplicate issue and no one is already working on it.

**Comment by misaochan** [comment]
Thanks for the report! You are very welcome to work on it, but I would wait until v2.9 is out, because there will be significant changes to both the upload process and main activity. You can keep an eye on 2.9-release branch. :)

**Comment by konohakesh** [comment]
Alright @misaochan . Now that you are talking about 2.9 -release, can you please briefly tell me and other newbies that how do we go about releasing the commons apps? I am not aware of the release cycles and even though I read in one of the comments under an issue that v2.8.6 is out, I don't see it in Play Store. Can you explain this a bit how releases are done here?

**Comment by misaochan** [comment]
Sure. :) You can see the procedure at https://github.com/commons-app/apps-android-commons/wiki/Project-maintenance . And to know our latest release, you can look at https://github.com/commons-app/apps-android-commons/releases .

v2.8.6 is a bit of a one-time anomaly, as it will remain in Google Play beta until v2.9 is out. You can still access it by signing up for beta testing.

**Comment by konohakesh** [comment]
@misaochan Thanks for sharing the insights.

**Comment by neslihanturan** [comment]
Referencing #2509 here, they are slightly different but solutions may be related.

**Comment by kamrutha** [comment]
@misaochan the issue doesn't exist

**Comment by nicolas-raoul** [comment]
@kamrutha Could you please post a screenshot showing the app's home activity just before and just after an upload? Thanks a lot :-)

**Comment by kamrutha** [comment]
@nicolas-raoul
This is the image before uploading:  
![WhatsApp Image 2019-12-03 at 12 37 05 PM (2)](https://user-images.githubusercontent.com/34261526/70028162-e8689800-15c9-11ea-9978-081cda572c19.jpeg)

While i am uploading the current image, it is showing the previous image till it completely upload the current image
![WhatsApp Image 2019-12-03 at 12 37 05 PM (1)](https://user-images.githubusercontent.com/34261526/70028169-ed2d4c00-15c9-11ea-80d8-adf3185a2b3a.jpeg)
This is the image after uploading
![WhatsApp Image 2019-12-03 at 12 37 05 PM](https://user-images.githubusercontent.com/34261526/70028174-f0283c80-15c9-11ea-97e2-e0cfe4deeb46.jpeg)

**Comment by kamrutha** [comment]
@nicolas-raoul 
**View before uploading the image:**
![WhatsApp Image 2019-12-03 at 12 37 05 PM](https://user-images.githubusercontent.com/34261526/70028286-44cbb780-15ca-11ea-81e3-0ddf67917446.jpeg)

**Image after uploading**
![WhatsApp Image 2019-12-03 at 12 37 05 PM (2)](https://user-images.githubusercontent.com/34261526/70028328-6167ef80-15ca-11ea-811d-e8394cbe991b.jpeg)

**While uploading the current HSV image, the page is showing the previous image only, until the current image is uploaded completely**
![Uploading WhatsApp Image 2019-12-03 at 12.37.05 PM (1).jpeg…]()

**Comment by kamrutha** [comment]
** But, While uploading the current HSV image, the page is showing the previous image only, until the current image is uploaded completely**
![WhatsApp Image 2019-12-03 at 12 37 05 PM (1)](https://user-images.githubusercontent.com/34261526/70028474-c7547700-15ca-11ea-925f-ac6ecef5408a.jpeg)

**Comment by kamrutha** [comment]
@nicolas-raoul

**Comment by kamrutha** [comment]
@nicolas-raoul  This issue still exists.. the count is incremented only on application re-open.

**Comment by nicolas-raoul** [comment]
@kamrutha 
Can you see the number 1223 in my home activity below?
![Screenshot_20191203-171958_Commons](https://user-images.githubusercontent.com/99590/70032624-275e1400-15f1-11ea-8172-b9e06a745453.jpg)
If I upload 1 more picture now, the number should become 1224.
I guess you will see the number appear if you kill the app and restart it.

**Comment by nicolas-raoul** [comment]
Ah, it seems that you have found the problem, great :-)

Now, please:
1. run the app in debug mode
2. find where the number is cached after it is retrieved the first time
3. write a cache invalidation method which sets the cache variable to null, for instance
4. find the Java source code which runs when an upload finishes
5. At that place, call the method created at step 3

Good luck :-)

**Comment by kamrutha** [comment]
@nicolas-raoul  
I can see the number but as the count didn't increase after uploading an image
![WhatsApp Image 2019-12-03 at 1 55 39 PM](https://user-images.githubusercontent.com/34261526/70033046-b14bb400-15d4-11ea-9fde-ece6a47e6413.jpeg)
 
It incremented only after I CLOSE the app

**Comment by kamrutha** [comment]
@nicolas-raoul  Yes, I will work on it. Thanks ! :-)

**Comment by nicolas-raoul** [comment]
If you are new to caches, this can be interesting to read:

https://en.wikipedia.org/wiki/Cache_invalidation

The best method for your case here is [Purge](https://en.wikipedia.org/wiki/Cache_invalidation#Purge), because it is the one that makes the lowest number of web requests in the long run.

**Comment by kamrutha** [comment]
@nicolas-raoul  While I am trying to solve the above issue, I am not able to upload pictures, it is showing the following message.
![WhatsApp Image 2019-12-04 at 7 38 55 AM](https://user-images.githubusercontent.com/34261526/70156794-544e0d80-1669-11ea-9c64-500927402150.jpeg)

**Comment by maskaravivek** [comment]
@kamrutha The crash that you are facing was recently fixed by #3248. Can you check if you have the latest version of the master branch.

**Comment by kamrutha** [comment]
@maskaravivek  Okay, Thanks!!!

**Comment by kamrutha** [comment]
@nicolas-raoul  I am facing problem in using cache invalidation. Could you please help me out in how to solve the issue?

**Comment by nicolas-raoul** [comment]
First, try to disable the cache code, so that the number is calculated everytime.

**Comment by neslihanturan** [comment]
We get a recent feedback about upload count is not updated at all.

**Comment by Prince-kushwaha** [comment]
i want to work on this issue
