### ISSUE TITLE
Start Nearby map zoomed in

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#1987]
I had a conversation with User:Jim Henderson at https://commons.wikimedia.org/wiki/Commons_talk:Mobile_app#Wish_list , and a concern of his (that I agree with) is that the map frequently auto-zooms out to display an unusable dense cluster of pins, which requires the user to keep zooming back in.

I think that whenever the user starts Nearby, the map should be zoomed in to a reasonable distance (perhaps with the screen width corresponding to 1km)? The reason is that nobody can use the map while it is zoomed out the way it currently is. In order to use it, everyone will have to zoom in - so we should do that work for them.

The Nearby items (pins) however, should be loaded and populate the map to a larger radius (the way it currently works). It is just the initial display to the user that should change.

(Currently we also zoom out whenever the user taps the Nearby list button. That should be fixed too. ;))

This will need to work alongside #591 , but there should hopefully be minimal conflict.

**Comment by domdomegg** [comment]
Possibly also rather than just have a fixed scale factor it could depend on pin density i.e.. start more zoomed in if lots of pins on screen - although this could be over-complicating it.

**Comment by ashishkumar468** [comment]
@misaochan   Just to make sure all of us are on the same page. The following changes needs to be done
* Nearby is by default zoomed out to a level making a lot of pins cluster together and we need to make sure that when nearby is loaded initially, it should be zoomed in to a possible radius of 1 km.
