### ISSUE TITLE
Removing failed uploads from ContributionsList

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#199]
From andrea as:

> Hi, usually I, from commons app, tap gallery and search in Google photos and dont crash immidiatly but when is uploading.
> Often The uploading dont finish and i have a lot of upload not finish in the top of my list "non riuscito" how can i erase it?

Do we have a way for the user to remove the failed uploads from their Contributions list? If not, should we?

**Comment by nicolas-raoul** [comment]
I have never seen such a feature.
I don't think it is very high priority though?
Especially if the first page is eventually replaced with a map of requested pictures around.

**Comment by tobias47n9e** [comment]
I just ran into this problem while I had a bad internet connection. It would be good if the app would have a button to retry the upload.

**Comment by neslihanturan** [comment]
I think this issue is quite annonying, my proposed solution is:
- If an upload failed
    - Check if we can still access to file to be uploaded. If we can, then display retry and cancel buttons
    - Do same operation on each time contributions list is loaded.

I think this issue is high priority from now on.

**Comment by misaochan** [comment]
> Check if we can still access to file to be uploaded. If we can, then display retry and cancel buttons

Sounds good. AFAIK retry does not usually work currently though, that would need to be fixed simultaneously.

> Do same operation on each time contributions list is loaded.

How resource-intensive would this be?

**Comment by neslihanturan** [comment]
> Sounds good. AFAIK retry does not usually work currently though, that would need to be fixed simultaneously.
Yes this also needs to be fixed, but for some cases, retry is not event possible. So we need to cancel it automaticcally with a toast message.

> How resource-intensive would this be?
I think we can listen when a new item is added to our db.

**Comment by neslihanturan** [comment]
This seems to be related with #118 , so closing the old issue. 
Currently we have retry and delete buttons for failed uploads, they work well in general but they are still not very consistent.

**Comment by Rishavgupta12345** [comment]
@nicolas-raoul  This issue is pretty old and now we can easily remove the failed uploads , HENCE this issue is already solved

**Comment by nicolas-raoul** [comment]
@Rishavgupta12345 You are right, there is now a button to remove failed uploads.
