### ISSUE TITLE
Allow dynamic loading of contributions, without number limit

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#1993]
There was a request on our mailing list:

> Hello 
> It would be great if we can show images up to 1000 or more. 
> Thank you
> Tris T7
> 

While there are bandwidth and memory concerns with downloading large numbers of images, I personally think if the user decides they want to, we should allow it (however the default should remain the same as currently). Currently the max you can set in Settings is 500. Would this be a good idea?

**Comment by nicolas-raoul** [comment]
I think the ideal solution would be to implement My Uploads like it is done in Explore:

1. Load N images
2. When the scrolling user comes close to the end of these N, load N more. Etc.

**Comment by misaochan** [comment]
Agreed. Will change the title accordingly.

**Comment by maskaravivek** [comment]
I would like to pick this up.

**Comment by nicolas-raoul** [comment]
@maskaravivek Don't hesitate to use the "Assignees" button to assign issues to yourself :-)

**Comment by maskaravivek** [comment]
The code in contributions fragment and contribution list fragment is quite old and things have been patched on top of it. One of the focus areas of the next grant is to overhaul legacy code(#1092) and introduce a consistent code pattern across the app.

So, before starting working on this talk it would be great if we could finalize the architecture for the presentation layer. Let's continue the discussion for the architecture in #888.

**Comment by maskaravivek** [comment]
@ashishkumar468 Recently you refactored the contributions list. Can you confirm if this has already been taken care of?

**Comment by ashishkumar468** [comment]
@maskaravivek my refactors did not change the way things were already there. AFAIK I know such things would need pagination at the end of the recycler view which is not there as of now
