### ISSUE TITLE
Mem leaks on 2.9-release

### ISSUE THREAD

**Issue by neslihanturan** [commons-app/apps-android-commons#1996]
**Summary:** 
There are some mem leaks on 2.9-release. I solved some of them but couldn't find the reason for these.
**Steps to reproduce:** 
- Go nearby tab
- Click one of nearby markers
- Click to bottom sheet and expand it
- Go contrib tab
- Click notification icon, change activity to notifications activity
- Click back button, and come back to main activity. You should see the leak.

**Device and Android version:** 
API 26, Nexus 6
 
**Commons app version:** 
2.9-release

**Screen-shots:** 

![image](https://user-images.githubusercontent.com/3127881/48350331-e0c11300-e697-11e8-8338-649f560ebe7c.png)

![image](https://user-images.githubusercontent.com/3127881/48350364-fa625a80-e697-11e8-9ef3-f83ddb69c5cd.png)

**Would you like to work on the issue?**
I already did, but some help may work.

**Comment by sp2710** [comment]
@neslihanturan I had done some work in #2373.
Maybe this will fix some memory leak issue

**Comment by domdomegg** [comment]
Think these are now fixed (also see discussion in #2373)
