### ISSUE TITLE
New main UI - progress bar in Nearby card view sometimes runs forever.

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#2001]
**Summary:** 

Main UI - If we are unable to access the list of Nearby places for whatever reason, the progress bar in the Nearby card view on the main screen keeps going and going. This actually happens fairly frequently for me.

I think there are a few components of this issue:
1. Loading of the nearest place should not carry on indefinitely. If location is unavailable for whatever reason (or, to make it simpler, after a set period of time perhaps), it should say "Unable to load nearest place that needs pictures", with the subtext underneath: "Tap to retry, or swipe to dismiss".
2. It still puzzles me why Nearby is sometimes unable to get a location - when I try using a different map app after Nearby fails, it tracks my location just fine. I don't think this is a recent problem - it has happened before, it is just more obvious when it is on the main screen. We may need to revisit the way we handle locations in the future.

IMO we should at least handle Component 1 before releasing the new main UI. @neslihanturan what do you think?

**Device and Android version:** 

Samsung Galaxy s7 API 26, and also Nexus S emulator API 27
 
**Commons app version:** 

2.9-release branch

**Screen-shots:** 

![screenshot_1542188323](https://user-images.githubusercontent.com/3611199/48474438-4b17b600-e846-11e8-81aa-9c9ab52a8b38.png)

**Would you like to work on the issue?**

Pref not

**Comment by neslihanturan** [comment]
I think best solution before release is setting a timer and putting tab to retry button. I am on it.
