### ISSUE TITLE
Result of the quiz activity could be improved for smaller screens

### ISSUE THREAD

**Issue by sivaraam** [commons-app/apps-android-commons#2010]
**Summary:** 
When the user is shown the result of the quiz activity at the end of taking the quiz, Some parts of the sentence are hidden by the button.

*A side note*: The 2nd picture never showed up in the quiz as a consequence of which I had to quit it in the middle. The progress bar for the second picture went close to the end but the picture never showed up. The mobile network was a little wavery but it wasn't that bad at that time.

**Steps to reproduce:** 
1. Go to the quiz activity (One way: have more than 50% of the uploaded images deleted in your account. Then log-in to the app. I got a pop-up to take the quiz)
2. Complete the quiz to get the results

Expected: The sentence in the Results activity is readable.
Actual: Some part of the sentences are hidden behind the 'Continue' button making it unreadable.

**Device and Android version:** 
Samsung Galaxy J1 Ace, Android 5.1.1 (stock)

**Commons app version:** 
2.8.6

**Screen-shots:** 
![screenshot_2018-10-21-14-14-19](https://user-images.githubusercontent.com/12448084/48665140-7bbe5080-eacf-11e8-9d8d-1f3ac5a7885c.png)

**Would you like to work on the issue?**
No for now. Maybe when I get some free time, I can.

**Comment by sp2710** [comment]
I would like to work on this
