### ISSUE TITLE
Nearby: confusing message about location permission

### ISSUE THREAD

**Issue by sivaraam** [commons-app/apps-android-commons#2011]
**Summary:** 
I use an Android 5.1.1 device. Runtime permissions were introduced only in Android 6. When I use the Nearby feature with Location (not the Location permission for the app, the location (GPS) of the phone) turned off, I get an error stating "GPS is disabled" error which is fine. If I give "Cancel" instead of "Enable GPS", I'm shown a error message stating "Nearby places" can't be displayed without location permission. This seem irrelevant as there's no such things as location permission for the app in my device. It's better to improve the wordings a little in this case.

**Possible solution**
When the user taps on "Cancel" instead of "Enable GPS" for the "Enable GPS" pop-up, showing a full screen error page stating GPS needs to be enabled to use this feature might be helpful. It might also contain a "Refresh" icon or something. Asking to enable GPS permission when the user has denied it doesn't seem to be a nice User experience. If he has did it by mistake the "Refresh" icon should help him.

Just wondering, why don't we also allow users to use Nearby to find places needing pictures by manually specifying a location in Maps? This makes the feature usable even without GPS.

**Steps to reproduce:** 
1. Ensure you're using the app on a device with Android version < 6. Also, ensure GPS is turned off.
2. Open the app
3. Go to Nearby
4. Tap cancel for the "Enable GPS" pop-up

Expected: Either Nearby is usable without enabling GPS (OR) a full-screen error is shown stating requirement of GPS (with Refresh button)
Actual: A weird "Nearby permission" pop-up shows up.

**Device and Android version:** 
Samsung Galaxy J1 Ace, Android 5.1.1 (stock)

**Commons app version:** 
2.8.6

**Screen-shots:** 
Just for reference:
![screenshot_2018-06-21-15-30-03](https://user-images.githubusercontent.com/12448084/48665432-33edf800-ead4-11e8-92c3-eaab97eca76a.png)
![screenshot_2018-06-21-15-30-07](https://user-images.githubusercontent.com/12448084/48665435-3c463300-ead4-11e8-9928-032a925880b2.png)

**Would you like to work on the issue?**
No.

**Comment by misaochan** [comment]
Ah, thanks for spotting this! Indeed the error message needs to be improved. Currently it seems the same dialog is displayed when GPS is off AND when permissions aren't given, which should not be the case.

> Just wondering, why don't we also allow users to use Nearby to find places needing pictures by manually specifying a location in Maps? This makes the feature usable even without GPS.

This is planned for the near future, see #591 . :)

**Comment by sivaraam** [comment]
I don't get the pop-up with the confusing message anymore but one things surprises me. Tapping on the "Locate me" icon doesn't ask me to enable location (GPS) when it's disabled. It simply does nothing when I've disabled it. This is misleading. I'll open a separated issue for that. I'm closing this as its not relevant anymore.
