### ISSUE TITLE
Add option in Explore for users to easily browse images uploaded via our app

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#2017]
Users can technically already do this, but it is a bit convoluted: Directly from within the app: Tap "Explore", search for "Uploaded with Mobile/Android", tap "Categories", tap "Uploaded with Mobile/Android".

I was wondering if we should make it easier for users to browse the ones uploaded from our app (which could potentially tie into the "patrolling other images uploaded via the app" feature, finally allowing us to include that into master with a polished UI). Maybe we could have 2 tabs in the main Explore view - 1 for "Featured" (the current implementation) and 1 for "Uploaded via app"? @nicolas-raoul

**Comment by neslihanturan** [comment]
Great idea!

**Comment by nicolas-raoul** [comment]
Yes good idea!
Adding tabs would make the already tiny search button even less visible, and make the Explore activity less beautiful (our public is photographers or photography enthusiasts, they like beautiful things). Scrolling through images is one of the places where we want to be as close as possible to full-screen.
That being said, I am not sure where we could put a way to access that. Maybe a "Mobile uploads" or "Peer uploads" item below Explore in the left menu?
After writing this I concede tabs are the most understandable implementation, though, so feel free to go for tabs.

**Comment by brendajerop** [comment]
Is anyone working on this? If not, I'd like to work on it :)

**Comment by brendajerop** [comment]
@misaochan @nicolas-raoul I'd like to work on this:)

**Comment by nicolas-raoul** [comment]
@brendajerop It is yours, please let us know about your progress :-)

**Comment by brendajerop** [comment]
![screenshot_2019-03-06-11-19-34](https://user-images.githubusercontent.com/20903830/53867477-fec6d080-4004-11e9-88fa-25428a0a297e.png)
![screenshot_2019-03-06-11-19-20](https://user-images.githubusercontent.com/20903830/53867481-fec6d080-4004-11e9-9ed7-7e9c240705fb.png)
@nicolas-raoul This is what I have so far. Is this the intended output?

**Comment by nicolas-raoul** [comment]
Yes wonderful :-)

**Comment by brendajerop** [comment]
@nicolas-raoul For this specific issue I created a new activity similar to CategoryImagesActivity but with tabs, since CategoryImagesActivity is used to display images of any category, so I didn't want to clutter it with tabs. 
Is this okay or should I have added the tabs to CategoryImagesActivity?

**Comment by nicolas-raoul** [comment]
Sounds reasonable to me, feel free to send a pull request :-)
