### ISSUE TITLE
'i' icon in 2.9-release branch has too wide a range

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#2019]
**Summary:** 

On the 2.9-release branch with the new upload UI, I wanted to remove a word from the end of my description. However, there was no way I could select the end of the sentence because whenever I tapped in an area remotely near the 'i' icon, it would trigger the tooltip instead.

**Steps to reproduce:** 

Upload picture, tap near 'i' icon (but not directly on it).

**Device and Android version:** 

Samsung Galaxy s7 running API 26
 
**Commons app version:** 

2.9-release branch

**Would you like to work on the issue?**

@maskaravivek Do you think you could fix this before 2.9? Would just need to reduce the area of the tooltip.

**Comment by domdomegg** [comment]
Fixed in #2025
