### ISSUE TITLE
Fix missing lost build error

### ISSUE THREAD

**Issue by zhao-gang** [commons-app/apps-android-commons#2027]
**Summary:** 

Build failed by error message: Failed to find byte code for com/mapzen/android/lost/api/LostApiClient$ConnectionCallbacks

**Steps to reproduce:** 

Clone and build this project in Android Studio 3.2.1.
Build failed and error message is: Failed to find byte code for com/mapzen/android/lost/api/LostApiClient$ConnectionCallbacks

**Would you like to work on the issue?**

Yes. A pull request will be made to address this issue.

**Comment by neslihanturan** [comment]
Hi @zhao-gang , I also use Android Studio 3.2.1, but I don't experience this issue. Does anyone else experienced this issue?

**Comment by domdomegg** [comment]
Duplicate of #1941
