### ISSUE TITLE
When logging in after Skip Login, the usual main activity does not load

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#2030]
**Summary:** 

I logged in after choosing Skip Login in welcome activity. The login actually works (as seen from the logs), but I am not redirected to main activity. Even worse, the nav drawer has not changed. I must tap "Login" again before main activity appears.

**Steps to reproduce:** 

Skip login, tap "Login" in nav drawer

**Device and Android version:** 

Nexus S API 27
 
**Commons app version:** 

2.9-release prodRelease

**Would you like to work on the issue?**

Pref not

**Comment by ashishkumar468** [comment]
@misaochan I followed the exact steps, skip login->login, but I could not reproduce the issue

**Comment by misaochan** [comment]
Do you see the normal main activity after logging in via the nav drawer?

**Comment by maskaravivek** [comment]
I am also not able to reproduce this issue. 

Steps: 
- Skip login
- Click Login from Nav drawer
- Login
- Main activity opens and nav drawer is updated

**Comment by misaochan** [comment]
Hmm. If it doesn't happen for anyone else, we can close this. It is unlikely other users will encounter it, we can reopen if they do. :)
