### ISSUE TITLE
Add "use previous title/desc" option to new upload screen (2.9)

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#2035]
The new upload process (2.9) is missing the "use previous title/desc" option. We would also need to discuss where in the UI it would fit best, and what sort of UI element to use.

**Comment by pgmpofu** [comment]
@misaochan May I work on this?

**Comment by nicolas-raoul** [comment]
@pgmpofu I suggest you start this after you implement the map scale :-)

**Comment by nicolas-raoul** [comment]
Ideally the button would only be visible before the user either taps it or starts typing some original text.

About the wording: It would be great if we could convey the meaning of "*reuse the text you entered and modify it to fit this particular picture*" rather than just "*reuse the text as an exact duplicate*".

**Comment by nfatma** [comment]
Hi!
I am an Outreachy applicant and interested in this project.
Can I start with this issue as my contribution?

**Comment by nicolas-raoul** [comment]
@nfatma It is yours! Please let us know about your progress at least every two days, thanks :-)

**Comment by nfatma** [comment]
sure :)
I have imported the project in my Android studio and trying to understand the code of UploadActivity to add the enhancement.

**Comment by nfatma** [comment]
I am able to add the "_use the title/desc from your previous upload & edit_" button in the UI but I am not able to get the prev title/desc from the database. Can I get any help??

**Comment by KaveriKR** [comment]
Is it still open? , I would like to work on it.

**Comment by maskaravivek** [comment]
@nfatma Is already working on this issue.
