### ISSUE TITLE
Send crash reports to a developers-only mailing list (until an open anonymized solution is found)

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#204]
Crash reports contain people's email addresses.
They should be sent to a separated Google Group to which only developers have access (for instance, people who have committed at least once).
(until we get an ACRA server #203)

**Comment by misaochan** [comment]
How do we go about this? Should I create one and invite you all?

**Comment by nicolas-raoul** [comment]
Yes that would be great :-)

**Comment by misaochan** [comment]
Done, invites sent to @nicolas-raoul  and @whym (if anyone else wants invites, please ask and provide email address). Let me know if the group settings are appropriate, this is the first time I'm creating one. :)

**Comment by misaochan** [comment]
Does the mailing list work for you @nicolas-raoul ? If all is well I'll release the next version soon with the crash reports being sent there

**Comment by nicolas-raoul** [comment]
Yes I received the test message :-)

**Comment by misaochan** [comment]
@domdomegg , would you like access?

**Comment by misaochan** [comment]
@veyndan , @maskaravivek and @domdomegg , would you guys like to have access to our crash reports? We are currently receiving them in a private group to prevent spambots from harvesting user email addresses, but we are more than happy to share access with anyone who is interested in viewing or working on the crash reports. :) Let me know if you're interested and I will invite you. 

I will need your email address for the invite, feel free to either email me with it (josephinelim86@gmail.com) or post it here if you wish.

**Comment by veyndan** [comment]
Awesome, I'd love that. My email address is [veyndan@gmail.com](veyndan@gmail.com)

**Comment by misaochan** [comment]
@veyndan Sent, let me know if you haven't received it.

**Comment by veyndan** [comment]
Thanks, just accepted the invitation

**Comment by domdomegg** [comment]
That would be great - my email is jones_adam@rocketmail.com

**Comment by misaochan** [comment]
@domdomegg sent.

**Comment by maskaravivek** [comment]
Yep that would be great. Can you add maskaravivek@gmail.com

**Comment by misaochan** [comment]
Added you @maskaravivek
