### ISSUE TITLE
Multiple dialog are generating on Nearby page when user has explicitly denied location permission to app through system. 

### ISSUE THREAD

**Issue by Archiit19** [commons-app/apps-android-commons#2049]
**Summary:** 
Multiple dialog are generating on Nearby page when user has explicitly denied location permission to app through system. 
Expected : If nearby page could not be opened without location permission, we can show one time dialog and show home screen.

**Steps to reproduce:** 
1. Open Nearby Places and allow location permission.
2. Go to system and revoke app's location permission.
3. Now whenever you open Nearby Places, dialog keeps on generating for long time.

App should show one time dialog and show last accessed page.

**System logs:**

NA

**Device and Android version:** 

Samsung Galaxy S6 Edge.
Android Version 7.0 Nougat.

 
**Commons app version:** 
App Version - 2.8.5

**Screen-shots:** 
![screenshot_20181129-223454](https://user-images.githubusercontent.com/15213376/49239354-9629ef80-f428-11e8-9605-81711396b850.png)

**Would you like to work on the issue?**

Sure

**Comment by misaochan** [comment]
@Archiit19 , thanks for reporting this. Please feel free to take up this issue if you'd like!

**Comment by namrata-jha** [comment]
Since there has been no update on this yet, can I take this up?

**Comment by maskaravivek** [comment]
@namrata-jha I have assigned #2026 to you. Let us know when you are done with it. You can pick other issues after that. :)

**Comment by neslihanturan** [comment]
This issue is solved.
