### ISSUE TITLE
2.9.0: the 'i' icon in nearby doesn't do anything

### ISSUE THREAD

**Issue by sivaraam** [commons-app/apps-android-commons#2055]
**Summary:** 
In 2.9.0, I see that the nearby screen has been brought alongside the Contributions activity as a side bar. I also noted there's an `i` symbol near the title 'Nearby' which I guess would give some information about 'Nearby'. But tapping on it does nothing. It just freezes the app for some time and then nothing happens. See [linked screen cast](https://drive.google.com/open?id=1ilbBJDcH-FQPiHi5vKTAbiLLJlOjLlKA) for a demo.

**Steps to reproduce:** 
1. Open the app
1. Tap on the `i` icon found near the 'Nearby' screen's title

**Device and Android version:** 
Galaxy J1 Ace running Android 5.1.1 (stock)
 
**Commons app version:** 
2.9.0

**Would you like to work on the issue?**
No

**Comment by neslihanturan** [comment]
Well, it works for my tests:
![image](https://user-images.githubusercontent.com/3127881/49328054-c8e3fd00-f57a-11e8-8aa6-7a876812c9c9.png)

**Comment by maskaravivek** [comment]
@neslihanturan Can we use the normal alert dialog instead? All other places in the app uses an alert dialog to show (i) information.

**Comment by neslihanturan** [comment]
Sure @maskaravivek :)

**Comment by domdomegg** [comment]
Fixed in #2057
