### ISSUE TITLE
Show bookmarked nearby locations differently

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#2059]
I bookmark locations that I shot with my DLSR camera but have not uploaded yet.
If bookmarks were shown differently on the map, it would be very easy to see what locations I have not shot yet.
Everyone uses bookmarks differently, but I believe that everyone would benefit from seeing them differently, for instance as stars, or in a different color.
People who use bookmarks to select places where they plan to go will benefit as well.

**Comment by sp2710** [comment]
I am working on this
