### ISSUE TITLE
When I tap an item in the list of nearby locations, center the map on it

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#2060]

**Comment by sp2710** [comment]
I am working on this

**Comment by silkypriya** [comment]
@nicolas-raoul I would like to work on this issue, in case @sp2710 is not working on this now.

**Comment by nicolas-raoul** [comment]
@sp2710 Does the PR 2366 does what is described in this issue, especially in the complement of information above? Sorry for not being clearer from the beginning!

**Comment by sp2710** [comment]
@nicolas-raoul Yes it does what is described in this issue. It is ready to be reviewed

**Comment by nicolas-raoul** [comment]
@sp2710 Thank you! And sorry for the time it takes us to review all pull requests.

@silkypriya Could you please choose another issue? I suggest #2253 :-)

**Comment by silkypriya** [comment]
Yes sure! Thank you @nicolas-raoul
