### ISSUE TITLE
First time flow of nearby notification feature is not good

### ISSUE THREAD

**Issue by sivaraam** [commons-app/apps-android-commons#2063]
## Summary
There seems to be a new feature in v2.9.0. It's titled the "nearby notifications", I guess. It would be a nice feature to have but the way in which I had to discover it as a first time user was not nice. The first time user flow could be improved a lot.

Let me describe how it was for me.

1. First of all, when I open the app after upgrading to v2.9.0 a weird permission request pops-up which says,

    _Would you like us to use your current location to display the nearest place that needs pictures?_

    I'm not sure why I'm getting this pop-up. What would be the consequence if I grant/deny the permission? It also didn't tell me where it would show me the nearest places that need pictures.

    **Possible improvement**: It would be nice if the feature was introduced before asking for permissions related to it. he introduction could possibly done using an onboarding screen (like the one shown when a user opens the app for the first time. Seems it's time to dig back into #869)
1. When I deny the permission, it shows me a weird toast message stating:

    _Unable to display nearest place that needs pictures without location permissions_

    I denied the permission consciously. This message seems redundant and isn't so helpful.

    **Possible improvement**: In it's place, it would be better to show the user how to re-enable the permission (or) better let users know what it's about at least now.
1. I went to the 'Settings' screen, I saw two new settings which are probably related to this feature. The 'Display nearby notification' and 'Display location permission'. They seem odd too and the descriptions are quite vague.

    a. *Display nearby notification*: The description reads _Tap here to see the nearest place that needs pictures_. That doesn't seem quite informative. Tapping on it just just disables the option about which I have know idea.
    b. *Display location permission*: The description reads _Ask for location permission when needed for nearby notification card view feature_. This description is a little better. But is this even required?

    I guess controlling flow via the settings is not a good idea. It's better to just control the features.
    **Possible improvement**: It would nice to merge the two options into a single 'Nearby notifications' setting and give a meaningful description for it. Also, mention that the location would be used to show the places in the description. (I don't think the feature would work without it, would it?)

**Device and Android version:** 
Samsung Galaxy J1 Ace
 
**Commons app version:** 
2.9.0

**Screen-shots:** 
1. Initial permission request
    ![screenshot_2018-11-29-09-47-59](https://user-images.githubusercontent.com/12448084/49358601-3ddd4100-f6f9-11e8-9d43-a49cc91fd9f8.png)
1. The toast message after denying it
    ![screenshot_2018-11-29-09-48-15](https://user-images.githubusercontent.com/12448084/49358623-50577a80-f6f9-11e8-82a3-6621343265d4.png)
1. The settings related to the feature
    ![screenshot_2018-12-03-12-33-00](https://user-images.githubusercontent.com/12448084/49358642-5f3e2d00-f6f9-11e8-88a4-efc008582903.png)

**Would you like to work on the issue?**
No

**Comment by neslihanturan** [comment]
Hi @sivaraam , thanks for your feedback about workflow, I think we can have more of this kind of first time experience issues.

>    **Possible improvement**: It would be nice if the feature was introduced before asking for permissions related to it. he introduction could possibly done using an onboarding screen (like the one shown when a user opens the app for the first time. Seems it's time to dig back into #869)

Promoting new feature first is a good idea indeed.

> 1. When I deny the permission, it shows me a weird toast message stating:
>
>   _Unable to display nearest place that needs pictures without location permissions_
>
>    I denied the permission consciously. This message seems redundant and isn't so helpful.
>
>    **Possible improvement**: In it's place, it would be better to show the user how to re-enable the permission (or) better let users know what it's about at least now.

Maybe you denied permission consciously but for some user it is a reflex to deny location permissions. Thus, I think we can continue to display our current informative message and add they can reenable them from settings.

> Possible improvement: It would nice to merge the two options into a single 'Nearby notifications' setting and give a meaningful description for it. Also, mention that the location would be used to show the places in the description. (I don't think the feature would work without it, would it?)

The second setting is there, since we have a never ask for permission again checkbox, and if user clicked to that permission etc. But I do agree this workflow can be improved. Merging two into one seemed to me like a good idea.

**Comment by nicolas-raoul** [comment]
The first time flow is still maybe not optimal, but I guess this issue needs an update, or maybe recreate the issue to focus on current problems? Thanks! :-)

**Comment by sivaraam** [comment]
> The first time flow is still maybe not optimal, but I guess this issue needs an update, or maybe recreate the issue to focus on current problems? Thanks! :-)

You're right. A major part of this issue appears stale. I observed a new issue for which I've filed #4765.
