### ISSUE TITLE
Bookmarking a location sometimes does not work

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#2064]
**Summary:** 

Yesterday I was trying to bookmark a location, but tapping would not make the star full, actually it is like it had no effect, I tapped many times with no apparent reaction.

Unfortunately I have not been able to reproduce the problem.

 
**Commons app version:** 

2.9.0

**Comment by maskaravivek** [comment]
@nicolas-raoul Can you share your app logs?

**Comment by albendz** [comment]
For reference, this seems to be the piece of code related to this action: https://github.com/commons-app/apps-android-commons/blob/master/app/src/main/java/fr/free/nrw/commons/bookmarks/locations/BookmarkLocationsDao.java#L119

If the update failed, it should have thrown a runtime exception.

**Comment by maskaravivek** [comment]
DB update, in particular, should ideally never fail. If anything would have failed here, then it is possible that the `bookmarkLocation` is not constructed properly.

**Comment by nicolas-raoul** [comment]
Closing as I haven't experienced this in a while.
