### ISSUE TITLE
Increase timeout for achievements 

### ISSUE THREAD

**Issue by neslihanturan** [commons-app/apps-android-commons#2066]
**Summary:** 

As I noted under this PR #2056, for our user Ainali, who reported this issue, 30 seconds wasn't enough on first trial. So we may need to increase it to maybe 40?

**Steps to reproduce:** 
`  private void setAchievements() {`
`       progressBar.setVisibility(View.VISIBLE);`
`       if (checkAccount()) {`
`           compositeDisposable.add(mediaWikiApi`
`                   .getAchievements("Ainali")`
`

You can test achivements for a specific username by editing username in shared code part

**Comment by maskaravivek** [comment]
IMO, we can set the timeout to 60 seconds. As a future enhancement, we can show a more verbose loading indicator so that the user doesn't get impatient.

**Comment by ashishkumar468** [comment]
Although 60 is a lot, but considering out current scenario, I agree with @maskaravivek considering the worst cases

**Comment by maskaravivek** [comment]
Yes, with 60 seconds it is up to the user to wait or not. Also, we know of instances where the API is actually taking more than 30 secs.

**Comment by ashishkumar468** [comment]
I will go ahead and add a patch for the same

**Comment by misaochan** [comment]
Sounds good to me.

**Comment by domdomegg** [comment]
Fixed in #2080
