### ISSUE TITLE
Fix default license selector in Settings

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#2072]
From a user on our forum:

> I've selected CC-BY-SA 4.0 as my default license, but the upload wizard in step three defaults to CC-BY-SA 3.0 unless I manually change it each time.

**Comment by nicolas-raoul** [comment]
I confirm. I always select CC0 but the app sometimes (not always) reverts to the default.

**Comment by briancollins-92** [comment]
Hello, I've started working on this.

**Comment by misaochan** [comment]
Wonderful, thanks @briancollins-92 !
