### ISSUE TITLE
Multi-upload top widget does not always expand correctly

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#2079]
**Steps to reproduce:** 

1. Upload several images together
2. I the wizard, notice the banner at the top that says "3 Uploads". Press the arrow at its right
3. Sometimes (typically after moving from an image to the other) it does not expand.

 
**Commons app version:** 

2.9.0

**Screen-shots:** 
Notice the arrow:
![screenshot_20181204-102311](https://user-images.githubusercontent.com/99590/49443669-5db35880-f810-11e8-9473-ac14a641869b.png)
![screenshot_20181204-102307](https://user-images.githubusercontent.com/99590/49443719-80457180-f810-11e8-8452-05497a387ada.png)

**Comment by oluwadara-abijo** [comment]
I could not reproduce the issue but I noticed my banner is not at the center. The margin at the end is missing here.

![20190307_135420](https://user-images.githubusercontent.com/24768306/53958372-27bc9380-40e1-11e9-80de-d350bf921e97.png)
![20190307_135358](https://user-images.githubusercontent.com/24768306/53958374-28552a00-40e1-11e9-8c43-41eef341d036.png)
