### ISSUE TITLE
Night mode: Category pages

### ISSUE THREAD

**Issue by millbittencourt** [commons-app/apps-android-commons#2088]
**Summary:** 

When clicking on a category in night mode, the app does not show the "Parent Categories", there's a blank space instead.

**Steps to reproduce:** 

How can we reproduce the issue? 
Settings > Night Mode;
Explore > Click any image > Click on a random categorie > Parent Categories

What did you expect the app to do, and what did you see instead?
The names of the parent categories should be shown.

**Device and Android version:** 

Found on Xiaomi A1, Android 8.1.0

**Commons app version:** 
2.8.5

**Screen-shots:** 
![9a656a2e-8237-4dbe-b4b0-16f5b277ae89](https://user-images.githubusercontent.com/25803596/49691398-5d74cf00-fb28-11e8-9dc4-ca31751cbd9c.jpg)

**Would you like to work on the issue?**

Yess.

**Comment by vanshikaarora** [comment]
Hey!!
Have you made any changes to your code. My app crashes while trying to open this activity. It gives null pointer exception.

java.lang.NullPointerException: Attempt to invoke virtual method 'android.support.v4.app.FragmentActivity android.support.v4.app.Fragment.getActivity()' on a null object reference
        at fr.free.nrw.commons.media.MediaDetailPagerFragment$MediaDetailAdapter.getItem(MediaDetailPagerFragment.java:401)

**Comment by domdomegg** [comment]
@vanshikaarora I think that's unrelated. I fixed that in 46db38b8e902b4f81333ea54de41f861407c0e3c

**Comment by domdomegg** [comment]
Just checked, this also happens in subcategories. So basically any categories page

**Comment by vanshikaarora** [comment]
Ok @domdomegg  I'll check that out

**Comment by domdomegg** [comment]
@vanshikaarora are you working on this? Just want it to be clear for other developers looking at issues.

**Comment by Divyanshu2132** [comment]
I am working on this issue

**Comment by domdomegg** [comment]
Okay. I'm going to do the tabs separately in #2186, so please don't change them if possible (to avoid merge conflicts)

**Comment by Divyanshu2132** [comment]
Sure
I'll talk to you before changing or creating pull request

**Comment by Divyanshu2132** [comment]
@domdomegg I have created a pull request look into the files changed to avoid merge conflicts
