### ISSUE TITLE
Night mode: Search activity

### ISSUE THREAD

**Issue by millbittencourt** [commons-app/apps-android-commons#2090]
**Summary:** 

Searching for images or categories in night mode works but the words doesn't show neither the recent researches.

**Steps to reproduce:** 

How can we reproduce the issue? 
Settings > Set Night Mode on;
Explore > Search Tool > Type anything.

What did you expect the app to do, and what did you see instead?
We should see the words and recent researches while typing.

**Device and Android version:** 

What make and model device (e.g., Samsung J7) did you encounter this on?
Xiaomi A1
What Android version (e.g., Android 4.0 Ice Cream Sandwich or Android 6.0 Marshmallow) are you running?
Android 8.1.0 - Oreo
Is it the stock version from the manufacturer or a custom ROM ?
 
**Commons app version:** 
2.8.5

**Screen-shots:** 
![photo4927166128577423332](https://user-images.githubusercontent.com/25803596/49691883-5c956a80-fb33-11e8-99dd-209d8edb954f.jpg)
![photo4927166128577423331](https://user-images.githubusercontent.com/25803596/49691885-61f2b500-fb33-11e8-9ac2-268f1f2cc636.jpg)
![photo4927087895748126714](https://user-images.githubusercontent.com/25803596/49691895-9bc3bb80-fb33-11e8-8430-8fecdd9a7f49.jpg)

**Would you like to work on the issue?**
Yep.

**Comment by vanshikaarora** [comment]
Hey!
I have started working upon this issue.

**Comment by pereiraJr** [comment]
#2095

**Comment by domdomegg** [comment]
As of 3399576 search activity looks like

![screenshot_1545307990](https://user-images.githubusercontent.com/4953590/50284327-a560f380-0450-11e9-8ca6-4f24f4789c9f.png)
![screenshot_1545307992](https://user-images.githubusercontent.com/4953590/50284328-a560f380-0450-11e9-9ca8-9b50a3e08f08.png)
