### ISSUE TITLE
Cannot sign up on beta version

### ISSUE THREAD

**Issue by Szymon20000** [commons-app/apps-android-commons#2094]
Probably the problem is with server.
I tried to go to the address from buildConfig on my computer: 
```public static final String SIGNUP_LANDING_URL = "https://commons.m.wikimedia.beta.wmflabs.org/w/index.php?title=Special:CreateAccount&returnto=Main+Page&returntoquery=welcome%3Dyes";``` and there was nothing but white screen.

**Comment by Szymon20000** [comment]
How can I sign up for the beta version of the app? I just want to contribute, but I need an account.

**Comment by misaochan** [comment]
I think there might be a bit of confusion here. It looks to me like you are trying to access the "beta" product flavour of the app, which  uses the Commons Beta server, i.e. uploads do not go to the real Commons. On the other hand, the "beta version" of the Commons app can be downloaded from the Play Store by signing up at https://play.google.com/apps/testing/fr.free.nrw.commons .

Are you wanting to contribute as a developer or as a tester?

**Comment by Szymon20000** [comment]
I want to contribute as a developer. I see that it works properly now. Thanks.
