### ISSUE TITLE
Remove from EXIF: copyright field (name)

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#212]
By jayvdb at https://github.com/nicolas-raoul/apps-android-commons/issues/181

Remove real name from copyright field, if the camera adds it and the user wishes to remain pseudonomous.

An external app to perform this isnt very helpful, as most users will want to keep EXIF on the media on their device, but upload to Commons without some of the EXIF, and possibly only remove it for some media. The user doesnt want to create a separate set of images before uploading.

**Comment by ilgazer** [comment]
I can take this up.

**Comment by misaochan** [comment]
Great, thanks @ilgazer !

**Comment by ilgazer** [comment]
Implemented in #2863
