### ISSUE TITLE
Include releases notes while making automated play store alpha releases

### ISSUE THREAD

**Issue by maskaravivek** [commons-app/apps-android-commons#2126]
**Summary:** 

After #1056, at each commit to master a new alpha release is made automatically. It would be great if we could include automatic release notes with it. 

We use `Squash and merge` for merging any PR that means our Github history is pretty clean. We can simply use Github commit message for the `What's new` section.

**Comment by maskaravivek** [comment]
If anyone wants to pick this up, this guide might be useful. We have everything in place, and we just need to implement the "Generating release notes on the fly" bit. 

https://proandroiddev.com/gradle-play-publisher-43abf77db344

**Comment by maskaravivek** [comment]
I am attempting to make this work. Will make a few changes and commit directly to master to check it out. Will revert back if things don't work. 

You might receive a couple of dummy alpha releases. Please ignore them. :)

**Comment by maskaravivek** [comment]
Release notes are now published along with automatic alpha releases: 

![Screenshot_2019-03-10-18-53-01-105_com android vending](https://user-images.githubusercontent.com/3069373/54085986-3c5f8c80-436a-11e9-97c8-ddd0468ed573.png)

As of now am showing just the latest change ie the last commit because we make a release after every commit. But practically, would it be more useful if we show the last 5 changes. So that when I update the app, I can easily figure out what all changed recently? 

@misaochan @nicolas-raoul

**Comment by nicolas-raoul** [comment]
I would say latest change is the best :-)
5 changes might lead to misunderstandings.
