### ISSUE TITLE
Multiple Uploads: All pictures are having same description

### ISSUE THREAD

**Issue by sp2710** [commons-app/apps-android-commons#2131]
**Summary:**

I uploaded some photos via multiple uploads. Each one having different description. After Uploading all photos have the same description. The description they have is the description of the last photo.

**Steps to reproduce:**

Upload multiple photos via multiple uploads option all having different description.

**Device and Android version:**

Motorola Moto G5 plus API 24

**Commons app version:**

2.9-release prodRelease build

**Would you like to work on the issue?**

Yes

**Comment by domdomegg** [comment]
Recreated on master (fb3055e)

Uploaded two files:

- `Test2132 0 1` with description `Desc 1`
- `Test2132 0 2` with description `Desc 2` 

However on commons both have description `Desc 2`

https://commons.wikimedia.beta.wmflabs.org/wiki/File:Test2132_0_1.jpg
https://commons.wikimedia.beta.wmflabs.org/wiki/File:Test2132_0_2.jpg
