### ISSUE TITLE
"Upload your first media" message visible when loading my contributions

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#2139]
![screenshot_20181217-104330](https://user-images.githubusercontent.com/99590/50064779-51f36900-01f6-11e9-98ab-215bd1faeaf5.png)

2.9.0 last alpha

My Internet connection might have been flimsy at that time.

**Comment by domdomegg** [comment]
Made a little progress in https://github.com/domdomegg/apps-android-commons/commit/8cf13ecc372ce7ae0d6515b6d4e142ef825b3c43 which might help someone to take this up in the future.

Problem is on logging in for the first time `onLoadFinished` is called with a cursor with zero rows (see FIXME on L324 of ContributionsFragment). Therefore once a user logs in and has bad internet they will see the "Welcome to Commons!" message for a few seconds before the images actually load. However if they have contributions, they should actually see the loading animation (loadingContributionsProgressBar).

**Comment by domdomegg** [comment]
Yep, not working on this any more. Assigned to @srinivas1729
