### ISSUE TITLE
Left swipe on home activity: show nearby?

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#2140]
With the tabbed contributions/nearby UI, it would seem natural to show nearby when swiping. Like in Snapchat.

Low priority.

**Comment by neslihanturan** [comment]
Thanks Nicolas, it was default. But I intentionally disabled. Because, swiping nearby card view and moving around nearby map uses same gestures. Thus, sometimes tabs changes accidentally.

**Comment by nicolas-raoul** [comment]
Indeed swipe should not do anything when on the Nearby tab.

**Comment by neslihanturan** [comment]
When it comes to contributions fragment, nearby card view and campaigns card view use swipe and hide gestures. Thus, my suggestion is totally disabling it for tab switching.

**Comment by ashishkumar468** [comment]
Agree with @neslihanturan  on this one. Enabling swipe for one of the tabs and not for the other does not seems the best thing to me
