### ISSUE TITLE
User unable to login

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#215]
From a recent Google Play review:

krishnag kulkarni 28 Jul 2016 at 14:19 0 0
Can't log in. Cannot login even if i have created an account with Wikipedia. I think the app must be awesome. Please fix this issue asap.

Any idea what the issue is?

**Comment by nicolas-raoul** [comment]
The best would be to contact the user by replying to their review, but it seems Wikimedia has not given us the permission to do that? Do you have something like below?
![screenshot from 2016-08-01 14-40-14](https://cloud.githubusercontent.com/assets/99590/17284493/1c8707ec-57f6-11e6-8f8e-67ecb021bc7b.png)

**Comment by misaochan** [comment]
Nope :/

**Comment by whym** [comment]
According to <https://meta.wikimedia.org/wiki/Schema:MobileAppLoginAttempts>, the failed login attempt should have been logged on the server side. If someone [obtains an NDA](https://meta.wikimedia.org/wiki/Schema:MobileAppLoginAttempts) with WMF and look at it, we can get a bit more information.

**Comment by misaochan** [comment]
That would be a good idea if possible, 3 out of 12 of our reviews are people having trouble with logging in. :/
