### ISSUE TITLE
When uploading a single image the category and license selector implies plural

### ISSUE THREAD

**Issue by domdomegg** [commons-app/apps-android-commons#2163]
**Summary:** 

When uploading a single image there's is the message `(For all images in set)`. While it still kind of works (as it's a set of 1 image), it does feel a bit weird. Think it would be better just being hidden in the case of uploading 1 image.

Sorry to keep being so specific about these details, but I do think it improves the overall 'polish' of the app.

@ravi-kishan or @zhao-gang one (one!) of you might want to take this up given it's probably quite similar to #2156.

**Screen-shots:**

| Categories | License |
| - | - |
| ![screenshot_1545153852](https://user-images.githubusercontent.com/4953590/50171845-7c731e00-02eb-11e9-870f-0e4fa1ae98b9.png) | ![screenshot_1545153949](https://user-images.githubusercontent.com/4953590/50171848-7e3ce180-02eb-11e9-8c7a-7aad15d9d59e.png) |

**Comment by maskaravivek** [comment]
@domdomegg Thanks for finding and creating issues which beginners can pick up. :)

**Comment by zhao-gang** [comment]
@domdomegg I'd like to pick this. Check the number of images and hide the view if it is only one image could fix this issue.
