### ISSUE TITLE
Links out of the app should use Utils.handleWebUrl

### ISSUE THREAD

**Issue by domdomegg** [commons-app/apps-android-commons#2164]
**Summary:** 

Links to Wikimedia Commons should probably use `Utils.handleWebUrl` instead of launching the web browser, so it feels less like you're leaving the app. Also can immediately return by pressing the `x` in the top right. Also see screenshots below.

Some places I know where this is not implemented are:
- the final upload page the link to `Wikimedia Commons Policies`
- the final upload page links to CC licenses
- about page text links

This one will probably be debatable (please do comment with arguments below), but there's also the 'View in browser' functionality from viewing media. I'd say not to handle this with `Utils.handleWebUrl` because I think the user does expect to be taken out of the app there.

**Screen-shots:** 

| Not using `Utils.handleWebUrl` | Using `Utils.handleWebUrl` |
| - | - |
| ![screenshot_1545155295](https://user-images.githubusercontent.com/4953590/50172507-2606df00-02ed-11e9-843b-317c9b02d2e5.png) | ![screenshot_1545155288](https://user-images.githubusercontent.com/4953590/50172509-269f7580-02ed-11e9-8cd7-ab95e73d7a56.png) |

**Comment by DylanRobson** [comment]
I'm working on this. 👍
