### ISSUE TITLE
Clearing recent searches only removes last 10

### ISSUE THREAD

**Issue by domdomegg** [commons-app/apps-android-commons#2181]
**Summary:** 

Currently, clicking the 'bin' icon on searches only deletes your last 10 searches. Personally I think it should wipe your entire search history - I'm not sure why it's implemented the way it is currently.

If however we do want it to only delete last 10 then at least the method call should be renamed to something other than `deleteAll`

https://github.com/commons-app/apps-android-commons/blob/b0b4b0810084a89d2be80c10814be921ecaa4835/app/src/main/java/fr/free/nrw/commons/explore/recentsearches/RecentSearchesDao.java#L58

**Comment by sp2710** [comment]
Hey.I had started working on this
