### ISSUE TITLE
Night mode: Tabs

### ISSUE THREAD

**Issue by domdomegg** [commons-app/apps-android-commons#2186]
**Summary:** 

Tabs are inconsistent in how they are styled. I'm okay with MainActivity being different but Search and Category tabs should definitely look the same.

Should also probably standardise across non-night mode too.

Tabs are used in (edit this list if I've forgotten some):
- MainActivity (Contributions/Nearby)
- SearchActivity (Media/Categories)
- Category page (Media/Subcategories/Parent categories)
- Bookmarks page (Pictures/Locations)

**Screen-shots:** 

| MainActivity | SearchActivity | Category |
| - | - | - |
| ![screenshot_1545301973](https://user-images.githubusercontent.com/4953590/50279898-fbc73580-0442-11e9-9990-fa9708887bf4.png) | ![screenshot_1545302017](https://user-images.githubusercontent.com/4953590/50279899-fbc73580-0442-11e9-8f50-d320d5cfa736.png) | ![screenshot_1545302049](https://user-images.githubusercontent.com/4953590/50279900-fbc73580-0442-11e9-9e52-1ef04f79eb53.png) |

**Comment by borisenkotim** [comment]
Hey, I would like to work on this issue.

**Comment by domdomegg** [comment]
Assigned to @borisenkotim

**Comment by domdomegg** [comment]
It's obviously up for debate, but I think the best look is having them look like part of the toolbar (as they are in the `Category` screenshot above).

**Comment by domdomegg** [comment]
Or white on black is quite good. Basically just not something with a white background.

**Comment by neslihanturan** [comment]
Actually my favorite here is first (MainActivity) style, _whoever create a PR please share 3 screenshots for dark theme like above and 3 for light theme._ 

But I think this PR requires discussion, so please do not start implementation before we find our path.

**Comment by borisenkotim** [comment]
Working on it.

**Comment by domdomegg** [comment]
Looks good. I can have a look over the code so far if you'd like - push your changes to your fork on Github and start a pull request with `[WIP]` in the title (work in progress).

**Comment by borisenkotim** [comment]
Before
![searchb](https://user-images.githubusercontent.com/42623783/50390686-2806de80-06ef-11e9-8199-b162b0101b40.png)
After
![searcha](https://user-images.githubusercontent.com/42623783/50390691-2d642900-06ef-11e9-9292-472d9e69b49b.png)

Here is how the searchactivity page looks now.
