### ISSUE TITLE
Night mode: Settings

### ISSUE THREAD

**Issue by domdomegg** [commons-app/apps-android-commons#2187]
**Summary:** 

In night mode:
- Dark blue text hard to read in settings
- Blue toggle switches are hard to see in settings

**Screen-shots:** 

![screenshot_1545301108](https://user-images.githubusercontent.com/4953590/50280062-6bd5bb80-0443-11e9-9419-8975269a672c.png)

**Comment by sp2710** [comment]
I am working on this

**Comment by domdomegg** [comment]
> @sp2710 Apologies for doing so, but I think I've accidentally fixed the toggle buttons working on #2095. Can you just focus on the titles for this one?

Actually maybe not. Ignore this for now.

**Comment by domdomegg** [comment]
Closed in #2098
