### ISSUE TITLE
Category selection screen disappears after accepting permission

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#219]
1. Install the app
2. Push Gallery button, choose pic to upload
3. Enter description, save
4. Categories selection screen is empty, with a bottom thing asking for a permission (location I think?), press it
5. Accept the permission
6. The screen disappear, back to the gallery, no way to enter categories

I guess this only happens once, but it probably confuses everyone trying the app for the first time.
It might also give the impression that not filling categories is OK.

**Comment by misaochan** [comment]
Should have been fixed, please let me know if anyone is still experiencing this.
