### ISSUE TITLE
Rename "Nearby" feature?

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#2190]
With the implementation of #591 , it seems that Nearby is no longer just "Nearby" any more, but rather a full-fledged map of places that need pictures, anywhere in the world.

I wonder if we should consider renaming the feature? To be fair, I can't think of anything else that is equally concise, and "Nearby" is what all of us refer to it as now. But it just doesn't seem accurate anymore.

**Comment by domdomegg** [comment]
Maybe just "map"? I feel if we were to call it this it would need a search feature which I think could be difficult to implement well without using non-open-source services.

Given it does start at your location "nearby" does still kinda make sense

**Comment by neslihanturan** [comment]
We need to update nearby info i consequently, see #2194 . Map is a alternative, does "Upload via Map" too long;?

**Comment by nicolas-raoul** [comment]
I think "Nearby" is the best for now.
It makes people curious, it is personal and a call to action.

An even more personal name could be "Around you".

If the tab was called "Map" I believe many people would think "Why would I want to see a map, that's boring".

**Comment by Rishavgupta12345** [comment]
@nicolas-raoul @4D17Y4 this issue is obsolete so we can close this now

**Comment by misaochan** [comment]
Yes, I think the consensus is that "Nearby" is still best. Closing. :)
