### ISSUE TITLE
Update Nearby ⓘ icon content after "search this area" feature

### ISSUE THREAD

**Issue by neslihanturan** [commons-app/apps-android-commons#2194]
**Summary:** 

We need to update nearby information box text and include search this area feature ( #2051 ) in it.

**Comment by ShridharGoel** [comment]
May I take this up?

**Comment by domdomegg** [comment]
Assigned to @ShridharGoel

**Comment by neslihanturan** [comment]
Team, can we discuss the text needs to be written here?

**Comment by ShridharGoel** [comment]
What about "...fixes the map at that location..."? Or maybe we can omit that part and just write that it launches a nearby search around that location?

**Comment by domdomegg** [comment]
I think the focus on the text should not really be explain the feature given it's pretty self explanatory - or the technical aspects like the fact it will lock the map. I think it should be on informing users that they can move the map to another place to search a different location.

**Comment by neslihanturan** [comment]
I think we can also emphasize this is a **new** feature. But I couldn't establish the sentence. Something like [Previous sentence] +
Now, you can also discover and improve knowledge for other places by moving on the map.

**Comment by domdomegg** [comment]
Sure. Will need to keep updated though, because it won't be a new feature a couple releases down the line so we'd have to remove 'now'.
