### ISSUE TITLE
Non-existent category proposed

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#22]
In the categories selection dialog, when I start typing "flapja" I get two choice: "Flapjack" and "Flapjack image". None of these categories exist on Commons, the only real choice is "Flapjacks".

I tried selecting "Flapjack", and [as a result](https://commons.wikimedia.org/w/index.php?title=File:%E3%82%B5%E3%83%B3%E3%82%B6%E3%82%B7_cereal_bar.jpg&action=history) the image is attributed that wrong category, resulting in a red link.

That category does not even seem to have been renamed recently, so I am not sure what is going on: https://commons.wikimedia.org/w/index.php?title=Category:Flapjacks&action=history

I had never searched for that category (or any with a similar name) before.

Where the request for categories from Commons seems to be made: https://github.com/nicolas-raoul/apps-android-commons/blob/master/commons/src/main/java/fr/free/nrw/commons/category/CategorizationFragment.java#L169

The same (mostly, I think?) request on the API sandbox: https://commons.wikimedia.org/wiki/Special:ApiSandbox#action=query&list=allcategories&format=json&acfrom=flapja&acdir=descending as you can see results are "Flap Jack" and "FlapJack Image". Not sure where "Flapjack" came from.

**Comment by nicolas-raoul** [comment]
Same with "Former school" https://commons.wikimedia.org/wiki/File:Former_school_in_Le_Puy-Notre-Dame.jpg

**Comment by nicolas-raoul** [comment]
https://commons.wikimedia.org/wiki/Category:Badge actually does not exist and does not seem to have ever existed:

![screenshot_2016-03-08-22-32-43](https://cloud.githubusercontent.com/assets/99590/14165213/636eee60-f741-11e5-87cb-0ba23eef9edd.png)

With latest version as of 2016 March 08

**Comment by misaochan** [comment]
Hmm. Is this fixable on our end though? We're just returning the categories found via the Commons API. Could there be an issue with the way the API works?

**Comment by nicolas-raoul** [comment]
Is this a limitation documented in the API's documentation?

This is a problem that affects us, and since it is not a problem with our code, we have to report the problem upstream. Probably the best place would be Phabricator? Maybe there is even an existing issue about it already?

**Comment by misaochan** [comment]
Okay, I'll ask about it on the #Commons project board, that should be the best place right?

**Comment by nicolas-raoul** [comment]
Do you mean https://commons.wikimedia.org/wiki/Commons:Village_pump ?
People there know about content policies but often not much about technical things

The present problem is probably deep inside the Mediawiki software, and the file search feature is used on many wikis, not just Commons, so I think Phabricator is a better place to ask. It also lowers the probability that the topic gets forgotten :-)

**Comment by misaochan** [comment]
Oh, no, I meant what project board I should tag my Phabricator task with. Like https://phabricator.wikimedia.org/tag/commons/

**Comment by nicolas-raoul** [comment]
Oh I understand! Yes sounds good :-)

**Comment by misaochan** [comment]
Posted at https://phabricator.wikimedia.org/T139911 , tagging #Commons and #MediaWiki-API. Please feel free to modify my post as needed. :)

**Comment by nicolas-raoul** [comment]
Thanks!

**Comment by jayvdb** [comment]
So, categories do exist when an image uses them, even if a page for the category doesnt exist.

I.e. one image here:
https://commons.m.wikimedia.org/wiki/Category:Flapjack

**Comment by nicolas-raoul** [comment]
@jayvdb : Thanks for the investigation! https://commons.wikimedia.org/wiki/Category:Flapjack says "This page does not currently exist". The Commons search API seems to return any category name that at least an image uses, regardless of whether the category page exists or not.

If confirmed, I would call that a bug of the API. Or at least we should have the option to ask for only categories with existing pages, imho.

**Comment by jayvdb** [comment]
In mediawiki terminology, the category exists even if the page about the category does not.

You can add extra parameters & properties to the results to filter out those categories, and maybe filter out redirects, etc.
Or maybe you want `list=allpages&alnamespace=14`

See https://m.mediawiki.org/wiki/API:Allcategories and https://m.mediawiki.org/wiki/API:Allpages

**Comment by misaochan** [comment]
Posted by anomie (who also closed the Phab task):

> The definition of "category" for list=allcategory includes anything that was ever a category on a page, even if it doesn't have any members anymore. This is independent of whether a corresponding page ever existed in the Category namespace.
> 
> See also T28411: Entries for non-existent categories should be deleted from the 'category' table.

**Comment by nicolas-raoul** [comment]
As an upload client, I guess what we want is not just "categories" as defined in the two previous comments. Instead, we want "currently already in use categories".

@jayvdb: https://commons.wikimedia.org/w/api.php?action=query&list=allcategories&acprefix=badge&aclimit=25&alnamespace=14 says `Unrecognized parameter: 'alnamespace'`... any idea how to modify the API request to get what we want? Thanks a lot! :-)

Linking to the Phabricator issue for this Mediawiki bug: https://phabricator.wikimedia.org/T28411

**Comment by jayvdb** [comment]
I still dont know 100% what you want, but we are getting close .
I suspect https://commons.wikimedia.org/w/api.php?action=query&list=allcategories&acprefix=badge&acmin=2&acprop=size , with client side ordering, would be appropriate.

But possibly if you have a fixed sized UI list to fill, or you want to get the best results first (responsive app) and fetch lower value results second, issue 
https://commons.wikimedia.org/w/api.php?action=query&list=allcategories&acprefix=badge&acmin=100&acprop=size&aclimit=25 first, and if there are less then 25 results, send another query using `acmin=2&acmax=9` to fill the UI space available . Categories with only one member are likely to be unsuitable categories

**Comment by nicolas-raoul** [comment]
Interesting!
Server-side ordering would really be more efficient than performing many requests and then dropping most of the results...

Showing first categories that contain many files sounds like a good idea indeed. Also showing categories that are towards the root (even if they have only sub-categories and no files) would probably be another good idea.

**Comment by nicolas-raoul** [comment]
Using version 2.9.0, category https://commons.wikimedia.org/wiki/Category:Azabujuban_summer_festival was proposed, even though it is a category redirect to the real category https://commons.wikimedia.org/wiki/Category:Azabu-J%C5%ABban_N%C5%8Dry%C5%8D_Matsuri
```
{{Category redirect|Azabu-Jūban Nōryō Matsuri}}
```

**Comment by ashishkumar468** [comment]
Seems to be fixed, feel free to re-open if this still exists on the latest releases

**Comment by nicolas-raoul** [comment]
It is still happening unfortunately.
When I searched for trees in the app I saw this suspicious category: "Trees,nature..."
![20201012_082628](https://user-images.githubusercontent.com/99590/95693045-30822d80-0c65-11eb-87f9-2a14ed93725e.jpg)

Sure enough, Upload Wizard does not allow it:
<img width="657" alt="Screen Shot 2020-10-12 at 08 24 56" src="https://user-images.githubusercontent.com/99590/95693053-3bd55900-0c65-11eb-9ad1-5eb5c7ca944c.png">
For reference here is how the upload wizard looks when typing a valid category name:
<img width="658" alt="Screen Shot 2020-10-12 at 08 24 45" src="https://user-images.githubusercontent.com/99590/95693065-50b1ec80-0c65-11eb-8e2d-856394117a57.png">

The problem is probably that one picture wrongly uses that category name: https://commons.wikimedia.org/wiki/File:Forest_!!.jpg
Upload Wizard's category search is inferior to our category search, so replacing our search algorithm with theirs is not a good solution. But maybe we should double-check that categories exist before listing them?

**Comment by sivaraam** [comment]
Showing a category regardless of whether a page exists for it or not is how the `allcategories` API we use is designed to behave. I'm not sure if we have anything to do in our end for this. 

The cases you observe would eventually get fixed when the community removes those categories. For instance, the last case mentioned even seems fixed now. So, can we close this issue?

**Comment by nicolas-raoul** [comment]
Indeed it does not seem to happen anymore.
