### ISSUE TITLE
Clicking back on Notifications always takes to Home

### ISSUE THREAD

**Issue by ShridharGoel** [commons-app/apps-android-commons#2208]
**Summary:** 

Clicking back on Notifications always takes to Home.

**Steps to reproduce:** 

1. Go to Explore.
2. Now, go to Bookmarks.
3. Then, Notifications.
4. Press back.
5. Home will open.

Expected behaviour:
Pressing back should have taken to Bookmarks. Again pressing back should have opened Explore. On going back again, Home should have come up.

**Device and Android version:** 

Android 7.1.2 (API 25)
 
**Commons app version:** 

2.9.0
Branch:master
Build variant: betaDebug

**Would you like to work on the issue?**

Yes

**Comment by maskaravivek** [comment]
Fixed in #2102.
