### ISSUE TITLE
Pressing back when viewing a category of a picture from search or explore goes too far

### ISSUE THREAD

**Issue by domdomegg** [commons-app/apps-android-commons#2212]
**Summary:** 

When pressing 'back' when viewing a category from media details of in explore or search activity, it returns you to explore/search results rather than the media page.

This doesn't happen if you are viewing through a category.

Should make sense if you view GIFs below.

**Steps to reproduce:** 

1. Go to explore
2. Click the first picture
3. Click the first category
4. Click back
Expected: view the media the user was just viewing
Actual: returns to explore

GIF:

![mediaback](https://user-images.githubusercontent.com/4953590/50363228-aa15cc80-0562-11e9-958b-e53f53576fed.gif)

Note if viewing "through" a category this doesn't happen, so might want to look at how that is implemented and reuse it. For example:

![expected](https://user-images.githubusercontent.com/4953590/50363315-f9f49380-0562-11e9-9907-7c7b7cc9ec82.gif)

**Comment by Divyanshu2132** [comment]
@domdomegg 
So you want that on back pressing it should go to the picture from where it was called?
I can take up this issue

**Comment by domdomegg** [comment]
@Divyanshu2132 yes exactly

**Comment by domdomegg** [comment]
Assigned to @Divyanshu2132

**Comment by domdomegg** [comment]
If you can't reproduce it, it may have been fixed. If it doesn't cause a bug, I'm not sure how it affects this issue - could you explain some more and I might be able to help? Thanks for continuing to work on the issue :)

**Comment by sp2710** [comment]
@domdomegg I would like to work on this issue

**Comment by domdomegg** [comment]
Assigned to @sp2710 - however I don't want to assign you to to many things at once - are you still working on #2609?

**Comment by sp2710** [comment]
Yes. For now I am having an issue in setting up emulator with API 19. I will work on #2609 after solving this issue
