### ISSUE TITLE
Incorrect Greek translation of "navigation_item_about"

### ISSUE THREAD

**Issue by athatsakk** [commons-app/apps-android-commons#2223]
**Summary:** 

When i press the menu button , and menu shows up , there is an option called 'About' in english. In my case ( that i have greek language ) it's called 'Γύρω Από' , and when i press this button , on the top the name changes to another one called 'Σχετικά' ( this one is the correct by the way ).

**Steps to reproduce:** 

It should have the same 'name' at every location

**Device and Android version:** 

Samsung J7 2017

 
**Commons app version:** 

2.8.5

**Screen-shots:** 

![48389708_267424367257805_7177298416458792960_n](https://user-images.githubusercontent.com/32622637/50383267-c1ff6480-06b8-11e9-842d-e9ebdd0ff795.jpg)
![48418611_1008454582682515_3183023352809783296_n](https://user-images.githubusercontent.com/32622637/50383269-cb88cc80-06b8-11e9-955c-6bb15551bb40.jpg)

**Comment by NicholasWeiner** [comment]
I can take on this issue.

**Comment by domdomegg** [comment]
Hi @athatsakk, thanks for bringing this to our attention.

Translations are managed on translatewiki. This exact string is here:
https://translatewiki.net/w/i.php?title=Special:Translate&showMessage=commons-android-strings-navigation_item_about&group=commons-android-strings&language=en-gb&filter=&optional=1&action=translate

Unfortunately I haven't gone through the translatewiki verification process so I can't edit this yet.

@NicholasWeiner I think you're new to the project so I'd advise reading through https://github.com/commons-app/apps-android-commons/wiki/Translating-the-app. If you edit the Greek `strings.xml` and submit a PR the @translatewiki account will overwrite it so it does need to be done there.

**Comment by domdomegg** [comment]
I got translatewiki rights and have updated this translation. Hopefully we should get changes ported into the app by translatewiki soon. Please reopen this issue if this still happens after the latest update.
