### ISSUE TITLE
Only allow squash merging in with Github settings

### ISSUE THREAD

**Issue by domdomegg** [commons-app/apps-android-commons#2225]
**Summary:** 

Current policy is to only use squash and merge. I can't see a scenario where we'd need to have the flexibility to not do this, so recommend enforcing it in the Github settings so we can remove it from documentation.

Tagging @nicolas-raoul and @misaochan as I believe you two are the only ones with permissions to edit these settings.

**Screen-shots:** 

I believe the option should be set to:

![image](https://user-images.githubusercontent.com/4953590/50387595-2392f380-06f8-11e9-8a3b-87304b6430fa.png)

**Comment by misaochan** [comment]
Hmmm. I'm good with setting it up, if we have a consensus. @nicolas-raoul @maskaravivek ?

**Comment by maskaravivek** [comment]
Am also fine with it. :)

**Comment by nicolas-raoul** [comment]
Feel free to take decisions without waiting for me :-)

**Comment by whym** [comment]
For context, there was https://github.com/commons-app/apps-android-commons/issues/1386 in April 2018 and we maintained the options other than squashing during transition.

It looks like it's time to move out of the transition. :)

**Comment by misaochan** [comment]
Done, thanks all. :) Let me know if any problems.
