### ISSUE TITLE
History issues while exploring

### ISSUE THREAD

**Issue by athatsakk** [commons-app/apps-android-commons#2231]
**Summary:** 

When i press the explore button, history comes up with my previous searches. When i search something new and results shows up, i press 'x' button on right top and goes back to my history. But history does not refresh and i have to go to main page and then back to 'explore' ( in order to refresh my history ).

This may cause a lot of issues , one of them is this below

**Steps to reproduce:** 

Go to 'explore'
( Clear your history )
Search something
Press 'x' button
Delete your history

Your history will not be empty but it will contain your last search

**Screen-shots:** 

![49253476_591294174658349_1579986041471762432_n](https://user-images.githubusercontent.com/32622637/50424778-b5267080-0872-11e9-8478-d7ff3d05c6f3.jpg)
![48908433_2290950857591024_8970439518712758272_n](https://user-images.githubusercontent.com/32622637/50424781-b9528e00-0872-11e9-94b7-6eaa52a3df1a.jpg)
![48413605_2054084407964047_9175477018291077120_n](https://user-images.githubusercontent.com/32622637/50424784-beafd880-0872-11e9-8883-6e109d59a211.jpg)
![48926283_2033832026696717_5357977998182055936_n](https://user-images.githubusercontent.com/32622637/50424785-c1aac900-0872-11e9-9afe-1618686e34a7.jpg)
![49106298_336037940314969_6255988353343160320_n](https://user-images.githubusercontent.com/32622637/50424787-c40d2300-0872-11e9-8fed-6935da8206f6.jpg)

''Το ιστορικό αναζήτησης διεγράφη''     ---->   History cleared 
the other message with options 'yes' , 'no' is the message when you try to clear your history

**Comment by ShridharGoel** [comment]
I would like to work on this.
