### ISSUE TITLE
Cannot sync 

### ISSUE THREAD

**Issue by Szymon20000** [commons-app/apps-android-commons#2233]
"Caused by: java.lang.IllegalStateException: No credentials provided
	at com.github.triplet.gradle.play.internal.ValidationKt.requireCreds"

How can I sync Gradle project properly?

**Comment by whym** [comment]
What were you going to do before seeing this? Was it the automatic 'sync' of Android Studio? What will happen if you try to use any gradle command from CUI?

**Comment by nicolas-raoul** [comment]
Please ask on the mailing list instead, thanks! :-)
https://groups.google.com/d/forum/commons-app-android
