### ISSUE TITLE
Sub-categories and parent categories not visible in night mode

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#2234]
![screenshot_20181226-193906](https://user-images.githubusercontent.com/99590/50448552-e0b06600-0919-11e9-9e96-0fc766189312.png)
![screenshot_20181226-193922](https://user-images.githubusercontent.com/99590/50448563-eb6afb00-0919-11e9-9af8-564c8acdd03a.png)

White on white background
2.9.0.139

**Comment by ShridharGoel** [comment]
I would like to work on this.

**Comment by vanshikaarora** [comment]
Hey!! I can  work on this

**Comment by maskaravivek** [comment]
Sure @vanshikaarora, feel free to take this up. :)

**Comment by vanshikaarora** [comment]
OK I'll take this up

**Comment by vanshikaarora** [comment]
@maskaravivek  I had noticed that this was the issue of some previous versions after pulling the code from the master I couldn't reproduce this issue. Could you please recheck. I guess the issue was resolved here https://github.com/commons-app/apps-android-commons/pull/2213

**Comment by maskaravivek** [comment]
@nicolas-raoul Can you confirm if this issue is fixed in the latest alpha. 

@vanshikaarora You can probably pick up other [beginner-friendly](https://github.com/commons-app/apps-android-commons/labels/beginner%20friendly) issues for the time being. :)

**Comment by vanshikaarora** [comment]
ok

**Comment by nicolas-raoul** [comment]
Yes it is fixed thanks :-)
