### ISSUE TITLE
"No images found" despite category having images

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#2237]
alpha
reproducible always
![screenshot_20181227-124616](https://user-images.githubusercontent.com/99590/50470436-56631300-09a8-11e9-996f-6efa3f043d70.png)
![screenshot_20181227-124723](https://user-images.githubusercontent.com/99590/50470443-5ebb4e00-09a8-11e9-96f7-5ca015a4e980.png)

**Comment by Divyanshu2132** [comment]
I am willing to work on this issue

**Comment by albendz** [comment]
I would like to try to repo this: can you tell me which branch is "alpha"?

**Comment by nicolas-raoul** [comment]
@albendz Alpha is actually reflects the latest commit on the master branch.

Actually I can't reproduce the problem either, so I will close this :-)
