### ISSUE TITLE
Show map scale

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#2238]
Like in Google Maps.
Useful when planning another area

**Comment by pgmpofu** [comment]
@nicolas-raoul  May I work on this?

**Comment by nicolas-raoul** [comment]
@pgmpofu Yes it is yours :-)
Let us know about your progress once a day or so.
Thanks!

**Comment by namrata-jha** [comment]
Since there hasn't been any updates on this issue, can I take it up?

**Comment by pgmpofu** [comment]
@namrata-jha  I'm have forked a branch and am currently working on it

**Comment by nicolas-raoul** [comment]
@pgmpofu Cool looking forward to your pull request :-)

**Comment by pgmpofu** [comment]
@namrata-jha please take over this issue. I apologize for the inconvenience but I am unable to complete due to other commitments.

**Comment by 318anushka** [comment]
Can i take this issue if no one is working on it?

**Comment by sivaraam** [comment]
@318anushka Sure. I've assigned this issue to you. Let us know how you get on. Also let us know if you need any help with something. 🙂

**Comment by 318anushka** [comment]
Thanks @sivaraam I'll keep you updated with the work.

**Comment by 318anushka** [comment]
I am an outreachy applicant and since this is my first issue so i'll be needing a little help with it.
So i am thinking to proceed with scale bar plugin as it is used with mapbox object.

**Comment by sivaraam** [comment]
> I am an outreachy applicant and since this is my first issue so i'll be needing a little help with it.

Sure. Feel free to ask for help when you need it. 👍 

> So i am thinking to proceed with scale bar plugin as it is used with mapbox object.

Yeah, proceed with that.

**Comment by 318anushka** [comment]
@Override
    public void onMapReady(@NonNull MapboxMap mapboxMap) {

        mapboxMap.setStyle(Style.MAPBOX_STREETS, new Style.OnStyleLoaded() {
            @Override
            public void onStyleLoaded(@NonNull Style style) {

                scaleBarPlugin = new ScaleBarPlugin(mapView, mapboxMap);
                scaleBarOptions = new ScaleBarOptions(getContext())
                        .setTextColor(R.color.button_background_light)
                        .setTextSize(35f)
                        .setBarHeight(10f)
                        .setBorderWidth(5f)
                        .setMetricUnit(true)
                        .setRefreshInterval(15)
                        .setMarginTop(50f)
                        .setMarginLeft(15f)
                        .setTextBarMargin(15f);

                scaleBarPlugin.create(scaleBarOptions);
                scaleBarPlugin.setEnabled(true);
            }
        });

   }

This is my code for implementing Scalebar in NearbyParentFragment. I have also included necessary dependencies but it won't work.
What am i missing.

**Comment by macgills** [comment]
@318anushka is this code getting executed? I think I just saw some ticket about `onMapReady` never firing but it could have been quite old. Put a breakpoint in this method and see if it gets triggered when you debug

**Comment by 318anushka** [comment]
> @318anushka is this code getting executed? I think I just saw some ticket about `onMapReady` never firing but it could have been quite old. Put a breakpoint in this method and see if it gets triggered when you debug

yes you're right , i checked and it's not getting executed but according to following article:

https://stackoverflow.com/questions/27531037/onmapready-not-calling-even-though-the-map-display-without-any-error?rq=1

onMapReady() is triggered by getMapAsync() and we are calling that in onViewCreated()

**Comment by 318anushka** [comment]
okay, i figured.How does this look?
Let me know if any styling or position changes are required.

![Screenshot_20200311-205937__01](https://user-images.githubusercontent.com/45694892/76434970-6cf26000-63dc-11ea-83df-f2b3e185a1dc.jpg)

**Comment by sivaraam** [comment]
@318anushka There was a recent change (#3485) as a consequence of which the logo and trademark are shown in the bottom left corner too. Can you checkout the latest master (which contains the change) and apply your changes over them to see how they both play together?

**Comment by sivaraam** [comment]
BTW, the scale looks good. Can you also check that the scale bar doesn't take up a lot of space in a small screen device?

**Comment by 318anushka** [comment]
Yeah sure I'll check that.

**Comment by 318anushka** [comment]
> BTW, the scale looks good. Can you also check that the scale bar doesn't take up a lot of space in a small screen device?

i have changed orientation and scaling a bit because scalebar is positioned wrt top left corner so it was creating problem in smaller screen device (i tried on Nexus S 4.0 inch) . Also it was overlapping with the compass at bottom corner.Now it works fine 
![Screenshot_20200312-005149](https://user-images.githubusercontent.com/45694892/76456443-003b8d80-63fd-11ea-87c6-9b0db2655124.jpg)
<img width="342" alt="Screenshot 2020-03-12 at 12 58 40 AM" src="https://user-images.githubusercontent.com/45694892/76456454-03cf1480-63fd-11ea-8b83-b1f650e1580d.png">

**Comment by nicolas-raoul** [comment]
Looks good, thanks a lot Anushka :-)

**Comment by sivaraam** [comment]
@318anushka The scale looks perfect in the first screen shot. But the scale seems to be taking up considerable amount of space in the small screen device. The amount of place to access to access the map is already pretty less in the small screen device. So, even a little space matters there. Is there any way to improve this? For instance, in my device Google maps shows the scale only when I zoom in/out the map. Is it possible to do something like that?

**Comment by 318anushka** [comment]
So scaling is fine , I should just work on visibility?

**Comment by nicolas-raoul** [comment]
In the first screenshot, the font size of "750 m" is similar to the font size of "Place type".
In the second screenshot, the font size of "250 m" is much larger than the font size of "Place type".

Ideally, the font size should always be more or less similar to the font size of "Place type". Not sure what controls that.
Similarly, the width of the black/white bar is similar to the handle of the loop in the first screenshot, but about double in the second screenshot.

If there is an easy way to fix this, that would be great. If not, I guess it is good enough for now :-)

**Comment by 318anushka** [comment]
A fixed float value is passed as parameter for all font size. I'll check if something can be done.

**Comment by 318anushka** [comment]
Passed the default value (same as that of "place type") and this looks fine now.
Also about visibility , i tried to enable scaleBar visibility only when bottom sheet is dragged or state changed but looks like the method isn't called. Any fixes to that or is it fine for now?

<img width="309" alt="Screenshot 2020-03-12 at 10 57 02 PM" src="https://user-images.githubusercontent.com/45694892/76557632-efa11b00-64c1-11ea-818c-e5cd72ec919f.png">

**Comment by nicolas-raoul** [comment]
I would say it is fine.
Further enhancements can be filed as separate enhancement GitHub issues :-)

**Comment by sivaraam** [comment]
@318anushka I suppose this is a lot better too :)

**Comment by misaochan** [comment]
That looks fine to me @318anushka . Feel free to submit your PR for this. :)
