### ISSUE TITLE
Show compass in home nearby banner

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#2239]
Showing the nearest item is a great call to action.
But it only says like "200 meters", so the hardest thing next is to figure out in what direction to head.
I suggest showing an arrow that shows the direction.
Of course, it will not work great when the phone is held vertically.

**Comment by mumtazcem** [comment]
hello, I am working on it

**Comment by maskaravivek** [comment]
As of now showing directions/routes in the app is still debated in #2424. 

It might be better to show a directions icon clicking on which fires a map intent with the route. Also, I sometimes feel that we should have more CTA options in the card itself. Maybe the same set of options which are shown on tapping a nearby item in the list.

**Comment by nicolas-raoul** [comment]
@maskaravivek While directions are debated, I don't think the present enhancement is controversial?
![adb-screenshot](https://user-images.githubusercontent.com/99590/52924598-c40c3980-3370-11e9-8b03-66feb59c405c.png)

**Comment by ronanb80** [comment]
Is this issue finalized and not assigned?

**Comment by nicolas-raoul** [comment]
@mumtazcem Are you still working on this? Please inform us about your progress, or if you have abandoned the task then @ronanb80 will work on it. Thanks! :-)

**Comment by nicolas-raoul** [comment]
@ronanb80 If there is no news from @mumtazcem within 24 hours, the issue becomes assigned to you. Meanwhile how about you research how to extract mediawiki captions for #2337 ? :-)

**Comment by mumtazcem** [comment]
hello, I am deeply sorry that I could not update you guys.. Due to homeworks and midterms for the last two weeks I could not check my emails.

However, I was able to implement 'Bearing' which is explained here -> [https://www.movable-type.co.uk/scripts/latlong.html](url) successfully. Using this method I am able to calculate the bearing between given two points.

By checking the bearing value, cardinal points with precision 2 would be printed to the view just as @nicolas-raoul expected and can be observed below. Direction would be printed as string for now, I can update it with compass or with simple arrow.

![compass](https://user-images.githubusercontent.com/17280538/54061852-cc3ef280-4213-11e9-8baa-ab0d067a37a7.png)

**Comment by nicolas-raoul** [comment]
Thanks for sharing your progress!
Yes, a compass (or simple arrow) is needed, because when walking in the street it can be difficult to tell where North-East is, and on the opposite it is easy to go in the direction of an arrow.
Thanks!

**Comment by mumtazcem** [comment]
New update, I added compass icon. Icon would be rotated with calculated bearing value. Below you can observe that icon is rotated 73 degrees exactly.

![compass_icon](https://user-images.githubusercontent.com/17280538/54082147-23cb8400-4322-11e9-95d8-db0b0b25be76.png)

This is the map as well.

![compass_nearby](https://user-images.githubusercontent.com/17280538/54082149-2c23bf00-4322-11e9-9b79-cd7be7c695a1.png)

**Comment by mumtazcem** [comment]
Here I added some more examples. If the design and the icon are acceptable for you guys @nicolas-raoul , I can make a pull request for my changes.

**1. First example**
![Screenshot_1552245520](https://user-images.githubusercontent.com/17280538/54091552-58772400-4392-11e9-9f53-33f313941a25.png)


![Screenshot_1552245613](https://user-images.githubusercontent.com/17280538/54091561-75135c00-4392-11e9-8d68-2fc79dea814d.png)




**2. Second example**
![Screenshot_1552246796](https://user-images.githubusercontent.com/17280538/54091569-82c8e180-4392-11e9-9c1d-0cac3729f6f9.png)


![Screenshot_1552250277](https://user-images.githubusercontent.com/17280538/54091570-852b3b80-4392-11e9-98ee-7009c05ca19c.png)

**Comment by nicolas-raoul** [comment]
@mumtazcem 
Great start!

If you turn your phone 30 degrees to the right, does the compass turn 30 degrees to the left to compensate?
If it does not, you should use Android's internal compass and include that in the calculation.

The idea is that if you hold your phone horizontally, the arrow points in the direction in which you must walk. So you can start walking even if you have no idea where the north is.

**Comment by mumtazcem** [comment]
I actually never thought about that :). I assumed that this compass would help user to find out the nearest location in Nearby section. Thank you for your feedback, I will update you as soon as possible.

**Comment by nicolas-raoul** [comment]
Thanks, and sorry for my approximate explanation :-)

**Comment by nicolas-raoul** [comment]
This *might* help:
https://stackoverflow.com/questions/8315913/how-to-get-direction-in-android-such-as-north-west

**Comment by nicolas-raoul** [comment]
Also:
https://bitbucket.org/alekseyt/compass/src/41d8dc3b1d40f8e5d79920aaffa8ca7c330850cd/src/com/sgr_b2/compass/navigation/Monitor.java#lines-214

**Comment by nicolas-raoul** [comment]
This is maybe the closest code to what we are trying to achieve:
https://github.com/metinkale38/prayer-times-android/blob/bfc080918d68e3b0d2bda0ba0ab98b96f614e399/features/compass/src/main/java/com/metinkale/prayer/compass/_2D/Frag2D.java#L69
It displays an arrow that shows the direction of the Kaaba, Muslims can just look at the arrow and pray in the right direction. We would just have to replace the Kaaba's coordinates with the item's coordinates.

**Comment by mumtazcem** [comment]
Not unfortunately all phones (mine samsung galaxy J5) have a magnetic sensor. I finally borrowed one for this project that is why I could not update you guys... 

However, since having a magnetic sensor is possibility, should I alert the user if they have a magnetic sensor or not? If a phone does not have a magnetic sensor, then the compass would work just as I described [above](https://github.com/commons-app/apps-android-commons/issues/2239#issuecomment-471348660) in current situation.

**Comment by nicolas-raoul** [comment]
If the phone does not have any way to find the direction, then please just hide the arrow.
Thanks! :-)

**Comment by LuGO0** [comment]
can I work on this issue is it still assigned??

**Comment by nicolas-raoul** [comment]
@mumtazcem Are you still working on this? Feel free to commit or even post here any source code you might have. Thanks! :-)

**Comment by LuGO0** [comment]
Can I take it up now?!

**Comment by 318anushka** [comment]
@nicolas-raoul  if nobody is working on this issue i would like to take it.

**Comment by nicolas-raoul** [comment]
Hi @LuGO0 and @318anushka,
Sorry for the late reply!
@LuGO0: OK feel free to work on it, as mumtazcem seem to not be around anymore. Good luck, let us know about your progress :-)

**Comment by XxBrezxX** [comment]
Hi, is this issue taken? If not I would be happy to try a solution!, btw, if u could give me more details, ill be glad :))

**Comment by nicolas-raoul** [comment]
@XxBrezxX Please focus on one issue at a time :-) Thanks for your enthusiasm!

**Comment by ShashwatKedia** [comment]
@nicolas-raoul I would like to work on this issue

**Comment by nicolas-raoul** [comment]
@ShashwatKedia It is yours, thanks! :-)

**Comment by ShashwatKedia** [comment]
@nicolas-raoul I've implemented the required changes. Kindly review the PR :-)
