### ISSUE TITLE
Delete specific search

### ISSUE THREAD

**Issue by athatsakk** [commons-app/apps-android-commons#2241]
**Summary:** 

When i try to delete my history , i have to delete all searches. I would like to be able to delete/keep a specific search. 

**Steps to reproduce:** 

Go to 'explore' 
Search something
Check history
Try to delete only 1 search ( not all )

**Comment by sp2710** [comment]
I would like to work on this.

**Comment by noahwalugembe** [comment]
@sp2710  like to work on this
