### ISSUE TITLE
Zoom in/out button

### ISSUE THREAD

**Issue by athatsakk** [commons-app/apps-android-commons#2244]
**Summary:** 

It would be useful to have two buttons ( '+' , '-' ) in order to zoom in/out when being in nearby map

**Comment by neslihanturan** [comment]
Agreed:)

**Comment by sp2710** [comment]
I am working on this

**Comment by nicolas-raoul** [comment]
This is not needed nowadays, the last devices without multitouch were last sold like 8 years ago (if I am wrong please correct me).
For instance the Google Maps app does not have + - buttons (though maybe it shows them on some specific hardware models?).
I close the issue based on these considerations, but if I was mistaken please do reopen, thanks! :-)

**Comment by misaochan** [comment]
I agree with this. Adding the +- buttons would unnecessarily complicate the UI for no gain IMO. Sorry to waste your time @sp2710 . :(
