### ISSUE TITLE
Pressing 'back' goes to main page

### ISSUE THREAD

**Issue by athatsakk** [commons-app/apps-android-commons#2245]
**Summary:** 

When pressing 'back' button in ''nearest places'' after pressing the button on right top, it goes straight to the main page. I should expect that it would just close that tab , and continue searching on map.

**Steps to reproduce:** 

At main page, show menu and choose 'Nearest Places' ( or whatever, my app is in Greek )
When map shows up , press the button on top right
A list with places appears
Then press back button  

**Screen-shots:** 

![screenshot_5](https://user-images.githubusercontent.com/32622637/50514021-43356d80-0aa4-11e9-8ddc-878dd4c38cb8.jpg)
![screenshot_3](https://user-images.githubusercontent.com/32622637/50514024-47618b00-0aa4-11e9-8c52-ce36a3431160.jpg)
![screenshot_4](https://user-images.githubusercontent.com/32622637/50514029-4a5c7b80-0aa4-11e9-96e6-205ba8f95aff.jpg)

**Comment by Divyanshu2132** [comment]
@athatsakk  are you working on this issue or should I take up this issue

**Comment by athatsakk** [comment]
you can go for it

**Comment by vanshikaarora** [comment]
Is anyone working on this issue or shall i take up?

**Comment by nicolas-raoul** [comment]
@vanshikaarora Divyanshu2132 has already submitted a pull request about this: https://github.com/commons-app/apps-android-commons/pull/2251 It is being processed.

**Comment by vanshikaarora** [comment]
Hey!! Is anyone working on this Issue?
I have submitted a PR for this here in #2300

**Comment by vanshikaarora** [comment]
Hey!! Is anyone working on this Issue?
Few days back, I have submitted a PR for this here in #2300

**Comment by shabrikaruna** [comment]
Hey, guys, I fixed this issue!

**Comment by vanshikaarora** [comment]
Hey if no-one is working on this issue then I have a PR submitted here #2301. Kindly review :)
