### ISSUE TITLE
Make version number easily copyable

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#2250]
Maybe with a button like the repo clone button on GitHub.com?
Or at least make the label selectable.

**Comment by maskaravivek** [comment]
Maybe we can simply copy the version number by tapping on it. I see no harm in copying the version number accidentally. :)

**Comment by sivaraam** [comment]
> I see no harm in copying the version number accidentally. 

There is. You **replace the contents** of the clipboard of the user. I never like something that unintentionally replaces the contents of my clipboard as I sometimes have data which I would like to use later or which is not yet stored somewhere.

**Comment by maskaravivek** [comment]
You have a valid concern @sivaraam! Maybe 
- we can have a copy icon beside the version number. 
- we can copy on multiple taps instead of one
- we can make it selectable as @nicolas-raoul suggested

**Comment by sivaraam** [comment]
The first and last are nice but I'm not sure if the second one is necessary. It just makes the unintended surprise less likely. IMO, we should avoid surprises completely. We could do that by just adding a copy button or making it selectable. Even just one of them would satisfy the need.

**Comment by maskaravivek** [comment]
I was simply suggesting multiple ways to do it. Obviously, we won't be adding all the ways to copy a version number! Once there is a consensus about how to go about it, a beginner can pick this up. :)

**Comment by sivaraam** [comment]
Seems I misunderstand part of it, sorry. Anyways my point is *don't introduce unpleasent surprises*. So, your option 1 and 3 would be fine :)

**Comment by misaochan** [comment]
I'm good with either making it selectable or having a copy button. :)

**Comment by sup95** [comment]
Is this for the version number on the About screen? I would like to work on this! :)

**Comment by nicolas-raoul** [comment]
@sup95 Yes exactly!
The consensus seems to be that solutions 1 or 3 of https://github.com/commons-app/apps-android-commons/issues/2250#issuecomment-450958591 are good, so feel free to implement the one you prefer, the issue is yours :-)

**Comment by domdomegg** [comment]
Reopened, see #2290

**Comment by domdomegg** [comment]
Fixed again in #2347
