### ISSUE TITLE
Retry button too close to scrollbar

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#2255]
2.9.0 recent alphas

Tapping the retry button is very difficult as it is dangerously close to the "X" button, and most taps when I try are taken by the scrollbar.

**Comment by sup95** [comment]
@nicolas-raoul I would like to take this up! I am new to the application, could you help me figure out which retry button, or on which screen are we looking at? Thanks!

**Comment by maskaravivek** [comment]
Feel free to take this up @sup95. :)

**Comment by nicolas-raoul** [comment]
@sup95 

It is on the home activity, which shows your contributions.
You first have to make an upload fail, for instance by cutting network during the upload.

![adb-screenshot](https://user-images.githubusercontent.com/99590/50763291-b9ab4a00-12b2-11e9-940f-c15895cbef08.png)

**Comment by abhishekd08** [comment]
Do you mind if I work on this issue ? @nicolas-raoul @vanshikaarora

**Comment by vanshikaarora** [comment]
@abhishekd08 actually since noone has replied on this issue since 21 days. So I was starting to work upon this issue.

**Comment by abhishekd08** [comment]
No problem. Go ahead. @vanshikaarora

**Comment by vanshikaarora** [comment]
Thanks:) @abhishekd08 
@sup95 Are you still working on this?

**Comment by sashrikakaur** [comment]
@vanshikaarora Do you mind if I work on this issue?

**Comment by sup95** [comment]
@vanshikaarora I am not working on this and will not be able to get to it, anybody could take it up:)
