### ISSUE TITLE
cannot upload

### ISSUE THREAD

**Issue by cascafico** [commons-app/apps-android-commons#2263]
Commons 2.9.0
Huawei MYA-L11
Android 6.0

Progress bar ok and upload seems completed, but listed as "non riuscito" (failed).

Also cannot remove failed uploads from app main page.
Besides, it is not clear why "nomimate for deletion" is active for an image with failed upload status.

**Comment by nicolas-raoul** [comment]
Was the image actually uploaded?
Did you click the "retry" button?
Sometimes uploads fail, that is expected.

About your last note, I created this issue: #2311

**Comment by domdomegg** [comment]
Closing stale issue, please reopen if new information becomes available. What should be done with failed images now in #2311
