### ISSUE TITLE
Log file is not automatically attached for 'Send logs'

### ISSUE THREAD

**Issue by sivaraam** [commons-app/apps-android-commons#2265]
**Summary:** 
When trying to send the crash reports using the 'Send logs' feature, the logs file is expected to be attached with the mail that opens up for composition after clicking in 'Send logs'. It only seems to work when using Gmail as the default email client to send emails. For other email clients the file is not getting attached.

**Steps to reproduce:** 
0. Choose any email client other than Gmail as default email client (if required). E.g. K-9 mail
1. Go to the 'Settings' page
2. Tap in 'Send logs'
3. Choose any email client other than Gmail (if required) to complete the action.

**Expected**
The logs file gets attached.

**Actual**
The logs doesn't get attached. It only gets attached when using Gmail as the email client.

**Device and Android version:** 
Samsung Galaxy J1 ace running Android 5.1.1
 
**Commons app version:** 
2.9.0

**Screen-shots:** 
1. Other email client: K-9 mail
    ![signal-2019-01-03-005347](https://user-images.githubusercontent.com/12448084/50608580-f3e8a600-0ec4-11e9-9684-211d3ff6e723.jpg)

2. Gmail
    ![signal-2019-01-03-005117](https://user-images.githubusercontent.com/12448084/50608403-7cb31200-0ec4-11e9-818b-cf735e84c473.jpg)

**Would you like to work on the issue?**
Not for now.

**Comment by maskaravivek** [comment]
I am working on this.
