### ISSUE TITLE
Tapping map doesn't close details tab in ''nearby'' 

### ISSUE THREAD

**Issue by athatsakk** [commons-app/apps-android-commons#2272]
**Summary:** 

While exploring the map in 'neaby' , if you click a pin and open the details down there , to close that tab , you have to click again on it. It would be useful to click anywhere on map and also this tab should be closed.

**Steps to reproduce:** 

Go to 'nearby'
Click on a pin
Open the details tab ( this one down )
Tap anywhere on the map

 
**Commons app version:** 

2.9

**Screen-shots:** 

![screenshot_10](https://user-images.githubusercontent.com/32622637/50701701-435edb80-1057-11e9-9381-7ebebdb429c3.jpg)

**Comment by vanshikaarora** [comment]
Hey I can work on this issue

**Comment by Tanvi-Goyal** [comment]
Hi i would like to work on this issue

**Comment by neslihanturan** [comment]
This issue is no more around.
