### ISSUE TITLE
Using Play Store alpha, version number still shows 2.9.0

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#2279]
**Steps to reproduce:** 

1. Sign up for the alpha, install from Play Store
2. Go to Android settings > Apps > Commons, see the version, now it is 2.9.0.161
3. Go to the Commons app's About
4. It shows just `2.9.0` instead of something longer as seen at https://github.com/commons-app/apps-android-commons/pull/2273#issuecomment-451664712

**Device and Android version:** 

Android 7.1.2

**Screen-shots:** 

![adb-screenshot](https://user-images.githubusercontent.com/99590/50806728-3f72d800-133b-11e9-9e3f-11b655772a6b.png)

**Comment by maskaravivek** [comment]
As of now only debug builds show the branch name and  commit SHA appended to the version number.

**Comment by nicolas-raoul** [comment]
Fixed now, thanks! :-D

**Comment by jidanni** [comment]
Alpha? Never heard of it. No search can find it. Certainly you mean the... #3976.
