### ISSUE TITLE
Retry does not link from Wikidata

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#2280]
**Steps to reproduce:** 

1. From Nearby, upload a picture (I only tried from gallery)
2. Make the upload fail (I actually had a network connectivity problem)
3. Close the app (not sure whether necessary)
4. Press the retry button
5. Image gets uploaded
6. Problem: The Wikidata item (which I used in Nearby) does not link to the image.

Example: https://commons.wikimedia.org/wiki/File:Ko%C5%ABry%C5%ABji.JPG

**Commons app version:** 

2.9.0.163

**Comment by maskaravivek** [comment]
Right now, the `Contributions` table doesn't store the associated Wikidata entity ID. Will make this change so that even on retry, the Wikidata edit is made.
