### ISSUE TITLE
Discuss the new camera permission required by the app

### ISSUE THREAD

**Issue by maskaravivek** [commons-app/apps-android-commons#2283]
**Summary:** 

> The image picker library that has been added in this PR seems to have one unintended consequence which seems to have been overlooked (as I don't see it discussed here). The app now asks for extra permission while upgrading. It asks for permission to access the camera which seems unnecessary to me as I don't see where it's used. This might go unnoticed for Android versions which have runtime permissions (I think Android 6 and later) but it's noticeable when upgrading the app in devices running an Android version < 6
> 
> Is there a way to prevent the extra permission from being asked in some way?

As pointed out by @sivaraam, after #2278 the app requires an extra permission ie CAMERA. 

There are 2 things to be addressed: 

- is it fine to request camera permission
- API > 23 isn't prompting for runtime permissions, which needs to be fixed. Will submit a PR soon. 

Personally, I would be fine with granting permissions to a photo uploader app requesting for Camera permission. Going forward, having control of the camera will have several advantages.

**Comment by sivaraam** [comment]
Personally I would be fine with granting the permission if there is a valid reason to it. For example, I don't mind my browser requesting the camera permission.

I just find it disturbing that the Commons app now asks for permission which it does not use. If there is a way to rempveot we should.

> Going forward, having control of the camera will have several advantages.

I personally do not like apps that ask for permission ahead of time with a reason that "it might be useful in future" (I've seen many of them). It's better to ask for it when the time comes as we would have a better reason to request for that permission. Anyway this my opinion.
