### ISSUE TITLE
I am underachieving

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#2284]
For my user, `Images used` and `Thanks received` have become zero, even though they were not before.

Many of my images are still used on Wikipedia, I just checked :-)

![adb-screenshot](https://user-images.githubusercontent.com/99590/51009666-5102ec80-1594-11e9-887b-0486165903c3.png)

**Comment by maskaravivek** [comment]
@nicolas-raoul This could be because of the changes in APIs that I did. I will take a look at the queries and fix it.

**Comment by nicolas-raoul** [comment]
I confirm it is fixed, thanks! :-)
