### ISSUE TITLE
Fresh clone fails build in latest Android studio

### ISSUE THREAD

**Issue by srinivas1729** [commons-app/apps-android-commons#2285]
**Summary:** 

Fresh clone fails build in latest Android Studio/SDK

**Steps to reproduce:** 

How can we reproduce the issue? 
- Fork project and go through quick start guide
- Fresh Android Studio install: I have 3.2.1. It setup with SDK 28
- Setup project via 'import from version control'

What did you expect the app to do, and what did you see instead?

Expected:
- Project syncs and builds
Actual:
- Sync/build failed. Checked Android Studio and saw references to android-27. Installed that in Sdk manager. Still had issues. Logs showed that I needed buildtools 27.0.3. Installed those specific tools as described in: https://stackoverflow.com/questions/47721952/how-to-solve-failed-to-find-build-tools-revision-26-0-2

This is more an Android Studio project setup issue. I noticed that root gradle.properties contains:
buildToolsVersion=27.0.3

**Comment by vanshikaarora** [comment]
Hey!! I also noticed this same issue. But I made certain changes in my gradle files and that worked for me shall I send a PR of my code here

**Comment by maskaravivek** [comment]
Am happy updating the build tool, compile SDK and Gradle tools to the latest version.

**Comment by vanshikaarora** [comment]
Thanks for approving the PR :)
