### ISSUE TITLE
Image Picker lets only local images to be picked

### ISSUE THREAD

**Issue by maskaravivek** [commons-app/apps-android-commons#2286]
**Summary:** 

#2278 introduced a library for picking images. Unfortunately, the library or other libraries that are available, let you choose only local images. We cannot access Google Photos, Drive or other places for photos. 

The library had 2 advantages: 
1) lets you limit the number of images that can be picked for upload
2) removes all boilerplate and potential bugs related to picking images from gallery and images. 

Not having Google photos or Drive is not an option so definitely, some action needs to be taken. 

I was discussing the same with @ashishkumar468 and finally reached some consensus about using another library that at least fixes (2). We still have our reservations as it won't address (1), but the positive side is that it would bring consistency around the handling of content URIs. 

We need more opinions before we make any changes and possible suggestions if anyone is familiar with it. 

The other option is to not use any library and handle the intents on our own. Even this is feasible and would just need some investment to ensure that issues like #2033 are eliminated completely. 

cc @nicolas-raoul @domdomegg @misaochan @neslihanturan

**Comment by misaochan** [comment]
Just read this after commenting at #2309 , sorry about that.

IMO, supporting Google Photos and other galleries is much more important than enforcing the limit on the number of images that can be uploaded simultaneously. The limit is a "nice to have", but with our current multiple upload structure (where title/desc needs to be input separately for every image), it is not essential as users cannot easily dump their entire camera roll into the app. 

For the sake of simplicity, I would be OK with removing the limit (just like how it was when multiple uploads was first implemented), if it means that external galleries can be supported again. Lots of users use external galleries (I personally do, and many users have reported doing so too), so the lack of support would be a dealbreaker IMO.

However, solving #2033 is still essential.
