### ISSUE TITLE
After canceling a sharing, application goes back to the search menu

### ISSUE THREAD

**Issue by lcartel** [commons-app/apps-android-commons#2296]
**Summary:** 

On pressing back button after clicking on sharing button, application goes back to the search activity not to the image activity.

**Steps to reproduce:** 
->Menu 
->Explore
->Search something
->Click on an image
->Click on share button
->Press back button or scroll down to cancel sharing

**Device and Android version:** 

Pixel 2 XL emulator (Android 8.0) and Motorola G4 (Android 7.0)
 
**Commons app version:** 

Latest master.

**Would you like to work on the issue?**

Yes

**Comment by nicolas-raoul** [comment]
Thanks for being willing to work on it, looking forward to your pull request :-)

**Comment by lcenfeux** [comment]
I'm new here so I'll need more time to understand the architecture of the app, but i'm working on it

**Comment by jashpreet** [comment]
Hey , Can i work on this issue ?

**Comment by nicolas-raoul** [comment]
@lcartel Are you still working on this? Have you made any progress? :-)

**Comment by lcartel** [comment]
I stoped working on this, I didn’t find the time to finish it. You can reasign the task if you want.

**Comment by nicolas-raoul** [comment]
@lcartel Understood! If you have made some modifications do not hesitate to push them to a remote branch :-)

@jashpreet It is yours! :-) Please let us know about your progress from time to time.

**Comment by jashpreet** [comment]
I am having trouble going back to the same fragment instance , Can you please guide me on the same ?

**Comment by Prince-kushwaha** [comment]
I want to solve this issue

**Comment by Prince-kushwaha** [comment]
I solved this issue can i make an PR

**Comment by neslihanturan** [comment]
Currently one of the issues (#4063) is closed and the other is still valid. Since this issue is trying to solve "both" of them I don't know what to do with this PR. This is why ideally we prefer single PR for one issue.

**Comment by ArmanNavodia** [comment]
@nicolas-raoul I am able to reproduce this issue. So I want to work on this can you please assign me this issue?

**Comment by nicolas-raoul** [comment]
@ArmanNavodia It is yours, thanks! The closed pull requests above _may_ be useful. Please let us know about your progree every few days.
