### ISSUE TITLE
Adding a feature to dismiss already read notifications

### ISSUE THREAD

**Issue by vanshikaarora** [commons-app/apps-android-commons#2298]
**Shall we add a feature to dismiss your old notifications in the NotificationsActivity?** 

- That may be added via a dismiss button or by swiping the item from notification list
-  In case of zero notification we can display "No recent notification"
- Also in the notification icon( that appears in the toolbar in the main activity) that currently shows a red circle in case of notification  we can add a text view to show the number of unread notifications.

Would you like to work on this issue?
Yes

**Comment by nicolas-raoul** [comment]
Sounds useful for people who use both the website and the app, and have already read all recent notifications on the website :-)

**Comment by vanshikaarora** [comment]
@nicolas-raoul If this sounds agreeable then I'll start working on this.

**Comment by maskaravivek** [comment]
@vanshikaarora Thanks for picking this up. Nice that we are finally implementing "ability to mark a notification as read". 

> That may be added via a dismiss button or by swiping the item from notification list

1.  The Notifications API has a filter that returns only unread notifications. So we should ideally change the API query to fetch only unread notifications. This should be the new query: 

https://commons.wikimedia.org/wiki/Special:ApiSandbox#action=query&format=xml&meta=notifications&notwikis=wikidatawiki%7Ccommonswiki%7Cenwiki&notfilter=!read&notformat=model

Note: all parameters other than `notfilter=!read` is already present. So you need to add this parameter to the API call. 

2. We can have "swipe to dismiss" and also "clicking on notification to mark it read". 

MediaWiki offers another API to mark any notification as read. We should be consuming this API to have consistency. 

https://www.mediawiki.org/wiki/Notifications/API

> Also in the notification icon( that appears in the toolbar in the main activity) that currently shows a red circle in case of notification we can add a text view to show the number of unread notifications.

Right now we maintain `last_read_notification_date` in `SharedPreferences` and use this time to determine whether the red icon should be shown or not. 

Now that we are fetching just unread notifications and marking them read on clicking/dismissing, we should rely on the number of notifications returned by the API. If it returns no notifications, then the icon should not be shown.

**Comment by vanshikaarora** [comment]
@maskaravivek @nicolas-raoul Thanks for approving the Issue suggested.

@maskaravivek I have started working upon this.

These are a few changes that I have already made:

- I have updated the API query in `ApacheHttpClientMediaWikiApi`
- Modified the notification item in menu, to have a text above the red circle(This text will show the number of unread notifications)
- Modified the MainActivity to show the include the updated menu item instead of the currently used drawable(image with a  dot). 

I'll be performing the other tasks as well, and will send you a PR soon.

**Comment by maskaravivek** [comment]
Good work @vanshikaarora! Thanks for sharing the progress. :)

**Comment by vanshikaarora** [comment]
Hey @maskaravivek I have made the following changes:

- Added to a slide feature to dismiss the notification
- Display a toast message on dismiss
- Show appropriate message in case of no notification
- Added markUnread function to `MediaWikiApi` class and correspondingly to `ApacheHttpClientMediaWikiApi` class.

Here in the link https://www.mediawiki.org/wiki/Notifications/API
The api accepts a token for notification wherein in the notification class I don't see any such parameter. 
So is this token asking for `link` in `Notification` or shall I add update the `Notification`  class to generate a new token.

**Comment by maskaravivek** [comment]
Try using the API sandbox on the documentation page and see the response that you receive. Then you can traverse the XML nodes accordingly. 

Let me know if you run into any trouble.

**Comment by vanshikaarora** [comment]
Hey @maskaravivek  there is some problem with this response
In accordance with the xml  i tried the path. These are the response
![screenshot from 2019-01-17 16-29-06](https://user-images.githubusercontent.com/34261945/51314108-325d9380-1a75-11e9-884c-30a348d5647c.png)
while it has no node named "query"
![screenshot from 2019-01-17 16-27-58](https://user-images.githubusercontent.com/34261945/51314157-46a19080-1a75-11e9-9156-5214a4a7711d.png)
Also on further parsing I got some error:
![screenshot from 2019-01-17 16-25-14](https://user-images.githubusercontent.com/34261945/51314295-63d65f00-1a75-11e9-822e-8f47566a6756.png)

Is there a problem with my CentralAuthToken? Does it works fine with you?

**Comment by maskaravivek** [comment]
Can you share your WIP diff so that i can take a look

**Comment by maskaravivek** [comment]
@vanshikaarora It seems you are not making the API call correctly. 

- `action` should be `echomarkread`
- You also need to pass `list` of notification IDs that you are marking as read. In our case, we will be marking 1 notification as read at a time. So you need to pass `notificationID`: 

```
.param("list", "<notifcationID>")
```

Right now, our `Notification` object doesn't contain the ID. 
- You need to add the attribute to it. 
- Also in `NotificationUtils:getNotificationFromApiResult` you need to set the value of this ID so that it can be consumed by the other API.

**Comment by vanshikaarora** [comment]
@maskaravivek I have followed the steps given.
Now what can be the notification Id. Is it a random token?

**Comment by maskaravivek** [comment]
@vanshikaarora Check the notification response that we get. We need to use this `id` attribute. 

```
<?xml version="1.0"?>
<api batchcomplete="">
  <query>
    <notifications>
      <list>
        <notification wiki="enwiki" id="133343595" type="thank-you-edit" category="system" section="message" read="20190117052202">
          <timestamp utciso8601="2018-04-04T13:52:01Z" utcunix="1522849921" unix="1522849921" utcmw="20180404135201" mw="20180404135201" date="4 April" />
          <title full="Parsnip" namespace="" namespace-key="0" text="Parsnip" />
          <agent id="20569479" name="Maskaravivek" />
          <targetpages />
        </notification>
        <notification wiki="enwiki" id="135742425" type="login-fail-new" category="login-fail" section="alert" read="20190117052202">
          <timestamp utciso8601="2018-05-03T12:42:57Z" utcunix="1525351377" unix="1525351377" utcmw="20180503124257" mw="20180503124257" date="3 May" />
          <agent id="20569479" name="Maskaravivek" />
          <targetpages />
        </notification>
        <notification wiki="enwiki" id="135955417" type="login-fail-new" category="login-fail" section="alert" read="20190117052202">
          <timestamp utciso8601="2018-05-04T12:00:34Z" utcunix="1525435234" unix="1525435234" utcmw="20180504120034" mw="20180504120034" date="4 May" />
          <agent id="20569479" name="Maskaravivek" />
          <targetpages />
        </notification>
      </list>
    </notifications>
  </query>
</api>
```

**Comment by maskaravivek** [comment]
Let me know if you are getting stuck in getting the `id`. I will raise a PR for it and then you can rebase your branch on top of it.

**Comment by vanshikaarora** [comment]
> Also in NotificationUtils:getNotificationFromApiResult you need to set the value of this ID so that it can be consumed by the other API.
@maskaravivek I have done all the rest. But here in NotificationUtils:getNotificationFromApiResult when returning a notification object I need to pass the notification Id
How do I get the notification Id here. Shall i use some other notification info as notification id or generate a random token here?

**Comment by maskaravivek** [comment]
Can you submit a PR with the rest of the changes. I will incorporate the `notificationID` changes and submit it as a patch on your PR.

**Comment by vanshikaarora** [comment]
@maskaravivek Yes but the PR will have error at the function `NotificationUtils:getNotificationFromApiResult` Will thet be fine?

**Comment by vanshikaarora** [comment]
@maskaravivek I have send the PR with ui and other implementations except NotificationId.
Kindly take some time also to review the code :)
