### ISSUE TITLE
App should ask for confirmation before exiting

### ISSUE THREAD

**Issue by ShridharGoel** [commons-app/apps-android-commons#2299]
**Summary:** 

According to the current behaviour, the app exits directly when back button is pressed on Home.  
 
Instead, we can add a feature of confirming before closing the app. A dialog would pop up asking the user whether they are sure that they want to exit the app.

**Would you like to work on the issue?**

Yes

**Comment by nikhilagrawal2000** [comment]
can I work on this issue?

**Comment by ShridharGoel** [comment]
@nikhilagrawal2000 I'll be working on it. Meanwhile, you can look for other issues.

**Comment by nicolas-raoul** [comment]
No offense, but I don't think this feature would be an enhancement.
It would make the user experience worse, for no added benefit.
The home activity has nothing to save and no important process going on that might warrant such a confirmation dialog.
See https://ux.stackexchange.com/questions/117159/is-it-a-good-practice-to-ask-before-exiting-an-application-with-nothing-to-save
Feel free to reopen and explain why this feature is needed.
Cheers! :-)
