### ISSUE TITLE
code optimizations

### ISSUE THREAD

**Issue by nikhilagrawal2000** [commons-app/apps-android-commons#2302]
**Summary:** 

Some fragments code needed to be optimized.

**Would you like to work on the issue?**

Yes

**Comment by domdomegg** [comment]
Can you provide some more clarity into what exactly you mean by this? Is there a particular set of fragments which are poorly optimized? If so, which ones and why?

**Comment by domdomegg** [comment]
Closing as I don't have more information about what you mean - please comment here or open a new issue if you have more info.
