### ISSUE TITLE
Contribution both failed and successful

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#2310]
I have a picture that I contributed via the app normally, as a single picture (not multi-upload), and that appears as two thumbnails in the home gallery: one failed, one succeeded.

I have no idea how to reproduce. It is the first time it ever happens to me.

Pressing the cancel button does not make it disappear, so it seems that I will have that fake failed upload stuck at the top until I reset the app.

**System logs:**
I don't have upload logs but here is what appears when I push the "Cancel" X button:
```
ContributionsListAdapter: Skipping deletion for non-failed contrib fr.free.nrw.commons.contributions.Contribution@de4851f
```

**Device and Android version:** 

Android 7.1.2
 
**Commons app version:** 

2.9.0.171

**Screen-shots:** 

![screenshot_20190116-000354](https://user-images.githubusercontent.com/99590/51291055-2cea5400-1a49-11e9-8048-69e4d39c94c7.png)

**Comment by albendz** [comment]
The only time I've seen this is when I've uploaded something twice and one failed where the other succeeded. Is it possible that the upload succeeded but before the response is received by the app, a disconnect occurs? Of course, disconnects are possible anytime.

**Comment by ashishkumar468** [comment]
Contributions have been refactored, should not happen on latest commits. Closing this issue, feel free to re-open if someone manages to reproduce this again.
