### ISSUE TITLE
Number of contributions does not update until the app is restarted

### ISSUE THREAD

**Issue by ShridharGoel** [commons-app/apps-android-commons#2324]
**Summary:** 

After uploading an image, the number of contributions (the number in the bracket on the "Contributions" tab) does not increase. It increases only after the app is reopened. It doesn't update even after switching to and back from some other fragment.

**Steps to reproduce:** 

1. Upload an image.
2. Notice that the number of contributions does not increase.

**Device and Android version:** 

Android version 7.1.2 (API 25)

**Would you like to work on the issue?**

Yes

**Comment by albendz** [comment]
@ShridharGoel Are you currently working on this?

**Comment by ShridharGoel** [comment]
No

**Comment by madhurgupta10** [comment]
@albendz can I start working on it?

**Comment by nicolas-raoul** [comment]
@madhurgupta10 Yes it is yours :-)

**Comment by madhurgupta10** [comment]
@nicolas-raoul I am unable to figure out why `if (!ConfigUtils.isBetaFlavour()) {
            setUploadCount();
 }`
is added in `onCreateView` in `ContributionsFragment.java`
