### ISSUE TITLE
I would like to contribute to this Project.

### ISSUE THREAD

**Issue by ShumailAhmed123** [commons-app/apps-android-commons#2327]
Hi,

My name is Shumail Ahmed and I am a Computer Science student. I am in the last year of graduation. I am writing this because I would like to contribute to this project. In university, I am studying about the "Open Source" software.
My teacher has given me a task to contribute to the GitHub in any project, which relates to my interest and according to my level of skills.
I found this project and I think I will be able to contribute to this project with some online research and with your little help.

Thanks
Shumail Ahmed

**Comment by maskaravivek** [comment]
Welcome to the project @ShumailAhmed123! Feel free to check out our wiki to get started with contributions. :)

https://github.com/commons-app/apps-android-commons/wiki/Volunteers-welcome%21

**Comment by albendz** [comment]
Thanks for the interest @ShumailAhmed123 . Please take a look at the contrition documentation @maskaravivek linked to you. I will be closing this issue.
