### ISSUE TITLE
FBMD in picture metadata = Probable copyright violation

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#2328]
Once #97 is implemented, we could refine it further by checking for FBMD.

It is apparently a field that Facebook puts in the metadata of images shown on its website.

Images downloaded from Facebook are most often not created by the user.

References:
- https://commons.wikimedia.org/wiki/Commons:Deletion_requests/File:Taungoke.jpg
- https://www.hackerfactor.com/blog/index.php?/archives/726-Facebook-Tracking.html

**Comment by vanshikaarora** [comment]
>Images downloaded from Facebook are most often not created by the user.

@nicolas-raoul so if the user downloads an image on facebook and tries to upload it on commons are we going to display them an error/Toast message that the image cannot be uploaded?

**Comment by nicolas-raoul** [comment]
@vanshikaarora Yes :-)
Or maybe just display a warning such as "`Please only upload pictures that you have taken by yourself. Don't upload pictures that you have found on other people's Facebook accounts.`", and let the user decide whether they really want to upload or not.

There is already a similar thing for black pictures. Please try: 1) Take a picture in the dark, totally black 2) Try to upload it 3) See the warning 4) Implement the same for FBMD :-)

**Comment by vanshikaarora** [comment]
@nicolas-raoul In [this post](https://www.hackerfactor.com/blog/index.php?/archives/726-Facebook-Tracking.html) the metadata decode dates back to 2014-11-13. Does Facebook follows the same format even after years?

**Comment by nicolas-raoul** [comment]
Good question! Not sure, that's something to check indeed. It might have changed or even disappeared.

**Comment by vanshikaarora** [comment]
Well It will take a lot of research. Also I have found some answers https://www.quora.com/How-do-you-find-the-EXIF-data-of-a-photo-uploaded-to-a-Facebook-album

Also using this link I cannot get EXIF of any image uploaded to facebook

**Comment by nicolas-raoul** [comment]
Here is the metadata of a picture I posted to Facebook this week:
http://fotoforensics.com/analysis.php?id=ae7ca2d48579b372aa393b64a539b0746eb00f6a.463379
As you can see it contains `FBMD01000a9f0d000010b40000918601006fa5010005d00100612f0200e79f03006cc00300f5eb0300bd22040013120700`.
This data is not in EXIF proper, though, it is in something called `IPTC`, not sure what I means but first you have to find a way to extract that IPTC in Java :-) First check whether the metadata extractor currently used in the app can see it.
I attach the picture downloaded from Facebook, I hope GitHub will not mess with the metadata:
![50507904_363829074441917_2709595477208203264_o](https://user-images.githubusercontent.com/99590/51787309-82460400-21b3-11e9-9d2c-aee268e08a81.jpg)

**Comment by vanshikaarora** [comment]
Hey @nicolas-raoul the second answer in this [link](https://stackoverflow.com/questions/12623302/get-meta-data-of-image-android) shows how to extract metadata using ImageUrl and from that metadata we can extract IPTC using [this](https://stackoverflow.com/questions/50669162/read-edit-write-jpg-iptc-metadata-in-java). Please have a look at these resources and correct me If I am wrong I'll start the work as soon as we are sure that this is the correct method

**Comment by nicolas-raoul** [comment]
First try with the metadata library we are currently using (during image upload to get the latitude/longitude/etc), if it can see IPTC too that would be great, so that the size of the APK does not grow.
If it does not work, icafe looks great so feel free to use it :-)
 Thanks!

**Comment by vanshikaarora** [comment]
@nicolas-raoul the GPSExtractor in the upload activity uses EXIF Interface I have gone through that interface and didn't got anything that would suit our purpose.

So we can use Icafe for extracting IPTC.
I can start working on it using Icafe

>This data is not in EXIF proper, though, it is in something called IPTC, not sure what I means but first you have to find a way to extract that IPTC in Java :-) 

The next thing to cover is how to get Facebook data out of this IPTC. Does IPTC provides an Interface to check for facebook data like in EXIF?

**Comment by nicolas-raoul** [comment]
I am not sure how icafe works, but I guess you get a IPTCRecord and get its string value. If that string starts with "FBMD" then the picture comes from Facebook, and that's all we need to know :-)

**Comment by vanshikaarora** [comment]
>I am not sure how icafe works, but I guess you get a IPTCRecord and get its string value. If that string starts with "FBMD" then the picture comes from Facebook, and that's all we need to know :-)

That's perfect :+1:

**Comment by vanshikaarora** [comment]
@maskaravivek I had created a class ReadFBMD to which I will pass the ImageUrl and it will extract metadata then process it to check for FBMD

- Now there can be two options either to call this function in `ImageProcessingService` or in `FileProcessor`  I look up for more suggestions on this.

Also I have one query how will the process be?

- User selects the images to be uploaded and if amongst them if any of the image contains FBMD then after the activity_upload_please_wait screen display a Snackbar or redirect the user back to home.

Is this agreeable or there is some better idea to execute the flow?

**Comment by maskaravivek** [comment]
Yes, IMO call the function in ImageProcessingService inside the checkImageQuality function. 

This function returns an integer value based on which a alert dialog with warning is shown to the user. The message contains a list of reasons for which the checks failed. Go through the current flow once and you will get an idea about the implementation.

**Comment by vanshikaarora** [comment]
>I am not sure how icafe works, but I guess you get a IPTCRecord and get its string value. If that string starts with "FBMD" then the picture comes from Facebook, and that's all we need to know :-)

@nicolas-raoul I have gone through the following works:

-  Added the jar file for Icafe in the libs under Project root
-  Added one class(`MetadataEntry`) of `Jar` file manually into our package(For it wasn't supported)
-  Created a class `ReadFBMD`
-  This class takes the image Url and extracts the `IPTC`
-  We can Iterate over this `IPTC` to get the `MetadataEntry` which contains two strings key and value (Not sure whether this was the data that we were searching for or we'll figure it out later)


For the `IPTCRecord` class I am not sure whether there is any parameter that is related to `FBMD` 
Yet we can think about `MetadataEntry` returned by `IPTC` 

I am sending the PR for current sate of code for reviews. 
If you have any suggestions then please share them here :)

**Comment by vanshikaarora** [comment]
> Yes, IMO call the function in ImageProcessingService inside the checkImageQuality function.
> 
> This function returns an integer value based on which a alert dialog with warning is shown to the user. The message contains a list of reasons for which the checks failed. Go through the current flow once and you will get an idea about the implementation.

@maskaravivek I'll implement this functions soon in `ImageProcessingService` but before that could you please review the current state of code. Also I need suggestions for reading FBMD from IPTC.

Kindly have a look and the PR and share some feedback's :)

**Comment by vanshikaarora** [comment]
>I am not sure how icafe works, but I guess you get a IPTC Record and get its string value. If that string starts with "FBMD" then the picture comes from Facebook, and that's all we need to know :-)

@nicolas-raoul I am able to retrieve IPTC dat out of that from that image. The data returned is here:
![screenshot from 2019-02-03 17-15-40](https://user-images.githubusercontent.com/34261945/52176353-90a9a680-27d7-11e9-8394-ea3505817988.png)


I am a bit confused here because there is no such FBMD tag available. Could you please help :)

**Comment by vanshikaarora** [comment]
>Does the processing take time?

@maskaravivek  I have observed the time for the execution and the time for reading metadata from is not complex (upon measuring through System.currentTimeMillis() I got the difference of 93)

**Comment by maskaravivek** [comment]
> @maskaravivek I have observed the time for the execution and the time for reading metadata from is > not complex (upon measuring through System.currentTimeMillis() I got the difference of 93)

Okay great! Did you check for large images as well?

> I am a bit confused here because there is no such FBMD tag available. Could you please help :)

Is your PR up to date? Can any of us run the build and check locally?

**Comment by nicolas-raoul** [comment]
@vanshikaarora Please post here the whole content of this data field, it might be FBMD in some encoded form:
![52176353-90a9a680-27d7-11e9-8394-ea3505817988](https://user-images.githubusercontent.com/99590/52200737-e56b2100-28ac-11e9-9134-36163a77bdf2.png)

**Comment by vanshikaarora** [comment]
@nicolas-raoul Here is a preview for the data from data fiels that is in byte format
![screenshot from 2019-02-04 23-00-10](https://user-images.githubusercontent.com/34261945/52225582-b8306a00-28d0-11e9-9693-2c62d4811029.png)

**Comment by vanshikaarora** [comment]
>Is your PR up to date? Can any of us run the build and check locally?

@maskaravivek I have updated the PR. You can check that locally :)

**Comment by nicolas-raoul** [comment]
Cool, that's what we were looking for :-)
![52225582-b8306a00-28d0-11e9-9693-2c62d4811029](https://user-images.githubusercontent.com/99590/52250087-83a4c880-2939-11e9-966f-02cdec7f925e.png)
70 66 77 68 is "FBMD" is ASCII code.
So, in Java we must check whether that code is present or not in the `SpecialInstructions` field.

**Comment by vanshikaarora** [comment]
>Since FBMD is always in the "SpecialInstructions" field, `iptc.datasetMap.get("SpecialInstructions").get(0).data` sounds like the best way to get it (I haven't tried it though).

@nicolas-raoul I'll test it on few other images to see which of them fits best if both of them fits then I feel the same `iptc.datasetMap.get("SpecialInstructions").get(0).data` will defintely be the better option :)

**Comment by nicolas-raoul** [comment]
I just tested this feature in 2.10.1.232 : an image downloaded from Facebook resulted in this popup:
![adb-screenshot](https://user-images.githubusercontent.com/99590/53317615-b24a0980-390f-11e9-961f-aba84267b64b.png)
... while an image that I took with my camera was uploaded normally :-) Well done @vanshikaarora !

**Comment by nicolas-raoul** [comment]
@vanshikaarora In case you are still looking for tasks, the section "Method 2" at #97 should be easy for you :-)

**Comment by vanshikaarora** [comment]
>@vanshikaarora In case you are still looking for tasks, the section "Method 2" at #97 should be easy for you :-)

Yes definitely I'll start working on it :)
