### ISSUE TITLE
Center vertically "Receiving shared content"

### ISSUE THREAD

**Issue by vanshikaarora** [commons-app/apps-android-commons#2329]
**UI of Upload Activity can be improved** 

Currently the Ui has a progress bar is at the bottom with a text view which is nearly aligned with the bottom. leaving the whole activity blank:
![whatsapp image 2019-01-22 at 10 05 03 am](https://user-images.githubusercontent.com/34261945/51528601-eb81ec00-1e2e-11e9-9f39-c7e9e16d08b3.jpeg)

How can we reproduce the issue? 
Select the FAB from home screen  then upload an image You will see the above screen for a few seconds.

**What could have made it better**
We can use material components or a custom ProgressBar in the middle of the screen like the one given below to improve the current UI.
![1tkwg](https://user-images.githubusercontent.com/34261945/51528796-5f23f900-1e2f-11e9-8ea2-ef292c490075.png)

_Suggestions are most welcome_ :)
I'll start working on this immediately after the UI is selected.

**Would you like to work on the issue?**
Yes

**Comment by nicolas-raoul** [comment]
Just to clarify, you are not talking about the progress percentage (like 70%), but only about the vertical position (centered), right?

**Comment by vanshikaarora** [comment]
I am asking for suggestions 
1. Vertical position: definitely can be better
2.  Directed progressbar: we can think over this whether to implement a directed progressbar or a custom one

**Comment by vanshikaarora** [comment]
Or we can add such a UI with a different background
![whatsapp image 2019-01-22 at 10 11 24 am](https://user-images.githubusercontent.com/34261945/51531316-fdff2400-1e34-11e9-8f70-3c279816cab5.jpeg)

**Comment by nicolas-raoul** [comment]
Could you please create a separate issue for the progress percentage?
And also for the background if you really think it is a good idea (if then please explain why on that issue's page).
Thanks! :-)

**Comment by vanshikaarora** [comment]
Ok sure Currently in this thread shall I change the vertical position of the progressbar and the TextView
I'll Create a separate issue for showing percentage after this.
