### ISSUE TITLE
"Nearby" tab name not localized

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#2331]
**Steps to reproduce:** 

1. Set language to another language than English that has 100% translation on translatewiki (such as French)
2. Open app
3. See that the tab name is still in English: "Nearby"

![screenshot_20190123-125102](https://user-images.githubusercontent.com/99590/51594671-52d79300-1f38-11e9-9a65-881bc0f57697.png)

**Comment by ravi-kishan** [comment]
I would like to work on this
