### ISSUE TITLE
Notification activity: Dates not localized

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#2332]
**Steps to reproduce:** 

1. Set language to another language than English that has 100% translation on translatewiki (such as French)
2. Open app
3. Go to notifications activity
4. Notice that the dates are in English

![screenshot_20190123-133905](https://user-images.githubusercontent.com/99590/51594850-b5309380-1f38-11e9-9f5a-637867cdb7d9.png)

**Comment by ravi-kishan** [comment]
I would like to work on this

**Comment by maskaravivek** [comment]
Sure take this up @ravi-kishan :)

**Comment by maskaravivek** [comment]
@ravi-kishan Are you still working or this issue? If not, the function added in @vanshikaarora's PR can be used to fix this issue as well.

**Comment by ravi-kishan** [comment]
I could not get to an efficient solution. You may use that pr to fix this issue.
