### ISSUE TITLE
Nearby pin bubble at wrong place in right-to-left languages

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#2333]
**Steps to reproduce:** 
1. Set your phone to Hebrew (probably also works with Arabic, Persian and Urdu)
2. Go to the nearby map
3. Tap on a pin
4. The bubble often appears at the wrong place

In this screenshot I actually tapped the pin at the left of the screen:
![screenshot_20190123-133816](https://user-images.githubusercontent.com/99590/51595062-2d975480-1f39-11e9-867e-a66c124ad197.png)

**Comment by silkypriya** [comment]
hi @nicolas-raoul ,
I would like to fix this.

**Comment by madhurgupta10** [comment]
@nicolas-raoul if the bug still exists, I would like to solve it :)

**Comment by nicolas-raoul** [comment]
Yes it still exists, I checked yesterday. Thanks, it is yours! :-)

**Comment by Claud-C** [comment]
@nicolas-raoul Can I try to work on this issue?

**Comment by nicolas-raoul** [comment]
@Claud-C Yes thanks! 🙂

**Comment by Claud-C** [comment]
I wonder if this issue still exists?  After I used a right-to-left language, my device made corresponding changes, but the problem mentioned in the issue did not appear in the software.

**Comment by nicolas-raoul** [comment]
Thanks for testing! It might have been fixed, thanks for letting us know!

I will thus close for now, if anyone observes the issue again please do not hesitate to reopen 🙂

**Comment by Claud-C** [comment]
Since I couldn't reproduce the bug, I thought about it and came up with a few ideas.

First, what are the devices that reproduce this bug? Perhaps their common trait is the cause of the bug.

Second, is this bug only in Japan? The specific text content they provide may be the cause of this bug.

I'm sorry that I can't solve this issue, because I can't reproduce this bug and I don't have more ideas to solve this bug.

**Comment by nicolas-raoul** [comment]
@Claud-C No need to be sorry, identifying what bug reports are no longer applicable is an important part of software maintenance. I guess another modification had the side effect of eliminating this bug. Thanks again and do not hesitate to check other issues if you want!
