### ISSUE TITLE
Nearby notification empty in right-to-left languages

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#2334]
**Steps to reproduce:** 
1. Set your phone to Hebrew (probably also works with Arabic, Persian and Urdu)
2. Open app
3. Wait a minute or so for the nearby notification to appear (blue band between the tabs and the pictures)
4. See how its label is not visible. The pin icon is shown but not the name of the place.

![screenshot_20190123-133643](https://user-images.githubusercontent.com/99590/51595392-f6757300-1f39-11e9-8f86-70ada074aa41.png)
![adb-screenshot](https://user-images.githubusercontent.com/99590/51595445-1311ab00-1f3a-11e9-90d7-077950c1851e.png)

**Comment by nicolas-raoul** [comment]
@vanshikaarora Thanks for your enthusiasm!
I assign you this one too, but before claiming more please make sure that you don't have more than one or two issues assigned to you already (not counting the ones for which you have a pull request waiting for review). Cheers :-)

**Comment by vanshikaarora** [comment]
Sincere apologies!!
I'll take care of that from next time :+1:
