### ISSUE TITLE
Nearby map is not localized

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#2335]
**Steps to reproduce:** 
1. Put Android's locale to French
2. Open the app
3. Tap Nearby
4. Scroll all the way to Paris
5. All labels are in English. It is not just labels missing from OpenStreetMap, see screenshot, these obviously have French labels.

Was also the topic of the closed issue #669

![screenshot_20190123-130158](https://user-images.githubusercontent.com/99590/51595646-94693d80-1f3a-11e9-982e-ea7a2f0a30fb.png)

**Comment by zhao-gang** [comment]
@nicolas-raoul Hi. I think this may be because wikimedia tiles are not correctly loaded into nearby map. You can see the nearby map with wikimedia tiles in above PR.

**Comment by nicolas-raoul** [comment]
Here is how the Google Maps website shows London to a French-language user:
![screenshot from 2019-02-22 18-14-24](https://user-images.githubusercontent.com/99590/53232167-e2a26580-36cd-11e9-8163-a0ddc19851ae.png)
As you can see, a lot of labels (at least the major ones) are in French, even if this is an English city.

**Comment by zhao-gang** [comment]
@nicolas-raoul I found that Mapbox android sdk has a localization plugin https://github.com/mapbox/mapbox-plugins-android/tree/master/plugin-localization. I will see if it can help with the localization problem you mentioned.

**Comment by zhao-gang** [comment]
After I added the localization plugin, it seems that with mapbox Style.OUTDOORS style, the labels will change with system language settings; but with custom style with wikipedia tiles, the labels are the places' language(say, London with English, Paris with French), without regarding to the system language settings. One advantage of the custom wikipedia style is that it has more places than mapbox(see screenshot). Now I don't have a way to use wikipedia style and at the same time support system language settings. I don't know if there's a way to do this. Hope someone familiar with this can point it out.

Updated the related PR to use localization plugin and mapbox tiles.

| mapbox tiles with French | wikimedia tiles with French |
|---|---|
| ![mapbox-london-french](https://user-images.githubusercontent.com/692944/53247259-d9c18c00-36ed-11e9-9a0d-6894dd237b96.png) | ![wikipedia-london-french](https://user-images.githubusercontent.com/692944/53247263-da5a2280-36ed-11e9-96ef-dd157c0f952e.png) |

**Comment by nicolas-raoul** [comment]
The screenshot on the left (in the post just above) looks like what would be ideal I think (in terms of language). For privacy reasons, I am afraid we can not use mapbox tiles though (that would reveal the user's IP address to a third party).

**Comment by zhao-gang** [comment]
The best solution would be that wikimedia tiles support mapbox localization plugin. So we can have both :-) I checked that in current Google Play store's Commons app we actually are using mapbox tiles, the wikimedia tiles are not used indeed(Because of the code that changed to wikimedia tiles somewhat does not do its work). To distinguish these two tiles, mapbox tiles are a little brighter than wikimedia tiles(See above screenshots).
