### ISSUE TITLE
Image details: date not correctly localized in Japanese

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#2336]
**Steps to reproduce:** 

1. Switch Android's locale to Japanese
2. Tap a picture (via "Explore" for instance)
3. Go to the upload date field
4. It is like `18 1月 2019` whereas it should be `2019年1月18日`

That might apply to other languages too.

![screenshot_20190123-132224](https://user-images.githubusercontent.com/99590/51595942-2f621780-1f3b-11e9-9411-0d64b5f00566.png)

**Comment by vanshikaarora** [comment]
Hey!! I am working on this

**Comment by nicolas-raoul** [comment]
The date must appear in a format that is natural for the locale of the user.
For instance, the same date will appear as `2019年1月18日` to a Japanese user and `18 Jan. 2019` to a German user.

**Comment by vanshikaarora** [comment]
> The date must appear in a format that is natural for the locale of the user.
> For instance, the same date will appear as `2019年1月18日` to a Japanese user and `18 Jan. 2019` to a German user.

ohh ohk
Sorry I have misunderstood it earlier

**Comment by nicolas-raoul** [comment]
I don't know this method, would you mind posting screenshots in various languages on the pull request page? Thanks! :-)

**Comment by vanshikaarora** [comment]
@nicolas-raoul Can you post the name that you of the image for which you have searched in the screenshot.  In most of the Images that I have viewed I am getting `Uploaded Date not available`

**Comment by nicolas-raoul** [comment]
https://commons.m.wikimedia.org/wiki/File:Iotaryoji_Tateishi_and_Masaya_Arai%2C_creators_of_a_ping-pong_table_that_simulates_physical_disabilities.jpg

**Comment by vanshikaarora** [comment]
>I don't know this method, would you mind posting screenshots in various languages on the pull request page? Thanks! :-)

@nicolas-raoul  I don't know what's the Issue here But out of many images that I have searched through explore I am getting `Uploaded Date not available` on each of them. Also I am not getting this file:
>https://commons.m.wikimedia.org/wiki/File:Iotaryoji_Tateishi_and_Masaya_Arai%2C_creators_of_a_ping-pong_table_that_simulates_physical_disabilities.jpg

Can you please verify the PR whether it's working fine when locale language is changed

**Comment by nicolas-raoul** [comment]
There seems to be a bug with Explore indeed. The bug seems to not happen
with self-uploaded pictures so please upload a picture you have taken and
see its date, thanks! 🙂

**Comment by vanshikaarora** [comment]
>There seems to be a bug with Explore indeed. The bug seems to not happen
with self-uploaded pictures so please upload a picture you have taken and
see its date, thanks!

@nicolas-raoul You were right the there was a bug with explore I can see the uploade date on a self-uploaded it. It shows absolutely correct response in case of English and Hindi

Here's a screenshot for the date in Hindi

![whatsapp image 2019-01-27 at 3 38 07 pm](https://user-images.githubusercontent.com/34261945/51799646-b3711380-2249-11e9-8cbf-0c147533e182.jpeg)

**Comment by maskaravivek** [comment]
Nice to see the localized date in Hindi. :) Have created another issue for Explore. #2362. 

After one round of testing, we can merge #2341.

**Comment by vanshikaarora** [comment]
OK @maskaravivek till then I'll look at the other Issue as well

**Comment by nicolas-raoul** [comment]
It works great, thanks! :-)

**Comment by vanshikaarora** [comment]
>It works great, thanks! :-)

Good to see this :)
