### ISSUE TITLE
Version number not selectable in About menu

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#2342]
On this screen I can not select the version number, long-pressing on it does nothing:
![adb-screenshot](https://user-images.githubusercontent.com/99590/51722274-35213f80-2098-11e9-96c6-9b79260264a0.png)

This was apparently fixed in #2250 but maybe it reappeared, or maybe it is a problem in my particular environment? I am using Android 7.1.2 with German locale (but the problem also occurs in English locale).

**Comment by sp2710** [comment]
I am working on this

**Comment by nicolas-raoul** [comment]
That works now thanks! :-)
