### ISSUE TITLE
Achievements Activity's toolbar is scrollable

### ISSUE THREAD

**Issue by vanshikaarora** [commons-app/apps-android-commons#2343]
**On scrollong Achievements Activity it's toolbar scrolls along with the activity** 

As mentioned in the issue #[2165](https://github.com/commons-app/apps-android-commons/issues/2165)

The same scrolling state can be observed for achievements activity
**Steps to reproduce:** 
Go to achievements activity
Scroll the Activity

**Would you like to work on the issue?**
Yes

**Comment by maskaravivek** [comment]
Feel free to pick this up. :)
