### ISSUE TITLE
If image has not failed, let caption take the whole horizontal space

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#2357]
For the second picture, "entrance" should be on the same line:
![screenshot_20190127-175611](https://user-images.githubusercontent.com/99590/51798893-11f3bd00-225d-11e9-9971-189a3b4cc278.png)
No need to keep button space for image whoseupload did not fail.

**Comment by vanshikaarora** [comment]
I am working on this Issue!!

**Comment by nicolas-raoul** [comment]
The fix works great, thanks! :-)
