### ISSUE TITLE
Adding a feature to crop image uploaded using camera

### ISSUE THREAD

**Issue by vanshikaarora** [commons-app/apps-android-commons#2361]
**Summary:** 

When uploading an Image using camera the camera takes the image and before uploading asks for retake or OK.
Also after user clicking OK we should ask the user to crop the image as per the need. 

**Would you like to work on the issue?**
Yes

**Comment by maskaravivek** [comment]
related #1192

**Comment by maskaravivek** [comment]
From the discussion, it looks like everyone agrees with having at least a few editing options. 

Ref: https://github.com/commons-app/apps-android-commons/issues/1192#issuecomment-402044845

It would be great if you could share your approach on this thread before implementing it. If we can plug in an image editing library that can help us achieve all/some of the editing options, it would save us a lot of time and effort. 

Also, are you planning to implement it only for camera uploads or all uploads?

**Comment by vanshikaarora** [comment]
Sure I'll do that

**Comment by maskaravivek** [comment]
This library looks good for image cropping: https://github.com/ArthurHub/Android-Image-Cropper

It also supports image rotation.

**Comment by vanshikaarora** [comment]
@maskaravivek The library for cropping that you have mentioned is conflicting with other files in the project here is the error report

`Android resource linking failed
Output:  warn: removing resource fr.free.nrw.commons.beta:string/contributions_subtitle without required default value.
warn: removing resource fr.free.nrw.commons.beta:string/login_failed_password without required default value.
warn: removing resource fr.free.nrw.commons.beta:string/login_failed_username without required default value.
warn: removing resource fr.free.nrw.commons.beta:string/multiple_uploads_title without required default value.
warn: removing resource fr.free.nrw.commons.beta:string/preference_tracking without required default value.
warn: removing resource fr.free.nrw.commons.beta:string/preference_tracking_summary without required default value.
warn: removing resource fr.free.nrw.commons.beta:string/share_license_summary without required default value.
warn: removing resource fr.free.nrw.commons.beta:string/starting_multiple_uploads without required default value.
warn: removing resource fr.free.nrw.commons.beta:string/upload_image_problem_duplicate without required default value.
warn: removing resource fr.free.nrw.commons.beta:string/uploads_pending_notification_indicator without required default value.
warn: removing resource fr.free.nrw.commons.beta:string/use_wikidata without required default value.
/media/vanshika/25151b5f-bb91-4813-863c-b418727a0635/vanshika/apps-android-commons/app/build/intermediates/incremental/mergeBetaDebugResources/merged.dir/values-v28/values-v28.xml:7: error: resource android:attr/dialogCornerRadius not found.
/media/vanshika/25151b5f-bb91-4813-863c-b418727a0635/vanshika/apps-android-commons/app/build/intermediates/incremental/mergeBetaDebugResources/merged.dir/values-v28/values-v28.xml:11: error: resource android:attr/dialogCornerRadius not found.
/media/vanshika/25151b5f-bb91-4813-863c-b418727a0635/vanshika/apps-android-commons/app/build/intermediates/incremental/mergeBetaDebugResources/merged.dir/values/values.xml:702: error: resource android:attr/fontVariationSettings not found.
/media/vanshika/25151b5f-bb91-4813-863c-b418727a0635/vanshika/apps-android-commons/app/build/intermediates/incremental/mergeBetaDebugResources/merged.dir/values/values.xml:702: error: resource android:attr/ttcIndex not found.
error: failed linking references.

Command: /home/vanshika/.gradle/caches/transforms-1/files-1.1/aapt2-3.2.0-4818971-linux.jar/cb90afecad6ed23074430384aa846114/aapt2-3.2.0-4818971-linux/aapt2 link -I\
        /home/vanshika/Android/Sdk/platforms/android-27/android.jar\
        --manifest\
        /media/vanshika/25151b5f-bb91-4813-863c-b418727a0635/vanshika/apps-android-commons/app/build/intermediates/merged_manifests/betaDebug/processBetaDebugManifest/merged/AndroidManifest.xml\
        -o\
        /media/vanshika/25151b5f-bb91-4813-863c-b418727a0635/vanshika/apps-android-commons/app/build/intermediates/processed_res/betaDebug/processBetaDebugResources/out/resources-betaDebug.ap_\
        -R\
        @/media/vanshika/25151b5f-bb91-4813-863c-b418727a0635/vanshika/apps-android-commons/app/build/intermediates/incremental/processBetaDebugResources/resources-list-for-resources-betaDebug.ap_.txt\
        --auto-add-overlay\
        --java\
        /media/vanshika/25151b5f-bb91-4813-863c-b418727a0635/vanshika/apps-android-commons/app/build/generated/not_namespaced_r_class_sources/betaDebug/processBetaDebugResources/r\
        --proguard\
        /media/vanshika/25151b5f-bb91-4813-863c-b418727a0635/vanshika/apps-android-commons/app/build/intermediates/proguard-rules/beta/debug/aapt_rules.txt\
        --custom-package\
        fr.free.nrw.commons\
        -0\
        apk\
        --output-text-symbols\
        /media/vanshika/25151b5f-bb91-4813-863c-b418727a0635/vanshika/apps-android-commons/app/build/intermediates/symbols/beta/debug/R.txt\
        --no-version-vectors
Daemon:  AAPT2 aapt2-3.2.0-4818971-linux Daemon #0`

**Comment by maskaravivek** [comment]
Feel free to check out other libraries. In a few days, after I am done with my current tasks, I can help in resolving the library conflicts.

**Comment by vanshikaarora** [comment]
OK sure I'll check out some other methods

**Comment by maskaravivek** [comment]
A customizable one would be apt. A square cropped image would be appropriate for apps like Instagram that allows only Square image uploads. 

You might have already come across this link, but just for ref I was looking for cropping libraries amongst the ones listed here:

https://android-arsenal.com/tag/45

**Comment by vanshikaarora** [comment]
I have got a library that works on API level above 14 https://github.com/igreenwood/SimpleCropView?utm_source=android-arsenal.com&utm_medium=referral&utm_campaign=2366

Shall I start working with this?

**Comment by maskaravivek** [comment]
Sure, you can start working on it. :)

Where are you thinking of providing crop option?

**Comment by vanshikaarora** [comment]
After the image is captured via camera take the Uri of the image and take t to an activity for cropping
After the user crops the image send the flow to UploadActivity

**Comment by maskaravivek** [comment]
I see 2 issues with this approach: 
- it will add an extra mandatory step for the user. He will have to explicitly skip if he doesn't want to crop the image
- it won't handle multiple upload scenario

IMO, we should add an edit button somewhere on the upload screen.

**Comment by vanshikaarora** [comment]
Yes that's definitely a better suggestion. 
Right now there are two options in hand 

- Either we can add a button on the Upload Screen
- Or before taking the user to upload screen we can display a dialog if they want to crop the image or some other message

What is your opinion about this?

**Comment by maskaravivek** [comment]
Personally i find dialogs to be obstructive as they require an explicit action from the user. 
But we can go ahead with dialogs if others agree. 

Anyways you can start working on it. It can be plugged in anywhere later on. Not much should change on the implementation front

**Comment by vanshikaarora** [comment]
OK I'll start with creating an activity for cropping feature :+1:

**Comment by maskaravivek** [comment]
Sure. The CropActivity should be opened using startActivityForResult with originalUri passed to it and the caller can handle the modifed URI in onActivityResult

**Comment by vanshikaarora** [comment]
Ok I'll complete this soon :+1:

**Comment by vanshikaarora** [comment]
I need another suggestion what are we going to do in case of multiple uploads?

**Comment by vanshikaarora** [comment]
@maskaravivek I think we first need to fix #2289 this libraryshowed the same AAPT2 error as was with the previous one

**Comment by maskaravivek** [comment]
For now you can probably try using an older version of the library. If you checkout the commit history in the library’s project, you would notice that they migrated to AndroidX recently. So lets use an older version of the library for now.

**Comment by vanshikaarora** [comment]
> I have got a library that works on API level above 14 https://github.com/igreenwood/SimpleCropView?utm_source=android-arsenal.com&utm_medium=referral&utm_campaign=2366
> 
> Shall I start working with this?

@maskaravivek This library also gave the same Issues like the previous one's that i have tried

**Comment by ashishkumar468** [comment]
Check this out https://github.com/Yalantis/uCrop

**Comment by vanshikaarora** [comment]
>Check this out https://github.com/Yalantis/uCrop

Sure I'll just have a look at this :)

**Comment by vanshikaarora** [comment]
@ashishkumar468 I have checked that code but the library allows only square and rectangles of fixed ratio. So far in the discussion we had been planning to implement a customisable cropping feature.

The idea of rectangle's of various ratio also sounds good. :)
To implement anything further I would like to have more suggestions: @maskaravivek @nicolas-raoul Can you please pitch in your ideas?

**Comment by nicolas-raoul** [comment]
Not much to add :-)
I suggest merging this issue into #1192 though, since the discussion here is pretty much heading the same way. Let's continue the discussion over there.

**Comment by vanshikaarora** [comment]
>The [library](https://github.com/ArthurHub/Android-Image-Cropper/blob/master/build.gradle) is using SDK 28 and AndroidX. That is causing conflicts. After #2289 is merged, we should plan [migration to AndroidX](https://developer.android.com/jetpack/androidx/migrate) from our current usage of support libs.

@maskaravivek Now shall I start working upon this cropping feature

**Comment by maskaravivek** [comment]
Sure. And lets continue the discussion on #1192.
