### ISSUE TITLE
Rotating screen erases title

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#2369]
1. select image for upload
2. enter title
3. rotate screen
4. title field is now empty 😱

even on the categories selection screen, rotating takes you back to step 1.

**Comment by vanshikaarora** [comment]
@nicolas-raoul Shall I work on this?

**Comment by nicolas-raoul** [comment]
@vanshikaarora  How many issues are you already working on right now? When you have one or less, sure feel free to take it :-)

**Comment by vanshikaarora** [comment]
@nicolas-raoul This same issue arises for description of the image shall I create a separate Issue for that for fix it in the same PR?

**Comment by maskaravivek** [comment]
IMO you can fix it in the same PR. The issue seems to be related to each other.

**Comment by vanshikaarora** [comment]
Sure, I'll do that :+1:

**Comment by koala0090** [comment]
I think this problem wasn't closed yet. I would like to report the same problem. Not only the title would be erased, but all the data you filled in.

**Comment by nicolas-raoul** [comment]
@koala0090 Are you using the alpha version? Could you please post a screenshot of your About screen?

**Comment by koala0090** [comment]
@nicolas-raoul Sure, thanks for you reply.
http://imgur.com/gallery/D7sjRpn
