### ISSUE TITLE
On Changing orientation restore state of nearby map

### ISSUE THREAD

**Issue by sp2710** [commons-app/apps-android-commons#2384]
**Summary:** 

Currently nearby map takes some loading when its orientation is changed and then displays the map. It will be better if the previous state will be used when its orientation is changed and it will not take any loading at all.

**Steps to reproduce:** 
Rotate screen on nearby map fragment

**What did you expect the app to do?**
It does not takes any loading and previous state should be used for displaying the map

**What did you see instead?**
It takes some loading before displaying the map

**Device and Android version:** 

Motorola Moto G5 plus With API 24
 
**Commons app version:** 

Latest Master

**Would you like to work on the issue?**
yes

**Comment by josephyim** [comment]
Hi @sp2710 , I am a newbie in open source project and java. My apologies if I say anything stupid.

I was checking out the issue #2369 , which I think is similar to this issue. Then I found this website http://code.hootsuite.com/orientation-changes-on-android/. It explains that adding "android:configChanges" is not a good idea... It suggests "_The most important aspect of handling orientation changes is saving state. In most cases this involves implementing the onSaveInstanceState method (this could be in your Activity, Fragment or both) and placing the values you need to save in the Bundle argument that gets passed to the method._"
