### ISSUE TITLE
unused message "about_"

### ISSUE THREAD

**Issue by jayvdb** [commons-app/apps-android-commons#239]
Please excuse my lack of knowledge in this area, but the following en message appears to be unused.

```xml
<string name="about_">SignupActivity</string>
```

Should it be removed?

**Comment by nicolas-raoul** [comment]
I don't remember anything about this about_ ...
If you remove & compile & run, does the app still work?

**Comment by jayvdb** [comment]
I can remove & compile, but I'm not yet set up to deploy and do test runs of the app.

**Comment by nicolas-raoul** [comment]
From command line with your device connected via USB and developer options
enabled:

./gradlew installDebug

Or "Play" button from most IDEs :-)

You might need to uninstall before.
