### ISSUE TITLE
Clicking on the bottom card in Step 1 of upload image should toggle the state of the card

### ISSUE THREAD

**Issue by ShridharGoel** [commons-app/apps-android-commons#2390]
**Summary:** 

Clicking outside the arrow to expand on the bottom card in Step 1 of upload image should also toggle the state of the card.

Currently, the state toggles only when the arrow to expand the card is clicked.

**Commons app version:** 

Latest master.

**Would you like to work on the issue?**

Yes.

**Comment by IwanPolri** [comment]
Ya
