### ISSUE TITLE
Adding "Click Button Twice to exit " on MainActivity 

### ISSUE THREAD

**Issue by prajurock** [commons-app/apps-android-commons#2403]
**Summary:**

Adding "Click Button Twice to exit " on MainActivity

**Android version:**

Android 8.1.0 (API 27)

**Commons app version:**

Latest master

**Would you like to work on the issue?**

Yes

**Comment by ShridharGoel** [comment]
A similar issue was closed in the past because such a feature isn't required. You can read this: https://github.com/commons-app/apps-android-commons/issues/2299#issuecomment-454243436
