### ISSUE TITLE
Can't multiselect

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#2406]
I can't select several pictures with the new picker.
Long-press makes a grey border appear around the pic but it disappears.
The button "Cancel" never becomes "Done".

2.9.0.196~52ab393

**Comment by maskaravivek** [comment]
@nicolas-raoul Are you unable to multi-select from any of the apps(ie google photos, gallery, file manager etc) or does it work for few of them? 

For me, multi-select works for Google photos and Gallery. It is not working for File Manager.
