### ISSUE TITLE
Option to View archived notifications

### ISSUE THREAD

**Issue by maskaravivek** [commons-app/apps-android-commons#2408]
**Summary:** 

With #2298 now implemented, it would be nice to have an option to view archived/read notifications. 

The Wikipedia app provides an option in the action bar menu to view archived ones. We can probably mimic a similar UI. 

![device-2019-02-04-110953](https://user-images.githubusercontent.com/3069373/52191992-6b677780-286d-11e9-98af-5e39a68b877c.png)

**Comment by sp2710** [comment]
@maskaravivek In API query can we use the same filter to fetch only read notifications?

>.param("notfilter","read")

**Comment by maskaravivek** [comment]
Yes, that would be nice. 

Also, modify the startup intent for `NotificationsActivity` to accept this filter. 

```
NotificationsActivity.startYourself(context, "read/unread");
```

**Comment by sp2710** [comment]
Sure I will do that  :+1:

**Comment by sp2710** [comment]
@maskaravivek should i display the archived in the same fragment or use a different fragment for it

**Comment by maskaravivek** [comment]
You can use the same fragment. At a time either it will show archived or unread notification based on the parameter.

**Comment by maskaravivek** [comment]
@sp2710 I couldn't find an API to mark a notification as unread. 

You can go ahead and create a separate issue for that.  Later, we can check their implementation and get an idea about how to do it. :)

**Comment by sp2710** [comment]
Sure I will do that:)
