### ISSUE TITLE
"Error occurred while loading images" for no apparent reason

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#2410]
1. Explore 
2. Search for something
3. Scroll
4. This message appears from time to time

Latest alpha

**Comment by ShridharGoel** [comment]
Yes, I've observed this issue sometimes. I thought maybe it's because of server issues.

**Comment by prajurock** [comment]
I would like to work on it.

**Comment by prajurock** [comment]
I made the pull request Please check it.

**Comment by maskaravivek** [comment]
@nicolas-raoul Is this duplicate of #2435

**Comment by nicolas-raoul** [comment]
This problem existed two weeks ago, while I noticed #2435 only 2 days ago, but maybe I just did not notice and it was already present.
Anyway I don't see any of the two now, so hopefully they are both solved :-) I will reopen if not.
