### ISSUE TITLE
Structured Commons (issues list)

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#2415]
Here are the proposed Structured Commons properties:
https://www.wikidata.org/wiki/Wikidata:WikiProject_Commons/Properties_table
We should find out which ones are relevant to us when uploading, when searching, and when showing media.

In order of perceived priority:

- Caption #2297 #2337 #2525
- Depicts #2097
- Media type https://www.wikidata.org/wiki/Property:P1163
- EXIF-like data https://commons.wikimedia.org/wiki/Commons:Structured_data/Properties_table#EXIF(-like)_data and https://commons.wikimedia.org/wiki/Commons:Structured_data/Properties_table#Two-dimensional_images though the logic might better be on the server side

**Comment by ujjwalagrawal17** [comment]
I was going through the links in the issue . The project seems super amazing. :100:

**Comment by VojtechDostal** [comment]
We could actually start inserting Depicts for files uploaded via Pins on our Nearby map (we know what such pictures depict).

**Comment by nicolas-raoul** [comment]
@VojtechDostal 

> We could actually start inserting Depicts for files uploaded via Pins on our Nearby map (we know what such pictures depict).

Good idea! I just created #2942 please check.

**Comment by nicolas-raoul** [comment]
Closing as every implementable task has its own issue.
