### ISSUE TITLE
Achievements activity share option is not working.

### ISSUE THREAD

**Issue by prajurock** [commons-app/apps-android-commons#2416]
**Summary:** 
On clicking the share option on achievement activity App closes.

**Device and Android version:** 
Asus Zenfone Max m1 pro(API 27)
 
**Commons app version:** 

latest  master version

**Gif**

![video2gif_20190205_223545](https://user-images.githubusercontent.com/26791135/52290845-04de7880-2997-11e9-96b2-ccda2c5c96b3.gif)

**Would you like to work on the issue?**

Yes

**Comment by thomas154** [comment]
I would like to work on this.

**Comment by prajurock** [comment]
Ok @thomas154 .You can work.

**Comment by prajurock** [comment]
@thomas154 You can proceed.
