### ISSUE TITLE
Add feature to zoom images when viewing media details

### ISSUE THREAD

**Issue by ShridharGoel** [commons-app/apps-android-commons#2421]
**Summary:** 

Users should have a pinch-to-zoom feature so that they can zoom the image without the need to download.

**Commons app version:** 

Latest master.

**Would you like to work on the issue?**

Yes

**Comment by nicolas-raoul** [comment]
Ah yes that would be really great! I often regret this feature is not present :-)

**Comment by nicolas-raoul** [comment]
Merging into #2950
