### ISSUE TITLE
Unused license messages

### ISSUE THREAD

**Issue by jayvdb** [commons-app/apps-android-commons#243]
There are many apparently unused license messages, like `license_name_pd_usgov`.

Is there any intention to use them in the near future?

**Comment by misaochan** [comment]
I don't think so, as we should probably only offer the licenses that the Upload Wizard does? Anyone have thoughts on this?

**Comment by nicolas-raoul** [comment]
People who really need `license_name_pd_usgov` probably use desktop computers.
Those not offered by the Upload Wizard can be removed, I would say.

**Comment by misaochan** [comment]
For clarity, these are in wikimedia_licenses.xml
