### ISSUE TITLE
Show number of Wikidata edits from the Commons app 

### ISSUE THREAD

**Issue by maskaravivek** [commons-app/apps-android-commons#2430]
**Summary:** 

It would be nice to show the number of Wikidata edits he has made using the commons android app. Personally, it would motivate me to make more edits. 

This task is also an action item (Point number 6) as part of "Targeted acquisition of photos for places that need them" in the upcoming IEG 2019 grant. 

https://meta.wikimedia.org/wiki/Grants:Project/Commons_app/Commons_Android_app_v3#Part_2:_Targeted_acquisition_of_photos_for_places_that_need_them

We already track the edits made through the app by adding a `wikimedia-commons-app` tag. If we have an API that could return the number of edits then showing it in the achievements screen would be trivial.

**Comment by maskaravivek** [comment]
As the changes for API are done, I am going ahead and picking this up. We would be using this API but on @urbanecm's endpoint. 

https://tools.wmflabs.org/commons-android-app/tool-commons-android-app/wikidataedits.py?user=Maskaravivek

@urbanecm  On a separate note, the uploads and feedback APIs seem to be down right now. It would be great if one of us( common app members) could have maintainer access for the repo.

**Comment by urbanecm** [comment]
The down issue is fixed now. I don't have issues with granting you access to the GitHub repository itself, but I'm a little bit reluctant to grant you maintainer rights to the tool itself, since that would effectively grant you access to my Wikipedia account (on the same tool there are some cron jobs needing sysop access).

**Comment by urbanecm** [comment]
Deployed&pulled, see https://tools.wmflabs.org/urbanecmbot/commonsmisc/wikidataedits.py.

**Comment by maskaravivek** [comment]
Awesome thanks @urbanecm. :)

> I don't have issues with granting you access to the GitHub repository itself, but I'm a little bit reluctant to grant you maintainer rights to the tool itself, since that would effectively grant you access to my Wikipedia account (on the same tool there are some cron jobs needing sysop access).

It would be great if you grant me collaborator access for the repo. Now, that I have managed to set up a mirror for testing, it can be used for testing before making the actual releases. 

Mirror tool: https://toolsadmin.wikimedia.org/tools/id/commons-android-app
Repo which is up to date with the original repo: https://phabricator.wikimedia.org/source/tool-commons-android-app/

**Comment by urbanecm** [comment]
Done. Maybe you would want the repo to be transferred to commons-app android, so you have full control over it?

**Comment by maskaravivek** [comment]
Am good either way but having it under `commons-app` org on Github might make it easier for other contributors to find it. 

@nicolas-raoul @misaochan would be able to answer if we should have it transferred.

**Comment by misaochan** [comment]
I'm good with it if @urbanecm is good with it. No pressure otherwise. :)

**Comment by urbanecm** [comment]
Transferring a repo adds more workload to you than to me, if you want me to do it for you, you need to grant me repository creation right in your rights. As soon as I recieve the rights, I'll do the transfer and waive the rights. If you're fine with leaving this under my acc, fine with me, it was just an offer.

**Comment by misaochan** [comment]
Sent you the invite.

**Comment by urbanecm** [comment]
Thanks. Can you please delete https://github.com/commons-app/commonsmisc, so I can transfer my repository to this place? Thanks!

**Comment by misaochan** [comment]
Done!

**Comment by urbanecm** [comment]
Thanks, transferred the repository to the same place. If you want, you can revoke my rights now, as I don't need them.

**Comment by misaochan** [comment]
Thanks @urbanecm ! :) I'll remove the membership, but I'll send you a collaborator invite for the repo so you can make changes to it whenever you want.
