### ISSUE TITLE
Multiple uploads not possible via Gallery (local storage) in 2.10-release branch

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#2434]
**Summary:** 

After the image picker library overhaul, uploads from Google Photos and other 3rd party galleries now work! Yay! :)

But, while they work perfectly for 3rd party galleries now, I cannot select multiple uploads via the Android stock gallery (local storage). In the image picking stage, there is no option to select more than 1. Long tap, which normally works for selection, does not work anymore.

**Steps to reproduce:** 

- Pull from 2.10-release branch
- Contributions > FAB > Gallery
- Select the Android stock gallery
- Try to select more than 1 image

**Device and Android version:** 

Samsung Galaxy s9 running Android 8.0.0
 
**Commons app version:** 

2.10-release branch

**Would you like to work on the issue?**

Pref not

**Comment by albendz** [comment]
I'll take this.

**Comment by maskaravivek** [comment]
@albendz I was also taking a look at this issue as it might be required for this release. It would be great if you could also post progress updates here and once any of us is able to figure out the issue, we can create a PR for it

**Comment by albendz** [comment]
No problem. When is the next release?

**Comment by maskaravivek** [comment]
#2435 and #1971 are the pending blockers before the release. We would make a beta release as soon as these are fixed.

**Comment by albendz** [comment]
Samsung Galaxy S6 7.0 does not have this issue with either gallery or google photos on 2.10 branch.

**Comment by albendz** [comment]
I tried again with an 8.0 and 9.0 emulator using the file explorer (not sure how to get the gallery instead if it's not set to default). Since I can't repro this I'm going to unassign.

**Comment by maskaravivek** [comment]
@misaochan From stock gallery do you mean file manager? It doesn't work for me while using the File manager but works for the stock gallery. 

Multiple uploads didn't work with the file manager earlier as well.

**Comment by misaochan** [comment]
Hmm no, I mean stock gallery. Open app > Contributions > Gallery FAB > Gallery > Camera. It works if I go directly to my stock gallery and select the multiple images then tap Share.

But if it is working for both of you, maybe we do not need to block the release for this?

**Comment by nicolas-raoul** [comment]
I can reproduce exactly what @misaochan said in the message just above.
2.10.241~64eae8b on LineageOS 7.1.2

**Comment by AshTheGoblin** [comment]
I reproduced the issue, but I'm not sure if anything can be done about it.

I opened Google Drive > + FAB > Upload > Gallery > (any folder).

Long pressing an image does not allow for the selection of multiple files, and this is in a first party app.

**Comment by misaochan** [comment]
Fixed in overhaul.
