### ISSUE TITLE
"Explore" not loading new pics dynamically anymore (2.9.0.207~5a6402c)

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#2435]
**Summary:** 

"Explore" would normally load new pics dynamically after you scroll all the way down. Currently, it just stops at the bottom after 10 pics

**Steps to reproduce:** 

Go to Explore, scroll down

**Device and Android version:** 

Samsung Galaxy s9 Android 8.0.0

**Commons app version:** 

Alpha test (2.9.0.207~5a6402c)

**Would you like to work on the issue?**

Pref not

**Comment by nicolas-raoul** [comment]
I had noticed this, I can confirm it is fixed in 2.9.0.209 :-)
