### ISSUE TITLE
Tapping notification does not bring me to my talk page any more (alpha)

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#2437]
**Summary:** 

Previously, tapping a notification would bring me to my talk page. This is very important, because our notifications feature does not display the full message, it is just meant as a heads up. But after the recent changes, tapping does nothing. 

**Steps to reproduce:** 

Notifications > Tap on a notification

**Device and Android version:** 

Samsung Galaxy s9 8.0.0
 
**Commons app version:** 

Current master (alpha)

**Would you like to work on the issue?**

Pref not

**Comment by ShridharGoel** [comment]
I can take this.

**Comment by misaochan** [comment]
Thanks @ShridharGoel !

**Comment by maskaravivek** [comment]
@ShridharGoel Any updates on this? We are hoping to include this fix in the next beta release.

**Comment by maskaravivek** [comment]
@ShridharGoel Am taking this up as this fix is one of the hotfixes required for next beta release.

**Comment by ShridharGoel** [comment]
Sorry, couldn't work on this due to exams.

**Comment by maskaravivek** [comment]
No issues @ShridharGoel :)
