### ISSUE TITLE
Bookmarks activity wrongly says "No images found"

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#2440]
1. Go to Explore
2. Bookmark the first image
3. Go to bookmarks activity

![screenshot_20190212-140347](https://user-images.githubusercontent.com/99590/52613130-1a402f00-2ed0-11e9-92e3-d16b3cbe6b9e.png)

**Comment by jainharsh96** [comment]
I I am working on this bug.

**Comment by nicolas-raoul** [comment]
@jainharsh96 Thanks!
have you managed to reproduce the problem?

**Comment by jainharsh96** [comment]
@nicolas-raoul  Yes 
and I am working on it.

**Comment by jainharsh96** [comment]
Now there is another bug,
when  I upload image app gets crash without uploading the image.

**Comment by jainharsh96** [comment]
currently, an image is not uploading. because the database is set read-only

**Comment by nicolas-raoul** [comment]
This issue is reproducible even without any upload. Just try the 3 steps above :-)

**Comment by jainharsh96** [comment]
in Explore, an image is not loading.

**Comment by jainharsh96** [comment]
I resolved this issue #2440.
Now bookmarked images are loading in this activity.
![image](https://user-images.githubusercontent.com/45347251/52839694-063d3d00-311d-11e9-9d46-7990367c8f81.png)

**Comment by nicolas-raoul** [comment]
@jainharsh96 Cool, please commit and push to your repo, then send us a pull request :-)

**Comment by vanshikaarora** [comment]
I think the Issue here and the one posted [here](https://github.com/commons-app/apps-android-commons/issues/2414#issuecomment-473650576) in the issue #2414 are related

**Comment by neslihanturan** [comment]
This issue is solved.
