### ISSUE TITLE
Tap here to see the ongoing campaigns: Wrong wording

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#2441]
Sounds misleading when it is already enabled.
![screenshot_20190212-211731](https://user-images.githubusercontent.com/99590/52634980-f26ebc80-2f0b-11e9-9e59-a0a73577a426.png)

**Comment by misaochan** [comment]
How about "See ongoing campaigns"?

Btw, "Display Nearby Notifications" has the same problem, so both can probably be fixed together. :)

**Comment by nicolas-raoul** [comment]
I find this clearer:
![screenshot_20190212-214203](https://user-images.githubusercontent.com/99590/52636217-55158780-2f0f-11e9-8ae8-70fecd150d62.png)

**Comment by sp2710** [comment]
What about "Turn on to see the ongoing campaigns" ?

**Comment by sp2710** [comment]
How about "Turn on to See ongoing campaigns"?

**Comment by akash1994deep** [comment]
"Tap here" can be removed and then it makes sense "See the ongoing campaigns" and for nearby notifications "See the nearest place that needs pictures".
Or the summary of the menu items can be dynamically changed depending on whether the toggle is on or off.

**Comment by vanshikaarora** [comment]
Well generally toggle switches have such description's of the switches beneath them.
So may be, we can change to "Once enabled" or "Turning on the switches"
![whatsapp image 2019-02-24 at 10 59 07 pm 1](https://user-images.githubusercontent.com/34261945/53302760-deba4300-3887-11e9-9ecf-a9c1d660b9f0.jpeg)
![whatsapp image 2019-02-24 at 10 59 07 pm](https://user-images.githubusercontent.com/34261945/53302761-dfeb7000-3887-11e9-82a3-c88f5d005631.jpeg)

**Comment by misaochan** [comment]
> "Tap here" can be removed and then it makes sense "See the ongoing campaigns" and for nearby notifications "See the nearest place that needs pictures".

This would be my vote. :)

**Comment by vanshikaarora** [comment]
Do we have more opinions on this?

**Comment by misaochan** [comment]
@nicolas-raoul Are you OK with "See the ongoing campaigns"? If you are, we can allow the student to proceed with this, I think it is very beginner-friendly. ;)

**Comment by nicolas-raoul** [comment]
OK! :-)

**Comment by JobGetabu** [comment]
I would like be to this assigned @nicolas-raoul

**Comment by nicolas-raoul** [comment]
@JobGetabu It is yours, looking forward to your pull request :-)

**Comment by JobGetabu** [comment]
> @JobGetabu It is yours, looking forward to your pull request :-)

[Pull request](https://github.com/commons-app/apps-android-commons/pull/2745)

**Comment by nicolas-raoul** [comment]
Thanks!
Would you mind doing the same for "Display nearby notification" by the way?

**Comment by JobGetabu** [comment]
No, I don't mind.
I'll fix that and pick up another issue
Thanks
