### ISSUE TITLE
Image quality warning dialog appears 2 times if you quick on next quickly

### ISSUE THREAD

**Issue by maskaravivek** [commons-app/apps-android-commons#2442]
**Summary:** 

The warning dialog appears twice for an image that fails one of the checks

**Steps to reproduce:** 

- select a place from nearby
- choose a picture to upload (say duplicate image/image with wrong geolocation)
- quickly click on next

You will see an error dialog but notice a flicker. On clicking Yes/No, you can still see the dialog. This is because the dialog appeared twice.

**Comment by aniketnath** [comment]
Whenever I am trying to upload an image progress dialogue is coming only and the image is not getting uploaded

**Comment by maskaravivek** [comment]
Which version of the app are you using

**Comment by aniketnath** [comment]
beta version. cloned 2.9 released

**Comment by maskaravivek** [comment]
use 2.10-release

**Comment by zhao-gang** [comment]
@mashawan Hi. I found the reason is that method ImageProcessingService.validateImage gets called twice and the results interfered. I am working on a solution so please assign this issue to me :-)

**Comment by macgills** [comment]
Closing as I believe this to no longer be an issue
