### ISSUE TITLE
Night mode: Achievements

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#2446]
white text difficult to read on silver background.
![screenshot_20190213-122205](https://user-images.githubusercontent.com/99590/52684748-9bf49300-2f8a-11e9-85ba-2b5e55a3d4ab.png)

**Comment by aniketnath** [comment]
I have changed the background in light grey.
![screenshot_2019-02-13-15-27-55-489_fr free nrw commons beta 1](https://user-images.githubusercontent.com/25636078/52703534-8ee49d80-2fa4-11e9-97e3-13d9e08880e4.png)

**Comment by aniketnath** [comment]
solved this issue and I am giving my screenshot. can I contribute it?
![screenshot_2019-02-14-14-10-11-660_fr free nrw commons beta 1](https://user-images.githubusercontent.com/25636078/52774114-92d6f500-3062-11e9-84fb-78b3754d3b48.png)

**Comment by nicolas-raoul** [comment]
The colors in your previous screenshot were better actually :-)

**Comment by aniketnath** [comment]
ok

**Comment by aniketnath** [comment]
@nicolas-raoul changed it as previous one

**Comment by maskaravivek** [comment]
I have reverted the fix as it changes the background for light mode as well. Apologies for not noticing it while testing. :/

@aniketnath Let us know if you need any help keeping different backgrounds for light and dark themes. :)

**Comment by radhika1601** [comment]
@nicolas-raoul Can I work on this issue?

**Comment by silkypriya** [comment]
@maskaravivek ,@nicolas-raoul I have solved this issue along with some more related with night mode.
Kindly review.
Thanks!

**Comment by nicolas-raoul** [comment]
@radhika1601 Sorry for the inconvenience, would you mind choosing another issue? Thanks!

**Comment by domdomegg** [comment]
Fixed in #2574
