### ISSUE TITLE
Erroneous string shown in tutorial

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#2447]
![adb-screenshot](https://user-images.githubusercontent.com/99590/52758606-4a144180-304c-11e9-8ad6-de006a3fe264.png)
If this label has a purpose, it should be fixed.
If not, the label itself should be removed.
(screenshot above is in locale zh-hant)

**Comment by aniketnath** [comment]
For which language is it showing?

**Comment by nicolas-raoul** [comment]
zh-hant
Chinese traditional (Taiwan)

**Comment by aniketnath** [comment]
ok. thank you

**Comment by nicolas-raoul** [comment]
What is the value of the English string, by the way?

**Comment by zhao-gang** [comment]
I have updated the translation in [translate wiki](https://translatewiki.net/w/i.php?title=Special:Translate&showMessage=commons-android-strings-welcome_help_button_text&group=commons-android-strings&language=zh-hant&filter=&optional=1&action=translate).

@aniketnath You should see https://github.com/commons-app/apps-android-commons/wiki/Translating-the-app to learn how to update the translations of the app :-)

@nicolas-raoul The English string is "More Information".

**Comment by nicolas-raoul** [comment]
Thanks @zhao-gang! Apparently app/src/main/res/values-qq/strings.xml contains the same problem, would you mind checking?

**Comment by nicolas-raoul** [comment]
```
$ grep -R 1333 *
app/src/main/res/values-qq/strings.xml:  <string name="welcome_help_button_text">\'\'\'\'\'This message is empty, and it\'s probably invalid\'\'\'. See bug report: https://github.com/commons-app/apps-android-commons/issues/1333 .\'\'</string>
app/src/main/res/values-qq/strings.xml:  <string name="nominated_see_more">\'\'This message is empty, and it\'s probably invalid. See bug report: https://github.com/commons-app/apps-android-commons/issues/1333 .\'\'</string>
app/src/main/res/values-zh-rTW/strings.xml:  <string name="welcome_help_button_text">此提示為空，可能無效。請見錯誤報告： https://github.com/commons-app/apps-android-commons/issues/1333 。</string>
app/src/main/res/values-zh-rTW/strings.xml:  <string name="nominated_see_more">此提示為空，可能無效。請見錯誤報告： https://github.com/commons-app/apps-android-commons/issues/1333 。</string>
```

**Comment by madhurgupta10** [comment]
@nicolas-raoul Can I fix that as well? I think the strings were not updated when the [#1333](https://github.com/commons-app/apps-android-commons/issues/1333) was closed

**Comment by nicolas-raoul** [comment]
@madhurgupta10 Yes please fix them on translatewiki as explained by Zhao, thanks! :-)

**Comment by madhurgupta10** [comment]
@nicolas-raoul
 
Fixed [app/src/main/res/values-zh-rTW/strings.xml:  <string name="nominated_see_more">](https://translatewiki.net/w/i.php?title=Special:Translate&showMessage=commons-android-strings-nominated_see_more&group=commons-android-strings&language=zh-hant&filter=&optional=1&action=translate)

Fixed [app/src/main/res/values-qq/strings.xml:  <string name="welcome_help_button_text">](https://translatewiki.net/w/i.php?title=Special:Translate&showMessage=commons-android-strings-welcome_help_button_text&group=commons-android-strings&language=qqq&filter=&optional=1&action=translate)


Fixed [app/src/main/res/values-qq/strings.xml:  <string name="nominated_see_more">](https://translatewiki.net/w/i.php?title=Special:Translate&showMessage=commons-android-strings-nominated_see_more&group=commons-android-strings&language=qqq&filter=&optional=1&action=translate)

As mentioned [here](https://github.com/commons-app/apps-android-commons/wiki/Translating-the-app) the translation to the app is done automatically, so I am closing my PR #2479 

Hope, this helps

**Comment by nicolas-raoul** [comment]
Thanks @zhao-gang and @madhurgupta10 for fixing this! :-)
