### ISSUE TITLE
Seemingly redundant strings that must be translated

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#2448]
I am asked to translate these 4 strings:
![screenshot from 2019-02-14 11-46-55](https://user-images.githubusercontent.com/99590/52759224-6ca75a00-304e-11e9-91e1-ed23ab64aedb.png)
It looks like the first string is not really necessary?
Same for the `Selfies or pictures of your friends` etc
Avoiding these duplications would be friendly to the translators.

**Comment by RajatChandel** [comment]
translate to which languages?

**Comment by zhao-gang** [comment]
@nicolas-raoul The first string is actually not used in the code. I removed this and similar two in the strings.xml. I think removing them is enough to let them not occur in translate wiki ?

**Comment by nicolas-raoul** [comment]
Yes, I believe translatewiki will notice that the strings are not needed anymore, and remove them from translations.

**Comment by zhao-gang** [comment]
@RajatChandel Hello. You should see https://github.com/commons-app/apps-android-commons/wiki/Translating-the-app to learn how to update the translations of this app. Also, you should not include other people's commits in your PR :-)
