### ISSUE TITLE
Wikidata query isn't returning updated edit count

### ISSUE THREAD

**Issue by maskaravivek** [commons-app/apps-android-commons#2458]
**Summary:** 

On checking the recent changes on wiki-data it shows edits being made every day with tag `#Wikimedia Commons app`. 

https://www.wikidata.org/w/index.php?hidebots=1&translations=filter&hidecategorization=1&tagfilter=wikimedia-commons-app&limit=500&days=30&hideWikibase=1&title=Special:RecentChanges&urlversion=2

But on checking the statistics in the DB, the count has not been changing for the past 1-2 months. 

https://quarry.wmflabs.org/query/33398

Is there an issue with the query? We are using the same query for showing edits in the Achievements activity.

**Comment by maskaravivek** [comment]
cc @urbanecm As you are familiar with the DBs, do you have any insights about why this could be happening?

**Comment by urbanecm** [comment]
Replag (https://tools.wmflabs.org/replag/ shows wikidatawiki_p is delayed by 20941 secs, but that wouldn't explain no change in several months. Let me investigate.

**Comment by urbanecm** [comment]
I found it. There was apparently a schema change, and ct_tag is not populated anymore. You have to filter by ct_tag_id. For wikimedia-commons-app, the corresponding tag id is 155.

**Comment by urbanecm** [comment]
Fixed, but looks I lack permissions to close this issue. Please re-test and close :-).

**Comment by maskaravivek** [comment]
Thanks a lot, @urbanecm. :)

**Comment by maskaravivek** [comment]
Thanks
