### ISSUE TITLE
Instance of railway station is "undefined" in nearby places screen

### ISSUE THREAD

**Issue by tobias47n9e** [commons-app/apps-android-commons#246]
<img width="250" src="https://cloud.githubusercontent.com/assets/6953323/18223527/7023e5c2-71ba-11e6-83e5-beb0a8163767.png">

https://www.wikidata.org/wiki/Q2264241 shows up as undefined but is p31 = railway station on Wikidata.

**Comment by nicolas-raoul** [comment]
Could you please post this issue at https://github.com/alemela/wiki-needs-pictures and post a link to it here?
Thanks :-)

**Comment by tobias47n9e** [comment]
Done: https://github.com/alemela/wiki-needs-pictures/issues/16

**Comment by misaochan** [comment]
Thanks for pointing this out, @tobias47n9e , I hadn't realized that. Hopefully if this can be resolved on their end, we might have fewer undefined items.

**Comment by nicolas-raoul** [comment]
I guess Wikidata does not have this issue? (for items that have an "instance of" defined)

**Comment by tobias47n9e** [comment]
We can probably close this issue.
