### ISSUE TITLE
Floating add button turns into a spot in landscape mode

### ISSUE THREAD

**Issue by Spartz1** [commons-app/apps-android-commons#2461]
**Summary:** 
After launching the app go to nearby tab and rotate the orientation to landscape and go back to contributions tab, the add button turns into a blue color spot.

**Steps to reproduce:** 

How can we reproduce the issue? 
Expected: The floating add button should retain it's state
Showing: A blue color spot instead

```

**Device and Android version:** 
Mi note 3
Android 6.0 Marshmallow
 
**Commons app version:** 
2.10.0


**Would you like to work on the issue?**

I would like to work on it

**Comment by nicolas-raoul** [comment]
Would you mind posting a screenshot? Thanks! :-)

**Comment by silkypriya** [comment]
Screenshot showing FAB in landscape orientation. 

![dot_fab](https://user-images.githubusercontent.com/25826255/54013037-f787fa00-419f-11e9-91b9-e0379644efe8.png)

Screenshot showing clicked FAB in landscape orientation. 

![clicked_fab](https://user-images.githubusercontent.com/25826255/54013338-de337d80-41a0-11e9-98dc-aa0426e03c57.png)

Hello @nicolas-raoul,
I would like to work on this issue.

**Comment by nicolas-raoul** [comment]
@silkypriya It is yours :-)
