### ISSUE TITLE
Nearby tab does not load the map

### ISSUE THREAD

**Issue by HaricharanDharmaji** [commons-app/apps-android-commons#2462]
**Summary:** 

Nearby tab takes forever to load map. The progressbar keeps rotating. But the map is being loaded in some devices. Even the menu on the top right corner does not load anything but the progressbar keeps rotating.

**Steps to reproduce:** 

1. Install and launch the app
2. Shift to Nearby tab on the home 
3. Give location permission on request

**Device and Android version:** 

Device: ASUS_X00DDB
Android Version: 8.1.0 - Oreo
 
**Commons app version:** 

2.10.0-debug-master-b5a479ce

**Screen-shots:** 

![whatsapp image 2019-02-14 at 19 32 08](https://user-images.githubusercontent.com/20542865/52791659-7309f600-308f-11e9-9a48-d38f181bab5e.jpeg)

![whatsapp image 2019-02-14 at 19 43 35](https://user-images.githubusercontent.com/20542865/52792267-f5df8080-3090-11e9-8e5a-2f02763ff4db.jpeg)

**Would you like to work on the issue?**

I am not sure where the problem is as it works fine on some devices. I will still try to fix the issue. Others are welcome to contribute.

**Comment by nicolas-raoul** [comment]
I think this is similar to #1309 ?
Let's exchange ideas over there :-)
