### ISSUE TITLE
Label overlaps number in Achievements

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#2465]
Should wrap instead.

![screenshot_20190215-132907](https://user-images.githubusercontent.com/99590/52834663-42c16680-3126-11e9-9ae1-cf8463e253a7.png)

**Comment by shabrikaruna** [comment]
i will fix this issue.

**Comment by silkypriya** [comment]
@nicolas-raoul , I would like to fix this issue.

**Comment by silkypriya** [comment]
Made pull request fixing this issue.
Kindly review.
Thank you!

**Comment by domdomegg** [comment]
Fixed in #2577
