### ISSUE TITLE
Is it really useful to localize this string? "Featured image author user name goes here"

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#2471]
It is in app/src/main/res/values/strings.xml and seems to be used in app/src/main/res/layout/fragment_media_detail.xml but I don't remember seeing it anywhere in the app.

1. Is it useful?
2. Does it apply only to featured images, and not for instance to images from search?

**Comment by zhao-gang** [comment]
<img width="239" alt="screen shot 2019-02-19 at 12 28 03" src="https://user-images.githubusercontent.com/692944/52990163-defaae80-3441-11e9-8165-8be36840e802.png">

The string is the placeholder for media detail page. I think we'd just need to change it to "Media author user name goes here" ?

**Comment by nicolas-raoul** [comment]
Yes, that would be better.

Are users supposed to see these strings?
If it is only used when debugging or when developing the UI, then these strings might not need localizations and thus might better be hard-coded.
If someone familiar with the topic sees this, please don't hesitate to explain to us :-)

**Comment by zhao-gang** [comment]
As in my above edited post says, users can see these strings when the media detail data is being fetched from the server. AFAIK these strings are used as a placeholder when the data has not been fetched from the server. So I think to some extend it's useful to translate these strings.

**Comment by nicolas-raoul** [comment]
If users can see them while details are believed fetched from the server, then I would argue that a generic "Loading..." label would be more informative and much simpler to translate to dozens of languages.

**Comment by misaochan** [comment]
Wow, I hadn't noticed these (especially the media details placeholder, lol!!). I agree that "Loading..."(or even just leaving them blank) would be preferable.

**Comment by zhao-gang** [comment]
If we use "Loading...", should we change the placeholder when fetching data failed or network is unavailable. I think placeholders in media detail fragment really have little meaning to the user. I prefer to leave these fields blank.

**Comment by nicolas-raoul** [comment]
OK for blank! @zhao-gang feel free to implement the changes if you want :-)

**Comment by zhao-gang** [comment]
@nicolas-raoul Ok. You can assign this issue to me so other people won't dig into this issue :-)
