### ISSUE TITLE
Click event not showing button layout without scrolling for last item in the list

### ISSUE THREAD

**Issue by madhurgupta10** [commons-app/apps-android-commons#2489]
**Summary:** 
Click event not working for last item in the list

**Steps to reproduce:** 
Launch the Nearby Option List and tap on last item.
![ezgif-2-1b35368e7582](https://user-images.githubusercontent.com/30932899/53006637-964fef00-345b-11e9-92c6-3e94ea5f2129.gif)

**Device and Android version:** 

Tested on Xiaomi Mi A1 running Android 9 Pie with Stock Android
 
**Commons app version:** 
betaDebug

**Would you like to work on the issue?**
Yes I want to fix this issue :)

**Comment by nicolas-raoul** [comment]
I can reproduce, good find! :-)

**Comment by misaochan** [comment]
Thanks @madhurgupta10 , it is yours. :)

**Comment by madhurgupta10** [comment]
@nicolas-raoul @misaochan I changed the issue title because the click event was working fine but the user needs to scroll manually to see the layout, also fixed it in PR #2491.
