### ISSUE TITLE
Collection of device's essential information when user want to share feedback 

### ISSUE THREAD

**Issue by madhurgupta10** [commons-app/apps-android-commons#2494]
**Summary:** 
When a user wants to share some feedback, the current scenario does not include the device name, model number, network type, etc. 
Automatically adding this to the email template would help the team to address the feedback precisely. 
![screenshot_20190220-211244](https://user-images.githubusercontent.com/30932899/53103862-5ae51b80-3554-11e9-8370-839eda816dfa.png)

**Steps to reproduce:** 
Open the app < hamburger menu < Feedback

**Would you like to work on the issue?**
Yes, I want to work on this issue :)

**Comment by madhurgupta10** [comment]
@nicolas-raoul Should I keep the support information same for all languages?

**Comment by nicolas-raoul** [comment]
@madhurgupta10 Localization would be a good thing, I would say.

**Comment by madhurgupta10** [comment]
@nicolas-raoul Cool, well in that case shall I just create strings in res file for English and translate would take care of the rest, right?

**Comment by nicolas-raoul** [comment]
Yes, that's it :-)

**Comment by madhurgupta10** [comment]
@nicolas-raoul Done, shall I add anything else?
![screenshot_20190221-143825](https://user-images.githubusercontent.com/30932899/53156965-89133b80-35e6-11e9-9bb3-0607567bc04a.png)

**Comment by nicolas-raoul** [comment]
Is that how it will appear to English-language users?
If yes, why not the friendlier "API level" instead of "API_LEVEL"? Same for
the others.

Also, since "App version" is in the body, we can remove it from the email
title :-)

Thanks!

**Comment by madhurgupta10** [comment]
@nicolas-raoul  Sure, I will make the changes

**Comment by madhurgupta10** [comment]
@nicolas-raoul I think keeping the app version in the title would be better than the body, but I can do it, either way, let me know :)

**Comment by nicolas-raoul** [comment]
I let you choose what you think is best :-)

**Comment by madhurgupta10** [comment]
@nicolas-raoul PR is ready :)

**Comment by maskaravivek** [comment]
@nicolas-raoul will localising these strings be useful? Most of the people who are part of the commons and commons private Google groups understand English whereas if these meta deta come in any of the ~50-100 supported languages then it might be difficult to interpret.

As these strings would be seen by one who is reading the feedback/logs IMO it would be better not lo localise it. 

My understanding might be wrong. Please correct me if I am missing something. :)

**Comment by nicolas-raoul** [comment]
From the perspective of a non-technical non-English-language person who wants to send feedback about the app, it might be scary to have obscure codes and words in a language you do not understand added to your feedback.

For us English-speaking developers the content sounds obvious, but imagine you want to send feedback about something and this text gets attached to your email:
```
الشركة المصنعة 98942367423962
الجهاز 460234530942
موديل 49386243968
```
Would you press `Send`? Would you not be at least a little bit tempted to erase it or not send the email at all?
That being said, I am also OK with not localizing that part.

**Comment by madhurgupta10** [comment]
@nicolas-raoul I agree this will be scary, as the person doesn't know what information is attached to the email. What if we replace `--Support-Info--` with something that explains the information attached below like `Down below we have added some information which will help developers to help you better, you don't need to change anything below`

**Comment by nicolas-raoul** [comment]
@madhurgupta10 I think `Technical information` would be clear enough :-)

**Comment by madhurgupta10** [comment]
@nicolas-raoul @maskaravivek  Okay 👍 I will make the changes, thanks for the discussion :)
