### ISSUE TITLE
"uploaded by myself", "used by", and several other lego messages 

### ISSUE THREAD

**Issue by amire80** [commons-app/apps-android-commons#2498]
**Summary:** 

I've been reviewing the translatable strings for the Commons app, and I noticed that several of them are what we call "lego messages" in the Wikimedia jargon: strings that are translated separately and concatenated with each other and with other parameters in run time.

Lego messages are a localization antipattern in any software project. They don't take into account that different languages have different word order. Messages must be written as complete phrases, and parameters such as filenames, usernames, dates, upload counts, etc., must always be filled as parameters.

Some messages that are almost certainly lego are:
* "Uploaded by myself on" (the date should probably be a parameter)
* ",used in" (the comma tells me that it's probably a part of another sentence)

There may be more strings of this kind that I haven't noticed till now.

Please fix all of these and move them to one message.

For more information about "lego messages", see the page https://www.mediawiki.org/wiki/Localisation#Avoid_fragmented_or_'patchwork'_messages . It was written for MediaWiki developers, but this part, as well as many others, applies to localization of any software project.

Thanks! :)

**Comment by chris-fo** [comment]
Can I try to work on this?

**Comment by nicolas-raoul** [comment]
@chris-fo Yes, it is yours! :-)

**Comment by chris-fo** [comment]
I`m sorry that it is taking a while, but I have been quite busy the last few days. After tomorrow I will have more time again and I think I will be able to fix this by Sunday. Is that ok?

**Comment by nicolas-raoul** [comment]
@chris-fo OK!
