### ISSUE TITLE
Nicer icons for description types in list of nearby places

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#250]
The list of nearby places needing photos (see #73) uses icons from openclipart.org to denote the type of location (e.g. landmark, city, edu, event, mountain, isle). As these are all by different artists, they have different styles. As suggested by @tobias47n9e , custom clip art with a coherent style would probably look much more aesthetically pleasing.

**Comment by tobias47n9e** [comment]
I reached out, but so far nobody has answered: https://commons.wikimedia.org/wiki/Commons:Graphic_Lab/Illustration_workshop#Commons_App

**Comment by nicolas-raoul** [comment]
Thanks Tobias, looks like it was a good idea to ask:
https://commons.wikimedia.org/wiki/Category:Landmark_icons_by_User:BMacZero :-)
Do we have a place for credits/etc? If yes we could add the name of the icons creator.

**Comment by misaochan** [comment]
Cool! Yeah, I can put him in the credits.md file (although that file only shows up on GitHub and not in the app - do we want it to?). I'll do that after I've gotten the icons in.

**Comment by nicolas-raoul** [comment]
credits.md is fine, as the license is CC0

**Comment by misaochan** [comment]
Should we tell him that we'd like an icon for 'undefined' as well? That sounds like a slightly odd request (how do you draw undefined?), but that would have the biggest impact by far I think since so many items are undefined.

**Comment by nicolas-raoul** [comment]
I think so. I posted that as an addition.

**Comment by misaochan** [comment]
Sounds good.  :) I'll be away for two weeks from the 20th, so I'll put in whatever icons are ready by next week I guess, and do the rest after I get back? Or better to do all of them together later?

**Comment by nicolas-raoul** [comment]
It can be good to merge early to detect any unforeseen problem :)

**Comment by tobias47n9e** [comment]
This query shows what the most missing images by type (P31 statement) are. You can switch the country to see what is missing most in your area:

https://query.wikidata.org/#SELECT%20%3Ftype%20%3FtypeLabel%20%3Fcount%20WHERE%20%7B%0A%20%20%7B%0A%20%20%20%20SELECT%20%3Ftype%20%28COUNT%28%3Fitem%29%20AS%20%3Fcount%29%20WHERE%20%7B%0A%20%20%20%20%20%20%3Fitem%20wdt%3AP625%20%3Fcoord.%0A%20%20%20%20%20%20%3Fitem%20wdt%3AP17%20wd%3AQ145.%0A%20%20%20%20%20%20%3Fitem%20wdt%3AP31%20%3Ftype.%0A%20%20%20%20%20%20FILTER%28NOT%20EXISTS%20%7B%20%3Fitem%20wdt%3AP18%20%3Fimage.%20%7D%29%0A%20%20%20%20%7D%0A%20%20%20%20GROUP%20BY%20%3Ftype%0A%20%20%7D%0A%20%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22en%22.%20%7D%0A%7D%0AORDER%20BY%20DESC%28%3Fcount%29

**Comment by tobias47n9e** [comment]
Can we maybe have the mapping between symbols and Q-IDs in a separate file, so it is not too difficult to contribute to it. For example the house icon could be used for https://www.wikidata.org/wiki/Q879050 and https://www.wikidata.org/wiki/Q3947 

Even with 20 icons this switch might become too long otherwise: https://github.com/misaochan/apps-android-commons/blob/4b01f6e95f79cc507dba1ea0ff8335eef9b11521/app/src/main/java/fr/free/nrw/commons/nearby/NearbyListFragment.java#L192

**Comment by misaochan** [comment]
Wow, interesting. I had no idea there were so many types!

@tobias47n9e great idea, I think it would definitely be wise to reuse some icons. How do you think the mapping should work though, is there a way to do it without any switch blocks? 

I don't know if I will have the time to do a major overhaul of the switch in this IEG round, but if anyone can do it I would be more than happy to merge.  :) Otherwise I could give it a shot after I have completed all my required tasks.

**Comment by misaochan** [comment]
Also, do we actually have an 'unknown manmade' and 'unknown natural' type, as shown in the list of icons bmaczero made? I don't think there's any way to distinguish between the various 'undefined' items?

**Comment by tobias47n9e** [comment]
In theory it would be possible to distinguish natural from man-made objects. In practice it seems to be a little more complicated.

This graph shows the p279 (subclass) of 'geographical object'. Already in the first order link we have quite some complexity:

https://angryloki.github.io/wikidata-graph-builder/?property=P279&item=Q618123&iterations=1&mode=reverse

Using 2 iterations we have some clusters that fall into either category, but there doesn't seem to be an easy solution for this problem. Maybe we can distinguish it for the easy cases and just ignore it for the more complex cases (e.g. landscapes which can be a mix of natural and man-made).

**Comment by nicolas-raoul** [comment]
I don't think the length of the switch is something to worry about.
Having a mapping is a good idea, be it as a switch statement or as a data
file.

**Comment by misaochan** [comment]
Hrmmmm. In that case I think I'll just use one of the "?" icons for the 'undefined' type, and leave natural vs man-made for a future optimization, heh.

**Comment by misaochan** [comment]
The icons have been added, so closing this despite the QID issues (see #260 ).
