### ISSUE TITLE
Swipe to delete specific recent searches

### ISSUE THREAD

**Issue by madhurgupta10** [commons-app/apps-android-commons#2502]
**Summary:** 
Adding Swipe Gesture to Delete Recent searches will make the app more user-friendly.

**Steps to reproduce:** 
Hamburger Menu < Explore < Click on Search Button

**Screen-shots:** 
![screenshot_20190221-164327](https://user-images.githubusercontent.com/30932899/53165231-2e82db00-35f8-11e9-81e9-5fa9d83ecb9e.png)

**Would you like to work on the issue?**
Yes, I want to work on this issue :)

**Comment by misaochan** [comment]
Hmmm. What would be the benefit of adding the swipe feature over the existing bin icon?

**Comment by madhurgupta10** [comment]
@misaochan When using the app with Left hand, it is difficult for the user to reach the bin button, a swipe gesture where the user can swipe from left to right will be helpful.
Also, I don't want to remove the bin icon, but having both options will be great.

**Comment by albendz** [comment]
Just to clarify, should this be for swipe in any direction?

An alternative is to have swipe right to be delete and swipe left to search again. I'm in favor of delete in any direction but if we are adding swipe gestures at all it would be good to consider how they are used in other apps.

**Comment by madhurgupta10** [comment]
@albendz yes we can have different swipe gesture for different task

**Comment by BinduVerma123** [comment]
@madhurgupta10 can i work on this issue?

**Comment by madhurgupta10** [comment]
@albendz @misaochan any updates on this issue?

**Comment by misaochan** [comment]
I'm still not certain about this - it feels like we would be adding complexity for very little gain IMO. For instance, the Wikipedia app does not have swipe to delete recent searches either - presumably they consider the bin icon to be sufficient.

An implementation that I think COULD add functionality, would be to allow swipe to individually delete searches, since currently the bin icon deletes all of them and there are no individual options.

**Comment by madhurgupta10** [comment]
@misaochan we can implement the swipe to delete individual search.

**Comment by madhurgupta10** [comment]
@misaochan Can I start implementing swipe to delete individual search? :)

**Comment by domdomegg** [comment]
@madhurgupta10 

We can now click and hold to remove a specific search (see #2275) so adding the extra gesture might not be worth it - up to you. If you do decide to go ahead ideally use the same handler function.

I think you can try implementing swipe to delete, and it may be merged as long as it's a small change (i.e. ideally just add another listener, without adding any extra libraries). I think it will probably not be worth it if it adds a lot of complexity - the app already has many bugs and we don't want to add more. If you're burning to get working on something there are plenty other issues you could have a look at taking up - we desperately need more tests too!

Either way please comment what your plans are on this.

**Comment by madhurgupta10** [comment]
@domdomegg I agree that it will not be the best to make the app more complicated by adding a small feature. I will try to experiment with this change and if you think the change won't make the app more complicated, then we can merge it. I will keep this on low priority and focus more on other potential issues :)

**Comment by ujjwalagrawal17** [comment]
@madhurgupta10 I think it's better to skip this for now. I am closing this issue now. Feel free to reopen this issue if you think your solution will add value to the app.
