### ISSUE TITLE
Nearby map window gets deformed when switching from map tab to contributions and then back

### ISSUE THREAD

**Issue by VojtechDostal** [commons-app/apps-android-commons#2507]
steps to reproduce:

1) load Nearby map
2) switch to Contributions tab.
3) switch back to Nearby map

I am using 2.10.0

**Comment by VojtechDostal** [comment]
![screenshot_20190222-153859](https://user-images.githubusercontent.com/21329813/53249309-12df0980-36b8-11e9-8353-21dcd3e35246.jpg)

**Comment by misaochan** [comment]
Interesting. I am not able to reproduce this on 2.10.1.

Could you update to 2.10.1 (it should be out in beta by now) and see if it happens again? If it does, please send us your logs (via Settings > Send Logs).

**Comment by VojtechDostal** [comment]
Yep it still happens after I updated.I sent you logs :)

**Comment by neslihanturan** [comment]
Hi @VojtechDostal , is it something like you see a black rectangle on bottom of screen or does the height of map become smaller?

Can you also please share a normal screen to compare them with deformed screen?

**Comment by VojtechDostal** [comment]
It seems like the dimensions of the map get screwed. 
![screenshot_20190223-135631](https://user-images.githubusercontent.com/21329813/53286746-47fc6200-3773-11e9-9396-f46d0e51dfce.jpg)
![screenshot_20190223-135640](https://user-images.githubusercontent.com/21329813/53286749-4df24300-3773-11e9-861e-3bec8d194c24.jpg)

**Comment by albendz** [comment]
Just a thought: sometimes I see this on other apps when automatic screen rotation is enabled or if the screen was in a different view when the app started.

**Comment by nicolas-raoul** [comment]
I have never seen this happen, despite switching back and forth between the two tabs many times the past two days.

**Comment by VojtechDostal** [comment]
@albendz This doesn't seem to be the case, I have screen rotation disabled.

**Comment by misaochan** [comment]
Hmm. Does it happen consistently for you @VojtechDostal , or only sometimes?

**Comment by VojtechDostal** [comment]
Always... :)

**Comment by misaochan** [comment]
Hmm, very interesting. The map should not be updating every time you switch tabs...  

Does it also happen when you switch very quickly, without having moved location?

**Comment by VojtechDostal** [comment]
No, the "return to normal dimensions by update of the map" does not happens everytime I switch tabs. Only sometimes :) probably only when location changes. I was just trying to explain that the problem does not go away unless the map update happens.

**Comment by VojtechDostal** [comment]
Interestingly, I found out that the problem can be 'rescued' by tapping the Task Switcher/Recent apps button (the square) and then navigating back to the app window.

**Comment by VojtechDostal** [comment]
This stopped after I switched to a new phone. Without any other case available, we can probably close the issue.

**Comment by neslihanturan** [comment]
Good idea @VojtechDostal , nearby is being refactored currently. Might be solved meanwhile.

**Comment by sivaraam** [comment]
I think I'm facing a similar issue in my device now. But for me it is the "Contributions" screen in which I see the black part in the bottom of the screen. It happens to me consistently when I switch to "Nearby" and then back to "Contributions". It only goes away when there is a screen update in the Contributions page (e.g., when a "Nearby location" card is shown above the contributions).

I'm using version 2.12.0.514 of the app. My device runs Android 5.1.1

**Normal screen**
![Screenshot_2019-12-05-23-22-00](https://user-images.githubusercontent.com/12448084/70260765-fdeee500-17b6-11ea-8c6a-72d4a6fb7286.png)


**Screen with black part in bottom**
![Screenshot_2019-12-04-00-09-20](https://user-images.githubusercontent.com/12448084/70260771-02b39900-17b7-11ea-81e2-641cf3db0ae5.png)
