### ISSUE TITLE
Count on Contributions does not update on deletion

### ISSUE THREAD

**Issue by madhurgupta10** [commons-app/apps-android-commons#2509]
**Summary:** 
If we delete a photo, the number of contributions do not change until the app is restarted.
#2377 & #2324 are similar but does not mention this specific case.
![ezgif-5-5827a67ba2ac](https://user-images.githubusercontent.com/30932899/53289424-db598580-37bb-11e9-95ae-95c749738cd5.gif)

**Steps to reproduce:** 
Delete the file which is not uploaded and you will see the count of contributions is not uploaded.

**Device and Android version:** 
Xiaomi Mi A1, with API level 28 running stock android
 
**Commons app version:** 
betaDebug

**Would you like to work on the issue?**
Yes, I want to work on this issue :)

**Comment by maskaravivek** [comment]
The contribution gets counted only after a upload is successful

**Comment by madhurgupta10** [comment]
@maskaravivek in my case the contribution do get updated even if the upload fails and do not updates when uploaded file is removed.

**Comment by maskaravivek** [comment]
> upload fails
not updating as this upload was never counted

> uploaded file is removed
again the file was still not fully uploaded to server. so canceling an upload won't affect the count.

**Comment by madhurgupta10** [comment]
@maskaravivek got it, thanks for the clarification. Should I close this issue?

**Comment by maskaravivek** [comment]
Closing it
