### ISSUE TITLE
Switching from action bar to navigation drawer

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#251]
The action bar is getting pretty crowded and some of the items (About, Settings, Nearby) should ideally be placed in a navigation drawer instead. This requires a bit of an overhaul, as AFAIK proper navigation drawer implementation would require the activities to be converted to fragments. 

I initially started on this (see https://github.com/misaochan/apps-android-commons/tree/nav-drawer-hamburger) but encountered issues that I could not resolve (see http://stackoverflow.com/questions/39010912/actionbardrawertoggle-disappears-when-addtobackstacknull-is-used ).

**Comment by tobias47n9e** [comment]
Did you already do some drawings of how it should look? I think the current Wikipedia app is a good example to aim at. For this app I think we should also leave some space for gamification elements. The elements could be discusses in a seperate thread, but something like number of downloads would be motivating. I also like the concept of streaks (e.g. Duolingo). For this app that could be the count of consecutive weeks/days that the user has uploaded a picture (Not just on mobile, which probably makes it easier to query that from Commons API?).

**Comment by misaochan** [comment]
Haha, no, I don't have any drawings of how it should look - if I tried, it'd probably look worse than it currently does. ;) I think if a reasonably experienced artist were to want to help us out with it, I personally would be happy to leave the choice of style entirely up to them.

I really like the gamification ideas you mentioned. There already is a basic thread at #85 , but it would be great  if you could add your ideas there.

**Comment by misaochan** [comment]
Edit: Oh, I got confused between this and the icons thread. I was initially planning for just a basic material design nav drawer (in black).

**Comment by misaochan** [comment]
I am taking the liberty of marking this as high priority, as I feel that this needs to be handled before too many more new features are added.

**Comment by maskaravivek** [comment]
@tobias47n9e @misaochan We might want to keep the issue open until the drawer is made theme specific.

**Comment by misaochan** [comment]
This has largely been done, but there are a few issues that need fixing:

1. Only the main activity, Nearby, About, and Settings should have the hamburger menu icon IMO. The other screens that people will actually want to go back from (the entire upload process, and media detail view) should still have a backbutton IMO.

2. The hamburger menu icon occasionally disappears from the action bar (e.g. in the main activity after returning from other activities).

3. We should change the title of the main activity back to "My recent uploads" (currently says "Commons").
