### ISSUE TITLE
Find ideas we can reuse from "Commons Lab" (similar app on Play store)

### ISSUE THREAD

**Issue by sivaraam** [commons-app/apps-android-commons#2510]
I recently came across ["Commons Lab"](https://play.google.com/store/apps/details?id=com.commons.lab.app) which is also an Android app with the description "_Upload photos, videos, and audios directly from your phone to Wikimedia Commons. No need to transfer your files to your desktop to upload on Wikimedia anymore._" I haven't seen this before but the information from Play store states the app was last updated in Oct 2017.

I tried using the app and to be honest the UI seems very nice. It's very simple and allows you to upload Photos, Audio and Video. Also it shows your contributions. It does seem to have it's own bugs. I'm not sure who is maintaining the app but just found it in the wild and noted that it seems to be an app which seems very similar to the "Wikimedia Commons" app. It doesn't seem to have been updated in a while though. So, I thought I could bring it to the notice of people here.

Has anyone heard/seen it before?

**Comment by nicolas-raoul** [comment]
Yes I tried it a long time ago, I remember it was lacking in the area of categorization but otherwise a nice app.

Don't hesitate to post more findings about it, things that we should get inspiration from, and screenshots :-) Thanks!

**Comment by sivaraam** [comment]
> Don't hesitate to post more findings about it, things that we should get inspiration from, and screenshots :-) Thanks!

I think I really should've got the screenshots. The app appears to be gone from play store now. My search to find some other way to get the APK, didn't go well either. So, closing this for now. Do re-open if you find any other way to try out the app.
