### ISSUE TITLE
Move \n\n from translations to Java

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#2512]
Per https://github.com/commons-app/apps-android-commons/commit/3a822d3c3034955471639c3962d74c05e6ee9dec#r32453577

**Comment by maskaravivek** [comment]
Apologies, I was the one who made this change in @vanshikaarora's repo https://github.com/vanshikaarora/apps-android-commons/pull/4  :(

Have raised a PR to fix this.
