### ISSUE TITLE
Duplicate "date" parameter in Information template

### ISSUE THREAD

**Issue by VojtechDostal** [commons-app/apps-android-commons#2514]
<img width="203" alt="bez nazvu" src="https://user-images.githubusercontent.com/21329813/53342527-719dc080-390e-11e9-808d-f3f648de5ec2.png">
My recent uploads have duplicate "date" parameter in the Information template, see attached image.

Same issue is observed in other users's recent files:
https://commons.wikimedia.org/wiki/File:Shinto_Taikyo.jpg

I guess we should first fix the issue and then fix the occurences as well.

Issue created as instructed in #2511

**Comment by misaochan** [comment]
This is out in master now, should be deployed on alpha builds in a few hours. Please let us know if it works for you. :)

**Comment by VojtechDostal** [comment]
Very cool, thank you :) I probably fixed most if not all occurences of the error in existing files on Wikimedia Commons.

**Comment by maskaravivek** [comment]
> Very cool, thank you :) I probably fixed most if not all occurences of the error in existing files on Wikimedia Commons.

Thanks a lot @VojtechDostal 🎉
