### ISSUE TITLE
Migrate from Icafe to metadata-extractor

### ISSUE THREAD

**Issue by vanshikaarora** [commons-app/apps-android-commons#2518]
**Summary:** 

As discussed in https://github.com/commons-app/apps-android-commons/pull/2383. 
Metadata-extractor is to be used in place of Icafe for reading facebook metadata

**Would you like to work on the issue?**

Yes

**Comment by vanshikaarora** [comment]
>From what I checked both libraries add very little to the size of the final APK.

@maskaravivek have you successfully received IPTC using metadata extractor
```
metadata = ImageMetadataReader.readMetadata(new File(path));
            for (Directory directory : metadata.getDirectories()) {
                for (Tag tag : directory.getTags()) {
                    System.out.format("[%s] - %s = %s",
                            directory.getName(), tag.getTagName(), tag.getDescription());
                    System.out.println();
                }
                if (directory.hasErrors()) {
                    for (String error : directory.getErrors()) {
                        System.err.format("ERROR: %s", error);
                    }
                }
            }
```

I got the following output:
```
/System.out: [JPEG] - Compression Type = Progressive, Huffman
    [JPEG] - Data Precision = 8 bits
I/System.out: [JPEG] - Image Height = 1123 pixels
    [JPEG] - Image Width = 540 pixels
    [JPEG] - Number of Components = 3
    [JPEG] - Component 1 = Y component: Quantization table 0, Sampling factors 2 horiz/2 vert
I/System.out: [JPEG] - Component 2 = Cb component: Quantization table 1, Sampling factors 1 horiz/1 vert
    [JPEG] - Component 3 = Cr component: Quantization table 1, Sampling factors 1 horiz/1 vert
I/System.out: [JFIF] - Version = 1.1
    [JFIF] - Resolution Units = none
I/System.out: [JFIF] - X Resolution = 1 dot
    [JFIF] - Y Resolution = 1 dot
I/System.out: [JFIF] - Thumbnail Width Pixels = 0
    [JFIF] - Thumbnail Height Pixels = 0
I/System.out: [Huffman] - Number of Tables = 2 Huffman tables
    [File Type] - Detected File Type Name = JPEG
    [File Type] - Detected File Type Long Name = Joint Photographic Experts Group
I/System.out: [File Type] - Detected MIME Type = image/jpeg
    [File Type] - Expected File Name Extension = jpg
    [File] - File Name = 00675657-3f07-4328-a9de-8f5d2ef34e7b.jpg
    [File] - File Size = 38384 bytes
I/System.out: [File] - File Modified Date = Tue Feb 26 14:27:35 +05:30 2019
```

Also searching  for IPTC i got a null response:

![screenshot from 2019-02-26 14-55-33](https://user-images.githubusercontent.com/34261945/53401917-c442af80-39d6-11e9-8a23-b81c479695c0.png)

@nicolas-raoul @maskaravivek Can you please look into this :)

**Comment by maskaravivek** [comment]
I can check this on Monday. :)

**Comment by vanshikaarora** [comment]
Whenever you get time :)

**Comment by vanshikaarora** [comment]
@maskaravivek  Have you gone through it?

**Comment by maskaravivek** [comment]
@vanshikaarora I am able to retrieve the IPTC information using metadata-extractor. Instead of using the file path, I used the original `contentUri` in `UploadableFile`. 

When an image is picked, the app copies the file to a local path (see `PickedFiles:pickedExistingPicture`). It's possible that some of the metadata information is lost while creating the file. 

You might have noticed that even for extracting EXIF date/time information, the app uses `contentUri` ie `UploadableFile:getDateTimeFromExif`. 

Here's the snippet that I used:

```
private void getIPTC(Context context) {
        Metadata readMetadata = null;
        try {
            readMetadata = ImageMetadataReader.readMetadata(context.getContentResolver().openInputStream(contentUri));
        } catch (ImageProcessingException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        }

        IptcDirectory iptcDirectory = readMetadata != null ? readMetadata.getFirstDirectoryOfType(IptcDirectory.class) : null;
        if (iptcDirectory == null) {
            return;
        }
        for (Tag tag : iptcDirectory.getTags()) {
            Timber.d("%s: %s", tag.getTagName(), tag.toString());
        }
    }
```

Screenshot with IPTC information: 

<img width="1440" alt="screen shot 2019-03-05 at 11 56 43 pm" src="https://user-images.githubusercontent.com/3069373/53827978-639d0f00-3fa2-11e9-855e-5a4adda445e3.png">

**Comment by maskaravivek** [comment]
You can add the `contentUri` field in `UploadItem`. 

`checkFBMD` method can pass the `contentUri` instead of `path`. 

Then you can get the original input stream using: 

```
context.getContentResolver().openInputStream(contentUri)
```

**Comment by vanshikaarora** [comment]
@maskaravivek Is the contentUri useful for other code or should I generate content Uri from file path while calling the `checkFBMD` method?

**Comment by maskaravivek** [comment]
Generating contentUri from the file path won't help as it would be of the copied file.

**Comment by vanshikaarora** [comment]
>You can add the contentUri field in UploadItem

@maskaravivek Since the content uri wasn't required anywhere else hence I didn't created a variable for contentUri but i had generated the Uri in UploadItem

Here is the submitted PR https://github.com/commons-app/apps-android-commons/pull/2546 kindly review :)

**Comment by vanshikaarora** [comment]
>Generating contentUri from the file path won't help as it would be of the copied file.

So should i first create a file from that path?

**Comment by maskaravivek** [comment]
- `UploadableFile` has a field called `contentUri`. 
- add a field called `contentUri` in `UploadItem`. populate this field using `UploadableFile`'s `contentUri`

**Comment by vanshikaarora** [comment]
>populate this field using UploadableFile's contentUri
