### ISSUE TITLE
Last picture always displayed again and again in a category

### ISSUE THREAD

**Issue by plarus** [commons-app/apps-android-commons#2523]
**Summary:** 

In category:Velles (Indre) I have an infinite scrolling with last picture always displayed again and again

**Steps to reproduce:** 
Go to category:Velles (Indre)
Scroll down

**Device and Android version:** 
Honor Play, android 9
 
**Commons app version:** 
Commons Android App (2.10.0~4a08a129)

**Screen-shots:** 
![screenshot_20190227_001443_fr free nrw commons](https://user-images.githubusercontent.com/16477554/53473586-0ddcda00-3a6b-11e9-8c06-c94505087266.jpg)

**Comment by zhao-gang** [comment]
I think this issue is the same as #2182 

There is a PR solved the indefinite repeated image issue and waiting to be merged.

**Comment by nicolas-raoul** [comment]
Thanks @piarus and @zhao-gang !
Let's continue the discussion at #2182 :-)
