### ISSUE TITLE
Achievements: Put Nearby above featured and thanks

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#2524]
App users are much more likely to find/upload nearby images, than to get their images featured and receive thanks (these two don't happen much to people who are not active on talk pages, and our app is not focused on talk pages, at all).

So, it would make sense to move the `Images via "Nearby Places"` item two lines up:
![adb-screenshot](https://user-images.githubusercontent.com/99590/53482957-c2a2e580-3ac3-11e9-829e-e5fe0045a874.png)

**Comment by misaochan** [comment]
Good point!

**Comment by madhurgupta10** [comment]
@nicolas-raoul I want to work on this issue :)

**Comment by maskaravivek** [comment]
Sure take this up @madhurgupta10 :)

**Comment by twisted-sres** [comment]
Hey, I am an outreachy applicant. Please let me know if I could take this up?

**Comment by madhurgupta10** [comment]
@twisted-sres already working on it, you can solve some other issue :)
