### ISSUE TITLE
Show caption instead of filename (in my contributions and Explore)

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#2525]
Caption from Structured Commons, localized in the user's language.
Fall back to filename if no caption is available.

**Comment by BinduVerma123** [comment]
Hello @nicolas-raoul i am an outreachy applicant..I would like to work on this issue.

**Comment by nicolas-raoul** [comment]
@BinduVerma123 It is yours :-)
Here is the API you will have to use: https://github.com/commons-app/apps-android-commons/issues/2337#issuecomment-470782124

**Comment by sp2710** [comment]
@nicolas-raoul does this mean we should remove Title field from media details and add Captions instead of it?

**Comment by nicolas-raoul** [comment]
Yes, if a caption is available in the user's language, it should be shown, and the title not shown.

_(for those wondering: the title can still be obtained if needed via the "copy wikitext" button)_

**Comment by sp2710** [comment]
In that case some minor changes in #2662 will be enough to solve the issue.

**Comment by nicolas-raoul** [comment]
@BinduVerma123 Any progress on this?
Please share anything you might have found out, things that worked and also things that did not work if any :-)

**Comment by nicolas-raoul** [comment]
@vanshikaarora This needs to be implemented. It is the most important part of the GSoC to make the app more localized :-)

How to reproduce:

1. Set Android language to English or French or Japanese
2. Open the app
3. Tap "Explore"
4. Tap the search icon
5. Enter "tantanmen"
6. Scroll until you see this picture: https://commons.wikimedia.org/wiki/File:Tantanmen.jpeg

Expected: The app labels the picture using its caption in Android's language, for instance English or French or Japanese
Problem: The app labels the picture using its filename "Tantanmen" (which is not any of the captions)

Screenshots: 
![adb-screenshot](https://user-images.githubusercontent.com/99590/61614467-c6b3e780-ac9e-11e9-98ce-3473426f4db9.png)

![adb-screenshot](https://user-images.githubusercontent.com/99590/61614364-7c326b00-ac9e-11e9-9670-00dafa65aeb9.png)

**Comment by vanshikaarora** [comment]
@nicolas-raoul I am currently working on this :)

**Comment by nicolas-raoul** [comment]
I believe this is now implemented in all places where titles (filenames) were shown before.
(in Vanshika's upload_caption_depict branch)
If you find any other place where captions could be used, please let us know :-)
