### ISSUE TITLE
Add CC 4.0 to license options?

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#254]
Suggested by A. L. on Google Play:

> More permissions choice needed The software only allows cc-0, cc-by-3.0 and cc-by-sa-3.0 yet there's no option to choose cc 4.0. It needs to be updated to include this option

Should this be implemented? Thoughts?

**Comment by nicolas-raoul** [comment]
It would seem sensible to have all licenses that the web Upload Wizard has, I would say.

**Comment by misaochan** [comment]
- [ ] Modify SettingsActivity.java and Prefs.java to add new license options

The current options on the Upload Wizard are:

Creative Commons Attribution ShareAlike 4.0 (legal code)
Creative Commons Attribution ShareAlike 3.0 (legal code)
Creative Commons Attribution 4.0 (legal code)
Creative Commons Attribution 3.0 (legal code)
Creative Commons CC0 Waiver (release all rights, like public domain: legal code)

So we would be adding cc-by-4.0 and cc-by-sa-4.0 , right?

**Comment by misaochan** [comment]
Is anyone interested in picking this up? It seems like a fairly good task for anyone wanting to get started with this codebase. :)

**Comment by misaochan** [comment]
This has been closed due to duplicate - please see #144
