### ISSUE TITLE
Place `google()` repository as the first priority repository

### ISSUE THREAD

**Issue by moksh-mahajan** [commons-app/apps-android-commons#2540]
**Summary:** 

In build. gradle file jcenter() repository have first priority than google() repository. My idea is to Place google() repository as the first priority repository to avoid such errors like:
**Failed to resolve: multidex-instrumentation**
Here is a [link](https://stackoverflow.com/questions/45608362/android-studio-3-0-beta-1-failed-to-resolve-com-android-supportmultidex1-0-2) to check to solve this error.

**Steps to reproduce:** 

How can we reproduce the issue? 
Open Project level build.gradle file and under Repsository, see that jcenter() repository is placed before google() repository.

What did you expect the app to do, and what did you see instead?
Placing google() repository before jcenter() repository.

**Would you like to work on the issue?**
Yes

**Comment by maskaravivek** [comment]
Go ahead with this change @moksh-mahajan

**Comment by moksh-mahajan** [comment]
@maskaravivek on it.
