### ISSUE TITLE
Campaigns bar icon position in right-to-left languages

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#2544]
For right-to-left languages, the icon should appear on the right, like the nearby icon:

![adb-screenshot](https://user-images.githubusercontent.com/99590/53876405-0c527980-404a-11e9-8961-946138bd4373.png)

**Comment by vanshikaarora** [comment]
Hey I can work on this issue!

**Comment by nicolas-raoul** [comment]
@vanshikaarora It is yours :-)

**Comment by vanshikaarora** [comment]
>@vanshikaarora It is yours :-)

Thanks @nicolas-raoul I have submitted  a PR  [here](https://github.com/commons-app/apps-android-commons/pull/2550). Kindly review :)
