### ISSUE TITLE
Achievements broken in right-to-left languages

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#2545]

**Comment by nicolas-raoul** [comment]
![screenshot_20190306-202818](https://user-images.githubusercontent.com/99590/53878427-30648980-404f-11e9-80de-4194f40d88e6.png)

**Comment by silkypriya** [comment]
Hello @nicolas-raoul, I am an outreachy applicant and I want to work on this issue.Could I take this?

**Comment by nicolas-raoul** [comment]
@silkypriya Yes, it is yours :-)
Let us know about your progress like every two days at least, thanks!

**Comment by silkypriya** [comment]
Hello @nicolas-raoul 
Made pull request #2557 fixing this issue.Kindly review.
would love your feedback.
Thank you!
