### ISSUE TITLE
Some properties are lost in failed uploaded images

### ISSUE THREAD

**Issue by zhao-gang** [commons-app/apps-android-commons#2547]
**Summary:** 

If image uploading failed, we can try later in CONTRIBUTIONS fragment. But some properties are not saved to Contribution database and they are lost. This caused the problem that these properties have to be manually added/edited after we successfully uploaded the failed image.

**Steps to reproduce:** 

Upload an image with location and categories, interrupt the uploading process, so the image appears as Failed in contribution list.

Re-uploading this image in contribution list.

The location and categories properties are lost in the re-uploaded image.

Expected:
Re-uploaded image has its previously set location and categories properties.

**Device and Android version:** 

Unrelated
 
**Commons app version:** 

current master

**Would you like to work on the issue?**

Yes

**Comment by Kiraeraser** [comment]
I would like to work on this issue

**Comment by nicolas-raoul** [comment]
@Kiraeraser Sorry this issue is assigned already but you can find others [here](https://github.com/commons-app/apps-android-commons/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+no%3Aassignee+-label%3Aassigned+-label%3Adebated), cheers!

**Comment by neslihanturan** [comment]
I have closed previous sleeping PR. Anyone who claims the issue, please make sure you have inspired from the changes there. These changes were almost done with some minor details.

**Comment by nicolas-raoul** [comment]
This issue was fixed and a release is available. Is it still happening? If yes, please reopen, thanks! :-)
