### ISSUE TITLE
FAB doesn't close automatically after uploading an image

### ISSUE THREAD

**Issue by brendajerop** [commons-app/apps-android-commons#2552]
**Summary:** 
The FAB in Contributions remains open even after uploading an image. It has to be clicked again in order for it to collapse. 

**Steps to reproduce:** 
1. Go to Home>Contributions
2. Click the FAB at the bottom right
3. Upload an image either via camera or gallery
4. Go back to contributions
5. FAB is still open

**Expectations**
FAB should have closed

**Device and Android version:** 
Samsung Galaxy Note 3, Android Version 5.0, Stock ROM

**Commons app version:** 
2.10.1 prodDebug master

**Screen-shots:** 
![screenshot_2019-03-06-23-14-26](https://user-images.githubusercontent.com/20903830/53913181-c4dce500-406b-11e9-8ecf-b8d11095192f.png)

**Would you like to work on the issue?**
Yes

**Comment by domdomegg** [comment]
Recreated on `2.10.1-debug-master~44c18ac23`

[Beta Commons](https://commons.wikimedia.beta.wmflabs.org/wiki/File:MobileTest_2556.jpg)
