### ISSUE TITLE
Preference summary should change when in night mode

### ISSUE THREAD

**Issue by oluwadara-abijo** [commons-app/apps-android-commons#2554]
**Summary:** 

When user turns on night mode, theme summary should not remain "Use dark mode" but something like "Use light mode".

**Steps to reproduce:** 

Navigation icon -> Settings -> Night mode -> Toggle the button

**Expectation:** 
When on light theme, summary should be "Use dark theme" and that is the case. But when on dark theme, summary should be changed to "Use light theme"

**Device and Android version:** 

Samsung S6, Android 6.0 Marshmallow
 
**Commons app version:** 

2.10.1-debug-master
master and prodDebug

**Screen-shots:** 

![screenshot_20190307-105926](https://user-images.githubusercontent.com/24768306/53949154-bfae8300-40c9-11e9-8ab8-304aa0e42cc1.png)
![screenshot_20190307-105935](https://user-images.githubusercontent.com/24768306/53949153-bf15ec80-40c9-11e9-9219-f77cd790779f.png)

**Would you like to work on the issue?**

Yes

**Comment by misaochan** [comment]
Hi @oluwadara-abijo , the toggle signifies "On" when it is on the right, and "Off" when it is on the left. So I think it is currently working as intended. If we made the text say "Use light theme" in your second screenshot, the toggle position would be wrong.

**Comment by oluwadara-abijo** [comment]
Okay then @misaochan
