### ISSUE TITLE
Spacing after "Uploaded by:"

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#2558]
The spacing is wrong in French:
![adb-screenshot](https://user-images.githubusercontent.com/99590/54015807-32038e00-41c4-11e9-8913-1b6803a27165.png)

As explained in #2498 I believe the user name should be a parameter in a full string such as `Uploaded by: {0}`

**Comment by oluwadara-abijo** [comment]
Can I work on this?

**Comment by nicolas-raoul** [comment]
@oluwadara-abijo OK it is yours :-)

**Comment by nicolas-raoul** [comment]
Be sure to check how similar problems were solved by this pull request: https://github.com/commons-app/apps-android-commons/pull/2532/files

**Comment by oluwadara-abijo** [comment]
Alright.
Thanks.
