### ISSUE TITLE
Make title edit field wrap and become bigger

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#2561]
A good title should be like 100~200 characters, which is a pain to edit on a single line on mobile:
![Screenshot_20190212-091953](https://user-images.githubusercontent.com/99590/54068492-955af200-4290-11e9-8bcc-24f2d908f06d.png)
I suggest enlarging the field as soon as it does not fit on a single line.

**Comment by oluwadara-abijo** [comment]
I'd like to work on this

**Comment by maskaravivek** [comment]
@oluwadara-abijo Yes, sure. Can you raise a PR for it? :)

**Comment by oluwadara-abijo** [comment]
Yes, I can @maskaravivek. Will do so soonest.

**Comment by oluwadara-abijo** [comment]
> @oluwadara-abijo Yes, sure. Can you raise a PR for it? :)

Hi @maskaravivek. I'm guessing I no longer need to raise a PR for the issue because as it appears, @VitalyPinchuk already did. There was just no information that the issue was being worked on already.

**Comment by VitalyVPinchuk** [comment]
I'm awfully sorry, I'm a total novice with github and android sdk so I was just experimenting. I wasn't going to announce that I would work on the issue. And I didn't expect my commit to appear here (I guess it's due to commit message that references to this issue).

**Comment by maskaravivek** [comment]
@oluwadara-abijo Which PR are you referring to? 

I see no PRs by @VitalyVPinchuk https://github.com/commons-app/apps-android-commons/pulls/VitalyPinchuk%20

@oluwadara-abijo you can go ahead and raise the PR. :)

@VitalyVPinchuk Welcome to the community! If you are looking at issues to get started then you can probably pick up any of these issues: 

https://github.com/commons-app/apps-android-commons/labels/beginner%20friendly

**Comment by VitalyVPinchuk** [comment]
@maskaravivek Thank you very much, I would definitely do :)

**Comment by oluwadara-abijo** [comment]
> I'm awfully sorry, I'm a total novice with github and android sdk so I was just experimenting. I wasn't going to announce that I would work on the issue. And I didn't expect my commit to appear here (I guess it's due to commit message that references to this issue).

No worries.
Welcome!
