### ISSUE TITLE
Place bookmark blue buttons hard to see in night mode

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#2562]
**Steps to reproduce:** 
1. Go to Setting, enable night mode
2. Go to Nearby, bookmark a place
3. Go to Bookmarks, select Places tab, tap the place
4. The blue buttons (bookmark/camera/gallery/directions/...) are hard to see

A slightly lighter blue would be better I think. Especially the directions and ... somehow.

**Screen-shots:** 
![Screenshot_20190213-130007](https://user-images.githubusercontent.com/99590/54068542-2d58db80-4291-11e9-84c4-3f7d9625363f.png)
Same in Nearby map.

**Comment by silkypriya** [comment]
Hello @nicolas-raoul, I'd like to work on this issue.

**Comment by silkypriya** [comment]
Made pull request for this issue.
Kindly review.
Thank you!

**Comment by silkypriya** [comment]
@nicolas-raoul , I have changed the bookmarks buttons colour to slightly lighter blue in light mode as well.
Am i supposed to change it only in night mode.
Thank you!
