### ISSUE TITLE
When type of nearby place is unknown, let description empty rather than just "?"

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#2563]
**Steps to reproduce:** 

1. Go to Nearby
2. Find a place which has no type (when you tap on it then tap on the bottom panel that appears, the last line says "?"
3. Upload a picture for it (you can cancel before the real upload)
4. Description is pre-filled with "?"

While it makes sense to prefill if the type is "school" or "hospital", when it is "?" the description should be left empty.

**Screen-shots:** 
![Screenshot_20190224-012328](https://user-images.githubusercontent.com/99590/54068952-6f841c00-4295-11e9-8afb-841145545137.png)

**Comment by brendajerop** [comment]
@nicolas-raoul I'd like to work on this

**Comment by nicolas-raoul** [comment]
@brendajerop It is yours! :-)

**Comment by brendajerop** [comment]
@nicolas-raoul I am not able to work on this issue as of now due to complications with my computer :(. So someone else can take it up.

**Comment by vanshikaarora** [comment]
@nicolas-raoul  Shall I take this up?

**Comment by ujjwalagrawal17** [comment]
Sure @vanshikaarora feel free to work on it.

**Comment by vanshikaarora** [comment]
Thanks @ujjwalagrawal17 :)

**Comment by nicolas-raoul** [comment]
@brendajerop Thanks for letting us know! :-)

**Comment by vanshikaarora** [comment]
@nicolas-raoul @ujjwalagrawal17 I have made a Pull Request here #2586 Kindly review :)
