### ISSUE TITLE
Notifications: message not centered in German

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#2564]
**Steps to reproduce:** 

1. Switch Android locale to German
2. Go to your notifications, make sure you have none
3. "No notifications" message is left-aligned, as per screenshot:

![Screenshot_20190307-000521](https://user-images.githubusercontent.com/99590/54069014-4c0da100-4296-11e9-92f7-3db06ea0a555.png)

Strangely this does not seem to happen with English/French.

**Comment by vanshikaarora** [comment]
Hey I can work on this
