### ISSUE TITLE
Upload category search in RTL: Spinner overlaps text

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#2565]
**Steps to reproduce:** 

1. Switch to a right-to-left (RTL) language such as Hebrew
2. Upload an image
3. When searching for a category, a spinner appears

Problem: This spinner overlaps the text I typed.
That does not happen with English.

**Screen-shots:** 
![Screenshot_20190306-203829](https://user-images.githubusercontent.com/99590/54069162-1cf82f00-4298-11e9-93b3-51612e3c6ae7.png)

**Comment by vanshikaarora** [comment]
Hey!! I can work on this.

**Comment by nicolas-raoul** [comment]
@vanshikaarora OK :-)

**Comment by vanshikaarora** [comment]
@nicolas-raoul  I have submitted a PR here #2575. Kindly review :)
