### ISSUE TITLE
Category suggestions wrong in RTL

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#2566]
**Steps to reproduce:** 

1. Switch Android to RTL language such as Hebrew
2. Upload image
3. When selecting categories, you see this:
![Screenshot_20190306-203852](https://user-images.githubusercontent.com/99590/54069339-92fd9580-429a-11e9-93d2-4138d0c7a5e0.png)
Checkboxes should be on the left and category names on the right.

**Comment by vanshikaarora** [comment]
Hey I can work on this!!

**Comment by vanshikaarora** [comment]
@nicolas-raoul I have submitted a PR here #2567. Kindly review :)
