### ISSUE TITLE
Text doubled after switching phone orientation in Nearby

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#257]
![screenshot_20160905-211502](https://cloud.githubusercontent.com/assets/99590/18247520/f437064c-73ad-11e6-9809-d0a87d27913b.png)

**Comment by misaochan** [comment]
Oh, wow, interesting...

**Comment by tobias47n9e** [comment]
I can confirm that this is happening on Android 6.0.1. 

Offtopic comment: https://www.wikidata.org/wiki/Q11661218 has a Japanese and Chinese label. Are we only getting the English for some items?

**Comment by nicolas-raoul** [comment]
@tobias47n9e: Based on your tip: https://github.com/commons-app/apps-android-commons/issues/260

**Comment by misaochan** [comment]
Thanks guys. I think I might know what's causing it, will try to work on a fix soon...

**Comment by misaochan** [comment]
Released a fix for this, please let me know if it solves the issue for you guys. :)

**Comment by tobias47n9e** [comment]
Works!

**Comment by misaochan** [comment]
Awesome, thanks!
