### ISSUE TITLE
Effective UI in night mode 

### ISSUE THREAD

**Issue by silkypriya** [commons-app/apps-android-commons#2573]
**Summary:** 

UI of some activity is not effective in night mode 

**Steps to reproduce:** 

Go to setting. Switch on the night mode

1. Go to Home>Nearby then tab on any location. The bottom row buttons are hard to see in night mode.

![bottom_buttons](https://user-images.githubusercontent.com/25826255/54091234-d7298c80-43a5-11e9-931f-95a34b03d9a3.jpg)

2. Backgroundolour of navigation bar header doesn't changes in night mode.

![54521637_295348647828100_1339231941752258560_n](https://user-images.githubusercontent.com/25826255/54124485-a475a780-442a-11e9-95d5-e5a60773a59f.png)

3. Background colour of tutorial activities does not change in night mode.   

![tutorial](https://user-images.githubusercontent.com/25826255/54091251-13f58380-43a6-11e9-9213-2b7344f03a6c.jpg)

**Device and Android version:** 

Realme 2 pro, Android Version 8.1.0, Stock Version from manufacturer

**Commons app version:** 

2.10.1 prodDebug master

**Would you like to work on the issue?**

Yes!

**Comment by nicolas-raoul** [comment]
There are several issues about night mode already, would you mind removing from this issue the ones that are already covered at existing issues? (see #2180)
Thanks!

**Comment by silkypriya** [comment]
Hello @nicolas-raoul, 
I updated this issue, removing the one same as #2446.
Pull request #2574 fixes both this issue and #2446.
Thank you!

**Comment by domdomegg** [comment]
Fixed in #2574
