### ISSUE TITLE
Cannot Run Git

### ISSUE THREAD

**Issue by HareemWaqas** [commons-app/apps-android-commons#2576]
An error occur when Opening project in Android Studio, By following these steps
In the menu bar, click File > New > Project from Version Control... > Git
OR
(if Quick Start menu open): Check out project from Version Control > Git
Enter the Git URL you obtained from Fork the Git repository.

Error : Cannot Run Git
Illegal char :> at index 5: 
https://github.com/YourName/apps-android-commons.git

**Comment by maskaravivek** [comment]
Can you try cloning from the command line? 

Go the folder where you wish to clone the repo and use this command: 

```
git clone https://github.com/YourName/apps-android-commons.git
```

**Comment by HareemWaqas** [comment]
yes, thank you
 I have tried but still not working

**Comment by neslihanturan** [comment]
First you should make sure git is installed on your system.  https://stackoverflow.com/questions/51032739/error-running-git
Second, YourName is an alias for your actual user name. Ie. for me it is https://github.com/neslihanturan/apps-android-commons.git

**Comment by HareemWaqas** [comment]
yes git is installed in my system, 
and for me it is https://github.com/HareemWaqas/apps-android-commons.git

**Comment by domdomegg** [comment]
What operating system are you using?

What is the result of running the command in a terminal:

```
git --version
```

Are you able to clone other repositories? e.g. how about

```
git clone https://github.com/Microsoft/calculator
```

If it doesn't work but has different output could you post it here?

**Comment by domdomegg** [comment]
Also another thing to try is maybe clone with the Git URL instead of HTTPS - it shouldn't make a difference but from the sounds of the error it seems to be getting stuck processing the http prefix.

Your git URL:
```
git@github.com:HareemWaqas/apps-android-commons.git
```

**Comment by HareemWaqas** [comment]
Thanks domdomegg!
 I am using Windows10,  trying again and again but still stuck, Let me follow your given steps ,i'll upload screen shots

**Comment by nicolas-raoul** [comment]
@HareemWaqas I suggest you ask at StackOverflow or another developers forum, since this seems to be independent from the app.

**Comment by mesineb** [comment]
It relectant to change
