### ISSUE TITLE
Show warning when picture uploaded via Nearby has wrong or no coordinates

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#2578]
When a picture is uploaded via Nearby with wrong or no coordinates, the app must show a popup telling:

> This picture's location does not match the nearby place's location. Are you sure this picture represents that place?

- If the user say Yes, the picture should be uploaded and linked from WIkidata.
- If the user say No, the picture should be uploaded but not linked from WIkidata.

Why? This should prevent some misuse. But we must let the user have the last decision, because coordinates often do not match, for instance when uploading picture that has no GPS coordinates, or when uploading a picture of a mountain, taken from reasonably far away.

There is a start of implementation, if I understand correctly a `Picture_Has_Correct_Location` value is calculated, but then it is not used.

A pull request would:
1. Add a case similar to https://github.com/commons-app/apps-android-commons/blob/2bc0d417487959ac1fad6a64947bcbab1ca35391/app/src/main/java/fr/free/nrw/commons/upload/UploadPresenter.java#L158
2. Show a popup "*This picture's location does not match the nearby place's location. Are you sure this picture represents that place?*" when needed.
3. Set Picture_Has_Correct_Location accordingly.

Tests can be done using the sandbox item: https://www.wikidata.org/wiki/Q4115189

Thanks!

**Comment by zhao-gang** [comment]
@nicolas-raoul As I explained in [this post](https://github.com/commons-app/apps-android-commons/issues/2530#issuecomment-471910636). There already has the popup to warn user if the image location is not matched to nearby place location. If you think my explanation in that post is reasonable, you could close this issue :-)
