### ISSUE TITLE
Overlapping text in login screen in landscape mode

### ISSUE THREAD

**Issue by madhurgupta10** [commons-app/apps-android-commons#2592]
**Summary:** 
The text is getting overlapped in landscape mode.

**Steps to reproduce:** 
Go to the login screen in landscape mode in a tablet.

**Device and Android version:** 
Stock Android API level 28 on Custom Virtual Device with the resolution 2048x1536 320dpi
 
**Commons app version:** 
latest betaDebug

**Screen-shots:** 
![screenshot-2019-03-15_00 41 21 186](https://user-images.githubusercontent.com/30932899/54384998-9a1e0c80-46bb-11e9-8912-6fdf813d7fe5.png)

**Would you like to work on the issue?**
Yes

**Comment by noahwalugembe** [comment]
Am just new to this repo can i work on this @madhurgupta10

**Comment by nicolas-raoul** [comment]
@noahwalugembe Sorry, Madhur has indicated he would like to work on this issue, Please choose another, thanks :-)
I had forgotten to put the label, I put it now.
