### ISSUE TITLE
Migrate to AndroidX

### ISSUE THREAD

**Issue by maskaravivek** [commons-app/apps-android-commons#2593]
**Summary:** 

While working on #2591 I thought it would be nice to migrate to AndroidX as well. 

Recently we ran into issues while adding new libraries or while updating to latest versions of existing libraries(which used AndroidX). Eg. #1192 

https://developer.android.com/jetpack/androidx/migrate

**Comment by dbrant** [comment]
Whoops, you'll notice that I've already got a PR (#2595) that updates to API 28 (as well as library versions), and also fixes and updates CI to match these updates, along with a few other related issues in the code.

Perhaps the PR to migrate to AndroidX can be a separate one?

**Comment by maskaravivek** [comment]
> Perhaps the PR to migrate to AndroidX can be a separate one?

Yes, makes sense. I will rebase my PR(#2594) once #2595 gets merged.
