### ISSUE TITLE
Adding information dialog to Statistics

### ISSUE THREAD

**Issue by madhurgupta10** [commons-app/apps-android-commons#2599]
**Summary:** 
Adding information dialog to Statistics.

**Screen-shots:** 
![InkedScreenshot_20190315-155319_LI](https://user-images.githubusercontent.com/30932899/54425332-13a90f80-473b-11e9-8412-ba11987de69d.jpg)

**Would you like to work on the issue?**
Yes

**Comment by domdomegg** [comment]
Assigned to @madhurgupta10

**Comment by maskaravivek** [comment]
@madhurgupta10 Can you elaborate on what would you show in the information dialog. :)

**Comment by madhurgupta10** [comment]
@maskaravivek I wanted to add information dialog button next to each **Featured Image**, **Thanks Received**, **Images via Nearby Places** so that a user can know more about these milestones and boost up his/her contributions accordingly.

For instance, the **Featured Image** heading does not explain much and someone who is new to the platform might want to know more about it. As per the current scenario they might want to search Google for the answer.

**Comment by domdomegg** [comment]
I think like how "images uploaded", "images reverted" and "images used" have information icons which explain what they mean, adding those for the other categories.

**Comment by domdomegg** [comment]
To avoid clutter by having 6 buttons maybe we could change this to have one information button which takes the user to something which explains all the achievement stats? It could also explain how level is calculated.

**Comment by madhurgupta10** [comment]
@domdomegg Great idea 👍 we can redirect them to a github page as we have for FAQ.

**Comment by maskaravivek** [comment]
IMO, we are just adding little (i) icons, it won't clutter the UI as such. We can probably just add these icons instead of redirecting to Github.

**Comment by domdomegg** [comment]
I'd agree redirecting them to Github is probably a bit much. Let's stick with the (i) icons for now.

**Comment by ujjwalagrawal17** [comment]
@madhurgupta10 feel free to start working on this issue and to add (i) icons.

**Comment by madhurgupta10** [comment]
@domdomegg @maskaravivek Please suggest **strings** for information dialogs for each of the three

**Comment by domdomegg** [comment]
> @domdomegg @maskaravivek Please suggest **strings** for information dialogs for each of the three

I don't mind too much - as long as it's not just restating the text already there (e.g. should *not* be something like for 'thanks recieved': 'this is the number of thanks you have received on Wikimedia Commons').

For thanks and featured pictures, perhaps looking at the text from one of these might help:

https://commons.wikimedia.org/wiki/Commons:Featured_pictures
https://en.wikipedia.org/wiki/Wikipedia:Notifications/Thanks

**Comment by madhurgupta10** [comment]
@domdomegg Definitely 👍
