### ISSUE TITLE
Quiz Checker is not being used

### ISSUE THREAD

**Issue by maskaravivek** [commons-app/apps-android-commons#2607]
**Summary:** 

It seems that quiz checker is not being used anywhere. Earlier if the revert rate was more than 15% then the quiz popup was shown. It doesn't seem to happen anymore.

**Comment by sp2710** [comment]
Yes @maskaravivek it is not being used anywhere

![Screenshot from 2019-03-16 16-49-08](https://user-images.githubusercontent.com/39745544/54474489-779b0900-480b-11e9-96f5-9d67fa6e2f89.png)

I would like to work on this. Shall i pick it up?

**Comment by maskaravivek** [comment]
I was actually already working on it. Can you please take up some other issue. :)

**Comment by sp2710** [comment]
Sure :-)
