### ISSUE TITLE
FAB weird behaviour when toggling on API 19

### ISSUE THREAD

**Issue by domdomegg** [commons-app/apps-android-commons#2609]
**Summary:** 

The FAB behaves weirdly on API level 19:

![issue](https://user-images.githubusercontent.com/4953590/54474562-3fc99c80-47de-11e9-83ad-9ec02b236271.gif)

**System logs:**

There are no logs when doing this

**Device and Android version:** 

Galaxy Nexus Emulator, at API level 19

```
Name: Galaxy_Nexus_API_19
CPU/ABI: Google APIs Intel Atom (x86)
Path: /home/adam/.android/avd/Galaxy_Nexus_API_19.avd
Target: google_apis [Google APIs] (API level 19)
Skin: 720x1280
SD Card: 512M
fastboot.chosenSnapshotFile: 
runtime.network.speed: full
hw.accelerometer: yes
hw.device.name: Galaxy Nexus
hw.lcd.width: 720
hw.initialOrientation: Portrait
image.androidVersion.api: 19
tag.id: google_apis
hw.mainKeys: no
hw.camera.front: emulated
avd.ini.displayname: Galaxy Nexus API 19
hw.gpu.mode: auto
hw.ramSize: 1024
PlayStore.enabled: false
fastboot.forceColdBoot: no
hw.cpu.ncore: 4
hw.keyboard: yes
hw.sensors.proximity: yes
hw.dPad: no
hw.lcd.height: 1280
vm.heapSize: 80
skin.dynamic: yes
hw.device.manufacturer: Google
hw.gps: yes
skin.path.backup: _no_skin
hw.audioInput: yes
image.sysdir.1: system-images/android-19/google_apis/x86/
showDeviceFrame: no
hw.camera.back: virtualscene
AvdId: Galaxy_Nexus_API_19
hw.lcd.density: 320
hw.arc: false
hw.device.hash2: MD5:fcb1c44f60d9172bb27b44fdd821eed1
fastboot.forceChosenSnapshotBoot: no
fastboot.forceFastBoot: yes
hw.trackBall: no
hw.battery: yes
hw.sdCard: no
tag.display: Google APIs
runtime.network.latency: none
disk.dataPartition.size: 2G
hw.sensors.orientation: yes
avd.ini.encoding: UTF-8
hw.gpu.enabled: yes
```

**Commons app version:** 

`2.10.1-debug-master~57e685cf6`

**Would you like to work on the issue?**

No

**Comment by sp2710** [comment]
I am picking it up

**Comment by sp2710** [comment]
@domdomegg Is this happening everytime? I am not able to reproduce this issue on Galaxy Nexus emulator on API 19.

**Comment by domdomegg** [comment]
@sp2710 Yes, the padding is wrong every time. The button only jumps position if both notifications are present. Example without notifications:

![Screenshot_1553023201](https://user-images.githubusercontent.com/4953590/54635418-01510d80-4a7c-11e9-831f-4095cf0378c3.png)

I think #2675 might have fixed this, will review it soon and close this if so.
