### ISSUE TITLE
Wrong bookmarked item expanding onResume

### ISSUE THREAD

**Issue by madhurgupta10** [commons-app/apps-android-commons#2616]
**Summary:** 
Wrong bookmarked item expanding onResume.

**Steps to reproduce:** 
Go to Bookmarks > locations > tap on an item other than first one > go to camera or map > the wrong item will expand when you return to the activity.

**Device and Android version:** 
Xiaomi Mi A1 API level 28 Stock Android
 
**Commons app version:** 
lastest betaDebug

**Screen-shots:** 
![ezgif-5-2556a54a1a5e](https://user-images.githubusercontent.com/30932899/54476526-6d393900-4824-11e9-8796-53a8416fdd78.gif)

**Would you like to work on the issue?**
Yes

**Comment by madhurgupta10** [comment]
@domdomegg could you please add **assigned** tag as well?

**Comment by Prince-kushwaha** [comment]
@madhurgupta10 i test this issue in latest master but this issue not present in  latest master

**Comment by domdomegg** [comment]
Thanks for testing @Prince-kushwaha :raised_hands:
