### ISSUE TITLE
I would like to add detect text copy/ paste event in password and username edit-text box

### ISSUE THREAD

**Issue by noahwalugembe** [commons-app/apps-android-commons#2637]
@nicolas-raoul I would like to add detect text copy/ paste event in password and username edit-text box os as to enable user to copy and paste passwords which I do a lot when logging

**Comment by domdomegg** [comment]
We can currently copy and paste usernames/passwords by pressing and holding in the textview, then clicking paste. However maybe a dedicated button in the beta app could take the contents of the clipboard and fill both fields and simulate clicking the login button.

e.g. if you had your username and password in clipboard seperated by a newline like:
```
domdomegg
thisIsNotMyRealPassword123
```
then clicked a button under the normal login button labelled `Login with clipboard` which only appeared if you were in the Beta version and had clipboard contents of the correct format.

**Comment by noahwalugembe** [comment]
Thanks for the good idea am going to try it out that way

**Comment by nicolas-raoul** [comment]
Does the WIkipedia app, or any other popular app, have this feature?

**Comment by domdomegg** [comment]
> Does the WIkipedia app, or any other popular app, have any of these features you guys are describing?
> It does not strike me as necessary, but maybe it is just me.

I'm not sure. I do think it could make the beta easier to test - however it does come with a cost of adding complexity.

**Comment by misaochan** [comment]
My vote is no, sorry. I personally think this proposed improvement adds complexity for very minimal benefit.

**Comment by nicolas-raoul** [comment]
Sorry about that @noahwalugembe how about working on https://github.com/commons-app/apps-android-commons/issues/2352 instead if you want? :-)

**Comment by noahwalugembe** [comment]
> a



> Sorry about that @noahwalugembe how about working on #2352 instead if you want? :-)

Okay nicolas-raoul
