### ISSUE TITLE
Remove BitmapUtils

### ISSUE THREAD

**Issue by domdomegg** [commons-app/apps-android-commons#2638]
**Summary:** 

Currently in achievements the level badge (`badge.xml`) has the level number drawn on top with `BitmapUtils`. I think it would be better to somehow use a normal `TextView` overlaid on the badge to do this. This would have three benefits:
- Massively reduce opportunity for bugs
- Crisper text as not rendered to a bitmap
- Marginally better performance

**Screen-shots:** 

![Screenshot_1552843041](https://user-images.githubusercontent.com/4953590/54495076-8996ad80-48d8-11e9-9425-6e0f6a6ad908.png)

**Would you like to work on the issue?**

No. For someone that would the appropriate files are likely to be `BitmapUtils` and `AchievementsActivity` (particularly the method `inflateAchievements`)

**Comment by zhao-gang** [comment]
@domdomegg Hi. I'd like to work on this. Please assign this issue to me.

**Comment by maskaravivek** [comment]
Assigned to @zhao-gang!
