### ISSUE TITLE
Refresh the 'nearby list' on down-swipe

### ISSUE THREAD

**Issue by tobias47n9e** [commons-app/apps-android-commons#264]
At the top of the 'nearby list' a down-swipe should reload the list. This is practical if one moved to another location and wants to get an up to date listing without having to restart the app.

**Comment by nicolas-raoul** [comment]
Great idea!

**Comment by misaochan** [comment]
Agreed, that would be awesome. :)

**Comment by misaochan** [comment]
Is this still needed with the new refresh icon?

**Comment by nicolas-raoul** [comment]
Very low-priority, but if someone want to implement this I think it would be nice to have in addition to the refresh button.

**Comment by RSBat** [comment]
I would like to work on this

**Comment by misaochan** [comment]
@RSBat please feel free. :)

**Comment by 97balakrishnan** [comment]
I will work on this.

**Comment by misaochan** [comment]
@97balakrishnan it is yours. :)

**Comment by 97balakrishnan** [comment]
thanks

**Comment by neslihanturan** [comment]
- When it comes to map, pulling down is hard because map is moving.
- When it comes to list, it is also hard because pull down swipes the list down.

I think we can close this for now.
