### ISSUE TITLE
Extend WelcomeActivityTest

### ISSUE THREAD

**Issue by domdomegg** [commons-app/apps-android-commons#2644]
**Summary:** 

Would be good to extend WelcomeActivityTest to cover more cases. These are taken from #2636:

- Test swiping the correct number of times and then clicking 'yes' exits WelcomeActivity
- ~Test that on beta clicking the 'skip tutorial' button exits WelcomeActivity~
- ~Test we can swipe both ways (i.e. backwards and forwards)~
- Test swiping beyond the proper bounds shouldn't do anything e.g. swiping left on the first page or right on the last page

**Comment by vanshikaarora** [comment]
Hey, is the issue still open?

**Comment by domdomegg** [comment]
@vanshikaarora Yep! Do you want to take it up?

**Comment by vanshikaarora** [comment]
Yes I want to work on this

**Comment by domdomegg** [comment]
Perfect. Feel free to request a review from me (although I'm happy for anyone else to review, just in case it speeds things up).

**Comment by vanshikaarora** [comment]
@domdomegg I have sent a PR for the first three tests here #2666 
They pass all the tests, Can you please review them :)

**Comment by domdomegg** [comment]
Might also want to add:

Test swiping all the way through, then clicking the finish button should result in the activity being destroyed.
