### ISSUE TITLE
Create unit tests for darkness-checking logic

### ISSUE THREAD

**Issue by domdomegg** [commons-app/apps-android-commons#2649]
**Summary:** 

Would be good to have a unit test for the darkness checking algorithm. It could use the 4 images in #1767 as samples.

See https://github.com/commons-app/apps-android-commons/pull/2639#issuecomment-473773865

**Comment by domdomegg** [comment]
For someone picking this up: it might be useful to reuse the generate image methods from #2626

**Comment by misaochan** [comment]
Added beginner-friendly label, this would be great for a GSoC student.

**Comment by silkypriya** [comment]
Hello @domdomegg @misaochan can i work on this issue ?

**Comment by maskaravivek** [comment]
Sure take this up @silkypriya

**Comment by misaochan** [comment]
Go for it! :)

**Comment by silkypriya** [comment]
Created PR #2727 for this.
Kindly review. Thank you!

**Comment by ciphereck** [comment]
@misaochan @maskaravivek @nicolas-raoul 
Can I work on closing this issue?

**Comment by maskaravivek** [comment]
Yes, sure. It is yours.

**Comment by ciphereck** [comment]
I wrote some tests of ImageUtils class. But I'm not able to run it. It shows error "No tests were found".
I try to run tests using both ImageUtilsTest Class and the test function I created. But it's showing the same error. It's showing the same error, for tests written in the past as well by someone else.
Can anyone help?

**Comment by ashishkumar468** [comment]
@ciphereck  Please attach a screenshot

**Comment by ciphereck** [comment]
![Screenshot from 2020-02-05 18-49-36](https://user-images.githubusercontent.com/24265219/73845369-7706c900-4848-11ea-9bb8-205eb5e9d3c2.png)

Here it is @ashishkumar468

**Comment by ashishkumar468** [comment]
Such things happen due to invalid-test configurations. To Validate, try this open any Test class and right-click and Run.

**Comment by ciphereck** [comment]
I did the same thing. Ran from the green arrow button and by right-clicking also.
Although just changed from prodDebug to betaDebug and clean and build it again. And it's working. Idk why it's working now.

**Comment by ashishkumar468** [comment]
@ciphereck  My guess would be that this could be because of some improper configurations, anyways, it's working for you now, right?

**Comment by ciphereck** [comment]
Hi,
I'm getting a problem. 
The line number 99 ( bmp = BitmapFactory.decodeFile(imagePath); ) which is supposed to convert an image into bitmap is always returning null when I'm calling it from the text file.
I tried whether it is the same case when running on mobile with debugging, but on mobile while debugging it's working just fine and returning bitmap as required.
While testing it returns null always. 
Can anyone help? @ashishkumar468 @maskaravivek @nicolas-raoul

**Comment by ciphereck** [comment]
Hi,
Can anyone help why BitMapFactory is not able to convert image into Bitmap in darkness checking logic?

**Comment by ciphereck** [comment]
Hi,
I'm getting a problem. When I'm writing tests for ImageUtils class.
The line number 99 ( bmp = BitmapFactory.decodeFile(imagePath); ) which is supposed to convert an image into bitmap is always returning null when I'm calling it from the text file.
I tried whether it is the same case when running on mobile with debugging, but on mobile while debugging it's working just fine and returning bitmap as required.
While testing it returns null always.
Can anyone help? @ashishkumar468 @maskaravivek @nicolas-raoul @misaochan @neslihanturan
![Screenshot from 2020-02-06 13-59-20](https://user-images.githubusercontent.com/24265219/74589186-1423e780-5029-11ea-823f-03078045c6a5.png)

**Comment by maskaravivek** [comment]
@ciphereck While running a unit test `BitmapFactory.decodeFile` won't be available and you might need to mock it as its a static class. See `FileUtilsWrapper` and `FileUtils` to see how it can be done.

**Comment by ciphereck** [comment]
@misaochan @maskaravivek 
I tried mocking ImageUtils as static class using wrapper as was in FileUtilsWrapper.
There's already a wrapper for ImageUtils i.e. ImageUtilsWrapper, but it's still returning null to me.

I also tried @RunWith as mentioned in StackOverflow somewhere, but it's still of no help :(
Can you please help me on this?

**Comment by gengarrrr** [comment]
Hi @misaochan @maskaravivek @nicolas-raoul 
Can I work on this issue?

**Comment by nicolas-raoul** [comment]
@gengarrrr Yes thanks! :-)

**Comment by gengarrrr** [comment]
@nicolas-raoul. Hello, I found that there already exists an ImageUtilsTest file, and I think it contains the check for dark with no image example through the merged pull request of Add ImageUtils Tests #4542. Should I just work on adding some images? or Can I write my own test functions within the file. Thank you

**Comment by nicolas-raoul** [comment]
@gengarrrr Good find, please add your oyn test fuctions within that file 🙂
