### ISSUE TITLE
Fix warnings about string resources 'without required default value'

### ISSUE THREAD

**Issue by domdomegg** [commons-app/apps-android-commons#2655]
**Summary:** 

There are a bunch of warnings about string resources without the required default value (i.e. a fallback in `strings.xml`). As these strings are not used throughout the app I think we should remove them.

The main benefit is that it'll be easier to search for failures in the logs as the string resources have the text 'failed' in them which is annoying when going through Travis logs trying to find useful info.

**Steps to reproduce:** 

Run a process manifest gradle task.

**Logs:**

```
> Task :app:processBetaReleaseManifest
warn: removing resource fr.free.nrw.commons.beta:string/contributions_subtitle without required default value.
warn: removing resource fr.free.nrw.commons.beta:string/login_failed_password without required default value.
warn: removing resource fr.free.nrw.commons.beta:string/login_failed_username without required default value.
warn: removing resource fr.free.nrw.commons.beta:string/media_detail_media_title without required default value.
warn: removing resource fr.free.nrw.commons.beta:string/multiple_uploads_title without required default value.
warn: removing resource fr.free.nrw.commons.beta:string/preference_tracking without required default value.
warn: removing resource fr.free.nrw.commons.beta:string/preference_tracking_summary without required default value.
warn: removing resource fr.free.nrw.commons.beta:string/share_license_summary without required default value.
warn: removing resource fr.free.nrw.commons.beta:string/starting_multiple_uploads without required default value.
warn: removing resource fr.free.nrw.commons.beta:string/upload_image_problem_duplicate without required default value.
warn: removing resource fr.free.nrw.commons.beta:string/uploads_pending_notification_indicator without required default value.
warn: removing resource fr.free.nrw.commons.beta:string/use_wikidata without required default value.
```

```
> Task :app:processProdDebugManifest
warn: removing resource fr.free.nrw.commons:string/contributions_subtitle without required default value.
warn: removing resource fr.free.nrw.commons:string/login_failed_password without required default value.
warn: removing resource fr.free.nrw.commons:string/login_failed_username without required default value.
warn: removing resource fr.free.nrw.commons:string/media_detail_media_title without required default value.
warn: removing resource fr.free.nrw.commons:string/multiple_uploads_title without required default value.
warn: removing resource fr.free.nrw.commons:string/preference_tracking without required default value.
warn: removing resource fr.free.nrw.commons:string/preference_tracking_summary without required default value.
warn: removing resource fr.free.nrw.commons:string/share_license_summary without required default value.
warn: removing resource fr.free.nrw.commons:string/starting_multiple_uploads without required default value.
warn: removing resource fr.free.nrw.commons:string/upload_image_problem_duplicate without required default value.
warn: removing resource fr.free.nrw.commons:string/uploads_pending_notification_indicator without required default value.
warn: removing resource fr.free.nrw.commons:string/use_wikidata without required default value.
```

**Would you like to work on the issue?**

No, but I would be happy to review.

**Comment by vanshikaarora** [comment]
Hey I am working on this

**Comment by vanshikaarora** [comment]
>As these strings are not used throughout the app I think we should remove them.

**Comment by vanshikaarora** [comment]
>As these strings are not used throughout the app I think we should remove them.

@domdomegg Do you mean removing their declaration in strings.xml.  Because on removing one of the listed string from strings.xml  `contributions_subtitle` . I found that it was used in some classes(like MainActivity for contributions_subtitle)

Have I misunderstood the Issue?

**Comment by vanshikaarora** [comment]
>Ah I didn't know they were used - if that's the case a default value for them should be added to strings.xml so it stops complaining.

OK I'll do that :+1:

**Comment by vanshikaarora** [comment]
>warn: removing resource fr.free.nrw.commons.beta:string/login_failed_password without required default value.
warn: removing resource fr.free.nrw.commons.beta:string/login_failed_username without required default value.


@domdomegg I didn't find these declarations in the latest master. Are you working on a different version?

**Comment by domdomegg** [comment]
I think these are in master. e.g. `login_failed_username` is present in [values-af/strings.xml](https://github.com/commons-app/apps-android-commons/blob/master/app/src/main/res/values-af/strings.xml)

**Comment by vanshikaarora** [comment]
@domdomegg I have raised a PR for this [here](https://github.com/commons-app/apps-android-commons/pull/2684). Kindly review :)
