### ISSUE TITLE
"Nominate for deletion" shows wrong reasons in "Uploaded via mobile"

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#2657]
In the new "Uploaded via mobile" tab of "Explore", I have found an off-topic picture, and as the "Nominate for deletion" button was visible I tapped it. Here is what appeared:
![Screenshot_20190318-230646](https://user-images.githubusercontent.com/99590/54577078-bf08db80-4a3d-11e9-8f67-1b4de0484f89.png)
As you can see, 4 of the reasons start with "I" which is a mistake since the picture was not uploaded by me.

I suggest using a different set of nomination reasons for pictures uploaded by others:

- The picture has been downloaded from a random website
- The uploader is not the author of the picture (copyright violation)
- The picture is a selfie or joke

**Comment by vanshikaarora** [comment]
Hey, I am working on this!

**Comment by nicolas-raoul** [comment]
Oh, actually I just got a better idea:
If the picture is not uploaded by me, it should not have a "nominate for deletion" button, but instead it should have a "Peer review" button that redirects to the Peer Review activity for that picture.
The Peer Review activity is not totally ready yet, but it should not change too much anymore so I suggest you create a feature branch and pull #2602 into it, and start integrating with it.
Thanks!

**Comment by vanshikaarora** [comment]
@nicolas-raoul I am suffering frequent crashes in the application after merging the PR.

Let's wait for the work completion. I'll pick this work whenever #2602 is merged with master

**Comment by mrudultora** [comment]
Anyone working on this? If not, I would like to work on this.

**Comment by nicolas-raoul** [comment]
Actually this is fixed now. Sorry for letting it open!
