### ISSUE TITLE
Tapping Android notification after deletion nomination does not do anything

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#2659]
**Steps to reproduce:** 

1. Upload a picture
2. Nominate it for deletion
3. An Android notification appears. Tap it.

Expected: Go to the nomination page in the browser, or to the picture's media details activity. I think.
Actual: Nothing happens.
![Screenshot_20190318-230806](https://user-images.githubusercontent.com/99590/54583600-0734f780-4a58-11e9-83ca-2729a7a32bd6.png)

**Comment by nicolas-raoul** [comment]
I suggest than when tapping (after everything has finished successfully) just opens the nomination's webpage in the browser.

**Comment by vanshikaarora** [comment]
@nicolas-raoul I have create a Pull Request [here](https://github.com/commons-app/apps-android-commons/pull/2667) Kindly review :)
