### ISSUE TITLE
Android notification after deletion nomination unclearly worded, and not localized

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#2660]
**Steps to reproduce:** 

1. Upload a picture
2. Nominate it for deletion
3. An Android notification appears. 

As seen below it says `Successfully nominated XYZ deletion`. Instead it should say `Successfully nominated "XYZ" for deletion` (note the `"` and `for`).

More importantly, all strings in this method should be localized:
https://github.com/commons-app/apps-android-commons/blob/57e685cf6cc5f1c2ec3f475347d5d30be15034ec/app/src/main/java/fr/free/nrw/commons/delete/DeleteTask.java#L163

And should not use lego messages, see https://github.com/commons-app/apps-android-commons/issues/2498 for what it means and how to fix it.

![Screenshot_20190318-230806](https://user-images.githubusercontent.com/99590/54583600-0734f780-4a58-11e9-83ca-2729a7a32bd6.png)

**Comment by noahwalugembe** [comment]
Hi @nicolas-raoul can i instead work on this i am done with #1107

**Comment by nicolas-raoul** [comment]
@noahwalugembe OK it is yours :-)

**Comment by noahwalugembe** [comment]
> Hi @nicolas-raoul can i instead work on this i am done with #1107

Can you check out the pool trequest for  #1107 issue

> @noahwalugembe OK it is yours :-)

Can you check out  pull request #2618 for issue  #1107

**Comment by nicolas-raoul** [comment]
Is this issue still present in master?

**Comment by maskaravivek** [comment]
No. I couldn't find any of the above strings. Closing the issue.
