### ISSUE TITLE
Do not suggest technical categories during categorization

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#2664]
**Steps to reproduce:** 

1. Upload a picture
2. During categorization, enter "moved" (let's say you the picture is about "The House That Moved")

Problem: Many technical categories show up, for instance the "Requested moves" categories in the screenshot below. Selecting such a category in the app would always be a mistake, so better not show them.

Preferably we should find a category search method that does not return such categories.

![Screenshot_20190313-100842](https://user-images.githubusercontent.com/99590/54590409-618b8380-4a6b-11e9-9903-53c8faadc44f.png)

Different but a bit related: #1703

**Comment by sivaraam** [comment]
I think you were observing this when our app was also showing hidden categories. If I understand correctly, we don't show hidden categories anymore. So, this should not be an issue anymore and hence closing this.

Feel free to re-open if I misunderstood this issue.
