### ISSUE TITLE
Main Activity crashes when returning from Upload

### ISSUE THREAD

**Issue by vanshikaarora** [commons-app/apps-android-commons#2679]
**Summary:** 

Main Activity crashes while returning back from Upload(if no image is selected) or returning from settings(while enabling location) 

**Steps to reproduce:** 

- From Main Activity select Fab Icon and Upload via gallery
- Press back from Image Picker

Main Activity will crash in the onActivityResult() method.

**Device and Android version:** 
Vivo 1713 API Level 24
 
**Commons app version:** 
Latest master

**Would you like to work on the issue?**

Yes

**Comment by domdomegg** [comment]
Reproduced on `2.10.1-debug-master~052d09e08`
