### ISSUE TITLE
Write Unit Test for Login Activity

### ISSUE THREAD

**Issue by madhurgupta10** [commons-app/apps-android-commons#2686]
**Summary:** 
Write Unit Test for Login Activity

**Would you like to work on the issue?**
Yes

**Comment by domdomegg** [comment]
Please write the new test in Kotlin if possible - I know it's a mix but it should be standardised soon :)

**Comment by madhurgupta10** [comment]
@domdomegg please check #2687 I tried to write it with kotlin :)
