### ISSUE TITLE
Achievements page takes a long time to load

### ISSUE THREAD

**Issue by sivaraam** [commons-app/apps-android-commons#2691]
**Summary:** 
The achievements page seems to be taking ~30 seconds for me to load in some cases. Not sure why it is taking a lot of time to load despite the network being fast/reliable.

**Steps to reproduce:** 
1. Open the app
2. Open the sidebar
3. Tap on the trophy icon to open the achievements page.

**Device and Android version:** 
Samsung SM-J111F (Android 5.1.1)
 
**Commons app version:** 
2.10.2

**Screen shot**
The achievements page looks like the following when it is not loaded. It is what I see for about 30 seconds. There's not even a progress indicator.

![Screenshot_2019-03-20-23-09-53](https://user-images.githubusercontent.com/12448084/54736368-bf85ab80-4bd0-11e9-94a1-5e791805ef75.png)

**Would you like to work on the issue?**
Nope.

**Comment by vanshikaarora** [comment]
Hey @sivaraam I can see the progressbar in achievements activity. Are you working on latest master?

**Comment by neslihanturan** [comment]
Possibly related #1816 or #2603

**Comment by sivaraam** [comment]
>  I can see the progressbar in achievements activity. Are you working on latest master?

Nope. As I state in the description, I use the version 2.10.2 of the app which has just recently been release as a stable one.

Anyways, I found why I don't see the progress indicator. It shows when enable animations in the developer settings of my device and doesn't show up when I disable them.

The progress indicators in various places of the app don't seem to be visible when the animations are turned off. I think this could be improved as I've seen apps which show different indicators when the animations are turned off. Not sure how they do it, though.

**Comment by Rishavgupta12345** [comment]
@4D17Y4 now to achievement is smoother and perfectly working so we can close this issue

**Comment by neeldoshii** [comment]
I guess the issue still exists and from logs Its seems like when the achievement is opened the leaderboards also gets called and start populating which is giving leading to more time to load.

**Comment by ShashwatKedia** [comment]
@nicolas-raoul I think the Achievements section now loads pretty fast and also has a progress indicator for the level badge. Could this be closed?
