### ISSUE TITLE
Image not displayed at upload step 1, maybe because of slow internet

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#2693]
**Steps to reproduce:** 
1. Start image upload with slow internet connection
2. At step 1, nothing is displayed:
![Screenshot_20190320-145428](https://user-images.githubusercontent.com/99590/54736734-eb645980-4bef-11e9-94fa-1db8431df44e.png)

**Comment by JobGetabu** [comment]
I would like to be assigned to this issue ?

**Comment by sp2710** [comment]
@nicolas-raoul IMO we should add progress bar to it untill image gets loaded.

**Comment by ashishkumar468** [comment]
@nicolas-raoul  are you still seeing this issue?

**Comment by nicolas-raoul** [comment]
I have not seen this for a very long time.
