### ISSUE TITLE
Deletion nomination sent to my own page, instead of the uploader's page

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#2703]
**Steps to reproduce:** 

1. Go to Explore
2. Go to the Mobile uploads tab
3. Find a picture that you want nominate for deletion
4. Push the button to nominate it for deletion

Expected: Among other things, a message is sent to the uploader
Actually: That message is sent to my own talk page. Example: https://commons.wikimedia.org/wiki/User_talk:Syced#File:@Oleballinazz_14.jpg and nothing sent by my account to https://commons.wikimedia.org/wiki/User_talk:Oleballinazz

**Comment by sherlockbeard** [comment]
#2827 talked about two dialog box for deletion . 
if you look at the dialog box i think the first dialog box is for when someone is trying to nominated other's upload for deletion, and the second one is for the deletion on the picture you uploaded( according to the option's that can be selected). @nicolas-raoul could this be the reason?

**Comment by nicolas-raoul** [comment]
Great find!
Indeed part of the code has been written for own picture deletion, and then probably reused for review without thinking about this detail.
So now you know what to fix :-)

By the way, other parts of the workflow will probably be different, for instance if you propose for deletion the picture of someone else you must write on their talk page, but if it is your own picture then it does not make sense to post on your own talk page.

**Comment by sherlockbeard** [comment]
are username unique. i mean how can i know that the user uploaded the picture or it is uploaded by someone else.

**Comment by nicolas-raoul** [comment]
Yes, usernames are unique.

**Comment by sherlockbeard** [comment]
ok . i think i know what i need to do . i need to check the author name with the current account name . 
and if is true i have to show the drop down box dialog box otherwise the dialog box with input text .
correct me if i am wrong.

**Comment by nicolas-raoul** [comment]
Yes sounds good :-)

And also, send a message to the right talk page, and only if the uploader is not me.

**Comment by sherlockbeard** [comment]
sorry to ask. but i need help mediawikiapi 
https://github.com/commons-app/apps-android-commons/blob/master/app/src/main/java/fr/free/nrw/commons/delete/DeleteHelper.java#L106-L113A 
can you explain what these lines are doing

**Comment by neslihanturan** [comment]
Hi @sherlockbeard . Here is the API documentation: https://www.mediawiki.org/wiki/API:Main_page and sandbox: https://www.mediawiki.org/wiki/Special:ApiSandbox . I hope these helps.

**Comment by sherlockbeard** [comment]
@neslihanturan  @nicolas-raoul  
https://github.com/commons-app/apps-android-commons/blob/master/app/src/main/java/fr/free/nrw/commons/delete/DeleteHelper.java#L113
in this user talk is set to session.gecurrentAccount().name i think i should change it to media.getcreater but i don't know how to check the result .

**Comment by neslihanturan** [comment]
@sherlockbeard do you mean you don't know how to test your implementation?

**Comment by sherlockbeard** [comment]
@neslihanturan. the problem is i don't know about the stuff of usertalk on wikimedia and don't know how to produce it. i have fixed up the issue of dialog box.

**Comment by neslihanturan** [comment]
Hi @sherlockbeard , you can find several documentation about what the talk page is and what is nomination for deletion etc. Also, you can use beta flavor of our app for nominating for deletion some images and debug to understand what is going on. For learning what beta flavor is please make sure you read our contributor docs.

**Comment by sherlockbeard** [comment]
https://commons.wikimedia.org/wiki/User_talk:Sherlocktest (uploader)
https://commons.wikimedia.org/wiki/User_talk:Sherlocktest2 (nominator )

https://commons.wikimedia.org/wiki/File:Sherlocktest.jpg (file page)

@nicolas-raoul

**Comment by nicolas-raoul** [comment]
The place where the message has been sent is correct, thanks for fixing! :-)
