### ISSUE TITLE
Login do not working

### ISSUE THREAD

**Issue by higimo** [commons-app/apps-android-commons#2716]
My login is higimo.

**Comment by maskaravivek** [comment]
@higimo Can you share logs from your device.

**Comment by higimo** [comment]
@maskaravivek how can i get log from my device?

**Comment by higimo** [comment]
@maskaravivek how can i get log from my device?

**Comment by nicolas-raoul** [comment]
@higimo Tap Settings>Send log

**Comment by higimo** [comment]
@nicolas-raoul there is no settings (Настройки) and logs (Лог or Журнал) button in this interface. Screenshot:
![Screenshot_free nrw commons](https://user-images.githubusercontent.com/2804205/55481536-499b2e80-562b-11e9-8867-260e2b14c258.jpg)

**Comment by nicolas-raoul** [comment]
Thanks for noticing, I created a separate issue for that: https://github.com/commons-app/apps-android-commons/issues/2853

Meanwhile, you can also take the log with ADB logcat: https://www.youtube.com/watch?v=W6iDw76UpQw

**Comment by ashishkumar468** [comment]
As the logs are not added and considering the issue has been marked before backend overhaul (which aimed to fix such issues), closing this one.
