### ISSUE TITLE
Fix fetching of media details in bookmarks

### ISSUE THREAD

**Issue by maskaravivek** [commons-app/apps-android-commons#2730]
**Summary:** 

`BookmarkPicturesController:loadBookmarkedPictures` inefficiently fetches the media information by searching on the file name. Instead, it should simply use 
`OkHttpJsonApiClient:getMedia` to get media information based on file name.

The backend query for search would be more expensive than querying by the exact filename.

**Comment by ashishkumar468** [comment]
I can take this up:-)

**Comment by maskaravivek** [comment]
I am taking this up as this has been pending for almost a month. :)
