### ISSUE TITLE
Review: Notifications seem to be about picture I have not reviewed yet

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#2743]
I just tried the review feature for the first time today. I reviewed the picture of a 2016 senator, all perfect, great picture with relevant categories, so I tapped "seems fine" at each step.

After sending the thank, two notification appeared. Problem: They seem to be about the next picture (Pedro Americo drawing).

Other apparent problem: "Requesting category check" appears despite me tapping to say that the categories are fine. (my [contributions](https://commons.wikimedia.org/wiki/Special:Contributions/Syced) do not show any activity for that period, though)
![Screenshot_20190325-145038](https://user-images.githubusercontent.com/99590/54898184-95085b00-4f0e-11e9-8508-f8dfc93ab14f.png)

**Comment by vanshikaarora** [comment]
Hey, @nicolas-raoul I am working on this issue.

**Comment by ShashwatKedia** [comment]
@nicolas-raoul, this issue seems to be gone, as the app shows a Toast message instead of a notification on sending thanks. We could close this issue?

**Comment by nicolas-raoul** [comment]
@ShashwatKedia Indeed, thanks! :-)
