### ISSUE TITLE
Review: No thanks given despite "Sending Thanks: Success"

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#2744]
As part of the review I performed, I chose to thank the uploader (why not?), and a notification tells me that it worked:
![Screenshot_20190325-145038](https://user-images.githubusercontent.com/99590/54898184-95085b00-4f0e-11e9-8508-f8dfc93ab14f.png)
But when I look at https://www.mediawiki.org/wiki/Special:Log/thanks I do not see my thank (it was two hours ago):
![Screenshot from 2019-03-25 16-35-21](https://user-images.githubusercontent.com/99590/54902186-10243e00-4f1c-11e9-97f6-0c3507cf833f.png)

**Comment by vanshikaarora** [comment]
Hey, @nicolas-raoul I am working on this

**Comment by nfatma** [comment]
Can I work on this issue?

**Comment by maskaravivek** [comment]
Sure. Assigned to @nfatma

**Comment by nfatma** [comment]
I have been working on this issue for quite long. It seems to me that the API calling and use is perfect. Also when I was trying to make Request `https://commons.wikimedia.org/w/api.php?action=thank&revid=108006&source=diff&token=8f9706723e33af5c950b628dceb6f7555cd2a2f0+\`  via API sandbox I am getting the below error:

{
    "error": {
        "code": "mustpostparams",
        "info": "The following parameter was found in the query string, but must be in the POST body: token.",
        "*": "See https://commons.wikimedia.org/w/api.php for API usage. Subscribe to the mediawiki-api-announce mailing list at &lt;https://lists.wikimedia.org/mailman/listinfo/mediawiki-api-announce&gt; for notice of API deprecations and breaking changes."
    },
    "servedby": "mw1346"
}

**Comment by neslihanturan** [comment]
Hi @nfatma can you copy the request url taken from sandbox here?

**Comment by nfatma** [comment]
sure @neslihanturan 

/w/api.php?action=thank&format=json&token=34a419c2852c0e298652b8199193240c5cd3e626%2B%5C&source=diff

and here I am getting this:
{
    "error": {
        "code": "missingparam",
        "info": "One of the parameters \"rev\" and \"log\" is required.",
        "*": "See https://commons.wikimedia.org/w/api.php for API usage. Subscribe to the mediawiki-api-announce mailing list at &lt;https://lists.wikimedia.org/mailman/listinfo/mediawiki-api-announce&gt; for notice of API deprecations and breaking changes."
    },
    "servedby": "mw1225"
}

**Comment by neslihanturan** [comment]
>I have been working on this issue for quite long. It seems to me that the API calling and use is perfect. 

Can you also share related code lines that your sentence above is about? So that I can help

**Comment by nicolas-raoul** [comment]
@nfatma Are you still working on this issue? What are your findings? What would be the correct URL to make it work? Thanks :-)

**Comment by chaytanyasinha** [comment]
Well I have a question that the "Thanks" message is sent via mail or is it a notification on the application?

**Comment by nicolas-raoul** [comment]
It is a notification in the web application.
Please create an account if you don't have one already, and try to send
thanks to someone who uploaded a nice picture.

**Comment by chaytanyasinha** [comment]
what is the language used in webapp

**Comment by neslihanturan** [comment]
Hey @chaytanyasinha , our app facilities using https://commons.wikimedia.org/ from android devices. When you click "view in browser" , you will see the image on browser.

**Comment by chaytanyasinha** [comment]
Yes @neslihanturan,I opened the webapp in my mobile browser.Can you please tell me in which language are the api written for the issue.

**Comment by neslihanturan** [comment]
We are using MediaWiki API for this purpose. However, we probably shouldn't need to edit the API for this issue. So, I can't understand why you need the langugage of the APı. Please make sure you read our contributors documents beforehand, you can find more information about APIs we used there. 

I think for this issue we need help with investigation. If you are able to reproduce the issue please share the details here, as @nicolas-raoul did, so that we can find the solution.

**Comment by chaytanyasinha** [comment]
I did reproduced the issue and updated about it in the earlier comments @neslihanturan.

**Comment by neslihanturan** [comment]
Sorry @chaytanyasinha I can't see it. Can you please share the link of the comment you mentioned?

**Comment by chaytanyasinha** [comment]
Sorry @neslihanturan,I got confused actually I updated about the reproduction of issue in the issue #3202 and the link of the comment is: https://github.com/commons-app/apps-android-commons/issues/3202#issuecomment-558137956

**Comment by neslihanturan** [comment]
Thanks for the update @chaytanyasinha , can you add more info toy our test though? There are some points I couldn't understand about the comment you linked:
1 - Did you send thank or did you nominate for deletion or did you do both?
2- Is your thank succeed and given, or it succeeded but not given as described in this issue?

**Comment by chaytanyasinha** [comment]
@neslihanturan Actually I did thank for the first it succeeded but it was showing a progress in notification bar so just to test I nominated a picture for deletion and it worked on the first go.
So,I concluded that there is an issue in sending thanks as it shows it succeeded but it's still in progress according to the notification  bar and it's not sent in real.

**Comment by neslihanturan** [comment]
Notification is not reliable to verify thank is worked or not, instead you should check:

> But when I look at https://www.mediawiki.org/wiki/Special:Log/thanks I do not see my thank (it was two hours ago)...
as written in @nicolas-raoul 's comment. If you did this on beta cluster, you should check this on beta.

**Comment by chaytanyasinha** [comment]
Yes @neslihanturan ,In this list also I was not able to find my user name.

**Comment by neslihanturan** [comment]
Then, the way we make API call should be wrong. @nfatma already did great investigation though, those comments can be helpful to create the correct the API call.

**Comment by chaytanyasinha** [comment]
Yes I went through those comments and I went on the provided url.

**Comment by chaytanyasinha** [comment]
@neslihanturan @nicolas-raoul If you say I can give a try of writing new API.

**Comment by neslihanturan** [comment]
I would like to be able to combine two issues. Currently this issue and #3202 seems like the same thing. Lets discuss here.

@chaytanyasinha I think writing the new API is not the way we go. The way we make the API call should be investigated. You can use Mediawiki APı sandbox for investigation purposes. If you are willing to do in this way, please say us so that I will assign the issue to you. Otherwise, @SamuelleMollard also interested.

**Comment by chaytanyasinha** [comment]
Yes I can do this way too @neslihanturan

**Comment by neslihanturan** [comment]
Okay so this issue is assigned to @chaytanyasinha

**Comment by chaytanyasinha** [comment]
@neslihanturan Actually I went through MediaWiki APi Sandbox yesterday only and I came to know about this error:
{
    "error": {
        "code": "mustpostparams",
        "info": "The following parameter was found in the query string, but must be in the POST body: token.",
        "*": "See https://commons.wikimedia.org/w/api.php for API usage. Subscribe to the mediawiki-api-announce mailing list at &lt;https://lists.wikimedia.org/mailman/listinfo/mediawiki-api-announce&gt; for notice of API deprecations and breaking changes."
    },
    "servedby": "mw1235"
}

**Comment by chaytanyasinha** [comment]
Currently I am going through this(https://www.mediawiki.org/wiki/Extension:Thanks#API_Documentation) so that I can find a way to solve it

**Comment by SamuelleMollard** [comment]
Should I try and work on it too then or would it be more efficient if I worked on an other issue then ?

**Comment by neslihanturan** [comment]
Please work on another issue @SamuelleMollard , I am currently online, if you want to pick one just left a comment under the issue and I will assign it to you if it is not already assigned.

Note: 
- Do not rely on the assigned label to strictly, sometimes the label is outdated and the issue is still available. 
- Following beginner friendly labels usually helps.

**Comment by SamuelleMollard** [comment]
Very well, I'm selecting an issue labelled 'beginner-friendly' and commenting under it then. Thanks

**Comment by chaytanyasinha** [comment]
@neslihanturan @nicolas-raoul I went through the APIs and I found them fine.Even we can see on all other wikimedia platforms its working as in the thank list I checked all other thanks are used in other platforms so I think there is problem with something else.

**Comment by chaytanyasinha** [comment]
@neslihanturan @nicolas-raoul Please reply what should I do next. As I am getting same errors nfatma got and I found the api fine as its working for other platforms.

**Comment by neslihanturan** [comment]
Actually I don't know @chaytanyasinha , since I haven't work on this issue before.

**Comment by chaytanyasinha** [comment]
It's okay @neslihanturan . So should I work on another issue or the issues which I started?

**Comment by neslihanturan** [comment]
Sure @chaytanyasinha , you can always switch between issues, just clearly say if you want to leave it so that someone else can work on.

**Comment by neslihanturan** [comment]
Actually this comment of @nicolas-raoul is beneficial for this issue too: https://github.com/commons-app/apps-android-commons/issues/3202#issuecomment-559685641 

You can try using breakpoints to find out unexpected pattern of the method.

**Comment by sivaraam** [comment]
I think there is a slight misunderstanding here. The Thanks feature seems to be working fine. The link in the issue description clearly shows that the logs at **Mediawiki** were being searched. If I understand correctly, when you thank a user for uploading the image to Common the log would be found in the **Commons wiki** and not in Mediawiki. So, I checked the [logs at Commons ](https://commons.wikimedia.org/wiki/Special:Log/thanks) and guess what I found when I searched for the Thanks [logs on 25March2019](https://commons.wikimedia.org/w/index.php?title=Special:Log&offset=20190326000000&limit=500&type=thanks&user=&page=&wpdate=2019-03-25&tagfilter=&day=25&month=3&year=2019):

![image](https://user-images.githubusercontent.com/12448084/69859970-3d9b6580-12bb-11ea-94bc-1b82decb8472.png)

I'm not sure whether that is the Thank @nicolas-raoul was looking for. So, my theory might  be wrong. But just wanted to note my observation.

**Comment by chaytanyasinha** [comment]
@neslihanturan I think I will switch to other issues.

**Comment by neslihanturan** [comment]
Oh so thanks were working according to @sivaraam 's comment. I am not closing this issue until @nicolas-raoul verifies it though. Thanks @sivaraam !

**Comment by nicolas-raoul** [comment]
Samuelle, could you please try the thank feature and see whether it appears
in the log Sivaraam mentioned? Please post the log here. Thanks! 🙂

**Comment by SamuelleMollard** [comment]
I can try, but I have to do something before and launching android studio should take about 20 min anyway so not right now, but I am not sure I will be able to, since I have not been able to get a sending thanks:success yet to be honnest

**Comment by SamuelleMollard** [comment]
I can't get a sending thanks: success, no matter how i try
I'll work on #3202 and if I can fix that I will send you the logs, but for now I can't get them.
Furthermore, I can confirm that those thanks are not in the log mentioned above

**Comment by sivaraam** [comment]
FWIW, I just tried to Thank an uploader. Regardless of the fact that the I got a "Sending Thanks: Failure" notification the Thanks was indeed sent as you can see in [the thanks log](https://commons.wikimedia.org/wiki/Special:Log?type=thanks&user=Kaartic&page=&wpdate=2019-12-04&tagfilter=).

![image](https://user-images.githubusercontent.com/12448084/70126595-634fb280-169f-11ea-9876-90d1c5b8e68b.png)


On a side note, I'm getting a "Requesting category change ..." notification despite the fact that I never chose to request a category change for the image I reviewed. The worst part is that the notification is sticky i.e., I'm not able to swipe to make it go away!

**Comment by nicolas-raoul** [comment]
@sivaraam Your last paragraph is actually another well-known bug waiting for someone to fix it :-) : https://github.com/commons-app/apps-android-commons/issues/2909

**Comment by sivaraam** [comment]
@nicolas-raoul Are you still facing this issue?

I could reliably see the Thank I give to images in the [Commons thank log](https://commons.wikimedia.org/wiki/Special:Log/thanks) despite the app stating that it could not successfully thank. (looks like a different issue).

**Comment by nicolas-raoul** [comment]
@sivaraam I just tried with the latest master, you are right! I guess this can be closed.
