### ISSUE TITLE
Clicking on Sending thanks should take to thank logs

### ISSUE THREAD

**Issue by vanshikaarora** [commons-app/apps-android-commons#2747]
**Summary:** 

**Expected**
After "Send Thanks" notification is completed clicking on notification should take us to "Thanks Log" for the image.  

**Observed**
Currently it opens Home page of the Application

**Would you like to work on the issue?**

Yes

**Comment by nicolas-raoul** [comment]
Sounds like a reasonable idea.

**Comment by vanshikaarora** [comment]
Hey @nicolas-raoul I just checked there is no API showing thanks log. Do we have a webpage to display thanks received we can display that Url in a webview.

**Comment by nicolas-raoul** [comment]
I suggest displaying the page that shows everyone's recent thanks. That's
all we have.

**Comment by vanshikaarora** [comment]
https://en.wikipedia.org/wiki/Special:Log/thanks
@nicolas-raoul Is this the correct link for Recent Thanks?

**Comment by nicolas-raoul** [comment]
@vanshikaarora Yes!

But now I am thinking: Do we really need notifications for this? How about nothing, or maybe just toasts/snackbars? @neslihanturan

**Comment by neslihanturan** [comment]
> @vanshikaarora Yes! 
@nicolas-raoul don't we need to use https://commons.wikimedia.org/wiki/Special:Log/thanks or https://commons.wikimedia.beta.wmflabs.org/wiki/Special:Log/thanks depending to the flavor instead?

> But now I am thinking: Do we really need notifications for this? How about nothing, or maybe just toasts/snackbars? @neslihanturan
I agree notification can be too much, on the other hand snacbar/toast can feel like "Is something really happened?"

**Comment by nicolas-raoul** [comment]
Ah yes beta might need a different URL.
But is we don't show notifications then no need to think about that :-)

When sending an email in Gmail, only a snackbar is shown. No need to show more here.

**Comment by vanshikaarora** [comment]
@nicolas-raoul @neslihanturan shall I remove the notification and add a snackbar instead?

**Comment by nicolas-raoul** [comment]
Yes thanks! :-)

**Comment by Rishavgupta12345** [comment]
@4D17Y4 now we have different feature in our app so we can close this old issue

**Comment by nicolas-raoul** [comment]
Created clearer issue: https://github.com/commons-app/apps-android-commons/issues/4906
