### ISSUE TITLE
Disable the answering buttons in Review Activity until image is loaded

### ISSUE THREAD

**Issue by vanshikaarora** [commons-app/apps-android-commons#2753]
**Summary:** 

Disable the yes and no buttons in Review activity until image is loaded

**Would you like to work on the issue?**

Yes

**Comment by noahwalugembe** [comment]
Yes i would like to work on this

**Comment by neslihanturan** [comment]
Please do not @noahwalugembe , @vanshikaarora already worked on it as she stated:
>Would you like to work on the issue?
Yes

And she already sent a PR for this issue.

**Comment by noahwalugembe** [comment]
Sorry dear my net work was down I posted before seeing the updated page

**Comment by neslihanturan** [comment]
No problem @noahwalugembe :) We always try to avoid two PRs for the same issue.

**Comment by yashk2000** [comment]
I would like to work on this issue.
