### ISSUE TITLE
JSON version of image info API doesn't sort the results by timestamp

### ISSUE THREAD

**Issue by maskaravivek** [commons-app/apps-android-commons#2755]
I am sending parameters to sort by `timestamp` but it seems to be not working for the JSON API. There seems to an upstream issue in the JSON version of the API. 

JSON response: https://commons.wikimedia.org/w/api.php?action=query&format=json&generator=categorymembers&gcmtype=file&gcmtitle=Category%3AFeatured_pictures_on_Wikimedia_Commons&gcmsort=timestamp&gcmdir=desc&gcmlimit=10&prop=imageinfo&iiprop=url%7Cextmetadata&iiextmetadatafilter=DateTime%7CCategories%7CGPSLatitude%7CGPSLongitude%7CImageDescription%7CDateTimeOriginal%7CArtist%7CLicenseShortName&iiextmetadatalanguage=en

XML response: https://commons.wikimedia.org/w/api.php?action=query&format=xml&generator=categorymembers&gcmtype=file&gcmtitle=Category%3AFeatured_pictures_on_Wikimedia_Commons&gcmsort=timestamp&gcmdir=desc&gcmlimit=10&prop=imageinfo&iiprop=url%7Cextmetadata&iiextmetadatafilter=DateTime%7CCategories%7CGPSLatitude%7CGPSLongitude%7CImageDescription%7CDateTimeOriginal%7CArtist%7CLicenseShortName&iiextmetadatalanguage=en

IMO, we can merge this and create an upstream issue to get it fixed in the backend.

_Originally posted by @maskaravivek in https://github.com/commons-app/apps-android-commons/pull/2731#issuecomment-476529857_

**Comment by nicolas-raoul** [comment]
Please anyone:
1. Reproduce the problem
2. Create an upstream issue report at http://phabricator.wikimedia.org
3. Link to it from here
Thanks! :-)

**Comment by domdomegg** [comment]
Created https://phabricator.wikimedia.org/T219576

**Comment by SamuelleMollard** [comment]
I don't really understand if that is a bug, though if you want to I can try and create an OrderedJson object, which will be an ordered JSON, so that we can have JSON ordered and keep them ordered. It will not be preserved through the API, but I believe we can re sort it every time we get it through the API, and we can send it since the API doesn't care about ordering.

**Comment by nicolas-raoul** [comment]
" good first issue" was about creating the Phabricator issue, which is done now :-)

I also remove the "upstream" label because Mediawiki says it works as intended.

Can anyone remember us where is the actual impact on the app? What are the app usage steps to show the problem within the app?

**Comment by maskaravivek** [comment]
The app is no longer using this API. So i am closing this for now.
