### ISSUE TITLE
Pic of the Day Widget API not working

### ISSUE THREAD

**Issue by madhurgupta10** [commons-app/apps-android-commons#2756]
**Summary:** 
Pic of the Day Widget API not working

Current API (https://commons.wikimedia.beta.wmflabs.org/w/api.php?action=query&generator=images&format=json&titles=Template%3APotd%2F2019-03-26&prop=imageinfo&iiprop=url%7Cextmetadata) used to fetch Pic of the day returns 

`{
"batchcomplete": ""
}`

**Would you like to work on the issue?**
Yes

**Comment by maskaravivek** [comment]
@madhurgupta10 Can you test if it is working on prod?

**Comment by madhurgupta10** [comment]
https://commons.wikimedia.org/w/api.php?action=query&generator=images&format=json&titles=Template%3APotd%2F2019-03-26&prop=imageinfo&iiprop=url%7Cextmetadata

Works @maskaravivek

**Comment by maskaravivek** [comment]
On beta server no images would be present in POTD list.

**Comment by madhurgupta10** [comment]
@maskaravivek Okay, then I think we can close the issue :)
