### ISSUE TITLE
Add title of the picture to the App Widget

### ISSUE THREAD

**Issue by madhurgupta10** [commons-app/apps-android-commons#2757]
**Summary:** 
Add the title of the picture to the App Widget so that users can know about the picture they are looking at.

**Would you like to work on the issue?**
Yes

**Comment by noahwalugembe** [comment]
> **Summary:**
> Add the title of the picture to the App Widget so that users can know about the picture they are looking at.
> 
> **Would you like to work on the issue?**
> Yes

Yes.  can i work on it
