### ISSUE TITLE
Wrong translated license symbols

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#276]
> I have just installed the app and remarked that license symbols (in the preferences menu; ) include strange characters so that they are barely recognisable by newbies:CCu00A0U stands for CC-BY-SA 3.0 (description helped me a bit)
> 
> I am using the app on Polish language phone.
> 
> Regards, Bonvol

Could anyone familiar with translations help with this?

**Comment by nicolas-raoul** [comment]
I believe this is #217 :-)
