### ISSUE TITLE
Peer Review loads different image on rotation

### ISSUE THREAD

**Issue by sp2710** [commons-app/apps-android-commons#2761]
**Summary:** 

After rotating the device peer review Activity is loading a different image 

**Steps to reproduce:** 

Rotate screen on Peer Review activity

**Device and Android version:** 

Motorola Moto G5 plus on API 24
 
**Commons app version:** 

Latest master

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/39745544/55072676-b81f4000-50b1-11e9-84dc-af416109a7cd.gif)

**Would you like to work on the issue?**

Yes

**Comment by neslihanturan** [comment]
Ah thanks for discovering:)
