### ISSUE TITLE
Peer review: show description

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#2763]
Description often says why a picture is special. For instance:

Title: Abdel Rawid
Description: Soccer player in the 2020 Iraqi Olympics team

That can change the reviewer's perception from "_Hum probably another worthless selfie_" to "_Whoa this is a very valuable picture_".

**Comment by neslihanturan** [comment]
Referencing #2698

**Comment by sp2710** [comment]
Currently on clicking the image it does nothing. IMO we should show the user the media details on clicking the image same as we do for explore and contributions fragment.

**Comment by nicolas-raoul** [comment]
@sp2710 That would be great indeed!

**Comment by neslihanturan** [comment]
assigned to @sp2710

**Comment by Prince-kushwaha** [comment]
@nicolas-raoul if you want i  work on this issue in my pull requests i make required changes

**Comment by nicolas-raoul** [comment]
@Prince-kushwaha It should be a separate pull request. Feel free to unassign yourself from some other issues if you want to focus on this one.

**Comment by Prince-kushwaha** [comment]
@nicolas-raoul I unassign from some issue can i work on this issue

**Comment by nicolas-raoul** [comment]
OK thanks :-)

**Comment by Prince-kushwaha** [comment]
@nicolas-raoul i think idea of @cypherop is right that when we click on the Peer review image Media Detail page is open it show all 
information about image not just description becouse for any user to review the image user known everything about image 
So can i implement to show Media Detail when click on the peer review image ?

**Comment by nicolas-raoul** [comment]
@Prince-kushwaha OK!
