### ISSUE TITLE
Nearby places aren't sorted

### ISSUE THREAD

**Issue by tacsipacsi** [commons-app/apps-android-commons#277]
On a Samsung Galaxy A3, if I open "Nearby Places", regardless of the GPS is turned on or off, the list shows the places not sorted by distance, but in the order as they appear in the CSV. I would expect an error message saying the nearby places cannot be determined if GPS is off, and of course sorted by distance if on. I have an Android Studio, but I don't know how to debug this issue; if you help me, I try to debug it—it can turn out that the problem is in my device.
P.S. Is there any convenient way (web service) to localize this app, or I have to edit the XML manually?

**Comment by nicolas-raoul** [comment]
Strange, the list is always sorted for me! Would you mind pasting the logcat?

About localization: We are waiting for the translatewiki guys to create our project, I can't understand why it takes them so much time, feel free to ask them about the status of this at https://translatewiki.net/wiki/Support#Former_WMF_app_now_community-maintained,_where_to_crowdsource_localization?_49961 Thanks!

**Comment by misaochan** [comment]
Hi @tacsipasci ,

It should already be sorted by distance if the GPS is on. I like your suggestion of displaying an error message if the GPS is off, though. 

Do you have your GPS on the entire time or do you just enable it after loading the list of nearby places?

**Comment by tacsipacsi** [comment]
Now it sorted for the first time (I've tried it about five-ten times)—at least five minutes after opening the Nearby list.
@nicolas-raoul Where can I find the logcat?
@misaochan I tried it now and also earlier with GPS entirely turned off and GPS turned on before opening the list. (Sometimes I opened the list first by mistake, but usually not.)

**Comment by misaochan** [comment]
Interesting. Do you have similar problems when accessing other location based apps, or is it just us?

**Comment by nicolas-raoul** [comment]
How to get the logcat: http://android.stackexchange.com/a/157594/501

**Comment by tobias47n9e** [comment]
I did some tests with GPS spoofing. It takes the app a few tries to recover to the real position after the spoofer is turned off. That might be a related issue to this one.

**Comment by tacsipacsi** [comment]
@nicolas-raoul I can't get logcat working… I don't find any drivers for my phone on the Samsung website. :(

**Comment by tobias47n9e** [comment]
The Wikidata list is now sorted by distance and I don't think we will fix issues with the old list anymore. Please reopen if you feel there is something we can do to improve the situation.

**Comment by tacsipacsi** [comment]
Strange... When I open Nearby, it immediately says "No nearby places found", without even trying to get my position (Google Maps works normally). Android Marshmallow (6.0.1), Commons app v2.4.1 (latest beta).

**Comment by misaochan** [comment]
@tacsipacsi Yeah, we are having issues with that currently (see #650 ). We are still trying to fix it, sorry about that!

**Comment by tacsipacsi** [comment]
OK, no problem (actually I don't use this feature, just opened it for testing; I don't like photographing with mobile, I use it only when I don't have a normal camera). It didn't work for me either after giving permission to the app – maybe I don't have real GPS signal, and Google Maps works with network-based location.
