### ISSUE TITLE
Incomplete Nearby List shown in Landscape mode

### ISSUE THREAD

**Issue by madhurgupta10** [commons-app/apps-android-commons#2770]
**Summary:** 
Incomplete List is shown in Landscape mode.

**Steps to reproduce:** 
Go to Nearby, hit the List Icon and scroll to the end, then switch to landscape mode to see the difference.

Actual Behaviour
Sector 70, Mohali (Last Element of my list) which you see in Portrait mode is not visible in Landscape mode

Expected Behaviour
Upon Rotation to Landscape mode, the list shown should be the same as that of portrait mode.

**Device and Android version:** 
Xiaomi Mi A1 API 28 stock android.
 
**Commons app version:** 
Latest betaDebug

**Screen-shots:** 
![Screenshot_20190328-023942](https://user-images.githubusercontent.com/30932899/55112778-55ef2b00-5103-11e9-965a-cc9b68c69c46.png)
![Screenshot_20190328-023934](https://user-images.githubusercontent.com/30932899/55112783-58518500-5103-11e9-9e3d-26b6609f0da6.png)

**Would you like to work on the issue?**
Yes

**Comment by nicolas-raoul** [comment]
Please add to your issue:
- What you expected
- What you saw instead
Thanks! :-)

**Comment by madhurgupta10** [comment]
@nicolas-raoul Sector 70, Mohali (Last Element of my list) which you see in Portrait mode is not visible in Landscape mode

**Comment by nicolas-raoul** [comment]
Even if you scroll down to the bottom of the list, right?

**Comment by madhurgupta10** [comment]
@nicolas-raoul Yes, that is the problem

**Comment by madhurgupta10** [comment]
@nicolas-raoul this code is the root of this problem, we need to remove it
`bottomSheet.getLayoutParams().height = getActivity().getWindowManager()             .getDefaultDisplay().getHeight() / 16 * 9;`

**Comment by nicolas-raoul** [comment]
Does it work well without? :-)

**Comment by madhurgupta10** [comment]
@nicolas-raoul Yes, I have tested it, but if we remove it the list would occupy the all available screen optionally we can add marginTop to maintain the same ratio

**Comment by madhurgupta10** [comment]
![Screenshot_20190403-142646](https://user-images.githubusercontent.com/30932899/55466382-afcc8500-561c-11e9-8d8a-b674e261db36.png)
![Screenshot_20190403-142704](https://user-images.githubusercontent.com/30932899/55466383-b0651b80-561c-11e9-9ff0-1fd0271f38ee.png)

**Comment by ashishkumar468** [comment]
@madhurgupta10 The list inside the bottomsheet is scrollable, right ?, so even if we fix the height of the bottom sheet , the list would have had all the items irrespective of the orientation, right ?

**Comment by madhurgupta10** [comment]
@ashishkumar468 The list inside is 100% scrollable, the problem we had earlier was, when the view is generated in potrait mode the height was set according to the potrait mode, when we rotate the height of the cointainer remained same as of potrait, due to the we were not able to see the rest of the list which was already generated but was hidden.

**Comment by Prince-kushwaha** [comment]
can i work on this issue

**Comment by madhurgupta10** [comment]
@Prince-kushwaha yes, feel free to make a PR
