### ISSUE TITLE
Search this area takes forever to load if no internet connection

### ISSUE THREAD

**Issue by sp2710** [commons-app/apps-android-commons#2773]
**Summary:** 

If there is no internet then clicking search this area button in nearby makes starts loading the map and it takes forever to load. An app kill if require even if the connection is re-established.

**Steps to reproduce:** 

1.Go to nearby
2.After map is loaded turn off internet.
3.move to a different location.
4.Click on search this area button.
5.The app gets stuck at this point. Even if the connection is re-established it requires an app kill to load the nearby

**What did you expect the app to do, and what did you see instead?**

I think Search This Area button should not be there if there is no internet connection.

**Device and Android version:** 

Motorola Moto G5 plus with API 24

**Commons app version:** 

Latest Master 

**Would you like to work on the issue?**

Yes

**Comment by nicolas-raoul** [comment]
I noticed that indeed. Could you detail what you plan to do?
- Just remove the "Search this area" button?
- Or display an error if connection times out, and retry the next time the user opens that tab or press "retry"?

**Comment by sp2710** [comment]
@nicolas-raoul I removed the "Search this Area" button if connection is lost. Currently if connection gets lost it shows a snackbar With the message but "Search this Area button" is still there. Clicking it makes the nearby stuck at it even if the connection is re-established. 
IMO removing "Search This Area" button whenever connection gets lost would be a nice option.
