### ISSUE TITLE
Replace Search Button with FAB

### ISSUE THREAD

**Issue by madhurgupta10** [commons-app/apps-android-commons#2776]
**Summary:** 
Replace Search Button with FAB for making the app more Material Design friendly.

**Would you like to work on the issue?**
Yes

**Comment by neslihanturan** [comment]
I think such a big design change needs some discussion with team. Personally I don't think having search button in FAB is better than having it on the top.

**Comment by neslihanturan** [comment]
Closing this one for now since @domdomegg and me doesn't find this change necessary. Please feel free to reopen if you think this change is needed.

**Comment by madhurgupta10** [comment]
@neslihanturan Definitely, I will take care of this :)

**Comment by madhurgupta10** [comment]
@neslihanturan Okay cool 👍
