### ISSUE TITLE
Upload FAB Missing Padding in Nearby 

### ISSUE THREAD

**Issue by madhurgupta10** [commons-app/apps-android-commons#2779]
**Summary:** 
Upload FAB Button is Missing Padding in Nearby 

**Screenshot**
![Screenshot_20190328-082901](https://user-images.githubusercontent.com/30932899/55126655-a1213200-5133-11e9-9683-67e086713eb4.png)

**Would you like to work on the issue?**
Yes

**Comment by neslihanturan** [comment]
This UI change is necessary, thanks for pointing it out @madhurgupta10 .
