### ISSUE TITLE
Multiple instances of Peer Review

### ISSUE THREAD

**Issue by sp2710** [commons-app/apps-android-commons#2781]
**Summary:** 

Multiple instances of Peer Review Activity are created if opened multiple times.

**Steps to reproduce:** 

1.Click on Peer Review several times from the Navigation Drawer
2.Click on Back button.
 
It can be seen that multiple instances are created

**Device and Android version:** 

Motorola Moto G5 plus with API 24
 
**Commons app version:** 

Latest Master

**Would you like to work on the issue?**

Yes

**Comment by domdomegg** [comment]
This is likely an issue with intent flags in either NavigationBaseActivity or the peer review activity's `startYourself`

**Comment by sp2710** [comment]
@domdomegg Yes it was an issue with flags in peer review activity. I have raised a PR for it.
