### ISSUE TITLE
Remove unnecessary tags from string resources

### ISSUE THREAD

**Issue by domdomegg** [commons-app/apps-android-commons#2782]
**Summary:** 

NB: This has potential merge conflicts with #2741, so probably best to wait until that's merged before working on this (or work on just the ones outside WelcomeActivity).

Would be ideal to remove any tags like `CDATA` or `<u>` from string resources. There are probably more but the ones I know about are the 'More information' link from WelcomeActivity, and all the links from AboutActivity. Ideally we should store just the link text in `strings.xml`, then use a Spannable / similar to give the links an underline, and use onClick listeners with either lambda functions or Butterknife to call `Utils.handleWebUrl`.

**Would you like to work on the issue?**

No, but this would be a perfect first issue (when #2741 merged)

**Comment by ronanb80** [comment]
I can take a look in to this when #2741 is merged

**Comment by domdomegg** [comment]
To be assigned to @ronanb80 once #2741 merged

**Comment by bistaastha** [comment]
Hi. Can I work on this?

**Comment by nicolas-raoul** [comment]
@bistaastha OK it is yours :-)
