### ISSUE TITLE
Position of tabs on Main Activity is wrong for a while

### ISSUE THREAD

**Issue by neslihanturan** [commons-app/apps-android-commons#2785]
**Summary:** 
For a while, position of Main Activity tabs are not centered in both half of the page, they are centered on whole page instead. They weren't like that previously, something should have break them. 

**Expected behaviour:**
They both should be centered to both half of the page. 

![image](https://user-images.githubusercontent.com/3127881/55157775-51ac2780-516e-11e9-8d0a-d7ed24a6abf1.png)

**Comment by Menna-Elshazly** [comment]
@maskaravivek is that considered an issue ?

**Comment by domdomegg** [comment]
> @maskaravivek is that considered an issue ?

I believe the idea is that on any size screen the tabs should both be 50% the width of the screen.

**Comment by Menna-Elshazly** [comment]
i will solve it

**Comment by Rishavgupta12345** [comment]
@4D17Y4 we have a completely different Ui now so we can close this issue
