### ISSUE TITLE
Navigation UI problem in split screen mode

### ISSUE THREAD

**Issue by madhurgupta10** [commons-app/apps-android-commons#2788]
**Summary:** 
Navigation UI problem in split screen mode

**Steps to reproduce:** 
Go to Split Screen Mode, Open Navigation Drawer

**Device and Android version:** 
Xiaomi Mi A1 API Level 28 stock

**Commons app version:** 
latest betaDebug

**Screen-shots:** 
![Screenshot_20190328-222733](https://user-images.githubusercontent.com/30932899/55177431-3b6f8d00-51a9-11e9-80e4-7c0af8ca7906.png)

**Would you like to work on the issue?**
Yes

**Comment by domdomegg** [comment]
Sorry if it's a dumb question to ask, what exactly is the issue with that screenshot?

**Comment by madhurgupta10** [comment]
@domdomegg 
The Achievement button is very small and joining the edge and it very difficult to click.
![InkedScreenshot_20190328-222733_LI](https://user-images.githubusercontent.com/30932899/55194681-63beb200-51d0-11e9-8410-83d31c1f785e.jpg)

**Comment by madhurgupta10** [comment]
@domdomegg PR is ready :)
