### ISSUE TITLE
Make upload folder selectable 

### ISSUE THREAD

**Issue by Halibutt** [commons-app/apps-android-commons#279]
I have my mobile pictures in different folders. Some are on my SD card, some in phone memory, some photo apps have their own folders and so on. Yet apparently I can only upload from one folder (unless I "send to" from gallery app to Commons Upload). Some basic file explorer function is definitely needed.

**Comment by misaochan** [comment]
Hi @Halibutt , could you send us a screenshot of what you see when you tap on the 'gallery' icon from within the app? In my case, I can select from gallery, google drive, google photos, etc.

**Comment by Halibutt** [comment]
Huh, sorry, false alarm, found it. The window showed me an empty folder that used to contain pictures. Only just now I accidently discovered, that when I swipe right, a drawer with additional options appears (Gallery, SD card and whatnot). I guess this might be a feature of my handset (Huawei P8 lite), as it uses non-standard MIUI.

**Comment by misaochan** [comment]
Haha, good to know. :) Are we okay to close this, then?

**Comment by misaochan** [comment]
Closing this, please feel free to reopen if you have further issues @Halibutt . :)
