### ISSUE TITLE
Deletion request notification goes to wrong URL

### ISSUE THREAD

**Issue by domdomegg** [commons-app/apps-android-commons#2794]
**Summary:** 

Clicking the deletion success notification adds an extra `File:` to the URL e.g.:

https://commons.m.wikimedia.beta.wmflabs.org/wiki/Commons:Deletion_requests/File:File:MobileTest_190327-105304.jpg

But it should be

https://commons.m.wikimedia.beta.wmflabs.org/wiki/Commons:Deletion_requests/File:MobileTest_190327-105304.jpg

I've only tested this on beta (as don't want to delete real files on Commons) - even if it just beta it is still a bug. Maybe a solution to test this would be to upload some real images, then delete those - you can always reupload them if you are intending them to be permanently on commons.

**Comment by madhurgupta10** [comment]
@domdomegg I would like to solve it :)

**Comment by madhurgupta10** [comment]
@domdomegg Done :)
