### ISSUE TITLE
Map showing nearby Commons pictures

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#28]
WikiMiniAtlas can be used to show Commons pictures on a map.

We could take latitude/longitude from the GPS and open wma.wmflabs.org in the default browser.

URL syntax details: http://webapps.stackexchange.com/a/86266/1374

While it is not directly about uploading, I believe it is still on-topic for this app, as people might want to check covered subjects before uploading their own similar (and probably lower-resolution) pictures.
Not sure where in the UI that would fit.

**Comment by misaochan** [comment]
I think this would synergize well with #73 ? We could put both in the same part of the UI maybe, so people can see nearby pics as well as nearby articles without pics. Not sure how feasible that would be, but just a thought...

**Comment by misaochan** [comment]
We are currently discussing adding this to the UI at #725

**Comment by nicolas-raoul** [comment]
https://tools.wmflabs.org/wikishootme actually does a better job at showing existing nearby pictures than WikiMiniAtlas. Anyway rather than a link we should probably show the map inside the app.

**Comment by nicolas-raoul** [comment]
Existing Commons pictures could be shown on the Nearby map, but they should probably be hidden by default, or at least less visible than items missing a picture. Once again, WikiShootMe is a good example to follow.

**Comment by misaochan** [comment]
Instead of showing them on Nearby, why not show them in our brand new Explore feature? I think it would be nice to have a map icon in Explore that loads all the nearby Commons pictures on a map. That would help keep use cases nice and separate - users who want to upload pictures would go to Nearby, and users who want to browse pictures can go to Explore.

(I was in favour of having them in Nearby before, but now that Explore has been implemented in the last year I think it would be better suited for it)

**Comment by nicolas-raoul** [comment]
@misaochan Sounds reasonable. What UI would be the most understandable? Maybe tabs like "Featured", "Nearby", "From Android"?

**Comment by misaochan** [comment]
That would be awesome!

(If you guys are planning to mentor a GSoC this year, I think this could be a great project too ;))

**Comment by misaochan** [comment]
Now that we already have pins for Wikidata items with pictures, I wonder if it would make sense for the next step to involve displaying the actual picture (maybe in a tiny thumbnail, like [this](https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRZhR9I45smnnu_M1DupcB-uY8OQi6ZHe62j1iOyLoMQSpV1GrV). Especially if the user submits photos to Nearby, it would be encouraging for them to be able to actually see their own photo on the map the next time they check Nearby.

Of course, this should be disabled in limited connection mode.

**Comment by nicolas-raoul** [comment]
great idea! It should not cover the no-picture pins, though.

**Comment by misaochan** [comment]
@nicolas-raoul Hmm, yeah, I reckon there's a way to set the no-picture pins to always be in front (I hope).

**Comment by ashishkumar468** [comment]
I am assuming this discussion was for nearby, closing this, feel free to open if I have misunderstood the issue

**Comment by nicolas-raoul** [comment]
@ashishkumar468 Nearby only shows Wikidata items.

The goal of this feature is to display all existing Commons pictures, independently of Wikidata items.

For instance within a forest it would show me what places have a lot of pictures in Commons, and which places have no picture on Commons... even if Wikidata has nothing about this forest has zero Wikidata item.

**Comment by ashishkumar468** [comment]
My bad @nicolas-raoul, thanks for re-opening it :)

**Comment by neslihanturan** [comment]
Hi everyone, here is my first mockup suggestion based on the discussions here. Please write me your feedback.
![attemt1](https://user-images.githubusercontent.com/3127881/120466757-19d14800-c3a8-11eb-9b62-7aa31fc9e43e.png)

**Comment by nicolas-raoul** [comment]
It looks fantastic Nes! Tapping a picture on the map would open this picture's media details I guess?

**Comment by neslihanturan** [comment]
Yeah, I was thinking the same @nicolas-raoul

**Comment by misaochan** [comment]
Looks great to me, thanks for the mockup @neslihanturan ! I agree that tapping on the picture should open up media details for that picture.

I think I might have made, uh, a slight planning mishap with our Nearby pins. :) Currently users can deselect "needs photos" in Nearby, which will show pins that already have photos (but not the photos themselves). That would be somewhat redundant with this new feature in Explore.  Do we want to remove that option once this feature is up in Explore, or do we want to switch this feature to the Nearby map instead of Explore?

**Comment by neslihanturan** [comment]
Hmm, since the one in nearby is for wikidata items only, but this one is for commons images that has location and explore gives us an interface to search items, I think that would be better to have this feature in explore. However, we can imrove the feature that we have in nearby by displaying images in the same way on nearby map too.

**Comment by misaochan** [comment]
Right, that makes sense, let's stick to Explore then. And we can add another enhancement issue for adding the feature for Wikidata items on Nearby perhaps?

**Comment by nicolas-raoul** [comment]
It does not seem to be duplicates to me.
1. One activity focuses on taking pics (of any item, having or not having
pics yet).
2. The other activity is really a search for existing pictures.
Maybe we could start thinking about more explicit names for these two?
1. "Go" (à la Pokemon Go), "Photohunt", "Shoot", ... with an icon
representing a shoe
2. "Search", "View", ... with a loop icon

**Comment by misaochan** [comment]
Haha yeah, we should think about renaming Nearby at some point, especially since users are not restricted to "nearby" items anymore. I like "photo hunt" or "Go", but probably not "shoot" ;)

**Comment by neslihanturan** [comment]
Hmm I like "Photo hunt" among suggestions. Also more brain storming: "Photo walk", "Upload on map"

**Comment by neslihanturan** [comment]
Hey team, I was writing the query for this issue and there is a point that is not clear for me. Do we try to display nearby wikidata items that has pictures, and/or commons uploads that has lat long is entered. As far as I understood the one we want to achieve on the first place is displaying nearby places that has pictures (according to our explore parameter).

**Comment by nicolas-raoul** [comment]
This issue is about showing **all Commons pictures that have coordinates**. It does not rely on Wikidata, in patrticular it is not limited to pictures that are used on Wikidata.

The request should not be a SPARQL request. Instead, I believe you should use this Commons api.php request: https://commons.wikimedia.org/w/api.php?callback=jQuery3100638443216302247_1636028648481&action=query&list=geosearch&gsbbox=35.0897147419763%7C128.89297485351565%7C35.06344403936958%7C129.1678047180176&gsnamespace=6&gslimit=500&format=json&_=1636028648587 as seen at https://wikishootme.toolforge.org/#lat=35.07657939067294&lng=129.03038978576663&zoom=13

_(if that does not work for some reason, you could try something like https://wma.wmflabs.org/label.php?l=commons&a=17599&b=38637&z=13&g=Earth  as seen at [WikiMiniAtlas](https://wma.wmflabs.org/iframe.html?wma=38.8977_-77.0365_700_500_commons_14_en&globe=Earth&lang=en) but I think api.php is more reliable)_

**Comment by Easytatenda** [comment]
Help with my nearby locations
