### ISSUE TITLE
Codecov reports for PRs?

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#2805]
Some time ago (I can't remember how long, probably a year or so?) we used to have Codecov reports for every PR that was submitted. In the pull request itself, Codecov would mention how merging the PR would affect test coverage.

Somewhere along the way, we lost that. Does anyone know why, and how we can get these reports activated again? @whym @domdomegg @psh @maskaravivek

**Comment by misaochan** [comment]
Edit: Oh, I just realized that some PRs have them, but some don't. For instance, #2798 does not have them, but #2792 does. It does appear that the majority of PRs have them, although the report will be posted at a variable time.

**Comment by maskaravivek** [comment]
Yes, I have observed that sometimes the report takes a lot of time to get generated.

**Comment by domdomegg** [comment]
It is bizarre that it does take so long with some PRs (like #2798). Maybe it's worth raising a bug upstream with Codecov? I've found a trick to force it to review it again is to redo the Travis build. This seems to me maybe like some webhook getting lost on its way from either Travis or Github to Codecov.

**Comment by madhurgupta10** [comment]
This issue is fixed now :)
