### ISSUE TITLE
Moving to travis-ci.com (from travis-ci.org)

### ISSUE THREAD

**Issue by domdomegg** [commons-app/apps-android-commons#2806]
**Summary:** 

Travis advise that using travis-ci.com is now recommended for open source projects (over travis-ci.org)

See the announcement: https://docs.travis-ci.com/user/migrate/open-source-on-travis-ci-com/

Migration guide: https://docs.travis-ci.com/user/migrate/open-source-repository-migration

This is probably low priority for now.

**Comment by sivaraam** [comment]
We switched completely to GitHub actions now. As a consequence, this has become irrelevant. Hence, closing.
