### ISSUE TITLE
Option to Remove a new language description while uploading

### ISSUE THREAD

**Issue by madhurgupta10** [commons-app/apps-android-commons#2810]
**Summary:** 

Sometimes, a user might accidentally hit the "+" when uploading a photo, there is no option to remove it. We should add a "-" so that the user can remove it.

**Steps to reproduce:** 
Upload a new photo, hit the + button many times in Step 1, then try to remove not needed ones.

**Screen-shots:** 
![Screenshot_20190330-065845](https://user-images.githubusercontent.com/30932899/55269473-c93a9d80-52b9-11e9-88ab-5c38ec27e3d2.png)

**Would you like to work on the issue?**
Yes

**Comment by maskaravivek** [comment]
Apart from this, the user should not be allowed to add the same language twice.

**Comment by madhurgupta10** [comment]
@maskaravivek Good Point, I would implement that as well :)

**Comment by domdomegg** [comment]
> @maskaravivek Good Point, I would implement that as well :)

I'm not sure how tightly bound this code is, but if you are it might be best to do them as separate PRs so they're easier to review.

**Comment by madhurgupta10** [comment]
@domdomegg Cool, I will make separate issue for it :)

**Comment by maxbetton** [comment]
Hello, I see the issue is available. Can I take it ?

**Comment by madhurgupta10** [comment]
@maxbetton Sure go ahead!

**Comment by madhurgupta10** [comment]
Feel free to refer https://github.com/commons-app/apps-android-commons/pull/3504#issuecomment-600801773 for UI

**Comment by maxbetton** [comment]
Thank you. For sure, I saw it :)

**Comment by maxbetton** [comment]
Just to be sure, are we OK with that?
![Screenshot_1611321374](https://user-images.githubusercontent.com/55984454/105495474-83d03700-5cbc-11eb-8539-f31cf803d7f3.png)

**Comment by madhurgupta10** [comment]
@maxbetton My Bad, I see that some comments got hidden and the UI which was actually finalised is this https://github.com/commons-app/apps-android-commons/pull/3504#issuecomment-619364827
![80324860-0a8ddb80-8833-11ea-8471-ba2319196c5e](https://user-images.githubusercontent.com/30932899/105569781-b7699a80-5d6a-11eb-9768-f337f650b86f.png)

**Comment by maxbetton** [comment]
I have open the PR #4206 for this issue;

**Comment by neslihanturan** [comment]
The PR #4206 was working, however it had irrelevant changes, thus we couldn't merge it. Anyone else can implement is in the same way and this issue should be solved :)

**Comment by Ayan-10** [comment]
@neslihanturan Can I do this?

**Comment by madhurgupta10** [comment]
@Ayan-10 feel free to create a PR for this issue!

**Comment by Ayan-10** [comment]
@madhurgupta10 can I use 

![Screenshot_20210420_170952](https://user-images.githubusercontent.com/71203077/115390383-ce9a1600-a1fb-11eb-90e3-887fc582d099.png)

this remove icon. Instead of X icon?

**Comment by madhurgupta10** [comment]
@Ayan-10 I would prefer the "x" but lets discuss it with @neslihanturan

**Comment by misaochan** [comment]
I would strongly prefer an "x" as well, it's much more commonly used.

**Comment by Ayan-10** [comment]
@madhurgupta10 @misaochan Thank you for your response. I create the PR.

**Comment by Ayan-10** [comment]
> I would say "x" too. Also please consider the previous PR implementation since it was mostly working in general.

@neslihanturan I already made a PR. Please have a look at #4406
