### ISSUE TITLE
Nominating for deletion is cancelled on leaving the media details

### ISSUE THREAD

**Issue by domdomegg** [commons-app/apps-android-commons#2815]
If the user clicks off the screen the deletion nomination is cancelled. This is better than the previous behaviour (just crashing), however ideally the deletion nomination would continue after leaving the media details screen, and just not try to edit the views if we're out of the media details.

Also, nominating for deletion seems quite slow - maybe a semi-solution for this would to be at least change the button text to 'nominating for deletion' with a spinner so the user would get some feedback it was working at least.

Also see https://github.com/commons-app/apps-android-commons/pull/2792#issuecomment-478230751

**Comment by domdomegg** [comment]
This may have actually been done, this is based on the 2.10-release branch. If so please close/ask me to close this issue

**Comment by Pratham2305** [comment]
Hi! @domdomegg I think the issue still exists on the latest master, Can I work on this one?

**Comment by domdomegg** [comment]
> Hi! @domdomegg I think the issue still exists on the latest master, Can I work on this one?

Sure
