### ISSUE TITLE
Espresso tests for testing upload with multilingual descriptions

### ISSUE THREAD

**Issue by maskaravivek** [commons-app/apps-android-commons#2817]
**Summary:** 

It would be nice to automatically test uploads with multilingual descriptions. The user can click on the (+) button to add a description in another language. 

![device-2019-03-30-173139](https://user-images.githubusercontent.com/3069373/55275817-b653b780-5311-11e9-85dd-541cd00f7c0f.png)

IMO, there are two things that need to be tested here. 

- test that verifies that the user is able to enter descriptions in multiple languages.
- test that verifies that an image with multiple descriptions is queued for upload.

**Comment by KaveriKR** [comment]
Is it still open? , I would like to work on it.

**Comment by maskaravivek** [comment]
@KaveriKR I have already started working on it. :)
