### ISSUE TITLE
Modify warning about existing picture name

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#2818]
His comment: 

> It isn't possible to use one name for a series of pictures. In the older version it was possible. Now I have to copy and paste the name and add manually a different number. That's horrible.
> 
> At the moment all of my uploads fail and I don't know why.

Did we change something that broke the automatic appending of suffixes to files of the same name? @ashishkumar468 @maskaravivek 

Edit: The scope of this task has changed to:

Can we include some more detailed text to the warning about even f they proceed with same name, a suffix will be added to their filename. Besides can we add "don't display again" button to this warning?

**Comment by maskaravivek** [comment]
@misaochan Just to confirm, is this user an alpha user or a beta/normal user?

**Comment by misaochan** [comment]
I asked him to confirm, but `2.10.2~66e1539a1` indicates that he is on alpha.

**Comment by misaochan** [comment]
Edit: How strange, he isn't in our alpha testing group as far as I can see. I wonder why the feedback is displaying that as his version?

**Comment by maskaravivek** [comment]
Indeed he is on our beta version ie. https://github.com/commons-app/apps-android-commons/commit/66e1539a1. 

We decided to use SHA for both alpha and normal releases. See comment. 

>> Given that the version number does not actually HAVE to be incremental, and AFAIK does not even need to be all numbers (the build.gradle equivalent is actually a "version name"), why not use the SHA for both?

https://github.com/commons-app/apps-android-commons/issues/2127#issuecomment-448531983

**Comment by misaochan** [comment]
Eep. Let's carry on the discussion there, I think I might not have worded that comment clearly, lol.

**Comment by maskaravivek** [comment]
> It isn't possible to use one name for a series of pictures

It works for me. It shows a warning popup message but lets me continue. 

Also, i verified that the suffixes are appended as expected.

**Comment by maskaravivek** [comment]
Maybe after a user reaches a certain level, we can let him choose to not display these warnings again and again.

**Comment by neslihanturan** [comment]
>It isn't possible to use one name for a series of pictures. In the older version it was possible. Now I have to copy and paste the name and add manually a different number. That's horrible.

It can be about missing "Use previous title and description button" too. 

On the other hand, the warning feels like if I proceed with the same file name, I will violate Commons. However we already add suffixes for same file names. Can we include some more detailed text to the warning about even f they proceed with same name, a suffix will be added to their filename. Besides can we add "don't display again" button to this warning?

**Comment by misaochan** [comment]
This poster clarified that he was actually talking about #2035 . Sorry for the false alarm!

I actually don't much see the point in the warning about the same filename since suffixes are automatically appended anyway. But if we keep the warning, I agree with @neslihanturan 's suggestion:

> Can we include some more detailed text to the warning about even f they proceed with same name, a suffix will be added to their filename. Besides can we add "don't display again" button to this warning?

Shall we go with that?

**Comment by jamespm4** [comment]
I'm looking for a first repo to work on, and I'm interested in working on this.

**Comment by misaochan** [comment]
@jamespm4 It is yours. :)

**Comment by misaochan** [comment]
@anadi198 it seems like this has been inactive for over a year, so it is now yours. Feel free to go for it. :)

**Comment by neslihanturan** [comment]
@anadi198 , I saw you are also working on another issue. If you are not working for this issue, please let us know. So that someone else can work:)

**Comment by anadi198** [comment]
@neslihanturan I didn't realise I got a reply on this thread, feel free to assign it to someone else. I can take this up once I'm done with the current one if no one else does.

**Comment by misaochan** [comment]
@anadi198 I have just merged your other PR. Please feel free to work on this now if you'd like.

**Comment by anadi198** [comment]
Just making sure,

> A file with the file name %1$s exists. Are you sure you want to proceed? (`strings/upload_title_duplicate`)

needs to be changed to something like:

> A file with the file name %1$s exists. Are you sure you want to proceed?\n\nNote: A suitable suffix will be added to the file name automatically.

Also, should I save the "don't display again" boolean into saved preferences?

**Comment by misaochan** [comment]
Yes, that is correct. :)

> Also, should I save the "don't display again" boolean into saved preferences?
I don't see why not.

**Comment by anadi198** [comment]
@misaochan I'm not sure if just opening a PR notifies the necessary people or not so I'm just dropping this comment to update you.
