### ISSUE TITLE
Removing checkstyle from Travis

### ISSUE THREAD

**Issue by domdomegg** [commons-app/apps-android-commons#2823]
**Summary:** 

I'm planning on brushing up the travis config, and considering removing checkstyle from Travis.

The reasons for doing this are:
- Codacy already does this, and provides the output in a much better way
- Speed up Travis
- Remove about ~3000 lines of Travis' log output which are always ignored - making it easier to find important stuff when it does fail. It will also help avoid [log length issues](https://docs.travis-ci.com/user/common-build-problems/#log-length-exceeded) which I think remember being an issue before? (can't find ref though so maybe I'm just going insane)

I believe the current reason Travis is doing it is because it was added before we had Codacy, and then not touched since (#359). Also we are considering moving to another provider which gets us much better feedback (#2769) than the very generic checkstyle results anyways.

Before making this change want to get feedback on it @maskaravivek @misaochan @neslihanturan ?

**Comment by maskaravivek** [comment]
Yes, I am okay with it being removed. Personally, I haven't checked it even once. Codacy anyways shows this feedback in a much prettier way.

**Comment by domdomegg** [comment]
Just been testing a bit - incredibly it knocks off almost 6 minutes from the build! Probably going to add all that back on (and more) when we enable instrumented tests - though at least it shouldn't be as painful a wait, and the output will be much more useful.

**Comment by misaochan** [comment]
I agree, please remove it. No need for the redundancy since we already have Godacy, and it saves time and makes the Travis output a bit cleaner.

**Comment by neslihanturan** [comment]
I never use it either, and it increases complexity. Good idea to remove it @domdomegg

**Comment by maskaravivek** [comment]
@domdomegg Are you picking this up? :)
