### ISSUE TITLE
Update to Gradle 5

### ISSUE THREAD

**Issue by domdomegg** [commons-app/apps-android-commons#2824]
**Summary:** 

Updating Gradle from 4.10 to 5.3.1 should give us
- Faster builds
- Less noisy transform output (https://github.com/gradle/gradle/issues/6334)
- Potentially fix/help towards fixing #1941

I've marked this tentatively as beginner friendly - it's hard to judge things like this, but if it turns out to be difficult can always remove.

Useful links:

https://developer.android.com/studio/releases/gradle-plugin
https://docs.gradle.org/current/userguide/upgrading_version_4.html
https://docs.gradle.org/current/userguide/upgrading_version_5.html

**Comment by aadilahmed** [comment]
Hi, can I work on this?

**Comment by domdomegg** [comment]
@aadilahmed, please do, it's been assigned to you :)
