### ISSUE TITLE
Requesting reason twice on nomintion for deletion

### ISSUE THREAD

**Issue by neslihanturan** [commons-app/apps-android-commons#2827]
**Summary:** 

Ideally there the reason for nomination of deletion should be asked once, we should suggest some possible reasons and we should let user edit their own reason. Currently it is asked twice. It is intentional?

**Steps to reproduce:** 

Nominate an image for deletion

**Screen-shots:** 
![Screenshot from 2019-04-01 14-19-22](https://user-images.githubusercontent.com/3127881/55324129-d4dcbe80-5489-11e9-830e-16f7a3d0f66e.png)

![Screenshot from 2019-04-01 14-24-02](https://user-images.githubusercontent.com/3127881/55324130-d4dcbe80-5489-11e9-8c94-ca49ff37382d.png)

Additionally, an old file name is displayed on first screenshot. The file name was "Some test uploads"

**Comment by maskaravivek** [comment]
It might have got introduced after my recent refactoring of Async tasks. :(

**Comment by madhurgupta10** [comment]
@maskaravivek @neslihanturan I would like to take this up :)

**Comment by maskaravivek** [comment]
Assigned to @madhurgupta10

**Comment by madhurgupta10** [comment]
@neslihanturan Shall I remove the first popup?
> ![Screenshot from 2019-04-01 14-19-22](https://user-images.githubusercontent.com/3127881/55324129-d4dcbe80-5489-11e9-830e-16f7a3d0f66e.png)

**Comment by neslihanturan** [comment]
This issue needs some more discussion before implementation. Firstly I want to make sure does this second dialog is intentional or not?

**Comment by madhurgupta10** [comment]
@neslihanturan Okay I will wait before implementation 👍

**Comment by madhurgupta10** [comment]
@neslihanturan Any update on this?

**Comment by neslihanturan** [comment]
@madhurgupta10 sorry for the late response, my personal preference is removing the first dialog, and keeping the second one with build in options. What do you think?

**Comment by ashishkumar468** [comment]
@madhurgupta10 , Are you still working on it. Please let us know if you have any updates ?

**Comment by madhurgupta10** [comment]
@ashishkumar0207 Sorry for the late response, I was busy in a hackathon. I think that we can definitely remove the first dialog and just have the second one.
