### ISSUE TITLE
Notification does not disappear when upload fails

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#2836]
**Steps to reproduce:** 

1. Upload something
2. During the upload, remove the network connection or make the Internet super slow. It might need to be done at a very specific time, you will have to try.
3. The upload becomes marked as "Failed" in the Home activity.
4. Problem: The notification is still pretending to be progressing (in my case it says "Finishing uploading"). Expected: The notification either disappears or says that the upload failed.

**Device and Android version:** 
LineageOS 7.1.2
 
**Commons app version:** 
2.10.1.370~76e5a30

**Screen-shots:** 
![adb-screenshot](https://user-images.githubusercontent.com/99590/55388883-12ffde00-556f-11e9-8333-1cd2ed1608d7.png)

**Comment by omer-rotem1** [comment]
Hi, can I work on this please as a first issue?

Thanks

**Comment by nicolas-raoul** [comment]
@omer-rotem1 Yes, thanks!

**Comment by 318anushka** [comment]
This issue doesn't exist anymore. 
Could you please close it :-)

**Comment by nicolas-raoul** [comment]
@omer-rotem1 Are you still working on it? If not please let us know, thanks :-)

@318anushka I experienced this issue last week, do you think it has been fixed very recently? By the way, you might be interested in this issue meanwhile: #3582

**Comment by 318anushka** [comment]
Yeah i checked and it seems to work fine. As soon as i remove net connection, failed notification pops up

![Screenshot_20200325-142354](https://user-images.githubusercontent.com/45694892/77520172-cbbcdc80-6ea6-11ea-9404-ece24d8749e4.jpg)

**Comment by nicolas-raoul** [comment]
Ah, yes indeed this issue is about the "Finishing uploading" message, I see, thanks!

The remaining issue is that it seems impossible to swipe the failure notification away. The only solution to make it disappear seems to be to reboot the phone, which is quite inconvenient. Do you experience this problem? If yes, would you mind creating an issue about it? Thanks!

**Comment by 318anushka** [comment]
Yes, swiping away is a problem. But once the upload fails, just tap on notification it takes you to the Home Activity then the notification automatically disappears. you don't have to reboot the phone. 
Although it would be better if we could just swipe away the notification.

**Comment by nicolas-raoul** [comment]
wow I will try next time lol

**Comment by sivaraam** [comment]
>  Although it would be better if we could just swipe away the notification.

+1 for this. I don't see any reason why the failure notification should be sticky.

**Comment by 318anushka** [comment]
Should i create a new issue for this?

**Comment by nicolas-raoul** [comment]
@318anushka Yes good idea, thanks! :-)

**Comment by Rishavgupta12345** [comment]
@nicolas-raoul  notification works properly now so we can close this old issue
