### ISSUE TITLE
jpeg should get converted to jpg

### ISSUE THREAD

**Issue by whym** [commons-app/apps-android-commons#284]
Most do already, but a small number of files somehow remain unconverted. Examples:
- https://commons.wikimedia.org/wiki/File:Vazana_vez.jpeg
- https://commons.wikimedia.org/wiki/File:Giza.jpeg
- https://commons.wikimedia.org/wiki/File:Wikidata_at_wikicon_2016_on_saturday_morning.jpeg

With Utils.fixExtension() in place, how these have remained unconverted?

I'm not sure if it's linked but I see many (but not all) coincide with Issue #228 (Overwrite happens).

**Comment by nicolas-raoul** [comment]
Why is it important to rename these files?

**Comment by whym** [comment]
I think the reason is two-fold.

1. To reduce the possibility of creating nearly identical file names, which can be confusing to file users.
2. This is how MediaWiki normalizes file page names (among other conversions such as mpeg→mpg) and we would like to stick with it to not surprise editors: https://doc.wikimedia.org/mediawiki-core/master/js/source/mediawiki.Title.html#mw-Title-method-normalizeExtension

**Comment by nicolas-raoul** [comment]
That convinced me! :-)

**Comment by misaochan** [comment]
Interesting. My guess is that the try-catch block in UploadService.java that was supposed to call Utils.fixExtension() failed due to IOException, which would result in fixExtension() not being called. But in that case I don't know why the image upload would still proceed.

**Comment by albendz** [comment]
Is this still relevant? If so, I can refactor the upload method and add unit testing to ensure no file gets uploaded with the wrong extension. Let me know.

**Comment by neslihanturan** [comment]
It should be solved @albendz , tahnks!
