### ISSUE TITLE
Notification badge on home page remains highlighted always

### ISSUE THREAD

**Issue by KaveriKR** [commons-app/apps-android-commons#2840]
**Summary:** 

The notification badge on the home page remains highlighted even after reading the notification, according to general understanding it should only be highlighted when we have any new unread notifications.  

**Device and Android version:** 

Teted on Moto G6 - version Android P. API -28
 

**Screen-shots:** 

![Screenshot_20190403-120645](https://user-images.githubusercontent.com/30476249/55459066-3af14f00-560c-11e9-97c6-b5ebe2c48f02.png)

**Would you like to work on the issue?**

Yes

**Comment by neslihanturan** [comment]
I got a similar feedback to this issue.

**Comment by neslihanturan** [comment]
And what I experienced on API 19 is device is pink check mark displayed for a second, then the notification came back to its own space.

**Comment by PanagiotisBatsikouras** [comment]
Since this is an unassigned issue, may I take up this one?

**Comment by nicolas-raoul** [comment]
@PanagiotisBatsikouras Sure, looking forward to your pull request, please let us know about your progress :-)

**Comment by neslihanturan** [comment]
Hi @PanagiotisBatsikouras thanks for volunteering for this task:) You may need some discussion for implementing this task. Ie. for some questions like when we will define a notification as read?

My personal opinion is each time notifications activity is visited, all notifications before visit date should be considered as read. No matter if user clicked to them or not. So after each visit, red notification number should disappear. 

A possible implementation storing latest notification date and visit date, then compare.

**Comment by PanagiotisBatsikouras** [comment]
Perfect, I will inform you about the progress in a couple of days or so.

**Comment by PanagiotisBatsikouras** [comment]
Hi @neslihanturan, can you please tell me how to generate notification ? I have generated the notification after the first post and after that i don't know when notification gets generated.

**Comment by neslihanturan** [comment]
It is not something we can generate, but I can help you by thanking your uploads if you share your beta user page with me? You should continue development end testing no beta, but notifications works same on beta and prod so it should be fine.

**Comment by PanagiotisBatsikouras** [comment]
Thanks for the response. I will create a second user then in order to thanking my other user's uploads so that I will generate notifications on my own for testing purposes.

**Comment by neslihanturan** [comment]
Even better:) Just make sure you are on beta, to not violate real commons. https://commons.wikimedia.beta.wmflabs.org/wiki/Main_Page

**Comment by PanagiotisBatsikouras** [comment]
I believe it's almost done. Just doing some final tests and I will create the pull request until tomorrow.

**Comment by nicolas-raoul** [comment]
I believe this is fixed. :-)
If you observe this issue again with recent versions, please do not hesitate to let us know!
