### ISSUE TITLE
Hosting app on Appetize

### ISSUE THREAD

**Issue by madhurgupta10** [commons-app/apps-android-commons#2842]
**Summary:** 
Appetize provides a free evaluation of the app, new contributors do not need to install/build the app to check it.

https://appetize.io/

Check out this [susi ](https://appetize.io/app/mbpprq4xj92c119j7nxdhttjm0?device=nexus5&scale=75&orientation=portrait&osVersion=8.1)hosted app from fossasia

**Would you like to work on the issue?**
Yes

**Comment by misaochan** [comment]
Looks good to me, as long as it doesn't break any policy? @nicolas-raoul

**Comment by nicolas-raoul** [comment]
Can accounts be transfered? Can several people manage a single app?

**Comment by madhurgupta10** [comment]
https://blog.fossasia.org/tag/appetize-io/
I found this nice blog

**Comment by madhurgupta10** [comment]
> Can accounts be transfered? Can several people manage a single app?

People can manage a single app using the token and the key

**Comment by nicolas-raoul** [comment]
I just looked at the pricing:
![Screenshot from 2019-04-04 17-55-03](https://user-images.githubusercontent.com/99590/55542866-e8468e80-5702-11e9-9347-979c11abd8f5.png)
From that, I guess that we will not advertise appetize.io as a mainstream way to try the app, as we would quickly overflow the free tier. So setting up scripts to automatically push APKs is probably not worth the trouble.
That being said, pushing an APK is perfectly fine, the app is open source after all :-)

**Comment by madhurgupta10** [comment]
@nicolas-raoul @misaochan I generated a singed apk for v2.10.2 prodRelease and uploaded it to appetize, check out https://appetize.io/app/8ywtpe9f8tb8h6bey11c92vkcw

**Comment by nicolas-raoul** [comment]
@neslihanturan Having the app on appetize is great. Having a badge is totally optional, but I would say why not, we can always remove it when appetize stops working or if nobody is motivated to update it at least once a year.
