### ISSUE TITLE
Moving hardcoded URLs from About Activity to a constant file

### ISSUE THREAD

**Issue by madhurgupta10** [commons-app/apps-android-commons#2850]
**Summary:** 
There are many hardcoded strings which makes them difficult to locate and change the URL in case needed, so I think we should move them build.gradle file.

like
```
@OnClick(R.id.about_credits)
    public void launchCredits(View view) {
        Utils.handleWebUrl(this,Uri.parse("https://github.com/commons-app/apps-android-commons/blob/master/CREDITS/\\"));
    }

    @OnClick(R.id.about_privacy_policy)
    public void launchPrivacyPolicy(View view) {
        Utils.handleWebUrl(this,Uri.parse("https://github.com/commons-app/apps-android-commons/wiki/Privacy-policy\\"));
    }


    @OnClick(R.id.about_faq)
    public void launchFrequentlyAskedQuesions(View view) {
        Utils.handleWebUrl(this,Uri.parse("https://github.com/commons-app/apps-android-commons/wiki/Frequently-Asked-Questions\\"));
    }
```

**Would you like to work on the issue?**
Yes

**Comment by maskaravivek** [comment]
These URLs would be the same for all build flavors. To tidy it up you may move it to a constants file.

**Comment by madhurgupta10** [comment]
@maskaravivek I reason I wanted to move them to build.Config because of the Unit Test, I want to write the Unit test for About Activity, so it will be easy to check on click if the correct URL intent is fired or not.

**Comment by madhurgupta10** [comment]
@maskaravivek Should I create a class and add all the URLs to it?

**Comment by maskaravivek** [comment]
Will it be difficult to write a unit test if the urls are in a constants file?

**Comment by madhurgupta10** [comment]
@maskaravivek I think, test can be written easily by using **IntentMatchers.hasData()** and passing the URL string from the constant file :)
