### ISSUE TITLE
Show settings even when not logged in

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#2853]
**Steps to reproduce:** 

1. Log out
2. Open navigation drawer

Expected: Settings item exists.
Actually: No Settings item

It prevents users from setting up night mode, sending logs, and other things that do not rely on login.

Some settings might need to be hidden though? The only one I can think of are:
- "Recent upload limit"
- "Use custom author name"

Not hiding them would not be the end of the world, though.

**Comment by silkypriya** [comment]
Hello @nicolas-raoul, can I work on this issue?

**Comment by nicolas-raoul** [comment]
@silkypriya Yes it is yours :-)

**Comment by silkypriya** [comment]
Hello @nicolas-raoul,
PR #2867 fixes this. Kindly review.
Thank you!

**Comment by madhurgupta10** [comment]
@nicolas-raoul I think this issue is solved, we can close it.
