### ISSUE TITLE
Navigation Drawer is huge in Tablets

### ISSUE THREAD

**Issue by madhurgupta10** [commons-app/apps-android-commons#2854]
**Summary:** 
The navigation drawer seems to occupy extra space in tablets.

**Device and Android version:** 
Custom Tablet 9 inch API 28 stock android.
 
**Commons app version:** 
latest betaDebug

**Screen-shots:** 
![screenshot-2019-04-04_14 35 10 181](https://user-images.githubusercontent.com/30932899/55543795-65fca100-56e7-11e9-8129-442c22c7ca11.png)
![screenshot-2019-04-04_14 35 40 499](https://user-images.githubusercontent.com/30932899/55543796-65fca100-56e7-11e9-9a05-4cd7efea1909.png)

**Would you like to work on the issue?**
Yes

**Comment by nicolas-raoul** [comment]
How does it look in other apps such as Gmail?

**Comment by madhurgupta10** [comment]
@nicolas-raoul On other stock android apps such as Contacts, it is like this
![screenshot-2019-04-04_14 42 42 843](https://user-images.githubusercontent.com/30932899/55544144-179bd200-56e8-11e9-8964-5951c932d16c.png)
![screenshot-2019-04-04_14 42 53 771](https://user-images.githubusercontent.com/30932899/55544145-179bd200-56e8-11e9-91a6-6c8d43400ae4.png)
