### ISSUE TITLE
0 contributions shown on MainActivity

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#2879]
**Summary:** 

I'm getting 0 shown on my contributions tab, even though it actually displays my contributions correctly.

**Steps to reproduce:** 

I logged in and looked at the contributions tab

**System logs:**

Difficult to obtain directly with #2878 unsolved. I sent log files to the forum.

**Device and Android version:** 

Samsung Galaxy s9 Android 8.0

**Commons app version:** 

Latest master (2.10.2.385~4f76f1b) via Play Store alpha testing

**Screen-shots:** 

![Screenshot_20190415-204216_Commons](https://user-images.githubusercontent.com/3611199/56129894-c97bae00-5fc6-11e9-9a37-62055faca45b.jpg)

**Would you like to work on the issue?**

Pref not

**Comment by madhurgupta10** [comment]
@misaochan This issue might be similar to #2377

**Comment by misaochan** [comment]
Ah, I didn't notice, thanks for pointing that issue out @madhurgupta10 .
