### ISSUE TITLE
New Media Details UI

### ISSUE THREAD

**Issue by neslihanturan** [commons-app/apps-android-commons#2881]
**Summary:** 

Hi, here is a UI suggestion, which fits wit our new upload UI, for our Media Details interface.
Option 1:
![mediaDetailsUI](https://user-images.githubusercontent.com/3127881/56140003-ac34e880-5fa2-11e9-9624-894bf7d429cf.png)

Option 2:
![mediaDetailsUI2](https://user-images.githubusercontent.com/3127881/56140016-b1923300-5fa2-11e9-8833-d970a8427df0.png)

After nomination for deletion, for both options:
![mediaDetailsUINominated](https://user-images.githubusercontent.com/3127881/56140035-bd7df500-5fa2-11e9-9a9e-1ba9220d7eb2.png)

Feedback is appreciated.

**Comment by nicolas-raoul** [comment]
Personally I prefer option 2, because nominating for deletion is a grave thing to do. Showing delete as a prominent icon would make it appear as a day-to-day operation, and may encourage people to upload anything, thinking they can easily delete it later.

**Comment by neslihanturan** [comment]
You explanation was my motivation for designing second one @nicolas-raoul , I agree the second is better.

**Comment by ashishkumar468** [comment]
Looks really good @neslihanturan, but instead of expand/collapse by clicking (if I am inferring that correctly), do you think we should go ahead with a collapsing toolbar, the image being the collapsible component?

**Comment by ashishkumar468** [comment]
Correction : Re-read material.io and found these, 
Expanding bottom sheets provide a small, collapsed surface that can be expanded by the user to access a key feature or task. They offer the persistent access of a standard sheet with the space and focus of a modal sheet.
Bottom sheets can display a wide variety of content and layouts, ranging from menu items (in list and grid layouts), to supplemental content laid out according to the layout grid.
Considering the above points, the current designs would be just perfect, here is an image reference. https://storage.googleapis.com/spec-host-backup/mio-design%2Fassets%2F12fiIOKSBCqjFRePXnWZnQ88oGFWhfBXv%2Fstandard-placement-mobile.png

Thanks for adding them @neslihanturan

**Comment by maskaravivek** [comment]
I personally love option 2 suggested by Neslihan.

**Comment by misaochan** [comment]
Great job @neslihanturan ! I agree with Option 2, nominate for deletion should come with a warning sign, it should not be with the other options.

**Comment by neslihanturan** [comment]
@ujjwalagrawal17 while implementing this feature, please consider adding an edit icon next to categories too, as in descriptions. I forgot to add on design.

**Comment by ujjwalagrawal17** [comment]
Sure @neslihanturan, I will add it.
