### ISSUE TITLE
Image sometimes not shown in upload description activity

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#2883]
2.10.2.388~84637c5
![Screenshot_20190416-210519](https://user-images.githubusercontent.com/99590/56208241-a23ae480-608b-11e9-8dbf-cd8f9c8c0a11.png)

**Comment by OlgaMorales** [comment]
i'd like to work on the issue. :) it could be my first contribution.

**Comment by OlgaMorales** [comment]
@nicolas-raoul how can i start working on this issue?

**Comment by nicolas-raoul** [comment]
@OlgaMorales Thanks for working on this! :-)

The first steps:
1. Run the app from Android Studio, as https://github.com/commons-app/apps-android-commons/wiki/Quick-start-guide-for-Developers
2. Reproduce the problem
3. Insert breakpoints at source code lines where you think the image might be loaded.

**Comment by OlgaMorales** [comment]
just a question , why when I run the project app on my mobile I see beta version, how can i see the same which is in the play store version

**Comment by OlgaMorales** [comment]
hi @nicolas-raoul I've reproduced the problem many times but neither of them has failed.

**Comment by nicolas-raoul** [comment]
@OlgaMorales Do you mean the image correctly appears every time?
Strange, for me it fails to display almost every time.
Could you please download some pictures from https://drive.google.com/open?id=1YeYGelmhKbpO_OPAKLT-S4Cw-rsbCG6V and try to upload them?

**Comment by nicolas-raoul** [comment]
Also, it might be because of low memory. I am using a Nexus 5, please try to use a similar device or the emulator with only 2GB of RAM.
Thanks!

**Comment by OlgaMorales** [comment]
I'll try with the device you said , as I tried with the pictures you indicated and my phone uploaded those very well,

**Comment by ashishkumar468** [comment]
Can't reproduce on master, We've had major revamps and since this issue is old, I am safely assuming its fixed. Feel free to re-open if reproduced
