### ISSUE TITLE
First time ever tapping "Nearby": Tab does not show

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#2888]
**Steps to reproduce:** 

1. Install app on new phone
2. Log in
3. Tap "nearby"
4. Location permission popup appear, accept
5. Nearby tab is not opened (nearest location bar is shown, though)

Workaround: Tap on "Nearby" again.

**Commons app version:** 
2.10.2-debug-master~84637c5fe

**Screen-shots:** 
![Screenshot from 2019-04-17 17-38-54](https://user-images.githubusercontent.com/99590/56273452-b5a38980-6137-11e9-9375-bbdd7d9a5a82.png)

**Comment by ahmedmamdouh13** [comment]
requesting location permission off the main thread seems to solve the problem , but still loading forever after permission being granted , i'm on it.

**Comment by nicolas-raoul** [comment]
@ahmedmamdouh13 Assigned to you, thanks! :-)

**Comment by ahmedmamdouh13** [comment]
in what format should i upload videos , i couldn't upload but gif 

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/31363038/56419629-329b4400-629b-11e9-9eaf-e3a9d4805b41.gif)

**Comment by nicolas-raoul** [comment]
I don't think GitHub accepts videos formats, except GIF

**Comment by ahmedmamdouh13** [comment]
![untitled](https://user-images.githubusercontent.com/31363038/56425331-1061f000-62b4-11e9-81ab-ef09b76fa00a.gif)
