### ISSUE TITLE
Write Instrumentation Tests for AboutActivity

### ISSUE THREAD

**Issue by madhurgupta10** [commons-app/apps-android-commons#2889]
**Summary:** 
Write Instrumentation Tests for AboutActivity in Kotlin

**Would you like to work on the issue?**
Yes

**Comment by maskaravivek** [comment]
@madhurgupta10 Can you list down the test cases that you plan to write?

**Comment by domdomegg** [comment]
We need #2868 to be fixed first.

**Comment by vanshikaarora** [comment]
This issue seems to be inactive since long. I would like to work on writing Unit tests. @maskaravivek @nicolas-raoul @domdomegg. Can you please list down some Unit tests for About Activity

**Comment by nicolas-raoul** [comment]
- Open About. Make sure the version shown is the real version of the APK. Make sure that the commit number is the real commit number (might be difficult to make that a unit test though)
- Click on each link, make sure a browser opens to the right page (also difficult to make as a unit test I guess)

**Comment by maskaravivek** [comment]
It would be great if you could first focus on finishing unit tests for the tasks that you are working on. Those things are part of the critical flows. :)

**Comment by maskaravivek** [comment]
> * Open About. Make sure the version shown is the real version of the APK. Make sure that the commit number is the real commit number (might be difficult to make that a unit test though)
> * Click on each link, make sure a browser opens to the right page (also difficult to make as a unit test I guess)

These would be [instrumentation tests](https://developer.android.com/training/testing/unit-testing/instrumented-unit-tests). :)
