### ISSUE TITLE
Revamp the About Activity

### ISSUE THREAD

**Issue by madhurgupta10** [commons-app/apps-android-commons#2891]
**Summary:** 
About Activity UI does not seems to be updated for a long time. The Activity does not look very good on large screen devices. I think we should update the UI.

We can refer to the Wikipedia App About Activity for UI.

**Screen-shots:** 
<img src="https://user-images.githubusercontent.com/30932899/56335707-2770e700-61bb-11e9-88ae-4ab873458bde.png" width="90%"> 
<img src="https://user-images.githubusercontent.com/30932899/56335655-06a89180-61bb-11e9-9675-3f5f306ecdff.png" width="45%"> <img src="https://user-images.githubusercontent.com/30932899/56335656-06a89180-61bb-11e9-9eb5-28520a257afa.png" width="45%">
**Would you like to work on the issue?**
No

**Comment by nicolas-raoul** [comment]
I don't think it is bad right now :-)
Before starting coding please post a mockup showing what you think would be ideal, thanks!

**Comment by Rishavgupta12345** [comment]
@nicolas-raoul is this issue still relevant to work on? because we are still using the old version and it is working pretty well since then

**Comment by nicolas-raoul** [comment]
Closing for now, but if anyone has a mockup please do not hesitate to post a comment :-)
