### ISSUE TITLE
Contributions: Same 3 images repeat forever

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#2892]
2.10.2.388 (latest master as of now)
Scrolling down shows 5 images, then the last 3 are repeated forever:
https://i.imgur.com/AEFqTlY.mp4

**Comment by neslihanturan** [comment]
I experience d the same issue today. Does anyone remember any PR that effects contributions list recently?

**Comment by domdomegg** [comment]
Potentially related? #2182
