### ISSUE TITLE
"Get it on F-Droid" badge broken?

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#2895]
The image for "Get it on F-Droid" on https://github.com/commons-app/apps-android-commons/blob/master/README.md appears to be broken for me. Just checking if this is the case for anyone else or if it's just my connection?

**Comment by nicolas-raoul** [comment]
https://f-droid.org/badge/get-it-on.png has become extra-slow.
I reported the problem internally.

**Comment by nicolas-raoul** [comment]
Reply:

> For quite a while, the entire site is slow. So many users, quite a load! Why not copy the badge to where you want to show it?

So we should use this one instead: https://commons.wikimedia.org/wiki/File:%22Get_it_on_F-droid%22_Badge.png

**Comment by sivaraam** [comment]
I've just created #2896 to fix this. Hope this helps.
