### ISSUE TITLE
Urgent: 0 uploads shown on fresh install

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#290]
Is anyone else getting 0 uploads shown if they uninstall the app and install a fresh copy of it (v1.33)? Would appreciate if anyone would help test. If it isn't just my phone that is causing problems, I might need to revert #285 and see if it fixes the issue (since AFAIK no other change in this version affects ContributionsListFragment.java, which displays the list).

**Comment by nicolas-raoul** [comment]
I just tried uninstalling and reinstalling again (1.33 from Google Play), and my uploads are shown normally.
You had network enabled?

**Comment by misaochan** [comment]
Thanks! I just tried again and it works for me now. Pretty sure I had network or at least wi-fi enabled since my fresh install was from Google Play and not from my computer - there is no way we can install from Google Play without network/wi-fi, right?

If it was just a momentary error on my phone, that's all good. :)

**Comment by nicolas-raoul** [comment]
You can close and reopen if you ever experience this again :-)

**Comment by misaochan** [comment]
Yeah, good idea!
