### ISSUE TITLE
Use image info instead of event logs for getting user uploads

### ISSUE THREAD

**Issue by maskaravivek** [commons-app/apps-android-commons#2904]
**Summary:** 

Currently, the app fetches the user's contributions by: 

- Step 1: querying `logevents` API (`ApacheHttpClientMediaWikiApi:logEvents`). This gives the `pageid`, `filename` and `dateUpdated` for user's uploads

- Step 2: Deleted files(the ones with `pageid` 0) are skipped and the rest is inserted int the `contributions` db. 

- Step 3: To show the list of contributions, `findThumbnailByFilename` is called for each file and the image along with filename is shown. 

I propose that we move away from this approach and start consuming `imageinfo` API for displaying user's contributions. 

Eg: 

https://commons.wikimedia.org/w/api.php?action=query&format=json&formatversion=2&generator=allimages&gaisort=timestamp&prop=imageinfo&iiprop=url%7Cextmetadata&iiurlwidth=640&iiextmetadatafilter=DateTime%7CCategories%7CGPSLatitude%7CGPSLongitude%7CImageDescription%7CDateTimeOriginal%7CArtist%7CLicenseShortName%7CLicenseUrl&gaiuser=Maskaravivek&gailimit=10

Pros: 
- all meta info(categories, url, thumbnail, author etc) related to the image can be retrieved in  a single call. 
- paginated response(similar to the log events API)
- Step 2, Step 3 won't be required
- In all probability, we can remove the limitation of showing just 500 images in the app. (#1993)
- The behavior will become similar to the category list and search list
- Will make #2525 pretty straightforward to implement
- Will fix #2892 (Note: There are other ways to fix this. The fix is not entirely dependent)
- Will pave way for #2739, as the same fragment can be reused just by replacing the user's name. 
- Move closer to #1566. 

Cons: 
- If we want to show deleted images then we will need a way to fetch them. Discussion #118. 
- Still won't address #2496. We can think of a common caching strategy for images displayed in explore, search and contributions. Obviously, we would be more aggressive in caching contributions.

**Comment by maskaravivek** [comment]
Most of the code in `ContributionsSyncAdapter` is from 2013. Fixing the above would help us with #1092 

@misaochan @nicolas-raoul it would be great if you could give your opinions on this issue.

**Comment by misaochan** [comment]
@maskaravivek This sounds good to me. The old method is a relic from the legacy app that was implemented before category suggestions etc. I really like the idea of switching to using the same API as that used to generate category suggestions and search - maybe we could even reuse some of the common code if feasible?

Not being able to retrieve deleted images may indeed be a disadvantage, but I don't think we ever reached a consensus on whether we even want that, to begin with.

**Comment by maskaravivek** [comment]
@ashishkumar468 After our latest refactoring are we still using `logEvents` to fetch the contributions or has it changed?

**Comment by ashishkumar468** [comment]
@maskaravivek We are still using logEvents.
