### ISSUE TITLE
Yes/no buttons not reachable when many categories

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#2908]
Here I scrolled to the bottom:
![Screenshot_20190422-132214](https://user-images.githubusercontent.com/99590/56482983-fddcf600-6501-11e9-8f42-bf8cce979fc1.png)

**Comment by Szymon20000** [comment]
I've made a pull-request

**Comment by nicolas-raoul** [comment]
Is this fixed?

**Comment by thetimeheist76** [comment]
![2908](https://user-images.githubusercontent.com/53221361/61819061-e2bab300-ae6f-11e9-92df-e36e38c5b4d3.png)
I tried reproducing the issue on Xiami Redmi Note 4 Android 7 but the issue doesn't show up.

**Comment by nicolas-raoul** [comment]
I guess this is fixed the, thanks :-)
