### ISSUE TITLE
"Requesting category check" notification even though I did not mark as such

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#2909]
Categorization of the picture was correct, so I pushed the button accordingly, but despite that a "Requesting category check" notification is shown. I have not checked whether the request is actually uploaded or not.
![Screenshot_20190422-125319](https://user-images.githubusercontent.com/99590/56483201-52cd3c00-6503-11e9-8c13-8c6c6c3b67bf.png)

**Comment by thetimeheist76** [comment]
![2909](https://user-images.githubusercontent.com/53221361/61820169-244c5d80-ae72-11e9-8118-a50ccf2f7f5d.png)
Was able to reproduce the same issue. 
Device: Xiaomi Redmi Note 4
Android Version: 7.0
Commons app version: 2.10.2-debug master~0574b753b

**Comment by neslihanturan** [comment]
@thetimeheist76 thanks for wanting to work on this issue:) It can be better to note you claimed the issue under issue page instead of the mail list, so that anyone who sees this issue can know that you are working on it.

**Comment by thetimeheist76** [comment]
Ok. I am on it.

**Comment by nicolas-raoul** [comment]
Bug still present in latest master.

**Comment by kbhardwaj123** [comment]
@nicolas-raoul sir can i proceed working on this issue ?

**Comment by mds08011** [comment]
This bug is still present in version 2.12.3.569~b13d888.

Also, my "Requesting category check" notification never finished, was not able to be cleared, and persisted even after quitting the app.

<img src="https://user-images.githubusercontent.com/8010709/74051525-f8677400-498c-11ea-8836-4dbf29a06ba8.png" width="50%">

**Comment by nicolas-raoul** [comment]
@kbhardwaj123 Sorry for the late reply! Are you still interested in working on this?

**Comment by kbhardwaj123** [comment]
@nicolas-raoul yeah sure I'll take this up :)
