### ISSUE TITLE
No OpenStreetMap attribution

### ISSUE THREAD

**Issue by picsi** [commons-app/apps-android-commons#2911]
The map in the Nearby tab has no OSM attribution. OSM requires attribution in a very specific way: in the map frame, as "© OpenStreetMap Contributors".

See https://www.openstreetmap.org/copyright

**Comment by nicolas-raoul** [comment]
Thanks for letting us know!
Note: Apparently it is actually `© OpenStreetMap contributors` with a lowercase `c`.

**Comment by domdomegg** [comment]
> Thanks for letting us know!
> Note: Apparently it is actually `© OpenStreetMap contributors` with a lowercase `c`.

You've used the uppercase in your comment, and OSM use the uppercase in [their guidance](https://www.openstreetmap.org/copyright).

**Comment by nicolas-raoul** [comment]
Somehow the attribution has disappeared.
Anyone please fix this, you can probably look at Neslihan's code above for inspiration. Thanks! :-)

**Comment by aakankshaa23** [comment]
I would like to fix this issue.

**Comment by ashishkumar468** [comment]
@aakankshaa23  It is yours :)

**Comment by aakankshaa23** [comment]
Hello sir,
 I just did the attribution part. Could you please tell if I can send the
pull request.
The screenshot is attached below along with how it looked previously.

Thanks
