### ISSUE TITLE
Clicking on a category crashes the app

### ISSUE THREAD

**Issue by picsi** [commons-app/apps-android-commons#2912]
When looking at an image file and clicking on one of its categories, the app crashes and shuts down.

**Comment by maskaravivek** [comment]
@picsi Does this happen on latest master or on one of the market builds?

**Comment by picsi** [comment]
I'm using the latest from F-Droid.

**Comment by maskaravivek** [comment]
Can you share logs from your device?

**Comment by picsi** [comment]
Not entirely sure how to do that. I'm on Lineage 15.1 on mido, if that helps.

**Comment by maskaravivek** [comment]
Just click on Settings > Send logs from within the app. It will open an email client and with the log files attached.

**Comment by maskaravivek** [comment]
Am closing this issue as its not reproducible. Feel free to reopen it if the issue persists. :)
