### ISSUE TITLE
App adds space at end of filename sometimes

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#2917]
From a user on our FB page:

> 2. very often the app will add a space at the end of the filename. since i'm a commons admin i'm able to quickly move and replace. but the app should probably make the check and remove any spaces appearing right before the extension "abc_.jpg" > "abc.jpg"

This is probably v2.10.2 since both beta and prod Play Store versions are on it, and she mentioned she recently reinstalled the app. Hopefully she'll submit a crash report for a crash that she mentioned, then we can get her Android version etc without having to ask her to find and repeat everything.

**Comment by misaochan** [comment]
More information:

>  I use Sony Experia. I start from the "Camera". Select  the "Share" option
> 
> and when I upload numer of photos in a row, the symbol of the Wikimedia Commons app appears automatically as an option next to the "Share"
> and then it's the same I guess - filename, choosing [bg] from the language menu, file description, etc. etc.
> maybe for some words my phone's autocorrect has remembered to place explicit spaces after the words, and this is not easily seen when this is the end of the filename
> hence the spaces before the ".jpg"

**Comment by VitalyVPinchuk** [comment]
Hi.
Could it be due to the following line of code?
`                String canonicalFilename = "File:" + result.getString("/api/upload/@filename").replace("_", " "); // Title vs Filename
`
Is there a need to replace underscore back with space?

**Comment by VojtechDostal** [comment]
This happens on my phone because a space is automatically inserted just after a word which was selected from auto-suggest. Would be cool to have the space removed automatically, as long as it does not interfere with the ability of the app to warn me about Commons images with the same file name,

**Comment by VitalyVPinchuk** [comment]
Hi.
Do I open PR for this minor fix?

**Comment by nicolas-raoul** [comment]
Yes, a PR is needed for any code change.
Thanks :-)
