### ISSUE TITLE
Add option for default language for file descriptions

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#2918]
From a user on FB group:

> I have one more idea for improvement: in the app settings, please add the option default language for the file descriptions
> maybe even number of 1-2 default languages
> for me that would be "bg" (if only one) and "bg" + "en" (if 2 are allowed)
> this will save some time for scrolling up and down the menu, and will - i guess - reduce the number of mistaken languages
> some people will probably not care enough to scroll down this menu everytime and will use the default "en" for whichever language they use
> is this doable?

**Comment by fredrikjonasson** [comment]
I would like to start working on this issue.  

Regards,

Fredrik

**Comment by neslihanturan** [comment]
Great idea @misaochan ! Thanks for your interest @fredrikjonasson , can you explain the implementation in your mind?

**Comment by fredrikjonasson** [comment]
@misaochan, due to some unforeseen happenings i havent been able to investigate this closer. If anyone else have an implementation in mind and an interest of working on this one; feel free!

**Comment by OlgaMorales** [comment]
hi @neslihanturan I'd like to wok on this issue.

**Comment by OlgaMorales** [comment]
hey there , @neslihanturan could you tell me where do you get the list of the languages please? I haven't found where ...

**Comment by neslihanturan** [comment]
Hi @OlgaMorales investigating current adding description process for upload can help you. We are displaying the list of language there.

**Comment by OlgaMorales** [comment]
Here's my PR @neslihanturan !
I hope to receive your feedback!
Regards.

**Comment by neslihanturan** [comment]
Hi @OlgaMorales I can't see you PR, but I saw you pinged me. Additionally your account seems like disabled.

**Comment by olgalesan** [comment]
@neslihanturan here's my PR
Regards.
