### ISSUE TITLE
Photos are displayed as rotated on upload screen

### ISSUE THREAD

**Issue by neslihanturan** [commons-app/apps-android-commons#2919]
**Summary:** 
A report from our user says photos on upload screen displayed 90 degree rotated. On the other hand, she sees the images properly on her gallery.

![Screenshot_20190424-121417_Commons](https://user-images.githubusercontent.com/3127881/56648133-6acfc780-668b-11e9-8f53-a516334d2d1e.jpg)

She just installed the app, so version should be latest production 2.10.2

Edit: 
![Screenshot_20190424-125808_Commons](https://user-images.githubusercontent.com/3127881/56652093-2a744780-6693-11e9-9607-f5b61406fc4d.jpg)

**Comment by neslihanturan** [comment]
Reported device was a Samsung 5A device, and apparently there is some issues with rotation and Samsung devices, see: https://stackoverflow.com/questions/11023696/setrotation90-to-take-picture-in-portrait-mode-does-not-work-on-samsung-device#comment14414266_11024837

It would be great if someone with Samsung device help me to reproduce this issue.

**Comment by nicolas-raoul** [comment]
I remember seeing this quite often on a Samsung S10.

**Comment by thetimeheist76** [comment]
![2919](https://user-images.githubusercontent.com/53221361/61818484-8dca6d00-ae6e-11e9-9ebc-9090c357413b.png)
I tried reproducing it on Xiaomi Redmi Note 4 device but the mentioned issue cannot be found. FYI I had clicked the image in a landscape mode.

**Comment by Rishavgupta12345** [comment]
@nicolas-raoul  this issue is pretty old and no more reproducible so we can safely close this issue

**Comment by nicolas-raoul** [comment]
I haven't seen this in a while indeed. If anyone can reproduce, please comment, thanks!
