### ISSUE TITLE
Images are streched on display 

### ISSUE THREAD

**Issue by neslihanturan** [commons-app/apps-android-commons#2923]
**Summary:** 
Images doesnt seems properly on MediaDetailsActivity and contributions list.

**Screen-shots:** 
See vertically, 
![Screenshot from 2019-04-24 15-43-55](https://user-images.githubusercontent.com/3127881/56669840-74bcef00-66ba-11e9-90dc-537bc10bf63b.png)

and horizontally,
![image](https://user-images.githubusercontent.com/3127881/56670200-180e0400-66bb-11e9-9a06-b3bc90228fc3.png)

**Comment by maskaravivek** [comment]
@neslihanturan This would have got introduced after my recent changes in #2906. I am currently using `fitXY` stretch mode for images ie. 

```
android:scaleType="fitXY"
```

Should we use some other scale type? 

https://developer.android.com/reference/android/widget/ImageView.ScaleType

**Comment by neslihanturan** [comment]
I think previous version was much better. It wasn't transform the image, it was just showing what fits into screen.

**Comment by maskaravivek** [comment]
Does this look good? 

https://user-images.githubusercontent.com/3069373/56682478-3a1e7b00-66e9-11e9-8fcd-8ed1af41f631.png

**Comment by neslihanturan** [comment]
Exactly this @maskaravivek

**Comment by maskaravivek** [comment]
Then merging #2924 should fix the issue. :)
