### ISSUE TITLE
Vienna Hackathon

### ISSUE THREAD

**Issue by tobias47n9e** [commons-app/apps-android-commons#293]
We should coordinate if some of us can participate in the Vienna hackathon (19 – 21 May 2017) and what specific goals we would like to accomplish during the event.

It is still very early but the main information channels are:
- https://phabricator.wikimedia.org/project/view/1919/
- https://www.mediawiki.org/wiki/Wikimedia_Hackathon_2017

**Comment by misaochan** [comment]
I would love to attend, but that will probably be dependent on some factors (including funding), as I live in NZ, which is on the other side of the globe. :)

Regardless of whether or not I am able to attend, I'd be more than happy to provide support. I should probably mention that I am planning to apply for an IEG renewal (see [here](https://meta.wikimedia.org/wiki/Grants:IEG/Improve_%27Upload_to_Commons%27_Android_App/Midpoint#IEG_renewal)). If it is approved, I would be halfway through the proposed tasks by the time the hackathon comes, so it might be better to pick a different goal/focus for the two?

There are plenty of improvements that need to be made though, so plenty of wiggle room there. :) Depending on what you guys would like to work on for the hackathon, I can rearrange my IEG proposal goals around that as well.

**Comment by whym** [comment]
> How much time does a team have to work on tasks during the hackathon? Can the team spend the entire 3 days on it, or does the time have to be split between projects?

I think there will always be a free space to hack in if you are not interested in the ongoging sessions elsewhere. (At least that was the case in 2014.)

Volunteers tend to have interest in two or more projects (for me, Commons app and Pywikibot, etc) and they might want to split their time. But if you want to focus on one, I think there is nothing stops you from that.

**Comment by whym** [comment]
Some random ideas for possible topics to work on using the occasion:

* Stalled issues and meta issues, especially ones that involve other infrastructures and tools (e.g. Refactor and share components with the Wikipedia app / other Java-based upload tools? Move from GitHub to Wikimedia Phabricator/Gerrit? Restore and enhance EventLogging features?)
* Sharing knowledge between contributors; recruiting and onboarding new contributors to the Commons app, maybe by hosting a hands-on session
* Reducing technical debts (e.g. What to do with the obsolete MWApi library?)

What do you think?

**Comment by misaochan** [comment]
@whym I love suggestion 2, that would really take advantage of the in-person nature of a hackathon. I think getting set up and getting a rough understanding of the codebase is probably the most difficult part of new contributors getting started (though it is easier than before now that we have migrated to Gradle). A hands-on session would be great.

I'm not sure about suggestion 1 - do we want to migrate to Phabricator/Gerrit? AFAIK the official Wikipedia app is on GitHub as well, although I don't know if they have a Gerrit mirror.

**Comment by whym** [comment]
I didn't really mean to suggest migrating to Gerrit. (I think there are both benefits and pains - but that's for another discussion, I guess.) I just thought issues "that involve other infrastructures and tools" categorically could use the hackathon where people who otherwise don't usually meet meet.

In that category, "Refactor and share components with the Wikipedia app" might be more suitable for a hackathon - the internals of the app would be easier to understand if you can directly ask people from the team looking at the same screen.

**Comment by misaochan** [comment]
Ah, yes, that does make a lot of sense. I agree with you, that would be awesome as well. Would a member of the Wikipedia app team be on board with working with us for a session?

**Comment by whym** [comment]
I reached to hackathon@wikimedia.at about it and Rachel Farrand responded. She told me that many of the WMF's Android developers do plan to attend the event - so it looks like we will have a good opportunity for collaboration. She also suggested sending to android@wikimedia.org for discussions with the developers.

Here is an excerpt from her response (posted with permission) with other related points:

> (snip)
> we are actively trying to come up with new and better ways to encourage and facilitate pre-hackathon collaboration. It is being discussed here: https://phabricator.wikimedia.org/T120092 and also here: https://phabricator.wikimedia.org/T124262

> There are a lot of ideas flying around at the moment, and we will have a more solid plan in a few months. 

> Additionally, it looks like there may be multiple smaller technical events taking place in European cities. We will announce these events to registered hackathon participants (once we open registration and start collecting names and email addresses). Keep an eye out for these.

**Comment by misaochan** [comment]
Awesome. :) I don't really know how submission of a project for a hackathon works, do we need to officially submit ours to the event committee for inclusion?

**Comment by misaochan** [comment]
@VojtechDostal sounds good, and I agree! The Nearby function definitely needs a lot of improvement. Do you think you could organize our inclusion in the hackathon? I could help with whatever is needed but I have never attended one before, let alone organized one. :)

Many thanks!

**Comment by misaochan** [comment]
I've been reading https://www.mediawiki.org/wiki/Hackathons/FAQ and from what I can see the process is just:
1. Register (and apply for travel scholarship if needed) when WMF opens registration for the event
2. Put up our project on the associated Phabricator board when it is open
3. Show up and work on it?

Did I get that mostly right?

**Comment by tobias47n9e** [comment]
Registration is now open: https://www.mediawiki.org/wiki/Wikimedia_Hackathon_2017/Register_and_Attend

**Comment by misaochan** [comment]
Thanks @tobias47n9e ! @VojtechDostal and I are currently trying to set up the prehackathon as well : https://www.mediawiki.org/wiki/Wikimedia_Hackathon_2017/Prehackathon_Prague

Some things that I think we might need to discuss:

- How do we allocate the topics to work on, between the pre-hackathon and hackathon? Should we have one small task for the pre-hackathon and one larger task for the hackathon perhaps? I think both should be related to the Nearby function, as that appears to be the aspect of our app that has garnered the most interest in the community.
- Who else should we invite to the prehackathon (besides the people on this thread who have already expressed interest in attending)?

**Comment by tobias47n9e** [comment]
@misaochan Speaking of the Nearby-function. I am pretty confident that I can get the photo-request part of the webapp done before the hackathon (first version should be online in a couple of weeks).

These 3 tasks therefore seem to be good things to work on for both events:

 - SPARQL-based finding of missing images on Wikidata
 - REST-based requested images provided by the web-app
 - A ~ 1 hour discussion, how to model campaigns in the web and mobile app

Should we for example also notify: https://okfn.org/network/czech-republic/ about the event?

**Comment by misaochan** [comment]
@tobias47n9e great suggestions. Re: the web app, do you mean the spatial database described at https://github.com/commons-app/commons-app.github.io/issues/16 ? Would we be wanting to work on further developing the web service, or on setting up the client side in the Android app?

**Comment by tobias47n9e** [comment]
@misaochan That might be good idea for people that have more experience with HTML/JS/Python than with Java and Android.

**Comment by misaochan** [comment]
@tobias47n9e if we do run a session for the web app, would you be willing to lead it? I'm not very familiar with web development, but would like to learn. :)

**Comment by tobias47n9e** [comment]
@misaochan Sure. I can give a short introduction to what it currently does.

**Comment by misaochan** [comment]
Shall I close this to focus on #353 ?

**Comment by tobias47n9e** [comment]
@misaochan I think we can close this issue. Seems like the original topic has been solved and the other topics are tracked elsewhere.
