### ISSUE TITLE
Remove the strings which have to be stored as constant from strings.xml

### ISSUE THREAD

**Issue by neslihanturan** [commons-app/apps-android-commons#2931]
**Summary:** 

As @yarons pointed out at #2927 , some strings from strings.xml should be removed. They should have been defined as constants. Ie.

\<string name="review_c_violation_report_problem">copyRightViolation\</string>

They don't need to be translated, they are strings to be used for the code, not for the user read them. 

This task is quite beginner friendly though.

**Comment by sivaraam** [comment]
Just for the note, I don't think we would have to declare them as constants within the code (i.e., the Java files) though. These constant strings could be kept in a separate string resource file (like [string_no_translate.xml](https://github.com/wikimedia/apps-android-wikipedia/blob/master/app/src/main/res/values/strings_no_translate.xml)) so that they aren't subject to translation.

I'm not sure if we would have to do anything more than just putting the strings which should not be translated into a separate resource file, though. May be looking into [how the Wikipedia app has done it](https://github.com/wikimedia/apps-android-wikipedia/blob/master/app/src/main/res/values/strings_no_translate.xml) would help.

**Comment by domdomegg** [comment]
I'm not sure how they're used in the code, but it sounds like an enum might be the best solution. Definitely agree they shouldn't be a translated string!

If we're keeping it in XML, [the docs](http://tools.android.com/recent/non-translatablestrings) suggest using the `translatable="false"` attribute - I don't know if translatewiki obeys this.

**Comment by ashishkumar468** [comment]
The string has been used for branch statements as below(problem being the string usage)
 `if (problem.equals("spam")) {
            reasonList[0] = "A selfie";
            reasonList[1] = "Blurry";
            reasonList[2] = "Nonsense";
            reasonList[3] = "Other";
        } else if (problem.equals("copyRightViolation")) {
            reasonList[0] = "Press photo";
            reasonList[1] = "Random photo from internet";
            reasonList[2] = "Logo";
            reasonList[3] = "Other";
        }`
Considering the situation, as @domdomegg said, I believe there is no reason to not put the string as  constant or  enum or maybe stringdefs

**Comment by neslihanturan** [comment]
@sivaraam 
> Just for the note, I don't think we would have to declare them as constants within the code (i.e., the Java files) though. These constant strings could be kept in a separate string resource file (like string_no_translate.xml) so that they aren't subject to translation.

Can you please explain why you think in this way?

Enum seems like the best to me.

**Comment by sivaraam** [comment]
> Can you please explain why you think in this way?
>
> Enum seems like the best to me.

Sorry for the unuseful comment in between :-( I was commenting in general about how to handle some constant string which shouldn't be translated. It's only now after looking the code that I realise that the string of concern should indeed be an element in an enumeration. Sorry again. I'm surprised someone thought of using string to handle this case. Anyways, let's just fix that at least now :-)

**Comment by neslihanturan** [comment]
Yeah, this code is from the hackathon. This mistake should have been related with time constraint. I am glad we all agreed:)

**Comment by kateOmally** [comment]
I'm a first timer at open source. May I take this issue? Looks simple enough. But i'm new here, so let me know if I'm missing something.

**Comment by neslihanturan** [comment]
Yes this one is quite beginer friendly, welcome @kateOmally :)

**Comment by kateOmally** [comment]
Is there a way to find which strings should be turned into enum? So far, i only know about review_c_violation_report_problem.

**Comment by sivaraam** [comment]
> Is there a way to find which strings should be turned into enum? So far, i only know about review_c_violation_report_problem.

To find which strings need to turned into enum just search for the usages of the *review_c_violation_report_problem* string in the code. Your search must lead you to [ReviewController.java](https://github.com/commons-app/apps-android-commons/blob/dcbf076965071576889b13af02d6574533974136/app/src/main/java/fr/free/nrw/commons/review/ReviewController.java). Try to dig more from there to find what string need to be turned into enum. 

Let us know if you want more help :-)

**Comment by neslihanturan** [comment]
There are some urls and tokens as well, ie. mapbox://styles/mapbox/traffic-night-v2
Everything under strings.xml should be translatable. Others should be constants instead.

**Comment by kateOmally** [comment]
I need some help: I can't find the right place in the app for the user to exercise this code. That is, I expected that if the user looks at an uploaded image (in its page with Summary and so on), there'd be a button to [flag content] as inappropriate or some such thing.

The fix is straightforward, but i want to test my change, and i can't figure out how.  :-/

**Comment by kateOmally** [comment]
Never mind, I think i found it.

> I need some help: I can't find the right place in the app for the user to exercise this code. That is, I expected that if the user looks at an uploaded image (in its page with Summary and so on), there'd be a button to [flag content] as inappropriate or some such thing.
> 
> The fix is straightforward, but i want to test my change, and i can't figure out how. :-/

**Comment by kateOmally** [comment]
Okay , new question. I'm trying to run DeleteHelperTest and get the error "command line is too long. Shorten command line for DeleteHelperTestor also forAndroid JUnit default configuration."  I've never encoun

**Comment by ashishkumar468** [comment]
Hi @kateOmally . Please try [this](https://blog.jetbrains.com/idea/2017/10/intellij-idea-2017-3-eap-configurable-command-line-shortener-and-more/)

**Comment by kateOmally** [comment]
Thanks. That worked.

**Comment by kateOmally** [comment]
Okay, I think i've gotten myself oriented on how the app works and how the code is structured.

Do you agree with the following changes?
Remove these from strings.xml:
```
  <string name="review_spam_report_problem">spam</string>
  <string name="review_c_violation_report_problem">copyRightViolation</string>

```
Add an enum to ReviewController.java
make corresponding changes to DeleteHelper.java
 
Looking for similar issues, 
I didn't find usages of these:
```
  <string name="map_theme_light">mapbox://styles/mapbox/traffic-day-v2</string>
  <string name="map_theme_dark">mapbox://styles/mapbox/traffic-night-v2</string>
  <string name="get_directions">GET DIRECTIONS</string>
  <string name="read_article">READ ARTICLE</string>

```
And these look like a candidate for removing from strings.xml or making translatable="false"
```
  <string name="beta_opt_in_link">https://play.google.com/apps/testing/fr.free.nrw.commons</string>
  <string name="mapbox_commons_app_token">pk.eyJ1IjoibWFza2FyYXZpdmVrIiwiYSI6ImNqMmxvdzFjMTAwMHYzM283ZWM3eW5tcDAifQ.ib5SZ9EVjwJe6GSKve0bcg</string>


```
