### ISSUE TITLE
Set "depicts" automatically for images uploaded via "Nearby"

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#2942]
Daithib8 uploaded https://commons.wikimedia.org/wiki/File:Ailtbrack_Lough.jpg via Nearby for Q33225778.

Automatically, Q33225778 had its P18 set to https://commons.wikimedia.org/wiki/File:Ailtbrack_Lough.jpg

Enhancement: Automatically, https://commons.wikimedia.org/wiki/File:Ailtbrack_Lough.jpg should have its P180 set to Q33225778 (as "Prominent").

**Comment by VitalyVPinchuk** [comment]
Hello @nicolas-raoul 
I'd like to work on this.

**Comment by nicolas-raoul** [comment]
@VitalyVPinchuk Thanks it is yours :-) Please let us know about your progress everyday, as it might interest people at the hackathon this Friday/Saturday/Sunday.

**Comment by VitalyVPinchuk** [comment]
While uploading an image on beta-cluster from nearby, I get an error `badtoken The centralauthtoken is not valid` when call to `wikidatCreateClaim` method is made. Trying to find out what the problem is.

**Comment by VitalyVPinchuk** [comment]
Hello @nicolas-raoul 
I've tried to set property P180 for uploaded images via "nearby".
Image itself uploads ok with the property added, but after that the map at "nearby" isn't shown anymore. I need some advice on how to call API correctly. 
I haven't been able to make it work on beta-cluster yet, so I used prodDebug and then manually cleared my test uploads, sorry for that.
E.g. https://commons.wikimedia.org/wiki/File:Fedov_14.jpg

**Comment by nicolas-raoul** [comment]
The P180 looks good, congratulations!
Sorry, I am not sure what the problem is with the map not showing.

**Comment by VitalyVPinchuk** [comment]
Could anyone of the seniors please have a look into the code and tell what the problem is with the map after `wbeditentity` api call?

**Comment by neslihanturan** [comment]
Hi @VitalyVPinchuk , Are you sure map isn't visible is related with your api call? I mean they seem irrelevant to me at first. Can you please check error logs, maybe your previous api call has some errors and this blocks further api calls etc?

**Comment by VitalyVPinchuk** [comment]
Hello @neslihanturan
I make two calls to commons api, first one is to get page id, and the other one is to set p180 property for the id I got from the first call. Image still uploads okay, despite this problem.
And yes, I am pretty sure that the problem is due to these calls, because when I remove them image uploads and the map is shown afterwards.

**Comment by neslihanturan** [comment]
Hi @VitalyVPinchuk , do you still see an empty map? Or just s grey area? Is there any crash you can share with me? 

Additionally currently a complete refactor happens on nearby classes, so current issue might be solved in new implementation. Here, #2969 . It is not ready yet, I am currently working on them. Can you please share which methods should be implemented to test your changes? So that I can prioritize them and you can test your changes with new implementation. Maybe problem would be solved itself.

**Comment by VitalyVPinchuk** [comment]
Thanks.
It is grey area with spinning progress indicator.
I have to check logs for any related messages.
You could have a look at my repo branch fix-2942.
Those changes are minor.

**Comment by macgills** [comment]
I think that has been done? @nicolas-raoul what are the steps I would need to undertake to validate this?

**Comment by nicolas-raoul** [comment]
Sean:
I recently uploaded this pic via Nearby:
https://commons.m.wikimedia.org/wiki/File%3A%E4%B8%96%E7%94%B0%E8%B0%B7%E5%B8%82%E5%A0%B4.jpg
The Wikidata item has its P18 linking to the picture, which is good.
But the point of this issue is to set "depicts" in the structured data of
the picture linking to the item, which the app is not doing yet as you can
see at my URL.

**Comment by macgills** [comment]
@nicolas-raoul Were you using the structured-data branch?

**Comment by nicolas-raoul** [comment]
Ah no sorry lol
Would you mind sending me an APK?

**Comment by nicolas-raoul** [comment]
After testing this a lot today, I think that the item from Nearby (when coming from Nearby) should be added as pre-selected (maybe even undeselectable) in Step 2 or the upload.

If not, people will try to find this item, and waste time searching needlessly.

**Comment by macgills** [comment]
@nicolas-raoul will we make a new ticket for "Nearby Item should be added as a preselected depiction"?

**Comment by nicolas-raoul** [comment]
Sean: Sure, would you mind creating it? Thanks 🙂

**Comment by macgills** [comment]
#3694 done
