### ISSUE TITLE
Web page opened isn't persisted across app opens

### ISSUE THREAD

**Issue by sivaraam** [commons-app/apps-android-commons#2944]
**Summary:** 
When I open a web page by tapping on a web link from within the app, it opens it using custom tabs. Then if I tap on the home button and re-open the app by tapping on the app's icon, the web page that I opened is gone. I'm taken back to the page from which I opened the web page.

**Steps to reproduce:** 
1. Go to About
2. Tap on the Privacy policy link
3. Tap on the home button of your device
4. Re-open the app by tapping on the app's shortcut icon (not via the recent apps)

I expect to see the webpage that I opened but I don't see it.

**Device and Android version:** 
Samsung SM-J111F running Android 5.1.1

**Commons app version:** 
2.10.2.421~5d827e4

**Would you like to work on the issue?**
Nope

**Comment by madhurijain97** [comment]
I think that this is the expected behavior. The webpage is opened in a browser only when a click is triggered. The browser and app are separate and as a result, the webpage will not open up when the user re-opens the app. Please correct me if I am missing out something.

**Comment by sivaraam** [comment]
I don't think this is the intended behaviour. I suspect this might be because we specifically add a flag for the browser to open as a new activity.

`customTabsIntent.intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK | Intent.FLAG_ACTIVITY_CLEAR_TASK);`

Ref: [handleWebUrl](https://github.com/commons-app/apps-android-commons/blob/master/app/src/main/java/fr/free/nrw/commons/Utils.java#L144)

I use another app where this seems to work as expected (i.e., opening the app opens the web page I last opened). [Corresponding code in that app](https://github.com/gsantner/markor/blob/14a933963e571ab107af8a9870433d6f3463dd37/app/src/main/java/net/gsantner/markor/util/MarkorWebViewClient.java#L63) doesn't seem to set the `FLAG_ACTIVITY_NEW_TASK`.
