### ISSUE TITLE
Shrink images to width of screen in media details view, and allow users to zoom to enter

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#2950]
Feedback from @schoenbaechler at hackathon: Media details view of image should automatically shrink images to width of screen, and allow them to zoom in, instead of just displaying a part of the image.

**Comment by nicolas-raoul** [comment]
Yes I always thought this!

**Comment by nicolas-raoul** [comment]
A similar PR was closed recently for inactivity: #2427

**Comment by VojtechDostal** [comment]
> Yes I always thought this!

Me too!

**Comment by misaochan** [comment]
I think this would be fixed in #2954 when it is merged.

**Comment by Rishavgupta12345** [comment]
@nicolas-raoul this issue is already fixed by the above pull request so we can close this issue now
