### ISSUE TITLE
Caption lost after going to depicts then "previous" back to captions

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#2976]
1. Open the upload activity
2. Enter a caption and description
3. Press Next, enter a category
4. Press Next, you are now in the "depicts" activity
5. Press "Previous"
6. Press "Previous" again
7. Expected: Caption and description still visible. Actual problem: Caption and description are lost

**Comment by vanshikaarora** [comment]
@nicolas-raoul , this issue persisted in the previous commits. AFAIK this issue doesn't persist in the latest commit. 
Can you please verify that the issue is solved or not

**Comment by nicolas-raoul** [comment]
Yes it is fixed, thanks!
