### ISSUE TITLE
New Feature: Location-based Wikidata tagging of uploaded photos

### ISSUE THREAD

**Issue by kalpaitch** [commons-app/apps-android-commons#298]
The idea would be to use the location data gathered from a photo to suggest nearby Wikidata items that could be tagged, to enable greater reuse of commons uploads.

**Comment by tobias47n9e** [comment]
Thank you for your suggestion. I think similar ideas are also addressed here: https://github.com/commons-app/apps-android-commons/issues/259

**Comment by kalpaitch** [comment]
Yes, apologies for not finding that one, please mark this as a duplicate.

**Comment by tobias47n9e** [comment]
Don't worry about it. It would be great if you could comment on the existing issue how you would expect the feature to work.

**Comment by misaochan** [comment]
Hi @kalpaitch ,

Thanks for posting here! Sorry, I had forgotten about #259 when I was discussing this feature with you and John. 

We could definitely use help with implementing this feature anyhow. :)
