### ISSUE TITLE
Categories from last upload selected

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#2983]
1. Upload a picture with 3 categories
2. Start uploading another picture
3. Reach the categorization activity
4. Expected: No categories selected. Actually: The 3 categories from step 1 are selected.

With yesterday's commit (not tried with today's commits)

Not sure whether the problem is in master too, or not.

**Comment by ashishkumar468** [comment]
@nicolas-raoul , shouldn't be there in master, I will look into it and add a fix for the same.

**Comment by nicolas-raoul** [comment]
I have not noticed that recently.
