### ISSUE TITLE
Non-selected categories shown when category search field empty

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#2984]
Steps:
1. Start uploading a file
2. Choose 2 categories
3. Erase everything from the categories search field
4. Expected: Only selected categories are shown. Actually: Non-selected categories are shown too.

This might be a problem in master too, I have not tried.

![Screenshot_20190603-141713_Commons](https://user-images.githubusercontent.com/99590/58777753-c7b78980-860a-11e9-8e20-eea0bbebb588.jpg)

**Comment by vanshikaarora** [comment]
@nicolas-raoul I am not able to reproduce the issue. Does the issue still persist?

**Comment by nicolas-raoul** [comment]
I haven't seen this in a while.
