### ISSUE TITLE
Double slash in URL

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#2991]
The app performs this request:

https://tools.wmflabs.org/urbanecmbot/commonsmisc//wikidataedits.py?user=Syced

As you can see, the last slash is doubled. It believe this is a small mistake?
It has no impact on the results, but I guess it is worth fixing anyway.

Super-low priority.

**Comment by ashishkumar468** [comment]
Thanks for pointing this out @nicolas-raoul, as the fix was really small, I have raise a PR for the same :-)
