### ISSUE TITLE
Load images without an Internet connection

### ISSUE THREAD

**Issue by kodchi** [commons-app/apps-android-commons#30]
Wouldn't it be great that once images are synced they stay available locally even when the internet is off?

**Comment by misaochan** [comment]
Sounds like a good idea to me!

**Comment by misaochan** [comment]
Rethinking this. Wouldn't it take up quite a lot of disk space?

**Comment by nicolas-raoul** [comment]
Not much if we only store thumbnails.

**Comment by Ayan-10** [comment]
@nicolas-raoul I think this issue is resolved now. Isn't it?

**Comment by nicolas-raoul** [comment]
You are right, thanks!

**Comment by nicolas-raoul** [comment]
You are right, thanks!
