### ISSUE TITLE
[GsoC 2019] Copy previous caption & description

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#3004]
Steps to reproduce the problem:
1. In Android gallery, choose 2 pictures
2. Share to Commons app
3. Enter caption for first picture
4. Press Next
5. Press "Copy previous title & description"
6. Problem: caption does not get copied.

Also, the button should be renamed to "Copy previous caption & description"

**Comment by vanshikaarora** [comment]
I'll fix this in the next commit

**Comment by vanshikaarora** [comment]
Hey @nicolas-raoul, I have fixed the Issue here n the commit https://github.com/vanshikaarora/apps-android-commons/commit/be6b726699d3f8e07b290b0e393ceb65d074f467

**Comment by nicolas-raoul** [comment]
It works now, thanks for fixing! :-)

**Comment by nicolas-raoul** [comment]
Related: #3035
