### ISSUE TITLE
[GSoC 2019] Caption not filled when uploading from Nearby

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#3005]
Steps to reproduce:
1. Go to Nearby
2. Select a pin
3. Add a picture for it
4. Problem: In the metadata activity, Caption is empty

In master, title get filled with the label of the Wikidata item.

Fix:
Fill the caption using the label of the Wikidata item (using the code already present for title, that should be an easy change, the only difficulty is to set the right language in the UI).

![Screenshot_20190609-144512_Commons](https://user-images.githubusercontent.com/99590/59191089-78003180-8bb9-11e9-9fa3-f4010f2d50bd.jpg)

**Comment by vanshikaarora** [comment]
@nicolas-raoul I have started working on it. But there is just one problem. How can i detect current language in which the place is returned from NearbyFragment. Do you have any idea how to proceed?

**Comment by nicolas-raoul** [comment]
Good question!
You should modify NearbyFragment to make it give the language too.
Let's consider that `classLabelPreferredLanguage` is always the language of the description _(even though it is not always true today: As can be seen in `app/src/main/resources/queries/nearby_query.rq`, the language might be any other language if there is no label filled for `classLabelPreferredLanguage`, but that's [another issue which is out-of-scope for this GSoC](https://github.com/commons-app/apps-android-commons/issues/2663#issuecomment-502527127))_.

**Comment by vanshikaarora** [comment]
@nicolas-raoul here i see:

```
localizationPlugin.matchMapLanguageWithDeviceDefault();
```

that we are trying to match with the apps language, so instead of searching in nearbyfragment, shall i use the devices locale as caption's language

**Comment by nicolas-raoul** [comment]
Yes, you can do that.
It is not ideal, but anyway we can't make that feature perfect until #2663 is implemented, so using the device's language is good enough for now.

**Comment by vanshikaarora** [comment]
OK I'll try this out

**Comment by vanshikaarora** [comment]
@nicolas-raoul I have resolved the issue [here](https://github.com/commons-app/apps-android-commons/pull/2970/commits/cbd52ec460ae744ad62d09134fffa79cb582dcfb). Please check:)

**Comment by nicolas-raoul** [comment]
Unfortunately the issue is still present.

**Comment by vanshikaarora** [comment]
@nicolas-raoul this issue is fixed for me in the commit https://github.com/vanshikaarora/apps-android-commons/commit/59ac10959ba7723dfd368d074cce3ac3df5beac7 .  In case if the issue still persist for you we can try using `place.label` instead of `place.name`. Can you please check :)

**Comment by nicolas-raoul** [comment]
I just tried the latest upload_caption_depict and unfortunately the caption is not set:
https://commons.wikimedia.org/wiki/File:Shark_fins,_abalone,_birds%27_nests.jpeg

**Comment by vanshikaarora** [comment]
I'll look into the issue again:)

**Comment by nicolas-raoul** [comment]
This now works as expected, the caption is present, I tried with several languages :-)
