### ISSUE TITLE
[GSoC 2019] Categories names blank

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#3006]
At the categories selection step, categories names do not appear:

![Screenshot_20190610-123259_Commons](https://user-images.githubusercontent.com/99590/59190812-ac272280-8bb8-11e9-9863-572230d76b17.jpg)

Anyone using alpha master: Is it a problem on master too?

**Comment by vanshikaarora** [comment]
@nicolas-raoul I just checked the Issue it does not persist in the master, it is only in Refactor-uploads. I'll fix this in the next commit

**Comment by vanshikaarora** [comment]
@nicolas-raoul this issue is fixed herein the commit https://github.com/vanshikaarora/apps-android-commons/commit/d900748aaccdb27f3376dcb72a43e1efd4d9261b

**Comment by vanshikaarora** [comment]
![WhatsApp Image 2019-06-16 at 4 17 42 PM](https://user-images.githubusercontent.com/34261945/59563094-eda14d00-9052-11e9-924e-4872538858a2.jpeg)

**Comment by nicolas-raoul** [comment]
I just tested, it works, thanks for fixing! :-)
