### ISSUE TITLE
Achievements nearby tooltip hidden

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#3007]
The circled "i" is half hidden:
![Screenshot_20190605-192441_Commons](https://user-images.githubusercontent.com/99590/59194603-7f790800-8bc4-11e9-89db-bb626f1c5e80.jpg)
I guess the line should wrap or something?

**Comment by vanshikaarora** [comment]
@nicolas-raoul I noticed this Issue too.
Should we just add a single line below "Images via Nearby Places" which says [Tap here for more info], if  this makes the layout a little crowded then may be reducing the font size might me an option. What do you say?

**Comment by nicolas-raoul** [comment]
@vanshikaarora Some languages take more space than others, for instance I am sure French will not fit even if we make the font smaller. The best solution would be to make sure that the text AND the (i) wrap nicely when it is too long.

**Comment by madhurgupta10** [comment]
@nicolas-raoul Looks like this one solved in https://github.com/commons-app/apps-android-commons/pull/4323
