### ISSUE TITLE
Error publishing Google Play Alpha builds with Gradle 5

### ISSUE THREAD

**Issue by domdomegg** [commons-app/apps-android-commons#3018]
**Summary:** 

Travis builds are failing, I think in the command publishing the alpha build to the play store. This is after updating to Gradle 5 (I merged #2860 - everything seemed to be working, it built fine and tests passed - sorry for breaking it).

Have taken a look myself but not sure how to fix - @maskaravivek I'm hoping you might? Otherwise we can revert the changes until we think publishing to Google Play from Travis works again.

**Comment by neslihanturan** [comment]
Can we revert until a solution is found? Otherwise we have to revert it for each branch that we sync with master to test them.

**Comment by neslihanturan** [comment]
I created the revert pull request, please feel free to merge it if you agree, I don't want to merge my own PR:  #3019

**Comment by neslihanturan** [comment]
Well, it seems like sleep time for everyone's time zone, I merged my own pull request. It just reverts the problematic pull request.

**Comment by misaochan** [comment]
Thanks @domdomegg and @neslihanturan for the quick response! :) I pinged @maskaravivek for review of #3023 since he was the one who set up our automated releases.
