### ISSUE TITLE
Category search does not work properly [current master]

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#3027]
**Summary:** 

Searching for the exact category name does not output any results even though that category exists.

**Steps to reproduce:** 

I searched for "Christchurch Botanic" and was told "No Categories Found". However that exact category does exist as per my search of only "Christchurch".

![Screenshot_1561017509](https://user-images.githubusercontent.com/3611199/59832502-62dc8d00-9387-11e9-9b02-95c2364a8f2b.png)
![Screenshot_1561017541](https://user-images.githubusercontent.com/3611199/59832509-640dba00-9387-11e9-9290-f701ee5cbdff.png)

**System logs:**

Sorry, forgot to collect logs but it is 100% reproducible for me, so if you have difficulty reproducing I can collect them again.

**Device and Android version:** 

Nexus S API 27 emulator, AND Samsung Galaxy S9 
 
**Commons app version:** 

Current master 2.10.2.452

**Comment by nicolas-raoul** [comment]
I noticed this too, it is a very recent problem.
![Screenshot_20190619-140838_Commons](https://user-images.githubusercontent.com/99590/59833681-91576980-9381-11e9-9eab-8a1d2de8f1e6.jpg)

**Comment by ashishkumar468** [comment]
Thanks for finding the issue @misaochan  and @nicolas-raoul , I will look into it :-)

**Comment by ashishkumar468** [comment]
@misaochan  I tried manually calling the api's with ["Christchurch Botanic"](https://commons.wikimedia.org/w/api.php?aclimit=25&action=query&format=xml&list=allcategories&acprefix=Christchurch+Botanic), for which I get the response ```
<allcategories>
<c xml:space="preserve">Christchurch Botanic Gardens</c>
</allcategories>
```,  
And the app as expected shows, one search result for the same.
![device-2019-06-23-160042](https://user-images.githubusercontent.com/17375274/59975049-53e91b00-95d1-11e9-820b-1b4a21e55053.png)


But for the search term [christchurch botanic g](https://commons.wikimedia.org/w/api.php?aclimit=25&action=query&format=xml&list=allcategories&acprefix=christchurch+botanic+g), I actually gets 0 response from the api's 
```

<query>
<allcategories/>
</query>
</api>
```

The keywords are case sensitive, and that is why, although Christchurch Botany has some results, but christchurch botanic g does not have any

**Comment by misaochan** [comment]
A recap of my conversation with Ashish: It actually looks like the first letter of the first word is not case-sensitive, but the others are. That would explain both my and @nicolas-raoul 's findings. 

We are planning to look at the old category implementation (prior to the upload process overhaul) to see how this was handled previously, since this issue appears to be new (but to the best of our knowledge the API hasn't changed).
