### ISSUE TITLE
Wrong photo displayed in ContributionsActivity during upload process [current master]

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#3028]
**Summary:** 

The previous photo uploaded is displayed instead of the current photo being uploaded

**Steps to reproduce:** 

Upload a photo and watch the process in ContributionsActivity

**Device and Android version:** 

Samsung Galaxy s9 Android 8.1
 
**Commons app version:** 

Current master

**Screen-shots:** 

![Screenshot_1561017562](https://user-images.githubusercontent.com/3611199/59832829-2f4e3280-9388-11e9-96e4-cb7d3797c4a9.png)

**Comment by nicolas-raoul** [comment]
I confirm, it happens all the time.

**Comment by ashishkumar468** [comment]
I was trying to fix this issue, seems like the local URI which we have while uploading an image is not an actual path of the image, its the one provided by the content provider for temporarily accessing the input stream and my guess is that it does not support concurrent access(while the upload is going on the image is not loaded). The best solution I could come temporarily is to show a place holder image instead of wrong image while the upload is in progress and once the upload finishes, show the image with the url we have. What do you guys say @maskaravivek  @misaochan @neslihanturan @nicolas-raoul ?

**Comment by neslihanturan** [comment]
@ashishkumar468 Place holder image seems like a good idea to me. 

But what I did not understand this issue is recently happened. How come it was working previously?

**Comment by ashishkumar468** [comment]
@neslihanturan , You mean the correct image was being shown while the image was being uploaded ?

**Comment by neslihanturan** [comment]
Yes @ashishkumar468

**Comment by ashishkumar468** [comment]
Do you mean the current master @neslihanturan , I just downloaded the app from play store, seems like even in this version, we just show a  place holder image while the upload is going on and then just after the upload finishes, we show the actual image. Attaching the relevant gif file
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/17375274/60625210-b8438000-9e04-11e9-9bf0-9fd1416ce142.gif)

**Comment by nicolas-raoul** [comment]
Placeholder is OK for me. It is definitely better than showing the wrong image.

**Comment by neslihanturan** [comment]
Thanks for the gif @ashishkumar468 , I was trying to say not in current master but there was a time upload preview was working. Anyway, I think everyone agrees and we go with placeholder solution.

**Comment by ashishkumar468** [comment]
I just edited my comment, I meant the current prod app live on google play store. @neslihanturan  :-), I will still try to figure out if we can somehow show the actual image while upload, worst cases will show the place holder

**Comment by misaochan** [comment]
Placeholder is fine in my book as long as it updates to the correct image after the upload is complete.

@neslihanturan I think it might be caused by changes that we made to the way we handle file paths in the last several months, to prevent certain crashes and failures that we were experiencing.

**Comment by neslihanturan** [comment]
I suspected the same @misaochan , but such a obvious bug would be reported on pull request tests for sure. But definitely related with those changes.

**Comment by ashishkumar468** [comment]
This has already been via #3046, feel free to re-open this issue if someone is still facing it
