### ISSUE TITLE
"Copy previous caption & description" only works for second picture in set

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#3035]
In a 4 pictures set.

At third picture, the button does nothing when pressed (even though caption&description of second picture is filled).

At fourth picture, the button does nothing when pressed (even though I filled manually the caption&description of the third picture).

**Comment by misaochan** [comment]
@nicolas-raoul , does this only happen in gsoc2019 branch, or also in the Play Store alpha (master)?

**Comment by nicolas-raoul** [comment]
Sorry I did not try on master.
Every bug I tag gsoc2019 is tested only on that particular branch.

**Comment by vanshikaarora** [comment]
@nicolas-raoul @misaochan I have fixed the issue [here](https://github.com/commons-app/apps-android-commons/tree/f7c675856bd92e307ba1c88ec27b7e349dbc9d21) . Please check :)

**Comment by nicolas-raoul** [comment]
Great, it works now, thanks for fixing! :-)
