### ISSUE TITLE
Author is not shown for Uploaded via Mobile tab in Explore [current master]

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#3037]
**Summary:** 

In the "Uploaded via Mobile" tab of Explore, the author isn't shown for some pictures. Interestingly, after you scroll down a lot and then go back up to the top, the author isn't shown for ALL pictures. 

In Media Details View, the author field is empty, too.

This does not happen for Featured images at all.

![Screenshot_20190624-194111_Commons](https://user-images.githubusercontent.com/3611199/60009001-68eca980-96b8-11e9-925b-78e547416268.jpg)
![Screenshot_20190624-194126_Commons](https://user-images.githubusercontent.com/3611199/60009011-6b4f0380-96b8-11e9-9162-1f633a52562f.jpg)

**Steps to reproduce:** 

Go to Explore then Uploaded via Mobile tab

**Device and Android version:** 

Samsung Galaxy S9 Android 8.1
 
**Commons app version:** 

Play Store alpha (current master)

**Comment by bistaastha** [comment]
Hi
I tried to reproduce this on the current master, and all images under 'Uploaded via Mobile' tab have author names. However, 'Featured' tab does not have any author names showing under the image, though they are present in the Media Details View.

**Comment by aakankshaa23** [comment]
Hello,
I tried to reproduce and the featured tab is not showing the name of some authors though the author exists.
![WhatsApp Image 2020-03-12 at 12 55 19 PM (2)](https://user-images.githubusercontent.com/37452934/76497510-1e3ad980-6461-11ea-8378-85c90e20ad6d.jpeg)
![WhatsApp Image 2020-03-12 at 12 55 19 PM (1)](https://user-images.githubusercontent.com/37452934/76497515-20049d00-6461-11ea-89cb-8f074f962575.jpeg)
![WhatsApp Image 2020-03-12 at 12 55 19 PM](https://user-images.githubusercontent.com/37452934/76497517-209d3380-6461-11ea-81a1-f5e956cb953c.jpeg)

**Comment by misaochan** [comment]
Thanks for sharing @aakankshaa23 ! Would you like to work on this?

**Comment by aakankshaa23** [comment]
yeah. I would love to :)

**Comment by misaochan** [comment]
It's yours! Please keep us updated on your progress. :)

**Comment by aakankshaa23** [comment]
I tried to replace the setAuthorView function with direct check whether the author exists or not.
It is not repeating or disappearing the data as it is inside getView which prevents this kind of misfunctionality. 
Please suggest this change 
![Capture](https://user-images.githubusercontent.com/37452934/76546566-c11b4400-64b1-11ea-90b1-9c996221a3e0.PNG)

**Comment by aakankshaa23** [comment]
The latest PR contains the author's name shown in the featured tab. I just changed the setAuthorView with a check whether the creator exists or not and setting the author textview blank instead of GONE which solves the misfunctionality of changing author name while scrolling.
Sorry for the above closed PRs as it contained unnecessary commits.
The latest PR contains only 1 required commit :)

**Comment by misaochan** [comment]
Hmmm. Referring to your PR, there is a bit of a problem here, as there is actually an author for https://commons.wikimedia.org/wiki/File:Paul_C%C3%A9zanne_-_The_Pigeon_Tower_at_Bellevue_-_1936.19_-_Cleveland_Museum_of_Art.jpg , as you can see in the Commons page. However, because the uploader is not the artist, it probably uses a different template, which we might not have accounted for when fetching the image details. @nicolas-raoul any idea what we should do for the "Author" field in situations like that?
