### ISSUE TITLE
[GSoC 2019] Upload not performed

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#3044]
Latest branch as of now.

**Steps to reproduce:** 

1. Upload a picture
2. After the license step, the app suddenly closes, unexpectedly
3. Pictures is not uploaded, as seen at https://commons.wikimedia.org/wiki/Special:Contributions/Aroravanshika or equivalent

**Comment by vanshikaarora** [comment]
Hey @nicolas-raoul this issue is fixed in the commit https://github.com/vanshikaarora/apps-android-commons/commit/e8db428b56406ab2df00f837c81308fe0df12fb1 . Please check if it works for you :)
