### ISSUE TITLE
Upload fails

### ISSUE THREAD

**Issue by Opsylac** [commons-app/apps-android-commons#3051]
**Summary:** 

I cannot upload new files.

**Steps**

I am on the french version of the app.
I upload a file, enter name, description, categories, licence. Click submit.
The loading bar charges... 
Then it says " failed" ("échoué"). 
The image does not appear, there is only a grey image icon flashing.

**Device and Android version:** 

Mobile : Fairphone 2 (FP2)
Android version : 7.1.2

**Commons app version:** 

2.10.2~66e1539a1

**Screen-shots:** 

Image insert doesn't seem to work on my browser (Firefox focus android).
Here is a link to a screenshot : https://www.dropbox.com/s/c51v22qawgz4tpy/Screenshot_20190702-142332.png?dl=0

**Would you like to work on the issue?**

I don't have the skills! Thank you in advance if you can fix that.

**Comment by neslihanturan** [comment]
Hi @Opsylac , thanks a lot for your report. Currently we are working to fix this issue. For a temporary solution you can try logging out and in again, sometimes this helps. For permanent solution please stay tuned, it will be available soon.

**Comment by Opsylac** [comment]
Great, thank you for answering so fast!
And thank you for working on this.

**Comment by ashishkumar468** [comment]
Uploads have been refactored, should not happen on latest commits, also without the logs there is nothing where we could look specifically for this issue, closing this issue, feel free to re-open if someone is able to reproduce this
