### ISSUE TITLE
delete branch bot deleted master branch

### ISSUE THREAD

**Issue by maskaravivek** [commons-app/apps-android-commons#3073]
The delete branch bot deleted the master branch when this PR was merged #3072. 

<img width="747" alt="Screen Shot 2019-07-15 at 10 39 07 PM" src="https://user-images.githubusercontent.com/3069373/61234936-f2d8e100-a751-11e9-862e-db953b17ae58.png">

We should disable the plugin or maybe configure it to protect some branches. Anyways we are safe as I have a local copy of the latest master.

**Comment by misaochan** [comment]
Bot uninstalled until we get config up.
