### ISSUE TITLE
Hide disambiguation items from depiction search

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#3077]
This first item is a disambiguation item, it should not be shown:
![Screenshot from 2019-08-28 12-09-18](https://user-images.githubusercontent.com/99590/63823004-39467000-c98d-11e9-8532-79605f65dd2b.png)
There are other kinds of "technical" items that probably should not be shown either, for instance Wikimedia categories like https://www.wikidata.org/wiki/Q32415105

**Comment by ashishkumar468** [comment]
@nicolas-raoul Do we have any property which explicitly specifies that this item is a disambiguation item or do we have to go by text ?

**Comment by nicolas-raoul** [comment]
We must rely on the P31 (instance of) statement.
Please note that this is a long-term enhancement, not in scope of GSoC 2019.
Anyone feel free to implement it :-)
I am not sure what is the best approach, if possible modifying the search query would be the most efficient, but it might not be possible.

**Comment by vanshikaarora** [comment]
Since disambiguation responses are noticed here, this must also be prevelant on the Commons Website. Right?. Shouldn't the we modify the APIs to remove disambiguation item from the backend itself?

**Comment by nicolas-raoul** [comment]
@vanshikaarora That's an idea indeed. I guess many other apps need an API search method that returns only "real-world" items.

This issue is not marked with the "gsoc2019" label, which means you don't need to worry about it (it is out of scope), but thanks for your insight! :-)

**Comment by macgills** [comment]
@nicolas-raoul I might need a definition on `disambiguation items`

Your linked example `No label defined (Q32415105)` is an `Instanceof (P31)` a `Wikimedia Category(Q4167836))`

Do I remove all results I fetch from the search endpoint that is an instanceOf Wikimedia Category?
Are are there further instances that must also be pruned?

The endpoint currently used is [wbsearchentities](https://www.wikidata.org/w/api.php?action=help&modules=wbsearchentities) and I don't see any existing parameters applicable to filtering out disambiguation items.

**Comment by nicolas-raoul** [comment]
There will be a handful of QIDs of classes we want to filter out, maybe 20 maximum.

Basically, [all subclasses](https://query.wikidata.org/#SELECT%20%3Fitem%20%3FitemLabel%20WHERE%20%7B%0A%20%20%3Fitem%20p%3AP31%2Fps%3AP31%20wd%3AQ17442446.%0A%20%20%23%3Fitem%20p%3AP31%2Fps%3AP31%2Fwdt%3AP279%2a%20wd%3AQ17442446.%0A%20%20%0A%20%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22%5BAUTO_LANGUAGE%5D%2Cen%22.%20%7D%0A%7D) of [Q17442446](https://www.wikidata.org/wiki/Q17442446) (Wikimedia internal item). Getting these items in real time [in SPARQL](https://opendata.stackexchange.com/questions/9591/how-to-include-sub-classes-in-a-wikidata-sparql-query-example-when-querying) would be the most elegant solution but it would be very server-resources-intensive, slow, and risky as a Wikidata editor could break it easily by setting a popular item as a subclass of one of these items.

So I would suggest hard-coding them and filtering out client-side. Please check for impact on paging though.

For now here is a hard-coded list of items to not show in search:
- Q4167410 Wikimedia disambiguation page
- Q17442446 Wikimedia internal item
- Q4167836 Wikimedia category

For the others, we can gather them little by little and add them to the list in a year, but for now the 3 above can do.

**Comment by macgills** [comment]
@nicolas-raoul 
```
props
Return these properties for each entity.

Values (separate with | or alternative): url
Default: url
```

is there an example usage of this parameter for the endpoint?

It would be really handy if these `props` were Wikidata Properties but I won't hold my breath.

We can I guess join the image request with the request for instanceOf items so our total number of requests doesn't increase but it is still not great.
We don't trigger an image request until absolutely necessary, ie the user has scrolled to that item in the list, so the user would see these items, the new request would (hopefully) complete and the disambiguation item would disappear.
To ensure the user never sees the disambiguation items we would have to do a request per item before presenting the results.

**Comment by nicolas-raoul** [comment]
Do you mean that when we display "Bow - Wikimedia disambiguation page", we don't have the QID yet?
Sorry I am not familiar with this API :-/ Would you mind posting a current sample request URL?
The SPARQL endpoint might offer more options, but that would be a big change and I am not sure how fast it is when paging tons of results.

**Comment by macgills** [comment]
https://www.wikidata.org/w/api.php?action=wbsearchentities&search=abc&language=en see an example search there.

`searchEntities` doesn't return an `Entity` but a limited searchResult sort of looking thing. We have the id of this object but no statements/claims.

I am pouring through the api docs and it seems `wbgetentities` can actually return us a list of Entities based on a list of ids so that seems a lot more viable than our current solution

**Comment by nicolas-raoul** [comment]
That URL returns results like:
```
{
            "id": "Q169889",
            "title": "Q169889",
            "pageid": 170288,
            "repository": "local",
            "url": "//www.wikidata.org/wiki/Q169889",
            "concepturi": "http://www.wikidata.org/entity/Q169889",
            "label": "American Broadcasting Company",
            "description": "American broadcast television network owned by The Walt Disney Company",
            "match": {
                "type": "alias",
                "language": "en",
                "text": "ABC"
            },
            "aliases": [
                "ABC"
            ]
        },
```
Just compare `Q169889` with the list of hard-coded banned QIDs Q4167410/Q17442446/Q4167836 and only show if it is not in the list :-) Am I missing something?

**Comment by macgills** [comment]
Yes, that QID is not an InstanceOf property, it is a specific item eg Elephant or in this case American Broadcasting Company"

**Comment by nicolas-raoul** [comment]
Indeed sorry!
How about just disabling the item (making it unselectable) once its P18 and P31 have been loaded?

**Comment by macgills** [comment]
I have already made a lot of headway into "instead of individually fetching the image property instead fetch the entities for all the ids returned in a search"  and from there it is pretty easy to do just add the instance of property and have some filtering in the presentation layer.
This reduces are amount of requests from `1+N+N/2` requests to `1+N/2`
