### ISSUE TITLE
Show captions in "Home" and "Explore"

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#3088]
As you scroll you see titles (=filenames) over the thumbnails, these should be captions:

![adb-screenshot](https://user-images.githubusercontent.com/99590/61783205-5940bc00-ae42-11e9-9fa1-e27814d9dbd4.png)

Show titles at first but replace with captions when available

**Comment by vanshikaarora** [comment]
@nicolas-raoul here are the commits for showing captions in [Explore](https://github.com/commons-app/apps-android-commons/pull/2970/commits/b9766199faeabd95564fc93f30ec1fc592ac3d98) and [home](https://github.com/commons-app/apps-android-commons/pull/2970/commits/22be5b50135403cdf7d91e71c40cbb620c033f56)

**Comment by nicolas-raoul** [comment]
Also, this must be implemented in the "Media" tab of Explore search.

**Comment by vanshikaarora** [comment]
I'll add it int my next commit

**Comment by nicolas-raoul** [comment]
Strangely, my home does not seem to show captions.

For instance, I recently uploaded https://commons.wikimedia.org/wiki/File:%E9%9A%85%E7%94%B0%E5%B7%9D%E9%A7%85_JR%E5%80%89%E5%BA%AB_3.jpg with the app, then added an English caption using the Commons website.
Problem: In my home activity the filename is used, not the English caption (my Android's locale is English): 
![adb-screenshot](https://user-images.githubusercontent.com/99590/62198753-30c63e00-b3bd-11e9-8f41-a32518fd3ab8.png)

**Comment by vanshikaarora** [comment]
OK I'll check this out

**Comment by nicolas-raoul** [comment]
Please test it on your device with a picture you uploaded. You can add captions easily using the Commons website :-)

**Comment by vanshikaarora** [comment]
@nicolas-raoul this issue is resolved here https://github.com/commons-app/apps-android-commons/pull/2970/commits/238a91a0462e71c7e860a5af9d8443a8fbbf01ed.

Please check :-)

**Comment by nicolas-raoul** [comment]
Wonderful!

Similarly, we must show captions in the list of images shown by depiction search.

For instance, search for the "boat" Wikidata item and you will find this image: https://commons.wikimedia.org/wiki/File:Stade,_Hansehafen_--_2018_--_2961.jpg
Problem: On my English locale Android it is not shown with its English caption but rather with its filename (minus the .jpg):
![adb-screenshot](https://user-images.githubusercontent.com/99590/62217462-9b8b6f80-b3e5-11e9-8873-cb519f08eac3.png)

**Comment by vanshikaarora** [comment]
>Similarly, we must show captions in the list of images shown by depiction search.

I'll add it in my next commit

**Comment by vanshikaarora** [comment]
@nicolas-raoul I have made the necessary changes in the [commit](https://github.com/commons-app/apps-android-commons/pull/2970/commits/2c94e4ec81243713a934dcfd2191dbfb8b464b52)

Please check :-)

**Comment by nicolas-raoul** [comment]
Wonderful, thanks for all the fixes you performed yesterday, that's impressive :-)

**Comment by vanshikaarora** [comment]
Thanks @nicolas-raoul :-)
