### ISSUE TITLE
Media details categories empty immediatly after upload, even though correctly uploaded

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#3092]
**Steps to reproduce:** 
1. Install latest 2.11 branch ( 8cd9bd5524248e51ec626aeb2b0a62b3d320fd27 ), prodDebug
2. Upload a picture with various categories
3. Wait for the upload to finish
4. Tap the picture in the home activity
5. Media details open, check categories
6. Expected: The categories I entered. Actually: "None selected"
7. Wait 10 minutes
8. Repeat from step 4: Same problem
9. Kill app (real kill from Android settings > Apps) then reopen: Same problem

Not a critical bug, but I am sure some users will wonder why their categories are "lost".

**Device and Android version:** 
Samsung S10e, Android 9

**Example** 
https://commons.wikimedia.org/wiki/File:Seaplane_maintenance_at_Trans_Maldivian_Airways_terminal.jpg
![adb-screenshot](https://user-images.githubusercontent.com/99590/61949690-980f7700-afe6-11e9-91ad-3d8a1ce9e449.png)

**Comment by thetimeheist76** [comment]
Hey, if this is still open I would like to work on it.

**Comment by nicolas-raoul** [comment]
It is yours! 🙂

**Comment by ashishkumar468** [comment]
@nicolas-raoul  are you still facing this issue on one of the latest commits?

**Comment by nicolas-raoul** [comment]
Seems fixed :-)
