### ISSUE TITLE
"No Depictions matching %1$s found"

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#3098]
1. Open search
2. Select Items tab
3. Enter a random long string
4. The message should be `No Wikidata items matching "あかさたなはまやら" found.` but instead I get this message:
![adb-screenshot](https://user-images.githubusercontent.com/99590/62112014-ce057180-b2ec-11e9-9640-460414ba2cd7.png)

**Comment by vanshikaarora** [comment]
@nicolas-raoul I have solved this issue in the latest commit [here](https://github.com/commons-app/apps-android-commons/pull/2970/commits/29e0fcad74055dba4dbc440941716e020eec1f40).

Please review :-) 

**Preview**
![Uploading IMG-20190726-WA00056.jpg…]()

**Comment by nicolas-raoul** [comment]
Great!
Very minor: Could you please make the "d" in "depictions lowercase? And a point at the end of the sentence.

**Comment by nicolas-raoul** [comment]
Ah sorry please ignore my previous message.

Instead, use this message: `No Wikidata items matching "あかさたなはまやら" found`

**Comment by vanshikaarora** [comment]
I have added this in my code. Will be pushed along with the next commit

**Comment by vanshikaarora** [comment]
I have resolved this issue in the commit [here](https://github.com/commons-app/apps-android-commons/pull/2970/commits/369137a96d5ee0c3dacc6a9a417fd8465e818d4d).

Please check :-)
