### ISSUE TITLE
No match message subsists even after searching again

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#3099]
1. Search for a random long string
2. "No match" message appears
3. Search for something else that exists
4. "No match" message still visible
![adb-screenshot](https://user-images.githubusercontent.com/99590/62112240-43714200-b2ed-11e9-9a02-03fbe59b2111.png)

**Comment by vanshikaarora** [comment]
@nicolas-raoul I have resolved the issue [here](https://github.com/commons-app/apps-android-commons/pull/2970/commits/62954080f25ef537cff9981bebe9ad6d11a2000b).

Please review :-)

**Comment by nicolas-raoul** [comment]
Fixed, thanks!
