### ISSUE TITLE
Same Wikidata items re-appear when scrolling

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#3100]
1. Open search
2. Search for "hello"
3. Select Items tab
4. The first item is "original song written and composed by Adele and Greg Kurstin"
5. Scroll down. New items get appended.
6. PROBLEM: Among the new items, the same item "original song written and composed by Adele and Greg Kurstin" is present.

**Comment by vanshikaarora** [comment]
@nicolas-raoul I have resolved the issue here in the latest commit https://github.com/commons-app/apps-android-commons/pull/2970/commits/f9a9854b18de289fb6e997f91b2381ba24b8ff2f
Please check :-)

**Comment by nicolas-raoul** [comment]
Thanks for fixing, it works great now :-)

**Comment by vanshikaarora** [comment]
>Thanks for fixing, it works great now :-)

Good to see :-)
