### ISSUE TITLE
Test fails in Travis CI even though it passes on my PC

### ISSUE THREAD

**Issue by ilgazer** [commons-app/apps-android-commons#3102]
The Travis CI build is failing in my PRs #3081 #3085 and #3087 because of this:
```
fr.free.nrw.commons.upload.UploadPresenterTest > handleSubmitTest FAILED
    org.mockito.exceptions.verification.WantedButNotInvoked at UploadPresenterTest.kt:63
```
However, when I run the tests on my PC, everything is fine and I don't get the same message. Can anyone help me out with this?

**Comment by sivaraam** [comment]
Closing this as the mentioned MRs seem merged by now. Thank you for your contribution, @ilgazer 🙂
