### ISSUE TITLE
Wikidata items list is not padded

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#3104]
The text is 1 pixel from the left side.
A bit more padding would probably be good.

**Comment by vanshikaarora** [comment]
@nicolas-raoul is this okay?

![Screenshot_20190731_144032](https://user-images.githubusercontent.com/34261945/62199531-462d6f00-b3a1-11e9-9fcd-14bce7725c62.png)

**Comment by nicolas-raoul** [comment]
Yes it looks great!

**Comment by vanshikaarora** [comment]
okay, I have added this in my code. Will be pushed along with the next commit

**Comment by vanshikaarora** [comment]
@nicolas-raoul I have resolved this issue [here](https://github.com/commons-app/apps-android-commons/pull/2970/commits/369137a96d5ee0c3dacc6a9a417fd8465e818d4d).

Please check :-)
