### ISSUE TITLE
Show thumbnail of P18 when asking the user to select a Wikidata item

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#3106]
This makes the choice much easier, especially when no label/description is available for the user's locale:

![bitmap](https://user-images.githubusercontent.com/99590/62345922-1a3ff400-b52f-11e9-8242-334a2b2606c3.png)

This should be used:
- When choosing depictions during upload
- When choosing depictions during search

Most Wikidata items used in depictions statements have an image, it can be retrieved easily from the item's QID by requesting the P18 property. If there is no image, just show empty space. Optional: In the rare cases where several images are present (that happens even though it is against the rules), choose the one with the highest Wikibase rank.

**Comment by vanshikaarora** [comment]
@nicolas-raoul I have fixed the issue [here](https://github.com/commons-app/apps-android-commons/pull/2970/commits/bcd457722efe69780366f61f2f3148549577e29e).

Please check :-)

### Preview
![Screenshot_20190806_135217](https://user-images.githubusercontent.com/34261945/62523652-e2e48680-b851-11e9-810f-ccde3dbb3950.png)

**Comment by nicolas-raoul** [comment]
in my tests it shows the same thumbnail several times.

2019年8月6日(火) 17:26 Vanshika Arora <notifications@github.com>:

**Comment by vanshikaarora** [comment]
@nicolas-raoul are you on the latest commit?

**Comment by nicolas-raoul** [comment]
@vanshikaarora Yes, latest commit bcd457722

**Comment by nicolas-raoul** [comment]
![adb-screenshot](https://user-images.githubusercontent.com/99590/62549244-1bf91700-b8a3-11e9-9075-fcd2b62d1c93.png)

**Comment by nicolas-raoul** [comment]
Also, would you mind making the thumbnails a bit larger, maybe something like 70 pixels? :-)

**Comment by vanshikaarora** [comment]
Sure :-)

**Comment by ashishkumar468** [comment]
Also, ux wise, shall we add a placeholder image for even those items who do not have the images the ui looks a little zig-zaggy, and would be nice to add a very light colored divider, what do you say @nicolas-raoul  ?

**Comment by vanshikaarora** [comment]
> @vanshikaarora Yes, latest commit [bcd4577](https://github.com/commons-app/apps-android-commons/commit/bcd457722efe69780366f61f2f3148549577e29e)

Oh then I guess all of them have same label hence same value of url like
```
https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Guion_Bluford.jpg/50px-Guion_Bluford.jpg
```

**Comment by nicolas-raoul** [comment]
Yes, a placeholder based on this image would make the list more coherent and beautiful: https://commons.wikimedia.org/wiki/File:Wikidata-logo.svg

**Comment by nicolas-raoul** [comment]
The thumbnail should be retrieved using the Wikidata QID, not the label.
In my screenshot above, the first item is Q312 (Apple Computer, Inc) so you must:
1. Get the P18 property of Q312
2. Retrieve the thumbnail of that P18 URL

**Comment by vanshikaarora** [comment]
I have added this placeholder https://commons.wikimedia.org/wiki/File:Wikidata-logo.svg

**Comment by nicolas-raoul** [comment]
With the latest commit, here is what I see for a search on "apple":
![adb-screenshot](https://user-images.githubusercontent.com/99590/62988808-a7b10b80-be80-11e9-9083-061fdf63f54b.png)

**Comment by nicolas-raoul** [comment]
Also, during upload:
![adb-screenshot1](https://user-images.githubusercontent.com/99590/62990561-6c660b00-be87-11e9-832e-74f4305c945f.png)
![adb-screenshot](https://user-images.githubusercontent.com/99590/62990563-6f60fb80-be87-11e9-903b-655d1f9801cd.png)

**Comment by nicolas-raoul** [comment]
Also getting wrong thumbnail during upload (using latest commit):
![Screenshot_20190819-182252_Commons](https://user-images.githubusercontent.com/99590/63255068-d7f90f80-c2af-11e9-9094-ab28e4de988a.jpg)
Here is the thumbnail which should appear: https://www.wikidata.org/wiki/Q843426

**Comment by nicolas-raoul** [comment]
Implemented by @vanshikaarora 
I have created two issues for the small bugs I have found, but we can close this main issue :-)
