### ISSUE TITLE
Depiction search: loading forever

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#3107]
1. Search for "bow"
2. One result gets displayed

Problem: The "loading" wheel never disappears

Maybe when there are several images it is simply hidden by the pictures?
![adb-screenshot](https://user-images.githubusercontent.com/99590/62347587-2929a500-b535-11e9-968d-cff9566b3e11.png)

**Comment by vanshikaarora** [comment]
Solved the issue [here](https://github.com/commons-app/apps-android-commons/pull/2970/commits/46978b485b5b27d3d4131157510a5adaf5de8074)

**Comment by nicolas-raoul** [comment]
It works, thanks! :-)
