### ISSUE TITLE
Wikidata items label/description not localized

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#3108]
Problem: Despite locale being Japanese, the label and description for "apple" are shown in English:
![adb-screenshot](https://user-images.githubusercontent.com/99590/62352128-5e88bf80-b542-11e9-9095-91003245c742.png)
Despite the "apple" item https://www.wikidata.org/wiki/Q89 having a label and description in Japanese:
![Screenshot from 2019-08-02 16-26-07](https://user-images.githubusercontent.com/99590/62352110-54ff5780-b542-11e9-936e-fc3f2ffa306a.png)

**Comment by vanshikaarora** [comment]
Solved the issue [here](https://github.com/commons-app/apps-android-commons/pull/2970/commits/46978b485b5b27d3d4131157510a5adaf5de8074)
