### ISSUE TITLE
Depiction added every time I switch and come back to the Commons app

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#3110]
1. Open Commons app
2. Tap a picture that has a depiction
3. Switch to another app, for instance a web browser
4. Switch back to Commons
5. Depictions are doubled

After two app switches:
![adb-screenshot](https://user-images.githubusercontent.com/99590/62367290-2abe9180-b564-11e9-861c-7f17c1c0b36a.png)

**Comment by vanshikaarora** [comment]
Fixed [here](https://github.com/commons-app/apps-android-commons/pull/2970/commits/ee2b7befe47e4d70269327157d3c19c2f2814829)

**Comment by nicolas-raoul** [comment]
Fixed, thanks!
