### ISSUE TITLE
Move depictions section to just above categories section (media details)

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#3112]
Currently, depictions are just below caption and title.
Let's put them be a bit lower: In the same group as categories, just above categories.
It is the most logical place for them.

**Comment by vanshikaarora** [comment]
Fixed [here](https://github.com/commons-app/apps-android-commons/pull/2970/commits/ee2b7befe47e4d70269327157d3c19c2f2814829)

**Comment by nicolas-raoul** [comment]
Thanks for fixing! :-)
