### ISSUE TITLE
Tapping a depiction in media details should open search on that depiction

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#3113]
In media details, if you tap on a category, the app will show all media in that category.

Similarly: In media details, if you tap on a depiction, the app will show all media in that depict the same item.

Right now, the app opens the Wikidata page of the item, which is better than nothing, but I think that the behavior above would be preferable now that depiction search works well :-)

**Comment by vanshikaarora** [comment]
@nicolas-raoul I have fixed this issue [here](https://github.com/commons-app/apps-android-commons/pull/2970/commits/c22762b5cfc3dc7ec476e862b17661eeb77106c1)

**Comment by nicolas-raoul** [comment]
Thanks, it works for media details from Home.

However, after you open an image found with depiction search, clicking on one of its depictions in media details does not do anything

Example: Search for "warehouse" depiction, open "Godorf station at dusk, May 2018", tap "rail".

**Comment by vanshikaarora** [comment]
Thanks for the finding, I'll look into the issue again :-)

**Comment by vanshikaarora** [comment]
@nicolas-raoul I have resolved the issue [here](https://github.com/commons-app/apps-android-commons/pull/2970/commits/1607bd9515f76cc8c81f79e3187b3f2f5c94ce62)

**Comment by nicolas-raoul** [comment]
Great that works now :-)
