### ISSUE TITLE
Character ` appearing in media details

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#3117]
_(on Vanshika's upload_caption_depict branch, but most probably elsewhere too)_
The label should be `議論` only but somehow a random ` character appears to be prepended.
![Screenshot_20190806-002603_Commons](https://user-images.githubusercontent.com/99590/62509871-d3604000-b847-11e9-9ed4-6327049ab78c.jpg)
![Screenshot from 2019-08-06 12-45-11](https://user-images.githubusercontent.com/99590/62509913-17ebdb80-b848-11e9-89b7-59024a095910.png)

**Comment by BhuvanaGN** [comment]
will work on it

**Comment by nicolas-raoul** [comment]
@BhuvanaGN Are you still working on it?

**Comment by vvijayalakshmi21** [comment]
Hi, Kindly let me know how to reproduce this bug?
I tried going to the 'Explore' tab (using the latest app on Google Play Store) but I did not know how to see this issue?
Do I have to change any settings to the language seen in the issue?

**Comment by nicolas-raoul** [comment]
You have to change Android's language to Japanese.
Only for Japanese I guess.

**Comment by vvijayalakshmi21** [comment]
I just checked this on the latest version of the app in Google store on my Google Pixel 3a Phone with Android version 10. I could not see the extra character 
Is this issue particular to any specific branch?
![Screenshot_20200330-112900](https://user-images.githubusercontent.com/34595292/77880342-0e254700-7222-11ea-86f5-bff43856bdfb.png)

**Comment by nicolas-raoul** [comment]
Oh, I guess it has been fixed.
Thanks you for checking! :-)

**Comment by vvijayalakshmi21** [comment]
Is there another beginner-friendly issue I could take up?

**Comment by nicolas-raoul** [comment]
@vvijayalakshmi21 Sorry for the delay, would you mind working on https://github.com/commons-app/apps-android-commons/issues/3526 ? It is on the "structured-data" branch. Thanks!

**Comment by misaochan** [comment]
@vvijayalakshmi21 If you have time, #3584 on `structured-data` would be good too. :)
