### ISSUE TITLE
"No depiction found" despite some found

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#3118]
I think that happens when typing some random string then correcting. The red message does not disappear.
![Screenshot_20190804-194238_Commons](https://user-images.githubusercontent.com/99590/62510511-30f58c00-b84a-11e9-8144-b21bc9634cc1.jpg)

This also happens for categories: https://github.com/commons-app/apps-android-commons/issues/2236

**Comment by vanshikaarora** [comment]
@nicolas-raoul I have solved this issue [here](https://github.com/commons-app/apps-android-commons/pull/2970/commits/f3389a507ca152bbaa1da040b98acc3322d2b0ca).

Please check :)

**Comment by nicolas-raoul** [comment]
It works now, thanks :-)
