### ISSUE TITLE
"Back" button exits the app after tapping media details depiction

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#3119]
1. Find any image that has a "depiction"
2. Tap the depiction in the media details
3. You are now in a search that shows all images that depict the same thing
4. Press "Back"

Expected: Go back to the media details
Actually: The app is closed

**Comment by vanshikaarora** [comment]
@nicolas-raoul I have resolved the issue [here](https://github.com/commons-app/apps-android-commons/pull/2970/commits/3370b11bf4ff8333a28e2ef0b61e3194730c0045)

Please check :-)

**Comment by nicolas-raoul** [comment]
That's fixed, thanks :-)
