### ISSUE TITLE
Suggest categories based on depictions

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#3120]
In the Upload activity, after the user inputs that her picture depicts an [elephant](https://www.wikidata.org/wiki/Q7378), in the next screen (category selection) we should append to the list of suggested categories, the category associated with that Wikidata item.

https://www.wikidata.org/wiki/Q7378 -> Retrieve the P373 (Commons category) property -> Suggest https://commons.wikimedia.org/wiki/Category:Elephants

If the user has selected several Wikidata items, the corresponding categories should all be suggested.

**Comment by macgills** [comment]
This is ridiculously difficult to do with how the reactive streams are configured. I am switching off of this for now and may first create a ticket to rewrite this particular Rx flow before implementing this new suggestion stream, whenever I circle around
