### ISSUE TITLE
The app category autosuggest suggest categories including Disambiguation

### ISSUE THREAD

**Issue by Aktron** [commons-app/apps-android-commons#3123]
**Summary:** 

When you upload an image of a street or something else of an non-Unique name, it suggests a generic category that serves usually for a Dsambiguation

**Steps to reproduce:** 

Take a picture of something that has a category with a generic name

**System logs:**

N/A

**Device and Android version:** 

AGM A8 Android 7.1
 
**Commons app version:** 

AGM A8 2.10.2

**Screen-shots:** 

N/A

**Would you like to work on the issue?**

Just add "if category contains {{disambig}} then do not suggest for an user.

**Comment by Rishavgupta12345** [comment]
@nicolas-raoul I think this issue is not valid so we can close this

**Comment by nicolas-raoul** [comment]
Indeed I have not seen any disambiguation category suggested, recently.

@Aktron If you find a disambiguation category being suggested, would you mind telling us which one exactly, so that we can reproduce the issue? Thanks!
