### ISSUE TITLE
Clean up all string literals in code and replace them with string resources

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#3129]
Subtask of #1092 

Clean up all string literals in code and replace them with string resources, to better take advantage of TranslateWiki translations. (Fairly simple task)

**Comment by RozaliyaRusskikh** [comment]
Hi there! I'm a beginner and I'm eager to contribute to this project. Could I take this issue?

**Comment by nicolas-raoul** [comment]
@RozaliyaRusskikh Yes, it is yours!
Please let us know about your progress :-)

**Comment by RozaliyaRusskikh** [comment]
Thank you! I am starting right now and I will create PR as soon as possible  :)

**Comment by misaochan** [comment]
Welcome aboard, @RozaliyaRusskikh ! Let us know if you need any help. :)

**Comment by RozaliyaRusskikh** [comment]
Hello! Unfortunately I do not have enough time to work on this issue. So the issue can be reassigned.

**Comment by PavelAplevich** [comment]
@misaochan I think, all done. You can close this issue

**Comment by misaochan** [comment]
Thanks @PavelAplevich !
