### ISSUE TITLE
Tapping a depiction in media details sometimes does nothing

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#3130]
In media details, if you tap on a depiction, the app will show all media in that depict the same item.

It works most of the time, but not always, strangely.

- In your home activity, tap a picture to which you have added depictions
- Tap on a depiction. The explore activity opens, showing all media with that depiction. That's great.
- Tap an image in that list
- In the media details, tap a depiction. This time tapping does not do anything, that's the problem.

**Comment by vanshikaarora** [comment]
@nicolas-raoul I have resolved the issue [here](https://github.com/commons-app/apps-android-commons/pull/2970/commits/e778de4ff1b9fc1da501e62ba9ef914bd88e3be8).

Please check :-)

**Comment by nicolas-raoul** [comment]
It works now, thanks for fixing :-)
