### ISSUE TITLE
Text when no parent/child class

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#3132]
Currently: "No Wikidata items matching XYZ found"
Better text: "XYZ has no child classes"

Similarly: "XYZ has no parent classes"

**Comment by vanshikaarora** [comment]
@nicolas-raoul I have fixed the issue [here](https://github.com/vanshikaarora/apps-android-commons/commit/2ec7823d4c397328088e111c94fa10bf1eeafa83)

Please check :-)

**Comment by nicolas-raoul** [comment]
It works great now! Thanks for fixing :-)
