### ISSUE TITLE
Global metrics (for IEG final report)

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#3139]
I'm working on the required global metrics for our IEG renewal's final report -https://meta.wikimedia.org/wiki/Grants:IEG/Improve_%27Upload_to_Commons%27_Android_App/Renewal/Final#Global_Metrics . Looking at the [previous grant](https://meta.wikimedia.org/wiki/Grants:IEG/Improve_%27Upload_to_Commons%27_Android_App/Final), it seems like we only needed to fill in 3 of the 6 metrics.

2. Number of new editors - this was previously calculated by https://quarry.wmflabs.org/query/18084 , but it fails to work any more, with the error
Unknown column 'log_user_text' in 'field list'

3. Number of individuals involved - we previously used https://tools.wmflabs.org/ptools/uploadersincat.php?category=Uploaded_with_Mobile%2FAndroid_%28Jul_2016_-_Jun_2017%29 for this but it depends on creating a new category for the relevant timespan and using a bot to populate it if I recall correctly?

4. Number of new images/media added to Wikimedia articles/pages - this depends on the same category as number 3.

@VojtechDostal @urbanecm or @nicolas-raoul , would it be possible to get your help with this? The timespan we would be needing is Nov 2017 to Aug 2019. Thanks so much! :)

**Comment by urbanecm** [comment]
> Number of new editors - this was previously calculated by https://quarry.wmflabs.org/query/18084 , but it fails to work any more, with the error Unknown column 'log_user_text' in 'field list'

That's because of a schema change in MediaWiki. https://quarry.wmflabs.org/query/38568 should give the same data as https://quarry.wmflabs.org/query/18084.

> Number of individuals involved - we previously used https://tools.wmflabs.org/ptools/uploadersincat.php?category=Uploaded_with_Mobile%2FAndroid_%28Jul_2016_-_Jun_2017%29 for this but it depends on creating a new category for the relevant timespan and using a bot to populate it if I recall correctly?

Yeah, you're right. Going to get the script I used to add the category, and add it again. If you have a github link to an issue where we solved it last year, it might help.

**Comment by urbanecm** [comment]
Nvm, found it, it's #696. Going to use the last year query, and this time I added it to commonsmisc repository, so I don't find it too long next year :).

**Comment by misaochan** [comment]
@urbanecm Thanks so much for your help! How long should we wait for the category to be ready?

A few odd things about the "number of new editors" stat:
- https://quarry.wmflabs.org/query/38568 gives us 195907 users. I would be thrilled if that were true, but that actually exceeds our total app downloads. It's not implausible that people would be creating multiple accounts, but also the `is_mobile` column is showing as 0 for everyone. Do you think there might be an issue with the filter?
- https://quarry.wmflabs.org/query/18084 now works, for some reason... and it does actually produce some '1's in the `is_mobile` column.

**Comment by urbanecm** [comment]
I'm so sorry, I forgot about this totally. Feel free to ping me if you don't hear a response in reasonable time :P. I've tried to create https://quarry.wmflabs.org/query/38955, which hopefully will "solve" the issue for this timebeing. 

https://quarry.wmflabs.org/query/18084 doesn't work, it last executed on "Fri May 18 2018", long before the breaking schema change. 

Ad the category, could you spot check https://people.wikimedia.org/~urbanecm/commons-app-ieg-2019/pages-20190914.txt please? It's the result of my query, hopefully, it's all good, but 50k looks like a lot of images...

**Comment by urbanecm** [comment]
@misaochan Ping? Could you check the above?

**Comment by misaochan** [comment]
Hey @urbanecm , sorry for the slow response, I just got back from vacation a few days ago and had a huge backlog. :)

> Ad the category, could you spot check https://people.wikimedia.org/~urbanecm/commons-app-ieg-2019/pages-20190914.txt please? It's the result of my query, hopefully, it's all good, but 50k looks like a lot of images...

I spot-checked 10 of those, and they all appear to be correct! Thanks so much! 

> I've tried to create https://quarry.wmflabs.org/query/38955, which hopefully will "solve" the issue for this timebeing.

This one doesn't look right to me for number of new editors, it has 200k+ rows, and is_mobile is 0 for all of them?

**Comment by urbanecm** [comment]
> Hey @urbanecm , sorry for the slow response, I just got back from vacation a few days ago and had a huge backlog. :)
> 
> > Ad the category, could you spot check https://people.wikimedia.org/~urbanecm/commons-app-ieg-2019/pages-20190914.txt please? It's the result of my query, hopefully, it's all good, but 50k looks like a lot of images...
> 
> I spot-checked 10 of those, and they all appear to be correct! Thanks so much!

Cool! I've started a bot to fill https://commons.wikimedia.org/wiki/Category:Uploaded_with_Mobile/Android_(Nov_2017-Aug_2019) from that list then :). 

> 
> > I've tried to create https://quarry.wmflabs.org/query/38955, which hopefully will "solve" the issue for this timebeing.
> 
> This one doesn't look right to me for number of new editors, it has 200k+ rows, and is_mobile is 0 for all of them?

That might be because there was `user_registration > "20180101000000"`.

**Comment by misaochan** [comment]
> Cool! I've started a bot to fill https://commons.wikimedia.org/wiki/Category:Uploaded_with_Mobile/Android_(Nov_2017-Aug_2019) from that list then :).

@urbanecm Awesome, thank you! Has the bot already completed, i.e. https://commons.wikimedia.org/wiki/Category:Uploaded_with_Mobile/Android_(Nov_2017-Aug_2019) can now be used for stats?

> That might be because there was user_registration > "20180101000000".

Hmm. I checked the new query with user_registration > "20190101000000", but it still seems wrong. For instance [Booktab pub](https://commons.wikimedia.org/w/index.php?limit=50&title=Special%3AContributions&target=Booktab+pub&namespace=&tagfilter=&start=&end=)'s first upload was a cross-wiki upload and [Deep Lane](https://commons.wikimedia.org/w/index.php?limit=50&title=Special%3AContributions&target=Deep+Lane&namespace=&tagfilter=&start=&end=)'s first upload was via Upload Wizard.

**Comment by urbanecm** [comment]
The bot completed, but it seems to missed ~100 pages. The missing pages should be added soon. 

Ad the query, maybe the simplest thing would be to write it from scratch. What results it should have? I'll try to write a query for that soon-ish!

**Comment by misaochan** [comment]
> What results it should have? I'll try to write a query for that soon-ish!

I think we would want the number of users whose first contribution to Commons was via mobile app, from Nov 2017 to Aug 2019.

**Comment by misaochan** [comment]
> I think we would want the number of users whose first contribution to Commons was via mobile app, from Nov 2017 to Aug 2019.

Hey @urbanecm , just pinging as requested. :) 

Also, I guess https://commons.wikimedia.org/wiki/Category:Uploaded_with_Mobile/Android_(Nov_2017-Aug_2019) is ready to use now?

Thanks again!

**Comment by urbanecm** [comment]
Yes, the category should be ready now. Sorry for writing so late, almost all of my attention was given to conference I organized, so I didn't think much about this one. What about https://quarry.wmflabs.org/query/40268 - it should have only users with first upload using your app.

**Comment by urbanecm** [comment]
With the help of few other folks, here is an optimalized version of the query that finishes in time: https://quarry.wmflabs.org/query/40273, but across all users (not necessarily registered in the timeframe you specified), https://quarry.wmflabs.org/query/40278 _might_ have the filtering, but made on date of first upload, not date of registration (that can differ).

**Comment by misaochan** [comment]
https://quarry.wmflabs.org/query/40278 works perfectly for me, and date of first upload is fine! Thanks so much for your help @urbanecm . :)

**Comment by maskaravivek** [comment]
Closing this issue as our final report has been submitted.
