### ISSUE TITLE
Image appearing twice in search

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#3142]
When I search for "aburasoba azabujuban", [this image](https://commons.wikimedia.org/wiki/File:Tantanmen.jpeg) appears twice. Maybe because it has captions? I haven't tried in master though.
![Screenshot from 2019-08-26 09-03-29](https://user-images.githubusercontent.com/99590/63657819-846f5000-c7e0-11e9-997c-8bcbf3639874.png)

**Comment by RenatoViana01** [comment]
Can I work on this?

**Comment by ashishkumar468** [comment]
Sure @RenatoViana01 . Please keep us posted about the progress :)

**Comment by RenatoViana01** [comment]
@ashishkumar468 do you guys have a slack?

**Comment by RenatoViana01** [comment]
@ ashishkumar468 this seems to be an API problem.

**Comment by nicolas-raoul** [comment]
> do you guys have a slack?

We often use Zulip and Hangout. But talking on GitHub issues has the advantage that people coming afterwards can see all of the information.

**Comment by ashishkumar468** [comment]
@RenatoViana01  as @nicolas-raoul  We use github threads to discuss the issue, that way we also get to keep track of our conversations. Also, Have you seen the response, are we getting the same entry multiple times.

**Comment by nicolas-raoul** [comment]
@RenatoViana01 Could you please post the API request (preferably as a curl command line) and the resulting erroneous response? Thanks :-)

**Comment by RenatoViana01** [comment]
I was away this weekend, will get on it now :)

**Comment by RenatoViana01** [comment]
I was trying to get it with the network profiler and now I can't even reproduce the issue, it just gives me no images matching. Other queries work fine.
<img width="274" alt="Screenshot 2019-09-19 at 16 33 19" src="https://user-images.githubusercontent.com/12497487/65258718-4a514f80-dafb-11e9-8841-890034f4388f.png">

**Comment by nicolas-raoul** [comment]
Seems fixed now :-)
