### ISSUE TITLE
Possible SecurityException if user doesn't provide access to AccountManager

### ISSUE THREAD

**Issue by anirudh24seven** [commons-app/apps-android-commons#317]
![lintpermissionsecurityexception](https://cloud.githubusercontent.com/assets/617443/19845378/51fd0630-9f5c-11e6-843e-d9b1524482da.PNG)

Related to #316

**Comment by misaochan** [comment]
Hm, my second comment at #318 probably belongs here.

**Comment by domdomegg** [comment]
See [#318#257490267](https://github.com/commons-app/apps-android-commons/pull/318#issuecomment-257490267)
