### ISSUE TITLE
Travis failing on master

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#3188]
Execution failed for task ':app:mergeBetaDebugResources'.
> /home/travis/build/commons-app/apps-android-commons/app/src/main/res/values-tt-cyrl: Error: Invalid resource directory name

**Comment by yashk2000** [comment]
@misaochan renaming the file to `values-b+tt+Cyrl` fixes the error. Should I rename the file accordingly and send a pr?

**Comment by yashk2000** [comment]
@misaochan renaming the file to `values-b+tt+Cyrl` does not cause the error to occur on my laptop. Should I rename the file accordingly and send a pr?

**Comment by misaochan** [comment]
Sounds good to me, thanks. :)

**Comment by yashk2000** [comment]
On it.

**Comment by neslihanturan** [comment]
Travis fails with same reason:
```
* What went wrong:

Execution failed for task ':app:mergeProdReleaseResources'.

> /home/travis/build/commons-app/apps-android-commons/app/src/main/res/values-tt-cyrl: Error: Invalid resource directory name
```

**Comment by yashk2000** [comment]
@neslihanturan @misaochan this happened because this file was added by localization updates from translatewiki again. 
I don't know how to prevent that from happening.

Maybe we could update the travis.yml so that if this file is found, it should be renamed to `values-b+tt-Cyrl`. Could you please tell if this should be done?

**Comment by maskaravivek** [comment]
@misaochan Do you know how translate wiki is able to merge commits directly to master? Is there some kind of pipeline set up for it. Maybe we can change it so that pull requests are created instead of direct commits.

**Comment by nicolas-raoul** [comment]
I am sure the rename can be performed automatically via Translatewiki
configuration. We already do something similar for other languages.

**Comment by yashk2000** [comment]
@nicolas-raoul could you please provide some guidance as to how to do that?

**Comment by misaochan** [comment]
Pinging @Nikerabbit for input on this.

**Comment by maskaravivek** [comment]
I had a chat with @Nikerabbit during the tech conference, and it seems that translate wiki doesn't support pull requests yet.

**Comment by nicolas-raoul** [comment]
@yashk2000 I am not sure to understand exactly how but we usually fix such problems with a magic line here: https://phabricator.wikimedia.org/diffusion/GTWN/browse/master/groups/Wikimedia/CommonsAndroid.yaml$10

**Comment by yashk2000** [comment]
@nicolas-raoul thanks for providing the link. I'll send a patch with the correct name for `tt-cyrl` to the CommonsAndoird.yaml in the phabricator.

**Comment by misaochan** [comment]
Any updates on this please? :) We have to keep fixing the build manually recently.

**Comment by yashk2000** [comment]
@nicolas-raoul @misaochan patch sent to translatewiki.
https://gerrit.wikimedia.org/r/#/c/translatewiki/+/553461/
please review it and tell me if any changes are needed.

**Comment by yashk2000** [comment]
@misaochan @nicolas-raoul @neslihanturan I think this issue has been resolved for now. The build is passing now.

**Comment by misaochan** [comment]
Thanks @yashk2000 !
