### ISSUE TITLE
Make the username along with the rewards icon clickable in the Navigation Drawer

### ISSUE THREAD

**Issue by yashk2000** [commons-app/apps-android-commons#3191]
**Summary:** 

Make the username along with the rewards icon clickable in the Navigation Drawer

**Steps to reproduce:** 

How can we reproduce the issue? 
What did you expect the app to do, and what did you see instead?

- Open the app's Navigation Drawer.
- See the username and the trophy icon.
- The trophy icon doesn't appear to be clickable at first glance. 
- Make the username also clickable as generally clicking the user name open a user's profile in any application.

**Commons app version:** 

2.11.0-debug-master

**Would you like to work on the issue?**

Opening this as a GCI issue.

**Comment by yashk2000** [comment]
@misaochan @neslihanturan @ashishkumar468 could you please provide your views on this? Is it fine for a GCI issue?

**Comment by ashishkumar468** [comment]
Hi @yashk2000. Not sure about this in terms of GCI, but IMO, the feature looks fine to me. It would be nice to have the entire area clickable.

**Comment by yashk2000** [comment]
@ashishkumar468 @neslihanturan I have a few more ideas for GCI tasks, but I want to discuss them with you before I create the tasks. So should I just open issues over here, or should I send a list of all my ideas to the mailing list?

**Comment by neslihanturan** [comment]
I agree this one is not for GCI but would be lovely to have, thanks.

**Comment by yashk2000** [comment]
I'm taking up this issue since it hasn't been resolved yet.
