### ISSUE TITLE
Improve the share message of the app

### ISSUE THREAD

**Issue by yashk2000** [commons-app/apps-android-commons#3192]
**Summary:** 

Improve the share message of the app

**Steps to reproduce:** 

- Enter the about activity.
- Click the share icon.
- The message sent on sharing the app can be improved a bit by adding some punctuations. 

**Commons app version:** 

2.11.0-debug-master

**Would you like to work on the issue?**

Opening this issue for GCI.

**Comment by yashk2000** [comment]
@misaochan @neslihanturan @ashishkumar468 could you please provide your views on this? Is it fine for a GCI issue?

**Comment by neslihanturan** [comment]
Hi @yashk2000 , would you mind sharing GCI task specifications etc.? I am not sure if this issue is really needed. What punctuation do you want to change? Can you provide current and updated strings?

**Comment by yashk2000** [comment]
@neslihanturan the current share message is this:
`Upload photos to Wikimedia Commons on your phone Download the Commons app: https://play.google.com/store/apps/details?id=fr.free.nrw.commons`

It's missing the punctuation over here `on your phone Download`. It also seems to be a bit too dull in my opinion. I was thinking of adding the punctuation and making the message as follows:
`Upload photos to the Wikimedia Commons directly from your phone. Download the Commons App now: https://play.google.com/store/apps/details?id=fr.free.nrw.commons`

**Comment by neslihanturan** [comment]
Oh okay, a native speaker it better to share their idea here:) Let's wait for someone else join the conversation.

**Comment by yashk2000** [comment]
@neslihanturan I have a few more ideas for GCI tasks, but I want to discuss them with the maintainers before I create the tasks. So should I just open issues over here, or should I send a list of all my ideas to the mailing list?

**Comment by neslihanturan** [comment]
Creating issues seems to better to me. You can create a label and add it to your issues like "GCI ideas"

**Comment by nicolas-raoul** [comment]
I agree with Neslihan's comment above.
Then please add GCI tasks for each issue we have set labels for.
Thanks a lot :-)

**Comment by yashk2000** [comment]
@nicolas-raoul I should add GCI tasks for each issue with the label `good first issue`?

**Comment by yashk2000** [comment]
@nicolas-raoul @neslihanturan I should add GCI tasks for each issue with the label good first issue?

**Comment by shash137** [comment]
Hello @yashk2000 , @neslihanturan , @nicolas-raoul , @ashishkumar468  I'm new to the community and I would like to resolve this.

**Comment by ashishkumar468** [comment]
Sure @shash137. Please let us know what changed do you intend to make to resolve this issue?

**Comment by shash137** [comment]
@ashishkumar468  I've changed the current share message:
`Upload photos to Wikimedia Commons on your phone Download the Commons app: https://play.google.com/store/apps/details?id=fr.free.nrw.commons`
to 
`Upload photos to the Wikimedia Commons directly from your phone. Download the Commons App now: https://play.google.com/store/apps/details?id=fr.free.nrw.commons`

**Comment by ashishkumar468** [comment]
LGTM, good to go if one of @neslihanturan, @maskaravivek @nicolas-raoul  @misaochan  confirms.

**Comment by yashk2000** [comment]
@ashishkumar0207 @shash137 this is a GCI issue. We have created a task for it in the GCI dashboard too. 

We should wait till 2nd December when GCI starts and assign it to a GCI student.

**Comment by ashishkumar468** [comment]
Thanks, @yashk2000, I did not know @shash137  was not picking this up as a part of the GCI task. @shash137, as @yashk2000 said this is a GCI task and only those associated with GCI can be assigned this task.

**Comment by shash137** [comment]
@ashishkumar468 , @yashk2000  i don't know about GCI please tell me.
But I was told in the zulip to contribute in the issues under "good first issues" tag.

**Comment by nicolas-raoul** [comment]
Sorry, adding that tag was my mistake.
Let's add this tag again on such issues if they are not solved after CGI.

**Comment by shash137** [comment]
What is CGI @nicolas-raoul  if can ask?

**Comment by shash137** [comment]
@nicolas-raoul  okay so I don't have to solve issues under GCI.

**Comment by zoranzoki21** [comment]
This should be closed as resolved now, as my pull request is merged.

**Comment by nicolas-raoul** [comment]
@zoranzoki21 Thanks for fixing this :-)
@yashk2000 Thanks for filing the issue!
