### ISSUE TITLE
Ordering problem at contributions list when same file name is used

### ISSUE THREAD

**Issue by neslihanturan** [commons-app/apps-android-commons#3195]
**Summary:** 
We expect that contributions list add latest item to top. But when we used same filenames, the last one appears on the bottom, see the screenshots:

**Steps to reproduce:** 
Add files with same file name

**Device and Android version:** 

 API 21 Emulator
 
**Commons app version:** 

Current master, beta debug

**Screen-shots:** 

![image](https://user-images.githubusercontent.com/3127881/68288219-11623f80-0095-11ea-8807-d24fd47304ed.png)

![image](https://user-images.githubusercontent.com/3127881/68288249-1d4e0180-0095-11ea-9427-cd3cf6ad2003.png)

**Comment by DeepaMalani** [comment]
Hi, Neslihanturan,

I tried to reproduce issue #3195 on the same device which you specified(Emulator Api 21) but it's working fine, which means a new image with the same file name added to the top.

Here is screen shots
<img width="257" alt="issue_3195" src="https://user-images.githubusercontent.com/24900514/68498144-003b3f00-020b-11ea-8706-3e33fef1fb2c.PNG">

Could you please suggest me is there any other way to reproduce it?

**Comment by neslihanturan** [comment]
I will try to reproduce it as soon as possible @DeepaMalani , thanks a lot.

**Comment by isnirp** [comment]
I noticed latest item isn't placed at the top until pull-refresh. If this issue is still standing I can have a look at it @nicolas-raoul

**Comment by nicolas-raoul** [comment]
@isnirp Thanks for testing! Actually it seems that the situation has worsened recently, the order is messed up independently from file name. It would be great if you could fix it, thanks! It is yours, please let us know about your progress :-)

**Comment by isnirp** [comment]
@nicolas-raoul thanks I'll keep you updated

**Comment by isnirp** [comment]
hello @nicolas-raoul I introduced a comparator<Contribution> for sorting based on the datecreated. This helped with the ordering. I pushed to my fork, if you may review...
