### ISSUE TITLE
The xml files contain a lot of hardcoded dimensions

### ISSUE THREAD

**Issue by yashk2000** [commons-app/apps-android-commons#3197]
**Summary:** 

The xml files contain a lot of hardcoded dimensions
 
**More Information**

Currently, a lot of the layout files contain hardcoded dimension values as layout_width, layout_height, padding, etc. Instead of being hardcoded, these values should be a part of the dimens.xml file from which they should be accessed each time needed. The same should be done for text size which is currently hardcoded in a lot of places. 

**Commons app version:** 

2.11.0-debug-master

**Would you like to work on the issue?**

Opening for GCI.

**Comment by yashk2000** [comment]
@neslihanturan @ashishkumar468 @nicolas-raoul please provide your views on this issue for GCI.

**Comment by ashishkumar468** [comment]
Hi @yashk2000  Can you provide specific examples for the same ?

**Comment by yashk2000** [comment]
@ashishkumar468 Some files where I noticed these issues are:
- welcome_final.xml
- activity_notification.xml
- activity_quiz.xml
- bottom_sheet_nearby.xml

These are just few of the files. I think whoever takes up this issue will have to go through all the layouts and see if this issue exists in them.

**Comment by neslihanturan** [comment]
@yashk2000 we are not sure about the scope of a GCI issue. We don't know how hard it should be etc. Can you provide us a document about which issues can be accepted as an GCI issue. "Ie. issues which can be done in 1 day for experienced developer and 7 days for a newbie."

**Comment by nicolas-raoul** [comment]
It is a rather hard CGI task, but still OK I think.
In the instructions, be sure to link to https://github.com/commons-app/apps-android-commons/wiki/Quick-start-guide-for-Developers

**Comment by yashk2000** [comment]
@neslihanturan the minimum time for completing a GCi task is 3 days. We cannot set the time for completing a task in less than 3 days.

Here is a list of some sample tasks: https://developers.google.com/open-source/gci/resources/example-tasks

As far as I could make out, we should make tasks that are not very tough for beginners to figure out by using online resources. I saw some other GCI tasks too created by other GCI mentors in Wikimedia. Those issues also seem to be simple issues with minor code changes that can be figured out easily.

**Comment by neslihanturan** [comment]
After reading the info at the link, I think punctuation fixes can not be accepted as GCI task, on the other hand fixin hard coded variables in xmls can be a task.

**Comment by yashk2000** [comment]
@neslihanturan while punctuation fixes aren't a very high-level task, but I think it will be acceptable to help someone get started. 
The tasks given in the link are only some of the tasks which were taken by last year's winners. I think we can keep the punctuation fix as a beginner level task.

**Comment by urbanecm** [comment]
Published as https://codein.withgoogle.com/tasks/6173151566757888/ (or https://codein.withgoogle.com/dashboard/tasks/6173151566757888/ for GCI-recognized mentors)

**Comment by m-alzam** [comment]
Working on this (task claimed)

**Comment by yashk2000** [comment]
@m-alzam great :rocket: 
All the best :+1:
Let us know if you have any doubts.

**Comment by m-alzam** [comment]
Pull requests send. @yashk2000 I have [this problem](https://github.com/commons-app/apps-android-commons/pull/3282#issuecomment-562662825).

**Comment by yashk2000** [comment]
@nicolas-raoul this issue also created by me for GCI has not been fixed yet. There is an open pr, but it has some issues. There are some unneeded changes in some files. Should I take it up and fix this minor issue?
