### ISSUE TITLE
[GCI Ideas] Remove unused imports from classes

### ISSUE THREAD

**Issue by yashk2000** [commons-app/apps-android-commons#3201]
**Summary:** 

Currently, some classes contain unused imports. To improve code quality and make the app-building faster, these unused imports should be removed. 

A few files that contain unused imports are:

- SessionManager.java
- BookmarkPicturesController.java
- Bookmark.java
- CacheController.java
- CampaignsPresenter.java

Similarly, go through other classes and remove all unused imports. Unused imports show up in a dull gray color when the file is opened in android studio, unlike used imports which appear in white color.

**Would you like to work on the issue?**

Opening for GCI

**Comment by yashk2000** [comment]
@neslihanturan @ashishkumar468 @nicolas-raoul please tell if this is a good task for GCI.

**Comment by nicolas-raoul** [comment]
good for CGI

**Comment by GearGit** [comment]
Can I work on this issue?

**Comment by GearGit** [comment]
> **Summary:**
> 
> Currently, some classes contain unused imports. To improve code quality and make the app-building faster, these unused imports should be removed.
> 
> A few files that contain unused imports are:
> 
> * SessionManager.java
> * BookmarkPicturesController.java
> * Bookmark.java
> * CacheController.java
> * CampaignsPresenter.java
> 
> Similarly, go through other classes and remove all unused imports. Unused imports show up in a dull gray color when the file is opened in android studio, unlike used imports which appear in white color.
> 
> **Would you like to work on the issue?**
> 
> Opening for GCI

Can I work on this issue?

**Comment by yashk2000** [comment]
@GearGit this is a GCI task. So if you are a GCI student, please wait till December 2nd to officially claim the task and then start working on it. 
If you are not a GCI student, please go for a non-GCI issue :)

**Comment by nicolas-raoul** [comment]
@GearGit Thanks for your comprehension :-)

**Comment by GearGit** [comment]
No problem, I will revisit this issue after 2nd December.

**Comment by m-alzam** [comment]
Working on it

**Comment by yashk2000** [comment]
All the best @m-alzam. Let me know if you face any difficulties.
