### ISSUE TITLE
Review: App crash when rotating the Peer Review screen

### ISSUE THREAD

**Issue by DeepaMalani** [commons-app/apps-android-commons#3203]
**Summary:** 

Summarize your issue in one sentence (what goes wrong, what did you expect to happen)

App is getting crash when I rotate the screen for "Is this correctly categorized?" title.

**Steps to reproduce:** 

How can we reproduce the issue? 
What did you expect the app to do, and what did you see instead?

Steps to reproduce

1. Go to the Navigation Drawer and click on "Review".
2.  Click "seems fine" 2 times for the image.
3. Now "Is this correctly categorized?" title will come.
4. Rotate the screen, app will crash.
 
![Screenshot_2019-11-13-17-43-59](https://user-images.githubusercontent.com/24900514/68792392-1b89be00-0600-11ea-8e4d-ec145f3aa52a.png)
![Screenshot_2019-11-13-17-44-11](https://user-images.githubusercontent.com/24900514/68792396-1fb5db80-0600-11ea-8ebc-3939fe40a114.png)

**Device and Android version:** 

SONY XPERIA Android version 5

 
**Commons app version:** 

2.11.0

**Screen-shots:** 

**Would you like to work on the issue?**

YES

**Comment by neslihanturan** [comment]
Then this is assigned to you @DeepaMalani thanks a lot for reporting.
