### ISSUE TITLE
Reminding for usage of the PR title templates

### ISSUE THREAD

**Issue by neslihanturan** [commons-app/apps-android-commons#3204]
**Summary:** 

As noted in documentations we have templates for pull request titles. sometimes some of us doesnt rely on this template. This is a kind reminder that please make sure you followed templates. Hint:
Fixes #xxxx TITLE OF XXXX so that the reviewer can relate the issue and PR when they are checking from the list.

**Comment by Rishavgupta12345** [comment]
@nicolas-raoul this issue is obsolete so we can close this
