### ISSUE TITLE
Notification when a picture is added to bookmarks.

### ISSUE THREAD

**Issue by chaytanyasinha** [commons-app/apps-android-commons#3207]
Summary:
There is no notification about the bookmarks when they are added.

Steps to reproduce: 
Just go to explore select a picture of your choice then just click on the star in the top right  then it will be added to your bookmarks but there is no notification  about the picture being added to bookmarks.
What did you expect the app to do, and what did you see instead?
App should show an notification about picture being added to bookmarks section and the notification should be shown in bottom.
Device-Samsung S6 Android-8.0
Would you like to work on the issue?
Yes

**Comment by chaytanyasinha** [comment]
@neslihanturan @maskaravivek @ashishkumar468 @nicolas-raoul what you guys say about this issue.

**Comment by nicolas-raoul** [comment]
I don't think we need a notification when adding a bookmark.
If you know any popular app that has this behavior, please let us know.

I will close this issue for now. Thanks for you participation though :-)

**Comment by chaytanyasinha** [comment]
okay @nicolas-raoul

**Comment by chaytanyasinha** [comment]
Well @nicolas-raoul I was talking about an notification like error the message pop up.
![WhatsApp Image 2019-11-03 at 23 50 19](https://user-images.githubusercontent.com/50200796/69214809-f3fd9d00-0b8d-11ea-8f43-e69ae64143dd.jpeg)
