### ISSUE TITLE
Add email verification to the app

### ISSUE THREAD

**Issue by shash137** [commons-app/apps-android-commons#3209]
**Summary:** 

Email verification must be added to the app to avoid anonymous logging in.

_If there is authentication in the app so there must be email verification in the app so as to avoid anonymous log in to the app, this will restrict fake login and will be more safe._

**Steps to reproduce:** 

I think this can be solved by using firebase authentication and email verification. 

**Device and Android version:** 
Device: _Asus ZenFone Max Pro M1_
Android Version: 9
Is it the stock version from the manufacturer or a custom ROM ?
 _Stock version_

**Commons app version:** 
2.11.0~93b948d20

**Screen-shots:** 
In the below screenshots you can see there is no valid email in the mail section and by entering this also a user can log-in to the app.

![Screenshot_20191118-005842](https://user-images.githubusercontent.com/44723604/69012927-dae3c900-09a0-11ea-9ebc-7ccd4bd1726c.png)

![Screenshot_20191111-124703](https://user-images.githubusercontent.com/44723604/69012957-02d32c80-09a1-11ea-9203-cb5e8b7c586b.png)

**Would you like to work on the issue?**

Yes, I would like to work on this issue.

**Comment by shash137** [comment]
@neslihanturan @nicolas-raoul what you guys say about this issue?

**Comment by sivaraam** [comment]
Just chiming in. Commons ([which is a global account for all Wikimedia projects](https://meta.wikimedia.org/wiki/Help:Unified_login)), does not mandate the user to provide an email address.

Regardless, when one provides the email address a verification email is indeed sent to verify the email address. So, I don't understand what's missing here.

**Comment by shash137** [comment]
Yes email verification is said, but I'm saying without verifying email app must not start. I just wanted this, but I think it is not required.
thanks

**Comment by sivaraam** [comment]
Nice suggestion but I think that would make the flow inconsistent with that of the Commons website. So, its better to leave this here. Hope you'll find something better :slightly_smiling_face:

**Comment by nicolas-raoul** [comment]
Yes, I don't think we need additional verification, unless WMF requires it from us for some reason.
I close the issue for now, but feel free to continue the discussion to bring new arguments.
Thanks for participating! :-)

**Comment by shash137** [comment]
Okay thnx for your help @nicolas-raoul and @sivaraam, one more thing earlier I forgot to add when sign in completes there is toast message "Account Created", and there is no message related to email verification, I think it should be like first "Account Created" and then "email verification sent" or we can do it "Account Created and email verification sent!". Is it good @nicolas-raoul and @sivaraam  please check this also for GCI if it is okay/good. 
Thank you
