### ISSUE TITLE
Crash when uploading a picture via Nearby

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#3210]
API level: 28
Android version: 9
Device manufacturer: samsung
Device model: SM-G970F
Device: beyond0
Network type: wifi
App version name: 2.11.0.493 (GitHub commit 8ccad22)

Steps to reproduce:

1. Start Commons app
2. Tap "Nearby"
3. Select any pin
4. Tap the + button
5. Tap gallery
6. Select any picture
7. Crash

Same if tapping camera at step 5

**Comment by IgnacioGarcia198** [comment]
Hello, I would like to fix this bug :)

**Comment by neslihanturan** [comment]
Okay @IgnacioGarcia198 go for it. Please don't hesitate to ask us because this can be a relatively complicated issue.

**Comment by IgnacioGarcia198** [comment]
That is true. I just tried a very easy fix for this issue, my app on my device is not crashing anymore. Although I also changed some version numbers etc in the build.grade files (nothing to do with this issue, just Android Studio always complains about such things) I hope it's not a problem, just let you know.

**Comment by neslihanturan** [comment]
Actually changing build number would be a problem. When you create the pull request please make sure just relevant changes are made. Any extra changes will block your Pr beıng merged.

**Comment by IgnacioGarcia198** [comment]
Hello, there is this directory values-tt-cyrl which is causing an error, may I delete it?
Also should I send the PR on master or on a different branch?
Thanks in advance.

**Comment by maskaravivek** [comment]
As mentioned in #3212, I am reopening this issue until @neslihanturan confirms that this looks to be correct way of fixing the issue. :)

**Comment by nicolas-raoul** [comment]
I just tested, it does not crash anymore :-)

The image is not linked to Wikidata though:
https://commons.wikimedia.org/wiki/File:Queensway_Shopping_Centre.jpg
https://www.wikidata.org/wiki/Q7271124
Should I create a new issue about that?

**Comment by maskaravivek** [comment]
@nicolas-raoul What version of the app are you using? Wikidata edit was fixed just a few hours back(7 hours back) by this commit https://github.com/commons-app/apps-android-commons/commit/891d9ec41ce6b799fa6bc001c48da40074b09e9a.

**Comment by nicolas-raoul** [comment]
@maskaravivek I just tried again with commit 9b15a327c55cb811e7d8ed4d2ffbacc65d821864 (the commit just after your fix), and unfortunately the image is not linked from Wikidata:
https://commons.wikimedia.org/wiki/File:Geylang_Methodist_Secondary_School.jpg
https://www.wikidata.org/wiki/Q5554989

**Comment by misaochan** [comment]
Hi @nicolas-raoul , I'm on alpha currently and https://www.wikidata.org/wiki/Q34814515 works for me. If the current alpha version doesn't work for you, could you send us logs please?

**Comment by neslihanturan** [comment]
Seems like crash is solved:)
