### ISSUE TITLE
Only start image upload after categories have been selected?

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#322]
Currently, categories aren't submitted with the original file but are submitted as a modification later - this is because uploading starts immediately when the picture is selected, whereas categories are selected after that.

There are 2 issues with this:
1) The modification sometimes doesn't go through (see #310 ). A few of my recent uploads, such as https://commons.wikimedia.org/wiki/File:Old_building_near_Beverly_Hills_Park.jpg , suffer from this, and other people have complained about it too
2) It might be confusing to new users. For instance, this comment:

> But apart from that, the workflow didn't feel natural. When you start, it is hard to understand what was going on. At some point I think I was seeing new images being uploaded? And without being asked for a license, whether I took the photo myself or anything, or to confirm anything, the image was suddenly uploaded (even before the category selection, which was apparently added in a later edit) - which I only noticed because it was the top image on the 'recently uploaded' flow. Quite a confusing experience.

What do you guys think? The web-based Upload Wizard only starts uploads after categories are selected, and aside from it taking just a bit more time, there don't seem to be any significant drawbacks to waiting.

**Comment by nicolas-raoul** [comment]
I firmly believe that we are doing the good thing. Uploading as soon as we can is important for user efficiency.
Actually there are talks to implement the same thing in the Upload Wizard.

**Comment by misaochan** [comment]
Hm, okay. We will need to try and figure out why some modifications work and others don't, then. I still haven't been able to deduce a pattern with that - unfortunately it leads to many pictures being uploaded without categories even though the user did select them.

**Comment by nicolas-raoul** [comment]
Maybe the users just press back on the categories screen?
What proportion of uploaded pictures have this problem?

**Comment by misaochan** [comment]
In the case of the photo I submitted, I definitely submitted it with categories selected. For me the % of pictures with this issue are maybe 10%, glancing at my contributions screen. Some people seem to have it more often (at least, judging from their feedback).

**Comment by nicolas-raoul** [comment]
Strange!
But delaying the image upload would probably not make that 10% much better. Both requests (picture, categories) can fail for a number of reasons, but we only see cases where the second step failed, because in cases where the first step fails, the second step can not even start.

**Comment by misaochan** [comment]
Yeah, really strange. :( It's hard to figure out why the second step is failing occasionally (and works at other times).

**Comment by misaochan** [comment]
Have you never had this issue happen with your pictures, @nicolas-raoul ?

**Comment by nicolas-raoul** [comment]
I haven't noticed any so far.

**Comment by misaochan** [comment]
Closing this since it is a duplicate of #310
