### ISSUE TITLE
Selectively delete search history

### ISSUE THREAD

**Issue by chaytanyasinha** [commons-app/apps-android-commons#3221]
Summary:
After we choose to delete the searches the most recent searches automatically deletes and to delete the older searches we need to click it longer.We cannot select multiple searches for delete.

Steps to reproduce:
Go to explore,click on search bar then click on bin icon then automatically the most recent search gets deleted even if u don't want to delete it.

What did you expect the app to do, and what did you see instead?
I expect that if I click on delete button a check box comes infront of every search then we can choose the thing/things we want to delete at once
Device-Samsung S6
Android-8.0
Would you like to work on the issue?
Yes
![WhatsApp Image 2019-11-24 at 21 51 16 (1)](https://user-images.githubusercontent.com/50200796/69500181-e2661d80-0f1e-11ea-8847-73aad8414a05.jpeg)

**Comment by nicolas-raoul** [comment]
I am afraid the search history source code is already complex enough, and
thus takes time to maintain. After all, the webapp does not even offer
search history at all 🙂
There are hundreds of very important tasks waiting for you, how about
choosing one of them? 🙂

**Comment by chaytanyasinha** [comment]
sure @nicolas-raoul,thanks for your feedback

**Comment by nicolas-raoul** [comment]
@chaytanyasinha Would you accept to take charge of https://github.com/commons-app/apps-android-commons/issues/3222 ? That would be wonderful :-)

**Comment by chaytanyasinha** [comment]
I will surely try for it sir @nicolas-raoul

**Comment by nicolas-raoul** [comment]
Oh, someone took the issue just an hour ago :-O

Then could you please try #3202 ? Please comment on the issue saying "I take this issue", so that nobody else takes it :-) Thanks a lot!

**Comment by chaytanyasinha** [comment]
@nicolas-raoul  Actually I was interested in doing #3202 but it's okay  if someone else took it,as its open source.
I'll be working on other issues.

**Comment by GearGit** [comment]
Maybe rather than having a checkbox next to each search result, we can have a simple "x" which when clicked will remove that particular search result.

**Comment by nicolas-raoul** [comment]
I still think it would be [overengineering](https://en.wikipedia.org/wiki/Overengineering).

**Comment by GearGit** [comment]
> I still think it would be [overengineering]

(https://en.wikipedia.org/wiki/Overengineering).
![20191127_112731](https://user-images.githubusercontent.com/41429261/69698045-3a14ac80-110a-11ea-9a4a-4380343ff02b.jpg)

This was what I was suggesting, the user will not have to press the delete button to delete the specific search result,instead the use will press the x button to delete the specific search result.

Although,it is your call if this feature is really needed or use the resources somewhere else.

**Comment by misaochan** [comment]
Hi, I think this feature is a "nice to have", but the added complexity does not seem to be worth it. Additionally, new contributors are strongly encouraged to work on issues tagged "bug" or "beginner friendly" as far as possible, as per our volunteer guidelines - https://github.com/commons-app/apps-android-commons/wiki/Volunteers-welcome%21 . :)

**Comment by chaytanyasinha** [comment]
okay @misaochan I understand this as  overengineering.

**Comment by misaochan** [comment]
Closing in that case. :)
