### ISSUE TITLE
Some pictures shown twice in my home activity

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#3225]
Steps:
- In the app, go to "Nearby"
- Use it to upload pictures of a few nearby places
- Go to app's home activity (maybe after killing the app)
- Some pictures appear twice, example:

![Screenshot_20191127-135634_Commons](https://user-images.githubusercontent.com/99590/69695388-83232b80-111f-11ea-89fe-ca5a19d87d06.jpg)

Not sure whether Nearby is relevant or not.

**Comment by chaytanyasinha** [comment]
@nicolas-raoul It even happens to me when I just upload  new picture.It doesn't show the new picture instead it shows the second latest picture.

**Comment by nicolas-raoul** [comment]
@chaytanyasinha Feel free to fix this bug when/if you don't have any other issue assigned to you :-)

**Comment by neslihanturan** [comment]
@chaytanyasinha if you see this "during the upload" it can be another issue. Do you also reliable reproduce this by following Nicolas's use case, I mean after uploading some nearby items?

**Comment by chaytanyasinha** [comment]
No @neslihanturan I mean after the photo is uploaded but it happens with me for the time the app is opened after exiting the app and coming again it comes the way it should.

**Comment by chaytanyasinha** [comment]
May I work with this issue.I have a solution for it.

**Comment by chaytanyasinha** [comment]
@neslihanturan @nicolas-raoul what about the issue

**Comment by chaytanyasinha** [comment]
I mentioned about issue which is mentioned in #3267 under this issue

**Comment by nicolas-raoul** [comment]
Duplicate of #3359
