### ISSUE TITLE
Provide explicit selection of licenses when uploading image

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#323]
I've received feedback from a few users (on Google Play and on Commons) that they did not like not being able to select the license when uploading. Users can currently select a license in Settings, but this isn't very clear.

Thoughts on putting a license selection field in the title/desc screen?

**Comment by nicolas-raoul** [comment]
Why not. It could also act as a reminder that the file must be compliant with that license.

**Comment by misaochan** [comment]
Note: This should probably be done alongside #254

**Comment by misaochan** [comment]
I just realized that this has been previously discussed at #140 . There are a few potential options I guess:

1. No explicit license selection on upload screen, but do the one-time popup thing explaining what the default license is and how to change license selection
2. License selection on upload screen but it defaults to the selection that user made previously (so no need for him to select it every upload)
3. Have a link to Settings page ("Change license here") below the small license text in upload page (and maybe make that text bigger)

**Comment by misaochan** [comment]
@nicolas-raoul , any thoughts on which option is preferred? I'm leaning towards option 2 or option 3 personally.

**Comment by nicolas-raoul** [comment]
Option 2 sounds perfect to me :-)
