### ISSUE TITLE
"Nearby" always first puts me in Punta Arenas

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#3231]
**Steps to reproduce:** 

- Start app
- Go to Nearby

Expected: map centered on Tokyo
Actually: map centered on Puntas Arenas, at the other side of the globe.

Every time.

**Device and Android version:** 

On two different recent phones.
 
**Commons app version:**

2.11.0.500~8472c63

**Comment by neslihanturan** [comment]
Thanks for this @nicolas-raoul , I am on it.

**Comment by neslihanturan** [comment]
I tested it again, it puts me to my current location correctly. Can you share some logs for this @nicolas-raoul , or any details you think might be related?

**Comment by neslihanturan** [comment]
Hi @nicolas-raoul , I am going through your logs but all the locations seems correct:
東京, Kanto
東京 東京 日本

Would it be possible for you to share your logs after fresh install, just after experiencing the issue, without playing with the app too much?

**Comment by neslihanturan** [comment]
Hi @nicolas-raoul , I am going through your logs but all the locations seems correct, they are in Japan.

Would it be possible for you to share your logs after fresh install, just after experiencing the issue, without playing with the app too much?

**Comment by misaochan** [comment]
I finally managed to reproduce this with a clean install (previously it did not happen to me). Logs sent.

**Comment by misaochan** [comment]
(It might be helpful to figure out why BOTH of us are defaulting to Punta Arenas when this happens - is there something special about those coords?)

**Comment by nicolas-raoul** [comment]
I created a new Wikimedia account, and noticed that the new account works fine, I am shown my correct location.

With my normal account, location is always Punta Arenas (more exactly: inside a bay near Punta Arenas), even when using a different phone.

**Comment by misaochan** [comment]
@nicolas-raoul Do you have 2FA enabled for your normal account? It sounds a bit strange that it could affect GPS location, but I was just wondering, since it was my 2FA account that has the problem (and my other acc doesn't).

**Comment by nicolas-raoul** [comment]
@misaochan No 2FA on any of my accounts
It might sound strange indeed, but this bug is so strange that any idea is worth investigating :-)

**Comment by misaochan** [comment]
Hmm, I did a clean install with the non-2FA account that did not have problems previously, and I still have this issue. Probably not related to accounts, then.
