### ISSUE TITLE
No items shown in Nearby

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#3233]
Wherever I go, no pins are shown:

![Screenshot_20191129-182904_Commons](https://user-images.githubusercontent.com/99590/69859012-a0e6c100-12d6-11ea-9c7b-1612e1ca0582.jpg)

**Comment by neslihanturan** [comment]
This one seems like a critical one. Do you have more details about this @nicolas-raoul , ie. logs, use cases.

**Comment by misaochan** [comment]
This only happened to me when I managed to reproduce #3231

**Comment by neslihanturan** [comment]
This issue is also should be solved by #3271
