### ISSUE TITLE
The colorAccent is white in darkMode making toggle switch unidentifiable whether on/off

### ISSUE THREAD

**Issue by ankit1414** [commons-app/apps-android-commons#3249]
**Summary:** 

The colorAccent is white in darkMode making toggle switch unidentifiable whether on/off.

**Steps to reproduce:** 

How can we reproduce the issue? 
->going to settings from the  navigation drawer.

What did you expect the app to do, and what did you see instead?
->The toggle switch should have some color when its on , which gives a better visual effect and easy identification.

**Device and Android version:** 

everywhere

**Commons app version:** 

current master branch

**Screen-shots:** 

![photo_2019-11-29_14-50-39](https://user-images.githubusercontent.com/45892437/69899005-997ef080-1386-11ea-8dde-b10b064d4a13.jpg)

**Would you like to work on the issue?**

yes

**Comment by maskaravivek** [comment]
Thanks for creating the issue @ankit1414. It would be great if you could reference google's material style guide to see what color should be used.

**Comment by ankit1414** [comment]
@maskaravivek  i think this is fine considering the app theme.
Hex Code : #108DE8
![colorAccent](https://user-images.githubusercontent.com/45892437/69903770-006eca80-13c4-11ea-89fc-49ba2bc2fdee.jpg)
