### ISSUE TITLE
Prevent repeated uploads of the same image under the same file name

### ISSUE THREAD

**Issue by whym** [commons-app/apps-android-commons#325]
Presumably because of unstable/interrupted network connection, the app produces unwanted identical versions to the same image.

Examples:

https://commons.wikimedia.org/wiki/File:Marstadter_See_-_6.jpeg
https://commons.wikimedia.org/wiki/File:Dresdner_umland_NO_November_2016_-_17.jpeg
https://commons.wikimedia.org/wiki/File:Relic_bibi_ka_alam.jpeg
https://commons.wikimedia.org/wiki/File:Indian_rupee_de_monitisation.jpeg

**Comment by neslihanturan** [comment]
For long time overrides arent reported. I think this is solved.
