### ISSUE TITLE
Error encountered when searching for captions.

### ISSUE THREAD

**Issue by GearGit** [commons-app/apps-android-commons#3254]
**Issue:**

When searching for a caption in the explore section of the upload_caption_depict branch at https://github.com/VitalyVPinchuk/apps-android-commons/tree/upload_caption_depict  we encounter an error in the media and category sections.

Here are two screenshots for each of the error encountered:

![Screenshot_20191129-091321_Commons](https://user-images.githubusercontent.com/41429261/69842934-5429c880-128b-11ea-996d-ba8cfdf69937.jpg)

![20191130_020040](https://user-images.githubusercontent.com/41429261/69892018-31e58880-1327-11ea-8568-0a36923f17e9.jpg)

**Steps to reproduce:**

1. Clone https://github.com/VitalyVPinchuk/apps-android-commons/tree/upload_caption_depict and store on your local machine.
2. Open the apps-android-commons folder in Android Studio. 
3. Switch to the upload_caption_depict branch by clicking on VCS -> Git -> Branches and select the upload_caption_depict branch.
4. Then press the 'Sync the project with Gradle Files' button to sync your app.
5. Run the app on an emulator or on an actual device.
6. Go to the explore section and search for a caption.

You should expect to see the error message in either the media or the category tab. It may also happen that both may show the same error.

**Expected Behaviour:**
"No Images matching bow found" and "No category matching flowers found" is the expected message that should have been displayed.

**Actual Behaviour:**
"No Images matching %1$s found" and "No category matching %1$s found" is the actual message that is being displayed.

**Would I like to be assigned this issue:**
Yes, as I am already working on issue #3222

**Comment by GearGit** [comment]
@nicolas-raoul @maskaravivek I found the function causing the error but to resolve it I need to know which variable or function is responsible for getting the input from the user.
Can you help me with this task?
https://github.com/VitalyVPinchuk/apps-android-commons/tree/upload_caption_depict

**Comment by GearGit** [comment]
I found a solution for it, however, I don't know if it violates the code style used by Wikimedia or not. 

Locate:
1. apps-android-commons\app\src\main\java\fr\free\nrw\commons\explore\images\SearchImageFragment.java
2. apps-android-commons\app\src\main\java\fr\free\nrw\commons\explore\categories\SearchCategoryFragment.java

Both of these files will have a method to handle cases when there is no data to display. 

![Screenshot_20191203-222328_Commons](https://user-images.githubusercontent.com/41429261/70073264-8a19d480-161e-11ea-8929-20e655b6682d.jpg)

The strings.xml file contains the keyid= "categories_not_found", which contains the message "No categories matching %1$s found", where %1$s is a string format and it is meant to be replaced by the actual caption that user had searched for, which was not happening in this branch of the app.

![Capture](https://user-images.githubusercontent.com/41429261/70073217-78383180-161e-11ea-8038-2e07411a5650.PNG)

I found a fix  by using the following line of code :
String searched_query = String.format((getResources().getString(R.string.categories_not_found)).toString(),query);

Here I am giving the string proper formatting by using String.format(). The "query" is a String containing the caption that was searched by the user. The same code has to be used in the other file too.

@nicolas-raoul @maskaravivek Does his modification follows the Wikimedia's style of code or not? If yes, then I will create a pull request for the 'upload_caption_depict' branch. If no, please suggest an alternative.

**Comment by maskaravivek** [comment]
@GearGit You can check our wiki to know about the code style or contributor guidelines. https://github.com/commons-app/apps-android-commons/wiki

Also, when in doubt, don't hesitate in creating a PR. If there's a code style issue or any other issue, any of the collaborators would point it out in the code review. :)

**Comment by GearGit** [comment]
> @GearGit You can check our wiki to know about the code style or contributor guidelines. https://github.com/commons-app/apps-android-commons/wiki
> 
> Also, when in doubt, don't hesitate in creating a PR. If there's a code style issue or any other issue, any of the collaborators would point it out in the code review. :)

I will check out the guide and create a PR asap.

**Comment by GearGit** [comment]
@maskaravivek @nicolas-raoul Sorry for delay, but I created a pull request which will fix the issue. Now I am waiting for it to be tested and merged with the upload_caption_depict branch at https://github.com/VitalyVPinchuk/apps-android-commons/tree/upload_caption_depict

**Comment by reveredvalidation198** [comment]
> [@GearGit](https://github.com/GearGit) You can check our wiki to know about the code style or contributor guidelines. https://github.com/commons-app/apps-android-commons/wiki
> 
> Also, when in doubt, don't hesitate in creating a PR. If there's a code style issue or any other issue, any of the collaborators would point it out in the code review. :)





https://stackdev.space/questions/retrieve-an-indefinite-number-of-values-from-a-jsonobject-and-populate-them-into-a-spinner-on-an-android-device
