### ISSUE TITLE
Create a video explaining the best practices for media upload

### ISSUE THREAD

**Issue by apap04** [commons-app/apps-android-commons#3259]
**Reserved for GCI Students**

**Summary:** 

Commons Android App is an open-source project which lets users contribute to Wikimedia by uploading media directly from their Android phone. Certain best practices need to be followed while you contribute. Often first-time contributors don't know about them and end uploading photos that might violate the policies. Your task is to create a video that demonstrates the best practices with the help of examples.

You have **4 days** to complete this task. See the [GCI task](https://codein.withgoogle.com/tasks/4739758895398912).

**Comment by nicolas-raoul** [comment]
A few policies that you can remind about in your video:
- Only upload pictures that you have taken yourself. Not pictures you have downloaded from the web, or screenshots.
- Do not upload selfies. Rather, upload pictures of things that are relevant for an encyclopedia, such as a public building, a mountain, a river, a local tool or dish.
- Do not upload pictures of your friends. Pictures of persons who already have a Wikipedia article are also very welcome.

**Comment by madhurgupta10** [comment]
@nicolas-raoul A student recently submitted a video, please let us know your feedback.

**Comment by nicolas-raoul** [comment]
@madhurgupta10 Could you please link to the video, or add me as a mentor to the video task? Thanks :-)

**Comment by madhurgupta10** [comment]
@nicolas-raoul Added you as mentor.

**Comment by nicolas-raoul** [comment]
@madhurgupta10 Thanks!
- Youtube video at https://codein.withgoogle.com/dashboard/task-instances/5176651416076288/ : Introduce how to install the app (not required but why not), what pictures not to upload, what pictures are OK to upload. Not super high quality but the main points are there, I suggest approving.
- MP4 at https://codein.withgoogle.com/dashboard/task-instances/5393129109192704/ : The tips are well understood and illustrated nicely. Uses commercial music and photos, but we had no rules about that (maybe add a rule that the video must be released under an open license?). Ironically the video itself is in portrait mode haha... Maybe add a requirement on the video format? I suggest approving this one too.

It is nice to see people contributing in various different styles.

**Comment by madhurgupta10** [comment]
@nicolas-raoul Thanks, I shared the feedback with them.

At:  https://codein.withgoogle.com/dashboard/task-instances/5393129109192704/ 
Already submitted the video with the changes and uploaded it to youtube. To change the orientation he needed to do it all over again so I think we can skip it. I think we are good to approve this one now.
https://www.youtube.com/watch?v=QsyjjuEOo8w&feature=youtu.be

**Comment by madhurgupta10** [comment]
@nicolas-raoul Other student At https://codein.withgoogle.com/dashboard/task-instances/5176651416076288/ Also completed.
@misaochan We can promote the videos on social media channels :)

https://youtu.be/3uMI8VGRKCQ

**Comment by nicolas-raoul** [comment]
Nice, the audio is much better.

**Comment by misaochan** [comment]
> @nicolas-raoul Other student At https://codein.withgoogle.com/dashboard/task-instances/5176651416076288/ Also completed.
> @misaochan We can promote the videos on social media channels :)
> 
> https://youtu.be/3uMI8VGRKCQ

Awesome! Is there a way to get a compilation of all of them? A playlist or something?

**Comment by madhurgupta10** [comment]
@misaochan not as of now 😕

Here are the links to both.

1. https://www.youtube.com/watch?v=QsyjjuEOo8w&feature=youtu.be
2. https://youtu.be/3uMI8VGRKCQ

**Comment by madhurgupta10** [comment]
@apap04 I think we can close this now!

**Comment by apap04** [comment]
> @apap04 I think we can close this now!

closed :)
