### ISSUE TITLE
Add java docs to methods which have it missing

### ISSUE THREAD

**Issue by maskaravivek** [commons-app/apps-android-commons#3278]
Recently we merged a few PRs with java docs missing and it would be great to have java docs added for all new methods that were added in those PRs. 

Or in general, it would be great to have java docs added to methods that have it missing.

**Comment by maskaravivek** [comment]
@nicolas-raoul @vanshikaarora @ujjwalagrawal17 This might be a good GCI task. Can new GCI tasks still be added? It would be great if students can pick as of their tasks. :)

**Comment by madhurgupta10** [comment]
@maskaravivek Great! I have drafted this task https://codein.withgoogle.com/dashboard/tasks/6669477291229184/preview/

**Comment by vanshikaarora** [comment]
Great! That's a nice task for students. 

@madhurgupta10 Can I help you with the task?

**Comment by madhurgupta10** [comment]
@vanshikaarora Sure

**Comment by vanshikaarora** [comment]
Do you need any help with drafting the task, or is it complete?

Also shall I assign myself as a mentor?

**Comment by madhurgupta10** [comment]
> Also shall I assign myself as a mentor?
Sure
> Do you need any help with drafting the task, or is it complete?
You may add additional details!

**Comment by vanshikaarora** [comment]
So shall we go ahead and publish this task?

**Comment by madhurgupta10** [comment]
@maskaravivek please let us know if anything else needs to be added.

**Comment by FlorianSW** [comment]
Hi guys, I saw your task in GCI :) I think there's some information missing to help students get started. First of all: How many methods a student should look like? Do you've any convention or good examples about how a good docblock for a method should look like? Any other information a newcomer should get in order to get started with contributing to your project?

Once these infos are in the task, I'm happy to publish it :)

**Comment by aklapper** [comment]
Also see https://www.mediawiki.org/wiki/Google_Code-in/Mentors#Task_requirements for how to write good and clear GCI tasks with enough info - thanks a lot! :)

**Comment by kbhardwaj123** [comment]
As GCI is over can i start working on this issue ?

**Comment by aklapper** [comment]
Yes, I'd say so :)
