### ISSUE TITLE
Contributions screen is deformed switching between tabs

### ISSUE THREAD

**Issue by neslihanturan** [commons-app/apps-android-commons#3287]
**Summary:** 
This issue is slightly related with an old issue #2507 
From @sivaraam 's report:

I think I'm facing a similar issue in my device now. But for me it is the "Contributions" screen in which I see the black part in the bottom of the screen. It happens to me consistently when I switch to "Nearby" and then back to "Contributions". It only goes away when there is a screen update in the Contributions page (e.g., when a "Nearby location" card is shown above the contributions).

I'm using version 2.12.0.514 of the app. My device runs Android 5.1.1

**Normal screen**
![Screenshot_2019-12-05-23-22-00](https://user-images.githubusercontent.com/12448084/70260765-fdeee500-17b6-11ea-8c6a-72d4a6fb7286.png)

**Screen with black part in bottom**
![Screenshot_2019-12-04-00-09-20](https://user-images.githubusercontent.com/12448084/70260771-02b39900-17b7-11ea-81e2-641cf3db0ae5.png)

**Comment by VojtechDostal** [comment]
Yes this does look similar to #2507 . I haven't experienced this problem for a long time, though.

**Comment by ashishkumar468** [comment]
I seemed to have been able to reproduce this, will try to add a fix in the upcoming nearby refactor-branch
