### ISSUE TITLE
Map does not work

### ISSUE THREAD

**Issue by VojtechDostal** [commons-app/apps-android-commons#3293]
Don't know where to start... these new functions look so pretty but unfortunately I cannot use them :-( map basically does not work for me in the latest version. I realize this is not the most useful way to report issues but let me just list a few of them:

- it starts to load somewhere in the Argentina and only shifts to Prague when the pins load (if they do)
-  it loads all wikidata items including those which are photographed. This means it's much slower, to the point it's unusable in the middle of Prague (where there is an item every few meters)
- cannot click on pins which do not have a label in any language
- "place type" function is either extremely slow (to the point it does not work) or has some bug, not sure

**Comment by misaochan** [comment]
@VojtechDostal We have merged a fix for this that we plan to release next week, but it would be great if we could get someone to test it on alpha.

I invited you to our alpha testing google group, so once you join you should be able to download the alpha version from the Play Store. Please let me know if the fix works for you. :)

You can leave alpha testing and resume beta testing at any time by leaving the alpha testing google group.

**Comment by VojtechDostal** [comment]
Not very specific bug and I haven't been able to sign in to alpha testing - due to lack of time :(
