### ISSUE TITLE
sir what do we exactly need to show in the video

### ISSUE THREAD

**Issue by animedhruv** [commons-app/apps-android-commons#3294]

**Comment by siamsot** [comment]
I think we can close this unless there are some extra information provided

**Comment by madhurgupta10** [comment]
@animedhruv Hi, I believe you are a Code-In student. Please use the official Google Code-In Comment section for any queries or you can continue on the conversation on https://github.com/commons-app/apps-android-commons/issues/3259

**Comment by madhurgupta10** [comment]
@nicolas-raoul I think we can close this now.
