### ISSUE TITLE
Ultimate achievement: Too many contributions (making our script time out)

### ISSUE THREAD

**Issue by VDK** [commons-app/apps-android-commons#3295]
**Summary:** 

I have over ¼ million edits on Wikimedia Commons. The "achievements" tab in the app isn't able to calculate which awards I've got because there's too much data. I think this is not an issue that can be fixed because we don't cache user data statistics. A "you got all the achievements"-award shouldn't be too hard to implement? 

**Steps to reproduce:** 

An account with a lot of edits (1Veertje for instance) loads the "achievements" tab in the menu
Request times put 

**System logs:**

**Device and Android version:** 
MIUI 11

 
**Commons app version:** 
2.12.0

**Screen-shots:** 

![Screenshot_2019-12-15-23-50-02-114_fr free nrw commons](https://user-images.githubusercontent.com/849603/70870607-a4946c00-1f95-11ea-9554-bbacdcf58272.jpg)

**Would you like to work on the issue?**
Haven't developed for Android 
.

**Comment by nicolas-raoul** [comment]
Thanks Vera for using the app! :-)

Good idea, instead of showing this error we should display something like:
```
Congratulations!
Your number of contributions is so high that it breaks our achievements calculation system.
This is the ultimate achievement.
```

The difficulty is to differentiate between:
- Failures due to high number of contributions
- All other kinds of failures, for instance high server load or database issues

If we can differentiate those reliably, then we can implement this enhancement.

**Comment by VDK** [comment]
[A simple API query](https://commons.wikimedia.org/w/api.php?action=query&list=users&ususers=1Veertje&usprop=editcount) gets you the total edit count. 
It's probably safe to assume the achiements caculation has failed because a user has over 200.000 edits?
Some testing could be done beforehand to determine when the calculation starts to fail or afterwards by logging a user's edit count when the calculation has failed and adjust it downward accordingly.

**Comment by GearGit** [comment]
@VDK @nicolas-raoul This seems an interesting feature to implement, I would like to work on this issue. But I don't have a test account with this high number of edits.

**Comment by maskaravivek** [comment]
@GearGit It seems there are other issues already assigned to you. It would be great if you could first complete those. If this issue still remains unassigned by the time you are done with other tasks, feel free to ping again. :)

**Comment by kbhardwaj123** [comment]
@maskaravivek @nicolas-raoul Sir this issue seems quite intriguing, can i work on this ?
