### ISSUE TITLE
Switching to/from night mode causes crash on Nearby tab

### ISSUE THREAD

**Issue by tmutimer** [commons-app/apps-android-commons#3300]
**Summary:** 

Toggling the night mode on or off, then navigating back to the nearby screen causes the map to not display properly. Tapping the List button then causes a crash.

**Steps to reproduce:** 
1. Open the nearby tab.
2. Open the sidebar and go to settings
3. Toggle once the night mode option
4. Go back to nearby.
::DEFECT map does not show up. small white square region shows instead in top-right corner.
5. Press list button
::DEFECT app crashes

It appears this occurs in NearbyParentFragment.getNearbyMapFragment() - in this method the view and animation variables remain null when the map fragment is reused.

**System logs:**

[MapCrashLog.txt](https://github.com/commons-app/apps-android-commons/files/3984560/MapCrashLog.txt)

**Device and Android version:** 

Oneplus 5
Android 9
Stock OxygenOS 9.0.9
 
**Commons app version:** 
2.12.0-debug-master

**Screen-shots:** 
![image](https://user-images.githubusercontent.com/44621832/71192817-e74d9100-2280-11ea-9522-2e18af00608f.png)

**Would you like to work on the issue?**
I would like to work on this myself if possible. This would be my first contribution, so I understand if this is not allowed.

**Comment by neslihanturan** [comment]
Sure it is allowed:) Welcome to team and thanks for reporting and being volunteer to work on this issue @tmutimer . By the definition the issue seems like suitable for a first time contributor. Please ask if you face with any problem.

**Comment by gouri-panda** [comment]
@neslihanturan  can I work this issue?

**Comment by maskaravivek** [comment]
@gouri-panda Sure. It is yours. :)

**Comment by ashishkumar468** [comment]
Hi @gouri-panda , We are about to merge a refactor branch of nearby(#3322 ). This issue should not happen any more. I would recommend you to wait for a few days (until that branch is merged) and if  the issue still persists, you can surely pick that up :).

**Comment by ashishkumar468** [comment]
Assigning this to myself to avoid future confusions.

**Comment by gouri-panda** [comment]
Sure@ashishkumar

**Comment by gouri-panda** [comment]
@ashishkumar468 Sure

**Comment by ashishkumar468** [comment]
This has been resolved #3322, closing this one.
