### ISSUE TITLE
[GCI Ideas] Update the app on Appetize to latest version and update URL on Readme

### ISSUE THREAD

**Issue by madhurgupta10** [commons-app/apps-android-commons#3301]
**Summary:** 
The Appetize app version seems to be outdated (2.10.2)

A good Code-In Task can be, updating the app on Appetize to latest version and update URL on Readme.

Student needs to generate a signed apk of prod flavor and upload it to a free appetize account (they can ask an adult if it requires 18+ to upload). After that, they can update the Readme file and open a PR.

**Comment by maskaravivek** [comment]
@madhurgupta10 Do we have any statistics on how many people are using the app via appetize? If even a few users are trying out the app using appetize, we can probably automate the process in the future using their APIs. 

https://appetize.io/docs#updating-apps

**Comment by madhurgupta10** [comment]
@maskaravivek Here is the usage report. I see few people are actually using the app on appetize.
![image](https://user-images.githubusercontent.com/30932899/71418473-a5618800-2690-11ea-9126-ceafde877d37.png)

**Comment by maskaravivek** [comment]
@madhurgupta10 Can you help in creating a separate task for automating the appetize update process. Any volunteer can pick it up. :)

**Comment by madhurgupta10** [comment]
@maskaravivek Sure, also if we are automating this task then it would be too difficult for Code-In, so I think we should not include this in Code-In.

**Comment by maskaravivek** [comment]
Yes, apologies for not being clear. I meant a general task here on Github :)

**Comment by madhurgupta10** [comment]
@maskaravivek task created #3311
