### ISSUE TITLE
Create Youtube video to be placed on Play Store

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#331]
Splitting this task from #86 . For reference, we want to create a Youtube video showing how to use our app, and have it placed on our Google Play Store.

Some thoughts/questions:

1. What exactly do we want to demonstrate in the video? My thoughts:
  - Upload gallery pics from within the app
  - Upload pics directly from gallery (via Share)
  - Upload pic taken by in-app camera
  - Enabling geotagging and changing licenses in Settings (maybe?)
  - Nearby function (maybe?)
2. Should we create a new Youtube account just for the video?
3. How should we do the narration? I've never made a video before, so I have no experience of this. Do we take the video first and then try to match narration to it, or narrate while taking the video? How do we make it look not-too-amateurish? Should we consider asking for help to make it look/sound more professional?

**Comment by nicolas-raoul** [comment]
contents sounds ok.

youtube links with google plus, i had a bad experience with this, so i
would say better create a dedicated google account.

take, assemble, and only then narrate on top of it. androidscreencast might
help.

**Comment by misaochan** [comment]
Noted, thanks!

**Comment by misaochan** [comment]
Okay, newbie question here: I browsed through the  Play store page of several high profile apps to try and get good examples to work from, and none of them have videos on their store page. I can't find a single example so far, not even for games where gameplay trailers would be important. Not sure if it is allowed?

Some of them do have videos on their websites, though. Should we be aiming for this instead @nicol

**Comment by misaochan** [comment]
Okay, newbie question here: I browsed through the Play store page of several high profile apps to try and get good examples to work from, and none of them have videos on their store page. I can't find a single example so far, not even for games where gameplay trailers would be important. Not sure if it is allowed? Or am I missing something?

Some of them do have videos on their websites, though. Should we be aiming for this instead @nicolas-raoul ? Tagging @tobias47n9e as well for input on whether we would like a video on the website.

**Comment by nicolas-raoul** [comment]
AnkiDroid has a video :-)

**Comment by misaochan** [comment]
John has helped create the video based on my script: https://www.youtube.com/watch?v=LLR-muFd1D0&feature=youtu.be

Thanks John! :)
