### ISSUE TITLE
Picture zoomed too much

### ISSUE THREAD

**Issue by chinmoy12c** [commons-app/apps-android-commons#3312]
**Summary:** 
When a picture is clicked, the picture is zoomed to the point that parts of the picture are not visible.

**Steps to reproduce:** 
Open any picture in featured or mobile uploads.

**Device and Android version:** 
I'm using Redmi note 7s with android version 9(Pie)

**Commons app version:** 
version 2.11.0

**Screen-shots:** 
![Screenshot_2019-12-30-18-18-53-445_fr free nrw commons](https://user-images.githubusercontent.com/57670338/71583149-3f16b280-2b33-11ea-946e-9cfc318489ba.jpg)

![Screenshot_2019-12-30-18-18-56-921_fr free nrw commons](https://user-images.githubusercontent.com/57670338/71583165-4ccc3800-2b33-11ea-9e97-5d9e684083af.jpg)

**Would you like to work on the issue?**
Yes, I would like to work on this issue. I have found a way to fix it by using https://github.com/ongakuer/PhotoDraweeView and i request permission to use this library.

**Comment by nicolas-raoul** [comment]
So, do you suggest showing the picture at the top and fill the rest with black?

Is there really no way to achieve that without using the PhotoDraweeView library?

**Comment by chinmoy12c** [comment]
> So, do you suggest showing the picture at the top and fill the rest with black?
> 
> Is there really no way to achieve that without using the PhotoDraweeView library?

Yes, the library places the image automatically in the centre and it looks good on the black background as well.
![Screenshot_2019-12-30-20-33-05-285_fr free nrw commons beta](https://user-images.githubusercontent.com/57670338/71587519-fd423800-2b43-11ea-8f18-69e3eb8af6dc.jpg)

![Screenshot_2019-12-30-20-28-52-257_fr free nrw commons beta](https://user-images.githubusercontent.com/57670338/71587538-121ecb80-2b44-11ea-97da-d3be5cd414ff.jpg)

The reason for using PhotoDraweeView library was that it was an extension to the Fresco library so it was compatible with existing code. If you want i can look for a way to achieve this without the library.

**Comment by chinmoy12c** [comment]
Found a better solution without using the library , changing the scale type to fitCenter fixed the issue. 

![Screenshot_2019-12-31-01-15-15-711_fr free nrw commons beta](https://user-images.githubusercontent.com/57670338/71598148-c41dbe00-2b6b-11ea-8826-8982b5cfd4fd.jpg)

***EXTRA MODIFICATIONS***
Should I make the background black as well? It looks better.

**Comment by nicolas-raoul** [comment]
Yes, black background would be great :-)
Also, does it look strange when scrolling the details up a bit? A few more
screenshots would be great (once the background is black).
Thanks!

**Comment by chinmoy12c** [comment]
This is how it looks now.

![Screenshot_2019-12-31-11-35-14-939_fr free nrw commons beta](https://user-images.githubusercontent.com/57670338/71611846-59e43800-2bc2-11ea-80d5-b6afb0b8d46a.jpg)
![Screenshot_2019-12-31-11-35-10-156_fr free nrw commons beta](https://user-images.githubusercontent.com/57670338/71611847-59e43800-2bc2-11ea-8d90-8c17f134dfff.jpg)
![Screenshot_2019-12-31-11-33-39-724_fr free nrw commons beta](https://user-images.githubusercontent.com/57670338/71611848-59e43800-2bc2-11ea-9788-a4c192904cf5.jpg)
![Screenshot_2019-12-31-11-33-35-363_fr free nrw commons beta](https://user-images.githubusercontent.com/57670338/71611850-5a7cce80-2bc2-11ea-8439-6b78d742b026.jpg)
![Screenshot_2019-12-31-11-33-31-079_fr free nrw commons beta](https://user-images.githubusercontent.com/57670338/71611851-5a7cce80-2bc2-11ea-834d-cb3c11c0ddb6.jpg)

**Comment by nicolas-raoul** [comment]
Looks like a good improvement to me!
Could you please post a few screenshots in landscape mode too? 🙂

**Comment by chinmoy12c** [comment]
These are landscape view screenshots
![Screenshot_2020-01-01-12-40-55-304_fr free nrw commons beta](https://user-images.githubusercontent.com/57670338/71638996-37225400-2c94-11ea-9e4b-5114b52a9fb4.jpg)
![Screenshot_2020-01-01-12-39-58-700_fr free nrw commons beta](https://user-images.githubusercontent.com/57670338/71638997-37225400-2c94-11ea-9019-4b318cc550a9.jpg)
![Screenshot_2020-01-01-12-40-09-460_fr free nrw commons beta](https://user-images.githubusercontent.com/57670338/71638998-37baea80-2c94-11ea-9e4b-0095370ee767.jpg)

**Comment by nicolas-raoul** [comment]
Looks great!
Could you please send a pull request and post the link to it here?
Thanks :-)

**Comment by chinmoy12c** [comment]
This is the pull request link.
https://github.com/commons-app/apps-android-commons/pull/3315#issue-358640716
Thank You :)

**Comment by madhurgupta10** [comment]
@nicolas-raoul Was the issue closed without any PR merger?

**Comment by kbhardwaj123** [comment]
@madhurgupta10 oh actually I have added fix for this in my PR #3422 for handling zoom in which I have maintained the aspect ratio as requested in it's issue thread
