### ISSUE TITLE
Enabled Fast Scroll disrupts normal scroll flow

### ISSUE THREAD

**Issue by bistaastha** [commons-app/apps-android-commons#3316]
**Summary:** 
In Explore activity, scrolling through 'Featured' or 'Uploaded via Mobile' has fast scrolling enabled for the GridView. For right-handed scrolling, this GridView scrollbar is often accidentally touched and may lead to an abrupt jump to another image. Also, it is counter-intuitive to normal scrolling.

**Steps to reproduce:** 
- Go to Explore
- Scroll through images in any of the tabs
- The GridView scrollbar is visible on the right side of the screen

**Device and Android version:** 
Moto G (5S) Android 8.1.0 API level 27

**Commons app version:** 
Current master

**Screen-shots:** 

![Screenshot_20200103-132726 (1)](https://user-images.githubusercontent.com/40273492/71714362-91a5e680-2e33-11ea-8f93-36c26debb045.png)
![Screenshot_20200103-132721 (1)](https://user-images.githubusercontent.com/40273492/71714374-9f5b6c00-2e33-11ea-95cf-f026dfabe0eb.png)

**Would you like to work on the issue?**
No

**Comment by bistaastha** [comment]
@nicolas-raoul Can you tag this issue as a good first issue? It is a small change but it would require some digging around.

**Comment by maskaravivek** [comment]
Yes I have also faced this issue multiple times. Can you do a bit of research and propose possible approaches to tackle it. AFAIK fast scrolling was enabled as these lists could potentially contain 100s of items.

**Comment by bistaastha** [comment]
@maskaravivek For smaller screen devices and possibly for the ones with a curved edge, I think that fast scroll hinders scrolling more than it helps with it.

**Comment by bistaastha** [comment]
I'll try to look for other alternatives for fast scroll. Since the section where this is enabled in called Explore, is the functionality for skipping to certain parts of the scroll flow really required?

**Comment by maskaravivek** [comment]
I am not sure if we would be able to detect curved edges of the device and disable fast scrolling just for those devices. 

Currently, the scroll bar is very thick. Can you check if decreasing the scrollbar width to 1px or helps? Also, maybe we can set `android:fadeScrollbars:true` so that it is not visible at all times. 

It would be great if could check these approaches and maybe any other approach that comes to your mind. We can then finalize what fix should be used.

**Comment by bistaastha** [comment]
I tried fading the scrollbar, but accidental touches still managed to activate it. It will be some time before I will be able to check out the scrollbar after decreasing the width.

**Comment by avivith** [comment]
Hi. Is this issue solved already, or should I work on it?

**Comment by bistaastha** [comment]
Hi @avivith. This hasn't been resolved yet. 

The fast scrollbar's height and width can be customized by making custom drawables ([referene](https://stackoverflow.com/questions/45370246/how-to-use-fastscrollenabled-in-recyclerview)) .

@maskaravivek Reducing the width using this method might be a possible approach to solving the problem of accidental touches.

**Comment by avivith** [comment]
Sadly, I'm a little sick and don't manage to work currently. I hope someone else would solve this issue.

**Comment by 318anushka** [comment]
I'd like to give this a try if no one is working on it.

**Comment by 318anushka** [comment]
I have enabled fast scroll only when user actually scrolls(state is changed) so even if you accidentally touch scroll bar it wouldn't lead to abrupt jump or disrupt normal scroll.

**Comment by 318anushka** [comment]
I have fixed the issue [here](https://github.com/commons-app/apps-android-commons/pull/3593)
Can someone review it please.

**Comment by 318anushka** [comment]
@maskaravivek I came up with a better solution. Firstly change the width(styling) of scrollbar and then set an offset(this can be width of scrollbar) such that fastscroll is enabled only when user scrolls within that offset. This reduces abrupt jumps to great extent.
Also fading scrollbar doesn't work because that will only hide it.

**Comment by maskaravivek** [comment]
Quoting @macgills's comment here: 

> I was just validating code quality. I don't think that reading the issue there is much consensus on what is to be done. Personally I'd be more for deleting fast scroll, to me flinging is very quick at getting through data and I don't understand why people want to be scrolling through `explore>uploaded via mobile` arbitrarily? Are people using it as a `Random` feature essentially? Is it a most recent list and if so why do they want to see the 1000th most recent item? I just don't understand who the feature is for so I can't make a recommendation on what to actually do.

@nicolas-raoul @neslihanturan What are your opinions on fast scrolling?

**Comment by nicolas-raoul** [comment]
I agree with bistaastha that "fast scrolling" is irritating, I often tap it by mistake, and I have almost never used it on purpose. I am in favor of removing it.

Context: "Uploaded via mobile" is meant to emulate good behavior by showing good pictures uploaded by others. It also allows experienced users to spot bad pictures and delete them, on the go.

**Comment by 318anushka** [comment]
If everyone agrees then it's better we remove it. I just tested it on a 4.0" screen device and it really is a problem works in about 1/7th of screen width
but if fast scroll is disabled then obviously user cannot directly jump to image.
Consider users who scrolls upto some items and later want to continue after that or review different pictures. There is no refreshing by pull feature so opening explore again after a short interval of time brings up same images.

**Comment by macgills** [comment]
@318anushka please remove fast scroll. 

If you want to discuss pull to refresh then please create a ticket.
