### ISSUE TITLE
App Crash when click on location button in NearBy

### ISSUE THREAD

**Issue by DeepaMalani** [commons-app/apps-android-commons#3319]
**Summary:** 

App crash when clicks on the location button in NearBy before loading the Map. The location button is working properly once the map is loaded but if we click on the location button before the loading app gets crash.

**Steps to reproduce:** 

How can we reproduce the issue? 

1. Click the NearBy tab in the home screen.
2. Try to click on the location button(top right) before loading the map.
3. App will crash.

What did you expect the app to do, and what did you see instead?

The location button should be disabled until the map is not loaded.

**System logs:**

```

**Device and Android version:** 

1. Emulator API 23
2. HTC - Android 5
 
**Commons app version:** 

2.11.0

**Screen-shots:** 


https://user-images.githubusercontent.com/24900514/72184115-85c2a300-33a4-11ea-82f3-4656916784a4.png

**Would you like to work on the issue?**

Yes

**Comment by DeepaMalani** [comment]
![NearByjpg](https://user-images.githubusercontent.com/24900514/72184257-e18d2c00-33a4-11ea-801a-8c7b36f91448.jpg)

**Comment by neslihanturan** [comment]
It should be fixed on current master, can you please try give us a feedback. Thanks for finding it though @DeepaMalani !

**Comment by DeepaMalani** [comment]
Sure  @neslihanturan will try on current master and then update you.

Thanks

**Comment by ashishkumar468** [comment]
HI @DeepaMalani, Even if it's not fixed on current master, @neslihanturan & I are working on some bug fixes in nearby. It should be fixed then, Appreciate you for your help :)

**Comment by DeepaMalani** [comment]
Thank @ashishkumar468 for informing.

**Comment by vvijayalakshmi21** [comment]
Hi, is this issue fixed?
I see the same in 2.12.3~dc08a5e88 version of the app. In my case I didn't grant permissions to location access and when I clicked on the icon, the app crashed

**Comment by neslihanturan** [comment]
Can you try it on current master @vvijayalakshmi21 ? If it is solved feel free to close this issue:)

**Comment by vvijayalakshmi21** [comment]
Tested on current master on Google Pixel 3a with API level 10
The issue does not occur anymore. I did not experience crash when I click the icon before the map loads or without granting permission to access my location.
This can be closed.
