### ISSUE TITLE
Trim whitespaces from title on upload

### ISSUE THREAD

**Issue by t-karcher** [commons-app/apps-android-commons#3327]
**Summary:** 

In a recent upload I noticed (too late) that autocorrect somehow added a space after my title and the app didn't trim it on upload: https://commons.wikimedia.org/wiki/File:Lumix_G6_mit_Objektiven_.jpg

I'd appreciate if the app could automatically trim all whitespaces from the beginning and the end of titles.

**Steps to reproduce:** 

Add a whitespace at the end of a title. It will not be trimmed.

**Device and Android version:** 

Android 8.1 on Gigaset GS270+
 
**Commons app version:** 

2.11.0

**Comment by misaochan** [comment]
Makes sense, thanks for the suggestion. :)

**Comment by GearGit** [comment]
Working on it. I think I found the exact code to edit, but I will have to test it first.

**Comment by GearGit** [comment]
There are Network issues on the 2.11 version of the app. Whenever I try to login or go to the Explore page of the app, there is always the error of network issue. Is this issue due to the fact that I am running the app in beta mode from Android Studio or am I missing something?

**Comment by misaochan** [comment]
Hi @GearGit , can you try with the current master build or v2.12.1 (latest release), please?

**Comment by maskaravivek** [comment]
The login issue is been discussed in #3320. Yes, its specific to beta app.

**Comment by GearGit** [comment]
@maskaravivek @nicolas-raoul 
I went through the issue [#3320](https://github.com/commons-app/apps-android-commons/issues/3320). I am also facing the same issue "Chain Validation Failed". How do I switch to the production model in the 2.11-release branch as well as in the master branch? 

Even when I try to Skip Login, the explore section doesn't fetch any data. Can anyone help me understand why?

**Comment by misaochan** [comment]
@GearGit , re: your question from the other issue:

> What methodology would you recommend me to test the issue #3327 ?

You can just use prodDebug to upload a proper picture with a whitespace at the end of the title and link to the result on your PR. You will not be banned for uploading a proper picture. :)

**Comment by GearGit** [comment]
I have resolved the issue but for some reason the PR checks have failed. Can someone please review and merge my PR?
PR #3338 
I have attached relevant screenshots of the commit working fine.

**Comment by rimshach** [comment]
Hey can I work on this issue?
