### ISSUE TITLE
Can't change language.

### ISSUE THREAD

**Issue by petkakisgeorge** [commons-app/apps-android-commons#3329]
**Summary:**

I'm going to settings and there is only an option for changing the default description language.
The default app description is been set by the device's default language and cannot be changed.

**Steps to reproduce:** 

We should  add an option where user could also choose for the default app language.
So after the User choose an other language , the program should re-choose  the right resource bundle and re-load the program's default String Values .

**Would you like to work on the issue?**

I want to give it a try. I'm new in contribution, actually this would be my first, and i would need help in solving it and sure some directions. 
e.x. In which Class should i contribute? , should i reload the hole program or i could change the string values one by one ?.....

**Comment by 6point022** [comment]
@nicolas-raoul Can I work on this issue? I have identified the code which is causing this and would like to get someone's go-ahead to start working on this.

**Comment by neslihanturan** [comment]
Hi @6point022 , this seems like a new feature request, more than a bug report.

**Comment by 6point022** [comment]
@neslihanturan The app provides the user the option to change the default language, but nothing happens on doing so. Isn't it a bug if the app gives unexpected results or behaves in unintended ways? Shouldn't the option either work properly or be removed completely?

**Comment by neslihanturan** [comment]
No worries @6point022 , there is a confusion between language of the description and language of the app:) Would you still be interested to work on this feature, ie. adding a new setting to change app language, default setting should be phone local as we do now.

**Comment by 6point022** [comment]
> Would you still be interested to work on this feature, ie. adding a new setting to change app language, default setting should be phone local as we do now.

@neslihanturan I would love to work on this! However, I will need some guidance because the codebase still feels overwhelming to me. 

Will this be a good way to proceed? 
1. I will add an option in the Settings for the user to change the app's language.
2. I will save this preference using Shared Preferences.
3. I will create a method that will change the app's language.

Now, I want to understand two things: Where should this method reside? And when should this method be called?

**Comment by 6point022** [comment]
> Would you still be interested to work on this feature, ie. adding a new setting to change app language, default setting should be phone local as we do now.

@neslihanturan I would love to work on this! After going through the code, I have finally got some idea of how to begin. If possible, please assign this issue to me. Thanks!

**Comment by sivaraam** [comment]
Excuse me for chiming in. IIUC, this change is to add a new setting to the app that would allow the user to switch the interface language independent of the device language. Is that correct? I was just wondering, in what case would a user want to set an interface language for the app different from that of the system language? :thinking:

**Comment by 6point022** [comment]
@sivaraam This [stackexchange question](https://ux.stackexchange.com/questions/36541/should-i-provide-the-option-to-change-the-language-in-an-app) discusses some interesting cases when we may want to provide an explicit option to the user and not listen for the language of the system. I guess it depends on the type of app and can be useful at times.

**Comment by sivaraam** [comment]
> This [stackexchange question](https://ux.stackexchange.com/questions/36541/should-i-provide-the-option-to-change-the-language-in-an-app) discusses some interesting cases when we may want to provide an explicit option to the user and not listen for the language of the system.

That's an interesting link. Thanks!

> I guess it depends on the type of app and can be useful at times.

I get that. I was just curious to know how this option would benefit the users of the Commons Android app. The app already changes the interface language according to the system language if a translation is available. I was of the opinion that that behaviour was good enough for the app. I couldn't see how an option to switch the interface language independent of the device language would be beneficial to the user of the Commons app.

**Comment by nicolas-raoul** [comment]
I don't think our app needs this setting more than any other app.
This makes settings (and our codebase) a bit more complex, without a strong reason.
(sorry for joining late, I thought I had posted this a few weeks ago already)

**Comment by misaochan** [comment]
I agree that it adds unnecessary complexity. I don't see a common or compelling reason why a user would want to have just our app in a different language from their device. Would anyone else like to chime in on this?

The PR that is already up does seem to be a pity  - it looks like a well-written PR that would have taken a lot of time to do. On the other hand, this is also clearly an "enhancement" issue and not a "bug", and it was not tagged "good first issue". As per #3363 and https://github.com/commons-app/apps-android-commons/wiki/Volunteers-welcome%21 , it doesn't fit the criteria for PR submission from a new contributor.

**Comment by 6point022** [comment]
>The PR that is already up does seem to be a pity - it looks like a well-written PR that would have taken a lot of time to do.

Yes, but I did learn a lot doing it, and I believe that's what matters the most. 😄 

>it doesn't fit the criteria for PR submission from a new contributor.

I have created some other issues and hope to work on them to get started. 😃

**Comment by misaochan** [comment]
Thank you for your understanding, @6point022 . :) We will leave the discussion open for now, but even if we decide to close your PR, I will make a note on it that the PR was a good one and adheres to our code quality requirements, and that we couldn't merge it for reasons unrelated to code. So you can mention it on your GSoC application etc either way.

**Comment by neslihanturan** [comment]
Sorry @6point022 , that I mis-guided you about this feature can be a good idea (I actually considered it as a good idea). Still your efforts will be considered during GSoC application. Please don't feel demotivated :purple_heart:

**Comment by misaochan** [comment]
If everyone is OK with it, I will close this issue?
