### ISSUE TITLE
For an item that already has a P18, do not add another one

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#3333]
The Nearby activity now also shows Wikidata items that **have** a P18 image. That's great.

But when the user choose to add an image based on this item, the image should not be added as an another P18.
Why? Because a Wikidata item should only have one P18 image. By the way, the selection of the most representative image is sometimes the result of a community conversation, so replacing the existing image is probably not a good idea either.

The item's information can still be used to propose categories/etc, though, so it makes sense to keep the + even for items that already have a P18.

I tag this as a bug because I have to clean up manually behind haha.

**Comment by misaochan** [comment]
Ah, thanks for bringing this up. I agree, we should remove the last step (adding the item to p18) for items that already have a p18 (i.e. does not "need photos").

**Comment by nicolas-raoul** [comment]
I don't think that should block any release, though.
I personally review all P18 manually and fix all such cases, it only takes a few minutes per week.
It is an interesting task for a newcomer, I think.

**Comment by misaochan** [comment]
Thanks @nicolas-raoul . :) 2.13 is a long time away, but I will make a note that it is optional still.

**Comment by vishakha-a** [comment]
@misaochan can I work on this issue?

**Comment by misaochan** [comment]
@vishakha-a Sure, let us know how it goes. :)

**Comment by misaochan** [comment]
@vishakha-a How are things going?

**Comment by CodeMonk263** [comment]
Can i work on this issue

**Comment by vishakha-a** [comment]
No, no
I am trying to figure out what to do

**Comment by misaochan** [comment]
@vishakha-a If you let us know where exactly you are stuck and what you have tried so far, we might be able to help you.

**Comment by nicolas-raoul** [comment]
@vishakha-a Yes, at least every two days please let us:
- What you tried
- What did not work
- What worked
- What step you are planning to start next
Thanks :-)

**Comment by rimshach** [comment]
Hey @nicolas-raoul , can I work on this issue?

**Comment by nicolas-raoul** [comment]
@vishakha-a Please share your progress, thanks!
Otherwise you might have to let someone else take the issue.
Thanks for your understanding :-)

**Comment by vishakha-a** [comment]
Hey, yes you can take the issue. Sincere apologies for holding it back. I
am unable to understand the issue I probably need to learn a lot before I
can make any contributions.
