### ISSUE TITLE
Hotfix: Coordinates of picture are not uploaded

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#3336]
A user mentioned that since 2.11 (and still existing in 2.12.1), coordinates are not uploaded with his pictures. He confirms that he can see the coordinates in his stock gallery.

**Comment by maskaravivek** [comment]
I also faced the same issue on the latest master. When I checked I found out that all EXIF info was stripped by default. Once I checked all EXIF tags in settings, it worked for me perfectly. 

As far as I remember, we were not supposed to strip EXIF by default. I forgot to report this issue.

**Comment by misaochan** [comment]
Argh, I thought we fixed that? Must have been reverted for some reason. :/

**Comment by GearGit** [comment]
Can I work on this?

**Comment by maskaravivek** [comment]
@GearGit Are you assigned any other issues then I would suggest that you first finish them and then if this issue is still unassigned then you can comment here again. :)

**Comment by misaochan** [comment]
Bumping this in priority since it happens for all users.

**Comment by GearGit** [comment]
@maskaravivek I was assigned the issue #3222, but I think the upload_caption_depict branch will be merged with the master branch #3334. Therefore, I don't know if I can contribute to it or not.

**Comment by VitalyVPinchuk** [comment]
I think it is this commit that reverted changes https://github.com/commons-app/apps-android-commons/commit/8ccad2277d9974b82ae166e12f70b1e61d14d3ca#diff-9ce737f6c063c5b0b8182e771d45d97f

**Comment by vibhusharma101** [comment]
can I Work on this?

**Comment by ashishkumar468** [comment]
@vibhusharma101  I have already added a PR for this. Feel free to help us in one of the other open issues :)

**Comment by ashishkumar468** [comment]
Merged in 2.12-release, closing this issue
