### ISSUE TITLE
Add map of Nearby places needing photos (currently only have list)

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#334]
Some people would prefer using a map to a list, as @VojtechDostal and John Lubbock (Wikimedia UK) have suggested. A map would be easier to gamify in the future (a la Pokemon Go) if we wanted to as well.

Potential task for Vienna Hackathon 2017.

**Comment by nicolas-raoul** [comment]
The Google Maps-based MapView is not available to devices without Google Play, so better use this OpenStreetMap-based replacement: https://github.com/osmdroid/osmdroid

**Comment by misaochan** [comment]
Ah yes, good point. Also I suppose we need to consider how we want to switch between the two views, and which one to use as the default.

**Comment by tobias47n9e** [comment]
Can we use https://maps.wikimedia.org as a tile server?

**Comment by nicolas-raoul** [comment]
@tobias47n9e Unless we grow to millions of users overnight AND make the map the default activity, we can safely assume that they won't be bothered by our impact.

**Comment by maskaravivek** [comment]
I was interested in contributing on this feature. Are we planning to pick it up at the pre-hackathon or hackathon events?

**Comment by misaochan** [comment]
We were planning to work on it during the pre-hackathon, but we have other potential tasks for that as well (e.g. making the switch to Wikidata). If you would like to work on it now, please feel free. If it's completed before the pre-hackathon, we can just work on the other potential tasks, or alternatively if it's partially completed, we can use your work as a base then.

**Comment by misaochan** [comment]
This has been implemented and released in beta, please create an issue if anyone is having any problems with it.
