### ISSUE TITLE
Cannot login into the app. Chain validation failure is showing

### ISSUE THREAD

**Issue by vibhusharma101** [commons-app/apps-android-commons#3340]
Can Anybody tell me the test credentials to login into the app?
![WhatsApp Image 2020-01-23 at 4 33 25 PM](https://user-images.githubusercontent.com/39101226/72979344-216cfe00-3dfe-11ea-8566-c4baa5f0e450.jpeg)

**Comment by neslihanturan** [comment]
Hey @vibhusharma101 , we are using beta cluster ( https://commons.wikimedia.beta.wmflabs.org/wiki/Main_Page ) for test purposes, to not vandalize real commons servers with our test uploads. We all have a beta account along with our normal wikimedia accounts.
