### ISSUE TITLE
Ghost metadata from Nearby

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#3342]
I had something strange happen, but can't reproduce it.

1. I tapped a few pins in Nearby, including a pharmaceutical organization.
2. I did some other unrelated things while walking around.
3. With my stock camera app I took a picture of a train station.
4. I opened Commons, pressed the plus button in the home activity (my gallery)
5. I selected my train station pic
6. Surprise: Metadata prefilled with the pharmaceutical organization.
![Screenshot_20200123-203313_Commons](https://user-images.githubusercontent.com/99590/72981657-a537e200-3e20-11ea-913b-d7f5e4b027fa.jpg)

**Comment by vibhusharma101** [comment]
@nicolas-raoul  sir can I work on this issue?

**Comment by maskaravivek** [comment]
@vibhusharma101 Yes, it would be great if you could help in reproducing the issue and then pick it up. :)

**Comment by nicolas-raoul** [comment]
@vibhusharma101 Any progress on this issue? Please let us know :-)

**Comment by nicolas-raoul** [comment]
I haven't seen this for a while, closing for now.
