### ISSUE TITLE
Upload limit is working even if I leave the upload limit edittext blank or if I press Cancel button

### ISSUE THREAD

**Issue by vibhusharma101** [commons-app/apps-android-commons#3346]
**Summary:** 
Upload limit is taking the first digit of last entered number a the upload limit if I am leaving upload limit edittext blank.

What did you expect the app to do, and what did you see instead?
I wanted app to show an toast displaying an error that upload limit edittext is empty.

**Screen-shots:** 

![todayfifd](https://user-images.githubusercontent.com/39101226/73133075-c9c2d280-4049-11ea-8c31-9182803d0c8e.gif)

**Would you like to work on the issue?**

I want to work on this issue.
@nicolas-raoul @maskaravivek

**Comment by vibhusharma101** [comment]
@ashishkumar0207  sir, Can I work on this?

**Comment by ashishkumar468** [comment]
@vibhusharma101  It is yours, please feel free on posting updates on the same over here.

**Comment by vibhusharma101** [comment]
@ashishkumar468  sir I am facing a little bit problem I am unable to login to the beta version of app.
chain validation failed is coming can you please send me some test credentials. In app in production mode on playstore, I am able to login but in Beta version of app I am unable to login.

**Comment by ashishkumar468** [comment]
Hi @vibhusharma101, I have added a probable fix for #3320. Once that is merged, I am sure you will be able to login with your beta credentials and use the beta flavor of the app.

**Comment by vibhusharma101** [comment]
ok sir @ashishkumar0207

**Comment by ashishkumar468** [comment]
@vibhusharma101 Login issue has been resolved, please take a pull from master. Feel free to post updates on this issue :)

**Comment by vibhusharma101** [comment]
@ashishkumar468 sir incorrect username password coming even if I enter correct one

**Comment by 6point022** [comment]
@ashishkumar468 I don't think this issue has been fixed, the linked PR doesn't really display any error message nor does it fix the issue that even pressing "Cancel" saves the change. I'd be interested in working on this if it can be re-assigned. Thanks!

**Comment by maskaravivek** [comment]
@6point022 if you see any issues in @vibhusharma101's PR feel free to post your code review comments on the PR itself. :)

**Comment by madhurgupta10** [comment]
@maskaravivek Hopefully migrations to AndroidX Pref #3521 will include this fix

**Comment by madhurgupta10** [comment]
@maskaravivek I tested the master branch after #3521 merger and this issue is resolved, so we can close #3346 and #3362
