### ISSUE TITLE
Store settings on backend?

### ISSUE THREAD

**Issue by vibhusharma101** [commons-app/apps-android-commons#3347]
**Summary:** 

All the settings are restored to Default automatically when I Logout and again Login in the app.

**Screen-shots:** 
![helgf](https://user-images.githubusercontent.com/39101226/73134874-b1f74880-4061-11ea-9970-6dfe66a44d93.gif)

Can be created by pressing the Volume Down and Power Button at the same time on Android 4.0 and higher.

**Would you like to work on the issue?**

@maskaravivek  @nicolas-raoul    sir I want to confirm that is this a bug or it is a feature of the app that previous settings are not saved in the app.

**Comment by ashishkumar468** [comment]
@vibhusharma101 The app does not store such preferences in the backend, all this information is stored locally. As a result of which, whenever you logout, such preferences are cleared and hence not maintained across sessions

**Comment by vibhusharma101** [comment]
Ok, sir . But sir we should try to save it in the backend for better user experience as user have to change the settings again and again.

**Comment by GearGit** [comment]
@maskaravivek  @ashishkumar0207 
So is this an issue that has to be worked upon or not?

**Comment by nicolas-raoul** [comment]
I suggest doing it only if the Wikipedia app already does it.
So, the first task would be to check whether the Wikipedia app does it or not.
Thanks for the fresh idea!
If the Wikipedia app does not do it yet, I suggest closing this issue and re-opening it when they do.

**Comment by vibhusharma101** [comment]
Ok sir @nicolas-raoul
