### ISSUE TITLE
Use "taken in" template

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#3353]
From https://commons.wikimedia.org/wiki/Commons_talk:Mobile_app#{{Taken_in}} :

Would it be possible to use {{Taken in}} rather than a regular category? The categories actually state that they should not be added manually. Please see Revision #390555221 for what I am talking about.

**Comment by GearGit** [comment]
@misaochan Can I work on this issue?

**Comment by misaochan** [comment]
Sure @GearGit , please keep us updated. :)

**Comment by GearGit** [comment]
@misaochan I looked into Revision #390555221, but I didn't quite understood what is to be done exactly.
Can you help me out?

**Comment by misaochan** [comment]
The revision shows that "[[Category:Taken with Samsung Galaxy M30s]]" was moved to "{{taken in|Samsung Galaxy M30s}}" in the "|source=" line. Basically, they are suggesting we do this for all categories starting with "Taken with".

**Comment by misaochan** [comment]
Edit: Actually, I looked at the file page and that revision looks wrong to me. https://commons.wikimedia.org/wiki/Template:Taken_in does not seem like it should be used for "Taken with", because a location is desired and not a camera model. Perhaps this issue is not so straightforward after all. :/ @nicolas-raoul what do you think?

**Comment by GearGit** [comment]
> 
> 
> Edit: Actually, I looked at the file page and that revision looks wrong to me. https://commons.wikimedia.org/wiki/Template:Taken_in does not seem like it should be used for "Taken with", because a location is desired and not a camera model. Perhaps this issue is not so straightforward after all. :/ @nicolas-raoul what do you think?

@misaochan 
So should I work on this issue or not?

**Comment by misaochan** [comment]
We can unassign it from you for now and you can look for a different issue. When we come to a consensus we can open it up again.

**Comment by avivith** [comment]
Hi. Is this issue reopened or solved?

**Comment by misaochan** [comment]
The issue is still being discussed (I am awaiting @nicolas-raoul 's input), sorry.

**Comment by ahsanz024** [comment]
any updates on this issue?

**Comment by nicolas-raoul** [comment]
There is no reply from Gone_Postal, it is unclear what they want. I think we can close this issue.
If there is any additional information that would make sense for us to upload, please feel free to open a new issue detailing exactly what it would add. Thanks all :-)
