### ISSUE TITLE
Do not display pins at all when "Needs Photo" is selected?

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#3355]
Currently, when "Needs Photo" filter is selected, we still display the pins of Wikidata items that DON'T need photos, except that they are transparent. However, this seems to confuse users - for instance, one user thought that the transparent pins were the [items that "don't exist"](https://commons.wikimedia.org/wiki/Commons_talk:Mobile_app#Beta_map_not_working) (which kind of makes sense!).

While the current UI does look very nice, I wonder if it might be best to:
1. Do not display the pins of items that don't "need photos" at all, when that filter is selected. When the user de-selects that filter, the current system of green pins is fine.
2. Instead, display the pins of items that don't "exist" as transparent

What do you think @neslihanturan @VojtechDostal @nicolas-raoul ?

**Comment by VojtechDostal** [comment]
I must say I was confused when I first saw this but I got used to it. If you don't mind, I'd be in favour of spmehow hiding the pins altogether which do not comply with the chosen criteria.

**Comment by kbhardwaj123** [comment]
![20200210_201103 1](https://user-images.githubusercontent.com/44129798/74159304-8f5c5680-4c41-11ea-8689-b00b438d503e.gif)
This does look a bit confusing i think we should remove those pins, moreover due to that border they look grey rather than transparent, if everyone is in favour of this i would interested to work on it

**Comment by nicolas-raoul** [comment]
I agree too.
@kbhardwaj123 looking forward to your pull request :-)

**Comment by misaochan** [comment]
Yes, that solution sounds fine, just make sure they are displayed when the user selects to view them. :)

**Comment by neslihanturan** [comment]
Hey, I was testing #3335 . Currently filtered out pins are removed at all. But it does not seems clear when the user filtered out everything: 
![image](https://user-images.githubusercontent.com/3127881/74820816-b38bf780-5313-11ea-8fed-959ae471ba72.png)

I think our current implementation is more clear.

**Comment by misaochan** [comment]
Sorry, I'm confused, how is it possible to filter out everything? If they select "Exists" then it should only filter out the pins that don't exist, right? Or are you referring to the place type?

**Comment by neslihanturan** [comment]
When we filter by place type, we can select a type which is not there. Ie. parks.

**Comment by misaochan** [comment]
I think for place type that would be an expected behaviour - in other maps (e.g. Google Maps or booking.com), if I am searching for something and I make my filters too restrictive and I see nothing, I think I would intuitively understand that I have filtered out all the possibilities. Perhaps however it could be useful to have an indicator that the place type filter is active, in the upper panel.
