### ISSUE TITLE
Duplicate photos in "Contributions" page

### ISSUE THREAD

**Issue by mds08011** [commons-app/apps-android-commons#3359]
**Summary:** 

After uploading photos, I see duplicate images in the app's "contributions" screen.

**Steps to reproduce:** 

1. Upload an image to Wikimedia Commons using this Android App.
2. Look though your photos in the "contribution" for duplicate images (they may not be adjacent to each other in the image feed).
3. View your account's "uploads" on https://commons.wikimedia.org and look for any duplicate images.

I see duplicate images on the app but the website shows that the photo uploaded correctly (no duplicates).

**System logs:**

Logs exported from the app: https://privatebin.net/?6ccdcedda9153900#7YwYwPohymf1LZ6iBuUf8jBQBbj9hDzUjiZcwGvejr4i

**Device and Android version:** 

API level: 29
Android version: 10
Device manufacturer: Google
Device model: Pixel 2
Device: walleye
Network type: wifi
App version name: 2.12.3~dc08a5e88
User name: Mds08011
 
**Commons app version:** 

App version name: 2.12.3~dc08a5e88

I am currently using the Beta version but this issue occurred on the regular/stable version as well.

**Screen-shots:** 

Duplicate photo in app:
<img src="https://user-images.githubusercontent.com/8010709/73565371-3fe28300-4416-11ea-90ec-dac8728c5285.png" width="30%">

Duplicate photo in app:
<img src="https://user-images.githubusercontent.com/8010709/73565372-3fe28300-4416-11ea-9dde-c4d98cdd6034.png" width="30%">

"Uplaods" on website showing only single images:
<img src="https://user-images.githubusercontent.com/8010709/73565373-3fe28300-4416-11ea-8987-7eeadf024db6.PNG" width="80%">

**Would you like to work on the issue?**

No.  I don't have the technical knowledge to address this.

**Comment by gouri-panda** [comment]
@mds08011 This  issue already exists #3218

**Comment by mds08011** [comment]
Thank you.  I moved my bug report to the existing issue.  Note that my case is slightly different in that I didn't see any uploading error messages and only one copy of my image uploads commons.wikimedia.org despite the app showing two.

**Comment by nicolas-raoul** [comment]
I don't think it is the same issue, actually.
Malcom has not experienced any failed upload, yet duplicate picture show up.
Actually I had the same issue until recently.
I signed up for the alpha, then uninstall and reinstalled, now it is better. Could you please try @mds08011 ? https://github.com/commons-app/apps-android-commons/wiki/Volunteers-welcome%21#how-to-install-the-alpha Thanks for your feedback! :-)

**Comment by GearGit** [comment]
I would like to work on this issue @misaochan @mds08011

**Comment by ashishkumar468** [comment]
@GearGit  Please verify if the build still exists over here https://github.com/commons-app/apps-android-commons/wiki/Volunteers-welcome%21#how-to-install-the-alpha. If yes, feel free to pick this up

**Comment by mds08011** [comment]
I installed the Alpha release (Version: 2.12.3.568~fdbe53d) and my issue appears to be fixed.  However, I am suspicious that it was the act of installing and reinstalling the app, not the Alpha release itself, that resolved it.

**Comment by ashishkumar468** [comment]
Hey @mds08011 , Can you try following the steps you have mentioned in the issue, maybe then we can conclude if it's actually fixed or not.

**Comment by mds08011** [comment]
I am still experiencing this issue on Alpha Version: 2.12.3.569~b13d888

**Comment by misaochan** [comment]
> I would like to work on this issue @misaochan @mds08011

@GearGit sounds good, let us know how you get on!

**Comment by nicolas-raoul** [comment]
@GearGit Please let us know about your progress :-) Thanks!

**Comment by misaochan** [comment]
Hi @GearGit , any updates on this issue?

**Comment by GearGit** [comment]
> Hi @GearGit , any updates on this issue?

I am trying to recreate the issue. I will update on the issue by EOD.

**Comment by nicolas-raoul** [comment]
Still happening in 2.12.3.591~e303491
![Screenshot_20200228-100001_Commons](https://user-images.githubusercontent.com/99590/75500760-419d6780-5a11-11ea-95df-8eb6058e9d24.jpg)

**Comment by misaochan** [comment]
Hi @GearGit , as this issue is a pretty visible bug, I am bumping its priority.

How are things going with your work on it? If you are actively working on it now, we're happy to keep you assigned to it. Please update us with where exactly you are stuck, and what you have tried, so we can try to help you.

If you are not actively working on it, please let us know so we can assign it to someone else.

Thanks!

**Comment by GearGit** [comment]
@misaochan
I am not able to resolve the issue, please do assign it to someone else.

**Comment by ashishkumar468** [comment]
Picking this up
