### ISSUE TITLE
Improve review feature documentation

### ISSUE THREAD

**Issue by neslihanturan** [commons-app/apps-android-commons#3361]
**Summary:** 
Currently our review tool is not well documented. It is not clear what happens when user click to buttons. This lack of information may prevent users from using this tool, since they don't know what they effect. Some infoboxes can be added to inform users about.

**Comment by vibhusharma101** [comment]
@neslihanturan  can I work on this ?

**Comment by animeshk08** [comment]
@neslihanturan Can I work on this?

**Comment by ivantux1** [comment]
Excuse my question but:
Are you looking for the application to see small banners of what each button does or a small section where you can see screenshots of the actions to be performed by the app?

**Comment by avivith** [comment]
Hi. Is this issue closed/worked on, or should i work on it?

**Comment by FawziyahAlebiosu** [comment]
do you mean adding the type of info buttons that are in this [image](https://user-images.githubusercontent.com/20774412/77117770-0affaf00-6a09-11ea-9aed-f4cd21a86989.png) to these two options at the [bottom?](https://user-images.githubusercontent.com/20774412/77117805-1bb02500-6a09-11ea-8496-89b37be5a643.png)
If I would throw a solution out there, maybe we should just modify what the boxes that are already there say?To make it even more clear? But, i'm not sure if it would NOT be repetitive if we add info boxes next to both of those options at the bottom?

![image](https://user-images.githubusercontent.com/20774412/77117685-ea375980-6a08-11ea-9c64-831ab90bddee.png)
![image](https://user-images.githubusercontent.com/20774412/77117733-fb806600-6a08-11ea-88ac-166869feace6.png)

**Comment by ankitadhiman003** [comment]
@neslihanturan Can I work on this issue?

**Comment by adizcode** [comment]
Hi, I'd like to contribute. Could I get a few pointers on how to get started?

**Comment by Danejerosa1111** [comment]
Hi, I would like to work on this issue if nobody is assigned.

**Comment by Danejerosa1111** [comment]
![image](https://user-images.githubusercontent.com/51971585/97120461-57644900-16d4-11eb-88a4-ff1cbde6f22d.png)

**Comment by Danejerosa1111** [comment]
I had revised the tool tip review button to have three different options that have alert boxes that go into a little more detail for this issue

**Comment by neslihanturan** [comment]
Hi everyone seemed to interested, sorry for the latency of the response. Based on the mockups shared, I decided to explain what is in my mind about this task in more details:
- A rounded info button next to Peer Review title should exists
- When clicked to that button a group of explanation of each function of this feature should be visible. This explanation should be a detailled explanatin, ie. "when you say "no out of scope", you are adding a nomination for deletion template to this image."
- Every question should have their own info buttons at their near
- When they are clicked a detailed (what is happening on commons side when both of these options are clicked) explanation should appear.

**Comment by Soroyesodiq** [comment]
> Hi everyone seemed to interested, sorry for the latency of the response. Based on the mockups shared, I decided to explain what is in my mind about this task in more details:
> 
> * A rounded info button next to Peer Review title should exists
> * When clicked to that button a group of explanation of each function of this feature should be visible. This explanation should be a detailled explanatin, ie. "when you say "no out of scope", you are adding a nomination for deletion template to this image."
> * Every question should have their own info buttons at their near
> * When they are clicked a detailed (what is happening on commons side when both of these options are clicked) explanation should appear.

Thanks for the detailed explanation.

**Comment by AdityaArunSharma** [comment]
@neslihanturan is this issue still open? can it be assigned to me?

**Comment by Dannyhh** [comment]
@neslihanturan any updates on this issue? or is someone working on it

**Comment by neslihanturan** [comment]
No one is working on it and the issue is still open :) A good start point would be answering how you plan to solve each bullets that I listed at https://github.com/commons-app/apps-android-commons/issues/3361#issuecomment-725372809 . @Dannyhh , are you interested?

**Comment by Krshivam25** [comment]
Hi @neslihanturan Please assign me this issue as I'm a new bees here and love to contribute over documentation

**Comment by Krshivam25** [comment]
Hi @neslihanturan Please assign me this issue as I'm a new bees here and love to contribute over documentation

**Comment by shreyadenny** [comment]
Hello! @neslihanturan this issue was last assigned on 23rd of March and I noticed that it has been over 2 months since. If there haven't been any developments, can I please contribute to this. I am new to open source and I'd like to start with this documentation.

**Comment by Rishavgupta12345** [comment]
@nicolas-raoul  I would like to work on this issue and implement the feature told here, just verify it once, 

if this is actually needed, assign me this issue

**Comment by nicolas-raoul** [comment]
@Rishavgupta12345 Thanks please follow https://github.com/commons-app/apps-android-commons/issues/3361#issuecomment-725372809

**Comment by Rishavgupta12345** [comment]
@nicolas-raoul you can close this issue now

**Comment by AdityaArunSharma** [comment]
Please remove me from your mailing list

**Comment by misaochan** [comment]
@AdityaArunSharma , you have to unsubscribe from the GitHub email notifications yourself, we can't do it for you.
