### ISSUE TITLE
Information for all GSoC/Outreachy aspirants

### ISSUE THREAD

**Issue by maskaravivek** [commons-app/apps-android-commons#3363]
Everyone, welcome to our GitHub repository! Thanks for showing interest in the Commons Android app. 

I am posting this information as some of you have messaged me asking where to get started. 

### How do I get started? 

- Look for  "good-first-issues" and volunteer to pick one up.  Also, some of the issues might have been assigned a long ago, so you can comment on the issue thread to check whether someone is actually working on it or not. It can be then reassigned.
- Apart from "good-first-issues", you can look for issues with labels "bug" or "tests" and take one up. 
- Also, compile and run the app on your phone and I am sure you will find numerous minor issues. You can create a new issue on Github and then write that you volunteer to fix it.
- Moreover, if you don't find anything at all, then feel free to add unit test cases for any classes that are missing tests. :)
- Github is our primary tool for communication with volunteers. Feel free to create a new issue on GitHub if you get stuck with anything or if in doubt. One of our collaborators will check and reply on the issue in a few days. Use Github if: 
   - If you come across an undocumented bug and want to report/fix it
   - If you have a new feature suggestion
   - If you are having trouble setting up your local environment
   - Anything else related to the codebase as long as it doesn't require personal attention
- Feel free to mail one of the collaborators/maintainers if there's something you want to discuss in private.  

### Are there any guidelines for volunteering for this project? 

Check the volunteer guide and contributing guidelines for more details. 

- https://github.com/commons-app/commons-app-documentation/blob/master/android/Contributing-Guidelines.md
- https://github.com/commons-app/commons-app-documentation/blob/master/android/Volunteers-welcome!.md

### Important Note

- The number of contributions you make will not be the primary criterion for choosing the intern. So please don't feel pressured to make the biggest number of contributions.

- Please avoid creating a pull request for an issue until the issue has been assigned to you.

### Communication

- Feel free to create Github issues whenever you get stuck with anything and are not sure how to proceed. Github is usually must faster and more convenient as our project has a lot of active collaborators who keep an eye on all the threads. 
- Once the intern is selected, we will add them to Zulip. You don't need to be on Zulip right now. 

### Submitting a proposal

In the proposal, we want to see the timeline and understand how you have broken down the main task into small sub-tasks. Please make sure that you are able to clearly mention the sub tasks and provide a good estimate of the time you think it might take. Also, factor in time for documentation and unit test cases. 

Things to note: 
- provide a clear timeline
- Mention your unavailability or other prior commitments. 
- Outreachy doesn't allow you to take up another part-time/internship whereas GSoC does not have any such restriction. So if you are planning to take part-time apart from this internship then please mention it clearly in the proposal. 

You can find sample proposals here: 

https://phabricator.wikimedia.org/project/board/3795/query/all/

**Comment by GearGit** [comment]
@maskaravivek I have multiple possible project ideas for Commons Mobile App, should I message you directly or will it be discussed here?

**Comment by maskaravivek** [comment]
This is the project that we have proposed for this year's GSoC/Outreachy. https://phabricator.wikimedia.org/T217439

If you wish to discuss other ideas, you can send an mail about it.

**Comment by aarushivij** [comment]
hey @maskaravivek 
The view to this link is restricted

**Comment by misaochan** [comment]
> hey @maskaravivek
> The view to this link is restricted

Have you created an account?

**Comment by 6point022** [comment]
@misaochan The issue still persists after creating an account.

![image](https://user-images.githubusercontent.com/44764339/73771446-6bfa5d00-47a4-11ea-9476-ff29c9363b3a.png)

**Comment by dzekem** [comment]
Have the same issue too after creating an account.

**Comment by ciphereck** [comment]
I created the account. Still getting the same issue.

**Comment by misaochan** [comment]
Ah yes, we need @maskaravivek to edit the task then. :)

**Comment by maskaravivek** [comment]
I have updated the task link. It should work now.

**Comment by kbhardwaj123** [comment]
it just works now :)

**Comment by maskaravivek** [comment]
**Important Note:** 

The number of contributions you make won't be the primary criteria for choosing the intern. So please don't feel pressurized to make the most number of contributions. 

Please avoid creating a pull request for an issue until the issue has been discussed and assigned to you.

**Comment by sivaraam** [comment]
@maskaravivek Wouldn't it be better to also mention the note in the description of the issue to ensure it isn't missed? :thinking:

**Comment by misaochan** [comment]
I modified the desc with Vivek's note.

**Comment by madhurgupta10** [comment]
@misaochan maybe it is also a good idea to add the following to the description:

That student should first request a code review from the person who assigned the issue or who created the issue, instead of tagging every maintainer on each and every PR.

**Comment by maskaravivek** [comment]
> That student should first request a code review from the person who assigned the issue or who created the issue, instead of tagging every maintainer on each and every PR.

Haha. I think it is okay that new contributors are tagging lots of people as its understandable that they are excited about getting their first PRs merged. :)

I used to tag @misaochan and then also ping her on the issue thread 🤣 

But yes IMO there's no need to initially tag anyone for code reviews. One of the collaborators will check it out in 1-2 days. If no one checks it then feel free to tag relevant folks.

**Comment by misaochan** [comment]
Hi all, this was written for the 2020 GSoC programme, but I just wanted to re-pin this because it contains extremely good advice for anyone aiming to apply for the 2021 round. In particular, please note this section:

> **The number of contributions you make will not be the primary criterion for choosing the intern**. So please don't feel pressured to make the biggest number of contributions. 

Please avoid creating a pull request for an issue until the issue has been assigned to you.

**Comment by sivaraam** [comment]
Speaking of GSoC 2021, are we aware of the [upcoming changes](https://opensource.googleblog.com/2020/10/google-summer-of-code-2021-is-bringing.html) to the programme? 🤔

**Comment by misaochan** [comment]
> With the pandemic straining folks’ time we are changing the size of the projects and time commitment students are expected to spend on their projects. Starting in 2021, students will be focused on a 175-hour project over a 10-week coding period.

What was the requirement for the last GSoC, does anyone remember?

Pinging also @madhurgupta10 for this. :)

**Comment by madhurgupta10** [comment]
> > With the pandemic straining folks’ time we are changing the size of the projects and time commitment students are expected to spend on their projects. Starting in 2021, students will be focused on a 175-hour project over a 10-week coding period.
> 
> What was the requirement for the last GSoC, does anyone remember?
> 
> Pinging also @madhurgupta10 for this. :)

These changes are for GSoC 2021, for last year the pattern was the same as all previous years with 10 weeks of coding and 3 evaluations. [Check out this article](https://www.geeksforgeeks.org/whats-different-in-gsoc-2021-eligibility-timeline-stipend/#:~:text=Changes%20in%20GSoC%202021%20Edition&text=So%2C%20the%20changes%20which%20are,have%2010%20weeks%20to%20code.)

**Comment by sivaraam** [comment]
> > What was the requirement for the last GSoC, does anyone remember?
> > Pinging also @madhurgupta10 for this. :)
> 
> These changes are for GSoC 2021, for last year the pattern was the same as all previous years with 10 weeks of coding and 3 evaluations.

I believe it is 12 weeks. Also, the 350 hour time requirement of previous years is being reduced to 175 in 2021 (that's 1/2 the time requirement). Here's [concise piece](https://git.github.io/rev_news/2020/10/30/edition-68/) about the changes:

> Google Summer of Code 2021 has been announced with significant changes compared to previous editions. Notably coding hours and period will be reduced from 350 hours and 12 weeks to 175 hours and 10 weeks; there would be 2 evaluations (instead of 3). Additionally, eligibility requirements will be relaxed, among others allowing people participating in a variety of different licensed academic programs, not just students of accredited university programs.

**Comment by Prince-kushwaha** [comment]
@nicolas-raoul  @misaochan  what this year this organization participate in gsoc 2021

**Comment by nicolas-raoul** [comment]
The information for GSoC 2021 is at https://github.com/commons-app/commons-app-documentation/blob/master/android/Students.md
Thanks! :-)
