### ISSUE TITLE
Bug: SoftKeyboard showing even after switching from nearby tab to contribution tab

### ISSUE THREAD

**Issue by animeshk08** [commons-app/apps-android-commons#3367]
**Summary:** 
While searching for a place type if we switch from nearby tab to contributions tab the keyboard is still visible

**Steps to reproduce:** 

How can we reproduce the issue? 
1. Open nearby tab.
2. Search for a place type.
3. With the soft keyboard visible open contributions tab

What did you expect the app to do, and what did you see instead?
The soft keyboard should have collapsed

**Device and Android version:** 

What make and model device Redmi Note 7 pro
What Android version ANDROID 9
**Commons app version:** 
2.12.3-debug

**Screen-shots:** 
<img src="https://user-images.githubusercontent.com/32506591/73609994-da022100-45f8-11ea-8922-a812903ac910.gif " width="300" height="500">

**Would you like to work on the issue?**
Yes

**Comment by ashishkumar468** [comment]
Hi @animeshk08 , A major refactor branch of nearby is about to be merged. I would recommend you to wait for it to be merged and if the issue still persists, feel free to pick it up .

**Comment by animeshk08** [comment]
Okay I had already created a PR along with the issue.

**Comment by animeshk08** [comment]
Also, can you provide some inputs for Issue #3352 @ashishkumar468
