### ISSUE TITLE
Enchancement: Preventing multiple clicks on views which open Webview/BrowseIntent

### ISSUE THREAD

**Issue by animeshk08** [commons-app/apps-android-commons#3369]
**Summary:** 

A lot of views in the application opens BrowseIntent. However, clicking on these views multiple time the intent is also created multiple times which is quite heavy. Hence we can disable the button between successive calls so as to prevent multiple intent calls.
**Steps to reproduce:** 

1. Click on campaign view multiple times in a short period of time.

**Device and Android version:** 

What make and model device Redmi note7 pro
What Android version Android 9
 
**Commons app version:** 
2.12.3-debug

**Screen-shots:** 
<img src="https://user-images.githubusercontent.com/32506591/73611803-a8468580-460b-11ea-903f-89cfb0402321.gif" width="400">

**Would you like to work on the issue?**
Yes.

**Comment by animeshk08** [comment]
Sir can I get some inputs on this? @maskaravivek @ashishkumar468 @nicolas-raoul

**Comment by nicolas-raoul** [comment]
betaDebug often behaves weirdly.
Could you please send the same screencast with the prodDebug flavor? Thanks :-)

**Comment by sivaraam** [comment]
I believe this is obsolete now as #2944 is now fixed. Hence closing this.
