### ISSUE TITLE
Letters in Peer Review

### ISSUE THREAD

**Issue by petkakisgeorge** [commons-app/apps-android-commons#3376]
**Summary:** 
Some words doesn't appear correctly to the user . The line <VIOLATION> under the <NO, COPYRIGHT> and some of the descriptions.

**Steps to reproduce:** 
We could change the dimensions.

**Device and Android version:** 
Redmi note 5 , Android version 9

**Commons app version:** 
2.12.3

**Screen-shots:** 
![Screenshot_2020-02-05-19-40-04-954_fr free nrw commons](https://user-images.githubusercontent.com/37193878/73868409-10d27400-4851-11ea-8e46-61fca0a1c6cd.jpg)

**Would you like to work on the issue?**
No

**Comment by GearGit** [comment]
@petkakisgeorge Can I work on this?

**Comment by maskaravivek** [comment]
@GearGit yes, sure. its yours.

**Comment by mds08011** [comment]
I am experiencing a similar issue.  The text below “Is this correctly categorized?” is displayed from edge to edge of my screen.  It would help to have a larger margin.

<img src="https://user-images.githubusercontent.com/8010709/74050326-b4736f80-498a-11ea-9721-f645805224c8.png" width="50%">

**Comment by GearGit** [comment]
If I change the width in the layout, then other text will not behave as expected, although we can maybe make the container's height dynamically adjust to text length, where the height of the container will be bounded by maximum and minimum height?
@maskaravivek What do you say, although I have made changes and resolved the issue?

**Comment by mds08011** [comment]
What about reducing the text size instead of the container size?  I think the text would still be readable even if a little smaller.

**Comment by GearGit** [comment]
> What about reducing the text size instead of the container size? I think the text would still be readable even if a little smaller.

That is also a possibility but it's up to the mentors. Let's wait for their approval first, if they allow then I will make the necessary changes.

**Comment by madhurgupta10** [comment]
@GearGit any updates on this issue?

**Comment by mds08011** [comment]
@madhurgupta10 there is a Pull Request waiting to be reviewed: https://github.com/commons-app/apps-android-commons/pull/3386

**Comment by GearGit** [comment]
Created a new pull request.

https://github.com/commons-app/apps-android-commons/pull/3552

**Comment by gabrielchl** [comment]
(would like to work on this)

**Comment by madhurgupta10** [comment]
> (would like to work on this)

@gabrielchl Feel free to create a PR for this issue, you can checkout the discussion on old PR for the possible fixes for this issue.
