### ISSUE TITLE
Automatic Switching to Night Mode if system wide Dark Theme is enabled

### ISSUE THREAD

**Issue by madhurgupta10** [commons-app/apps-android-commons#3377]
**Summary:** 

With the new Android 10, there is a system-wide dark theme available.
Most of the apps automatically turn on/off the dark theme if it is enabled in the phone's setting.
We can add an option in our app's settings which will automatically switch to the preferred mode.

**Screen-shots:** 

![Screenshot_1580935030](https://user-images.githubusercontent.com/30932899/73880935-6d4f8680-4885-11ea-86bd-6e5219e062b2.png)

**Would you like to work on this issue?**

Yes

**Comment by madhurgupta10** [comment]
@nicolas-raoul What do you suggest?

**Comment by madhurgupta10** [comment]
@nicolas-raoul @neslihanturan @misaochan What do you suggest?

**Comment by neslihanturan** [comment]
This would be nice, but we should also keep our in-app setting IMO.

**Comment by madhurgupta10** [comment]
@neslihanturan Yes, we should keep it since Android 10 is new and not available to all phones yet.

**Comment by sivaraam** [comment]
@madhurgupta10 IIUC, you're thinking of changing the existing into something like the following:

![Screenshot_2020-02-10-23-21-40](https://user-images.githubusercontent.com/12448084/74176033-ea4f7700-4c5c-11ea-8ef6-9bf33eb12c4f.png)

Is that correct? If that is, then it would be a good addition indeed.

**Comment by madhurgupta10** [comment]
@sivaraam Indeed

**Comment by ashishkumar468** [comment]
@madhurgupta10 @sivaraam Or there could be just the two options, Light or Dark, and by default, the system's default theme should be selected?

**Comment by madhurgupta10** [comment]
@ashishkumar0207 I think it would be fine as well since most users who use dark mode on other apps won't prefer white mode on our app and vice-versa.

**Comment by sivaraam** [comment]
I think it would be better to provide the options following the guidelines mentioned in the [Android Developer guide for Dark theme](https://developer.android.com/guide/topics/ui/look-and-feel/darktheme#changing_themes_in-app):

> When running on devices running Android 9 or earlier, the recommended theme options are:
> 
> * Light
> * Dark
> * Set by Battery Saver (the recommended default option)
>
> When running on Android 10 (API level 29) and higher, the recommended options are different, to allow the user to override the system default:
> 
> * Light
> * Dark
> * System default (the recommended default option)
>
> Note that if the user selects Light, then Battery Saver will not change that setting.

This sounds sensible to me. This might improve the scope of the task but I hope it's for the better :slightly_smiling_face:

**Comment by sivaraam** [comment]
There seems to be a lot of discussion in the PR. So, can someone quickly catch me up on something? Were the changes done so that the options are provided as suggested in [the above comment](https://github.com/commons-app/apps-android-commons/issues/3377#issuecomment-584820998) as seemed to be the consensus? I'm mostly wondering about whether we show different options for the different Android versions.

**Comment by madhurgupta10** [comment]
@sivaraam I changed the night mode setting from a simple switch to a list preference. User can now set it as Dark or Light or Default (System-Wide Theme)

 In Android 10 if the default is selected in Commons app setting then the app will follow the system setting.

For older devices default system-wide theme remains Light or incase a custom skin of android supports dark theme then the app will also support it.

For a quick recap, the Commons app now follow the same theme system used by Gmail, Keep, etc.

**Comment by macgills** [comment]
There isn't actually a real mapping to these settings specifically but that is because we don't have a dayNight theme.
What the app does for `auto` is check the configuration to see if night mode is active and if so sets the theme dark, otherwise light.
Hopefully we will get to using `AppCompatDelegate.setDefaultNightMode().` once #3461 is done

**Comment by sivaraam** [comment]
I've noted some general comments about the change in a [PR comment](https://github.com/commons-app/apps-android-commons/pull/3460#issuecomment-596095164). Now some replies to the some points:

> For older devices default system-wide theme remains Light or incase a custom skin of android supports dark theme then the app will also support it.

Ah ha! I totally missed this when I said I'm not sure what happens on Android 9 or lower devices for the "Default" option in the [PR comment](https://github.com/commons-app/apps-android-commons/pull/3460#issuecomment-596095164). Sorry about that.

> For a quick recap, the Commons app now follows the same theme system used by Contacts, Gmail, etc.

Not exactly, I would say. At least not in Android 5.1 devices. Gmail doesn't even have an option to change the theme in Android 5.1. In Android 10, I see an option to change the theme. This is for the same versions of the app. I'm surprised they don't provide an option to switch between "Light" and "Dark" themes in Android 5.1. Anyways, that's not our concern now 🤷‍♂ So, moving on.

The behaviour of the Contacts app seems to mimic what's described in the [developer guide](https://developer.android.com/guide/topics/ui/look-and-feel/darktheme) including the options shown for the different Android versions. If resolving #3461 required to get this right, then fine. I'm just trying to clarify that the app still isn't there yet.

> Hopefully we will get to using AppCompatDelegate.setDefaultNightMode(). once #3461 is done

If that would improve the status quo, that would be great!
