### ISSUE TITLE
"Nearby Place found" despite already Nearby upload

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#3380]
Via Nearby, I took a pic of https://www.wikidata.org/wiki/Q21019339 (日本福音ルーテル社団)

Problem: While entering title, it asked me whether it is a pic of https://www.wikidata.org/wiki/Q11386485 (Oreno Hamburg Yamamoto) :
![Screenshot_20200207-083854_Commons](https://user-images.githubusercontent.com/99590/73988763-05816480-4987-11ea-8838-732fa0951078.jpg)
I said no, obviously.

Sad result: pic is linked from no Wikidata item.
https://commons.m.wikimedia.org/wiki/File%3A%E6%97%A5%E6%9C%AC%E7%A6%8F%E9%9F%B3%E3%83%AB%E3%83%BC%E3%83%86%E3%83%AB%E7%A4%BE%E5%9B%A3.jpg

Latest alpha (2.12.3.566~a6d2523)

**Comment by madhurgupta10** [comment]
@nicolas-raoul Can I work in this
?

**Comment by nicolas-raoul** [comment]
@madhurgupta10 Sure, thanks! :-)

**Comment by nicolas-raoul** [comment]
Just to make sure I was explicit:

When I come from Nearby, I already have a Wikidata item QID number associated, so the app should not display any "Nearby Place Found". Actually it should not even perform the latitude/longitude retrieval and Wikidata request, as they take time for nothing in that case.

:-)

**Comment by misaochan** [comment]
I agree, the solution would be to simply disable the search if the user is doing a direct Nearby upload.

**Comment by nicolas-raoul** [comment]
The issue is still present, I uploaded the picture below via Nearby, and P18 did not get filled: https://commons.wikimedia.org/wiki/File:Embassy_of_Slovakia,_Tokyo_2.jpg
![Screenshot_20200613-140838_Commons](https://user-images.githubusercontent.com/99590/84561048-3aae2100-ad84-11ea-9992-27c46d6ef021.jpg)
Actually my last 5 Nearby uploads have all failed to get P18, this bug is particularly penalizing in dense cities.

**Comment by macgills** [comment]
@madhurgupta10 I can take this issue if your are busy

**Comment by madhurgupta10** [comment]
@macgills Sure, thank you!

**Comment by Pratham2305** [comment]
@nicolas-raoul @madhurgupta10 I am able to reproduce this one on the latest master, Can I work on this?

**Comment by nicolas-raoul** [comment]
@Pratham2305 It is yours, thanks! :-)
The best would probably be to not search nearby items (and thus not show the popup) if the upload is already coming from the Nearby feature.

**Comment by misaochan** [comment]
Did #3799 not fix this?

**Comment by nicolas-raoul** [comment]
I experienced this bug two days ago, so I guess it somehow is still around.
Ah, good find, this PR should be a good source of inspiration :-)
