### ISSUE TITLE
Image Category Search Results

### ISSUE THREAD

**Issue by mds08011** [commons-app/apps-android-commons#3384]
**Summary:** 

When searching for categories, the most relevant category is not shown if searched for directly.  When I searched for "Ulster", the app suggested the category "Ulster Bank".  But when I searched for "Ulster Bank", no categories were shown.

**Steps to reproduce:** 

1. Begin uploading an image.
2. When selecting a category, search for "Ulster".  You should see "Ulster Bank" in the results.
3. Search for "Ulster Bank".  The search results say "No categories found" despite the exact search input being presented as a category in step 2.

**System logs:**

I neglected to capture logs at the time but can reproduce if they are desired.

**Device and Android version:** 

API level: 29
Android version: 10
Device manufacturer: Google
Device model: Pixel 2
Device: walleye
Network type: wifi
App version name: 2.12.3.569~b13d888
User name: Mds08011
 
**Commons app version:** 

App version name: 2.12.3.569~b13d888

**Screen-shots:** 

"Ulster" Category Search Results:
<img src="https://user-images.githubusercontent.com/8010709/74053801-7f1e5000-4991-11ea-98d7-98e871a8390b.png" width="50%">

"Ulster Bank" Category Search Results:
<img src="https://user-images.githubusercontent.com/8010709/74053803-804f7d00-4991-11ea-9fa3-c30b289497ac.png" width="50%">

**Would you like to work on the issue?**

No.

**Comment by nicolas-raoul** [comment]
Thanks for reporting!
Somehow the website seems to get it right:
<img width="809" alt="Screen Shot 2020-02-08 at 20 13 35" src="https://user-images.githubusercontent.com/99590/74084161-97848c80-4aaf-11ea-95cf-91701a45af88.png">
We should compare the requests parameters.

**Comment by ciphereck** [comment]
Can I work on this @nicolas-raoul

**Comment by nicolas-raoul** [comment]
@ciphereck Yes, thanks! Please post about your progress every day or so :-)

**Comment by ciphereck** [comment]
@nicolas-raoul Can you tell me how can I make text-based category search efficient or is there an alternative?
Also, I think this is the repo where I can make the server-side change? https://github.com/commons-app/commonsmisc

**Comment by ciphereck** [comment]
@nicolas-raoul Can you help me in optimize finding categories. I got that searchForCategories in CategoriesPresenter using streams to get the category and different stream to set the same in view. I got the high-level logic, but I'm still struggling from where exactly it's getting category results and how to optimize that.

**Comment by ciphereck** [comment]
@nicolas-raoul @misaochan @maskaravivek 
Just pinging you to give me some help on how to optimize text-based search Categories. I'm stuck on it.

**Comment by maskaravivek** [comment]
@ciphereck Did you figure out which API is been used in the app to display the search results. 

The first step would be to figure out the API and post the API URL and request parameters here on the issue thread.

**Comment by macgills** [comment]
```
    /**
     * Searches for categories with the specified name.
     *
     * @param filter    The string to be searched
     * @param itemLimit How many results are returned
     * @return
     */
    @GET("w/api.php?action=query&format=json&formatversion=2"
            + "&generator=search&gsrnamespace=14")
    Observable<MwQueryResponse> searchCategories(@Query("gsrsearch") String filter,
                                                 @Query("gsrlimit") int itemLimit, @Query("gsroffset") int offset);
```

the result then gets mapped by this
```
/**
     * Internal function to reduce code reuse. Extracts the categories returned from MwQueryResponse.
     *
     * @param responseObservable The query response observable
     * @return Observable emitting the categories returned. If our search yielded "Category:Test", "Test" is emitted.
     */
    private Observable<String> responseToCategoryName(Observable<MwQueryResponse> responseObservable) {
        return responseObservable
                .flatMap(mwQueryResponse -> {
                    MwQueryResult query;
                    List<MwQueryPage> pages;
                    if ((query = mwQueryResponse.query()) == null ||
                            (pages = query.pages()) == null) {
                        Timber.d("No categories returned.");
                        return Observable.empty();
                    } else
                        return Observable.fromIterable(pages);
                })
                .map(MwQueryPage::title)
                .doOnEach(s -> Timber.d("Category returned: %s", s))
                .map(cat -> cat.replace("Category:", ""));
    }
```

Thought this was a problem on depictions branch but it is also on master, only tested on `betaDebug`

**Comment by nicolas-raoul** [comment]
Thanks @macgills ! These methods seem to be used in "Explore" when searching for categories, but not when searching for categories during picture upload, for some reason I ignore.

Here are the queries I see in logcat at step 2 (search categories) when uploading a picture:
- Ulster: https://commons.wikimedia.org/w/api.php?action=query&format=json&formatversion=2&generator=allcategories&gacprefix=ulster&gaclimit=25&gacoffset=0 : many results, including "Ulster Bank"
- Ulster bank: https://commons.wikimedia.org/w/api.php?action=query&format=json&formatversion=2&generator=allcategories&gacprefix=ulster%20bank&gaclimit=25&gacoffset=0 : Zero results

That's our problem. We must fix our query. Maybe use the methods cited by macgills as they seem to perform better in my tests?

**Comment by macgills** [comment]
My mistake, the problems I was having with that endpoint seemed to be the same, searching `commons` returned nothing but `com` had results that clearly had "Commons" in them. I don't think that api performs better

**Comment by macgills** [comment]
Actually it is weirder than that, adding a category to an upload works fine:
```
 https://commons.wikimedia.beta.wmflabs.org/w/api.php?action=query&format=json&formatversion=2&generator=allcategories&gacprefix=commons&gaclimit=25&gacoffset=0
```
This returns a list of things with commons in them, a good few entries.


Searching for a category in explore works odd:
```
https://commons.wikimedia.beta.wmflabs.org/w/api.php?action=query&format=json&formatversion=2&generator=search&gsrnamespace=14&gsrsearch=common&gsrlimit=25&gsroffset=0 
```
Note here it is the search term `common` i only get 2 entries. Commons gets me more.
Most results on the way to spelling `commons` are empty.

I am using beta endpoints so that could be affecting it. I can't make Ulster Bank appear on either with any combination

**Comment by nicolas-raoul** [comment]
I have found that using the production is better when developing, because
beta is so different. I would suggest using the beta server only when you
really have do many nonsense write operations.

**Comment by Prince-kushwaha** [comment]
@nicolas-raoul i latest master i think this is not present in latest master

**Comment by sivaraam** [comment]
> @nicolas-raoul i latest master i think this is not present in latest master

Yeah. I could confirm that with v3.1.1~1c9267ca0, when I search for "Ulster Bank" in the category search the corresponding category does appear to be showing up. So, closing the issue.

Feel free to re-open in case you observe this again.
