### ISSUE TITLE
Encourage users by automatically creating (or adding) the category: photos by [username]?

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#3387]
I received a suggestion that adding a category "Photos by [username]" when a user uploads a photo, could potentially encourage more uploads. A lot of power-users already have a category with their name, so I wonder if extending it to other users would be okay? Or would it create too much clutter? @nicolas-raoul @VojtechDostal

**Comment by sivaraam** [comment]
Excuse my ignorance, but how is adding a "Photos by [username]" category to every photo uploaded by an user different from what [Special:ListFiles](https://commons.wikimedia.org/w/index.php?title=Special:ListFiles) does (listing all files uploaded by the user)?

I just don't see how this would encourage users to upload more images 🤔

**Comment by nicolas-raoul** [comment]
I sometimes see these categories, and I always think it is redundant and wasteful lol

This could encourage people, as it makes it a bit easier to jump to other pictures by this user, but I think that solving this problem via categories is not the best solution. How about starting to solve this problem via https://github.com/commons-app/apps-android-commons/issues/3389 instead? :-)

**Comment by misaochan** [comment]
Makes sense. I will close this, and I agree that focusing on profiles is a better idea. :)
