### ISSUE TITLE
Organize a "Nearby Places that need photos" walk?

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#3388]
A suggestion I received: An event like "let's take a walk in the city, take some photos, and upload them to Commons" would potentially sound fun and attractive to new contributors. This would be different from a workshop in that, rather than an official "tutorial" on how to use the app, it would be an outdoor exercise and would focus primarily on using Nearby. Thoughts?

@sivaraam @VojtechDostal @nicolas-raoul @neslihanturan

**Comment by sivaraam** [comment]
This sounds really interesting! It would be more practical and entertaining if we could find the appropriate place for such an event.

The place would play an important role because if there aren't enough interesting things to capture and upload then it wouldn't be fun. Nearby does show places which need images but I'm not sure if all places that need an image would be interesting enough for such an event. That's why I think we can't just pick the place indicated by Nearby as needing a lot of images. Some groundwork would have to be done to ensure the place is interesting.

Coming to Nearby, we would have to ensure that any crucial bugs in Nearby have been squashed to ensure it doesn't come back to us biting during the event 😉 I'm not sure if there are any, just wanted to mention this.

**Comment by nicolas-raoul** [comment]
Yes, I would use it :-)
Ideally the user would be able to select what distance they can/want walk, for instance 1km/2km/5km/10km/20km. The algorithm would then calculate the route, going via as many places with no photo as possible. In the countryside it might not be funny, but in most cities it should find enough places. If there are no places at all that need a picture, switching to ALL Wikidata items (including those with a picture) could be an interesting addition in a subsequent phase.
We have to find a catchy name for this feature, maybe "Adventure" or "Trail" or "Challenge" or something.

I agree with @sivaraam that Nearby bugs must be fixed first, and especially the blue dot must follow the user while they walk :-)

**Comment by neslihanturan** [comment]
This is an really interesting idea, what about suggesting this feature as a hackathon 2020 idea, if none of us are there? I think this can be implemented during a hackathon scope.

**Comment by misaochan** [comment]
Awesome, thanks for the feedback, everyone! :) It sounds like there are two different (but related) things being discussed here, though:
1. An implemented feature in the app that would calculate a route for the user
2. An organized event that is publicized, there is someone to guide everyone, everyone would do the same route. I think in this case, as @sivaraam mentions, we probably would want to scout the place and select it ahead of time, instead of using an automated algorithm

Option 1 sounds great for the hackathon. Actually, Option 2 is probably OK for the hackathon too, but it would require more organizing from someone who is attending the hackathon. :) I think we can implement Option 1 during the hackathon (if people are interested), and then organize Option 2 later. 

Yes, we would need to squash all bugs in Nearby before organizing Option 2. In fact, I think we should also have the iOS app up before organizing this event, so that everyone can be included regardless of what phone they are using. Fortunately, we have plans for this in the near future... :)

**Comment by sivaraam** [comment]
> It sounds like there are two different (but related) things being discussed here, though:

Yeah, you're right. I'm kind of curious as to how 1 came up 🤔 Doesn't matter, though.

> An implemented feature in the app that would calculate a route for the user, which is what I think @nicolas-raoul and @neslihanturan are talking about.

An algorithm that plans the route does sound interesting. Though I also slightly suspect that the [devil is in the detail](https://en.wikipedia.org/wiki/The_devil_is_in_the_detail).

> I think we should also have the iOS app up before organizing this event, so that everyone can be included regardless of what phone they are using. Fortunately, we have plans for this in the near future... :)

Hey, this sounds cool! I didn't know an iOS app was coming up. That would really be a good thing as there are indeed a lot of iOS users out there.

**Comment by misaochan** [comment]
> An algorithm that plans the route does sound interesting. Though I also slightly suspect that the [devil is in the detail](https://en.wikipedia.org/wiki/The_devil_is_in_the_detail).

Haha, it is possible. I do think that if we don't have strict requirements for the route it would be doable. We don't necessarily need to solve the traveling salesman problem...

> Hey, this sounds cool! I didn't know an iOS app was coming up. That would really be a good thing as there are indeed a lot of iOS users out there.

Yes! Well, at least, we have a proposal in the works... I will link you when it's up. ;)

**Comment by sivaraam** [comment]
> > An algorithm that plans the route does sound interesting. Though I also slightly suspect that the [devil is in the detail](https://en.wikipedia.org/wiki/The_devil_is_in_the_detail).
> 
> Haha, it's possible that that could be the case. I do think that if we don't have strict requirements for the route it would be doable.

Exactly. But one problem is that the route planned might not be an optimal one. That should hopefully be fine. Just speculating 😉

> We don't necessarily need to solve the traveling salesman problem...
>

Yeah. We would just be fine if we're cautious in not getting lost in the details when implementing the solutions. We should plan to improve the algorithm in iterations rather than trying to get the best version in the first attempt. 
 
> > Hey, this sounds cool! I didn't know an iOS app was coming up. That would really be a good thing as there are indeed a lot of iOS users out there.
> 
> Yes! Well, at least, we have a proposal in the works... I will link you when it's up. ;)

Sure! I'll be glad to be involved and contribute in ways I could regardless of the fact that I don't own an iPhone :wink:

**Comment by sivaraam** [comment]
Just wanted to share a page which seemed related to this: https://meta.wikimedia.org/wiki/Wikiexpedition

**Comment by misaochan** [comment]
Oh, so that's the name of what we were talking about... 😄 

Thanks for the resource! We still have about a year before we start planning this (perhaps longer, depending on the duration of the WMF offline events ban...), but it is great to have more info at our fingertips for when we start.

**Comment by misaochan** [comment]
After v4 release (soon, hopefully!), it will be time to start planning the publicity measures, notably this task and #2428 . 

Based on https://meta.wikimedia.org/wiki/Grants:Risk_assessment_during_COVID-19 , unless we limit this event to 10 people or less, we will have to go through a rather complicated risk assessment and apply for approval from the Foundation. So, IMO our options are to either run this for 9 people (+1 for the organizer) and turn any extra participants away, or to just focus all our attention on #2428 instead, which is virtual. 

I would personally be in favour of the latter, but interested in others' opinions. @neslihanturan @madhurgupta10 @nicolas-raoul @sivaraam ?

**Comment by VojtechDostal** [comment]
> Based on https://meta.wikimedia.org/wiki/Grants:Risk_assessment_during_COVID-19 , unless we limit this event to 10 people or less, we will have to go through a rather complicated risk assessment and apply for approval from the Foundation. So, IMO our options are to either run this for 9 people (+1 for the organizer) and turn any extra participants away, or to just focus all our attention on https://github.com/commons-app/apps-android-commons/issues/2428 instead, which is virtual.

Have you seen the latest update on this? https://diff.wikimedia.org/2022/03/29/announcement-of-the-removal-of-the-covid-travel-policy/

**Comment by misaochan** [comment]
@VojtechDostal That's great news, thanks for sharing! :) I had no idea about that, I guess the grant pages weren't updated yet.

Incidentally, do we know if any hackathons/meetups are currently being planned for this year, or will that be too soon? If they are, it would be fantastic to be able to tag this on to one of those perhaps.

**Comment by VojtechDostal** [comment]
> Incidentally, do we know if any in-person hackathons/meetups are currently being planned for this year, or will that be too soon? If they are, it would be fantastic to be able to tag this on to one of those perhaps.

I am not aware of any. Wikimedia Hackathon is mostly happening online this year (https://m.mediawiki.org/wiki/Wikimedia_Hackathon_2022).

**Comment by neslihanturan** [comment]
Hello all, here is the report of the photowalk that I facilitated last weekend:

- 10 people joined to the walk, 7 uploaded pictures to Commons
- 143 photos are uploaded
- We worked as 5 groups, each has 2 people, 
- Here is the report tweet (I edited video of the event too): https://twitter.com/oydorgtr/status/1531550037477666816
- Here is the call tweet (also called from telegram): https://twitter.com/oydorgtr/status/1530175574383132672
-Here is the dashboard https://outreachdashboard.wmflabs.org/courses/%C3%96zg%C3%BCr_Yaz%C4%B1l%C4%B1m_Derne%C4%9Fi_and_Yer%C3%A7izenler/Photo_walk_%C4%B0stanbul1/uploads

**Comment by neslihanturan** [comment]
Also here is the wikishootme results: 
![animation](https://user-images.githubusercontent.com/3127881/171409205-4b5c02e3-1be4-4e9c-8e95-79c2fe37d292.gif)

**Comment by misaochan** [comment]
Fantastic job, thanks a lot @neslihanturan ! :)
