### ISSUE TITLE
Move from v1.x to v2.x

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#339]
As I'm coming up to Phase 3 (increasing publicity) of my IEG, I figure it might be time to move from v1.x to v2.0 (as suggested by @nicolas-raoul , that is a good reason for requesting publicity :) ). We're already 40 versions into 1.x, anyway.

Anyone have any thoughts on this?

**Comment by nicolas-raoul** [comment]
:champagne:

**Comment by tobias47n9e** [comment]
+1

**Comment by misaochan** [comment]
Whoops, that got sidetracked a bit. Planning to release 2.0 this week, and will be starting to publicize soon. Still plenty of room for improvement of course, but we're a long way from the early version 1s, thanks to everyone here! :)

**Comment by misaochan** [comment]
Done!
