### ISSUE TITLE
Zoom level gets reset every few seconds

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#3391]
Open app
Nearby
Zoom in to alley level
Wait a few seconds
Problem: Zoom level gets reset (when updating the position of the blue dot, I guess)

**Comment by madhurgupta10** [comment]
@nicolas-raoul I am facing this issue!

**Comment by kbhardwaj123** [comment]
This issue does not exist for the 2.12.3 play store release however

**Comment by sivaraam** [comment]
I think the situation is actually worse than the just the zoom level getting reset. In nearby, if I'm exploring a different place far from my current location when I'm on the move, the map moves back to my current location when the location marker updates. This is intrusive to my exploration. I suppose it would be better to not update the location marker when the user is exploring a place far from his current location. But I'm not sure what would be a reliable way to detect this. :thinking: 

That said, please let me know in case I'm speaking of a totally different issue :wink:

**Comment by ashishkumar468** [comment]
@nicolas-raoul, is this happening on the current master or one of the 2.12 releases?

**Comment by nicolas-raoul** [comment]
@ashishkumar0207 2.12.3.574~eb40051 which I believe is the latest alpha. Thanks! :-)

**Comment by avivith** [comment]
Is this issue solved, or can I work on it?
