### ISSUE TITLE
Wikimedia Hackathon ideas

### ISSUE THREAD

**Issue by neslihanturan** [commons-app/apps-android-commons#3394]
**Summary:** 

Well, hackathon is coming:) This year target topic is GLAM. We can start to think of suitable projects. Remember, peer review feature is implemented during a hackathon:)

**Comment by sivaraam** [comment]
Looks like the Hackathon is still "on". This time it's **remote**! For more information, see:

* [[Wikitech-l] Remote hackathon (May 9 - 11, 2020)](https://lists.wikimedia.org/pipermail/wikitech-l/2020-April/093312.html)
* [Wikimedia Hackathon 2020/Remote Hackathon - MediaWiki](https://www.mediawiki.org/wiki/Wikimedia_Hackathon_2020/Remote_Hackathon)

Just spreading the word :)

**Comment by misaochan** [comment]
Awesome, thanks for the news @sivaraam ! I see that Multichill (one of the WLM guys) is attending, and he has previously expressed interest in collaborating with us on campaign integration into our app. If a few of us are interested in participating, maybe I could ping him?

**Comment by Rishavgupta12345** [comment]
@nicolas-raoul this issue is useless you can close this
