### ISSUE TITLE
Changing main activity to list/map of nearby places that need photos (far future)

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#340]
Currently the main activity is a list of the user's past uploads, with the upload, camera, and nearby functions relegated to small icons on the ActionBar (and that is in the best case scenario with a wide screen - on small phones some of them are in the overflow menu). It looks pretty, but I wonder if that is the best use of main screen real estate?

In the far future (after the Nearby feature has been suitably improved), what do you think of changing the main activity to a list/map of nearby places that need photos, with the upload and camera buttons taking up a more prominent location on the main screen? The current list of past uploads could still exist, but instead would be accessible via the ActionBar (or a nav drawer if we get around to that).

This would be a pretty big change though, so I am hesitant to propose it without strong userbase support.

**Comment by nicolas-raoul** [comment]
I agree. The main purpose of the app should not be browsing one's past uploads (although having a way to check one's uploads is good, especially in case where I have a great number of picture and upload them little-by-little whenever I have free time.

**Comment by misaochan** [comment]
Definitely, even if the main screen changes, the option to view past uploads should still exist.

**Comment by misaochan** [comment]
We can probably close this for the time being as Nearby will be much more accesible with #725
