### ISSUE TITLE
Tower of London teleportation

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#3400]
Sometimes when going back to Nearby, my map is centered around the Tower of London, despite the fact that I am in Japan.
If anyone faces the same problem, please comment.

Version 2.12.3.574~eb40051

**Steps to reproduce:** 
Not sure. I will update this issue if I find out.

![Screenshot_20200211-114927_Commons](https://user-images.githubusercontent.com/99590/74226253-95187180-4cff-11ea-9ffc-ed9714d63899.jpg)

**Comment by Glitch101** [comment]
Hey @nicolas-raoul. This is similar to the bug I am working on(#3397) . In my case, this happens when I open nearby with my GPS turned off.

**Comment by kbhardwaj123** [comment]
It happened for me as well. Actually my GPS was on but i was connected to a slow wifi network, however it disappeared after a couple of seconds, i was unable to capture it because of the same reason

**Comment by nicolas-raoul** [comment]
@Glitch101 Thanks for the insight! Please not that I never turn the GPS off nor prevent the app from using it,  and I was always on a strong LTE network.

**Comment by Glitch101** [comment]
Hi there @nicolas-raoul. Were you able to reproduce this issue? Actually, I was about done on issue #3397 and was thinking that I might as well take a look at this one since they are similar. Do let me know if you find anything.

**Comment by nicolas-raoul** [comment]
I used the app a lot this weekend and did not get the bug, I guess it has been fixed :-) Thanks!
