### ISSUE TITLE
Position of privacy policy on the login screen

### ISSUE THREAD

**Issue by yashk2000** [commons-app/apps-android-commons#3403]
**Summary:** 

Currently, in the login screen, the privacy policy button is at the absolute bottom of the screen. There is no gap between the bottom of the screen and the button, making it's positioning very awkward.

**Steps to reproduce:** 

See the position of the privacy policy button in the login screen.

**Device and Android version:** 

Nokia 7 plus, android 28
 
**Commons app version:** 

2.12.3-debug-master

**Screenshots:** 

![screencap](https://user-images.githubusercontent.com/41234408/74331816-7cb95d00-4dba-11ea-915a-ab1f055189ff.png)

**Would you like to work on the issue?**

Yes.

**Comment by yashk2000** [comment]
@nicolas-raoul @neslihanturan @maskaravivek @misaochan while going through the code of the application, I noticed that in several places, the code-style of the app might not be followed. For example, in some places the following style is used:

`if(condition){ }`

In some other places the following style is used:

`if (condition) { }`

We should be using the second type of style since we are following the Google Java Code Style. 
In order to fix this, and prevent any future discrepancies, we should consider using the **[spotless](https://github.com/diffplug/spotless/tree/master/plugin-gradle)** gradle plugin. Once added, on running the `spotlessApply` command just once, it will automatically fix the existing faults in the code. And we can also add the check(`spotlessCheck`) to Travis so that if while contributing in future commits the style isn't followed, the Travis check won't pass. 
This will enhance the maintainability and code style of the app a lot. 
Should I create an issue regarding this and send a pr?

**Comment by maskaravivek** [comment]
> @nicolas-raoul @neslihanturan @maskaravivek @misaochan while going through the code of the application, I noticed that in several places, the code-style of the app might not be followed. For example, in some places the following style is used:
> 
> `if(condition){ }`
> 
> In some other places the following style is used:
> 
> `if (condition) { }`
> 
> We should be using the second type of style since we are following the Google Java Code Style.
> In order to fix this, and prevent any future discrepancies, we should consider using the **[spotless](https://github.com/diffplug/spotless/tree/master/plugin-gradle)** gradle plugin. Once added, on running the `spotlessApply` command just once, it will automatically fix the existing faults in the code. And we can also add the check(`spotlessCheck`) to Travis so that if while contributing in future commits the style isn't followed, the Travis check won't pass.
> This will enhance the maintainability and code style of the app a lot.
> Should I create an issue regarding this and send a pr?

It is a very good suggestion indeed. I wasn't aware of such a plugin. Do you mind creating a separate issue for this? It is not related to this issue.

**Comment by yashk2000** [comment]
@maskaravivek sure. On it :rocket:
