### ISSUE TITLE
Improve Quick start guide for Developers documentation

### ISSUE THREAD

**Issue by Mishrasubha** [commons-app/apps-android-commons#3411]
Instant run is missing in Android Studio 3.5 and is replaced with Apply Changes in Run. So, the documentation needs to be updated.

**Comment by maskaravivek** [comment]
@Mishrasubha Can you provide more details about the issue?

**Comment by Mishrasubha** [comment]
It is written in Quick start guide for Developers documentation to Disable Instant Run in Android studio by doing the following steps:
In the menu bar, click File > Settings
In Build, Execution, Deployment > Instant Run uncheck the Enable Instant Run checkbox
Click OK to save and exit from the settings window.
But for Android Studio 3.5 this has been removed and replaced with "Apply Changes".
![upload](https://user-images.githubusercontent.com/32950636/74591942-8e149a80-5042-11ea-90c1-3f4ba78efdda.png)

**Comment by Mishrasubha** [comment]
It is written in Quick start guide for Developers documentation to Disable Instant Run in Android studio by doing the following steps:
In the menu bar, click File > Settings
In Build, Execution, Deployment > Instant Run uncheck the Enable Instant Run checkbox
Click OK to save and exit from the settings window.
But for Android Studio 3.5 this has been removed and replaced with "Apply Changes".
![upload](https://user-images.githubusercontent.com/32950636/74591956-abe1ff80-5042-11ea-9aa6-76ec95fac7e6.png) 
![apply changes](https://user-images.githubusercontent.com/32950636/74591974-ce741880-5042-11ea-84c6-26182b5c5606.png)

**Comment by maskaravivek** [comment]
Okay thanks for pointing out the issue.

**Comment by maskaravivek** [comment]
@misaochan This is another instance where it would have been great if the volunteers would have been able to help us update the documentation. Given the tight control we want for our docs, we can probably consider some workaround for letting volunteers contribute to wiki documentation. 

One approach is described here where people maintain a separate fork for the wiki. https://stackoverflow.com/questions/10642928/how-to-pull-request-a-wiki-page-on-github

**Comment by misaochan** [comment]
@maskaravivek I agree. It's a pity GitHub does not have that option, at the very least they should be able to submit pull requests to it! 

I actually wonder if we can/should migrate to MD files instead. That way they can be maintained with pull requests like the rest of the repo. The solutions mentioned in your SO thread would have a higher maintenance overhead IMO, especially if many small changes are made.

**Comment by domdomegg** [comment]
I've fixed the docs, just removed the bit about Instant Run now the new android gradle plugin fixes the underlying issue (see #3443)

I've been thinking about the wiki, and actually think the best idea would be a mix of the two: have a seperate repo, where we store MD files. I think having it in the main repo doesn't make too much sense (as at the moment changes are quite heavy, as Travis will build an android build for every small change) - plus it means we can be less tight with reviews etc. before merging as it's docs only.

If people are happy with that propsal I'm happy to create it and migrate the existing wiki over (shouldn't be too hard, as under the hood it's already a git repo).

**Comment by maskaravivek** [comment]
I am happy with this proposal. Let us wait for @misaochan's opinion.

**Comment by misaochan** [comment]
I'm happy with this as well. We can update our readme.md to point users to the documentation repo, too. :)

Thanks @domdomegg !

**Comment by sivaraam** [comment]
> I'm happy with this as well. We can update our readme.md to point users to the documentation repo, too. :)

Oh, and don't forget to link to it from the then main page of the wiki for better reach!

**Comment by domdomegg** [comment]
I've moved the wiki to [commons-app/documentation](https://github.com/commons-app/documentation/blob/master/android/README.md) - let me know what you think. Always happy to change it with feedback, and the easiest time to do that is now :)

If everyone's happy with how that seems (at least for now) I'll update the links from this repo's README.

**Comment by misaochan** [comment]
Thank you for your work @domdomegg ! The new repo looks great IMO. :)

**Comment by sivaraam** [comment]
@domdomegg The repo is really good and well organized. I love the way you've used the emojis. It gives it a really nice touch. 🙂 Great job ❣️

Just a few suggestions:
* I see that the specific docs [[1]](https://github.com/commons-app/documentation/blob/master/android/How-to-install-and-use-the-app.md) [[2]](https://github.com/commons-app/documentation/blob/master/android/Volunteers-welcome!.md) don't have a header at the top. Is there any reason for this?
* Wouldn't it be nice to organize the pages into folders mirroring the way they are categorized in the wiki page?

I'll be glad to send a PR (which is the whole point of introducing the repo!) that makes the changes related to the suggestions above. Just wanted to get some inputs/opinions before I do that. 🙂

**Comment by domdomegg** [comment]
> * I see that the specific docs [[1]](https://github.com/commons-app/documentation/blob/master/android/How-to-install-and-use-the-app.md) [[2]](https://github.com/commons-app/documentation/blob/master/android/Volunteers-welcome!.md) don't have a header at the top. Is there any reason for this?

No, just that GitHub doesn't store wiki page's titles in the markdown files you export them as - I'm planning on writing a script to add all the titles soon.

> * Wouldn't it be nice to organize the pages into folders mirroring the way they are categorized in the wiki page?

Yeah that would be good - just make sure to update the links :)

> I'll be glad to send a PR (which is the whole point of introducing the repo!)

Feel free to tag me for a review :)

**Comment by maskaravivek** [comment]
Thanks a lot @domdomegg :)
