### ISSUE TITLE
Snackbar on clicking add to bookmarks. 

### ISSUE THREAD

**Issue by yashk2000** [commons-app/apps-android-commons#3416]
**Summary:** 

A snackbar with an option to directly open the bookmarks activity should be displayed when the user presses the add to the bookmarks icon. Similarly, when the user removes an item from bookmarks a snack bar should be shown notifying that the item has been removed from bookmarks. 

**Steps to reproduce:** 

Open a photo from the explore section. Click on the star icon to add to bookmarks.
Now a snackbar should be shown saying "Item added to bookmarks" along with an action to open the bookmarks activity. 

**Device and Android version:** 

Nokia 7 Plus, Android 10
 
**Commons app version:** 

2.12.3-debug-master

**Would you like to work on the issue?**

Yes.

**Comment by yashk2000** [comment]
I have already sent a pr for the issue. I waited until the enhancement label had been added. There were no other comments, so once the label was added, I thought that it was fine to work on it since the changes were direct.
Apologies for the misunderstanding.

**Comment by yashk2000** [comment]
@misaochan @maskaravivek @nicolas-raoul how should we proceed with this issue. The thing I had in mind has been done in the pr I sent. If anything changes are needed, please let me know.

**Comment by ashishkumar468** [comment]
Showing a snack bar is good, although,  personally I don't see the need to add a link to go to the bookmarks screen.

**Comment by yashk2000** [comment]
@misaochan @maskaravivek @nicolas-raoul how should we proceed with this issue. The thing I had in mind has been done in the pr(tests are failing which will be fixed) I sent. If anything changes are needed, please let me know.

**Comment by misaochan** [comment]
I agree with @ashishkumar468 , I don't think the link in the snack bar is necessary, as Bookmarks is directly accessible from the nav drawer.

**Comment by yashk2000** [comment]
Ok, I will remove that action. 
I had another question regarding the failing tests. 

Since I changed the signature of the updateBookmarks() function, they need to be changed in the test too and for that, we might need to make quite a few changes. So I can either make those changes or figure out a different way to show the snack bar.

Which option should I proceed with?
