### ISSUE TITLE
Typo in peer review info

### ISSUE THREAD

**Issue by yashk2000** [commons-app/apps-android-commons#3417]
**Summary:** 

Commons is spelled as Commoms in the peer review info menu.

**Steps to reproduce:** 

Go to review.
Click on the info icon.
Commons is spelled as Commoms.

**Device and Android version:** 

Nokia 7 Plus, Android 10
 
**Commons app version:** 

2.12.3 debug-master

**Would you like to work on the issue?**

No, anyone can solve this is as a first issue.

**Comment by gouri-panda** [comment]
Can i work on this?
