### ISSUE TITLE
Commons app future plans - Project Grant proposal for 2020 is up!

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#3420]
Hi all, our tentative future plans for Jun 2020 - May 2021 are out! 
https://meta.wikimedia.org/wiki/Grants:Project/Commons_app/Commons_app_Android_and_iOS . Basically, we are hoping to release an iOS app, add a few new features and stability/code quality to our Android app, and do some publicity stuff.  :)

If you have any concerns about anything proposed in that proposal, feel free to ping me here or talk about it in the **Discussion tab**. If you see any typos or mistakes, please ping me too! 

If you are in support of our plans and would like to help us get them approved, there are a couple of things you can do:
- **Endorse the proposal:** Log in and click "Endorse" in the Probox at the top. Or you can manually edit the "Endorsements" section with your signature, too.
- **Sign up as a volunteer**: Anyone can join us as a volunteer (there are no time obligations or anything else required) by clicking "Join" in the Probox at the top or manually editing the "Volunteers" section. But if you prefer to just unofficially volunteer without signing up, that is totally fine too. ;)

You may notice that there is an empty "contractor" slot. I will put out the call here for that job position if/when the grant is approved (we will probably know around May).

Thank you all for being with us thus far. :)

@sivaraam @domdomegg @ujjwalagrawal17 @tobias47n9e @Deskana @ilgazer @VojtechDostal @nicolas-raoul @maskaravivek

**Comment by sivaraam** [comment]
Great job with the proposal, all!

Just wondering, can someon share some important dates related to the proposal? Like the last date before which the endorsements should be made for the proposal?

**Comment by misaochan** [comment]
Thanks @sivaraam ! 

There isn't really a fixed date for endorsements I think - all I have from https://meta.wikimedia.org/wiki/Grants:Project is that "community review" ends on March 16, but in my experience the grants committee would already have started reading the proposals before that point. So I guess my answer would be "as soon as possible, please!" :)

**Comment by sivaraam** [comment]
@misaochan Looks like there's a new blog now to Wikimedia technical blog now. It can be found at [[[WM:TECHBLOG]] – Open Source for Open Knowledge](https://techblog.wikimedia.org/).

See also:
* [[Wikitech-l] New Wikimedia Technical Blog](https://lists.wikimedia.org/pipermail/wikitech-l/2020-March/093250.html)
* [Wikimedia technical blog editorial guidelines - MediaWiki](https://www.mediawiki.org/wiki/Wikimedia_technical_blog_editorial_guidelines)

Sharing this as you mentioned about writing for the Wikimedia blog in the Grant proposal and thought this would be relevant.

**Comment by misaochan** [comment]
@sivaraam thank you, that is useful! Do you know if the process for submitting an article remains the same?

**Comment by sivaraam** [comment]
@misaochan I'm not aware of the details but I presume the following wiki page contains the details you would be looking for: [Wikimedia technical blog editorial guidelines#Publishing on the Tech blog](https://www.mediawiki.org/wiki/Wikimedia_technical_blog_editorial_guidelines#Publishing_on_the_Tech_blog)

Let me know if I'm missing something.

**Comment by misaochan** [comment]
Update: The new grant has been approved. :) WMF declined funding for an iOS app but gave us the opportunity to modify the proposal, so I removed the iOS component as requested by them and added campaigns. 

They have also requested significant increases to the testing and stability goals. To that end, we have additional funding that we can allocate for this purpose, and we can hire an additional contractor. In the coming weeks I will be putting up an issue with further details, so if anyone here is interested, check back soon. :)

**Comment by sivaraam** [comment]
> Update: The new grant has been approved. :)

Great! 🎉 

> WMF declined funding for an iOS app but gave us the opportunity to modify the proposal, ...

That's sad. There was so much hopes for the iOS app as one could see from the endorsements. I'm curious to know the reason, if possible.

> ... so I removed the iOS component as requested by them and added integration for campaigns (specifically WLM).

Anyways, a better integration with campaigns would be a nice addition too. Though this integrations needs to be done with caution so that it provides a seamless experience for both users interested and not interested in participating in the campaign.

**Comment by misaochan** [comment]
> That's sad. There was so much hope for the iOS app as one could see from the endorsements. I'm curious to know the reason, if possible.

Yeah, I'm sad about that too. :( The reason they gave us was that they are concerned about maintenance of an additional app after the grant period is over.

> Anyways, a better integration with campaigns would be a nice addition too. Though this integrations needs to be done with caution so that it provides a seamless experience for both users interested and not interested in participating in the campaign.

Yes. :) We are currently talking to WLM organizers about it, and we will open up discussions in mailing lists etc soon. The plan is to have something like a Nearby map filter that other users can just not select if they don't want to participate.

**Comment by misaochan** [comment]
The contractor job posting is up #3840 . :) Closing this issue.
