### ISSUE TITLE
"Set as Wallpaper" is not working properly

### ISSUE THREAD

**Issue by madhurgupta10** [commons-app/apps-android-commons#3425]
**Summary:** 
"Set as Wallpaper" is not working properly. (Very slow)

**Steps to reproduce:** 
Go to any image and try setting it as a wallpaper using the built-in option.

**Device and Android version:** 
Tested on two devices, Mi A2 on Android 10 and Google Pixel 2 on Android 7
 
**Commons app version:** 
latest-beta-debug-master

**Would you like to work on the issue?**
Yes

**Comment by maskaravivek** [comment]
Assigned to you.

**Comment by madhurgupta10** [comment]
@maskaravivek Few things I found:

The set wallpaper is working but not properly, we are unable to see the changes.

1. If the image is used to set the wallpaper earlier then the wallpaper will set instantaneously. Maybe due to a cached copy.
2. If it is a new image then it takes a very long time to set the wallpaper, If I close the app before that I guess the process will cancel.

Solution:
I think adding a loader might be a good option, because the time to set wallpaper depends on network speed, size of image and user's phone processor.

**Comment by maskaravivek** [comment]
Yes, you are right. Wallpaper option was added by me as a quick add on (see #1525). Yes it would be great if we could add a loader so that the user knows that something is going on in the background. 

Also, a success and failure toast might he helpful.
