### ISSUE TITLE
"Archived" notifications should be referred to as "Read"

### ISSUE THREAD

**Issue by 6point022** [commons-app/apps-android-commons#3426]
**Summary:** 

"Read" notifications are referred to as "archived" notifications. However, this is inconsistent with how the website displays the notifications. 

![image](https://user-images.githubusercontent.com/44764339/75116082-9dbb6100-568a-11ea-844f-989ddea01881.png)
 
**What did you expect the app to do, and what did you see instead?**

When you open archived notifications, the option to go back says `View unread` which is again, inconsistent. We should either refer to notifications as  _archived_ and _unarchived_, or _read_ and _unread_. In my opinion, we should follow the latter labelling.

![image](https://user-images.githubusercontent.com/44764339/75116125-22a67a80-568b-11ea-835a-8efbe8783f74.png)

**Commons app version:** 

2.12.0-debug-master~d0d663578

**Would you like to work on the issue?**

Yes, if we can agree the issue is genuine then I'd like to work on this.

**Comment by sivaraam** [comment]
This looks like a good change to me 🙂

**Comment by madhurgupta10** [comment]
@sivaraam I agree. It makes more sense to change the name to **read**

**Comment by maskaravivek** [comment]
As far as I remember we used the word "Archived" as this is what the Wikipedia app uses. While building the notifications feature, we tried to follow the same user experience/behavior as the Wikipedia app. 

Before making changes lets double-check the following: 
- the terminology Wikipedia app is using
- the behavior in our Commons app ie. are all the notification in "Archived" actually marked as read or not.

**Comment by 6point022** [comment]
> * the terminology Wikipedia app is using

It indeed uses the word "Archived". I find it strange though, given that the website doesn't follow this terminology.

> * the behavior in our Commons app ie. are all the notification in "Archived" actually marked as read or not.

Yes, I confirmed this by checking the unread and archived notifications in my account through the app and the website, and they match.

**Comment by maskaravivek** [comment]
Thanks for checking both these @6point022. Let us get some more opinions and if everyone agrees then I am okay with this change.

**Comment by sivaraam** [comment]
> As far as I remember we used the word "Archived" as this is what the Wikipedia app uses. While building the notifications feature, we tried to follow the same user experience/behavior as the Wikipedia app.

That's an interesting point. I went searching for the rationale behind using "Archived" in [phabricator](https://phabricator.wikimedia.org/). Here are some related tasks that I could find:

* [⚓ T201933 Add a Notifications UI to the Android app](https://phabricator.wikimedia.org/T201933)
* [⚓ T123155 [EPIC] Echo notifications on Wikipedia mobile apps (Android & iOS)](https://phabricator.wikimedia.org/T123155)

I don't speak for them but from what I understand from those tasks and from using the app, they've used "Archived" as they provide a flow in which you could treat the list of unread notifications as kind of a backlog of notifications that you would like to get back to. They also provide ways to move a notification "to" and "from" the archive. We could ask them about the rationale, if necessary.

That said, I don't think the commons app provides a way to move the notifications "from" the archive to the "unread" group. So, I don't think the commons app is providing the "same user experience/behavior as the Wikipedia app" yet. 😉 

As we are show the "Unread" notifications and only provide a way to mark them as read without anyway to mark them as "Unread" like the Wikipedia app, I think it makes sense to do this change.

**Comment by 6point022** [comment]
@misaochan @macgills I'd really appreciate your inputs to proceed with this issue.

**Comment by macgills** [comment]
I say do it

**Comment by misaochan** [comment]
I'm on board with it. :)
