### ISSUE TITLE
Tabs don't occupy the complete width in landscape mode

### ISSUE THREAD

**Issue by gupta-anmol** [commons-app/apps-android-commons#3431]
**Summary:** 

Home, Explore and Bookmarks pages have two tabs each. In portrait mode, both tabs occupy half of the whole width. However, when the screen is rotated, they remain at the centre of the page and don't utilize the whole width. Every app I have tried adjusts tab width according to the screen orientation.

**How can we reproduce the issue?** 

Open the app and change orientation to landscape mode.

**What did you expect the app to do, and what did you see instead?**

Currently, it looks like this.

![image](https://user-images.githubusercontent.com/44764339/75149016-035d2b00-5727-11ea-9b20-caea6e7fcb7f.png)

I expect it to look like this for each of the three activities (and, in fact, for every activity with a TabLayout).

![image](https://user-images.githubusercontent.com/44764339/75149037-0e17c000-5727-11ea-9612-9a935b650487.png)

**Device and Android version:** 

Redmi Note 5 Pro
MIUI version 11
Android 9
 
**Commons app version:** 

2.12.0-debug-master~d0d663578

**Would you like to work on the issue?**

Yes, if we can agree the issue is genuine then I'd like to work on this.

**Comment by FawziyahAlebiosu** [comment]
oh!! Okay wow I did NOT know that developers can control what a layout looks like in landscape format, and now I went down a rabbit hole researching landscape variations. 
Have you been notified if it is a genuine issue that can be worked on? I know it seems like a low-priority issue, but it'd still be interesting to work on, i think. 

If you're no longer interested, I'd like to ~play around with this~ and change it. - if I never knew

**Comment by 6point022** [comment]
> Have you been notified if it is a genuine issue that can be worked on?

No, we haven't had any discussion on this issue. Please tag and ask a collaborator/member before starting to work on it.

> If you're no longer interested, I'd like to ~play around with this~ and change it.

Sure, you can take up the issue once you have had it approved. :)

**Comment by FawziyahAlebiosu** [comment]
@nicolas-raoul @maskaravivek can I try working on this?

**Comment by nicolas-raoul** [comment]
Sorry, I just saw this.
Is it really a problem?
What official Android guidelines says that it should look like this?
Thanks :-)

**Comment by misaochan** [comment]
The screenshot previews are broken, but I clicked through and I do feel like https://user-images.githubusercontent.com/44764339/75149037-0e17c000-5727-11ea-9612-9a935b650487.png looks better.

**Comment by macgills** [comment]
These are [clustered fixed tabs](https://material.io/components/tabs/#fixed-tabs)

> Clustered fixed tabs should be used in wide horizontal layouts, such as landscape mode.

I see no issue with usage. They could be aligned right to favour the right handed? I don't have a strong opinion here.

**Comment by nicolas-raoul** [comment]
I believe there is no issue here, so I close for now. If you believe something must be fixed, please comment, preferably linking to official Android guidelines. Thanks all!
