### ISSUE TITLE
Integrate Google Play Services or not for showing the user location off dialog?

### ISSUE THREAD

**Issue by Glitch101** [commons-app/apps-android-commons#3435]
**Summary:** 

In order to show the user a dialog box as needed in issue #3397, we could also integrate the Google Play Services to do that just like Google Maps prompt us.
I wanted to discuss this with the team before I move ahead and send my PR.

Just for the sake of discussion, I would suggest that we do not integrate Play Services as they have not been integrated into the Commons app before and it seems overkill to do that just for showing a dialog  box as the same could be accomplished without them https://github.com/commons-app/apps-android-commons/issues/3397#issuecomment-590121007

### Comparing both options:
![compare](https://user-images.githubusercontent.com/46349662/75273518-050e1800-5827-11ea-9051-8dc52a4d6979.png)

### Working of the approach without Play Services:
![Screenshot from 2020-02-25 23-21-41](https://user-images.githubusercontent.com/46349662/75273563-1f47f600-5827-11ea-92f8-524d0d22c7d3.png)

![Screenshot from 2020-02-25 23-22-23](https://user-images.githubusercontent.com/46349662/75273579-2838c780-5827-11ea-8257-4f5ec9fc4d76.png)

**Comment by maskaravivek** [comment]
Yes, I agree. Let's not integrate google play services just for the location dialog. As we also support devices that don't have google play services, we would need to handle a different flow for them. 

I don't see much UX improvement with this addition.

**Comment by Glitch101** [comment]
>Yes, I agree. Let's not integrate google play services just for the location dialog. As we also support devices that don't have google play services, we would need to handle a different flow for them.

>I don't see much UX improvement with this addition.

Great! I would then go ahead and send my PR. Thanks @maskaravivek :)

**Comment by maskaravivek** [comment]
Can you update the opening comment of #3397 to briefly explain the final approach that has been decided?

**Comment by Glitch101** [comment]
>Can you update the opening comment of #3397 to briefly explain the final approach that has been decided?

Sure. Should I also attach the flow charts that I attached above or will it be fine without them?

**Comment by maskaravivek** [comment]
Thanks for putting in the efforts for creating the flowcharts. If any of these flowcharts represent the final approach, feel free to add it to the issue. You can skip the other ones :)

**Comment by sivaraam** [comment]
@Glitch101 The flow charts are really nice! Speaking of flow charts, just wanted to mention that the flow charts could use some improvements the consistency. Let me know if you're interested in hearing. Feel free to ignore as they're good the way they are 🙂

**Comment by Glitch101** [comment]
> @Glitch101 The flow charts are really nice! Speaking of flow charts, just wanted to mention that the flow charts could use some improvements the consistency. Let me know if you're interested in hearing. Feel free to ignore as they're good the way they are

Ignore and miss the chance to get some real and useful feedback. **No sire!**
I am all ears :)

**Comment by Glitch101** [comment]
> @Glitch101 The flow charts are really nice! Speaking of flow charts, just wanted to mention that the flow charts could use some improvements the consistency. Let me know if you're interested in hearing. Feel free to ignore as they're good the way they are

Still waiting for that feedback:^)

**Comment by sivaraam** [comment]
@Glitch101 I appreciate your eagerness. Sometimes delay is unavoidable when you want to ensure that the feedback is constructive. Be patient. You'll get it soon 🙂

**Comment by Glitch101** [comment]
> @Glitch101 I appreciate your eagerness. Sometimes delay is unavoidable when you want to ensure that the feedback is constructive. Be patient. You'll get it soon

Sure. I thought that maybe you forgot or didn't see my comment.

**Comment by sivaraam** [comment]
Ok. Here's the feedback I was speaking of. It's only general feedback about some elements of the flowchart and not about any flowchart in particular. So, I'm not sure how interesting it would be. It might possibly sound like being pedantic/nitpicking. You can safely ignore it, if it does ☮️ 🕊 

Let me clarify one thing about one of my previous comments before I go into the feedback. 

> Speaking of flow charts, just wanted to mention that the flow charts could use some improvements the consistency.

By "consistency", I refer to the "consistency" of the way in which flowchart symbols were used in your flowcharts.

First of all, let me share a reference for the various symbols used in flowcharts which I refer to below. The ["Common symbols" section](https://en.wikipedia.org/wiki/Flowchart#Common_symbols) of the Wikipedia page on [flowcharts](https://en.wikipedia.org/wiki/Flowchart) covers it nicely.

### The feedback
In the first flow chart you've split the "Using Google Play Services" and "Not using play services" without a decision symbol. It would've been nice if you had used a decision symbol called "Using Google Play services?". A similar comment goes to "Location Off" process box in the second diagram.

In the second diagram, you've merged the two flows to show the common operation of a user tapping "No" on the dialog. But it's kind of unintuitive to represent it that way. A better way might've been to duplicate the flow. Duplication is good at times. 🙂 Here's what I have in mind:

![locate_me_flow](https://user-images.githubusercontent.com/12448084/75478285-b0ec6a80-59c3-11ea-8e1b-73a54c4b03df.png)

In the third diagram, you seem to have used the decision symbol incorrectly to label the modes. Also, it would be nice if you had given a glossary about what the different modes you refer to are. It would help with interpreting the flow chart easily.

That's all that I have. Hope this helps. That said, I have some comments about the flow itself. I'll come back to them later.

**Comment by Glitch101** [comment]
>It might possibly sound like being pedantic/nitpicking

That's great actually. At least it's better than fake appreciation which seems to be so common nowadays.
>First of all, let me share a reference for the various symbols used in flowcharts which I refer to below. The "Common symbols" section of the Wikipedia page on flowcharts covers it nicely.

Interesting, I didn't knew these existed. Thanks for sharing. They will definitely help in making better flow charts in the future.

>In the second diagram, you've merged the two flows to show the common operation of a user tapping "No" on the dialog. But it's kind of unintuitive to represent it that way

I agree. My bad. No excuses.

>Also, it would be nice if you had given a glossary about what the different modes you refer to are. It would help with interpreting the flow chart easily.

Yeah, that would have been better.

>That's all that I have. Hope this helps. 

It very much does! Thanks for putting in the effort for writing this feedback @sivaraam. I really appreciate this.
