### ISSUE TITLE
Switch to Material Card design for the Media Detail Fragment

### ISSUE THREAD

**Issue by kbhardwaj123** [commons-app/apps-android-commons#3436]
**Switch to Material Card design** 

As discussed in the issue #3414 the Black tile design has been around for a while so we could switch to material card design as follows:
![GIF-200216_014623 1](https://user-images.githubusercontent.com/44129798/74594608-5a476e00-505e-11ea-9ad0-a0e9089a6715.gif)

Would you like to Contribute?
**Yes**

**Comment by kbhardwaj123** [comment]
I have submitted a PR to handle zoom and for that i created the above mockup so it won't take time to fix

**Comment by kbhardwaj123** [comment]
@misaochan @maskaravivek what are your views on this :)

**Comment by misaochan** [comment]
Pinging @neslihanturan for design input. :)

**Comment by kbhardwaj123** [comment]
@neslihanturan what are your views on this ?

**Comment by kbhardwaj123** [comment]
@neslihanturan sorry for bothering again and again but now since the handle zoom pr is merged can we convert those black tiles to material card design as misaochan recommender in the handle zoom issue discussion

**Comment by neslihanturan** [comment]
Sorry for latency, I didnt see the noification :( I have some designs for this purpose, will add them today

**Comment by neslihanturan** [comment]
Hey @kbhardwaj123 , design option 2 in here displays the UI we aimed to have: https://github.com/commons-app/apps-android-commons/issues/2881 and actually almost implemented in: https://github.com/commons-app/apps-android-commons/pull/2954 . But it is merged on another branch, not up to date anymore. Maybe your aim can be rebasing those changes from @ujjwalagrawal17 .

**Comment by kbhardwaj123** [comment]
@neslihanturan sure i would be happy to do implement that :)

**Comment by kbhardwaj123** [comment]
After analysing the media detail fragment of the hackathon-2019 branch i think the design option 2 is much better, should i start it's implementation ?

**Comment by misaochan** [comment]
@kbhardwaj123 Yes, please feel free to go ahead with the design option 2 that is linked by @neslihanturan , thanks!
