### ISSUE TITLE
Add an option to clear cache

### ISSUE THREAD

**Issue by madhurgupta10** [commons-app/apps-android-commons#3437]
**Summary:** 
We should add an option to clear the cache in the settings of the app. 

It not only helps you free up space but also sometimes when there is a software update the app behaves oddly, luckily clearing the cache helps most of the time.

It is easier for some phones running stock android to clear the cache by quickly going to the system settings, but not for all Android Launchers and for a non-tech person it is difficult.

Many apps follow this for example Spotify.
![Screenshot_20200225-232027](https://user-images.githubusercontent.com/30932899/75293017-9b413e80-5825-11ea-958b-fb319b744a74.png)

**Would you like to work on the issue?**
Yes

**Comment by sivaraam** [comment]
> It is easier for some phones running stock android to clear the cache by quickly going to the system settings, but not for all Android Launchers and for a non-tech person it is difficult.

I'm not sure what you mean when you say it would difficult for some android launchers. But your other point sounds contradictory to me. For me a "non-tech" person wouldn't know about caching at all. If they do, they would as well know that there would be an option to clear for each app in the device's settings. This could just be me, though 🙂 

> Many apps follow this for example Spotify.

Of all the apps I've used, the only ones that provide the option to clear the cache in their app's settings are Spotify and Pocket. Both have a valid reason to do so. One of their primary things is handling cached, offline content. I don't think the Commons app has similar goals.

> It not only helps you free up space but also sometimes when there is a software update the app behaves oddly, luckily clearing the cache helps most of the time.

That's interesting. I've not faced the "weird behaviour that goes away on clearing the cache". Can you describe what issues you've faced? Ideally you shouldn't have faced the odd behaviour you describe. So, fixing those issue would be something worth pursuing.

**Comment by madhurgupta10** [comment]
> I'm not sure what you mean when you say it would difficult for some android launchers. But your other point sounds contradictory to me. For me a "non-tech" person wouldn't know about caching at all. If they do, they would as well know that there would be an option to clear for each app in the device's settings. This could just be me, though 🙂

I mean some launchers I used before don't give you 2 step process to clear an app's cache as stock android os do. It is tricky to find this option, I can only say this about the launchers I used before.

> Of all the apps I've used, the only ones that provide the option to clear the cache in their app's settings are Spotify and Pocket. Both have a valid reason to do so. One of their primary things is handling cached, offline content. I don't think the Commons app has similar goals.

I agree Commons app don't have goals to be an offline-focused app but we still cache a lot of media to the phone, for instance when you open the app for the first time we cache all the media from user's contributions in high resolution, this can be verified by comparing the size of the cache before log in and after first time login.


> That's interesting. I've not faced the "weird behaviour that goes away on clearing the cache". Can you describe what issues you've faced? Ideally you shouldn't have faced the odd behaviour you describe. So, fixing those issue would be something worth pursuing.

I was trying to set a media as wallpaper but it was not working for the one which has cached copy, I cleared the cache and it worked!

**Comment by misaochan** [comment]
Hi @madhurgupta10 , thanks for the suggestion. Given that the option is already present in the Android system, and it isn't something that the average non-technical user would use often anyway (unlike, say, logout), I'm personally not sure it's worth adding the complexity to our app. Do bear in mind that all features that are added need to be maintained (bugs/crashes fixed, compatibility with all future features that are added, etc), so there has to be a really good reason to add a feature.

**Comment by madhurgupta10** [comment]
@misaochan I agree maybe in the future. But, for now, we can skip working on this feature.

**Comment by maskaravivek** [comment]
I guess we can close this task for now and reopen it when the need arises. :)

**Comment by sivaraam** [comment]
I see there already a consensus here. I just wanted to add a few comments.

> I mean some launchers I used before don't give you 2 step process to clear an app's cache as stock android os do.

Yeah, but clearing the cache of a specific app is not something you should be doing often. As I've noted before, that just indicates that something is wrong with app's handling of the cache. We should be identifying and fixing the mishandling rather than providing a way to work around it. 🙂 

That said, there's one valid case where clearing the cache would be valid thing to do: to make some space. But even in that case the person is more likely to clear the cache of _all the apps via the Storage settings of the device_ rather than clearing the cache for an individual app.

> It is tricky to find this option, I can only say this about the launchers I used before.

Personally, I've never found it hard to go through Settings > Applications > Choose your app > Clear cache (or) Settings > Storage > Clear cache. 😉 Of course, I can only speak for the devices I've used. I'm not sure if some devices make this flow hard.

> I was trying to set a media as wallpaper but it was not working for the one which has cached copy, I cleared the cache and it worked!

If you're sure that it wasn't a coincidence that clearing the cache made it work, kindly open an issue.

**Comment by sivaraam** [comment]
> Do bear in mind that all features that are added need to be maintained (bugs/crashes fixed, compatibility with all future features that are added, etc), so there has to be a really good reason to add a feature.

That's one thing I had in mind too when I was thinking if it was worth including the feature now. I'm curious about why I never mentioned it _#SelfAnalysis_ 🤔
