### ISSUE TITLE
Campaign notification is not removed from Home even after disabling it in the Settings

### ISSUE THREAD

**Issue by gupta-anmol** [commons-app/apps-android-commons#3440]
**Summary:** 

Campaign notification is not removed from Home even after disabling the "Display campaigns" preference in the Settings. This happens because the `MainActivity` is in memory and is not being recreated.

**How can we reproduce the issue?** 

Open Home. 
Notice the campaign notification. 
Go to Settings and disable "Display campaigns". 
Go back to Home.

**What did you expect the app to do, and what did you see instead?**

I expected the campaigns notification to have been removed when I reopened Home.

**Device and Android version:** 

Redmi Note 5 Pro
MIUI version 11
Android 9
 
**Commons app version:** 

2.12.0-debug-master~d0d663578
master and betaDebug

**Screen-shots:** 

![del](https://user-images.githubusercontent.com/44764339/75580104-296b2e00-5a8d-11ea-817f-6039bfa2968e.gif)

**Would you like to work on the issue?**

Yes, if we can agree the issue is genuine then I'd like to work on it.

**Comment by sivaraam** [comment]
IMO, this does seem to be a valid issue that could be fixed. It's interesting that while disabling the setting doesn't make the campaigns notification in the home screen go away. Enabling the setting immediately results in the notification re-appearing on the home screen. 🤔

**Comment by 6point022** [comment]
> Enabling the setting immediately results in the notification re-appearing on the home screen.

Yes, I noticed that too, but was unable to figure out the reason behind this difference. I am interested in knowing why this happening though, I will try to dig through the code again when I get time. 😛

**Comment by 4D17Y4** [comment]
I'd like to work on this one.

**Comment by 4D17Y4** [comment]
On investigation, I found that even swiping doesn't seem to do the job whilst the nearby notification works perfectly.
Will start working as soon as I'm assigned @nicolas-raoul , @misaochan .
Thanks.

**Comment by nicolas-raoul** [comment]
@gupta-anmol Are you still working on this? :-)
@4D17Y4 if there is no answer from Gupta within 24 hours please feel free to work on it.

**Comment by gupta-anmol** [comment]
@nicolas-raoul I'm not working on this. 
@4D17Y4 you can go ahead with it. 👍
