### ISSUE TITLE
Totally change how the help pop-up is shown in achievements screen

### ISSUE THREAD

**Issue by maskaravivek** [commons-app/apps-android-commons#3441]
@TejaswiKarasani The reduction of size for that content alone does give an awkward look. My suggestion to fix the issue would be to totally change how the help pop-up is shown. Rather than having a separate "info" icon for each item that would show the help pop-up, we could show the pop-up when a user taps on the text for that item. For example, we could just show the help pop-up when a user taps on the "Feature Images" text. That should totally obviate the issue of info icon getting truncated.

To give an idea, here's the "Suggested edits" screen from the Wikipedia app where they do something similar.

1. **Info overlay shown when tapping on the contribution count**
    ![Screenshot_2020-02-29-22-16-06](https://user-images.githubusercontent.com/12448084/75612592-0bfc9980-5b4b-11ea-8205-539e50308303.png)

1. **Info overlay shown when tapping on the pageview count**
    ![Screenshot_2020-02-29-22-16-03](https://user-images.githubusercontent.com/12448084/75612616-4bc38100-5b4b-11ea-918e-b7eae44e904d.png)

_Originally posted by @sivaraam in https://github.com/commons-app/apps-android-commons/issues/3434#issuecomment-592974582_

**Comment by TejaswiKarasani** [comment]
Ok , I will work on it

**Comment by sivaraam** [comment]
Oh! I forgot to mention the main reason I suggested this. We don't do anything when tapping on that text and that looks like a lot of space that could be put to use. It would also make it easy to access the help pop-up. I find it really difficult to tap on the info icon in my device screen. It's too small.

![Screenshot_2020-02-29-23-42-14](https://user-images.githubusercontent.com/12448084/75612866-a1009200-5b4d-11ea-8a22-0a6a5cd12c50.png)

**Comment by TejaswiKarasani** [comment]
> Oh! I forgot to mention the main reason I suggested this. We don't do anything when tapping on that text and that looks like a lot of space that could be put to use. It would also make it easy to access the help pop-up. I find it really difficult to tap on the info icon in my device screen. It's too small.
> 
> ![Screenshot_2020-02-29-23-42-14](https://user-images.githubusercontent.com/12448084/75612866-a1009200-5b4d-11ea-8a22-0a6a5cd12c50.png)

@sivaraam Yeah sure thing , it's a notable issue we need to consider. 


@maskaravivek Right now , I have my exams going on. I will keep working on the issue in between the exams whenever so there is free time available

**Comment by maskaravivek** [comment]
@TejaswiKarasani this issue is a proposed enhancement and is still under discussion. For now, let us just fix the bug in #3434 using the existing designs.

**Comment by TejaswiKarasani** [comment]
Ok I will do that @maskaravivek

**Comment by Roshan13046** [comment]
Is this issue fixed?

**Comment by sivaraam** [comment]
@Roshan13046 I don't think so. Even after the major UI revamp the behaviour of the info icon hasn't changed. It would be nice to see it changed as suggested above.
