### ISSUE TITLE
Updating Logos for Github, Facebook and Website in About Activity

### ISSUE THREAD

**Issue by madhurgupta10** [commons-app/apps-android-commons#3444]
**Summary:** 
I think we should be using the latest logos from Facebook and Github for About Activity.

<img src="https://user-images.githubusercontent.com/30932899/75636568-18065b00-5c20-11ea-92c2-5e7b6f6b1a9b.png" width="120" height="120" />

<img src="https://user-images.githubusercontent.com/30932899/75636582-41bf8200-5c20-11ea-9b11-4cf0350ec812.png" width="120" height="120" />

![Screenshot_1583107062](https://user-images.githubusercontent.com/30932899/75636653-d5914e00-5c20-11ea-9bdd-5a782b9a21e3.png)

**Comment by sivaraam** [comment]
As a related change, I think we could also update the web icon to something modern, if available. Otherwise, there's a possibility that the web icon might look outlandish when compared to the GitHub and Facebook icons after the change.

**Comment by misaochan** [comment]
@madhurgupta10 Sounds like a good plan! Would you like to take it up?

@sivaraam Yes, that too. :)

**Comment by nicolas-raoul** [comment]
And convert the Facebook logo to black/transparent, I presume.

**Comment by sivaraam** [comment]
> And convert the Facebook logo to black/transparent, I presume.

This made me wonder what Facebook's branding guidelines were. Here's what I found:

https://en.facebookbrand.com/facebookapp/assets/f-logo?audience=landing

I'll leave it to others to do the brainstorming 😄

**Comment by madhurgupta10** [comment]
@misaochan I would be happy to do it, but in case a new contributor wants to solve this issue then I will be happier if you assign them :)

**Comment by madhurgupta10** [comment]
> As a related change, I think we could also update the web icon to something modern, if available. Otherwise, there's a possibility that the web icon might look outlandish when compared to the GitHub and Facebook icons, after the change.

Could you please suggest modern icons for the web?

**Comment by sivaraam** [comment]
>
> @sivaraam Could you please suggest modern icons for the web?

I didn't have any icons in mind when I suggested this. Anyways, here are some suggestions.

*Note*: I've included the images below only for demonstration. In case we choose to use one of these, it's better to use the original resources from the respective websites):

* [Material Design's globe icon](https://material.io/resources/icons/?search=publi&icon=public&style=baseline)
    ![image](https://user-images.githubusercontent.com/12448084/75702587-c15e5700-5cdb-11ea-8747-3c404ddf4a66.png)
* [Flaticon's globe icon](https://www.flaticon.com/free-icon/worldwide_814587?term=globe&page=1&position=3) (*attribution required*)
    ![world](https://user-images.githubusercontent.com/12448084/75702732-071b1f80-5cdc-11ea-9f54-e9abbbbe2f32.png)
* [Another flaticon's globe icon](https://www.flaticon.com/free-icon/planet-earth_921439?term=globe&page=1&position=5) (*attribution required*)
    ![world-1](https://user-images.githubusercontent.com/12448084/75702872-519c9c00-5cdc-11ea-95d6-0152784e1265.png)
* [Fontawesome globe icon](https://fontawesome.com/icons/globe-americas?style=solid) (*attribution required*)
    ![image](https://user-images.githubusercontent.com/12448084/75708694-4f8c0a80-5ce7-11ea-82c9-da0a06050e29.png)

I know they might not be the best but that's all I the free resources that I could find. 🤷‍♂ If you don't find them good, please feel free to suggest better ones!

**Comment by 6point022** [comment]
@misaochan Can I work on this issue?

**Comment by sivaraam** [comment]
Sure @6point022! Go for it :)

**Comment by sivaraam** [comment]
Just wanted to mention that I've found a usage of Google's Material Design's globe icon in the app detail page of play store [obviously :)]

![image](https://user-images.githubusercontent.com/12448084/75801710-963e3b00-5da1-11ea-980a-3469a3832602.png)
*Credits: [Commons wiki page](https://github.com/commons-app/apps-android-commons/wiki/Volunteers-welcome!#how-to-install-the-beta)* 😉 

I realise this is the old UI but the same icon is used in the new UI.

**Comment by misaochan** [comment]
I guess the Material Design globe icon would be best. :)
