### ISSUE TITLE
Add codestyle to git

### ISSUE THREAD

**Issue by macgills** [commons-app/apps-android-commons#3445]
**Summary:** 

The codestyle should be a part of the project and require no setup for a new contributor

**Steps to reproduce:** 

Clone the project and go to a file, press `ctrl+alt+l` and see the file will be changed.

**Would you like to work on the issue?**

I think this would be best if somebody with an already correct style configured were to do this.

Just adding this to the `.gitignore` should be sufficient
```
# IDEA/Android Studio Ignore exceptions
!/.idea/inspectionProfiles/
!/.idea/codeStyles/
```

**Comment by FawziyahAlebiosu** [comment]
Hi @nicolas-raoul I would like to work on this issue, can you assign it to me?

**Comment by macgills** [comment]
@FawziyahAlebiosu do you currently have a codestyle that is compliant with the project?

I am new to the project and was hoping it would just be an easy task for an existing contributor. However if you are willing to do this task then I am for it

**Comment by FawziyahAlebiosu** [comment]
@macgills you have a good point. I did some research on codestyle before I asked for it to be assigned to me, and I didn’t think about having a codestyle that was already compliant with the project! Thanks for bringing that up :)
For anyone reading this issue, I’m not working on this anymore because I don’t have a compliant codestyle- in relation to this project.

**Comment by sivaraam** [comment]
Looks like there are some unintended consequences of using

```gitignore
!/.idea/codeStyles/
```

See #3495 file changes. Is there any way to avoid this?

**Comment by macgills** [comment]
@sivaraam looks like the user resolved it. A part of having our codestyle in git is that people can change it if they so wish, we should just reject anything done accidentally.

I was going to make a documentation update, I asked a question somewhere about whether the issue should be here or on the documentation repo. I'll just go do it on the doc repo

**Comment by sivaraam** [comment]
> @sivaraam looks like the user resolved it. 

@macgills Yeah, he has.

> A part of having our codestyle in git is that people can change it if they so wish, ...

Just for clarification, who do you refer to as "people" here? Contributors?

> ... we should just reject anything done accidentally.

To clarify, I'm not against keep the code style in Git. I was just wondering if we could avoid such accidental changes while keeping the file Git. 🤔

The closest I could find is https://stackoverflow.com/a/936290/5614968 (the `git update-index --assume-unchange` part). But that's in the hands of the contributors. Not sure if there are any better ways.

> I was going to make a documentation update, I asked a question somewhere about whether the issue should be here or on the documentation repo. I'll just go do it on the doc repo

Yeah, the wiki has been moved to the documentation repo. So, that would be right place. 🙂

**Comment by macgills** [comment]
> Just for clarification, who do you refer to as "people" here? Contributors?

Contributors, frogmen, mermaids, skeletor, whoever can submit a pr to this repo.

If a file is in git then it can be changed and trying to enshrine it seems like something we should not do. Just treat it like any other file and educate people on IntelliJ/Android Studio functionality. 

I have a local branch for the documentation update and am awaiting access to the repo.
