### ISSUE TITLE
Use Butterknife unbinder for fragments to stop leaking views

### ISSUE THREAD

**Issue by macgills** [commons-app/apps-android-commons#3454]
**Summary:** 

As the Butterknife [page](https://jakewharton.github.io/butterknife/) states
>Fragments have a different view lifecycle than activities. When binding a fragment in onCreateView, set the views to null in onDestroyView. Butter Knife returns an Unbinder instance when you call bind to do this for you. Call its unbind method in the appropriate lifecycle callback.

**Would you like to work on the issue?**

Sure

**Comment by nicolas-raoul** [comment]
If there is the same issue with the newer view binding solution, better create a new issue.
Thanks! 🙂
