### ISSUE TITLE
Permissions in Manifest only granted to system apps

### ISSUE THREAD

**Issue by macgills** [commons-app/apps-android-commons#3457]
**Summary:** 

```
<uses-permission android:name="android.permission.MANAGE_DOCUMENTS" />
<uses-permission android:name="android.permission.READ_LOGS" />
```
Should not be requested and I would think do nothing.

**Would you like to work on the issue?**

Sure

**Comment by maskaravivek** [comment]
We are for sure not using `android.permission.MANAGE_DOCUMENTS` anywhere and it can be removed. 

Am not sure about `READ_LOGS`. Its possible that our log sender code might be using it. We will have to double check. AFAIK according to updated google's policies, we should not be using it.

**Comment by misaochan** [comment]
I agree re: manage_documents permission.

Read_logs can be removed as long as we test ACRA crash reports and the Settings > Send Logs function to make sure that they both still work.

(Pasting the SO thread that was linked to me: https://stackoverflow.com/questions/45270547/is-read-logs-a-normal-or-dangerous-android-permission/45270606#45270606 )
