### ISSUE TITLE
all-caps must not be used for emphasis

### ISSUE THREAD

**Issue by amire80** [commons-app/apps-android-commons#346]
Capital letters can be used only in a small number of scripts. They don't exist in Arabic, Hindi, Georgian, Chinese, and most other languages.

Because of this, relying only on all-caps, as in "Please do NOT upload" makes it impossible to translate the emphasis into languages that don't have capital letters.

The emphasis must be added using some other design method.

**Comment by misaochan** [comment]
Hm, we already have big red X's on the images above this text, so I wouldn't say that the capitals are absolutely essential to making the point. Is it possible to have caps in languages where it makes sense, and just omit it where it doesn't?

**Comment by amire80** [comment]
Yes, it's possible, but then isn't the big X enough for these languages, too? :)

If you insist on having capital letters in languages in the Latin alphabet, and you thing it's OK not to translate it, please do mention this in the corresponding string under values-qq.

**Comment by misaochan** [comment]
Please bear with me here. Does something like the below suffice?

`<string name="tutorial_3_text" values-qq="Caps not required">Please do NOT upload:</string>`

**Comment by amire80** [comment]
Yes, that's OK. Thank you.
