### ISSUE TITLE
Remove usages of assert

### ISSUE THREAD

**Issue by macgills** [commons-app/apps-android-commons#3463]
```
/**
 * Throws an [AssertionError] if the [value] is false
 * and runtime assertions have been enabled on the JVM using the *-ea* JVM option.
 */
@kotlin.internal.InlineOnly
public inline fun assert(value: Boolean) {
    assert(value) { "Assertion failed" }
}
```
*and runtime assertions have been enabled on the JVM using the *-ea* JVM option.* 
They have not been enabled and won't be. Replace with appropriate `AssertThat`s.

**Comment by u7281898** [comment]
Hi, could I please be assigned to this issue.

**Comment by nicolas-raoul** [comment]
@u7281898 Any progress on this? 🙂

**Comment by Atheer2104** [comment]
Hello me and four other people are having 1 week to work on open source issue, this is part of our course assignment. We would like to work on this. Can you add me as an assigne ?

**Comment by nicolas-raoul** [comment]
@Atheer2104 It is yours! 🙂

**Comment by cyrille-artho** [comment]
I think you can fix this with a one-line shell script:
```
find . -name '*.kt' | xargs grep -l 'assert *(' | xargs sed -i -e 's/assert *(/AssertThat (/'
```

**Comment by nicolas-raoul** [comment]
@Atheer2104 Did you get a chance to check the feedback on your pull request at https://github.com/commons-app/apps-android-commons/pull/5574#issuecomment-1976599786 ?

**Comment by nicolas-raoul** [comment]
@Atheer2104  I unassign for now, but if you are you still working on this, please let us know. If no answer, someone else may be assigned to it. Thanks a lot. :-)

**Comment by oelivvvv** [comment]
Hi, I'm working in a group of 4 as part of a university assignment, could we be assigned this issue please?

**Comment by u7683345** [comment]
Hi we are a team of 5 working on a universtiy project to contribute to an OSS repo. Would love to work on this issue if it is still active.  :-)

- Andrew

**Comment by nicolas-raoul** [comment]
@u7683345 It is yours, looking forward to your pull request(s). 🙂
