### ISSUE TITLE
Change Preferences to use AndroidX

### ISSUE THREAD

**Issue by macgills** [commons-app/apps-android-commons#3465]
**Summary:** 

We are not using the Androidx artifact for our preferences screen meaning we are missing out on key features like summaryProvider support

**Comment by macgills** [comment]
tagging @madhurgupta10 in the hopes it will then let me assign them to this ticket

**Comment by madhurgupta10** [comment]
Sure! I will take up this issue, do help me 😅

**Comment by macgills** [comment]
Still haven't figured out how to assign you but I'm working on it!

Always here to help.

**Comment by madhurgupta10** [comment]
> Still haven't figured out how to assign you but I'm working on it!

You can add the assign tag!

**Comment by macgills** [comment]
You finally appeared in the list, maybe you had to comment on the issue? Eh it all worked out

**Comment by sivaraam** [comment]
> ..  do help me 😅

You might have used that phrase out of your curiosity to learn, which BTW is totally good, but just wanted you to beware the [*impostor syndrome*](https://www.hanselman.com/blog/ImAPhonyAreYou.aspx). 🙂

**Comment by madhurgupta10** [comment]
> > ..  do help me 😅
> 
> @madhurgupta10 You might have used that phrase out of your curiosity to learn, which BTW is totally good, but just wanted you to beware the [_impostor syndrome_](https://www.hanselman.com/blog/ImAPhonyAreYou.aspx). 🙂

😆 Don't worry, just an expression!
