### ISSUE TITLE
Switch from RvRenderer to AdapterDelegates

### ISSUE THREAD

**Issue by macgills** [commons-app/apps-android-commons#3468]
**Summary:** 

RvRenderer has no support for the paging library and [the issue](https://github.com/pedrovgs/Renderers/issues/45) has been open for some time.

[AdapterDelegates](https://github.com/sockeqwe/AdapterDelegates) has support for the paging library and has a more expressive syntax.

**Would you like to work on the issue?**

Sure

**Comment by misaochan** [comment]
Just to clarify, the RvRenderer library will be removed entirely from our dependencies upon resolving this issue, to be replaced with AdapterDelegates?

**Comment by macgills** [comment]
That was the intention, I am not right now aware of the full scope of RvRenderer use but a switch shouldn't be too difficult.

There is also the possibility of sub tickets to replace the instances after identifying all usages.

**Comment by misaochan** [comment]
+1 from @maskaravivek and myself. :)

**Comment by macgills** [comment]
I have converted everything but Place Renderer, that one might take a bit.
