### ISSUE TITLE
Remove android.enableUnitTestBinaryResources

### ISSUE THREAD

**Issue by macgills** [commons-app/apps-android-commons#3471]
```
The following project options are deprecated and have been removed: 
android.enableUnitTestBinaryResources
The raw resource for unit test functionality is removed.
Affected Modules: <a href="openFile:C:/Users/Work/Documents/apps-android-commons/app/build.gradle">app</a>
```

**Comment by nicolas-raoul** [comment]
Can anyone check whether this issue still exists?

**Comment by rohit9625** [comment]
This is the info about that line:

> That line in your gradle.properties file is actually deprecated and should be removed. It was used in older versions of Android Studio (before 3.3) to enable a feature called "unit test binary resources". This feature aimed to speed up unit tests by using a different resource-loading mechanism


So, this issue can be closed now :+1:

**Comment by nicolas-raoul** [comment]
@rohit9625 Has the line been removed in main?

**Comment by rohit9625** [comment]
Yes, the line is removed by the PR linked in this issue and I also checked in the gradle.properties file.
