### ISSUE TITLE
Change the names and order of Theme options

### ISSUE THREAD

**Issue by madhurgupta10** [commons-app/apps-android-commons#3473]
As per [#3460(Comment)](https://github.com/commons-app/apps-android-commons/pull/3460#issuecomment-596095164), we can discuss if we need to change to names and order for theme options or not.

**Comment by sivaraam** [comment]
Continuing discussion from the PR:

Quotes from https://github.com/commons-app/apps-android-commons/pull/3460#issuecomment-596098017:
>> This particular suggestion about "not showing the 'Default' option at all" is based on how Signal handles this. They recently added supported to handle the system theme on Android 10+ devices. When I use the Signal app with that change, I only see the 'Light' and 'Dark' options in the Theme setting. If it's of any help, here's the related commit: signalapp/Signal-Android@4e7a926
>
> I used custom android skin for my Android 9 device and I liked the way app selects the theme automatically, so IMO it is better if we keep it.

I understand that this would benefit users who use a custom theme. But we would also have to think about those don't use a custom theme. For those other users, the "Default" means "Light" and that could be confusing. If there's a reliable way to identify if an Android 9 or lower device has support for a custom dark theme, then we can show the option only for those devices. Is that possible?


>> My preference would be for 1 if it could be done easily. Otherwise, we could just go with 3 despite the surprise I mentioned. Share your opinions/suggestions too, including possibly new ones. 🙂
>
> I agree with you, we can educate them about this, many dark theme lovers will keep the system-wide dark theme on and it won't be a surprise for them. Also recently Whatsapp introduced dark theme for the app and after the update, it automatically changed my theme from Light to System Default (Dark) and I loved it.

I think you misunderstood what I meant by educating users. I should have been more clear, sorry. When I said "educating users", I was imagining that after the app upgrade we would show a screen that would clearly communicate to them that we are adding a "System default" option to the "Theme" option and that we would be changing the default to the newly introduced option. This way the user wouldn't be _surprised_ when the app theme changes to their system default. FWIW, Signal introduces (_educates about_) new features this way to its users and I love it.

That said, it's arguable that this is overkill for what's a simple change to the default value of a preference which is actually for the better. And I agree. I just wanted to share my thoughts ☮️

**Comment by madhurgupta10** [comment]
Github Android app also have theme options

Dark
Light
System Default

Which is quite similar to one we are using. I am not sure about pre-Android 10 devices.

**Comment by macgills** [comment]
`Follow System` works for me

**Comment by sivaraam** [comment]
> Which is quite similar to one we are using. 

"Follow system" sounds a lot better but whether it's quite similar to "Default" [is debatable](https://github.com/commons-app/apps-android-commons/pull/3460#issuecomment-596095164).

> I am not sure about pre-Android 10 devices.

Yeah they show the same thing there too.

FWIW, WhatsApp shows just "Light" and "Dark" as options for the theme in my device (Android 5.1.1).

**Comment by sivaraam** [comment]
Rather than bikeshedding this further, I believe it would be better if we just go with the following:
1. Light
2. Dark
3. Follow system

Note the order there. What do you think?

**Comment by madhurgupta10** [comment]
I will make the change if @macgills and @misaochan approves :)

**Comment by macgills** [comment]
Approved

**Comment by misaochan** [comment]
Sounds good to me.
