### ISSUE TITLE
Items in Place type list in Nearby become unreadable on unselecting

### ISSUE THREAD

**Issue by 6point022** [commons-app/apps-android-commons#3474]
**Summary:** 

Background of items in Place type list in Nearby becomes white on unselecting. Since the text is also white, the item becomes unreadable. This only happens in the dark theme.

**How can we reproduce the issue?** 

Enable dark theme. Open Nearby. Tap on the search option in front of Place type. If you tap once on any item, the background becomes light grey. Tap the same item again, i.e., unselect it, and the background becomes completely white.

**What did you expect the app to do, and what did you see instead?**

I expected the item's background colour to change to what it was before I had selected it, i.e., black.

**Device and Android version:** 

Redmi Note 5 Pro
MIUI version 11
Android 9
 
**Commons app version:** 

2.12.3-debug
master and betaDebug

**Screen-shots:** 

_Default_

![image](https://user-images.githubusercontent.com/44764339/76146842-67cfa100-60bc-11ea-98da-d808487b8170.png)

_Tap once to select item_

![image](https://user-images.githubusercontent.com/44764339/76146849-7322cc80-60bc-11ea-8f75-07d7ab2450b8.png)

_Tap again to unselect_

![image](https://user-images.githubusercontent.com/44764339/76146852-7a49da80-60bc-11ea-8fc1-a470b8e21156.png)

**Would you like to work on the issue?**

Yes, I'd like to work on this.

**Comment by misaochan** [comment]
@6point022 Go for it!
