### ISSUE TITLE
Add progressbar to new Media details zoom activity

### ISSUE THREAD

**Issue by neslihanturan** [commons-app/apps-android-commons#3479]
**Summary:** 
When it is a DSLR image with a big size, it took some time for it to be displayed. But user is looking at a black screen during this time. Instead there should be an progressbar.

Progressbar should appear after image from media details is clicked until image is being loaded.

**Comment by kbhardwaj123** [comment]
@neslihanturan I have understanding of the custom ZoomableDraweeView which I added so can I work on this?

**Comment by neslihanturan** [comment]
Go for it @kbhardwaj123 :)
