### ISSUE TITLE
If an upload fails and is retried, the depictions, captions, etc must be persisted somewhere

### ISSUE THREAD

**Issue by maskaravivek** [commons-app/apps-android-commons#3484]
@macgills I guess the idea of `DepictionDao` might be to store depictions that were selected during the upload process. If an upload fails and is retried, the depictions, captions, etc must be persisted somewhere so that it can be attached in the retrial request. 

We can probably have the `Contributions` table take care of the extra metadata instead of having a separate table.

_Originally posted by @maskaravivek in https://github.com/commons-app/apps-android-commons/pull/3483#issuecomment-597257468_

**Comment by macgills** [comment]
This is already done. Media/Contributions were extended to contain depictionEntityIds/captions
