### ISSUE TITLE
[Discussion] Add inspections to git

### ISSUE THREAD

**Issue by macgills** [commons-app/apps-android-commons#3492]
**Summary:** 

Inspections are a part of intellij, giving us highlighting & autofixes for many common issues in code. We should share them between developers so everyone has the same experience.

Should we try and enforce people run Inspections on VCS changed code? 
It is difficult to achieve this in any automated fashion, this [tool](https://github.com/bentolor/idea-cli-inspector) is trying but I feel is still not there.

There is the larger question of which inspections we should enable and at what severity.

**Comment by macgills** [comment]
@maskaravivek @ashishkumar0207 @misaochan @neslihanturan  any thoughts?

**Comment by ashishkumar468** [comment]
@macgills  Before we conclude something, can you elaborate, how does this generally work?

**Comment by macgills** [comment]
Exactly like the codestyle a file gets added to git.

The file is the settings you can see in your inspections
![image](https://user-images.githubusercontent.com/3358282/77448733-0c562080-6de9-11ea-86b5-8a67a4d7d0aa.png)

We would all share the same settings, be able to raise the level to get red syntax highlighting if it is something we especially don't want, turn on ones that are not on by default but should be. So on and so forth.

**Comment by ashishkumar468** [comment]
Good to go from my side.

**Comment by macgills** [comment]
We can potentially use [this](https://github.com/checkstyle/checkstyle/blob/master/config/intellij-idea-inspections.xml)

**Comment by misaochan** [comment]
Just to clarify, this would have to be run locally, right? I wonder if it is at all possible to include this in Travis CI? It would be incredibly helpful to be able to view the inspection results of any PR submitted rather than having to check locally.

**Comment by macgills** [comment]
@misaochan they also play an important role in the IDE highlighting which should be the first line of defence. The tool I linked in the description is for running inspection commandline but I don't trust it and it would probably add bloat to the build time.

We could encourage people to commit via AndroidStudio as one of the checkboxes is `run inspections on VCS changed text` in the commit dialog? I don't like this option too much as the in built VCS is a bit lacking.

Inspections don't have the idea of a baseline where we have a list of accepted legacy issues (aside from suppressions) so it would be a bit difficult to integrate into a pass/fail flow.

**Comment by misaochan** [comment]
Thanks for the clarification. :) I'm on board with adding the file to git.
