### ISSUE TITLE
Give better names for the upload warning dialog buttons

### ISSUE THREAD

**Issue by sivaraam** [commons-app/apps-android-commons#3494]
Per [@macgills' comment](https://github.com/commons-app/apps-android-commons/issues/3428#issuecomment-597555730):

> Also if we go with the material guidelines "Yes/No" are poor words to use, the action should be repeated in the positive button eg "Upload/Proceed" and the negative should be something like "Cancel" if you cancel an operation

This sounds valid. We should think about changing the text shown for the dialog buttons in the following places which are the two warnings shown when a user tries to upload a duplicate or bad picture:
* [UploadMediaDetailFragment.java#L352](https://github.com/commons-app/apps-android-commons/blob/master/app/src/main/java/fr/free/nrw/commons/upload/mediaDetails/UploadMediaDetailFragment.java#L352)
* [UploadMediaDetailFragment.java#L370](https://github.com/commons-app/apps-android-commons/blob/master/app/src/main/java/fr/free/nrw/commons/upload/mediaDetails/UploadMediaDetailFragment.java#L370)

**Comment by FawziyahAlebiosu** [comment]
Does this mean that instead of calling R.string.warning as the text for those dialog boxes, we would replace it with R.string.cancel ?
And it would be replaced in those two instances where .warning is called, that you link in your comment?

**Comment by hudlerr** [comment]
Hey @sivaraam, am I alright to work on this?
