### ISSUE TITLE
Replace BiMap with a HashMap

### ISSUE THREAD

**Issue by macgills** [commons-app/apps-android-commons#3498]
**Summary:** 

BiMap is unnecessary and can be deleted, `contansKey(V v)` is replaceable by `containsValue`

**Comment by 6point022** [comment]
@macgills Can I work on this? 

I have identified  the following changes that will have to be made:

1. Change BiMap to HashMap in `DescriptionsAdapter.java`
2. Change BiMap to HashMap in `SpinnerLanguagesAdapter.kt`
3. Delete `BiMap.java` (I am not sure, maybe we can keep it)

I didn't find any usage of `contansKey(V v)`, so I don't think there's any issues here.

**Comment by macgills** [comment]
There is one instance where you will have to use `containsValue` I think. Please delete BiMap in your PR
