### ISSUE TITLE
Automatically add Commons Geocoding Template from the GPS data stored in image

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#35]
The MediaWiki API only finds images that have been explicitly geocoded, i.e. the Locations template added to the Commons page. The web-based Upload Wizard automatically adds the Location template, but our app doesn't seem to do it. This hampers categorization of future uploaded pics with similar coordinates, as the newly-implemented GPS categorization depends on finding nearby pictures.

**Comment by tobias47n9e** [comment]
Is this already in the app? I uploaded this image, and a bot had to read out the coordinates:

https://commons.wikimedia.org/wiki/File:Vermarkungspunkt_of_the_Austrian_Post.jpeg

**Comment by misaochan** [comment]
Hi @tobias47n9e , this feature has been scheduled for implementation by October, as per the [timeline](https://meta.wikimedia.org/wiki/Grants:IEG/Improve_%27Upload_to_Commons%27_Android_App/Timeline). Sorry for the wait! :)

**Comment by tobias47n9e** [comment]
@misaochan Thanks. Will be looking forward to this.

**Comment by misaochan** [comment]
Just confirming that the `{{Location|lat|long}}` template described at https://commons.wikimedia.org/wiki/Commons:Geocoding will be appropriate for this?

**Comment by tobias47n9e** [comment]
I think so. Are there any other parameters you will set in the template?

**Comment by misaochan** [comment]
No, I don't think so. Do you think any other parameters will be necessary?

**Comment by tobias47n9e** [comment]
Just checked and I don't think we need to add precision. Does the location API give the standard deviation of the current position measurement? In a canyon with few visible GPS satellites the measurement can be off by 100s of km.

**Comment by misaochan** [comment]
As far as I know, the Android location API doesn't.

**Comment by misaochan** [comment]
Picture that I uploaded to test my PR branch: https://commons.wikimedia.org/wiki/File:Punnet_Strawberry_Farm.jpg

The template seems to work, I think.

**Comment by misaochan** [comment]
This has been released - please let me know if it works properly for you. It seems to work for my pictures.

**Comment by tobias47n9e** [comment]
It works!

**Comment by misaochan** [comment]
Great! :) @nicolas-raoul , do you think this is okay to close?

**Comment by nicolas-raoul** [comment]
Great!
