### ISSUE TITLE
Error Message for uploading with an already existing title is wrong

### ISSUE THREAD

**Issue by macgills** [commons-app/apps-android-commons#3500]
**Summary:** 

Try to upload on beta with a title "t" and a dark image. You see the message "title is empty" when it actually already exists
 
**Commons app version:** 

master

**Comment by VitalyVPinchuk** [comment]
I tried to upload but app said "name already exists". Maybe it's fixed already

**Comment by macgills** [comment]
![image](https://user-images.githubusercontent.com/3358282/76952375-e9b59a80-6904-11ea-9cd5-9e11b9545cb2.png)

Try with a dark image, looks like somebody was being too clever with bit shifting and when multiple conditions are true it is showing incorrect messages

**Comment by VitalyVPinchuk** [comment]
Oh, you're right, now I see. It's weird :)

**Comment by macgills** [comment]
Updated my misleading description, do you want to be assigned to this issue?

**Comment by VitalyVPinchuk** [comment]
Yes I do. Thanks.

**Comment by macgills** [comment]
@misaochan to resolve this well we might need to rethink the validation flow. Have we ever considered adding a validation screen that shows the progress of the individual checks and a customised message depending on which check fails?

**Comment by misaochan** [comment]
Yes, our current validation flow is pretty wonky and reliant on a bunch of cases. A validation screen showing the individual checks in a more organized manner would be fantastic, however if ALL of the checks are good I see no reason to burden the user with it. Only display it when one or more of the checks fail perhaps. @neslihanturan @maskaravivek @ashishkumar468  ?

**Comment by macgills** [comment]
The checks are so lengthy I think surfacing it to the user has merit so they don't get frustrated but I think that is mostly the `isDark` check and I have been only uploading dark images, maybe it would be quicker without doing that.

**Comment by misaochan** [comment]
Do they take a long time for you? It usually takes 1-2 sec for me to proceed to the next stage.

**Comment by macgills** [comment]
15 seconds sometimes, this is on beta though. Try with a totally black image

**Comment by maskaravivek** [comment]
Yup a validation screen sounds great.

**Comment by misaochan** [comment]
> 15 seconds sometimes, this is on beta though. Try with a totally black image

Right, it takes longer if one of the checks fail for some reason(?). But I meant that currently, for users who submit a photo that passes all the checks, they would usually just go straight to the next stage in 1-2 sec, in my experience. The validation screen sounds to me like it would be a step back for them, although it would be a step forward for photos that fail a check.

**Comment by macgills** [comment]
> it takes longer if one of the checks fail for some reason(?)

I think the dark check just takes longer for a dark picture.

I didn't see your message @misaochan so I just sort of rambled  for a bit:
So I am thinking a list of conditions, intedeterminate progressbar beside each one while checking, green tick, red x or orange/yellow exclamation  for on success, fatal error, non fatal error/warning?

Show a button for previous if any are in progress, progress automatically if all pass, show button "Continue with warnings"(something to this effect) when non fatal errors are present. Maybe "Cancel Upload" should also show at this time


I think we can adapt the above into a Validation failure screen/dialog, just no progress bars

**Comment by macgills** [comment]
If it is just a Validation Failed Dialog, all it needs to show is the errors and not the successes.

Are there many unprogressable errors? I think empty/invalid title are the only ones that fully stop you moving forward.
```
 checkDuplicateImage(filePath),
        checkImageGeoLocation(uploadItem.getPlace(), filePath),
        checkDarkImage(filePath),
        validateItemTitle(uploadItem),
        checkFBMD(filePath),
        checkEXIF(filePath),
```

Also it would be preferable if we moved away from ints and represented our errors as types.

I think all this has to do is combine non fatal errors into one dialog - as long as there are no fatal errors - and allow for an cancel proceed as we already have

**Comment by VitalyVPinchuk** [comment]
Is there anything I could help with?

**Comment by macgills** [comment]
@VitalyVPinchuk I am not sure we have agreed on functionality. @misaochan ?

**Comment by Rishavgupta12345** [comment]
@nicolas-raoul this issue is not relevent now and so we can close this

**Comment by misaochan** [comment]
@Rishavgupta12345 does the issue not happen for you anymore when following the steps listed by Macgills?
