### ISSUE TITLE
Depictions remain selected on subsequent upload

### ISSUE THREAD

**Issue by macgills** [commons-app/apps-android-commons#3501]
**Summary:** 

A depiction from a previous upload was shown when I had yet to select any for the current upload.

**Steps to reproduce:** 

Upload an image and select a depiction.
Go to upload another image and search for any depiction.
See the previously selected depiction.

 
**Commons app version:** 

structuredData

**Would you like to work on the issue?**

yes

**Comment by macgills** [comment]
Possible duplicate of #2803

**Comment by nicolas-raoul** [comment]
I just had this problem too (in the 3601-depiction-thumbnails branch to be exact).
There is a pull request in #2803 so I suggested we keep that one.

**Comment by nicolas-raoul** [comment]
Sorry I just realized the other is only about name/description, might be unrelated so indeed better have two issues.

**Comment by macgills** [comment]
Can no longer reproduce on master
