### ISSUE TITLE
[Discussion] Remove plurals from app

### ISSUE THREAD

**Issue by macgills** [commons-app/apps-android-commons#3502]
**Summary:** 

[Docs](https://developer.android.com/guide/topics/resources/string-resource#Plurals)
>It's often possible to avoid quantity strings by using quantity-neutral formulations such as "Books: 1". This makes your life and your translators' lives easier, if it's an acceptable style for your application.

I doubt the plurals work well for other languages as many cases are missing.

From my running of lint there are 74 missing quantities and 18 Implied Quantities along with 98 Unused quantities

>Missing quantity translation  Different languages have different rules for grammatical agreement with quantity. In English, for example, the quantity 1 is a special case. We write "1 book", but for any other quantity we'd write "n books". This distinction between singular and plural is very common, but other languages make finer distinctions.  This lint check looks at each translation of a <plural> and makes sure that all the quantity strings considered by the given language are provided by this translation.  For example, an English translation must provide a string for quantity="one". Similarly, a Czech translation must provide a string for quantity="few".  Issue id: MissingQuantity  http://developer.android.com/guide/topics/resources/string-resource.html#Plurals

>Implied Quantities  Plural strings should generally include a %s or %d formatting argument. In locales like English, the one quantity only applies to a single value, 1, but that's not true everywhere. For example, in Slovene, the one quantity will apply to 1, 101, 201, 301, and so on. Similarly, there are locales where multiple values match the zero and two quantities.  In these locales, it is usually an error to have a message which does not include a formatting argument (such as '%d'), since it will not be clear from the grammar what quantity the quantity string is describing.  Issue id: ImpliedQuantity  http://developer.android.com/guide/topics/resources/string-resource.html#Plurals

>Unused quantity translations  Android defines a number of different quantity strings, such as zero, one, few and many. However, many languages do not distinguish grammatically between all these different quantities.  This lint check looks at the quantity strings defined for each translation and flags any quantity strings that are unused (because the language does not make that quantity distinction, and Android will therefore not look it up).  For example, in Chinese, only the other quantity is used, so even if you provide translations for zero and one, these strings will not be returned when getQuantityString() is called, even with 0 or 1.  Issue id: UnusedQuantity  http://developer.android.com/guide/topics/resources/string-resource.html#Plurals

**Comment by madhurgupta10** [comment]
@macgills How about using something like - **book(s)**

**Comment by macgills** [comment]
I am in favor of it but others would need to be as well. @misaochan ?

**Comment by misaochan** [comment]
Requesting @Nikerabbit or @amire80 's input on this.

**Comment by amire80** [comment]
Thanks for the ping! I'm not sure I understand the question. Does the app already have proper plural support and you want to remove it? If yes, why?

Or maybe the app doesn't have plural support, and you want to change the existing strings so that they would be number-neutral? If yes, can you just add proper plural support instead?

**Comment by macgills** [comment]
@amire80 

> From my running of lint there are 74 missing quantities and 18 Implied Quantities along with 98 Unused quantities

The app has plural support but plurals have a lot of issues. Plurals missing that are required, extra plurals in languages that don't need them.

My suggestion is to use number neutral strings and ditch our plurals.

Hello again, been a while.

**Comment by amire80** [comment]
Why remove plural support instead of improving the strings?

If there are problems in the translations, mark them as fuzzy by appending the string `!!FUZZY!!` to the beginning of each problematic translation. And where is the plural support documented? Translators at translatewiki are usually most experienced with localizing MediaWiki and its extensions, and if the strings here work differently, this must be documented. I couldn't find documentation about this.

If there are problems with the English strings, fix them! :)

**Comment by macgills** [comment]
It is not a problem with the english strings (potentially), it is that the generated plurals exist when they shouldn't and don't exist when they should.

The english:
```
  <plurals name="uploads_pending_notification_indicator">
    <item quantity="one">%1$d file uploading</item>
    <item quantity="other">%1$d files uploading</item>
  </plurals>
```

![image](https://user-images.githubusercontent.com/3358282/76857971-68033580-684e-11ea-94ec-7164714d2e2c.png)

Here the mistake was made to add a `zero` rule for English

```
  <plurals name="contributions_subtitle">
    <!--zero is not used in english. Category mentioned here for easy reference in future-->
    <item quantity="zero">@string/contributions_subtitle_zero</item>
    <item quantity="one">(%1$d)</item>
    <item quantity="other">(%1$d)</item>
  </plurals>
```

and that caused this issue

![image](https://user-images.githubusercontent.com/3358282/76858186-d2b47100-684e-11ea-8211-f766aeaa3cbe.png)


It seems like we would have to supply every rule in the english file to get the correct plural for all languages but this would give us unused plurals in many languages.

Ideally we could define an english plural with only `one`, `other` and then the translated file would produce a plural with the correct rules for the language. eg Arabic has `few many one two zero other`, the whole gamut.  That is an ideal world though.

**Comment by macgills** [comment]
> Translators at translatewiki are usually most experienced with localizing MediaWiki and its extensions, and if the strings here work differently, this must be documented. I couldn't find documentation about this.

If I can be pointed at the place to add it then I am happy to add documentation on how android plurals work, which will mostly be a regurgitation of the [docs](https://developer.android.com/guide/topics/resources/string-resource#Plurals)

**Comment by Nikerabbit** [comment]
We now have plural validator for Android. Compare for example to Ajapaik which has it enabled:
* https://translatewiki.net/w/i.php?title=Special:Translate&showMessage=strings-profile_rephotos&group=ajapaik-app&language=ar&filter=&optional=1&action=translate (make sure you are logged in first, then make change in the text area but don't save. You see a warning from the validator).
https://translatewiki.net/w/i.php?title=Special:Translate&showMessage=commons-android-strings-uploads_pending_notification_indicator&group=commons-android-strings&language=ar&filter=&optional=1&action=translate (no warning shown here)

Can we enable this validator? It won't magically fix existing violations, but it will prevent new ones.

**Comment by macgills** [comment]
What would the strategy be for fixing our existing plurals?

**Comment by Nikerabbit** [comment]
I can only make them show up in the list of messages needing translation/updating. Translators are required to update those messages appropriately.

Extreme solution would be to remove the problematic translations for these messages.

**Comment by macgills** [comment]
It is extreme but slightly to where I am leaning. We have 7 plurals and 2 of these should probably not be plurals.

I'll let @misaochan weigh in as it is not a decision to take lightly.

**Comment by misaochan** [comment]
> Can we enable this validator? It won't magically fix existing violations, but it will prevent new ones.

This would be great!

> I can only make them show up in the list of messages needing translation/updating. Translators are required to update those messages appropriately.

This sounds OK to me, I would prefer it over simply removing the problematic translations.

**Comment by Nikerabbit** [comment]
Plural validator is now enabled and I'm marking bad plural translations for review.

Btw, `zero` key should not be used in English. It is not the same as number 0 in some languages. See for example Latvian in https://www.unicode.org/cldr/charts/34/supplemental/language_plural_rules.html

**Comment by macgills** [comment]
> Here the mistake was made to add a zero rule for English

I am aware. I should probably make a ticket to get rid of that also our zero string for that is not a quantity string and should not be used 
`<string name="contributions_subtitle_zero">No uploads yet</string>`

A conditional in code should express it I think

**Comment by amire80** [comment]
I see that this was enabled in translatewiki. It's mostly a good thing, but would it be possible to make some rules optional? For example, in Hebrew "two" and "many" are almost always identical, and something similar is probably true for a lot of other languages.

It probably has to be done on the translatewiki or Extension:Translate side, so pinging @Nikerabbit again.

**Comment by macgills** [comment]
@amire80 just as input for "translatewiki or Extension:Translate side", lint would still complain at us if it says hebrew should have two/many and the file only has 1 of the rules. This could be dealt with by having ignores in the hebrew files for this issue of `MissingQuantity` but it would mask all missing quantities then, unless applied to specific translations

**Comment by amire80** [comment]
If the linter complains about it, it is a bug in the linter. A linter is supposed to complain about likely problems. A missing "two" rule in Hebrew is likely not a problem because the "two" form is only used when talking about hours, days, years, and body parts, and that's about it. If a linter reports about it at all, it's supposed to be in the lowest priority. A linter is not supposed to override common sense :)

Maybe translatewiki could auto-replicate the two and many rules when synching, but that would be an ugly hack. I'd suggest ignoring this linter error, at least for Hebrew. (And again, I suspect that it's also true for some other languages.)

**Comment by Nikerabbit** [comment]
@amire80 As a translator, what would you think of an explicit syntax for aliasing forms, such as `{{PLURAL|one=...|two&many=...}}`?

**Comment by amire80** [comment]
> @amire80 As a translator, what would you think of an explicit syntax for aliasing forms, such as `{{PLURAL|one=...|two&many=...}}`?

Somewhat redundant, but much better than just duplicating everything.

(And if you are doing this, then this should be documented for all the translatewiki projects where it is used.)
