### ISSUE TITLE
Remove Title/Caption From MediaUploadDetail and only use Caption/Description pairs

### ISSUE THREAD

**Issue by macgills** [commons-app/apps-android-commons#3503]
**Summary:** 

`Caption (Required)` should be removed and the first caption be used as title instead

**Commons app version:** 

structuredData

**Screen-shots:** 

![image](https://user-images.githubusercontent.com/3358282/76530720-0e74c280-646c-11ea-9838-97401773a213.png)

**Would you like to work on the issue?**

Yes

**Comment by ahmedmamdouh13** [comment]
Can i work on this issue ?

**Comment by macgills** [comment]
I am working on it @ahmedmamdouh13

**Comment by macgills** [comment]
duplicate of #2297

**Comment by nicolas-raoul** [comment]
Just tested, it is great now :-)
