### ISSUE TITLE
Image View Height remains zero for some time on a bad network 

### ISSUE THREAD

**Issue by kbhardwaj123** [commons-app/apps-android-commons#3506]
**Image View height stays at zero for some time on bad network** 

This happens only sometimes but the image height in media detail remains zero for some time on a bad network then suddenly jumps into existence

It happens only for some images and only rarely

**i managed to capture it on a bad LTE network**
![GIF-200313_125411 1](https://user-images.githubusercontent.com/44129798/76599131-59550f80-652a-11ea-9001-4baf97c93575.gif)

**System logs:**
Didn't find anything helpful 

**Would you like to work on the issue?**
Yes

**Comment by ashishkumar468** [comment]
Hi @kbhardwaj123  How are you planning to approach this issue?

**Comment by kbhardwaj123** [comment]
@ashishkumar468 i will try to debug using timber arguments and try to analyse the logs, to see what is causing this delay

**Comment by kbhardwaj123** [comment]
i will post here as soon as i find something

**Comment by kbhardwaj123** [comment]
after a bit of debugging i found that if we try to print log for value of finalHeight :
![image](https://user-images.githubusercontent.com/44129798/76658624-880ace80-659a-11ea-99db-2e83116e777c.png)
i get:
![image](https://user-images.githubusercontent.com/44129798/76658844-f8b1eb00-659a-11ea-8fe4-7ca918e21448.png)
