### ISSUE TITLE
Improve Kotlin conversion of Achievement Models

### ISSUE THREAD

**Issue by macgills** [commons-app/apps-android-commons#3510]
Data classes (preferably completely immutable) should be leveraged and there shouldn't be empty constructors

**Comment by VitalyVPinchuk** [comment]
Hello
Is it suitable for beginners? If so, I'd like to work on it but some clarification and guidance needed.

**Comment by macgills** [comment]
It should be okay, basically the problem is that the models were converted automatically and then not given a manual pass.
This [PR](https://github.com/commons-app/apps-android-commons/pull/3096) did a good job but was superseded.

**Comment by elemcraft** [comment]
Hello, is anyone still working on this issue? Can I take this issue?

**Comment by nicolas-raoul** [comment]
@elemcraft It is yours, thanks! :-)

**Comment by nicolas-raoul** [comment]
@elemcraft  I unassign for now, but if you are you still working on this, please let us know. If no answer, someone else may be assigned to it. Thanks a lot. :-)

**Comment by u7479759** [comment]
Hi, I was wondering if I could be assigned this issue? I'm working in a group of 4 as part of a university assignment.
