### ISSUE TITLE
[DISCUSSION] Use Kotlin Android Extensions instead of Butterknife

### ISSUE THREAD

**Issue by macgills** [commons-app/apps-android-commons#3530]
**Summary:** 

In kotlin we have the option of using [Kotlin Android Extensions ViewBinding](https://kotlinlang.org/docs/tutorials/android-plugin.html#view-binding) 

I am in favour of their usage for their ease of use.

 The alternatives are:
1. Continue using butterknife
1. Use [ViewBinding](https://developer.android.com/topic/libraries/view-binding) for compile time safety

**Comment by maskaravivek** [comment]
I am in favour of using Kotlin Android Extensions ViewBinding for all the Android components that are written in Kotlin. 

IMO our goal should be to gradually remove all usages of Butterknife. Whenever an existing Android component which is written in Java is converted to Kotlin, we should ideally replace Butterknife with Kotlin Android Extensions ViewBinding. 

Let's wait for what others think about this and then we can make this part of our contributor guidelines.

**Comment by misaochan** [comment]
> Whenever an existing Android component which is written in Java is converted to Kotlin, we should ideally replace Butterknife with Kotlin Android Extensions ViewBinding.

This sounds good to me.

**Comment by maskaravivek** [comment]
@misaochan Do we need to wait for more opinions on this or if everyone agrees then we can unblock #3524.

**Comment by misaochan** [comment]
Let's just get @ashishkumar468 's opinion, we should be good after that since this is a relatively minor policy.

**Comment by ashishkumar468** [comment]
Agree with @maskaravivek  's opinion, I am okay to go with this, read the docs, supports both View Caching and Layout Containers (so that classes like ViewHolders can also be used as an extension containner).

**Comment by macgills** [comment]
A minor xml style point now that it seems we are all in agreement.

Should we start writing our `id`s in camelCase instead of snake_case seeing as they will be present in Kotlin classes?

**Comment by ashishkumar468** [comment]
I think that should be okay.

**Comment by macgills** [comment]
@maskaravivek if you are okay with it then I will consider this issue closed

**Comment by maskaravivek** [comment]
Once the liked PR is merged, we can close this issue.

**Comment by ashishkumar468** [comment]
I was reading the docs, and the layout container support is experimental, are we okay with that?

**Comment by macgills** [comment]
It has been experimental since it released and has seen no real change over the 2 years I have been using it in production. It is also not "experimental" in the same way they mark APIs `experimental` where it is a compiletime error to not also mark your caller experimental

**Comment by domdomegg** [comment]
Kotlin Android extensions looks to be being deprecated in favour of view binding for Android. However, looks like support will only be dropped in September 2021

https://android-developers.googleblog.com/2020/11/the-future-of-kotlin-android-extensions.html
