### ISSUE TITLE
Rephrase the requirement asking for screenshots in the pull request template

### ISSUE THREAD

**Issue by 6point022** [commons-app/apps-android-commons#3544]
_Continuing the discussion from issue #3540_ 

> Also, while we are on the subject of making changes to the PR template, can we also modify "Screenshots showing what changed (optional - for UI changes)." I am never sure of what it means. I don't know if I misunderstand it or it could be phrased better. Does it mean this is optional? Does it mean this is optional for UI changes? Does it mean this is optional, but necessary for UI changes?

> It means add screenshots if you changed the UI. We could change it to to for UI changes only. Separate issue though, please make an issue to discuss it further

**Screenshots showing what changed (optional - for UI changes)** can have better phrasing. We could change it to **Screenshots showing what changed (for UI changes only)**.

**Comment by sivaraam** [comment]
I believe "**Screenshots (for UI changes only)**" would be more concise and clear enough.

**Comment by macgills** [comment]
@6point022 want this assigned to you?

**Comment by 6point022** [comment]
@macgills Sure. And if we have a consensus on what @sivaraam proposed, i.e., "**Screenshots (for UI changes only)**", then I'll create a PR for that.
