### ISSUE TITLE
[Structured Commons] Remove both captions and description instead of just descriptions

### ISSUE THREAD

**Issue by madhurgupta10** [commons-app/apps-android-commons#3551]
**Summary:** 

Continuing the discussion from [thread](https://github.com/commons-app/apps-android-commons/pull/3504#issuecomment-601249775)

When Structured Commons are implemented, change the action of "X" to delete both Captions and Description instead of just Descriptions.

Use the UI mockup discussed in PR where the X and the Spinner are vertically centered.

Mockup:
![screenshot-user-images githubusercontent com-2020 03 20-01_37_21](https://user-images.githubusercontent.com/30932899/77127054-78343400-6a4b-11ea-8f86-8412d10e0bee.png)

**Comment by FawziyahAlebiosu** [comment]
I hope you don't mind me asking, I promise I DID some research about this but I couldn't find anything  helpful. What is structured commons? Is it a repository that holds another version of the android app? What is the difference between this one and that-if any?

**Comment by macgills** [comment]
@FawziyahAlebiosu there is a branch on the repo called structuredData that I am working on after inheriting, you can read more [here](https://commons.wikimedia.org/wiki/Commons:Structured_data). It seems like this ticket will now be done as part of the original ticket to remove descriptions once Structured Data is merged so I wouldn't worry about it

**Comment by FawziyahAlebiosu** [comment]
> @FawziyahAlebiosu there is a branch on the repo called structuredData that I am working on after inheriting, you can read more [here](https://commons.wikimedia.org/wiki/Commons:Structured_data). It seems like this ticket will now be done as part of the original ticket to remove descriptions once Structured Data is merged so I wouldn't worry about it

Ohhhhhhh that page has so much information, thank you!! I was just curious because I had seen it referenced in multiple issues.

**Comment by nicolas-raoul** [comment]
Do we really need a X button? The field is already quite narrow, so an X button would make it too small, I think. Leaving the fields empty would be enough, I think. We have to check that empty fields are not uploaded.
What do you think about it? :-)

**Comment by macgills** [comment]
It feels a bit messy to not have a way of removing them?

On my contacts app if I try to add a custom field I get the x option once I have added data
![image](https://user-images.githubusercontent.com/3358282/78539241-24b33b80-77ea-11ea-8111-f5c8bd470091.png)


It would be a larger change to the ui but we could launch an `Add caption & description` dialog and not have input fields in this list. It gives us the space we need and I think lets the user see what they have typed a lot better. We would then need edit functionality too. Just a thought on my own frustrations at adding a description of any substantial length.

**Comment by nicolas-raoul** [comment]
Fixed in master, thanks all! :-)
