### ISSUE TITLE
"Did you shoot these two pictures at the same place" is not translatable

### ISSUE THREAD

**Issue by amire80** [commons-app/apps-android-commons#3557]
The message "Did you shoot these two pictures at the same place? Do you want to use the latitude/longitude of the picture on the right?" is not translatable on translatewiki.

It appears in the code in app/src/main/res/layout/fragment_similar_image_dialog.xml, but not on translatewiki. I've just seen in the app, even though I see the rest of the app in Hebrew.

I suspect that other messages from the same are also not translatable.

**Comment by sivaraam** [comment]
Yeah. As you've observed. It seems the string is currently non translatable. It has to be moved to the `strings.xml` file to enable translation.

On a related note, there's discussion going on in #3550 about whether this feature could be removed. You can be part of the discussion if you're interested @amire80 :)

**Comment by amire80** [comment]
Whatever, I don't care very much to be honest. I trust the app's designers on this. But if you do plan to keep it, please make it translatable :)
