### ISSUE TITLE
Nearby: Copy the place name on long click

### ISSUE THREAD

**Issue by 6point022** [commons-app/apps-android-commons#3558]
**Summary:** 

In Nearby, copy the place name to clipboard on long click, instead of just a normal click.

**How can we reproduce the issue?**

Open Nearby. Select any location pin. Tap on the place name.

**What did you expect the app to do, and what did you see instead?**

Currently, a normal click also copies the text to clipboard. And it is very annoying because the toast appears whenever we expand or collapse the place information (see gif below).

It was first introduced through issue #2405. Clearly, it was always intended to be a copy on long click. However, this was changed (most probably by mistake) when [these](https://github.com/commons-app/apps-android-commons/commit/44cdd2fdc729f1e38b93459c21e57c2250257ec4#diff-8d9ad016c785a9a63a7d770dc72dbebd) commits were made, and the code from `NearbyMapFragment.java` was shifted to `NearbyParentFragment.java`.

**Screen-shots:** 

![screen](https://user-images.githubusercontent.com/44764339/77186720-572a1c80-6af9-11ea-93d7-fb52174ed853.gif)

**Would you like to work on the issue?**

Yes.

**Comment by macgills** [comment]
Long click always hides a feature for me, the benefit here is if people do try to select the text by long pressing on it we get rid of the need to deal with highlighting. If we wish to surface this functionality better an explicit copy button could be used like the github icon
![image](https://user-images.githubusercontent.com/3358282/77299377-438ed980-6ce4-11ea-8a70-511b08a1d007.png)
or the text `copy` itself

**Comment by nicolas-raoul** [comment]
@6point022 I agree that it is annoying now. Good enhancement idea! :-)

Since it is a very non-vital feature, I don't think we need to surface it more.
Actually the Google Maps app does not surface it either, but the place name is actually copyable via long-press.

**Comment by 6point022** [comment]
@nicolas-raoul Let me know if the proposed solution (changing it to a long click) is fine and I will create a PR. :)

**Comment by nicolas-raoul** [comment]
Yes, it is fine. Thanks! :-)
