### ISSUE TITLE
Logos in "About" screen are hardly viisble in dark theme

### ISSUE THREAD

**Issue by sivaraam** [commons-app/apps-android-commons#3567]
**Summary:** 
The logos in About screen were recently changed in #3444. But the new logos are hardly visible in dark theme. We should show appropriate logos which are visible well in dark theme.

**Screen-shots:** 
![Screenshot_2020-03-21-21-46-41](https://user-images.githubusercontent.com/12448084/77290161-93c86480-6d01-11ea-9242-22f9c9277f73.png)

**Comment by bharathbiju** [comment]
guess this issue has been cleared @sivaraam 
if so could you please close the issue  @nicolas-raoul

**Comment by madhurgupta10** [comment]
> guess this issue has been cleared @sivaraam
> if so could you please close the issue @nicolas-raoul

@bharathbiju I don't think this issue is solved yet!

**Comment by madhurgupta10** [comment]
Pinging @misaochan and @nicolas-raoul for suggestions!

**Comment by macgills** [comment]
Change them to white? Are these vectors? You can change 1 line to get them to be white, add that as a new icon and then use attributes set in light/dark theme to switch between the images, there are some examples for colors already there

**Comment by sivaraam** [comment]
> Change them to white?

Changing color is nice. But changing it to white might make the icons stand out in the black background and they might possibly attract attention away from the text (which seems to be greyish in color). It would be nice if we could use a different color other than white.

But it seems, both [Facebook](https://en.facebookbrand.com/facebookapp/assets/f-logo?audience=landing) and [GitHub](github.com/logos) are against changing colors. So, I think it's better if we just use the light colored icons provided by them as it is.

* GitHub has a light colored icons in it's [mark logo zip](https://github-media-downloads.s3.amazonaws.com/GitHub-Mark.zip)
* Facebook has both grey and white icons but I think we can just go with white to be consistent.
* For the globe icon we use Material *public* icon and we can download a white colored icon from [their website](https://material.io/resources/icons/?search=publi&icon=public&style=baseline).

**Comment by madhurgupta10** [comment]
How about keeping the color of logos black and adding a small white circle in the background similar to the Github Android App Icon.

**Comment by macgills** [comment]
Use white, I think we are all in agreement.

Now who wants the ticket assigned?

**Comment by madhurgupta10** [comment]
@macgills The issue seems to be perfect for first-time contributors.

**Comment by isnirp** [comment]
hello @macgills @nicolas-raoul I would like to handle this issue.

**Comment by sivaraam** [comment]
@isnirp I've assigned this to you. Let us know how you get on. Feel free to ask for any help, if need be. :)

**Comment by isnirp** [comment]
@sivaraam it's resolved. created an attr for images present in about.  do I do a PR?

![dark](https://user-images.githubusercontent.com/10153512/77791083-4bdd7080-7066-11ea-9d63-e0d19f5c1cd5.jpeg)

**Comment by sivaraam** [comment]
@isnirp That's great!

> do I do a PR?

Sure, feel free to open a PR :)
