### ISSUE TITLE
In review page bottom texts are hidden.

### ISSUE THREAD

**Issue by prince-09** [commons-app/apps-android-commons#3570]
**Summary:** 

bottom text are hidden in the review page.

**Steps to reproduce:** 

go to the review page.

**Device and Android version:** 

Mi 5a
25 API
 
**Commons app version:** 
2.12.3

**Comment by macgills** [comment]
Can you add an image please @prince-09

**Comment by bharathbiju** [comment]
![commons](https://user-images.githubusercontent.com/37261249/77330446-63a2b500-6d45-11ea-8b46-872df025a562.jpeg)
 @macgills i am sure this is what @prince-09  meant

**Comment by macgills** [comment]
This has an open pr, closing
