### ISSUE TITLE
Remove empty icon space/left padding from Settings

### ISSUE THREAD

**Issue by gupta-anmol** [commons-app/apps-android-commons#3573]
**Summary:** 

There's empty space before every preference in the Settings page.
This may be due to the PR for issue #3465.

**Screen-shots:** 

_This is how it looked before._

![image](https://user-images.githubusercontent.com/44764339/77318450-19183d00-6d33-11ea-9f8b-60d3e947b8aa.png)

_This is how it looks now._

![image](https://user-images.githubusercontent.com/44764339/77318326-e79f7180-6d32-11ea-8514-88a1f59d89bd.png)

**Would you like to work on the issue?**

No, feel free to take it up.

**Comment by macgills** [comment]
Not an issue, just how settings screen works, see [docs](https://developer.android.com/guide/topics/ui/settings)

**Comment by sivaraam** [comment]
I was about open an issue for the same reason. It kind of feels weird seeing the Settings page this way. I've never seen any Settings page like this with lots of space to the left and in between settings. See below screenshots:

![Screenshot_2020-03-29-00-15-38](https://user-images.githubusercontent.com/12448084/77831159-6e998300-7153-11ea-9fc3-f51c4ac962f4.png)
![Screenshot_2020-03-29-00-17-21](https://user-images.githubusercontent.com/12448084/77831161-72c5a080-7153-11ea-92a7-ef3994acb589.png)

It really seems like it's wasting a lot of space when I scroll through it in my device (Samsung SM-J111F). Couldn't we reduce the amount of space this takes?

**Comment by macgills** [comment]
apparently we can use `app:iconSpaceReserved="false"`? I suppose go for it if it still looks alright, I was hesitant to do it because `<*Preference` elements have no attributes like `padding/margin`

**Comment by sivaraam** [comment]
Just wanted to share another issue that I noted with the extra space. If you observe the following screenshot closely, you would notice weird white dots (in dark theme) corresponding to each setting.

![Screenshot_2020-03-31-15-52-50](https://user-images.githubusercontent.com/12448084/78712045-9b108480-7935-11ea-9c2a-71db3ab292aa.png)

I'm wondering why they're shown. 🤔

**Comment by macgills** [comment]
We could use layoutInspector to expose the underlying view hierarchy and what these views are? Kiwix , which is my latest dark mode/prefs screen experience, is unfortunately not using androidx preferences and has a DayNight theme driven night mode, not much similarity

**Comment by sivaraam** [comment]
> We could use layoutInspector to expose the underlying view hierarchy and what these views are? 

I'm not familiar with this. Let me know how I could help with this.

**Comment by macgills** [comment]
![image](https://user-images.githubusercontent.com/3358282/78870561-3bea6700-7a3e-11ea-9998-22a7489fac45.png)
Click this with the app running on the screen you want to inspect and you get to see what the views actually are along with their attributes
Ignore the custom key binding I have for it.

**Comment by sivaraam** [comment]
Ok. This is what I get when inspecting the Settings screen:

![image](https://user-images.githubusercontent.com/12448084/78929575-477e7200-7ac0-11ea-958e-d883ed413671.png)

**Comment by macgills** [comment]
Perhaps recheck that after this issue is addressed, with any luck it will just disappear. If it doesn't we will make a new issue

**Comment by madhurgupta10** [comment]
> apparently we can use `app:iconSpaceReserved="false"`? I suppose go for it if it still looks alright, I was hesitant to do it because `<*Preference` elements have no attributes like `padding/margin`

@macgills I think ```iconSpaceReserved``` is only available on API 26+

**Comment by sivaraam** [comment]
> @macgills I think `iconSpaceReserved` is only available on API 26+

So, that's why it didn't work in my device (API 22) when I tried using it. 🤔

**Comment by macgills** [comment]
it has the `app:` prefix, it is backported by the androidx libraries. Ye must have been using `android:` prefix which uses the platform implementation

**Comment by sivaraam** [comment]
I did use the `app:` prefix.

This diff captures what I tried:

```diff
diff --git app/src/main/res/xml/preferences.xml app/src/main/res/xml/preferences.xml
index e58dbefd6..b8af50b10 100644
--- app/src/main/res/xml/preferences.xml
+++ app/src/main/res/xml/preferences.xml
@@ -3,6 +3,7 @@
   xmlns:android="http://schemas.android.com/apk/res/android">

     <PreferenceCategory
+      app:iconSpaceReserved="false"
       android:title="@string/preference_category_appearance">

         <ListPreference
@@ -17,6 +18,7 @@
     </PreferenceCategory>

     <PreferenceCategory
+      app:iconSpaceReserved="false"
       android:title="@string/preference_category_general">

         <SwitchPreference
@@ -75,6 +77,7 @@
     </PreferenceCategory>

     <PreferenceCategory
+      app:iconSpaceReserved="false"
       android:title="@string/preference_category_privacy">

         <MultiSelectListPreference
@@ -91,6 +94,7 @@
           Do not reuse this key unless you revive the same feature with the changes mentioned at #1599.-->

     <PreferenceCategory
+      app:iconSpaceReserved="false"
       android:title="@string/preference_category_feedback">

         <Preference

```

**Comment by macgills** [comment]
https://issuetracker.google.com/issues/111662669 this was an issue in the lead up to 1.1.0 but it has been resolved? I don't think this is limited by api level

```
    /**
     * Sets whether to reserve the space of this preference icon view when no icon is provided. If
     * set to true, the preference will be offset as if it would have the icon and thus aligned with
     * other preferences having icons.
     *
     * @param iconSpaceReserved Set {@code true} if the space for the icon view should be reserved
     *                          {@link android.R.attr#iconSpaceReserved}
     */
    public void setIconSpaceReserved(boolean iconSpaceReserved) {
        if (mIconSpaceReserved != iconSpaceReserved) {
            mIconSpaceReserved = iconSpaceReserved;
            notifyChanged();
        }
    }
```

certainly unmentioned in the method.

I tried briefly on API 27 with android: app: and setting it in code to no effect. Makes me think something is wrong in the implementation, ours or the library. Sadly there is no later version to upgrade to

**Comment by SaumiaSinghal** [comment]
Hi @macgills, @sivaraam Can I work on this, if no one else is working on it?

**Comment by sivaraam** [comment]
Hi @SaumiaSinghal, yeah you can work on this. No one appears to be working on this.
