### ISSUE TITLE
Flickering colors on screen

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#3575]
In the current master, when an image is uploading, colors flicker frantically in the contributions list. This needs to be fixed, especially since it could be an epilepsy trigger(?).

**Comment by misaochan** [comment]
Perhaps picking one color and sticking to it would be a good idea. Maybe white in regular mode and black in dark mode? @neslihanturan

**Comment by ashishkumar468** [comment]
@neslihanturan  can you confirm the UI suggestions by @misaochan

**Comment by neslihanturan** [comment]
I agree with picking one color but, can't we pick the same color with background color of each theme? Dark grey and light grey, instead of harsh black and white. Then there wont be any flickering effect, I guess?

**Comment by ashishkumar468** [comment]
@neslihanturan Just of confirm,  you mean these for the corresponding themes?
```
<color name="main_background_dark">#303030</color>
    <color name="main_background_light">#fafafa</color>
```

**Comment by misaochan** [comment]
> I agree with picking one color but, can't we pick the same color with background color of each theme? Dark grey and light grey, instead of harsh black and white. Then there wont be any flickering effect, I guess?

Sounds good to me.

**Comment by neslihanturan** [comment]
Yes @ashishkumar468 , exactly those two.
