### ISSUE TITLE
If you get the "Is this a picture of..." popup and you say "No", it still autofills the title/desc

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#3576]
**Summary:** 

If you get the "Is this a picture of..." popup and you say "No", it still autofills the title/desc

**Steps to reproduce:** 

Upload a photo with a geotag near a popular location. You will get the popup. If you say "no", the title/desc should be empty, but they are still autofilled.

**Device and Android version:** 

Samsung Galaxy S9, Android 10
 
**Commons app version:** 

Current master

**Would you like to work on the issue?**

Pref not.

**Comment by maskaravivek** [comment]
I think this issue cropped up because recently we swapped the positive and negative buttons for dialog boxes. Therefore title/desc is getting filled when you say no and nothing happens on clicking yes.

**Comment by misaochan** [comment]
@maskaravivek Wait, hold on, we swapped ALL of them?? I thought we were only swapping for one specific dialog. Which PR was this again...?

**Comment by misaochan** [comment]
Alright, I found it. The PR is #3496 , which handles the issue in #3428. Based on the opening post, I was under the assumption that we were only making the change for the "turn location on" dialog (and I specifically mentioned that I was okay with the change being made for [just that dialog](https://github.com/commons-app/apps-android-commons/issues/3428#issuecomment-597510758)), but it seems like the changes were broader than that.

We may need to go through and check the other dialogs to be certain that this problem does not happen for the other ones. It can be a very big issue (like a "we have to apologize on Village Pump and make a bot to correct it" big issue) if a user says "no" to something and we end up still doing it.

**Comment by maskaravivek** [comment]
Yes, I just checked the PR and am not sure why it was implemented that way. IMO, its better to revert #3496 instead of discovering and fixing all issues one by one.

**Comment by sivaraam** [comment]
To give some context, the change was done that way as @macgills rightly pointed out](https://github.com/commons-app/apps-android-commons/issues/3428#issuecomment-597515984) that "Positive/negative have no correlation between destructive/constructive actions. It is simply the response to the question posed". After some discussion we decided to switch the position of the dialog buttons [[ref](https://github.com/commons-app/apps-android-commons/issues/3428#issuecomment-597772241)]. And as there was no objection the PR was merged.

To clarify one more thing the issue #3428 was never about the location dialog it was in general about the API in `DialogUtils`. Though I understand how the screenshot in the description might be misleading.

**Comment by misaochan** [comment]
@sivaraam Thanks for the clarification. Yeah, I think there may have been a misunderstanding. :/

The changes are being checked at https://github.com/commons-app/apps-android-commons/issues/3428#issuecomment-603741583

**Comment by macgills** [comment]
I would move to close this in lieu of my comment.

**Comment by misaochan** [comment]
Right, thanks @macgills . :)
