### ISSUE TITLE
Add tooltips for "depicts"

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#3584]
Structured-data introduces a new concept to users, depicts. It would be good if we could add a tooltip to the "depicts" upload stage in the structured-data branch, to educate them on what it means (similar to what we currently have for title/desc).

**Comment by vvijayalakshmi21** [comment]
Hi @misaochan 
When you say tooltips, do you refer to the one we see in Nearby (which upon clicking shows a text) or does it have to be a toast displayed when the user presses on the icon long?

**Comment by vvijayalakshmi21** [comment]
I would like to take this up after #3526 if thats okay?

**Comment by misaochan** [comment]
> When you say tooltips, do you refer to the one we see in Nearby (which upon clicking shows a text) 

Yes, I am referring to this one. Or the tooltips displayed in the title/desc section of the upload process.

> I would like to take this up after #3526 if thats okay?

Sure! :)

**Comment by nicolas-raoul** [comment]
Here is the activity to which the tooltip should be added:
![Screenshot_20200411-183347_Commons](https://user-images.githubusercontent.com/99590/79042003-06f13680-7c2f-11ea-87f4-a616eb495276.jpg)

Here is how tooltips work in Step 1:
![Screenshot_20200411-183904_Commons](https://user-images.githubusercontent.com/99590/79042896-70c10e80-7c36-11ea-88f6-5d2cdb1cd992.jpg)

Maybe you could implement it like this:
![Screenshot_20200411-183347_Commons](https://user-images.githubusercontent.com/99590/79043910-34dd7780-7c3d-11ea-8c10-21d441986985.jpg)

**Comment by vvijayalakshmi21** [comment]
Thanks @nicolas-raoul 
I will start looking into this.

**Comment by nicolas-raoul** [comment]
The text can be rather long, for instance the tooltip for "description" is 10 lines. I suggest:

Select all things that your picture shows. For instance, if your picture shows a townhall in Smallville, then please select both "Townhall" and "Smallville". Try to be a specific as possible, for instance select "bulldog" instead of "dog" or "animal". Nearby items and recently used items may appear in the list, please only select the items that are actually visible in your picture.

**Comment by vvijayalakshmi21** [comment]
Hi @nicolas-raoul 
I checked the code and I see that for step 1 the relevant java files are UploadMediaDetailAdapter and UploadMediaDetailFragment. Currently for depictions we have only DepictsFragment and no adapter file. Shall I create a new one similar to the uploadmedia adapter and proceed to make changes?

**Comment by macgills** [comment]
@vvijayalakshmi21 the code being located in the adapter is not relevant to this feature, adapters are just classes that feed data into views and on structured data all these input fields are a part of a list.

If you look at the master branch you will see a freewheeling textview outside the list in uploadMediaDetail and that is closer to what we want but is not such a terrific example either, it should really be following [this advice](https://material.io/develop/android/components/text-fields/)

Raoul's mockup has the icon positioned outside of the textview
![image](https://user-images.githubusercontent.com/3358282/79430821-68176200-7fc1-11ea-8e0b-75a069583345.png)

So we don't even need to bother with TextInputLayout methods and can just use an ImageView + clickListener

If we were to use TextInpuLayout endIcon then I think it might overlap with the progress indication so if you think that looks better we might have to move the progress indication elsewhere

**Comment by misaochan** [comment]
I think keeping the progress indicator in the search field and having the tooltip icon outside the EditText as @nicolas-raoul suggests would be best.

**Comment by VibhorChinda** [comment]
Can i take this issue ?? @misaochan

**Comment by misaochan** [comment]
@vvijayalakshmi21 are you still interested in working on this?

**Comment by VibhorChinda** [comment]
Can I work on this ? @misaochan

**Comment by misaochan** [comment]
Let's give @vvijayalakshmi21 a bit more time to get back to us, if another week passes I think we can assign to you @VibhorChinda .

**Comment by vvijayalakshmi21** [comment]
@misaochan Sincere apologies for not getting back. 
Please feel free to reassign to @VibhorChinda

**Comment by misaochan** [comment]
Thanks for getting back @vvijayalakshmi21 ! @VibhorChinda It is yours. :)

**Comment by robsonbbs** [comment]
Can I take this?

**Comment by nicolas-raoul** [comment]
@VibhorChinda Are you working on this? :-)

**Comment by VibhorChinda** [comment]
@nicolas-raoul Please feel free to re-assign the issue to @robsonbbs  :)

**Comment by nicolas-raoul** [comment]
@robsonbbs It is yours, please let us know about your progress every few days at least, thanks :-)

**Comment by madisoncfallin** [comment]
Any chance I could take this over? :)

**Comment by nicolas-raoul** [comment]
@robsonbbs How is your progress so far? :-)

**Comment by gouri-panda** [comment]
@nicolas-raoul  I want to work on this issue.

**Comment by gouri-panda** [comment]
>If we were to use TextInpuLayout endIcon then I think it might overlap with the progress indication so if you think that looks better we might have to move the progress indication elsewhere

@nicolas-raoul As seàn suggested we can place the icon inside the `TextInputEditText` and on the side of progress bar like this.
<img width="709" alt="Screenshot 2020-11-07 at 9 28 17 PM" src="https://user-images.githubusercontent.com/43576162/98445871-28bc8880-2140-11eb-962d-d999230de11a.png">

**Comment by misaochan** [comment]
Oh wow, I just realized that this issue overlaps with #3757 , since it makes sense to include tooltips with the "depicts" title. @gouri-panda would you mind discussing this on #3757 ? Then I can close this issue.

**Comment by Roshan13046** [comment]
Is anyone still working on this issue?

**Comment by nicolas-raoul** [comment]
@Roshan13046 Double sorry: 1) For my late reply 2) Because we forgot to close this issue, the "tooltip" is already implemented. Please feel free to look at other issues, thanks a lot! :-)
