### ISSUE TITLE
Use Checkstyle for travis-CI

### ISSUE THREAD

**Issue by veyndan** [commons-app/apps-android-commons#359]
I saw that it was mentioned in passing on #24 but nothing seemed to come of it. As Travis-CI is now in use since that issue, I feel it would be beneficial to reconsider the use of Checkstyle as Checkstyle would then be run against every PR. My suggestion would to use Google's coding standard as it is one of the more popular ones.

I'd be happy to work on this but just want some confirmation that such a change is desired.

**Comment by misaochan** [comment]
Sounds good to me :)
