### ISSUE TITLE
Unable to exit the app from onbarding tutorial

### ISSUE THREAD

**Issue by sivaraam** [commons-app/apps-android-commons#3590]
**Summary:** 
After a fresh install, we show the onboarding tutorial to the users to educate them about Wikimedia Commons and the kinds of pictures they can upload. That's nice. But it's impossible to exit the tutorial using the back button. This seems too restrictive and unreasonable, IMO. An user should be able to exit the tutorial without issues. We can show them the tutorial again upon next open if they haven't completed it.

**Steps to reproduce:** 
1. Install the app
2. Open the app
3. Confirm that the tutorial screen is shown
4. Tap on back to exit the app
5. Observe that it's not possible to exit the app

**Device and Android version:** 
Samsung SM-J111, Android 5.1.1

**Commons app version:** 
2.12.3.629~a63a358

**Comment by 318anushka** [comment]
@sivaraam I think it's a minor change. will fix this.

**Comment by 318anushka** [comment]
It's done, should i submit a PR for this?

**Comment by sivaraam** [comment]
@318anushka Sure, feel free to submit a PR :)

**Comment by madhurgupta10** [comment]
@sivaraam on beta we provide a **Skip Tutorial** button but on prod, it's intentionally hidden from there so we should be giving this feature only for beta IMO.

**Comment by sivaraam** [comment]
@madhurgupta10 I don't get it. Why should we prevent the user from exiting the tutorial in any case? Wouldn't that be intrusive? It's his wish if he wants to exit. As mentioned in the description, we can show the tutorial again if he hasn't completed it.

Also, as of now the user *can* exit by tapping on home or removing app from recent apps. We're just making sure they can exit via the back button too for ease of use.

**Comment by ashishkumar468** [comment]
Yes, this is clearly a back, the back button should take him to the previous activity or so exit the app if there are no activities in the stack

**Comment by sivaraam** [comment]
> Yes, this is clearly a bug, the back button should take him to the previous activity or so exit the app if there are no activities in the stack

Exactly. This is what I was thinking too.

Jus in case it's not clear, I'm speaking of exiting the app by tapping on back from the *first tutorial screen*. I'm not speaking of exiting the app when the user is in the middle of the tutorial.

**Comment by 318anushka** [comment]
We don't want to exit from app when user again go through the tutorial after login, right?
In that case we want to go to the previous activity.
Have to modify the code because in that case too, on pressing back app closes clearing the backstack.

**Comment by sivaraam** [comment]
> We don't want to exit from app when user again go through the tutorial after login, right?

Right.

> In that case we want to go to the previous activity.

Exactly.

Also, I think there's *at least* one case in which the tutorial is shown. When you have more number of deletions (> 50%) the app prompts you to take a quiz. If you answer that quiz badly it asks you go through the tutorial, AFAIR.

**Comment by madhurgupta10** [comment]
> @madhurgupta10 I don't get it. Why should we prevent the user from exiting the tutorial in any case? Wouldn't that be intrusive? It's his wish if he wants to exit. As mentioned in the description, we can show the tutorial again if he hasn't completed it.
> 
> Also, as of now the user _can_ exit by tapping on home or removing app from recent apps. We're just making sure they can exit via the back button too for ease of use.

I wanted to share that the **prod** do not have the **Skip Tutorial** button which was intentionally hidden (which I assume to force new users to go through the tutorial) but as you said it doesn't make much sense to prevent a user from skipping the tutorial. So we should allow the user to quit the tutorial by pressing the back button and also show the **Skip Tutorial** button for **prod** also.

![Screenshot_20200331-224302](https://user-images.githubusercontent.com/30932899/78073535-5d45b600-73a1-11ea-8011-f40e3c0b13d6.png)
![Screenshot_20200331-224244](https://user-images.githubusercontent.com/30932899/78073538-5e76e300-73a1-11ea-8514-9e063be6ec9d.png)

**Comment by 318anushka** [comment]
@madhurgupta10 Actually, it's not about skipping tutorial but exiting the app on pressing back button in the first screen of tutorial. 
Fresh install the app and open it and try to exit the app by pressing back button. It won't, first screen of tutorial keeps popping up.

**Comment by madhurgupta10** [comment]
> @madhurgupta10 Actually, it's not about skipping tutorial but exiting the app on pressing back button in the first screen of tutorial.
> Fresh install the app and open it and try to exit the app by pressing back button(keep pressing until you reach first screen). It won't, first screen of tutorial keeps popping up.

Okay, now I see the bug. I was trying it by launching the Tutorial from the Navigation Drawer.
