### ISSUE TITLE
Q1402200 shows up on the map as not photographed

### ISSUE THREAD

**Issue by VojtechDostal** [commons-app/apps-android-commons#3591]
Interestingly, [Q1402200](https://www.wikidata.org/wiki/Q1402200) shows up on my map as blue - unphotographed - even though it has P18 correctly filled in. Do you see it too?

![Screenshot_20200328-165846_Commons](https://user-images.githubusercontent.com/21329813/77827377-84885300-7115-11ea-8bbf-16539c984389.jpg)

**Comment by sivaraam** [comment]
I can confirm that I could see Q1402200 in Nearby too.

![Screenshot_2020-03-28-22-36-46](https://user-images.githubusercontent.com/12448084/77828982-00e65a80-7145-11ea-9292-df24bc08db7c.png)

**Comment by misaochan** [comment]
@VojtechDostal Is this the only occurrence that you've seen, or are there others as well?

**Comment by VojtechDostal** [comment]
The only one I have seen so far. We can leave it for now and wait if someone reports other similar cases of this behaviour. 

Also I wonder if Q1402200 would pop up in the "unphotographed" results of the app's SPARQL query if accessed using https://query.wikidata.org.

**Comment by neslihanturan** [comment]
Hey @VojtechDostal , what happens 
1- if you deselect need photo
2- Then select it back?

**Comment by nicolas-raoul** [comment]
Strange, the Wikidata item looks perfectly normal, no special attributes or anything unusual.
Time to show off how I can see inside HTTPS packets thanks to [HttpCanary](https://github.com/MegatronKing/HttpCanary):
![Screenshot_20200401-152303_Commons](https://user-images.githubusercontent.com/99590/78106001-7005cc80-742d-11ea-9f25-1fc0aae394a9.jpg)
Request:
```
GET /sparql?query=SELECT%0A%20%20%20%20%20%28SAMPLE%28%3Flocation%29%20as%20%3Flocation%29%0A%20%20%20%20%20%3Fitem%0A%20%20%20%20%20%28SAMPLE%28COALESCE%28%3FitemLabelPreferredLanguage%2C%20%3FitemLabelAnyLanguage%29%29%20as%20%3Flabel%29%0A%20%20%20%20%20%28SAMPLE%28%3FclassId%29%20as%20%3Fclass%29%0A%20%20%20%20%20%28SAMPLE%28COALESCE%28%3FclassLabelPreferredLanguage%2C%20%3FclassLabelAnyLanguage%2C%20%22%3F%22%29%29%20as%20%3FclassLabel%29%0A%20%20%20%20%20%28SAMPLE%28COALESCE%28%3Ficon0%2C%20%3Ficon1%29%29%20as%20%3Ficon%29%0A%20%20%20%20%20%3FwikipediaArticle%0A%20%20%20%20%20%3FcommonsArticle%0A%20%20%20%20%20%28SAMPLE%28%3FcommonsCategory%29%20as%20%3FcommonsCategory%29%0A%20%20%20%20%20%28SAMPLE%28%3Fpic%29%20as%20%3Fpic%29%0A%20%20%20%20%20%28SAMPLE%28%3Fdestroyed%29%20as%20%3Fdestroyed%29%0A%20%20%20WHERE%20%7B%0A%20%20%20%20%20%23%20Around%20given%20location...%0A%20%20%20%20%20SERVICE%20wikibase%3Aaround%20%7B%0A%20%20%20%20%20%20%20%3Fitem%20wdt%3AP625%20%3Flocation.%0A%20%20%20%20%20%20%20bd%3AserviceParam%20wikibase%3Acenter%20%22Point%2813.9399%2049.8140%29%22%5E%5Egeo%3AwktLiteral.%0A%20%20%20%20%20%20%20bd%3AserviceParam%20wikibase%3Aradius%20%224.24%22%20.%20%23%20Radius%20in%20kilometers.%0A%20%20%20%20%20%7D%0A%0A%20%20%20%20%20%23%20Get%20the%20label%20in%20the%20preferred%20language%20of%20the%20user%2C%20or%20any%20other%20language%20if%20no%20label%20is%20available%20in%20that%20language.%0A%20%20%20%20%20OPTIONAL%20%7B%3Fitem%20rdfs%3Alabel%20%3FitemLabelPreferredLanguage.%20FILTER%20%28lang%28%3FitemLabelPreferredLanguage%29%20%3D%20%22en%22%29%7D%0A%20%20%20%20%20OPTIONAL%20%7B%3Fitem%20rdfs%3Alabel%20%3FitemLabelAnyLanguage%7D%0A%0A%20%20%20%20%20%23%20Get%20Commons%20category%20%28P373%29%0A%20%20%20%20%20OPTIONAL%20%7B%20%3Fitem%20wdt%3AP373%20%3FcommonsCategory.%20%7D%0A%0A%20%20%20%20%20%23%20Get%20%28P18%29%0A%20%20%20%20%20OPTIONAL%20%7B%20%3Fitem%20wdt%3AP18%20%3Fpic.%20%7D%0A%0A%20%20%20%20%20%23%20Get%20%28P576%29%0A%20%20%20%20%20OPTIONAL%20%7B%20%3Fitem%20wdt%3AP576%20%3Fdestroyed.%20%7D%0A%0A%20%20%20%20%20%23%20Get%20the%20class%20label%20in%20the%20preferred%20language%20of%20the%20user%2C%20or%20any%20other%20language%20if%20no%20label%20is%20available%20in%20that%20language.%0A%20%20%20%20%20OPTIONAL%20%7B%0A%20%20%20%20%20%20%20%3Fitem%20p%3AP31%2Fps%3AP31%20%3FclassId.%0A%20%20%20%20%20%20%20OPTIONAL%20%7B%3FclassId%20rdfs%3Alabel%20%3FclassLabelPreferredLanguage.%20FILTER%20%28lang%28%3FclassLabelPreferredLanguage%29%20%3D%20%22en%22%29%7D%0A%20%20%20%20%20%20%20OPTIONAL%20%7B%3FclassId%20rdfs%3Alabel%20%3FclassLabelAnyLanguage%7D%0A%0A%20%20%20%20%20%20%20OPTIONAL%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%3FwikipediaArticle%20%20%20schema%3Aabout%20%3Fitem%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20schema%3AisPartOf%20%3Chttps%3A%2F%2Fen.wikipedia.org%2F%3E%20.%0A%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20OPTIONAL%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%3FwikipediaArticle%20%20%20schema%3Aabout%20%3Fitem%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20schema%3AisPartOf%20%3Chttps%3A%2F%2Fen.wikipedia.org%2F%3E%20.%0A%20%20%20%20%20%20%20%20%20%20%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22en%22%20%7D%0A%20%20%20%20%20%20%20%20%20%7D%0A%0A%20%20%20%20%20%20%20%20%20OPTIONAL%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%3FcommonsArticle%20%20%20schema%3Aabout%20%3Fitem%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20schema%3AisPartOf%20%3Chttps%3A%2F%2Fcommons.wikimedia.org%2F%3E%20.%0A%20%20%20%20%20%20%20%20%20%20%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22en%22%20%7D%0A%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%7D%0A%20%20%20%7D%0A%20%20%20GROUP%20BY%20%3Fitem%20%3FwikipediaArticle%20%3FcommonsArticle%0A&format=json h2
Host: query.wikidata.org
accept-encoding: gzip
user-agent: okhttp/4.2.0
```
[Link](query.wikidata.org/sparql?query=SELECT%0A%20%20%20%20%20%28SAMPLE%28%3Flocation%29%20as%20%3Flocation%29%0A%20%20%20%20%20%3Fitem%0A%20%20%20%20%20%28SAMPLE%28COALESCE%28%3FitemLabelPreferredLanguage%2C%20%3FitemLabelAnyLanguage%29%29%20as%20%3Flabel%29%0A%20%20%20%20%20%28SAMPLE%28%3FclassId%29%20as%20%3Fclass%29%0A%20%20%20%20%20%28SAMPLE%28COALESCE%28%3FclassLabelPreferredLanguage%2C%20%3FclassLabelAnyLanguage%2C%20%22%3F%22%29%29%20as%20%3FclassLabel%29%0A%20%20%20%20%20%28SAMPLE%28COALESCE%28%3Ficon0%2C%20%3Ficon1%29%29%20as%20%3Ficon%29%0A%20%20%20%20%20%3FwikipediaArticle%0A%20%20%20%20%20%3FcommonsArticle%0A%20%20%20%20%20%28SAMPLE%28%3FcommonsCategory%29%20as%20%3FcommonsCategory%29%0A%20%20%20%20%20%28SAMPLE%28%3Fpic%29%20as%20%3Fpic%29%0A%20%20%20%20%20%28SAMPLE%28%3Fdestroyed%29%20as%20%3Fdestroyed%29%0A%20%20%20WHERE%20%7B%0A%20%20%20%20%20%23%20Around%20given%20location...%0A%20%20%20%20%20SERVICE%20wikibase%3Aaround%20%7B%0A%20%20%20%20%20%20%20%3Fitem%20wdt%3AP625%20%3Flocation.%0A%20%20%20%20%20%20%20bd%3AserviceParam%20wikibase%3Acenter%20%22Point%2813.9399%2049.8140%29%22%5E%5Egeo%3AwktLiteral.%0A%20%20%20%20%20%20%20bd%3AserviceParam%20wikibase%3Aradius%20%224.24%22%20.%20%23%20Radius%20in%20kilometers.%0A%20%20%20%20%20%7D%0A%0A%20%20%20%20%20%23%20Get%20the%20label%20in%20the%20preferred%20language%20of%20the%20user%2C%20or%20any%20other%20language%20if%20no%20label%20is%20available%20in%20that%20language.%0A%20%20%20%20%20OPTIONAL%20%7B%3Fitem%20rdfs%3Alabel%20%3FitemLabelPreferredLanguage.%20FILTER%20%28lang%28%3FitemLabelPreferredLanguage%29%20%3D%20%22en%22%29%7D%0A%20%20%20%20%20OPTIONAL%20%7B%3Fitem%20rdfs%3Alabel%20%3FitemLabelAnyLanguage%7D%0A%0A%20%20%20%20%20%23%20Get%20Commons%20category%20%28P373%29%0A%20%20%20%20%20OPTIONAL%20%7B%20%3Fitem%20wdt%3AP373%20%3FcommonsCategory.%20%7D%0A%0A%20%20%20%20%20%23%20Get%20%28P18%29%0A%20%20%20%20%20OPTIONAL%20%7B%20%3Fitem%20wdt%3AP18%20%3Fpic.%20%7D%0A%0A%20%20%20%20%20%23%20Get%20%28P576%29%0A%20%20%20%20%20OPTIONAL%20%7B%20%3Fitem%20wdt%3AP576%20%3Fdestroyed.%20%7D%0A%0A%20%20%20%20%20%23%20Get%20the%20class%20label%20in%20the%20preferred%20language%20of%20the%20user%2C%20or%20any%20other%20language%20if%20no%20label%20is%20available%20in%20that%20language.%0A%20%20%20%20%20OPTIONAL%20%7B%0A%20%20%20%20%20%20%20%3Fitem%20p%3AP31%2Fps%3AP31%20%3FclassId.%0A%20%20%20%20%20%20%20OPTIONAL%20%7B%3FclassId%20rdfs%3Alabel%20%3FclassLabelPreferredLanguage.%20FILTER%20%28lang%28%3FclassLabelPreferredLanguage%29%20%3D%20%22en%22%29%7D%0A%20%20%20%20%20%20%20OPTIONAL%20%7B%3FclassId%20rdfs%3Alabel%20%3FclassLabelAnyLanguage%7D%0A%0A%20%20%20%20%20%20%20OPTIONAL%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%3FwikipediaArticle%20%20%20schema%3Aabout%20%3Fitem%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20schema%3AisPartOf%20%3Chttps%3A%2F%2Fen.wikipedia.org%2F%3E%20.%0A%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20OPTIONAL%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%3FwikipediaArticle%20%20%20schema%3Aabout%20%3Fitem%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20schema%3AisPartOf%20%3Chttps%3A%2F%2Fen.wikipedia.org%2F%3E%20.%0A%20%20%20%20%20%20%20%20%20%20%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22en%22%20%7D%0A%20%20%20%20%20%20%20%20%20%7D%0A%0A%20%20%20%20%20%20%20%20%20OPTIONAL%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%3FcommonsArticle%20%20%20schema%3Aabout%20%3Fitem%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20schema%3AisPartOf%20%3Chttps%3A%2F%2Fcommons.wikimedia.org%2F%3E%20.%0A%20%20%20%20%20%20%20%20%20%20%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22en%22%20%7D%0A%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%7D%0A%20%20%20%7D%0A%20%20%20GROUP%20BY%20%3Fitem%20%3FwikipediaArticle%20%3FcommonsArticle%0A&format=json)
The response contains the item, among others:
```
...
    }, {
      "item" : {
        "type" : "uri",
        "value" : "http://www.wikidata.org/entity/Q1402200"
      },
      "wikipediaArticle" : {
        "type" : "uri",
        "value" : "https://en.wikipedia.org/wiki/Felbabka"
      },
      "location" : {
        "datatype" : "http://www.opengis.net/ont/geosparql#wktLiteral",
        "type" : "literal",
        "value" : "Point(13.942 49.8135)"
      },
      "label" : {
        "xml:lang" : "en",
        "type" : "literal",
        "value" : "Felbabka"
      },
      "class" : {
        "type" : "uri",
        "value" : "http://www.wikidata.org/entity/Q20871353"
      },
      "classLabel" : {
        "xml:lang" : "en",
        "type" : "literal",
        "value" : "cadastral area in the Czech Republic"
      },
      "commonsCategory" : {
        "type" : "literal",
        "value" : "Felbabka"
      },
      "pic" : {
        "type" : "uri",
        "value" : "http://commons.wikimedia.org/wiki/Special:FilePath/Felbabka-ulice.jpg"
      }
    }, {
...
```

**Comment by nicolas-raoul** [comment]
Looks like the problem is somehow solved now.
If anyone finds this issue again, please reopen and let us know, thanks!
![adb](https://user-images.githubusercontent.com/99590/145936324-273c17b5-ffa8-4858-9432-1ec3b7e54675.png)
