### ISSUE TITLE
"No categories matching %1$s found" message is displayed 

### ISSUE THREAD

**Issue by vvijayalakshmi21** [commons-app/apps-android-commons#3594]
**Summary:** 
I tried to search for an image - ''aburasoba azabujuban" by clicking on 'Explore'. When the image results were loading I clicked on the Category tab. I saw a message stating "No categories matching %1$s found"

**Steps to reproduce:** 

How can we reproduce the issue? 
Commons app -> Explore ->Search Commons  -> Enter ''aburasoba azabujuban'' -> Click Categories when the results are loading

What did you expect the app to do, and what did you see instead?
Should not see %1$s text in the screen 

**Device and Android version:** 

Google Pixel 3A
Android Version 10
 
**Commons app version:** 

2.12.3~dc08a5e88

**Screen-shots:** 
![Screenshot_20200329-031804](https://user-images.githubusercontent.com/34595292/77834849-d4ffb080-7115-11ea-8254-c5646f351f67.png)

**Would you like to work on the issue?**

Yes

**Comment by vvijayalakshmi21** [comment]
The same issue is seen for Media as well when we search for ''aburasoba az"
The message reads "No images matching %1$s found"

**Comment by vvijayalakshmi21** [comment]
I did find an issue that is closed - https://github.com/commons-app/apps-android-commons/issues/3254

Not sure if the version I tested has these changed merged.

**Comment by neslihanturan** [comment]
Thanks for reporting this issue @vvijayalakshmi21 :) I think we can close this one since the same issue is reported and still open.

**Comment by vvijayalakshmi21** [comment]
Sorry yeah I meant a merge has been done for this issue and not closed.
