### ISSUE TITLE
Sticky notification when upload fails

### ISSUE THREAD

**Issue by 318anushka** [commons-app/apps-android-commons#3596]
**Summary:** 
When an upload fails, you cannot just swipe away the notification that appears. Have to tap on it which takes you to HomeActivity, then it disappears automatically.However, dismissing it with a swipe would be better.

**Steps to reproduce:** 

- upload a photo.

- Remove internet connection so that upload fails.

- Notification pops up, try to swipe to away. It won't .

**Device and Android version:** 
OnePlus 5 Android 9 API level 28

**Would you like to work on the issue?**

Yes, Sure!!

**Comment by sivaraam** [comment]
@318anushka go for it. Hope I'm not over-assigning issues to you :)

**Comment by 318anushka** [comment]
No😅. Actually i already figured this out while looking for other issue.
I'll submit the PR to get it reviewed.
