### ISSUE TITLE
[structured-commons] From Nearby, "Next" button greyed out until modifying caption

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#3600]
Uploading from Nearby

Button should be available immediately
![Screenshot_20200327-192901_Commons](https://user-images.githubusercontent.com/99590/77873055-ccc58380-7283-11ea-878e-8509c675e9fe.jpg)
![Screenshot_20200327-192937_Commons](https://user-images.githubusercontent.com/99590/77873069-d353fb00-7283-11ea-94e5-ca1ed812c8ed.jpg)

**Comment by vvijayalakshmi21** [comment]
HI Nicolas,
Is this issue reg modifying the caption of an already uploaded image or for a new upload?
I tried to upload a new image and could see different fields on screen plus the Next button automatically enabled once I entered a character in the Title field.
![Screenshot_20200330-123021](https://user-images.githubusercontent.com/34595292/77884455-b7703b00-722a-11ea-8ef7-5a3c08de918b.png)

**Comment by nicolas-raoul** [comment]
This is only for the "structured-data" branch.

**Comment by johnnyrev** [comment]
Can it be assigned to me?

**Comment by nicolas-raoul** [comment]
I forgot to say: it is only when uploading from Nearby.

**Comment by nicolas-raoul** [comment]
@johnnyrev  Any progress on this? Have you managed to reproduce the issue? :-)

**Comment by johnnyrev** [comment]
I recently got into this and I have started working on that issue!

**Comment by macgills** [comment]
@johnnyrev are you still working on this issue? I have availability to work on this if you are happy for me to be assigned it

**Comment by nicolas-raoul** [comment]
@johnnyrev Please commit and push your current work, even if it is not finished, someone might be able to give you tips about your code :-)

**Comment by johnnyrev** [comment]
@nicolas-raoul My apologies for my delayed answer, but I was all in for issue [#3634](https://github.com/commons-app/apps-android-commons/issues/3634). So I haven't managed to implement some code on this one. Please feel free to assign it to someone who is more interested to.

My apologies again!

**Comment by nicolas-raoul** [comment]
@johnnyrev No problem, thanks for letting us know :-)
