### ISSUE TITLE
Include Sign-In link in Sign Up page if Username already exists

### ISSUE THREAD

**Issue by vvijayalakshmi21** [commons-app/apps-android-commons#3603]
**Summary:** 

This is not an issue but just a suggestion.
When a user clicks on Sign-up and enters an existing username, the screen currently only advises that the username already exists. If we modify the message to say that if they are an existing user, then to click on a button/link which would take them to sign-in page, it will be easier.

**Steps to reproduce:** 

Attempt Sign Up using existing Username

**Device and Android version:** 

Android 10
Google Pixel 3a

**Screen-shots:** 
![Screenshot_20200330-121030](https://user-images.githubusercontent.com/34595292/77883645-28aeee80-7229-11ea-9c8d-fb469e12edc1.png)

**Would you like to work on the issue?**
Yes

**Comment by ashishkumar468** [comment]
This is a web view which just shows the signup page, the commons app does not handles the signup on its own

**Comment by vvijayalakshmi21** [comment]
Thanks for clarifying this @ashishkumar468 
So does that mean it's out of scope for us and won't need fixing?

**Comment by ashishkumar468** [comment]
As far as I understand yes, @misaochan would know better

**Comment by misaochan** [comment]
Yes, it is out of scope for us as we do not handle the website.

Thanks anyway @vvijayalakshmi21 . :)
