### ISSUE TITLE
Display thumbnail for categories too

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#3604]
Thumbnails are super useful to distinguish two categories with similar names.

Many categories have images (for instance https://commons.wikimedia.org/wiki/Category:Rabbits see the upper right), probably taken from Wikidata.

We should display thumbnails, like is done for depictions.

**Comment by Ayan-10** [comment]
@nicolas-raoul Can I work on it?

**Comment by nicolas-raoul** [comment]
@Ayan-10 Yes, thanks!

The first step is to find what API URL(s) you need to call to get from "_Category:Rabbits_" to "_Q9121386_" to "_Ikesbunny.jpg_".

**Comment by Ayan-10** [comment]
@nicolas-raoul Yes, I already did that. I think this is the right API call for getting the 70px thumbnail.

https://commons.wikimedia.org/w/api.php?action=query&format=json&prop=pageimages&titles=Category%3ARabbits&piprop=thumbnail&pithumbsize=70

**Comment by nicolas-raoul** [comment]
Wonderful! It is great that you found how to achieve all of this in only 1 API call. 👍
