### ISSUE TITLE
Clicking Cancel in About -> Translate opens the previous activity

### ISSUE THREAD

**Issue by 6point022** [commons-app/apps-android-commons#3606]
**Summary:** 

Clicking Cancel in About -> Translate opens the previous activity.

**Steps to reproduce:** 

Go to About. Click on Translate and press Cancel. 

Instead of staying on the About page, it opens the previous activity.

**Screen-shots:** 

![](https://im.ezgif.com/tmp/ezgif-1-053cd9702337.gif)

**Would you like to work on the issue?**

No, please feel free to take this up. This can also be labelled as a good first issue.

**Comment by isnirp** [comment]
The cancel calls "finish" which causes the about activity to close. I would like to resolve this @sivaraam

**Comment by sivaraam** [comment]
@isnirp Sure. Go for it. :)
