### ISSUE TITLE
Notification marked as read still appearing in unread

### ISSUE THREAD

**Issue by 318anushka** [commons-app/apps-android-commons#3616]
**Steps to reproduce:** 

- click the bell icon

- click on a notification, it will open the webpage

- come back to app, notification marked as read snackbar appears(notification disappears from here).

- go back to home activity

- count of notification is still same and it appears in unread.

What did you expect the app to do, and what did you see instead?
notification to disappear from unread section.

Related issue #2840

**Device and Android version:** 
OnePlus 5 Android 9 API level 28

**Would you like to work on the issue?**
Yes

**Comment by 6point022** [comment]
In which build variant are you facing this issue? I am unable to reproduce this for betaDebug, i.e., the notification disappears correctly for me.

**Comment by 318anushka** [comment]
prodDebug.
I will test it on betaDebug and confirm

**Comment by Pratham2305** [comment]
@318anushka @nicolas-raoul  can I work on this issue ?

**Comment by nicolas-raoul** [comment]
@Pratham2305 Yes thanks :-)
