### ISSUE TITLE
Language names in About -> Translate are not sorted

### ISSUE THREAD

**Issue by 6point022** [commons-app/apps-android-commons#3622]
**Summary:** 

Currently, it is very difficult to find a particular language in the list. The names should be sorted and should be in English. 

**How can we reproduce the issue?** 

Got to About and click on Translate.

**What did you expect the app to do, and what did you see instead?**

The language names displayed should be sorted lexicographically. Since some names are in the respective language, they will also have to be changed to English.

**Commons app version:** 

master betaDebug

**Screen-shots:** 

![image](https://user-images.githubusercontent.com/44764339/78505413-f35a5180-7790-11ea-9080-e70443ad2445.png)

**Would you like to work on the issue?**

Sure.

**Comment by rhulkb27** [comment]
Hi - may I work on this issue?

**Comment by 6point022** [comment]
@rhulkb27 If you are interested then feel free to take it up. However, before beginning to work on this, please get the issue approved by a member/collaborator by tagging them here.

**Comment by rhulkb27** [comment]
Ok, will do. @neslihanturan may I work on this issue?
