### ISSUE TITLE
DateTimeFormat wrong

### ISSUE THREAD

**Issue by macgills** [commons-app/apps-android-commons#3624]
**Summary:** 

Cannot save contribution on successful upload because format is not is08601 datetime

**Steps to reproduce:** 

Attempt to upload anything, see failure.

**System logs:**

```
W/UploadService: Exception during upload
    java.text.ParseException: Unparseable date: "2020-04-07T14:16:51Z"
        at java.text.DateFormat.parse(DateFormat.java:362)
        at fr.free.nrw.commons.upload.UploadService.lambda$uploadContribution$5$UploadService(UploadService.java:290)
```
 
**Commons app version:** 

master.

**Would you like to work on the issue?**

Yes

**Comment by sivaraam** [comment]
Just wanted to mention that this seems related to the change done in PR #3589
