### ISSUE TITLE
[Library Discussion] Core-ktx

### ISSUE THREAD

**Issue by macgills** [commons-app/apps-android-commons#3630]
**Summary:** 

Add [core-ktx](https://developer.android.com/kotlin/ktx#core) dependency.

> The Core KTX module provides extensions for common libraries that are part of the Android framework.

Adding this library will give us access to some nice QOL improvements when writing kotlin.

**Comment by macgills** [comment]
@misaochan @maskaravivek @ashishkumar468 thoughts

**Comment by misaochan** [comment]
I'm on board with this as it's part of Jetpack. But let's wait for the others to chime in.

**Comment by maskaravivek** [comment]
Yes, +1 for having this in our app.

**Comment by misaochan** [comment]
Ashish is away, so I think we are good to go with 2 votes for this.
