### ISSUE TITLE
Many Mnull requests

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#3653]
`structured-data` branch

I see a lot of these lines in my logcat:
```
GET https://commons.wikimedia.org/w/api.php?action=wbgetentities&props=labels&format=json&languagefallback=1&sites=commonswiki&languages=en&ids=Mnull
```
I does not seem to have any bad consequence, but I don't think we can expect it to ever return any useful result either. Is `Mnull` expected to show up sometimes here? If yes, maybe we could avoid sending the request if it is for `Mnull`?

**Comment by macgills** [comment]
This is in the contribution adapter when trying to render captions, the request shouldn't be done with a null id but first of all the id gets `M` prefixed to it hence `Mnull` which isn't null so it does the request. Easy fix but there may be something more fundamental we can do about having to do web requests for 1 piece of text for every Contribution?

**Comment by maskaravivek** [comment]
Yeah, it is a very expensive way of fetching captions. :(

It seems there are limited options to fetch captions as of now. https://commons.wikimedia.org/wiki/Commons:File_captions#How_can_I_query_the_captions_using_the_API?

Perhaps having lazy loading of contributions(#3566) would ease up things a bit.

**Comment by macgills** [comment]
I have elected to just slap a bandaid on this as it is quite annoying right now. I think #2904 is probably the way to go long term, at least for ContributionViewHolder

**Comment by maskaravivek** [comment]
Yes, I agree. I am working on it. It should be in place by this weekend.

**Comment by macgills** [comment]
I have an open PR for it

**Comment by maskaravivek** [comment]
Yes, I was talking about #2904.

**Comment by macgills** [comment]
awesome
