### ISSUE TITLE
No Depictions Selected Dialog has reversed buttons

### ISSUE THREAD

**Issue by macgills** [commons-app/apps-android-commons#3661]
**Summary:** 

The dialog buttons have the positive action in the negative position and vice versa

 
**Commons app version:** 

structuredData

**Comment by sivaraam** [comment]
One comment about the "No, Go back" button in the dialog. It's possible for someone to read the "Go back" (if they don't read the description) and wonder if this would take them to the previous step. I believe "Submit" and "Cancel" would be a concise pair of words that would avoid this confusion.

Also, a more general doubt. Do we really show a dialog whenever a user does not choose any depictions? Wouldn't that be intrusive? Depictions might be a good to have. Can't we convey that in a more subtle way than prompting them each time using a dialog?

**Comment by macgills** [comment]
@sivaraam this issue is now merged and I am going to close it, please open a new ticket for discussion on the text/functionality

**Comment by sivaraam** [comment]
Ok. I've created #3675 for this.
