### ISSUE TITLE
Convert ConfigUtils to Kotlin

### ISSUE THREAD

**Issue by madhurgupta10** [commons-app/apps-android-commons#3673]
**Summary:** 
As per the discussion from the [thread](https://github.com/commons-app/apps-android-commons/issues/747#issuecomment-591081603).

Convert ConfigUtils.java to Kotlin.

**Want to work on this issue?**
Yes

**Comment by neslihanturan** [comment]
Hey @madhurgupta10 , thanks a lot for your issue and PR! But we usually discuss the issue beforehand. Do we want to convert our util files to kotlin, everyone?

**Comment by macgills** [comment]
Yes, that was end of the discussion on #747 I believe

**Comment by madhurgupta10** [comment]
@neslihanturan It was discussed already so I created my PR. Sorry I forgot to link the parent issue :)

**Comment by misaochan** [comment]
Yes, any kotlin conversions that adhere to our code quality guidelines are welcome. :)

**Comment by neslihanturan** [comment]
Oh sorry I missed we let it be used in any files, thanks for clarification :)
