### ISSUE TITLE
Rename buttons of the dialog box shown when no depiction is selected

### ISSUE THREAD

**Issue by sivaraam** [commons-app/apps-android-commons#3675]
It seems that we show the following dialog when a user chooses no depictions in the when uploading an image:

![image](https://user-images.githubusercontent.com/12448084/79694758-13f5d180-8290-11ea-99ee-5a3a12ffa2fa.png)
*(image courtesy: PR #3662)*

I just wanted to share a couple of comments I had about this dialog:
1. The "No, Go back" button in the dialog. It's possible for someone to read the "Go back" (if they don't read the description) and wonder if this would take them to the previous step. I believe "Submit" and "Cancel" would be a concise pair of words that would avoid this confusion.
2. More generally, do we really show a dialog whenever a user does not choose any depictions? Wouldn't that be intrusive? Depictions are a good to have. Can't we convey that in a more subtle way than prompting them each time via a dialog?

*Update: As the scope of the second point seems to have broadened, it has been branched out to #3685. Discussions to continue there.*

**Comment by macgills** [comment]
pinging @nicolas-raoul for his input.

I am all for using different strings for the buttons, this was based on the No Categories Dialog so we should also update that when/if doing this.

I think we want to heavily encourage depictions so I think warning when no Depictions are selected is a good idea but I delegate to nicolas here.

**Comment by nicolas-raoul** [comment]
In my opinion depictions are the future of Commons, since categories are widely unpractical and the category search API is problematic with no fix in view. So I would say we should keep this dialog.
But I agree with you that we can improve the wording. How about "Continue anyway" and "Add a depiction"?

**Comment by macgills** [comment]
"Cancel" and "Submit" are well within the parameters of the official design docs. The positive and negative buttons should be a response to the question posed, [link](https://material.io/components/dialogs#alert-dialog)

**Comment by misaochan** [comment]
My thoughts:
1. I personally feel that we should keep the dialog. We already have a warning dialog when the user submits an upload with no categories (along with a warning for lots of other things like a dark picture), so it isn't much of a stretch to extend that to depictions.
2. I agree with changing the button words to "Cancel" and "Continue" (though if we do choose "Continue", the warning text should change to reflect that).
3. I feel that the warning text itself could do with some improvement. How about something like: "Images with depictions are more easily found and more likely to be used. Are you sure you want to continue without selecting depictions?" ?

**Comment by sivaraam** [comment]
> 1. I personally feel that we should keep the dialog. We already have a warning dialog when the user submits an upload with no categories (along with a warning for lots of other things like a dark picture), so it isn't much of a stretch to extend that to depictions.
>

Thanks for the info. I didn't realize that we show the dialog when a user shows no categories. That just increased my concern about which I've detailed in #3685. Let's discuss it there and keep this just about the renaming of the buttons :)

> 2. I agree with changing the button text to "Cancel" and "Continue" (though if we do choose "Continue", the warning text should change to reflect that).
> 

Agreed. I wonder if we should also rename the dialog buttons of the "No categories selected" dialog too which seem to have the same issue as the "No depictions selected" dialog.

> 3. I feel that the warning text itself could do with some improvement. How about something like: "Images with depictions are more easily found and more likely to be used. Are you sure you want to continue without selecting depictions?" ?

Sounds better to me.

**Comment by macgills** [comment]
I think we are all in agreement, I will open a PR implementing @misaochan 's text
