### ISSUE TITLE
Issues with new meda details UI

### ISSUE THREAD

**Issue by neslihanturan** [commons-app/apps-android-commons#3679]
**Summary:** 
There are some issues appeared after our new media details UI.

1- Moving from portrait to landscape deforms the image, here are the steps to reproduce:
- Display as portrait, first normal
<img src="https://user-images.githubusercontent.com/3127881/79740616-a6d25280-8308-11ea-95bb-b3739bf7fd79.png" alt="landscape" width="150">

- Change orientation to landscape, it is deformed
<img src="https://user-images.githubusercontent.com/3127881/79740542-8609fd00-8308-11ea-80fb-952ca0ee0c31.png" alt="landscape" height="150">

- Change orientation back to protrait, it is still deformed:D
<img src="https://user-images.githubusercontent.com/3127881/79740451-5ce96c80-8308-11ea-8223-0bcfb4302490.png" alt="portrait again" width="150">

---------------------------------

2- In some cases bottom sheet is not visible after orientation changed. User should know it is there, and swipe to make it display. Ie:
<img src="https://user-images.githubusercontent.com/3127881/79740451-5ce96c80-8308-11ea-8223-0bcfb4302490.png" alt="portrait again" width="150">

Just a wild idea, can't we disable landscape mode at all? Do you think we have users who use the app in landscape?

**Comment by misaochan** [comment]
I imagine some users would use it in landscape, especially because many photos are landscape themselves.

Can we not fix this by just setting images to NOT stretch to fill the screen?

**Comment by sivaraam** [comment]
I wonder if #3678 is due to the new UI change? 🤔

**Comment by neslihanturan** [comment]
Deforming images on rotation one, also happens before #3505 . I verified that same issues exists in 2.13-release branch too. So we loose nothing cherry picking UI improvements to release branch @misaochan :)

**Comment by misaochan** [comment]
Okay, let's cherrypick the UI improvement over, but keep this issue open.

**Comment by sivaraam** [comment]
I observe a weird over-sizing of the text shown in the media details view _after the merge_. I observe this in a Samsung SM-J111F running Android 5.1.1.

*Screenshots of the media detail view as observed in the tip of the PR branch (at 9644183ca)*
![Screenshot_2020-04-22-01-09-51](https://user-images.githubusercontent.com/12448084/79907002-81436700-8436-11ea-95a5-daf52615fe03.png)
![Screenshot_2020-04-22-01-09-54](https://user-images.githubusercontent.com/12448084/79906996-7d174980-8436-11ea-9d6f-ec5a8c3b9aaf.png)

*Screenshots of the media detail view as observed in the tip of the 2.13-release branch (at d7c248017)*
![Screenshot_2020-04-22-00-26-32](https://user-images.githubusercontent.com/12448084/79907183-d2ebf180-8436-11ea-9cb6-6225b56f05fa.png)
![Screenshot_2020-04-22-00-26-55](https://user-images.githubusercontent.com/12448084/79907057-99b38180-8436-11ea-9e68-c3589e2683d3.png)


I also happen to observe this in the Home page.
*Homepage at tip of PR branch (9644183ca)*
![Screenshot_2020-04-22-01-20-03](https://user-images.githubusercontent.com/12448084/79907595-776e3380-8437-11ea-92b0-c6c7eb42edf7.png)

*Homepage at tip of 2.13-release branch (d7c248017)*
![Screenshot_2020-04-22-00-34-49](https://user-images.githubusercontent.com/12448084/79907554-61607300-8437-11ea-8064-33349a0b5996.png)

Observe the over-seize of "NEARBY". I'm not sure if there are other places with similar over-sizing.

**Comment by kbhardwaj123** [comment]
I have investigated some of these problems and have potential solution should i start working on solving them ?

**Comment by neslihanturan** [comment]
Would be great @kbhardwaj123 :)

**Comment by kbhardwaj123** [comment]
@misaochan @neslihanturan @sivaraam after some through investigation i found that there was no function to update the view dimension when device changes orientation, but the main problem is that even when i tried to add one it gave the exact opposite result i.e Landscape gave view height for portrait and vice versa that's why the **image would remain deformed no matter what** and even if i add a `globalLayoutListener` or a custom `runnable` it still happens to skip a beat and then give opposite results, but by making use if some simple `if and else` loops the problem got solved i will post the PR now :)

**Comment by sivaraam** [comment]
@kbharadwaj123 Did you manage to fix the text over-sizing issue in the PR?

**Comment by kbhardwaj123** [comment]
@sivaraam yes I tried to look into that but it doesn't seem to be related to this issue, I mean the text size is taken from dimens file and I haven't changed the text size anywhere

**Comment by sivaraam** [comment]
Ok. I was of the opinion that you were fixing the issue in the new UI, in general. Anyways, I've filed #3711 for the issue I observed Thanks :)
