### ISSUE TITLE
{{Location|0.0|0.0}}

### ISSUE THREAD

**Issue by Aschroet** [commons-app/apps-android-commons#3684]
**Summary:** 

The app adds _{{Location|0.0|0.0}}_ to the file description although the files metadata does not contain any GPS data. Example: [File:Renaturierter Tauberabschnitt zwischen Tauberbischofsheim und Impfingen 8.jpg](https://commons.wikimedia.org/wiki/File:Renaturierter_Tauberabschnitt_zwischen_Tauberbischofsheim_und_Impfingen_8.jpg)

This is wrong and, thus, the location should not appear in the wikitext.

Generally, (0.0, 0.0) is a strong indicator that something is wrong with the data.

**Comment by VitalyVPinchuk** [comment]
Probably we're having the same issue as https://github.com/commons-app/apps-android-commons/issues/3647

**Comment by misaochan** [comment]
It happens to me with a picture that has GPS data (I checked the metadata on my phone's gallery).

**Comment by sivaraam** [comment]
> It happened to me with a picture that has GPS data, overriding the coordinates (I checked the metadata on my phone's gallery).

That seems like the issue described in #3647 (mentioned before).
