### ISSUE TITLE
Media needs refactoring to remove code that has been rendered useless

### ISSUE THREAD

**Issue by kbhardwaj123** [commons-app/apps-android-commons#3687]
**Summary:** 

After analysing the media section i came across the following things which can be removed:

 - The `MediaDetailSpacer` class has been rendered useless, it was previously used in the `fragment_media_detail.xml` file but after some recent changes it is not required.

 - The `updateTheDarkness` method inside `MediaDetailFragment` was used when we had a partially transparent media detail fragment so that when the user pulls it up the **Alpha of the image** was changed to make the details readable but now since the design has been completely overhauled i think we should remove this.

This is what the `updateTheDarkness` method does:
**Before Scroll**
![Screenshot_20200421_125645_fr free nrw commons beta](https://user-images.githubusercontent.com/44129798/79858214-b2974500-83ec-11ea-9e06-677bfa25f7db.jpg)

**After Scroll** 
![Screenshot_20200421_125650_fr free nrw commons beta](https://user-images.githubusercontent.com/44129798/79858282-cc388c80-83ec-11ea-9504-43abb56bfac0.jpg)

**Would you like to work on the issue?**
Yes :)

**Comment by macgills** [comment]
I'd say definitely remove `MediaDetailSpacer`

The fade is sort of nice(?) but I don't see a reason for it to be there. I'd wait for more people to weigh in on that.

**Comment by kbhardwaj123** [comment]
Tagging @neslihanturan for review on this aspect

**Comment by neslihanturan** [comment]
I agree about removing both, simplicity is better.

**Comment by kbhardwaj123** [comment]
since most of us are in favour of removing both i will create a PR for the same
