### ISSUE TITLE
[structured data]Not able to proceed without refilling caption when uploading via Nearby

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#3690]
**Summary:** 

When you upload via Nearby, the caption/desc fields are autofilled as they should be. However the app considers the caption field "empty" and does not allow you to proceed until you remove and re-type the autofilled caption.

This only exists on structured-data branch.

**Steps to reproduce:** 

- Upload via Nearby
- Try to tap "Next", it is greyed out

**Device and Android version:** 

Nexus S API 27 emulator
 
**Commons app version:** 

structured-data, prodDebug

**Screen-shots:** 

![Screenshot_1587481242](https://user-images.githubusercontent.com/3611199/79881926-3117d500-8435-11ea-83c3-414888ea586f.png)

**Would you like to work on the issue?**

No

**Comment by macgills** [comment]
duplicate #3600
