### ISSUE TITLE
When Uploading from Nearby the Place should be added as a pre-selected Depiction

### ISSUE THREAD

**Issue by macgills** [commons-app/apps-android-commons#3694]
**Summary:** 

nicolas-raoul :
 I think that the item from Nearby (when coming from Nearby) should be added as pre-selected (maybe even undeselectable) in Step 2 or the upload.

**Comment by misaochan** [comment]
Pre-selected sounds good, probably not deselectable though.

**Comment by misaochan** [comment]
To me it feels a bit strange if just one item in the list is de-selectable. It also seems to add more complexity for not a very good reason, since if the user wants it there, pre-selection is enough. 

For myself, I regularly upload Nearby pics that aren't actually related to that spot, to production servers, for testing reasons (beta does not produce the same results for various reasons), and I just remove the place's p18 afterwards. Making it deselectable would mean that I have 2 properties to remove for each, AFAIK.

I was not aware that it automatically adds the depicts property, time to check my uploads lol.

**Comment by nicolas-raoul** [comment]
In current master, the `depicts` is indeed added silently to all Nearby uploads.
It is actually _too_ silent: If you do not select _another_ `depicts` as well, a popup appears shaming you for not filling depictions. By the item is suggested and not checked, if you check it then the `depicts` is duplicated like this:
<img width="221" alt="Screen Shot 2020-12-30 at 00 54 01" src="https://user-images.githubusercontent.com/99590/103296497-8af78280-4a39-11eb-86f4-b910b6ff1c27.png">

**Comment by misaochan** [comment]
Oh whoops, that is not good. We should at the very least prevent the duplication.

@nicolas-raoul What do you think about displaying the relevant depicts, pre-selected, with all the other depicts at that step? That way the user knows it is already selected.

**Comment by nicolas-raoul** [comment]
Yes that's a perfect solution 🙂

**Comment by byerlyb20** [comment]
I can take a look at this.

**Comment by nicolas-raoul** [comment]
@byerlyb20 Thanks, it is yours! :-)

**Comment by byerlyb20** [comment]
What about when the upload is started from the Contributions screen but the app prompts the user to confirm whether or not the image is of a nearby place?

![Screenshot_1623372782](https://user-images.githubusercontent.com/6891883/121615019-efc5f880-ca2d-11eb-863c-5d42630f6191.png)

If the user confirms, the upload continues as if it were started from the Nearby screen. In this sense, it might still be good to pre-select the Place as a Depiction. However, things can get tricky if the user selects a set of images. If the images are taken in different locations (and the user confirms this via several dialogs), should all of these places be pre-selected as depictions? This behavior would be misleading, as the selected depictions apply to all images in the set.

**Comment by nicolas-raoul** [comment]
Very good remark.

The app's philosophy is that you should upload a set only if it is the same thing or place. For instance, upload 5 pictures of a townhall as a set. Upload 15 pictures of a politician as a set. But 3 pictures taken in a city, one depicting a subway station and one depicting a giant milk bottle, one depicting a pond, should probably not be uploaded as a set :-) By the way, we should find ways to make that philosophy more explicit, that could be another issue.

Conclusion: It is fine to pre-select depiction "Place Rosslyn Station" for the set if the user taps "Yes" in the screenshot you posted above. The user can deselect it if they realize it does not apply to all pictures. Hopefully in the future we will have a way to edit the depictions of already uploaded pictures (it is already possible for categories).
