### ISSUE TITLE
Multiple upload: Only one file's caption is used for all files, others ignored

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#3699]
Latest master 67faa40

How to reproduce:
- In the Android gallery, select 2 (or more) pictures
- Tap "Share", select the Commons app
- Give a different name to each, for instance "Himonya tennis courts" and "Himonya park entrance"
- Finish the upload

**Problem**: the two uploaded files are "[Himonya tennis courts](https://commons.wikimedia.org/wiki/File:Himonya_tennis_courts.jpg)" and "[Himonya tennis courts 2](https://commons.wikimedia.org/wiki/File:Himonya_tennis_courts_2.jpg)", in other words the caption I wrote for the second file has been ignored.
**Expected**: The second file should have been called "Himonya park entrance"

![Screenshot_20200423-150035_Commons](https://user-images.githubusercontent.com/99590/80064809-e8b30100-8573-11ea-9088-236ebecb156f.jpg)

![Screenshot_20200423-150211_Commons](https://user-images.githubusercontent.com/99590/80064769-d5079a80-8573-11ea-8c1f-614db761f443.jpg)

I did not try descriptions but it might be worth checking too.

**Comment by misaochan** [comment]
Oops, this is a pretty important bug!

**Comment by macgills** [comment]
As soon as I am finished the unit testing on my current ticket I will be on this.

**Comment by misaochan** [comment]
Thanks @macgills !
