### ISSUE TITLE
Search my uploaded pictures by title

### ISSUE THREAD

**Issue by nextLane** [commons-app/apps-android-commons#370]
Adding a simple search box that will do title based searching may add convenience at user end while searching for a particular upload. Essentially helpful, when number of uploads go up.

**Comment by nicolas-raoul** [comment]
Our priority is currently geared towards uploading features, rather than towards browsing already uploaded pictures, but that's an interesting idea!

**Comment by nicolas-raoul** [comment]
Apologies we forgot this issue and started discussing the topic again at https://github.com/commons-app/apps-android-commons/issues/5882, let's keep that one as it contains the most up-to-date considerations. Thank you for your understanding!
