### ISSUE TITLE
Green pin visible at first, despite "Needs Photo" enabled

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#3704]
Steps:
- Start the app, after killing it if necessary
- Tap "Nearby"
- Notice that "Needs Photo" is enabled
- Problem: Green pins are visible
- Workaround: Tap "Contrbutions" then "Nearby" again: Now the green pins are not visible anymore
![Screenshot_20200424-105849_Commons](https://user-images.githubusercontent.com/99590/80167870-7518fe80-861c-11ea-9bae-5191dd15e7d7.jpg)

**Comment by VitalyVPinchuk** [comment]
Hi
I would like to work on this

**Comment by nicolas-raoul** [comment]
@VitalyVPinchuk Thanks! :-)
