### ISSUE TITLE
Over sized text in some places of the app

### ISSUE THREAD

**Issue by sivaraam** [commons-app/apps-android-commons#3711]
The text in some places of the app seem over-sized. I say over-sized as I use the "Extra small" font size in my device for which the size I see in the app seems over-sized. I just checked and it looks like the app doesn't care about the device's font size setting at all. I'm not sure if this was the case ever since the beginning. I just happened to notice this now as the font size increased all of a sudden and there are even inconsistencies in the text sizing in some places. It would be nice if the app respected the device's font sizing setting. Regardless, this font-size seems a bit too large at least for my device's screen size.

#### With previous text size ([before](https://github.com/commons-app/apps-android-commons/commit/9644183ca0c2e24ac25b0b7a28fc24673d951209))
![Screenshot_2020-04-22-01-09-51](https://user-images.githubusercontent.com/12448084/79907002-81436700-8436-11ea-95a5-daf52615fe03.png)
![Screenshot_2020-04-22-01-09-54](https://user-images.githubusercontent.com/12448084/79906996-7d174980-8436-11ea-9d6f-ec5a8c3b9aaf.png)

#### With over-sized text ([after](https://github.com/commons-app/apps-android-commons/commit/d7c2480174db15bd834872d7b669b1acc6ca85ea))
![Screenshot_2020-04-22-00-26-32](https://user-images.githubusercontent.com/12448084/79907183-d2ebf180-8436-11ea-9cb6-6225b56f05fa.png)
![Screenshot_2020-04-22-00-26-55](https://user-images.githubusercontent.com/12448084/79907057-99b38180-8436-11ea-9e68-c3589e2683d3.png)

#### With previous text size ([before](https://github.com/commons-app/apps-android-commons/commit/9644183ca0c2e24ac25b0b7a28fc24673d951209))
![Screenshot_2020-04-22-01-20-03](https://user-images.githubusercontent.com/12448084/79907595-776e3380-8437-11ea-92b0-c6c7eb42edf7.png)

#### With over-sized text ([after](https://github.com/commons-app/apps-android-commons/commit/d7c2480174db15bd834872d7b669b1acc6ca85ea))
![Screenshot_2020-04-22-00-34-49](https://user-images.githubusercontent.com/12448084/79907554-61607300-8437-11ea-8064-33349a0b5996.png)
*Note:* Observe the over-sized "NEARBY".

#### With over-sized text ([at 67faa40](https://github.com/commons-app/apps-android-commons/commit/67faa40))
![Screenshot_2020-04-24-23-48-14](https://user-images.githubusercontent.com/12448084/80245672-b9da7f00-8688-11ea-961c-96429290a531.png)
*Note:* Observe the over-sized "FEATURE" 

I'm not sure if there are other places with similar over-sizing.

**Device and Android version:** 
Samsung SM-J111F; Android 5.1.1

**Commons app version:** 
2.12.3.683-67faa40

**Comment by LeoPaulC** [comment]
Hello , 
Is this issue still available ?
We are two & we are interested in your project , and collaborate with you.
( @Paul-Tra & me )

Best Regards ,

**Comment by sivaraam** [comment]
@LeoPaulC  Yeah, this one is availables. You can take it up, if you wish :)

Be sure to discuss about how you plan to fix this, here. You can make a PR after we agree on the proposed solution. Good luck :)

**Comment by Paul-Tra** [comment]
Hello,
I am the second contributor who works with @LeoPaulC .
We have searched for the location responsible for displaying category titles
and we found a way to solve the problem by fixing the size of the categories in size dp rather than in size sp.
On the attached image, we have resized the phone font to the maximum.
![Resized_Screenshot_20200426-122637_Commons001](https://user-images.githubusercontent.com/64268144/80305622-21deb180-87be-11ea-98af-d0c5d5037a68.jpg)

Does the way in which we solve the problem seem suitable to you?

**Comment by LeoPaulC** [comment]
Hello ,

After other research we managed to find a second way to solve the problem by keeping the dimensions in "sp".
By adapting the mode according to the scale device and fix label size.
We used something like that : 
```Resources ressourcesDevice = getResources() ;
        Configuration configDevice = ressourcesDevice.getConfiguration() ;
        float scale = configDevice.fontScale;
        /**
         * This part allow the app to know the scale of the font size.
         * And then , adapt the TabLayout
         */
        if ( scale >= 1.7 ){
            tabLayout.setTabMode(TabLayout.MODE_SCROLLABLE);
        }
        else{
            tabLayout.setTabMode(TabLayout.MODE_FIXED);
        }
```

That solves the problem, but on the other hand it changes the size of the cells (cf: screen), what do you think about this ?

Here you'll find 4 screens , about min / max font size about our device ( Samsung A7 ) .

Max font size :

![MAx1](https://user-images.githubusercontent.com/33942038/80311913-a7745880-87e2-11ea-8355-8b29d762d748.jpg)
![Max2](https://user-images.githubusercontent.com/33942038/80311915-a93e1c00-87e2-11ea-8002-0c496caaa6fe.jpg)


Min font size : 

![Min1](https://user-images.githubusercontent.com/33942038/80311917-ae02d000-87e2-11ea-8e3a-8c236d1ee9d8.jpg)
![Min2](https://user-images.githubusercontent.com/33942038/80311918-af33fd00-87e2-11ea-9a47-138d4dbf5a54.jpg)

**Comment by neslihanturan** [comment]
Hey @LeoPaulC and @Paul-Tra , thanks for your investigation but we don't want to change the UI and text or cell rates. So two proposed solutions are not doable. Just some text are oversized compared to others, ideally they should look in identical sizes.

**Comment by LeoPaulC** [comment]
Hello @neslihanturan and @sivaraam , 
Thanks for your comments 
So we've make some changes , you'll find some screens .
According to the issue "It would be nice if the app respected the device's font sizing setting" ,
when the device font size is low/medium , it will be OK .
However , when the font size is at the Maximum , the text doesn't look great ...
So the questions is , will we have to set the maximum size of the text ? But we have some troubles with the API version , which not allow to setMaxSize .. here's the problem.
Do you have some intuitions about that ?
Or simply set all the textSize at the same value without care about device fontsize ? 

"Normal size" :

![normal1](https://user-images.githubusercontent.com/33942038/80362900-b7904480-8883-11ea-9972-f1ac39ec1baa.jpg)
![normal2](https://user-images.githubusercontent.com/33942038/80362904-b8c17180-8883-11ea-936e-5929b9b579ff.jpg)

"Low size" :

![petit1](https://user-images.githubusercontent.com/33942038/80362976-d098f580-8883-11ea-9ce7-d5794be91b76.jpg)
![petit2](https://user-images.githubusercontent.com/33942038/80362980-d1318c00-8883-11ea-9059-1b7d985e09c1.jpg)

"Maximum size" :

![max](https://user-images.githubusercontent.com/33942038/80363640-ca574900-8884-11ea-8d4e-51078ffa7d85.jpg)


thanks again

**Comment by sivaraam** [comment]
> According to the issue "It would be nice if the app respected the device's font sizing setting" ,

Yeah. I mostly said that as it would be a nice to have future enhancement. Though, I could've mentioned that clearly.

> ... when the device font size is low/medium , it will be OK .

It looks like the app's layout isn't designed to be influenced by the device's font size setting. So, as @neslihanturan points out, kindly just look into why the font size appears to be oversized and undersized in some places of the app and fix it. Thanks!

**Comment by LeoPaulC** [comment]
Hello ,

> just look into why the font size appears to be oversized and undersized in some places of the app 

We have an idea:
The sizes of the titles being in "sp", the text tries to take the available place, if the two titles are not the same length, then they will try to set themselves to the maximum size.
And the title "Nearby" is into a custom layout which include a textView and an ImageView , so it doesn't react as other titles.

A possible solution would be to put a fixed size, regardless of the font size of the phone , by using this solution , we'll avoid Oversized/Undersized texts.

Is this solution work for you ?

**Comment by neslihanturan** [comment]
As far as I checked, we don't have this issue anymore with new UI. However, I am not quite sure that I see over texts on some screen shoots. Can someone else also check if this issue exists with our latest UI?

**Comment by sivaraam** [comment]
Yeah, I don't appear to notice any over-sized text either. So, I'll close this one. Regardless, I would like to see the app respect the device font size. I've opened #4299 for that 🙂
