### ISSUE TITLE
"Next" button in depictions selection screen has no background

### ISSUE THREAD

**Issue by sivaraam** [commons-app/apps-android-commons#3712]
**Summary:** 
The depictions selection step seems to be the only step in the set of upload steps for which the "Next" button seems to be missing a background. This appears inconsistent.

**Device and Android version:** 
Samsung SM-J111F; Android 5.1.1 

**Commons app version:** 
2.12.3.683-67faa40

**Screen-shots:** 
![Screenshot_2020-04-24-21-49-47](https://user-images.githubusercontent.com/12448084/80248102-e7c1c280-868c-11ea-8118-80f1af7e4746.png)

**Comment by siamsot** [comment]
I would like to work on this
