### ISSUE TITLE
Depiction search does not return any results

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#3716]
Latest master

Steps:
1. Upload a picture that has latitude/longitude coordinates
2. At the depiction step, you see suggestions. In the search bar, enter "rabbit"
3. The suggestions do not change

![Screenshot_20200426-093130_Commons](https://user-images.githubusercontent.com/99590/80294090-cce07280-87a0-11ea-9082-4743b1bab5cd.jpg)

Tip: I believe that suggestions still work when there are no suggestions. You can try that by resetting the app settings and using a picture with no EXIF (for instance a random logo image from a news website).

**Comment by GearGit** [comment]
@nicolas-raoul  Can I work on this?

**Comment by nicolas-raoul** [comment]
@GearGit Sure, thanks :-)

**Comment by GearGit** [comment]
@nicolas-raoul for thus issue, you want the suggestions to also include the title which user entered and not only using gps cordinates right?

**Comment by nicolas-raoul** [comment]
- If the search bar is empty: Show the suggestions
- If the search bar is not empty: Show the results for the term entered into the search bar
That's what the categories selection activity does, actually, so you can take it as an example :-)

**Comment by macgills** [comment]
@GearGit the fix is - I think - quite simple as it is due to misuse of an api by myself and forgetting the presenter was a Singleton. If you are happy for me to make a PR I can fix it quickly

**Comment by GearGit** [comment]
> @GearGit the fix is - I think - quite simple as it is due to misuse of an api by myself and forgetting the presenter was a Singleton. If you are happy for me to make a PR I can fix it quickly

Sure go ahead

**Comment by macgills** [comment]
cheers
