### ISSUE TITLE
Add auto numbering of multiple images when reusing title

### ISSUE THREAD

**Issue by AtaZh** [commons-app/apps-android-commons#3717]
**Summary:** 
Desktop Commons adds automatic numbering at the end of the file names when reusing title. This feature would be useful here, too.

**Steps to reproduce:** 
Choose two files, use copying the title and description, press upload. The app uploads two images as different versions of the same file. 

**Device and Android version:** 

API level: 29
Android version: 10
Device manufacturer: samsung
Device model: SM-A405FN
Device: a40
Network type: wifi
App version name: 2.12.3~dc08a5e88
User name: ата

https://commons.wikimedia.org/wiki/File:Microwave_popcorn-.jpg

**Comment by GearGit** [comment]
@AtaZh I would like to work on this

**Comment by sivaraam** [comment]
This seems related to #228 :thinking:

**Comment by nicolas-raoul** [comment]
I think this is already implemented?
I uploaded a set of two pictures yesterday, the first got the original title and the second got the original title + ` 2` suffix.
Using the latest master.
If it does not work for you, please reopen, thanks :-)
