### ISSUE TITLE
[2.13-release] Nearby map starts with "Needs photos" selected, but green pins can still be seen

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#3719]
**Summary:** 

When you launch Nearby for the first time, "Needs photo" should be selected, and there should be no visible green pins. Currently "Needs photo" is selected by default, but this is not reflected in the state of the pins (green pins can still be seen) the first time you launch Nearby.

In order to get the display right, the user has to tap "Needs photo" again twice.

**Device and Android version:** 

Samsung Galaxy S9 Android 10
 
**Commons app version:** 

2.13-release branch, prodRelease

**Would you like to work on the issue?**

No

**Comment by sivaraam** [comment]
This looks like a dupe of #3704

**Comment by VitalyVPinchuk** [comment]
Hi
Can I work on this?

**Comment by misaochan** [comment]
Okay, closing this, @VitalyVPinchuk please feel free to work on #3704 , thanks!
