### ISSUE TITLE
[2.13-release] None of the filters work on Nearby list

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#3720]
**Summary:** 

The filters for place state and place type work for the map display, but changing them does not affect the list, even if you close and reopen the list.

This is especially bad for the "needs photo" place state as users will end up uploading a photo to a location that already has one, even though they have "needs photo" selected.

**Device and Android version:** 

Samsung Galaxy S9 Android 10
 
**Commons app version:** 

2.13-release branch, prodRelease

**Would you like to work on the issue?**

No

**Comment by VitalyVPinchuk** [comment]
Hi @misaochan 
Can I work on this?

**Comment by misaochan** [comment]
@VitalyVPinchuk Yes, please feel free :)

**Comment by VitalyVPinchuk** [comment]
Should I fork it from 2.13-release or master branch?
