### ISSUE TITLE
Add information about pin colours

### ISSUE THREAD

**Issue by neslihanturan** [commons-app/apps-android-commons#3726]
**Summary:** 

One of our users suggested to add information about colors of pins in nearby. I think this is a good idea. Additionally, I think we should add information to explain place type, place state, exists etc. too.

**Comment by nathanmeade** [comment]
Should this be a legend that we include within the "Nearby" tab of the app? Or should this information be included within the pin itself whenever it is selected?

**Comment by neslihanturan** [comment]
Hmm, pin itself is too hard to find. But we already have a legend for nearby which explains what it is. Maybe we can add some more explanation to the existing legend for the pins? For place type and place state, there can be "i" button in their rows maybe? What do you think?

**Comment by nathanmeade** [comment]
I agree with your implementation suggestions above. Just to make sure I'm understanding your suggestions correctly, here are screenshots of what I believe is proposed:

For "i" buttons on the place type and place state rows:
![nearbyTabPinScreenshot](https://user-images.githubusercontent.com/9450306/81122635-485bc580-8eff-11ea-910a-0bc86a840f8c.png)

For the nearby legend where the pin information can be included:
![nearbyTabLegendScreenshot](https://user-images.githubusercontent.com/9450306/81122668-5c072c00-8eff-11ea-9499-660e5f8d26d9.png)

Is this what you are proposing @neslihanturan?

**Comment by neslihanturan** [comment]
Yes, it was. But after seeing your mockups, I changed my mind a little.
- We should add an explanation to nearby legend (img 2), about filtering in general. Something like "you can filter out pins now!" with a better english preferably.
- And add information about colors of pins next to place type (since colors indicates place types).

Note1: In your img1, I would add "i" buttont to the left side of the row.
Note2: Your screenshoots seems an older version of master, make sure you sync to current master before you start to work :)

**Comment by misaochan** [comment]
Just to clarify, the "transparent" pins have been removed in #3355 - it just hasn't been released yet. However information about the green pins would be nice.

**Comment by neslihanturan** [comment]
> Just to clarify, the "transparent" pins have been removed in #3355 - it just hasn't been released yet. However information about the green pins would be nice.

Yes, transparent pins are there since shots from previous version

**Comment by nathanmeade** [comment]
> Yes, it was. But after seeing your mockups, I changed my mind a little.
> 
> * We should add an explanation to nearby legend (img 2), about filtering in general. Something like "you can filter out pins now!" with a better english preferably.
> * And add information about colors of pins next to place type (since colors indicates place types).
> 
> Note1: In your img1, I would add "i" buttont to the left side of the row.
> Note2: Your screenshoots seems an older version of master, make sure you sync to current master before you start to work :)

Got it, that makes sense. You are correct, I did not have the latest version of master checked out here - this is actually the current PROD version from the Play Store. I definitely should be using the latest version of master instead. :)

**Comment by VmKid** [comment]
Perhaps we could do something like this, adding the icon to the filter chips (and possibly adding additional filters for the other icons) (Please excuse the slightly squished icon- this was only a test run)
![Screenshot_20200621-115652](https://user-images.githubusercontent.com/3360357/85229287-d3612400-b3b6-11ea-86bb-6aad66f2700b.jpg)

**Comment by misaochan** [comment]
> Perhaps we could do something like this, adding the icon to the filter chips (and possibly adding additional filters for the other icons) (Please excuse the slightly squished icon- this was only a test run)

This is a nice idea, but it would require rethinking how we display the selected chip, as it replaces the check mark. I think there was a discussion earlier where people perceived a greyed-out chip in different ways (some people thought it meant selected, and some people thought the opposite), hence why we use a check mark for that purpose.

**Comment by VmKid** [comment]
Fair enough.
How does this look
![Screenshot_20200622-174724](https://user-images.githubusercontent.com/3360357/85338702-c9235080-b4b0-11ea-8308-852a251357d8.jpg)
?
