### ISSUE TITLE
Nearby list bottom sheet UI issues

### ISSUE THREAD

**Issue by neslihanturan** [commons-app/apps-android-commons#3727]
**Summary:** 
1- It should display a message when no place is found, instead of empty white sheet.
2- The height should be smaller if number of items in the list is smaller than N.

**Comment by nathanmeade** [comment]
@neslihanturan Is this what you are observing (2 screenshots provided below:)?
No results map screenshot:
![nearbyNoResultsMapScreenshot](https://user-images.githubusercontent.com/9450306/81021743-de2d1d00-8e39-11ea-8931-b8f85bbc4a45.jpg)
No results map screenshot with list displaying:
![nearbyNoResultsListScreenshot](https://user-images.githubusercontent.com/9450306/81021737-da00ff80-8e39-11ea-9f74-459fbd880320.jpg)

Are you specifically talking about this blank white sheet being displayed when you select list?

Steps to reproduce for the blank white sheet issue (#1):
1. Make sure the app does not have the location permission
2. While logged in, select the "Nearby" tab of the "Home" screen
3. Deny the access to location
4. Select "No" to the permission request dialog
5. Select the "Nearby" tab again
6. Tap away from the dialog to make it disappear
7. Observe that there are no results

**Comment by neslihanturan** [comment]
> * Make sure the app does not have the location permission
> 
> * While logged in, select the "Nearby" tab of the "Home" screen
> 
> * Deny the access to location
> 
> * Select "No" to the permission request dialog
> 
> * Select the "Nearby" tab again
> 
> * Tap away from the dialog to make it disappear
> 
> * Observe that there are no results

Seems like you discovered another bug, ideally we expect user is sent to contributions tab instead of displaying an empty nearby. What about creating a new issue for this one?

But yes, the white bottom sheet that I mentioned is the one you displayed with your screen shoots. There should be a message and progressbar there, indicating states.

**Comment by nathanmeade** [comment]
@neslihanturan Okay, I will create a new issue for the new issue discovered above. I am curious though as to how you reproduced this initially? I'm assuming this was performed by using mock data so that there were only a few results or none at all? Either way, I agree that the currently observed behavior is wrong and should be changed to handle these situations like you listed above.

**Comment by CloeARiva** [comment]
@neslihanturan @nathanmeade Hello, I'm new here and I've been working in software for just over a year, I'm currently unemployed so would like to contribute :) . Could I work on this as my first issue? 

I have replicated the white sheet by deselecting the "All" checkbox in "Place type" without selecting any of the specific options. 
![image](https://user-images.githubusercontent.com/29753876/81175781-02a10a80-8f9c-11ea-8491-2596446a3cce.png) 
and then clicking on the list.

Is the proposed solution to display a ghost text on the empty list, something like "No results found", or to actually pop up a dialog with a message?

**Comment by neslihanturan** [comment]
Hi @CloeARiva , welcome to the team :). Considering @nathanmeade seems like interested with the issue too, I would like to ask him if he is working on the issue or not. If he is already working, you can pick another beginner friendly issue. Otherwise, you are welcome to work on this one :).

**Comment by nathanmeade** [comment]
If issue #3732 is valid (given that I have understood the issue properly and that my proposed solution is valid) then I will be working on that issue instead (preventing the user from accessing the "Nearby" tab if the location permission has been denied). @neslihanturan Would you agree that I have understood issue #3732 properly? If so, @CloeARiva this issue (#3727) would be a great issue to tackle while I tackle the other. Also, welcome - I am very new here as well.

**Comment by neslihanturan** [comment]
Seems like you shared issues as this one is for @CloeARiva and #3732 is for @nathanmeade . Both of you are welcome, looking forward for your updates:)

**Comment by CloeARiva** [comment]
@neslihanturan @nathanmeade thank you both for replying so quickly, I'll start working on this issue now :)

**Comment by nathanmeade** [comment]
Sounds good, no problem!

**Comment by CloeARiva** [comment]
@neslihanturan @nathanmeade Hi both, I believe I have found another bug while testing my changes.

Steps to reproduce:

- on the Nearby tab click on the "Place type:" field
- deselect the "All" checkbox (this is basically searching for places of no place type so will return no results)
<img width="269" alt="wikimedia selecting no place type" src="https://user-images.githubusercontent.com/29753876/81683270-d3801280-944d-11ea-9ec7-2d6230e96a5e.png">
- Click on the list button on the top right, you will see no results 
- Click the button again to minimise the list
- scroll to a new area of the map until the "search this area" button appears at the top
- Click "search this area"
- Check in your "Place type: " field that the "All" check box is not selected, as before
- Click the list button in the top right
- Results are returned as if you were searching for all placetypes (i.e. as if "All" was checked)

Ticking and unticking "All" again fixes this so I believe that we are not refiltering properly when we first move to a new location.
Do you agree? Should I create a new issue for this?
