### ISSUE TITLE
Update bookmarkLocationDao to include "destroyed" info.

### ISSUE THREAD

**Issue by neslihanturan** [commons-app/apps-android-commons#3729]
**Summary:** 
Currently we don't have a destroyed column in the table of bookmarkLocationDao. As you know pic and destroyed are added later. This can cause an issue when user bookmarked a destroyed place. Since there is no destroyed info stored in bookmark dao (currently null), pin will appear as star inside blue, instead of star inside gray. Even if this is an edge case, we better to cover it.

So we need to update bookmark db from 11 to 12 I guess. 

Disclaimer: Probably not a beginner friendly task.

**Comment by misaochan** [comment]
Note: Probably will need to do a migration if we do this? Since the old version was released to users.

**Comment by gvaibhav1734** [comment]
Can I take this up?

**Comment by misaochan** [comment]
Are you familiar with doing db migrations, @gvaibhav1734 ?

**Comment by gvaibhav1734** [comment]
Yeah. Have written a few migrations when using Room library for a project.


``` sql 
ALTER TABLE bookmarksLocations ADD COLUMN destroyed STRING;
```
This SQL statement should get the job done right?

**Comment by gvaibhav1734** [comment]
Can I go ahead with this @misaochan

**Comment by misaochan** [comment]
Sorry for the late reply, @gvaibhav1734 . Sure, please feel free to go ahead and submit a PR for it in that case, thanks. :)

**Comment by gvaibhav1734** [comment]
Successful addition of _destroyed_ column to the table doesn't change the pin to appear as star inside gray. 
Should I be coding the star inside grey (when destroyed) feature? @neslihanturan
