### ISSUE TITLE
What is the best alternative for stetho? 

### ISSUE THREAD

**Issue by maskaravivek** [commons-app/apps-android-commons#3740]
**Summary:** 

Till some time back we were using [Stetho](http://facebook.github.io/stetho/#integrations) for viewing and editing SQLite DB. But we removed it as the Android studio lets you go to the device file explorer and download the DB. 

I am struggling to find a good Android Studio plugin that allows to view and edit real-time changes. Some of the plugins let you download the DB and then view it. I found another plugin called SQLScout that seems to support almost realtime viewing of DB but it isn't working for me. 

What are you guys using for debugging the data in the DB? Tagging a few people @ashishkumar468 @misaochan @neslihanturan @macgills. Others also feel free to comment. 

If the alternatives are not straightforward to use then it would be great to have Stetho back.

**Comment by ashishkumar468** [comment]
Android Studio is about to roll out an update which would support db browsing by default. In fact some of the canary versions already have it (4.1 canary 6 >) 

https://developer.android.com/studio/preview/features

**Comment by maskaravivek** [comment]
Thanks, @ashishkumar468. 

Are there other options for people who are not using the canary builds?

**Comment by macgills** [comment]
This cropped up from  [a google](https://github.com/amitshekhariitbhu/Android-Debug-Database) but not exactly a world of difference from Stetho. I would wait for the AS release, not that we have any guarantee that it will be very functional, sometimes AS releases stuff that just doesn't work (instant run, multiple simultaneous previews) but 4.0 and beyond is looking like good, they will actually have gutter icons for Dagger.

Mostly I find "needing to view the db" somewhat unnecessary as debugging can mostly solve the problem anyway, `Evaluate Expression` button is great for running arbitrary code which is way nicer than jury rigging sql commands yourself. Adding fake data is as easy as

```
dao.insert(listOf(0..100.map{ DbItem(it, "fake value%it")} ))
```

probably with a subscribe or `Completable.fromAction`  thrown in

**Comment by maskaravivek** [comment]
Android Studio 4.1 is working well for me.
