### ISSUE TITLE
Items not displayed after coming back to search

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#3742]
Latest master

Steps:
1. Open Explore
2. Search for "rabbit"
3. Tap "Items"
4. Press back button
5. You are now back to the items screen, with "rabbit" still typed.

Expected: Results shown
Actually: results not shown

![Screenshot_20200511-221715_Commons](https://user-images.githubusercontent.com/99590/81565947-1c47b500-93d5-11ea-92bf-69b0831f1306.jpg)

Appending a space and then removing it, makes the results appear.

**Comment by ddopik** [comment]
Hello @nicolas-raoul 
can i work on this issue

**Comment by ddopik** [comment]
Hello @nicolas-raoul 
i have tested the issues on my phone and i havn't faced the issue you have mentioned 
device was huwaie mate 10 lite,  and latest commit " Latest commit "b7ba1f0" on master branch
if you still facing the issue would you mention your deveice model so i can emulate it 

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/21159364/84545713-0133d200-ad00-11ea-8690-c0bb6aede0f9.gif)

**Comment by nicolas-raoul** [comment]
Indeed I can't reproduce it, it seems to have been solved as a side-effect of another fix.
Thanks a lot for finding out! Thanks to you we can close this bug :-)
