### ISSUE TITLE
Is READ_EXTERNAL_STORAGE permission really necessary when picking file from gallery?

### ISSUE THREAD

**Issue by VitalyVPinchuk** [commons-app/apps-android-commons#3744]
**Summary:** 
I think `READ_EXTERNAL_STORAGE` permission isn't required for picking an image from gallery.
The message `Required permission: Read external storage. App cannot access your gallery without this.` seems to be misleading as it's required for the purpose of searching for similar images e.g. getting GPS coordinates of images taken at the same time.
 
**Steps to reproduce:** 
Choosing file from gallery without the permission granted. 

![Screenshot_1589202630](https://user-images.githubusercontent.com/26341194/81565764-901c9a00-93a2-11ea-9a89-dcb108e43ca0.png)

**Comment by nicolas-raoul** [comment]
Thanks for spotting that! Strange that I have never experienced this despite uninstalling and resetting and reinstalling the app many times per week.
The permission should probably only be asked for, only when we really need it.

**Comment by ashishkumar468** [comment]
@VitalyVPinchuk  Have you tried choosing an image without permission?

**Comment by VitalyVPinchuk** [comment]
@ashishkumar468 No
Taping Cancel button cancels the action I guess

**Comment by Ayan-10** [comment]
@nicolas-raoul Can I work on this?

**Comment by nicolas-raoul** [comment]
@Ayan-10 Yes thanks!
