### ISSUE TITLE
Shifting the closeness evaluation to server side.

### ISSUE THREAD

**Issue by nextLane** [commons-app/apps-android-commons#376]
Just a suggestion, but instead of downloading and parsing through the entire csv, we can send the location coordinates to the server, the calculation to find the closest places is done on the server end and only selected places are sent as a response.

**Comment by misaochan** [comment]
I agree, downloading and parsing the entire CSV each time is very suboptimal. There are plans to switch entirely to a Wikidata query instead, for other reasons as well as this - see #289

**Comment by tobias47n9e** [comment]
That is a good idea and something we would like to work on during the Prague and Vienna hackathon. I think both are still open for registration. Scholarships could still work over wikimedia travel grants. Let us know if you would like to come or work remotely on this.

**Comment by nextLane** [comment]
@tobias47n9e Yes, I would be glad to come and work on this.
