### ISSUE TITLE
Invisible pins on Nearby map are still targetable

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#3762]
**Summary:** 

There is an interesting bug on Nearby - even with "Needs Photos" filter enabled, you can actually target the invisible green pins if you tap on their location on the map. E.g. the screenshot below:

![Screenshot_20200521-204411_Commons](https://user-images.githubusercontent.com/3611199/82552115-d8a73500-9ba4-11ea-80a2-11d4988b01d1.jpg)

So with bookmarks, sometimes I end up accidentally tapping a space close to my intended blue pin (but not quite there), which targets an invisible pin. If I don't realize that I targeted the wrong pin, I will bookmark it, and it then magically appears as a new green pin despite the Needs Photos filter being enabled.

![Screenshot_20200521-204602_Commons](https://user-images.githubusercontent.com/3611199/82552097-d04efa00-9ba4-11ea-981b-0fead21de5f2.jpg)

We shouldn't have nonexisting pins being targetable if they are filtered out.

**Device and Android version:** 

Samsung Galaxy S9, Android 10
 
**Commons app version:** 

I found it on #3728 , but it was reported that it also exists on master

**Would you like to work on the issue?**

No

**Comment by nicolas-raoul** [comment]
I experienced this yesterday with latest master. At first I thought the label was referring to a visible pin which is very close to it. It may lead to mistakes, for instance taking a picture of the wrong thing and only realizing it when you are away (after taking a picture I usually keep walking, towards my next destination, and upload while walking).

**Comment by robdjq** [comment]
Hi, I would like to try fixing this issue.

**Comment by nicolas-raoul** [comment]
@robdjq Thanks, it is yours :-)

**Comment by ashishkumar468** [comment]
Hi @robdjq  Are you still working on this issue?

**Comment by robdjq** [comment]
@ashishkumar468 I couldn't solve it, please unassign it from me, sorry and thanks for the opportunity.

**Comment by nicolas-raoul** [comment]
@robdjq No problem, thanks for letting us know :-)

**Comment by neslihanturan** [comment]
After #3931 this should be closed.
