### ISSUE TITLE
Achievements: Nearby count invisible

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#3767]
![Screenshot_20200523-233043_Commons](https://user-images.githubusercontent.com/99590/82733217-53ab4f80-9d4d-11ea-9573-11be7059c230.jpg)

**Comment by Charlitos96** [comment]
Hi, I would like to make my first contribution, can you give me more info about this, please?
Also, I clone the project and download the app from Google Play, but I can't find the view for this issue.

**Comment by nicolas-raoul** [comment]
@Charlitos96 You have to log in and click the kind of cup next to your username in the left menu.
Thanks! :-)

**Comment by Charlitos96** [comment]
Thank you, I can access on the app from Google Play, but When I run the project from Android Studio to my Phone, it asks me for a "Common Beta Account", Can you provide me one for tests?
![Commons Beta](https://user-images.githubusercontent.com/42658489/84005342-d8879300-a921-11ea-81d8-a0e2402fcf84.jpeg)

**Comment by nicolas-raoul** [comment]
Please build the prodDebug flavor.

**Comment by Charlitos96** [comment]
It seems like the bug was because you call the API and need to wait for a response, while the app is waiting for a response, the counter comes invisibly. I set a default value of 0 before calling the API and when the response of the API is ready, the value was updated.
#3796

**Comment by Charlitos96** [comment]
I'm looking for a folder to make a Test for my contribution, but I didn't find it, Can you tell me where did you put yours tests? or do I make a new folder?

**Comment by macgills** [comment]
@Charlitos96 You can follow the guidelines [here](https://developer.android.com/studio/test#add_a_new_test), automated tests must live under the `androidTest` source set and unit tests must live under a `test` source set. The package structure of the project should be mirrored between test and source

**Comment by Charlitos96** [comment]
Hi, I made a PR with my test, but when I run the test this problem jumps:
`AboutActivityTest.kt: (39, 68): Unresolved reference: getVersionNameWithSha`

That's a problem not realted with my issue, or with what I made, in fact I see there is another PR that can solve it #3850

**Comment by Charlitos96** [comment]
Hello,
Following the pattern from the [link](https://www.w3.org/TR/wai-aria-practices/examples/dialog-modal/dialog.html), they pass the reference of the element that triggered the Modal using `openModal('dialog1',this)`.
Using that as a guide, I update the method `handleOnClick()` to pass the reference of the button with `event.target` to update `modalTriggerElement` with it.
If this was not the approach you suggested please let me know. 😄

**Comment by ashishkumar468** [comment]
Hi @Charlitos96  Can you add the link to your PR over here so that we can help finalize it?
