### ISSUE TITLE
fix: Give new link to User Documentation in Readme

### ISSUE THREAD

**Issue by Bhavnaharitsa** [commons-app/apps-android-commons#3768]
**Summary:** 

In Readme, under the User Documentation, it shows to go to some other page after it is clicked. Instead, we could directly provide the link to the page in which it is available. Might seem like a smaller issue, but I felt we need to correct it. 
@misaochan Your thoughts on this, please!

**Steps to reproduce:** 
1. Open Readme
2. Click "User Documentation"

**Would you like to work on the issue?**
Yes

**Comment by sivaraam** [comment]
Thanks for a filing an issue for this! While [moving the documentation to a separate repo](https://github.com/commons-app/apps-android-commons/issues/3411#issuecomment-594631285) we never updated all the links in the repo. So, fixing them is a good thing indeed.

I'll assign this to you. You can work on this. :)

If possible, you can update the other instances of such broken links, too. For instance, there a reference to the wiki page in [ISSUE_TEMPLATE.md](https://github.com/commons-app/apps-android-commons/blob/master/ISSUE_TEMPLATE.md).

**Comment by Bhavnaharitsa** [comment]
@sivaraam Actually, I have noticed that all the links lead to the same documentation. Should we modify it into a single link "Guidelines" instead of "User documentation", "Volunteers", etc? Please tell me what you feel  :)

**Comment by sivaraam** [comment]
> @sivaraam Actually, I have noticed that all the links lead to the same documentation. 

While it is true that most of the links lead to the same documentation page, the section to which each link corresponds, to varies. For instance:

* **User documentation** should link to https://github.com/commons-app/commons-app-documentation/blob/master/android/README.md#-user-documentation
* **Contributor Documentation** should link to https://github.com/commons-app/commons-app-documentation/blob/master/android/README.md#%EF%B8%8F-contributor-documentation
* **Developer Documentation** - https://github.com/commons-app/commons-app-documentation/blob/master/android/README.md#-developer-documentation

Observe how the anchor part of the link varies. This is done to allow the different audience to quickly get the relevant information. So, it's best to keep them as it is.

Also, there are a few links that lead to different pages like:

* **Volunteers Welcome!** - https://github.com/commons-app/commons-app-documentation/blob/master/android/Volunteers-welcome!.md
* **Libraries Used** - https://github.com/commons-app/commons-app-documentation/blob/master/android/Libraries-used.md

Hope this clarifies your doubt.
