### ISSUE TITLE
Convert CategoryDao to Room

### ISSUE THREAD

**Issue by macgills** [commons-app/apps-android-commons#3777]
Summary:

The app has a mix of DAO implementations and we should standardize on Room

**Comment by Ayan-10** [comment]
@nicolas-raoul Can I work on this?

**Comment by nicolas-raoul** [comment]
Anyone: Is this still relevant?

**Comment by misaochan** [comment]
AFAIK, no. Pinging @ashishkumar468 for confirmation.

**Comment by Rishavgupta12345** [comment]
@nicolas-raoul we are already using room , this issue is not relevant we can close this
