### ISSUE TITLE
Items needed for 2.13.1 hotfix

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#3781]
Please target `2.13-release` branch with these.

- [x] #3705 fixed
- [x] Add version number to body of ACRA crash report
- [x] #3829 
- [x] #3792 fixed
- [x] See if #3856 occurs in 2.13 or not

**Comment by ashishkumar468** [comment]
@misaochan about the bitmap crash, do we have an issue or any crash logs?

**Comment by misaochan** [comment]
2.13.2 released to beta.
