### ISSUE TITLE
Remove CategoryImagesActivity

### ISSUE THREAD

**Issue by macgills** [commons-app/apps-android-commons#3785]
**Summary:** 

This activity is never used and can potentially be removed

**Commons app version:** 

master

**Comment by FawziyahAlebiosu** [comment]
@macgills can I do this or should I wait till there is more discussion on this thread?

**Comment by macgills** [comment]
@maskaravivek @misaochan @ashishkumar468  can ye weigh in on @FawziyahAlebiosu  removing this activity and its related files?

**Comment by ashishkumar468** [comment]
I think @FawziyahAlebiosu can take this up, the activity is actually never used
