### ISSUE TITLE
No images found on explore tab

### ISSUE THREAD

**Issue by neslihanturan** [commons-app/apps-android-commons#3798]
**Summary:** 
1- Type a category, ie. "Cat"
2- Images should appear on first tab and categories should appear on second tab "Felix the Cat"
3- Click "Felix the Cat" category
4- Images under felix the cat category should appear, but it says "Error occurred while loading images" at bottom and "No images found".

**Comment by macgills** [comment]
The title in the request isn't prefixed with `Category:`, pushing a fix
