### ISSUE TITLE
Use Material icons

### ISSUE THREAD

**Issue by veyndan** [commons-app/apps-android-commons#380]
Proposition to use the [Material design icons](https://material.io/icons/) instead of the default Android ones, the use of which is [generally discouraged](http://stackoverflow.com/a/3203765/3424405).

**Comment by misaochan** [comment]
I agree, that would be great.

**Comment by misaochan** [comment]
Would anyone like to take this task on? Would be fairly straightforward I believe.

**Comment by maskaravivek** [comment]
@misaochan I am picking this up. :)

**Comment by misaochan** [comment]
@maskaravivek Awesome, thanks. :)
