### ISSUE TITLE
[Leaderboard] Get a user's avatar

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#3826]
Commons does not really have a notion of avatar, but people who want to have a representative picture post it to their userpage. Examples:

https://commons.wikimedia.org/wiki/User:%C5%A0J%C5%AF (self-portrait)
https://commons.wikimedia.org/wiki/User:Amqui (self-upload picture showing the user's nickname)
https://commons.wikimedia.org/wiki/User:Giantflightlessbirds (picture the user is most proud of)
https://commons.wikimedia.org/wiki/User:Dan_Koehl (self-protrait in an infobox within a very elaborate userpage)
https://commons.wikimedia.org/wiki/User:Darren_J._Prior (several pictures that the user is proud of, we can just use the first one)

In most cases though there is no such picture, example: https://commons.wikimedia.org/wiki/User:Jeuwre

I suggest using the API that fetches media of a page, I don't remember its name but it was discussed recently by Jo I think.

**Comment by sivaraam** [comment]
I wonder if this is a good thing to do. People who include pictures in their talk pages don't particularly do that with an idea that it would shown as an avatar of them in some place (in our case: the leaderboard). Of course, some people might include them with the intent that it could be used to identify them. But I certainly don't think everyone would have such an idea. It's like we're going against their expectations.

So, why don't we just go with plain usernames just like how it's in the wiki world? I guess that would be a lot better and wiki-like.

**Comment by nicolas-raoul** [comment]
@sivaraam We have to be more user-friendly than the current "wiki world". The wiki world is currently very text-based (and visually boring), but this is changing, with for instance full-width horizontal banners at the top of Wikivoyage pages. The [web-hosted leaderboard](https://stats.wikimedia.org/#/commons.wikimedia.org/contributing/top-editors/normal|table|2020-06-22~2020-06-22|~total|daily) is extremely boring to see because it is text-based. Another advantage: Especially in a leaderboard, it is easier to remember other users with a picture than with a username, so that next time you see what progress you and others have made. And I don't think there is any legal nor moral problem with representing people with a picture they uploaded to their userpage.

**Comment by sivaraam** [comment]
>  And I don't think there is any legal nor moral problem with representing people with a picture they uploaded to their userpage.

May be not a legal issue. But I certainly think some people _might_ get offended by it because [god](https://commons.wikimedia.org/wiki/User:F%C3%A6) [knows](https://commons.wikimedia.org/wiki/User:Ytoyoda) [what](https://commons.wikimedia.org/wiki/User:Strakhov) [images](https://commons.wikimedia.org/wiki/User:Hohum) they have in their user pages. The main thing is: they would have no idea that the image in their user page would get used to identify them somewhere.

> Especially in a leaderboard, it is easier to remember other users with a picture than with a username, so that next time you see what progress you and others have made. 

If this is your goal, I think a self generated avatar or something similar would be a much better and non-controversial solution than using the image present in the user page. Also, the image present in the user page has several caveats including but not limited to the fact that it's not guaranteed to be the same image over time. So, an generated avatar sounds like a better solution to me.

**Comment by nicolas-raoul** [comment]
@sivaraam All of the images that you have found and linked under your sentence "god knows what images" are good pictures and represent correctly the user's style of contribution, which is great. Some avatars changing is not a big problem, a bit like companies change logos or people change their social media profile picture to a black rectangle or a soccer team.

**Comment by sivaraam** [comment]
I think you missed my main point.

> The main thing is: they would have no idea that the image in their user page would be used to identify them somewhere.

I say that as there are possibilities that a user ([count me in](https://commons.wikimedia.org/wiki/User:Kaartic)) might have used images for various purposes in their user page. They can't always be used to represent the user. At least, that's what I think. If you were suggesting to use an image uploaded by the user, that's different. We know that the user uploaded that for sure and so it might not that much of an issue when compared to using the image in the user page. Also, if we do that, we're more likely to get images for a user. (ex. a [top contributor](https://commons.wikimedia.org/wiki/User:Spinster) whose user page features no images)

Now, putting that ethical consideration aside and viewing from a technical perspective: I'm not sure how you would take any image from Commons and resize that to fit the size of the avatar. Commons has images of all sizes. I believe it's not an easy thing to resize those images to properly match the size of an avatar. Even if we could resize, I'm not sure how we can ensure it would look good. What idea do you propose to overcome this issue?

**Comment by nicolas-raoul** [comment]
About the technical perspective: We can just do like [Histropedia](http://histropedia.com/timeline/jynrtpg9bg0t/Italian-painters ) and resize. I don't think anyone has ever criticized Histropedia for resizing images, even though it often leads to unexpected results, for instance this circle-shaped painting of Da Vinci, with the top of the head cut off. Not a big worry.

**Comment by sivaraam** [comment]
>  We can just do like Histropedia and resize.

That does look nice. The images seem to be resized well for the container size that they have. Do they actually take those images from Commons and resize them?

**Comment by madhurgupta10** [comment]
I would be implementing this feature in the upcoming weeks, I think the best way is to add a menu item next to "Set As Wallpaper" which we can call as "Set as Avatar". This gives users the flexibility to browser through and selects the one they want.

**Comment by sivaraam** [comment]
> I would be implementing this feature in the upcoming weeks, I think the best way is to add a menu item next to "Set As Wallpaper" which we can call as "Set as Avatar". This gives users the flexibility to browser through and selects the one they want.

Nice idea. I just have one problem with that. As we would be managing the avatar chosen by a user, we would have to ensure the information is kept safe enough, right? How do we do that?

I'm considering "avatar" as a private information which we needs to be treated carefully (correct me if I'm wrong). So far, we didn't have this problem as all the information we use is obtained from Commons. We were just clients and didn't have to store anything. Your suggestion likely changes that aspect. Let me know if I'm missing something.

**Comment by madhurgupta10** [comment]
@sivaraam On the database side, I am just storing the suffix of the media and using it along with the base URL to display it in the app. 

Just to be clear that there is no duplicate copy created or saved anywhere.

**Comment by madhurgupta10** [comment]
@nicolas-raoul Maybe we can close this ticket?
