### ISSUE TITLE
WMF is planning to remove api_urls field in /page/summary endpoint

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#3831]
I just saw this post in wikitech-l, reposting in its entirety below. Do you know if we are using that endpoint @maskaravivek @ashishkumar468 ?

> Message: 1
> Date: Sun, 14 Jun 2020 21:00:00 -0500
> From: Adam Baso <abaso@wikimedia.org>
> To: Wikimedia developers <wikitech-l@lists.wikimedia.org>
> Subject: [Wikitech-l] Planned removal of api_urls field in
>         /page/summary   endpoint
> Message-ID:
>         <CAB74=Nr7wK6n_1MnUiFzkbRjzR+_RB45-r=uuEiuu2DKykSy2w@mail.gmail.com>
> Content-Type: text/plain; charset="UTF-8"
> 
> This message is a notice about forthcoming removal of a response field in
> the REST API’s /page/summary endpoint. [1] This message is being cross
> posted to wikitech-l and mediawiki-api-announce.
> 
> The endpoint is used in the Page Previews (“hovercards”) functionality on
> the classic web (desktop) and Android & iOS experiences for Wikipedia, in
> addition to numerous external experiences. We don't anticipate impacts on
> the mainline Wikipedia experiences from this forthcoming field removal, as
> the endpoint will still be operational.
> 
> The REST API's /page/summary endpoint provides an api_urls field in its
> response with links to several other REST API endpoints supported by the
> Page Content Service.
> 
> Three of the api_urls subfields refer to experimental endpoints that have
> been removed from the REST API altogether in favor of newer API endpoints.
> 
> 1. media (/page/media)
> 2. references (/page/references)
> 3. metadata (/page/metadata).
> 
> api_urls also contains subfields referring to stable endpoints that
> continue to exist in the REST API:
> 
> 1. summary (which is self referential)
> 2. edit_html (/page/html - the Parsoid HTML)
> 3. talk_html (/page/html/Talk:<title> - the Parsoid HTML for the
> corresponding Talk page)
> 
> Wikimedia’s Product Infrastructure team intends to remove the api_urls
> field of the /page/summary response.
> 
> A cursory review at https://codesearch.wmflabs.org/ and Wikimedia Git
> mirrors suggests api_urls isn’t in use in consuming code.
> 
> Review of web logs suggests traffic for the following endpoints:
> 
> - The media endpoint is at about 5% of its original traffic before its
> decommission and it appears to be from old Wikipedia for Android clients.
> This is expected.
> - The references endpoint’s Wikipedia for Android traffic does not seem
> present and its other traffic appears to be from non-user application
> software based on User-Agent header components.
> -The metadata endpoint’s traffic seems to have all but stopped.
> 
> This change is being announced in advance of the change because the
> endpoint is advertised as stable. [2]
> 
> Please update your clients if you rely on the presence of the api_urls
> field. If this change poses a problem for your clients, please do let us
> know as soon as possible at the tracking task:
> 
> https://phabricator.wikimedia.org/T247991
> 
> We plan to remove the api_urls field described here on or after 14 July
> 2020.
> 
> Thank you.
> 
> Adam Baso
> Director of Engineering
> Wikimedia Foundation
> 
> [1]
> https://en.wikipedia.org/api/rest_v1/#/Page%20content/get_page_summary__title_
> [2] Refer to
> https://www.mediawiki.org/wiki/API_versioning#End_point_stability and
> https://www.mediawiki.org/wiki/Wikimedia_Product/Wikimedia_Product_Infrastructure_team/API_endpoint_stability_policy
> for more information on stability designations.
>

**Comment by maskaravivek** [comment]
We are not using this endpoint.

**Comment by misaochan** [comment]
Thanks @maskaravivek
