### ISSUE TITLE
We are hiring a part-time Android developer and tester (contractor)

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#3840]
Hey all, we are hiring a part-time Android app developer and tester (contractor, 1 yr) to join our team! This is a fully-remote position, and you will be working in a collaborative open-source environment with a diverse team from all over the world to improve the Commons app. :)

**Role**
- Android app development, primarily focused on increasing code coverage (writing unit tests, refactoring code to increase testability) and improving stability (fixing bugs/crashes)
- Manual app testing

**Details**
- USD 20/hr @ 15 hrs/week, for 50 weeks
- Fully-remote. We are open to all timezones and you can choose your own hours, as long as deadlines and quality requirements are met

**Requirements**
- 1+ year of experience in native Android development (Java/Kotlin) and version control systems (git)
- An active open-source development profile and familiarity with working in collaborative environments

If you are interested, apply [here](https://bit.ly/37TkFOJ).

Applications close on 12 July 2020, and the job will begin mid-late July. Feel free to ask if you have any further questions!

**Comment by madhurgupta10** [comment]
@misaochan Although I am working on the GSoC project right now till August 2020, I would be happy to apply if eligible :)

**Comment by misaochan** [comment]
Hi @madhurgupta10 , thanks for your interest! You are definitely eligible to apply for this job from my point of view, however you would need to check with your GSoC mentors to see if there are any GSoC regulations that prohibit you from applying for it. :)

**Comment by bnasim** [comment]
@misaochan I am interested for this role. I would apply.

**Comment by vvijayalakshmi21** [comment]
Just submitted my application!
This is an amazing opportunity. Thank you!

**Comment by misaochan** [comment]
Thank you for applying, @vvijayalakshmi21 and @bnasim . :) We'll get back to you shortly.

**Comment by madhurgupta10** [comment]
@misaochan I just completed my application as well :)

**Comment by misaochan** [comment]
Thanks @madhurgupta10 !

**Comment by ujjwalagrawal17** [comment]
@misaochan I am interested too. Will fill the application soon.

**Comment by misaochan** [comment]
@ujjwalagrawal17 Awesome! :)

**Comment by chirag-jn** [comment]
@misaochan thanks for opening such opportunity. I'm currently a GSoC 2020 participant and my participation ends on 31 August. Is there some way in which we can start by 1st September and make up for the lost time by increasing the number of hours per week by the amount of time lost before that?

**Comment by misaochan** [comment]
@chirag-jn Yes, you can apply anyway and request this in the final comment section in your application. I cannot guarantee it but it is a possibility.

**Comment by chirag-jn** [comment]
Great @misaochan thanks

**Comment by misaochan** [comment]
Hi all, just a friendly reminder that I will be closing the application form around [9am UTC](https://www.worldtimebuddy.com/?qm=1&lid=100,2174003,8&h=100&date=2020-7-13&sln=9-10) on 13th July. If you are planning to apply and have not done so, please do so before then. :)

**Comment by ujjwalagrawal17** [comment]
Just submitted my application @misaochan :)

**Comment by chirag-jn** [comment]
I've just submitted my application @misaochan. Expecting to hear a reply soon 😁

**Comment by MSSoumya** [comment]
@misaochan I have just submitted my application. :) 
Thank you for this opportunity!

**Comment by misaochan** [comment]
Applications are now closed. Thank you to everyone who applied! :) I will be discussing the applications with the team, and will get back to you within the next couple of weeks.

**Comment by Husseinhj** [comment]
If it's still open. I am interested too

**Comment by TejaswiKarasani** [comment]
@misaochan just a request to checkout my github profile overview. I have been playing almost similar role for [this project](https://github.com/mozilla-mobile/fenix/) since early this year. Thanks  in advance!

**Comment by misaochan** [comment]
Sorry guys, applications were closed on 12 July. :( I will update you if we have an opening in the future.

**Comment by misaochan** [comment]
The position has been filled, thank you very much to everyone who took the time to apply! If we have another opening in the future, I will create a new issue.
