### ISSUE TITLE
Contributions list starts at the last uploaded pic, not the currently uploading one

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#3845]
**Summary:** 

Normally after the user uploads a pic and goes back to Contributions, the first item on the list should be the currently-uploading pic. But now it is the last-uploaded pic and they need to scroll up to see the current one. This makes it confusing as they might assume that the upload didn't go through.

**Steps to reproduce:** 

Upload a pic
Go back to Contributions

**Device and Android version:** 

Samsung Galaxy s9 Android 10
 
**Commons app version:** 

master

**Comment by rhulkb27** [comment]
Hey I wan't to work on this, i'll repro it tonight. @misaochan

**Comment by misaochan** [comment]
Go for it @rhulkb27 ! :)

**Comment by ashishkumar468** [comment]
Hi @rhulkb27  Any updates on this issue?

**Comment by neslihanturan** [comment]
I guess this issue is available/unassigned now
