### ISSUE TITLE
welcome_final images are offset to left

### ISSUE THREAD

**Issue by domdomegg** [commons-app/apps-android-commons#385]
In [`welcome_final.xml`](https://github.com/commons-app/apps-android-commons/blob/master/app/src/main/res/layout/welcome_final.xml) images are offset to left when the phone is portrait:

![screenshot_20170305-011609](https://cloud.githubusercontent.com/assets/4953590/23583625/c22b65ea-0141-11e7-8629-96a08eaf24c8.png)

I think it's related to the LinearLayout rather than RelativeLayout - not sure why used here, will have to have a look properly later.

**Comment by domdomegg** [comment]
Just realised this is our 100th issue closed @misaochan @nicolas-raoul 

:champagne: :tada:

**Comment by misaochan** [comment]
Yay! You're the lucky winner! 💯 :rofl:
