### ISSUE TITLE
Checkstyle results should be visible on pull requests

### ISSUE THREAD

**Issue by whym** [commons-app/apps-android-commons#386]
"Use Checkstyle for travis-CI" (#359) has been implemented. I think the next step for the repo owner is integrating it and making it visible on pull requests, just like the check marks given by Travis CI for builds (but apparently not for Checkstyle?).

Does anyone have suggestions on how to integrate Checkstyle to GitHub?

I'm not well experienced with this, but it looks like one option is [using Codacy](https://github.com/integrations/codacy). See https://support.codacy.com/hc/en-us/articles/207280219-GitHub for how to do that.

**Comment by misaochan** [comment]
@nicolas-raoul , what do you think?

**Comment by nicolas-raoul** [comment]
Yeah, that would be very useful!
I hope it does not prevent creating and merging pull requests that are not 100% Checkstyle-approved, though.

**Comment by misaochan** [comment]
Sounds good @nicolas-raoul . Only you or I can make the changes needed for the integration, right?

**Comment by nicolas-raoul** [comment]
I tried, not sure everything is OK?
I did not find any way to enter an organisation's repo, so I entered by URL.

**Comment by misaochan** [comment]
I don't see anything new on the PRs, haha. And it says "Pull Requests integration not enabled" on the dashboard that you linked? Not sure how to fix that, I'll have to read up more on Codacy first.

**Comment by whym** [comment]
I tried a new pull request and it does not seem to be working: https://github.com/commons-app/apps-android-commons/pull/398

Here is how it should look like: https://github.com/whym/apps-android-commons/pull/4 https://github.com/whym/apps-android-commons/pull/5

**Comment by whym** [comment]
@nicolas-raoul: did you use https://www.codacy.com/wizard/projects? I remember seeing an option to add an organization repo there.

**Comment by nicolas-raoul** [comment]
@whym: I don't see any such option:
![screenshot from 2017-03-06 21-12-29](https://cloud.githubusercontent.com/assets/99590/23609514/c08c5156-02b1-11e7-96fd-204c6b3708f6.png)

**Comment by whym** [comment]
@nicolas-raoul Is the "commons-app" org listed at the Codacy section of your https://github.com/settings/applications ? If not, revoking the authorization and then re-enable it (by sigining into Codacy with GitHub) might work.

**Comment by nicolas-raoul** [comment]
@whym: It was not listed, so I tried revoking, but I don't see how to re-enable it:
![screenshot from 2017-03-06 22-04-17](https://cloud.githubusercontent.com/assets/99590/23611118/01b608c8-02b9-11e7-8d0b-2441fef07153.png)

**Comment by whym** [comment]
I think Codacy will ask you at your next login. You might have to manually logout first.

**Comment by nicolas-raoul** [comment]
@whym Still no luck... would you mind setting it up? :-)

**Comment by whym** [comment]
Okay, after some attempts, it now seems to work. https://github.com/commons-app/apps-android-commons/pull/399#pullrequestreview-25458265

Let's see if it works on patches that are not mine (preferably not from a member of this org).

**Comment by whym** [comment]
@nicolas-raoul can you try integration (both GitHub integration and Post-Commit Hook) from https://www.codacy.com/app/commons-app/apps-android-commons/settings/integrations again? I think this requires owner access to the repo. You might have to disable my integration first.

**Comment by nicolas-raoul** [comment]
Done! Anything else I should do?

**Comment by misaochan** [comment]
Seems to work for me now, thanks guys. :) Will keep you updated when more PRs come in, @whym .

**Comment by misaochan** [comment]
Also, @whym , I sent you an invite to join this repo as collaborator, did you receive it?

**Comment by whym** [comment]
@misaochan Accepted, but being a collaborator doesn't seem to help enabling integrations like this, does it? I still don't have access to the repo's settings page.

**Comment by misaochan** [comment]
Looks like it's working on the latest PRs?

**Comment by whym** [comment]
Yes, it seems that there is no remaining issue with this. Thanks!
