### ISSUE TITLE
Available for volunteering on a data science project

### ISSUE THREAD

**Issue by ghost** [commons-app/apps-android-commons#3866]
I am open to volunteering in a data science related project.

I just started learning how to program with Python. I have skills in MySQL query writing, using Excel and i am available to volunteer in a data science related project as long as i can learn at the end of it. I can dedicate 3 hours daily. My reasons are for me to learn, experience, grow in my skills and also add value. 

 Thank you @nicolas-raoul for encouraging me to put this here.

**Comment by nicolas-raoul** [comment]
Hi! Thanks for posting.
Do you have a minimum and a maximum regarding the number of days that the project should take?
Is it OK to send you different projects rather than one big project?

**Comment by nicolas-raoul** [comment]
A possible project could be to find out how contributions made from the Android Commons app differ from contributions made by other means.

Here is some documentation, please be aware that finding the right documentation can be hard and is part of the work, included in the project: https://www.mediawiki.org/wiki/Category:MediaWiki_database_tables

Many query examples can be found here: https://quarry.wmflabs.org/query/runs/all A first task could be to find all queries that are related to Commons.

Also, please be aware that we are volunteers and can not promise dedicated help :-)

**Comment by nicolas-raoul** [comment]
@JOYCE-FRED Here is the first task: Show per-country upload trends. It requires some SQL skills to get the image titles, a bit of scripting to get latitudes/longitudes from pictures EXIF, and a bit of data processing to match latitudes/longitudes to countries. If you have any question please ask here. If you have 3 hours daily, it could take from 2 weeks to 2 months. Thanks and good luck! :-)

**Comment by JOYCE-FRED** [comment]
@nicolas-raoul on checking through the links sent to me. I noticed that quarry platform has additional projects asides MediaWiki, how can categorical search be done more easily through the site?
MediaWiki database is large which is not what i am used to, so i will take time to read and understand how the table are connected. 
Also, is there a particular table that the project is focused on?

**Comment by nicolas-raoul** [comment]
Quarry is only about Mediawiki sites such as Wikipedia or Commons.

There are many databases and tables, but the most important for the task I described at https://github.com/commons-app/apps-android-commons/issues/3866#issuecomment-655937535 is probably table `image` of database `commonswiki_p`, which can be seen in use in this query: https://quarry.wmflabs.org/query/46513

Please use https://quarry.wmflabs.org/query/653 and https://quarry.wmflabs.org/query/46514 and use LIMIT to get familiar with the data.

**Comment by Rishavgupta12345** [comment]
@nicolas-raoul this issue is useless you can close this

**Comment by nicolas-raoul** [comment]
@Rishavgupta12345 Please do not say "useless", that's unfriendly.

@ghost Did you find anything? If yes feel free to comment :-)

**Comment by gangaasoonu** [comment]
I'll try
