### ISSUE TITLE
Chunked uploads fail on master

### ISSUE THREAD

**Issue by maskaravivek** [commons-app/apps-android-commons#3868]
Hi everyone, I looked into the logs sent by @nicolas-raoul. So the this error is thrown when the upload fails
`{"errors":[{"code":"stashfailed","text":"Invalid chunk offset","data":{"offset":"2621440"},"module":"upload"}],"docref":"See https://commons.wikimedia.org/w/api.php for API usage. Subscribe to the mediawiki-api-announce mailing list at &lt;https://lists.wikimedia.org/mailman/listinfo/mediawiki-api-announce&gt; for notice of API deprecations and breaking changes.","servedby":"mw1362"}`

@maskaravivek  Could this be related to your recent commits for the pause/resume feature?

_Originally posted by @ashishkumar468 in https://github.com/commons-app/apps-android-commons/issues/3247#issuecomment-655644628_

**Comment by maskaravivek** [comment]
Update: I have been trying to fix the issue by handling `stashfailed` and other errors like `verification-error`(listed [here](https://www.mediawiki.org/wiki/API:Upload#Possible_errors)) but I am running into issues while testing it. I should be able to fix the issue by this weekend.

**Comment by misaochan** [comment]
Thanks for the update @maskaravivek !
