### ISSUE TITLE
Codecov is not running for some of the PRs

### ISSUE THREAD

**Issue by maskaravivek** [commons-app/apps-android-commons#3873]
**Summary:** 

Codecov should run and comment should appear automatically on PRs with code coverage information. Recently it seems to be not happening for some of the PRs.

**Comment by madhurgupta10** [comment]
@maskaravivek Does it work on master branch PRs?

**Comment by maskaravivek** [comment]
Nope

**Comment by madhurgupta10** [comment]
@maskaravivek Looks like this one is resolved, I can see the report on my PR https://github.com/commons-app/apps-android-commons/pull/3892
