### ISSUE TITLE
[GSoC Task] Add pagination in the leaderboard screen to load more users on scrolling down.

### ISSUE THREAD

**Issue by madhurgupta10** [commons-app/apps-android-commons#3874]
**Summary:** 
Add pagination in the leaderboard screen to load more users on scrolling down.

- [x] Implement Pagination

- [x] Add Button for AutoScroll to user’s rank

**Would you like to work on the issue?**
Yes

**Comment by maskaravivek** [comment]
@madhurgupta10 Please use AndroidX Paged Lists for pagination.

**Comment by madhurgupta10** [comment]
@nicolas-raoul @maskaravivek We currently don't have many users on the leaderboard, if you would give me a list of some usernames that I can add, then it would be great :)

**Comment by maskaravivek** [comment]
You can use my user IDs `Maskaravivek` and `Testmaskara`. 

Tagging others to see if they would be okay sharing their userIDs for the leaderboard. 

@misaochan @neslihanturan @ashishkumar468 @sivaraam

**Comment by nicolas-raoul** [comment]
<img width="187" alt="Screen Shot 2020-07-16 at 09 14 10" src="https://user-images.githubusercontent.com/99590/87612183-ce3c8e00-c744-11ea-8db9-d4b1dd504a54.png">
You can find thousands others here: https://quarry.wmflabs.org/query/18084

**Comment by misaochan** [comment]
> You can use my user IDs `Maskaravivek` and `Testmaskara`.
> 
> Tagging others to see if they would be okay sharing their userIDs for the leaderboard.
> 
> @misaochan @neslihanturan @ashishkumar468 @sivaraam

Sure, you can use `Misaochan` and `Misaochan2` . :)

**Comment by sivaraam** [comment]
> Tagging others to see if they would be okay sharing their userIDs for the leaderboard.
> 
> @misaochan @neslihanturan @ashishkumar468 @sivaraam

Sure you can use `Kaartic` .

I'll note that I don't have a lot of [uploads](https://commons.wikimedia.org/wiki/Special:ListFiles?limit=50&user=Kaartic), though :) I guess that might be helpful in its own way ;)
