### ISSUE TITLE
Update min SDK?

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#3880]
For a long time, we have kept our min SDK lower than most (currently we are at 19), because we wanted to be as inclusive as possible towards lower income user groups. Realistically speaking however, we do not usually test the app exhaustively on the lowest APIs and we probably will not have the resources to do so in the near future, so people using these devices would be very prone to crashes. Also the lower APIs require some code workarounds that the higher ones don't.

Updating the min SDK based on the industry average would have the tradeoff of not being as inclusive, but would provide users with a smoother experience.

In https://stackoverflow.com/questions/24441178/recommended-minimum-android-app-sdk/42489666 , a commenter linked https://twitter.com/minsdkversion , which seems to be relatively reputable. It recommends a min SDK of 23 as of Dec 2019.

Looking at our dev console, this would remove <200 users, compared to the 6700 that we currently have.

Thoughts?

**Comment by maskaravivek** [comment]
Yeah, I agree with the pros of increasing the minSdk version. Also, updating the min SDK would mean that users on lower versions can't receive app updates but they can still use the existing version. Also, new users would still be able to download the current version after we update the minSDK(Google Play Console lets you keep the existing version for older devices.).

**Comment by neslihanturan** [comment]
My suggestion is removing it after we think we have a stable version already. Considering they won't get any updates, critical bugs shouldn't exist.

**Comment by misaochan** [comment]
Good point, let's go with that. We can revisit this discussion after 3.0 has been out for a while maybe. :)

**Comment by sivaraam** [comment]
If resource is the primary reason for increasing the min SDK from 19, I'll be glad to lend a hand. I use an API 22 (5.1.1) device for day to day use and also happen to have access to a API 19 device (4.4). I'm really glad that many apps that I use day to day such as [Signal](https://github.com/signalapp/Signal-Android), still support lower API devices. I would be glad if we could do the same.

If technical burden due to support for low minSdk is the primary reason, then feel free to proceed with the plan. In the end, we do have to make this choice someday.

**Comment by misaochan** [comment]
Thanks a lot @sivaraam , that would be greatly appreciated! I will ping you when v3.0 is ready for testing? :)

There is definitely a technical burden caused by low minSdk as well. Eventually that will probably be the main reason for switching, but for the time being it would be great to have an API 19/22 user to test our next release to make sure it's stable for lower API devices.

**Comment by sivaraam** [comment]
> I will ping you when v3.0 is ready for testing?

Sure. Also, feel free to ping me whenever you want something tested in the low APIs. I'll be glad to. 🙂 

That doesn't mean I would stop testing at my own will, of course. 😉

**Comment by TacoTheDank** [comment]
I feel like upgrading from 19 to 23 is a bit too large of a jump. I think it would be better to first upgrade to 21, and in due time (when Google gets closer to dropping support for API 16-19) eventually upgrade to 23 (or maybe to 22 and then 23).

**Comment by Roshan13046** [comment]
> I feel like upgrading from 19 to 23 is a bit too large of a jump. I think it would be better to first upgrade to 21, and in due time (when Google gets closer to dropping support for APIs 16-19) eventually upgrade to 23 (or maybe to 22 and then 23).

Can I update the min SDK version from 19 to 21?

**Comment by U81-A** [comment]
I'm trying to provide my own method to enhance it. :)

**Comment by sivaraam** [comment]
Closing this as we've already bumped minSdk to 21 as part of #5175 and even [bump the same to 29](https://github.com/commons-app/apps-android-commons/commit/9b9521a034d10f87ce43ba36bef8c7581dcbf8d6) (intermediarily) to fix #5031.
