### ISSUE TITLE
Changing orientation in media detail view resets fragment_media_detail

### ISSUE THREAD

**Issue by domdomegg** [commons-app/apps-android-commons#389]
Changing orientation while viewing a file shows the template fragment_media_detail

![screenshot_20170305-172543](https://cloud.githubusercontent.com/assets/4953590/23589661/12b50ba6-01c9-11e7-8953-d071a3655ba6.png)

**Comment by misaochan** [comment]
Uh, wow. Good find, lol.

**Comment by domdomegg** [comment]
Had a deeper look, caused in [`MediaDetailFragment.java#L131`](https://github.com/commons-app/apps-android-commons/blob/master/app/src/main/java/fr/free/nrw/commons/media/MediaDetailFragment.java#L131). Normally, media is never null, however when `onCreateView` is called after orientation change it is for some reason.

`index` is the same regardless of how `onCreateView` was called, so it has to be something about `detailProvider`

**Comment by domdomegg** [comment]
Some more information for troubleshooting, when `onCreateView` is called normally, `getTotalMediaCount` returns 468 (the number of files I have uploaded). When called from orientation change it returns 0.

**Comment by neslihanturan** [comment]
I think #639 solved this issue. If not, please reopen it.
