### ISSUE TITLE
The same images are listed multiple times in contributions tab

### ISSUE THREAD

**Issue by matkoniecz** [commons-app/apps-android-commons#3898]
**Summary:** 

Summarize your issue in one sentence (what goes wrong, what did you expect to happen)

https://commons.wikimedia.org/wiki/File:Asphalt_track.jpg is displayed at least twice in my list of images

It is not limited to just flicker as one scrolls across list (when previously displayed imaged are briefly shown before showing real one)

It is not confusion with other uploads, see https://commons.wikimedia.org/w/index.php?title=Special:ListFiles/Mateusz_Konieczny&ilshowall=1

It seems that photos uploaded with app are shown twice.

_Before creating an issue, please search the existing issues to see if a similar one has already been created. You can search issues by specific labels (e.g. `label:nearby`) or just by typing keywords into the search filter._

Done

**Steps to reproduce:** 

How can we reproduce the issue? 

Upload image with this app.

What did you expect the app to do, and what did you see instead?

Contributions image lists shows it exactly one. It is displayed twice instead.

**System logs:**

Not attached for now, I can do this later if useful/needed.

```
Add logcat files here (if possible).

Need help? See https://github.com/commons-app/apps-android-commons/wiki/Getting-app-logs-from-Android-Studio
```

**Device and Android version:** 

What make and model device (e.g., Samsung J7) did you encounter this on?

Xiaomi Mi A2 Lite

What Android version (e.g., Android 4.0 Ice Cream Sandwich or Android 6.0 Marshmallow) are you running?
Is it the stock version from the manufacturer or a custom ROM ?
 
Stock Android 10

**Commons app version:** 

You can find this information by going to the navigation drawer in the app and tapping 'About'. If you are building from our codebase instead of downloading the app, please also mention the branch and build variant (e.g. master and prodDebug).

2.12.3~dc08a5e88

**Screen-shots:** 

Can be created by pressing the Volume Down and Power Button at the same time on Android 4.0 and higher.

![Screenshot_20200812-102515](https://user-images.githubusercontent.com/899988/89992881-36b85580-dc86-11ea-9726-3510bd1eeec0.png)

**Would you like to work on the issue?**

Please let us know whether you want to fix the issue by yourself. If not, anyone can get the issue assigned to them.

No, I sadly have no time left for that.

**Comment by Soroyesodiq** [comment]
I will like to work on this

**Comment by ashishkumar468** [comment]
Hi, @Soroyesodiq  Feel free to pick this up, before you attempt to fix this, please try to reproduce this and feel free to post updates over here :)

**Comment by Soroyesodiq** [comment]
I tested the app on both Android 7.0 and 9.0 devices and it worked perfectly fine.

**Comment by misaochan** [comment]
Hi @Soroyesodiq , which version of the app did you test? Was it the current master?

**Comment by Soroyesodiq** [comment]
I tested it on both version 2.12.3-debug-master and the current android play store version

**Comment by ashishkumar468** [comment]
Hi @Soroyesodiq I am not seeing this issue in the latest release, or master, please verify if this still exists

**Comment by sivaraam** [comment]
> Hi @Soroyesodiq I am not seeing this issue in the latest release, or master, please verify if this still exists

I believe the verification should be done by @matkoniecz

**Comment by ashishkumar468** [comment]
@matkoniecz Are you seeing this issue in the latest release?

**Comment by matkoniecz** [comment]
2.13.2~757c7b008 - scrolling down (especially fast one) still triggers this

**Comment by sivaraam** [comment]
I believe it's fine to make a test upload when you file it under the "[Test uploads](https://commons.wikimedia.org/wiki/Category:Test_uploads)" category and later nominate it for deletion.

Alternatively, @nicolas-raoul _might_ be able to provide you a useful image for upload if you want to got that route :)

**Comment by nicolas-raoul** [comment]
@matkoniecz Feel free to upload these pictures: https://drive.google.com/drive/u/1/folders/1T5wfM16qb78XCvnf1Zunww4neg8BXJj6 :-) You can use each picture's filename as a title. Thanks!

**Comment by matkoniecz** [comment]
@nicolas-raoul Sorry for a later reply. Which license I should use for that photos?

**Comment by nicolas-raoul** [comment]
CC0, thanks!

**Comment by matkoniecz** [comment]
I finally go to this, unable to really reproduce it.

Lets assume that it was fault of my phone/Android version that had buggy RecyclableView.

**Comment by nicolas-raoul** [comment]
Thank you for checking!
If you notice any problem, please do not hesitate to create another issue :-)
