### ISSUE TITLE
Contributing to the project

### ISSUE THREAD

**Issue by sid-the-ant** [commons-app/apps-android-commons#3907]
Me and my team are looking for an open source project to contribute to, and this seems like a good starting point to work on.

I have a couple of queries, and I would be glad if someone would help us out.

1. Besides the ones listed in the CONTRIBUTING.md, are there anymore requirements for the contributions(mostly bug fixes) to be merged with the project?
 2. Are feature additions considered for merging with the project?

I'm new to contributing to OSS, so any help would be really appreciated! :D

**Comment by madhurgupta10** [comment]
@sid-the-ant Hi welcome, you can look for issues with **good-first-issue** tag and get them assigned to you, regarding new features, you can always create a new issue and based upon the discussion a new feature could be implemented :)

**Comment by Rishavgupta12345** [comment]
@nicolas-raoul this issue is useless you can close this

**Comment by nicolas-raoul** [comment]
@Rishavgupta12345 Please do not say "useless", that's unfriendly.
