### ISSUE TITLE
Make spinners labels fit in portrait mode

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#3910]
The spinners are an important part of the leaderboard, we want to allow everyone to quickly check each.
Unfortunately their labels are truncated in portrait mode on a rather wide (1080 pixels) smartphone, making them less discoverable and less usable:
![screen](https://user-images.githubusercontent.com/99590/91304705-e3e1b080-e7e4-11ea-96f0-1d0216efe1cb.png)
The labels definitely have space to fit, it is strange that they get truncated at all.

**Comment by madhurgupta10** [comment]
@nicolas-raoul I will surely do it after the https://github.com/commons-app/apps-android-commons/pull/3905 is merged.
