### ISSUE TITLE
"Send Log File" does not collect updated logs

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#3920]
**Summary:** 

Recently I've noticed that the "Send Log File" feature does not collect the recent logs. The last one that I sent only collected up to 3rd September, which is pointless for actually finding the source of a problem.

**Steps to reproduce:** 

Settings > Send Log File, then check the files generated

**Device and Android version:** 

Android 10, Samsung Galaxy s9
 
**Commons app version:** 

2.13-release

**Comment by nicolas-raoul** [comment]
Is there a way to work around the problem?
For instance restarting the app?
Or maybe deleting the app's storage in the Android settings?

**Comment by misaochan** [comment]
I am not familiar with a workaround. :/ But I have asked @ashishkumar468 to prioritize this.

**Comment by ashishkumar468** [comment]
I verified the code and the official docs on ACRA, not sure how we could have added a bug in this because our code does exactly as they have mentioned in their docs

**Comment by nicolas-raoul** [comment]
If everything is done according to the doc, it is worth reporting the issue at https://github.com/ACRA/acra/issues

**Comment by misaochan** [comment]
Does "Send Log File" use ACRA, though? ACRA is just for the crash reports, right?

**Comment by ashishkumar468** [comment]
My bad, I assumed this is done via ACRA, let me debug the code and get back, sorry for the confusion

**Comment by nicolas-raoul** [comment]
Thanks! :-)

Might be totally unrelated and a problem on my side, but I noticed this strangely cropped namespace in logcat:
<img width="139" alt="Screen Shot 2020-10-11 at 23 02 49" src="https://user-images.githubusercontent.com/99590/95680631-03f2f500-0c16-11eb-98fd-60de850140be.png">
