### ISSUE TITLE
[2.13-release] Logout does not work 

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#3921]
**Summary:** 

Tapping "Logout > Yes" does not actually log me out now. 

More specifically, it seems like I am technically "logged out" but it is not reflected in the UI. Instead of being brought back to LoginActivity I am in Contributions still, with a bunch of images that are not mine.

**Device and Android version:** 

Android 10, Samsung Galaxy s9
 
**Commons app version:** 

2.13-release

**Comment by sivaraam** [comment]
Possible duplicate of #3547
