### ISSUE TITLE
2.13.1: "Back" does nothing in Nearby in particular circumstance

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#3923]
2.13.1-debug-2.13-release~624d351d4
I sent a log with the same title.

I actually did not open the app's home activity at all today, I only shared pics to the app. After doing something else I opened the app, it opened on Nearby (maybe the state at which I left it yesterday?). I pressed "Back" but it did nothing, not exiting the app, not going to contributions. I pressed Back many times, same absence of result.

After killing the app and trying again, "Back" correctly sends me to contributions.

![Screenshot_20200911-112312_Commons](https://user-images.githubusercontent.com/99590/92846379-fc77da80-f422-11ea-9d4b-b3c28c47eba8.jpg)

**Comment by ashishkumar468** [comment]
@nicolas-raoul  I have raised a possible fix PR for this one, can you help test it please?

**Comment by nicolas-raoul** [comment]
Actually this issue has only happened once to me, so it is difficult to reproduce on any branch...
