### ISSUE TITLE
2.13.1: Upload really failed, but "Retry" does not seem to do anything, pics actually not uploaded

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#3925]
2.13.1-debug-2.13-release~624d351d4

- On a fast Internet connection, I uploaded two sets of pictures, all with せたかや未来の平和館 in the title.
- They all failed (which is strange too by the way). 
- When I tapped the "retry" icon on any of them, nothing happened. I tapped several times.
- Scrolling up does not show more pics.
-  On the Commons website, I don't see the pics in my contributions.

![Screenshot_20200911-112433_Commons](https://user-images.githubusercontent.com/99590/92846796-67c1ac80-f423-11ea-898d-f01a0a63b052.jpg)

Edit: This just happened again, for a single picture upload this time.

**Comment by mnalis** [comment]
- Possible related issue is still present in 4.1.0, see https://github.com/commons-app/apps-android-commons/issues/5231#issuecomment-1593305371 for logs & screencast video

**Comment by nicolas-raoul** [comment]
This area has improved and changed a lot since.
