### ISSUE TITLE
Feature request: remember categories and suggest

### ISSUE THREAD

**Issue by dpriskorn** [commons-app/apps-android-commons#3937]
Remember last users categories and suggest them by default to the user

**Comment by ashishkumar468** [comment]
As @nicolas-raoul  mentioned that the app already does this, does that not happen for you @egils-consulting . Also it would be really helpful if you could follow the issue template and add more tags, removing the bug tag for now while we receive more information on the issue.

**Comment by dpriskorn** [comment]
I no longer use the application and resort to the browser based upload instead which work better for me 🤷‍♂️
Closing this.
