### ISSUE TITLE
Unable to report crash using ACRA

### ISSUE THREAD

**Issue by sivaraam** [commons-app/apps-android-commons#3941]
**Summary:** 
I'm using version 2.13.1.793~66f6e2e of the app on a Samsung SM-J111F running Android 5.1.1. When I face a crash when using the app, the ACRA pop-up shows up but when I enter a description and hit "Submit" the e-mail client doesn't seem to be opening up like it should. As a consequence I'm unable to report crashes using the ACRA window. Note that I use K-9 mail as my e-mail client and *do not* have Gmail installed on my device. Let me know if more information is needed.

**Comment by misaochan** [comment]
Hmm. Are you able to open K-9 mail with an intent from any other apps? Do you have any other email apps on your phone (not necessarily gmail) that you could test with to see if it works? We need to figure out if the issue is K-9 mail specific, or if it affects more than just one client (I know it works for gmail).

**Comment by sivaraam** [comment]
> Are you able to open K-9 mail with an intent from any other apps? 

The "Send log file" option in our app works fine with K-9 mail. I also remember that crash reporting worked fine with K-9 mail for the "[My Expenses](https://github.com/mtotschnig/MyExpenses)" app when I reported a crash a couple of days ago.

> Do you have any other email apps on your phone (not necessarily gmail) that you could test with to see if it works?

I actually installed two e-mail apps to check this one. One of those was Gmail. None of them work. I just see nothing after tapping on "OK" on the ACRA crash dialog. Very werid.

**Comment by neslihanturan** [comment]
Possibly related: 
![resim](https://user-images.githubusercontent.com/3127881/94596953-951cb000-0295-11eb-8d0d-feef7a90b10b.png)

**Comment by sivaraam** [comment]
I observed a crash in v2.13.1.809~409e43c of the app and the ACRA window popped up. When I tapped on "Ok", "Open with" suggests for e-mail clients are shown. When I tap on K-9 mail it properly takes me to the mail composition window. So, it looks like crash reporting works in that version. So, I'm closing this issue for now. If I or someone else is able to reproduce, we can re-open this.
