### ISSUE TITLE
Write Test for Quiz

### ISSUE THREAD

**Issue by madhurgupta10** [commons-app/apps-android-commons#3942]
**Summary:** 
Write tests for Quiz package classes.

**Would you like to work on the issue?**
Yes

**Comment by madhurgupta10** [comment]
@misaochan While writing test for QuizController I noticed that **context.getResources().getString()** is used to get Strings instead we can directly use **context.getString()** on context, this makes it easier to mock during the test, should I change this in the class?

**Comment by maskaravivek** [comment]
Yes, feel free to make this change. It won't affect the behavior.
