### ISSUE TITLE
Toggling the Telemetry opt-out option has no effect

### ISSUE THREAD

**Issue by sivaraam** [commons-app/apps-android-commons#3943]
**Summary:** 
In the app settings, when I'm unable to toggle the "Telemetry opt-out" option that's supposed to enable/disable the Mapbox telemetry. How many ever times I tap on it, it just remains enabled.

Also, in retrospect, I believe "Telemetry Opt Out" is kind of a contradictory name for the option as it contradicts the option description by conveying that enabling the setting means the user has **opted out** of telemetry while that is not the case. To my understanding, enabling the setting means telemetry would be sent to Mapbox. So, we should use a better name for the setting too. My suggestion would be "Mapbox Telemetry".

**Steps to reproduce:** 
1. Open Settings
2. Scroll and tap on the "Telemetry Opt Out" option

**System logs:**
Couldn't find any relevant logs in logcat.

**Device and Android version:** 
Samsung SM-J111F running Android 5.1.1.
 
**Commons app version:** 
2.13.1.793~66f6e2e

**Comment by misaochan** [comment]
Can confirm, unable to toggle it off too on real device running Android 10.

> To my understanding, enabling the setting means telemetry would be sent to Mapbox. So, we should use a better name for the setting too. My suggestion would be "Mapbox Telemetry".

I agree, but AFAIK we are simply following Mapbox's own requirements. If we are allowed to change it, that would be great. Should probably be a separate issue though. ;)

**Comment by sivaraam** [comment]
> Should probably be a separate issue though. ;)

You're right. I opened #3946 for this. We can continue the discussion there.
