### ISSUE TITLE
Ability to show captions and descriptions in all entered languages

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#3949]
Media details currently shows only one pair of caption/description (either in the user's locale or a fallback language).

It could be useful if there was the ability to see captions and descriptions in all languages were they are available.

It would show information similar to this (probably in a more mobile-friendly form):
<img width="661" alt="Screen Shot 2020-10-06 at 08 46 45" src="https://user-images.githubusercontent.com/99590/95143763-efe06b00-07b1-11eb-9939-6a9f06512a25.png">

**Comment by borisenkotim** [comment]
I'd be willing to tackle this issue.

**Comment by nicolas-raoul** [comment]
Thanks a lot @borisenkotim it is yours :-) Please let us know about your progress every few days.

**Comment by borisenkotim** [comment]
I just realized that since this is labeled as an enhancement issue, and I have less than 5 previous pull requests for this repo, I technically don't qualify to work on this.

**Comment by nicolas-raoul** [comment]
Ah, you're right, thanks for your integrity! (same for #3951 I guess)
For now how about working on this bug instead? https://github.com/commons-app/apps-android-commons/issues/3681
Thanks a lot!

**Comment by Prince-kushwaha** [comment]
can i work

**Comment by nicolas-raoul** [comment]
@Prince-kushwaha Please focus on bugs for now, thanks! :-)

**Comment by Prince-kushwaha** [comment]
@nicolas-raoul  can i work on this

**Comment by nicolas-raoul** [comment]
@Prince-kushwaha Yes thanks :-)

**Comment by Prince-kushwaha** [comment]
@nicolas-raoul UI to show all show captions and descriptions
Tell me if improvement need 
![Screenshot_2021-04-09-14-09-03-378_com example test](https://user-images.githubusercontent.com/65972015/114153963-864a4080-993d-11eb-97f7-5924d1d50827.jpg)

**Comment by Prince-kushwaha** [comment]
@nicolas-raoul this another UI for showing all language Caption and Description 
![Screenshot_2021-04-09-17-12-35-343_com example test](https://user-images.githubusercontent.com/65972015/114175071-311b2880-9957-11eb-9f44-477162caf78b.jpg)

i thing is more better than previous UI i make it more better

Tell me if improvement need

**Comment by nicolas-raoul** [comment]
I would imagine it like this:
```
Caption: Cat
Description: Cat in Lima
V more languages V
```

After tapping on `more languages`:
```
Caption: Cat
Description: Cat in Lima
^ less languages ^
Caption (francais): Chat
Description (francais): Chat à Lima
Caption (日本語): ねこ
Description (日本語): リマでのねこ
```

**Comment by Prince-kushwaha** [comment]
@nicolas-raoul i implemented UI this to show all descriptions and caption in all  entered languages
I need the help to get all descriptions in  all entered language of image(media) using api call 
I use the` media.getDescriptions() ` to get all entered lanuage but this function not return any description
and media.getFallbackDescription() given one description in local language 
help me

![Screenshot_2021-04-10-14-18-58-090_fr free nrw commons](https://user-images.githubusercontent.com/65972015/114269825-90943980-9a26-11eb-98d2-3e94c0f3c61f.jpg)

**Comment by nicolas-raoul** [comment]
By using a network analyzer when loading https://commons.wikimedia.org/wiki/File:TianqiZhe.jpg you can see that the page gets language captions by calling the URL https://commons.wikimedia.org/wiki/Special:EntityData/M75558527.json?revision=552105075

You can just use https://commons.wikimedia.org/wiki/Special:EntityData/M75558527.json which gives the latest version which is what we want. I believe that we already have that `M75558527` identifier.

So, when the user taps "in more languages" you could call that URL and then display the results.

**Comment by Prince-kushwaha** [comment]
@nicolas-raoul problem  is  in the descriptions . descriptions is empty for all image   `"descriptions": {}`
see the descriptions in this json is empty https://commons.wikimedia.org/wiki/Special:EntityData/M75558527.json but image have descriptions  https://commons.wikimedia.org/wiki/File:TianqiZhe.jpg
How i get all descriptions for image

**Comment by nicolas-raoul** [comment]
Ah, you are right!
It is OK to only show localized captions for now.
Localized descriptions can be added in a later phase, when we have an easy API to retrieve them.

**Comment by Prince-kushwaha** [comment]
@nicolas-raoul i find another way to find descriptions for image using another the api call- https://commons.wikimedia.org/w/api.php?action=parse&page=File:Hibiscus%20syriacus%20capsule%20hoarfrost%20-20200101-RM-102111.jpg in this json `"text":{ }` contain all the html code to show page .<td class=\"description\">Contain all descriptions of image < /td>  extract code between td  and using webview to show all descriptions of image 
I implement it it work 
this is very easy way

![WhatsApp Image 2021-04-12 at 8 07 05 PM](https://user-images.githubusercontent.com/65972015/114412797-0fc27280-9bcb-11eb-9027-3dde44bf3e39.jpeg)

image link -https://commons.m.wikimedia.org/wiki/File%3AHibiscus_syriacus_capsule_hoarfrost_-20200101-RM-102111.jpg
 

**Can i implement it in this issue to show all descriptions of image ?**

**Comment by nicolas-raoul** [comment]
Yes, thanks! Please make sure that if the HTML is broken the app does not crash (and instead just shows no descriptions).
