### ISSUE TITLE
Can't find upload button anywhere!

### ISSUE THREAD

**Issue by jidanni** [commons-app/apps-android-commons#3950]
The app description says it helps his upload pictures to Commons. However no matter how I look I just can't figure out how to upload anything in it. There's just no upload button in the menu or anything, even though I'm successfully logged in.

**Comment by jidanni** [comment]
Oh, I get it. It's that blue plus button that could very well end up on an exactly same color blue background so one could hardly notice it. Perhaps around it with a white circle.
![Screenshot_20201006-122038.jpg](https://user-images.githubusercontent.com/1230959/95158534-6723f800-07ce-11eb-9352-be08b23c7b33.jpg)
I would say also put an Upload entry in the menu,  but I'm an old-timer.

**Comment by ashishkumar468** [comment]
Hi @jidanni , Thanks for the suggestion. We are having a major ui-revamp which should address your issues. We will let you know when it goes to beta.

**Comment by nicolas-raoul** [comment]
Let's merge this into #3951
