### ISSUE TITLE
Documentation for the upload button

### ISSUE THREAD

**Issue by jidanni** [commons-app/apps-android-commons#3951]
There is a 5-page tutorial that we see upon first using the app. The tutorial does not at all include telling the person to look for the big upload button on the lower right corner of the screen. It should!

**Comment by borisenkotim** [comment]
I'd like to work on this

**Comment by ashishkumar468** [comment]
It is yours @borisenkotim . Please share with us the changes you think you are going to make :)

**Comment by borisenkotim** [comment]
I would say there are multiple options to include this information in the tutorial. We could create a whole new slide with the button instructions and possible an image locating the upload button, or add this information to one of the slides of the tutorial, I was thinking the second slide. Maybe including it as another bullet point or as text above the image or at the bottom (below the bullet points)

**Comment by borisenkotim** [comment]
![Slide4AsATitle](https://user-images.githubusercontent.com/42623783/96045726-39baf800-0e27-11eb-9786-c1190520f41f.png)

**Comment by jidanni** [comment]
You need a big arrow, pointing to a big circle around the big upload button.
Using only words to describe it is not enough.

**Comment by borisenkotim** [comment]
Here is a mock-up of doing it the way you described, note this would be adding another slide to the tutorial.
![image](https://user-images.githubusercontent.com/42623783/96194920-419a9b00-0f00-11eb-9991-f10d4f956ce8.png)
If we go this route I will spend some more time on the aesthetics of the arrow and circle. And currently I am using the home page screenshot that was posted on another thread, I presume I would need to change that as well.

**Comment by jidanni** [comment]
I would make it super obvious:
![e](https://user-images.githubusercontent.com/1230959/96198218-cdefa100-0f86-11eb-8bf5-0144d0a305ac.png)
(And add thicker red circle.)
Thanks.

**Comment by borisenkotim** [comment]
Here is an update on that
![image](https://user-images.githubusercontent.com/42623783/96212267-3c067a80-0f2b-11eb-8f42-1160e7fd5fcc.png)

Technically, since this was labeled as enhancement, I don't qualify to work on this issue. However, all that's left for me is doing the same for landscape. I already added this slide to the tutorial in the code, it was a simple process.

**Comment by jidanni** [comment]
Okay, but the button itself still needs a circle added so later when it's on its own outside of the tutorial it will still contrast if it happens to be on in exactly the same color page as itself.

**Comment by Prince-kushwaha** [comment]
@nicolas-raoul i want to work on this issue

**Comment by nicolas-raoul** [comment]
@Prince-kushwaha Sorry this is not marked as `bug`. There are many bugs left to choose from :-)

**Comment by Prince-kushwaha** [comment]
@nicolas-raoul accounding to contribution guide how make more than 5 merged pull requests
 is work on enhancement i made more than 10 merged pull request so can i work on this issue

**Comment by Prince-kushwaha** [comment]
@nicolas-raoul accounding to contribution guide who make more than 5 merged pull requests
is work on enhancement i made more than 10 merged pull request so can i work on this issue

**Comment by nicolas-raoul** [comment]
Ah sorry, congratulations @Prince-kushwaha ! :-)
For enhancements, agreements from core developers is needed.
This enhancement has actually not reached that stage.

The argument I would have against are:
- It adds to the burden of **maintenance**, as we would have to update the screenshots every time the user interface changes (it changes quite often), preferably in the user's locale (as for instance for Persian speakers the + button is on the left).
- It dilutes the super-important message of the tutorial, which is about **Commons policy** (copyright, and what kind of pictures are expected). The tutorial is not meant to explain anything technical (features, buttons, UI) as it would make it too long.

**Comment by Prince-kushwaha** [comment]
@nicolas-raoul thanks for explaining

**Comment by jidanni** [comment]
OK, but at least mention with words "to upload, press the upload button, which is probably the biggest button on the screen".

**Comment by nicolas-raoul** [comment]
I think the upload button explanation should be written as a new top section in the user guide: https://commons-app.github.io/docs.html

**Comment by Rishavgupta12345** [comment]
@nicolas-raoul I would like to work on this issue but can you sum up and say me what exactly I have to do in this issue?

**Comment by nicolas-raoul** [comment]
https://commons-app.github.io/#usage now has full instructions on how to perform an upload.
