### ISSUE TITLE
Participate in Hactober?

### ISSUE THREAD

**Issue by sivaraam** [commons-app/apps-android-commons#3956]
[Hacktober](https://hacktoberfest.digitalocean.com/) is in progress and this year they've made it [opt-in](https://hacktoberfest.digitalocean.com/hacktoberfest-update) so interested projects have to add a 'hacktoberfest' repository topic.

Should we participate in Hactober by adding the topic?

**Comment by misaochan** [comment]
@sivaraam that looks cool! :) Would love to participate, the only thing is that this is a very busy time for the grantees. Would you or other volunteers be OK with handling the reviewing/testing of the PRs for Hacktober? If you are then I can add the topic.

**Comment by ashishkumar468** [comment]
Sounds like a nice idea to me too :)

**Comment by sivaraam** [comment]
> Would you or other volunteers be OK with handling the reviewing/testing of the PRs for Hacktober?

Sure! I'll do the best I can on helping with the PRs. 🙂

**Comment by misaochan** [comment]
Thanks @sivaraam , I have added the topic and the label. :) Please let me know if anything else is needed for us to join.

**Comment by sivaraam** [comment]
We're long past Hacktober now. :)

**Comment by sivaraam** [comment]
I think we could remove the 'hacktoberfest' tag from the repository as it doesn't seem necessary any more 🤔

**Comment by Rishavgupta12345** [comment]
@nicolas-raoul this issue is useless now we can close this
