### ISSUE TITLE
Retry overwrites pic of same set with same title

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#3960]
1) I uploaded a set of 2 pictures of a butterfly (top and side views), the top view of the butterfly failed, and the side view of the butterfly succeeded.

2) I pushed "Retry", and there was no error.

3) The app gallery was only showing the side view picture, so I checked my uploads at https://commons.wikimedia.org/w/index.php?title=Special:ListFiles&user=Syced and saw that the top view got overwritten. See the "File history" section at https://commons.wikimedia.org/wiki/File:White-black-orange_butterfly_at_Institute_for_Nature_Study.jpg

That was with the branch for https://github.com/commons-app/apps-android-commons/pull/3916 (but might be same in master)

I had given the same title to both pics. Usually in such case the app adds a suffix to the second pics.

![IMG_20201011_234739](https://user-images.githubusercontent.com/99590/95682089-63550300-0c1e-11eb-98d3-6bf8bae5643b.jpg)

**Comment by ashishkumar468** [comment]
@nicolas-raoul  Did this happen in limited connection mode or in general?

**Comment by nicolas-raoul** [comment]
My connection is slow, but I did not change any setting intentionally, so general I guess? How to see what mode I am using?

**Comment by misaochan** [comment]
If you were on a branch that had limited connection mode implemented, there would be a toggle on the upper right. Since there doesn't seem to be one in the screenshot, it appears to be general @ashishkumar468

**Comment by nicolas-raoul** [comment]
I haven't observed this in months
