### ISSUE TITLE
But we may already be a Beta Tester

### ISSUE THREAD

**Issue by jidanni** [commons-app/apps-android-commons#3968]
In Settings > Feedback section:
`Become a Beta Tester...`
But we may already be a Beta Tester.
So the wording should say:
`Become a Beta Tester (if not one already)....`
Or else more fancy detection should be enabled.

**Comment by nicolas-raoul** [comment]
I actually don't see this in the dev branch I use... maybe the UI has changed and this is not needed anymore?

This is actually a good first issue for anyone who wants to take it, the first tasks is to check whether the UI includes that string or not, in both master and the maintenance branch. Thanks!

**Comment by jidanni** [comment]
Maybe also related to #3976.

**Comment by Mugurell** [comment]
A potential issue with the above string recommendation -  `Become a Beta Tester (if not one already)` is that on some devices it could not entirely fit on one row.
Maybe this important note could be added to the description? (`Opt-in to..`)

**Comment by jidanni** [comment]
OH, AND... do mention "alpha tester" too!
Because currently beta=non-beta!!
And it will take the user a long time to figure out
1.  beta=non-beta, and even longer, if ever, to stumble upon the fact that:
2. There is also a little mentioned alpha.

**Comment by gouri-panda** [comment]
I want to work on this issue.

**Comment by gouri-panda** [comment]
@nicolas-raoul Should I start working on this issue? and also I need descriptions.

**Comment by misaochan** [comment]
I don't think there's any need to mention alpha in the app, as it's not possible to opt in to alpha solely within the app (it requires signing up to our google group). Alpha is generally for users who are already very familiar with our project and have looked us up on GitHub. It can be unstable so I don't feel comfortable recommending users to be alpha testers in-app.

@gouri-panda It seems like there is a PR up at #3984 ? @madisoncfallin are you interested in making the requested changes to your PR?

@gouri-panda If you still are looking for an issue to work on, anything with the "bug" label can easily be assigned to you too. :)

**Comment by jidanni** [comment]
I would say do like
https://www.chromium.org/getting-involved/dev-channel
Full disclosure of all four channels to the testing community, right from the start.

**Comment by misaochan** [comment]
We have a wiki for the same purpose: https://github.com/commons-app/commons-app-documentation/blob/master/android/Volunteers-welcome!.md

**Comment by jidanni** [comment]
OK, but
1. Starting as a user looking at the wording on #3984 
2. There is no path for them to ever reach [that wiki page](https://github.com/commons-app/commons-app-documentation/blob/master/android/Volunteers-welcome!.md).

**Comment by AdityaArunSharma** [comment]
Hey! @misaochan @jidanni  @nicolas-raoul 
I am a begineer in open source but have little experience in andriod development. 
Can I work in this good first issue? I am very eager to start with open source.

**Comment by nicolas-raoul** [comment]
@AdityaArunSharma The "good first issue" was about searching strings and it is done already, I just forgot to remove the tag, sorry for the confusion! Anyway welcome to the team, glad to have you on board ! :-) Would you mind finding another issue at https://github.com/commons-app/apps-android-commons/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+no%3Aassignee+-label%3Aassigned+-label%3Adebated+label%3Abug ? Thanks!

**Comment by Rishavgupta12345** [comment]
@nicolas-raoul can you please tell me what actually we have to do in this issue? is this issue even relevant to be open?

**Comment by nicolas-raoul** [comment]
Beta versioning is not used as much as it used to be in the past, so no need to spend time on this now.
