### ISSUE TITLE
Recent Upload Limit not remembered

### ISSUE THREAD

**Issue by jidanni** [commons-app/apps-android-commons#3969]
1. In Settings, change Recent Upload Limit from 100 to 10.
2. Close the app.
1. Launch the app again.
1. Check the limit again.

It is back to 100.

**Comment by jidanni** [comment]
Yes, other settings are successfully saved. Just not this setting.

**Comment by nicolas-raoul** [comment]
Could you please try the alpha? I think the "Recent Upload Limit" setting does not exist anymore, only a few images are loaded, and only if you scroll down, more are loaded. If I understand correctly.

**Comment by jidanni** [comment]
I don't know about any 'alpha'. All I know is #3976.

**Comment by sivaraam** [comment]
> I don't know about any 'alpha'.

@jidanni You can find information about the alpha and how to install it in the following page: https://github.com/commons-app/commons-app-documentation/blob/master/android/Volunteers-welcome!.md#testers

**Comment by Saral-code** [comment]
I think I can fix this issue.
Can I work on this?

**Comment by nicolas-raoul** [comment]
Thanks Saral for proposing your help, but actually this "Recent Upload Limit" does not exist anymore, now there is no limit :-)
Sorry that I had forgotten to close this issue.
