### ISSUE TITLE
"Wikimedia Commons" as a trademark must remain in English

### ISSUE THREAD

**Issue by amire80** [commons-app/apps-android-commons#397]
Hi,

I was translating this app at translatewiki.net and noticed the "about license" string, which says:
```
Wikimedia Commons and its logo are trademarks of the Wikimedia Foundation and are used with the permission of the Wikimedia Foundation.
```

The problem with this is that "Wikimedia Commons" has pretty different names in some languages, for example _Vikisklad_ (Викисклад) in Russian or _Vikishituf_ (ויקישיתוף) in Hebrew, but only the original English name is an actual trademark.

I added a note about it to the message documentation (qq), but to avoid confusing translators, it shouldn't appear in the string at all, but be inserted using a parameter (like %1$s).

Thank you!

**Comment by whym** [comment]
Maybe the name should also be quoted?

    "%1$s" and its logo are ...

**Comment by anukarsh1** [comment]
I think this issue should be closed, shouldn't it?

**Comment by amire80** [comment]
Yes, it can be closed. The message is always auto-inserted in English, [set as ignored in translatewiki.net](https://gerrit.wikimedia.org/r/#/c/366842/), and in 815465b the existing translations were removed from the source.
