### ISSUE TITLE
Losing filled data when screen rotate

### ISSUE THREAD

**Issue by Prince-kushwaha** [commons-app/apps-android-commons#3973]
**Summary:** 

In signup  form filled information is lossed when screen is rotated 

**Steps to reproduce:** 
Go to Login activity 
click on signup
Fill signup  form  then rotated the screen 
  
What did you expect the app to do, and what did you see instead?
In signup  form filled information is not lossed when screen is rotated 

**Device and Android version:**
Device :Redmi Y3;

**Screen-shots:** 

![WhatsApp Video 2020-10-18 at 8 04 15 PM (1)](https://user-images.githubusercontent.com/65972015/96371708-b7149e80-1180-11eb-95de-d7cc3ebfcdca.gif)

**Would you like to work on the issue?**
Yes

Please let us know whether you want to fix the issue by yourself. If not, anyone can get the issue assigned to them.
i want to fix this issue

**Comment by Prince-kushwaha** [comment]
i am working on this issue

**Comment by Prince-kushwaha** [comment]
I want to work on this issue 
assigned me

**Comment by nicolas-raoul** [comment]
It is yours, thanks! Please let us know about your progress every few days :-)

**Comment by Prince-kushwaha** [comment]
ok
