### ISSUE TITLE
Add Documentation for Sending Thanks & Reviewing Content

### ISSUE THREAD

**Issue by rebeccachild74** [commons-app/apps-android-commons#3974]
**Summary:** 

The [commons-app documentation](https://github.com/commons-app/commons-app-documentation/blob/master/android/README.md) does not include any information about the review feature or about sending thanks. We should update it to help new developers get familiar with the app and increase the amount of people reviewing content through it.

[#3361](https://github.com/commons-app/apps-android-commons/issues/3361) is open, but it is concerned with adding more information to reviewing content within the app.

**Would you like to work on the issue?**
Yes. Do I need to create an issue on the documentation repository?

**Comment by nicolas-raoul** [comment]
Thanks!
Documentation issues should ideally be on the tracker over there, but now that this one exists, let's use it, it's OK :-)

**Comment by rebeccachild74** [comment]
I've added a PR to the documentation repository: [#29](https://github.com/commons-app/commons-app-documentation/pull/29).
Please check it out

**Comment by KishkinJ10** [comment]
can i work on this i am a beginner it will help me . can you guide me?

**Comment by nicolas-raoul** [comment]
@KishkinJ10 
Sorry, this task was completed already by Rebecca, I had forgotten to close it.
Apologies and please find a good issue for you using [this search link](https://github.com/commons-app/apps-android-commons/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+no%3Aassignee+-label%3Aassigned+-label%3Adebated+label%3Abug).
Thanks for your interest!
