### ISSUE TITLE
F-Droid logo is much bigger that that for Google Play

### ISSUE THREAD

**Issue by jidanni** [commons-app/apps-android-commons#3975]
On https://github.com/commons-app/apps-android-commons the F-Droid logo is much bigger that that for Google Play.

![1710-1](https://user-images.githubusercontent.com/1230959/96584476-da6e5380-1310-11eb-9566-0005aa21d5da.jpg)

**Comment by jidanni** [comment]
Compare https://commons-app.github.io/ where they are equal size.

**Comment by sivaraam** [comment]
Looks like F-droid increased the size of their logo 🤔 

The website is not affected as it uses a stored version of the logo rather than fetching it directly from the F-droid website.

**Comment by sivaraam** [comment]
> ... the F-droid logo in the README file is from [Commons](https://upload.wikimedia.org/wikipedia/commons/9/96/%22Get_it_on_F-droid%22_Badge.png)

The file in common has a newer revision that removes the surrounding blank space thus resulting in it being rendered bigger than the play store icon. Linking to the older version which has the surrounding blank space would fix the issue.
