### ISSUE TITLE
Hitting "My Rank" button from a list position below your rank on leaderboard takes you to the person ranked below you.

### ISSUE THREAD

**Issue by rebeccachild74** [commons-app/apps-android-commons#3980]
**Summary:** 

When you view the leaderboard, it will default to show the top users in the filtered results. If you select the "My Rank" button from a position in the list above your rank,  it will scroll the list down so that your rank is right above the "My Rank" button, so one from the bottom. If you select the "My Rank" button from a position in the list below your rank, it will scroll the list up to the rank immediately below your rank, so your user rank is not on the screen.

**Steps to reproduce:** 

Log in to app, go to your profile and the leaderboard tab. Then scroll below the your user's rank so that your rank is not on the screen and select the my rank button. 

**Would you like to work on the issue?**

Yes, I have implemented a fix for this but need to add tests.

**Comment by madhurgupta10** [comment]
Hello, @rebeccachild74 I ideal behaviour should be that when **A User with rank X** taps the **My Rank** button then we should scroll to **X+1** position so that **My Rank** button is just below the actual rank of the user.
