### ISSUE TITLE
Starting Uploads notification not dismissing

### ISSUE THREAD

**Issue by madhurgupta10** [commons-app/apps-android-commons#3981]
**Summary:** 
Starting Uploads notification not dismissing.

I installed the app on a new device and the notification was automatically triggered even when there were no pending uploads and I am unable to dismiss it.

**Device and Android version:** 
Xiaomi A2 API 29

**Commons app version:** 
2.13.1-debug-master-409e43c3a prodDebug latest master

**Screen-shots:** 
![Screenshot_20201022-145328](https://user-images.githubusercontent.com/30932899/96852859-4965bc80-1477-11eb-8c75-35ddbd47a64d.jpg)

**Comment by sivaraam** [comment]
I'm experiencing this for quite some time now. Currently I can reproduce this using v2.13.1.809~409e43c of the app that I installed from the Play store alpha channel on a Android 5.1.1 device. I have to force stop the app to make the notification go away. I'm suspecting this was introduced after the introduction of the limited-network mode option in PR #3934.

**Comment by madhurgupta10** [comment]
@sivaraam same behaviour for me, the only way to dismiss the notification is by force stopping the app.

Pinging @maskaravivek for discussion on this issue.

**Comment by madhurgupta10** [comment]
@ashishkumar0207 @sivaraam Unfortunately the issue still exists for me (2.13.1-debug-master~c793827c5) when I toggle Limited Connection Mode.

**Comment by nicolas-raoul** [comment]
I uninstalled then reinstalled the app (alpha/master) yesterday and had this notification run for hours, even though I did not enable Limited Connection mode.

**Comment by misaochan** [comment]
Same here, it also started happening much more frequently for me on the current master.

**Comment by Prince-kushwaha** [comment]
This issue is not solved in the master branch 
I want to work on this issue

**Comment by ashishkumar468** [comment]
@Prince-kushwaha Sure, go ahead, please post updates over here :)

**Comment by Prince-kushwaha** [comment]
assigness me for this issue

**Comment by Prince-kushwaha** [comment]
@ashishkumar0207 can  review my pull request #4041 and #4028

**Comment by misaochan** [comment]
I merged your other PRs. :) Please feel free to work on this now @Prince-kushwaha .

**Comment by ashishkumar468** [comment]
Hi @Prince-kushwaha  are you still working on this?

**Comment by Prince-kushwaha** [comment]
Yes

**Comment by Prince-kushwaha** [comment]
Make PR in few days

**Comment by ashishkumar468** [comment]
@Prince-kushwaha Thanks for the update, how are you planning to approach the issue?

**Comment by Prince-kushwaha** [comment]
* fixes automatically triggered of Upload then their is no Pending of uploads of media
* fixes notification that is not dismissing

**Comment by Prince-kushwaha** [comment]
Not able to solve this issue completly

**Comment by nicolas-raoul** [comment]
@Prince-kushwaha No problem, just commit and push your code into a branch on your repository and link to it here so that others can have a look :-) Also please feel free to share here any tips or things you have noticed. Thanks for your work!

**Comment by Prince-kushwaha** [comment]
Any one explain me how Uploading of media work in this app

**Comment by Prince-kushwaha** [comment]
on  install latest branch
there is many bugs regarding uploads

**Comment by ashishkumar468** [comment]
Hi @Prince-kushwaha , are you still working on this one?

**Comment by Prince-kushwaha** [comment]
No

**Comment by Prince-kushwaha** [comment]
Yes

**Comment by misaochan** [comment]
@Prince-kushwaha could you let us know specifically what you have tried and where you are stuck, please? Unfortunately the questions you are asking are very general and I'm not sure how we can help you with them. :/
