### ISSUE TITLE
We see "starting uploads" upon upgrade to Alpha

### ISSUE THREAD

**Issue by jidanni** [commons-app/apps-android-commons#3985]
We see "starting uploads" upon upgrade to Alpha, and it never stops. However we don't have any uploads scheduled. So I don't know what it's doing.
Version 811.

**Comment by ashishkumar468** [comment]
Hi @jidanni an issue already exists for this, also I have already raised a PR for the fix, should be merged this, closing this as duplicate

**Comment by jidanni** [comment]
Okay. That's good. However what should I do today to stop it?
Directly use Android's Force stop?

**Comment by jidanni** [comment]
Okay, Force stop worked. Unless one launches the app again.

**Comment by ashishkumar468** [comment]
Closing this as duplicate

**Comment by jidanni** [comment]
(OK, but next time do please add the link to what the duplicate is of.)
