### ISSUE TITLE
Limited connection mode switch  needs a label

### ISSUE THREAD

**Issue by jidanni** [commons-app/apps-android-commons#3986]
Limited connection mode switch  needs a label. Yes, I know there's no way to put a label there. However I challenge you to figure out what this switch is for without forcing yourself to toggle it to find out. What if there was a fire alarm button and nobody could figure out what the purpose of it was without having to push it to find out?
Version 811.

**Comment by misaochan** [comment]
If you can see the limited connection mode, you must be testing master/alpha, not a release build. Yes, it needs a label, and it will have one. The UI in master is still in progress. :)

**Comment by jidanni** [comment]
> If you can see the limited connection mode, you must be testing master/alpha, not a release build.

(Yes. I hope I am still filing these in the right place here on GitHub.)

**Comment by nicolas-raoul** [comment]
#2843 has been closed 4 days ago, so I think it is now fair to report any big problem :-)
Yes, this GitHub issue tracker is the right place for alpha too, but let's keep in mind that alpha is a work in progress ;-)

**Comment by jidanni** [comment]
OK I will try to get used to the "cloud".

**Comment by sivaraam** [comment]
You'll see an _actual_ label (briefly) for the switch when long pressing it. There is still one thing that could be improved about it, though. Currently it says "Limited Connection" which feels blunt to me. So, we could re-phrase it a little. I would suggest using "Limited connection mode".

**Comment by misaochan** [comment]
I'm good with changing the text to "Limited connection mode".
