### ISSUE TITLE
Peer review picture blank in limited connection mode

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#3994]
Limited mode should either remove peer review from the menu, or load the pic under review (it is not that big)
![Screenshot_20201027-171008_Commons](https://user-images.githubusercontent.com/99590/97275560-69332100-1879-11eb-8e5e-0370d6866361.jpg)

**Comment by Prince-kushwaha** [comment]
can i work on this issue

**Comment by Prince-kushwaha** [comment]
@nicolas-raoul  can i work on this issue

**Comment by Ankita13-code** [comment]
@nicolas-raoul I'm new to contributing to wikimedia and would love to take this up as my first issue. Can this issue be assigned to me?

**Comment by nicolas-raoul** [comment]
Prince, Ankita: This issue is quite hard, it will require some policy decisions. I would suggest finding another issue at https://github.com/commons-app/apps-android-commons/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+no%3Aassignee+-label%3Aassigned+-label%3Adebated+label%3Abug ? Thanks!

**Comment by misaochan** [comment]
I think removing Peer Review from the menu during limited connection mode would be the best solution, what do you think @sivaraam @nicolas-raoul ?

**Comment by nicolas-raoul** [comment]
In my personal opinion, loading a miniature of 1 picture (I mean 1 by 1) is OK in limited connection, especially since opening Peer Review is voluntary.
But I totally agree with removing the menu entry until someone wants to implement that :-)

**Comment by mrudultora** [comment]
@nicolas-raoul Can I work on this?

**Comment by nicolas-raoul** [comment]
@mrudultora It is yours, thanks!
What approach will you take?

**Comment by mrudultora** [comment]
@nicolas-raoul I am removing peer review from bottom sheet menu if the user is in limited connection mode. Is it fine ?

**Comment by nicolas-raoul** [comment]
@mrudultora Sounds good :-)
