### ISSUE TITLE
Progress Bar Visibility change with Orientation Change and login process terminated

### ISSUE THREAD

**Issue by Prince-kushwaha** [commons-app/apps-android-commons#4001]
**Summary:**

In Login activity when I clicked login button Progress Bar visible when I rotated the screen Progress bar invisible 
and login process of user stop or terminated  

**What did you expect the app to do, and what did you see instead?**
Maintaining Progress Bar Visibility  and prevent stop of login process with Orientation Change

**Steps to reproduce:**
 Go to Login activity
 Filled the information
 Click on the login button and change the rotated the screen

**Device and Android version:** 
Device :Redmi Y3;

**Commons app version:** 
 2.13.2
**Screen-shots:** 
![20201029_084511](https://user-images.githubusercontent.com/65972015/97521268-385f0300-19c3-11eb-9ccd-2198581ebba7.gif)

**Would you like to work on the issue?**
**YES**
Please let us know whether you want to fix the issue by yourself. If not, anyone can get the issue assigned to them.
**YES I want to fix this**

**Comment by Prince-kushwaha** [comment]
i am working on this issue

**Comment by Prince-kushwaha** [comment]
I want to work on this issue
assigned me

**Comment by madhurgupta10** [comment]
@Prince-kushwaha feel free to create a PR for this issue.

**Comment by Prince-kushwaha** [comment]
ok
