### ISSUE TITLE
Screen flashing

### ISSUE THREAD

**Issue by jidanni** [commons-app/apps-android-commons#4003]
2.13.1.818~9d99c25

Does anybody notice the screen flashing a little?

 Seems to start after you queue a picture, and doesn't even stop even after you finally upload it.

Flashes about once per second.

**Comment by jidanni** [comment]
Sure, WAI perhaps. However many users will take their cell phones to the repair shop asking if there's something wrong with their battery.

**Comment by neslihanturan** [comment]
It happens sometimes to me too @jidanni , thanks for reporting it

**Comment by nicolas-raoul** [comment]
It happens to me all the time too.
It might or might not be related to #3959.

**Comment by gouri-panda** [comment]
@nicolas-raoul  @neslihanturan  @jidanni Can you give some more details on how to reproduce this issue?

**Comment by nicolas-raoul** [comment]
@gouri-panda Just install the app and open it.
I guess it only happens with accounts that have uploaded already 10 or more pictures. Feel free to upload 10 or 20 of these pictures, using their filename (without the extension) as a title and "Tokyo" as category: https://drive.google.com/drive/u/1/folders/1T5wfM16qb78XCvnf1Zunww4neg8BXJj6

**Comment by 4D17Y4** [comment]
Hey, @nicolas-raoul  
Can I work on this issue ?

**Comment by nicolas-raoul** [comment]
@4D17Y4 Yes, thanks :-)
Can you see the issue happening? You might have to upload a few pictures before that happens, please see my comment above.

**Comment by 4D17Y4** [comment]
Yes, I can see it.
@nicolas-raoul 

There are two thinks playing there part here.
First one is the recycler view whose default animation on uploading is making the screen flash.
Secondly its the SimpleDraweeView used for image which flickers on upload.

So, I was wondering if we want no flickering at all or only the image to flicker on upload.


According to me the flicker on image looks good, suggesting that the image is being loaded.

What to go for ?

**Comment by nicolas-raoul** [comment]
Thanks for the investigation and for confirming, great way to proceed!

We want no flicker at all :-)
The progress bar is there to indicate that the image is being uploaded.

**Comment by nicolas-raoul** [comment]
@4D17Y4 Thousands of thanks, the scrolling is so nice now! :-)
