### ISSUE TITLE
"(For all images in set)" appears even when I am not uploading a set but rather a single image

### ISSUE THREAD

**Issue by jidanni** [commons-app/apps-android-commons#4005]
One of the steps during upload asks us:
"(for all images in set)..."

Well, in this certain case there was only one media item. Please detect that and have the wording reflect that. Otherwise the user gets very worried that he's about to upload a big bunch of stuff that he didn't intend to.

In fact, showing an exact count, would make the user confident of what is about to happen.
2.13.1.818~9d99c25

**Comment by nicolas-raoul** [comment]
I agree, we should hide the "(For all images in set)" when it is not a set.

**Comment by gouri-panda** [comment]
@nicolas-raoul I want to work on this issue.

**Comment by gouri-panda** [comment]
What should we call him if we upload one image or multiple images?

**Comment by nicolas-raoul** [comment]
Thanks @gouri-panda !
If you need a variable that says whether we upload one image or multiple images, how about a boolean called `set`, or maybe `isSet`? Does that answer your question, or did I misunderstand?

**Comment by gouri-panda** [comment]
@nicolas-raoul   I'm thinking about what should we display to users on the text?

**Comment by gouri-panda** [comment]
@nicolas-raoul  I was trying to say if the user will select one image what should we display instead of "For all images in set"? Similarly what about multiple images.

**Comment by nicolas-raoul** [comment]
Multiple images -> Current behavior, do not change anything
One image -> Do not display the label `(For all images in set)`

**Comment by Prince-kushwaha** [comment]
@nicolas-raoul  can i work on this issue

**Comment by nicolas-raoul** [comment]
@Prince-kushwaha I just asked Gouri-panda to rebase and will probably merge as soon as it is done :-)
