### ISSUE TITLE
Progress bar lacks appropriate contrast

### ISSUE THREAD

**Issue by jidanni** [commons-app/apps-android-commons#4013]
Have a look at the progress bar when uploading an image.  You will see it is blue on dark blue. In other words very hard to see.
2.13.1.823~d4b73fa

**Comment by misaochan** [comment]
This will be changed in the v3.0 UI. :)

**Comment by nicolas-raoul** [comment]
I confirm, in the new UI the bar is very visible :-)
I will close this as fixed.
Thanks!
