### ISSUE TITLE
New UI - Nearby list does not update when a new area is searched

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#4014]
**Summary:** 

The Nearby list should update when "Search this area" is tapped in a new location. Currently it just shows the old list, although the map does update.

**Steps to reproduce:** 

Nearby > move to different area > "Search this area" > select list icon at top right

**Device and Android version:** 

Samsung Galaxy S20FE, Android 10
 
**Commons app version:** 

master (after merging new UI #3891 )

**Comment by neslihanturan** [comment]
Hi Josephine, I investigated this issue today. DiffUtils does not do its job for some reason, will look closer tomorrow. However, I think this issue is not related with latest changes.

**Comment by misaochan** [comment]
Thanks for the investigation @neslihanturan ! It's good to know that it's not related, however we still have to fix it before releasing v3.0 as it's a pretty major bug.
