### ISSUE TITLE
Map is black after uploading from Nearby

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#4015]
**Summary:** 

After uploading directly from Nearby, when I return to the Nearby fragment, the map is black

**Steps to reproduce:** 

Upload a pic via Nearby > complete the process > look at Nearby

**Device and Android version:** 

Samsung Galaxy S20FE, Android 10
 
**Commons app version:** 

master after merging #3891 

**Screen-shots:** 

![Screenshot_20201107-015943_Commons](https://user-images.githubusercontent.com/3611199/98389248-8351d800-209f-11eb-853f-aa9156c3b4b9.jpg)

**Comment by nicolas-raoul** [comment]
Seems like it also happens without uploading via Nearby.
Yesterday I uninstalled the app, installed alpha instead, uploaded a picture not from Nearby, opened Nearby, left it. This morning when I came back to Nearby it was black.

**Comment by nicolas-raoul** [comment]
The easiest way I have found to reproduce the problem:

1. Open Nearby
2. Either press "Home" or switch to a different app
3. Come back to the Commons app
4. Map is now black
