### ISSUE TITLE
0,0 coordinates added after uploading

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#4016]
**Summary:** 

The app adds false coordinates (always 0,0) to recent uploads. Not sure when it started but I just noticed it. See https://commons.wikimedia.org/wiki/File:Catseye_Bay.jpg for instance

**Steps to reproduce:** 

Upload a picture that has coordinates > check coordinates on Commons

**Device and Android version:** 

Samsung Galaxy S20FE, Android 10
 
**Commons app version:** 

master

**Comment by sivaraam** [comment]
This looks like a duplicate of #3684

**Comment by misaochan** [comment]
Hmm, in my case the pic had GPS coordinates, though. But good point, it probably stems from the same root cause. I will close this and we can discuss it there.
