### ISSUE TITLE
"Uploaded by" bugged in Explore

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#4018]
**Summary:** 

The "uploaded by" field in Explore frequently displays gibberish or is empty.

**Steps to reproduce:** 

Go to Explore, look at "uploaded by"

**Device and Android version:** 

Samsung Galaxy S20FE, Android 10

**Commons app version:** 

master

**Screen-shots:** 

![Screenshot_20201107-023255_Commons](https://user-images.githubusercontent.com/3611199/98393384-edb94700-20a4-11eb-83ea-caed69eea488.jpg)

**Comment by sivaraam** [comment]
This looks related to #3341 for which a PR is already up (#3714). It just needs a bit more tweaking.

**Comment by misaochan** [comment]
Thanks for letting me know @sivaraam ! That PR is from April though, and there have been a lot of changes to the codebase since then. I wonder if it might just be easier to start from scratch than to resolve so many conflicts?

**Comment by sivaraam** [comment]
> I wonder if it might just be easier to start from scratch than to resolve so many conflicts?

Yeah. That might indeed be better (or) a person could just try rebasing the PR branch over `master` in case that could be easily done without much conflicts. Otherwise, doing the change from scratch using the PR as a reference would indeed be better.
