### ISSUE TITLE
Memory leaks when resuming and pausing

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#4019]
**Summary:** 

Memory leaks found when resuming and pausing uploads

**Steps to reproduce:** 

Install LeakCanary, pull #4011 , upload a pic, pause 

**Device and Android version:** 

Samsung Galaxy S20FE, Android 10
 
**Commons app version:** 

#4011

**Comment by maskaravivek** [comment]
@misaochan Can you share a screenshot of the leak info.
