### ISSUE TITLE
"Depictions" is a word not seen in the Upload Wizard.

### ISSUE THREAD

**Issue by jidanni** [commons-app/apps-android-commons#4021]
"Depict(ions)" is a word not seen in the Upload Wizard.
![Screenshot_20201106-124530_1](https://user-images.githubusercontent.com/1230959/98434427-54248080-210a-11eb-8ef2-9cb85667f9e7.jpg)
Please use the same vocabulary as seen in the Upload Wizard. At least make sure you use words that are seen at least once in the Upload Wizard.
2.13.1.825~71d200e

**Comment by misaochan** [comment]
It does exist in the Upload Wizard:

![depicts](https://user-images.githubusercontent.com/3611199/98525442-30a53580-22c4-11eb-8fb1-aca3b058d058.png)

There will be a tooltip added soon before we release 3.0.

With all due respect @jidanni , do you think that maybe the beta might be more suited for you? ;)

**Comment by jidanni** [comment]
(I do not see it and I am already at the
![14375-0](https://user-images.githubusercontent.com/1230959/98641592-fccf1c00-2366-11eb-8dc1-07393bd83e37.jpg)
step.
To proceed further I must click "Publish files", which I dare not do with just a test image.
Therefore I'll have to take your word for it.)

**Comment by nicolas-raoul** [comment]
The Upload Wizard has that step in "Add data".
I encourage you to try it by first transferring a picture from phone to PC, or using Upload Wizard in a mobile browser (not easy).
I will close this for now.

**Comment by jidanni** [comment]
But does that mean
- The app does this step **before** the user "Publishes the file" (hits the button that actually makes the file public online), but:
- The website does this step **after** ?

If so, bad!
