### ISSUE TITLE
 Words cut off

### ISSUE THREAD

**Issue by jidanni** [commons-app/apps-android-commons#4026]
Words cut off:
![Screenshot_20201110-092949_1](https://user-images.githubusercontent.com/1230959/98616417-ba421b00-2337-11eb-84fb-dd5b5a34077c.jpg)
2.13.1.827~1baea1e

**Comment by nicolas-raoul** [comment]
Indeed! The label should be made multiline to wrap when needed.

**Comment by Prince-kushwaha** [comment]
I want to work on this issue

**Comment by Prince-kushwaha** [comment]
assign me this issue

**Comment by misaochan** [comment]
@Prince-kushwaha please feel free to work on it, thanks!

**Comment by Prince-kushwaha** [comment]
ok

**Comment by Prince-kushwaha** [comment]
this issue is solved in latest version 2.13.2 ~757c7b008

**Comment by neslihanturan** [comment]
Thanks for debugging it @Prince-kushwaha

**Comment by sivaraam** [comment]
Re-opening this as I could still observe the issue in the latest master (2ed5a74b4d24f80e8f24c2cb642f457e953e5b28). I believe the truncation depends on the screen size. So, to observe this it's best to try testing in a smaller screen device. For completeness, I observe this in a 4.2" screen device.

**Comment by Saral-code** [comment]
I want to work on this issue. I think I can fix that. Assign me this issue.
Thank You.

**Comment by sivaraam** [comment]
Sure @Saral-code ! Feel free to work on it and let us know how it goes :)

**Comment by Prince-kushwaha** [comment]
but i work on this issue

**Comment by Saral-code** [comment]
@Prince-kushwaha You can continue working and i ll also try to correct it. No problem.

**Comment by Prince-kushwaha** [comment]
ok

**Comment by neslihanturan** [comment]
Actually we don't assign the same issue to 2 people. We don't want to waste you efforts. 

@Prince-kushwaha you said you can't replicate the issue, right? It this still the case? 

@Saral-code , if @Prince-kushwaha is still willing to work on the issue, please pick another issue for yourself. 

Thanks both for your interest:)

**Comment by Saral-code** [comment]
Ok then , i m also facing issue in running Android studio in my laptop.
See ya

**Comment by Prince-kushwaha** [comment]
Anyone review my pull request #4041 and #4028
