### ISSUE TITLE
Beta testing?

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#403]
Now that we have >2000 active installs, I'm wondering if we should consider some form of beta testing to reduce the chances of us pushing broken code in a release. What do you guys think, would it be useful or should we not bother until we have more active users? If it's a good idea, how should the beta testing be carried out?

**Comment by nicolas-raoul** [comment]
Good idea!
And possibly set Github to push to beta at every commit to master:
https://github.com/codepath/android_guides/wiki/Automating-Publishing-to-the-Play-Store

**Comment by misaochan** [comment]
@nicolas-raoul so the beta on Google Play will technically be a separate app, right? Do we need to get WMF permission to do so?

**Comment by nicolas-raoul** [comment]
Google Play can have several versions of the same app (release/beta/alpha).
No need to have several apps.
People who subscribe to a special Google Group get the betas.

**Comment by misaochan** [comment]
Great, thanks. Will try to set it up ASAP.

**Comment by tobias47n9e** [comment]
IRC Cloud shows it like this in the settings which I think is very transparent. It then routes you to a Google login where you can switch to the Beta testing. How is this done for FDroid?

![screenshot_2017-03-07-17-14-35](https://cloud.githubusercontent.com/assets/6953323/23671065/35a803fa-036a-11e7-9159-9a4c4eb2245b.png)

**Comment by misaochan** [comment]
What do we want to use as the feedback channel for our beta? I was initially thinking they could just open issues here with BETA in the title (and we could add a tag), but it would get unwieldy pretty quickly.

What other options are there?

**Comment by misaochan** [comment]
Also, I can't publish an APK in beta with the same version number as the release APK. Ideally we would just always push to beta and then switch the same APK to release once it's proven to be stable, but that wouldn't always be feasible. E.g. if we have a hotfix that really needs to go straight to release. Or if we need to make changes to the beta, and then we want to push a release without having anything new that needs to go to beta yet. Seems like there'd be a lot of superfluous version numbers just to cater to the "no two APKs with same version number" rule in Google Play?

**Comment by nicolas-raoul** [comment]
Reporting here is the best, I think.
Some reported issue will probably be found to exist also in the stable
version.
Also, having a separate place would force the developers to look at two
places.

**Comment by misaochan** [comment]
Do we want to have a "beta" branch here, with "master" being used for the live version?

**Comment by nicolas-raoul** [comment]
I would suggest switching to this versionCode numbering:

Mmmmhh

M: Major version number
mmm: Minor version number
hh: Hotfix number

Examples:
200500 for the original 2.5
200501 for the first hotfix to 2.5
705613 for the 13th hotfix to 7.56

- If not urgent, always release as beta
- After 2 days in beta, if there are no complains, just click the button in Google Play to move that release to production
- If an urgent fix is needed for the production-released 2.5 (for instance), then create a branch "2.5-hotfix" from the release commit, implement the fix, and release as 2.5.1 directly in production

Beta branch: The best solution would probably be (or [gitflow](http://nvie.com/posts/a-successful-git-branching-model/)) but I suggest we wait until we have at least 30 beta testers. How many beta testers do we have now?

**Comment by misaochan** [comment]
Thanks @nicolas-raoul ! I haven't released the beta signup URL yet, because I've been trying to figure out how to set the system up. If we don't use a beta branch or gitflow, should we just use master for everything?

**Comment by nicolas-raoul** [comment]
Using master for everything (except hotfixes) is probably the easiest for
now, yes.

**Comment by misaochan** [comment]
So... under the versionCode numbering that you suggested, we would use 200001 for the current release, right?

**Comment by nicolas-raoul** [comment]
Yes!
I suggest writing a small script that increases version code and name
automatically, to avoid mistakes. Could be in the vein of this one:
https://github.com/ankidroid/Anki-Android/blob/develop/tools/release.sh#L32

**Comment by misaochan** [comment]
Oh okay. I guess I'll just carry on with the standard numbering first, until we can get the script ready. Otherwise 1 mistake could throw the whole thing off since we need to upload sequentially, lol.

**Comment by misaochan** [comment]
I've pushed the first beta release! Opt-in at https://play.google.com/apps/testing/fr.free.nrw.commons .

Would appreciate it if folks here could opt in and see if it works for them. If everything is okay, I'll announce the opt-in link on our forums and WMF mailing lists.

I think we might also want a link in the app like @tobias47n9e suggested. I guess it would just be a straightforward addition of a link in our Settings.

**Comment by misaochan** [comment]
Does the beta work for anyone else? I'd like to announce the opt-in URL on mailing lists etc soon if possible. :)

**Comment by tobias47n9e** [comment]
@misaochan Beta works perfectly. It is listed with other Beta-Apps in the Play store. Can we ping someone that is using FDroid?

**Comment by misaochan** [comment]
Thanks @tobias47n9e ! @nicolas-raoul , do you use F-Droid?

**Comment by nicolas-raoul** [comment]
F-Droid does not allow beta versions, so I get Commons from Play beta.

**Comment by misaochan** [comment]
Ah, okay, that's fine then. Will announce soon. :)

**Comment by misaochan** [comment]
Re: the version names, I think I will probably use 2.x.0 for major changes and 2.x.y for minor changes? Granted, the line between 'major' and 'minor' is pretty subjective, but since the version name is largely "for display" anyway, I figure that shouldn't be too bad? The next patch with the beta link and potential UI improvements sounds like it should be a major change for instance, so 2.1.0. I don't think it will be feasible for us to hold on to 2.0.y all the way up to Vienna. :)

**Comment by nicolas-raoul** [comment]
I would suggest using 2.x.0 for any enhancement, even minor; and 2.x.y only
for hotfixes to version 2.x
Of course 2.0 is quite significant PR-wise so this "rule" can be put aside
for 2.0.

**Comment by misaochan** [comment]
Ah okay, that does make sense. Thanks nicolas!

**Comment by misaochan** [comment]
Will close this since beta testing has been set up, and will create new issues for further beta testing enhancements.
