### ISSUE TITLE
Textview(No Copyright violation) not fit in Peer Review Activity

### ISSUE THREAD

**Issue by Prince-kushwaha** [commons-app/apps-android-commons#4031]
**Summary:** 
Textview(No Copyright violation) not fit in Peer Review Activity
**Steps to reproduce:** 
Go to the home activity 
Open navigation bar ->click on Review
See the Bug by Screes-shots
**Device and Android version:** 
Device:Redmi y3
Android version:9, API :29
**Commons app version:** 
2.13.2
**Screen-shots:** 
![WhatsApp Image 2020-11-12 at 6 17 34 PM](https://user-images.githubusercontent.com/65972015/98942117-8e7b8c80-2513-11eb-99ba-036c7c9ca279.jpeg)

**Would you like to work on the issue?**
Yes
;
Please let us know whether you want to fix the issue by yourself. If not, anyone can get the issue assigned to them.
Yes

**Comment by Prince-kushwaha** [comment]
i like to work on this issue

**Comment by Prince-kushwaha** [comment]
assinge me for this issue

**Comment by madhurgupta10** [comment]
@Prince-kushwaha This issue was already reported https://github.com/commons-app/apps-android-commons/issues/3376

**Comment by Prince-kushwaha** [comment]
ok
