### ISSUE TITLE
GitHub new issue app version autofiller button

### ISSUE THREAD

**Issue by jidanni** [commons-app/apps-android-commons#4034]
How about a button, in the app, at least development versions, that would directly take us to a new GitHub issue with the version number of the app already filled-in in the comment!

So it would call the GitHub app via a Android intent...

(No, I don't know what should happen if the person doesn't have the GitHub app already also installed.)

Yes, I do know that it is still very easy to copy it (e.g.,2.13.1.828~2ed5a74) into the GitHub issue comments ourselves.

**Comment by nicolas-raoul** [comment]
Creating a new issue should only bee done when no such issue exists already.
So taking people to issues is fine, but taking people to a new issue directly is not really a good thing to do, I think.

**Comment by jidanni** [comment]
Well, they would probably already have fully investigated the problem with a wide big desktop screen in the days before they filed the bug. And only when they're actually ready to file it, pushed the button.  It's been years since I had to paste a version number into a bug report. We always get them into the bug reports automatically for example, https://bugs.chromium.org/p/chromium/issues/detail?id=1145718 .
Anyway, I was thinking you could take advantage of a GitHub API, I'm sure they have one to do this.
Certainly will take the worries about missing version numbers or wrong version numbers away.
Stop thinking you can have two buttons, one just goes to the issues list and another one would be if you're ready to file an issue.
But yes, these are luxury items you might say.

**Comment by jidanni** [comment]
Perhaps even the Android version number could be  stuffed into it also, just like when creating a feedback email ...

**Comment by nicolas-raoul** [comment]
If the GitHub API allows to remember a version number when show the list of existing issues, then auto-fill the version number if the user chooses to create a new bug, that would be ideal indeed. Please anyone reopen if you find a way to achieve that.

**Comment by jidanni** [comment]
Well https://docs.github.com/en/free-pro-team@latest/rest/reference/issues#create-an-issue gives full control of the content...

**Comment by jidanni** [comment]
And https://www.google.com/search?q=prefill+github+issue finds tons...

**Comment by jidanni** [comment]
Maybe the issue, with a few fields filled in, could be created.
Then a link given to the user: "OK, issue `#1234` created. Please
browse it and add any missing details."

**Comment by jidanni** [comment]
https://ytdl-org.github.io/youtube-dl/ , if you hit the  Support button, leads straight into their template.

**Comment by jidanni** [comment]
https://github.com/ytdl-org/youtube-dl/issues/new/choose

**Comment by nicolas-raoul** [comment]
It is not what we want, unfortunately. We want people to first check whether a similar issue exists.

**Comment by jidanni** [comment]
To report a bug, follow these easy steps:
1. First [check](https://github.com/ytdl-org/youtube-dl/issues) if a similar issue exists.
2. No? Really? OK, then please [report it](https://github.com/ytdl-org/youtube-dl/issues/new/choose)!

(Using youtube-dl as an example.)
