### ISSUE TITLE
"Copy previous captions & descriptions" feature does not copy the secondary language choice

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#4037]
Steps to reproduce:
- Install latest master
- Select 2 pictures to upload, share to the Commons app
- For the first picture, enter two captions, one in English ("en") and one in Japanese ("ja")
- For the second picture, press "Copy previous captions & descriptions"

Expected: The second picture now has an English caption and a Japanese caption.
Actually: The second picture now has an English caption and an Afrikaans caption. Afrikaans is the first (default) language of the list.

**Comment by gouri-panda** [comment]
@nicolas-raoul Can I work on this issue?

**Comment by nicolas-raoul** [comment]
@gouri-panda Sure, thanks!

**Comment by Prince-kushwaha** [comment]
i want to work on this issue
Assignees me

**Comment by gouri-panda** [comment]
@Prince-kushwaha Sorry, I'm working on this issue.

**Comment by nicolas-raoul** [comment]
@Prince-kushwaha please choose an issue by clicking on the "unassigned issue" link at https://github.com/commons-app/commons-app-documentation/blob/master/android/Volunteers-welcome!.md#developers Thanks!

**Comment by Pratham2305** [comment]
@gouri-panda  Are you still working on this issue ?

**Comment by gouri-panda** [comment]
@Pratham2305 you can take it.
