### ISSUE TITLE
Highlight currently active image with a contrasting border

### ISSUE THREAD

**Issue by jidanni** [commons-app/apps-android-commons#4042]
Here in 2.13.1.835~9375a8b there is confusion of what the grayed out image means. Only on the second page now do we realize that it's not indicating a half uploaded image, but just indicating which image we are answering questions about. Please resolve such confusion via some redesign so basic uses don't get confused. Thanks.
![Screenshot_20201124-074059](https://user-images.githubusercontent.com/1230959/100028072-078ab600-2e29-11eb-859c-dd22601c1a7f.jpg)

**Comment by misaochan** [comment]
Could you suggest a modification that would make it clearer to you which picture is active?

**Comment by sivaraam** [comment]
> Could you suggest a modification that would make it clearer to you which picture is active?

To me, highlighting the currently active image using a contrasting border comes to mind.

**Comment by jidanni** [comment]
Yup, so greyed-out or one side of a single image itself being greyed-out should indicate partial uploading states. And then a border around an image, no matter if it's greyed out or not, could indicate this is the current selected image that we are adding notations to.

**Comment by misaochan** [comment]
> To me, highlighting the currently active image using a contrasting border comes to mind.

Great idea! I think this would be a nice task for a beginner. :)

**Comment by Saral-code** [comment]
I would like to work on this issue. Please assign me this issue.
