### ISSUE TITLE
Accessibility: overlapping seen with larger font sizes

### ISSUE THREAD

**Issue by jidanni** [commons-app/apps-android-commons#4043]
Here in 2.13.1.835~9375a8b we see that some older users who have cranked up their cell phone font size etc.  settings, will not be able to see all the items on the page due to overlapping. Therefore more testing needs to be done at different font sizes to make sure the app will work for all of them. Also consider screen magnification sizes excetera, all the things that you'll find on a common Android cell phones accessibility settings page.
![Screenshot_20201124-073953](https://user-images.githubusercontent.com/1230959/100028321-a2839000-2e29-11eb-9d0b-7ebb717967d1.jpg)

**Comment by jidanni** [comment]
Following simple accessibility principles will ensure a clear view for all app users.

**Comment by misaochan** [comment]
Good point. We should at the very least minimize the top card if there is insufficient space.

**Comment by Saral-code** [comment]
Hello,
I would like to work on this issue. I think I can fix that.

**Comment by misaochan** [comment]
@Saral-code Please feel free! I think this would be a good issue for you too. :)
