### ISSUE TITLE
The number of steps is influenced by the number of images

### ISSUE THREAD

**Issue by jidanni** [commons-app/apps-android-commons#4044]
In #4042 we observe how if you are uploading one image there are four steps. But if you're uploading two images,  it becomes five steps. Thus we can see that you're confusing two kinds of steps. This would never happen on the website version.
So call them 1.1, or 1A, Etc.

Yes, it is correct that there are indeed five steps but you are still confusing two kinds of steps. Thank you.

**Comment by nicolas-raoul** [comment]
This is by design.
If many users complain about it, this can probably be reconsidered.
