### ISSUE TITLE
Identical file names seen during upload

### ISSUE THREAD

**Issue by jidanni** [commons-app/apps-android-commons#4046]
In 2.13.1.838~9202c3a
we observe that during uploading the two file names are exactly the same! This is rather frightening to the user. Only after the upload is complete do the file names become different with one having a number two added to it. Why can't this be done before showing them to the user?
![Screenshot_20201128-141051](https://user-images.githubusercontent.com/1230959/100495305-3f755e80-3185-11eb-8e07-123156cac6ca.jpg)

**Comment by nicolas-raoul** [comment]
This is working as intended.
These are not filenames, they are captions.
Captions are human-friendly.
Ideally the picture should show up instead of these grey placeholders, so that you can make a difference between each.

**Comment by jidanni** [comment]
(Well they are 99% similar to what the filenames end up being.
You see the user wants to make sure they have chosen good filenames.
As it is 100 times harder to change them later (yes, on the website) then any of the other things they type in.
OK, well we'll just trust the app to make good filenames. If the end up not good, well at least one can't blame the user.)
