### ISSUE TITLE
Field tip truncated on small screen / big font

### ISSUE THREAD

**Issue by jidanni** [commons-app/apps-android-commons#4047]
If the (older) user has larger fonts enabled, then the  numbers after "limit 2" are truncated.
2.13.1.838~9202c3a
![Screenshot_20201128-140726](https://user-images.githubusercontent.com/1230959/100495369-11dce500-3186-11eb-9ba6-e4eed5c8609a.jpg)
We also note a logo, covering up the word after "media".

**Comment by nicolas-raoul** [comment]
Curious to hear what the UX experts think about this.
Could you please post a screenshot of 2 or 3 other similar apps to show how other apps handle a field tip too long to fit?

**Comment by jidanni** [comment]
Mmmm, I don't know. Maybe related: https://developer.android.com/guide/topics/ui/look-and-feel/autosizing-textview

**Comment by jidanni** [comment]
https://developer.android.com/guide/topics/ui/accessibility

**Comment by jidanni** [comment]
I was also going to mention
https://material.io/design/usability/accessibility.html#implementing-accessibility
but due to https://bugs.chromium.org/p/chromium/issues/detail?id=1153673
it takes some work to get exactly there.

**Comment by jidanni** [comment]
https://material.io/design/typography/understanding-typography.html#readability is OK though.

**Comment by jidanni** [comment]
In the first picture on https://github.com/commons-app/apps-android-commons/pull/4055#issuecomment-736014504
the "Limit 2..." looks a whole lot better!

**Comment by misaochan** [comment]
The first picture in that comment is what happens when you tap on the text field.

**Comment by jidanni** [comment]
Well, just here using the GitHub app it seems everybody's comments on these issues are nicely wrapped and folded or whatever, never going off the screen, even though they are one long line.

**Comment by nicolas-raoul** [comment]
@jidanni Important content is wrapped  of course, but have you seen many major apps wrapping **field tips**?

**Comment by jidanni** [comment]
If that their official name?
https://www.google.com/search?q=android+%22field+tips%22
can't find them.

**Comment by misaochan** [comment]
Interesting idea @4D17Y4 ! I'm good with moving the info about the character limit to the info tooltip. We should also limit the EditText, but users do still have to be informed.

**Comment by 4D17Y4** [comment]
> but users do still have to be informed.

Should we add a down counter to show the number of characters left like in stackoverflow and in whatsapp ?
@misaochan

**Comment by misaochan** [comment]
I think for the time being, this issue can be handled by simply moving the info. Adding a counter would be a separate enhancement IMO. :)

**Comment by 4D17Y4** [comment]
Cool,
Assign it to me, I'll do a PR first thing in the morning. 
Thx .

**Comment by misaochan** [comment]
@4D17Y4 I think you deleted your comment by accident? Sure, I can assign you this issue. Generally speaking issues tagged enhancement tend to be a bit iffy, but as the discussed solution for this is quite simple (and you are not adding any features) I will tag this as "good first issue".

**Comment by 4D17Y4** [comment]
> @4D17Y4 I think you deleted your comment by accident?

Nope,
Actually I thought same, tagging it as good first issue. 
And decided to work on other bugs, letting beginners handle this one ;)

**Comment by misaochan** [comment]
Works for me. :)

**Comment by trdillon** [comment]
Hey, I'm new here and would like to contribute. This looks like a good place to get started, is it available for me to work on?

**Comment by nicolas-raoul** [comment]
@trdillon It is yours, thanks! Please post about your progress once in a while :-)
