### ISSUE TITLE
"copy to subsequent media" button

### ISSUE THREAD

**Issue by jidanni** [commons-app/apps-android-commons#4048]
Version 2.13.1.838~9202c3a.
Shouldn't the words "copy previous captions and description" go away after we press it? 
![Screenshot_20201128-141002](https://user-images.githubusercontent.com/1230959/100495491-456c3f00-3187-11eb-9a05-59bb424e5cc7.jpg)
(You know we pressed it several times thinking that it is the only choice on this tiny little shred of window that's left visible, (due to probably being an  older user using bigger fonts.))
( We thought it would go away and then maybe the Big Blue Button underneath it would slide up so that we could push it. Well yes we could make our keyboard slide down and then we can get to the big blue button. But still...)

**Comment by nicolas-raoul** [comment]
I have no strong opinion on this, let's let the UX experts decide :-)

**Comment by jidanni** [comment]
It could stay, if the Next Step button was visible enough on some users' crowded screens without it needing to go away to leave room for that button... (Yes, sloppy users leave big keyboards on the screen.)

**Comment by misaochan** [comment]
Now that we have changed our upload process significantly, I wonder if there's a better way to handle copying title/desc, than to have that big chunk of text on every screen. That button is, after all, a relic of our old upload process where multiple uploads were not yet possible from within the app.

My thought is that we could have a "copy" icon on the first upload screen, and if the user taps it, we copy the title and desc to their other pictures (they must still go through each one and confirm it, but they don't have to type it again). 

What do you guys think? @neslihanturan @sivaraam

**Comment by nicolas-raoul** [comment]
I use that button very often when uploading many pictures of the same town for instance.

The "copy to subsequent media" button idea is great!
The desktop Upload Wizard actually has that, so it most of the serious Commons users will find it familiar:
<img width="280" alt="Screen Shot 2020-12-01 at 22 13 23" src="https://user-images.githubusercontent.com/99590/100745481-afecdb80-3422-11eb-96cb-e086349326d2.png">
When uploading several media using the desktop Upload Wizard, this is actually present in all steps except the last. I would recommend doing the same :-)

**Comment by Pratham2305** [comment]
@nicolas-raoul @misaochan, Can I work on this?

**Comment by sivaraam** [comment]
@Pratham2305 Sure, you could work on it. Let us know how you plan to approach this issue.

**Comment by Pratham2305** [comment]
I agree with @nicolas-raoul  and @misaochan, So will basically add a "copy to subsequent media" button on the first upload screen that will copy the caption and description to all the other media and I think it would better to hide the button in the next steps if it is pressed and also if, in any step, the user changes any of the captions and description then button should reappear and allow copying the same to remaining steps. If this sounds good then I will start working on it. Thanks!

**Comment by sivaraam** [comment]
If we hide the button in some cases and show it in other cases, users might find it difficult to figure out when it is shown and when it is not shown. So, I feel it would be better to just show it all the time in all screens except the last one.

**Comment by Pratham2305** [comment]
@sivaraam Okay!, No problem
