### ISSUE TITLE
Add option to not have the app run in the background

### ISSUE THREAD

**Issue by jidanni** [commons-app/apps-android-commons#4049]
Can there please be an option added to not have the app run in the background? I don't actually see the point of having the app run in the background.
![Screenshot_20201128-144311_1](https://user-images.githubusercontent.com/1230959/100495658-a0526600-3188-11eb-8ea4-544d3331ece6.jpg)
In fact, this is the only app out of probably one hundred on on my cell phone that triggers this kind of message. Other apps like big social media networks', seem to work just fine  and do a lot of things, without causing this reminder.

2.13.1.838~9202c3a

**Comment by nicolas-raoul** [comment]
What this notification means and how to turn it off:
https://www.howtogeek.com/325083/how-to-disable-the-is-running-in-the-background-notification-on-android-oreo/

**Comment by jidanni** [comment]
Yes, the notification is correct and nobody should try hacking their phone to turn it off.

There is no reason the app should be continuously running in the background.

Not even the mighty facebook app does this.

And most folks would be uploading five times more pictures per day to Facebook than to commons.

It's just like if I leave my car's motor running all night because I might want to drive it the next morning.

**Comment by jidanni** [comment]
https://developer.android.com/docs/quality-guidelines/build-for-billions/battery-consumption

**Comment by misaochan** [comment]
I don't actually get this notification for the app despite not having it turned off. It would be good if you can provide specifics about when it triggers for you, e.g. only when uploading? did you open Nearby? or does it just happen all the time? etc. Alongside your Android version and device.

**Comment by madhurgupta10** [comment]
I think this issue might be similar to https://github.com/commons-app/apps-android-commons/issues/3981 If I recall correctly in older android versions the progress bar is not shown for non dismissing notifications.

**Comment by jidanni** [comment]
Yes, I bet they're related. So I'll just wait till the other one gets fixed and  uploaded...

**Comment by nicolas-raoul** [comment]
Both the app and Android have changed a lot in this regard, I think this can be closed.
