### ISSUE TITLE
Add some spacing on the "About" view

### ISSUE THREAD

**Issue by tobias47n9e** [commons-app/apps-android-commons#405]
On my phone there is no space between the text and the edge of the screen. I would be nice to have the usual 5 to 20px left and right. Might be a good issue for a new contributor. Do we have a tag for that?

![screenshot_2017-03-07-17-16-41](https://cloud.githubusercontent.com/assets/6953323/23671224/bdcdc558-036a-11e7-8666-9c3c8c448ffb.png)

**Comment by domdomegg** [comment]
I quite like `for-beginners` or `entry-level`

I think it's a great idea to create this tag - help get us some more contributors. We should then add the project to lists like [Awesome-for-beginners](https://github.com/MunGell/awesome-for-beginners) or [up-for-grabs](http://up-for-grabs.net/#/)

**Comment by misaochan** [comment]
Good idea! Done :) Please feel free attach this tag to any other issues that you guys feel would suit, too.

**Comment by maskaravivek** [comment]
Contributors who are still relatively new to the codebase should feel free to grab these issues, right?

**Comment by misaochan** [comment]
Sure, I think anyone should feel free to tackle any  open issue that they wish to. From my point of view, the beginners tag will make it easier for a newbie to find an easy task when he arrives, but I don't think we should "reserve" issues solely for that occasion. Besides, new issues pop up all the time anyway. :)

**Comment by nicolas-raoul** [comment]
@misaochan "for beginners" sounds rather exclusive indeed.
Some might feel bad implementing a task marked "for beginners", it feels a bit like stealing cotton candy from a kid at Disneyland.
To avoid this, how about maybe renaming the tag "beginner friendly"?
By the way, creating this tag was a great idea I think :-)

**Comment by misaochan** [comment]
Haha good point, done!
