### ISSUE TITLE
Add feature in Login Account 

### ISSUE THREAD

**Issue by Prince-kushwaha** [commons-app/apps-android-commons#4058]
**Summary:** 
In Login Activity add feature when click on the username field it so the previous Login Username 
So that the user not type username again again for the Login 
**Commons app version:** 
2.13.2~757c7b.0008
**Would you like to work on the issue?**
Yes
Please let us know whether you want to fix the issue by yourself. If not, anyone can get the issue assigned to them.
Yes

**Comment by Prince-kushwaha** [comment]
I want work on this 
assignees me

**Comment by misaochan** [comment]
I am not sure if this would be a desirable feature, due to security/privacy concerns. I know that some apps do this, but Wikimedia privacy guidelines might be different. @nicolas-raoul @sivaraam what do you think?

**Comment by nicolas-raoul** [comment]
I would say it is not really desirable.
An activist might not like this feature when the bad guys find out that their phone contains a username linked to pictures of them doing bad things. Sounds extreme, but it is what privacy is about.
If someone logs out, we better forget them.

Some OS-level password managers exist for people who need this, what we could do is make sure that we are compatible with these password managers.

**Comment by sivaraam** [comment]
I agree with @nicolas-raoul. As a matter of fact, I haven't seen many Android apps that remember username. Also, I don't even see much use for it in out app given that users don't get logged out unless they manually do so. So, I don't see how this would be beneficial either.

On a _side note_, there were two global logouts [[1](https://lists.wikimedia.org/pipermail/wikitech-l/2020-June/093543.html)], [[2](https://lists.wikimedia.org/pipermail/wikitech-l/2020-October/093922.html] occurred in the past 6 months. The Wikipedia app logged me out properly during those occurrances but I don't remember being logged out of the Commons app. I wonder why 🤔

**Comment by misaochan** [comment]
I agree. Closing then, since it appears to be unanimous.

**Comment by sivaraam** [comment]
>  @sivaraam shall we make a new issue for that? :)

Done. #4060
