### ISSUE TITLE
If phone not connected with internet our Appliction does not show any message or DailogBox

### ISSUE THREAD

**Issue by Prince-kushwaha** [commons-app/apps-android-commons#4065]
**Summary:** 
when our app is not connected with Internet I want to add an DailogBox or message which show You are not connected with Intenet
**Commons app version:** 
2.13.1
**Would you like to work on the issue?**
YES
Please let us know whether you want to fix the issue by yourself. If not, anyone can get the issue assigned to them.
YES

**Comment by Prince-kushwaha** [comment]
I want to work on this 
can i work

**Comment by Prince-kushwaha** [comment]
@nicolas-raoul

**Comment by Prince-kushwaha** [comment]
can i work

**Comment by nicolas-raoul** [comment]
It is intended that such a notification does not appear.
The app is usable (not fully but some feature) without an Internet connection.

**Comment by Prince-kushwaha** [comment]
Every app show an Layout or DailogBox  when Internet is not connect it show only 
when their is having need of Internet to Loading data from Internet and show data to user

**Comment by Prince-kushwaha** [comment]
Like in commons app need to show an Layout or DailogBox when Internet is not connected In some activity like-MainActivity,ExploreActivity and where having need
