### ISSUE TITLE
Delete Old UI Tests?

### ISSUE THREAD

**Issue by madhurgupta10** [commons-app/apps-android-commons#4073]
**Summary:** 
![Capture](https://user-images.githubusercontent.com/30932899/101281691-7dfac100-37f6-11eb-9d5f-c0718b5e5a21.PNG)

**Comment by domdomegg** [comment]
I support removing the tests if they don't even compile. We haven't been running these instrumentated tests in so long it'd be great to see them fixed or removed so we can get them running in Travis again.

**Comment by misaochan** [comment]
Agreed, we need to either fix or remove these.

**Comment by Roshan13046** [comment]
Can I fix this issue?
My Approach: Deleting the old UI tests from the file.
Any suggestions?

**Comment by misaochan** [comment]
I think it's OK to delete for now. We should probably make a separate issue for writing UI tests that actually work.

**Comment by madhurgupta10** [comment]
@Roshan13046 Feel free to make a PR for this issue!

**Comment by Roshan13046** [comment]
> @Roshan13046 Feel free to make a PR for this issue!

Please, suggest to me which UI tests are considered old UI tests?

**Comment by madhurgupta10** [comment]
Fixed in https://github.com/commons-app/apps-android-commons/pull/4828
