### ISSUE TITLE
Removing pmd and checkstyle

### ISSUE THREAD

**Issue by domdomegg** [commons-app/apps-android-commons#4077]
The build currently contains two steps, `checkstyle` and `pmd` which were previously used to check code quality. Since 2017 Android's own `lint` tool has lessened the need for both of these, and we've actually set the old tools to [ignore their own failures](https://github.com/commons-app/apps-android-commons/blob/dcd767351bf45524d8d8c994b47aa0184f615f31/app/quality.gradle#L27). Additionally, pmd is dropping the android ruleset in the next major version (`The RuleSet rulesets/java/android.xml has been deprecated and will be removed in PMD 7.0.0`).

Despite this, we run `checkstyle` and `pmd` on every build in Travis. This makes the logs much harder to decipher and slows down the build. I'm not aware of any effort to resolve the issues they report (#171 is for the new Android lint issues), and the new Android lint covers most of them anyways (and better integrates with the Android Studio IDE).

I propose removing these steps from the project and focusing on cutting down the Android lint issues. This should:
- Make build logs easier to read (useful for contributors to identify failing tests etc.) - checkstyle alone accounts for almost 90% of the build output
- Speed up builds
- Allow us to focus on one source of lint issues (built-in Android lint)

**Comment by misaochan** [comment]
I agree. To be honest, I scroll right through all of the checkstyle output when going through a Travis build, it is far too verbose.

Do you know if there's a way to add Android lint checks to CI, @domdomegg ? For instance if a PR triggers an additional lint warning, is there a way for the person reviewing the PR to see it without going through the local build?

**Comment by domdomegg** [comment]
> Do you know if there's a way to add Android lint checks to CI, @domdomegg ? For instance if a PR triggers an additional lint warning, is there a way for the person reviewing the PR to see it without going through the local build?

Yes, I'll try adding the lint step to the CI gradle build. Ideally with GitHub actions we might be able to get annotations within the PR as you describe. I think to prevent it being too noisy to start with we can create a [lint baseline](https://developer.android.com/studio/write/lint#snapshot) so only new problems are reported. Hopefully over time given more focus on one set of lint checks we can remove all problems from the baseline too.
