### ISSUE TITLE
menu item are not visible 

### ISSUE THREAD

**Issue by Prince-kushwaha** [commons-app/apps-android-commons#4079]
**Summary:** 
In Different Activity or fragment color of toolbar is different In some activity color of toolbar and color of menu item is same due
to this menu item are not visible

**Steps to reproduce:** 
open different pages of app see the toolbar and menu item

**Device and Android version:** 
 Android Device:Redmi Y3
API :29
**Commons app version:** 
2.13.1~debug-issue15~b24ed1cf6
**Screen-shots:** 
![Screenshot_2020-12-07-07-07-11-646_fr free nrw commons beta](https://user-images.githubusercontent.com/65972015/101301002-77536480-385d-11eb-9fc9-06a078386134.jpg)

![Screenshot_2020-12-07-07-06-23-198_fr free nrw commons beta](https://user-images.githubusercontent.com/65972015/101301536-26447000-385f-11eb-9b67-28e09ea4c960.jpg)

**Would you like to work on the issue?**
YES
Please let us know whether you want to fix the issue by yourself. If not, anyone can get the issue assigned to them.
YES

**Comment by Prince-kushwaha** [comment]
I want to work on this issue
asssimed me

**Comment by Prince-kushwaha** [comment]
This issue raise after pull request is merge #3891

**Comment by Prince-kushwaha** [comment]
@neslihanturan hi

**Comment by Prince-kushwaha** [comment]
which color i used for toolbar or menu item 
UI v.3 there are two color toolbar white and blue

**Comment by Prince-kushwaha** [comment]
**In new UI which color for toolbar or menu item** ? 
Anyone tell me so that i work on this issue

**Comment by Prince-kushwaha** [comment]
@maskaravivek can i work on this issue

**Comment by nicolas-raoul** [comment]
If I understand correctly, the problem is that in Explore the search icon is white on almost-white background so it is very difficult to see (I can experience this on latest master).

**Comment by Prince-kushwaha** [comment]
Yes

**Comment by Prince-kushwaha** [comment]
@nicolas-raoul see  in below image  menu icon and toolbar background color is same  so it is difficult to see icon  
tell me background color for menu icon and toolbar 
![Screenshot_2020-12-07-07-07-11-646_fr free nrw commons beta](https://user-images.githubusercontent.com/65972015/101301002-77536480-385d-11eb-9fc9-06a078386134.jpg)

**Comment by nicolas-raoul** [comment]
Sorry would you mind circling the problem in red?
If possible on a higher-resolution screenshot.
Thanks!

**Comment by Prince-kushwaha** [comment]
you can reproduce this issue in master branch
->Go to explore,->search for image 
->then click on any search result the see the toolbar it is difficult to  see toolbar icon like- Download ,share ,Star

**Comment by neslihanturan** [comment]
I confirm this issue exists on light mode. However I can not understand the questions of @Prince-kushwaha , sorry. It is just basic color change depending to the theme. See attrs.xml. There are share and download buttons on toolbar but they are not visible.
![device-2020-12-22-203951](https://user-images.githubusercontent.com/3127881/102918603-40ee2a00-4498-11eb-93b6-cb158e1185af.png)

Since @Prince-kushwaha has already collected more than one issue, this issue should be done by someone else. We work on one PR at a time. This means that this issue is currently unassigned.

**Comment by shikhar8434** [comment]
Can i work on this issue please ?
