### ISSUE TITLE
Update Gradle and Android Gradle Build Tools

### ISSUE THREAD

**Issue by domdomegg** [commons-app/apps-android-commons#4088]
## What

We should keep Gradle and the Android Gradle Build Tools up-to-date.

## How

#4076, but after updating Triple-T/gradle-play-publisher (#4089) 

## Why

This will:
- eliminate build warnings
- improving build performance
- added tool capabilities (better debugging etc.)
- better compatibility for running tests in CI (I'd like to get UI tests working again, plus explore GitHub actions as an alternative to Travis)

Overall, this should make our builds and tooling much happier. My long term vision of this is:
1. Improve build tools and CI
2. Improve unit tests and fix UI tests
3. Refactor app to standardize the way everything is implemented, eliminating bugs, making testing super easy and helping new contributors start coding and maintainers with reviewing

I think this is the right order to do things. Step 1 will make sure tests actually all work happily both locally and in CI. Step 2 will ensure the app is stable and continues to work as we perform Step 3, refactoring it into something much easier to work with. Then going forward adding additional high-quality code with tests should be easier as there will be lots of examples of how it's done. Long-term, this will massively improve the stability and quality of the app as well as generally make our lives a lot nicer.

**Comment by mrudultora** [comment]
@domdomegg  I want to work on this !

**Comment by sivaraam** [comment]
We're using Android gradle tools 8.0.3 and Gradle 8.1.1 for the app now. These are fairly recent as far as I could check. So, I think we're done with this issue.

Feel free to reopen if I happened to miss something. 🙂
