### ISSUE TITLE
In nearby tab when back button is pressed nothing happen

### ISSUE THREAD

**Issue by Prince-kushwaha** [commons-app/apps-android-commons#4096]
**Summary:** 
In nearby tab back button is pressed then  nothing happen

**Steps to reproduce:** 
 Go to nearby tab
 click on Back button is pressed
**Device and Android version:*
Android Device:Redmi y3
API:29
**ScreenShot**

![20201212_134114](https://user-images.githubusercontent.com/65972015/101980005-0a3e3580-3c88-11eb-86ef-96627114f0e7.gif)

**Commons app version:** 
2.13.2
**Would you like to work on the issue?**
Yes
Please let us know whether you want to fix the issue by yourself. If not, anyone can get the issue assigned to them.
Yes

**Comment by Prince-kushwaha** [comment]
assinge me

**Comment by nicolas-raoul** [comment]
I can reproduce the issue in latest master.
