### ISSUE TITLE
In MediaDetailfragment Editext Dailog is Blank in Dark mode

### ISSUE THREAD

**Issue by Prince-kushwaha** [commons-app/apps-android-commons#4101]
**Summary:** 

See bug in Screenshot

**Steps to reproduce:** 
Go to  Dark mode in app
Click on any media or image
click on Edit view icon

**Device and Android version:** 
Android Device:Redmi Y3
API:29

**Commons app version:** 
2.13.2

**Screen-shots:** 
![WhatsApp Image 2020-12-12 at 7 27 20 PM (1)](https://user-images.githubusercontent.com/65972015/101985876-a5e39c00-3cb0-11eb-8fca-88f2a9905c5b.jpeg)

![WhatsApp Image 2020-12-12 at 7 27 20 PM](https://user-images.githubusercontent.com/65972015/101985878-ae3bd700-3cb0-11eb-8dc7-a11d9e9a3efd.jpeg)

**Would you like to work on the issue?**
YES
Please let us know whether you want to fix the issue by yourself. If not, anyone can get the issue assigned to them.
YES

**Comment by Ankita13-code** [comment]
Hey! I would like to work on this issue! Can this be assigned to me?
