### ISSUE TITLE
Search icon is hard to see

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#4111]
On latest master, go to "Explore"
The search icon (looking glass just above "Uploaded via mobile") is very hard to see as it is white on a very light grey background.

**Comment by Prince-kushwaha** [comment]
can i work

**Comment by Prince-kushwaha** [comment]
this is subissue of my create issue #4079

**Comment by Prince-kushwaha** [comment]
i fixes this issue i can make PR

**Comment by Ankita13-code** [comment]
@nicolas-raoul Shall I work on this issue or is it assigned to someone?

**Comment by sivaraam** [comment]
Hi @Ankita13-code 👋. Welcome to the project. Looks like @Prince-kushwaha is working on #4079 which is very related to this issue. So, I believe this is taken. You could find other beginner friendly issue by looking at issues tagged with [good-first-issue](https://github.com/commons-app/apps-android-commons/labels/good%20first%20issue). Also, take a look at our [Volunteers-welcome!](https://github.com/commons-app/commons-app-documentation/blob/master/android/Volunteers-welcome!.md#volunteers-welcome) wiki doc, in case you haven't already done so. 🙂

**Comment by neslihanturan** [comment]
Hey all, actually considering our one issue at a time principle and @Prince-kushwaha has a lots of open pull requests with some reviews, I think we should assign this issue to someone else. After you are done with your existing issues, we can continue to assign you new ones @Prince-kushwaha .

Are you still willing to work on this issue @Ankita13-code ?

**Comment by neslihanturan** [comment]
Sorry, if the PR is open for this issue I did not see it. @Prince-kushwaha can you please verify the PR for this issue is not send? 

Another note, please do not create one PR for multiple issues or multiple PRs for one issue. It became very hard to control them and review. And please do not claim new issues before you are done with your existing PRs for next time :)

**Comment by shikhar8434** [comment]
Sir can I work on this issue please?

**Comment by Aditya-1295** [comment]
Hi, I am very new to opensource coding , i know that this issue was not assigned to me . I just wanted to get familiar to Github and
codebase base for this repo . Looking forward to contributing to this community.

**Comment by Prince-kushwaha** [comment]
@shabar-shab I already create the PR for this issue you make PR on different unassign bugs

**Comment by neslihanturan** [comment]
There are two issues on this same bug. Please everyone let us know that you are working on the issue and make sure no one else interested with the same issue before you do. And remember, one issue at a time. If you have open PR with reviews needs to be done, you should not work on a new issue. Unfortunately one of the solutions came for the same issue will be closed. Please be more careful next time, we don't want to waste your effort.

**Comment by Prince-kushwaha** [comment]
@neslihanturan  There is two pull request of this issue I already make the PR for this issue but //@shabar-bar // make another PR of this issue
