### ISSUE TITLE
Crash when tapping search result

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#4112]
On latest master:

- Go to Explore
- Tap the search icon in the upper-right (yes it is hard to see, that's the topic of  #4111)
- Type "rabbit" or anything in the search bar
- Tap any result that appears
- Crash

This also happens with items search.
I just sent 3 logcats.

**Comment by Prince-kushwaha** [comment]
This bug is fixed by my pull request -#4074

**Comment by Prince-kushwaha** [comment]
install the app with current master branch

**Comment by nicolas-raoul** [comment]
You are right, I was mistakenly using an old version!
Sorry and thanks for pointing out :-)
