### ISSUE TITLE
Erroneous data when uploading from Contributions after Nearby

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#4114]
**Summary:** 

After selecting a Wikidata item from the Nearby map to upload an image to, the next upload (through the regular Contributions screen) thinks that you are still uploading from Nearby, and erroneously populates p18.

**Steps to reproduce:** 

Go to Nearby map, select a pin, tap "+", tap Gallery. Then go back to Contributions. Upload a picture - the title and desc are prefilled from the Wikidata item. Even if you change them, the image is added to the Wikidata item's p18.

**Device and Android version:** 

Samsung Galaxy S20FE, Android 10
 
**Commons app version:** 

ProdRelease, current master

**Would you like to work on the issue?**

No

**Comment by 4D17Y4** [comment]
Can I work on this ?

The issue can be traced as following,

The place parameters are saved as soon as gallery icon is pressed in nearby fragment as shared preferences.
https://github.com/commons-app/apps-android-commons/blob/9e92c95d425a53f98d0b845ea0ef7605af711d24/app/src/main/java/fr/free/nrw/commons/nearby/fragments/NearbyParentFragment.java#L1454-L1459

They are removed as we enter the upload activity after picking the image.
https://github.com/commons-app/apps-android-commons/blob/0415a57d34abbb6e45ac563442fb165cbb6844c1/app/src/main/java/fr/free/nrw/commons/upload/UploadActivity.java#L387-L389

Now when the request is canceled (ie back is pressed) there is no call to upload activity and as the data in shared preferences in not removed it is available for upload from Contributions, causing erroneous data autofill.


A possible solution is,
As we have not handled the event onCanceled on the activity result, 
https://github.com/commons-app/apps-android-commons/blob/cb3de856463923dc3ba9d6d100d281a303540838/app/src/main/java/fr/free/nrw/commons/contributions/ContributionController.java#L96-L109

we can remove the data from shared preference in this overridden function.

```
@Override
            public void onCanceled(final ImageSource source, final int type) {
                super.onCanceled(source, type);
                defaultKvStore.remove(PLACE_OBJECT);
            }

```

@misaochan 
Should I go with it ?

**Comment by ashishkumar468** [comment]
@4D17Y4 It is yours :)

**Comment by misaochan** [comment]
Thanks for the detailed investigation, @4D17Y4 ! I've merged your PR. :)
