### ISSUE TITLE
Achievements shows "1" and nothing else

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#4115]
**Summary:** 

Achievements activity does not work, it only displays a "1" to me (and my level is also not 1).

**Steps to reproduce:** 

Go to Achievements activity (bottom bar > [your username])

**Device and Android version:** 

Samsung Galaxy S20FE
 
**Commons app version:** 

ProdRelease, e454cfd98fe7537a9b95960031aa46edaf7a50ab

**Screen-shots:** 

![Screenshot_20201219-014603_Commons](https://user-images.githubusercontent.com/3611199/102633418-1f412a00-419c-11eb-8613-90bddc2564d5.jpg)

**Would you like to work on the issue?**

No

**Comment by Saral-code** [comment]
I would like to work on this issue. I think I can fix that.

**Comment by misaochan** [comment]
Go for it, @Saral-code ! :)

**Comment by Saral-code** [comment]
@misaochan 
What should this section actually display?

**Comment by sivaraam** [comment]
@Saral-code you should see something like what you see in the [following screenshot](https://github.com/commons-app/apps-android-commons/issues/3434#issuecomment-591069107) ...

![Achievements](https://user-images.githubusercontent.com/46127128/75287634-b8373b00-5840-11ea-9597-da8d35796136.jpg)

... but for the new UI. I'm guessing its broken in the new UI from the beginning. So, the task here is to correct that :)
