### ISSUE TITLE
Introducing new option for deletion of image after selecting them

### ISSUE THREAD

**Issue by Saral-code** [commons-app/apps-android-commons#4118]
PROBLEM : While selecting the pics of someone selects an extra image and wants to remove it ,he/she has to select all the images again in case of multiple images. I think their should be an option for  removing the image  then and there.
SOLUTION : 
1. I think that either we can use drag and drop motion to select and drag it to some place to get it deleted.
2. We can create a separate button on the media detail beside previous option to delete the currently selected image.
3. We can also create a simple dustbin icon which appears when we click on any of the images and on selecting that it deletes the image from uploaded files.

![WhatsApp Image 2020-12-18 at 9 53 56 PM](https://user-images.githubusercontent.com/54104573/102637422-fd37af80-417b-11eb-8f9d-0948856f1790.jpeg)

I think its worth working on.

**Would you like to work on this issue?**
Yes, definitely.

**Comment by misaochan** [comment]
Hmm. To be perfectly honest, this feels a bit like overengineering to me, introducing more complexity for minimal benefit. Personally I've uploaded quite a few sets of multiple images and have never needed to do this, and on the rare occasion that someone changes their mind, the inconvenience to them isn't very high IMO. 

What do you guys think @nicolas-raoul @sivaraam ?

**Comment by sivaraam** [comment]
I haven't used the multi-upload feature much. So, I can't say much about usefulness out of experience. But I could imagine that the following might not be overkill:

> We can create a separate button on the media detail beside previous option to delete the currently selected image.

I do wonder if that would make the take more precious free space from the already crowded media details input overlay, though (there's also a draft PR for adding a new button that allows the removal of a description: #3504). Especially in small screen devices it could take up all the available free space making it look cluttered. So, I would lean towards not adding this unless there's a clear need for it.

**Comment by nicolas-raoul** [comment]
I think I agree with Josephine and Kaartic, it would help in a few cases but it would be another feature to maintain, and it would make this screen a bit more complex.
I will close this for now, but please do not take it personally, and please do not hesitate to suggest other ideas, most features in this app were suggested by relative newcomers :-)
Also, anyone who need this feature please comment. Thanks!
