### ISSUE TITLE
Abnormal Behavior on theme change.

### ISSUE THREAD

**Issue by 4D17Y4** [commons-app/apps-android-commons#4123]
**Summary:** 

On Changing the theme the app behaves abnormally.

Instances:
Change the theme while on the nearby fragment, after getting back to the app we see that we are taken to contributions fragment while the bottom tab still points to the nearby fragment.

Change the theme while on favourites/explore, the app crashes on returning.

What did you expect the app to do, and what did you see instead?
The app should just return to its previous state without any crashes or unexpected behaviour.

**Device and Android version:** 

Present master on Nokia 6.1+ android 10.
 
**Commons app version:** 

Master, betaDebug.

**Would you like to work on the issue?**
Yes.

An extension of issue #3352

**Comment by shabar-shab** [comment]
@neslihanturan can I work on this issue

**Comment by 4D17Y4** [comment]
I'm on it 🙃
