### ISSUE TITLE
Toolbar with share button is missing in Profile Activity

### ISSUE THREAD

**Issue by Prince-kushwaha** [commons-app/apps-android-commons#4140]
**Summary:** 

After latest changes, toolbar with share button and back button of ProfileActivity disapeared. It should be added with back button.
**Commons app version:** 
2.13.1
**Screen-shots:** 
Screenshot of Current Master branch  

![Screenshot_2020-12-31-18-45-51-161_fr free nrw commons beta](https://user-images.githubusercontent.com/65972015/103412062-60bcd680-4b99-11eb-8c6a-4c4b96d24220.png)

screenshot of 2.13.2 (App at Google play store)

![Screenshot_2021-01-01-17-48-39-397_fr free nrw commons](https://user-images.githubusercontent.com/65972015/103438540-e0aa7580-4c59-11eb-880e-259c9e2073cb.jpg)

**Would you like to work on the issue?**
Yes
Please let us know whether you want to fix the issue by yourself. If not, anyone can get the issue assigned to them.
Yes

**Comment by nicolas-raoul** [comment]
What do you suggest should appear in the toolbar of categoryDetailsActivity?
What do you suggest should appear in the toolbar of profileActivity?
Do you have any link to a document or discussion mentioning that an empty toolbar is a bad thing?
Thanks!

**Comment by Prince-kushwaha** [comment]
@nicolas-raoul  view screenshot the screenshot

**Comment by nicolas-raoul** [comment]
Ah, I see! That's a bug indeed, thanks!

**Comment by neslihanturan** [comment]
Hey @nicolas-raoul , lets not assign this issue to @Prince-kushwaha since there are already 2 open PRs that requires changes. This issue is a release blocker so I will handle it ASAP.

**Comment by Roshan13046** [comment]
is there anyone working on this issue? I would like to fix it.

**Comment by ashishkumar468** [comment]
Hi Roshan, this is yours :)
