### ISSUE TITLE
Nearby tab shows no locations, gives SQL error

### ISSUE THREAD

**Issue by mr-yman** [commons-app/apps-android-commons#4141]
**Summary:** 

Nearby tab malfunctions; gives no nearby locations and offers only a toast with an SQL error.

**Steps to reproduce:** 

- Having already been logged into Commons on my device, I open the app.
- Taking no other action, I click the "Nearby" tab. I initially get a "Location not available" toast. (This parenthetical is NOT part of the steps to reproduce: Commons does have location access on my phone, and clicking the crosshairs button brings me to my correct, current location. However, Commons does open to the wrong location, Tower Bridge in London, while I live in the Chicago area.)
- A few seconds after the "Location not available" toast, I got a longer toast with an SQL error (see screenshot and logs). No locations pop up on map.
- If I return to the contributions tap and click on the "Nearby tab" again, now my correct location is shown on the screen, and no "Location not available" toast appears. A loading animation displays for a second, and then the same SQL error toast shows. 
- Error persists regardless of filters ("Exists" and "Needs photo"). 

**System logs:**
[Log txt](https://github.com/commons-app/apps-android-commons/files/5753712/logcatcommonserror.txt)

**Device and Android version:** 
API level: 30
Android version: 11
Device manufacturer: Google
Device model: Pixel 4a
Device: sunfish
Network type: wifi

I am running the stock OS from the manufacturer.
 
**Commons app version:** 

2.13.2~757c7b008

**Screen-shots:** 
![First SQL error](https://user-images.githubusercontent.com/54076045/103341998-fd725d80-4a4d-11eb-8577-db01278d23cf.png)

**Would you like to work on the issue?**

No.

**Comment by misaochan** [comment]
Thanks for reporting this! We thought we had fixed it previously in #3792 , but it seems not :(

**Comment by ashishkumar468** [comment]
Fix has been merged on 3.0-release, closing this one

**Comment by 4D17Y4** [comment]
Unfortunately, the fix isn't working.

<img src="https://user-images.githubusercontent.com/54016427/105353631-8297ff00-5c15-11eb-8b50-688a89194550.jpeg" height=500px>

Date and time of ss: 21 jan 2021, 6:06 IST.

For the context, I was logging in and out several times to test a bug and this showed up.

Thanks.

**Comment by misaochan** [comment]
Did you test the 3.0-release branch, @4D17Y4 ?

**Comment by 4D17Y4** [comment]
Oh,
I just noticed that,
Thanks @misaochan 
and sorry for the noise ;)

**Comment by misaochan** [comment]
So just to confirm @4D17Y4 , you don't encounter this bug on 3.0-release? :)

**Comment by 4D17Y4** [comment]
Actually, this bug is very hard to reproduce even on the master. 
I'll continue testing bugs on the 3.0-release and if I encounter this again I'll surely inform. 
Thanks.
