### ISSUE TITLE
Pre-fill desc in Nearby uploads with Wikidata item's label + description

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#4147]
As mentioned by @SJu-w in #4137

> Files uploaded to Commons by the app have a name of the photographed subject just in the filename, but not in the file description ("description" field of the "Information" template). The description field contains just the label of the value of the P31 (instance of) property, which is usually a vague general term. 
> 
> Example:
> 
> See https://commons.wikimedia.org/w/index.php?title=File:Souso%C5%A1%C3%AD_svat%C3%BDch_j%C3%A1hn%C5%AF_Ji%C5%99%C3%ADho_a_Agapita_u_cesty_ke_kostelu_sv._Petra_a_Pavla_v_Mimoni.jpg&oldid=521598789 file title and original file description. The description should be {{cs|1=Sousoší svatých jáhnů Jiřího a Agapita u cesty ke kostelu sv. Petra a Pavla v Mimoni}} but it is {{cs|1=socha}} (= statue) instead.
> 
> Solution:
> 
> Edit the template which generates the description of photos saved to Commons by the application: "description" field of the "Information" template should be filled with the label of the photographed subject, not with the label of the value of its P31 (instance of) property

**Task:** If the Wikidata item has a description in the user's language → Pre-fill the picture's description using the Wikidata item's label+description.  (example: sculpture of the Holy Deacons of George and Agapit on the way to the Church of St. Peter and Paul in Mimoň (baroque statue in Mimoň, Czech Republic))

**Comment by Saral-code** [comment]
I would like to work on this. : )

**Comment by nicolas-raoul** [comment]
@Saral-code It is yours, thanks! If you are unsure about what the goal is, please do not hesitate to ask.

**Comment by burnerlee** [comment]
@nicolas-raoul can I work on this issue and submit a PR?

**Comment by nicolas-raoul** [comment]
@Saral-code Any progress on this? :-)

**Comment by burnerlee** [comment]
@nicolas-raoul please let me know if I can start off with this issue

**Comment by nicolas-raoul** [comment]
@burnerlee Let's wait for @Saral-code for 24 hours from now, if no reply then you can have it :-)

**Comment by burnerlee** [comment]
oh cool, thank you :)

**Comment by burnerlee** [comment]
also @nicolas-raoul, sorry if this isn't the right place to ask this question, but is this project planned to participate in gsoc 2021?

**Comment by nicolas-raoul** [comment]
@burnerlee Yes, we are planning to participate in GSoC 2021 :-)

**Comment by burnerlee** [comment]
@nicolas-raoul, may I start working on the issue now?

**Comment by nicolas-raoul** [comment]
No news from Saral since 2 days unfortunately, so yes, you can take it. Thanks!

**Comment by burnerlee** [comment]
thank you so much, I'll start with the contributor's guide right away :)

**Comment by diamniko** [comment]
Hello, can I work on this?

**Comment by misaochan** [comment]
@burnerlee Are you still working on this? If not, we would like to assign this to @diamniko .

**Comment by SJu-w** [comment]
It's been a few months, and the app still produces those nonsensical, meaningless descriptions!

**Comment by misaochan** [comment]
Sorry, it seems the volunteer who wished to work on it is not responding. This issue is now up for grabs again.
