### ISSUE TITLE
List state not retained, on coming back to explore fragment from media detail fragment after choosing any media.

### ISSUE THREAD

**Issue by Pratham2305** [commons-app/apps-android-commons#4151]
**Summary:** 
On explore tab, When you open any media detail then on Pressing back navigation button on the toolbar it is sending back to the list fragment but it is not retaining the state of list as it is showing the list again from the starting.  

**Steps to reproduce:** 
On explore tab, scroll down and open any media's details, then on media details screen press back navigation button on toolbar.

What did you expect the app to do, and what did you see instead?

While testing I have noticed that on pressing back button on phone it is showing the same retained state of list, but on pressing the back button on toolbar the list is basically showing from starting, So  I think it should worked the same. and Please Correct me If I am wrong.

**Device and Android version:** 

Device: Motorola One Fusion+, Android 10
 
**Commons app version:** 

2.13.1-debug
Branch: Master, Build Variant: betaDebug.

**Screen-shots:** 

https://user-images.githubusercontent.com/54663429/103571272-97278800-4ef0-11eb-9226-a42996939706.mp4

**Would you like to work on the issue?**
Yes

**Comment by neslihanturan** [comment]
This would be very nice if it gets solved in next hotfixes. How is your work going @Pratham2305 ?

**Comment by Pratham2305** [comment]
@neslihanturan Its going great, looking forward to make more good contributions and learn new things. Thanks

**Comment by Pratham2305** [comment]
I have added a setNavigationOnClicklistener on toolbar and now Its working fine, @neslihanturan  Can I make a PR to close this issue.
