### ISSUE TITLE
On Explore Tab, All Available Options on toolbar in media detail view are only targeting the first media in the list.

### ISSUE THREAD

**Issue by Pratham2305** [commons-app/apps-android-commons#4159]
**Summary:** 
On explore tab, when open any media detail from the list then try to download or open the media in browser it is targeting only the first media from the list. This same thing also happens with other options like set wallpaper, share.

**Steps to reproduce:** 
On explore tab, open any media detail then try to choose any available option like download image, set wallpaper, open in browser etc.

What did you expect the app to do, and what did you see instead?
It should target the selected media, not the first media on the list.

**Device and Android version:** 

Device: Motorola One Fusion+, Android 10
 
**Commons app version:**  
3.0.0-debug
Branch: Master, Build Variant: betaDebug.

**Screen-shots:** 
I have tried open in browser option in the screen recording, but it is true for all other options also.

https://user-images.githubusercontent.com/54663429/104087414-727f3780-5285-11eb-8467-599cfc4090b8.mp4

**Would you like to work on the issue?**
Yes

**Comment by madhurgupta10** [comment]
@Pratham2305 Thanks for reporting the issue, feel free to ping us back when you have completed other assigned issues, we will assign it to you if no one else is working on it :)

**Comment by 4D17Y4** [comment]
To add to the issue, the bookmark option is showing similar unexpected behavior.
Would love to work on this if it's unassigned.
Thanks.

**Comment by Pratham2305** [comment]
Sorry, I forgot to mention here, I have already started working on it. I have tested the bookmark option as well and I think its working fine. @4D17Y4  Can you share a video or gif of the bug.

**Comment by 4D17Y4** [comment]
Hey @Pratham2305 , 
U can try this way. 
Bookmark the first item from the details and swipe in the details to go to next picture u would see that the bookmark doesn't change even though u haven't bookmarked all pictures.

If that doesn't clears it I'll send the video.
Thanks.

**Comment by Pratham2305** [comment]
@4D17Y4 Yes, I have also noticed the bug now. Thanks for the detail
