### ISSUE TITLE
"View in browser" should open mobile view of Commons

### ISSUE THREAD

**Issue by tobias47n9e** [commons-app/apps-android-commons#417]
When looking at an image of the gallery I think the button "View in browser" should redirect to the mobile view of Commons instead of the desktop view.

**Comment by domdomegg** [comment]
Commons automatically redirects users to the correct site (or should) - Is it worth creating a method to update the URL?

If we did implement this it would probably be fairly straightforward - create a new method in `Media.java` called something like `getMobileDescriptionUrl()`, and create a new constant something like `CommonsApplication.MOBILE_HOME_URL`, and call said method from L146 in `MediaDetailPagerFragment.java`.
