### ISSUE TITLE
Bookmarks not Updated in Picture section after remove

### ISSUE THREAD

**Issue by 4D17Y4** [commons-app/apps-android-commons#4178]
**Summary:** 

When u remove a bookmarked picture in media detail in bookmark picture fragment the bookmark is still shown in the fragment.

**Steps to reproduce:** 

How can we reproduce the issue? 
1. Open bookmarks/favorites
2. Select a picture to go to picture detail
3. Tap on the bookmark (bookmark removed)
4. Go back to the fragment(either with back button or the option in the title bar)
5. The removed bookmark is still there and the list is not updated.

What did you expect the app to do, and what did you see instead?
Bookmark should be removed and the list should be refreshed.

**Device and Android version:** 
Nokia 6.1+ android 10.
 
**Commons app version:** 
Latest master.

**Would you like to work on the issue?**
Yes.

**Comment by madhurgupta10** [comment]
@4D17Y4 I am not able to reproduce this issue, can you share a video of the bug? Thanks

**Comment by 4D17Y4** [comment]
![2021-01-16-22-38-17-online-video.GIF](https://user-images.githubusercontent.com/54016427/104818410-7a267980-584d-11eb-9ec6-603d37d0f99a.GIF)

Here u go @madhurgupta10 
U can still see the image in the fragment even though it was removed.

**Comment by madhurgupta10** [comment]
@4D17Y4 Thanks for the details. I see the bug. Feel free to make a PR for this :)
