### ISSUE TITLE
Incomplete bottom sheet appears in landscape mode

### ISSUE THREAD

**Issue by Pratham2305** [commons-app/apps-android-commons#4184]
**Summary:** 
Incomplete bottom sheet appears on clicking more option tab in landscape mode, and It is also not scrollable.

**Steps to reproduce:** 
Switch to landscape mode, then open more option tab in bottom navigation bar

What did you expect the app to do, and what did you see instead?
Bottom sheet appeared should be scrollable till the bottom.

**Device and Android version:** 
Device: Pixel 3 emulator, Android 10
 
**Commons app version:** 
3.0.0-debug
Branch: Master, Build Variant: betaDebug.

**Screen-shots:** 
![Screenshot_1610788362](https://user-images.githubusercontent.com/54663429/104807922-8dfbbc80-5808-11eb-9b84-1c695bbb1d00.png)

**Would you like to work on the issue?**
   Yes

**Comment by madhurgupta10** [comment]
@Pratham2305 Feel free to work on this issue
