### ISSUE TITLE
Publicize app

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#420]
I think it will soon be time to publicize! :)

Below are my current plans for publicizing the app, please feel free to comment or add new suggestions:
- See if we can get featured on the Wikimedia blog and Wikimedia FB page
- Contact a few tech blogs and app review websites to see if they are interested in writing about us. Not sure which exact ones - I'm thinking of TechCrunch and lifehack.r, any other suggestions? 
- Contact Wiki Loves Monuments affiliates to see if they could help; I figure our app would be pretty useful for the WLM participants

**Comment by tobias47n9e** [comment]
Should we draft some sort of summary together that can be used both as a reference for the press and for the IEG report? We could draft it on Metawiki?

**Comment by misaochan** [comment]
That would be great, @tobias47n9e . :) The IEG report isn't due for a while yet (since it hasn't been completed yet, the publicizing is part of the final phase), but it would still be helpful. Plus we could use it for the WMF blog draft with a few tweaks.

**Comment by veyndan** [comment]
Regarding point no. 2, to increase the change of the app getting featured by some websites, the app needs a revamp of the UI. I mainly say this as the initial reaction to an app (and ultimately whether someone will even try the app) is usually based solely on the UI.

**Comment by misaochan** [comment]
@veyndan @tobias47n9e Those would be good changes to make. Do we think they could be doable within the next week or so? If so, I can hold back on the publicizing until they are done.

**Comment by maskaravivek** [comment]
I could pick atleast one of these tasks. It would be great if we are able to finish these tasks before the publicity begins. Also we could come up with some sort of a press release content so that its easier for the tech blogs to publish about the app. 

Moreover i would be happy to publish it on my blogs too. :)

**Comment by misaochan** [comment]
@maskaravivek Fantastic, thanks. :)

I will start a draft of the press release on our wiki so anyone can contribute.

**Comment by misaochan** [comment]
https://github.com/commons-app/apps-android-commons/wiki/Press-release-%5BDraft%5D

**Comment by veyndan** [comment]
@misaochan Awesome, I'm a bit busy this week but if I have time I'll try and do a bit of work.

**Comment by veyndan** [comment]
What I'll do is make a PR for each screen as it appears that a few people want to work on the interface. This avoids too many conflicts.

**Comment by misaochan** [comment]
Yup, good idea @veyndan .

**Comment by misaochan** [comment]
Update: I will be aiming to do a beta release next Mon or Tues if possible, and hopefully push to production and complete the publicity draft by the end of next week. Amazing work so far, thanks all! :) 

@neslihanturan and @nextLane , would you two like to be added to credits.md? Let me know what your preferred name is if you do.

**Comment by neslihanturan** [comment]
> 
> @neslihanturan and @nextLane , would you two like to be added to credits.md? Let me know what your preferred name is if you do.
> 
Thanks:) Neslihan Turan is okay for me.

**Comment by misaochan** [comment]
v 2.1 is in beta now. :) I'll leave it there til Sunday before putting it into production, and will get the publicity ball rolling after. Would very much appreciate it if folks could test and see if everything is okay.

**Comment by misaochan** [comment]
Update: 

I've put up new screenshots in our Google Play page to reflect all the new improvements in the app, and also added one for 7-inch and 10-inch tablets respectively. Will be working on updating the store listing shortly - https://github.com/commons-app/apps-android-commons/wiki/Google-Play-store-listing

I contacted the Wikimedia blog team about the possibility of submitting a blog post for our app, but they haven't gotten back to me, will have to wait and see. Will start looking up other blogs/sites that we can submit our app to.

**Comment by nicolas-raoul** [comment]
https://en.wikipedia.org/wiki/Wikipedia:Wikipedia_Signpost/Newsroom/Suggestions
Though it has Wikipedia in its name, the Signpost often runs stories about Commons.
Topics that will probably interest them:
- History of the app, from official to forgotten to revived to official again
- Quality stats that go against received ideas

**Comment by misaochan** [comment]
I've updated the [Store listing wiki
](https://github.com/commons-app/apps-android-commons/wiki/Google-Play-store-listing) with a draft of what I plan to write on the Google Play Store - please feel free to review/comment so I can make the necessary changes before putting it up.

Also, I wonder if we should edit https://en.wikipedia.org/wiki/Wikimedia_Commons to include ourselves in the Utilities section?

Thanks @nicolas-raoul ! Will try there as well. Should I post in Suggestions or just create a proposal directly on their Submissions Desk? The former seems to be for people who want to request an article that they cannot write themselves?

**Comment by nicolas-raoul** [comment]
I edited a few minor things on the wiki.

The rule of Wikipedia mainspace is: Never write about yourself. If you are
notable enough, someone will eventually write about you.

I don't know, probably Submissions Desk then :-)

**Comment by misaochan** [comment]
Great, thanks! :)

**Comment by misaochan** [comment]
I've just received approval from Ed Erhart of the Wikimedia blog team to submit a draft for our app. :) He suggests using https://blog.wikimedia.org/2016/03/10/new-wikipedia-app-ios/ as a template for language/tone/style. I'll be working on a draft for the blog post here: https://github.com/commons-app/apps-android-commons/wiki/Press-release-%5BDraft%5D

**Comment by misaochan** [comment]
Added the template provided by Ed to the draft.

He recommends submitting only 1-2 screenshots, no more. That might be difficult to choose - anyone want to weigh in on which screenshots we want? Bear in mind that this will reflect ALL the changes to the app in the past 6 months. 

I'm thinking the Nearby feature and possibly the new title/desc screen which now has Material icons, "Use previous title/desc" option, and license selections. Not sure though.

**Comment by misaochan** [comment]
I've completed the Wikimedia blog post draft at https://github.com/commons-app/apps-android-commons/wiki/Press-release-%5BDraft%5D and will be submitting it to the blog team soon. Please let me know if there's anything you think should be changed or reworded. I'd also really like to have input on which title would be best (I suggested a few alternatives), and what image to use as the lead image (will be the image shown on the main blog and at the top of the blog post, cannot be a screenshot).

Thanks!

**Comment by nicolas-raoul** [comment]
Title: I prefer the first one with "2.0"

In the new features, I think you should talk about location-based
categories, that's one of the most convenient things ever in my opinion. I
know it was developed a while ago, but still after 1.0, I guess? I don't
remember well.

My suggestion for a lead image: Picture of a random street passer-by using
her/his Android phone to take a picture of something that looks very
important/historical.
We can use that same image as the Play banner instead of the mushrooms, by
the way.

Nearby is a bit sub-par for prime time, I believe. Any volunteer to replace
my horrible CSV-download hack by a query to Wikidata as described at
https://github.com/commons-app/apps-android-commons/issues/289 ? I would do
it but my IDE is totally broken and I somehow did not managed to fix it
last time I tried.

Maybe add a small paragraph about why the app is so much needed? Like, more
and more people have a smartphone but no computer, people don't have time
so better allow them to upload wherever they happen to need to kill time,
fresher images, etc.

**Comment by misaochan** [comment]
@nicolas-raoul I didn't mention location-based category suggestions because those were published in a blog post after my Outreachy internship. But good point - maybe people have forgotten anyway, so we can just include that?

The lead image you suggested sounds good. Will just have to look for one with an open license (I'm guessing any image acceptable for Commons use should be acceptable for the blog picture, we don't need to take it by ourselves?)

The switch to Wikidata would be great if anyone has the time to do it. We can always change our hacakthon project to the map instead, if someone manages to do it before the hackathon.

What issues are you experiencing with your IDE?

Will add the paragraph suggested. I need to figure out a way to do it in a less-promotion-y style though, as required by the [blog guidelines](https://meta.wikimedia.org/wiki/Wikimedia_Blog/Guidelines) (no blatant promotion).

**Comment by misaochan** [comment]
I've updated the draft based on the points made by @nicolas-raoul .

**Comment by tobias47n9e** [comment]
Looks good to me. Is it worth mentioning some community stats? Number of contributors, number of uploads since reviving?

**Comment by misaochan** [comment]
Good point @tobias47n9e , done. The final draft is at https://meta.wikimedia.org/wiki/Wikimedia_Blog/Drafts/Wikimedia_Commons_Android_app:_version_2.0 awaiting Ed's approval.

**Comment by nicolas-raoul** [comment]
Even if you don't integrate that in the press release, some elements that you might want to use when talking about the app, they show how much the Android app is needed:

1. This map that shows how Android is the way to go to reduce Commons' countries gap:
![](https://upload.wikimedia.org/wikipedia/en/1/17/StatCounter_OS_Worldwide_December_2016_map.png)

2. Android is now the most widespread operating system, it made big news 4 days ago when it was announced that Android took over Windows:
http://www.zdnet.com/article/sorry-windows-android-is-now-the-most-popular-end-user-operating-system/

**Comment by misaochan** [comment]
The Wikimedia blog post is out! :) https://blog.wikimedia.org/2017/04/13/commons-android-app-improvements/

Please share and spread the word if you can.

**Comment by misaochan** [comment]
Completed the first round of press notifications - these are for tech blogs that have written about the app before, so it's mostly just a "Hey, this app has been updated" nudge. One of them has gotten back to me so far. 

List of blogs notified in this round:
- Thenextweb (email)
- Engadget (online form)
- Gizmodo (online form)
- rising.globalvoices.org (online form)
- www.addictivetips.com (online form)
- theverge.com (email)

For the next round (tech blogs/magazines/etc that have never written about our app before), I'll probably send a more detailed email to them that explains what the app does and why it's useful. I'm guessing this should be written in a style that's halfway between a "pitch" and a "press release"?

**Comment by misaochan** [comment]
The previous round of press notifications did not go terribly well. Only one of them got back to me at all (globalvoices). I admit I was a little surprised, as I wasn't emailing them out of the blue about a brand new app - this is an app that they have actually written about before. Their old articles still exist and still predominate Google search rankings (with links pointing to a **nonexistent** Google Play store listing :/). But it seems none of them were interested in updating it.

I could possibly stand to improve my pitch, but I also wonder if the lack of 'official' accreditation is part of what's preventing them from taking us seriously. For one thing, I am emailing them with my personal email address (I don't have a @wikimedia email address), so it probably looks less credible.

I wonder if there is any way to get around this and improve for the final notifications round? That will be for blogs/magazines/news sites that haven't written about the app before, so I'm expecting a lower response rate for those.

**Comment by tobias47n9e** [comment]
Did we inquire here yet: https://www.mapbox.com/blog/ ?

**Comment by misaochan** [comment]
@tobias47n9e I could try!
