### ISSUE TITLE
View in (in app) browser

### ISSUE THREAD

**Issue by jidanni** [commons-app/apps-android-commons#4201]
We see a menu item, view in browser. However we're surprised as it turns out it is not a real browser, but it is just the the in-app browser. To finally get to the real browser we need to select even more, one time, view in browser. Therefore perhaps rename this menu item to something like, view in in app browser.

**Comment by madhurgupta10** [comment]
@jidanni I agree it makes more sense to make the change. Pinging @sivaraam @nicolas-raoul @misaochan for their opinion :)

**Comment by sivaraam** [comment]
I'm doubtful if users might perceive that we're shipping a full-blown browser with the app or something like that when they read "in-app browser".

In reality, all we do is use custom tabs to open links. Of course, they do look as if the links open within the app. That's one part of it. But there's another part which makes it difficult for us to use the phrase "in-app" for the menu. That is the fact that the links are actually handled by the browser installed by the user and _not_ by the app. This would be obvious, for example, when the user is logged into Commons on the app but have not logged in on their browser. In this case, they'll view the page as if they're logged out. So, if the user starts a discussion/comments on a talk page whilst viewing the page in the custom tab they'll be doing so as an anon possibly without even realizing that. That's not good.

Of course, there are chances for this misinterpretation even now. But it's very likely to be even more worse if we title the menu as "View page in in-app browser".

**Comment by jidanni** [comment]
OK, then maybe just say "View page".

**Comment by madhurgupta10** [comment]
How about saying "View webpage" instead?

**Comment by sivaraam** [comment]
> How about saying "View webpage" instead?

That sounds better 🙂

**Comment by misaochan** [comment]
I'm good with "view webpage" too.

**Comment by sivaraam** [comment]
I just remembered that the Wikipedia app, also uses text to indicate opening the page of the media in the browser. They're using the "file page" in those places. Here's a screen shot that shows their usage of "file page":

![Screenshot_2021-02-04-10-24-34](https://user-images.githubusercontent.com/12448084/106934900-ba886180-6740-11eb-9793-38b14061c604.png)

So, "View file page" is an alternative suggestion for the menu name that we could use.

**Comment by Bbiswabasu** [comment]
I would like to work on this

**Comment by Vikash174** [comment]
can i work on this issue

**Comment by jidanni** [comment]
Currently tapping the three dots, and then View In  Browser triggers the Android question screen of which app do we want to use, so we choose Chrome. However doesn't open it in Chrome. It just opens it inside the commons app. So it's asking us which application want to use to open it, but then it's ignoring our choice. Or, it's opening it inside Chrome, inside the Commons app.

**Comment by jidanni** [comment]
`intent://commons.m.wikimedia.org/wiki/File%3AStick_stuck_through_%E5%A7%91%E5%A9%86%E8%8A%8B_leaf.jpg#Intent;scheme=https;launchFlags=0x3008000;i.android.support.customtabs.extra.SECONDARY_TOOLBAR_COLOR=-16763027;i.android.support.customtabs.extra.TOOLBAR_COLOR=-15966052;B.android.support.customtabs.extra.EXTRA_ENABLE_INSTANT_APPS=true;end`
