### ISSUE TITLE
Blank Screen Appears on clicking any media after a theme change

### ISSUE THREAD

**Issue by Pratham2305** [commons-app/apps-android-commons#4203]
**Summary:** 

Summarize your issue in one sentence (what goes wrong, what did you expect to happen)
On explore tab, Blank Screen appears on clicking any media after changing the theme in settings.

**Steps to reproduce:** 
1. Go to the Explore tab and click on the More options tab
2. Open Settings from the bottom sheet and then Change the app theme 
3. Now return back to explore tab
4. Open any media from the list.

What did you expect the app to do, and what did you see instead?
Blank Screen appears instead of the media detail view.

**Device and Android version:** 

Device: Pixel 3 emulator, Android 10
 
**Commons app version:**  
3.0.0-debug
Branch: Master, Build Variant: betaDebug.

**Screen-shots:** 

![Screenshot_1611569042](https://user-images.githubusercontent.com/54663429/105692483-7ae19e80-5f24-11eb-972b-d65309e9e0a8.png)

**Would you like to work on the issue?**
Yes

**Comment by Roshan13046** [comment]
> **Summary:**
> 
> Summarize your issue in one sentence (what goes wrong, what did you expect to happen)
> On explore tab, Blank Screen appears on clicking any media after changing the theme in settings.
> 
> **Steps to reproduce:**
> 
> 1. Go to the Explore tab and click on the More options tab
> 2. Open Settings from the bottom sheet and then Change the app theme
> 3. Now return back to explore tab
> 4. Open any media from the list.
> 
> What did you expect the app to do, and what did you see instead?
> Blank Screen appears instead of the media detail view.
> 
> **Device and Android version:**
> 
> Device: Pixel 3 emulator, Android 10
> 
> **Commons app version:**
> 3.0.0-debug
> Branch: Master, Build Variant: betaDebug.
> 
> **Screen-shots:**
> 
> ![Screenshot_1611569042](https://user-images.githubusercontent.com/54663429/105692483-7ae19e80-5f24-11eb-972b-d65309e9e0a8.png)
> 
> **Would you like to work on the issue?**
> Yes

It works fine on the Samsung J7 Android device.

**Comment by Roshan13046** [comment]
@Pratham2305 
It works fine on Android devices.
My device: Samsung j7 Prime

**Comment by Pratham2305** [comment]
That's strange, I can still reproduce it, here a video

https://user-images.githubusercontent.com/54663429/106320707-3eea6880-6299-11eb-82d5-f069cb429915.mp4


@Roshan13046  can you just confirm that you have also followed the same steps? Thanks!

**Comment by Roshan13046** [comment]
@Pratham2305 I followed the steps mentioned in the above video. Yes, this issue exists.

**Comment by madhurgupta10** [comment]
@Pratham2305 Thanks for reporting the issue, feel free to work on it

**Comment by nicolas-raoul** [comment]
I confirm that the issue still exists in the latest master.
