### ISSUE TITLE
Add link to website in main menu

### ISSUE THREAD

**Issue by jidanni** [commons-app/apps-android-commons#4209]
Okay, perhaps the app cannot do the job for a certain file. Or, maybe we are just bored. So now we want to go to the Commons website upload page. Well there in the main three bar menu there should be a link to that page. That link should simply launch a browser like Google Chrome that would take us there.

**Comment by jidanni** [comment]
Not sure if that link should go to the commons main page, or the commas upload page. You guys decide. Also how it should be titled you guys decide also. But it should be there in the main menu because it's the granddaddy of this program you might say.

**Comment by jidanni** [comment]
Maybe it should be called Website. Anyway there's no other way to get there, without at least three clicks, otherwise from within the app.

**Comment by aakashgoel2002** [comment]
The link can be attached in the Commons Logo which appears after clicking the three-bar menu, and according to me, the link should be of Commons Main Page as it doesn't symbolize upload. Can I work over this issue?

**Comment by nicolas-raoul** [comment]
Does the Wikipedia app has something like this? If yes, could you please post screenshots showing all steps to go from the app's main screen to the website?

Right now you can go to About, tap the earth icon, then on that website tap the Wikimedia Commons hyperlink.

@aakankshaa23 Please read https://github.com/commons-app/commons-app-documentation/blob/master/android/Volunteers-welcome!.md#developers especially the part about the "bug" label :-) Thanks!

**Comment by jidanni** [comment]
> Does the Wikipedia app has something like this?

I'm not sure. Other reporters perhaps can install it and see. My phone is off today.

> Right now you can go to About, tap the earth icon, then on that website tap the Wikimedia Commons hyperlink.

Sounds rather hidden / obscure.

Like [the mobile websites' highest menu level](https://phabricator.wikimedia.org/T274744), important stuff is right there.

**Comment by Rishavgupta12345** [comment]
@nicolas-raoul we already have this feature in about option so we can close this issue now
