### ISSUE TITLE
Swiping on the last item in explore featured tab takes you to uploaded via mobile.

### ISSUE THREAD

**Issue by 4D17Y4** [commons-app/apps-android-commons#4215]
**Summary:** 

When you swipe on the last item in explore featured fragment it gets to uploaded via mobile.

**Steps to reproduce:** 
go to the last item of the featured tab and swipe left, you'll notice you're taken to uploaded via mobile.
* this issue also exist in bookmark fragment.

What did you expect the app to do, and what did you see instead?

This is not the major issue but when we click on media in this uploaded via mobile tab, the app shows some unexpected behavior when returning from the media details.

**Device and Android version:** 

Nokia 6.1 android version 10 (stock).
**Commons app version:** 

Latest master.

**Screen recording**

![ezgif com-resize](https://user-images.githubusercontent.com/54016427/107181822-9ad39080-6a01-11eb-8e3d-0c184271c901.gif)

Observations:
* First we can see that 'Uploaded from mobile/featured' tabs are not there.
* Media details work perfectly fine.
* On returning from details 'Uploaded from mobile/featured' tabs are restored.
* On switching to featured we see that the list fragment is replaced by the view pager which does not allow vertical scroll between items although scrolling horizontally is possible as in view pager.

**Would you like to work on the issue?**

Please let us know whether you want to fix the issue by yourself. If not, anyone can get the issue assigned to them.
Yes.

**Comment by 4D17Y4** [comment]
@misaochan ,
Assign me this one.
I'll fix it and also the crash on tapping the last item which seems to show up again, once and for all. As these, both issues are linked ill fix them in one pr.

**Comment by 4D17Y4** [comment]
For the solution part, 
I'm thinking of restricting the user from swiping to get to the 'uploaded from mobile' that will remove any abnormal behaviour on returning or tapping an item.
@nicolas-raoul , @madhurgupta10 for suggestions.

**Comment by madhurgupta10** [comment]
@4D17Y4 Hi, could you please add a screen recording of the current behaviour?

**Comment by 4D17Y4** [comment]
@madhurgupta10, I've updated the issue, added the recording.
The major issue is the last one according to me.

**Comment by madhurgupta10** [comment]
@4D17Y4 Thanks for the details, this happens only when there is no network or slow network and async loading isn't continuing in the background.

Feel free to work on it if you are not working/assigned any other issue at the moment.

**Comment by 4D17Y4** [comment]
> this happens only when there is no network or slow network and async loading isn't continuing in the background.

I don't find any connection with network and the view pager nested swipes not configured properly.
Can u explain it , it'll help me in tackling the issue efficiently. 


Will start working on it .
Thx.

**Comment by nicolas-raoul** [comment]
I can reproduce the issue even with a good mobile connection, if I swipe very fast for a minute.
Maybe I have to swipe faster than the next page loads.

**Comment by 4D17Y4** [comment]
Yes, @nicolas-raoul 
U can see this issue in bookmarks too where loading isn't an issue if u haven't bookmarked many of them.
I have linked a PR that solves the issue in both explore and favorites fragment.
Waiting for review and suggestions ; )

**Comment by Pratham2305** [comment]
@nicolas-raoul  @madhurgupta10  I think this issue still exists, I can reproduce it on the latest master.

**Comment by 4D17Y4** [comment]
Hey @Pratham2305, the issue still exist.
I've gone through the code and I believe a commit under #4446 made some change that affected the PR fix.

Code from current master
https://github.com/commons-app/apps-android-commons/blob/c6f4649fcf1e95f84f1e58c4e8a569871af821de/app/src/main/java/fr/free/nrw/commons/explore/ExploreListRootFragment.java#L111-L117

As one can notice 
`((ExploreFragment) getParentFragment()).setScroll(false);`
is missing.

A quick fix would be to add this line. 
I think It would be good to take a look at the specific commit that did the change just to be sure.

**Comment by Pratham2305** [comment]
@4D17Y4 Thanks for pointing out, I have checked the commit, and Yes that is the only line missing. Now it's working fine!
