### ISSUE TITLE
In-App notifications appear on media detail fragment

### ISSUE THREAD

**Issue by Pratham2305** [commons-app/apps-android-commons#4218]
**Summary:** 
In-App notifications appear on media detail fragment after coming back from zoom image activity.

**Steps to reproduce:** 
On Contribution Tab, Open any media details then click on the image and now return back to the media detail page.

What did you expect the app to do, and what did you see instead?
These should not appear on the media detail fragment.

**Device and Android version:** 
Device: Pixel 3 emulator, Android 10
 
**Commons app version:** 
Latest Master

**Screen-shots:** 
![Screenshot_1612687305](https://user-images.githubusercontent.com/54663429/107141398-75d21580-694e-11eb-9588-c5141779d01c.png)

**Would you like to work on the issue?**
Please let us know whether you want to fix the issue by yourself. If not, anyone can get the issue assigned to them.
Yes

**Comment by nicolas-raoul** [comment]
Well spot!
Since you already have an issue assigned, I leave this one unassigned. When you have no issue assigned, please ask us to assign you, thanks :-)
