### ISSUE TITLE
App crashes in ExploreListRootFragment 

### ISSUE THREAD

**Issue by mrudultora** [commons-app/apps-android-commons#4224]
**Summary:** 

On clicking the last image in **ExploreListRootFragment** the app crashes with **IndexOutOfBoundsException**

**Steps to reproduce:** 

• Go to Explore tab from Bottom Navigation Bar.
• Clicking on the last image in Featured tab causes the app to crash.

**System logs:**

> 2021-02-12 13:11:00.128 26125-26125/fr.free.nrw.commons.beta E/AndroidRuntime: FATAL EXCEPTION: main
    Process: fr.free.nrw.commons.beta, PID: 26125
    java.lang.IndexOutOfBoundsException: Index: 10, Size: 10
        at androidx.paging.PagedStorage.get(PagedStorage.java:138)
        at androidx.paging.PagedList.get(PagedList.java:410)
        at fr.free.nrw.commons.explore.media.PageableMediaFragment.getMediaAtPosition(PageableMediaFragment.kt:49)
        at fr.free.nrw.commons.explore.ExploreListRootFragment.getMediaAtPosition(ExploreListRootFragment.java:127)
        at fr.free.nrw.commons.media.MediaDetailFragment.onResume(MediaDetailFragment.java:293)
        at androidx.fragment.app.Fragment.performResume(Fragment.java:2747)
        at androidx.fragment.app.FragmentStateManager.resume(FragmentStateManager.java:363)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1197)

**Device and Android version:** 
• Device (Redmi Note 7S)
• Android (Android 10)

**Screenshots**

https://user-images.githubusercontent.com/65870389/107845041-8d9e1380-6dfe-11eb-897f-c0f3206af66b.mp4

**Would you like to work on the issue?**
I want to work on this issue.

**Comment by nicolas-raoul** [comment]
Strange, I am not able to replicate this issue.
Does this happen all the time, or only sometimes?
Is there a trick to make it happen more often, for instance use a slow Internet connection, or any other trick?
Thanks! :-)

**Comment by mrudultora** [comment]
@nicolas-raoul No it's not due to slow internet connection. Go to explore tab. Scroll down fastly and open the last image immediately. The next few images must be loading at that time (this is important). This bug also is present in current beta version on play store. I hope you will be able to produce this bug by the above steps :-)

**Comment by mrudultora** [comment]
Also, it's happening in both logged in and not logged in !

**Comment by 4D17Y4** [comment]
Yes, @nicolas-raoul,
Can confirm this issue does not exist on the current master,
Moreover, there is a very similar closed issue #4186.

@mrudultora, you can follow the discussion there, although I was not able to point to the commit that fixed it.
https://github.com/commons-app/apps-android-commons/issues/4186#issuecomment-772615882


If the PR fixes another issue link it to that specific issue, or open a new issue we'll be glad to review it.

This can be closed now ; )
Thanks.

**Comment by mrudultora** [comment]
@4D17Y4 The issue you mentioned gives a **NullPointerException**. The issue I mentioned is giving **IndexOutOfBoundsException**. So I guess, this is a valid issue ;-)

**Comment by nicolas-raoul** [comment]
@mrudultora Are you able to reproduce the issue on the latest master?

**Comment by mrudultora** [comment]
@nicolas-raoul I was on latest master. But, I am trying today and it's not crashing. On clicking the last item the index is not exceeding the size of list today (I was logging the index).

**Comment by neslihanturan** [comment]
If this issue is still valid and someone tries to solve this, please make sure to look at comments on closed PR #4225 to see @mrudultora 's investigation.

**Comment by nicolas-raoul** [comment]
I believe this is fixed. If not please reopen, thanks! 🙂
