### ISSUE TITLE
Opening notifications in "Read" section still marks them as read and removes them from the list.

### ISSUE THREAD

**Issue by 4D17Y4** [commons-app/apps-android-commons#4230]
**Summary:** 

On tapping a notification in read section of notifications, the app behaves as if in unread section and marks the notifications as read, removing them from the list.

**Steps to reproduce:** 
* Go to read the section in the notification.
* Tap on an item to view it.
* Get back to see notification removed from read section.

What did you expect the app to do, and what did you see instead?
Notification should not be removed.

**Device and Android version:** 
Nokia 6.1+ android 10 stock.
 
**Commons app version:** 
Latest master.

**Would you like to work on the issue?**

Yes.

**Comment by nicolas-raoul** [comment]
I can reproduce that on latest master indeed, good find!

**Comment by nicolas-raoul** [comment]
Since you already have an issue assigned, please ask when you want to work on this one and we will assign you, thanks :-)

**Comment by 4D17Y4** [comment]
I can work on this one now.
I will start as soon as assigned ; )
