### ISSUE TITLE
Alternative solution to view binding other than ButterKnife

### ISSUE THREAD

**Issue by veyndan** [commons-app/apps-android-commons#424]
Disclaimer: this is a copy-paste from #395 as it seems that I was late to the discussion and I feel that my points warranted a separate issue.

One problem with using Butterknife (though minor) is that the fields must be at least package-private, which means the scope is unnecessarily broad in some circumstances.

An alternative that I am currently using in one of my projects is to use the generated view binder found using the data binding. Using this doesn't mean that you have to use any of the features of the data binding library (nor would I advocate for such a thing). The main benefit that I found using the generated view binder is that it is type safe, something that neither Butterknife nor the standard Android `findViewById` offers i.e. you don't have to cast the `findViewById` to a subclass of `View`.

Jake Wharton (the writer of Butterknife) even says that the use of it can be advantageous ([source](https://www.reddit.com/r/androiddev/comments/54ug8h/no_more_findviewbyid_if_you_havent_started_using/d85uoec/)). [Here](https://medium.com/google-developers/no-more-findviewbyid-457457644885#.evq9g4cul)'s an article which tells you basically all that you need to know about this approach. 

I thought I'd just add this to the discussion as it doesn't get talked about much, but would reduce the boilerplate code even more than that of Butterknife alone, is type safe, and IIRC `findViewById` traverses the layout at runtime whereas using the view binding aspect of databinding, view processing is done at compilation time.

**Comment by maskaravivek** [comment]
Yes, we were unable to complete the discussion on data binding during weekdays. I explored a bit about data binding and the general opinion on it in the community. Let me list the main take aways that i could gather. 

#### Pros:
- can develop things faster
- already present and follows MVVM

#### Cons: 
- merging business logic and xml
- difficult to write unit tests
- Putting expressions inside the XML layout creates a maintenance nightmare

Here are two articles that particularly compare butterknife and data binding and seem to advocate butterknife's usage. 
1. [4 Reasons I’m Not Using Android Data Binding](https://medium.com/@Miqubel/4-reasons-im-not-using-android-data-binding-e62127c2650c#.me69fwn32)
2. [What is data binding and what does it solve?](http://toastdroid.com/2015/07/24/what-is-data-binding-and-what-does-it-solve/)

Moreover [Jake Wharton too doesn't seem to be advocating](https://github.com/JakeWharton/butterknife/issues/269) for data binding approach. 

It would be great if we could get someone who contributes to wikipedia android app to provide insights on why they chose Butterknife over data binding.

**Comment by veyndan** [comment]
I think that I may have not described myself properly. I do not in anyway advocate the merging of business logic and xml as in having expressions inside the XML layout. What I am advocating is to use the functionality of **one** part of the data binding library which is its view binding aspect. An example of this can be found in an app that I am working on where I made such a change in [this commit](https://github.com/veyndan/paper-for-reddit/commit/aafd408f3bd4f5e7d4996852968ac3b9c7741006). As you can see the only modification to the XML is that I wrapped it in the layout tag so the view bindings can be generated. Otherwise I am not putting any logic into the XML nor am I following MVVM (that codebase continued to follow MVP after such a change).

I hope this makes more sense, but please say if I haven't explained anything well enough.

**Comment by maskaravivek** [comment]
Right, if we are just talking about the view binding aspect then can we discuss how it compares against butterknife. The general opinion that i found is that it caters to a lot more usecases.

**Comment by veyndan** [comment]
I'm assuming that when you say "it caters to a lot more usecases" the "it" refers to ButterKnife. I can understand that when binding resources it can be beneficial to use ButterKnife still (and possibly for OnClickListener's though I never found I used them personally). That's why it doesn't need to be an either or decision. We could use both these methods in conjunction i.e. the view binding aspect of data binding and any other binding need from Butter Knife.

**Comment by whym** [comment]
Just noting that #409 is getting closer to a merge-able state.

**Comment by misaochan** [comment]
@whym Given that the generated view binder can be used in conjunction with Butterknife, should we merge #409 and just consider the addition later?

**Comment by ilgazer** [comment]
It seems that the project has settled on Butterknife and the generated view binder hasn't seen any use.
