### ISSUE TITLE
Correct spell error in the message shown when app crashes

### ISSUE THREAD

**Issue by Anu-123-gif** [commons-app/apps-android-commons#4241]
**Summary:** 
The error message shown when the app crashed had a few spelling errors.

**Steps to reproduce:** 
I gave location access to the app then it crashed and I saw the message.

**Device and Android version:** 

What make and model device (e.g., Samsung J7) did you encounter this on?
Redmi Note 5
What Android version (e.g., Android 4.0 Ice Cream Sandwich or Android 6.0 Marshmallow) are you running?Android 4.0 Ice Cream Sandwich
Is it the stock version from the manufacturer or a custom ROM ?
 
**Commons app version:** 
Latest Master

**Would you like to work on the issue?**
Yes

Please let us know whether you want to fix the issue by yourself. If not, anyone can get the issue assigned to them.

**Comment by nicolas-raoul** [comment]
Thanks for noticing! :-)
This file is generated by TranslateWiki, so we should not modify it manually.
I actually noticed the spelling errors too and fixed them on TranslateWiki 2 days ago.
TranslateWiki automatically overwrites these localization files every 3 days: https://github.com/commons-app/apps-android-commons/commits/master?author=translatewiki
More info about localization: https://github.com/commons-app/commons-app-documentation/blob/master/android/Translating-the-app.md
Cheers!

**Comment by nicolas-raoul** [comment]
I will close this for now, sorry about that!
Please do not be discouraged, your PR was perfect otherwise :-)
There are plenty of other bugs to fix, so looking forward to your next pull requests!
