### ISSUE TITLE
Pictures taken with the app and saved locally lack proper EXIF headers

### ISSUE THREAD

**Issue by jidanni** [commons-app/apps-android-commons#4243]
The app should just hand over the picture taking job to the native camera app.

Then take the first picture off the stack when the native app returns.

One day if the user discovers their pictures lack proper headers, they may be disappointed that they can't enter them into various contests, etc.

It simply is a unfortunate loss of data.

**Comment by jidanni** [comment]
In fact, after pressing the "+", if we choose the second button (upload from file), Android asks us anyway if the picture we want to upload should come from the camera (take picture now), or an existing file (in the users Android Gallery etc.).
Therefore, perhaps just have "+" punch the second button automatically for us, eliminating a step, and eliminating the need for a first button, and also always giving us a proper EXIF header (I hope, not tested.)

**Comment by nicolas-raoul** [comment]
I just tested on my Samsung S10, a picture taken using the in-app camera button gets correct geographic depiction suggestions.
Do you get correct depiction suggestions (items near the place where you take the picture)?

**Comment by jidanni** [comment]
As I don't have any great pictures to upload to Commons right now all I can tell you is simply looking in my Android gallery the pictures taken with the app all lack exif headers.

Also the one time I did try to upload one of them there was this weird extra question about location that I normally never stumbled into meaning that Commons website did not know where the picture was taken because it did not have a proper exif header.
Sure I suppose these days there are alternatives to  EXIF headers however it's so easy to make one so why not allow it to get uploaded to Commons?

**Comment by jidanni** [comment]
And, I bet if you compare the final pictures that have ended up successfulyl uploaded, you'll see the ones without exif headers come from directly pushing the snap a picture button on the app.

**Comment by jidanni** [comment]
![Screenshot_20210221-185601.jpg](https://user-images.githubusercontent.com/1230959/108622845-77cfc480-7476-11eb-85d3-e39f385f839f.jpg)
" undeniable proof "

**Comment by jidanni** [comment]
(Okay, turns out when you press the second button Android doesn't ask you if you want it also to take a picture. However it should!)

**Comment by nicolas-raoul** [comment]
Something is unclear in your issue report: Is this about the uploaded file on Commons?
Or is it about the locally saved file which can be created if `Save In-app shots` is enabled?

**Comment by jidanni** [comment]
I was talking about:
> As I don't have any great pictures to upload to Commons right now all I can tell you is simply looking in my Android gallery the pictures taken with the app all lack exif headers.

**Comment by nicolas-raoul** [comment]
Anyone can reproduce this? Please paste the EXIF output of:
1. a picture saved by the app
2. a picture taken directly by your device's stock camera app

**Comment by marcosliberal** [comment]
I also cannot reproduce this issue (tested in a Nokia 7 plus with Android 10 and the commons app from the playstore).

As you can see in the screenshots below that show the EXIF of 2 pictures, 1 saved by the commons app and other taken with the stock camera app, they both have the same EXIF fields with almost the same exact values (except for things like timestamp obviously). They also have location (GPS) information.

<img width="366" alt="Screenshot 2021-03-08 at 17 44 51" src="https://user-images.githubusercontent.com/4533932/110360402-9321fe80-8036-11eb-84db-9e0264f45eea.png">

<img width="366" alt="Screenshot 2021-03-08 at 17 45 18" src="https://user-images.githubusercontent.com/4533932/110360407-961cef00-8036-11eb-9622-3cbff6b88181.png">

**Comment by jidanni** [comment]
OK then I better close this.
