### ISSUE TITLE
Category editing accessible when not logged in

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#4245]
**Steps to reproduce:** 

1. Open the app, latest master
2. Log out
3. Tap "Explore"
4. Tap any picture
5. In the "Categories" section, tap the pencil icon
6. Tap the loop icon
7. Type "Test"
8. Select the "Test" category
9. Tap "Update categories"
10. The UI shows the category as being added
11. Tap `...` and `View file page`, observe that the category has not really been added

The bug is at step 5. If not logged in, the icon should not be present.

**Comment by mrudultora** [comment]
I have opened PRs for all the issues assigned to me. So, can I work on this ?

**Comment by Prince-kushwaha** [comment]
can i work on this issue

**Comment by nicolas-raoul** [comment]
@mrudultora It is yours thanks!
