### ISSUE TITLE
Bookmarks  when user not logged in.

### ISSUE THREAD

**Issue by 4D17Y4** [commons-app/apps-android-commons#4250]
**Summary:** 
U can still bookmark a picture when ur not logged in from the media details.

**Steps to reproduce:** 
Tap on a media in explore or in uploaded from mobile.
Tap on the star to mark it as bookmark.
The app says "Added to the bookmark".

What did you expect the app to do, and what did you see instead?
User should not be able to bookmark the items 
or
We must include a bookmark section for not logged in User.

**Device and Android version:** 

Nokia 6.1+ android 10.
 
**Commons app version:** 

latest master 3.0.0

**Would you like to work on the issue?**
Yes.

**Comment by 4D17Y4** [comment]
According to me, we should remove the bookmark options from the details if a user is not logged in.

I'm also willing to add a bookmark section for the not-logged-in users if that is the solution we all agree on.

@nicolas-raoul , @neslihanturan , @misaochan for suggestions.

**Comment by nicolas-raoul** [comment]
I am in favor of letting non-logged in users have the bookmarks feature, since it is a local only feature.
I don't think there is any plan to synchronize bookmarks using a Wikimedia account.

**Comment by 4D17Y4** [comment]
Yus @nicolas-raoul,
They are not synchronized with an account,
Logout refreshes the bookmarks.

Should I start working on it @nicolas-raoul,
I'm thinking of adding a bottom nav button for bookmarks as in the logged-in version, also as there is no nearby so I don't think we require a location bookmark fragment in there.

**Comment by nicolas-raoul** [comment]
Sounds good, thanks!
