### ISSUE TITLE
when app  theme is Dark  then  CategoryDetailsActivity ,SearchActivity ,WikidataItemDetalActivity, Profile Activity Toolbar color is not change to dark  

### ISSUE THREAD

**Issue by Prince-kushwaha** [commons-app/apps-android-commons#4252]
**Summary:** 
when  app theme is Dark then  CategoryDetailsActivity Toolbar color is not  dark  

**Steps to reproduce:** 

1. Change the App theme to  Dark 
2. Open the CategoryDeatailsActivity and see the toolbar
 
What did you expect the app to do, and what did you see instead?
In Dark theme color of CategoryDetailsActivity Toolbar color change to dark

**Device and Android version:** 
Redmi y3 Api:29

**Commons app version:** 
Latest master (3.0.0)
**Screen-shots:** 
![Screenshot_2021-02-19-23-40-34-391_fr free nrw commons](https://user-images.githubusercontent.com/65972015/108545007-3c65b680-730d-11eb-860b-b5f423ae4dd1.jpg)

![Screenshot_2021-02-20-10-27-48-076_fr free nrw commons](https://user-images.githubusercontent.com/65972015/108584377-c68e3900-7366-11eb-9968-d2c16801fdfe.jpg)

![Screenshot_2021-02-22-22-56-00-834_fr free nrw commons](https://user-images.githubusercontent.com/65972015/108751376-20118600-7568-11eb-983e-7ac6e432b9a2.jpg)

**Would you like to work on the issue?**
YES
Please let us know whether you want to fix the issue by yourself. If not, anyone can get the issue assigned to them.
YES

**Comment by nicolas-raoul** [comment]
This also happens with the search bar in Explore, and the Items (Depictions) activity.
I think they should be all addressed together, as it is the same problem with presumably the same solution.

**Comment by gparap** [comment]
I want to fix the issue

**Comment by Prince-kushwaha** [comment]
@gparap  i am working on this issue

**Comment by gparap** [comment]
ok
