### ISSUE TITLE
Media details activity shows depictions in random languages, rather than in the user's locale

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#4255]
**Steps to reproduce:** 

1. Find a picture that has depictions (there are many in Explore>Uploaded via mobile)
2. Open its media details
3. Finds its depictions
4. Most often they do not match your locale

**Commons app version:** 

Latest master 3.0.0-debug

**Screen-shots:** 

My locale is English, but depiction for [fire engine](https://www.wikidata.org/wiki/Q208281) is shown in [Luxembourgish](https://lb.wikipedia.org/wiki/Pompjeesgefier): "Pompjeesgefier" even though the Wikidata item has a label in English.

![adb](https://user-images.githubusercontent.com/99590/108600114-7d76cd00-73d8-11eb-842a-320e1777acd7.png)
https://commons.wikimedia.org/wiki/File:Fire_truck_in_Tokyo.jpg

The easiest way to investigate is probably to look at the web requests in logcat and see where Pompjeesgefier comes from.

**Comment by Pratham2305** [comment]
Hey @nicolas-raoul, I would like to work on this one.
