### ISSUE TITLE
Clicking on the map again should hide the nearby places list

### ISSUE THREAD

**Issue by Anu-123-gif** [commons-app/apps-android-commons#4263]
**Summary:** 

Clicking on the map again should hide the nearby places list but instead it zooms into the map which is hardly visible.

_Before creating an issue, please search the existing issues to see if a similar one has already been created. You can search issues by specific labels (e.g. `label:nearby`) or just by typing keywords into the search filter._

**Steps to reproduce:** 

Go to nearby screen and click on the hamburger icon on top right .
A list of places will be shown.
Click on the part of the map still visible. 

**Device and Android version:** 

What make and model device (e.g., Samsung J7) did you encounter this on? Redmi Note 5
What Android version (e.g., Android 4.0 Ice Cream Sandwich or Android 6.0 Marshmallow) are you running?Android 4.0 Ice Cream Sandwich 
Is it the stock version from the manufacturer or a custom ROM ?

**Would you like to work on the issue?**
Yes
Please let us know whether you want to fix the issue by yourself. If not, anyone can get the issue assigned to them.

**Comment by 4D17Y4** [comment]
Hey @Anu-123-gif,
Thanks for spotting that.
Apparently, this issue seems quite similar to #2252, which is assigned.
If you have any inputs on the issue you can share them there to help the assignee tackle the issue.

Make sure to check if a similar issue already exists.  ;-)

Thanks.

**Comment by Anu-123-gif** [comment]
@4D17Y4 sorry about that. All the issues that I found were already addressed , apparently I missed checking this one.

**Comment by 4D17Y4** [comment]
Here is a URL that has bugs that are great for newcomers, to help you get started.
https://github.com/commons-app/apps-android-commons/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+no%3Aassignee+-label%3Aassigned+-label%3Adebated+label%3Abug

If you want to work on any issue or have any doubts do leave a comment on the issue,
maintainers will be happy to help.

You can close this issue now ; )
Thanks.

**Comment by Anu-123-gif** [comment]
> Here is a URL that has bugs that are great for newcomers, to help you get started.
> https://github.com/commons-app/apps-android-commons/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+no%3Aassignee+-label%3Aassigned+-label%3Adebated+label%3Abug
> 
> If you want to work on any issue or have any doubts do leave a comment on the issue,
> maintainers will be happy to help.
> 
> You can close this issue now ; )
> Thanks.

Thanks !
