### ISSUE TITLE
Changing language from settings doesn't work

### ISSUE THREAD

**Issue by mrudultora** [commons-app/apps-android-commons#4270]
**Summary:** 

Changing language from settings show us that language has changed but in reality it doesn't changes. There are strings present in **strings.xml** that have translations but they appear in default language (in my case english).
 
**Steps to reproduce:** 
• Go to settings and change language to your preferred language (I selected hindi).
• Then I moved to LoginActivity, but the strings appeared in English.

**System logs:**
None

**Device and Android version:** 
Redmi Note 7S and Android 10.

**Commons app version:** 
3.0.0-debug-master~88be88f25

**Would you like to work on the issue?**
**Yes**, I would work on this.

**Comment by mrudultora** [comment]
@nicolas-raoul Can you confirm this issue ;-)

**Comment by nicolas-raoul** [comment]
Thanks for asking before starting coding!

The setting is called `Default description language`, right?
It only affects the language in which the user enters description, when uploading a picture.
For instance, many Spanish speakers have their UI in Spanish but enter English descriptions so that their pictures are more easily searchable :-)

**Comment by mrudultora** [comment]
@nicolas-raoul  Hi, I was talking about UI. Have a look at the below screenshot. 
![Screenshot_2021-02-23-13-51-05-642_fr.free.nrw.commons.beta.jpg](https://user-images.githubusercontent.com/65870389/108817744-60abe680-75de-11eb-9b3f-dbb8e0cb3e82.jpg)
Like, I have fixed the issue so the strings are appearing in Hindi. The language of UI must change. 
But, in actual I get such a result inspite of changing language.
![Screenshot_2021-02-23-13-51-39-874_fr.free.nrw.commons.beta.jpg](https://user-images.githubusercontent.com/65870389/108818118-ed56a480-75de-11eb-97b3-be46ce766870.jpg)
I want to say that, when I select the language Hindi, the strings of UI are in English. They are not changing. I hope I am able to explain the main issue. Thanks :-)

**Comment by nicolas-raoul** [comment]
Oh, do you mean that you switched Android's system language to Hindi?
