### ISSUE TITLE
Explore Search: No title bar for item, non-existent menu for item, wrongly-worded menu for category

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#4271]
Explore>Search>Items>item lacks a title (maybe white on white?) and three-dot menu containing "View item page":
![adb](https://user-images.githubusercontent.com/99590/108818724-23a31c80-75fd-11eb-91fd-d06fb1baf3ce.png)

It should be like the equivalent category (notice the title "Rabbits" and the three-dot menu containing "View file page"):
![adb](https://user-images.githubusercontent.com/99590/108819177-d96e6b00-75fd-11eb-9637-2c6c1fbf11c9.png)

By the way, for categories "View file page" should be specifically reworded to "View category page".

To see these screens, go to Explore, tap in the search bar, type rabbit, tap either "categories" or "items", then tap the first row

**Comment by Prince-kushwaha** [comment]
can i work on this issue

**Comment by nicolas-raoul** [comment]
@Prince-kushwaha Sure, thanks! Please do not hesitate to ask if I forgot to clarify anything.

**Comment by nicolas-raoul** [comment]
Ah, I noticed that the bar (with many elements this time) is also missing in media details when opening a picture like this:
Explore
Tab "Featured"
Open the media details of any image with a depiction (for instance the recent "American kestrel" image)
Tap a depiction
Tab "Media"
Tap any picture

Directly from "Featured":
![adb](https://user-images.githubusercontent.com/99590/108825754-c01dec80-7606-11eb-885c-11bf653f4890.png)

Via the depiction:
![adb](https://user-images.githubusercontent.com/99590/108825701-b09ea380-7606-11eb-9a6a-ec230ffce9b7.png)
