### ISSUE TITLE
Add link to user guide in About

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#4273]
The user guide (https://commons-app.github.io/docs.html) is currently hard to reach.

The only way to reach it now is via  About>website icon>Documentation

How about a new item "User guide" just below "Tutorial" in the hamburger menu, linking to https://commons-app.github.io/docs.html?

**Comment by misaochan** [comment]
Hmm, personally the docs feel more like "documentation for advanced users" than a "user guide" (which I think would be more like a step-by-step guide on how to use the app, and which we don't currently have). Additionally, the hamburger menu feels quite full already, so IMO we should reserve it for features that most users would use frequently.

How about adding Documentation as a link in About? So it removes one step (they don't have to go to the website to find it). :)

**Comment by nicolas-raoul** [comment]
Indeed that page is very advanced for now, but recently we were asked for documentation for non-advanced features ([Nearby](https://github.com/commons-app/apps-android-commons/issues/4262), [the upload button](https://github.com/commons-app/apps-android-commons/issues/3951)), and I think https://commons-app.github.io/docs.html is where that should go.

Documentation as a link in About sounds good :-)

**Comment by marcosliberal** [comment]
I also like the idea. But if I may make another suggestion, wouldn't it also be nice to have a new button or link in the final page of the Tutorial pointing to the User Guide? The app asks "You think you got it?" and there is only one possible answer. Maybe a "No, show me User Guide" or something like that would make sense.

Either way, can I work on this issue? :)

**Comment by nicolas-raoul** [comment]
@marcosliberal Please note that this is labeled as "enhancement". Do you have 5 bugfixes to meet the requirement described at https://github.com/commons-app/commons-app-documentation/blob/master/android/Volunteers-welcome!.md#developers ? Cheers!

**Comment by marcosliberal** [comment]
Unfortunately not 😄

**Comment by Rishavgupta12345** [comment]
@nicolas-raoul @4D17Y4 i would like to work on this issue please assign me this
