### ISSUE TITLE
Commons isn't responding in Limited connection Mode

### ISSUE THREAD

**Issue by mrudultora** [commons-app/apps-android-commons#4277]
**Summary:** 

Frequently getting the message **_Commons isn't responding_** in Limited connection Mode. 

**Steps to reproduce:** 

How can we reproduce the issue? 
After switching to limited connection mode, I switched to peer review and nearby tab and suddenly the message popped out. Infact, got this once when pausing and resuming upload in limited connection mode.

**Device and Android version:** 
Redmi Note 7S and Android 10.

**Commons app version:** 
3.0.0-debug-master~d6dcd4390.

**Screen-shots:** 
![img](https://user-images.githubusercontent.com/65870389/108998872-88c34480-76c7-11eb-87f9-cebea4eb94d7.jpg)

**Comment by misaochan** [comment]
Ah, looks like an ANR. Would you like to investigate/fix this, @mrudultora ?

As a side note, I think we can probably disable peer review entirely in limited connection mode, since it requires downloading images. @nicolas-raoul what do you think?

**Comment by mrudultora** [comment]
Hi @misaochan my PR for completely hiding peer review in limited connection mode is merged. So that issue is solved ;-)
I tried to debug the cause leading to ANR but  was unable to resolve the issue. I want to work on this issue but I am completely clueless :-(

**Comment by misaochan** [comment]
Pinging @ashishkumar468 for thoughts on this. :)

**Comment by mrudultora** [comment]
@misaochan @ashishkumar468 Yes it's sometimes unrelated to peer review. I am adding logs based on ANR from stacktrace. The best way to produce this ANR is upload a file in limited connection mode and then switch on/off that mode frequently and also try pausing and resuming upload.
From stacktrace reason is :

> Reason: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{673f677 u0 fr.free.nrw.commons.beta/fr.free.nrw.commons.upload.UploadService}
    Load: 7.11 / 6.88 / 6.63

```
2021-03-01 17:47:45.939 1947-1973/? I/ActivityManager: Dumping to /data/anr/anr_2021-03-01-17-47-45-938
2021-03-01 17:47:54.604 1947-1973/? E/ActivityManager: ANR in fr.free.nrw.commons.beta
    PID: 6487
    Reason: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{673f677 u0 fr.free.nrw.commons.beta/fr.free.nrw.commons.upload.UploadService}
    Load: 7.11 / 6.88 / 6.63
    CPU usage from 0ms to 9454ms later (2021-03-01 17:47:45.110 to 2021-03-01 17:47:54.564):
      100% 10313/fr.free.nrw.commons.beta:leakcanary: 63% user + 37% kernel / faults: 1141893 minor 4 major
      23% 1947/system_server: 15% user + 8.4% kernel / faults: 17845 minor 314 major
      23% 765/surfaceflinger: 16% user + 6.9% kernel / faults: 1627 minor 28 major
      19% 2158/com.android.systemui: 16% user + 3% kernel / faults: 7482 minor 387 major
      13% 6487/fr.free.nrw.commons.beta: 10% user + 3.4% kernel / faults: 14694 minor 1214 major
      0.8% 1320/media.codec: 0.5% user + 0.3% kernel / faults: 37257 minor 138 major
      6.4% 27569/com.miui.home: 4.4% user + 2% kernel / faults: 6628 minor 308 major
      5.4% 714/android.hardware.graphics.composer@2.1-service: 2.8% user + 2.5% kernel / faults: 434 minor 31 major
      3.3% 446/mmc-cmdqd/0: 0% user + 3.3% kernel
2021-03-01 17:48:12.647 3333-21372/? W/MQSEventManager: anroccur
2021-03-01 17:48:12.669 1947-10817/? I/DropBoxManagerService: add tag=data_app_anr isTagEnabled=true flags=0x2
2021-03-01 17:48:12.747 3333-3646/? W/AnrEventHandler: Too noisy! skip duplicate anr report:fr.free.nrw.commons.beta now=1614601092747 mLastReportTime=1614601074938 interval=60000

```

**Comment by ashishkumar468** [comment]
Yes, this is unrelated to the Peer Review Service, this is because the Upload Service has does not call startForeground in its onCreate within the permitted threshold. In UploadService#showUploadNotification, we show the notification after querying the contributions which might be taking time in devices with too many contributions or lower-end devices. Most likely this is the issue

**Comment by mrudultora** [comment]
@ashishkumar468

> might be taking time in devices with too many contributions or lower-end devices. 

 I tested this in devices with 3-4 gb ram. Also, this is the second image I uploaded on commons app. 
So, I guess it could be happening frequently in all the devices. And this was happening in peer review also, but as discussed in #3994 the peer review activity was hided. So, it may be happening in peer review service also. I was able to reproduce in that also.

**Comment by ashishkumar468** [comment]
From the logs, this is happening in UploadService
`fr.free.nrw.commons.beta/fr.free.nrw.commons.upload.UploadService`. PeerReview does not have a service, we make normal API calls to get the data, because of the limited connection mode, we might not be downloading the images, fixing that should solve the issue

**Comment by mrudultora** [comment]
@ashishkumar468 Okay ;-) I wasn't much familar with PeerReview details like we make normal API calls to get the data. Are you working on it? If not, I would like to give it a try.

**Comment by ashishkumar468** [comment]
@mrudultora  This issue, "the one with the Service" will be fixed soon as a part https://github.com/commons-app/apps-android-commons/issues/3790, you can pick the go ahead with the current issue :)

**Comment by nicolas-raoul** [comment]
This area of the app has completely changed.
