### ISSUE TITLE
Media details categories editor: Category not actually added

### ISSUE THREAD

**Issue by Prince-kushwaha** [commons-app/apps-android-commons#4278]
**Summary:** 

when Add category to any (image,video) it show in add in categories(MedailDetail)
But when re again open current image  medailDetail it not show in categories its mean it is not upload to database  

**Steps to reproduce:** 
See in Screenshot 

**Device and Android version:** 
Android Device:Redmi 4
API :28
**Commons app version:** 
Latest master (3.0.0)
**Screen-shots:** 

https://user-images.githubusercontent.com/65972015/109042967-cdb29f80-76f6-11eb-9b8c-135ff2ae4829.mp4

**Would you like to work on the issue?**
YES
Please let us know whether you want to fix the issue by yourself. If not, anyone can get the issue assigned to them.
YES

**Comment by Prince-kushwaha** [comment]
@nicolas-raoul  can i work on this issue

**Comment by Prince-kushwaha** [comment]
@nicolas-raoul  @misaochan can i work on this issue

**Comment by misaochan** [comment]
Have you checked to see if the categories were actually added to Commons, by looking at the upload in your browser? That would help figure out if the categories were genuinely not added, or if they were added but there is a bug in media details that does not fetch/display them.

**Comment by nicolas-raoul** [comment]
I tried a few times, and can see that the category is actually not added.
For instance, I added category "Bakeries" to https://commons.wikimedia.org/wiki/File:Last_day_of_Mitsukoshi_at_Ebisu_Garden_Place_8.jpg but I can see nothing recent in history: https://commons.wikimedia.org/w/index.php?title=File:Last_day_of_Mitsukoshi_at_Ebisu_Garden_Place_8.jpg&action=history

**Comment by Prince-kushwaha** [comment]
@nicolas-raoul 
`@FormUrlEncoded
    @Headers("Cache-Control: no-cache")
    @POST(Service.MW_API_PREFIX + "action=edit")
    fun postAppendEdit(
        @Field("title") title: String,
        @Field("summary") summary: String,
        @Field("appendtext") appendText: String,
        @Field("token") token: String
    ): Observable<Edit>
` 
how i test this Post request locally on my browser 
can we explain how this http POST request work and what this POST request return

**Comment by Prince-kushwaha** [comment]
@misaochan @neslihanturan 
`@FormUrlEncoded @Headers("Cache-Control: no-cache") @POST(Service.MW_API_PREFIX + "action=edit") fun postAppendEdit( @Field("title") title: String, @Field("summary") summary: String, @Field("appendtext") appendText: String, @Field("token") token: String ): Observable<Edit>`
how i test this Post request locally on my browser
can we explain how this http POST request work and what this POST request return

**Comment by nicolas-raoul** [comment]
Adding a category means editing the image's page ([example](https://commons.wikimedia.org/w/index.php?title=File:Last_day_of_Mitsukoshi_at_Ebisu_Garden_Place_8.jpg&action=edit)) to append something like `[[Category:Bakeries]]` at the end of it.

Here is the documentation to edit a page: https://www.mediawiki.org/wiki/API:Edit

**Comment by Prince-kushwaha** [comment]
@nicolas-raoul  @misaochan @neslihanturan  what is `csrfTokenClient.tokenBlocking`
or what is csrfToken or token

**Comment by nicolas-raoul** [comment]
@Prince-kushwaha Please first tell us everything you understand about it, so that we can start from there or correct your understanding if needed :-)

**Comment by Prince-kushwaha** [comment]
@nicolas-raoul @misaochan 
`fun appendEdit(pageTitle: String, appendText: String, summary: String): Observable<Boolean> {
        return try {
            pageEditInterface.postAppendEdit(pageTitle, summary, appendText, csrfTokenClient.tokenBlocking)
                .map { editResponse -> editResponse.edit()!!.editSucceeded() }
        } catch (throwable: Throwable) {
            Observable.just(false)
        }
    }`

At runtime when compiler  try to access value of `csfrTokenClient.tokenBlocking` in above code then it thrown the exception 
due which upload category process stop and category does not upload and catch block  return `Observable.just(false)`
so can you tell me what is csrfTokenClient.tokenBlocking
or what is csrfToken or token

**Comment by Prince-kushwaha** [comment]
@nicolas-raoul below code is in file :PageEditClient.kt in actions folder 
```
  fun appendEdit(pageTitle: String, appendText: String, summary: String): Observable<Boolean> {
        return try {
            pageEditInterface.postAppendEdit(pageTitle, summary, appendText, csrfTokenClient.tokenBlocking)
                .map { editResponse -> editResponse.edit()!!.editSucceeded() }
        } catch (throwable: Throwable) {
            Observable.just(false)
        }
    }

**Comment by nicolas-raoul** [comment]
Have you read about CSRF? See https://stackoverflow.com/questions/5207160/what-is-a-csrf-token-what-is-its-importance-and-how-does-it-work
Please add log debug lines, just before the postAppendEdit, and before the equivalent post call used when uploading (which works and probably uses CSRF too).

**Comment by 4D17Y4** [comment]
I can reproduce this on master,
While uploading the categories are added without any issue but adding categories to the images does not work as intended.
Additionally, on add categories dialog, the back button is not configured properly and triggers the back of media detail.

I would like to work on this one if no one is working on it.

**Comment by nicolas-raoul** [comment]
@Prince-kushwaha Since you are working on another issue, I take the liberty to reassign this one, thank you for your understanding :-)
