### ISSUE TITLE
Add light theme

### ISSUE THREAD

**Issue by tobias47n9e** [commons-app/apps-android-commons#428]
As mentioned by @veyndan in https://github.com/commons-app/apps-android-commons/issues/420 the app would benefit from having a light theme for daytime photo trips.

I think that we should keep the dark theme too, for indoor and night time conditions. A switch close to the top level of the UI would be ideal. An example of such a switch is for example in the Twitter app:

![screenshot_2017-03-12-10-46-07](https://cloud.githubusercontent.com/assets/6953323/23830715/9519ad7a-0711-11e7-81a6-0b2bbde42ae5.png)

**Comment by misaochan** [comment]
Agreed, would be nice.

**Comment by neslihanturan** [comment]
I can work on this:)

**Comment by misaochan** [comment]
Nice, thanks @neslihanturan ! :)

**Comment by neslihanturan** [comment]
Currently, it is switching between themes but there is some hardcoded colors which need to be change. To achieve this completely, it is better to remove hardcoded colour codes on xml files. I try to make it convenient with current naming style. Besides, do you have a strict naming strategy to follow? 
Additionally, I need to make up some new colours for light theme. Should we discuss them in a separate thread? If not, I can just set some colours for light theme and change later if you don't like. This option would be much faster.

**Comment by misaochan** [comment]
I'm good with removing hardcoded colour codes, and certainly, by all means choose your own colours. A screenshot after you are done would be good for feedback, I'm sure it will be fine. :)

We don't have a strict naming strategy, but others might want to weigh in on whether or not we want to establish one in the near future.

**Comment by domdomegg** [comment]
Also looks like it would probably be a good idea to tie in with #380, (you can keep working on light theme, just leave the icons for now (or if you could do both in one that would be great)).

**Comment by neslihanturan** [comment]
Yes, I left the icons, waiting for material icons:) Currently @maskaravivek should be working on this issue, if he is busy I can do it too. The toggle theme is done but there is a small problem: the toggle button on overlay menu  appears on the left which looks wrong to me. I am trying to make it on the right side as in Twitter app above. I tried several regular things (and some experimental ones:)) but none of them worked, the button insists to stay on left. Here some screens:
![dark](https://cloud.githubusercontent.com/assets/3127881/23928256/6bff7678-0927-11e7-9995-75fbed03131a.png)
![light](https://cloud.githubusercontent.com/assets/3127881/23928255/6bb64034-0927-11e7-84aa-304bcc55eb34.png)
![light_about](https://cloud.githubusercontent.com/assets/3127881/23928258/6ce319f0-0927-11e7-89dc-584fa92f64d0.png)
![light_upload](https://cloud.githubusercontent.com/assets/3127881/23928257/6c13c6aa-0927-11e7-9892-fbd575f5944c.png)

**Comment by maskaravivek** [comment]
@neslihanturan Yes i am doing the icons. The PR should be up by tomorrow. Great work with the themes (Y)

**Comment by misaochan** [comment]
@neslihanturan nice work! Have you tried asking on StackOverflow about the toggle? I've found them very useful for cases like this (where you have already tried a few methods that aren't working). You might also want to post snippets of the code that you tried.

**Comment by maskaravivek** [comment]
Are we sure that we want the theme switch toggle in the main menu. Should it not belong to the Settings page?

**Comment by nicolas-raoul** [comment]
I see it being used more often than other settings. Use cases:
- People who never switch
- People who switch for stylistic reasons, once and probably never again
- People who switch twice per day (day, night)
- People who switch many times per day, for instance indoor/outdoor

**Comment by misaochan** [comment]
I would vote for it being in the main menu - like Nicolas says, it would likely be changed more often than other settings.

**Comment by neslihanturan** [comment]
I didn't ask it to stackoverflow because it would be duplicate (or even quad-licate:)) but none of the answers worked in our app. I will re-try the answers again today (in case I made a mistake ). If it fails, I will ask. 
I am waiting for your PR @maskaravivek then I can arrange them for the icons too. 
I also think being in the main menu is better (Settings page would be easier though:)).

**Comment by domdomegg** [comment]
Could you push what you've currently got to Github so maybe we could suggest a solution?

**Comment by neslihanturan** [comment]
This would be great. Here my commits: https://github.com/neslihanturan/apps-android-commons/commits/addThemeToggle and I included what did I try after these stackoverflow posts:
http://stackoverflow.com/questions/11368260/menu-resource-item-position-title-to-left-of-icon
http://stackoverflow.com/questions/19562344/can-we-have-an-icon-on-right-side-of-text-in-menu-item-in-android
http://stackoverflow.com/questions/26756826/how-to-display-the-icon-of-the-right-side-of-the-text-in-an-menuitem-in-android
http://stackoverflow.com/questions/29076437/android-menuitem-in-actionbar-with-icon-and-text-how-to-align-icon-to-right

**Comment by neslihanturan** [comment]
@maskaravivek Thanks for great job:) I added black icons too for light theme. The app looks quite cool now. Our only problem is still toggle button being on the left side. I am preparing stackoverflow post now, I will pull request when it is solved. 
Here is the code: https://github.com/neslihanturan/apps-android-commons/tree/addThemeToggle
And here are screens:
![selection_008](https://cloud.githubusercontent.com/assets/3127881/24002426/6169a89e-0a69-11e7-8838-8f62d1ee6604.png)
![selection_007](https://cloud.githubusercontent.com/assets/3127881/24002425/611ca080-0a69-11e7-98a3-3c5f24d434f5.png)
![selection_006](https://cloud.githubusercontent.com/assets/3127881/24002427/623ced44-0a69-11e7-8f3c-259ae5faf4c1.png)

**Comment by domdomegg** [comment]
Tiny niggle: could the license selector dropdown arrow in the upload screen be white as well - probably a good idea to do this on main theme as well actually.

**Comment by domdomegg** [comment]
Thoughts about these proposed color changes? (https://github.com/neslihanturan/apps-android-commons/pull/1)

Main background: #ffffff
Action bar: #0c609c
Satus bar: #08436d
Action bar text and icons: #ffffff
Fragment categorisation background: #AA000000 (same as dark)

Screenshots:
![screenshot_20170316-210244](https://cloud.githubusercontent.com/assets/4953590/24018553/4c35f5ae-0a8c-11e7-8cd4-234d0da03f7a.png)
![screenshot_20170316-210320](https://cloud.githubusercontent.com/assets/4953590/24018606/745752d0-0a8c-11e7-9f3b-3eaa3f3f4083.png)
![screenshot_20170316-210326](https://cloud.githubusercontent.com/assets/4953590/24018607/74627e30-0a8c-11e7-9dd7-1e41df632fdc.png)
![screenshot_20170316-210252](https://cloud.githubusercontent.com/assets/4953590/24018783/45ce29b0-0a8d-11e7-8696-568994a4985b.png)
![screenshot_20170316-210309](https://cloud.githubusercontent.com/assets/4953590/24018611/74aedf64-0a8c-11e7-842d-80ede6e6b7ce.png)
![screenshot_20170316-210314](https://cloud.githubusercontent.com/assets/4953590/24018609/74772a9c-0a8c-11e7-9659-c9903358a372.png)
![screenshot_20170316-211417](https://cloud.githubusercontent.com/assets/4953590/24018888/a2f6528e-0a8d-11e7-8eb6-da33762a441e.png)

**Comment by domdomegg** [comment]
Actually I think a white background for `MediaDetailFragment` could look good, will check it out later.

**Comment by domdomegg** [comment]
Fixed dropdown bug in https://github.com/neslihanturan/apps-android-commons/pull/2

**Comment by domdomegg** [comment]
Thoughts on white background? I think it looks particularly good for transparent images (especially diagrams - see #102)

![screenshot_20170316-223349](https://cloud.githubusercontent.com/assets/4953590/24021621/bb44c292-0a99-11e7-874b-b1f0b3d88365.png)
![screenshot_20170316-223356](https://cloud.githubusercontent.com/assets/4953590/24021620/bb227e76-0a99-11e7-9163-c30ea801da11.png)
![screenshot_20170316-223404](https://cloud.githubusercontent.com/assets/4953590/24021619/bb03e63c-0a99-11e7-81e3-3cf690ccd22c.png)
![screenshot_20170316-223903](https://cloud.githubusercontent.com/assets/4953590/24021617/bae08a84-0a99-11e7-9fff-db9969bb5776.png)

**Comment by domdomegg** [comment]
(Last comment for today, I promise)

That toggle icon has defeated me - don't think it's possible to have it on the right without rewriting the entire menu class. Might be a good time to think about switching to a navigation drawer anyways, would make the app feel more modern (also some discussion on this in: #251, #324, https://github.com/misaochan/apps-android-commons/tree/nav-drawer-hamburger, #420). If doing that getting the [baseline grid](https://material.io/guidelines/layout/metrics-keylines.html#metrics-keylines-keylines-spacing) sorted too would be great - @veyndan also recommended this in #420.

If anyone knows much about design perhaps you could create a few mockups - I was thinking a potential overhaul of `fragment_media_detail` to be more - material-ly?

**Comment by misaochan** [comment]
@domdomegg I'm pretty hopeless at design, but the screenshots that you posted look good to me. :)

I agree, if the toggle icon in the Action Bar is proving to be difficult to fix, we should work around it. There are two options, in my opinion: (1) Implement the nav drawer and place it there, or (2) if the nav drawer is proving to be difficult as well, as a last ditch resort just put it in Settings first so we can release the work you guys have already done while we work on that.

**Comment by maskaravivek** [comment]
I agree with @domdomegg. Lets get this merged soon so that we meet our one week target for starting the publicity with the new designs. :)

**Comment by neslihanturan** [comment]
It looks like I am at cross time hours with most of you:) Thanks @domdomegg for the fixes. So firstly I choose option 1 and start to work on nav drawer.

**Comment by veyndan** [comment]
My 2 cents on the hamburger icon is not to do it, based on [user studies](https://www.nngroup.com/articles/hamburger-menus/). It feels extremely unnecessary as there aren't many options to consider in the toolbar anyway.

**Comment by domdomegg** [comment]
@veyndan The article you linked talks about a hamburger menu on desktop websites, which I agree aren't sensible. However on Android it is well understood I think, although I was able to find no evidence either way in native apps.

It may be worth just moving the toggle into settings temporarily until we can get it resolved to push it out early, as @misaochan suggested.

I'll create another pull req to @neslihanturan's repo with the white background - was that ok with everyone?

**Comment by neslihanturan** [comment]
I am ok to move it settings temporarily and discuss permanent solution on other thread later. @domdomegg when you fix rhe white background, I can carry the toggle button to settings activity as simple checkbox.

**Comment by misaochan** [comment]
Sounds good to me. :)

**Comment by neslihanturan** [comment]
I am asking to make it sure, how should the process run:
1 - When user clicked to check box, the settings activity re-start with new theme.
2- When user clicked to check box, nothing has changed at current activity. When user switch to another activity, it can start with new theme.

**Comment by veyndan** [comment]
@domdomegg Oops, I must have linked the wrong article. The one that I was thinking of was one written by Luke Wroblewski who is a product director at Google. [Here's](http://www.lukew.com/ff/entry.asp?1945) the article I meant to link.

**Comment by veyndan** [comment]
@neslihanturan Personally I'd side with 1 as it is more obvious from a user perspective that tapping the checkbox actually did something as with option 2 the user may be confused and think that tapping the checkbox had no effect.

**Comment by misaochan** [comment]
@neslihanturan I'd go with 1, too.

**Comment by domdomegg** [comment]
Now #440 is merged, can we close this? If we are going to follow up on navigation drawer we could keep it in #251.

**Comment by misaochan** [comment]
Sure, sounds good to me.

**Comment by YoCoB** [comment]
Hi,

I'd like to work on this issue !
