### ISSUE TITLE
Crash when rotating screen on media details (item search)

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#4280]
**Steps to reproduce:** 

1. Tap "Explore"
2. Tap the search button
3. Enter "rabbit"
4. Tap "Items"
5. Tap the "rabbit" item
5. Tap the first image. You are now seeing the media details.
6. Rotate the screen
7. Crash
 
**Commons app version:** 

Latest master

**Comment by Pratham2305** [comment]
@nicolas-raoul I think the issue is similar to #4276, as the system log of the crash are similar

**Comment by nicolas-raoul** [comment]
Thanks a lot for spotting that, @Pratham2305 ! I will close this issue and keep an eye on #4276 :-)
