### ISSUE TITLE
Wrong language pre-selected in Nearby upload

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#4281]
In Nearby I saw the pin for https://www.wikidata.org/wiki/Q48746543 and took a picture of it. When I tapped the + button of the Nearby item and selected my picture, I got this:
![Screenshot_20210301-140112_Commons](https://user-images.githubusercontent.com/99590/109514405-58c1da00-7ae9-11eb-8700-f296892d61b8.jpg)
Problem: Despite the Wikidata item not having an English label, the pre-entered caption/description has language "en". The Chinese label "文庫之森" being picked as a caption is fine, but then the selected language should be Chinese, not "en".

**Comment by 4D17Y4** [comment]
I'd like to work on this one.

**Comment by 4D17Y4** [comment]
I'd like to work on this one ;)

**Comment by nicolas-raoul** [comment]
@4D17Y4 It is yours! This issue is about Wikidata, which is a hot topic recently for Commons. There are a lot of interesting concepts in Wikidata, and I think that this issue is a good way to enter the field. If you have any question please do not hesitate to ask.

First, are you able to reproduce the issue? You can either use a "fake GPS" app or an Android emulator to place yourself geographically near https://www.wikidata.org/wiki/Q48746543, or modify the coordinates of a sandbox Wikidata item such as https://www.wikidata.org/wiki/Q4115189 to put it near you.

**Comment by 4D17Y4** [comment]
Yes, I can reproduce this one.

> There are a lot of interesting concepts in Wikidata, and I think that this issue is a good way to enter the field. 

Excited to work on this one.

> If you have any question please do not hesitate to ask.

Sure.

Thanks.

**Comment by 4D17Y4** [comment]
Hey @nicolas-raoul,

Ive investigated on the issue and found out that in uploadMediaDetails.kt 
https://github.com/commons-app/apps-android-commons/blob/9cf59f78010691b49ec582a4c5defdd534d325d7/app/src/main/java/fr/free/nrw/commons/upload/UploadMediaDetail.kt#L22-L26
We've used default language as the language code for media details (line 23).

This works well when the user wants to enter the caption but does not consider the case when caption is auto filled as in case of nearby upload.

I think if the caption is not null  (i.e. the case from nearby ) we can identify the language using tools and use it in place of language code otherwise we can return the default language as it does now.

Let me know if i'm in right direction.

**Comment by nicolas-raoul** [comment]
Good find!
From where in the code is this constructor called (when coming from Nearby)? That place is the code probably knows what language `place.name` and `place.longDescription` are in.

**Comment by 4D17Y4** [comment]
The constructor is passed an object of Place, here are its variables (no language)

https://github.com/commons-app/apps-android-commons/blob/9cf59f78010691b49ec582a4c5defdd534d325d7/app/src/main/java/fr/free/nrw/commons/nearby/Place.java#L21-L30


This place object is in fact created from an object of NearbyResultItem (generated from JSON received as query result) having these variables-
https://github.com/commons-app/apps-android-commons/blob/9cf59f78010691b49ec582a4c5defdd534d325d7/app/src/main/java/fr/free/nrw/commons/nearby/model/NearbyResultItem.kt#L5-L14


As we can see all of them are nullable ResultTuple-
https://github.com/commons-app/apps-android-commons/blob/9b91eb90958c48ad8c5d915d091f94adcd6ce5fc/app/src/main/java/fr/free/nrw/commons/nearby/model/ResultTuple.kt#L7-L10

The `value` of resultTuple `label` gives us the Place name.

Investigating further I found out that the query does return a language parameter in label
![image](https://user-images.githubusercontent.com/54016427/109793183-5753f700-7c3a-11eb-9bb7-4527ccc48f54.png)
but as we are only considering the value and type in result , the `xml:lang` is lost and we cant use it.

Now only thing left is getting the value of `xml:lang` and storing it for use in upload details.
I tried to access the parameter but as the parameter name contains a color , I cant access it in kotlin variable, I tried using camel case but it didn't help, seems to me the name must be exactly same to access it.

Solution:
I think if possible, we can change the name of variable to camel case in result json, for easy access in ResultTuple.
Or 
I can parse the json and get the required attributes explicitly.

Let me know if I missed something.

**Comment by nicolas-raoul** [comment]
Thanks for the investigation! Passing a `labelLanguage` along with `label` sounds like a good idea.

I am not sure to understand that:

> the parameter name contains a color

We can not change anything server-side, unfortunately.
For your second solution, are you proposing to do the parsing in OkHttpJsonApiClient.java?

**Comment by 4D17Y4** [comment]
> For your second solution, are you proposing to do the parsing in OkHttpJsonApiClient.java?

Yes @nicolas-raoul , was planning on that but I found out a better way to deal with the situation. 

PR for the same ;)
