### ISSUE TITLE
Remove unused strings

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#4284]
`No Image for Depiction` (`depictions_image_not_found` in `app/src/main/res/values/strings.xml`) seems to not be used anywhere. The app builds and runs fine without that string, it seems.

I think we should remove all unused strings, as they make localization less maintainable.

I am sure there are tools to find unused strings (maybe lint?).

**Comment by marcosliberal** [comment]
Hi @nicolas-raoul. I can give it a try if it's ok by you.

**Comment by nicolas-raoul** [comment]
@marcosliberal Thanks! :-)

**Comment by marcosliberal** [comment]
Hi @nicolas-raoul. Just made a pull request with the removed strings I found.

I did it by running an "Unused resources" analysis on strings.xml files with Android Studio. More than 100 strings were found.

**Comment by mksom0803-dot** [comment]
1. 

1. [ ] Fchvfyfg

  

> 

- [ ] @#Gfyfftyfg- [ ### **]//**
