### ISSUE TITLE
Contributions didn't appear after logging in again

### ISSUE THREAD

**Issue by Pratham2305** [commons-app/apps-android-commons#4286]
**Summary:** 

Empty contribution tab appears after you try to login again without closing the app.

**Steps to reproduce:** 

1. Log out from the app
2. Now again try to log in without closing the app
3. Empty contribution tab will appear.

**Device and Android version:** 

Device: Pixel 3 emulator, Android 10
 
**Commons app version:**

Latest Master

**Screen-shots:** 

![Screenshot_1614839622](https://user-images.githubusercontent.com/54663429/109921651-37780e00-7ce2-11eb-8fa8-785106591c52.png)

**Would you like to work on the issue?**
Yes.

**Comment by nicolas-raoul** [comment]
I just tried on latest master. After logout/login for me it is not empty, but it is showing very old contributions, not my most recent contributions (which should be at the top).
