### ISSUE TITLE
Tapping multiple items in explore should not be allowed

### ISSUE THREAD

**Issue by 4D17Y4** [commons-app/apps-android-commons#4287]
**Summary:** 
When tapping on multiple item at the same time the explore fragment is replaced by the media details.

**Steps to reproduce:** 
* Tap on multiple items in explore fragment simultaneously (use two fingers ;-) )
* Go back to the fragment from details ( back ).
* The fragment is replaced by a media detail.

**Device and Android version:** 
Nokis 6.1+ android 10 stock.
 
**Commons app version:** 
3.0.0 debug master.

**Would you like to work on the issue?**
YES.

**Comment by nicolas-raoul** [comment]
I can reproduce on latest master.
Thanks for noticing this, and sorry for the delay!
