### ISSUE TITLE
Fix the UI issue with leaderboard rank number

### ISSUE THREAD

**Issue by madhurgupta10** [commons-app/apps-android-commons#4293]
**Summary:** 
Leaderboard ranking UI isn't properly set for 3 digit rank or more.

**Steps to reproduce:** 
Open leaderboard scroll to 100 or more ranking

**Device and Android version:** 
Xiaomi Mi A2 Android 10
 
**Commons app version:** 
latest prodDebug

**Screen-shots:** 
![Screenshot_20210313-081807](https://user-images.githubusercontent.com/30932899/111016626-05973380-83d5-11eb-82b6-b09eb9e5d374.png)

**Would you like to work on the issue?**
No

**Comment by theankitbhardwaj** [comment]
I would like to work on this issue. Please assign it to me.

**Comment by theankitbhardwaj** [comment]
Thanks. 
Can you help me a bit ? I am new to open source contributions.
Which branch I have to fix the bug for ? I have fixed the bug in master branch though. Thanks in advance.

**Comment by madhurgupta10** [comment]
@theankitbhardwaj You can create a PR for the master branch.

**Comment by theankitbhardwaj** [comment]
Okay thanks. Will create a PR now.

**Comment by theankitbhardwaj** [comment]
#4294
