### ISSUE TITLE
UI Issue: After changing the system theme from settings

### ISSUE THREAD

**Issue by Pratham2305** [commons-app/apps-android-commons#4297]
**Summary:** 

Theme change didn't work properly, as After changing the system theme from settings, the Bottom Navigation bar disappears and the background color is also different.

**Steps to reproduce:** 

1. On Explore/Contribution Tab, Open any Media details

2. Close the app, and Change the System theme

3. Now reopen the app.

**Device and Android version:** 

Device: Pixel 3 emulator, Android 10
 
**Screen-shots:** 

![Screenshot_1616266518](https://user-images.githubusercontent.com/54663429/111882508-02ef9c00-89dc-11eb-8740-3d6976b48796.png)

**Would you like to work on the issue?**
Yes.

**Comment by nicolas-raoul** [comment]
I am able to reproduce this on latest master. Good find!
