### ISSUE TITLE
All GSoC (Google Summer of Code) 2021 candidates: Please read

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#4302]
Do you want to apply for GSoC 2021?

Please read [how to apply to our GSoC](https://github.com/commons-app/commons-app-documentation/blob/master/android/Students.md).

Thank you for your interest, and welcome to the team! 🙂

**Comment by Prince-kushwaha** [comment]
@nicolas-raoul @ Madhur Gupta can you tell me more about this idea( https://phabricator.wikimedia.org/T278015) GSoC 2021 - Commons Android app - Custom pictures selector which indicates what pictures have been uploaded already

**Comment by Prince-kushwaha** [comment]
@madhurgupta10 can you tell me more about this idea( https://phabricator.wikimedia.org/T278015) GSoC 2021 - Commons Android app - Custom pictures selector which indicates what pictures have been uploaded already

**Comment by nicolas-raoul** [comment]
@Prince-kushwaha If you have **specific questions** please feel free to ask here. 🙂
In particular, if some information is missing from https://phabricator.wikimedia.org/T278015 then please let us know and we will add it. Cheers!
