### ISSUE TITLE
Search widget to choose description language

### ISSUE THREAD

**Issue by Prince-kushwaha** [commons-app/apps-android-commons#4307]
**Summary:** 

The list of default Description language is large 
getting bottered to choice to desire language

![Screenshot_2021-03-28-20-12-20-422_fr free nrw commons](https://user-images.githubusercontent.com/65972015/112756266-0c8f8a00-9002-11eb-83e1-0445aa359525.jpg)
 
**Would you like to work on the issue?**
YES
Please let us know whether you want to fix the issue by yourself. If not, anyone can get the issue assigned to them.
YES

**Comment by Prince-kushwaha** [comment]
@nicolas-raoul @madhurgupta10 @misaochan  @ashishkumar468 can i work on this

**Comment by nicolas-raoul** [comment]
Great idea!
By the way, this languages list is unfortunately not ideal.
I suggest making the settings activity reuse the code that shows the languages list when uploading a picture:
![adb](https://user-images.githubusercontent.com/99590/113009202-b6157d80-91b2-11eb-8df2-c1079ce45e1e.png)
To sum up, the task would be:
1. Factorize by making the settings activity use the same code as the upload activity.
2. Add a search widget. Ideally the search widget would work with both the language name (for instance `日本語`) and the language code (for instance `ja`).

What do you think?

**Comment by Prince-kushwaha** [comment]
@nicolas-raoul this idea is great 
can you tell me more about the idea and  how i implement this

**Comment by nicolas-raoul** [comment]
@Prince-kushwaha Please first find the methods where each language list is built (one during settings modification, one during upload). Please post the GitHub link to both lines of code (to create links you can browse the repository on GitHub then click a line).

**Comment by Prince-kushwaha** [comment]
@nicolas-raoul  setting activity use below code to build language list  
it use Java Build class -Locale  to get language list

```

    private List<Language> getLanguagesSupportedByDevice() {
        List<Language> languages = new ArrayList<>();
        Locale[] localesArray = Locale.getAvailableLocales();
        for (Locale locale : localesArray) {
            languages.add(new Language(locale));
        }

        Collections.sort(languages, (language, t1) -> language.getLocale().getDisplayName()
                .compareTo(t1.getLocale().getDisplayName()));
        return languages;
    }

```

And Upload activity use  below code to build langauage list
language list is store language.xml 
```

public List<String> getLocalizedNames() {
        List<String> names = localizedNamesRef.get();
        if (names == null) {
            names = getStringList(R.array.preference_language_local_names);
            localizedNamesRef = new SoftReference<>(names);
        }
        return names;
    }

```
which method is both setting activity and upload activity

**Comment by nicolas-raoul** [comment]
@Prince-kushwaha Thanks a lot!

If Settings is using `getLanguagesSupportedByDevice`, it is clearly a bug. That list depends on the device, so it is not the language list we want (which is: the languages supported by Commons for captions and descriptions).

Would you mind creating a new issue for this bug? Exceptionally you can take it too if you want. Thanks!

**Comment by Prince-kushwaha** [comment]
@nicolas-raoul what i have to add search widget for both setting and  upload activity

**Comment by Prince-kushwaha** [comment]
@nicolas-raoul what i have to add search widget for language list of both setting and upload activity

**Comment by Prince-kushwaha** [comment]
@nicolas-raoul to implement Search view for language list in Upload activity i have to remove AppCompatSpinner and add ListView with searchview in  place of AppCompatSpinner

It is  not possible to add searchWidget for  language list in setting activity becouse we not add searchview in setting activity

So can i continue work to implement search view for language list in upload activity ?

**Comment by Prince-kushwaha** [comment]
@neslihanturan https://github.com/commons-app/apps-android-commons/issues/4307#issuecomment-815809364
So can i continue work to implement search view for language list in upload activity ?

**Comment by nicolas-raoul** [comment]
@Prince-kushwaha Yes thanks!

**Comment by Rishavgupta12345** [comment]
@nicolas-raoul  @4D17Y4  this enhancement is already implemented and working in our app , so we can close this issue
