### ISSUE TITLE
Improvise the design of the Quiz response buttons

### ISSUE THREAD

**Issue by sanjay-thiyagarajan** [commons-app/apps-android-commons#4309]
**Summary:** 
Redesigned the Yes & No radio buttons

**Steps to reproduce:** 
Create a custom drawable layout for the radio buttons to make them look more attractive.

**Device and Android version:** 
Emulated device - Pixel 2 XL 
API 28
 
**Commons app version:** 

3.0.0-debug-master~d0f895416

**Screen-shots:** 

## **Previous**  
![Previous version](https://github.com/sanjay-thiyagarajan/projects/raw/master/Quiz_Question-_commons_app.jpg)  
  
## **Planned design**  
![Planned version](https://github.com/sanjay-thiyagarajan/projects/raw/master/Screenshot_1617085451.png)  

**Would you like to work on the issue?**
Yes

**Comment by sanjay-thiyagarajan** [comment]
@nicolas-raoul  Can I work on this ?

**Comment by nicolas-raoul** [comment]
Thanks for the idea!
I have no strong opinion about this, both the first and second designs look reasonable to me.
With the second design, how about removing the "Next" button? For instance tapping "Yes" would take the user to the next step directly.
In any case this would be labeled as "improvement", which means it can only be implemented after 5 bugfixes: https://github.com/commons-app/commons-app-documentation/blob/master/android/Volunteers-welcome!.md#developers

**Comment by sanjay-thiyagarajan** [comment]
> Thanks for the idea!
> I have no strong opinion about this, both the first and second designs look reasonable to me.
> With the second design, how about removing the "Next" button? For instance tapping "Yes" would take the user to the next step directly.
> In any case this would be labeled as "improvement", which means it can only be implemented after 5 bugfixes: https://github.com/commons-app/commons-app-documentation/blob/master/android/Volunteers-welcome!.md#developers

Yeah. Removing the next button will be good. Can I start working on that ?

**Comment by nicolas-raoul** [comment]
@sanjay-thiyagarajan Please read https://github.com/commons-app/commons-app-documentation/blob/master/android/Volunteers-welcome!.md#developers ? Especially the part about bugfixes. Cheers!

**Comment by Ayan-10** [comment]
@nicolas-raoul can I work on this?

**Comment by nicolas-raoul** [comment]
@Ayan-10 Please avoid issues labeled as `debated` for now. Thanks! :-)

**Comment by Ayan-10** [comment]
@nicolas-raoul ok I will keep that in mind. But I was not talking about fixing this exact issue. In this issue, you commented about removing the "Next" button? For instance, tapping "Yes" would directly take the user to the next step. I was talking about doing this improvement. So can I?

**Comment by nicolas-raoul** [comment]
I see you have 5 merged pull requests already, congratulations! :-)
OK for removing Next.

**Comment by neslihanturan** [comment]
Hi all, next button has a function as "I don't know" button. When you are not sure if the photo is relevant or not, you may need to have a next button to see the next question. If you answer the question, no need to have an additional click to next button, it automatically changes the screen after your answer without using next button. So I am not sure about removing next button.

**Comment by neslihanturan** [comment]
My suggestion would be changing the name of the button from "next" to "I dont know" maybe?

**Comment by Ayan-10** [comment]
Hi @neslihanturan @nicolas-raoul , This idea seems good. I will rename the "next" button "I don't know"
and clicking this button pop up a dialog saying about the image uploadable or not and why and show the next question. Also, I make the Yes/No radio button clickable and according to the users' action, it will react and automatically shows the next question.
Should I move forward with this idea?

Thank you.

**Comment by nicolas-raoul** [comment]
Sounds good to me!
Yes and No can actually be normal buttons rather than radio buttons, and could be placed side-by-side (like in Sanjay's design but maybe with a normal color/shape).

**Comment by Ayan-10** [comment]
@neslihanturan @nicolas-raoul What if I change the name of the button "I am not sure"? and Is the UI of the radio button okay or should I change to a button with normal(square) shape as you proposed me to do in the previous comment?

<img src="https://user-images.githubusercontent.com/71203077/118290654-4a823800-b4f4-11eb-8666-fa6a5d11f32b.png" width=300/>

**Comment by U81-A** [comment]
I'd try to provide my edit to tackle this problem

**Comment by neslihanturan** [comment]
I think radio buttons is not a good approach for this UI. I think this does not improve the current UI. Lets think in terms of user flows:
- As a user I usually expect nothing will happen right after I choose a radio button. It is a selection control, not an action button. But in our scenario next question will appear after user selected one ratio which is unexpected. 
- I can't see any point having "I don't know" button as an action button and "yes"/"no" buttons as control. They should be the same type of element as they are doing the same thing: answering and getting the next question. 

My opinion is that they all should be action buttons. We can style them as contained, outlined or text buttons depending to their hierarchy.

**Comment by Ayan-10** [comment]
@neslihanturan Yes, I also think the same that only text for "yes"/"no" is enough. I think we can use buttons with green for yes and red for no. Should I just make two normal buttons or I think as it is a quiz user may expect any visual response in the button after clicking like in the case of the radio button a circle is filling with white color after clicking. Although It's acted immediately with the answer. So visual response in button may be irrelevant. What you expect in the button UI, Please let me know. How about two buttons with a little circular curved side with relevant color?

**Comment by nicolas-raoul** [comment]
Sorry for the late answer!
I seem to agree with both of you:
- "Yes", "No", "I am not sure" should all be buttons.
- No cross nor tick icon

About other aspects:
- Colors often create unforeseen problems with night mode, so how about standard color (no red/green) for now? Not a very strong opinion though.
- I don't think any special visual response is needed, because as you say the answer comes immediately.

**Comment by Ayan-10** [comment]
@nicolas-raoul Then two simple buttons with normal colors and shape. Is this ok?

**Comment by nicolas-raoul** [comment]
Sounds good!

**Comment by Ayan-10** [comment]
@nicolas-raoul @neslihanturan I made the required changes please review #4382 .
