### ISSUE TITLE
First item Location bookmarks in expanded state.

### ISSUE THREAD

**Issue by 4D17Y4** [commons-app/apps-android-commons#4311]
**Summary:** 

On expanding a location bookmark and switching between pictures and location , the first item in the location bookmark is expanded.

**Steps to reproduce:** 

* Bookmark some pictures and some locations .
* Go to location bookmark and expand a bookmark.
* Swipe to the Pictures section ( Should be loaded ) and then swipe back to the locations. 

**What did you expect the app to do, and what did you see instead?**

The bookmark should not be expanded.

**Device and Android version:**

Nokis 6.1+ android 10 stock.

**Commons app version:**

3.0.0 debug master.

**Would you like to work on the issue?**

YES.

**Comment by 4D17Y4** [comment]
I think we can collapse the location bookmark altogether on switching to pictures section.
Other way we can retain the state of expanded bookmark and correctly show it.

@neslihanturan , @nicolas-raoul for suggestions.

**Comment by nicolas-raoul** [comment]
Indeed something is wrong: When I expand the **second** bookmarked location then swipe left+right, now the **first** bookmarked location is expanded.

Since we remember the scrolled position for Pictures, I personally think we should remember the expansion status for Locations.
