### ISSUE TITLE
ProfileActivity should have a back button

### ISSUE THREAD

**Issue by Ayan-10** [commons-app/apps-android-commons#4312]
**Summary:** 

There should be a back button on the top of ProfileActivity like in Settings and Review Activity.

**Steps to reproduce:** 

* Open app and tap on Hamburger Menu
* Click and open the profile.
* You can see there is no back button
I think ProfileActivity should have a back button like other Activities Like Settings and share

**Device and Android version:** 

Device: Pixel 3a
API: 27
 
**Commons app version:** 

3.0.0-debug-master~d0f895416

**Screen-shots:** 

Profile Activity: Unlike all other activities this activity doesn't have any back button
<img src="https://user-images.githubusercontent.com/71203077/113142109-2a4e3080-9248-11eb-9433-1970bd8d5b97.png" width="300">

**Would you like to work on the issue?**

Yes, I would like to work on this issue. @nicolas-raoul Please assign me.

**Comment by nicolas-raoul** [comment]
It would be a good enhancement indeed.
Also, I think the title should display the username.
Actually, I think there used to be even a three-dots menu allowing people to share their achievements, not sure where it went.

**Comment by Ayan-10** [comment]
That would be a great idea @nicolas-raoul , and I would love to work on this. I think we should move forward one by one and first, we should add a back button because It is looking a little awkward compare to other Activities then we can move forward with displaying the username and fixing the share menu.

**Comment by nicolas-raoul** [comment]
@Ayan-10
Thanks for your interest! Howevere, have you read https://github.com/commons-app/commons-app-documentation/blob/master/android/Volunteers-welcome!.md#developers especially the part about issues labeled "enhancement"?
I suggest focusing on bugs at first :-)
Cheers!

**Comment by Ayan-10** [comment]
@nicolas-raoul can I consider it for GSOC? Actually, I am writing the proposal. So I am just asking.

**Comment by Bbiswabasu** [comment]
@nicolas-raoul if no one is working on this, can I start working?

**Comment by neslihanturan** [comment]
Hi @Ayan-10 , I am afraid that this task can be too easy for GSoC. Do you think it would be suitable? 

@Bbiswabasu thanks for your interest, @Ayan-10 seemed to be interested with this issue. I encourage you to check other issues:)

**Comment by nicolas-raoul** [comment]
@Ayan-10 I agree with Neslihan.

@Bbiswabasu Thanks for your interest! But please carefully read https://github.com/commons-app/apps-android-commons/issues/4312#issuecomment-812873414 :-) Cheers!

**Comment by Ayan-10** [comment]
@neslihanturan I know this task can be too easy for GSoC. That's why I am asking for everyone's opinion. Although I am not only adding a back button but also as you can see in the earlier discussion I want to display username in the title box and also add a share button that allow people to share their achievements. Thank you for the opinion.

**Comment by neslihanturan** [comment]
> @neslihanturan I know this task can be too easy for GSoC. That's why I am asking for everyone's opinion. Although I am not only adding a back button but also as you can see in the earlier discussion I want to display username in the title box and also add a share button that allow people to share their achievements. Thank you for the opinion.

Even if those are nice suggestions, I still think that might be a weak proposal idea. You can take a look at gsoc labelled issues in our repository to inspire from previous years.

**Comment by Ayan-10** [comment]
@neslihanturan @nicolas-raoul I was going through the idealist mentioned here [Task ideas](https://github.com/commons-app/commons-app-documentation/blob/master/android/Students.md#task-ideas). I think I can add some features from Task Ideas to the app. 

> `Edit already uploaded pictures: Edit title/description, add depictions, maybe even add coordinates.`

and

> `In the upload feature, add an activity to crop/blur pictures for privacy purposes (example usages: crop out a passer-by, blur a car's number plate).`

So what do you think now? Should I consider these Ideas for GSoC?

**Comment by nicolas-raoul** [comment]
These 3 tasks would probably take less than a week (two days of development and three days of testing/unit tests/etc max).
GSoC 2021 duration is 10 weeks (a bit shorter than past years when it was 3 months).

**Comment by Ayan-10** [comment]
Thank you so much @nicolas-raoul , for helping. Should I create issues of these task ideas or just write a proposal with these ideas no need to create an issue for that.

**Comment by nicolas-raoul** [comment]
@Ayan-10 No need to create issues, just explain in your proposal. Thanks! :-)

**Comment by Ayan-10** [comment]
@nicolas-raoul As you mentioned in the previous [comment](https://github.com/commons-app/apps-android-commons/issues/4312#issuecomment-812348378). I made the UI of the toolbar like this. Is it ok? 

<img src="https://user-images.githubusercontent.com/71203077/123991584-7ac06000-d9e8-11eb-87a2-570187ac6231.png" width=300/>

**Comment by nicolas-raoul** [comment]
It looks great to me :-)
