### ISSUE TITLE
Hitbox for info in achievement is too small

### ISSUE THREAD

**Issue by 4D17Y4** [commons-app/apps-android-commons#4318]
**Summary:** 

While testing a PR I faced difficulty toggling the info on the fields in the achievement tab.

**Steps to reproduce:** 

Go to the profile section and try toggling the info for any field.

**Device and Android version:** 

Nokia 6.1+ android 10 stock
 
**Commons app version:** 

3.0.0-debug master.

**Would you like to work on the issue?**

YES.

**Comment by 4D17Y4** [comment]
Instead of having a small icon at the top right of the info field we can have the whole field toggle the info dialog. ie tapping on the fields would open the info dialog instead of tapping on the icon.

We can also increase the size of the icon if necessary.

@nicolas-raoul, @misaochan for suggestions.

**Comment by nicolas-raoul** [comment]
You mean that tapping on "Quality images" would open the pop-up that explains what a quality image is, right?
Good idea I think.

Getting rid of the "?" might even solve #3434. As a consequence I think it is fair to let @Ayan-10 (assigned to that issue) work on this if they want, though. What do you think @4D17Y4?

**Comment by 4D17Y4** [comment]
> You mean that tapping on "Quality images" would open the pop-up that explains what a quality image is, right?

Yes, exactly.

> Getting rid of the "?" might even solve #3434. As a consequence I think it is fair to let @Ayan-10 (assigned to that issue) work on this if they want, though. What do you think @4D17Y4?

Sure, as @Ayan-10  is working on it I think it'll be fair to let him solve this.
@Ayan-10 keep us updated on ur progress.

**Comment by Ayan-10** [comment]
Thanks @4D17Y4 @nicolas-raoul , Although I think I solved #3434 , I love to work on this also.
Sure, I will keep you updated on my progress.

**Comment by Ayan-10** [comment]
Should I keep the help icon as it is and make the TextView clickable or Should I remove the help icon? @nicolas-raoul

**Comment by neslihanturan** [comment]
Hey @Ayan-10 it would be amazing if you could add UI screen shoots and explain what you propose :)

**Comment by nicolas-raoul** [comment]
My opinion is that if the labels are visibly tap-able (in other words: user can see that clicking the label will offer some kind of help) then the "?" circles can be removed. But Neslihan is more knowledgeable about UI, so a screenshot or mockup would be great.

**Comment by Ayan-10** [comment]
@nicolas-raoul That's right, but I think If I remove the help icon user can't able to understand that the label is clickable and the label can show a popup.
@neslihanturan I am attaching the screenshots that can explain my thought.

**1. Removing the help icon**: User can click anywhere on the label to see the help popup.
<table>
  <tr>
    <td> Removing the icon ( Look at the "Images via Nearby Places label" ) </td>
     <td> The whole label is clickable</td>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/71203077/113563941-29d9df00-9626-11eb-8914-f690ef9d5215.png"width="300"></td>
    <td><img src="https://user-images.githubusercontent.com/71203077/113563952-2e9e9300-9626-11eb-8471-df08c19398ff.png"width="300"></td>
  </tr>
 </table>
**2. Removing the help icon**: User can click anywhere on the label to see the help popup. No need to click to the small icon now it is clickable from everywhere.
<table>
  <tr>
    <td> Not Removing the icon</td>
     <td> The whole label is clickable</td>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/71203077/113563970-34947400-9626-11eb-8efd-7d0a5373ccb6.png"width="300"></td>
    <td><img src="https://user-images.githubusercontent.com/71203077/113563986-39f1be80-9626-11eb-83cf-e98b085d0b92.png"width="300"></td>
  </tr>
 </table>

**Comment by nicolas-raoul** [comment]
@Ayan-10 Thanks for this well-illustrated explanation, you convinced me that your option 2 is the best.

**Comment by Ayan-10** [comment]
Thank you so much @nicolas-raoul for your appreciation, Should I make a PR now?

**Comment by nicolas-raoul** [comment]
Let's wait a bit for Neslihan's insight.

**Comment by Ayan-10** [comment]
Hey @neslihanturan , Can you kindly give your insight on this so that I can proceed further.

**Comment by neslihanturan** [comment]
Thanks for the mockups @Ayan-10 , I agree we should go with option 2. Otherwise it is not clear that labels are clickable and there is a way to get help.

**Comment by madhurgupta10** [comment]
Hi, I wanted to link https://github.com/commons-app/apps-android-commons/issues/3441 here.

**Comment by Ayan-10** [comment]
Hey, @madhurgupta10 I think I did the same thing that @maskaravivek said in #3441 . Please tell me should I have to change something or is it ok?
