### ISSUE TITLE
Setting Language list is not an language list which is supported by Commons for caption and description

### ISSUE THREAD

**Issue by Prince-kushwaha** [commons-app/apps-android-commons#4321]
**Summary:** 

Settings langauge list is using `getLanguagesSupportedByDevice`, it is clearly a bug. That list depends on the device, so it is not the language list we want (which is: the languages supported by Commons for captions and descriptions).

Upload language list which is languages supported by commons for caption and description

_Originally posted by @nicolas-raoul in https://github.com/commons-app/apps-android-commons/issues/4307#issuecomment-812874617_

**What did you expect the app to do, and what did you see instead?**
Setting languages  list is same as Upload langauge list  

**Device and Android version:** 
Android Device :Redmi y3
API :29

**Commons app version:** 
Latest master 

**Would you like to work on the issue?**
Yes

**Comment by Prince-kushwaha** [comment]
@nicolas-raoul can i  work on this

**Comment by nicolas-raoul** [comment]
Yes thanks! :-)
