### ISSUE TITLE
Screwed batch upload

### ISSUE THREAD

**Issue by kozuch** [commons-app/apps-android-commons#4326]
Upload to this category

https://commons.wikimedia.org/wiki/Category:Josefovsk%C3%A9_louky

was largely screwed. 42 images selected, about 60 uploaded - many multiple times.

Filename pattern was
Ptačí park Josefovské louky (Josefov Meadows) ##.jpg

All images kept failing uploading so I had to restart them manually which probably caused the duplicates.

First image
https://commons.wikimedia.org/wiki/File:Pta%C4%8D%C3%AD_park_Josefovsk%C3%A9_louky_(Josefov_Meadows).jpg
Last image
https://commons.wikimedia.org/wiki/File:Pta%C4%8D%C3%AD_park_Josefovsk%C3%A9_louky_(Josefov_Meadows)_61.jpg

-- Technical information --
API level: 29
Android version: 10
Device manufacturer: Xiaomi
Device model: Redmi Note 9 Pro
Device: joyeuse
Network type: wifi
App version name: 2.13.2~757c7b008
User name: Kozuch

**Comment by nicolas-raoul** [comment]
Sorry for the duplicates issue! It happened to me as well. Fortunately, it has been fixed in the latest version :-)
