### ISSUE TITLE
On Nearby Fragment Place type SearchView is not visible properly in lower API devices

### ISSUE THREAD

**Issue by Ayan-10** [commons-app/apps-android-commons#4327]
**Summary:** 

On Nearby Fragment Place type SearchView is visible properly in higher API devices like API 27 but Place type SearchView is not visible properly in lower API devices like API 23.

**Steps to reproduce:** 

1. Run the app in any lower API device like API 23.
2. Go to Nearby
3. Click Place type search icon

What did you expect the app to do, and what did you see instead?

Search View should visible for every API device.

**Device and Android version:** 

**Device:** OPPO A57 || **Version:** 6.0.1
**Device:** Samsung J2 || **Version:** 6.0.1
**Device:** Pixel 3a || **Version:** 8.1
 
**Commons app version:** 

3.0.0-debug-search~d0f895416

**Screen-shots:** 

<table>
  <tr>
    <td> Samsung J2 ( version = 6.0.1 )</td>
     <td> OPPO A57 ( version = 6.0.1 )</td>
     <td> Pixel 3a ( version = 8.1 )</td>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/71203077/113539820-4103d700-95fc-11eb-867b-1619298306e8.png"width="300"></td>
    <td><img src="https://user-images.githubusercontent.com/71203077/113539852-54af3d80-95fc-11eb-9148-1ecdbe5fa933.png"width="300"></td>
    <td><img src="https://user-images.githubusercontent.com/71203077/113539882-67c20d80-95fc-11eb-9aed-3096bf0382a2.png"width="300"></td>
  </tr>
 </table>

**Would you like to work on the issue?**

Yes, I would like to work on this issue. @nicolas-raoul kindly assign me.

**Comment by nicolas-raoul** [comment]
If I understand correctly, the problem is that when typing something in the "Place type" text field, it is not correctly visible. Please correct me if my understanding is incorrect.

Thanks for spotting this! And for volunteering to work on it :-)

**Comment by Ayan-10** [comment]
Yes @nicolas-raoul , You got it. In lower API devices it is not properly visible. For higher APIs, It is visible properly.
