### ISSUE TITLE
In setting Default description language option is needed to get disable when user is not login   

### ISSUE THREAD

**Issue by Prince-kushwaha** [commons-app/apps-android-commons#4330]
**Summary:** 

when user is not login in app then there is not any need of  Default description language option 
so disable the Default description language option in setting  becouse Default description language option is use to set
language for description and caption in Upload  

when user is login in app then Default description language option enable in setting 
 

**Device and Android version:** 
Android Device :Redmi y3
API :29

**Commons app version:** 
Latest Master

**Would you like to work on the issue?**
YES

**Comment by Prince-kushwaha** [comment]
@nicolas-raoul can i work on this issue

**Comment by nicolas-raoul** [comment]
I am not sure this is worth the added maintenance complexity...

**Comment by neslihanturan** [comment]
> I am not sure this is worth the added maintenance complexity

I agree it is not a vital improvement, however I see a related code in SettingsFragment
```
        // Disable some settings when not logged in.
        if (defaultKvStore.getBoolean("login_skipped", false)) {
            findPreference("useExternalStorage").setEnabled(false);
            findPreference("useAuthorName").setEnabled(false);
            findPreference("displayNearbyCardView").setEnabled(false);
            findPreference("displayLocationPermissionForCardView").setEnabled(false);
            findPreference("displayCampaignsCardView").setEnabled(false);
        }
```
Description setting can simply be added between them. So since there is already related code, I think we can have this.
