### ISSUE TITLE
Exists and Needs Photo does not response if Location is not available.

### ISSUE THREAD

**Issue by Ayan-10** [commons-app/apps-android-commons#4335]
**Summary:** 

If the location is not available and user clicks to Exists and Needs Photo chip, it does not respond. In that state, if user clicks those chip it should show a Toast saying " Location not available ".

**Steps to reproduce:** 

- Goto Nearby Fragment without turned on GPS ( If location is not available, You can see a Toast of " Nearby might not work properly, Location not available ")
- Click Exists or Needs Photo
- You can see by clicking those chips nothing happens.

**What did you expect the app to do, and what did you see instead?**

In that state, if user clicks those chip app should let user know " Location not available " by showing a Toast.

**System logs:**

04-07 01:07:53.286 19459-19459/fr.free.nrw.commons.beta D/NearbyParentFragment: Checking permission and perfoming action
04-07 01:07:53.302 19459-19459/fr.free.nrw.commons.beta D/NearbyParentFragmentPre: Presenter updates map and list
04-07 01:07:53.305 19459-19459/fr.free.nrw.commons.beta D/NearbyParentFragmentPre: Skipping update of nearby places as location is unavailable
04-07 01:07:53.329 19459-19459/fr.free.nrw.commons.beta D/NearbyParentFragment: Location service manager added and registered
04-07 01:07:53.332 19459-19459/fr.free.nrw.commons.beta I/Choreographer: Skipped 8 frames!  The application may be doing too much work on its main thread.
04-07 01:07:53.361 19459-19459/fr.free.nrw.commons.beta D/LocationServiceManager: Provider network disabled
04-07 01:07:53.363 19459-19459/fr.free.nrw.commons.beta D/LocationServiceManager: Provider gps disabled`

**Device and Android version:** 

OPPO A57 version 6.0.1 ( API 23 )
 
**Commons app version:** 

App version- 3.0.0-debug-master~d0f895416 

**Screen-shots:** .

https://user-images.githubusercontent.com/71203077/113769242-639e0900-973e-11eb-9c44-a589def192f9.mp4

**Would you like to work on the issue?**

YES.

**Comment by NotSoImportant** [comment]
Actually the complete "Nearby" tab does not work while location is not available.
This however is sad, as when activated ANY location can be looked at (not only current gps position).

So please
1. enable the same functionality even with gps deactivated
2. Locally store the last gps location instead of jumping back to Tower Bridge, London

![IMG_20210425_232152](https://user-images.githubusercontent.com/35758921/116010602-42835680-a620-11eb-9de8-cb1bbabd8dfe.jpg)
![IMG_20210425_232109](https://user-images.githubusercontent.com/35758921/116010608-47e0a100-a620-11eb-9856-1161f3cc0961.jpg)

**Comment by NotSoImportant** [comment]
Wondering if this should have been fixed by #3732, but seems it is not.

**Comment by Ayan-10** [comment]
@NotSoImportant Yes #3732 should fix this issue. Currently, I am fixing another issue. I will look into this as soon as possible. Thanks for helping.

**Comment by NotSoImportant** [comment]
Thank you ☺️

**Comment by nicolas-raoul** [comment]
I just tried, Nearby's checkboxes and "Search this area" work even with Location disabled in the Android settings. 🙂
