### ISSUE TITLE
Duplicate uploads when uploading 10 pictures

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#4344]
Using the latest master (commit ecbff7e3b8c84b5d40f33bdae3369da090ef0e48 plus non-upload related changes) I uploaded these 10 selected pictures:
![adb](https://user-images.githubusercontent.com/99590/114191736-b5859f80-9987-11eb-889b-9b1d7f83bb7f.png)
Problem: Many of the pictures were uploaded twice or thrice (as seen at https://commons.wikimedia.org/w/index.php?title=Special:ListFiles/Syced&ilshowall=1 from 05:07, 9 April 2021)

<img width="1167" alt="Screen Shot 2021-04-09 at 23 16 19" src="https://user-images.githubusercontent.com/99590/114193613-a9024680-9989-11eb-839b-298b629a6ecb.png">

- Picture 1: 1 time as expected (flower)
- Picture 2: 1 time (beach)
- Picture 3: 1 time (plaza)
- Picture 4: 1 time (building front)
- Picture 5: **2 times** (boat)
- Picture 6: **2 times** (building side)
- Picture 7: **3 times** (orange fish at the bottom)
- Picture 8: **3 times** (orange fish only at the top)
- Picture 9: **3 times** (yellow fish)
- Picture 10: 1 time (telecube)

**Comment by ashishkumar468** [comment]
Hi @nicolas-raoul , thanks for creating the issue and sharing the steps. I will be looking into it.

**Comment by nicolas-raoul** [comment]
This might be happening every time I upload a large number of pictures together.

Another occurrence: 23 pictures uploaded from 07:05, 18 April 2021 here: https://commons.wikimedia.org/w/index.php?title=Special:ListFiles/Syced&ilshowall=1
7 of them got duplicated.

- Picture 1: 1 time
- Picture 2: 1 time
- Picture 3: 1 time
- Picture 4: 1 time
- Picture 5: 1 time
- Picture 6: 1 time
- Picture 7: 1 time
- Picture 8: 1 time
- Picture 9: 1 time
- Picture 10: 1 time
- Picture 11: 1 time
- Picture 12: 1 time
- Picture 13: 1 time
- Picture 14: 1 time
- Picture 15: 1 time
- Picture 16: **2 times**
- Picture 17: **2 times**
- Picture 18: **2 times**
- Picture 19: **2 times**
- Picture 20: **2 times**
- Picture 21: **2 times**
- Picture 22: **2 times**
- Picture 23: 1 time

**Comment by ashishkumar468** [comment]
Hi @nicolas-raoul , apologies for the delay in fixing this, seems like a multi-threading race condition issue, I went through the code and could not find a direct solution, please give me some time, possibly by this weekend I will try to raise the fix.

**Comment by ashishkumar468** [comment]
@nicolas-raoul  would it be possibe to share app logs from when this happened?

**Comment by nicolas-raoul** [comment]
OK! I just took this log while uploading 22 boat pictures: [multiupload.log](https://github.com/commons-app/apps-android-commons/files/6395664/multiupload.log)
As you can see at https://commons.wikimedia.org/w/index.php?title=Special:ListFiles/Syced&ilshowall=1, towards the end each picture was uploaded twice.

- Picture 1: 1 time
- Picture 2: 1 time
- Picture 3: 1 time
- Picture 4: 1 time
- Picture 5: 1 time
- Picture 6: 1 time
- Picture 7: 1 time
- Picture 8: 1 time
- Picture 9: 1 time
- Picture 10: 1 time
- Picture 11: 1 time
- Picture 12: 1 time
- Picture 13: 1 time
- Picture 14: 1 time
- Picture 15: **2 times**
- Picture 16: **2 times**
- Picture 17: **2 times**
- Picture 18: **2 times**
- Picture 19: **2 times**
- Picture 20: **2 times**
- Picture 21: **2 times**
- Picture 22: **2 times**

<img width="680" alt="Screen Shot 2021-04-29 at 09 47 10" src="https://user-images.githubusercontent.com/99590/116489432-eb0b1200-a8cf-11eb-9b7c-9ada98fe486d.png">

**Comment by nicolas-raoul** [comment]
Reproduced just now on latest master: uploaded as a set of 7 pictures, two of the pictures were each uploaded 3 times:
![Screenshot_20210603-200452_Commons](https://user-images.githubusercontent.com/99590/120637093-6d778a80-c4a9-11eb-871b-f2eb35c5ec03.jpg)
Another is somehow stuck in queue even though no all other pics have been uploaded, no upload is running:
![Screenshot_20210603-202131_Commons](https://user-images.githubusercontent.com/99590/120637215-926bfd80-c4a9-11eb-916f-33ced20f4b2f.jpg)

**Comment by ashishkumar468** [comment]
HI @nicolas-raoul , I have raised a PR hoping to fix this. I am testing it from my side too, would be great if you could help test it too. Also, I wanted to confirm, so are all these images you've uploaded, uploaded in a single flow as in all at once or was it like few at a time?
