### ISSUE TITLE
Blue square appears at end of description of image uploaded via Nearby

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#4345]
1. With latest master, upload a picture using Nearby
2. Open the picture in your contributions
3. Notice the blue square (shown by the red arrow):

![adb](https://user-images.githubusercontent.com/99590/114271686-96514580-9a4d-11eb-9dc3-d079c67f7b4e.png)

Actually [the image as seen on the website](https://commons.wikimedia.org/wiki/File:Masuma_island.jpg) does not even seem to have a description:
```
== {{int:filedesc}} ==
{{Information
|description=
|source={{own}}
|author=[[User:Syced|Syced]]
|date={{According to Exif data|2021-03-24}}
}}
{{Location|35.04006388888889|139.81208055555555}}
== {{int:license-header}} ==
{{self|cc-zero}}

{{Uploaded from Mobile|platform=Android|version=3.0.0.951~7a04a2b}}

[[Category:Tomiura, Minamiboso]]
```

It seems to also happen sometimes for Non-Nearby uploads.

**Comment by kurtkaiser** [comment]
Could I be assigned this issue? I experienced the same bug today. I use the application in dark mode and it is also present there.

**Comment by nicolas-raoul** [comment]
@kurtkaiser It is yours, thanks! 🙂

**Comment by kurtkaiser** [comment]
I am noticing the date and disappointed in myself. I have not given this the focus it deserves. I hope to spend more time on it but if it needs to be passed to someone else I understand.

**Comment by nicolas-raoul** [comment]
@kurtkaiser No problem, take your time :-)

**Comment by kurtkaiser** [comment]
Having pulled that latest and rebuilt I am no longer seeing this issue, pictured below. Does this appear to be resolved for anyone else?
![image](https://user-images.githubusercontent.com/8277340/148486445-e40f0b2f-196e-48b1-baad-693bc45af5ae.png)

**Comment by nicolas-raoul** [comment]
Thanks for coming back to this!
I am still seeing this issue on https://commons.wikimedia.org/wiki/File:July_2004,_Pays_Dogon_15.jpg that I uploaded with the app yesterday (GitHub master or super-close to it):
![adb](https://user-images.githubusercontent.com/99590/148491965-482bee2f-91bf-4f16-a7f9-51fd4888e3bf.png)

**Comment by nicolas-raoul** [comment]
@kurtkaiser Are you still working on this? I still see the issue. Thanks! :-)

**Comment by kanahia1** [comment]
Hello @nicolas-raoul 

I have also faced the similar issue today while reviewing

https://github.com/commons-app/apps-android-commons/assets/114223204/3862c507-9bed-4afa-ae7f-de495a6c577e

On going to same image through explore map gave me same blue box

https://github.com/commons-app/apps-android-commons/assets/114223204/5d292d14-9d7c-43b3-90ec-f480121240f6

Can I work on this issue ?

**Comment by kanahia1** [comment]
I have found the issue, it is with the HTMLTextView I have fixed it :-). Will be sharing the PR as soon as possible.


https://github.com/commons-app/apps-android-commons/assets/114223204/72addb0a-8a61-4431-8bf2-6065d802c6aa
