### ISSUE TITLE
Add image dialog is veeeery slow 

### ISSUE THREAD

**Issue by NotSoImportant** [commons-app/apps-android-commons#4349]
Whole "add new contribution" dialog is veeeery slow - depending on the file size.

Probably the same as #2402, but
- much much slower than in the attached video there
- especially slow when typing, marking text, copying

... leading soon to typos and definitively the most annoying thing when using the app.

It is **dependent on the file size** of the image you are trying to upload. For small images (e.g. 50kb) the text can be added very fast. Also switching text inputs works fine. But my typical uploads are ~5mb.
There every typed character is only appearing ~1-2 seconds delayed.

Device: Motorola Moto G4, Lineage OS 14 (Android 7), No GApps
App version: App version: 3.0.0~a36017d81 (and also all previous ones when I started using it some months) 

I have commented on issues for Signal and SimpleGalery for image zooming, that might be related. Please have a look:
https://github.com/signalapp/Signal-Android/issues/7208
https://github.com/SimpleMobileTools/Simple-Gallery/issues/1348 (seems now working there)

**Comment by nicolas-raoul** [comment]
Strange, I use the app daily and have never noticed such an issue.
Would you mind [trying the alpha](https://github.com/commons-app/commons-app-documentation/blob/master/android/Volunteers-welcome!.md#how-to-install-the-alpha), and if that still happens, posting a screencast of it?
Thanks!

**Comment by NotSoImportant** [comment]
Is there a possibility to get a compiled alpha version without play store?

**Comment by NotSoImportant** [comment]
Screen recording attatched. This unfortutately is the original speed. 

https://user-images.githubusercontent.com/35758921/115616661-beb02e00-a2f0-11eb-99f8-d511b7f26fe7.mp4

**Comment by nicolas-raoul** [comment]
APK for latest master: https://drive.google.com/file/d/1gnqgrH_8Yy93VPKlkOQQ1OoTDb8M0Hb4/view?usp=sharing

**Comment by NotSoImportant** [comment]
Requires a google account as well which I don't have ;-)

**Comment by nicolas-raoul** [comment]
Oh I didn't know that, sorry!
Would you have a file sharing service to recommend?

**Comment by NotSoImportant** [comment]
Fixed / not reproduceable in 3.1.1
