### ISSUE TITLE
Need Help : how get all entered descriptions of any media (image,video) in MediaDetailFragment

### ISSUE THREAD

**Issue by Prince-kushwaha** [commons-app/apps-android-commons#4351]
**Summary:** 
I want to get all entered descriptions of image in MediaDetailFragment i try how much

I use the `media.getDescriptions()` to get all entered lanuages descriptions but this function not return any description its size is zero and `media.fallbackDescription()` given one description 

I need help to solve this :https://github.com/commons-app/apps-android-commons/issues/3949 
Image link https://commons.m.wikimedia.org/wiki/File%3ACP_GE_AC4400CW_8608_Morant%27s_Curve.jpg

**Comment by Prince-kushwaha** [comment]
@nicolas-raoul @madhurgupta10 @neslihanturan @misaochan help me

**Comment by vinayak0505** [comment]
@Prince-kushwaha i tried solving it , as i can see there is no data in the table in description.
![image](https://user-images.githubusercontent.com/56196007/114352305-5b542c80-9b89-11eb-9c62-2858b035eb86.png)
So you might be doing it right you'll have to check if you are getting data from the api and also storing it. you can use postman for this. if I found something more ill let you know

**Comment by Prince-kushwaha** [comment]
@vinayak0505 i also use api call https://commons.wikimedia.org/w/api.php?action=query&format=json&formatversion=2&prop=imageinfo&iiprop=url%7Cextmetadata%7Cuser&&iiurlwidth=640&iiextmetadatafilter=DateTime%7CCategories%7CGPSLatitude%7CGPSLongitude%7CImageDescription%7CDateTimeOriginal%7CArtist%7CLicenseShortName%7CLicenseUrl&titles=File:Hibiscus%20syriacus%20capsule%20hoarfrost%20-20200101-RM-102111.jpg
get image information from image title but this api also give one description in imageDescriptions but this image have two descriptions

**Comment by vinayak0505** [comment]
Are you sure that the API call you are making if for the item with multi discription , like if you are checking for your own contributions then you are uploading multiple description.

**Comment by Prince-kushwaha** [comment]
@vinayak0505 yes image have multi description
image link for above api call 
https://commons.m.wikimedia.org/wiki/File:Hibiscus_syriacus_capsule_hoarfrost_-20200101-RM-102111.jpg

**Comment by vinayak0505** [comment]
I see, i guess this API is not getting what we want here, will have to read the documentation if there is no API then we might have to report this to the backend team. @nicolas-raoul @madhurgupta10 @neslihanturan @misaochan please check are these steps okay.

**Comment by nicolas-raoul** [comment]
I replied in the main thread: https://github.com/commons-app/apps-android-commons/issues/3949#issuecomment-817696283
If you have other questions feel free to post there, other people subscribed to that issue might know the answer, or in any case will be interested in seeing any answer :-)
