### ISSUE TITLE
Remind the user to turn on the network

### ISSUE THREAD

**Issue by jidanni** [commons-app/apps-android-commons#4358]
At this point the user is scratching his head, pushing the word "next" over and over and not knowing what the problem is. The problem is he hasn't simply turned on the network. Therefore there should be a friendly message reminding him / her to do that.
![Screenshot_20210416-114148.jpg](https://user-images.githubusercontent.com/1230959/114968653-5c4ace00-9ea9-11eb-9589-1b2740738b69.jpg)
I'm using the latest Alpha version.

**Comment by jidanni** [comment]
Also what is that weird  icon  floating over the other words for? I didn't dare press it to find out. Maybe it's because someone needs to test this with users who use large font setting in Android 🤓

**Comment by neslihanturan** [comment]
We could simply make them remember network issue, thanks for creating this issue @jidanni . Also seems beginner friendly to me.

For the button: It ideally is not floating. Seems like a UI bug.

**Comment by venkatesh2000** [comment]
Hi! I just ran the app from the master branch in betaDebug. Currently, the app displays the below error as a Toast upon clicking the 'next' button when there is no internet connection:

 'Unable to resolve host "commons.wikimedia.beta.wmflabs.org": No address associated with hostname'

So, do you mean to replace the above with a friendly message asking the user to check their network connection?

**Comment by jidanni** [comment]
A Toast ... only remains visible for a short time period.

Maybe that's why I didn't see it. Maybe it has a conflict with other stuff on the screen. What if the user looks away for a second? Therefore a message should stay until the user hits OK.

**Comment by obsidian-zero** [comment]
> Hi! I just ran the app from the master branch in betaDebug. Currently, the app displays the below error as a Toast upon clicking the 'next' button when there is no internet connection:
> 
> 'Unable to resolve host "commons.wikimedia.beta.wmflabs.org": No address associated with hostname'
> 
> So, do you mean to replace the above with a friendly message asking the user to check their network connection?

Hello, I also test this case. But when I don't connect to the Internet, it only shows: Please wait… 
And then it will return to the upload step.

**Comment by obsidian-zero** [comment]
> A Toast ... only remains visible for a short time period.
> 
> Maybe that's why I didn't see it. Maybe it has a conflict with other stuff on the screen. What if the user looks away for a second? Therefore a message should stay until the user hits OK.

When I test it, it will show "Please wait..." for a long time. Is that the case with you?
Maybe we could consider adding some caveats to this sentence.
Please wait ...
If the wait is too long, you may want to check your network connection.

**Comment by venkatesh2000** [comment]
> > A Toast ... only remains visible for a short time period.
> > Maybe that's why I didn't see it. Maybe it has a conflict with other stuff on the screen. What if the user looks away for a second? Therefore a message should stay until the user hits OK.
> 
> When I test it, it will show "Please wait..." for a long time. Is that the case with you?
> Maybe we could consider adding some caveats to this sentence.
> Please wait ...
> If the wait is too long, you may want to check your network connection.


For me, I see the "Please Wait..." for less than a second and then the Toast message appears with the error:

''Unable to resolve host "commons.wikimedia.beta.wmflabs.org": No address associated with hostname''

**Comment by obsidian-zero** [comment]
> 
> For me, I see the "Please Wait..." for less than a second and then the Toast message appears with the error:
> 
> ''Unable to resolve host "commons.wikimedia.beta.wmflabs.org": No address associated with hostname''

OK, I found it.
When I opened the emulator and failed to connect to the Internet the first time I uploaded, it was the same as you.
But if I go through the upload process and try to close the network connection to upload, it will wait a long time and the Toast message will be "Time Out".

**Comment by obsidian-zero** [comment]
> We could simply make them remember network issue, thanks for creating this issue @jidanni . Also seems beginner friendly to me.
> 
> For the button: It ideally is not floating. Seems like a UI bug.

I'd like to have a try at this problem. But I was a beginner and didn't know where to start.
I have the following ideas:
A) Added a reminder to note the network connection in "Please wait..."
B) Add a reminder screen after upload failure. It will disappear when the user confirms it.
C) Add a reminder on the upload page to remind users of their network connection.

Can you give me some advice? This is the first time I've tried to do this.

**Comment by jidanni** [comment]
I had a second look and didn't see any toasts... but of course my device has its fonts cranked real big...

**Comment by neslihanturan** [comment]
I think a warning should be displayed if network is not connected. I am okay to use a dialog instead of toast, toasts might be  unnoticeable.

**Comment by sophiya02** [comment]
Hi, I would like to contribute to this issue. Can I fork this project??

**Comment by byerlyb20** [comment]
@sophiya02 Are you still working on this? If not, I'd be happy to contribute.
