### ISSUE TITLE
Achievements shows zero Nearby uploads, despite leaderboard showing I have hundreds Nearby uploads

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#4365]
![adb](https://user-images.githubusercontent.com/99590/115140228-32dc9e80-a071-11eb-8a2a-243f0034dc97.png)
![adb](https://user-images.githubusercontent.com/99590/115140239-47209b80-a071-11eb-8366-63224ecc9386.png)

**Comment by Prince-kushwaha** [comment]
@nicolas-raoul can i work on this

**Comment by Prince-kushwaha** [comment]
@nicolas-raoul  i my case i upload two nearby picture Achievements shows two Nearby uploads but in leaderboard  it show zero nearby upload

**Comment by neslihanturan** [comment]
> @nicolas-raoul can i work on this

Hey @Prince-kushwaha , thanks for your interest but please complete your already open and changes requested PRs first. For example #4355 , #4361

Even if it is not the first time I had to write this, please note that it is impossible for us to follow every volunteers commitments. Please make sure yourself that you don't have any other remained tasks in your plate before asking for a new issue.

**Comment by 4D17Y4** [comment]
I'd like to work on this issue.

**Comment by nicolas-raoul** [comment]
@4D17Y4 It is yours! :-)

**Comment by 4D17Y4** [comment]
Are these screenshots from the current master @nicolas-raoul? 
In my case, achievement performs the same as I mentioned in https://github.com/commons-app/apps-android-commons/issues/3900#issuecomment-812888186, all the fields are zero and no numbers are shown in the top part of the fragment.

**Comment by nicolas-raoul** [comment]
Actually this seems fixed now :-)
![adb](https://user-images.githubusercontent.com/99590/115951200-59d81c00-a51a-11eb-8403-955bd2b6d226.png)
I think you have to use the production server to see relevant numbers.
