### ISSUE TITLE
Make Checkstyle and/or PMD work on Codacy/Codecov

### ISSUE THREAD

**Issue by whym** [commons-app/apps-android-commons#437]
Codacy is supposed to send Checkstyle results to pull requests. However, it seems that Codacy doesn't work with our checkstyle.xml well and doesn't deliver those results. (See https://www.codacy.com/app/commons-app/apps-android-commons/dashboard?bid=4271658 - there should be far more than 3 issues.) What seemed to have worked previously (#386) was [PMD](https://pmd.github.io/) contained in the default setting of Codacy. 

I asked the Codacy support about it, and they told me that their developers will investigate why it fails.

Because the investigation might take a long time, I'm looking into alternative checkers that work well with Codacy, such as PMD. Even if the resolution is quicker than I thought, another tool won't be bad to have.

**Comment by misaochan** [comment]
Having an alternative checker sounds like a great idea.
