### ISSUE TITLE
Increase number of leaderboard records fetched in a single request from API 

### ISSUE THREAD

**Issue by madhurgupta10** [commons-app/apps-android-commons#4372]
**Summary:** 
The current limit of pagination is set to 10 records at once, but I think we should increase it to something like 100, this will ensure that fewer networks calls are sent from the phone thus saving battery consumption.

**Comment by madhurgupta10** [comment]
@nicolas-raoul What do you think? IMO loading to the very last is annoying with 10 records per request, loader keeps on appearing and disappearing.

**Comment by nicolas-raoul** [comment]
I am pretty happy with the current loading.
Sure, feel free to increase from 10 to 100 if you think it is worth doing and has no noticeable impact on initial loading time :-)

**Comment by AyusmaTech** [comment]
Hi, can I work on this?
