### ISSUE TITLE
Contribution count does not get updated right away image successful uploaded

### ISSUE THREAD

**Issue by Prince-kushwaha** [commons-app/apps-android-commons#4380]
**Summary:** 

After a successful upload, when 'Contribution' activity is shown, then upload count in the header is not incremented. It still shows the old count. But when you close and re-open the application, it shows the correct count.

**Steps to reproduce:** 

1. Note the current upload count and then upload an image.
2. When you come back to 'contribution activity ' 
3. And see contribution count

**Actual**: You will see the upload count unchanged.
**Expected**: It should have incremented by one.

**Device and Android version:** 
Android Device :Redmi y3
API :29 
**Commons app version:** 
Latest Master

**Would you like to work on the issue?**
YES

**Comment by Prince-kushwaha** [comment]
@nicolas-raoul what this issue is considered as bug

**Comment by nicolas-raoul** [comment]
Yes thanks! I think this is the same as https://github.com/commons-app/apps-android-commons/issues/1853 by the way.
