### ISSUE TITLE
Edit categories feels broken, bad UX

### ISSUE THREAD

**Issue by NotSoImportant** [commons-app/apps-android-commons#4387]
**Summary:** 
Actually the first few times I thought the dialog is broken.
1. could not find a search box
2. even worse: dialog **closes** when clicking anywhere inside the dialog (else than the icon)

I only saw some wired lines below, tried to click on them but instead of a textbox appearing, the dialog closed.
Only later I found these are buttons with ~1px height, but clicking not only there, but anywhere in the dialog closes it.

![](https://user-images.githubusercontent.com/35758921/116615876-378c3700-a93c-11eb-817c-17c92f947ad4.jpeg)

**Proposal:**
1. Have the search box focused (and so keyboard broght up)
2. Let the buttons always by there in full size, but disabled if nothing is selected

**Steps to reproduce:** 
on an uploaded image go to details and click the edit icon next to categories

**Device and Android version:** 
android version: 7, lineage os
 
**Commons app version:** 
app version: 3.0.0~a36017d81 

**Would you like to work on the issue?**
no

**Comment by Pratham2305** [comment]
I agree on this one, this issue does exist on the latest master.
@nicolas-raoul I would like to fix this one if you can confirm this from your side. Thanks!

**Comment by nicolas-raoul** [comment]
Thanks @NotSoImportant for formalizing this, I always felt uncomfortable using this UI indeed.
And thanks @Pratham2305 for accepting to work on it!
