### ISSUE TITLE
Implement category chooser on desktop too

### ISSUE THREAD

**Issue by jidanni** [commons-app/apps-android-commons#4394]
Adding categories to images within the app is a breeze...
But what if we aren't finished and want to add the rest later via desktop computer?
Alas on desktop we must find the category, and paste it in via hand,
```
[[Category:Blurfowitz]]
```
Perhaps there could be some technology transfer to the desktop?

**Comment by nicolas-raoul** [comment]
I totally agree with you that category selection is more convenient with the Android app, mostly thanks to depiction search (better matching, multilingual) which finds associated categories.

I actually sometimes run the Android Commons app on desktop, using BlueStacks or Android Studio.

Another alternative is to use https://commons.wikimedia.org/wiki/Help:Gadget-HotCat

There is actually already an issue for porting to desktop, so I suggest centralizing discussions there: https://github.com/commons-app/apps-android-commons/issues/559
