### ISSUE TITLE
Hackathon 2021

### ISSUE THREAD

**Issue by sivaraam** [commons-app/apps-android-commons#4398]
Just wanted to spread the word about the remote Hackathon this year. It's been planned as a remote event on May 22-23.

Link to the main page about the hackathon: [Wikimedia Hackathon 2021](https://www.mediawiki.org/wiki/Wikimedia_Hackathon_2021)

A look at the main page tells me we at least a few of us might already be aware of this but opening an issue just in case 🙂

**Comment by misaochan** [comment]
Ahh, I was not aware, thanks for the link @sivaraam ! And well done @neslihanturan . ;)

**Comment by sivaraam** [comment]
Following the Wikimedia Hackathon, it looks like Wikimania is happening shortly (Aug 13 - Aug 17). It's virtual too. The hackathon specifically is happening on August 13th, 5:00 UTC.

More details could be found in the event page could be found here: https://wikimania.wikimedia.org/wiki/Wikimania

Registrations are open. Anyone can register via the [registration page](https://www.eventbrite.com/e/wikimania-2021-tickets-161884957265).

**Comment by Rishavgupta12345** [comment]
@nicolas-raoul @4D17Y4  this issue is not relevant now so we can close this now
