### ISSUE TITLE
Language-aware category search

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#44]
If the user's phone is in Japanese, then searching for パリ should return Category:Paris

Better limit ourselves to that, as inculding all languages would create many false-positives.

**Comment by neslihanturan** [comment]
Hi @nicolas-raoul , I saw this old issue but coudn't understand it properly. Can you please explain your suggestion a little more?

**Comment by nicolas-raoul** [comment]
When I search for the English spelling "Paris" I get the right category:

![adb-screenshot](https://user-images.githubusercontent.com/99590/54115388-aaba5280-442f-11e9-9980-511d56be7bf1.png)

But when I write (with a Japanese Android) in Japanese (パリ is the Japanese word for Paris) I get less relevant categories, probably found using some of their descriptions:

![adb-screenshot](https://user-images.githubusercontent.com/99590/54115593-143a6100-4430-11e9-99f3-f6423c1530d3.png)

**Comment by nicolas-raoul** [comment]
Hopefully categories will be made obsolete by Structured Commons, but that will probably be in many years, so any solution to use meanwhile would be great. The same problematic probably exists with the Commons web interface, so maybe a language setting can be specified when using the search API?

**Comment by nicolas-raoul** [comment]
Solved by asking first for depictions (these are much more non-English friendly), then showing categories based on the selected depictions.
