### ISSUE TITLE
{{Creator: Andy Mabbet}} in place of actual author name

### ISSUE THREAD

**Issue by Ayan-10** [commons-app/apps-android-commons#4400]
**Summary:** 

Sometimes, while uploading an image and after uploading an image, in place of the actual author name it's showing {{Creator: Andy Mabbet}} in Contribution Activity.

**Steps to reproduce:** 

Upload any image in the app. Although It's not happening every time.

**Device and Android version:** 

OPPO A57 API 23 and Pixel 4 API 27
 
**Commons app version:** 

Latest master

**Screen-shots:** 

<img src="https://user-images.githubusercontent.com/71203077/117150811-1dd46f00-add6-11eb-8eb5-12d89e661c97.png" width=300>

**Comment by misaochan** [comment]
Oh, wow. Are you interested in working on this @Ayan-10 ?

**Comment by Ayan-10** [comment]
@misaochan Yes, I would like to work on this.

**Comment by misaochan** [comment]
@Ayan-10 it is yours, please keep us updated on your progress. :)

**Comment by Ayan-10** [comment]
@misaochan This is weird. Actually previously authorName = {{Creator: Andy Mabbet}} is showing for both lower and higher API devices but now this issue is not showing with higher API devices but It does showing with OPPO A57 API 23. I thought it's occurring only in lower API devices. But I tested the app in some other lower API devices but It's not occurring. **Actually now this issue is only happening with OPPO A57 API 23.**

Can anyone please test the app on some other devices and see if this issue is occurring or not?

**Comment by misaochan** [comment]
It doesn't occur for me on Samsung Galaxy S10 Android 11.

**Comment by nicolas-raoul** [comment]
Due to super rare occurrence and old issue age I will close this, but if anyone observes this again please do not hesitate to reopen, thanks!
