### ISSUE TITLE
 Notification of  Number of image  is in uploading is not change 

### ISSUE THREAD

**Issue by Prince-kushwaha** [commons-app/apps-android-commons#4401]
**Summary:** 

If i upload the more than one together image  then Notification of  Number of image  is in uploading is not change when one by one 
image is seccussfully uploaded 
See the circle section in image 
![Screenshot_2021-05-05-13-22-04-200_fr free nrw commons_LI](https://user-images.githubusercontent.com/65972015/117187731-da8bf780-adf9-11eb-9c06-81ca61891fe0.jpg)

**Steps to reproduce:** 
- Upload more than one image together
- then alteast one  image is successfull upload 
- then see Notification of  Number of image  is in uploading

**Device and Android version:** 
Andrioid Device:Redmi y3'
**Commons app version:** 
Latest master

**Screen-shots:** 

**Would you like to work on the issue?**
YES

**Comment by Prince-kushwaha** [comment]
@nicolas-raoul what this issue is considered as bug

**Comment by nicolas-raoul** [comment]
If I understand correctly, you are expecting `Processing 2 uploads` to become `Processing 1 upload` as soon as the first image is successfully uploaded? I guess I would consider that an enhancement.

**Comment by Prince-kushwaha** [comment]
@nicolas-raoul yes can i work on this

**Comment by Prince-kushwaha** [comment]
i think it is bug

**Comment by nicolas-raoul** [comment]
It seems to me that the current behavior can be considered correct.
Even if there is only 1 file left to upload, it is correct to say that it is in the middle of processing 2 uploads.
I will mark this as debated for now, if other people think it needs work then it can be revisited.

**Comment by misaochan** [comment]
IMO "processing 2 uploads" is fine.

**Comment by nicolas-raoul** [comment]
Understood! I will close for now, anyone please feel free to comment if you have more thoughts about this.
