### ISSUE TITLE
Back Pressed Event not work in Explore tab 

### ISSUE THREAD

**Issue by Prince-kushwaha** [commons-app/apps-android-commons#4403]
**Summary:** 

Open the App without login  and go to Explore tab  and press back button then back press event not work 

**Steps to reproduce:** 
- Open an App without Login
- Go to Explore Tab 
- Press the Back button then nothing happens

**Device and Android version:** 
Android Device:Redmi y3

**Commons app version:** 
Latest master
**Would you like to work on the issue?**
YES

**Comment by Prince-kushwaha** [comment]
@nicolas-raoul can i work on this issue

**Comment by nicolas-raoul** [comment]
Great find!
Yes thanks :-)
