### ISSUE TITLE
Need Improvement in Peer Review Activity UI in landscape Mode 

### ISSUE THREAD

**Issue by Prince-kushwaha** [commons-app/apps-android-commons#4409]
**Summary:** 

Current Below UI is not good for Peer Review Activity in Landscape Mode

![Screenshot_2021-05-12-09-54-59-652_fr free nrw commons](https://user-images.githubusercontent.com/65972015/117919202-34188880-b30a-11eb-81b1-d8029ccf71bd.jpg)

 I thing Below UI is good for Peer Review Activity in Landscape Mode 
![Screenshot_2021-05-12-12-23-55-566_fr free nrw commons](https://user-images.githubusercontent.com/65972015/117931913-67184780-b31d-11eb-8705-391323acb826.jpg)

**Device and Android version:** 
Android Device :Redmi y3
 
**Commons app version:** 
Latest master 

**Would you like to work on the issue?**
YES

**Comment by Prince-kushwaha** [comment]
@nicolas-raoul @madhurgupta10 can i work on this

**Comment by madhurgupta10** [comment]
@Prince-kushwaha This issue is already under discussion https://github.com/commons-app/apps-android-commons/issues/4343
