### ISSUE TITLE
Failed prodRelease build on 3.0-release, solvable by disabling minify

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#4417]
**Summary:** 

Pulling from the 3.0-release branch, and building the app in prodDebug works totally fine. But building in prodRelease (which is the variant required for publishing) results in the error:

```
Execution failed for task ':app:minifyProdReleaseWithProguard'.
java.io.IOException: java.lang.RuntimeException: java.lang.IllegalArgumentException: Value "a" is not an integer value [proguard.evaluation.value.UnknownReferenceValue]
```

Disabling minify in build.gradle solves the problem, however we have to decide if that is something we want to do, or if there is a better way to solve the problem. Ideally, we should decide soon, as v3.0.1 is way overdue for release.

**Steps to reproduce:** 

Pull from 3.0-release branch, change build variant to prodRelease, add your keys to build.gradle, then try to build.

**Device and Android version:** 

Device agnostic, target SDK 29, Android Studio 4.2.1
 
**Commons app version:** 

3.0-release

**Comment by misaochan** [comment]
Ah, seems there was an issue with my run config. Solved now, no disabling of minify required.

**Comment by 4D17Y4** [comment]
Hey @misaochan,
My build is failing with the same error log.
Can you recall what was the config issue you were facing?

**Comment by misaochan** [comment]
Ahh, I honestly can't remember sorry. :( I should have been more specific about how I fixed it.
