### ISSUE TITLE
Be-tarask language is missing in description

### ISSUE THREAD

**Issue by Renessaince** [commons-app/apps-android-commons#4419]
**Summary:** 

As I uploading any file via Commons app, I fill in all the necessary fields including multilanguage description. But in the list of available languages be-tarask is missing.

**Steps to reproduce:** 

Upload file, enter description, choose language.

**Commons app version:** 

2.13.2.

**Comment by sivaraam** [comment]
@Renessaince I'm not able to find the language in the list of languages shows in Commons' [upload wizard](https://commons.wikimedia.org/wiki/Special:UploadWizard) either. Does Commons really support descriptions in this language already? Or is yet to be supported?

**Comment by Renessaince** [comment]
@sivaraam, take a look at any of my uploads, for instance https://commons.wikimedia.org/wiki/File:%D0%A6%D0%B0%D1%80%D0%BA%D0%B2%D0%B0_%D1%81%D1%8C%D0%B2%D1%8F%D1%82%D0%BE%D0%B9_%D0%9F%D0%B0%D1%80%D0%B0%D1%81%D0%BA%D0%B5%D0%B2%D1%8B_%D0%9F%D1%8F%D1%82%D0%BD%D1%96%D1%86%D1%8B_(%D0%9B%D1%8F%D0%B4%D0%B0%D0%B2%D1%96%D1%87%D1%8B)_003.jpg
All of them have descriptions in be-tarask.

**Comment by misaochan** [comment]
@Nikerabbit or @amire80 could you advise us on this? I recall there was an issue surrounding `be-tarask` in the past.

**Comment by Nikerabbit** [comment]
Sorry, I don't know how Wikimedia Commons does this.

**Comment by nicolas-raoul** [comment]
I see `беларуская (тарашкевіца)` in the SDoC captions editor (by the way like some other languages it is duplicated, not sure whether it is a bug):
<img width="835" alt="Screen Shot 2021-06-19 at 19 34 01" src="https://user-images.githubusercontent.com/99590/122639537-55ed0280-d135-11eb-9498-3dbc1704fa5d.png">

**Comment by Rishavgupta12345** [comment]
@nicolas-raoul @4D17Y4 we have be-tarask language in out app now so we can close this issue now .

be-tarask is present in out app and the given language code to it is [be-x-old]

**Comment by Renessaince** [comment]
> @nicolas-raoul @4D17Y4 we have be-tarask language in out app now so we can close this issue now .
> 
> be-tarask is present in out app and the given language code to it is [be-x-old]

Why be-x-old if it should have been be-tarask?

**Comment by nicolas-raoul** [comment]
Related Phabricator task `Rename "be-x-old" to "be-tarask"` implemented in 2015: https://phabricator.wikimedia.org/T11823

Next steps:
1. Do we get the list of languages from an API?
2. If yes, file a Phabricator bug for that API. If no, update our code.

**Comment by rohit9625** [comment]
Hey @nicolas-raoul,
We do not get the list of languages from an API instead we have the list items predefined here:
![image](https://github.com/commons-app/apps-android-commons/assets/101377978/720a4590-1428-4c97-b6f7-56f86dd8ce94)

Now, what am I supposed to do, should I change the item `be-x-old` to `be-tarask`?

**Comment by nicolas-raoul** [comment]
@rohit9625 Yes thanks :-)
