### ISSUE TITLE
Two items at same location: Uploading pic to the wrong one

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#4424]
1. Open Nearby 
2. Move/zoom the map to see this place that does not have a P18 image: https://www.wikidata.org/wiki/Q24876991
3. Tap the blue pin
4. Open the blue pin's Wikidata page
5. Problem: The opened Wikidata page is a different item (https://www.wikidata.org/wiki/Q11441990) which already has an image.

This is problematic because the user loses time taking a picture of an item that already has a picture, and is not shown the item which actually needs a picture. The user can be annoyed because the pin stays blue even after uploading.

Note: The two items have the same latitude/longitude but they are different things (a tree, and the temple where this tree grew).

I think there is a bug about places appearing on tap even when there is no pin, but I could not find it. Fixing that bug would probably fix this one too.

**Comment by Pratham2305** [comment]
@nicolas-raoul, I think I am able to reproduce the bug. See

<img src="https://user-images.githubusercontent.com/54663429/119561877-565add80-bdc3-11eb-91e5-9b3c510ea3e7.png" width="400">                  <img src="https://user-images.githubusercontent.com/54663429/119561947-6c689e00-bdc3-11eb-8c27-a1e5bbebcc89.png" width="400">

I would like to work on it.

**Comment by nicolas-raoul** [comment]
@Pratham2305 It is yours, thanks!
