### ISSUE TITLE
Master build failing

### ISSUE THREAD

**Issue by sivaraam** [commons-app/apps-android-commons#4425]
It looks like the latest translatewiki update [broke `master`](https://github.com/commons-app/apps-android-commons/runs/2655770485). The build fails with the following error:

```
* What went wrong:
Execution failed for task ':app:mergeProdDebugResources'.
> D:\Source\kaartic\apps-android-commons\app\src\main\res\values-ms-arab: Error: Invalid resource directory name
```

On some research, it looks like `ms-arab` [refers to](https://stackoverflow.com/a/50174605/5614968) the [Jawi script of Malay](https://en.wikipedia.org/wiki/Jawi_alphabet). I'm not sure if Android supports this variant. I couldn't find any info about whether Android supports this variant by looking at the [related doc](https://developer.android.com/guide/topics/resources/providing-resources.html) and [a QA](https://stackoverflow.com/questions/7973023/what-is-the-list-of-supported-languages-locales-on-android). Anyone has any idea how to fix this?

**Comment by misaochan** [comment]
Pinging @Nikerabbit for advice.

**Comment by Nikerabbit** [comment]
We can set up a code map from `ms-arab` to `b+ms+Arab`. Not sure if it makes selectable though.

**Comment by amire80** [comment]
I don't know if any Android device supports it. I have Samsung Galaxy S20 FE, which is fairly modern, and it doesn't seem to support it.

The addition of ms-arab was requested by User:Tofeiku for UI translations in translatewiki and values in Wikidata, and it made sense to me, so I added it (with the comment that to use it for wiki page _content_ in a Wikimedia project there would have to be a separate discussion). It works fine in Wikidata, for what it's worth.

In Wikipedia or Commons _apps_ it would only be for UI. If it's possible to make it selectable in the preferences, I guess it would be nice. I cannot comment further on the technical side of things.

**Comment by misaochan** [comment]
The code map sounds good. Is there anything else that we need to do on our end to get the build fixed, or will the next translatewiki commit suffice?

**Comment by Nikerabbit** [comment]
I just pushed a regular update that uses the supported code format. I will soon push a manual update to remove the pre-codemap file and then the build should be fixed.

**Comment by misaochan** [comment]
Wonderful, thanks! :)

**Comment by Nikerabbit** [comment]
a524ac7df passes tests.

**Comment by sivaraam** [comment]
> [a524ac7](https://github.com/commons-app/apps-android-commons/commit/a524ac7dfe0a54f9ecf217f00df0e389c7ac1033) passes tests.

Great! So, it looks like the only thing left if checking if the UI could be viewed with `ms-arab` as the language. I've opened #4432 for that. So, closing this.
