### ISSUE TITLE
App changes file data before upload, changing its EXIF data and thus changing SHA1

### ISSUE THREAD

**Issue by 4D17Y4** [commons-app/apps-android-commons#4429]
**Summary:** 
The app makes a cache copy of a file and changes the EXIF data of the copy for upload. This modifies the file and the file is no longer the same file that was supposed to be uploaded.

**Steps to reproduce:** 

Upload an image file from the app (quite evident when u use camera pictures.)
Download the image file from the server using the download button in the image detail.

now check the SHA1 hashes of both images, one from the camera and the other downloaded one.
The SHA1 of both images is different.

Link for SHA1 checksum https://emn178.github.io/online-tools/sha1_checksum.html

The app modified the image which it should not.

**Device and Android version:** 

BetaDebug on Nokia 6.1+ android 10.
 
**Commons app version:** 

Current master.

**Would you like to work on the issue?**
Yes.

**Comment by 4D17Y4** [comment]
The exact line which modifies the code:

line 60:
https://github.com/commons-app/apps-android-commons/blob/f8a8f9207028a6fb5a35483c040821f22daf755e/app/src/main/java/fr/free/nrw/commons/upload/FileProcessor.kt#L51-L62


line 101:
https://github.com/commons-app/apps-android-commons/blob/f8a8f9207028a6fb5a35483c040821f22daf755e/app/src/main/java/fr/free/nrw/commons/upload/FileProcessor.kt#L94-L104




Trackback

line 103:
https://github.com/commons-app/apps-android-commons/blob/f8a8f9207028a6fb5a35483c040821f22daf755e/app/src/main/java/fr/free/nrw/commons/upload/UploadModel.java#L91-L108

line 84:
https://github.com/commons-app/apps-android-commons/blob/f8a8f9207028a6fb5a35483c040821f22daf755e/app/src/main/java/fr/free/nrw/commons/upload/UploadModel.java#L80-L85

**Comment by nicolas-raoul** [comment]
My fault, I had forgotten about these EXIF modifications for privacy.
We will have to work around that.
And sorry for making you create an issue about it!

**Comment by sivaraam** [comment]
Sorry for chiming in. To sere as a reference for someone who doesn't have the context, could someone mention what the problem is here and how we're thinking of to address it? 🙂

**Comment by nicolas-raoul** [comment]
@sivaraam We are looking for a way to check whether an image has been uploaded already or not (using any device, potentially via the website/etc).
The best strategy so far seems to be to check the SHA1 of the picture after applying the user's current privacy setting. Not perfect but best we can do, I guess. We could also check the SHA1 of the original image, and various privacy settings variations, but that would increase server load.

**Comment by sivaraam** [comment]
Thanks for the context @nicolas-raoul ! 

> The best strategy so far seems to be to check the SHA1 of the picture after applying the user's current privacy setting. 

IIUC, that would detect images uploaded via the app with those settings. But wouldn't work for the ones that users uploaded via other ways like web etc. right?

> Not perfect but best we can do, I guess.

Yeah. This looks like a tricky problem indeed.

> We could also check the SHA1 of the original image, and various privacy settings variations, but that would increase server load.

Quite possible. But I think we could at least try 2 combinations: original image and original image with user's current privacy setting which should help cover the case where the image has been uploaded as it is. What do you think?

Speaking of SHA-1 based file detection, I happened to stumble upon "[File Analyzer](https://commons.wikimedia.org/wiki/Commons:SHA1)" which looks like a neat tool that does exactly what we're looking at. I thought of sharing it just in case it might be helpful 🙂

**Comment by nicolas-raoul** [comment]
> wouldn't work for the ones that users uploaded via other ways like web etc. right?

True.

> we could at least try 2 combinations: original image and original image with user's current privacy setting

Sounds like a good idea! The Upload Wizard does not modify files in any way, right?

Thanks for the tip! :-) I wonder whether this tool can recognize deleted files.

**Comment by 4D17Y4** [comment]
Thanks @sivaraam for the inputs,
@nicolas-raoul  if we look at the "[reference link](https://commons.wikimedia.org/wiki/Commons:Tools#Duplicates_and_Hash-based_search)" we can see there is a tool to check for the overwritten and deleted files, but I think the web interface is not working or the tool is not available anymore.

I tested the upload wizard and it does not modify the image, it's the same as checking the original image sha1 against the API.
Not sure about the deleted ones, do we have some deleted images uploaded without any EXIF changes?

**Comment by nicolas-raoul** [comment]
@4D17Y4 Yes, I uploaded [this image](https://i.stack.imgur.com/C2SAr.jpg) and it got deleted :'-( https://commons.wikimedia.org/w/index.php?title=File:Royal_Norwegian_Airforce_Lockheed_Orion_with_air-droppable_lifeboat_for_search-and-rescue_missions.jpg&action=edit&redlink=1

**Comment by sivaraam** [comment]
> 
> > we could at least try 2 combinations: original image and original image with user's current privacy setting
> 
> Sounds like a good idea! The Upload Wizard does not modify files in any way, right?
>

That's my belief too. Looks like @4D17Y4 has confirmed it :)

> Thanks for the tip! :-) I wonder whether this tool can recognize deleted files.

I'm afraid not. Finding deleted files using SHA-1 sounds even trickier 🔍 

>  @nicolas-raoul if we look at the "reference link" we can see there is a tool to check for the overwritten and deleted files, but I think the web interface is not working or the tool is not available anymore.

Yeah. The tool seems to be down and unmaintained for a while. If its really necessary, we could try pulling strings to explore the feasibility of bringing it back up. For now, [the source](https://github.com/Toollabs/expose-data) seems to be available, at least.

**Comment by 4D17Y4** [comment]
> @4D17Y4 Yes, I uploaded [this image](https://i.stack.imgur.com/C2SAr.jpg) and it got deleted :'-( https://commons.wikimedia.org/w/index.php?title=File:Royal_Norwegian_Airforce_Lockheed_Orion_with_air-droppable_lifeboat_for_search-and-rescue_missions.jpg&action=edit&redlink=1

Thanks for the image, no trace from the tool, it cannot look for deleted files.

> Yeah. The tool seems to be down and unmaintained for a while. If it's really necessary, we could try pulling strings to explore the feasibility of bringing it back up. For now, [the source](https://github.com/Toollabs/expose-data) seems to be available, at least.

It is not really important right now but can be included as a post-GSoC improvement. We can show the user that this file was uploaded on commons and was deleted; therefore, you are not allowed to upload this image even though it's not currently on commons.
