### ISSUE TITLE
Empty white bar shown above Achievements/Leaderboard screen

### ISSUE THREAD

**Issue by sivaraam** [commons-app/apps-android-commons#4431]
**Summary:** 

When opening the Achievements/Leaderboard screen, an empty white bar is shown above it which serves no purpose. It would be nice if it could be hidden instead.

**Device and Android version:** 
OnePlus Nord running Android 11

**Commons app version:** 
3.0.0.1003~7db6f83

**Screen-shots:** 
![Screenshot_20210529-234750](https://user-images.githubusercontent.com/12448084/120080869-56ffb680-c0d8-11eb-8f9f-c571d252e605.jpg)

**Would you like to work on the issue?**
Prefer not.

**Comment by Ayan-10** [comment]
Hey @sivaraam , Actually there was no back button also. The white bar has to be there for the back button and as @nicolas-raoul suggested the white bar can contain the username and a share button for allowing people to share their achievements. Here is the [discussion](https://github.com/commons-app/apps-android-commons/issues/4312#issuecomment-812348378). This issue already exists kindy see  #4312 . And I will make a PR soon including all these things.

Thanks

**Comment by sivaraam** [comment]
Ah. That's nice. I could find #4312 during my search. We can close this one in favour of it then :)
