### ISSUE TITLE
Improvement ideas for the custom picture selector

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#4434]
# Note: The GSoC task has been moved to https://github.com/commons-app/apps-android-commons/issues/4764

Other ideas for after the GSoC:
- Mark folder as already uploaded (greyed out, with Commons overlay icon, shown at the end next time the picker is opened) if all pictures inside have been uploaded already. Would have to find out what is the best trade-off between CPU consumption and accuracy.
- Long-press on a folder to reveal a menu offering folder operations:
  - Open the folder in another app (just launch an intent, Android should hopefully suggest available file explorers and gallery apps).
  - Mark all pictures currently in this folder as "Not for upload"
  - Always ignore this folder (which makes it greyed out, with 🚫 overlay icon, shown at the end next time the picker is opened)
  - Un-ignore if the folder that is the "Ignored" state. 

---

_Ideas rejected for now:_

- _Make the custom picture selector the default (so only camera and that one are available when tapping + in the main activity), and provide a setting to switch to the OS gallery instead (in case custom picture selector doesn't work well for some users)._

**Comment by 4D17Y4** [comment]
- For the limited connection mode we can directly show up the OS gallery. Custom picture selector would definitely be slow in low connectivity.

**Comment by nicolas-raoul** [comment]
Limited connection mode tries to limit transfer of huge amounts of data (=pictures), but since the selector's HTTP requests and responses are very light (a kilobyte or two I guess), they might be considered OK even if they can be numerous. I let the limited connection mode's experts decide :-)

**Comment by misaochan** [comment]
> Check not only the SHA1 of the privacy-modified file, but also of the original file, as it might have been uploaded via Upload Wizard which does not modify anything.

Sounds good to me.

> Make the custom picture selector the default (so only camera and that one are available when tapping + in the main activity), and provide a setting to switch to the OS gallery instead (in case custom picture selector doesn't work well for some users)

Personally I would prefer to keep the current default until the custom picture selector has been out for at least 1 version and we get user feedback on it. Little steps. :)
