### ISSUE TITLE
Main activity title is sometimes "Contributions", sometimes "Commons"

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#4438]
Latest master.
Not sure how to reproduce. "Commons" seems to become the title after having left the app for a few hours. I could be wrong though. Restarting the app makes it go back to "Contributions".
![Screenshot_20210605-150319_Commons](https://user-images.githubusercontent.com/99590/120882356-14773600-c612-11eb-9360-21b8a4db4fcd.jpg)
![Screenshot_20210605-150156_Commons](https://user-images.githubusercontent.com/99590/120882371-44bed480-c612-11eb-83ea-1e81371e16b0.jpg)

**Comment by ashar-7** [comment]
I was able to reproduce this issue by turning on `Don't keep activities` in developer options.

Steps to reproduce:
1. Turn on `Don't keep activities` in developer options.
2. Open the app. The title will be "Contributions".
3. Put the app in background.
4. Open the app again. The title is now "Commons".

**Comment by ashar-7** [comment]
Looks like it happens when the activity is destroyed and `savedInstanceState` is not null.
```
// From MainActivity.java:

if(savedInstanceState == null){
    //starting a fresh fragment.
    setTitle(getString(R.string.contributions_fragment));
    loadFragment(ContributionsFragment.newInstance(),false);
}
setUpPager();
```
I'll try fixing the issue

**Comment by nicolas-raoul** [comment]
@ashar-7 Thanks for the investigation! Please do not hesitate to send a pull request :-)
