### ISSUE TITLE
Category search spins forever in upload wizard

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#4460]
In master, since a few days nothing appear at the categories step even though I selected some items (that are linked to categories) in the depictions step.

Searching for the "Flowers" category does not show any result either.

![Screenshot_20210614-171949_Commons](https://user-images.githubusercontent.com/99590/122207912-a10cd880-cedd-11eb-973a-5bc0c5375bd3.jpg)

**Comment by Prince-kushwaha** [comment]
@nicolas-raoul can i work

**Comment by nicolas-raoul** [comment]
@Prince-kushwaha Are you able to reproduce the issue? (on prod)

**Comment by nicolas-raoul** [comment]
Sorry Prince, my bug is a duplicate of #4459 would you mind checking that one instead? Thanks!

**Comment by mnalis** [comment]
- see also https://github.com/commons-app/apps-android-commons/issues/5225; it might be related to be intermittent problem when conversing with server side via API
