### ISSUE TITLE
Sometimes can't copy/paste from/to Upload caption field

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#4469]
I often copy a term (by long-pressing or double-tapping) from the caption, and use it to search for depictions.
Sometimes it does not work. Example on latest master:

https://user-images.githubusercontent.com/99590/122629995-b8291180-d0fb-11eb-8d7a-3fabdd936180.mp4

I haven't found a pattern, sometimes it works and sometimes not.

**Comment by benryder1988** [comment]
I've been able to recreate this, and I think the pattern is:
- it works when you initially visit the screen where you can input the caption and description
- then if you click 'next' and then 'previous' to return the screen with the caption and description, then it no longer works.

@nicolas-raoul does this match your experience and help you recreate the issue? 

At a guess, I think the fields are perhaps not reinitialised properly. I will try and take a look at this tomorrow if thats okay?

**Comment by nicolas-raoul** [comment]
@benryder1988 
Yes, I am pretty sure that matches my experience!
Thanks a lot, looking forward to your pull request :-)

**Comment by benryder1988** [comment]
No problem :) the issue seems to be fixed now in pull request #4469, let me know if you still have issues!

**Comment by nicolas-raoul** [comment]
Sorry I was wrong, I just got a case where text is unselectable immediately after initiating the upload (before tapping "Next").
