### ISSUE TITLE
Move tutorial to after login

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#4477]
In my understanding, the main goal of the tutorial is to improve contributions quality, by explaining what images are worth uploading, and how to write captions/etc.

For people who do not want to log in, I believe that the tutorial is not really relevant.

So, how about moving the tutorial to after login? And not show any tutorial to users who do not log in (_or maybe show a different tutorial in a later phase/separate issue, which could explain the merits of logging in_).

**Comment by Ayan-10** [comment]
@nicolas-raoul Can I work on this issue?

**Comment by nicolas-raoul** [comment]
@Ayan-10 It is yours, thanks! :-)
