### ISSUE TITLE
Make media details caption & description copyable

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#4480]
I often want to copy a caption to reuse part of it for another picture.
Long-pressing does not seem to have any effect currently. I think the text should be made selectable.

**Comment by Ayan-10** [comment]
@nicolas-raoul I hope adding ` android:textIsSelectable="true"` in textView will fix this issue. Should I do that?

**Comment by nicolas-raoul** [comment]
Sounds good! 🙂
