### ISSUE TITLE
Capitalization not reflected consistently

### ISSUE THREAD

**Issue by jidanni** [commons-app/apps-android-commons#4493]
After we upload a picture it always is capitalized on the website automatically but not automatically in the app.

In fact if we will upload two pictures one has the number two added but now looking in the app the names are still exactly the same.

 I'm using the latest beta.

**Comment by nicolas-raoul** [comment]
About "number two": The app's gallery shows the picture's caption, not its filename.

About capitalization: not sure to understand, would you mind posting screenshots?

**Comment by jidanni** [comment]
OK, currently the capitalization is updated after the upload completes. So never mind that.

> About "number two": The app's gallery shows the picture's caption, not its filename.

So that means two items could have exactly the same name/title in the app?!

**Comment by nicolas-raoul** [comment]
Yes, exactly, just like in a book two different pictures could have the same caption.

**Comment by jidanni** [comment]
What if all the captions are the same?
How can one then distinguish them in the app?
Sounds like a recipe for disaster.
The user will delete the good one, thinking it is the bad one, etc.

**Comment by jidanni** [comment]
A family picture browser app should the captions by default.

An uploader app should show the nitty-gritty file names by default.
