### ISSUE TITLE
Depiction explanation cropped

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#4496]
Latest master.
The explanation is not wrapped correctly, a part of the word is not visible, see red arrow:
![adb](https://user-images.githubusercontent.com/99590/124685398-2c412300-df0c-11eb-9d96-92a35e648290.png)
It sometimes makes the explanation difficult to understand, which can lead to less-informed depiction choice.

**Comment by misaochan** [comment]
Interesting, does this happen in v3.0.2 for you as well @nicolas-raoul , or only in latest master?

**Comment by nicolas-raoul** [comment]
I am sure about v3.0.2 in particular, but I believe it has always been happening.
