### ISSUE TITLE
Is this a photo of place X: Do not ask if the item (depiction) is already selected for addition and the photo already has a caption

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#4497]
Latest master

In such cases, asking again has no positive benefit, and has some drawbacks:
- Takes time to think and answer
- If "Yes" is tapped, the caption (copied from previous media) is overwritten by a less useful caption

**Comment by Ayan-10** [comment]
@nicolas-raoul Can I work on it?

**Comment by nicolas-raoul** [comment]
@Ayan-10 It is yours, thanks!

**Comment by Ayan-10** [comment]
@nicolas-raoul Can you tell me by which image I can trigger `Is this a photo of place X` this dialog.

**Comment by nicolas-raoul** [comment]
@Ayan-10 Yes: Take a picture while being at the same coordinates as a Wikidata item (example: `48.8484, 2.35926`). You can use a FakeGPS app.

**Comment by Ayan-10** [comment]
@nicolas-raoul Immediate after clicking an image from the gallery with the same coordinates as a Wikidata item. The app is showing the dialog. 
Can you please elaborate what do you mean by this?
> Do not ask if the item (depiction) is already selected for addition and the photo already has a caption

**Comment by nicolas-raoul** [comment]
1. Take 2 pictures at location 48.8484, 2.35926 (using Fake GPS).
2. Select them both and start a multi-upload.
3. For the first picture, you get asked "is this a picture of ...", answer No.
4. For the second picture, the app asks again. It should "remember" and not ask again.

Same if you answer Yes at step 3, by the way.
