### ISSUE TITLE
Unit tests are breaking because of recent changes in some Activities

### ISSUE THREAD

**Issue by Ayan-10** [commons-app/apps-android-commons#4499]
**Summary:** 

Unit Tests are breaking because of recent changes in some Activities like QuizActivity and Logout State. Some methods are removed in those activities but those are not yet refected in Unit Tests.

**Steps to reproduce:** 

Run any unit tests

What did you expect the app to do, and what did you see instead?

**Commons app version:** 

latest master

**Would you like to work on the issue?**

Yes

**Comment by madhurgupta10** [comment]
@Ayan-10 can you check this PR #4491 

If there is still any specific test that is failing let us know

**Comment by Ayan-10** [comment]
@madhurgupta10 Yes, there are some in the latest master.

1. `MoreBottomSheetLoggedOutFragmentUnitTests` test `testOnTutorialClicked`
2. `QuizActivityUnitTests` test `testSetNextQuestion`

**Comment by madhurgupta10** [comment]
#4491 was already merged to the master branch, I just run all the tests on master and I don't see any issue. You can refetch the upstream master and update your local master branch and try again.
