### ISSUE TITLE
Only logged in users should be able to see manage EXIF tags setting

### ISSUE THREAD

**Issue by neslihanturan** [commons-app/apps-android-commons#4501]
**Summary:** 

 Manage EXIF tags should be disabled when user is not logged in, since it is not possible to upload photos if not logged in so EXIF tags are not an issue.

**Steps to reproduce:** 

Continue without login and go to settings. You will see EXIF setting is there for you. 

**Would you like to work on the issue?**

Preferably no and this is a beginner friendly issue.

**Comment by zachary-thomas-115** [comment]
I am willing to work on this!

**Comment by jeremybowenn** [comment]
I have a pull request for this out there called issue-4501-jeremybowenn
