### ISSUE TITLE
Rename "favorites" to "bookmarks"

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#4508]
The screen below uses both words "favorites" and "bookmarks" to refer to the same thing.
We should settle on one word, and use it in the whole UI ad source code (including variable names, ideally even database fields, to avoid one more hurdle for newcomers).

![adb](https://user-images.githubusercontent.com/99590/125882763-a334a4d9-689c-4795-ac62-af60211e20ab.png)

**Comment by misaochan** [comment]
I don't think it's too difficult to change, but I'm not sure which would be the most appropriate option. What do you think?

**Comment by nicolas-raoul** [comment]
No strong opinion.
https://www.techwalla.com/articles/what-is-the-difference-between-favorites-bookmarks says:

> Windows Internet Explorer is the only major Web browser that uses the term "favorites."

Given that Internet Explorer is really major anymore, I guess "bookmarks" will sound natural to more people?

**Comment by misaochan** [comment]
Sounds good to me. :)

**Comment by diamniko** [comment]
Hello, can I work on this?

**Comment by nicolas-raoul** [comment]
@diamniko Yes thanks!

**Comment by diamniko** [comment]
Hello, I committed in a new (local) branch but I can't push.

Also there's some screenshots:
![image](https://user-images.githubusercontent.com/56235463/130656985-b7b4d4e6-2743-4e50-a9ee-df0f37b36cc3.png)
![image](https://user-images.githubusercontent.com/56235463/130657013-636da93d-72c4-440b-808f-d1bfd91d065b.png)
![image](https://user-images.githubusercontent.com/56235463/130657033-63b04dd2-27f2-4eee-86cd-ceb25f0bf520.png)

**Comment by nicolas-raoul** [comment]
What happens exactly when you try to push?

**Comment by diamniko** [comment]
Hello, I still can't push...

**Comment by nicolas-raoul** [comment]
Please fork the repository before cloning.
See https://docs.github.com/en/get-started/quickstart/fork-a-repo
Thanks!

**Comment by Prince-kushwaha** [comment]
@nicolas-raoul  can i work on this issue

**Comment by nicolas-raoul** [comment]
@Prince-kushwaha It is yours, thanks! :-)
