### ISSUE TITLE
Hard to tell if we are looking at a scrolling list

### ISSUE THREAD

**Issue by jidanni** [commons-app/apps-android-commons#4513]
It's hard to tell if we are looking at a complete list or if there are more items that can be scrolled further.

![Screenshot_20210720-084156.jpg](https://user-images.githubusercontent.com/1230959/126245289-f8df2127-45e7-4bcf-873f-e8ac62bc14ae.jpg)

Version: latest beta.

**Comment by jidanni** [comment]
The only way to tell is to try scrolling it and if it scrolls then there are items below, which in fact is the case today.

**Comment by benryder1988** [comment]
Nice idea, the above pull request adds scrollbars to instances of RecyclerView so that is clearer when scrolling is available

**Comment by Prince-kushwaha** [comment]
@nicolas-raoul can i work on this issue

**Comment by nicolas-raoul** [comment]
@Prince-kushwaha  Yes thanks! The scrollbar should be visible whenever there are more items than fits. It should be visible from the beginning, even before the user starts scrolling.

**Comment by ShashwatKedia** [comment]
@nicolas-raoul I would like to solve this issue, if it's still open
