### ISSUE TITLE
Pasted text should have fonts unified

### ISSUE THREAD

**Issue by jidanni** [commons-app/apps-android-commons#4514]
![Screenshot_20210720-120519.jpg](https://user-images.githubusercontent.com/1230959/126260427-65a2f5f6-602a-4c48-9442-1b44a352c9de.jpg)
The fonts should become the same upon pasting. (We just pasted three words and added two words on the back.)
Latest beta.
All five words should be like the final two words.

**Comment by jidanni** [comment]
Yes, it does not affect the upload; all the characters are standard. It just looks bad in the app before we finish filling in the forms.

**Comment by nicolas-raoul** [comment]
Ah yes, I noticed this bug as well. It indeed looks bad and probably confuses a majority of the users who encounter that and believe that it will show up like this on Commons.

**Comment by sanchi0204** [comment]
Can I work on this?

**Comment by nicolas-raoul** [comment]
@sanchi0204 Yes thanks! 🙂

**Comment by Pranjal-dew** [comment]
hi there, can I contribute to this issue?

**Comment by nicolas-raoul** [comment]
@sanchi0204 Are you working on this? How is it going? 🙂

**Comment by dado1111** [comment]
So may I?

**Comment by jidanni** [comment]
Is there some way to manage internal assignments coordination better
than having them go to the same channel as the bug submitter?

I hope each role could be kept separate: But reporters just know about
reporting bugs, and could say "go right ahead" by accident to internal
staff assignment requests.

**Comment by nicolas-raoul** [comment]
@dado1111 No answer from either sanchi0204 nor Pranjal-dew so it is yours :-) Please let us know about your progress every few days.

@jidanni Indeed that could result in misunderstandings, thanks for your cooperation on that. By the way, only core developers can set assignees.
