### ISSUE TITLE
During upload wizard 'copy to subsequent media' copies language and row structure, but not captions and descriptions

### ISSUE THREAD

**Issue by benryder1988** [commons-app/apps-android-commons#4521]
**Summary:** 

So I started looking into issue #4391, and found an issue that is perhaps not related:
- During upload wizard 'copy to subsequent media' copies language and row structure, but not captions and descriptions

**Steps to reproduce:** 

- If I start the upload process with three images, enter some details in the Caption and Description field, and click 'copy to subsequent media' and then 'next', then the text is not copied into the fields
- If I start the upload process with three images, use the dropdown to change the language, enter some details in the Caption and Description field, and click 'copy to subsequent media' and then 'next', then the text is not copied into the fields - but the language does change for the subsequent media
- The above is true if I use the + button to add more rows for Caption and Description - the rows appear for subsequent media and the language changes, but the text doesn't appear in the corresponding boxes

Since the language and the new rows both appear, I think the copyTitleAndDescriptionToSubsequentMedia function in UploadMediaPresenter is copying the structure, and may be copying the data. But perhaps the text fields are not updating with the new values.

**Device and Android version:** 
**Commons app version:** 

Tested ProdBeta on Google Pixel 4a (5G) with API level 30 (Android Version 11)

**Would you like to work on the issue?**

Maybe - I'm looking into it, but might not have much time after today

**Comment by nicolas-raoul** [comment]
I noticed this too, it is very penalizing when uploading several pictures at the same time.

Anyone willing to do a bisect to find out what commit broke that feature? That would probably be the fastest way to finding a fix.

**Comment by Ayan-10** [comment]
@nicolas-raoul I think this issue is not occurring now?

**Comment by nicolas-raoul** [comment]
@Ayan-10 I am traveling so I can't test easily unforrtunately.
I can't reproduce the issue on 3.1.0-alpha.
Is it not happening on master either? If not this can be closed :-)

**Comment by Ayan-10** [comment]
@nicolas-raoul It's not happening in latest master too.

**Comment by nicolas-raoul** [comment]
@Ayan-10 Cool, thanks! :-)
