### ISSUE TITLE
Tap to view: could be success could be failure

### ISSUE THREAD

**Issue by jidanni** [commons-app/apps-android-commons#4523]
![Screenshot_20210725-072620.jpg](https://user-images.githubusercontent.com/1230959/126883277-bf3eb043-4b3f-4f42-a2e8-d8dadf213fdc.jpg)
We get the above notification, but  it could mean two things:
Success, or failure. In this case it just happens indicate failure. Why not be more clear in the message?

**Comment by jidanni** [comment]
PS, I tried to edit the image to crop it, but Github said the crop file size was too big. Hohoho.

**Comment by nicolas-raoul** [comment]
I _believe_ it changes to "Tap to view your upload" in case of success.

**Comment by jidanni** [comment]
Well even so, the failure case still would need to be reworded to make it clear it failed.

**Comment by 4D17Y4** [comment]
The issue is likely to be seen on devices with large font sizes.

The actual notification reads: `Uploading filename failed`.
And as we see the failed part is not visible.

We can refractor the notification to something on the lines of `Failed to upload filename`.
Thanks, @jidanni.

**Comment by Rishavgupta12345** [comment]
@nicolas-raoul  I would like to work on this issue please assign me
