### ISSUE TITLE
No images are showing in Items media tab

### ISSUE THREAD

**Issue by Ayan-10** [commons-app/apps-android-commons#4532]
**Summary:** 

No images are showing in the Items media tab.

**Steps to reproduce:** 

How can we reproduce the issue? 

1. Go to explore
2. Search Rabbit
3. Click Items Tab
4. Click any item
5. See the Media tab "No images found"

**Device and Android version:** 

Tested on
Pixel 2 API 30
Samsung J2 API 23
 
**Commons app version:** 

latest master

**Screen-shots:** 

https://user-images.githubusercontent.com/71203077/127760490-f8709154-2efa-4df7-8209-cf3a27082cd5.mp4

**Would you like to work on the issue?**

Yes

**Comment by nicolas-raoul** [comment]
Have you tried on the prodDebug flavor?
The beta server does not work for most Wikidata-related stuff. That might be the problem here.

**Comment by Ayan-10** [comment]
@nicolas-raoul Yes, that's the problem. I tested it in prodDebug and It working fine.

**Comment by nicolas-raoul** [comment]
More about the problem:

- #3135
- #3562

If you think we can improve the situation or developer documentation, please let us know.
Thanks!
