### ISSUE TITLE
Language selection: Search

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#4543]
The app has 3 places where a language can be selected: `App user interface language` and `Default description language`in Settings, and the Upload Wizard's Media Details dropdown. There are about a hundred languages, so it takes a long time to find the one you want.

It would be great if I could select a language by entering a few characters of the language's name.
Ideally in either the current app's language or the language itself. For instance if the UI is in English then both "ger" and "deu" (for Deutsch) would make the German language come up.

**Comment by jeremybowenn** [comment]
I can work on this, though I do have a question about searching by the current app's language. It looks like there is only a list for English names and another where each entry is the country's native language. So, if, for example, the current language was Spanish, we don't have a list of how Spanish translates German and all the other languages. Would we need to make a new list of languages for each language we add to have all of it's translations? Let me know if more clarification is needed.

**Comment by nicolas-raoul** [comment]
@jeremybowenn : It is OK to only perform the search using the lists we already have.

**Comment by Pratham2305** [comment]
@nicolas-raoul Can I work on this?

**Comment by nicolas-raoul** [comment]
@Pratham2305 Yes thanks!
