### ISSUE TITLE
Language selection: history

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#4544]
The app has 3 places where a language can be selected: `App user interface language` and `Default description language`in Settings, ` and the Upload Wizard's Media Details dropdown. There are about a hundred languages, so it takes a long time to find the one you want.

Since a user probably uses only a handful of languages, it would be great if we could show in a first sub-list the most-recently selected 5 (or 10) languages. They could be separated from the rest of the list by a simple separator.

**Comment by Ayan-10** [comment]
@nicolas-raoul I would like to work on it.

**Comment by nicolas-raoul** [comment]
By the way, just wondering: Do you receive an email notification when I assign an issue to you?

**Comment by Ayan-10** [comment]
@nicolas-raoul Yes, I do receive an email.

Also, I have made a UI regarding this issue. Please give your inputs.

<img src="https://user-images.githubusercontent.com/71203077/155337001-74565fa8-c4be-41ab-bece-3281e2953aeb.png" width=300/>

I was thinking to remove the recent searches section when the user will click on edit text as we can expect a user will only click on the edittext to search for a language that is not present in recent searches and as recent searches will contain 5 elements it will be unnecessary to search on 5 elements.

**Comment by nicolas-raoul** [comment]
Looks and sounds great! Thanks :-)
