### ISSUE TITLE
Another adaptation problem related to layout

### ISSUE THREAD

**Issue by yuhuitech** [commons-app/apps-android-commons#4550]
**Describe the bug**

Dear developer!
In the process of using, I found a bug in layout / display. As shown in the figure below, on the login page, **buttons of privacy and skip overlapped, which might be a severe problem**. This may be an adaptation problem. I suspect it is because **display and font size** are set to large **(mainly due to display size)**. And I have already submitted an issue report #4548 and a corresponding pull request #4549.

Still, the font and display are set to largest.
![103165857-dbaf8580-4857-11eb-9e22-120ae1901389](https://user-images.githubusercontent.com/25502419/128597553-7949a1a3-0b21-4ddf-9357-766b5c302518.png)

App version is 3.0.3, my mobile phone is Google Pixel 2, and the screen resolution setting is 1920* 1080. And **_my font size and display size are the largest ! ! !_** Also, my Android system version is 10.0.
The above is a description of the problem. The overall experience of the software is good. You can see that the design is very attentive. Thank you very much for the efforts of the developers all the time. I hope to receive a reply. Thank you so much!!

**Expected behavior**

I hope that the buttons of privacy and skip are separated.

**Steps to reproduce the behavior:**

1.use the largest font and display in the display setting
2.open this app for the first time, or go to the login page
3.this error could be seen

**Screenshot**

<img src="https://user-images.githubusercontent.com/25502419/129317429-cbc8a978-bfd8-48c1-8579-2f562506e891.png" alt="copy" width="250"/>

**Environment**

1. Version of Common: 3.0.3
2. Device : Google Pixel 2,
3. OS version : Android 10.0

**Comment by 4D17Y4** [comment]
Thanks for the report @yuhuitech, 
I think your PR #4549 fixes this issue too.
Feel free to edit issue #4548 description to mention the button overlap. 

Closing this, thanks.
