### ISSUE TITLE
Touching title should directly show us the details

### ISSUE THREAD

**Issue by jidanni** [commons-app/apps-android-commons#4556]
Here, if we touch one of the images, we see you the whole image. If instead we touch one of the titles, we instead again see the whole image.
![Screenshot_20210817-081729.jpg](https://user-images.githubusercontent.com/1230959/129644776-73d4ce68-e222-4450-adf9-07dc2f337dce.jpg)
In both cases if we want to see the details we need to flick down. I propose that if we touch one of the titles we should directly see the details.

**Comment by nicolas-raoul** [comment]
Material design for small screens means big tappable areas are a good thing.

Also, the app is trying to be as visual as possible, it is more engaging this way.

So I don't think that splitting tappable areas would be an improvement.
Anyone who disagree please comment below.

Thanks for the idea though!

**Comment by jidanni** [comment]
All I know is in the above image, we see (two) image areas, and (two) title areas.
No matter long press, short press, tap, or whatever, and no matter if it is done on an image area or a title area, all do the exact same thing! (I recall. My phone is at the cleaners today.)
