### ISSUE TITLE
Nearby: Save last known location and show it immediately without waiting for GPS

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#4571]
Whenever I start Nearby, the map shows the whole world (used to be centered on London).
How about centering on the last known location instead?
It won't make the pins appear faster (unless we decide to also load pins at the last known location while waiting for a GPS fix), but it is less surprising for the user.

**Comment by Pratham2305** [comment]
Hey @nicolas-raoul, I think it would be great. Can I work on this?

**Comment by nicolas-raoul** [comment]
Hi Pratham, great to see you again!
Sure, thanks :-)
