### ISSUE TITLE
Add Materialized Icon in DialogBox

### ISSUE THREAD

**Issue by jaimehta1912** [commons-app/apps-android-commons#4577]
**Summary:** 

Currently, the DialogBox which appears while Skipping Login seems to be in Default style. If there was a Materialized Icon relevalnce to the Functionality with primary color implemented in the DialogBox, this would improve the User Interface.

Maybe fixed on: #4578

**Steps to reproduce:** 

On Login Page, press `Skip`.

**Device and Android version:** 

Device Model: Realme XT
Android Version: Android 9.0 (Pie).
Stock from the Manufacturer.
 
**Commons app version:** 

Version: 3.0.2-debug-master.

**Screen-shots:** 

**Screenshot of current DialogBox:**

![WhatsApp Image 2021-08-25 at 3 52 15 AM](https://user-images.githubusercontent.com/54937640/130699253-7b496f20-aa65-4fb7-be79-876d07e04f98.jpeg)

**Would you like to work on the issue?**

I want to work on this Issue.

**Comment by neslihanturan** [comment]
I don't think this Pr improves the UI. Please feel free to reopen it if you don't agree :)
