### ISSUE TITLE
Refactor ShareActivity.java

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#458]
Unfortunately, ShareActivity is currently a big jumble of spaghetti code, haha. :/ It was already huge when we inherited the legacy app, but the complexity increased when I added to it during my newbie days as an Outreachy intern, and then again after we targeted API 23 and added runtime permissions checking.

I think ideally we would want to separate as much of the logic as possible into new classes - one for checking image coordinates, caching them, and initiating the calls to MediaWiki API for nearby categories; one for Uri handling; one for permissions if possible (not sure if possible since permissions require dialogs and thus access to the UI?)... and keep as little logic as possible in ShareActivity.java so that it is used mainly for interface code.

Not an easy undertaking, but it would be very appreciated if anyone wants to try. :)

**Comment by maskaravivek** [comment]
@misaochan I would like to pick it up. I have been just picking small tasks until now so working on this might help me get more familiar with the codebase.

**Comment by misaochan** [comment]
@maskaravivek that would be great, thanks! :)

**Comment by misaochan** [comment]
We probably need to whittle down the number of tasks remaining for the hackathon (since we only have 1.5 days left til the showcase on Sunday), so unless anyone wants to take this on personally, I'll remove the label.

**Comment by jakobsvenningsson** [comment]
Hello @misaochan! I would like to give this refactor a try. This is my first contribution to this project and I think this is a suitable task.

**Comment by maskaravivek** [comment]
Sure, @jakobsvenningsson. Feel free to take this up.

**Comment by misaochan** [comment]
Welcome, @jakobsvenningsson ! Please feel free. :)

**Comment by jakobsvenningsson** [comment]
I'm still working on the issue, I got a bit delayed due to some problems getting the tests running. However, I will soon make a first commit.

**Comment by jakobsvenningsson** [comment]
I have managed to move the permission logic and file image related processing logic to its own classes. I will continue with unit testing and some more refactoring.

**Comment by neslihanturan** [comment]
Tanks @jakobsvenningsson , looking forward for your PR.

**Comment by domdomegg** [comment]
@jakobsvenningsson Can we merge your changes? They look good, loving the unit tests 👍

**Comment by jakobsvenningsson** [comment]
@domdomegg  Yes, the changes are ready to be merged. I completely forgot to tell that the I finished the task when I worked on this issue in February last year. I'm sorry for that..

**Comment by misaochan** [comment]
Please correct me if I'm wrong (I'm not sure which PR the changes are in), but unfortunately it seems to me that this task is outdated as of today. #1968 will be merged shortly, which completes the overhaul.

**Comment by domdomegg** [comment]
Done in #1968
