### ISSUE TITLE
Send Log File does not work, no logs attached

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#4585]
**Summary:** 

I used Send Log File today and this is all that was sent:

> USER_COMMENT=null
> APP_VERSION_CODE=1021
> APP_VERSION_NAME=3.0.2-debug-3.1-release-alpha
> ANDROID_VERSION=11
> PHONE_MODEL=SM-G781B
> STACK_TRACE=Report requested by developer
> 
> IS_SILENT=true
> REPORT_ID=f5ece12b-0f67-46a0-a060-92d477532808
> USER_CRASH_DATE=2021-08-26T17:10:41.296+10:00 
> 

As you can see there are no logs attached, but there should be.

I am using Gmail on Samsung Galaxy S20FE, Android 11
 
**Commons app version:** 

prodDebug. 3.1-release branch, but I think this should exist for master too, since we changed nothing with logs in that branch.

**Would you like to work on the issue?**

No

**Comment by misaochan** [comment]
Ahh, the PR does not work for me. :( I tested 3.1-release after merging both PRs, and the Send Log File still does not send any files.

```
USER_COMMENT=null
APP_VERSION_CODE=1021
APP_VERSION_NAME=3.0.2-debug-3.1-release
ANDROID_VERSION=11
PHONE_MODEL=SM-G781B
STACK_TRACE=Report requested by developer

IS_SILENT=true
REPORT_ID=c6c66758-2c54-423f-b3dc-3184c3218eb5
USER_CRASH_DATE=2021-08-31T22:57:09.742+10:00 
```

**Comment by madhurgupta10** [comment]
@misaochan Due to the changes in Android 10 and above we need the following permission to write the log zip file to external storage, https://developer.android.com/about/versions/11/privacy/storage#maintain-compatibility-android-10
```
MANAGE_EXTERNAL_STORAGE
```
Not sure how it impacts the app review on Google Play

**Comment by misaochan** [comment]
Hmm. I looked this up, and due to the changes required (including the sdk version update), I think we would be better off doing this in master rather than in a release branch that is due for release soon. Could you rebase your PR to master please? Thanks!
