### ISSUE TITLE
Add In-App Update Prompt

### ISSUE THREAD

**Issue by jayant99acharya** [commons-app/apps-android-commons#4586]
**Summary:** 

If there is an update for Commons Android App, the only way how users could know about it is the notification from the Play Store. Sometimes, users enable the Auto-Update, but mostly only when connected to Wi-Fi. If there was a way to notify users about the Update inside the app regardless of Wi-Fi or mobile data, whenever a newer version is released, it would be better.

Maybe fixed on: #4587.

**Device and Android version:** 

Device Model: Realme XT.
Android Version: Android 9.0 (Pie).
Stock from the Manufacturer.
 
**Commons app version:** 

Version: 3.0.2-debug-master.

**Would you like to work on the issue?**

Yes I want to work on this Issue.

**Comment by sivaraam** [comment]
Closing a long dormant issue. Feel free to reopen if it seems like it'll be a useful addition.
