### ISSUE TITLE
Empty screen while no images found in custom picture selector

### ISSUE THREAD

**Issue by Ayan-10** [commons-app/apps-android-commons#4589]
**Summary:** 

When there is no image in the device, Custom picture selector opens with a white empty screen.

**Steps to reproduce:** 

1. Make sure there is no image in the device
2. Click the + icon 
3. Select custom picture selector

What did you expect the app to do, and what did you see instead?

There should be some information like "No images found" (with some graphic)

**Device and Android version:** 

Pixel 2 API 30
 
**Commons app version:** 

Betadebug latest master

**Screen-shots:** 

<img src="https://user-images.githubusercontent.com/71203077/131242417-bb3946dd-9529-4128-9a81-e1fdb8735d65.png" width=300/>

**Would you like to work on the issue?**
YES

**Comment by 4D17Y4** [comment]
Thanks for spotting that @Ayan-10 
Would be a nice improvement.

To add to the issue, a similar message can be shown in the image fragment when the folder is empty (delete images in the current folder and return to the custom selector).

**Comment by Rishavgupta12345** [comment]
@nicolas-raoul i would like to work on this issue please assign me

**Comment by nicolas-raoul** [comment]
I would be in favor of just showing "No images found" and no graphic (unless the app already embeds a usable graphic) in order to not make the app heavier for this edge user case.
Thanks! :-)
