### ISSUE TITLE
FAB of custom selector is still open after uploading

### ISSUE THREAD

**Issue by Ayan-10** [commons-app/apps-android-commons#4590]
**Summary:** 

FAB of the custom selector is still open after uploading an image from it and taking the user to the last opened folder

**Steps to reproduce:** 

1. Click + icon and click FAB of the custom selector
2. upload an image

What did you expect the app to do, and what did you see instead?

It should close the FAB after clicking it.

**Device and Android version:** 

Pixel 2 API 30
 
**Commons app version:** 

Betadebug latest master

**Comment by nicolas-raoul** [comment]
Thanks Ayan for spotting this! :-)

**Comment by jmora13** [comment]
Is this open? I'd like to contribute to it

**Comment by nicolas-raoul** [comment]
@jmora13 Yes thanks! :-)
