### ISSUE TITLE
Add Themed more_bottom_sheet

### ISSUE THREAD

**Issue by jaimehta1912** [commons-app/apps-android-commons#4597]
**Summary:** 

Currently, the More section which triggers a bottom_sheet layout seems to be default in style. If there was a bottom_sheet which adheres to the primary color of the android application, it would enhance the user interface and theme of the entire app.

Maybe fixed on: #4598

**Steps to reproduce:** 

Click on more on the bottom navbar.

**Device and Android version:** 

Device Model: Realme XT
Android Version: Android 9.0 (Pie).
Stock from the Manufacturer.
 
**Commons app version:** 

Version: 3.0.2-debug-master.

**Screen-shots:** 

**Current bottom_sheet:**

![WhatsApp Image 2021-08-31 at 8 11 45 PM](https://user-images.githubusercontent.com/54937640/131525112-3b1c4e02-26a2-4a10-b226-7b1334bf0e60.jpeg)

**Would you like to work on the issue?**

Yes, I would like to work on this Issue.

**Comment by nicolas-raoul** [comment]
I have no strong opinion on this as I am not a UI expert, the new look seen in your PR's screenshot seems reasonable to me.

**Comment by neslihanturan** [comment]
I don't think this will improve the UI, so closing for now. Please feel free to reopen :)
