### ISSUE TITLE
Change Facebook Icon color on About activity

### ISSUE THREAD

**Issue by jaimehta1912** [commons-app/apps-android-commons#4599]
**Summary:** 

In the About activity of the app, the Facebook icon is black. If it were changed to the official color of Facebook, it would enhance the user interface.

May be Fixed on: #4600.

**Steps to reproduce:** 

Click More > About.

**Device and Android version:** 

Device Model: Realme XT
Android Version: Android 9.0 (Pie).
Stock from the Manufacturer.
 
**Commons app version:** 

Version: 3.0.2-debug-master.

**Screen-shots:** 

**Current About activity:**

![WhatsApp Image 2021-08-31 at 9 10 48 PM](https://user-images.githubusercontent.com/54937640/131534633-f2723709-4042-4ebd-9f8a-2571ab73fd3d.jpeg)

**Would you like to work on the issue?**

Yes, I would like to work on this Issue.

**Comment by nicolas-raoul** [comment]
Thanks for suggesting!
This color is on purpose, though, to improve coherence between the 3 icons.
