### ISSUE TITLE
Campaigns come back despite promise

### ISSUE THREAD

**Issue by jidanni** [commons-app/apps-android-commons#4606]
Here it says we won't see any more campaigns:
![Screenshot_20210904-111348.jpg](https://user-images.githubusercontent.com/1230959/132083282-de47ed3c-4ff9-4f44-af53-97f89bc68b23.jpg)
But the next time we open the app the campaigns are right there:
![Screenshot_20210904-130943.jpg](https://user-images.githubusercontent.com/1230959/132083298-3584d5f9-2c40-4dd1-af9e-312b599ebb11.jpg)
Version: latest beta.

**Comment by Ayan-10** [comment]
Can't reproduce it on the latest betaDebug master. 
<img src="https://user-images.githubusercontent.com/71203077/144373556-0612e56c-695c-4e91-bbdf-098070ea2a40.png" width=300/>

**Reopening**
![Screenshot_1638428023](https://user-images.githubusercontent.com/71203077/144374050-2672da5d-4ab6-44f5-aa6e-2687faea6f1b.png)

**Comment by jidanni** [comment]
OK good.
