### ISSUE TITLE
Pencil only next to coordinates

### ISSUE THREAD

**Issue by jidanni** [commons-app/apps-android-commons#4609]
Here, the pencil only appears next to the coordinates. It is oddly absent next to the other items.
![Screenshot_20210905-095753.jpg](https://user-images.githubusercontent.com/1230959/132112522-32aca009-a2c2-47f1-bcab-7f72b359ce9f.jpg)
Latest beta.

**Comment by sivaraam** [comment]
That's because the co-ordinate edit option was recently added to the app (ref. #8). You should also see and edit option for the categories, though. Do you not see it?

**Comment by jidanni** [comment]
Yes , that's true I see the pencil way down at the bottom of all the categories. However it's very weird that some items can be edited and some cannot. I thought it was something wrong with my screen (senior citizen font choice.)

**Comment by jidanni** [comment]
One gets the impression that it is some permission problem. Thus one would not think about going to the website to edit those items.

I would hold off on adding these pencils until they're all ready.

**Comment by nicolas-raoul** [comment]
I created https://github.com/commons-app/apps-android-commons/issues/4615 and https://github.com/commons-app/apps-android-commons/issues/4616

Do you see anything else that should be made editable?

**Comment by jidanni** [comment]
Well even in the above picture, Licence is missing a pencil.
I.e., what should **not** be editable?

**Comment by nicolas-raoul** [comment]
Considering maintenance costs, we should focus on features that many people actually need.

We can leave this one to the desktop website UI. By the way, on the website I am sure that 99% of the users have never edited a license, and most of the users who edited one did it by mistake.

**Comment by jidanni** [comment]
Maybe have grey pencils for those, that when tapped say "please use the website
version to edit." That way all editable items still can have pencils.
