### ISSUE TITLE
Code walkthrough for new devs

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#461]
I was looking back through my old notes on the app, and found some that I wrote when I was getting to know the codebase. They are very informal and possibly not 100% technically accurate, but I wondered if they might be helpful to a new contributor. I know the Readme has some basic information, but it doesn't really go in depth into the working of the app (nor should it, otherwise it would be too long).

I copied my old notes into this wiki: https://github.com/commons-app/apps-android-commons/wiki/Code-walkthrough-for-new-devs-(draft) . If anyone is interested, please feel free to read, modify, etc.

**Comment by domdomegg** [comment]
Agree it would be super useful to have a guide for new contributors - but I enjoy the very informal style (providing the same information is given), gives me a chuckle reading [some comments](https://github.com/commons-app/apps-android-commons/blob/master/app/src/main/java/fr/free/nrw/commons/Utils.java#L191).
