### ISSUE TITLE
Make custom image selector available from Nearby

### ISSUE THREAD

**Issue by Ayan-10** [commons-app/apps-android-commons#4611]
**Summary:** 

In the current state of the app, custom image selector is only available from contributions fragment. We also upload images from Nearby. What about making the custom image selector available from Nearby too ( If that has no disadvantages).

**Comment by Eric-peng111** [comment]
@Ayan-10  can I take this issue?

**Comment by Ayan-10** [comment]
I think @nicolas-raoul can help you with that.

**Comment by Eric-peng111** [comment]
@nicolas-raoul Can I please take this issue ? Thanks

**Comment by nicolas-raoul** [comment]
Hi @Eric-peng111 Would you mind working on bugs first per https://github.com/commons-app/commons-app-documentation/blob/master/android/Volunteers-welcome!.md ? Thanks a lot! 🙂

**Comment by Eric-peng111** [comment]
@nicolas-raoul Thanks for replying
I'd like to take first issue 
However, I already fixed about 90% of the issue as this:
![image](https://user-images.githubusercontent.com/111075450/197372268-6ba175e7-ad97-4a92-8b90-4fbb29cb7446.gif)

is it possible to let me do this at first ?
Sorry I did not know this policy.

**Comment by nicolas-raoul** [comment]
Hard question 😱
OK for this time exceptionnally, but please keep in mind that it might take a very long time before we review it. Thanks for your understanding! 🙂

**Comment by Eric-peng111** [comment]
Thanks for letting me do this issue
@Ayan-10 @nicolas-raoul  can u assign this issue to me at this point?

**Comment by Eric-peng111** [comment]
Hi @nicolas-raoul 
I think I done this issue since I tested by debug, so I submitted  the first PR to this issue, pls have a check when u have time
No need to rush since you said gonna take time to review
Thanks

**Comment by shashankiitbhu** [comment]
Hi @nicolas-raoul do we still want to do this ? I still see Custom Selector not available in Nearby , if yes, then can I work on this ?

**Comment by nicolas-raoul** [comment]
Yes thanks! 🙂

**Comment by nicolas-raoul** [comment]
@shashankiitbhu Maybe you can build upon Peng's pull request?

**Comment by shashankiitbhu** [comment]
> @shashankiitbhu Maybe you can build upon Eric's pull request?

There seems to be a lot of conflicts since the Project has changed significantly since then but I'll definitely take a look at it.

**Comment by shashankiitbhu** [comment]
@nicolas-raoul Added the Enhancement and since the Enhancement was to be made in NearbyParentFragment which was still not migrated to view binding so I also migrated it to view binding in the same PR so that it's easier to test , Please Review
