### ISSUE TITLE
Add some in-app instructions for the new WLM feature

### ISSUE THREAD

**Issue by sivaraam** [commons-app/apps-android-commons#4614]
**Summary:** 
The new WLM feature in the app is a nice improvement but it could be improved a little w.r.t in-app instructions. Right now, when I tap on the WLM banner I'm taken to the Nearby screen. I see a small banner about WLM there. It has a link which takes me to the general WLM info page.

Other than that, there's no information in-app about what needs to be further. Even the though the app might do many things to handle WLM related things in the background, the user is not aware of it. It would be nice if more information is added about further steps, how the feature works etc. to make the user aware of it.

**Device and Android version:** 
OnePlus Nord running Android 11
 
**Commons app version:** 
3.1.0~b41882639

**Comment by misaochan** [comment]
This sounds like a good idea. Do you reckon we could use an 'i' tooltip similar to the ones used in uploading? And if so, where would be a good place to put it?

**Comment by sivaraam** [comment]
I guess 'I' tooltips won't be as helpful. I was envisioning something like a card based intro to contributing to WLM using our app.

If that sounds like too much work to so before the public release, we could setup a wiki page with instructions on how to contribute to WLM using our app. Something like in the "Overview" section of the ["WLM" feature description wiki](https://commons.m.wikimedia.org/wiki/Commons:Mobile_app/WLM_release) tuned for wider public audience would do. We could link that in place of the general WLM page that "Learn more" in the Nearby banner points to. We could link to the general WLM page from the wiki page instead.

**Comment by misaochan** [comment]
> If that sounds like too much work to so before the public release, we could setup a wiki page with instructions on how to contribute to WLM using our app

Great idea! 

Would you be willing to set this up, @sivaraam ? I don't think I would have the time to make it myself, but we can change the link if we can get a decent page up by Monday.

**Comment by sivaraam** [comment]
Sorry I was offline the past weekend. I've managed to create a page based on the "Outcome" section of the ["WLM" feature description wiki](https://commons.m.wikimedia.org/wiki/Commons:Mobile_app/WLM_release) page (as noted). I've tweaked the content a bit to make it relevant for public audience. You could find it here: https://commons.wikimedia.org/wiki/Commons:Mobile_app/Contributing_to_WLM_using_the_app

Please proofread it and make any amendments in case I mentioned something incorrectly. One thing that might particularly need a change is the version number in the first sentence. I've used v3.1.0 for now. We would need to change it to v3.1.1 or v3.1.2 depending on which one would be publicly released.

**Comment by misaochan** [comment]
Thanks a lot @sivaraam ! I've made a couple of small edits, just to add the link for more details and changing the version to v3.1 (which works for all potential releases ;)).

We will add the link in-app shortly.

**Comment by misaochan** [comment]
Link added at c36aeeedc237705601871c9713bf56fc89f48831
