### ISSUE TITLE
Media details: Make caption and description editable

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#4615]

**Comment by Ayan-10** [comment]
@nicolas-raoul After making the coordinates editable I was thinking about making this enhancement. But for my exams, I am delaying. So can I work on these two enhancements?

**Comment by Ayan-10** [comment]
@nicolas-raoul For editing caption and description should I reuse the existing UI for taking input for description and caption?

**Comment by nicolas-raoul** [comment]
@Ayan-10 Yes that would be great, as it already implements some complexities like language addition :-)

**Comment by nicolas-raoul** [comment]
Great to hear that Ayan!

The captions are powered by the Wikibase software (where it is called `label`), which means they should be easier (and more reliable) to edit than wikitext :-)
You need to edit the label of the image in the wikibase server of Commons. I believe you will need to call `getEntityForImage` from `app/src/main/java/fr/free/nrw/commons/media/MediaDetailInterface.java` then set the label of that object, or something like that.

**Comment by Ayan-10** [comment]
@nicolas-raoul `action=wbsetlabel` is working. By mistake I was making the set call with the production URL in prod sandbox for a beta server's media that's why it was showing an error.
