### ISSUE TITLE
Media details: Make depictions editable

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#4616]
Let the user add/remove depicted Wikidata items.
Even on pictures they did not upload themselves.

Implementation: Please reuse the Upload Wizard's depictions selection dialog:
![adb](https://user-images.githubusercontent.com/99590/132470450-9c5bcf54-4648-49e8-884d-6fbe3b96e6b6.png)

**Comment by Ayan-10** [comment]
Yes, we can do the similar as the categories have.

**Comment by nicolas-raoul** [comment]
> Yes, we can do the similar as the categories have.

Please beware that the categories selection UI might not be ideal though: #4620

**Comment by Ayan-10** [comment]
@nicolas-raoul I was talking about using the update category UI. Not the one you mentioned in #4620

**Comment by nicolas-raoul** [comment]
@Ayan-10  I added an "implementation" section above to make the issue clearer :-)

**Comment by Ayan-10** [comment]
@nicolas-raoul I was trying to find an endpoint for posting depicts(or wikidata) but can't find any. Can you help me with that?

**Comment by nicolas-raoul** [comment]
You should be able to use the exact same API call as in the Upload Wizard. The Upload Wizard first uploads the picture, then adds depictions as a second step, so hopefully you can reuse the code of the second step :-)
