### ISSUE TITLE
WLM multi-upload

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#4617]
In normal Nearby, it is natural to upload only **one** picture, because each Wikidata item should have one and only one image.

On the other hand, WLM monuments can have many pictures, the more the better.

Thus it would make sense to have Nearby's WLM pins open a multi-file picker, rather than the current single-file picker.

**Comment by pratik2315** [comment]
Hello sir, I would like to work on this issue if its still available/workable.

**Comment by nicolas-raoul** [comment]
@pratik2315 It is yours, thanks! Please let us know about your progress at the end of each day, if possible :-)

**Comment by pratik2315** [comment]
Hey @nicolas-raoul pls check and tell me if i have made any mistakes.
Thanks for your time.
