### ISSUE TITLE
All the pictures guaranteed to be from the same user, so why show the user name?

### ISSUE THREAD

**Issue by jidanni** [commons-app/apps-android-commons#4619]
In 
![Screenshot_20210905-103606.jpg](https://user-images.githubusercontent.com/1230959/132113028-279976e3-d77c-4eb7-8df1-78f3d7dd1222.jpg)
aren't all the pictures guaranteed to be from the same user, "Jidanni"?

So can't that line be eliminated? Latest Beta.

**Comment by nicolas-raoul** [comment]
One hand hand, yes, some space could be saved.
One the other hand, consistency is good for user experience, and having the exact same code for Contributions and Explore reduces maintenance cost.

I let UI experts decide :-)
