### ISSUE TITLE
Starting uploads notification can be cleaned up earlier

### ISSUE THREAD

**Issue by jidanni** [commons-app/apps-android-commons#4631]
This starting uploads notification is, yes, eventually cleaned up. But it could be cleaned up already at this stage.
![Screenshot_20210919-100504.jpg](https://user-images.githubusercontent.com/1230959/133913136-7f2d45b8-45b2-4f5a-984f-7dd677379689.jpg)
Latest beta.

**Comment by Ayan-10** [comment]
@jidanni You mean this "Starting uploads notification" should be dismissable. Right?

**Comment by jidanni** [comment]
Well, in the image above, it is like we see two headlines on the same newspaper:
- Biden winning in early results
- Biden won
Well, shouldn't the old news be replaced by the new news, and not just accumulate there on the headlines?

**Comment by Ayan-10** [comment]
Ok. I got it. Thanks for the amazing explanation.

**Comment by Ayan-10** [comment]
Can I work on it?
