### ISSUE TITLE
White symbols won't show up on white backgrounds, making the camera seem broken

### ISSUE THREAD

**Issue by jidanni** [commons-app/apps-android-commons#4655]
Today I wanted to try just directly using the camera. Okay so I pushed the plus button, and then I pushed the camera icon, and indeed I took a picture.

Okay, now I am just looking at my picture, full screen. Maybe it is waiting for something. Who knows. There's no message on the screen. So after about 20 seconds I just hit the back button. Anyway I couldn't find the picture I just took anywhere. So I took another picture and then from the gallery, uploaded it just fine, as usual.

Latest beta. Android 8.0. Asus Zenfone 3.

**Comment by misaochan** [comment]
Could you post a screenshot of what you see after you have taken the picture, please? Thanks!

**Comment by jidanni** [comment]
I just see the picture I took, fullscreen.
It just stays there. Many many seconds.
Tapping it does nothing.
So I hit the cellphone's back button to leave the app.

**Comment by misaochan** [comment]
There should be a "Retry" and "Ok" at the bottom of the screen. They do not show up at all for you?

**Comment by jidanni** [comment]
Well, I didn't see any.
I would love to test again,
but that will have to wait for me to find a special plant or insect to take a picture of,
as I don't want to create a junk file on Commons that needs to be deleted,
and there is no other way to test.

**Comment by misaochan** [comment]
You can test without uploading, just tap the back button once you get to the Caption/Description step and it will ask if you are sure you want to cancel your upload.

Please do take a screenshot if you manage to test it again, too. :)

**Comment by jidanni** [comment]
I completely understand the problem now!

The two symbols you mentioned are indeed there.

But **they are white**.

That is fine, except when they end up on a white background!

Then they become **nothing**!

Apparently they were only tested on dark backgrounds!

Therefore they need their own "personal black backgrounds" to ensure
they will show up on **any** background!

It's just that simple! Thanks.

**Comment by misaochan** [comment]
Can you post a screenshot please? Sounds like a simple fix that I could make a "good first issue" (so a volunteer can easily solve them), but to do that I need a screenshot so we can discuss it with clarity.

**Comment by jidanni** [comment]
It's real simple. Just take a picture of this mostly white GitHub screen.
Or even better: just a white sheet of paper.
So imagine a white screenshot:








Can you see any buttons on it? No. Because the buttons are white!

**Comment by Open-Sorcerer** [comment]
Unfortunately this can not be changed from within the code as it is dependent on the default camera app that the commons app opens by [sending the MediaStore.ACTION_IMAGE_CAPTURE intent](https://github.com/commons-app/apps-android-commons/blob/7ab561f23888a090a147f86fa08aa15c62f29847/app/src/main/java/fr/free/nrw/commons/filepicker/FilePicker.java#L70) .

The confirmation layout of the camera app would vary depending on which camera app it is, it doesn't  necessarily has to have "Ok" and "Retry" buttons. For instance, the default camera app on a pixel device shows the confirmation something like this: 
![pixel confirmation](https://user-images.githubusercontent.com/81802035/136633925-bfff8a49-0e6f-4f1f-83f3-09c01cf0fe9f.png)

Only workaround is to implement our own Camera UI with our own confirmation activity. Not sure if that is worth it though, as almost all of the users would have a default camera app which won't have this bug. However, you could discuss it with the the project owners and if they think it would be a good idea to implement a custom camera ui, I could give it a go. 

Btw, which camera app are you using as the default one on your zenfone?

**Comment by jidanni** [comment]
That's all above my head.
Anyways, OK, I will just always upload from the Gallery app.
> Btw, which camera app are you using as the default one on your zenfone?

Yes.

**Comment by jidanni** [comment]
Asking users to replace their camera app?

How about just take the picture we just took, and show it to us, with your own little yes or no buttons on the bottom. In fact, it would be just like one of those social networking apps where you see a picture and there's two buttons on the bottom green and red.

**Comment by jidanni** [comment]
![Screenshot_20211010-085446.jpg](https://user-images.githubusercontent.com/1230959/136677434-5fc71365-4f86-4db1-bb15-3ddb15c5c4fa.jpg)

**Comment by nicolas-raoul** [comment]
Here is how it looks on Samsung:
![Screenshot_20211112-184627_Camera](https://user-images.githubusercontent.com/99590/141446936-cd5bfc04-6c7e-4a1b-80aa-ca0a8c779eb5.jpg)

**Comment by nicolas-raoul** [comment]
I agree that this is not something we can solve, unfortunately.
You should tell ASUS support that it is about their camera app **when launched by a ACTION_IMAGE_CAPTURE intent**.
Cheers!
