### ISSUE TITLE
Press a button to scroll to the top of the Favorites tab

### ISSUE THREAD

**Issue by codingtosh** [commons-app/apps-android-commons#4670]
This is similar to #4557 and #4669, the functionality to conviniently scroll to the top of the list is missing in the "Favorites" tab as well.

**Steps to reproduce:** 
Scroll down to a large extent in either the "PICTURES" or "LOCATIONS" tabs, say, 50th entry on the list. Becomes inconvinient to scroll back to the top manually with multiple finger swipes or navigate away and then come back to the tab 

**Proposed solution:**
1. Pressing on the PICTURES button on the top should scroll to the top of Pictures list.
2. Pressing on the LOCATIONS button on the top should scroll to the top of the Locations list.
3. Pressing on the FAVORITES button in bottom navigation bar should scroll to the top of both PICTURES and LOCATIONS tab.

I would like to work on this, please assess the feasibility of the proposed solutions and assign this to me.

**Comment by codingtosh** [comment]
Hey @misaochan  sorry for the late reply, missed the notification. So the reason I have also proposed the third solution is because it is a common design to scroll/refresh the feed/list by clicking on the bottom navbar button, for example, youtube, twitter, facebook android app also have this. 

Also, I had proposed the same solution in #4557 and have submitted a [PR](https://github.com/commons-app/apps-android-commons/pull/4668) for that. So I figured we should have this same design across the app, in all the tabs.

But I take your point that pressing the Title in the toolbar above should also have that functionality in order to have consistency within the Explore and Bookmarks tab as well, so I what think we could do is, 

Have the list be scrolled both by pressing the navbar button in the bottom and the Title in the toolbar above in all  #4557 , #4669 and here in #4670. 

Please assign this and #4670 to me. I am participating in the Hacktoberfest and it would be nice to get at least 4 PRs merged before the 30th.

**Comment by Rishavgupta12345** [comment]
@nicolas-raoul i would like to work on this issue please assign me

**Comment by Rishavgupta12345** [comment]
@nicolas-raoul @4D17Y4  I would like to work on this issue please assign me

**Comment by misaochan** [comment]
I believe this has been fixed by #4668 ?
