### ISSUE TITLE
Robolectric 'application: Application!' is deprecated. Deprecated in Java

### ISSUE THREAD

**Issue by madhurgupta10** [commons-app/apps-android-commons#4671]
**Summary:** 
`'application: Application!' is deprecated. Deprecated in Java` so we should use `ApplicationProvider.getApplicationContext()` in All Robolectric Unit Tests

Link for help: https://stackoverflow.com/questions/52883747/robolectric-runtimeenvironment-application-is-deprecated-where-is-applicationpr

**Would you like to work on the issue?**
No

**Comment by bernabesc** [comment]
Could you assign me this one?

**Comment by madhurgupta10** [comment]
@bernabesc Sure, thanks :)

**Comment by Asgardian8740** [comment]
Hi,
Is this issue open?
Can i work on this?

**Comment by bernabesc** [comment]
If he has time go ahead and assign it to him, got stuck on another fix. Sorry for the inconvenience

**Comment by glitched-sudhanshu** [comment]
@madhurgupta10 @Asgardian8740 is this issue solved now?
Or can I look into this?

**Comment by madhurgupta10** [comment]
@glitched-sudhanshu Feel free to pick up this issue :)

**Comment by glitched-sudhanshu** [comment]
@madhurgupta10 I will surely have a look at it.

**Comment by bhavanagarlapati** [comment]
Hi @nicolas-raoul Can I take this up?

**Comment by nicolas-raoul** [comment]
@glitched-sudhanshu Any progress on this? :-)

@bhavanagarlapati Please take one issue at a time. Do not hesitate to come back to this one after sending a pull request for your currently assigned one. :-)

**Comment by RitikaPahwa4444** [comment]
Hi @nicolas-raoul, is there any update on this issue? Can I take it up?

**Comment by nicolas-raoul** [comment]
@RitikaPahwa4444 It is yours, please let us know about your progress every few days, thanks! :-)

**Comment by RitikaPahwa4444** [comment]
Thank you @nicolas-raoul. I'll surely update my progress regularly :)

**Comment by nicolas-raoul** [comment]
@RitikaPahwa4444 I have not checked but would you mind sending a pull request? It is easier to comment on :-)
Thanks!

**Comment by RitikaPahwa4444** [comment]
I just wanted to reiterate the steps I had taken to confirm the requirements and update you about my progress here. I have created a pull request now :)
