### ISSUE TITLE
Use a real progress bar in the app

### ISSUE THREAD

**Issue by jidanni** [commons-app/apps-android-commons#4679]
I discovered if one keeps on looking at the app during a picture upload, one just sees a fake progress bar imitation. If one wants to see a real progress bar one just has to pull down the notifications. So please use the same real progress bar that you have in  notifications, also in the app. Thanks. You might need a very slow network to see what I'm talking about. Version: latest beta.

**Comment by Rishavgupta12345** [comment]
I would like to work on this issue PLease assign me

**Comment by sivaraam** [comment]
Hi @Rishavgupta12345 ! We [usually assign 'enhancements'](https://github.com/commons-app/commons-app-documentation/blob/master/android/Volunteers-welcome!.md#developers) only to contributors with more than 5 merged pull requests. You take a look at issues [tagged with 'good first issue'](https://github.com/commons-app/apps-android-commons/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22) instead.

**Comment by devarsh-mavani-19** [comment]
@jidanni I am able to see the same thing in the notification progress bar and on-screen progress bar when uploading images. can you please share a screenshot of the notification progress bar? Thanks1

**Comment by nicolas-raoul** [comment]
@devarsh-mavani-19 Yes thanks! To answer your question: When uploading a picture, the contributions activity shows a bar which goes left to right, it is the same animation that loops the same way without any indication of what percentage of the upload has been accomplished. On the opposite, the progress bar in Android's notification area shows more or less accurately what percentage of the upload has been accomplished so far.
