### ISSUE TITLE
App requests READ_PHONE_STATE permission for map

### ISSUE THREAD

**Issue by neslihanturan** [commons-app/apps-android-commons#4682]
**Summary:** 

I think this feels weird to request phone state for map. This was required to solve #4447 with #4677 .

**Comment by nicolas-raoul** [comment]
I was also extremely surprised, and denied permission the first time. If I did not trust everyone personally in this team, I would probably have uninstalled the app.
![Screenshot_20211105-214245_Package installer](https://user-images.githubusercontent.com/99590/141422870-4d2a7a29-1128-4fdf-b0f2-2d920a5fec5b.jpg)
![Screenshot_20211105-214254_Commons](https://user-images.githubusercontent.com/99590/141423192-15623d55-0753-4df9-be4f-6350765dcaf9.jpg)

We really need to find a way to not rely on this permission.

**Comment by nicolas-raoul** [comment]
Has anyone tried the workarounds described at https://github.com/mapbox/mapbox-gl-native-android/issues/425#issuecomment-860182436 or https://github.com/mapbox/mapbox-gl-native-android/issues/425#issuecomment-865627138 ?

**Comment by misaochan** [comment]
I agree, we should look into fixing this. According to https://github.com/mapbox/mapbox-gl-native-android/issues/425#issuecomment-680753940 , Mapbox has already fixed this bug, so we just need to use the latest version? @ashishkumar468 @neslihanturan
