### ISSUE TITLE
Add "good first issue" badge to README

### ISSUE THREAD

**Issue by madhurgupta10** [commons-app/apps-android-commons#4696]
**Summary:** 
How about adding a "good first issue" badge to the Readme file? This will help new contributors (not familiar with GitHub issue discovery system) to easily discover issues to work upon?

[![good first issues open](https://img.shields.io/github/issues/commons-app/apps-android-commons/good%20first%20issue.svg)](https://github.com/commons-app/apps-android-commons/issues?q=is%3Aissue+is%3Aopen+label%3A"good+first+issue")

**Would you like to work on the issue?**
No

**Comment by misaochan** [comment]
Good idea IMO. :)

**Comment by matkoniecz** [comment]
@madhurgupta10  Where have you seen such badges? Is there some trustworthy service for generating image with proper count?

**Comment by madhurgupta10** [comment]
> @madhurgupta10 Where have you seen such badges? Is there some trustworthy service for generating image with proper count?

@matkoniecz  We can use https://shields.io/category/issue-tracking to generate custom badges, this is an open-source project (https://github.com/badges/shields) and seems to be quite popular :)

**Comment by matkoniecz** [comment]
`repo:commons-app/apps-android-commons is:issue is:open label:"good first issue" ` query 

`"good first issue" issues` label

on https://shields.io/category/issue-tracking

gives ![GitHub issue custom search](https://img.shields.io/github/issues-search?label=%22good%20first%20issue%22%20issues&query=repo%3Acommons-app%2Fapps-android-commons%20is%3Aissue%20is%3Aopen%20label%3A%22good%20first%20issue%22)
