### ISSUE TITLE
Tapping notification does not work if app has never been opened

### ISSUE THREAD

**Issue by jidanni** [commons-app/apps-android-commons#4698]
Tapping this notification does not work, if the app has never been opened yet. For instance if we are sharing a picture into the app to upload from our gallery.
![Screenshot_20211106-103623.jpg](https://user-images.githubusercontent.com/1230959/140595141-24f53c54-be01-435e-88ab-e022f6919767.jpg)

**Comment by jidanni** [comment]
Latest beta. Asus Zenfone 3. Android 8.0.

**Comment by jidanni** [comment]
Even if we later open the application. the notification still won't take us there. It just takes us nowhere. It does nothing when we tap on it.

**Comment by nicolas-raoul** [comment]
I can reproduce this.

- Tapping does nothing if the upload was initiated from seeing a picture in your default gallery app and sharing to "Upload to Commons?"
- On the other side, tapping shows the Commons app's gallery if the upload was initiated from within the Commons app.

It should behave the same way for both.

**Comment by neslihanturan** [comment]
I think this issue is same with #4604 (which is already solved) am I mistaken?

**Comment by jidanni** [comment]
OK maybe.
