### ISSUE TITLE
Center map to users location or last location they provided when adding coordinates to uploads

### ISSUE THREAD

**Issue by neslihanturan** [commons-app/apps-android-commons#4699]
**Summary:** 

This is requested by a user on mailing list:
 " when adding coordinates to a photo, the map should center on my location (if available) or at the last coordinates I provided. It is not very convenient to navigate from San Francisco to Germany every time."

**Comment by hkimbrough22** [comment]
Hello @neslihanturan would a partner and I attempt to tackle this? (it's our first time trying OSS Contributions) If so, would you been able to provide the activity/file that needs to work? I'm searching for it now and can't seem to figure it out.

**Comment by GiwrgosTsifoutis** [comment]
Hello @neslihanturan, I would like to tackle this issue. Is it still open? If not, is there an issue you would like me to help? First time helping on an OSS project.

**Comment by neslihanturan** [comment]
Hi @hkimbrough22 , sorry for seeing this so late. Are you still interested? If so, at which point you are facing a problem?

**Comment by hkimbrough22** [comment]
@neslihanturan I'm not really able to work on this currently. Thanks for the response!

**Comment by devarsh-mavani-19** [comment]
hi @misaochan  I made a pull request recently https://github.com/commons-app/apps-android-commons/pull/4816 that solves one of the two issues you mentioned. i.e. showing last location. I would like to add the second feature of showing current user location. Can you please assign me this task? Thank You

**Comment by devarsh-mavani-19** [comment]
@nicolas-raoul i would like to work on this issue it is almost similar to this what I solved in this https://github.com/commons-app/apps-android-commons/pull/4816 . Can you please assign this to me?

**Comment by nicolas-raoul** [comment]
@devarsh-mavani-19 Sure, thanks! :-)
I believe this is when editing coordinates of an already uploaded picture (for instance someone else's picture found in Explore).
