### ISSUE TITLE
People not pressing the floppy icon after selecting categories

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#470]
Especially with the new futuristic floppy icon, I am afraid that many people will select categories and then press Back, without thinking they have to press the floppy icon. This is a loss of time for them and a loss of metadata for Commons. How can we improve things?

Idea 1: Add icons in real time. As soon as the user taps a checkbox, send a request to Commons to add the category. I believe it is the safest to get all categories, but it may be hard to implement. We must also remove categories that the user unchecks.

Idea 2: Auto-upload categories when the user switches to another app or presses back.

Idea 3: If the user presses Back, tell them that they must press that floppy icon first. If the user switches to another app, or even reboot their phone, show that same category activity with the same "Press that floppy!" indication when they start the app again. (Auto-save the state the user is in. That concept could be useful in the description activity as well: Chose a pic, start entering a description, phone crashes, reboot and restart the app: You can continue to enter the end of the description like nothing happened)

Right now I would vote for Idea 3, what do you think? Don't hesitate to post other ideas.

**Comment by misaochan** [comment]
The first part of Idea 3 - If the user presses Back, tell them that they must press that floppy icon first" has already been implemented some time ago #58 . :) At least, there's a warning. If they insist that they want to leave, I'm not sure we should force them to stay?

I like the suggestion to auto-save the state. Would be very useful.

Could you please clarify Idea 1? I'm not sure what it would entail.

**Comment by domdomegg** [comment]
New upload flow fixes this
