### ISSUE TITLE
Make "Please wait" dialog modal to avoid upload problems

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#4703]
When "Please wait" is displayed I can still tap "Next".
Doing so is linked to uploads that never start, in my experience.

I think an easy fix would be to make "Next" not tappable when "Please wait" is visible.

![Screenshot_20211114-192943_Commons](https://user-images.githubusercontent.com/99590/141683145-e4f8e6cb-ddd3-41fa-9c98-6377744eaf5c.jpg)

**Comment by Ayan-10** [comment]
@nicolas-raoul Can I fix it?

**Comment by nicolas-raoul** [comment]
@Ayan-10 It is yours, thanks! :-)
