### ISSUE TITLE
"Images Used" profile metric not showing correct count

### ISSUE THREAD

**Issue by mds08011** [commons-app/apps-android-commons#4706]
**Summary:** 

My profile in the Commons app shows the "Images Used" metric as 0/5 despite the fact that a few of my photos are used in Wikipedia articles (listed below).

Photos
- https://commons.wikimedia.org/wiki/File:Golden_Hill_corner.jpg
- https://commons.wikimedia.org/wiki/File:Nebelung_cat_looking_out_door.jpg
- https://commons.wikimedia.org/wiki/File:Euclid_Trolley_Station.jpg

**Steps to reproduce:** 

1. Check profile for images used in Wikipedia articles( mine are listed above).  Listed in "file usage on other wikis" section.
2. Compare number of images against Commons profile.

**System logs:**

I neglected to capture logs at the time but can reproduce if they are desired.

**Device and Android version:** 

Android version: 12
Device manufacturer: Google
Device model: Pixel 4a
User name: Mds08011
 
**Commons app version:** 

App version name: 3.1.1~1c9267ca0

**Screen-shots:** 

<img src="https://user-images.githubusercontent.com/8010709/142585937-a75ad408-095d-48b3-a79a-bf15f5b1618a.jpeg" width="50%">

**Would you like to work on the issue?**

No.

**Comment by misaochan** [comment]
Thanks for reporting this! The same issue occurs for me on current master.

**Comment by Pratham2305** [comment]
Hey @misaochan, I am able to reproduce this.
I think the problem is from the server side. As the API returns the JSON in an invalid format due to which all values are initialized as zero.

**Comment by misaochan** [comment]
@Pratham2305 thanks for investigating! Could you link to a sample query string and the response, please?

**Comment by Pratham2305** [comment]
> Could you link to a sample query string and the response, please? 

Query: 
`https://urbanecmbot.toolforge.org/commonsmisc/feedback.py?user=Azanti`

Response:
```
Content-type: application/json
()
{"status": "ok", "uniqueUsedImages": 3, "articlesUsingImages": 7, "database": "commonswiki", "deletedUploads": 15, "featuredImages": {"Quality_images": 0, "Featured_pictures_on_Wikimedia_Commons": 0}, "labs": false, "thanksReceived": 0, "user": "Azanti", "imagesEditedBySomeoneElse": 5}
```

I think the first two lines in the response are unnecessary.


>Also, are you interested in working on this?

Yes, but I am not sure about the server-side so should I just make changes in the above response to extract the valid JSON?

**Comment by misaochan** [comment]
Yes, you can try that and post the results. If it works, please feel free to submit a PR. :)
