### ISSUE TITLE
Achievements tab shows "user" has not made any contribution

### ISSUE THREAD

**Issue by ujjman** [commons-app/apps-android-commons#4709]
**Summary:** 

`Achievements` tab shows that "user" has not made any contribution but when we click `contributions` tab, there is a list of contributions made by the "user"

**Steps to reproduce:** 
1. Restart the app
2. Click on 3 lines button on the bottom-right
3. Select the "user name"
4. Go to leaderboards tab
5. Click on any user (who made some contribution like I clicked on `Christian Ferrer` (5th position))
6. A popup will open with text that "user" has not made any contribution, click Ok
7. Go to contributions tab and there, you will see all the contributions made by the user

**System logs:**

I think this causes the error
`V/OkHttp: --> GET https://tools.wmflabs.org/urbanecmbot/commonsmisc/uploadsbyuser.py?user=Christian%20Ferrer&labs=commonswiki
E/AchievementsFragment: Error:com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
V/OkHttp: --> END GET
V/OkHttp: <-- 200 OK https://urbanecmbot.toolforge.org/commonsmisc/uploadsbyuser.py?user=Christian%20Ferrer&labs=commonswiki (1023ms)
V/OkHttp: Server: nginx/1.14.2`

**Device and Android version:** 

Device is Realme 3 pro
Android version :11
 
**Commons app version:** 

3.1.1-debug-master

**Would you like to work on the issue?**
Yes

**Comment by nicolas-raoul** [comment]
Trying the steps, for most users I get a spinner then after a long time `Something went wrong, We could not fetch your achievements` instead of step 6.
With some other users, I get a seemingly correct information (screenshot below).
Do you get the error for all users?
Thanks for the report!
![adb](https://user-images.githubusercontent.com/99590/145194415-bb603c99-6431-4e5e-a30b-b556ad358fc9.png)

**Comment by Rishavgupta12345** [comment]
I think this issue isn't present anymore , I am not gettin any bug here and its working perfectly . PLEASE verify and close this issue if needed

**Comment by nicolas-raoul** [comment]
It seems indeed that no popup (mentioned by step 6) appears.
Thanks @Rishavgupta12345 for letting us know about this! :-)

**Comment by Rishavgupta12345** [comment]
> It seems indeed that no popup (mentioned by step 6) appears. Thanks @Rishavgupta12345 for letting us know about this! :-)

similarly, I made 2 other issues to be close and many more to go. Will these be considered as my contribution ?

**Comment by nicolas-raoul** [comment]
These contributions are a good complement to your pull request, yes, so please mention them in your proposal. :-)
