### ISSUE TITLE
"Please provide a caption for this file" when uploading any dark picture

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#4711]
Latest master
![Screenshot_20211124-233829_Commons](https://user-images.githubusercontent.com/99590/143258600-8e765c84-4aa2-4783-8f18-86d737c5bbdd.jpg)

**Comment by Ayan-10** [comment]
@nicolas-raoul Can't reproduce the issue. It's working as expected.

<img src="https://user-images.githubusercontent.com/71203077/143772326-1471898d-406d-4f99-a80d-64f920175a0d.jpg" width=300/>

**Comment by nicolas-raoul** [comment]
Thanks for trying!
Strangely I can't reproduce it either now, even though it reproduced every time last week. Not sure what happened.
I will close this issue for now.
