### ISSUE TITLE
Can't upload on slow Internet

### ISSUE THREAD

**Issue by jidanni** [commons-app/apps-android-commons#4712]
![Screenshot_20211126-111138.jpg](https://user-images.githubusercontent.com/1230959/143521505-789c551c-fc4c-4e4f-8eb7-fd5dd976317c.jpg)
![Screenshot_20211126-111028.jpg](https://user-images.githubusercontent.com/1230959/143521580-d5a023e1-86cd-46a2-b425-20a4cb3696ad.jpg)
![Screenshot_20211126-110843.jpg](https://user-images.githubusercontent.com/1230959/143521639-768a7288-bc3d-478b-821f-8e2b5bb191ab.jpg)

**Comment by jidanni** [comment]
Need at least four bars to succeed. Notice the cell ID has not changed at all. I just have walked to a slightly different position. Therefore the app needs a little more patience before timing out. Otherwise in lower reception areas  it will time out just too fast.
![Screenshot_20211126-112004.jpg](https://user-images.githubusercontent.com/1230959/143521842-9a4a79e3-7208-4cb0-aa98-67e6027fb6dc.jpg)

**Comment by jidanni** [comment]
Current beta.

**Comment by nicolas-raoul** [comment]
How many seconds/minutes does it take to fail?

**Comment by jidanni** [comment]
A couple minutes I recall.
Surely "It is expected that all students drive their cars to school.
That Ralph still drives his bicycle, getting here after the gates have closed,
is his own fault."

**Comment by nicolas-raoul** [comment]
Thanks!
With the same Internet connection (when upload fails), would you mind running https://play.google.com/store/apps/details?id=com.internet.speedtest.check.wifi.meter and posting screenshots of the results?

Since Commons' most valuable contributors (=people who send pictures from places for which Commons does not any picture yet) are precisely people who are in remote areas with low Internet connectivity, we should make sure that the app works even in these conditions.

I wonder if slow Internet can be easily simulated using an app or emulator setting?

**Comment by jidanni** [comment]
Sure there is https://awik.io/simulate-slow-internet-connection-chrome-developer-tools/ but I'm not sure how realistic that is.

I'm sorry I'm on a limited data plan so can't do any of those data gobbling speed tests.

Actually all you need to do is go down into some home's basement,
or some Faraday Cage like tin shack.

Surely there is some corner of some storage room where you phone only even has one bar out of five remaining.

**Comment by matkoniecz** [comment]
> I wonder if slow Internet can be easily simulated using an app or emulator setting?

I have seen it in Android Emulator (see say https://stackoverflow.com/questions/6236340/how-to-limit-speed-of-internet-connection-on-android-emulator that hopefully is not outdated)

But I expect that the main problem is not low speed but intermittency which may be harder to simulate.

**Comment by matkoniecz** [comment]
> Surely there is some corner of some storage room where your phone only even has one bar out of five remaining.

Debugging app in forest would be quite irritating and would go really slow (forest 5km away us the closest place to me that has severe connectivity issues). The same may be true for developers of this app.
