### ISSUE TITLE
Tapping notification (Tap to view your upload) is not working at all

### ISSUE THREAD

**Issue by Ayan-10** [commons-app/apps-android-commons#4716]
**Summary:** 

I was trying to reproduce #4698 and found out that tapping on the upload state notification is not working at all.

**Steps to reproduce:** 

1. Upload any image on commons
2. App will send a notification about the upload state and it's saying "Tap to view your upload"
3. Tap the notification nothing happens

What did you expect the app to do, and what did you see instead?

As it's written tap to view upload. It should take the user to the commons contribution tab.

**Device and Android version:** 

Pixel 3 API 30
 
**Commons app version:** 

latest betaDebug master

**Would you like to work on the issue?**

****_YES_****

**Comment by Prince-kushwaha** [comment]
@nicolas-raoul can i work on this issue

**Comment by nicolas-raoul** [comment]
@Prince-kushwaha Ayan wrote "YES" at "Would you like to work on the issue?" :-)

**Comment by Prince-kushwaha** [comment]
@nicolas-raoul but @Ayan-10 already assigned to 3-4 issue and these issue is open  And @Ayan-10 have many pull request are in change required i think @Ayan-10 already have too many work assigned

**Comment by Prince-kushwaha** [comment]
@nicolas-raoul i am free and i like to work on this issue

**Comment by nicolas-raoul** [comment]
I believe #4656 was meant to fix this?
