### ISSUE TITLE
After uploading by sharing an image from gallery the app again returns to Upload Activity

### ISSUE THREAD

**Issue by Ayan-10** [commons-app/apps-android-commons#4718]
**Summary:** 

After uploading by sharing an image from the gallery the app returns to Upload Activity, but after uploading it should return to the contributions tab.

**Steps to reproduce:** 

1. Go to phone's gallery and tap share
2. Select Commons
3. It will take you to upload activity for uploading the image
4. Fill in all the details upload the image
5. Now the app takes you to your phone's gallery 
6. Press the home button and open Commons
7. It will show the Upload Activiy

What did you expect the app to do, and what did you see instead?

After uploading the app should return to the contribution tab instead of upload activity

**Device and Android version:** 

Pixel 3 API 30

**Commons app version:** 

lastest betaDebug master

**Screen-shots:** 

https://user-images.githubusercontent.com/71203077/144700066-4b97c12f-ae46-437b-9188-639050866cc0.mp4

**Would you like to work on the issue?**

**_YES_**

**Comment by nicolas-raoul** [comment]
Good find!

Note: You wrote `Press the home button and open Commons` as step 6, but in the video it seems that you are using the `Recents` button and choosing the existing Commons window. Does the problem happen for both methods?

**Comment by Ayan-10** [comment]
Sorry for the late response.

Yes, for any button we press to again go to commons. Commons will start with the upload form.
