### ISSUE TITLE
Unformat text pasted into depicts search field

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#4722]
Steps:
1) Copy some formatted text from another app, for instance an article title in the Wikipedia app
2) Paste into the "Depicts" search field of the Upload Wizard.
3) Problem: Pasted text looks huge. It should be the same size as when typing text using the keyboard

Same for categories search.

The solution at #4514 might give clues.

![adb](https://user-images.githubusercontent.com/99590/144995841-5de44b9d-56d8-4c14-a5c5-7a233f3946f4.png)
.

**Comment by KhyatiSaini** [comment]
Hi, I would like to work on this issue, can you please assign me?
Thanks

**Comment by nicolas-raoul** [comment]
@KhyatiSaini Sure, thanks!
