### ISSUE TITLE
Suggest to users to turn on camera location.

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#4728]
For people whose 10 last uploads had no EXIF coordinates (latitude, longitude): show this tip activity just after they push the "Submit" button of the last step of the Upload Wizard:

>Location data helps Wiki editors find your picture, making it much more useful.
>Your recent uploads have no location.
>We suggest you **turn on location** in your camera app's settings.
>Thank you for uploading!

Showing the tip should reset the counter, meaning the tip will appear again after 10 more consecutive pictures without location.

That's important because many camera apps have location off by default.

**Comment by Ayan-10** [comment]
@nicolas-raoul Can I work on it?

**Comment by nicolas-raoul** [comment]
Yes, thanks!

**Comment by sivaraam** [comment]
> Showing the tip should reset the counter, meaning the tip will appear again after 10 more consecutive pictures without location.
>
> That's important because many camera apps have location off by default.

This makes me wonder. Wouldn't it be nice to have a way to turn off the suggestion for someone who is not in a situation to upload images with location? Some kind of a "Don't show again" option in the dialog.

I'm asking because there might be legitimate cases where a user cannot upload an image without location. For instance, there's a possibility for their device GPS to not work properly. I suppose we wouldn't want to annoy them every 10 uploads 🙂

**Comment by nicolas-raoul** [comment]
I am actually uploading a lot of my old digicam pictures (without location) so I get the popup from time to time, personally I don't find it annoying :-) I believe the high advantages of having coordinates justifies insisting a bit.

**Comment by sivaraam** [comment]
> I am actually uploading a lot of my old digicam pictures (without location) so I get the popup from time to time, personally I don't find it annoying :-) I believe the high advantages of having coordinates justify insisting a bit.

Understandable. I just feel us showing the suggestion pop-up is the right level of nudge for users. Providing no way to stop the pop-up even when its not helpful might come out badly, I wonder.
