### ISSUE TITLE
Nearby banner appearing in Media Details

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#4731]
Is it intended?
That happens when opening the app and tapping a picture very fast.
In my opinion, the Nearby banner should only appear on the activity showing the list of my contributions.
![adb](https://user-images.githubusercontent.com/99590/145935682-f8d39a5c-449b-4e77-90a1-c8ade1efdf2c.png)

**Comment by misaochan** [comment]
I agree, the banner should only be on the main (contributions list) activity.

**Comment by Prince-kushwaha** [comment]
@nicolas-raoul can i work on this issue

**Comment by nicolas-raoul** [comment]
@Prince-kushwaha Sure, thanks!

**Comment by nicolas-raoul** [comment]
@Prince-kushwaha any progress on this? 🙂

**Comment by ArmanNavodia** [comment]
@nicolas-raoul I am able to reproduce this issue. So I want to work on this can you please assign me this issue

**Comment by nicolas-raoul** [comment]
@ArmanNavodia It is yours, please let us know about your progress every few days. Thanks! 🙂

**Comment by rohit9625** [comment]
The Navigation Banner still appears on the `Media Details` screen. However, it disappears after a few seconds.
<img src="https://github.com/user-attachments/assets/20260631-ccf0-465f-bb1b-880524fe8345" width="250px" />

**Comment by nicolas-raoul** [comment]
@rohit9625 Great observation! Would you mind filing a new bug report?

**Comment by rohit9625** [comment]
Sure :)
