### ISSUE TITLE
Commons app info lists "Contacts" permission, in "Not allowed" state but it should not be shown at all

### ISSUE THREAD

**Issue by jidanni** [commons-app/apps-android-commons#4740]
I found out one of the optional permissions needed by this app, is Contacts.
Maybe if I turn it on, it will send messages to all my friends!?
So perhaps it isn't really needed anymore.
Or, have some explanation within the app...

**Comment by nicolas-raoul** [comment]
That's worrying, could you please post a screenshot?
Thanks for reporting!

It might be linked to closed issue #4682

**Comment by jidanni** [comment]
In Android Settings, pick Apps, then pick this app, and then look up all the permissions it uses.

**Comment by nicolas-raoul** [comment]
Below is what I see.
If you reinstall the app, is the contacts permission still on?
![adb](https://user-images.githubusercontent.com/99590/147427508-209ee365-ef40-4004-acca-ab04f129681a.png)

**Comment by jidanni** [comment]
The Contacts permission never was on.
I am just _aghast_ that it was sitting there in the first place.

**Comment by nicolas-raoul** [comment]
Indeed another app does not show the `Contacts` permission (not even disabled):
![adb](https://user-images.githubusercontent.com/99590/147559886-26cd46a8-54f8-448c-8567-b0a6fd70e5d9.png)
Here is the relevant part of our `app/src/main/AndroidManifest.xml`:
```
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_SYNC_SETTINGS" />
    <uses-permission android:name="android.permission.READ_SYNC_STATS" />
    <uses-permission android:name="android.permission.REORDER_TASKS" />
    <uses-permission android:name="android.permission.WRITE_SYNC_SETTINGS" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.AUTHENTICATE_ACCOUNTS" />
    <uses-permission android:name="android.permission.GET_ACCOUNTS" />
    <uses-permission android:name="android.permission.USE_CREDENTIALS" />
    <uses-permission android:name="android.permission.MANAGE_ACCOUNTS" />
    <uses-permission android:name="com.google.android.apps.photos.permission.GOOGLE_PHOTOS" />
    <uses-permission android:name="android.permission.SET_WALLPAPER"/>
    <uses-permission android:name="android.permission.FOREGROUND_SERVICE" />
```
Not sure which one makes Contacts appear.

**Comment by jidanni** [comment]
Maybe a previous developer just added all the permissions that were available, to make sure that everything worked.

**Comment by vivek-gite** [comment]
`<uses-permission android:name="android.permission.GET_ACCOUNTS" />` uses groups of permissions instead of single permission when asking the user to grand them.

**Comment by neslihanturan** [comment]
Oh, do you thing we should fix this? Even if the permission is never granted, seeing an irrelevant permission on the list may be scary for some of our users.

**Comment by vivek-gite** [comment]
@neslihanturan GET_ACCOUNTS permission, may retrieve all registered accounts and email addresses stored in Account Manager. This will help commons to autofill the password from the account manager saved on your phone.

**Comment by jidanni** [comment]
Hmmm, https://developer.android.com/reference/android/Manifest.permission#GET_ACCOUNTS says
Protection level: **dangerous**

**Comment by vivek-gite** [comment]
@jidanni In Android 8.0 they introduced Autofill Framework, which does not require any type of contact permission. So, I would like to change the permissions in commons-app and add Autofill Framework.
Please assign me this issue.

**Comment by nicolas-raoul** [comment]
@vivek-gite Would you mind summarizing what the current issue is (with screenshots), and how it should be when fixed? Thanks a lot! :-)

**Comment by vivek-gite** [comment]
**Summary:**
Commons-App found to have an optional permission of contacts for autofill service. But in Android 8.0 we don't require contact permission for autofill service.
 Also, https://developer.android.com/reference/android/Manifest.permission#GET_ACCOUNTS says.
**Protection level: dangerous**
I think it would be great if we remove **contact permission**  and add **Autofill Framework**.
**Steps to reproduce:**
- Open the App settings of commons-app and head to app permissions.
- There you will find permission for contacts.
![Screenshot_2022-01-12-14-25-59-33_ab1359306de43320f9557c797b1c4be5](https://user-images.githubusercontent.com/71180467/149097577-3fc864e8-a3b8-4eb6-9125-4a4fb8adfe58.jpg)

**Would you like to work on the issue?**
Yes.

**Comment by nicolas-raoul** [comment]
Thanks!
Please remember to test your change on various API levels we support.

**Comment by vivek-gite** [comment]
@nicolas-raoul I have made a PR. Please review it once.

**Comment by parneet-guraya** [comment]
I'd like to pick this up @nicolas-raoul
