### ISSUE TITLE
Mention location permission doesn't affect picture location

### ISSUE THREAD

**Issue by jidanni** [commons-app/apps-android-commons#4741]
In settings, when discussing location permission, perhaps also mention that it won't affect picture location. Because the app always uses the camera of the cell phone.

**Comment by nicolas-raoul** [comment]
The current settings wording says the the permission is needed for nearby.
Is there any UI element that kind of implies that it "affects picture location"?

**Comment by jidanni** [comment]
I'm saying that most people will think it is for picture location.
So even though it says it is for something else,
it should also mention something like _it is not for picture location too, because it isn't actually the app that takes pictures_.
That way people will be doubly clear.

**Comment by neslihanturan** [comment]
Hmm, I think there is no harm of more clarification in settings and maybe in the window while getting the permission?

**Comment by mnalis** [comment]
I think we nowadays use GPS also if camera didn't (i.e. https://github.com/commons-app/apps-android-commons/pull/5249) if I understand it correctly? Is so, perhaps this issue could be closed?
