### ISSUE TITLE
Add bookmarked items to suggested depictions

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#4745]
The app now allows the user to bookmark Wikidata items, thanks to Ayan-10.

Since bookmarked items are probably things that the user has an interest for or encounters frequently, it would be good to append them when suggesting depictions (typically at the Upload Wizard's "depicts" step).

**Comment by Ayan-10** [comment]
@nicolas-raoul I would like to work on it.
