### ISSUE TITLE
When uploading many pictures, the top thumbnails strip do not show the current picture

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#4747]
How about moving the strip so that the current picture is always towards the middle in the strip?
It would help remember what other pictures I took of the same thing, in order to write more precise captions.

When uploading without touching the strip:
![adb](https://user-images.githubusercontent.com/99590/147763449-f3db4d21-60e2-41ba-a688-f5b7270ce6aa.png)

I have to swipe the strip to reveal the thumbnail of the current picture within the strip:
![adb](https://user-images.githubusercontent.com/99590/147763596-112b1f83-9bd2-4e2d-8b5d-7c4db58f278c.png)

**Comment by Pratham2305** [comment]
@nicolas-raoul Can I work on this?
