### ISSUE TITLE
"Exists" should be enabled by default for map view

### ISSUE THREAD

**Issue by matkoniecz** [commons-app/apps-android-commons#4750]
**Summary:** 

Filtering locations to only existing one would be much better user experience.

In general sane default are a good idea.

Looking for objects where no trace may exist anymore should be opt-in.

**Steps to reproduce:** 

Install app.

Switch to map tab.

Grant location permission.

Be deluged by nonexisting objects that used to exist and can be filtered out as nonexisting.

**System logs:**

Irrelevant.

**Device and Android version:** 

Irrelevant, I think.
 
**Commons app version:** 

3.1.1~1c9267ca0

**Screen-shots:** 

Should not be needed.

**Would you like to work on the issue?**

Sadly I do not have time for that (and time that I have will likely go into StreetComplete/OSM Carto etc where I already dealt with setup and initial unproductive time).

**Comment by mds08011** [comment]
Filtering for "Exists" by default in the Nearby Places feature seems reasonable to me.

<img src="https://user-images.githubusercontent.com/8010709/148502127-fb6d904e-6043-4bd0-a496-a4c3f49310a2.jpg" width="50%">

As an aside, matkoniecz, thank you for all your work on StreetComplete (and OSM generally) - that is a fantastic app!

**Comment by nicolas-raoul** [comment]
I tend to agree that `Exists` should be enabled by default.
Others might argue otherwise because non-existent places appear in a different color.

**Comment by matkoniecz** [comment]
I am pretty sure that it check Wikidata for this info, but I have not checked actual code.

**Comment by misaochan** [comment]
Sorry I missed this! Good idea, I agree that "Exists" should be enabled by default.

@arinmodi the black markers are places that are flagged in Wikidata as 'not existent currently'.

**Comment by arinmodi** [comment]
Hey @matkoniecz , currently when we are opening the near by screen, Need Photo filter is selected by default and after solving this issue <b>Exists and <b>Need Photo</b> both filter selected by default, is it ok ?
