### ISSUE TITLE
Category search is case-sensitive

### ISSUE THREAD

**Issue by mds08011** [commons-app/apps-android-commons#4751]
**Summary:** 

It would be easier to find relevant categories if the search was not case-sensitive.  When uploading photos from my phone, I am often rushing and not always typing carefully and using proper capitalization.

**Steps to reproduce:** 

1. Begin uploading photo to Commons.
2. When searching categories, use a known existing category and type it exactly (example in screenshots is "Solana Beach").  You should see the correct category suggested.
3. Try to search for the same category using different capitalization - all lower-case (example: "solana beach").  The expected category will not show.

**System logs:**

I don't think they are relevant but let me know if logs are desired.

**Device and Android version:** 

Android version: 12
Device manufacturer: Google
Device model: Pixel 4a
User name: Mds08011
 
**Commons app version:** 

App version name: 3.1.1

**Screen-shots:** 

Search for "Solana Beach"
<img src="https://user-images.githubusercontent.com/8010709/148495381-4524e194-b8e5-4ce9-bef4-3c4ece154081.png" width="50%">

Search for "solana beach"
<img src="https://user-images.githubusercontent.com/8010709/148495377-747fb294-9889-4c3f-8793-a528d6eca1a8.png" width="50%">

**Would you like to work on the issue?**

No.

**Comment by mds08011** [comment]
I do not think they are related, but I had previously reported a separate category search issue: https://github.com/commons-app/apps-android-commons/issues/3384

**Comment by ouroboran** [comment]
@mds08011 @neslihanturan  Can I work on this issue?

**Comment by nicolas-raoul** [comment]
Malcom, I believe this is similar to https://github.com/commons-app/apps-android-commons/issues/3179?
If not, please point out the differences, thanks! :-)

**Comment by mds08011** [comment]
@nicolas-raoul  you are correct, they appear to be the same. I had overlooked it when creating this issue.

**Comment by nicolas-raoul** [comment]
No problem, thanks for caring! I believe you can close this issue?
Please do not hesitate to report other issues.

**Comment by mds08011** [comment]
@ouroboran please see #3719 instead. Closing this duplicate issue.
