### ISSUE TITLE
In-app camera does not record location

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#4757]
Steps to reproduce:
1. Make sure the app is able to use the GPS, for instance by opening the "Nearby" activity.
2. In the main activity, tap the "+" button then tap the camera icon
3. Take a picture, try to upload it. At the "Media details" step, the latitude/longitude button is not visible, which means that the picture is considered to have no latitude/longitude associated with it.
4. Outside the app, use the phone's camera app to take a picture, then try to upload it to Commons. At the "Media details" step, the latitude/longitude button is visible.

I tried these steps 3 times, always with the same issue.

The in-app camera should record location.

**Comment by sivaraam** [comment]
I could confirm that the in-app shots don't appear to have any location associated with them.

Just for the note to anyone who picks this up, we need to ensure the app doesn't accidentally upload in-app camera images with location when the user has turned it off by disabling "Location" option via Settings > Manage EXIF Tags.

**Comment by Pratham2305** [comment]
@nicolas-raoul, Can I look into this?

**Comment by nicolas-raoul** [comment]
@Pratham2305 Yes thanks! 🙂

**Comment by Pratham2305** [comment]
I have noticed, this only happens when the app's location permission is not available otherwise it is working as expected when both commons and camera app have location permission.

**Comment by nicolas-raoul** [comment]
Interesting!
That presumably happens when the user has no interest in Nearby.
So maybe ask for user permission when starting the in-app camera? Preferably with a message such as:

> Location data helps Wiki editors find your picture, making it much more useful.
> We suggest you let the app attach location information to the pictures taken via this button.
> Thank you for your contributions!
> Yes, great! / No, do not attach location

**Comment by sivaraam** [comment]
> 



> I have noticed, this only happens when the app's location permission is not available otherwise it is working as expected when both commons and camera app have location permission.

Interesting indeed. For some reason, this doesn't appear to be the case at least in my device. i.e., the in-app camera doesn't seem to be capturing the location even when both the app and camera app have the location permission granted and GPS is turned one. Not sure how that's the case. Anyways, let me know in case any specific information is needed to debug this. I'll be happy to share it.

**Comment by Pratham2305** [comment]
> Interesting! That presumably happens when the user has no interest in Nearby. So maybe ask for user permission when starting the in-app camera? 

Yes, that would be great!

> Interesting indeed. For some reason, this doesn't appear to be the case at least in my device. i.e., the in-app camera doesn't seem to be capturing the location even when both the app and camera app have the location permission granted and GPS is turned one. Not sure how that's the case. Anyways, let me know in case any specific information is needed to debug this. I'll be happy to share it.

@sivaraam Can you just confirm that your camera is recording location when used normally?. Thanks!

**Comment by sivaraam** [comment]
> Can you just confirm that your camera is recording location when used normally?. 

Yes, it does.

**Comment by nicolas-raoul** [comment]
@Pratham2305 Any progress on this, maybe? It would be a really great bugfix :-) But if you are busy, don't worry!

**Comment by nicolas-raoul** [comment]
My initial report was with a Samsung S10 device.
Now I switched to Pixel 6 and can not reproduce the issue anymore.

**Comment by sivaraam** [comment]
Here's a screen recording link of the issue which I am able to always reproduce on my OnePlus Nord running Android 12: https://drive.google.com/file/d/1X35a7cbXBCFz62v_hdudXLlYhIeEAPCt/view?usp=sharing
