### ISSUE TITLE
Clicking the back button in Contribution Tab after uploading an image, return again to Contribution Tab

### ISSUE THREAD

**Issue by Ayan-10** [commons-app/apps-android-commons#4760]
**Summary:** 

Clicking the back button in Contribution Fragment after uploading an image, return again to Contribution Fragment

**Steps to reproduce:** 

How can we reproduce the issue? 

1. Open commons
2. click on the + button and upload an image
3. Then you will return to Contribution Tab. Now 
4. press the back button. You will again return to Contribution Tab

What did you expect the app to do, and what did you see instead?

Clicking the back button in Contribution Tab after uploading an image, should exit the app.

**Device and Android version:** 

Pixel 3 API 30
 
**Commons app version:** 

lastest prodDebug master

**Would you like to work on the issue?**

**YES**

**Comment by nicolas-raoul** [comment]
Thanks a lot Ayan for reporting the issue and being willing to work on it!
