### ISSUE TITLE
Only name of the category is showing for the categories which are linked with depicts

### ISSUE THREAD

**Issue by Ayan-10** [commons-app/apps-android-commons#4762]
**Summary:** 

 Because of the server-side response, we can get only the name of the category for the categories which are linked with depicts, other information like thumbnail and description is not available in the server response. It will be very useful if we can get not only the name but also the other details of those categories which are linked with depicts. so that those details can be used while using the linked categories in other places.

**Steps to reproduce:** 

You can go to DepictedItem class and check the commonsCategories implementation by the depicts

Other than that 
1. Upload an image in the app
2. Select Paris in the depict selection screen then click next
3. In the category screen you can see only the name of the category Paris, but if you search Paris all other details (description and thumbnail) with the name will be shown.

**Device and Android version:** 

Pixel 3 API 30
 
**Commons app version:** 

latest master prodDebug

**Would you like to work on the issue?**

**YES**

**Comment by Ayan-10** [comment]
@nicolas-raoul I was looking into the way of getting thumbnail and description for the categories inside DepictItem. It seems we can get the filename from the entity by P18 property for most of the entity and from the filename we can get the thumbnail. But when I searched for [L-Alanine](https://www.wikidata.org/wiki/Q218642). The P18 property I not available for this entity however we can find the filename/thumbnail from the P117 property. You can check the query. 
https://commons.wikimedia.org/w/api.php?action=wbgetentities&format=json&ids=Q218642&formatversion=2
So not sure if there is any specific property for getting the filename/thumbnail. Is there any specific property through which we can get the filename/thumbnail?

**Comment by nicolas-raoul** [comment]
Thank you for the investigation! It is OK to not show any thumbnail when the item does not have a P18.

**Comment by Ayan-10** [comment]
@nicolas-raoul One DepictedItem can be associated with more than one category. In that case, using P18 image to every associated category, will not be the same as the real thumbnail of every category. I was trying to find a way for this scenario. Can you suggest to me a wikidata with which more than one commons categories associated? I was trying to find one but can't find any.

**Comment by nicolas-raoul** [comment]
@Ayan-10  Could you please post here an example of the existing HTTP request and response that retrieves the description and thumbnail when performing a category search?

From that, we can hopefully find out what HTTP request to make to get the description and thumbnail of 1 particular category.

**Comment by Ayan-10** [comment]
@nicolas-raoul The problem is with commons categories that are associated with a DepictedItem. So I think category search HTTP requests will not give any way to find the description and thumbnail of 1 particular category which is associated with a Wikidata. As we have to retrieve the categories from DepictedItem. So I think we have to investigate depict search instead of category search I am attaching both depicted search and category search below.

Depicted Search -> https://www.wikidata.org/w/api.php?action=wbsearchentities&format=json&type=item&uselang=en&search=Paris&limit=25&language=en&uselang=en&continue=0

Getting an Entity by which a DepictedItem is formed -> https://www.wikidata.org/w/api.php?format=json&action=wbgetentities&ids=Q90%7CQ830149%7CQ167646%7CQ104197%7CQ162121%7CQ3181341%7CQ1018504%7CQ984459%7CQ576584%7CQ79917%7CQ18331346%7CQ934294%7CQ960025%7CQ1158980%7CQ151298%7CQ538772%7CQ1341876%7CQ3305306%7CQ923849%7CQ1451948%7CQ1818121%7CQ3382754%7CQ2300075%7CQ2219239%7CQ28337101

Category Search -> https://commons.wikimedia.org/w/api.php?action=query&format=json&formatversion=2&generator=allcategories&prop=categoryinfo%7Cdescription%7Cpageimages&piprop=thumbnail&pithumbsize=70&gacprefix=Paris&gaclimit=25&gacoffset=0

**Comment by nicolas-raoul** [comment]
In the category activity, we have the name of each category. Why not run a new HTTP request to https://commons.wikimedia.org/w/api.php for each? (minus the categories coming from search)

**Comment by Ayan-10** [comment]
Do you mean to say we should make a GET call for every commons-categories which are associated with a DepictedItem? 

> In the category activity

Can't understand what you mean by category activity.

**Comment by nicolas-raoul** [comment]
> Do you mean to say we should make a GET call for every commons-categories which are associated with a DepictedItem?

Yes, I think it is acceptable as there will typically not be more than a handful.

By "category activity" I meant the activity of the Upload Wizard where the user has to select the right categories to apply to their picture.

**Comment by Ayan-10** [comment]
Yes, that can be done. But as we are getting the thumbnail by P18 in the depicted response itself, I was avoiding the network call. Now it seems p18 have some exception like I gave the example of L-Alanine earlier and we don't have any specific property to get the information. I think the network call will be efficient to do.

Thanks.
