### ISSUE TITLE
Nearby screen flashes in a particular case when denying permission

### ISSUE THREAD

**Issue by sivaraam** [commons-app/apps-android-commons#4765]
**Summary:** 

When the location permission is denied for the app in a specific way the app screen keeps flashing with the "Requesting Location Permission" dialog being visible.

**Steps to reproduce:** 
1. Ensure the device's location is turned off
1. Use a fresh installation of the app
2. Log-in to the app
3. Tap on "Nearby". 
4. You'll see the location permission request
5. Tap **outside** the permission dialog.
6. You're shown the location permission request again (twice). Tap on "Don't allow" in both cases.

**System logs:**
Let me know if this is necessary.

**Device and Android version:** 
OnePlus Nord running Android 11
 
**Commons app version:** 
3.1.1~1c9267ca0

**Screen-shots:** 
Here's a screen recording:

https://user-images.githubusercontent.com/12448084/150677090-177d9b2d-1196-4223-8b79-5dc681eda369.mp4

**Would you like to work on the issue?**
Prefer not.

**Comment by Rishavgupta12345** [comment]
It's a problem that changes from device to device and is created by the system launcher of the device itself. My MIUI12 version of android works perfectly and doesn't cause any issue here

**Comment by sivaraam** [comment]
> It's a problem that changes from device to device and is created by the system launcher of the device itself. My MIUI12 version of android works perfectly and doesn't cause any issue here

I'm confused. This bug speaks about screen flashing that happens with a sequence of actions that are all within the app. How does the system launcher come into picture here? 🤔

**Comment by sivaraam** [comment]
I don't observe this anymore (possibly after the fix for #5182). Do feel free to reopen if you observe it.
