### ISSUE TITLE
Something went wrong, We could not fetch your achievements

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#4767]
1. Restart the app
2. Click on 3 lines button on the bottom-right
3. Select the "user name"
4. Go to leaderboards tab
5. Click on any user.
6. Sometimes it works, but most often the spinner spins for a few minutes, then a network error appears: `Something went wrong, We could not fetch your achievements`

Related: #2691

**Comment by Rishavgupta12345** [comment]
I am not able te replicate this issue , I tried 20 times and its working perfectly

**Comment by nicolas-raoul** [comment]
I am able to reproduce right now (at the first try) on a very fast WiFi network (when posting the issue above I was on fast 4G).

**Comment by devarsh-mavani-19** [comment]
@nicolas-raoul I also face such problem. But isn't this issue of backend?

**Comment by nicolas-raoul** [comment]
Yes, possibly a backend problem. The backend's source code is at https://github.com/commons-app/commonsmisc

**Comment by devarsh-mavani-19** [comment]
@nicolas-raoul on further debugging issues i found that three are probably 2 databases in the backend 1 for beta users/developers and 1 for normal users.  when we log in from development version our data is probably stored in a separate database. to prove this I tried logging in from the normal version (playstore version) with beta version credentials and I can't log in. In fact, in the forgot password screen I get an error that the account does not exist.  the same issue Is in the web version. I Can't say for sure without taking a look at the database structure.  And I checked the backend link you sent to me but it seems to have only a few scripts. I couldn't find the SQL schema file in that repo. It would be helpful if you can redirect me to database structure file. I will keep updated if i find anything else. Thanks

**Comment by nicolas-raoul** [comment]
The database for achievements is probably only for prod.
Here is some more documentation:
- https://github.com/commons-app/commons-app-documentation/blob/master/DB_Schema/leaderboard.md
- https://github.com/commons-app/commons-app-documentation/tree/master/API

**Comment by nicolas-raoul** [comment]
Working well recently 🙂
