### ISSUE TITLE
An issue form instead of a basic template

### ISSUE THREAD

**Issue by sivaraam** [commons-app/apps-android-commons#4768]
I happened to come across the [Mozilla Fenix issue creation page](https://github.com/mozilla-mobile/fenix/issues/new/choose). It has several types of issues that a user could choose from. Further, the [bug reporting page](https://github.com/mozilla-mobile/fenix/issues/new?assignees=&labels=%F0%9F%90%9E+bug%2Cneeds%3Atriage&template=---bug-report.yml&title=%5BBug%5D%3A+) is an actual form rather than a simple template. It looks really nice and appears more clean. Would it be nice to have multiple something similar for our repository too?

If it sounds like a good idea, I would say we could have templates for:
- Bug reports
- Feature requests
- Other issues (basic/no template for this one)
- Anything else?

Let me know your thoughts.

**Comment by madhurgupta10** [comment]
@sivaraam good thing to do IMO.

We could also have one with "Feedback" and "Need Help"?

**Comment by misaochan** [comment]
I agree, this would be fantastic. :) I wonder how they convert templates into actual forms? Is there a plugin needed?

- Bug reports: I guess the current template is mostly suited to "bug reports", so we can just convert that into a form (if possible).
- Feature requests: Mozilla's version looks good
- Feedback: Commons app version, Wikimedia username (optional), device
- Need help: Not sure about what we should have in this one

**Comment by madhurgupta10** [comment]
Here is a helpful link - https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

Maybe "Question" instead of "Nead Help", if someone needs any help with the project or have any general question to ask.
