### ISSUE TITLE
Peer review: Do not ask to review categories if there are none

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#4776]
If a picture has no category, then we already know the answer: The picture is not well-categorized.
In such cases, we could skip that step.
Even if some bots routinely flag all non-categorized pictures, our mobile peer-review still makes sense for other aspects of the pictures (encyclopedic or not, relevant categories or not, etc).

**Comment by devarsh-mavani-19** [comment]
when i don't enter any category, there are still some default categories entered by backend server. For example: **Uploaded with mobile** and many such default categories are always there, Is there a way we can identify the default categories?

**Comment by nicolas-raoul** [comment]
Excellent question!
These are called "Hidden categories", for instance for https://commons.wikimedia.org/wiki/File:Arenal_d'en_Castell.jpg :
<img width="667" alt="Screen Shot 2022-02-27 at 22 20 27" src="https://user-images.githubusercontent.com/99590/155884124-acfc3ab5-2ca2-4c30-8d7b-77b198752a28.png">

A hidden category can be recognized by the `__HIDDENCAT__` line when editing it, for instance you can see it at https://commons.wikimedia.org/w/index.php?title=Category:Uploaded_with_Mobile/Android&action=edit

So, the app would have to make a web request (get wikitext, rather than edit) for each category to check whether it is hidden or not.
I suggest creating a cache to store the names of hidden categories.

**Comment by devarsh-mavani-19** [comment]
@nicolas-raoul got it 👍🏿 . I would like to work on this one

**Comment by nicolas-raoul** [comment]
@VojtechDostal @sivaraam By any chance do you know any easier way (I mean easier than [my comment above](https://github.com/commons-app/apps-android-commons/issues/4776#issuecomment-1053555523)) to check whether a given picture has any non-hidden category?

**Comment by devarsh-mavani-19** [comment]
@nicolas-raoul i was going through documentation of API and found an easy way. I can simply pass a query parameter prop=categories and another parameter clprop=hidden. This will give me all the properties associated with that file and also give me whether it is hidden or not. see this example

https://commons.wikimedia.org/w/api.php?action=query&format=json&formatversion=2&clprop=hidden&prop=categories&titles=File:Arenal_d%27en_Castell.jpg

However after testing on beta version, I found that,  it is returning all the categories as **not** hidden. 

so I think currently in Beta version there are no hidden categories on backend server. But this should work with production

**Comment by nicolas-raoul** [comment]
@devarsh-mavani-19 Sounds promising! Feel free to test on production, if you are unsure just answer "Yes" at the questions, there will be no harm to production.
