### ISSUE TITLE
When adding coordinates, use smarter default position than San Francisco

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#4777]
Steps to reproduce:
1. Find any picture that has no coordinates
2. Press the pencil icon to add new coordinates
3. You now have a map where you can choose the coordinates. Problem: This map is centered on San Francisco.

The location should be the last used location. Factorize with `UploadMediaDetailFragment.LAST_LOCATION`

**Comment by devarsh-mavani-19** [comment]
I want to work on this issue. can you assign this to me? @nicolas-raoul
