### ISSUE TITLE
Send in-app feedback to wiki page instead of email

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#4779]
Currently, the `Feedback` button (in the app's main menu) opens an email editor.
For privacy reasons, let's switch to a form that posts the same information to the top of https://commons.wikimedia.org/wiki/Commons:Mobile_app/Feedback

For logged-in users:

1. Show a form:
 - 4-lines high text area where the user must write a custom message.
 - Checkboxes for each line of debug information (for instance `API level: 30`, `Android version: 11`, etc). The user can unselect the debug information that will be sent. For instance, if the user does not want others to know that they are using a SM-G986B phone (for privacy reasons), they can uncheck the checkbox at the `Device model: SM-G986B` line.
2. Post the content as a new section at the top of https://commons.wikimedia.org/wiki/Commons:Mobile_app/Feedback . Adding a new section to a wiki article is already implemented by the app in other places, such as peer review, so it should be rather easy to implement.

The probability of two users sending feedback at the exact same time is very low, but please just try to minimize the time between reading the content of the page and posting the updated content.

If the user is not logged in, just open the user's browser at https://commons.wikimedia.org/wiki/Commons:Mobile_app/Feedback (rationale: _once there the user will be able to add a new section, and will receive the WMF's official disclaimers regarding their confidentiality_)

**Comment by devarsh-mavani-19** [comment]
I would like to work on this issue :)

**Comment by devarsh-mavani-19** [comment]
@nicolas-raoul I would like to work on this issue

**Comment by devarsh-mavani-19** [comment]
hey, @nicolas-raoul in the master branch I am facing an SSLHandshake exception. So on which branch should I add this feature?

**Comment by nicolas-raoul** [comment]
Beta is probably OK too, you can use https://commons.wikimedia.beta.wmflabs.org/wiki/Commons:Mobile_app/Feedback

I think I saw that Madhur was having the same issue? If the issue does not disappear within a day, could you please file a Phabricator ticket? Thanks!

**Comment by devarsh-mavani-19** [comment]
@nicolas-raoul issues is resolved. I can actually login now. Thanks

**Comment by devarsh-mavani-19** [comment]
@nicolas-raoul I am trying to find what are the parameters of form data that I have to pass in POST Request. I tried the parameters from chrome network tab and tried those in postman but it is always showing this message 
"Some parts of the edit form did not reach the server; double-check that your edits are intact and try again."

Here is what I found from network tab
URL: https://commons.wikimedia.beta.wmflabs.org/w//index.php?title=Commons:Mobile_app/Feedback&action=submit
parameters I tried
1. wpTextbox1
2. wpEditToken
3. wpSummary
4. wpSave
5. wpAutoSummary
6. format

Note: I passed csrf token in wpEditToken field.

**Comment by nicolas-raoul** [comment]
Tip: For the signature/timestamp you can write `~~~~` and I believe the server will replace it with the signature and timestamp.

**Comment by nicolas-raoul** [comment]
Ah actually I notice that a signature is automatically attached to your tests, it is the `[2409:4041:D13:CBF3:E403:257A:60AC:A0EC](https://commons.wikimedia.org/wiki/Special:Contributions/2409:4041:D13:CBF3:E403:257A:60AC:A0EC) 05:21, 20 February 2022 (UTC)` part, so you can remove the `[Anonymos here](https://commons.wikimedia.org/wiki/User:Syced) ([talk](https://commons.wikimedia.org/wiki/User_talk:Syced)) 09:58, 4 January 2022 (UTC)` part.

**Comment by devarsh-mavani-19** [comment]
> Ah actually I notice that a signature is automatically attached to your tests, it is the `[2409:4041:D13:CBF3:E403:257A:60AC:A0EC](https://commons.wikimedia.org/wiki/Special:Contributions/2409:4041:D13:CBF3:E403:257A:60AC:A0EC) 05:21, 20 February 2022 (UTC)` part, so you can remove the `[Anonymos here](https://commons.wikimedia.org/wiki/User:Syced) ([talk](https://commons.wikimedia.org/wiki/User_talk:Syced)) 09:58, 4 January 2022 (UTC)` part.

yes the signature was attached when I passed in the default CSRF token (+\) otherwise it won't attach the signature. so I think I need to write ~~~~ to attach signature. I will make sure that is the behaviour though.

**Comment by devarsh-mavani-19** [comment]
hey @nicolas-raoul I am facing a problem. I am requesting a token using csrfTokenClient.getTokenBlocking() but when I try to make a request to upload post using that csrf token it is giving badtoken error. I even tried to generate a token from browser and then tried sending a POST request from postman but still getting same error. I tried this exact thing yesterday and it worked but today it is not accepting csrftoken. Are there any changes done in API for validating token?

**Comment by nicolas-raoul** [comment]
Can you reuse the same code as the peer review feature?
The peer review feature does the exact same thing (add a paragraph to a given wiki page), so hopefully not much new code is needed.

**Comment by devarsh-mavani-19** [comment]
@nicolas-raoul thanks its working. I used the same code of peer review. I will do a PR after adding unit tests. or will create a draft PR if you want to test the functionality and UI. Thanks :)
