### ISSUE TITLE
Cancel previous ongoing runs in the PR/branch when you push new commits

### ISSUE THREAD

**Issue by madhurgupta10** [commons-app/apps-android-commons#4781]
**Summary:** 
It makes sense to only build the latest commit and cancel any previous ongoing builds when you push new commits to a PR or branch. This will ensure that we don't run out of free build mins.

Link for help https://stackoverflow.com/questions/66335225/how-to-cancel-previous-runs-in-the-pr-when-you-push-new-commitsupdate-the-curre

**Would you like to work on the issue?**
No

**Comment by RishiKumarRay** [comment]
@madhurgupta10 can you please review if my approach is right?
