### ISSUE TITLE
Move all model classes into a single package

### ISSUE THREAD

**Issue by madhurgupta10** [commons-app/apps-android-commons#4782]
**Summary:** 
Model classes should be excluded from testing so we need to add them to the `excludes` in https://github.com/commons-app/apps-android-commons/blob/master/jacoco.gradle

Currently, these classes are distributed in various packages, adding them into a single package will make it much easier to achieve this task.

**Would you like to work on the issue?**
No

**Comment by Rishavgupta12345** [comment]
@madhurgupta10  can you expain about this issue a bit more , I am new to contribution

**Comment by madhurgupta10** [comment]
Hi @Rishavgupta12345 you need to look for all the model classes, sealed, enums, etc. both in java and kotlin in all packages and move them into a single package called **models**. If you are unfamiliar with model classes checkout this link - https://stackoverflow.com/questions/36031209/model-class-and-pojo-class#:~:text=A%20model%20class%20is%20typically,model%20java%20classes%20for%20JSON%20.

A good way to start this issue is by listing down all the potential classes here.

**Comment by RajeshPenugonda** [comment]
Hey! @madhurgupta10  I am interested to work on this. I can do this

**Comment by madhurgupta10** [comment]
@RajeshPenugonda Sure thanks :)

**Comment by madhurgupta10** [comment]
I have created a PR for the jacoco file (https://github.com/commons-app/apps-android-commons/pull/4821)

@RajeshPenugonda  You need to make a model subfolder for every package and move relevant files to it, see `customselector` (https://github.com/commons-app/apps-android-commons/tree/master/app/src/main/java/fr/free/nrw/commons/customselector) for example

Creating multiple PRs ideally one per package is appreciated.

**Comment by madhurgupta10** [comment]
@RajeshPenugonda Let us know how is the progress on this issue going?

**Comment by ben-mathu** [comment]
I would like to work on this.

**Comment by madhurgupta10** [comment]
Thanks, @ben-mathu Please do make multiple PRs for this issue. Ideally one per package.

**Comment by ben-mathu** [comment]
@madhurgupta10 Please review these PRs then give feedback.
