### ISSUE TITLE
"This feature is only available on the prod flavor."

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#4784]
Several features of the app are broken when you try to use them with the [beta flavor](https://github.com/commons-app/commons-app-documentation/blob/master/android/Quick-start-guide-for-Developers.md#building-the-source-code).
For instance, the [leaderboard throws an exception when running the beta flavor](https://github.com/commons-app/apps-android-commons/issues/4774#issuecomment-1027151359). It wastes everyone's time.

When opening the activity when such features are present, it would be helpful to show such a toast:

> This feature is only available on the prod flavor.

Activities for which the toast should be shown:
- Leaderboard
- Maybe "Review"?
- Maybe "Explore" > search for something > "Items"?
- If you find others, please comment :-)

_While our long-term goal should be to make all features work with the beta flavor too, for now we should at least clearly identify what features do not work._

**Comment by Rishavgupta12345** [comment]
I didn't understand the issue please explain a bit more

**Comment by nicolas-raoul** [comment]
@Rishavgupta12345 I added more details. To understand it, please build both flavors and test the leaderboard with both.

**Comment by KosOrKosm** [comment]
Hello @nicolas-raoul, I would like to handle this issue. Could I be assigned?

**Comment by nicolas-raoul** [comment]
@KosOrKosm Yes thanks! :-)
