### ISSUE TITLE
Moving to JDK 11?

### ISSUE THREAD

**Issue by madhurgupta10** [commons-app/apps-android-commons#4787]
**Summary:** 
I see this warning in the console, so maybe we should consider moving to JDK 11+

```
warning: Current JDK version 1.8.0_312-b07 has a bug (https://bugs.openjdk.java.net/browse/JDK-8007720) that prevents Room from being incremental. Consider using JDK 11+ or the embedded JDK shipped with Android Studio 3.5+.
```

**Would you like to work on the issue?**
No

**Comment by misaochan** [comment]
Good idea. I would request that the person submitting the PR also do a brief test of the app's functionality and report on that in the PR.

**Comment by Rishavgupta12345** [comment]
Changing the entire JDK is a big deal and should require a lot of file changes , is this really a good first issue

**Comment by misaochan** [comment]
@Rishavgupta12345 Hmm, could you provide an example of the file changes that would be required, please?

**Comment by Rishavgupta12345** [comment]
> @Rishavgupta12345 Hmm, could you provide an example of the file changes that would be required, please?

I don't know exactly but the plugins which work on old JDK and are deprecated in the new ones will give errors and have to be replaced by the latest plugins and functions

**Comment by madhurgupta10** [comment]
> don't know exactly but the plugins which work on old JDK and are deprecated in the new ones will give errors and have to b

Can you share the plugins that need to be updated?

**Comment by lucile98-ode** [comment]
Hello everyone,
with @xenom34 we would like to try to participate in this issue.
Is it possible to be assigned on it?
Thanks (:

**Comment by nicolas-raoul** [comment]
@JamunaSivanupandian It is yours, thanks!

Your first task is to check whether the app actually already uses JDK11 (or later) or not. 😊

**Comment by nicolas-raoul** [comment]
@JamunaSivanupandian  Any progress to share? :-)

**Comment by JamunaSivanupandian** [comment]
sorry..there is no progress..i am a newbie and i saw it is a good first issue so i would like to contribute but unfortunately i cant find exactly where to change and what is the exact issue..

**Comment by nicolas-raoul** [comment]
@JamunaSivanupandian 

You could try to increase both `JavaVersion.VERSION` lines in app/build.gradle and see whether the project still builds or not :-)

But as Paul says above I think the JDK used depends on what is installed on each person's machine, and there does not seem to be an problem with higher JDKs, so maybe this issue can just be closed?

**Comment by elemcraft** [comment]
Hello, can I take this issue?

**Comment by elemcraft** [comment]
Hello, @nicolas-raoul . Sorry I am a newbie. Can you provide a direction I could work on this issue? 

I saw there is a failing check symbol for the latest commit. And I could not build the project. Does the failing check symbol related to the build issue?
![image](https://github.com/commons-app/apps-android-commons/assets/48006644/4fb17827-d168-4271-ae08-412e3bf35497)

**Comment by elemcraft** [comment]
When I build the project, there's an error saying that `values-yue-hant` file in the `app\src\main\res` folder is missing. 

Is this issue related to someone removing `values-yue-hant`?
https://github.com/commons-app/apps-android-commons/pull/5573

**Comment by nicolas-raoul** [comment]
Yes sorry you can remove that folder. Thanks!

**Comment by elemcraft** [comment]
Hello, @nicolas-raoul 
I find that the project can be built with jdk17. Should I update to JDK 17 or stick with JDK 11 as planned?

**Comment by elemcraft** [comment]
Hello,
I find that the project can be built with JDK 17 but not JDK 11 as current AGP requires a Gradle JVM that supports version 17 . Can I update to JDK 17 instead of JDK 11?
