### ISSUE TITLE
"No location found" popup: Remove the need to tap "Next" again

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#4793]
After tapping "Next", the "No location found" popup appears.

Problem: After choosing a location, I am still at the caption/description step, so I have to tap "Next" again.

Goal: After choosing a location, I should be sent directly to the next step (depictions, or next media in the case of a multi-upload).

**Comment by arinmodi** [comment]
Can i work on this, issue ?
