### ISSUE TITLE
"No location found" popup location editor: Also remember zoom level

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#4794]
In addition to the longitude,latitude, it would be great if the zoom level could be remembered.

**Comment by Ashish-100-tiwari** [comment]
@nicolas-raoul , I want to contribute but when I downloaded the zip file and imported in android studio then its showing me an error ( photo attached ) , can you please help me to resolve this problem .
![Screenshot 2022-02-07 173337](https://user-images.githubusercontent.com/80841006/153193167-abaf11ee-cc5e-4e12-b46a-bae77a56cdd8.png)

**Comment by nicolas-raoul** [comment]
@Ashish-100-tiwari Thanks for your interest! Did you try performing an Internet search for the error message?

**Comment by arinmodi** [comment]
Can i work on this ?
 
I already setup the project on my machine and also run it on my phone.

I am ready to work on this, only thing i need is some detailed explanation of the issue

**Comment by nicolas-raoul** [comment]
@[Ashish-100-tiwari](https://github.com/Ashish-100-tiwari) Are you still working on this? :-)

**Comment by arinmodi** [comment]
Hey @nicolas-raoul, please suggest me any other issue for me to work, i really want to start contributing in this

**Comment by Ashish-100-tiwari** [comment]
> @Ashish-100-tiwari Thanks for your interest! Did you try performing an Internet search for the error message?
 yes , I tried internet search but still the same thing is coming "Gradle project sync is failed " 
![image](https://user-images.githubusercontent.com/80841006/153699722-8254ac31-d84d-40f9-a2e7-e8f8a9861a2c.png)

**Comment by Ashish-100-tiwari** [comment]
@Ayan-10 , thanks bro but I tried this also , you can go ahead and solve this issue

**Comment by arinmodi** [comment]
Can i work on this issue ?

**Comment by nicolas-raoul** [comment]
@Ayan-10 I see you are mentioned, are you interested in taking this issue? If not, please let @arinmodi know they can have it :-)

**Comment by arinmodi** [comment]
Hey @nicolas-raoul, to solve this issue i need to add new field to uploadItem. So how should i pass the values, using constructor or using only get method ?

**Comment by nicolas-raoul** [comment]
Please follow the same implementation strategy as `fr.free.nrw.commons.upload.mediaDetails.UploadMediaDetailFragment.LAST_LOCATION`.
Thanks!

**Comment by arinmodi** [comment]
Hey @nicolas-raoul, made a PR for this issue
