### ISSUE TITLE
Make caption field monoline (Upload Wizard)

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#4795]
A caption must not be multiline.

**Comment by misaochan** [comment]
Hi @nicolas-raoul , do you mean we should restrict the text field?

**Comment by nicolas-raoul** [comment]
Yes, exactly, in the UI :-)

Multiline descriptions might be acceptable, but captions should be a single short line.

**Comment by devarsh-mavani-19** [comment]
hi @nicolas-raoul can I fix this small issue I am new to this community? can you assign it to me? or can I directly create a PR?

**Comment by nicolas-raoul** [comment]
@devarsh-mavani-19 It is yours, thanks! :-)
