### ISSUE TITLE
Deletion requests: Post in English rather than in the flagger's locale

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#4800]
An app user (using the Romanian locale on their phone) flagged a picture for deletion.
The deletion requests was posted in Romanian:

https://commons.wikimedia.org/w/index.php?title=File%3AHexagone-Balard_%40_Paris_%2823766157612%29.jpg&type=revision&diff=627919510&oldid=627919420

The picture's uploader probably does not understand Romanian.
Even though we can not expect everyone to understand English, the current norm on Commons is to post these notices in English.

We should thus un-internationalize this message.

The month should also not be localized (`februarie` in the example).

**Comment by strainu** [comment]
I'm bikeshedding a little here, but I wonder what would happen if we published the text in **all** the languages instead? It would probably mean a lot of text to be sent by the phone, i.e. data usage issues. Could we perhaps create an i18n template on Commons and use that in order to prevent the app from sending the text? How complicated would it be to update the translations then?

**Comment by nicolas-raoul** [comment]
The template idea is great, as it would allow us to just post a short string (with parameters) and the exact wording would be easy to enhance by any wiki contributor in real-time (without having to wait for us to release a new version of the app, which does not happen often).

@strainu Would you mind creating a prototype of the wiki template and its parameter? Parameters would probably include the picture identifier and the selected reason(s?). Can templates find out the reader's locale? If not, the template's text could be in English and include short links to translations.

**Comment by devarsh-mavani-19** [comment]
Hey @nicolas-raoul I was checking the Code and I think the Language of reason uploaded by users depends on users keyboard. however we can control the language of name of month. we can make it english

**Comment by nicolas-raoul** [comment]
@devarsh-mavani-19 Thanks! We can do English for now, and then (in another issue) a template once @strainu or someone else creates a template.

**Comment by devarsh-mavani-19** [comment]
@nicolas-raoul so for now should change the language of the month of deletion request to english?

**Comment by nicolas-raoul** [comment]
Yes, and also the reason, which is `Pentru că este` in the example https://commons.wikimedia.org/w/index.php?title=File%3AHexagone-Balard_%40_Paris_%2823766157612%29.jpg&type=revision&diff=627919510&oldid=627919420

**Comment by devarsh-mavani-19** [comment]
@nicolas-raoul is there anyway i can read the deletion request just like you sent me this link https://commons.wikimedia.org/w/index.php?title=File%3AHexagone-Balard_%40_Paris_%2823766157612%29.jpg&type=revision&diff=627919510&oldid=627919420. can I read my own deletion request for testing my code?

**Comment by nicolas-raoul** [comment]
@devarsh-mavani-19 For tests, feel free to send actual deletion requests for this file: https://commons.wikimedia.org/wiki/File:Bicycles_shop_in_Ebisu.jpg You can find it in Explore by searching for "Bicycles shop in Ebisu".
