### ISSUE TITLE
[Bug]: "No location found" popup sometimes appears twice for the same picture

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#4806]
### Summary

The "No location found" popup sometimes appears again.

### Steps to reproduce

1. Take a screenshot of anything
2. Try to upload it
3. Enter a random text as caption
4. Tap "Next"
5. The "No location found" popup appears. Tap "Skip".
6. The image quality popup appears, tap "Upload"

### Expected behaviour

The depictions activity should appear.

### Actual behaviour

Instead, the "No location found" popup appears again.

### Android version

Android 9

### Commons app version

3.1.1 master prodDebug

### Would you like to work on the issue?

Prefer not

**Comment by nicolas-raoul** [comment]
Yes thanks!

**Comment by arinmodi** [comment]
Hey @nicolas-raoul, I have one query,

I found that same thing is happening in "Duplicate Image Found" dialog, should I also change that or do PR with current issue solution ?
