### ISSUE TITLE
Open the last opened screen of bottom navbar when launching the app

### ISSUE THREAD

**Issue by sivaraam** [commons-app/apps-android-commons#4808]
### What is the user problem or growth opportunity you want to see solved?

Whenever a users opens the app it starts in the "Contributions" screen. This might be useful for some users as they might prefer to be taken to the "Nearby" screen instead which they use often. OTOH, changing starting with "Nearby" screen by default might not help users who wish to see their Contributions first.

One possible solution that might satisfy both users is to open the last opened screen of the bottom navbar when launching the app. In this way, a user who leaves the app from the "Nearby" screen would see the "Nearby" screen when they open the app. Those who leave the app from the "Explore" screen would see it when they open the app. This would help the users to get to the screen they most use when that's one they were in when they leave the app.

**Note**: It is not possible now to leave the app from the "Nearby" / "Explore" screen by hitting back. Hitting back from those screens would take them to the "Contributions" screen from which they are able to exit the app. This needs to be changed in case we plan on implementing this.

### How do you know that this problem exists today? Why is this important?

Based on feedback from the users mailing list [[ref](https://groups.google.com/g/commons-app-android/c/nY9W4aBqAUw/m/5qWQcPxlEwAJ)]. It is important because it helps users get to their most used screen of the app quickly.

### Who will benefit from it?

Users who want screens other than the "Contributions" screen to be opened by default when the app opens.

**Comment by Ayan-10** [comment]
I would like to work on it.

**Comment by nicolas-raoul** [comment]
Great idea! If anyone is against this, please comment as soon as possible. 🙂

@Ayan-10 There is a small risk that the community or core developers are against the idea, but feel free to start working on it if you want. 🙂

**Comment by misaochan** [comment]
I would be in support of this idea for the Contributions and Nearby screen, but not for Explore or the other screens. As far as I'm aware, Explore is very rarely the primary feature that people use our app for (even though it's a cool feature), so it's likely that someone might check Explore out for a bit, then leave the app, and get very confused about why it's not showing them their own photos as per normal.

**Comment by nicolas-raoul** [comment]
The problem with adding settings is that the more important settings become more difficult to find.
Last opened screen (if it is Contributions or Nearby, otherwise Contributions) sounds good to me.

**Comment by sivaraam** [comment]
I somehow lean towards the more simpler "remember last opened screen" which opens the last screen that you left the app from. Not just when that was "Contributions" / "Nearby". I say that because I think the problem of opening launching "Explore" / "Favorites" when they were the last opened screens likely isn't a big cause of concern explictly because they _are not used a lot_. So, there are very few circumstances when the user would see them when opening the app. OTOH, in case there's some one who for some reason uses Explore feature of the app often, they would find it helpful that the app opens the "Explore" screen when they leave the app from there.

I suggest this to keep _both_ the implementation and user experience more straight-forward.

In case others still feel strongly about the "Last opened screen (if it is Contributions or Nearby, otherwise Contributions)" idea, that would be fine as that's likely a better status quo than the one we have now.

**Comment by nicolas-raoul** [comment]
I agree with @sivaraam actually. It is conceivable that some people use the app only to find freely reusable images.

**Comment by misaochan** [comment]
I guess my main concern is that this might generate a bunch of "why can I not get the app to show the usual screen when I launch the app??" complaints, as this logic is hidden to the user. The "hidden" part is important, as the user probably doesn't remember the last screen they used and it looks like unintentional behaviour or a bug, and also there is no clear instruction on how to change the launch screen. For a very commonly-used feature like Nearby it felt like the benefit was worth the risk, but for less-commonly used features it felt less worth it.

I was thinking that maybe there could be a toast that says "Displaying last exited screen" to let them know it's intentional, but that could be bothersome for users who already know that that's what they want (e.g. the people in the mailing list who requested it for Nearby).

**Comment by sivaraam** [comment]
> The "hidden" part is important, as the user probably doesn't remember the last screen they used and it looks like unintentional behaviour or a bug, and also there is no clear instruction on how to change the launch screen.

That's a valid point. May be a one-time user education of some sort would help here?

>  Especially if someone happened to land on something like... Settings or About. :)

Interesting. It's likely not clear from my description but I only intended for the app to launch the screens that are visible from the bottom navbar. I feel it would be better to stop with that. If we extend this to screens like "Setting", "About" etc. it could really become confusing and not so helpful 🙂

**Comment by arinmodi** [comment]
Can I work on this, if anyone not working on this ?

**Comment by arinmodi** [comment]
@nicolas-raoul, can I work on this ?

**Comment by nicolas-raoul** [comment]
@arinmodi This issue is still assigned to Ayan-10.

**Comment by arinmodi** [comment]
@Ayan-10, are you working on this ?

**Comment by Ayan-10** [comment]
Currently no, as my exams are going on. @nicolas-raoul You can assign him for this.

Thanks
