### ISSUE TITLE
Need help in writing unit test

### ISSUE THREAD

**Issue by arinmodi** [commons-app/apps-android-commons#4824]
### Description

I have to write the unit test for the small functionality of remembering zoom level in map, Can anyone help me to write test ?

For more info you can check the requested changes on PR #4817 

Thanks,

**Comment by Ayan-10** [comment]
As I can see your changes in the UploadMediaDetailFragment.java, the tests for those lines can be written by observing other already written tests of that class. I would suggest you to observe other test classes and try to understand the reasoning by doing some experiments while writing tests. It will help you to learn and write unit testing by yourself and also get familiar with the codebase.

On that note, The test class of LocationPickerActivity is not written yet. So if you want to add tests for your changes on LocationPickerActivity. You have to create a test class for it and then add tests for those lines.

@nicolas-raoul I am working on adding tests for LocationPickerActivity. There is some exception occurring from Mapbox internally. I am discussing the possible solution with madhurgupta10. So if there is no problem, I can handle these new lines of the LocationPickerActivity.

Thanks :)

**Comment by arinmodi** [comment]
@madhurgupta10, same error is happened with me

**Comment by arinmodi** [comment]
Thanks @Ayan-10
