### ISSUE TITLE
[Bug]: Multi-upload continues even after pausing all

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#4835]
### Summary

Pausing does not work correctly in multi-upload.

### Steps to reproduce

1. Select 4 pictures in your gallery app
2. Share → Send to Commons app
3. Pause all 4 pictures

### Expected behaviour

Uploads do not progress anymore.

### Actual behaviour

One of the pictures continues uploading.

Pausing it makes a different one start uploading.

Even exiting the app (apps button then swipe up) does not make it stop.

Here you can even see the app continuing to upload even though the play/pause button suggests it is paused:
![Screenshot_20220219-114814_Commons](https://user-images.githubusercontent.com/99590/154783480-ac142467-9b86-4c25-a070-a4d3561fa75f.jpg)

### Device name

Samsung S10

### Android version

Android 9

### Commons app version

master

### Would you like to work on the issue?

Prefer not

**Comment by arinmodi** [comment]
can I work on this ??

**Comment by arinmodi** [comment]
Hey @nicolas-raoul, I found that this problems only happens  when user pause the upload before the actual upload start by the upload worker, let me explain me with example that,

1. Suppose you upload the 4 photos, those 4 photos will be queued by the upload worker,
2. you pause the first upload,  now there is a delay between pausing First upload and starting the next upload.
3.  in this delay you paused the all remaining 3 uploads but upload-Worker did not know about it, upload-Worker still has queued uploads so it will start the upload of queued uploads, but they are paused from point of view of the user and that causing the issue

I hope that make sense 🤔 

So, solution to this is that, we will only display the pause-resume button when it actually starts the upload and initially we also have to set the state of uploads as queued other than first one and it will also an good user experience.

what do you think ?

**Comment by arinmodi** [comment]
Hey @4D17Y4,  can you also give it a think on above comment and this issue

**Comment by arinmodi** [comment]
@nicolas-raoul, please have a look on above comment, so that i can move forward

**Comment by arinmodi** [comment]
@nicolas-raoul, please update on this, thanks

**Comment by nicolas-raoul** [comment]
Sorry for the delay!
Pausing may be used by people who are on a slow or costly Internet connection, so being able to pause uploads before they start is a good feature to have...

**Comment by nicolas-raoul** [comment]
Strangely I can't reproduce this in master anymore.

**Comment by arinmodi** [comment]
I think that's because we added the pause dialogue, but in my device i am able to reproduce even with the pause dialogue.

**Comment by nicolas-raoul** [comment]
Indeed that's probably linked!
Would you mind posting updated steps for reproduction? Thanks a lot!

**Comment by arinmodi** [comment]
![Screenshot_20220320-171256~2](https://user-images.githubusercontent.com/61725413/159160690-dc7c5d4a-dcd5-4f46-9ee7-f2664f5e14d5.png)

Here are the steps:

1. Upload multiple images from the app
2. Try to stop the all four fast
And one image will be still uploading

I followed above step and able to reproduce

**Comment by nicolas-raoul** [comment]
Strange, I do not reproduce despite using the same steps. I tried several times.

**Comment by ShashwatKedia** [comment]
@nicolas-raoul I tried to reproduce this issue several times, but it's not reproducible on the master anymore. I think it was solved by some PR, can we close this?

**Comment by ShashwatKedia** [comment]
@nicolas-raoul I tried to reproduce this issue several times, but it's not reproducible on the master anymore. I think it was solved by adding the `Pause Dialog`, can we close this and the related PR?

**Comment by nicolas-raoul** [comment]
@ShashwatKedia  I tried to pause a 10-pictures multi-upload, and some of the pictures got uploaded anyway. I will send a screencast shortly. :-)

**Comment by ShashwatKedia** [comment]
> @ShashwatKedia  I tried to pause a 10-pictures multi-upload, and some of the pictures got uploaded anyway. I will send a screencast shortly. :-)

Oh, strange. Sure, a screencast will surely help in reproducing the issue.

**Comment by nicolas-raoul** [comment]
https://github.com/commons-app/apps-android-commons/assets/99590/b149ab3e-d466-4235-93e6-bc716f0b6d96

**Comment by nicolas-raoul** [comment]
This issue has been fixed by GSoC 2024. :-)
