### ISSUE TITLE
Cancel upload

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#4836]
### What is the user problem or growth opportunity you want to see solved?

Sometimes I select a picture by mistake, or forget to remove EXIF before uploading.

Currently the only option is to reset the app's data, which:
- is inconvenient,
- forces the user to log in again,
- redownloads hundreds of megabytes of contributions,
- loses bookmarks and history.

**Comment by arinmodi** [comment]
I want to work on this...

So in this i have to add functionality of cancelling upload, which is started by user, Am i right ?

**Comment by nicolas-raoul** [comment]
@arinmodi Yes, thanks! When tapping the X button, the upload should stop and the picture's row in Contributions should disappear entirely. Please try to reuse the round X button seen when an upload failed (it has the desired effect of removing the upload):

![adb](https://user-images.githubusercontent.com/99590/154794484-5c155e0b-b610-47df-8534-11d4b5180ec4.png)

**Comment by arinmodi** [comment]
Do I have to show any popup to user before cancellation ?

**Comment by nicolas-raoul** [comment]
@arinmodi Good idea! I would suggest `Are you sure you want to cancel this upload?`

**Comment by arinmodi** [comment]
@nicolas-raoul, I have one query that....

According to me, allowing the cancellation during the ongoing upload is not a good user experience, but we can allow this option once user pause the upload,

what you think ?

Thanks

**Comment by nicolas-raoul** [comment]
Yes, sounds good, thanks for citing an example from another app!

**Comment by arinmodi** [comment]
Just for the confirmation, I have to allow the cancel only after pause, right ?

**Comment by nicolas-raoul** [comment]
Yes.

- During upload only the pause button is visible.
- After tapping on pause, two buttons are visible: remove (cross-shaped icon) and unpause (play icon)
- After tapping remove, a popup asks for confirmation.
- Removing makes the picture's row disappear, and removes associated memory/connection resources if any.
