### ISSUE TITLE
[Bug]: In peer review, deletion proposal is sent even if no reason is chosen

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#4844]
### Summary

In peer review, the deletion proposal is sent even if no reason is chosen.

### Steps to reproduce

1. Start peer review
2. When asked whether the picture is in scope, tap No
3. Without selecting any reason, submit

### Expected behaviour

Should not be submittable until at least a reason is chosen.

### Actual behaviour

Submitted without any reason listed. This simply shouldn't happen, as it results in a very weird (and useless) proposal.

### Android version

All

### Commons app version

3.1.1 master prodDebug

### Would you like to work on the issue?

Prefer not

**Comment by arinmodi** [comment]
@nicolas-raoul, i would like to work on this
