### ISSUE TITLE
[Bug]:  Pause Upload feature not working in Android 11

### ISSUE THREAD

**Issue by arinmodi** [commons-app/apps-android-commons#4848]
### Summary

Pausing upload not working android 11

### Steps to reproduce

1. Upload the picture 
2. pause upload

### Expected behaviour

should pause the upload

### Actual behaviour

it is showing the paused state to user in foreground, but it is uploading picture in background, and after some time you will notice that picture is uploaded to the contribution, which should not happen

### Device name

Realme RMX1971

### Android version

Android 11

### Commons app version

3.1.1 debug

**Comment by Rishavgupta12345** [comment]
@arinmodi actually pausing upload works, BUT only once.  

Click the pause button while uploading, uploading will be paused then click resume. works perfect 
But if you try to pause it again , it won't pause , THIS IS THE ACTUAL issue

**Comment by arinmodi** [comment]
@Rishavgupta12345, did you try in Actual android 11 device ?

**Comment by pigsonthewing** [comment]
Is this the same as #4835 ?

**Comment by ShashwatKedia** [comment]
@nicolas-raoul I tried reproducing this on master (using Android 11 device), but it doesn't seem to be reproducible anymore. Can we close this?
