### ISSUE TITLE
Pre-release Nearby does not detect location

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#485]
The pre-release version of Nearby (current master branch) loads the CSV, but does not detect your location when used in a freshly-installed app. Tested on an API 24 real device (Samsung Galaxy S7). The released version works fine (tested on the same night).

Might have something to do with location permissions not being asked? Not sure, will have to test further. @maskaravivek , what do you think could have broken it?

**Comment by misaochan** [comment]
2nd fresh install test - location permissions were asked and granted, but location is still not detected.

**Comment by misaochan** [comment]
Log before the unsorted and distance-less list is displayed:

```
04-10 02:28:54.764: D/fr.free.nrw.commons.nearby.NearbyListFragment(27251): NearbyListFragment created
04-10 02:28:54.771: D/fr.free.nrw.commons.nearby.NearbyListFragment(27251): Saved instance state is null, populating ListView
04-10 02:28:56.300: D/fr.free.nrw.commons.nearby.NearbyPlaces(27251): Reading from CSV file...
```

Seems like various methods are not called, including loadAttractionsFromLocation() in NearbyListFragment. 

As a side note, could I please request that logging be done with the class TAG in the future? It helps to be able to filter out logs relevant to our app, especially when testing from a real device with lots of other processes present. For instance `Log.d("NearbyAdapter", "Place " + place.name);` in NearbyAdapter could be `Log.d(TAG, "Place " + place.name);` with TAG being defined as `private static final String TAG = NearbyAdapter.class.getName();`. Sorry I missed that bit when I reviewed the code.

**Comment by maskaravivek** [comment]
@misaochan I couldn't take a look at it but could it be because of the refactoring that was done by me?

Will take care to use `TAG` in future. Also any opinion on using [Timber](https://github.com/JakeWharton/timber) for logging.

**Comment by veyndan** [comment]
I second the use of Timber

**Comment by veyndan** [comment]
We are calling `LocationServiceManager#getLatestLocation(…)` straight away after the initialisation of `LocationServiceManager` in `NearbyListFragment#onViewCreated(…)` but we aren't give the location enough time to get updated. Maybe by passing in a callback to the `LocationServiceManager` it may work, I'll have a look into it.

**Comment by misaochan** [comment]
Reverting the refactor does indeed seem to solve the problem. It's a pity since the refactor really made the code neater, but I can't figure out exactly which part of the refactor is causing it.

**Comment by whym** [comment]
For the record, the change that fixes this problem seems to be related to the duplicate LocationServiceManager instances, one in the activity, another in the fragment.

I changed a lot of other things too, so I'm not 100% sure about the cause, though.
