### ISSUE TITLE
[Bug]: Prod/beta flavor messages may be nonsense for users

### ISSUE THREAD

**Issue by neslihanturan** [commons-app/apps-android-commons#4850]
### Summary

A recent feedback came about messages like "Achievements are only available in the prod flavor." and "The leaderboard is only available in the prod flavor." may be nonsense for some of our users. The strings refers to the beta and prod flavor should better be changed with something else which is more understandable for all.

### Steps to reproduce

Try to see achievements or leaderboard in beta flavor

### Expected behaviour

An explanatory message

### Actual behaviour

a message which means something only to user who know about beta

### Android version

All versions

### Commons app version

master

**Comment by misaochan** [comment]
Sorry, just to clarify - these messages are only shown when a beta build is used, right? Not if a prod build is used? I haven't been able to reproduce this on prod.

If that is the case, surely if someone is using the beta build, they would be a developer and not a regular user, and should be aware of the prod and beta builds (or should be made aware of them, at least).

**Comment by Rishavgupta12345** [comment]
I would like to work on this issue but am unable to understand what actually I have to do here, If the required message and response is specified by the mentors here then I will implement them on the app

**Comment by nicolas-raoul** [comment]
These messages are not shown in prod, they are only shown to developers who have built the beta flavor by themselves (as we do not distribute any binary for beta). Even if they do not know yet what flavors are, I am willing to think they will search for the text of the tooltip message in the source code.

That being said, any better wording is very welcome :-) How about adding `Please check the developer documentation.` at the end, for instance?

**Comment by Rishavgupta12345** [comment]
> 

okay got it , you can assign me the issue now

**Comment by Rishavgupta12345** [comment]
> These messages are not shown in prod, they are only shown to developers who have built the beta flavor by themselves (as we do not distribute any binary for beta). Even if they do not know yet what flavors are, I am willing to think they will search for the text of the tooltip message in the source code.
> 
> That being said, any better wording is very welcome :-) How about adding `Please check the developer documentation.` at the end, for instance?

okay got it , you can assign me the issue now

**Comment by nicolas-raoul** [comment]
@Rishavgupta12345 My previous comment was mostly meant for Neslihan. As you can see in the discussion, there is no clear consensus yet. Let's wait until a consensus is reached :-)

**Comment by misaochan** [comment]
> That being said, any better wording is very welcome :-) How about **adding "Please check the developer documentation"** at the end [..]?

I'm good with implementing this. :)

**Comment by Rishavgupta12345** [comment]
@neslihanturan @nicolas-raoul so tell me the work I have to do in this issue and then please assign me this issue

**Comment by nicolas-raoul** [comment]
Just find all occurrences of `only available in the prod flavor` (might be a bit different) and add `Please check the developer documentation.` at the end. Thanks! :-)
