### ISSUE TITLE
Copyright warning for beta flavor

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#4855]
### What is the user problem or growth opportunity you want to see solved?

We have a first-time tutorial, but many beta users seem to believe that it is does not apply.

In fact, the beta server is also very strict on copyright.
Recently a user of the beta flavor of the app uploaded copyrighted images and got banned.

Most beta users probably do not read the wiki nor any documentation, and just git clone from GitHub then run the app and upload test pictures.

For the beta flavor only, I suggest adding a popup at the beginning of the first-time tutorial that says:
```
Please only upload pictures you have taken by yourself.
Uploaders of copyrighted images will be blocked.
This applies to the beta flavor too.
Thank you for testing the app!
```

**Comment by Rishavgupta12345** [comment]
I would like to work on this issue please assign me

**Comment by RS400** [comment]
Wow🤔

**Comment by nicolas-raoul** [comment]
@Rishavgupta12345 Just show the popup on the first page of the first-time tutorial. No relation with the peer review feature. Thanks!

**Comment by Rishavgupta12345** [comment]
@nicolas-raoul  you have suggested adding a popup in the first time tutorial for copyright, but I have seen that popup works only when there is a button click, but there is no button click so should I add a new layout that gives the copyright message just like as other things in the first time tutorial

**Comment by nicolas-raoul** [comment]
> "_I have seen that popup works only when there is a button click_"

What do you mean? Could you please giving us an Android documentation page explaining this?
