### ISSUE TITLE
[Bug]: file not found please try another file 

### ISSUE THREAD

**Issue by Rishavgupta12345** [commons-app/apps-android-commons#4875]
### Summary

problem 1:- 
clicking multiple times on the ' + ' button keeps increasing the dialogs. Those dialogs are useless as you are only uploading a single image you don't need multiple captions and descriptions

problem 2:-
if you are uploading an image and making 2 dialogs in step 1 using the ' +' button and giving two different captions and descriptions to that image then the image is not uploading and showing a TOAST "file not found please try another file "

### Steps to reproduce

while uploading an image we get to step 1, where we write the caption and description of the image 

in that option the left corner has a ' + ' button, If you click on it, it will increase a dialog box where you can write the caption and description.

### Expected behaviour

once you have added the caption in one language for suppose (English) , then you should not be allowed to make another caption in english 

### Actual behaviour

 TOAST "file not found please try another file "

### Would you like to work on the issue?

No

**Comment by Rishavgupta12345** [comment]
@nicolas-raoul  I created this issue and would like to work on it, if you think its OK then please assign me

**Comment by 4D17Y4** [comment]
@Rishavgupta12345 problem 1 is a feature where u can add captions and descriptions in multiple languages.
I cannot reproduce problem 2. Maybe try with a different image and let us know if you get the same result.

**Comment by Rishavgupta12345** [comment]
> @Rishavgupta12345 problem 1 is a feature where u can add captions and descriptions in multiple languages. I cannot reproduce problem 2. Maybe try with a different image and let us know if you get the same result.

if problem 1 is the feature to add a caption in another language then if once the user is writing the caption in English then the second option should disable English from the options and show other languages. to reproduce this issue try adding English caption twice in the same image. (which should not be present)

**Comment by Rishavgupta12345** [comment]
> I just successfully uploaded an image with captions in English and French.
> 
> Also, when there is already a caption in Japanese (for instance), the app does not let me select Japanese as the language for the subsequent captions.
> 
> So, I don't see any bug here yet. If you think there is really a bug, maybe post a screencast? Thanks! 🙂

if it is so then I am closing the issue
