### ISSUE TITLE
Delete all branches that aren't master

### ISSUE THREAD

**Issue by veyndan** [commons-app/apps-android-commons#488]
It seems that all the branches that aren't master aren't being maintained and are very old, ranging from a year to 4 years old. Looking over the commits of each branch, it doesn't appear we would be losing anything as some of them have no commits, and the rest don't appear to have gotten very far in respect to the branches desire.

Keeping all these branches gives the false sense that a lot of parallel work is being done in this project when none is. Also, in the future, if any parallel work is to be done, then it won't be masked by all the current unmaintained branches.

**Comment by nicolas-raoul** [comment]
The only branch worth saving might have been "campaigns", but it has zero commits that are not in master anyway, so I agree.

**Comment by misaochan** [comment]
I'm happy to do it, should we ask @yuvipanda first though since pretty much all of them are his?

**Comment by veyndan** [comment]
Yeah we should wait for a response just in case. Should I remove all the other branches not created by him (I believe I have the access permission to do such a thing)?.

**Comment by yuvipanda** [comment]
Yes, feel free to get rid of them!

And thank you for maintaining the app!

**Comment by veyndan** [comment]
Awesome, I'll delete them now
