### ISSUE TITLE
Have default first letter capital

### ISSUE THREAD

**Issue by jidanni** [commons-app/apps-android-commons#4885]
Here we see the keyboard is set for lowercase for the first letter. Well, as it'll end up uppercase later on the website and might as well be reflected in the keyboard first letter choice!
![Screenshot_20220311-075107.jpg](https://user-images.githubusercontent.com/1230959/157775022-8c73af0a-c431-477f-85f4-7699e30bd91e.jpg)

**Comment by jidanni** [comment]
In other words, on the screenshot, instead of seeing a keyboard full of lowercase letters, you should see it full of uppercase letters, for that first letter.

**Comment by 4D17Y4** [comment]
That's the file name which is also dependent on the number of images. Try another image with same name, you'll see that image has an appended integer for uniqueness. 
Captions and descriptions remains exactly same, you can check that on the file page.

**Comment by jidanni** [comment]
Yes, but in all cases the first letter will be capitalized, no? If it's in Chinese it wouldn't matter anyway but for Roman characters they always get capitalized for the very first letter so it might as well be capitalized when the user enters  it anyway.

**Comment by jidanni** [comment]
The integer appended is appended at the end, I'm talking about the very beginning, the very first ASCII character.

**Comment by adi7yashah** [comment]
I want to work on this issue please assign it to me

**Comment by 4D17Y4** [comment]
@jidanni, 
The captions remain precisely the same as entered by the user, the only change is to the title which is the same as the caption with the first letter capitalized and appended with an integer if not unique (Serving as the file name).

**Comment by 4D17Y4** [comment]
Welcome to the project @adi7yashah, 
This issue is under discussion, feel free to drop your suggestions if any. 

In the meantime, you can ask to get assigned to another issue. 
https://github.com/commons-app/apps-android-commons/labels/good%20first%20issue could help you get started.

**Comment by jidanni** [comment]
I get it. A lowercase / original version is still used somewhere. OK, closing.
