### ISSUE TITLE
Bug report: Failed to clear unsuccessful uploading

### ISSUE THREAD

**Issue by koala0090** [commons-app/apps-android-commons#4891]
How to reproduced:
> Open Wikimedia Commons app(https://play.google.com/store/apps/details?id=fr.free.nrw.commons)
> Upload a file to Wikimedia Common.
> Forced to terminate the process of app.

What happens?:
> Upload failed, but show uploading and failed to terminate the process

**Comment by Rishavgupta12345** [comment]
same as #4893 this is a language specific issue, tell me the language in which you are using the app and facing this issue

**Comment by koala0090** [comment]
> Traditional Chinese

**Comment by nicolas-raoul** [comment]
I believe this is fixed. If not, please reopen.
Thanks a lot for your feedback! 🙂
