### ISSUE TITLE
Reuse information from depictions in categorization step

### ISSUE THREAD

**Issue by Ainali** [commons-app/apps-android-commons#4892]
### What is the user problem or growth opportunity you want to see solved?

It is tedious to add the category when it is perceived that the software could assist with data input.

### How do you know that this problem exists today? Why is this important?

When I add that an image depicts something that has a Commons category connected on the Wikidata item, it feels like the app could assist me by suggesting that category for me as a user rather than needing to type it in again. "These categories are connected to things you added as depicted in the image: [list of connected categories with checkboxes]"

### Who will benefit from it?

Every user that adds depicts information.

**Comment by misaochan** [comment]
Hmm, I actually thought this was something that we had already implemented. @Ainali , could you confirm the version of the app that you are using?

Tagging @nicolas-raoul for input.

**Comment by Ainali** [comment]
Now I see! I was confused because [Q636666](https://www.wikidata.org/wiki/Q636666) did not show the category I expected. It turns out that it has two values on [P373](https://www.wikidata.org/wiki/Q636666#P373) and the one that unfortunately is hard to interpret for me is chosen in the app. Perhaps in cases where there are several values the app should show all of them, or if you only want to go with one, pick the one that is used as sitelink.

**Comment by nicolas-raoul** [comment]
I did not know an item could have several P373. 🤯

It is a Wikidata constraint violation but I guess it is OK for some types of items ("_ship can change [name](https://en.wikipedia.org/wiki/Ship_naming_and_launching) and [flag state](https://en.wikipedia.org/wiki/Flag_state) through time, but the [IMO number](https://en.wikipedia.org/wiki/IMO_number) remains the same through the [hull's](https://en.wikipedia.org/wiki/Hull_(watercraft)) entire lifetime. As a result, it can be useful to identify a ship by using the IMO number._")

I am fine with either suggesting all linked categories, or only the one listed as "Multilingual sites" (there strictly can only be one so we can hope that the most appropriate is used).
<img width="390" alt="Screen Shot 2022-03-15 at 20 30 19" src="https://user-images.githubusercontent.com/99590/158368839-13cf0f21-1ce8-41b8-b86c-6aaa025790bf.png">

Would you mind creating a new bug report for this? :-)

**Comment by Ainali** [comment]
Sure, I'll do that!
