### ISSUE TITLE
[Bug]: Regular expression exposed when uploading files

### ISSUE THREAD

**Issue by koala0090** [commons-app/apps-android-commons#4893]
### Summary

Regular expression exposed when uploading files

### Steps to reproduce

> Open Wikipedia Commons app (https://play.google.com/store/apps/details?id=fr.free.nrw.commons)
> Upload` a file to Wikipedia Commons

### Expected behaviour

> No regular expression exposed.

### Actual behaviour

Regular expression exposed in information box.
![Screenshot_20220308-185824311 (1)](https://user-images.githubusercontent.com/24404556/158063558-9b3cbf12-43ff-4590-a066-e8f401f5e596.jpg)

### Device name

ASUS Zenfone 6

### Android version

Android 10

### Commons app version

3.1.1

**Comment by Rishavgupta12345** [comment]
@koala0090 can you please tell me the language in which you are using the app , because this is a language-specific issue and doesn't happens in all other languages

**Comment by koala0090** [comment]
@Rishavgupta12345 Traditional Chinese

**Comment by misaochan** [comment]
@Nikerabbit

**Comment by Nikerabbit** [comment]
Please ping @translatewiki in the future to get attention from our support team.

Looks like one translator has used `$` in place of `%`. I have filed https://phabricator.wikimedia.org/T304043 to prevent it from happening again.

**Comment by Abijeet** [comment]
We've added a validator to ensure that these variables cannot be skipped in translations.

![image](https://user-images.githubusercontent.com/1685517/167600412-2140d5c0-a2b4-48b4-aa7d-bac6c1e95a58.png)

**Comment by misaochan** [comment]
Thanks for fixing this. :)
