### ISSUE TITLE
[Bug]: language Bengali has many string problems

### ISSUE THREAD

**Issue by Rishavgupta12345** [commons-app/apps-android-commons#4894]
### Summary

Notice the title bar in the gif it changes from English to Bangla when tapped on the menu. Notice the name change in other tabs as well.

### Steps to reproduce

![158153697-bc771dc7-372b-4380-a97f-0259f650fbc2](https://user-images.githubusercontent.com/74723804/158181188-621531a5-05bb-49ba-91b4-17edbe6058d5.gif)

### Expected behaviour

This change of language should not happen and it should remain in BENGALI

### Actual behaviour

the title bar in the gif it changes from English to Bangla when tapped on the menu.

**Comment by misaochan** [comment]
I believe this is not caused by the app itself, but rather by the lack of Bengali translations for "Bookmarks". We welcome any new translations, and anyone can sign up as a translator at Translatewiki.

**Comment by nicolas-raoul** [comment]
Either missing translation or https://github.com/commons-app/apps-android-commons/issues/5501 I guess.
