### ISSUE TITLE
App downloads too many of my contributions, without reason

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#4900]
### Summary

Even without scrolling down, the app seems to download the metadata of hundreds of my past contributions.
This wastes network data, storage space, and seems to be the root cause of [a "Davey" latency problem](https://github.com/commons-app/apps-android-commons/pull/4725#issuecomment-1051425419).

### Steps to reproduce

1. Install the app with an account that has hundreds of uploads ([tip](https://github.com/commons-app/apps-android-commons/issues/4359#issuecomment-820904731)) 
2. Start the app
3. Launch adb logcat
4. Log in inside the app, do nothing else in the app
5. Just watch downloads of metadata in logcat

### Expected behaviour

Downloads of contributions should stop after a page or two

### Actual behaviour

The app continues loading hundreds of contributions

### Android version

Any

### Commons app version

Master

### Would you like to work on the issue?

Prefer not

**Comment by devarsh-mavani-19** [comment]
@nicolas-raoul  So we want something like lazy loading (pagination)? As we scroll down, more data should be loaded right?
I would like to work on this issue

**Comment by misaochan** [comment]
Hmm, it looks like when we introduced lazy loading, we only introduced it for the images but not the metadata. So I think we would need to download the data at the appropriate time (when the image is downloaded), not all at the start.

**Comment by nicolas-raoul** [comment]
@misaochan : I wrote metadata, but I am not too sure what transits. I just see a packet per picture, at a very fast pace (more than 1 request per second), and that seems to never stop.

@devarsh-mavani-19 : Thanks! Better use prod for this issue as it is not about writing. Do you have an account with hundreds of contributions? If not, see the tip above :-)

**Comment by devarsh-mavani-19** [comment]
@nicolas-raoul no I don't have account with hundreds of contribution.

**Comment by nicolas-raoul** [comment]
@devarsh-mavani-19 Please send me an email as tipped at https://github.com/commons-app/apps-android-commons/issues/4359#issuecomment-820904731 thanks!

**Comment by devarsh-mavani-19** [comment]
> @devarsh-mavani-19 Please send me an email as tipped at [#4359 (comment)](https://github.com/commons-app/apps-android-commons/issues/4359#issuecomment-820904731) thanks!

sorry for the delay. sent you an email
