### ISSUE TITLE
Feedback section title contains links and "talk", should only contain plain-text username

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#4904]
### Summary

Currently the app posts `~~~` which is transformed into something complex.
Instead, the app should insert the username (may be `AccountUtil.getUserName`).

### Steps to reproduce

1. Log into the app
2. Tap the hamburger menu
3. Tap `Feedback`
4. Send some feedback
5. Go to https://commons.wikimedia.org/wiki/Commons:Mobile_app/Feedback
6. Click `Edit` to see the wikicode

### Expected behaviour

The section title of the feedback you added should be something like `Feedback from Kaartic for version 3.1.1-debug-HEAD~5d33ee53c`

### Actual behaviour

Instead, it is something much more complex, for instance:

`Feedback from [[User:Kaartic | Kaartic]] <sup>[</sup><sup>[[User talk:Kaartic |talk]]</sup><sup>]</sup> for version 3.1.1-debug-HEAD~5d33ee53c`

### Android version

all

### Commons app version

master

### Would you like to work on the issue?

Prefer not

**Comment by devarsh-mavani-19** [comment]
Will do it
