### ISSUE TITLE
Peer review: "thank the contributor" should show snackbar instead of notification

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#4906]
![adb](https://user-images.githubusercontent.com/99590/159151757-41e422f1-d334-4471-903f-115f868d7147.png)

**Comment by arinmodi** [comment]
I want to work on this

**Comment by arinmodi** [comment]
![Screenshot_20220320-152617~3](https://user-images.githubusercontent.com/61725413/159159289-c9360ad6-0804-4b7e-8b07-6cbb76b626c2.png)
 
Is this ok ?

**Comment by nicolas-raoul** [comment]
Seeing this now, I am a bit worried about usability. Performing peer review usually means tapping about 1 button per second, so the button being hidden impacts productivity.

**Comment by arinmodi** [comment]
I think it will not a major issue cause we are displaying the snackbar for a sec and there is also a sec delay before the user start the next review because of the loading of the image. So it will not affect the user.

**Comment by arinmodi** [comment]
@nicolas-raoul, please update on this

**Comment by nicolas-raoul** [comment]
If you believe it does not hinder fast peer review, please send a pull request and we will be able to try it out.
Thanks!

**Comment by arinmodi** [comment]
made the pr
