### ISSUE TITLE
Thumbnail image is grey during upload

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#4908]
When a picture is being uploaded, it is shown as a grey default thumbnail:

![adb](https://user-images.githubusercontent.com/99590/159159847-aac70aeb-1c6a-4721-b83d-50fb862f371e.png)

I think that showing a thumbnail of the real picture would be more user-friendly, especially when I want to pause a given picture within a multi-upload, or to know what picture's upload failed, or to choose what pictures to upload next (without trying to upload the same twice).

**Comment by arinmodi** [comment]
I can solve this in the #4908 PR

**Comment by arinmodi** [comment]
I can solve this in #4905

**Comment by nicolas-raoul** [comment]
@arinmodi It is better done in a separate pull request.

**Comment by arinmodi** [comment]
ok @nicolas-raoul, please assign this to me
