### ISSUE TITLE
Turn off ACRA for debug builds

### ISSUE THREAD

**Issue by veyndan** [commons-app/apps-android-commons#491]
I don't get any stack trace of exceptions caused by the app, but instead I get the ACRA dialog stating that the app has crashed. This usually leads me to commenting out the ACRA initialisation in `CommonsApplication`. Wouldn't it be better to turn off ACRA when doing a debug build and turn it on for release builds?

**Comment by nicolas-raoul** [comment]
Is this doable automatically, for instance with ProGuard maybe?

**Comment by veyndan** [comment]
If we did:
```
if (BuildConfig.DEBUG) {
    ACRA.init(this);
}
```
that should do it. I suppose we could use Proguard but I feel the above method would be easier to implement, as well as easier to follow if someone looks over the code.

**Comment by whym** [comment]
Thanks @veyndan - this was actually a pain for me too.
