### ISSUE TITLE
Use one networking library

### ISSUE THREAD

**Issue by veyndan** [commons-app/apps-android-commons#492]
Currently both Volley and Apache HttpClient are being used. I think it'd be preferable to just use one networking library. My suggestion would not be to use either Volley or Apache HttpClient though, but instead use [Retrofit](https://github.com/square/retrofit), mainly because:
* it is used a lot more than Volley is
* there is a [GSON converter](https://github.com/square/retrofit/tree/master/retrofit-converters/gson) which makes JSON parsing a breeze
* there is better documentation on Retrofit compared to Volley
* it is more modular than Volley or Apache HttpClient with the use of converters and adapters (though it has been a while since I've used Volley or Apache HttpClient so correct me if I'm wrong).

Thoughts?

**Comment by nicolas-raoul** [comment]
Uniformizing is a good idea, and Retrofit looks nice indeed.
What is the size of the JARs for each solution?

**Comment by misaochan** [comment]
Looks good to me, if anyone would like to rewrite the relevant code to use it.

**Comment by veyndan** [comment]
I wasn't totally sure how to find out the jar size of a dependency through Gradle, so if anyone has any idea I'd be very grateful. According to [methodscount.com](http://www.methodscount.com/), Retrofit has a size of [505KB](http://www.methodscount.com/?lib=com.squareup.retrofit2%3Aretrofit%3A2.1.0) and Volley has a size of [86KB](http://www.methodscount.com/?lib=com.squareup.retrofit2%3Aretrofit%3A2.1.0). Note that Retrofit has a large size due to transitive dependencies, but this also means that if we use other Square libraries that depend on Okio or Okhttp then we won't incur the cost of the transitive dependencies again.

**Comment by dbrant** [comment]
This will be handled via #1092
