### ISSUE TITLE
"No location found" despite EXIF coordinates

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#4925]
All pictures I take with my Pixel 4 default camera app (geolocation enabled) have EXIF coordinates.

Problem: The Commons app (latest master) always shows the "No location found" popup.

![Screenshot_20220402-140231](https://user-images.githubusercontent.com/99590/161367418-b8595d77-d94f-4e24-9377-fa4820595308.png)

Example picture, I am not sure whether GitHub keeps the EXIF though so please let me know your email address and I can send it to you. Thanks!

![PXL_20220220_072250755 MP](https://user-images.githubusercontent.com/99590/161367288-0d600554-fc96-405e-bdb0-9c14eb08ca00.jpg)

**Comment by nicolas-raoul** [comment]
@Compiledebuger Sent, thank you! :-)

**Comment by Compiledebuger** [comment]
@nicolas-raoul the picture you sent to me also isn't contain GPS information, and then I try to upload a picture with exif coordinates and find the location, the app didn't popup with "No location found"

**Comment by nicolas-raoul** [comment]
Sorry you are right, that picture had no EXIF location! Somehow Galaxy Gallery showed a map for it, maybe it stores location another way, or maybe I did a mistake.
I will close this issue, and reopen it if I manage to reproduce with a picture that really has EXIF location.
Thanks a lot for your help!
