### ISSUE TITLE
Fix CI - Invalid resource directory name

### ISSUE THREAD

**Issue by madhurgupta10** [commons-app/apps-android-commons#4927]
It seems like the CI is failing with the following error, not sure what is the problem here but we should fix this asap.
```
Caused by: com.android.build.gradle.tasks.ResourceException: /home/runner/work/apps-android-commons/apps-android-commons/app/src/main/res/values-zh-hk: Error: Invalid resource directory name
```

**Comment by madhurgupta10** [comment]
@nicolas-raoul @misaochan I am not familiar with `translatewiki bot` but looking at the logs it seems like it is linked to translatewiki.

**Comment by nicolas-raoul** [comment]
We need to add a new line `zh-hk: zh-rHK` to https://phabricator.wikimedia.org/diffusion/GTWN/browse/master/groups/Wikimedia/CommonsAndroid.yaml

**Comment by nicolas-raoul** [comment]
@Nikerabbit Would you mind adding `zh-hk: zh-rHK` to https://phabricator.wikimedia.org/diffusion/GTWN/browse/master/groups/Wikimedia/CommonsAndroid.yaml? Thanks a lot!

**Comment by Nikerabbit** [comment]
Ping @translatewiki

**Comment by misaochan** [comment]
@translatewiki 

> Would you mind adding zh-hk: zh-rHK to https://phabricator.wikimedia.org/diffusion/GTWN/browse/master/groups/Wikimedia/CommonsAndroid.yaml? Thanks a lot!

**Comment by misaochan** [comment]
@translatewiki @Nikerabbit Would it be possible to get a ETA on when this could be fixed on Wikimedia's end? Thanks a lot!

**Comment by Abijeet** [comment]
> @translatewiki @Nikerabbit Would it be possible to get a ETA on when this could be fixed on Wikimedia's end? Thanks a lot!

Sorry for the delay. We should be able to get this in sometime next week.

**Comment by misaochan** [comment]
Wonderful, thanks for the update @Abijeet !

**Comment by Abijeet** [comment]
Translatewiki now exports the language in `zh-rHK`. See commit: https://github.com/commons-app/apps-android-commons/commit/11bc72c5142ada2d9c21d845e35317ad8016daed
