### ISSUE TITLE
Nearby filter bookmark icon invisible in dark mode

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#4930]
The bookmarks icon in the nearby search menu needs a dark mode icon. 

The icon is present, but is the same color as the menu "black". When the bookmarks row is touched for selection the background changes to gray and the icon is revealed as the black color.

Solution probably just needs a different icon color while in dark mode.
![Screenshot_20220404-082726](https://user-images.githubusercontent.com/99590/162723868-eea59678-bd7c-402f-9348-7c3477650497.png)

**Comment by JustinLiang522** [comment]
hello, I would like to work on this issue. Could you plz assign it to me?

**Comment by nicolas-raoul** [comment]
@JustinLiang522 It is yours, thanks! :-)

**Comment by JustinLiang522** [comment]
@nicolas-raoul I have downloaded several icons from https://www.iconfont.cn/. Which one do you think is the most suitable?
![bookmarks](https://user-images.githubusercontent.com/73240868/162739426-0829a78f-4a42-40f9-baf3-0552ecda2d95.png)

**Comment by nicolas-raoul** [comment]
It looks great!
Sure, feel free to send a pull request :-)
