### ISSUE TITLE
Erroneous "Your recent uploads have no location"

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#4936]
### Steps to reproduce

1. Uploaded many pictures without EXIF location.
2. Uploaded one picture WITH EXIF location (via Nearby, not sure whether it matters).

Not sure whether reproducible every time.

### Expected behaviour

This message should not appear, as the picture being uploaded has location.

### Actual behaviour

![Screenshot_20220416-152035_Commons](https://user-images.githubusercontent.com/99590/163666575-e42a509b-502c-48ba-8c87-3af7e49f38b4.jpg)

### Android version

8

### Commons app version

master

### Would you like to work on the issue?

Prefer not

**Comment by Aman16-ai** [comment]
i would like to work on this issue

**Comment by nicolas-raoul** [comment]
@Aman16-ai It is yours, thanks!

**Comment by chan-j-d** [comment]
Hi @nicolas-raoul, it's been some time since this issue was assigned and I'd like to try my hand with it if that's alright.

**Comment by nicolas-raoul** [comment]
@chan-j-d It is yours now, thanks!
