### ISSUE TITLE
Template interferes with GitHub app

### ISSUE THREAD

**Issue by jidanni** [commons-app/apps-android-commons#4944]
Here I tried to use the GitHub app to file a bug report. However I was kicked out of the app as you see in the screenshot.

To continue using the GitHub app I had to instead select the very first choice: no template.

If this is GitHub's fault, please tell them.

![Screenshot_20220425-063827.jpg](https://user-images.githubusercontent.com/1230959/164999710-6292dfcd-627f-459a-975c-890e34de52ee.jpg)

**Comment by misaochan** [comment]
Does it work if you select a browser and use the web-based version?

**Comment by jidanni** [comment]
Well yes, but that takes the whole point out of GitHub making an app and templates.
I suspect this is all GitHub's fault.

**Comment by nicolas-raoul** [comment]
To be clear, the screenshot shows the GitHub app, right?

I don't use the GitHub app personally, but I feel like it is a good enhancement idea for their app indeed. @jidanni Would you mind reporting it to them?
