### ISSUE TITLE
[Bug]: After moving between tabs on Bookmark fragment, Bookmarks never loads

### ISSUE THREAD

**Issue by neslihanturan** [commons-app/apps-android-commons#4947]
### Summary

When we select Bookmarks from bottom menu, the picture tab comes selected and bookmarked pictures are there. After that if we select locations tab and come back to pictures tab again, we don't see bookmarked images (seeing them is expected) and we see a progressbar instead.

### Steps to reproduce

1. Select bookmarks tab
2. Wait until bookmarked photos are visible
3. Select location or item tab inside bookmarks
4. Select pictures tab again

### Expected behaviour

Seeing bookmarked image

### Actual behaviour

Seeing no image and only progress bar

### Device name

Pixel 5 API 30 Emulator

### Android version

Android 11.0

### Commons app version

master

**Comment by Ayan-10** [comment]
Can I look into it?

**Comment by misaochan** [comment]
Sounds like it's related to #4949 , although in my case it straight-up crashes. Might be because I have 0 bookmarks.

@Ayan-10 yes please feel free, thanks!
