### ISSUE TITLE
[Bug]: Back arrow still present on top-level activity (Contributions)

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#4950]
### Summary

If you load the app and select an image to view, you can return to the top-level activity (Contributions) by tapping the up button (back arrow). But the up button remains present once you are in Contributions again.

### Steps to reproduce

1. Open app
2. Tap an image to enter media details view
3. Tap up button to return to Contributions

### Expected behaviour

Up button should not be visible in top level activity

### Actual behaviour

Up button remains visible

### Device name

Samsung Galaxy S20 FE

### Android version

Android 11

### Commons app version

master and 4.0-release (prodRelease build variant)

### Screen-shots

![Screenshot_20220429-205500_Commons](https://user-images.githubusercontent.com/3611199/165938361-e29251ab-662d-4478-a384-ed94fab21891.jpg)

**Comment by neslihanturan** [comment]
this looks like fixed with #4952
