### ISSUE TITLE
[Bug]: Always show "unable to get description" dialog after exiting the media detail fragment.

### ISSUE THREAD

**Issue by JustinLiang522** [commons-app/apps-android-commons#4953]
### Summary

Every time I click the edit description button on a picture and exit, a pop-up dialog "unable to get description" will always show even if the descriptions are displayed correctly.

### Steps to reproduce

1. go to "Explore"
2. open a picture
3. click the edit description button
4. exit editing

### Expected behaviour

no pop-up dialog is shown

### Actual behaviour

a pop-up dialog "unable to get description" is shown

### Device name

Pixel 3

### Android version

Android 10

### Commons app version

prodDebug

### Screen-shots

![Screenshot_20220507_131750_fr free nrw commons](https://user-images.githubusercontent.com/73240868/167239633-2f112ef0-9b72-4ffe-b3e0-56f8dedd65c2.jpg)

### Would you like to work on the issue?

Yes

**Comment by nicolas-raoul** [comment]
I can reproduce the issue in master.
