### ISSUE TITLE
App corrupts Commons description

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#4957]
App erroneously modified `|description=` to `|descriptio`

https://commons.wikimedia.org/w/index.php?title=File%3A%E4%B9%9D%E5%8D%81%E4%B9%9D%E9%87%8C%E6%B5%9C_7.jpg&type=revision&diff=655568871&oldid=655568708

Another example: https://commons.wikimedia.org/w/index.php?title=File:Fishtbnk_truck_near_Kujukuri_beach.jpg&diff=prev&oldid=656180711

I believe that happened when editing the caption.

Current master

**Comment by madhurgupta10** [comment]
@nicolas-raoul Could you share the exact steps to reproduce this issue?

**Comment by madhurgupta10** [comment]
Also pinging @Ayan-10 as this seems related to https://github.com/commons-app/apps-android-commons/pull/4672

**Comment by Ayan-10** [comment]
@madhurgupta10 @nicolas-raoul I have investigated the issue. This issue occurs when the file doesn't have any description in any language and user only add a caption without a description. Like this file: https://commons.wikimedia.org/w/index.php?title=File:Fishtbnk_truck_near_Kujukuri_beach.jpg&diff=prev&oldid=656180711 doesn't have any description or caption, now if user add a caption in a language without a description in the editor screen. This issue will occur.

The lines, causing the issue are
```
Line 157: buffer.deleteCharAt(buffer.length - 1)
Line 158: buffer.deleteCharAt(buffer.length - 1)
```
in the `DescriptionEditActivity`. But these lines are important if the file has any description. I think the issue can be resolved by checking if any description is present in the list.

Thanks

**Comment by madhurgupta10** [comment]
> @madhurgupta10 @nicolas-raoul I have investigated the issue. This issue occurs when the file doesn't have any description in any language and user only add a caption without a description. Like this file: https://commons.wikimedia.org/w/index.php?title=File:Fishtbnk_truck_near_Kujukuri_beach.jpg&diff=prev&oldid=656180711 doesn't have any description or caption, now if user add a caption in a language without a description in the editor screen. This issue will occur.
> 
> The lines, causing the issue are
> 
> ```
> Line 157: buffer.deleteCharAt(buffer.length - 1)
> Line 158: buffer.deleteCharAt(buffer.length - 1)
> ```
> 
> in the `DescriptionEditActivity`. But these lines are important if the file has any description. I think the issue can be resolved by checking if any description is present in the list.
> 
> Thanks

Thanks for the detailed investigation, I believe these two lines are added to remove the extra `,  `  from the buffer string, in that case, I think replacing them with a regex pattern is a much better solution
