### ISSUE TITLE
CI: Instrumentation test started failing

### ISSUE THREAD

**Issue by sivaraam** [commons-app/apps-android-commons#4958]
### Description

In CI, the instrumentation tests started failing in `master` with the following trace:

```
fr.free.nrw.commons.MainActivityTest > testExplore[test(AVD) - 7.0] FAILED 
	java.lang.IllegalStateException: init() must be called prior to using this method.
	at androidx.test.espresso.intent.Checks.checkState(Checks.java:70)
...
```

Failed build link: https://github.com/commons-app/apps-android-commons/runs/6450786871?check_suite_focus=true

I also observed a similar failure when [running tests in my fork of the repo](https://github.com/sivaraam/apps-android-commons/runs/6457229905?check_suite_focus=true) for the test written for PR #4902.

I'm not too familiar with the instrumentation test to know what went wrong. I'll try to explore when I get enough time. In the meanwhile, any help would be appreciated.

Note: I wonder if this is related to #4832.

**Comment by madhurgupta10** [comment]
@sivaraam Unfortunately sometimes there could be flaky tests depending upon which kind of VM is running the emulator, there are some random dialogues on Android devices such as low storage, updates available, welcome popup, etc. which overshadows the actual views and leads to test failures. The only way, for now, we can fix it is by rerunning the CI manually. The ideal solution would be to keep instrumentation tests to minimal and cover max codebase using unit tests only.

**Comment by sivaraam** [comment]
In that case, could we at least consider making the instrumentation tests independent of the rest of the CI cycle by keeping it as a separate job ? I suggest this since it appears to be getting in the way of running unit test cases.

For reference, the Git repo has a [GitHub CI workflow with multiple jobs](https://github.com/git/git/blob/master/.github/workflows/main.yml).
