### ISSUE TITLE
Caption with trailing whitespace leads to failed upload (titleblacklist-custom-space)

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#4962]
Latest master.

Steps:

1. Upload any picture.
2. At the caption step, enter a name with a space at the end.
3. The upload seems to be starting fine, but at the end it fails with the logcat error `titleblacklist-custom-space`.

**Comment by Jiaweeeeeen** [comment]
@nicolas-raoul Hi, can I work on this issue?

**Comment by nicolas-raoul** [comment]
@Jiaweeeeeen Yes thanks! :-) Did you manage to reproduce the issue?

**Comment by Jiaweeeeeen** [comment]
@nicolas-raoul I haven't reproduced the issue. Is it the same step you provide above?

**Comment by nicolas-raoul** [comment]
Yes, it might take a few attempts in various situations.

**Comment by Jiaweeeeeen** [comment]
I think the solution could be to add a method in `UploadMediaDetailInputFilter.java` to check the trailing whitespace in the caption field. Then in the `filter`, if the input text has any trailing whitespace, simply remove it. I'm going to implement these methods and hope the solution works.

**Comment by Jiaweeeeeen** [comment]
Unfortunately, this solution doesn’t work because any empty space the user types is recognized as trailing space. Instead, I have another solution to remove them after the user typed the caption. Any trailing whitespace will be removed when set to  `uploadMediaDetails`.
