### ISSUE TITLE
[Bug]: Use of "previous" then "next" causes duplicates if name changed

### ISSUE THREAD

**Issue by pigsonthewing** [commons-app/apps-android-commons#4966]
### Summary

When uploading multiple images, switching backwards and forwards between them to edit the "caption" [sic: file name] causes duplicate uploads

### Steps to reproduce

1. Select multiple images to share
2. Share to app
3. Enter caption and description for first image
4. Copy details to all images 
5. Select "Next"
6. Modify image caption
7. Select "Previous"
8. Modify image caption
9. Select "Next"
9. Select "Next" again
10. Optionally repeat 6-9 
11. Complete upload

### Expected behaviour

Each image should be uploaded once, with the final version of its caption as the file name.

### Actual behaviour

Multiple copies of images are uploaded.

### Device name

Nord Plus One

### Android version

Android 11

### Commons app version

3.1.1~1c9267ca0

### Would you like to work on the issue?

Prefer not

**Comment by nicolas-raoul** [comment]
Thanks for reporting!

Good news, that does not seem to happen in recent master, I just tried with the exact same steps. If this is actually not happening every time, please let us know, thanks! 🙂

**Comment by pigsonthewing** [comment]
> If this is actually not happening every time, please let us know

Happy to test; when will this master be deployed?

**Comment by nicolas-raoul** [comment]
> Happy to test; when will this master be deployed?

Thanks a lot, that's a great help!
I believe it is already available to beta users. Here is how to join the beta: https://github.com/commons-app/commons-app-documentation/blob/master/android/Volunteers-welcome!.md#testers

**Comment by pigsonthewing** [comment]
I have now tested this using the current Beta (version=4.0.3~23c474b06). The issue persists, and occurred on my first attempt to upload multiple images..

See screenshot at https://commons.wikimedia.org/wiki/File:Commons_app_beta_screenshot_showing_duplicate_uploads_-_2022-08-07.png  (The duplicate copies have been nominated for speedy deletion.)

**Comment by nicolas-raoul** [comment]
Thanks, I will try again!

**Comment by ShashwatKedia** [comment]
@nicolas-raoul I tested with the steps provided, [[Screencast]](https://drive.google.com/file/d/1-t2vb7vAMlpz45YvwqQV5u-YlnHPa9zK/view?usp=sharing) but the app correctly uploaded the images without any duplicates. @pigsonthewing does this issue still occur for you? If not, could we close the issue?

**Comment by pigsonthewing** [comment]
Seems fixed; thank you
