### ISSUE TITLE
[Bug]: Blank page shown when trying to edit descriptions

### ISSUE THREAD

**Issue by JustinLiang522** [commons-app/apps-android-commons#4971]
### Summary

When I try to edit the description of this picture, a blank page is shown.
<img src="https://user-images.githubusercontent.com/73240868/169974280-909e2280-1daa-44ad-9b87-3b1df7668732.jpg" width="50%" height="50%" />
<img src="https://user-images.githubusercontent.com/73240868/169974312-02605e6b-facd-42ad-b07f-b4da74b18542.jpg" width="50%" height="50%" />
I think this is probably because the description extraction algorithm fail to handle specific descriptions.

### Steps to reproduce

1. click the image I mentioned from explore
2. click the edit description button

### Expected behaviour

descriptions shown

### Actual behaviour

a blank page shown

### Device name

HUAWEI HMA-AL00

### Android version

Android 10

### Commons app version

prodDebug

### Would you like to work on the issue?

Yes

**Comment by nicolas-raoul** [comment]
I can reproduce for the first pic I tried in Explore>Featured

Thanks!
