### ISSUE TITLE
[Bug]: Compile error when building with prodRelease 

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#4972]
### Summary

Building the 4.0-release branch with the prodRelease build variant encounters an error as of today (24 May). It did not encounter any errors the last time I did it (about 2 weeks ago), hence the issue probably lies with a deprecation or changes to the relevant external library.

Commenting out the line `implementation("io.github.coordinates2country:coordinates2country-android:1.2") {  exclude group: 'com.google.android', module: 'android' }` in build.gradle solves the compile error, but might introduce other issues.

### Steps to reproduce

Build the 4.0-release branch with the prodRelease build variant. Do not test with prodDebug, this does not run minifyWithProguard and therefore does not cause the same issue.

### Expected behaviour

Compile

### Actual behaviour

Error

### Device name

n/a

### Android version

all

### Commons app version

4.0-release branch

### Device logs

```
:app:minifyProdReleaseWithProguard
class [META-INF/versions/9/module-info.class] unexpectedly contains class [module-info]
java.io.IOException: Can't read [C:\Users\misao\.gradle\caches\transforms-3\f01f3ac3a037e688ad96109d2702c702\transformed\jetified-coordinates2country-android-1.2.jar(;;;;;;;**.class)] (Can't process class [io/github/coordinates2country/Coordinates2Country.class] (Unsupported version number [55.0] (maximum 54.0, Java 10)))
Unsupported version number [55.0] (maximum 54.0, Java 10)
```

**Comment by madhurgupta10** [comment]
@misaochan Did you try after deleting the cached packages and build folder?

**Comment by misaochan** [comment]
Yes, doesn't solve the issue. :/

**Comment by misaochan** [comment]
Hi @nicolas-raoul , any thoughts on what the issue could be? As you appear to be the author of https://github.com/coordinates2country/coordinates2country-android :)

**Comment by nicolas-raoul** [comment]
I can reproduce the issue.

I built that library using `openjdk 11.0.12 2021-07-20 LTS` or earlier.

If there is anything I can change on the library side to fix it, I am happy to do it. :-)
The answers at https://stackoverflow.com/questions/54147275/move-to-openjdk-11-but-compile-in-java-8 sound may be relevant?
