### ISSUE TITLE
[Bug]: No web browser found to open URL or map application

### ISSUE THREAD

**Issue by kudlav** [commons-app/apps-android-commons#4984]
### Summary

When I try to open any link in Commons app (beta release), it shows just a toast:

> No web browser found to open URL

or

> No compatible map application could be found on your device. Please install a map application to use this feature.

Other apps works fine. Stable Commons app works fine, it will open Firefox in _Custom tabs_ mode.

Installed browser:
- Firefox 100.3.0

Installed navigations:
 - Google Maps
 - Mapy.cz
 - Organic Maps

### Steps to reproduce

1. Open the app
2. Open a place
3. Click to Route/Wikidata/Commons
4. An error toast occures and nothing else happens

### Expected behaviour

It should open browser in Custom tabs mode or display "share" dialog for map navigation.

### Actual behaviour

An error toast occures and nothing else happens.

### Device name

Samsung Galaxy A40

### Android version

Android 11

### Commons app version

4.0.0~e27f5d445

### Would you like to work on the issue?

Prefer not

**Comment by misaochan** [comment]
@kudlav thanks for letting us know! We will try to fix this in the next release.

**Comment by madhurgupta10** [comment]
Fixed in #4987
