### ISSUE TITLE
Bigger text fields for title/description

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#499]
How about two lines for title, four lines for description?

Let's make life easier for people who are patient enough to enter a lot of info.

Most of my titles take two lines, and it is a pain to not see the beginning of my text. When line wraps I often wonder whether the beginning is lost.

**Comment by misaochan** [comment]
Sounds good to me. Would 2 + 4 be too much for the phones with smaller screens though?

**Comment by nicolas-raoul** [comment]
How about letting the description field use whatever space is left?

**Comment by misaochan** [comment]
We should probably bump this one - I think it is inconvenient for a lot of people, especially in the case of the description.

**Comment by zapdoss** [comment]
Is anyone working on this issue? I would like to work on it.

**Comment by nicolas-raoul** [comment]
@zapdoss That would be great, go ahead, thanks! :-)

**Comment by misaochan** [comment]
@zapdoss Welcome! And yes, please feel free to work on this. :)

**Comment by Divya063** [comment]
Can I have an update on the issue?I would like to work on this

**Comment by whym** [comment]
Solved via #838
