### ISSUE TITLE
[Bug]: F-Droid: GMS libs in the final apk

### ISSUE THREAD

**Issue by linsui** [commons-app/apps-android-commons#4994]
### Summary

F-Droid deploys a new binary scanner which finds GMS in the apk. See https://gitlab.com/linsui/fdroiddata/-/jobs/2577487197 I don't know where it comes from.

### Steps to reproduce

You can use dexdump and grep to check the apk.

### Expected behaviour

There is no nonfree libs.

### Actual behaviour

GMS sleaks in.

### Android version

_

### Commons app version

Since 2.6.5

**Comment by nicolas-raoul** [comment]
Thanks for letting us know about this!

**Comment by licaon-kter** [comment]
It's via mapbox, there are references in `com/mapbox/android/core/location/`

Any chance to update to https://github.com/maplibre/maplibre-gl-native instead of the old lib?

Ref: https://github.com/maplibre/maplibre-gl-native/pull/313

**Comment by nicolas-raoul** [comment]
The Timber error sounds like something that could be solved with some Gradle wizardry maybe?

**Comment by bhavanagarlapati** [comment]
@nicolas-raoul Hi, can I take this up?

**Comment by nicolas-raoul** [comment]
@bhavanagarlapati Yes, please let us know about your progress every two or three days, thanks! :-)

**Comment by bhavanagarlapati** [comment]
Hi @nicolas-raoul I started working on the issue. I will keep you posted

**Comment by kartikaykaushik14** [comment]
Hi @nicolas-raoul , is the issue fixed or I can take this up?

**Comment by nicolas-raoul** [comment]
@kartikaykaushik14 You are very welcome to take it up, thank you! Please let us know about your progress every two or three days.

@bhavanagarlapati I assume you have moved on, but if you have found anything please feel free to post your findings or ideas, thanks! :-)

**Comment by kartikaykaushik14** [comment]
Update: I first tried following @licaon-kter 's suggestion but even maplibre-gl uses GMS libraries internally. Trying to look for other alternatives.

**Comment by licaon-kter** [comment]
Try to look at Delta Chat or Element recipes, where it's cleaned up and rebuilt before the app is built.

It sounds straight forward to me but you might need to try it first to confirm.

**Comment by nicolas-raoul** [comment]
_(Just in case MapBox and maplibre are not usable, I want to mention that other options seem to be available: https://wiki.openstreetmap.org/wiki/Software_libraries#Native_widgets)_

**Comment by linsui** [comment]
Maplibre will remove the dep of GMS soon. See https://github.com/maplibre/maplibre-gl-native/pull/801

**Comment by kartikaykaushik14** [comment]
I have a probable solution and just wanted to confirm if it's feasible. 

As @licaon-kter rightly pointed out, there are references in com/mapbox/android/core/location/. This is currently being used in only one class fr.free.nrw.commons.LocationPicker.LocationPickerActiviy.java. However, we can avoid using the libraries altogether by getting the last known location from locationComponent instead of using the location engine to get the last location of the user. In addition to it we can exclude gms from mapbox-android-sdk as suggested in [this comment](https://github.com/maplibre/maplibre-gl-native/issues/288#issuecomment-1141974632) in the MapLibre repo

Please refer to [116ff70](https://github.com/commons-app/apps-android-commons/commit/116ff70557f93786804fd0bc5619dcce6f7edea4)

**Comment by licaon-kter** [comment]
@kartikaykaushik14 unfortunately the exclusion is not enough anymore, see Linsui's link above for the path forward.

**Comment by kartikaykaushik14** [comment]
I was going through Delta Chat as a reference and they seemed to have removed telemetry as in this [line](https://github.com/deltachat/deltachat-android/blob/6a677517fc698fdb554b1a149a8eae80f1aa7b9f/src/org/thoughtcrime/securesms/map/MapActivity.java#L74) after they made changes to move to maplibre. 

Do we retain telemetry or remove it? 

I'm facing a build issue with com.mapbox.mapboxsdk.maps.TelemetryDefinition as it seems to be derived from the mapbox-android-sdk dependency which we are trying to eliminate. The telemetry dependency that we had earlier mapbox-android-telemetry:7.0.0 does not contain the TelemetryDefinition class and can in fact be removed since maplibre already provides the required support.

**Comment by licaon-kter** [comment]
@kartikaykaushik14 when I said "deltachat recipe" I meant https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/com.b44t.messenger.yml#L1855-L1880

**Comment by kartikaykaushik14** [comment]
@licaon-kter so if my understanding is correct, we do not have to implement the pre-build steps in the deltachat recipe once MapLibre removes the dependency of GMS right? I see that the changes were merged just yesterday and they have removed gms dependencies in the files that were previously being done through the pre-build steps. So can we probably wait for the official release in such a case?

**Comment by kartikaykaushik14** [comment]
Also, please advise regarding Telemetry if I should retain it or remove it like in the case of deltachat?

**Comment by licaon-kter** [comment]
@kartikaykaushik14 yup, I guess you'd need a new maven release

**Comment by nicolas-raoul** [comment]
@kartikaykaushik14 We need to remove telemetry, due to our app's privacy policy. Thanks a lot!

**Comment by kartikaykaushik14** [comment]
MapLibre has released a new version 10.0.0 that contains the fixes to remove gms dependencies. But as a result, there is a heavy backward compatibility break. For example, It requires a Kotlin version 1.7.20 (we currently use 1.5.10). And the minSdkVersion is 21 (currently 19, compile and target SDK Versions have to be modified to 31). The changes are not straightforward. Is there an open issue where we are handling any such upgrades?

**Comment by kartikaykaushik14** [comment]
Also, can we have a separate issue to track removing telemetry and I can be assigned to it? We have to remove telemetry first, make the required upgrades, and then we can proceed to move to MapLibre.

**Comment by nicolas-raoul** [comment]
@kartikaykaushik14 Good idea, feel free to create such issues as you see fit. Thank you!

**Comment by nicolas-raoul** [comment]
@kartikaykaushik14 Would you mind creating an issue about switching to MapLibre? You can be assigned to it if you want (the general rule is one assigned issue at a time, but since you are very knowledgeable on the topic and involved already, an exception would be justified).

**Comment by kartikaykaushik14** [comment]
@nicolas-raoul Could we close this issue too as we closed #5154, #5158, #5175 and #5182?

**Comment by nicolas-raoul** [comment]
Yes, sure.

Thanks a lot @kartikaykaushik14 for brilliantly solving this very complex issue!

**Comment by nicolas-raoul** [comment]
@sivaraam How about pushing a beta release as soon as you can? 🙂

**Comment by licaon-kter** [comment]
Which commit you want as beta?

**Comment by nicolas-raoul** [comment]
@licaon-kter Commit cf35307d9ace28157263342ddf85e46f454cd4a8 (latest commit on master) would be great for beta, it is very reliable already.

**Comment by nicolas-raoul** [comment]
@licaon-kter Thanks a lot! Will it appear at https://f-droid.org/en/packages/fr.free.nrw.commons/? I do not see any beta-related setting in the F-Droid app, is there a way for F-Droid users get it? :-)

**Comment by licaon-kter** [comment]
F-Droid Client, your app, either manually expand Versions and install or go to upper right menu and enable "Betas".

This will be built in the next cycle.

**Comment by sivaraam** [comment]
> @sivaraam How about pushing a beta release as soon as you can? slightly_smiling_face

Sure. We certainly need to do that. Will initiate the process soon 🙂

**Comment by mnalis** [comment]
Is this still blocking f-droid release? 
I'd love to see latest bugfixed version 4.1.0 published on f-droid

**Comment by licaon-kter** [comment]
@sivaraam if it works once tested we can re-enable the [disabled autoupdate](https://gitlab.com/fdroid/fdroiddata/-/commit/31b605f996a2e9bddd08253ae2ead678d6c127d1)

**Comment by licaon-kter** [comment]
Done :tada: https://gitlab.com/fdroid/fdroiddata/-/commit/32e5bd97aa49be4b8d1228e1ae7413cc81d5ffff
