### ISSUE TITLE
Show where a picture is in use

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#4997]
### What is the user problem or growth opportunity you want to see solved?

A big motivation for users is to see that their uploads are useful, being embedded into Wikipedia articles etc.

### How do you know that this problem exists today? Why is this important?

Important to retain users and encourage them to upload more useful pictures.
Can also teach what kind of pictures are well-received.

### Who will benefit from it?

Wikipedia etc

### Anything else you would like to add?

The website has this feature already:
![Screenshot from 2022-06-20 14-07-32](https://user-images.githubusercontent.com/99590/174529176-645dd13a-2bff-423a-9177-1f4d45151b7c.png)

**Comment by Seylyn** [comment]
Hi, I've created this design for the file usage section. Could you please have a look and give an opinion?
<img width="311" alt="Screenshot 2022-10-30 at 12 57 26 pm" src="https://user-images.githubusercontent.com/79801220/198874267-748fe8ba-25aa-480d-8de6-61133ebfc998.png">

After adding a title of the website and its link:
<img width="310" alt="Screenshot 2022-10-30 at 1 53 53 pm" src="https://user-images.githubusercontent.com/79801220/198874301-8b035fbf-2aa2-4f44-b1ad-8604df5db69a.png">

**Comment by nicolas-raoul** [comment]
@Seylyn It is not about adding, rather it should show as an unmodifiable list.

**Comment by parneet-guraya** [comment]
Hi, I'd like to up this up. I guess this is endpoint I can use? https://www.mediawiki.org/wiki/API:Fileusage

**Comment by nicolas-raoul** [comment]
@parneet-guraya Looks good indeed! 🙂

**Comment by parneet-guraya** [comment]
Great! Working on it.

**Comment by parneet-guraya** [comment]
![Screenshot_2024-10-25-13-31-57-30_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/user-attachments/assets/3d465176-ecf6-4cd0-be8a-8a4027d4adae)

Do we want to show file usages that are on `Commons` only?

**Comment by nicolas-raoul** [comment]
All usages would be best. 🙂

**Comment by parneet-guraya** [comment]
Hi @nicolas-raoul , I have pushed the PR #5957. Before I finish things up I wanted to show you if you want any changes. Also right now we're just showing usages for user's file only, do we also want to show the usages for others too?

Let me know what you think.

**Comment by parneet-guraya** [comment]
Hi @nicolas-raoul , let me know what you think about this? Ignore color or items in the list, I'm just showing you a demo of what it would look like structure wise. Also, open to any suggestions about using diff color or anything else to separate out the expandable headers if needed.

Thanks :)


https://github.com/user-attachments/assets/f0b36784-eef6-4b49-b0a2-775894d6b3b6

**Comment by parneet-guraya** [comment]
BTW, I think list size of 10 is the sweet spot for showing in the details page.

**Comment by nicolas-raoul** [comment]
It looks great! :-)

However, could you make the sections **expended by default**?
Often they will contain only 0 or 1 element, so users will probably get bored of tapping. Expended by default takes less taps.

Feel free to put all usages in the same section if that makes development/maintenance easier. The distinction between Commons and other wikis is not so important. Keeping them separate is fine too. :-)

**Comment by parneet-guraya** [comment]
> However, could you make the sections **expended by default**? Often they will contain only 0 or 1 element, so users will probably get bored of tapping. Expended by default takes less taps.
> 
Makes sense :+1: 

> Feel free to put all usages in the same section if that makes development/maintenance easier. The distinction between Commons and other wikis is not so important. Keeping them separate is fine too. :-)

I saw on the webpage these were two categories shown that's why I also do it. I'm not sure if one of the request is drastically different than the other, just a parameter change, so I think maintenance wouldn't be a problem.
