### ISSUE TITLE
Add Logout 

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#5]
No obvious way to log out

**Comment by misaochan** [comment]
Where do we want the logout button to be? In SettingsActivity or ContributionsActivity?

**Comment by nicolas-raoul** [comment]
I would say settings maybe? I have no strong opinion about this.
The best would be to follow the Android guidelines if they talk about that particular case.
If there are no guidelines, it could be a good idea to ask at http://ux.stackexchange.com

**Comment by misaochan** [comment]
Okay. After logging out, we want to take them back to the login screen, right?

**Comment by nicolas-raoul** [comment]
That sounds sensible indeed.

**Comment by nicolas-raoul** [comment]
I have found how to log out haha.
Launch the Android "Settings" app, go to "Account", tap the "Upload to Commons" item, open the overflow menu, and choose "Remove account".

**Comment by misaochan** [comment]
Oh, okay. :) Are you sure you don't want a logout button anyway? Would be easier to tap 'logout' in the app rather than going through that. But I don't mind either way.

**Comment by nicolas-raoul** [comment]
Accounts seems to be used for this by some popular apps way, so I guess it is OK as is.
It is not like people need to log out everyday anyway.
I let the experts debate the matter here: http://ux.stackexchange.com/questions/85869/where-to-put-logout-in-an-android-app

**Comment by misaochan** [comment]
Ah okay, good point.

**Comment by misaochan** [comment]
Reopening this at the suggestion of folks at the prehackathon.

**Comment by addshore** [comment]
Fixed in https://github.com/commons-app/apps-android-commons/pull/611
