### ISSUE TITLE
v4.0 bug report - category search not working

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#5002]
From an email sent to our google groups forum:

> My app instance is rendered useless because category search is not working. I cannot categorize anything.
> 
> USER_COMMENT=
> APP_VERSION_CODE=1027
> APP_VERSION_NAME=4.0.1
> ANDROID_VERSION=12
> PHONE_MODEL=V2023
> 
> Over two weeks that it doesn't work. Out and in. Turn off the phone and restart. No change.
> 
> I use it in a particular language setting, Basque (previously it worked fine), and I thought, OK, maybe it's that, I'll switch to English...
> 
> Same result. It doesn't work with English settings.
> 
> Category search gets stuck, the rolling icon rolling and rolling, offering no matches
> 
> Even when I type the exact whole category name, the rolling icon doesn't stop, so I cannot cathegorize

**Comment by mds08011** [comment]
I am using `4.0.1~66f8f97d0` and experiencing the same issue since the last update from Google Play Store.

**Comment by sivaraam** [comment]
> I am using `4.0.1~66f8f97d0` and experiencing the same issue since the last update from Google Play Store. No categories are returned, whether the search field is left blank or filled with known category keywords.

I too got 4.0.1 through play store and experience the same behaviour. I'm using the app on a OnePlus Nord running Android 12.

The worst part is I'm not even able to get the specific app version (the one with the commit hash) since the app crashes when clicking on the "More" tab on the home screen navig. :-(

**Comment by misaochan** [comment]
Thanks for the reports, guys! We are working on it. :)

@sivaraam Could you submit a crash report the next time it happens please, so we can get the stack trace?

**Comment by misaochan** [comment]
By the way, @mds08011 @sivaraam do either of you know if the search worked for you in v4.0.0? (Between 28 May and 9 June)

**Comment by mds08011** [comment]
Actually, I was able to fix things by clearing both the storage and cache memory (Settings>Apps>Commons>Storage & Cache).  After clearing both and logging back in, the categories populated.

And I don't think I used the app during version 4.0.0 so I can't speak to that.

**Comment by sivaraam** [comment]
> (Edit: Ah I just saw the report, that seems similar to https://github.com/commons-app/apps-android-commons/issues/4988 which has a PR merged for it, so it should be fixed in the next release.)

Interestingly, the buttons appears to crash only when I'm on mobile data. It works fine when I'm on Wi-Fi. Anyways, good to know there's a fix for the issue. :-)

> Actually, I was able to fix things by clearing both the storage and cache memory (Settings>Apps>Commons>Storage & Cache). After clearing both and logging back in, the categories populated.
> 

I could confirm too that I'm not able to see the issue in a fresh installation.

> And I don't think I used the app during version 4.0.0 so I can't speak to that.

Me too. I'm not really sure if I used that particular version.

**Comment by mnalis** [comment]
- see also https://github.com/commons-app/apps-android-commons/issues/5225; it might be related to be intermittent problem when conversing with server side via API
