### ISSUE TITLE
Allow to edit description 

### ISSUE THREAD

**Issue by matkoniecz** [commons-app/apps-android-commons#5007]
### What is the user problem or growth opportunity you want to see solved?

User may want to add or fix description after upload

### How do you know that this problem exists today? Why is this important?

I tried to modify description as I failed to add or and I see no way to achieve it from within app or even how to get to Wikimedia Commons file page from the app

### Who will benefit from it?

People wishing to modify descriptions of their media

### Anything else you would like to add?

I expected link/edit field in warning about missing description
 
![Screenshot_20220709-185128](https://user-images.githubusercontent.com/899988/178115320-21cdd3d4-5f0c-4212-b722-3e079d5cc6df.png)

**Comment by nicolas-raoul** [comment]
Good news, this is implemented in the next version. Still quite buggy though. 😔
![Screenshot_20220806-164857](https://user-images.githubusercontent.com/99590/183239999-10bc529e-b4a6-4154-bc3c-dfaccd50ddb1.png)
