### ISSUE TITLE
Allow to mark objects as not existing anymore and as a defunct

### ISSUE THREAD

**Issue by matkoniecz** [commons-app/apps-android-commons#5009]
### What is the user problem or growth opportunity you want to see solved?

I am not interested in taking photos of not existing places - and I am definitely not interested in getting notifications about nearby places that turns out to be not existing

### How do you know that this problem exists today? Why is this important?

I just run into it

![Screenshot_20220709-190151](https://user-images.githubusercontent.com/899988/178115762-077d0e45-45dd-4f5a-b33c-206f7b7a969f.png)

I initially thought  it is about settlement without a photo - it turns to be about badly named entry about removed railway station

### Who will benefit from it?

People using app and using Wikidata data

### Anything else you would like to add?

Marking multiple Wikidata entries as duplicates of each other is an overkill I guess

**Comment by nicolas-raoul** [comment]
Good idea! I think this is similar to https://github.com/commons-app/apps-android-commons/issues/2425, which Vanshika has started to implement, so would you mind commenting there? 🙂
