### ISSUE TITLE
Show an alert when no Nearby result is found

### ISSUE THREAD

**Issue by whym** [commons-app/apps-android-commons#502]
Nearby may be empty when nothing exists around or data retrieval fails for network errors. Currently it results in an empty Nearby screen, which may confuse the user. A simple alert (maybe a Toast) saying something like "No results - please try again later" would solve this.

**Comment by tobias47n9e** [comment]
The screen in general has very little feedback for the user if the GPS signal is available and with what accuracy. It would be nice if it could show something that tells the user that her location has been found and with what accuracy. Or a warning if the location is unavailable or the accuracy is very bad (for example when the standard deviation exceeds 1km)
