### ISSUE TITLE
F-Droid version very out of date

### ISSUE THREAD

**Issue by endim8** [commons-app/apps-android-commons#5022]
### Feedback

Why is the F-Droid version so out of date? the last build was in 2017.
This really needs to be updated.

### Commons app version

2.6.0 (fdroid)

**Comment by misaochan** [comment]
I'm not really sure why - usually F-Droid automatically takes from our releases, and we haven't changed our system for those since 2017. https://github.com/commons-app/apps-android-commons/releases Is there a way for us to ask them about this?

**Comment by endim8** [comment]
ah, looking at https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/fr.free.nrw.commons.yml, it seems that all newer versions are disabled due to https://github.com/commons-app/apps-android-commons/issues/4994

**Comment by misaochan** [comment]
Noted, thanks. If anyone is interested in working on #4994 , please let us know!

**Comment by sivaraam** [comment]
Closing this now as there seems nothing left to be done here. #4994 seems to cover the actionable part to me. Feel free to correct me in case I got something wrong.
