### ISSUE TITLE
Google Play Store UGC issue. App update rejected - should we temporarily remove Explore?

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#5024]
Upon my attempt to publish v4.0.2, I received this email from the Google Play Store. Basically, due to a UGC policy change by Google, **all updates to our app, including the latest one that I submitted, will be rejected** until we make the changes required. I have attached a snippet of the email and the screenshot that they sent me below, but long story short, the issue is caused by Explore showing Commons photos. And unfortunately as Wikimedia has the policy of "we do not censor", Commons photos can potentially contain objectionable content. At least, this is how I understood it, perhaps @nicolas-raoul can confirm.

This is a bit of an impasse. It can be fixed by, as I understand, creating a system for users to report/flag "violations" and to block photos from specific users. The problems here are firstly that I don't think Wikimedia Commons's policy of what constitutes a "violation" correlates with Google's policy. And secondly, even if it were possible, we really have no gas in the tank left to implement this rather substantial feature - our grant funds have long run out, we have all had to fix many issues that weren't covered by the grant, and I really cannot ask any more of @neslihanturan and @madhurgupta10 .

So the only real option here, as I see it, is to temporarily remove Explore entirely from the app. This PR can be reversed when either the policy changes, or someone volunteers to implement these features (and Google approves the change). "Explore" is a huge feature that is very popular with users, and it pains me to make this suggestion, but I don't see any other way out.

Thoughts, @nicolas-raoul @whym @neslihanturan @madhurgupta10 ?

> Issue with your app
> Your app contains or features User Generated Content (UGC) that isn’t compliant with the [User Generated Content](https://notifications.google.com/g/p/APNL1TjAoqOxrwMcfyx6gJADXCkNxVUtsjtMJdJY0mrzEQyyan59ld87cDb3ajk_YvhpKodZFGxoQz-EjnnzBo81ZbN4U5Ck3uxFuou0gOYScRlPM7NbfyE0bCCclSFro3VFvhhSnSlOr9Q) policy.
>  
> Issue details
> 
> We found an issue in the following area(s):
> In-app experience: Please see attached screenshot fr.free.nrw.commons-InAppExperience-76.png
> 
> Please note that user-generated content is content that users contribute to an app, and which is visible to or accessible by at least a subset of the app's users. This includes, but is not limited to user profiles, comments, media, posts, etc.
> 
> As such, our guidelines require that apps containing UGC content, whether or not it is the app’s primary purpose, MUST have the following features/functionalities:
> A user-friendly, in-app system for reporting objectionable UGC and taking action against that UGC where appropriate. This includes:
> Providing an in-app function that allows users to report/flag other users for potential violations
> Providing an in-app function that allows users to report/flag potential violating content
> Providing an in-app function that allows users to remove/block abusive users
> For more information, you can review our [e-learning course on UGC](https://notifications.google.com/g/p/APNL1ThFZ_ibfn73ctib822OYoXnMmlw9Ww0Ew8zN_ktGlBLAJrusf8d2pmersfbhNwK71UdgkPvgaEwek89jWO0Bo4BhcOMAuDNo3TmOlT84oMcRxdmCOM8xADV0TJREDwEK6Fe75YFnQ) before submission.
> 
> During our review of your app, we found objectionable content and/or potentially missing UGC features. We kindly ask that you re-check your app and make sure that ALL these functionalities are in place for your users. We also ask that you review the [User Generated Content](https://notifications.google.com/g/p/APNL1ThFZ_ibfn73ctib822OYoXnMmlw9Ww0Ew8zN_ktGlBLAJrusf8d2pmersfbhNwK71UdgkPvgaEwek89jWO0Bo4BhcOMAuDNo3TmOlT84oMcRxdmCOM8xADV0TJREDwEK6Fe75YFnQ) policy to ensure your app features ALL the requirements outlined in the help article.
> 
> If your app is missing one or more of the UGC features, make sure you add them to your app before resubmission.
> 
> We recommend that all required functionalities are labeled and/or designed in a way that is clear for the users to avoid confusion. You can self-resolve this issue by ensuring all required UGC features are properly implemented. If your issue has already been resolved, OR if you have updated your app on Play Console and submitted them for review, no further action is required from you and you do not need to reach out to us.
> 
> If you’ve reviewed the UGC policy and feel our decision may have been in error because all the UGC required features in your app actually exist and are reasonably identifiable to your users, please reach out to our [policy support team](https://notifications.google.com/g/p/APNL1TjHyk6s3Vu7l43XDPtoTGdmUuNTrLnK4g3TNFIKSNDozn2Vr-u8QpDuV2uE9M7_3j4DyOwvNK-_RAaU1MqVJCjZy6X3lgTQzijMHOrSVrPuh0ZzHWJ7yfRzq4_QyyIFVqG678vnG8xaFM9nHziIIOg9lQ).

![fr free nrw commons-InAppExperience-76](https://user-images.githubusercontent.com/3611199/182823033-94eb9611-70e1-418b-a790-e251df2fcae5.png)

**Comment by madhurgupta10** [comment]
@misaochan If I understood correctly they require us to add a report option in the three-dot menu which can be used to report the 3 mentioned violations. I think if we simply show a popup with these three violations and generate an email template where the user can send an email to Google Group, it should be acceptable to Google I guess.

Even for YouTube, if someone wants to report any inappropriate content they simply notify the authorities using the dialog and the action is taken by manually reviewing the content.

Also, it would be fairly easy to add that dialog than to set up any complicated report mechanism.

**Comment by misaochan** [comment]
Hmm, interesting. I was thinking about the Commons review/report structure when I was considering the problem, but if just providing an option to email our mailing list works, then that could be an option. How would this work with the requirement to "remove/block abusive users"?

**Comment by madhurgupta10** [comment]
```
How would this work with the requirement to "remove/block abusive users"?
```

Not sure about that, if Google wants us to implement a block feature in that app then it would take a lot of time to develop.

Also, I notice that even in YouTube app if you click on block user it will only restrict that user from commenting on your videos nothing else so I am confused what Google want us to implement here as we don't have any direct user interaction within the app (As far as I can remember)

**Comment by misaochan** [comment]
Yes, exactly. It seems to be a change in Google's own policy, as we have had the Explore feature for a long time and this is the first time I received this email from them. I am open to trying just an email link for "Report inappropriate content", but it can delay the process (and consequently the ability for us to complete this grant, AND the date bug fix that is causing a lot of ire in the Commons community). It seems like removing Explore would be a more certain fix, but it's really up to you all.

**Comment by madhurgupta10** [comment]
@misaochan I can try putting up a PR with email option by today or tomorrow and we can see if Google approves it or not.

**Comment by misaochan** [comment]
That would be fantastic, thank you! There is also a Data Safety form requested by Google that I need to work out with @nicolas-raoul , but AFAIK that should not block releases until 22 Aug.

**Comment by whym** [comment]
If we are to let the user report things, I think it might make sense for us to implement a (probably app-embedded) list of banned categories. I refrain from linking but Commons does have dedicated categories for genital images that we might want to ban, for instance.

Illegal images (like child porn) can be directly reported to  legal-reports@wikimedia.org. (See also https://commons.wikimedia.org/wiki/Commons:Contact_us/Problems/en .) Merely objectionable images would be out of scope for them, though.

**Comment by nicolas-raoul** [comment]
I wonder whether the Wikipedia app has received this. Arguably a picture upload app is seen as more prone to abuse.

The Help page says "in-app" but I guess an in-app button that launches an email app is acceptable.
The policy does not say that we have to take down all content that gets reported.
It is not clear whether reporting users is enough, or whether blocking users (making them and their content invisible to me) is required too.

I don't expect a lot of violation reports, so we can probably handle those manually, it will be easier than implementing in the UI every possible violation reason.

I am not against removing Explore temporarily (the app is mostly about upload), but adding the report feature might be faster? (because Explore is accessible from several places)

User pages accessed from the leaderboard need a report button too.

How about this email template?
```
Title: Report a violation
To: commons-app-android-private@googlegroups.com 

Image or user that you want to report : https://commons.wikimedia.org/wiki/File:Toranomon_Hills_Station_Tower,_under_construction.jpg

Violation reason:
-----------------------
(please write reason here)
-----------------------

Thank you for your report! Our team will investigate as soon as possible.
Please note that images also have `Nominate for deletion` button.
```
The image URL is an example,it would be filled by the app automatically. For a user it could be just the username.

**Comment by whym** [comment]
> I wonder whether the Wikipedia app has received this.

It looks as though the Wikipedia app hasn't had to deal with the same issue, at least in the past. The alpha version updated today shows random images from Commons for editing tasks, without something like a report button. The (i) link is for [the feature's help page](https://www.mediawiki.org/wiki/Wikimedia_Apps/Suggested_edits), not for report/moderation.
![Screenshot_20220804_222931](https://user-images.githubusercontent.com/10674/182859316-da1f4c75-4e66-4844-b01a-bd3832461f11.png)

**Comment by misaochan** [comment]
TODO: https://github.com/commons-app/apps-android-commons/pull/5025#issuecomment-1206026553

**Comment by misaochan** [comment]
Thanks everyone, I have released v4.0.3 with these changes. Fingers crossed...

**Comment by nicolas-raoul** [comment]
Another issue came up, which I believe can be fixed in Play console settings?
It seems to mean that the UGC problem is considered fixed. :-)

**Comment by misaochan** [comment]
Ah, I got the Data Safety Form email an hour prior to the UGC email the last time, so I wouldn't necessarily assume that. :) Still, it would be great if you and I could work on the Data issue at the same time. I will message you.

**Comment by misaochan** [comment]
Yes, it is now published. Thank you all - I will make a new issue for https://github.com/commons-app/apps-android-commons/pull/5025#issuecomment-1206026553 .
