### ISSUE TITLE
"Use previous title/description" should be disabled for first upload

### ISSUE THREAD

**Issue by whym** [commons-app/apps-android-commons#503]
Showing the "Use previous title/description" button to a completely new user can be confusing.

I think it should be made invisible or a gray button that doesn't work, before the first upload is made.

**Comment by whym** [comment]
Another approach: when the previous value is empty and/or the current value is non-empty, warn the user about it. (e.g. "Are you sure? This will erase the title you have entered.")

**Comment by Vanethos** [comment]
Ha, still trying to get my head around git, sorry!

I have tried to solve this issue with  #716
