### ISSUE TITLE
[Bug]: Category selection not working

### ISSUE THREAD

**Issue by addshore** [commons-app/apps-android-commons#5036]
### Summary

Currently while using the app, category selection does not work at all. The spinner just keeps on spinning.
When entering text to start a search the spinner also just spins and no suggestions happen.
This results in me not adding categories to my uploads.

### Steps to reproduce

Upload image
Get to category selection screen
Wait

### Expected behaviour

Suggested categories would appear and the spinner would stop spinning

### Actual behaviour

Spinner spins for ever

### Device name

Motorola G9 plus

### Android version

Android 11

### Commons app version

4.0.3~23c474b06

### Screen-shots

![Screenshot_20220823-113916](https://user-images.githubusercontent.com/3308769/186148275-f1ceaf39-ca4a-42a5-a51e-f355d52f6c8a.png)

**Comment by addshore** [comment]
Fixed after logging out and in again

**Comment by mnalis** [comment]
- see also https://github.com/commons-app/apps-android-commons/issues/5225; it seems to be intermittent problem when conversing with server side via API
