### ISSUE TITLE
[Bug]: Upload says it fails, despite uploading and appearing in the list

### ISSUE THREAD

**Issue by addshore** [commons-app/apps-android-commons#5037]
### Summary

Any file I upload via the commons app will currently say that it has failed.
However the image will be uploaded and edits after the upload will also happen.

### Steps to reproduce

Upload an image
Enter data about the image
Wait for the upload to run

### Expected behaviour

Only 1 entry in the list for the image, and it shows that the upload has succeeded.

### Actual behaviour

Duplicate entry in the list. One of which says upload failed

### Device name

Motorola G9 plus

### Android version

Android 11

### Commons app version

4.0.3~23c474b06

### Screen-shots

![Screenshot_20220823-153642](https://user-images.githubusercontent.com/3308769/186187115-c0f5d78f-f800-42aa-ad94-4d53512f76f6.png)

**Comment by nicolas-raoul** [comment]
That often happens to me as well, however I have not found a 100% sure way to reproduce the problem.
Does anyone know a 100% sure way to reproduce the problem? That would help developers.

**Comment by OpenGreenStreet** [comment]
I often feel that way too (not always). I suspect the following: if file name and description are identical, it comes to the problem described
see here: [https://commons.wikimedia.org/wiki/File:20221014_xl_0705-Commons-App-Error.png](url)

**Comment by nicolas-raoul** [comment]
This issue was fixed and a release is available. Is it still happening? If yes, please reopen, thanks! :-)
