### ISSUE TITLE
[Bug]: Uploading photos from Custom Selector drops coordinates

### ISSUE THREAD

**Issue by trolleway** [commons-app/apps-android-commons#5041]
### Summary

When upload photos from 'Custom Selector' window, geographic coordinates are not read from photo.

### Steps to reproduce

1. Take a photo on street with GPS coordinates
2. Open 'Custom Selector', select photo, process to upload.

### Expected behaviour

In upload form, clicking on Coordinates button should show coordinates of photo

### Actual behaviour

In upload form Coordinates button show map on defaults or last set location, not from photo exif.
The coordinates showed good, if call upload photo from file manager app

### Device name

Samsung S20FE

### Android version

Android 11

### Commons app version

4.0.5

**Comment by nicolas-raoul** [comment]
Thanks for your report!
It is the same issue as #5015 if I understand correctly?
