### ISSUE TITLE
Add a direct "Copy Link" button next to Share button 

### ISSUE THREAD

**Issue by psyguy** [commons-app/apps-android-commons#5042]
### What is the user problem or growth opportunity you want to see solved?

Add a "Copy Link" button to the menu above articles to allow directly copying the link to the clipboard without going through Android's native Share menu.

### How do you know that this problem exists today? Why is this important?

This UX improvement makes sharing less effortful by reducing the number of taps (from 3 to 2) and preventing 1 to 3 seconds of delay on older phones to open Android's native Share menu.

### Who will benefit from it?

Many users, like me, who primarily need the link to the article to paste it in another app where in they're half way through writing a text or message.

### Anything else you would like to add?

Twitter has implemented in in it's Android app a long while ago. This improvement to the UX has made it easier and faster to copy links, taking only two (instead of three) taps clicking on Share button, and select:

![Screenshot_20220901-094547-160](https://user-images.githubusercontent.com/8527082/187862396-3544408d-61ac-4dda-b63f-4a2ba9061133.png)

**Comment by 2022H1030042G** [comment]
Hi @psyguy, Is the issue available, I would like to work on it.

**Comment by psyguy** [comment]
Hi @2022H1030042G, I'm not sure what you mean by the issue being available. It indeed has not been solved yet.

I found a possible implementation to this issue which would not require changing the UI (in case people are used to it), and would allow linking to _specific parts_ of the article (which is also really useful, especially when referencing to a subtopic of the entry in online discussions):

A link button (with an icon like 🔗) can be added the end of the article title and each (sub)header, which would copy the link to (the specific section in) the article into the clipboard if pressed. I mean something like this:

![image](https://user-images.githubusercontent.com/8527082/195572712-cdacfc9d-6f77-414f-abac-814bc0edf013.png)

Or this (🔗 before the title):

![image](https://user-images.githubusercontent.com/8527082/195572788-b00aed73-a5f9-49cc-8844-c0a59c3f43f5.png)

It would not also require changing the "legacy" UI, and is really convenient from a UX perspective (since it would only require **only one tap**).

**Comment by 2022H1030042G** [comment]
What I meant was if no one has been assigned to this issue or it has been not resolved, I would like to work on it

**Comment by 2022H1030042G** [comment]
Can you give some idea on how do I start working on it? And where do I have to make the changes (in which file)?

**Comment by psyguy** [comment]
I honestly have no clue; I'm afraid I'm basically illiterate in this regard (I know R and partly LaTeX). I was hoping someone with the knowledge of implementing it would pick up the issue.

**Comment by Justweng** [comment]
Hi, I also try to solve the problem.

**Comment by Justweng** [comment]
![Screenshot_20221018_175026](https://user-images.githubusercontent.com/68474038/196429190-1839413b-27bd-48d6-9427-5e8ba44e0547.png)
I've added a copy button next to share button, does that meet your requirements? @psyguy

**Comment by Justweng** [comment]
And after clicking it, there will be a toast.
<img width="344" alt="image" src="https://user-images.githubusercontent.com/68474038/196429647-c3ec0a62-390b-4639-8af2-716ce99cb32d.png">

**Comment by nicolas-raoul** [comment]
Actually, I am wondering whether this is still needed?
On a recent version of Android, it is already easy to copy the link after tapping the share button:
![Screenshot_20230407-100921~2](https://user-images.githubusercontent.com/99590/230520668-32791441-368d-4105-b6ab-75cff599282b.png)

**Comment by shankarpriyank** [comment]
I think this copy option is only available on Android 13 for now, and my guess is that a very low percentage of the users are having Android 13 devices.

**Comment by shankarpriyank** [comment]
Can I take this up @nicolas-raoul ?

**Comment by nicolas-raoul** [comment]
It is true that Android 13 is less than 20% of the users now, but this number will keep growing and it is not a vital enhancement, I think that we have many more important things to work on.

**Comment by neeldoshii** [comment]
Hello 👋
If no one else is planning to work on this, I’d be happy to take it on. 😊

My plan. 
1. Migrate Media Module to kotlin
2. Implement ShareSheet (https://developer.android.com/training/sharing/send) & Implement Clipboard over there.
3. > A link button (with an icon like 🔗) can be added the end of the article title and each (sub)header, which would copy the link to (the specific section in) the article into the clipboard if pressed. I mean something like this:

Adding a clipboard icon after the title ends and then implementing [ClipboardManager](https://developer.android.com/reference/android/content/ClipboardManager) to copy the link to the clipboard for ease in copying links.
