### ISSUE TITLE
[Bug]: Wiki Loves Monuments photos upload with 2021 template instead of 2022

### ISSUE THREAD

**Issue by trolleway** [commons-app/apps-android-commons#5043]
### Summary

While uploading photo to Wiki Loves Monuments via appilcation, a old template inserted
```
{{Wiki Loves Monuments 2021|1= ru}}
```
instead of
```
{{Wiki Loves Monuments 2022|1= ru}}
```

### Steps to reproduce

1. Take a photo of some monument
2. Open app, locate monument on map, upload photo

### Expected behaviour

```
{{Wiki Loves Monuments 2022|1= ru}}
``` 
should added

### Actual behaviour

```
{{Wiki Loves Monuments 2021|1= ru}}
```
template added

### Device name

Samsung S20 FE

### Android version

Android 11

### Commons app version

4.0.5

**Comment by bodhisattwawiki** [comment]
same for India

**Comment by whym** [comment]
Currently the year is hard-coded, so the 2021→2022 changes would be the simplest fix.

I would say we should set the current year (dynamically) for a long term fix, though. Maybe a template substitution, to allow WLM people to control it?

**Comment by nicolas-raoul** [comment]
Dynamic (based on first day of the campaign) sounds good enough to me, rather than introducing template complexity and possible validation errors.

**Comment by whym** [comment]
@bodhisattwawiki @trolleway While we are at it, do you know which countries participate in WLM 2022, and which countries are happy with having the app enabled for them? There is a list of countries that the feature is enabled for written in the source code.

https://github.com/commons-app/apps-android-commons/blob/e135fea20d216a771df83b05fd26bf8f7f3fb202/app/src/main/java/fr/free/nrw/commons/upload/mediaDetails/UploadMediaPresenter.java#L59

I think this was based on requests done last year. https://commons.wikimedia.org/wiki/Commons:Mobile_app/WLM_release#Requests
