### ISSUE TITLE
Small-scale code improvement in ImageFileLoader.kt

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#5046]
In [ImageFileLoader.kt](https://github.com/commons-app/apps-android-commons/blob/9c27f8510d8ea0d05e089f46556ada106456ac8e/app/src/main/java/fr/free/nrw/commons/customselector/ui/selector/ImageFileLoader.kt#L84), merge into single condition: `file != null && file.exists`

**Comment by bosankus** [comment]
Hi @nicolas-raoul I think this issue is solved through #5055 ? Is it correct ?

**Comment by nicolas-raoul** [comment]
@bosankus You are right, thanks for spotting this! I will close it now.
