### ISSUE TITLE
[Bug]: user name / IP address blocked while signing up

### ISSUE THREAD

**Issue by Lakshay-Pruthi** [commons-app/apps-android-commons#5048]
### Summary

I was signing up on the app and was typing my user name. This pops up : ( see the image attached )

### Steps to reproduce

1. Open the app
2. Go to sign up page
3. Type any user name

### Expected behaviour

Tell me if username available or not

### Actual behaviour

Telling if the username is not available but giving this popup when you enter a different username

### Device name

Samsung m21 2021

### Android version

Android 12 ( stock version )

### Commons app version

4.0.5

### Screen-shots

![Screenshot_20220910-140507_Commons 1](https://user-images.githubusercontent.com/91469717/189476154-e33a49c4-1c57-41f3-a3bf-9eabca06b04e.jpg)

**Comment by Lakshay-Pruthi** [comment]
I'm getting the same issue while registering for MediaWiki account on the website. I am not able to report this to MediaWiki repo as it requires a Mediawiki account. 
![image](https://user-images.githubusercontent.com/91469717/189516065-a9d20d41-09af-4109-9fac-cd8867ddfbec.png)

**Comment by nicolas-raoul** [comment]
Unfortunately, if the website does not work, the app will not either.
I believe the links in "You can contact" are usable without logging in.
