### ISSUE TITLE
Wikidata : display wikidata elements that need picture

### ISSUE THREAD

**Issue by JLZIMMERMANN** [commons-app/apps-android-commons#5051]
### What is the user problem or growth opportunity you want to see solved?

Wikidata is growing more and more and some pictures would be welcome to help understand each one. 

### How do you know that this problem exists today? Why is this important?

Any element that could have coordinates could be illustrated by pictures. A nomade app like commons would help a lot. 

### Who will benefit from it?

Anyone that like to walk and create pictures collections for everyone. 

### Anything else you would like to add?

A gamification and displaying major elements would be welcome. Then the app could write in exit the URI of wikidata Q.....

**Comment by nicolas-raoul** [comment]
Good news, this is already implemented. Please see the "Nearby" tab of the app. :-)
Thanks for using the app!
