### ISSUE TITLE
Use coordinates2country instead of Geocoder in UploadMediaPresenter

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#5056]
`UploadMediaPresenter.java` uses Geocoder in the `reverseGeoCode` method.
This usage has several problems:
- Requires a geocoding backend such as Google Play Services, which is not always available and reliable ([example](https://en.wikipedia.org/wiki//e/_(operating_system))).
- [Apparently](https://stackoverflow.com/questions/16258898/does-android-geocoder-work-only-with-internet-connection) uses the network.
- Possibly a Wikimedia privacy violation, as Geocoder sends the user's picture location to a third-party service.

We already use a [small offline geocoding library](https://github.com/coordinates2country/coordinates2country-android), it could be used for this too. We only need the country, not full address.

**Comment by nicolas-raoul** [comment]
@DKolibar Yes, it is yours, thanks!

**Comment by DKolibar** [comment]
@nicolas-raoul I created PR #5093 for this issue. I hope my implementation is as expected.
