### ISSUE TITLE
[Bug]: Uploads fail on my device all the time.

### ISSUE THREAD

**Issue by satdeepgill** [commons-app/apps-android-commons#5062]
### Summary

Uploads fail on my mobile device all the time.

### Steps to reproduce

I have shared the log file via email

I have tried uploading different images.

### Expected behaviour

Upload the file

### Actual behaviour

Fails to upload. 

### Device name

One Plus Nord

### Android version

Android 11

### Commons app version

4.0.5

### Screen-shots

![Screenshot_20221002-094627(1)](https://user-images.githubusercontent.com/10414529/193444577-b36eb126-3cb6-40fe-a375-5720773bac8c.jpg)

**Comment by tripathisharad** [comment]
Hi @satdeepgill can you please assign me this project I can try to solve the problem.

**Comment by nicolas-raoul** [comment]
@tripathisharad Sorry for the delay, feel free to work on it and ask Satdeep for details. Thanks!

**Comment by nicolas-raoul** [comment]
This issue was fixed and a release is available. Is it still happening? If yes, please reopen, thanks! :-)
