### ISSUE TITLE
Tell the user that this app does not support 2FA yet

### ISSUE THREAD

**Issue by strainu** [commons-app/apps-android-commons#507]
When trying to login with an account that has two factor authentication enabled, authentication fails with no explanation except "authentication failed". 

Until 2FA is actually implemented, at least a more explicit error message could be shown.

**Comment by whym** [comment]
The 2FA issue was reported at https://github.com/commons-app/apps-android-commons/issues/328.

But I think the idea of showing a more explicit error message should have its own issue. It would be easier and faster to implement, and helpful while we work on the actual support of 2FA.

**Comment by whym** [comment]
Perhaps when the error code is "UI", can we say something like "your account requires a login method not yet supported by this app"?
 
https://www.mediawiki.org/wiki/API:Login#The_clientlogin_action says
> If you received UI, present the new fields to the user and obtain their submission.
