### ISSUE TITLE
Numbers cropped in Leaderboard

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#5074]
The first digit is not entirely visible when numbers have 4+ digits:
![Screenshot_20221016-204532~2](https://user-images.githubusercontent.com/99590/196039008-1f6bf8b1-dd05-4dd0-9492-9894c5242e8a.png)

**Comment by Lz-01** [comment]
please assgin this issue to me

**Comment by babelstone** [comment]
Also, could you change the font colour to black and increase the font size, as the numbers are really hard to read at such a small size and in that light orange colour.

**Comment by RitikaPahwa4444** [comment]
Any progress on this issue? I would like to give it a try if it is still available.

**Comment by nicolas-raoul** [comment]
No news from Lz-01, you can take it @RitikaPahwa4444 thanks! The problem still exists:
![Screenshot_20230211-115937](https://user-images.githubusercontent.com/99590/218235653-cdfa0d98-1cd0-43b2-83ef-de8cccec3a20.png)
