### ISSUE TITLE
Nearby: More space for label?

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#508]
Maybe two lines would be more readable on most screens?
![screenshot_20170415-214957](https://cloud.githubusercontent.com/assets/99590/25064716/5995de82-223b-11e7-882e-4d0fc756b084.png)

**Comment by whym** [comment]
Should it remain one line when the particular label is short enough to fit in? Otherwise, having one empty line between the label and the type may not be optimal.

**Comment by nicolas-raoul** [comment]
@whym: You are right!
