### ISSUE TITLE
Item so dark they look unselectable

### ISSUE THREAD

**Issue by jidanni** [commons-app/apps-android-commons#5082]
Would any user expect that any other items except for the very leftmost, Contributions, would still be clickable, being so dark?

![Screenshot_20221021-204134_Commons.jpg](https://user-images.githubusercontent.com/1230959/197311254-fdd1b0be-2e0d-4d9c-b633-6e38aa1c5b38.jpg)

Such darkness tells the user "never mind tapping me because I am not functioning on the current page."

I have circled the trouble area in red.

Samsung Galaxy Android 12
4.0.5~f03b7dd8d

**Comment by nicolas-raoul** [comment]
I personally don't think it is misleading. I close meanwhile, but if anyone has a link to official guidelines about this (in dark mode), please let us know, would be happy to correct if we are against guidelines about this! :-)

**Comment by jidanni** [comment]
Here Restaurants is dark, meaning if we click it, we are not going to get Restaurants.
![20221026T081027](https://user-images.githubusercontent.com/1230959/198035032-bb7493de-5594-47bc-9a6d-d3b508695a60.jpg)

**Comment by jidanni** [comment]
Here we see various ways to display valid buttons to press on, with no need to darken any,
![20221026T080832](https://user-images.githubusercontent.com/1230959/198035722-b36daebb-43f7-4d46-9b55-dad8df3c011e.jpg)

**Comment by jidanni** [comment]
Here (mbasic.facebook.com again) dark is used, but choice names are then white,
![20221026T081850](https://user-images.githubusercontent.com/1230959/198036630-625d7e8a-82ef-44d9-a165-ea15f6e1de6f.jpg)

**Comment by jidanni** [comment]
Here current item is indicated, with no need to degrade other choices,
![20221026T080650](https://user-images.githubusercontent.com/1230959/198036882-8d1f990a-5331-4eef-9419-ff6ed1762237.jpg)
