### ISSUE TITLE
Tapping on GitHub icon results in "No web browser found to open URL" on Samsung Galaxy with Android 12

### ISSUE THREAD

**Issue by jidanni** [commons-app/apps-android-commons#5084]
Here on the About page we see a GitHub Issue link in blue, and a GitHub cat icon. If we touch the blue Issue link we get properly delivered to where we can write bugs. However if we touch the GitHub icon we get the error message you see at the bottom of this page, "No web browser found to open URL":
![Screenshot_20221021-205451_Commons.jpg](https://user-images.githubusercontent.com/1230959/197311475-d2968adf-0b14-4794-b204-2e3c3ba2bbb9.jpg)
Which is too bad because on our cell phone we not only have many browsers, but we even have the GitHub app itself.

**Comment by nicolas-raoul** [comment]
Interesting, it opens a web browser for me.
Anyone able to reproduce the issue?

**Comment by jidanni** [comment]
Hmm, I encountered the bug on Samsung Galaxy with Android 12. With Asus and Android 8 it opens it nicely  in the GitHub app,
![Screenshot_20221025-201400.jpg](https://user-images.githubusercontent.com/1230959/197911788-6f9b4f10-a49c-4417-8890-ff4d4ec33e31.jpg)

**Comment by nathanmeade** [comment]
@jidanni Which Samsung Galaxy device are you using when you observe this issue?

**Comment by jidanni** [comment]
Device Name : Galaxy A13 5G

**Comment by Discostu36** [comment]
I can reproduce on Fairphone 4 with Android 11. Default browser is Fennec.

**Comment by nicolas-raoul** [comment]
@jidanni Does the problem still happen on your Samsung Galaxy if you remove the GitHub app? Thanks!

**Comment by Discostu36** [comment]
The problem doesn't appear after I have uninstalled the GitHub app.

**Comment by nicolas-raoul** [comment]
Thanks @Discostu36!
I wonder whether it should be considered a bug of the GitHub app, and whether we can do something to work around it. If anyone finds similar bug reports not related to our app (ideally a bug report in the issue tracker of the GitHub app), please post here :-)

**Comment by Discostu36** [comment]
I have never encountered the problem when opening GitHub links in other apps.

**Comment by jidanni** [comment]
(Glad you answered it for me, because I don't want to uninstall any apps.)

**Comment by Discostu36** [comment]
Does anyone have Facebook installed an can check what happens when pressing the Facebook button?

**Comment by EduardoMtz1** [comment]
I have Facebook installed and it opens the link on the app. I also reproduced the problem with the Github application on a Poco X3 with Android 11.

**Comment by EduardoMtz1** [comment]
I think I know how to solve this issue, can I work on it?

**Comment by nicolas-raoul** [comment]
@EduardoMtz1 It is yours, thanks!

**Comment by jidanni** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=1412425 maybe related.
