### ISSUE TITLE
Say if Category spinner is waiting for input or not

### ISSUE THREAD

**Issue by jidanni** [commons-app/apps-android-commons#5087]
Here we see an info message that is seen when pressing the i-circle button. It could perhaps also mention the function of the spinner there on the right.

- is it spinning waiting for us to type things in?
- is it spinning, meaning we should wait for it to finish, before we start typing things in?

These are things the user needs to know.
![Screenshot_20221022-105510.jpg](https://user-images.githubusercontent.com/1230959/197349162-4c085c59-14a5-42eb-82a8-c82cd135f025.jpg)

**Comment by nicolas-raoul** [comment]
Spinning means a result should appear soon. It is a common UI element, I don't think it needs explaining.
Anyone feel free to post official UI guidance regarding this.

**Comment by jidanni** [comment]
(All I know is whenever I got to this page, and before I typed anything in, the spinner was spinning, and I just had to wait forever and nothing ever changed it just kept spinning. So I always gave up and started typing thins in. I found it worked much better once I had typed something in. So I'm saying that I-Circle button should explain exactly what is supposed to happen.)

**Comment by mnalis** [comment]
- Part of the confusion might've been induced by Category selection not working properly, i.e. spinner spinning indefinitely instead of showing category results - https://github.com/commons-app/apps-android-commons/issues/5225
