### ISSUE TITLE
[Bug]: App crashes and won't open again after signing in

### ISSUE THREAD

**Issue by Animyos** [commons-app/apps-android-commons#5088]
### Summary

Downloaded the app (version 2.6.0) from the F-Droid store. Opened the app and logged into the app with my Commons account. App crashes and won't open again, even after closing it repeatedly. The only thing that *does* help is uninstalling the app and re-installing it again, but even after that the app only works until you log in.

### Steps to reproduce

1. Download version 2.6.0 from the F-Droid store
2. Open the app and log in with a Commons account

### Expected behaviour

The app should work / not crash / be able to be opened again

### Actual behaviour

The app crashes / can't be opened

### Device name

Nokia (HMD) 3.4

### Android version

Android 12 (stock version, but with Lawnchair launcher installed and in use)

### Commons app version

2.6.0 (newest one)

### Screen-shots

![Screenshot_20221023-010358](https://user-images.githubusercontent.com/82672160/197365639-e05ed22c-cf78-4b0f-97cc-6e1af7ae8f78.png)
Screenshot's text translates roughly to "Commons is being closed repeatedly.", buttons are "Warren" ("wait") and "App schließen" ("close app")

### Would you like to work on the issue?

Prefer not

**Comment by Animyos** [comment]
I've got something wrong, the buttons on the screenshot are "App-Informationen" ("app information") and "App schließen" ("close app")

**Comment by nicolas-raoul** [comment]
Sorry for the inconvenience!
Would you mind uninstalling and reinstalling the app?

**Comment by sivaraam** [comment]
> Download version 2.6.0 from the F-Droid store

@Animyos Sorry about that but the version of the app in F-droid is pretty old. [side note: It's so old it only targetted Android 7.1. It's a bit surprising the app even shows you the login screen on Android 12!] The reason the F-droid version if pretty old is due to #4994 

Would you able to download and use the [latest version (v4.0.5) of the app from play store](https://play.google.com/store/apps/details?id=fr.free.nrw.commons)?

**Comment by Animyos** [comment]
@sivaraam Yes, I’ve already done that and can confirm that the issue doesn’t happen with the newest version from PlayStore. Thanks for replying!
