### ISSUE TITLE
[Bug]: Google image locations cannot be recognized

### ISSUE THREAD

**Issue by u7253519** [commons-app/apps-android-commons#5094]
### Summary

When locations are added through Google Gallery but not through camera taken, it cannot be recognized 

### Steps to reproduce

1.  Open Google Gallery and choose an image with no location
2.  Click top right navigation bar
3.  Add location for the image
4.  Open the Commons app and upload the image through any way

### Expected behaviour

The uploaded image should have a location already

### Actual behaviour

The uploaded image doesn`t have a location

### Device name

OPPO A53s

### Android version

Android 11

### Commons app version

4.0.3

**Comment by nicolas-raoul** [comment]
Do you mean Google Photos?

Would you mind adding a screenshot of step 3 "Add location for the image"? I will prevent misunderstandings.

Thanks a lot!

Also, does the picture have non-zero latitude/longitude showed when opened from the [EXIF Tag Viewer](https://play.google.com/store/apps/details?id=com.teapps.exiftagviewer) app?

**Comment by RitikaPahwa4444** [comment]
This is what I found in Google Photos Help:

![Screenshot from 2023-03-31 11-30-48](https://user-images.githubusercontent.com/83745993/229036086-133474f3-8113-42ea-bd98-245a7710d044.png)

Seems like any edits made on Google Photos remain within Google Photos only 🙂

**Comment by nicolas-raoul** [comment]
Thanks @RitikaPahwa4444!

> when you download [...] the original location your device saved shows without any edits you made in Google Photos

Indeed it seems like it would be difficult to get coordinates added/modified within Google Photos... if nothing works we can try and inform the user about it, for instance in the FAQ, or via popup if we manage somehow to recognize that a user is adding/modifying within Google Photos.

**Comment by RitikaPahwa4444** [comment]
I believe it would be hard to recognise that a user is adding/modifying the location within Google Photos if he/she is not getting redirected to the Photos app from some activity in the Commons app, and using Photos first and then uploading on Commons . Do we have that feature of redirecting to other apps from within the Commons app? I am sorry, I may not have realised this potential yet and thought of confirming once.

**Comment by nicolas-raoul** [comment]
@RitikaPahwa4444 You are right that it sounds hard, probably impossible in which case just adding a FAQ would be enough. The Commons app does not redirect to other apps except opening a web browser and maybe a few other rare cases.

**Comment by RitikaPahwa4444** [comment]
Thank you for confirming @nicolas-raoul. I was checking the location-loss tagged issues for GSoC, but since now you have created a new issue for that purpose, and I have two other issues assigned already, I will not take this one up for some time and may be leave it for the other contributors while I fix those bugs :)

**Comment by nicolas-raoul** [comment]
Totally understandable, actually better leave such tasks for the GSoC itself. Thanks for the research and insight! :-)

**Comment by nicolas-raoul** [comment]
I added a paragraph about this in the documentation. Thanks all! :-)
