### ISSUE TITLE
Reword message "A selfie" to "a selfie which is not used in any article"

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#5100]
Three tasks:
- Reword the string "A selfie" to "a selfie which is not used in any article" in `app/src/main/res/values/strings.xml`. Do not forget to change the uppercase "A" to lowercase "a".
- Please also reword "Blurry" to "totally blurry".
- Please also reword and "Nonsense" to "nonsense, absolutely unusable in any article".

Context: https://commons.wikimedia.org/wiki/Commons:Deletion_requests/File:JohnDavidWashington.jpg https://commons.wikimedia.org/wiki/Commons_talk:Deletion_requests#Commons_Android_App_problems

**Comment by guishas** [comment]
Hey, I would like to fix this, can I grab this issue?

**Comment by nicolas-raoul** [comment]
@guishas Yes thanks!

**Comment by guishas** [comment]
Hey Nicolas, I just submitted my PR fixing this issue! When you have time please take a look at it. If I did anything wrong please let me know!

**Comment by nicolas-raoul** [comment]
Thanks @guishas ! :-)
