### ISSUE TITLE
Review: Only pictures uploaded from the app

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#5101]
The `Review` feature (in the app's menu) was originally thought as a way to improve our app's overall upload quality, it is not really adapted to the wide variety of pictures uploaded via other upload tools.

Task: Make `Review` show only images that were uploaded from the app.

I believe a REST API request somewhere in the app needs to be modified. Images uploaded from the app have a special tag `Android app edit` that can be seen for instance at https://commons.wikimedia.org/w/index.php?title=File:Ratchaprasong.jpg&action=history

**Comment by jeremykenny** [comment]
I'd like to take on this issue.

**Comment by nicolas-raoul** [comment]
@jeremykenny It is yours, thanks!

Please post relevant Mediawiki API calls you find. 🙂

**Comment by jeremykenny** [comment]
> @jeremykenny It is yours, thanks!
> 
> Please post relevant Mediawiki API calls you find. 🙂

The relevant API call is https://github.com/commons-app/apps-android-commons/blob/f7d3414cc3f895edeaa2221e1c99655519d05e44/app/src/main/java/fr/free/nrw/commons/review/ReviewInterface.java#L13

Which calls this endpoint: https://commons.wikimedia.org/w/api.php?action=help&modules=query%2Brecentchanges.

I believe the right way to go about this is to add `tags` to the `rcprop` argument, create a `tag` property on the [RecentChange](https://github.com/commons-app/apps-android-commons/blob/master/data-client/src/main/java/org/wikipedia/dataclient/mwapi/RecentChange.java) class, and add a check for the `Android app edit` tag in the [ReviewHelper.isChangeReviewable](https://github.com/commons-app/apps-android-commons/blob/f7d3414cc3f895edeaa2221e1c99655519d05e44/app/src/main/java/fr/free/nrw/commons/review/ReviewHelper.java#L111) filter function.

Does that seem like a sensible approach?

**Comment by nicolas-raoul** [comment]
Great finding, thanks!

How about specifying `rctag` in the API call? If I understand correctly, that could give us only the review we want, instead of filtering afterwards :-) That seems to work:

https://commons.wikimedia.org/w/api.php?action=query&format=json&formatversion=2&list=recentchanges&rcprop=title|ids|tags&rctype=new|log&rctoponly=1&rcnamespace=6&rclimit=1&rctag=android%20app%20edit

returns

<img width="410" alt="Screen Shot 2022-11-23 at 16 46 32" src="https://user-images.githubusercontent.com/99590/203494685-b270b04d-87e9-4b8d-83a8-67cb142f9579.png">
