### ISSUE TITLE
Review: Only images that are not used

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#5103]
Task: When retrieving a new image to review, skip to next if the image is in use in any article or user page.

Same context as #5101, it is a bug to suggest that selfies that are used might be out of scope.

Caveat: Ignore usage under https://commons.wikimedia.org/wiki/User:Didym/Mobile_upload/ which has been a gallery of all of our uploads since 2014.

**Comment by arinmodi** [comment]
@nicolas-raoul, is there any field that tells that image is in use in any article or user page ?

**Comment by nicolas-raoul** [comment]
@arinmodi I believe there is either a field or other API call for this.

This specialpage probably uses it:
https://commons.wikimedia.org/wiki/Special:GlobalUsage/Mozzarella_di_bufala3.jpg

Usage is also visible in the "File usage on other wikis" section of any image such as https://commons.wikimedia.org/wiki/File:Mozzarella_di_bufala3.jpg

**Comment by nicolas-raoul** [comment]
These fields exist:
https://commons.wikimedia.org/w/api.php?action=help&modules=query%2Bfileusage
https://commons.wikimedia.org/w/api.php?action=help&modules=query%2Bglobalusage

They are not recognized by the current recent changes API call, it might need some tweaking:
https://commons.wikimedia.org/w/api.php?action=query&format=json&formatversion=2&list=recentchanges&rcprop=title|ids|tags|fileusage|globalusage&rctype=new|log&rctoponly=1&rcnamespace=6&rclimit=1&rctag=android%20app%20edit

If nothing else works, just call the API on each result:
https://commons.wikimedia.org/w/api.php?action=query&prop=fileusage|globalusage&titles=File:Mozzarella_di_bufala3.jpg

**Comment by arinmodi** [comment]
@nicolas-raoul, reviews are not loading, api reponse saying bad timestamp error

**Comment by nicolas-raoul** [comment]
Please post your API call URL and the exact error message, thanks!

**Comment by nicolas-raoul** [comment]
Please use build flavor prodDebug, not testDebug.
Then probably fix the timestamp, try to urldecode the URL.

**Comment by arinmodi** [comment]
@nicolas-raoul, it is related to the timestamp, %3A means ```:```, but it is converted into ```%253A``` in url, that's causing the problem

**Comment by arinmodi** [comment]
@nicolas-raoul, how to change the build flavors?
