### ISSUE TITLE
"Welcome to Full-screen Selection Mode" popup shown when tapping an already uploaded image in Media Details

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#5104]
1. Reset app storage.
2. Go to Explore.
3. Tap a picture.
4. In the details tap the picture again.

Screencast: https://drive.google.com/file/d/1exJ5BZYmkQ7Rzb5MNMI9PdAEykQolrbi/view?usp=drivesdk

It should just open the image in full-screen mode, without any selection gesture nor popup.

Also, it seems to just show a black screen afterwards.

This first-time-popup is meant to only appear when using full-screen mode inside the **custom selector** (in the main activity, when you push the +, the custom selector is the third button at the bottom), not when using full-screen inside Explore or other places.

**Comment by sivaraam** [comment]
When I tap on the image of an already uploaded image, I see the uploaded image in full-screen. I don't see a "Welcome to Full-screen Selection Mode" pop-up. Is there any specific steps that need to be followed in order to trigger this issue ? 🤔

**Comment by nicolas-raoul** [comment]
@sivaraam  Sorry I added the steps now.
