### ISSUE TITLE
Leaderboard does not update fast enough

### ISSUE THREAD

**Issue by babelstone** [commons-app/apps-android-commons#5106]
### Summary

I started using the app a few weeks ago, and the first time I viewed the leaderboard it correctly showed my stats and position on the board. But thereafter my stats, and also those of everyone else I think, have remained unchanged. Although I have uploaded 200+ photos with the app since then, my uploads on the leaderboard have remained the same as the first time I viewed the board. The Contributions page updates just fine. I have tried clearing the app cache, and logging off and on again, but to no avail.

### Steps to reproduce

1. View leaderboard and note user's upload count.
2. Upload a new photo.
3. View the leaderboard --- user's upload count is the same.

### Expected behaviour

Leaderboard should update to reflect new uploads by the user.

### Actual behaviour

Leaderboard does not update.

### Device name

Galaxy A70

### Android version

Android 11

### Commons app version

4.0.5

**Comment by sivaraam** [comment]
There are three leaderboards: 

1. Upload
2. Used
3. Nearby

Could you check if you're looking at leaderboards other than the "Upload" one ? If you're facing the issue with "Upload" one itself, then some screenshot would be helpful to understand what issue you're observing.

**Comment by babelstone** [comment]
Same for all three leaderboards for all three time periods. I attach a screenshot of my Achievements page which shows a total of 4219 uploads, and the uploads leaderboard which shows a count of 3987 uploads for all time. 3987 is the number of my uploads when I first opened the leaderboard in early October. Used for all time leaderboard shows 933 for all time, even though my current used count is 1034. And the Nearby leaderboard shows zero over all time, but I have uploaded over 100 nearby photos since I've started using the app.
![Screenshot_20221107-192024_Commons](https://user-images.githubusercontent.com/20558386/200397860-0205c696-0a3b-478a-bbeb-2424c44fad79.jpg)
![Screenshot_20221107-192043_Commons](https://user-images.githubusercontent.com/20558386/200397872-45feaeee-6595-4310-b82b-fd465313b3e2.jpg)

**Comment by sivaraam** [comment]
Thanks for the details! I suppose the leaderboard should be showing the right numbers at least for you now. Let me know in case it still shows incorrect numbers.

IIUC, the leaderboard information is maintained in tools server and should be updated periodically. For some reason, it seems not to be updating by itself. Let me ping relevant contributors to see if they could shed some light @madhurgupta10 @maskaravivek

**Comment by babelstone** [comment]
Thank you! Yes, the leaderboard has now been updated, and shows the correct figures for me. I agree that the leaderboard data does not seem to be automatically updating as expected.

**Comment by sivaraam** [comment]
@babelstone It's been some time. Could you confirm if you're still observing this issue ? If yes, we'll look into digging this further.

**Comment by babelstone** [comment]
The leaderboard seems to be automatically updating as expected now, so I guess the issue can be closed.
