### ISSUE TITLE
Translation issue with message Wikimedia:Commons-android-strings-show already actioned pictures/is

### ISSUE THREAD

**Issue by sveinki** [commons-app/apps-android-commons#5113]
Message URL: https://translatewiki.net/w/i.php?title=Special:Translate&showMessage=commons-android-strings-show_already_actioned_pictures&group=commons-android-strings&language=is

"Show already actioned pictures" - "actioned" means what? Is it pictures that have already been used in some context, or have been archived, or what?

**Comment by nicolas-raoul** [comment]
It means pictures that have already been either uploaded, or marked as "not for upload".
Thanks for localizing! :-)
