### ISSUE TITLE
Uploads fail on my device all the time Android Samsung 

### ISSUE THREAD

**Issue by Alasande** [commons-app/apps-android-commons#5114]
It is always disturbing while trying to upload photographs in real time. It discouraged me a lot. Please fix the problem, count the number of times I uninstalled the application, switch off the mobile, and find all possible ways to make it correct.

**Comment by nicolas-raoul** [comment]
Hi @Alasande 

Sorry for the inconvenience!
What is the size (in MB) of the picture you are trying to upload, on average?
I would suggest:
- Leaving the app open, screen open, while the picture is uploading, not using other apps at the same time.
- Uploading pictures one -by one, never as a multi-upload.

**Comment by Alasande** [comment]
Hello,

Greeting the day,

Thank you for reaching out to me. The average picture size is 500KB–5MB,
but some times it will vary up to 15MB. Neither camera photographs nor
mobile camera photos are uploading.

Thank you for your suggestions I will follow the same.

Regards,

Bharathesha A B

**Comment by nathanmeade** [comment]
@Alasande Could you provide your device details?

**Comment by nicolas-raoul** [comment]
@Alasande The beta version of the app fixes that, would you mind trying?
If you still experience issues, feel free to reopen.
Thanks a lot for your feedback! :-)
