### ISSUE TITLE
Fix unit tests: AdvanceQueryFragmentUnitTests

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#5115]
Broken since https://github.com/commons-app/apps-android-commons/pull/5091 it seems.

Anyone please feel free to send a pull request, thanks! :-)

**Comment by bosankus** [comment]
@nicolas-raoul  on it

**Comment by bosankus** [comment]
One observation found.
with `mockito-inline:3.13.0` multiple tests are not running, and showing `Test events not received`
<img width="739" alt="Screenshot 2022-11-25 at 8 11 46 AM" src="https://user-images.githubusercontent.com/46471379/203889659-fc5d69a6-1ca4-4616-ac65-b2a428a9ec0b.png">

So the option was to update `mockito-inline:3.4.0` which enables mocking static objects. And test results were matching with this issue.
<img width="274" alt="Screenshot 2022-11-25 at 8 13 51 AM" src="https://user-images.githubusercontent.com/46471379/203889870-ae15d4b5-2535-45a7-b745-85c720e62c1e.png">
`NB: Updating mockito-inline means removing mockito-core, as keeping it is redundant.`

cc: @nicolas-raoul should the dependency version be updated?

**Comment by nicolas-raoul** [comment]
By "updating", do you mean going from version 3.13.0 back to older version 3.4.0?

**Comment by bosankus** [comment]
If you see this link https://github.com/mockito/mockito/releases?page=2 there is no release note for 3.13.0. Though I understand 3.12.0 is successor of 3.4.0 which involves mocking static methods(https://github.com/mockito/mockito/releases?page=13).

**Comment by aunghsi1** [comment]
Hello

**Comment by psh** [comment]
This is an _interesting_ unit test - the test methods that are passing dont actually do anything (a null check on something created in the setup method, and calling a method to dismiss a keyboard that was never displayed).  The true business logic of the class (displaying the query and validating the buttons do what they are meant to) is never _actually_ validated.

Another approach to getting things working would be to treat onCreateView() and onViewCreated() as simply part of doing the setup; testing them is implicit in the validation of the real logic.  Dont bother mocking.  Let the class setup its GUI and drive the test using Robolectric (you'll need to fix the fact that the fragment is being attached to a FrameLayout that plays no part in the actual test activity though - another flaw of the test).

Putting on my senior dev / engineering manager hat for a moment, and writing the requirements in canonical form - 

* **GIVEN** an initial query passed in the fragment arguments 
**WHEN** the fragment is displayed 
**THEN** the query is displayed in the text field
* **GIVEN** no fragment arguments 
**WHEN** the fragment is displayed 
**THEN** the the text field should be blank
* **GIVEN** an initial query displayed in the text field and I have changed it 
**WHEN** I click the "Reset" button 
**THEN** the field resets to the initial query and the callback notified
* **GIVEN** an initial query displayed in the text field and I have changed it 
**WHEN** I click the "Apply" button 
**THEN** the callback is notified with the updated value and the screen closed
* **GIVEN** an initial query displayed in the text field and no changed are made 
**WHEN** I click the "Apply" button 
**THEN** the callback is notified with the original value and the screen closed

The only mock needed should be trivial - the callback so you can verify the reset / apply / close methods are called.  Each of these GIVEN / WHEN / THEN statements could be a simple test method to get full coverage of both code _and_ functionality.

**Comment by nicolas-raoul** [comment]
Thanks a lot @psh for the insight, that's extremely useful!!!

@bosankus Do you think you can do this? If not we should move Paul's advice to a new issue.

**Comment by bosankus** [comment]
Thanks @psh for the input. @nicolas-raoul I want to do the task. However expect little delay as I am on vacation till 9th. @nicolas-raoul can this issue wait, or suggest other ways to handle it.

**Comment by nicolas-raoul** [comment]
@bosankus That's fine, enjoy your vacation, thanks! :-)

**Comment by bosankus** [comment]
Hi @nicolas-raoul  & @psh Can you have a look at the PR I raised with the fix?
