### ISSUE TITLE
app often just hangs/stops working

### ISSUE THREAD

**Issue by subbass1** [commons-app/apps-android-commons#5117]
4.0.5~f03b7dd8d, Android 12

I regularly suffer from a problem where the app just hangs (current upload doesn't go on anymore), I don't see why. I then do have enough space and often extra rebooted before. I normally choose 10-20 files (as I saw the app regularly uses junks of 4 files at once). The only solution then is de- and reinstall. (stop/start is of no success). Any hints? --~~~~

**Comment by subbass1** [comment]
anyone? :(

**Comment by nicolas-raoul** [comment]
Does it also happen if you only upload 4 at a time after reinstalling?
Uploading more than 5 pictures is unfortunately not well supported.

**Comment by subbass1** [comment]
Really? Why? I wasn't aware of that. Will try. But sometimes it indeed does work with my 10-20 files at once. Also the field can be, say 10 MB...
Perhaps it can be "upgraded"?

**Comment by nicolas-raoul** [comment]
We are not sure why, but we observed that various bugs start to appear from time to time when uploading more than 5 at a time. We hope some very skilled Android developer will have a look at the issue some day, but we are all volunteers so it is hard to progress fast. Thank you for your patience!

**Comment by subbass1** [comment]
Thanks! Ok, knowing this limit surely is of help. My wish for uploading would be, say, 50-100 :) including automatic numbering of course (the app sees a syntax like (01) and automatically names the following files - and skips these annoying single location check, where you always have to cancel the question (instead of *one*  when the location is the same).

**Comment by nicolas-raoul** [comment]
@subbass1 What has been your experience afterwards? Did the frequency of the hangs get lower when uploading around 5 pictures instead of around 10-20? Thank you for your valuable feedback!

**Comment by subbass1** [comment]
In the meantime I didn't have problems anymore, uploading regularly, say, max 10-15 files at once (but not so much as in the months before). It's also possible that this was a local problem with my phone, storage nearly fully loaded. I experienced a few strange things then. I keep watching. Thanks for the work.
