### ISSUE TITLE
Unit tests failing for RecentLanguagesAdapterUnitTest

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#5121]
In master:
```
fr.free.nrw.commons.recentlanguages.RecentLanguagesAdapterUnitTest > testGetView FAILED
    java.lang.ClassCastException at RecentLanguagesAdapterUnitTest.kt:100
```

**Comment by nicolas-raoul** [comment]
@bosankus Do you want to work on this? :-)

**Comment by bosankus** [comment]
Let me spend a day or two on it. I will update here.

**Comment by nicolas-raoul** [comment]
I edited your message to use the triple-quote notation to show multiple lines of code, please check as it is useful syntax. :-)

It looks like a problem with your editor.
Could you please try `./gradlew testBetaDebugUnitTest` directly?

**Comment by bosankus** [comment]
Yes I fixed it. It was JDK error. I was using gradle JDK 11, changing to 1.8 worked. Also in my local the test failure at line 100 is visible now.

**Comment by bosankus** [comment]
Hi @nicolas-raoul have raised PR for the fix. Kindly review.

**Comment by nicolas-raoul** [comment]
Thanks a lot, master unit tests are running successfully now :-)
