### ISSUE TITLE
New project lead/maintainer

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#5123]
Hi folks,

Just wanted to announce some important changes in the Commons app's roadmap. Most of you who have been with us for a while may have noticed that we used to operate on a Wikimedia grants system, with a core (funded) dev team and a fixed list of new features for each year. However, this era of the Commons app now draws to a close, as our last grant was completed with the release of v4. There are currently no plans for applying for another grant, and I am stepping down from my role of project lead to focus on a different path in my career. For the past couple of months, we have been in a transition phase with no concrete plans for the future, although there were plenty of conversations.

I am thrilled to announce that we now have a new volunteer project lead/maintainer  - please welcome @sivaraam  ! Sivaraam is a regular volunteer contributor who has been with us since 2018, and has also been the primary maintainer of our website. I trust that the app will be in great hands with him at the helm. Many of us from the previous dev team also intend to stick around on a volunteer/occasional basis.

This transition should be completely smooth, and is unlikely to affect contributors or users of the app. We intend to keep the app published under WMF's account for the foreseeable future, to keep it completely open-source, and to keep encouraging  volunteer contributions.

Thank you all for your support throughout all these years. It has been a wild ride for me, from interning for this project in 2015 to leading it for 6 years, and I am immensely grateful to all our contributors past and present for making the app what it is today.

Best regards,
Josephine

**Comment by nicolas-raoul** [comment]
Many thanks @misaochan for all of your hard work during these 6 years!!! You are a great project leader.

And looking forward to working with @sivaraam :-)

**Comment by psh** [comment]
Congratulations on the new role @sivaraam!

I wish you all the best in the next season of your career @misaochan.  Thanks for all you have given to this project over the years!

**Comment by madhurgupta10** [comment]
@misaochan I had a great time working under your leadership and you were definitely a great mentor and project leader. I wish you all the best in your future endeavours.

Congratulations to @sivaraam on the new role. I hope this project continues to grow in future. I will also try to stick around and make contributions whenever possible.

**Comment by sivaraam** [comment]
I would also like to join the others in thanking @misaochan for all her wonderful work in taking the app forward and building a good environment for the community around it. Kudos 👏🏼 . Wishing you the best on your new career!

To the others, I thank you for all the kind words. I'm not sure how much I'll be able to fill Josephine's shoes. I hope to try my best in keeping the app alive and taking it forward in ways I can. All of your help and support is very crucial for the same. We're a community after all :-)

For many people here, you would know me as the friendly contributor you see around now and then trying to help the app 🙂 . For the others, I suppose I owe an introduction.

I'm Kaartic Sivaraam. You could call me Sivaraam. I've been an admirer of the free culture and the Wikimedia movement for quite a few years. Inspired by it, I've been contributing to help the free culture movement in multiple ways. Contributing to the Commons app has been a significant part of it. As Josephine mentioned, I've been a passive contributor for a few years now trying to help with fix issues, helping the new contributors and so on. Now I hope to continue doing the same while also taking on some additional responsibilities. I'm curious to see how this goes.

As a finishing note, I trust that we'll get together as a community and continue our collaborative efforts in making the app play a significant role in contributing to Wikimedia Commons. Cheers!

**Comment by nicolas-raoul** [comment]
Many months have passed, I think this can be closed. :-)
