### ISSUE TITLE
Add manual upload link to main menu

### ISSUE THREAD

**Issue by jidanni** [commons-app/apps-android-commons#5132]
In the main menu, there should be a link added, called "manual upload" or "upload (via) web  form", that's just simply a link to the upload form on the Commons website. This will come in handy in cases when the user has some problem and wishes to use an alternate upload method.

**Comment by arinmodi** [comment]
@nicolas-raoul, what are your thoughts on this ?

![upadated](https://user-images.githubusercontent.com/61725413/220732523-c4e3afcf-1ef4-42ef-b6e2-62a1000b8e76.jpeg)

I think we can add one more button with other buttons shown in above pic with browser icon in it for implementing this feature. But I am not sure that weather it will be good user experience or not.

@nicolas-raoul, I am waiting for your approval, before implementing this.

Thanks.

**Comment by nicolas-raoul** [comment]
I don't think this would be useful.
People who prefer the website would not go via the app.
