### ISSUE TITLE
No way to turn off "Nearby"

### ISSUE THREAD

**Issue by jidanni** [commons-app/apps-android-commons#5133]
Once the user tries Nearby, it will be with him for the rest of his life, as a black rectangle at the top of the contribution screen, with no way to get it back off.

**Comment by jidanni** [comment]
Okay. I found one must go into  Preferences to turn it off. So it's weird: you can turn it on outside of Preferences but then to turn it off you need to go into Preferences.

**Comment by matkoniecz** [comment]
> No way to turn off

Can you fix misleading title?

And in general disabling things in preferences is a quite standard way to do things.

**Comment by nicolas-raoul** [comment]
Most people consider this feature useful, so it is on by default, but you can turn it off in the settings.
That's a usual pattern found in most apps.
