### ISSUE TITLE
Consider hiding some thumbnails of categories

### ISSUE THREAD

**Issue by matkoniecz** [commons-app/apps-android-commons#5138]
### What is the user problem or growth opportunity you want to see solved?

As user I was adding category and search for category "Forest".

As I type, for "Fores" category "Foreskin" was among top matches and was shown with penis thumbnail.

I would prefer to avoid unexpectedly looking at dick pics.

### How do you know that this problem exists today? Why is this important?

I encountered it about minute ago (while uploading https://commons.wikimedia.org/wiki/File:Location_marked_as_cemetery_on_a_map.jpg ).

### Who will benefit from it?

People not wishing to look unexpectedly at dick pics.

### Anything else you would like to add?

I understand that there are depictions of Muhammad in its Wikipedia article despite https://en.wikipedia.org/wiki/Muhammad#Depictions - and I know that https://en.wikipedia.org/wiki/Penis article is well illustrated and https://en.wikipedia.org/wiki/Leprosy and other disease articles are well illustrated.

But random penis while typing forest is a bit too much for me.

**Comment by Theo-Stefan** [comment]
Hey I'd like to work on that and solve the issue, would you please contact me to talk further about it?

**Comment by nicolas-raoul** [comment]
@Theo-Stefan You must fix 5 issues marked as "bug" before working on issues marked as "enhancement". Thank you for your understanding!

**Comment by nicolas-raoul** [comment]
The Commons website seems to be having MUCH MUCH WORSE issues: https://phabricator.wikimedia.org/T331250

**Comment by mnalis** [comment]
Perhaps a  general app preference that users can check, which would just **not download thumbnails at all**? 

As an additional advantage (orthogonal to fixing the problem of this issue) users might choose to not download those thumbnails, as it would help them save on mobile data costs (and reduce battery drain).

Anything more complicated would need some kind of manual categorizing of all wikimedia (Category:NSFW ?) or AI that guesses what to show and what not, which is much harder (and more prone to failure) to implement and maintain. And likely introduce more bugs.

**Comment by matkoniecz** [comment]
Or maybe ability to skip adding categories/wikidata classification steps?

**Comment by nicolas-raoul** [comment]
@matkoniecz We really want users to enter depictions/categories, for findability reasons and to be good Commons citizens. If the user's pictures are geolocalized, the country will be suggested, and as you may know countries have very safe thumbnails. So, users who feel strongly about seeing unrelated thumbnails have this very quick/easy option.

**Comment by mnalis** [comment]
> We really want users to enter depictions/categories, for findability reasons and to be good Commons citizens.

I agree; depictions/categories should stay in as they are now (skippable, but only with warning) in order to make the uploads way more useful then without them. Some categories might be auto-added by bots or other interested parties, but lot of metadata can be only (or at least most accurately) provided only by submitter, so such behaviour of adding relevant metadata should be heavily encouraged (as it is currently).

**Comment by nicolas-raoul** [comment]
Wikipedia currently shows such thumbnails when searching for anything in the big search bar which is on top of every article (I added the bell pepper):
<img width="894" alt="Screenshot 2023-06-28 at 16 19 58" src="https://github.com/commons-app/apps-android-commons/assets/99590/75355ec4-12a5-41fb-a0df-3a88cd353cff">
We follow Wikimedia's policies, so I think we will wait for Wikipedia to implement it first.
Thank you for your understanding!

**Comment by matkoniecz** [comment]
> We follow Wikimedia's policies

Showing images of category is interface/UX decision, not a policy.

Well, I can just do not add categories at all.

**Comment by mnalis** [comment]
> Showing images of category is interface/UX decision, not a policy.

I agree, this is UI/UX design issue. And surely especially mobile app has different priorities then desktop website; especially when data-saving option is enabled?

@nicolas-raoul would a PR implementing a preference not to fetch thumbnails be accepted?

**Comment by nicolas-raoul** [comment]
We already have too many preferences and are trying to get rid of them to simplify app maintenance.
A mobile app needs to be even more visual than a website, because people can't hover nor open the category in a new tab to make sure that they are selecting the right one, so I would say that such a preference is even less needed on mobile than on the website.
I believe the data usage is negligible: our app makes a lot of useless network requests in the background almost all the time, that should be the priority as far as data usage is concerned.
