### ISSUE TITLE
On-the-go notifications for Nearby photo opportunities

### ISSUE THREAD

**Issue by VojtechDostal** [commons-app/apps-android-commons#514]
_(please change the title for a more meaningful one)_
This is an idea that is worth taking note of but I know it would require some thinking and possibly a lot of programming. It would be cool if I could receive notifications when walking around a city when I get close to an object that needs a picture. The app would notify me of the object and ask me to upload it, with a correct Q item number serving as the basis for the description (and possibly also P373 for the appropriate category).

**Comment by nicolas-raoul** [comment]
Like #79 and #259 ? :-)

**Comment by VojtechDostal** [comment]
*facepalm*

must have read them and then forgot that they existed

feel free to merge :)

**Comment by nicolas-raoul** [comment]
No problem ;-)
