### ISSUE TITLE
[Bug]: Remove Telemetry due to app's privacy policy

### ISSUE THREAD

**Issue by kartikaykaushik14** [commons-app/apps-android-commons#5154]
### Summary

Telemetry is often used to monitor the performance of applications, track usage patterns, and gather other data that can help developers improve their products. This data can be used to identify and diagnose issues, track trends, and make informed decisions about product development. However, due to the app's privacy, we would want to remove Telemetry from the app.

The issue is created as advised in [this comment](https://github.com/commons-app/apps-android-commons/issues/4994#issuecomment-1432296875).

### Steps to reproduce

1. Have the app open
2. Go to More
3. Go to settings
4. Under the Privacy section, see Mapbox Telemetry

### Expected behaviour

There should be no trace of telemetry in the code and app.

### Actual behaviour

As of now, the users have an option to opt-in or out of telemetry but we want it to be removed. Currently, there are traces of telemetry in the code. 

### Device name

Pixel 6

### Android version

Android 33

### Commons app version

4.0.3

### Would you like to work on the issue?

Yes

**Comment by kartikaykaushik14** [comment]
@nicolas-raoul Could you please assign this issue to me?

**Comment by kartikaykaushik14** [comment]
@nicolas-raoul Could you please review the code changes?

**Comment by nicolas-raoul** [comment]
I would argue that we comply with this documentation, as simply _installing the app_ already _opts the user out_ of telemetry. My understanding is of this rule's spirit is that users should not be forced to send telemetry if they do not want to.

@kartikaykaushik14 Do you know MapLibre's stance on this? Would switching to MapLibre (or another equivalent) avoid the telemetry question entirely?

**Comment by kartikaykaushik14** [comment]
MapLibre seems to have removed telemetry entirely. 
Sources - [Link 1](https://www.maptiler.com/news/2021/06/maplibre-gl-native-open-source-mobile-sdk-for-android-and-ios/), [Link 2](https://github.com/maplibre/maplibre/discussions/104), [Link 3](https://github.com/maplibre/maplibre/discussions/69)

**Comment by sivaraam** [comment]
> I would argue that we comply with this documentation, as simply _installing the app_ already _opts the user out_ of telemetry. My understanding is of this rule's spirit is that users should not be forced to send telemetry if they do not want to.
> 

Indeed. My concern is we're not even giving the option to opt-in if at all someone wants to do that. We're just disabling it ourselves for all our users.

> MapLibre seems to have removed telemetry entirely. Sources - [Link 1](https://www.maptiler.com/news/2021/06/maplibre-gl-native-open-source-mobile-sdk-for-android-and-ios/), [Link 2](https://github.com/maplibre/maplibre/discussions/104), [Link 3](https://github.com/maplibre/maplibre/discussions/69)

That's wonderful! If switching to it is a feasible thing and suits us well, I'm all for it 👍🏼 
We could settle this long standing dilemma once and for all :-)

**Comment by kartikaykaushik14** [comment]
@nicolas-raoul Can we please close this issue since we resolved it in #5182?

**Comment by nicolas-raoul** [comment]
Yes, thanks!
