### ISSUE TITLE
Longer questions not appearing completely in Peer Review

### ISSUE THREAD

**Issue by RitikaPahwa4444** [commons-app/apps-android-commons#5157]
### Summary

Longer questions do not appear completely in Peer Review. On scrolling, only the hint (in grey) appears.

### Steps to reproduce

1. Click on the hamburger icon in the bottom navigation bar
2. Click on Review
3. Observe longer questions

### Expected behaviour

Longer questions should be visible completely since the app is using a ScrollView.

### Actual behaviour

Longer questions are not visible completely.

### Device name

Redmi 5A

### Android version

8.1.0

### Commons app version

master and prodDebug

### Screen-shots

![Peer Review](https://user-images.githubusercontent.com/83745993/221882596-1eeb6a54-885c-4cc7-a897-61f1103f3b61.jpeg)

### Would you like to work on the issue?

Yes

**Comment by nicolas-raoul** [comment]
Does scrolling each of the text areas work?

**Comment by RitikaPahwa4444** [comment]
No, those text areas cannot be scrolled individually.

**Comment by nicolas-raoul** [comment]
Feel free to work on it, thanks!
