### ISSUE TITLE
Measuring contributors who have never contributed to Commons before

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#517]
When I wrote the "measures of success" for my [IEG grant proposal](https://meta.wikimedia.org/wiki/Grants:IEG/Improve_%27Upload_to_Commons%27_Android_App) last year, one of them was "10+ new contributors who have never contributed to Commons before". Clearly I did not think that through very well, haha, since I still have no idea how this could possibly be measured. :/ It would definitely need to be measured on the WMF side since we should not collect such data via the app.

Even worse, the next measure of success that I suggested was "Less than 10% of pictures uploaded by new users (who have never contributed to Wikimedia before) are unusable". Not only is this dependent on us being able to do the former item, it is also dependent on us having knowledge of which accounts exactly are new. I understand that we can check the contributions of every user tagged under "Uploaded with Mobile Android app", but with 2000+ active users now, that is not going to be a trivial undertaking (I wrote the proposal when we had 200 active users).

Any idea if there is any way I can do such a thing, or at least something close to it?

**Comment by nicolas-raoul** [comment]
For the second criteria:

As a sample, I took the last full period available at https://commons.wikimedia.org/wiki/User:Didym/Mobile_upload, which is: https://commons.wikimedia.org/wiki/User:Didym/Mobile_upload/2017_April_11-15

This period (5 days) has 341 pictures. Among those I have found:
- 10 copyvio
- 10 useless pictures (selfies, tests, pictures unusable without knowing the context)
- 4 pictures that, while not good candidates for speedy deletion, are very unlikely to help illustrate Wikipedia.

That makes 7% of "useless" pictures. That's less than 10%

**Comment by misaochan** [comment]
Thanks @nicolas-raoul !

For the 1st criteria, how are you looking for them? Is there a process I can replicate?

For the 2nd one, can we assume that Didym will collect all the images from new users, or at least enough of them that we can use it as a representative sample?

**Comment by nicolas-raoul** [comment]
Yes, I picked random pictures at https://commons.wikimedia.org/wiki/User:Didym/Mobile_upload then clicked on the author's name then on "contributions" in the left bar to see this user's contributions, then "500" to see them all then "Earliest" if needed to see what there first uploaded file was. Then just check whether this file has the mobile app tag or not. By the way the second example is not great as the picture will probably be deleted soon, better find other accounts.

Didym's tool has been around for a long time, and collects all new files created by the app. When do you want to take the sample? Better decide right now on the date, so that you can not be accused of "cherry picking" a favorable sample.

**Comment by misaochan** [comment]
@nicolas-raoul Thanks, will do that for the 1st criteria.

Re: the 2nd criteria, does Didym's tool collect files from new users, or just all files created by the app? 

I'm not sure exactly when I will take the sample - I will probably only be able to take it once I have completed the entire project, which is looking unlikely to be before the hackathon. Since I will be leaving for vacation shortly, and also it would be nice to have all the new improvements from the hackathon before making the final (and most significant) round of media notifications.

**Comment by nicolas-raoul** [comment]
Didym's tool collects all files created by the app, not just new users.

**Comment by whym** [comment]
Here is a list of the users whose first upload is tagged "mobile app edit": https://quarry.wmflabs.org/query/18084

I'm not done with fully checking the results but it appears to contain items that Didym's list misses, such as https://commons.wikimedia.org/wiki/File:Bharath_mata_cut_out.jpg
(I'm less sure about possible false negatives in my list.)

**Comment by misaochan** [comment]
Wonderful, thanks @whym ! :) I won't be using it for a while yet (until after the hackathon), but it looks like it will come in very handy.

**Comment by nicolas-raoul** [comment]
Would it be possible to sort these users by decreasing number of subsequent uploads?
This would allow us to grasp how addictive the app is :-)

**Comment by whym** [comment]
> Would it be possible to sort these users by decreasing number of subsequent uploads?

Good point, added. (Click "uploads" twice to sort.)

**Comment by tobias47n9e** [comment]
Would it be possible to gather anonymous statistics where people are using the app? It would be great to see how well we are covering certain areas of the globe.

**Comment by misaochan** [comment]
It seems that according to http://tools.wmflabs.org/commons-app-stats/ the deletion rate is around 20% (the blue bar to red bar ratio is roughly 5:1). I guess that's not too bad, but not what we had hoped.

I wonder if there's any way to find the uploads vs deletions stats for the web upload wizard?

**Comment by misaochan** [comment]
This is done, thanks all!
