### ISSUE TITLE
Wrong uploader in "X will be encouraged by your appreciation" label

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#5174]
The [picture being reviewed below](https://commons.wikimedia.org/wiki/File:02_10_2021_Visita_ao_Pavilh%C3%A3o_de_Portugal_(51543184183).jpg) has been uploaded by `A1Cafel` but the label mistakenly says `GeographBot will be encouraged by your appreciation`. The previous picture I reviewed was a picture uploaded by `GeographBot`, so it looks like a reset issue.

![adb](https://user-images.githubusercontent.com/99590/224221976-ffecc425-32a1-4c35-b9ac-f092119ca0a3.png)

**Comment by MaAnCoSa** [comment]
Hi! I am beginning to work on open-source projects. Can I give this issue a try? I am installing the project and I was looking for an issue to start working on.

**Comment by awanishyadav967** [comment]
Hi, @MaAnCoSa  any progress?

**Comment by MaAnCoSa** [comment]
Hi! Sorry, I have been having trouble with my internet connection these past couple of days, but now that it is fixed, I am working on it.
