### ISSUE TITLE
Upgrade Minimum SDK Version, Compile and Target SDK Version

### ISSUE THREAD

**Issue by kartikaykaushik14** [commons-app/apps-android-commons#5175]
### What is the user problem or growth opportunity you want to see solved?

As part of https://github.com/commons-app/apps-android-commons/issues/4994 and based on https://github.com/commons-app/apps-android-commons/issues/4994#issuecomment-1442125601, before migrating from Mapbox to MapLibre, we require certain upgrades in dependencies in our application. This enhancement is to upgrade the Minimum SDK Version, Compile and Target SDK Versions of the application.

minSdkVersion: 19 -> 21
compileSdkVersion: 28 -> 31
targetSdkVersion: 28 -> 31

**Comment by kartikaykaushik14** [comment]
@nicolas-raoul Could you please assign me this issue?

**Comment by nicolas-raoul** [comment]
While we try to keep `minSdkVersion` as low as possible to not disadvantage people who do not have access to recent technology, 21 means we cover 99.3% of Android users, which is quite acceptable:
<img width="536" alt="Screenshot 2023-03-10 at 13 58 47" src="https://user-images.githubusercontent.com/99590/224227843-e15417cc-0379-4bb2-83ac-f306c728605e.png">
