### ISSUE TITLE
Skip tutorial option not showing after signup/signin in Commons app

### ISSUE THREAD

**Issue by awanishyadav967** [commons-app/apps-android-commons#5178]
### Summary

Try to signup ,tutorial page comes up ,Earlier at right top, Skip Tutorial option was there but in new update it is not there.

### Steps to reproduce

1.Open the app
2.Sign up as new user 
3.Tutorial page come at first.
4.There is no option to skip the tutorial.

### Expected behaviour

When tutorial page opens then at top Skip Tutorial should be there.

### Actual behaviour

Skip Tutorial option is not there

### Device name

Realme 6

### Android version

Android 11

### Commons app version

4.0.3 

### Device logs

![image](https://user-images.githubusercontent.com/91160609/224513315-db2c1640-67c6-4733-b3d2-b79ed0841694.png)
![image](https://user-images.githubusercontent.com/91160609/224513355-4a398dd3-8f9a-493e-8dc1-87a20018eff3.png)
![image](https://user-images.githubusercontent.com/91160609/224513428-9cb9a899-9949-4e42-ad5f-ac75092e096a.png)

### Screen-shots

![pic1](https://user-images.githubusercontent.com/91160609/224512846-f4b73391-fde2-4e6a-b435-9ecb25d0b8b1.jpeg)
![pic2](https://user-images.githubusercontent.com/91160609/224512848-379b3df3-27c5-4b7b-b112-a507b5231cbe.jpeg)
![pic3](https://user-images.githubusercontent.com/91160609/224512849-10657588-3f52-460a-8d1a-c19e578bc5ac.jpeg)
![pic4](https://user-images.githubusercontent.com/91160609/224512850-91623027-bf38-4e73-ae69-1cb102aa523e.jpeg)
![pic5](https://user-images.githubusercontent.com/91160609/224512852-9fdf22ac-9c6f-453c-9c3f-47cf409eeab8.jpeg)

### Would you like to work on the issue?

Yes

**Comment by RitikaPahwa4444** [comment]
Is that not what we intend to have? I think users must know what kind of pictures they should refrain from uploading (like selfies) and this may be the reason why the latest update does not any option to skip it.

**Comment by awanishyadav967** [comment]
@RitikaPahwa4444 As an experienced user who already knows how the app works, it can be frustrating to have to go through the tutorial every time you sign in. In this case, it would be helpful to have a "Skip Tutorial" button that allows the user to bypass the tutorial and go directly to the app's main screen.

**Comment by RitikaPahwa4444** [comment]
I'm sorry for the confusion. Since you mentioned "sign up as new user" in the issue description, I was referring to new users. If this issue exists with the login functionality, then it would be nice to have a skip button. Thank you for clarifying.

**Comment by joseearias** [comment]
Hi. I don't seem to be having this issue when signing in. Like @RitikaPahwa4444 mentioned, this only seems be an issue when a new account is created, in which case, I think that is the expected behavior.

**Comment by nicolas-raoul** [comment]
I agree that not letting new users skip the tutorial is a good thing.
I guess this can be closed? If I misunderstood something please let me know. :-)
