### ISSUE TITLE
[Bug]: Duplicate filename notification completely replaces image-found-on-internet warning

### ISSUE THREAD

**Issue by chan-j-d** [commons-app/apps-android-commons#5180]
### Summary

If attempting to upload an existing image found on the internet but giving it an existing filename, l only see the duplicate file name warning before pressing next. Once I press 'upload' for the duplicate file name warning, I will never see the other warning as it has been 'whitelisted'. If I instead give it a unique file name, then I will get the warning about taking images off the Internet. 

I'm not sure what the expected behavior should be but I imagine the image-found-on-internet should take precedent before warning of duplicate file name.

### Steps to reproduce

1. Select a image off the Internet to upload, I used https://commons.wikimedia.org/wiki/File:Bergtocht_van_Guarda_via_Ardez_en_Ftan_naar_Scuol._20-09-2019._(actm.)_27.jpg.
2. Fill `asd` in the caption field
3. Click next, and skip for location message. Here, we will see the file name already exists warning. 
4. Click upload
5. Proceeds to depiction step.

If instead, for 2. we filled in a more unique caption like `asdasdasd`, then we get the warning about not taking images off the Internet.

### Expected behaviour

It should give the warning about taking images off the Internet. If the user still insists on submitting the image, then warn of duplicate file name.

### Actual behaviour

It only ever shows the duplicate file name warning and never the image-found-on-internet warning.

### Device name

Pixel XL

### Android version

API level 30

### Commons app version

master

### Screen-shots
With `asd` as caption
![image](https://user-images.githubusercontent.com/65345505/225332214-3920c2e0-dd91-4d8c-87af-a230addbb99b.png)

With `asdasdasd` as caption
![image](https://user-images.githubusercontent.com/65345505/225332399-eabd218c-f96a-4ccd-a483-1be9de72ae94.png)

### Would you like to work on the issue?

None

**Comment by ArmanNavodia** [comment]
I looked into the issue. I found that the warning of images talking from the internet is due to no exif data found and not due to image downloaded from facebook.
Tested on API 28 and API 31.
Attaching logs for reference.
I have used the image given above.
![image](https://user-images.githubusercontent.com/77919824/226101319-8075e63c-8e8c-429f-94e1-c84c80c94f62.png)

In the logs the error code generated for the same bug is 32 which is for no exif data.
So still this warning "upload pictures that you have downloaded" be given priority over the same name warning?
correct me if I understood something wrong.

**Comment by chan-j-d** [comment]
Thanks for the investigation! I think no exif data is the way they use to detect that the photo is not taken by the phone's camera (not sure though!). And yes in my opinion, I think this warning should take priority over the same name warning. 

But after some thinking, I think the core issue is that the user should at least be notified of both regardless of priority, instead of one superseding the other. Should probably get someone more experienced to decide the expected behavior though or if it is even an issue to begin with.

**Comment by chan-j-d** [comment]
Hi @nicolas-raoul wanted to check what you thought about this issue, if it is indeed a 'bug' and what might the expected behavior be.

**Comment by nicolas-raoul** [comment]
@chan-j-d Good find! This is indeed a bug. Do you want to work on it? Your answer to "Would you like to work on the issue?" means no, I guess?

**Comment by chan-j-d** [comment]
Nope, someone else can work on this issue. Thanks for asking!

**Comment by ArmanNavodia** [comment]
@nicolas-raoul can you please assign me this issue.
Thank you

**Comment by nicolas-raoul** [comment]
@chan-j-d Thanks for reporting the issue!

@ArmanNavodia It is yours!
