### ISSUE TITLE
Dark mode: Some UI elements not conform

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#5191]
# Upload Wizard Location Selection Step (when uploading a picture, tap the map icon on the screen when description can be entered)
The map should be dark (like the Nearby activity's map):
![Screenshot_20230328-165607](https://user-images.githubusercontent.com/99590/228169555-76d10e68-fa97-4cb8-88d0-c83c950a26ed.png)

# Feedback (in the app's hamburger menu)
The black font is not great for dark mode.
![Screenshot_20230328-165311](https://user-images.githubusercontent.com/99590/228169622-c6cb5b2f-46d0-42ac-abf4-2add6559f4b5.png)

**Comment by RitikaPahwa4444** [comment]
I feel that even the bottom navigation bar icons are not very much visible in dark mode:

![dark](https://user-images.githubusercontent.com/83745993/228542822-94238854-e1f4-4379-b562-865b80120895.jpeg)

@nicolas-raoul, may I take this issue up?

**Comment by RitikaPahwa4444** [comment]
Thank you for assigning the issue to me. Should I modify the icons too or just fix the feedback dialog and map?

**Comment by nicolas-raoul** [comment]
Just these two please, but if you can create an enhancement issue about visibility that would be great. 🙂

**Comment by RitikaPahwa4444** [comment]
Thank you for confirming. I will create an enhancement issue about visibility and restrict to only these two for this issue.
