### ISSUE TITLE
Updating Toolforge web service in anticipation of infrastructure changes

### ISSUE THREAD

**Issue by whym** [commons-app/apps-android-commons#5197]
### Description

Does anyone actively maintain the toolforge instance called "commons-android-app"? Toolforge's admins asked to migrate it to Kubernetes: https://phabricator.wikimedia.org/T319638 (Actually, we only have to deal with a simple wrapper script usually, instead of directly dealing with Kubernetes.) What is the current status regarding the migration?

@maskaravivek and @madhurgupta10 - your names are listed in the link above.

I believe this is related to https://github.com/commons-app/apps-android-commons/issues/2430 and in use.

If needed, I think I can help because I recently did it for other Toolforge instances, [archiving](https://phabricator.wikimedia.org/T319568) and [commons-app-stats](https://phabricator.wikimedia.org/T319639) - both written mainly in Python.

There is no concrete end date for the current grid infrastructure as far as I can see, but apparently it's been more than a year since the admins [first](https://techblog.wikimedia.org/2022/03/14/toolforge-and-grid-engine/) started asking us to migrate.

**Comment by nicolas-raoul** [comment]
Thanks a lot for the hint!
I think nobody is maintaining it currently unfortunately.
If you are willing to help perform the migration, that would be super helpful! :-)

**Comment by maskaravivek** [comment]
Hi @whym Yes, it would be great if you could help migrate it.

**Comment by whym** [comment]
@maskaravivek Thank you for the response. I'd like to see what I can do, then. Can you add my account as a maintainer of the tool? It's "Whym" on Toolforge, too.
I think you can do that at https://toolsadmin.wikimedia.org/tools/id/commons-android-app .

Also, where is the latest code hosted at?

**Comment by nicolas-raoul** [comment]
This is supposed to be the latest code:
https://github.com/commons-app/commonsmisc

I don't think I have admin rights.

**Comment by maskaravivek** [comment]
@whym Done

**Comment by sivaraam** [comment]
@whym I suppose you're already keeping track of the upcoming deadline for migrating the toolforge application that is used by the commons-app. I've assigned the [corresponding Phabricator task](https://phabricator.wikimedia.org/T319638) to you in order to keep that task up to date.

Thanks for you help on this! 🙂 
Let us know if you're facing any blocker and need help with making progress on this. We'll try to help in ways we can.

**Comment by whym** [comment]
I have not been able to spend much time for the Toolforge issue, sorry. I really hope to get it done, or at least have a tentative fix, by the February deadline. I should have some time after the end of January.

I'm confused by the fact that there seems to be 2 tools (or backend APIs) in use by the app currently. Tool A is available at https://tools.wmflabs.org/urbanecmbot/commonsmisc. Tool B is at https://tools.wmflabs.org/commons-android-app/tool-commons-android-app. I believe the GitLab repository I mentioned earlier contains the source code of the Tool B.

Is Tool B a super set, or an updated version of Tool A? It look like that is the case, but I cannot verify because .py files of Tool A are not readable. If yes, we can simply stop using Tool A (but I'm not sure why nobody did that, if that is the case).

The latter is called "Test" in the app's source code, as in
https://github.com/commons-app/apps-android-commons/blob/38b1a014dd2cb600e7fb76aa90e663f28d397e7b/app/src/main/java/fr/free/nrw/commons/di/NetworkingModule.java#L48-L50

**Comment by nicolas-raoul** [comment]
@urbanecm Are the .py files powering https://tools.wmflabs.org/urbanecmbot/commonsmisc visible somewhere? Thanks! :-)

**Comment by sivaraam** [comment]
> I have not been able to spend much time for the Toolforge issue, sorry. I really hope to get it done, or at least have a tentative fix, by the February deadline. I should have some time after the end of January.
> 

No worries. Thanks for your help! 🙂 

> Is Tool B a super set, or an updated version of Tool A? It look like that is the case, but I cannot verify because .py files of Tool A are not readable. If yes, we can simply stop using Tool A (but I'm not sure why nobody did that, if that is the case).
> 

I think the source code for "Tool A" could be found here: https://github.com/commons-app/commonsmisc

**Comment by urbanecm** [comment]
> @urbanecm Are the .py files powering https://tools.wmflabs.org/urbanecmbot/commonsmisc visible somewhere? Thanks! :-)

As it was linked here, it comes from commons-app/commonsmisc here at GitLab indeed. I pushed a local hack I had available at Toolforge, just in case. I don't have any information about https://commons-android-app.toolforge.org/tool-commons-android-app/.

**Comment by sivaraam** [comment]
I suppose commons-android-app toolforge instance came into existence when working on the app's [leaderboard feature](https://github.com/commons-app/apps-android-commons/issues/2074). We have some documentation of the [DB schema](https://github.com/commons-app/commons-app-documentation/blob/master/DB_Schema/leaderboard.md) and the [various APIs](https://github.com/commons-app/commons-app-documentation/tree/master/API) it provides in our documentation repo.

Why it was done using a different toolforge instance rather than using the existing one is something that I'm not aware of. May be @maskaravivek and @madhurgupta10 might be able to chime in and shed some light on that.

In any case, thanks a lot for your understanding @urbanecm 🙂

**Comment by madhurgupta10** [comment]
@sivaraam As far as I can recall, we used a different instance for the leaderboard because it was easier to deploy to `tool-commons-android-app` than `commonsmisc`

**Comment by whym** [comment]
Thanks a lot for chiming in, @urbanecm @madhurgupta10. I think it might be wise to migrate away from urbanecm's tool instance, in the long run, that is, for the access issue you mentioned. But for now, I'm happy to keep the way it is. Maybe that is something we can continue discussing in a separate task. 

I believe the migration of the "commons-android-app" tool is mostly done. Please let me know if something stopped working around the leaderboard. I see that contributions tab is not working properly - this seems to have to do with the fact that the urbanecmbot tool is not up - [I'm talking about it with Urbanecm](https://wikitech.wikimedia.org/wiki/User_talk:Urbanecm#Commons_app_endpoints_under_the_urbanecmbot_project). But if something is wrong with the leaderboard, that's probably caused by the migration I did.

**Comment by sivaraam** [comment]
> I believe the migration of the "commons-android-app" tool is mostly done.

That's great to hear! Thank you for your help, @whym 🙂 

> Please let me know if something stopped working around the leaderboard. I see that contributions tab is not working properly - this seems to have to do with the fact that the urbanecmbot tool is not up - [I'm talking about it with Urbanecm](https://wikitech.wikimedia.org/wiki/User_talk:Urbanecm#Commons_app_endpoints_under_the_urbanecmbot_project).

Indeed. That seems to be the case for a few days now. We've [switched to using the commons-android-app instance](https://github.com/commons-app/apps-android-commons/pull/5489) to address this but that change hasn't yet been released. You could use the app build from the `main` branch to verify your changes. If at all you need an APK, you could use the one I built from `main` just today [[link](https://drive.google.com/file/d/145yaK0dYaPql-zecs951iLVMXrgz1MYp/view?usp=sharing)].

> But if something is wrong with the leaderboard, that's probably caused by the migration I did.

I just tried out and Leaderboard seems to be working fine for me. There's the caveat that I'm not an ardent user of that screen, thought. @nicolas-raoul or others may be able to be able to give more precise feedback 🙂 

In any case, thanks a lot again for helping out!

**Comment by whym** [comment]
> If at all you need an APK, you could use the one I built from main just today 

Thanks a lot. I tried it and it seems to work well, including the contributions tab. A positive sign that we can start taking steps to merging the two Commons app tools, perhaps sooner than I thought.

**Comment by nicolas-raoul** [comment]
I can confirm that the leaderboard is working great! :-)

**Comment by whym** [comment]
It looks like we can close this, thanks everyone.

There are some remaining tasks I found during the migration (but I think these can be worked on later individually):

- Have a clear license (ongoing at https://github.com/commons-app/commonsmisc/pull/23)
- Commit the changes: https://github.com/commons-app/commonsmisc/issues/24
- Add protection against abuses (I have some more concrete ideas about those abuses but won't go into details here for obvious reasons)
- Refactor the scripts - we can serve endpoints from one script, rather than having one file per end point (This might need some more discussion)

**Comment by sivaraam** [comment]
Thank you very much for helping with this @whym ! 🙂
