### ISSUE TITLE
Autoload gallery when scrolling, instead of showing always 500 files

### ISSUE THREAD

**Issue by Halibutt** [commons-app/apps-android-commons#52]
When installing the app from scratch, one can log in to Commons. Then the process of scanning uploaded files starts. Yet, it never goes past 500 files uploaded: the text above still says "Scanning", or something along the lines, but the counter stops at 500. When I try to upload a file it crashes (another bug apparently, already reported), but the counter goes one up (apparently it counts failed uploads?)

**Comment by misaochan** [comment]
Hi @Halibutt ,

Is this still a problem in the current version of the app?

Thanks!

**Comment by Halibutt** [comment]
Kind of. This time it stopped at 498 :/

**Comment by misaochan** [comment]
@Halibutt wow, interesting. I've included this bugfix in the list of improvements that I plan to make in my IEG [proposal](https://meta.wikimedia.org/wiki/Grants:IEG/Improve_%27Upload_to_Commons%27_Android_App). I'll start looking into it as soon as I can.

**Comment by misaochan** [comment]
Hi @Halibutt ,

Could you please post the crash logs for this? I tried looking at our old crash reports but couldn't seem to find your issue there.

**Comment by misaochan** [comment]
Ah, okay, I figured out what's causing this. It's this method in ContributionsSyncAdapter.java 

```
    private int getLimit() {
        return 500; // FIXME: Parameterize!
    }
```

@nicolas-raoul how do you think we should fix this? I could just increase the limit, but would that work well? Maybe we could have a setting where the user can select his/her own limit?

**Comment by nicolas-raoul** [comment]
If I understand correctly, when the app is opened, it creates the UI slots for 500 pictures, but only actually downloads them if you scroll.
So, increasing this limit does not cost bandwidth, right?
There might be a cost in terms of CPU, memory and loading time though.

I don't think it is worth confusing users with another setting.

I don't think many people use the app to review the pictures they have uploaded months ago, but I could be mistaken? @Halibutt do you often do that, and if yes would you mind telling us why? It might enlighten us on alternative usages of the app.

Of course, the best would be to create the UI little by little, I remember watching a tutorial video about this.

**Comment by misaochan** [comment]
Ah, okay. When I tested with a limit of 1000, there wasn't any noticeable difference in loading time or resources used. But maybe that is because I only have 148 pics (not sure if the extra costs kick in if you are below the original limit or not).

Should I just leave the limit at 500 then, or increase it to 1000 for now?

**Comment by nicolas-raoul** [comment]
I believe that 500 should be enough for most people for now, unless Halibutt gives us good reasons to think otherwise.
I make this an enhancement to make the list length dynamic

**Comment by misaochan** [comment]
Okay, sure thing.
