### ISSUE TITLE
Add a privacy statement

### ISSUE THREAD

**Issue by whym** [commons-app/apps-android-commons#520]
With the Nearby feature using queries sent to Wikidata, (#289) I believe we have privacy issues to consider, for example the accidental disclosure of sensitive locations of the user (e.g. home address).

In my opinion, we should make sure that users are aware of the fact that:

1. the app may disclose the current location of the user's device to the Wikidata server when querying nearby places. <s>(And maybe explicitly ask the user to agree with the Terms of Use of the WMF?)</s>
2. the app may disclose the current location of the user's the device to the core app developers subscribed to the private mailing list when sending crash reports. (I believe the current app doesn't include coordinates to an error message, but it may happen in future.)

For developers, I would imagine something like:

1. Developers may use personal information obtained from the user only for the purpose of improving this app.
2. Developers may not disclose personal information obtained from the user.

I'm not sure in what way we want to deliver such a statement to the user. Maybe a wiki page and a link from the About screen to it? A dialog before a relevant action (e.g. sending a query) is done?

**Comment by misaochan** [comment]
Sounds good. I'd go with a wiki page, or maybe a brief disclaimer in About. I don't think it warrants interrupting the user with a dialog - but that's just my personal opinion.

**Comment by nicolas-raoul** [comment]
How do the other WMF apps do this (if they have a nearby feature)?

**Comment by whym** [comment]
It appears that they link to a privacy policy page from Login and AccountCreation.

```
app/src/main/java/org/wikipedia/createaccount/CreateAccountActivity.java-198-    }
app/src/main/java/org/wikipedia/createaccount/CreateAccountActivity.java-199-
app/src/main/java/org/wikipedia/createaccount/CreateAccountActivity.java:200:    public void showPrivacyPolicy(View v) {
app/src/main/java/org/wikipedia/createaccount/CreateAccountActivity.java:201:        FeedbackUtil.showPrivacyPolicy(this);
app/src/main/java/org/wikipedia/createaccount/CreateAccountActivity.java-202-    }
app/src/main/java/org/wikipedia/createaccount/CreateAccountActivity.java-203-
--
app/src/main/java/org/wikipedia/login/LoginActivity.java-122-    }
app/src/main/java/org/wikipedia/login/LoginActivity.java-123-
app/src/main/java/org/wikipedia/login/LoginActivity.java:124:    public void showPrivacyPolicy(View v) {
app/src/main/java/org/wikipedia/login/LoginActivity.java:125:        FeedbackUtil.showPrivacyPolicy(this);
app/src/main/java/org/wikipedia/login/LoginActivity.java-126-    }
app/src/main/java/org/wikipedia/login/LoginActivity.java-127-
--
app/src/main/java/org/wikipedia/util/FeedbackUtil.java-91-    }
app/src/main/java/org/wikipedia/util/FeedbackUtil.java-92-
app/src/main/java/org/wikipedia/util/FeedbackUtil.java:93:    public static void showPrivacyPolicy(Context context) {
app/src/main/java/org/wikipedia/util/FeedbackUtil.java:94:        visitInExternalBrowser(context, Uri.parse(context.getString(R.string.privacy_policy_url)));
app/src/main/java/org/wikipedia/util/FeedbackUtil.java-95-    }
app/src/main/java/org/wikipedia/util/FeedbackUtil.java-96-

app/src/main/res/layout/activity_create_account.xml-83-
app/src/main/res/layout/activity_create_account.xml-84-            <TextView
app/src/main/res/layout/activity_create_account.xml:85:                android:id="@+id/privacy_policy_link"
app/src/main/res/layout/activity_create_account.xml-86-                android:layout_width="wrap_content"
app/src/main/res/layout/activity_create_account.xml-87-                android:layout_height="wrap_content"
app/src/main/res/layout/activity_create_account.xml-88-                android:layout_gravity="bottom|center_horizontal"
app/src/main/res/layout/activity_create_account.xml-89-                android:padding="8dp"
app/src/main/res/layout/activity_create_account.xml:90:                android:text="@string/privacy_policy_description"
app/src/main/res/layout/activity_create_account.xml-91-                android:textAppearance="?android:attr/textAppearanceSmall"
app/src/main/res/layout/activity_create_account.xml-92-                android:textColor="?attr/link_color"
app/src/main/res/layout/activity_create_account.xml-93-                android:clickable="true"
app/src/main/res/layout/activity_create_account.xml:94:                android:onClick="showPrivacyPolicy"
app/src/main/res/layout/activity_create_account.xml-95-                />
app/src/main/res/layout/activity_create_account.xml-96-
--
app/src/main/res/layout/activity_wiki_login.xml-52-
app/src/main/res/layout/activity_wiki_login.xml-53-        <TextView
app/src/main/res/layout/activity_wiki_login.xml:54:            android:id="@+id/privacy_policy_link"
app/src/main/res/layout/activity_wiki_login.xml-55-            android:layout_width="wrap_content"
app/src/main/res/layout/activity_wiki_login.xml-56-            android:layout_height="wrap_content"
app/src/main/res/layout/activity_wiki_login.xml-57-            android:layout_gravity="bottom|center_horizontal"
app/src/main/res/layout/activity_wiki_login.xml-58-            android:padding="8dp"
app/src/main/res/layout/activity_wiki_login.xml:59:            android:text="@string/privacy_policy_description"
app/src/main/res/layout/activity_wiki_login.xml-60-            android:textAppearance="?android:attr/textAppearanceSmall"
app/src/main/res/layout/activity_wiki_login.xml-61-            android:textColor="?attr/link_color"
app/src/main/res/layout/activity_wiki_login.xml-62-            android:clickable="true"
app/src/main/res/layout/activity_wiki_login.xml:63:            android:onClick="showPrivacyPolicy"
app/src/main/res/layout/activity_wiki_login.xml-64-            />
app/src/main/res/layout/activity_wiki_login.xml-65-

```

**Comment by whym** [comment]
> And maybe explicitly ask the user to agree with the Terms of Use of the WMF?

Considering all users of the app has a WMF account, this is probably unnecessary.

**Comment by whym** [comment]
They link to https://wikimediafoundation.org/wiki/Privacy_policy.

Interestingly the page already talks about the Commons app.

> For example, if you want to upload a photo on the Wikimedia Commons mobile app, we may receive metadata, such as the place and time you took the photo, automatically from your device. Please be aware that, unlike location information collected using GPS signals described above, the default setting on your mobile device typically includes the metadata in your photo or video upload to the Wikimedia Sites.

**Comment by IanvsPoplicola** [comment]
Hi there, I'm interested in working on this issue - has there been a decision on what exactly is to be implemented for it? Any advice on where and how to get started with the implementation is also most welcome!

**Comment by aumassart** [comment]
@lanvsPoplicola
I already started previous week to work a little bit on this issue. I am new on this project and I chose this issue as a first one to enter in the code. So, if you want, we can work together on it and exchange ideas as a first experience on this project

**Comment by aumassart** [comment]
What I have done for now is that I added a Privacy Statement link to the page https://wikimediafoundation.org/wiki/Privacy_policy in the subscribe page. You can see the view of the subscribe page now : 

![login](https://user-images.githubusercontent.com/12572789/32185866-bc6224b6-bda0-11e7-9736-fe29ee1fe5c8.png)

So, when the user want to connect or subscribe, there is this link to the privacy statement in order to inform it. 
I'm open to exchange ideas about it

**Comment by IanvsPoplicola** [comment]
@aumassart that's cool, I'll leave this to you then! Looks like you're well on track of resolving it :)

**Comment by misaochan** [comment]
Hi @aumassart , thanks for your interest! Unfortunately we cannot use WMF's privacy policy - see #891 for the reasons. I would recommend that you submit your PR using the https://github.com/commons-app/apps-android-commons/wiki/Privacy-policy link instead (that is still in draft mode, but should be fixed up shortly). :)

**Comment by aumassart** [comment]
@misaochan thanks for your answer. I didn't see that. I will then change the privacy policy link to refer instead to the one you mention. :)

@IanvsPoplicola I hope you are finding an other issue that interests you a lot :)

**Comment by Sylvia23** [comment]
I would like to work on this issue if it is still open.

Can someone explain exactly what has to be implemented to resolve this because I can already see "Privacy policy" link on the login page which refers to [https://github.com/commons-app/apps-android-commons/] 

![screenshot from 2018-01-23 11-43-57](https://user-images.githubusercontent.com/23060217/35275154-c99fc65e-0064-11e8-9b70-2e4afadfdd1d.png)

**Comment by misaochan** [comment]
Oops, sorry, I think this should have been closed. Indeed the link has already been implemented. Please feel free to try your hand at other open issues @Sylvia23 .

**Comment by Sylvia23** [comment]
For sure @misaochan  :+1: 
Thanks.
