### ISSUE TITLE
Error while setting up project in Android Studio

### ISSUE THREAD

**Issue by rohit9625** [commons-app/apps-android-commons#5201]
Whenever I try to build a project it shows this error:-

Failed to find Platform SDK with path: platforms;android-31
<img width="960" alt="Screenshot 2023-04-04 143444" src="https://user-images.githubusercontent.com/101377978/229743355-f06b5ad7-4651-4c1b-acfc-ae83d75f05f0.png">

**Comment by kartikaykaushik14** [comment]
Hi,

Please try the following - 

1. File -> Settings -> Appearance & Behavior -> System Settings -> Android SDK
2. Under the SDK Platforms section scroll down to find the "Android 12.0 (S)" (API level 31) option and make sure it is checked.
3. If it is not checked, check it and click on the "Apply" button to download and install the required platform.
4. If it is already checked, click on the "Show Package Details" checkbox and make sure that the "Android SDK Platform 31" option is checked. If not, check it and click on the "Apply" button to install it.
5. Once the installation is complete, try building your project again.

Please let me know if it works.

**Comment by nicolas-raoul** [comment]
I assume this is solved, thanks Kartikay for helping!
