### ISSUE TITLE
Fix unit test UploadMediaPresenterTest.handleImageResult

### ISSUE THREAD

**Issue by shankarpriyank** [commons-app/apps-android-commons#5204]
### Summary

The unit test handleImageResult in regularly failing in CI.

### Steps to reproduce

Run the GitHub actions workflow

### Expected behaviour

The test should actually pass

### Actual behaviour

The test fails.
And when I ran the test locally it again failed with this error
```
view.showBadImagePopup(
    <any integer>,
    uploadItem
);
Wanted 1 time:
-> at fr.free.nrw.commons.upload.UploadMediaPresenterTest.handleImageResult(UploadMediaPresenterTest.kt:160)
But was 2 times:
-> at fr.free.nrw.commons.upload.mediaDetails.UploadMediaPresenter.handleBadImage(UploadMediaPresenter.java:339)
-> at fr.free.nrw.commons.upload.mediaDetails.UploadMediaPresenter.handleBadImage(UploadMediaPresenter.java:339)


org.mockito.exceptions.verification.TooManyActualInvocations: 
view.showBadImagePopup(
    <any integer>,
    uploadItem
);
Wanted 1 time:
-> at fr.free.nrw.commons.upload.UploadMediaPresenterTest.handleImageResult(UploadMediaPresenterTest.kt:160)
But was 2 times:
-> at fr.free.nrw.commons.upload.mediaDetails.UploadMediaPresenter.handleBadImage(UploadMediaPresenter.java:339)
-> at fr.free.nrw.commons.upload.mediaDetails.UploadMediaPresenter.handleBadImage(UploadMediaPresenter.java:339)
```

### Android version

NA

### Commons app version

NA

### Would you like to work on the issue?

None

**Comment by RitikaPahwa4444** [comment]
Seems like an issue with the usage of bitwise and in the code. It is returning the same values twice, thereby invoking `handleBadImage()` twice.

**Comment by nicolas-raoul** [comment]
Probably related to https://github.com/commons-app/apps-android-commons/pull/5192#issuecomment-1495970246

**Comment by shankarpriyank** [comment]
Yup, `handleBadImage() `is getting called two times and the in the test it is expected to be called only once

**Comment by nicolas-raoul** [comment]
I just disabled the test for now, anyone please feel free to send a pull request for a real fix, thanks! :-)

**Comment by RitikaPahwa4444** [comment]
May I take this up?

**Comment by nicolas-raoul** [comment]
Sure, thanks a lot! :-)
