### ISSUE TITLE
[Bug]: Author's Name not visible as expected in few cases

### ISSUE THREAD

**Issue by kartikaykaushik14** [commons-app/apps-android-commons#5207]
### Summary

I observed that the Author's name isn't visible as expected in a few cases. 

### Steps to reproduce

1. Open the app
2. Skip the login
3. In the featured tab, open an image
4. Observe the author's name. 

The issue doesn't occur in all photos, and the above steps may have to be performed for multiple images.

### Expected behaviour

The author's Name should be visible without the tags and title.

### Actual behaviour

The author's name has tags and title

### Device name

Pixel 6

### Android version

Android 33

### Commons app version

master

### Screen-shots

![Screenshot 2023-04-12 at 10 48 22 PM](https://user-images.githubusercontent.com/93285364/231637107-f1e5eb41-6f8f-47bc-b677-88958021c615.png)
![Screenshot 2023-04-12 at 10 44 51 PM](https://user-images.githubusercontent.com/93285364/231637110-ae54feab-2c3f-4b42-b437-7bd711016052.png)

### Would you like to work on the issue?

Yes

**Comment by RitikaPahwa4444** [comment]
Is this related to #5030?

**Comment by kartikaykaushik14** [comment]
Oh! Thanks for pointing that out.

Closing issue since it's a duplicate.
