### ISSUE TITLE
[Bug]: Uploads fail

### ISSUE THREAD

**Issue by cdman** [commons-app/apps-android-commons#5216]
### Summary

This app used to work for me in the past, but since about a year ago all uploads fail. It doesn't matter if I'm on wifi or (good quality) mobile data connection, it starts uploading it and then sends an error notification saying "Failed to upload [entry name]". 

### Steps to reproduce

Try uploading a picture.

### Expected behaviour

For the picture to be uploaded.

### Actual behaviour

After a while I get an error notification.

### Device name

Googel Pixel 6 Pro

### Android version

Android 13

### Commons app version

4.0.5~f03b7dd8d

### Device logs

API level: 33
Android version: 13
Device manufacturer: Google
Device model: Pixel 6 Pro
Device: raven
Network type: wifi
App version name: 4.0.5~f03b7dd8d
User name: Cd-MaN83

### Would you like to work on the issue?

None

**Comment by dhanushgowdahm** [comment]
i would like to work on this issue

**Comment by cdman** [comment]
Sorry, a bit late to the party, but can confirm that the app works as expected now. Thank you.
