### ISSUE TITLE
[Bug]: Media details is blanked when editing caption alone

### ISSUE THREAD

**Issue by sivaraam** [commons-app/apps-android-commons#5218]
### Summary

The app seems to completely blank the picture's details (description, location, categories) when using the Edit caption feature to edit the caption alone of an uploaded image. An example could be found in the following picture: https://commons.wikimedia.org/wiki/File:Sunset_view_from_Samanar_hills.jpg

When you look at the history, the edits with "Updating Description" completely nuke the media details of the file. If you look closely each such edit is made from the app and is associated with an edit of the caption.

### Steps to reproduce

1. Open an uploaded image from Contributions screen
2. Tap on the edit description button
3. Change the caption of an image leaving everything else intact
4. Hit "Submit"

### Expected behaviour

Only the caption should be updated.

### Actual behaviour

All media details such as description, location, caption are nuked. 

### Device name

OnePlus Nord

### Android version

Android 12

### Commons app version

master @ 1649d1e2ce1866d14c3225f07e55ff34123cf7d4

### Screen-shots

<details><summary>Recording of the issue</summary>
<p>

https://github.com/commons-app/apps-android-commons/assets/12448084/64055de2-bf94-422d-a3ef-e83af3765970

</p>
</details> 

### Would you like to work on the issue?

Prefer not

---
See also, report of this issue [on-wiki](https://commons.m.wikimedia.org/w/index.php?title=Commons_talk:Mobile_app&diff=prev&oldid=835167169&title=Commons_talk%3AMobile_app&diffonly=1)

**Comment by gururani-abhishek** [comment]
Hey @sivaraam, I want to work on this issue.

**Comment by gururani-abhishek** [comment]
Update on when I tried reproducing issue by editing just the caption, 

https://user-images.githubusercontent.com/59947871/235732952-827eccfc-383d-4bec-a595-d61895ca5ca8.mp4

**Comment by sivaraam** [comment]
> Update on when I tried reproducing issue by editing just the caption,
> proofWiki.mp4

So, it shows no description for you in the edit page but then after you submit the description is left intact. Interesting :thinking:

May be try having caption and description for the image in two languages? The image I faced a problem with had caption and description in 2 languages.

**Comment by sivaraam** [comment]
@gururani-abhishek Just checking to know if you were able to get any leads regarding this issue ? 🙂

**Comment by KorelU** [comment]
Hey there at @sivaraam I tried recreating this issue myself using the same caption, description, and image you provided, however I did not get the same issue you had. 

https://github.com/commons-app/apps-android-commons/assets/140857681/b85189b4-c683-432a-b94a-9b435f5dcbd3

Do you recall anything else about how you were able to find this bug?
Ill do my best to see if I can figure out what's wrong!

**Comment by sivaraam** [comment]
@KorelU Excuse the delayed response. I certainly do observe the bug stil. I've added a recording to the description. Kindly check the same.

Also, a few things: 

1. Which version of the app are you trying this with ?
2. Could you try editing the description of the other language?

**Comment by ZIYANGSONG2003** [comment]
Hello, I would like to try to resolve this issue if possible.

**Comment by ZIYANGSONG2003** [comment]
![image](https://github.com/commons-app/apps-android-commons/assets/110000045/af9c0b21-2f04-4777-b4d3-e7b7fc9f8579)
![image](https://github.com/commons-app/apps-android-commons/assets/110000045/e5a3772b-4d76-431a-9a4d-4ba4de469773)
![image](https://github.com/commons-app/apps-android-commons/assets/110000045/a41f7f1d-555d-4de3-be55-8fc7fff2f283)

When I tried to upload an image, an error occurred and the upload failed. It seems to be a stack error. I would like to ask if there is any way to solve this problem in the past.

**Comment by ZIYANGSONG2003** [comment]
![faff61d5cefdce8cda3815ae7ebb1b6](https://github.com/commons-app/apps-android-commons/assets/110000045/0cb13727-44fb-425f-9eed-2b4fa71bd4c4)
I think we need to modify the description of this issue. After actually trying it, I found that the real problem is that when you do not fill in the description, if you change the caption at this time, the caption will not change after submission. I think this is why some people have not successfully reproduced this issue.

**Comment by sivaraam** [comment]
> When I tried to upload an image, an error occurred and the upload failed. It seems to be a stack error.

Do you mean you get the mentioned exception for all your uploads ?

> I would like to ask if there is any way to solve this problem in the past.

Could you clarify a bit on what you mean by solve the problem in the past ? 🤔

**Comment by nicolas-raoul** [comment]
@ZIYANGSONG2003 Any progress to share? :-)

**Comment by sivaraam** [comment]
This has also been reported to us on-wiki. [ [ref](https://commons.m.wikimedia.org/w/index.php?title=Commons_talk:Mobile_app&diff=prev&oldid=835167169&title=Commons_talk%3AMobile_app&diffonly=1) ]

**Comment by sofiacharatsi** [comment]
Hello, if no one is assigned on this issue I would really like to work on it with @EleniVasilaki  if possible.

**Comment by EleniVasilaki** [comment]
> Hello, if no one is assigned on this issue I would really like to work on it with @EleniVasilaki if possible.

We are really keen to resolve it if feasible

**Comment by sivaraam** [comment]
Sure. Could you either confirm that you could reproduce the issue? It would be great if you could post a screen recording.

**Comment by sofiacharatsi** [comment]
Hi, @sivaraam the first time we tried we managed to successfully reproduce the issue getting the results shown in the screenshots however we made several other attempts to reproduce it and none of them were successful.
![437951128_284270644729916_127322808250332049_n](https://github.com/commons-app/apps-android-commons/assets/117755881/fbe77784-300a-4963-8377-fcaa0c9235d7)
![437864714_439813915393635_7952285164759113545_n](https://github.com/commons-app/apps-android-commons/assets/117755881/2de6fb83-679e-423f-ad7e-ee6358e98faf)

**Comment by sivaraam** [comment]
> Hi, @sivaraam the first time we tried we managed to successfully reproduce the issue getting the results shown in the screenshots however we made several other attempts to reproduce it and none of them were successful. 

This is indeed unfortunate. Could you try reaching out to the on-wiki user who faced [the issue](https://commons.m.wikimedia.org/wiki/Commons_talk:Abuse_filter/Archive_2023/12#c-Jonathanischoice-20231226025400-Report_by_Jonathanischoice) to see if you could get a possible set of steps which caused the bug for them?

**Comment by djbloop** [comment]
Hey there. Could I be assigned to this issue?

**Comment by sivaraam** [comment]
Any updates on your progress @djbloop ?

**Comment by chrisdebian** [comment]
@djbloop Is this still an issue with the current release? Can it be closed?

Thanks,

Chris.

**Comment by djbloop** [comment]
Hey @chrisdebian ,

Sorry for not replying sooner. This semester at university has been hectic, to say the least, and I forgot. I checked again, and I don't see the issue presenting itself. So, in my best judgment, this can be closed.

Regards,
@djbloop

**Comment by nicolas-raoul** [comment]
I can not reproduce the issue: https://commons.m.wikimedia.org/w/index.php?title=File%3AJapanese_Red_Cross_Medical_Center_-50660.jpeg&diff=971851582&oldid=971849766

**Comment by sivaraam** [comment]
Re-opening this given this also came up via a user feebdack [[ref](https://commons.wikimedia.org/wiki/Commons:Mobile_app/Feedback#Feedback_from_%D0%9C%D0%B0%D1%80%D0%B8%D0%BD%D0%B0%D0%B4_01_for_version_5.5.0~9eff9e8e8_on_2025/07/03_21:06:31)]

**Comment by sivaraam** [comment]
Steps mentioned in [the user feedback](https://commons.wikimedia.org/wiki/Commons:Mobile_app/Feedback#c-%D0%9C%D0%B0%D1%80%D0%B8%D0%BD%D0%B0%D0%B4_01-20250704122800-Kaartic-20250704105500):
1. Opened the "Overview" tab (I can’t see what it’s called in English, it looks like a planet in the middle of the panel at the bottom of the screen)
1. Clicked on the image in the "Featured" section
1. Clicked on the pencil icon to change the caption and description. At this moment the caption was displayed in English, but the description didn't
1. Returned to the image page to look at the English description. Maybe I also returned to the section and then opened the image again, I'm not sure
1. Followed the link that is in the English description to see the Wikipedia article and find out in which languages ​​it is available
1. Returned to the Wikimedia Commons app, again clicked on the pencil icon, added a field for signature and description in Russian
1. Closed the app to google the image object and see how it is usually translated in sources
1. Returned to the Wikimedia Commons app, entered a signature and description, saved the edit


<details><summary>Original in Russian</summary>
<p>

Не знаю, что из этого важно, но вот что я делала:

1. Открыла вкладку "Обзор"
1. Нажала на изображение в разделе "Избранное"
1. Нажала на значок карандаша, чтобы изменить подпись и описание. На английском в этот момент отображалась подпись, но не описание
1. Вернулась на страницу изображения, чтобы посмотреть на английское описание. Может быть, ещё вернулась в раздел, а потом снова открыла изображение, точно не помню
1. Перешла по вики-ссылке, которая была в английском описании, на статью в Википедии и посмотрела, на каких языках доступна эта статья
1. Вернулась в приложение Викисклада, снова нажала на значок карандаша, добавила поле для подписи и описания на русском
1. Свернула приложение, чтобы погуглить объект изображения и посмотреть, как обычно его переводят в источниках
1. Вернулась в приложение Викисклада, ввела подпись и описание, сохранила правку

Надеюсь, это как-то поможет 

</p>
</details>

**Comment by Kota-Jagadeesh** [comment]
is this still reproducible? i followed the exact steps to reproduce the issue, but i couldn't reproduce the bug
