### ISSUE TITLE
[Bug]: in the details of a photo tapping on license doesn't redirect to the License link(wiki link, for example)

### ISSUE THREAD

**Issue by gururani-abhishek** [commons-app/apps-android-commons#5219]
### Summary

When you tap on the license of a photo, it doesn't redirect to the license wiki page, or external link. It rather says, "Error! url not found". 

### Steps to reproduce

1. Open app
2. Tap on any of your contributed photo
3. In the bottom of the page, tap on License (i)

### Expected behaviour

user should be redirected to the License link 

### Actual behaviour

a toast prompts : "Error! url not found"

### Device name

Pixel 2

### Android version

API Level 33

### Commons app version

4.1.0-debug-master

### Screen-shots

https://user-images.githubusercontent.com/59947871/235728857-6c5a9b51-7d9f-497b-a1f2-d3ad1d52fbff.mp4

### Would you like to work on the issue?

None

**Comment by RitikaPahwa4444** [comment]
Hi @gururani-abhishek, I think the upload process has not finished yet (as I could figure out from the video) and the licence information will not be available in case the image has not been uploaded on the server. For me, the licence page opens for the pictures that have got uploaded on the server completely. Is that opening for you too, once the upload process gets completed?

**Comment by gururani-abhishek** [comment]
You're right, I'll close the issue. One question though, how long does it usually take to upload an image?

**Comment by nicolas-raoul** [comment]
Uploading a 3 megabytes pictures does not take more than 5 minutes, even on a slow connection. If it takes more, this might be a bug. I f you are trying to reproduce another bug, you may want to cancel and try again, or upload a different picture.
