### ISSUE TITLE
Reduce minSdk back to 21

### ISSUE THREAD

**Issue by sivaraam** [commons-app/apps-android-commons#5223]
In order to handle a play store policy requirement (see #5031) we had to bump the minSdk to API 29. As per [Nicolas' stats](https://github.com/commons-app/apps-android-commons/issues/5031#issuecomment-1221294006) from approx. 6 months ago, 2347 of our users will not get an app update.

For the sake of broader reach, it would be nice if we explore alternative ways to still support API 21 without violating the Google Play policy.

**Comment by dbrant** [comment]
(the Play Store policy is referring to your _target_ SDK, not your minimum SDK. I'm not sure there was ever a need to bump your minimum SDK to 29.)

**Comment by nicolas-raoul** [comment]
@dbrant Thanks for checking! You are right that usually it is all about  target SDK, but here increasing minimum SDK is really what allowed us to publish, I believe: the Play policy is stricter for apps that target less secure versions of Android.

Play's policy question is “_Does your app access location in the background in APKs or app bundles **targeting Android 9 or older**?_"

If we answer "_yes_", then we must implement really inconvenient things, it seems.

I wrote more at https://github.com/commons-app/apps-android-commons/issues/5031#issuecomment-1221294006

**Comment by sivaraam** [comment]
@dbrant Thanks for the clarifications! I gave a read of the corresponding [policy help page](https://support.google.com/googleplay/android-developer/answer/9799150?hl=en). Here's the relevant portion (which is also covered in the [Q&A linked by Nicolas](https://stackoverflow.com/a/67392120/5614968)):

> If you don’t see the declaration prompt in Google Play Console, confirm that you’re using one of the sensitive location permissions according to the target SDK level of your app:
> 
>  - If your app bundle or APK targets Android 10 or newer (SDK level 29 or higher) and contains ACCESS_BACKGROUND_LOCATION permission in the manifest, you’ll be directed to complete details on location usage.
>  -  If your app bundle or APK targets Android 9 or older (SDK level 28 or lower) and contains either ACCESS_COARSE_LOCATION or ACCESS_FINE_LOCATION, you will need to indicate your intention to access location in the background and then you’ll be directed to complete details on location usage.

Combining this with what you've said, it seems like we should be answering a "*No*" for the question "*Does your app access location in the background in APKs or app bundles targeting Android 9 (Pie) or older (SDK level 28 or lower)?*" in the console. I say that because our [`targetSdkVersion` is 31](https://github.com/commons-app/apps-android-commons/blob/master/app/build.gradle#L181) and we _do not_ request for the `ACCESS_BACKGROUND_LOCATION` permission. Let me know if I got anything wrong.

I actually checked the console and it seems to me like we already (correctly) answer "No" there. So, we don't have anything to do there.

Given this, I believe we are not even in a need to show a prompt for describing background location access. Hypotetically, even if we were required to show the prompt we can't give a proper reason to the user because we **never access location in the background** :-)

To conclude, I think it should safe for us to reduce the minSdk back to 21. I'm planning to put up an MR reducing minSdk 21. Once that's merged, we could do publish a release and see how it goes.

Let me know your thoughts.

**Comment by sivaraam** [comment]
On a side note, the CI pipeline fails for `master` ever since we bumped the minSdk to 29 because our CI environment currently tries to run the tests on API 24 device which is incompatible. It should hopefully be resolved once we reduce minSdk back to 21.

**Comment by sivaraam** [comment]
Just wanted to note here that the versions of the app which bumped minSdk down to 21 (e.g. v4.2.1) have been successfully published to play store. So, I think we're good here :-)
