### ISSUE TITLE
fr.free.wrw.commons (androidTest) not working because many unresolved references in code.

### ISSUE THREAD

**Issue by VinzRoosen** [commons-app/apps-android-commons#5226]
### Description

When im trying to run any androidTests. There are many unresolved references and the tests cant be run.

![afbeelding](https://github.com/commons-app/apps-android-commons/assets/125285295/7d985b90-c0ff-4087-b598-6051affc319f)

![afbeelding](https://github.com/commons-app/apps-android-commons/assets/125285295/bf9b02de-fb82-4dbc-81e7-8d6865fed6fd)

After adding the dependency 'apps-android-commons.app.main' everything seems to work.
Can anyone tell me if this is normal and the normal way of working or am I doing something wrong?

**Comment by sivaraam** [comment]
@VinzRoosen Could you elaborate a bit on how you ran the tests ? That would help in understanding the issue better.
