### ISSUE TITLE
Tutorial messages use line breaks instead of '\n' after being translated

### ISSUE THREAD

**Issue by antonv6** [commons-app/apps-android-commons#523]
Tutorial messages that use `\n` for stylistic purposes actually appear in https://translatewiki.net as if having actual line breaks. Here's an example original message:
```
  <string name="tutorial_2_subtext">- Natural objects (flowers, animals, mountains)\n- Useful objects (bicycles, train stations)\n- Famous people (your mayor, Olympic athletes you met)</string>
```
Shows as https://i.imgur.com/PYVYX4A.png

And naturally gets translated into:
```
  <string name="tutorial_2_subtext">- Objets naturels (fleurs, animaux, montagnes) 
- Objets utiles (bicyclettes, gares ferroviaires) 
- Personnes célèbres (votre maire, les athlètes olympiques que vous avez rencontrés)</string>
```
The problem? It seems that the thing that lays out text in android only respects `\n` and not actual line breaks, which means that the dashes that supposed to be list bullets appear _mid-line_.

Live example (using a different string, because it looks worse): https://i.imgur.com/SYYvbU7.png

Since translations come from https://translatewiki.net, it could be a problem on their side, but it may be easy to work around this for now.

**Comment by misaochan** [comment]
Ah, wow. I saw that happen when we first integrated translatewiki, but I thought it had been fixed.

Pinging @Nikerabbit , do you know why this is still happening?

**Comment by Nikerabbit** [comment]
This should be fixed now.

**Comment by misaochan** [comment]
Could anyone confirm that this works in their language?

**Comment by antonv6** [comment]
Works for me in French and Russian (version 2.4.2).

**Comment by Nikerabbit** [comment]
I believe most if not all of them were fixed in https://github.com/commons-app/apps-android-commons/commit/6a5629186b8fb9086fcdb6f0aa96731662614054.

**Comment by misaochan** [comment]
Awesome, thanks!
