### ISSUE TITLE
MCS API to be decomissened on July 2023 

### ISSUE THREAD

**Issue by mnalis** [commons-app/apps-android-commons#5239]
### Summary

According to this URL:
https://lists.wikimedia.org/hyperkitty/list/mediawiki-api-announce@lists.wikimedia.org/thread/ZBYSZ4VQYIVZFOCEUNCL3ZSSIEECBK6H/

> TL;DR: The legacy Mobile Content Service is going away in July 2023. Please
switch to Parsoid or another API before then to ensure service continuity.
>
>I'm writing about a service decommission we hope to complete mid-July 2023.
The service to be decommissioned is the legacy Mobile Content Service
("MCS"), which is maintained by the Wikimedia Foundation's Content
Transform Team. We will be marking this service as deprecated soon.
>
>We hope that with this notice, people will have ample time to update their
systems for use of other endpoints such as Parsoid [1] (n.b., MCS uses
Parsoid HTML).
>
>The MCS endpoints are the ones with the relative URL path pattern
/page/mobile-sections* on the Wikipedias. For examples of the URLs see the
"Mobile" section on the online Swagger (OpenAPI) specification
documentation with matching URLs here:
>
>https://en.wikipedia.org/api/rest_v1/#/Mobile
> [...]

However, those URLs with `/page/mobile-sections` still seem to be used in Commons app:

```
./data-client/src/main/java/org/wikipedia/dataclient/RestService.java:    String ACCEPT_HEADER_MOBILE_SECTIONS = ACCEPT_HEADER_PREFIX + "mobile-sections/0.12.4\"";
./data-client/src/main/java/org/wikipedia/dataclient/RestService.java:    String REST_PAGE_SECTIONS_URL = "page/mobile-sections-remaining/{title}";
./data-client/src/main/java/org/wikipedia/dataclient/RestService.java:    @GET("page/mobile-sections-lead/{title}")
```

### Steps to reproduce

API (that seems to be used by Commons app) is deprecated and about to be decommissioned in less than a month.

(it is possible that those strings are some benign leftovers which can be safely removed; but it is also possible that the decommissioning of that API will break things. It should probably be addressed in either case)

### Expected behaviour

Commons app should not use deprecated API that is about to be decommissioned

### Actual behaviour

Commons app seems to use MCS API that is about to be decomissioned

### Device name

n/a

### Android version

n/a

### Commons app version

4.1.0~1649d1e2c

### Would you like to work on the issue?

None

**Comment by sivaraam** [comment]
Thanks for the notification! This is being tracked via #5165. So, closing this one :-)
