### ISSUE TITLE
Upload Wizard: Let user remove picture location

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#5247]
The `Media Details` step has a location editor, but no way to _remove_ location, for instance for privacy purposes.

This is problematic when using the in-app camera to take a picture you do not want to share the location of (example:vegetable in your kitchen).

The current workaround would be to edit the location to somewhere else, which may or may not be a good idea.

Removing location is a rare use-case, so it should not be an additional step in the upload process, rather it could be an additional `Remove location` button (with a disclaimer `Location makes pictures more useful and findable. Do you really wish to remove location from this picture?`) in this dialog which can be reached by tapping the map icon:

![Screenshot_20230625-222723](https://github.com/commons-app/apps-android-commons/assets/99590/e6f24ff7-8636-4a6e-b2b7-26aab4126b0c)

**Comment by XxBrezxX** [comment]
Hi, is this issue still available? Could you give me more details?

**Comment by nicolas-raoul** [comment]
@XxBrezxX Yes, it is not assigned. In the app are you able to find the screen shown above?

**Comment by XxBrezxX** [comment]
@nicolas-raoul I'm new into this, tomorrow I'll be reading more about the app, and once I got more information I'll check where the screen is, is that ok?

**Comment by nicolas-raoul** [comment]
@XxBrezxX  Great, it is a good idea to first use the app a bit, upload a few pictures, I am sure you will find it :-)

**Comment by XxBrezxX** [comment]
Edit. I was installing android studio and making the project to work on my computer, now it works but I didn't found the screen that you posted

**Comment by nicolas-raoul** [comment]
@XxBrezxX Start uploading any image, then at the caption/description step, tap the map icon.

**Comment by paco-arana** [comment]
I want to give this a go. Is this the right idea for the button and popup?

<img width="563" alt="Screenshot 2023-07-22 at 19 08 56" src="https://github.com/commons-app/apps-android-commons/assets/118578052/8e0458bf-b675-48f8-912c-28149557e61a">
<img width="563" alt="Screenshot 2023-07-22 at 22 49 37" src="https://github.com/commons-app/apps-android-commons/assets/118578052/ce5aeede-bf9e-4efb-9020-2369a7c68c65">

**Comment by nicolas-raoul** [comment]
@paco-arana It looks perfect! :-)

**Comment by adambuchbinder** [comment]
Is this feature request still live? It looks to be stalled out, but it would still be useful to me.

**Comment by nicolas-raoul** [comment]
@adambuchbinder The feature described in this issue would still be extremely useful. Here are the next steps to implement, based on Paco's pull request: https://github.com/commons-app/apps-android-commons/pull/5262#issuecomment-1762778826

@shankarpriyank Are you still interested in working on this? :-)

**Comment by ShashwatKedia** [comment]
@nicolas-raoul I would like to work on this issue if shankarpriyank wouldn't want to :)
