### ISSUE TITLE
Nearby: Allow to open wiki page or Wikidata item

### ISSUE THREAD

**Issue by tobias47n9e** [commons-app/apps-android-commons#526]
When I am looking through the list of items in the Nearby list I would sometimes like to get more information. A short tap opens a menu with apps that can handle coordinates. How about showing a menu on long tap that also contains a link to the Wikidata item?

**Comment by nicolas-raoul** [comment]
Long tap is hard to discover, so on normal tap how about revealing these options:
- Open point in map app
- Open item in browser (Wikidata)
- Open item in browser (Japanese Wikipedia)    <-- if the user's language is Japanese. If an article is available.
- Open item in browser (German Wikipedia)   <-- if the point is situated in Germany (more chances that the article is full of details). If an article is available. If not available and above is not available either, show any language that has an article for this item, with a preference for English as it is a lingua franca.

**Comment by VojtechDostal** [comment]
Yes I think we are putting unnecessary stress on showing the point in map app. @nicolas-raoul 's idea seems the best to me - users can choose what they want to get. I am not sure how the menu could look like - would that be a floating menu opening in the place of the tap? Or below the list?

**Comment by misaochan** [comment]
Agreed. Alternatively we could bring the user to a "Place" screen where they can view all the details of the location within the app itself, including links to the map app? Not sure how easy it is to import the details though.

**Comment by tobias47n9e** [comment]
We could implement detail pages like for example like this Webapp https://www.wikidata.org/wiki/Wikidata:Tools/Monumental

But that might be worth a separate issue.

**Comment by nicolas-raoul** [comment]
I believe this is implemented?
