### ISSUE TITLE
[Bug]: Descriptions in multiple languages should not be separated by comma

### ISSUE THREAD

**Issue by mormegil-cz** [commons-app/apps-android-commons#5260]
### Summary

The `description` parameter in the `{{Information}}` template filled by the application when uploading an image contains description in provided languages, _separated by commas_ (`,`). Which is wrong. The individual `{{en|...}}`, `{{de|...}}` templates used in the description are rendered as blocks, meaning the separating commas are rendered between lines of individual languages, looking terrible.

See e.g. [this upload](https://commons.wikimedia.org/w/index.php?title=File:Cape_Donji_lighthouse_in_Slano.jpg&oldid=781651936).

The languages can be separated by whitespace (e.g. newlines) or not at all.

I believe this error is at `fr.free.nrw.commons.description.DescriptionEditActivity#updateDescription`. Note that the same logic is at multiple places in the application, including `fr.free.nrw.commons.upload#formatList` and `fr.free.nrw.commons.contributions#formatDescriptions`, implemented in a different style every time, but those two are correct and do not use any separator.

### Steps to reproduce

1. Upload an image with descriptions in more than one language.
2. Take a look at the resulting description page.

### Expected behaviour

The descriptions should look fine.

### Actual behaviour

There is a stray comma between every two language versions in the description.

### Device name

Samsung S22

### Android version

Android 13

### Commons app version

4.1.0~1649d1e2c

### Would you like to work on the issue?

None

**Comment by nicolas-raoul** [comment]
Note: I checked a few recent POTD pictures and indeed the norm seems to be no comma, example: https://commons.wikimedia.org/wiki/File:Ratargul_0276.jpg
Anyone feel free to send a pull request, thanks!

**Comment by nicolas-raoul** [comment]
@mormegil-cz This looks fixed to me using Paco's branch: https://commons.wikimedia.org/wiki/File:Kaba_amphibious_bus_in_Odaiba.jpg Any comment? :-)

**Comment by mormegil-cz** [comment]
Sure, that result seems fine.
