### ISSUE TITLE
[Bug]: trying to share geograpic location only works in SOME apps

### ISSUE THREAD

**Issue by mnalis** [commons-app/apps-android-commons#5264]
### Summary

When picture is taken with GPS in Commons app, its metadata contains `Coordinates` on which one can click, which in turns invokes Android sharing functionality asking user to choose which app should receive those coordinates.  However, while sharing such coordinates to some apps (like [OrganicMaps](https://f-droid.org/packages/app.organicmaps/)) works, sharing to other apps (like [Vespucci](https://f-droid.org/en/packages/de.blau.android/) or `Share on OpenStreetMap`) doesn't work, resulting in being positioned on `0,0` coordinates.

### Steps to reproduce

1. Take picture with GPS enabled in commons app
2. open details on such picture
3. click on numeric coordinates in `Coordinates:` fies
4. choose app to share to, and notice that some (like _OrganicMaps_) work, and that others (like _Vespucci) or _"Share on OpenStreetMap"_)  position to `0,0` instead.
5. try sharing `geo:` coordinates from some other app (like _OsmAnd_ or _StreetComplete_) and notice that sharing to **all** apps work correctly (including _Vespucci_ and  _"Share on OpenStreetMap"_)

### Expected behaviour

sharing coordinates to **any** other app should work and position correctly to given coordinates (like it does work for all apps when sharing is done from e.g. `OsmAnd` or `StreetComplete` - perhaps those use different and more reliable API?)

### Actual behaviour

**Some** apps position to given coordinates, but **some** always position to `0,0` instead when coordinates are shared from commons app.

### Device name

Huawei P30Pro

### Android version

Android 10 (EMUI 12)

### Commons app version

4.1.0~1649d1e2c (latest f-droid)

### Device logs

[CommonsAppLogs.zip](https://github.com/commons-app/apps-android-commons/files/12216150/CommonsAppLogs.zip)

### Screen-shots

Here is video

https://github.com/commons-app/apps-android-commons/assets/156656/142041cd-0b16-43cf-b09c-8496f7637e50

notice how at 00:00-00:06 sharing to `OrganicMaps` works correctly, but how it fails for `Share on OpenStreetMap` at 00:07-00:22, and fails for `Vespucci` at 00:24-00:39

### Would you like to work on the issue?

Prefer not

**Comment by nicolas-raoul** [comment]
Thanks @mnalis for reporting this!
I guess we are not using the best intent format.

Would anyone mind trying to use an intent inspection tool (logcat may work) to compare the intents that the OsmAnd, StreetComplete, Commons apps are sending? Thanks!

**Comment by Abdullah-Web-D** [comment]
Check App Permissions:
Ensure that the Commons app has the necessary location and storage permissions to access GPS and share the coordinates with other apps. On Android, you can check and manage app permissions in the device settings.

Update Commons App:
Make sure the Commons app is up to date. Developers often release updates to address bugs and improve compatibility with different devices and apps.

Contact App Developer:
If the issue persists, it's best to contact the developers of the Commons app and report the problem. You can provide them with the steps to reproduce the issue and share the video/screenshots for reference. They will have access to the app's source code and logs, making it easier for them to diagnose and fix the problem.

Check App-specific Settings:
Some apps, like Vespucci and Share on OpenStreetMap, may have specific settings related to handling location data from other apps. Check if there are any settings within these apps that could affect how they handle shared coordinates.

Try Other Workarounds:
If the issue persists, consider using other methods to share the GPS coordinates temporarily. For example, you could copy the coordinates from the Commons app and paste them directly into the target app. Many apps that require GPS coordinates support input through manual entry.

Check for Open Issues:
Before contacting the app developers, it's a good idea to check if there are any known issues or bug reports related to GPS coordinate sharing in the Commons app. Visit the app's repository or forums to see if others have experienced similar problems.

Remember that diagnosing and fixing app issues can be complex, and it's best to work with the app's developers for a comprehensive resolution.

**Comment by mnalis** [comment]
I've installed [Intent Intercept](https://f-droid.org/en/packages/de.k3b.android.intentintercept/) app. According to it, the apps which work correctly with all other apps (e.g. SCEE, StreetComplete, OsmAnd,  ...) use RFC5870-compliant data in this format:

```
DATA: geo:44.10614,15.24136?z=19.422995
URI: intent:44.10614,15.24136?z=19.422995#Intent;scheme=geo;launchFlags=0x3000000;launchHwFlags=0x400;end
```

while Commons app use this unofficial extension:
```
DATA: geo:0,0?q=44.11269,15.229004
URI: intent:0,0?q=44.11269,15.229004#Intent;scheme=geo;launchFlags=0x3000000;launchHwFlags=0x400;end
```
