### ISSUE TITLE
[Bug]: blocked {{GENDER:||e}}

### ISSUE THREAD

**Issue by bepolymathe** [commons-app/apps-android-commons#5267]
### Summary

Hello everyone, 

I'm going to have a bit of time to contribute (which I haven't had for several years) and I'm having a problem with Commons. I've reinstalled the app (android) and it finds the few photos I did share (the last one was in 2014!)... but when I try to add another, it tells me I'm blocked {{GENDER:||e}}. I can't figure out what it is and how to remove the block. I could use a little help, please.
I have no problem with wikipedia (same account). I can upload new photos without problems from the website but not from the android app.

Version (F-droid) - 4.1.0~1649d1e2c

### Steps to reproduce

1. Open app
2. Take a picture from app OR select a photo in gallery
3. Try to upload
4. Get error message : `blocked{{GENDER:||e}}`

### Expected behaviour

1. Open app
2. Take a picture from app OR select a photo in gallery
3. Try to upload
4. It works !

### Actual behaviour

1. Open app
2. Take a picture from app OR select a photo in gallery
3. Try to upload
4. Get error message : `blocked{{GENDER:||e}}`

### Device name

Galaxy A22 5g

### Android version

Android 13

### Commons app version

4.1.0

### Would you like to work on the issue?

None

**Comment by Thibaut120094** [comment]
Don't know if it helps but I corrected the `{{GENDER:||e}}` issue on [TranslateWiki](https://translatewiki.net/w/i.php?title=Wikimedia:Commons-android-strings-block_notification_title/fr&diff=prev&oldid=11813513).

**Comment by bepolymathe** [comment]
@Thibaut120094 

I don't think it's related. I have the message in French. Can you tell me what the restriction is?

**Comment by nicolas-raoul** [comment]
If you switch the app's language to English (Settings > App user interface language), does it work?

Thanks for fixing TranslateWiki! The next release will have it. 🙂

**Comment by bepolymathe** [comment]
> bepolymathe: If you switch the app's language to English (Settings > App user interface language), does it work?
> 

Yes you're right. It seems to work 👍

**Comment by bepolymathe** [comment]
Actually, no, the problem hasn't been solved. The message appears again. In French it's the one indicated in the first post. If I switch the application to English, i have another one 

`Blocked
You are blocked from editing Commons`

The last update doesn’t change anything 🤔

**Comment by bepolymathe** [comment]
As a workaround, when the error message appears in English, I can backspace with the phone key (android), the message disappears and I can edit and post the image.

**Comment by nicolas-raoul** [comment]
Thanks for the feedback!

Are you able to post the image with the same account using the Commons **website**?

**Comment by bepolymathe** [comment]
> Are you able to post the image with the same account using the Commons website?

Yes. My account name: Bépolymathe 

![Screenshot_20231103_081420_Commons_1.jpg](https://github.com/commons-app/apps-android-commons/assets/29939805/24704e05-8bdc-43c0-9363-4c2f1f4aa52b)

You need something else ?

**Comment by nicolas-raoul** [comment]
@bepolymathe You are indeed blocked until tomorrow, for a reason that we Android app developers have no control over:
![Screenshot_20231103-170926.png](https://github.com/commons-app/apps-android-commons/assets/99590/ed5a6209-d402-4172-8a41-27110cc2b8bb)

The bug here is that the string internationalization/localisation is buggy. Any volunteer to fix it? Thanks! 🙂

**Comment by bepolymathe** [comment]
Hi @nicolas-raoul 

Thanks for reply. I’ll waiting for tomorrow ;-)

**Comment by bepolymathe** [comment]
> You are indeed blocked until tomorrow

I'am still blocked.

**Comment by nicolas-raoul** [comment]
@bepolymathe If you are able to upload a picture via the website but not via the app, please let us know.
