### ISSUE TITLE
In-app camera does not open when location permission is revoked

### ISSUE THREAD

**Issue by RitikaPahwa4444** [commons-app/apps-android-commons#5273]
### Summary

The in-app camera should open even when the user does not grant location permission to the app. While this works fine in the first run, it does not open when the permission is denied for the second time or revoked later. For more details, you may check [this comment](https://github.com/commons-app/apps-android-commons/pull/5249#pullrequestreview-1566689963).

### Steps to reproduce

1. On a fresh installation, tap the in-app camera button 
2. Allow the app to record location for in-app shots 
3. Tap "Deny" when asked for location permission. The in-app camera will open with a toast
4. Try to open the in-app camera again and repeat step 2

### Expected behaviour

The in-app camera should open again with the same toast.

### Actual behaviour

The in-app camera does not open at all.

### Device name

Redmi 5A

### Android version

8.1.0

### Commons app version

master and prodDebug

### Would you like to work on the issue?

None

**Comment by srishti-R** [comment]
Tested this on android 12 emulator, I think this got fixed by #5299

**Comment by RitikaPahwa4444** [comment]
Tested it on my Android 8.1 device. For me, the in-app camera now opens up with a toast without asking for location permission even on a fresh installation :(

**Comment by sivaraam** [comment]
I observe the behaviour similar to what Ritika mentions. On a fresh install, the location permission request dialog opens as expected but the "Turn on location?" dialog does not open. The app proceeds to trigger the image capture despite this. Weirdly, when we come back from the upload screen the app shows the "Turn on location?" dialog. The dialog should've been shown before the image capture was triggered. Here's a screen recording that demonstrates the issue.

https://github.com/commons-app/apps-android-commons/assets/12448084/595f8571-d800-4367-bc12-4238d223d4ce

Also, the "Nearby" section of the app also does not seem to be asking for the "Turn on location?" dialog either.

**Comment by RitikaPahwa4444** [comment]
Interestingly, #5255 seems fixed now 🤔
