### ISSUE TITLE
Leaderboard does not load

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#5278]
Leaderboard keeps spinning for me, then after a few minutes `Something went wrong, We could not fetch your achievements` appears.

Is it working for anyone?

![adb](https://github.com/commons-app/apps-android-commons/assets/99590/6bb1e509-ea3c-4090-9100-9bf9f9459263)

**Comment by whym** [comment]
I logged into the Toolforge account (`become commons-android-app`) and restarted the webservice. (`webservice restart`) Did it work?

**Comment by nicolas-raoul** [comment]
By the way, the same error appears on the "Achievements" screen and the level is not shown. I can reproduce that now. Is it the same kind of issue by any chance? :-)

**Comment by whym** [comment]
@nicolas-raoul This time I cannot reproduce. Is any of the items (like the level) missing or wrong, aside from the error message?

**Comment by nicolas-raoul** [comment]
@whym Thanks for checking! I just created a new issue: #5287
