### ISSUE TITLE
Target the latest Android version

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#5279]
We must increase targetSdk in the manifest.

This is needed for release to Play Store.

**Comment by iligeoili** [comment]
I would be glad to help , please assign this issue to me.

**Comment by nicolas-raoul** [comment]
Looking forward to your pull request! :-)

**Comment by nicolas-raoul** [comment]
@iligeoili Any progress on this? Have you found the manifest, and the value of the latest version? 🙂

**Comment by shankarpriyank** [comment]
@nicolas-raoul @iligeoili I guess we will need to add a couple of lines [here](https://github.com/commons-app/apps-android-commons/blob/main/app/src/main/AndroidManifest.xml#L21).
And if this is what I think [this](https://developer.android.com/guide/topics/manifest/uses-sdk-element.html) might help

**Comment by nicolas-raoul** [comment]
Please set `compileSdkVersion` and `compileSdkVersion` to `33` in both app/build.gradle and data-client/build.gradle, then test the app and make sure unit tests are running successfully.

If no pull request from @iligeoili within 24 hours, @shankarpriyank feel free to can take over it.

Thanks both! :-)

**Comment by shankarpriyank** [comment]
I think I wont be able to fix this, cause I have the latest android studio version and I will be blocked until #5208 is merged

**Comment by RitikaPahwa4444** [comment]
I can take it up if no one is currently working on it :)

**Comment by nicolas-raoul** [comment]
wow thanks so much Ritika!
