### ISSUE TITLE
Upload gets stuck after the app has been closed/killed or the device has been rebooted

### ISSUE THREAD

**Issue by RitikaPahwa4444** [commons-app/apps-android-commons#5282]
### Summary

Upload gets stuck after the app has been closed/killed or the device has been rebooted. Pausing/Unpausing for all the images individually might help.

### Steps to reproduce

1. Start an upload 
2. Reboot the device before the upload process finishes

### Expected behaviour

The upload should resume.

### Actual behaviour

Upload gets stuck.

### Device name

Redmi 5A

### Android version

8.1.0

### Commons app version

master and prodDebug

### Would you like to work on the issue?

None

**Comment by Tup0lev** [comment]
Hi, I would like to attempt to work on this issue as my first (real) PR, could please assign this to me?

**Comment by nicolas-raoul** [comment]
@Tup0lev It is yours, thanks! :-)

**Comment by RitikaPahwa4444** [comment]
Any updates on this? I had some observations related to the existing code and can help with that :)

**Comment by nicolas-raoul** [comment]
@Tup0lev Are you still working on this? If not, maybe you can unassign yourself and someone else can continue your work. :-)

**Comment by Tup0lev** [comment]
Sure. I'm very sorry for the trouble that I may have caused.

**Comment by nicolas-raoul** [comment]
@Tup0lev No problem at all, thanks for your PR, hopefully someone can continue upon it. 🙂
