### ISSUE TITLE
Do not filter out category that exactly matches the search

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#5285]
# Context

In the categories selection dialog, when searching for "2021 in Japan", I get `No categories found` despite the existence of https://commons.wikimedia.org/wiki/Category:2021_in_Japan

This is because we filter out old year-based categories, which is a good thing (see https://github.com/commons-app/apps-android-commons/pull/1134/files https://github.com/commons-app/apps-android-commons/pull/1134)

However, when sorting old pictures, such a category is still useful to people who know exactly what they are looking for.

# Task

If a category is an exact match for the search string entered, do not filter it out.
Example 1: When "2021 in Japan" is entered, do not filter out the element related to https://commons.wikimedia.org/wiki/Category:2021_in_Japan
Example 2: When "2021 Japan" is entered, the current filtering should run as usual (meaning the element related to https://commons.wikimedia.org/wiki/Category:2021_in_Japan is not shown) because "2021 Japan" does not match ""2021 in Japan" exactly.

**Comment by nicolas-raoul** [comment]
![Screenshot_20230908-175450~2.png](https://github.com/commons-app/apps-android-commons/assets/99590/3b997156-38ff-4f2d-88a5-60f2d68e0c3d)

**Comment by iligeoili** [comment]
Hey as a new coder i would be glad to dive into this issue. Please assign it to me,

**Comment by nicolas-raoul** [comment]
@iligeoili: Please start on it after you have sent a pull request for #5279, thanks a lot! :-)

**Comment by Deanstirrat** [comment]
I think I can do this is @iligeoili is okay with it.

**Comment by nicolas-raoul** [comment]
@Deanstirrat It is yours, thanks! Please let us know about your progress every week or so. 🙂

**Comment by Deanstirrat** [comment]
@nicolas-raoul Will do thanks!

**Comment by Deanstirrat** [comment]
Made the changes I think will fix the issue but cannot run tests until #5208 is resolved

**Comment by nicolas-raoul** [comment]
Wonderful! In order for us to test and approve your changes, please do not hesitate to send a pull request based on https://github.com/commons-app/apps-android-commons/issues/5208 (then we will merge it once we merge #5208, which should hopefully be very soon).
