### ISSUE TITLE
"Copy to subsequent pictures" stops working after saying "Yes" to "Is this a picture of ..."

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#5290]
Steps:

1. Prepare one picture with EXIF location near a Wikidata item, and a few older pictures.
2. Upload them as a set.
3. At the first pictures, you are asked whether it is a picture of the Wikidava item from step 1. Say yes.
4. Caption gets replaced with the Wikidata item's label. Rewrite it to something different.
5. Tap "copy to subsequent pictures".
6. Tap "Next"
7. Problem: the caption of the second picture is still the Wikidava item's label, the copy operation at step 5 did not work.

Workaround: Tap "Previous", tap "copy to subsequent pictures" again, this time it works. For a multiupload this workaround has to be done for each picture, that takes a long time.

Note: If another picture is near a Wikidata item and you reply "No" for that one, the issue does not happen anymore for the remaining pictures.

**Comment by srishti-R** [comment]
@nicolas-raoul Couldn't follow how to create a picture with EXIF location near wikidata item, could you please elaborate the first step in a bit detail?

**Comment by srishti-R** [comment]
@nicolas-raoul could you please elaborate on how to prepare one picture and then upload with multiple other images as a set? I created one picture from in app camera near a nearby place, but don't know how to add other images with this.

**Comment by nicolas-raoul** [comment]
@srishti-R I just shared a Drive folder with you (email found on your website linked from GitHub sorry for the intrusion). Within that folder, feel free to upload the pictures found in this subfolder: `Fukushō-ji (Higashi, Shibuya)`

They are encyclopedy-worthy pictures that are not present on Wikimedia yet. All can be uploaded under the Wikidata item https://www.wikidata.org/wiki/Q106836708 and Wikimedia category "Fukushō-ji (Higashi, Shibuya)".

Almost all have EXIF and are near Wikidata items so I believe that "Is this a picture of ..." should appear.

Please delete pictures that you successfully uploaded.
I can add many more whenever needed.
Thanks! :-)

**Comment by srishti-R** [comment]
@nicolas-raoul I was not able to replicate the bug, maybe I am doing something wrong here. I tried finding fukushoji on nearby map and then  uploading the images shared in drive, but couldn't find. Then I tried editing the exif of my captured images to _near_ a nearby place in an effort to see if the "is this a picture of..." comes up, it didn't. Let me know if there is anything else I can try meanwhile I'll just give this issue a skip, if anyone else wants to try.

**Comment by nicolas-raoul** [comment]
@srishti-R Sorry you can install the FakeGPS app to artificially set your coordinates to 35.649833, 139.710972 then uncheck `Needs photo` to the pin appear.

**Comment by nicolas-raoul** [comment]
![Screenshot_20231003-154641.png](https://github.com/commons-app/apps-android-commons/assets/99590/1f077333-e807-445b-8812-5650174f0f00)

**Comment by srishti-R** [comment]
@nicolas-raoul thanks for replying, but I deleted that comment because I was able to replicate this with my current location and creating images with dummy exif. Will try to fix.
