### ISSUE TITLE
Wrong thumbnail for just-uploaded picture

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#5294]
- I uploaded 5 pictures taken inside a boat.
- Then i switched off the screen of my phone, and came back to it about an hour later.
- Problem 1: Only 1 picture was uploaded, not 5.
- Problem 2: The thumbnail (buoy of the boat) does not match the picture that was actually uploaded (map of the boat)

https://github.com/commons-app/apps-android-commons/assets/99590/66329ea5-c793-4add-8adb-415cc591c7d1

Actually uploaded:
![Screenshot_20230917-152530~2.png](https://github.com/commons-app/apps-android-commons/assets/99590/ae01cbb2-fc1d-4079-b784-5b9bedd58fe1)

Bug observed only once, on branch https://github.com/commons-app/apps-android-commons/pull/5292 but that may be a coincidence as it is difficult to reproduce.

**Comment by alamzeeshan** [comment]
@nicolas-raoul This is happening because of the private `MediaDetailPagerFragment` which is there is the master branch as well.. I have made the construction public in my branch #5292 and this should fix the issue.

**Comment by Qiuyang-Shen** [comment]
Hi Nicolas! Are you still dealing with this issue? Can I give it a try to it? 😃

**Comment by nicolas-raoul** [comment]
@Qiuyang-Shen This is issue is difficult because it is very hard to reproduce. I have only seen it once. Better choose a different issue for now, I would say. Thanks for your interest! 🙂

**Comment by Qiuyang-Shen** [comment]
I see. Thanks for response! I guess I should pick another one.

**Comment by nicolas-raoul** [comment]
I haven't seen this issue for 3 months, closing.
