### ISSUE TITLE
Can't upload pictures after targetSdkVersion bumped to 33

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#5297]
# Steps to reproduce and problems description

1. Reset the app's storage, for instance by uninstalling/reinstalling.
2. Log in.
3. When asked "Allow Commons to access photos and videos on this device?", tap "Allow all".
4. Share a picture to the app.
5. Problem 1: Asked again "Requesting storage permission - We need your permission to access the external storage of your device in order to upload images." I believe I already gave permission at step 2?
6. Problem 2: Background is flickering as seen in the first screencast.
7. Problem 3: After tapping "Settings", it is not clear what needs to be done. See the two screenshots. I am not able to get past the dialog and thus can't upload pictures.

As seen in the second screencast, I also did not find a way to upload using the in-app camera. The custom picker also does not seem usable.

# Version

- This does not occur with 81030d1e78151db3ee436524f8379d6d2dc35a58 ("Fix retried uploads stuck in queued state"), I just tried.
- This starts occurring with the next commit f5770539a5deeb3811082f89b5e15df2c00e7eee ("Target the latest Android version") which means it is currently occurring on the main branch.

I am testing on Android 14.

# Research

https://developer.android.com/about/versions/13/behavior-changes-13#granular-media-permissions
https://developer.android.com/about/versions/12/behavior-changes-12

Interestingly, if I uninstall then install 81030d1e78151db3ee436524f8379d6d2dc35a58 and use it (tap the gallery button then choose picture and reach the caption filling screen) then upgrade to f5770539a5deeb3811082f89b5e15df2c00e7eee without resetting the app's storage, then the problems do not happen (tried just now). This may be related to this API 33 note (and may suggest that getting appropriate READ_MEDIA_* permission(s) would solve this whole issue):

> If your app was previously granted the [READ_EXTERNAL_STORAGE](https://developer.android.com/reference/android/Manifest.permission#READ_EXTERNAL_STORAGE) permission, then any requested READ_MEDIA_* permissions are granted automatically when upgrading.

# Screencast / screenshots

https://github.com/commons-app/apps-android-commons/assets/99590/808341ba-42c3-4274-842e-d1f9ca565e9f

![Screenshot_20230920-205833.png](https://github.com/commons-app/apps-android-commons/assets/99590/d9c0a779-2448-4dca-a578-238fec16a036)

![Screenshot_20230920-205844.png](https://github.com/commons-app/apps-android-commons/assets/99590/d642eb29-6aa4-4286-9e29-87d5dc448154)

https://github.com/commons-app/apps-android-commons/assets/99590/36d876da-c8e8-4aec-8d8c-0df850916c10

**Comment by RitikaPahwa4444** [comment]
I doubt if problem 2 (step 6) is related to the targetSdkVersion. I remember facing something similar for the "Requesting Location Permission" dialog in the Explore fragment map.

**Comment by nicolas-raoul** [comment]
You are right Ritika, the map activities (in particular Nearby) also sometimes show a seemingly useless permission dialog, that can be ignored by tapping "back" and does not prevent use of the activity. On the other hand, the present bug does prevent upload. 😥
