### ISSUE TITLE
Improve blue-on-grey contrast in dark mode

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#5301]
For instance `Username` here is difficult to read:
![Screenshot_20230922-051459](https://github.com/commons-app/apps-android-commons/assets/99590/375bd893-0dc2-443f-8745-78e4204c984c)

**Comment by srishti-R** [comment]
What is the recommended color that it should change to? I am not a UI person but I can make the code changes if there is any recommendation.

**Comment by nicolas-raoul** [comment]
How about using the lighter blue of the "i" information button showed by the red arrow here in the metadata activity? ip believe it would be much more readable. Please note that this issue is not a blocker for the next release, but still a good issue to fix. 🙂
![Screenshot_20230924-164524.png](https://github.com/commons-app/apps-android-commons/assets/99590/fb4dfb5d-e430-413c-9323-8f560df4f43f)
