### ISSUE TITLE
[Bug]: App crashes when trying to sign up on lowest supported api 21.

### ISSUE THREAD

**Issue by srishti-R** [commons-app/apps-android-commons#5303]
### Summary

Need to update/downgrade google materials library version. I am supposing downgrading won't be an option here, so for upgrading need to update jdk version to at least 17.

### Steps to reproduce

* Try to Sign up on fresh app install.
* The app will crash.

### Expected behaviour

App should not crash

### Actual behaviour

App crashes when trying to open a webview.

### Device name

Pixel 5 emulator

### Android version

api 21

### Commons app version

prodDebug

### Would you like to work on the issue?

None

**Comment by nicolas-raoul** [comment]
I am not against increasing minSdk to 22 if fixing is not easy.
<img width="492" alt="Screenshot 2023-09-25 at 14 13 38" src="https://github.com/commons-app/apps-android-commons/assets/99590/315f3191-953d-4fcb-a46a-55c4372e4779">

**Comment by srishti-R** [comment]
> I am not against increasing minSdk to 22 if fixing is not easy. 

Will have to increase minSDK to at least 23 to bypass this, or fix this. Will try to do when I get some time.
