### ISSUE TITLE
[Bug]: In-app camera should avoid asking to capture the image twice

### ISSUE THREAD

**Issue by sivaraam** [commons-app/apps-android-commons#5305]
### Summary

This is a follow-up of the fix for #5300 (also #5233). With the merged MR, the in-app camera now asks to shoot the image twice for some strange reason. More interestingly, thought it asks to shoot the image twice the image from the first shot is the one that's used. This could be a confusing and annoying UX. We need to explore why this happens and avoid the same.

Side note: There's also a weird "Error while picking image" toast that appears after the second shot.

### Steps to reproduce

1. Open the app
2. Try to upload via the in-app camera 
3. Capture an image
4. Note that the first shot is skipped and you're requested to shoot again
5. Capture the image

### Expected behaviour

The app should directly take user to upload screen after the first shot.

### Actual behaviour

You're asked to upload the image taken on the first shot. The image taken on the second shot is lost.

### Device name

OnePlus Nord

### Android version

Android 12

### Commons app version

main

### Would you like to work on the issue?

None

**Comment by nicolas-raoul** [comment]
Thanks for filing!

- I was able to replicate this on Pixel 6 Pro and Pixel 7 Pro running Android 14, as well as with Samsung S10e running Android 9.
- On the other hand srishti-R reports "I was not able to replicate [...] on both emulator and a device"

**Comment by RitikaPahwa4444** [comment]
This happens occasionally on my Redmi 5A (API level 27). It is even more confusing in my case: sometimes it would decide to go with one shot, and sometimes it would ask for another shot!

**Comment by sivaraam** [comment]
Is it just me or do other also observe this not happening with v4.2.0-release branch ?

**Comment by sivaraam** [comment]
As I don't observe this on the v4.2.1 of the app too, I'm going ahead and closing this one. Feel free to reopen in case you still observe this.

cc @nicolas-raoul
