### ISSUE TITLE
Just after accepting location permission in Upload Wizard location edition map, "My Location" button does not move me to my position

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#5309]
### Steps to reproduce

1. Remove the app's location permission
2. Restart the app
3. Open the Contribution tab
4. Click on the upload from gallery icon (either regular or the custom selector)
5. Choose an image and click on the map icon
6. Click on the "My Location" icon present just above the green-coloured floating icon
7. A dialog must appear requesting for location access, accept.
8. Tap the "My Location" icon again

### Expected behaviour

Map moves to my position. My position has a blue dot.

### Actual behaviour

Map does not move. My position does not have a blue dot.

### Device name

Pixel 7 Pro

### Android version

Android 14

### Commons app version

main, prodDebug

**Comment by RitikaPahwa4444** [comment]
Are you getting the "Turn location on?" dialog? There's some issue with the flow at various places in the app due to some recent changes (related discussion: #5273)

**Comment by nicolas-raoul** [comment]
Yes, I am correctly getting asked for location permission each time.
