### ISSUE TITLE
When uploading via Nearby, make the item's depiction (and category) undeselectable

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#5317]
Steps to reproduce:

1. Go to Nearby
2. Select any Wikidata item on the map
3. Start adding a picture for it
4. At the depiction step, the Wikidata item is automatically selected
5. Problem: This Wikidata item can be deselected

If the Wikidata item has a category property (for instance https://www.wikidata.org/wiki/Q243 links to https://commons.wikimedia.org/wiki/Category:Eiffel_Tower), then the same problem exists: The category can be deselected.

Since a picture taken in Nearby must depict the Wikidata item, the app must prevent the item and category from being deselected by the user.

Unimportant note: Some may argue that if they select https://commons.wikimedia.org/wiki/Category:Eiffel_Tower_in_European_Union_livery_at_night then they do not need to select https://commons.wikimedia.org/wiki/Category:Eiffel_Tower , but this is very rare for an item to have Commons subcategories while having no P18, and de-parenting bots can take care of such cases. The benefits of making the category undeselectable are thus higher than the rare and small benefits.

**Comment by srishti-R** [comment]
Hi, I tried going through this issue but since I am new to this project, I had some trouble understanding what the problem is. Did you mean to say that the caption and description here in this screenshot should not be editable? and there should not be next option given?
![Screenshot_20230929-190827_Commons](https://github.com/commons-app/apps-android-commons/assets/53987325/3b01b06c-f9d4-4fb5-ac7c-e58ece571721)

**Comment by nicolas-raoul** [comment]
Thanks for checking this! It is a rather low priority issue, so feel free to drop it if you don't like it for any reason. ^_^

Your screenshot is at step 3 in the reproduction steps above. If you tap "Next", you will reach step 4 and hopefully things will be clearer. :-)

**Comment by srishti-R** [comment]
@nicolas-raoul Oh did you mean that this checkbox should not be there or this option should not be shown?
![Screenshot_20230929-192023_Commons](https://github.com/commons-app/apps-android-commons/assets/53987325/2b9c8769-0aac-49d6-9d61-db76e1c22e55)

**Comment by nicolas-raoul** [comment]
It should still be like this, but tapping the checkbox would not deselect it.
Maybe making the (selected) checkbox greyed out would be a good visual indication that it can't be modified:
![271615495-2b9c8769-0aac-49d6-9d61-db76e1c22e55](https://github.com/commons-app/apps-android-commons/assets/99590/c9892228-385a-48db-b64b-f68fa233f966)

It must be possible to add other depictions, though.

**Comment by srishti-R** [comment]
@nicolas-raoul cool, thanks for clarifying, will take this up after fixing one other issue I am looking at.
