### ISSUE TITLE
Bookmark categories

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#5318]
We have a bookmark panel with pictures/locations/items.

It would be great to have the same for categories. It would be especially useful if these bookmarks get automatically suggested when uploading (similar to #4745).

**Comment by Ahmed-Qaisar** [comment]
Hi Nicolas, would it be possible for you to assign this issue to me?

**Comment by nicolas-raoul** [comment]
@Ahmed-Qaisar Could you please choose an issue labeled "bug"? Thanks! 🙂

**Comment by bhoomigadhiya** [comment]
Can I work on this? @nicolas-raoul

**Comment by nicolas-raoul** [comment]
@bhoomigadhiya It is yours, thanks!

**Comment by nicolas-raoul** [comment]
@bhoomigadhiya No pressure, but any progress or observations to share? :-)

**Comment by neeldoshii** [comment]
Can I work on this?

**Comment by nicolas-raoul** [comment]
@neeldoshii It is yours, thanks! :-)

**Comment by parneet-guraya** [comment]
Does this #6035 fixes this?

**Comment by chrisdebian** [comment]
@bhoomigadhiya @parneet-guraya @Ahmed-Qaisar Hi, just trying to help prioritize what development work gets done next. Would you be able to have a look at this https://github.com/commons-app/apps-android-commons/issues/6034 and potentially add your thoughts/ priorities to the spreadsheet?

Thanks,

Chris.
