### ISSUE TITLE
Logging at hackathon

### ISSUE THREAD

**Issue by whym** [commons-app/apps-android-commons#532]
I have seen the idea of keeping individual, public logs in a beginner-friendly mini hackathon/coding workshop:  https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md (in Japanese). I haven’t tried it before and I’m not sure if it is the best format for us, but I find it inspiring. The idea is like this (at least this is my understanding):

- Each participant keeps a public log, adding every update they have during the hackathon (tools they have tried, references they have found, other attempts and failures they experienced during the day). It could be a wiki page on MediaWiki.org or a GitHub issue (maybe in a dedicate repository).
- When mentors alternate between different participants and topics (in addition to their own dev tasks) they can refer to the logs to keep themselves updated. In other words, it helps people work asynchronously.
- The log doesn’t have to be a complete write-up. Think something like “Tried to reproduce the XYZ bug. Stuck at a different error: …” or “Checked the official doc. It doesn't explain how to XYZ.”
- Participants should feel free to include basic matters such as trying to setup an environment or thoughts that may or may help others later on (e.g. “This feels kind of similar to the XYZ software I worked on in terms of ….”).
- If someone feels it is an obstruction, they don't have to follow this practice thoroughly. (But still, having a paragraph or two for a day can be recommended.)
- Of course, when appropriate, consider also posting to an existing or new GitHub issue instead of the personal log.

The main benefit is that reading the logs helps mentors to help mentees. The logs also may serve as a starting point towards making the software documentation more complete (this can happen post-hackathon).

**Comment by misaochan** [comment]
Sounds good to me. I think if we go with this, we could offer it as a suggestion (so people who want to can do it), but it should probably be optional?

**Comment by whym** [comment]
Yes, it would be just a suggestion.
