### ISSUE TITLE
Confirmation popup to cancel upload says "English English"

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#5321]
Steps:
1. Launch the upload of a file
2. While the file is uploading, tap the pause button.
3. Tap the x button to delete the upload.
4. Popup has wrong title and message:

![Screenshot_20230929-123921.png](https://github.com/commons-app/apps-android-commons/assets/99590/9733b9c7-26de-4259-acc6-95c7d19bbff1)

Same popup appears for failed uploads.

**Comment by Junan-YU** [comment]
Hi, I would like to try to reach out this issue if it's possible : )

**Comment by nicolas-raoul** [comment]
@Junan-YU Any progrerss on this? :-)

**Comment by STERILITZIA02** [comment]
> @Junan-YU Any progrerss on this? :-)

Yeah I was trying to see if this problem happens for other languages version, and maybe the error message pop up logic: : -)

**Comment by STERILITZIA02** [comment]
> > @Junan-YU Any progrerss on this? :-)
> 
> Yeah I was trying to see if this problem happens for other languages version, and maybe the error message pop up logic: : -)

By the way this is my another account

**Comment by Junan-YU** [comment]
Can you share what is the language you use? since the cancelling upload does not appear to be wrong in my devices.

**Comment by nicolas-raoul** [comment]
OS, app, UI, descriptions all in English

https://github.com/commons-app/apps-android-commons/assets/99590/ddf3e8a1-5740-47dd-9568-ff6b4bc2704c

**Comment by nicolas-raoul** [comment]
Apologies @Junan-YU this issue got fixed outside of the usual workflow, as it was prioritized for the upcoming release (#5308). Would you mind finding another issue? Thanks for your understanding!

**Comment by Junan-YU** [comment]
> Apologies @Junan-YU this issue got fixed outside of the usual workflow, as it was prioritized for the upcoming release (#5308). Would you mind finding another issue? Thanks for your understanding!

Sure I will find another issue to work on, apologise for not fixing this issue quickly.
