### ISSUE TITLE
[Need help]: Need to fix 2 failing unit test

### ISSUE THREAD

**Issue by srishti-R** [commons-app/apps-android-commons#5327]
### Description

Need to fix 2 failing unit test inside CategoriesPresenterTests.kt in PR #5325 . The `searchResults` method is returning NPE and these tests are thus failing.

**Comment by u7452206** [comment]
Can you assign this issue to me. I would like to finish the unit test.

**Comment by nicolas-raoul** [comment]
Thanks for helping @u7452206 it is yours. 🙂

**Comment by srishti-R** [comment]
@u7452206 hey, any update on this? I was able to put a fix to the tests but if your fix is better we can take yours as well.

**Comment by u7452206** [comment]
no yet. Still looking at. If you finish, can use yours

**Comment by nicolas-raoul** [comment]
@srishti-R Thanks for finding the time to fix these!

@u7452206 I will now close this issue, but feel free to improve the unit tests or add more tests related to this feature. Thanks! :-)
