### ISSUE TITLE
[Bug]: not able to edit description of uploaded images in all languages

### ISSUE THREAD

**Issue by srishti-R** [commons-app/apps-android-commons#5332]
### Summary

Description should be editable for already uploaded images in all languages, but currently its not editable.

### Steps to reproduce

1. Open any uploaded images in contributions
2. Tap on "in all languages" text on the screen as attached below
3. Tap on the pen icon which appears when trying to edit description in newly opened dialog.
4. the edit text disappears and is not editable.

### Expected behaviour

Description should be editable.

### Actual behaviour

Can't edit anything about description.

### Device name

samsung galaxy M31

### Android version

android 12

### Commons app version

prodDebug

### Screen-shots

![Screenshot_20231009-081108_Commons](https://github.com/commons-app/apps-android-commons/assets/53987325/ad1c61aa-d4aa-4889-bc68-79e550e713c3)

### Would you like to work on the issue?

Yes

**Comment by nicolas-raoul** [comment]
I can't reproduce on prodDebug, can you?

The test environment is unfortunately not really representative, many things fail on it especially Wikibase-related things. 😥

**Comment by srishti-R** [comment]
> I can't reproduce on prodDebug, can you?
> 
> The test environment is unfortunately not really representative, many things fail on it especially Wikibase-related things. 😥

Yes, this is how it appears for me on prodDebug. I can try to fix.

**Comment by srishti-R** [comment]
> Thanks for finding this issue and proposing to fix it!
> 
> For reference, here is how it looks for me on Android 14: https://github.com/commons-app/apps-android-commons/assets/99590/1abc0ecb-1900-4674-a00d-138184d48443

This issue is replicable only when you have NOT scrolled up the below tray containing title, caption and description. When its not expanded (refer my screenshot above) and then if you click on that pencil icon beside "in all languages" text, then that floating view above appears (which has the bug) to edit the description. When I had expanded that tray and then clicked on that icon, I got similar to how you posted. Will add this to issue description. Thankyou for this video 😃

**Comment by srishti-R** [comment]
> Thanks for finding this issue and proposing to fix it!
> 
> For reference, here is how it looks for me on Android 14: https://github.com/commons-app/apps-android-commons/assets/99590/1abc0ecb-1900-4674-a00d-138184d48443

Um, Okay. I was able to replicate it yesterday on my device. Today I could replicate one time and then it behaved the way you posted in the video. Seems like intermittently the tray containing title and description is failing to open entirely when we click on any uploaded image such that only title, captions and description are visible, and then if you click on that icon, it displays that weird popup. Since I can't replicate it anymore, there's no way to know if my fix actually worked. So closing this issue, thanks for the video. 😄

**Comment by nicolas-raoul** [comment]
If you find a way to reproduce, please don't hesitate to reopen. 🙂
