### ISSUE TITLE
[Bug]: F-Droid build failed

### ISSUE THREAD

**Issue by linsui** [commons-app/apps-android-commons#5333]
### Summary

https://monitor.f-droid.org/builds/log/fr.free.nrw.commons/1035#site-footer

Could you please take a look? Thanks!

### Steps to reproduce

None

### Expected behaviour

None

### Actual behaviour

None

### Device name

None

### Android version

None

### Commons app version

4.2.0

### Would you like to work on the issue?

None

**Comment by nicolas-raoul** [comment]
We plan to update Proguard within a month, that should fix it.

**Comment by licaon-kter** [comment]
My internet searches lead me to that info too, but I didn't quite figure out where is that setup :)

**Comment by sivaraam** [comment]
@licaon-kter We've fixed the issue and pushed out a new [v4.2.0-beta](https://github.com/commons-app/apps-android-commons/releases/tag/v4.2.0-beta) release that should build without issues. Could you push that as a new beta release of the app?

Also, the v4.2.0 contains non-working code. So, better to keep that disabled. 🙂

**Comment by linsui** [comment]
It has the same version name and version code as 4.2.0. What do you want us to do?

**Comment by nicolas-raoul** [comment]
@sivaraam I would advise creating a 4.2.1 ... it is just a number :-)

**Comment by sivaraam** [comment]
Ah. Totally missed that. Would it be possible to use the v4.2.0-beta in place of the v4.2.0 one so that the same version code and version are used?

**Comment by sivaraam** [comment]
> @sivaraam I would advise creating a 4.2.1 ... it is just a number :-)

We certainly need to do that for the production release. It would be nice if we could publish v4.2.0 version itself via F-droid since that's what we've published on Google Play.

If there's no to do that, we could certainly consider the alternative you suggest

**Comment by linsui** [comment]
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/13874 Done. :ok_hand:

**Comment by sivaraam** [comment]
Thanks much @linsui ! 🙂

**Comment by sivaraam** [comment]
@linsui @licaon-kter The v4.2.0 update of the app doesn't seem to appear on the app page on F-droid. I could see the app listed in the ["Need updating"](https://monitor.f-droid.org/builds/needsupdate) page. Could you let us know what that means?

Is it just a matter of time for the app to deploy? Or is there something that needs to be done at our end?

**Comment by licaon-kter** [comment]
@sivaraam fyi https://gitlab.com/fdroid/wiki/-/wikis/FAQ#how-long-does-it-take-for-my-app-to-show-up-on-website-and-client
