### ISSUE TITLE
Grey screen after fresh install then share

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#5342]
https://github.com/commons-app/apps-android-commons/assets/99590/a2f7e893-16ca-4f89-84c0-c60138634e8d

**Comment by sivaraam** [comment]
Yeah. I've observed this too. I guess we fail to get the media access permission when the login happens via any route other than directly opening the app after a fresh install.

We should look into correcting this.

**Comment by sivaraam** [comment]
Also, I should mention that this seems related to #5330

**Comment by nicolas-raoul** [comment]
Very related indeed (exact same symptom), though here I did not deny any permission.

**Comment by sivaraam** [comment]
Yeah. Here we're failing to ask for the permission itself IIUC from your recording
