### ISSUE TITLE
Cancelling an upload does not really cancel it

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#5346]
Scenario: You upload 5 pictures of a monument, but while it is uploading you suddenly realize that two of the pictures are privacy violations (for instance they are private family pictures). You want to cancel these two uploads, so for each of them you tap the pause button then the "X" delete button.

Problem: These two pictures actually get uploaded as well.

This is probably a rather difficult issue, as you will need to read the code and understand how the app retries failed uploads.

**Comment by RitikaPahwa4444** [comment]
For me, the cancel button is working correctly only for the _ongoing_ upload. For the _upcoming_ contributions, this does not work, which means only the first contribution in the `queuedContributions` list is impacted by the delete operation. Tapping the button apparently deletes the contribution from the database, so the retry logic should not find the entry at all🤔
https://github.com/commons-app/apps-android-commons/blob/64652b987d686bc1d9ed56d3c59bfdee2ffedde7/app/src/main/java/fr/free/nrw/commons/contributions/ContributionViewHolder.java#L240-L243

**Comment by RitikaPahwa4444** [comment]
I suspect if this line adds the contribution again to the database using the insert operation:

https://github.com/commons-app/apps-android-commons/blob/64652b987d686bc1d9ed56d3c59bfdee2ffedde7/app/src/main/java/fr/free/nrw/commons/upload/worker/UploadWorker.kt#L219

**Comment by nicolas-raoul** [comment]
Thanks Ritika, great insight! :-)

**Comment by nicolas-raoul** [comment]
@RitikaPahwa4444 Please do not feel obligated to, but if you want to take it then of course you are more than welcome! :-)
