### ISSUE TITLE
Transfer Mapbox SDK keys to a new account

### ISSUE THREAD

**Issue by maskaravivek** [commons-app/apps-android-commons#5351]
Hi maintainers,

6 years ago i created API keys for the Mapbox SDK that is being used in the commons app. This month the usage exceeded their free tier threshold and they are charging my account for the exceeded requests.

![image](https://github.com/commons-app/apps-android-commons/assets/3069373/c96f5d9e-6acd-4c48-87c9-e83f62be26e8)

The cost for additional requests is quite steep ie. 0.25$ / 1000 requests. For the last month the bill was 12$ which is not much but i am concerned that this month i might get a much bigger bill.  

Can the current maintainers of the app
- help in migrating API keys to a new account immediately. I am planning to keep my account active for some time so that existing users are not affected till the migration is done. Once we release an update, atleast some people will update their apps so the usage of old API key shouldn't increase. 
- in the long term, you could explore alternative options or SDKs which don't have such a limit. 

Migration of API key should be straightforward. Involves registering a new account with Mapbox, creating an Api key and then probably 1 line of code change. 

@nicolas-raoul @sivaraam

**Comment by sivaraam** [comment]
Sure, Nicolas. Let me look into this over this weekend.

**Comment by maskaravivek** [comment]
Hi @nicolas-raoul and @sivaraam  thanks for your quick response. I am traveling but i will try to share the config in a few hours.

**Comment by babelstone** [comment]
I am in the beta, and updated to 4.2.0 last week, but now the map is empty (no place markers displayed), and the error message "Error fetching nearby places.null" is reported. I am using a Samsung Galaxy A70 running Android 11.

**Comment by nicolas-raoul** [comment]
Ah @babelstone sorry my brain malfunctioned, this can not be related to the API key change which I performed only two days ago... could you please create a new issue and post a screenshot there? Thanks a lot!

**Comment by sivaraam** [comment]
Excuse the delay. I got occupied with some $DAYJOB work. Will look into releasing the beta within today.

@maskaravivek Just to cross-check, were you able to share the configuration with Nicolas ?

**Comment by nicolas-raoul** [comment]
The current main branch (using my API key) has been working fine for me for a week, so I seem to have an OK configuration.
Below is my configuration, Vivek if you notice anything that can be improved please do not hesitate to let me know as I am a Mapbox newbie. :-)
<img width="1226" alt="Screenshot 2023-10-25 at 22 48 44" src="https://github.com/commons-app/apps-android-commons/assets/99590/27d185e2-ec56-4018-9ac7-489be356bbba">

**Comment by sivaraam** [comment]
[v4.2.1](https://github.com/commons-app/apps-android-commons/releases/tag/v4.2.1) has been tagged and the same has been pushed for testing 👍🏼

**Comment by maskaravivek** [comment]
@nicolas-raoul Your configuration looks correct to me. 

<img width="1082" alt="Screenshot 2023-10-30 at 8 34 53 PM" src="https://github.com/commons-app/apps-android-commons/assets/3069373/eae91d82-e486-4854-850c-895938f49959">

Apologies for the delayed response. I was on a vacation and had limited access to internet. 

Also, as a side note, the bill for Oct ballooned to 480$. I just wrote to Mapbox support to get it waived but am not sure if they can.  

Does the commons project have access to any funds to help pay off the bill in case they cannot waive it?

**Comment by sivaraam** [comment]
That's so sad to hear, Vevek. Sorry about not being able to publish the app sooner. :-(

The v4.2.1 of the app with changed keys has now been published to play store successfully. So, things should start settling soon as users upgrade.

> Does the commons project have access to any funds to help pay off the bill in case they cannot waive it?

I'm not aware of any such funds, Vevek. We haven't applied for the grant yet. I think we should definitely check with the WMF about possible ways to settle this bill in someway in case Mapbox isn't able to help you with waive this off.

Any thoughts @nicolas-raoul @misaochan ?

**Comment by nicolas-raoul** [comment]
😰😰😰
How about contacting our contact at WMF aramadan?
And possibly ssethi who we have been working with for years.

**Comment by nicolas-raoul** [comment]
I wonder why you are getting raster tile requests, I see none on my side: 
![image](https://github.com/commons-app/apps-android-commons/assets/99590/afd53f28-6e24-43e5-a88f-fbd2107b4829)
I keep monitoring and will disable all scopes just before we go over the free tier.

**Comment by maskaravivek** [comment]
Mapbox waived off the bill and revoked my tokens to prevent abuse. 

If the token was indeed was being abused by bad actors, i think we should be storing the token as CI secret. @nicolas-raoul suggested something along these lines in the other thread. 

Since we have other issues created for next steps, I think we can close this issue if everyone agrees.

**Comment by nicolas-raoul** [comment]
Really relieved to hear that Vivek! 🎉
Next steps:

Short term: #5373
Medium term: #5372

**Comment by sivaraam** [comment]
Yeah. Good to know you were able to waive off the bill, Vivek!

Just wanted to confirm one thing. You mention that your keys have been revoked. Does that mean maps won't work on the older versions of the app?

If that's the case, we might need to announce this a bit widely to users to make sure they aren't confused by the map stopping to work all pf a sudden.

**Comment by nicolas-raoul** [comment]
Yes, we need to tell everyone to upgrade to the latest version. Some on super old Android version might not be able to install a new version, to those we can only recommend to use the online tool https://wikishootme.toolforge.org instead.

**Comment by sivaraam** [comment]
> Yes, we need to tell everyone to upgrade to the latest version. Some on super old Android version might not be able to install a new version, to those we can only recommend to use the online tool https://wikishootme.toolforge.org instead.

Got it, Nicolas. I've announced the release and this change in the mailing list.

Link to the thread: https://lists.wikimedia.org/hyperkitty/list/commons-l@lists.wikimedia.org/thread/U2PRDV7MDNATTIOGLJNXECACT7C432GS/

**Comment by sivaraam** [comment]
Also announced on the Commons:Village pump (technical): 

https://commons.wikimedia.org/wiki/Commons:Village_pump/Technical#Commons_app_-_Map_views_would_work_only_with_v4.2
