### ISSUE TITLE
Mapbox costs me money, find a gratis map provider

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#5352]
Our app is now so popular that Mapbox went well over the free tier and cost [480USD](https://www.mapbox.com/pricing#maps)  in October.
It is not scalable/futureproof as we have zero revenue and pricing is quite steep, it will probably get even more expensive very fast.

We must find a gratis solution. Any ideas, even wild ones?

# Map server

- Wikimedia has https://www.mediawiki.org/wiki/Wikimedia_Maps/API that we may be able to use, it powers for instance [WikiMap](https://wikimap.toolforge.org/?lat=48.856667&lon=2.352222&zoom=12&lang=en&wp=false). First we need to get this approved: https://phabricator.wikimedia.org/T349280
- OpenStreetMap.org tiles directly (example third party using them: https://tbo47.github.io).
  - Usage conditions seem rather strict: https://operations.osmfoundation.org/policies/tiles/
- Some community-run OpenStreetMap-based tile servers have usage conditions that may be more flexible and compatible with our purpose, example: https://tile.ourmap.us/usage.html
  
# Client side

- OpenStreetMap-using Android libraries:
  - https://github.com/osmdroid/osmdroid has pins and a quite readable map. 3k GitHub stars.
    - May need to fix Wikimedia tiles provider integration? https://play.google.com/store/apps/details?id=org.osmdroid -> OSMDroid Sample Map -> ... -> Map Source -> Wikimedia -> Map becomes grey
  - https://github.com/mapsforge/mapsforge Actively maintained, maybe not very readable on small screens.
  - https://github.com/k3b/LocationMapViewer Pin style looks a bit out-of-place judging from the screenshot but worth trying.
  - https://github.com/mousebird-consulting-inc/WhirlyGlobe Looks iOS-first and globe feature is not needed by us.
  - https://github.com/mapsforge/vtm/ 3D map screenshots look really great, but we must remember that our most valuable contributions are the ones from areas where there are few open data contributors, and thus probably no 3D map data.
- Using JavaScript in a web view might also be possible.

**Comment by mnalis** [comment]
OSM wiki lists some [Raster tile providers](https://wiki.openstreetmap.org/wiki/Raster_tile_providers) and [Vector tiles#Providers](https://wiki.openstreetmap.org/wiki/Vector_tiles#Providers).
