### ISSUE TITLE
[Bug]: Map is empty in 4.2.0

### ISSUE THREAD

**Issue by babelstone** [commons-app/apps-android-commons#5358]
### Summary

I am in the beta, and updated to 4.2.0 last week, but now the map is empty (no place markers displayed), and the error message "Error fetching nearby places.null" is reported. I am using a Samsung Galaxy A70 running Android 11.

### Steps to reproduce

1. Open app.
2. Navigate to the Nearby tab -- no place markers are displayed, and the message "Error fetching nearby places.null" is shown.

### Expected behaviour

The map should display markers for nearby places.

### Actual behaviour

The map does not display any markers for nearby places.

### Device name

Samsung Galaxy A70

### Android version

Android 11

### Commons app version

4.2.0

### Screen-shots

![Screenshot_20231021-151546_Commons](https://github.com/commons-app/apps-android-commons/assets/20558386/3de7a53b-93d6-42e0-bd25-5fb31e3707b4)

### Would you like to work on the issue?

None

**Comment by sivaraam** [comment]
Thanks for early report, @babelstone ! 

The change in #5359 should fix the issue for you. We'll release another version soon with the fix :-)
