### ISSUE TITLE
[Bug]:  Thumbnail not visible while uploading rotated image

### ISSUE THREAD

**Issue by shankarpriyank** [commons-app/apps-android-commons#5363]
### Summary

The thumbnail is not visible while the image is getting upload.

### Steps to reproduce

1. Select a image for upload, rotate it using the edit option
2. Upload that image
3. While the image is getting uploaded the thumbnail of an edited image is not visible

### Expected behaviour

The thumbnail should be visible

### Actual behaviour

The thumbnail is not visible

### Android version

Android 11

### Commons app version

4.2.0

### Would you like to work on the issue?

None

**Comment by javaman97** [comment]
@nicolas-raoul Should I start working on this issue ?

**Comment by nicolas-raoul** [comment]
@javaman97 Yes, it is yours, thanks! :-)

**Comment by nicolas-raoul** [comment]
@javaman97 Any progress on this? 🙂

**Comment by mshdabiola** [comment]
Can I try this, please

**Comment by nicolas-raoul** [comment]
@mshdabiola No news from javaman97 in 2 weeks, so it is yours. Thanks! :-)

**Comment by mshdabiola** [comment]
i have fix the bug please review it
