### ISSUE TITLE
Replace Mapbox with osmdroid (Nearby activity)

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#5372]
The Nearby activity shows a map using the Mapbox library.

We [need](https://github.com/commons-app/apps-android-commons/issues/5352) to switch to the **osmdroid** library:
https://github.com/osmdroid/osmdroid/wiki/How-to-use-the-osmdroid-library-(Kotlin)

The task here is to perform this switch, with the following feature still working:
- Map gets displayed, centered on the user's location
- Map can be moved/zoomed with the fingers (osmdroid default behaviors are fine)
- A pin appear on the map for each Wikidata item
- Tapping on a pin opens the bottom UI with +/name/etc
- The other features _(such as place state/type, dark mode, user position, locale)_ are not really required for now, they will be the topic of future other GitHub issues.

Any tiles server that works can be used for now.
![Screenshot_20231030-161141.png](https://github.com/ZeLonewolf/openstreetmap-americana/assets/99590/6f299349-1f15-471d-8d95-198ecc276aef)

**Comment by kanahia1** [comment]
Hello  @nicolas-raoul , I was playing around with [osmdroid library](https://github.com/osmdroid/osmdroid/wiki/How-to-use-the-osmdroid-library-(Kotlin)), and I have created a demo app including suggested features. I think making few UI changes will make it look similar to mapbox's integration.

https://github.com/commons-app/apps-android-commons/assets/114223204/8a93e7ea-51f7-44a4-9b17-f44c85c93d50


Can I work on integrating osm into nearby activity!

**Comment by nicolas-raoul** [comment]
Wonderful, it looks great!

Thanks a lot, it is yours, please let us know about your progress every week or so. 🙂

**Comment by nicolas-raoul** [comment]
@kanahia1 Please do not hesitate to start a draft pull request, and do not hesitate to ask anything. :-)

**Comment by kanahia1** [comment]
Happy Diwali 🪔@nicolas-raoul , I have integrated the OSM into the Wikimedia app and only few things are left. Actually, I had issue with my PC last week and it is resolved now 😄, I will be sharing the pull request by this weekend.

**Comment by nicolas-raoul** [comment]
Happy Diwali! 🙂
Wonderful!

**Comment by kanahia1** [comment]
Hi @nicolas-raoul, here's the progress of last weeks 

https://github.com/commons-app/apps-android-commons/assets/114223204/0af602bc-e092-46ad-aa85-5163701e0900

**Comment by nicolas-raoul** [comment]
@kanahia1 Very nice! The next big step would be displaying the points of interest (=Wikidata items) on the map, I guess? 🙂

**Comment by kanahia1** [comment]
Hi 👋 @nicolas-raoul, here's the progress this week

https://github.com/commons-app/apps-android-commons/assets/114223204/fe3f0261-67e8-4125-8600-710708b447f0

Few things are left such as Filters, Marker's UI changes. I will try to complete them by this weekend.

**Comment by nicolas-raoul** [comment]
Great, thanks! 🙂

**Comment by kanahia1** [comment]
I am sorry to interrupt 😞 but I won't be able to proceed further for 2 weeks as I have university exams, but I will continue in December as I have winter break in December I will be able to contribute a lot ✨

**Comment by nicolas-raoul** [comment]
@kanahia1 Would you just mind pushing your existing code (git commit, git push, or just send me a ZIP of your whole project to my email address found at http://nrw.free.fr) so that someone else can continue your work? You will still take credit for your amazing work so far :-) And no problem at all, please prioritize your university exams. :-)

**Comment by kanahia1** [comment]
Sure !, After making few changes I will share code with you

**Comment by kanahia1** [comment]
The process I have utilized to transfer from MapBox to OSMDroid is to utilize the existing code and make changes to it to make it fit for OSM, so this commit will still contain the MapBox code since I haven't fully implemented OSM.
https://github.com/commons-app/apps-android-commons/commit/365dd76acec2463b9166aca5fe6a6dc5eacccaba

Instructions for Other Contributors - 
- I have added documentation for the methods I have created.
- I have added TODOs for the work remaining.
- Since I have utilized the old code, so it works in similar as it was working earlier.

**Comment by nicolas-raoul** [comment]
I just tried it (pushed to https://github.com/commons-app/apps-android-commons/tree/issue5372_osmdroid).

It is extremely promising, and uploading from a pin actually correctly performs the linking with Wikidata ! :-)

It is OK to keep Mapbox libraries, for instace for things like pins/etc. The only high priority is to not use Mapbox **tiles** anymore in Nearby, which this commit brilliantly accomplishes.

Since the commit is already usable, I am in favor of actually merging this into main, unless @sivaraam has any objection. This will allow us to move away from Mapbox tiles faster, I will then create issues for the remaining work (make place state / place type at the top work, "search in this area", dark mode, errors that pop up, etc).

**Comment by sivaraam** [comment]
> Since the commit is already usable, I am in favor of actually merging this into main, unless @sivaraam has any objection. This will allow us to move away from Mapbox tiles faster, I will then create issues for the remaining work (make place state / place type at the top work, "search in this area", dark mode, errors that pop up, etc).

I suppose the intention is to welcome collaboration. In that case, rather than merging it to `main`. Can we consider having a branch based out of `main` to which these changed could be merged ? After that, any following changes necessary to make it production ready could be raised as MRs to that branch. When we find the changes production ready, we could merge the same to `main` and release it.

What do you think ?

**Comment by nicolas-raoul** [comment]
@sivaraam Understood, I just hope we are able to release an osmdroid version before we go over the free Mapbox tier again. :-)

**Comment by kanahia1** [comment]
Hi @nicolas-raoul Is someone else working on this issue ?

**Comment by nicolas-raoul** [comment]
@kanahia1 You are still the only person assigned to it. 🙂

**Comment by kanahia1** [comment]
Progress :-)

https://github.com/commons-app/apps-android-commons/assets/114223204/b2f7fd05-eedc-4851-b762-19bc65bb0bd2

**Comment by nicolas-raoul** [comment]
Fantastic!
I don't see your recent changes at https://github.com/kanahia1/apps-android-commons/branches, would you mind pushing? :-)

**Comment by kanahia1** [comment]
Progress :-) * 2
https://drive.google.com/file/d/1m43Wv7eOVb8ctHgd3BfNao3I-RcKPpLm/view?usp=drive_link

I think most of the features are implemented into OSM
Few things are left, which I will try to implement ASAP and will do PR

- [ ]  Remove MapBox code
- [ ] Add better marker click design
- [ ] Test ChipGroup

@nicolas-raoul, you can add more tasks to this list, I have committed latest work here https://github.com/commons-app/apps-android-commons/commit/2e3d690ad089f423cbbd6a16e565a12c2673c70a Also I wasn't able to test Chips ( Exists, Needs Photo) since I wasn't able to spot any difference in map, even in Released version. I have tried Chips at many locations, can you please share a specific location for testing it.

**Comment by nicolas-raoul** [comment]
Wonderful!

To test the `Needs Photo` checkbox, see [Malerkotla railway station](https://www.wikidata.org/wiki/Q63356679), I just added a picture to it so it does not need really one anymore:
<img width="1596" alt="Screenshot 2023-12-13 at 12 51 00" src="https://github.com/commons-app/apps-android-commons/assets/99590/41a6346e-e207-434b-8417-5d02f2df2099">
Same for the other green points on the screenshot above.

To test the `Exists` checkbox, see [2020 COVID-19 pandemic in Punjab](https://www.wikidata.org/wiki/Q87821425) (the **2020** pandemic does not really exist currently anymore in 2023) near Jagraon:
<img width="1598" alt="Screenshot 2023-12-13 at 12 46 28" src="https://github.com/commons-app/apps-android-commons/assets/99590/c2186bab-aa40-429d-be6b-4bfadff39ace">

Screenshots taken with [WikiShootMe](https://wikishootme.toolforge.org/#lat=30.52913959075432&lng=75.88235378265382&zoom=14).

**Comment by kanahia1** [comment]
Oh I checked it, it's working

**Comment by nicolas-raoul** [comment]
Would you mind rebasing from the project repo's main branch?
Or pull from it if easier. :-)

**Comment by nicolas-raoul** [comment]
I am trying your main now, unfortunately:
- the green pins stay when I enable "Needs Photo".
- the grey pins stay when I enable "Exists".

https://github.com/commons-app/apps-android-commons/assets/99590/c426c68e-48be-43ee-8741-cdcd4998a6e2

**Comment by kanahia1** [comment]
I guess it should work now https://github.com/commons-app/apps-android-commons/commit/59d21d2d618b32b028d6c24ffd85277bd452d0a4

I will make pull request by tommorow
