### ISSUE TITLE
Prevent our Mapbox API token being abused

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#5373]
There is a possibility that Vivek's Mapbox API token was used by a bad actor, costing [480 USD](https://github.com/commons-app/apps-android-commons/issues/5351).

While it is not possible to prevent bad actors from sniffing network and getting our new token, maybe there are ways to make that less easy and to make the token less usable?

1. Set `Restrict this token to specific URLs` and set a `Referer` header to our requests. Not sure it is supported, but worth trying.
2. [Remove the token from GitHub](https://docs.mapbox.com/help/troubleshooting/private-access-token-android-and-ios/#android) even if it makes it more difficult for new developers to get started (each developer has to register at Mapbox and create their own token). A lighter strategy could be to have two tokens (owned by two core developers), one for GitHub/development and one for releases, to reduce the possibility that we need to revoke production, and so that we can easily distinguish between abuse and actual app growth.

**Comment by nicolas-raoul** [comment]
I replaced the token at https://github.com/commons-app/apps-android-commons/blob/main/app/src/main/res/values/strings.xml with a "disposable" token that I can quickly delete if some GitHub-crawling baddy abuses it, without impacting production.

@sivaraam When releasing please replace with the former token (I can also send it to you in private anytime), without committing that file. Would you mind adding this (and any other tip you have) to https://github.com/commons-app/commons-app-documentation/blob/master/android/Project-maintenance.md? :-)

**Comment by sivaraam** [comment]
> I replaced the token at https://github.com/commons-app/apps-android-commons/blob/main/app/src/main/res/values/strings.xml with a "disposable" token that I can quickly delete if some GitHub-crawling baddy abuses it, without impacting production.
> 

Sounds like a good first step, Nicolas. 👍🏼 

> @sivaraam When releasing please replace with the former token (I can also send it to you in private anytime), without committing that file. 

Sure. Feel free to send it to me when possible.

> Would you mind adding this (and any other tip you have) to https://github.com/commons-app/commons-app-documentation/blob/master/android/Project-maintenance.md? :-)

Yeah. I'll add the same, Nicolas. I have a few tweaks to the doc which could be found in another branch: https://github.com/commons-app/commons-app-documentation/blob/maintenance-tweaks/android/Project-maintenance.md

I'll make sure to add this too and raise a PR.

**Comment by nicolas-raoul** [comment]
Bad news, the `Commons-GitHub` new token (which I created and posted to GitHub on November 7) just received a Raster Tiles API request from Python, which could be a probe before sending real traffic...
It might be just a misclassification, but I will monitor closely.
The good thing is that this token can be deleted and replaced at any time without any production impact.
![Screenshot from 2023-11-13 11-50-04](https://github.com/commons-app/apps-android-commons/assets/99590/d9e27a19-c277-4310-b748-fe079d972a13)

On the other hand, the production token seems safe so far, with peak activity on weekends, highest day at 4707 requests, highest week at 23,733 so far. As users continue to update their app version, weekly average may reach 40,000 per week, just below the 200,000 monthly free tier:
![Screenshot from 2023-11-13 11-49-30](https://github.com/commons-app/apps-android-commons/assets/99590/88cd37c6-38f5-44bd-8eb9-5535b85283fa)
![Screenshot from 2023-11-13 12-03-36](https://github.com/commons-app/apps-android-commons/assets/99590/ae4288df-47d2-446c-92de-6b83bd746e04)

**Comment by mnalis** [comment]
> @sivaraam When releasing please replace with the former token (I can also send it to you in private anytime), without committing that file

Would that affect f-droid builds?

**Comment by sivaraam** [comment]
Closing this given the release of v5.0.1 in which we replaced Mapbox totally with osmdroid.

**Comment by nicolas-raoul** [comment]
Fantastic, thanks to everyone involved!
