### ISSUE TITLE
Send `Referer` header from HTTP/HTTPS requests sent by the app

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#5374]
We [must](https://github.com/commons-app/apps-android-commons/issues/5373) set a `Referer` header to our network requests for map tiles.

The Referer must be http://maps.wikimedia.org so that we don't get banned from the map tiles server.

[Here](https://stackoverflow.com/a/17444612/226958) is an example of setting a header, though it might be different for various network libraries, and the osmdroid library might have its own way of setting it.

**Comment by getoxdev** [comment]
Hi @nicolas-raoul I'm new to Open Source contributions and came across this repo which has active contributors and work going on.
Can I pick this up, if that's okay?

**Comment by nicolas-raoul** [comment]
@getoxdev It is yours, thanks! Please let us know about your progress every few days. 🙂

This may help to see the headers that are actually sent: https://developer.android.com/studio/debug/network-profiler
If the above does not work, this will: https://hackupstate.medium.com/using-charles-proxy-to-debug-android-ssl-traffic-e61fc38760f7

**Comment by nicolas-raoul** [comment]
@getoxdev Would you mind sending a draft pull request? No worries if it is not 100% finished yet. :-)

**Comment by chsaikumar445** [comment]
is this issue still open? if so can you please tell me where exactly we should add headers

**Comment by nicolas-raoul** [comment]
@chsaikumar445 No news from getoxdev, so it is yours. Please let us know about your progress every few days. 🙂

**Comment by nicolas-raoul** [comment]
@chsaikumar445 Any progress on this? 🙂

I edited the task description above, priority is now high.

**Comment by chsaikumar445** [comment]
@nicolas-raoul I am still unable to figure out how to resolve this issue.you can un assign this to me.I think I can't fix this.

**Comment by nicolas-raoul** [comment]
https://stackoverflow.com/a/74320442/226958

**Comment by nicolas-raoul** [comment]
![Screenshot_20231219-185017.png](https://github.com/commons-app/apps-android-commons/assets/99590/1e8c3856-6dd2-41c8-b197-ac71d19178be)

![Screenshot_20231219-185555.png](https://github.com/commons-app/apps-android-commons/assets/99590/f0743cd9-a3bd-4a57-b3a4-c373f34a1358)

https://raw.githubusercontent.com/osmdroid/osmdroid/master/issues/osmdroid_issue432.json

**Comment by nicolas-raoul** [comment]
https://github.com/osmdroid/osmdroid/blob/be33d9814e99d6289dd80e0ffdcb77b87cb333f9/osmdroid-android/src/main/java/org/osmdroid/config/DefaultConfigurationProvider.java#L46

**Comment by nicolas-raoul** [comment]
Here are the headers we currently send:

User-Agent: fr.free.nrw.commons/1036
Host: tile.openstreetmap.org
Connection: Keep-Alive
Accept-Encoding: gzip

I saw these headers when using Nearby (latest main branch, which is based on OsmDroid with OpenStreetMap tiles), it was getting https://tile.openstreetmap.org/14/14551/6453.png on that particular request.

In other words, we need to find out how to set Referer because it is not set right now.

**Comment by rohit9625** [comment]
Hello @nicolas-raoul sir,
I was checking the headers in Android Studio but didn't see the headers we currently send. For which request this header was sent?

**Comment by nicolas-raoul** [comment]
The headers above are for one of the requests sent to the map server immediately after opening Nearby.
I am not sure Android Studio can show these requests easily, but you can put breakpoints on OsmDroid's methods to dive down to the HTTP requests.

**Comment by rohit9625** [comment]
Okay, I'll try that but one more thing please and that is how can I log in to the app. Is there any default login for developers?

**Comment by nicolas-raoul** [comment]
@rohit9625 You must create an account. It is easy, no need for an email address or any personal details.

**Comment by rohit9625** [comment]
@nicolas-raoul  thanks for your response. I looked at the code but didn't find file related to sending HTTP requests.

**Comment by nicolas-raoul** [comment]
@rohit9625 It is inside the OsmDroid library itself. You may need to fork it.

**Comment by mnalis** [comment]
https://github.com/osmdroid/osmdroid/discussions/1961#discussioncomment-7985601 indicates that

```
Configuration.getInstance().getAdditionalHttpRequestProperties().put("myHeader", "value");
```

might work. Would someone like to try it?

**Comment by rohit9625** [comment]
Yes, I will try this. Thank you @mnalis  .

**Comment by rohit9625** [comment]
Hello sir @nicolas-raoul, I am sorry to ask you this many questions but I am unable to find the file from where the commons-app is sending requests to get those map images. 
Do you have any idea where they are?

**Comment by rohit9625** [comment]
Well, I think I found the code, and this is the header that was sent on fetching nearby places with the same User-Agent you mentioned.
![image](https://github.com/commons-app/apps-android-commons/assets/101377978/1ed323a6-1e17-4e1e-a3f8-17296ee13468)

Now after adding the code provided by @mnalis, this header is sent on each request. 
I added the referer as required :- 
**Referer** - http://maps.wikimedia.org/
![image](https://github.com/commons-app/apps-android-commons/assets/101377978/8270b066-89dc-42ec-897f-fba33b4859de)


Please check and let me know if I did it right.

**Comment by nicolas-raoul** [comment]
Great!
Please send a pull request. 🙂

**Comment by nicolas-raoul** [comment]
Sorry for expending the scope of the issue, but would you mind also adding this line?

        mapView.setTileSource(TileSourceFactory.WIKIMEDIA);

You will need to `import org.osmdroid.tileprovider.tilesource.TileSourceFactory;`.

I just tried the code below and it seems to correctly show Wikimedia's maps.
<img width="887" alt="Screenshot 2024-01-03 at 09 57 40" src="https://github.com/commons-app/apps-android-commons/assets/99590/a80a041c-066f-4706-980e-9d3d22488958">

**Comment by nicolas-raoul** [comment]
![Screenshot_20240103-090126.png](https://github.com/commons-app/apps-android-commons/assets/99590/741c5192-6323-4d28-8717-82b3132dab20)

... which looks to match Wikimedia's tile style:
![Screenshot_20240103-090221.png](https://github.com/commons-app/apps-android-commons/assets/99590/a550e8c9-161b-49cf-9d2b-8fb3814a92f5)
vs.
![Screenshot_20240103-090205.png](https://github.com/commons-app/apps-android-commons/assets/99590/51265e84-dba8-4925-aedc-ac65c94f60ce)

**Comment by nicolas-raoul** [comment]
By the way another charasteristic is that Wikimedia's server is much slower. 😅

**Comment by rohit9625** [comment]
> Sorry for expending the scope of the issue, but would you mind also adding this line?
> 
> ```
>     mapView.setTileSource(TileSourceFactory.WIKIMEDIA);
> ```
> 
> You will need to `import org.osmdroid.tileprovider.tilesource.TileSourceFactory;`.
> 
> I just tried the code below and it seems to correctly show Wikimedia's maps. <img alt="Screenshot 2024-01-03 at 09 57 40" width="887" src="https://private-user-images.githubusercontent.com/99590/293815257-a80a041c-066f-4706-980e-9d3d22488958.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyNjg0MzUsIm5iZiI6MTcwNDI2ODEzNSwicGF0aCI6Ii85OTU5MC8yOTM4MTUyNTctYTgwYTA0MWMtMDY2Zi00NzA2LTk4MGUtOWQzZDIyNDg4OTU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAzVDA3NDg1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3OTA5NmFhOGNkZjgwOWI4NjgxY2Q2NTEyM2Y1MTY3NjY0Y2E5YTE2YTVkNTA5ZjQzM2I4YmM1ZWRhNTNjMGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hZcKH3CiR3yl9fFgGHMlziqm0caVEJ3_eZaqOFaxbsM">

I created the pull request after making the required changes you mentioned. Thank you @nicolas-raoul, for helping me contribute.

**Comment by nicolas-raoul** [comment]
Confirming the fix, Nearby is now using Wikimedia's tile server. 🎉

![Screenshot_20240106-082705_Commons.jpg](https://github.com/commons-app/apps-android-commons/assets/99590/3e35c0a4-86dc-4492-a8d2-6a6833dd44ba)

![Screenshot_20240106-082747_HttpCanary.jpg](https://github.com/commons-app/apps-android-commons/assets/99590/605c67c8-cc48-4fc4-88e4-4e8ed42acb08)

**Comment by rohit9625** [comment]
Which app is this in the second screen shot?

**Comment by nicolas-raoul** [comment]
@rohit9625 It is a SSL proxy man-in-the-middle inspector similar to Charles but running entirely on Android. It also has the small window at the bottom right on the first screenshot. The name of the app is HttpCanary, unfortunately it does not exist anymore.

**Comment by rohit9625** [comment]
@nicolas-raoul Thank you for the information, this app seems useful.
