### ISSUE TITLE
Move mapbox_commons_app_token away from localization file

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#5385]
It is not meant to be translated.

Not sure what is the best place, maybe Gradle property.

**Comment by shankarpriyank** [comment]
local.properties file could be a good option.
I had a look at #5373
We can have the original token stored in github secrets and it can be easily used in the ci/cd to build the app.
But if we add the token in the local.properties, every new contributor will need to add edit the file on their local machine to build the app

**Comment by nicolas-raoul** [comment]
@shankarpriyank Thanks for the idea! We will do that if the key gets abused too often, but for now better make it as easy as possible for newcomers to build+test the app without having to register at Mapbox.com. 🙂

**Comment by mnalis** [comment]
>  But if we add the token in the local.properties, every new contributor will need to add edit the file on their local machine to build the app

That would also affect (i.e. break) f-droid builds, so I too think it should be avoided unless the abuse gets rampant
