### ISSUE TITLE
Tidy About screen

### ISSUE THREAD

**Issue by domdomegg** [commons-app/apps-android-commons#539]
Would make 'CREDITS' lowercase, seems out of place with 'Privacy policy' lowercase. Might be worth in the future having credits built into the app rather than just a link to Github (as planned in #439). Would also remove faded 'commonswiki' text as it doesn't add anything to this screen.

~~Don't know much about funding/endorsement but is the Wikimedia Foundation endorsement/affiliation legalese still relevant? I thought the project was receiving some kind of funding + with the hackathon official support (might be completely wrong on this - get confirmation from someone who knows what they're talking about first!).~~ EDIT: @nicolas-raoul cleared this up, it should not be changed

Just some thoughts, if people disagree please do comment!

![](https://cloud.githubusercontent.com/assets/6900601/25014635/7c78acbc-2070-11e7-805b-092c20986610.png)

**Comment by nicolas-raoul** [comment]
I agree with your first paragraph.

About the second paragraph: the legal statement is actually mandatory, it was written a few months ago with help from a WMF lawyer, if I am not mistaken.

**Comment by misaochan** [comment]
Agreed, some tidying appears to be in order. The legalese is required though I'm afraid. It does seem fairly strange that we have to say we're not endorsed by the WMF when we're being published by their own Google Play account. I wonder if it would be possible to revisit that particular clause someday... but perhaps that's a topic for another thread.  :)

**Comment by domdomegg** [comment]
Yea, wasn't too bothered by the legal stuff just checking it was correct as it does seem to be endorsed somewhat - if it is all correct no need to change :) Other proposals could probably still be done
