### ISSUE TITLE
Voice input for caption and description

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#5404]
The Wikipedia app shows voice input buttons when adding an image to an article:
![Screenshot_20231212-091002.png](https://github.com/commons-app/apps-android-commons/assets/99590/2d31f8cc-ef65-419c-83af-7d2a09238f1e)

Even though other apps don't show any such speech-to-text UI. So I believe the Wikipedia app added this. For privacy reasons I am generally wary of using speech-to-text, but I use and like these buttons on the Wikipedia app because I trust Wikimedia's privacy policies.

I think it would be great to offer the same in our caption&description activity within the Upload Wizard.

To avoid privacy issues, we should implement it like the Wikipedia app implements it.

**Comment by kanahia1** [comment]
Hi @nicolas-raoul , I am constantly using Wikimedia app and I have found a few issues with the current design of the Upload activity. So I have designed a new UI for the Upload Activity in Figma. If anyone has more suggestions I am happy to accept them and incorporate them into the suggested design.

![TV - 1](https://github.com/commons-app/apps-android-commons/assets/114223204/7ab7efc3-84a6-44ed-b756-22eb90e15df6)

![TV - 2](https://github.com/commons-app/apps-android-commons/assets/114223204/9b9cafeb-8f02-44f8-9daf-fc9107a6e12d)

References -
https://www.nngroup.com/articles/gestalt-similarity/

**Comment by nicolas-raoul** [comment]
Moving the + button is a really great idea!

How about creating a new row under `Step 1 of 4: Media Details` which would contain `Location` (the map icon to which we can had a `Location` label to make it more discoverable) and `Edit image`? This would help fix the two other issues you found, I believe.

**Comment by kanahia1** [comment]
@nicolas-raoul Thank you ☺️ for the suggestion, I have incorporated it in new suggested design. It will make the User Experience more effective since after selecting the location, User can easily see the selected location from the Upload Activity itself User will opening the Location Selection Activity to see selected location. 

![Frame 34330](https://github.com/commons-app/apps-android-commons/assets/114223204/76aa5747-1058-4500-9fdf-22b1487039db)

**Comment by nicolas-raoul** [comment]
When the upload has no location, it should be clearly visible that it is missing. For instance now it shows a red icon and a "?", versus a green ✅ when location is present.

We strongly want to encourage people to enter a location if absent.

**Comment by kanahia1** [comment]
I have an idea that we can show a red dot in Select Location button, which will disappear when location is selected, and Select Location text will change to selected location indicating location is selected. We can also show a `Toast` message on clicking Next if location is not selected and disable working of Next button if location is not selected. 

![Frame 34330_new](https://github.com/commons-app/apps-android-commons/assets/114223204/dd21d91b-82a9-491b-9ae7-a5bb2b3f33c7)

**Comment by kanahia1** [comment]
Hi @nicolas-raoul , Can I work over this ?

**Comment by nicolas-raoul** [comment]
@kanahia1 Yes thanks! Feel free to split into 2 pull requests (voice, other UI changes) if you want.

**Comment by kanahia1** [comment]
Sure, It will make user experience much better (^.^)
