### ISSUE TITLE
publish apk on github

### ISSUE THREAD

**Issue by basings** [commons-app/apps-android-commons#5405]
### What is the user problem or growth opportunity you want to see solved?

You can't download commons right away from the source. Moreover, the user can't download commons apk via other means, e.g. obtainium.

### How do you know that this problem exists today? Why is this important?

Play store is not available on all devices. 

### Who will benefit from it?

Everyone who downlaods apks from github, uses apps like rssreader or obtainium. Any future user of those. waydroid users.

### Anything else you would like to add?

There is #2493 but it focuses on previous builds.

**Comment by nicolas-raoul** [comment]
Hi @basings ,

Thanks for linking to that issue, I think its intent is to have APKs uploaded as soon as we release a new version, so I removed the emphasis on "past" from that question. I will thus merge this issue into that one.

I will also add a tip there about F-Droid APKs.

Thanks for using the app! :-)
