### ISSUE TITLE
F-Droid store app icon is default grey icon

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#5406]
Our app is the sad gray Android head icon (4th result):

![Screenshot from 2023-12-18 16-02-44](https://github.com/commons-app/apps-android-commons/assets/99590/c84b5477-b932-46dc-bf93-04be7faac046)

It makes our app less recognizable on F-Froid, especially on mobile.
Maybe something missing from the app resources or [F-Droid metadata](https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/fr.free.nrw.commons.yml)?

https://f-droid.org/en/packages/fr.free.nrw.commons/

**Comment by mnalis** [comment]
It is probably app resources, not F-droid metadata (as it seems not to reference any app icon even for apps whose icon is displayed just fine, like e.g. https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/de.westnordost.streetcomplete.yml)

I think it might be related to fastlane config, e.g. see discussions at:
- https://forum.f-droid.org/t/applications-icons-not-visible-in-f-droid/18955
- https://forum.f-droid.org/t/missing-icon-on-apps/19831

**Comment by mnalis** [comment]
especially [this one](https://forum.f-droid.org/t/missing-icon-on-apps/19831/9):

> That’s the solution actually.
> So for each one that you see missing, open “Issues” link, and make a new one with

 >   "Hey devs, love your app, can you add a Fastlane folder structure (no tooling needed) so the app has screenshots and icon on F-Droid? eg. [Fastlane file structure ($1895688) · Snippets · GitLab 18](https://gitlab.com/-/snippets/1895688) " Thanks

**Comment by Zen-M** [comment]
Please assign to me.

**Comment by mnalis** [comment]
Any progress / observations @Zen-M ?
