### ISSUE TITLE
Complete the Data safety form

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#5409]
I just noticed this in Play Console:

![Screenshot from 2023-12-25 14-18-21](https://github.com/commons-app/apps-android-commons/assets/99590/cbce113c-415d-4fde-8704-5050748cebbe)

@sivaraam Might be worth solving now, before we urgently need to release for some other reason?

If the answers can be saved, better save them under source control.

**Comment by sivaraam** [comment]
Sure, Nicolas. We should definitely complete it. It seems though that filling the form would require a deeper idea on how the Wikimedia Commons account is managed by WMF. This is necessary to answer questions like the following properly:

> - Add a link that users can use to request that their account and associated data is deleted 
>
> - Do you provide a way for users to request that some or all of their data is deleted, without requiring them to delete their account? (Optional)

Do you happen to have any idea / pointers about where we could obtain these details?

**Comment by nicolas-raoul** [comment]
That account deletion issue is a difficult one, let's discuss it at https://github.com/commons-app/apps-android-commons/issues/5202

**Comment by sivaraam** [comment]
Based on various discussions with Nicolas, I've submitted the Data safety form by answering "Yes" to the questions asking if users can delete their data completely cum partially. I provided the following links for the same:

- Account deletion: https://foundation.wikimedia.org/wiki/Policy:Privacy_policy/- Frequently_asked_questions#anonymize
- Data deletion: https://commons.wikimedia.org/wiki/Commons:Deletion_policy

As our production version of the app still relies on Mapbox and Mapbox might send Telemetry, I've mentioned the app shared Location information to third-parties. When we're done releasing a version of the app switching to OSMDroid with Wikimedia maps server, we could update the form to remove the mention of the same.

        Add a link that users can use to request that their account and associated data is deleted

        Do you provide a way for users to request that some or all of their data is deleted, without requiring them to delete their account? (Optional)

**Comment by sivaraam** [comment]
An update. It seems the information that we provided in the data safety form is now live in our [app's play store listing](https://play.google.com/store/apps/datasafety?id=fr.free.nrw.commons). So, I think we're done with this 🙂

**Comment by nicolas-raoul** [comment]
Fantastic!
How about releasing a new version?
There are many new great changes, and most importantly for me it would finally replace MapBox with osmdroid, thus removing a big risk floating above my wallet. :-)

**Comment by sivaraam** [comment]
Indeed Nicolas. I've opened #5528 to discuss about the release. Let's continue the discussion there 🙂
