### ISSUE TITLE
Put some link in the readme to translatewiki

### ISSUE THREAD

**Issue by domdomegg** [commons-app/apps-android-commons#541]
Would potentially stop things like #521 occurring

**Comment by nicolas-raoul** [comment]
Related: #473

**Comment by anukarsh1** [comment]
I would like to start working on this :)

**Comment by domdomegg** [comment]
Oh - looks like @janpio just did this a [couple days ago](https://github.com/commons-app/apps-android-commons/commit/142e1edaaee10a9a4ce2fd4929108a49a320332a). Thanks for volunteering though, please do take a look at the other [beginner friendly](https://github.com/commons-app/apps-android-commons/labels/beginner%20friendly) issues if you're interested in contributing

**Comment by anukarsh1** [comment]
Sure I will :)

**Comment by janpio** [comment]
Sorry for not checking if an issue about this existed - I was working on fixing a concrete bug in the DE translation and made this change as I learned how it works myself just then.

**Comment by domdomegg** [comment]
@janpio no worries - thank you for fixing it anyways :)
