### ISSUE TITLE
[Bug]: Up/Down arrow image is opposite in the fragment_upload_media_details card show/hide button

### ISSUE THREAD

**Issue by ShashwatKedia** [commons-app/apps-android-commons#5411]
### Summary

The app has the up arrow image on the arrow when the details card is fully visible and the down arrow image when the details card is hidden, contrary to the usual norm. The user should see the down arrow to hide the details card, not the up arrow to hide the details card. The same goes for when the card is hidden.

### Steps to reproduce

1. Open the app
2. Click on + button and choose any picture
3. The Media Details fragment opens
4. Click on black up arrow on the extreme left corner

![BUg img 2](https://github.com/commons-app/apps-android-commons/assets/142137555/1cf63772-f45c-4f60-852c-0de0b2516de2)

![Bug img 1](https://github.com/commons-app/apps-android-commons/assets/142137555/ead045d1-3300-4b1c-a830-919a86356c85)

### Expected behaviour

The app should have the down arrow when the details card is fully visible and the up arrow when the details card is hidden

### Actual behaviour

The app has the up arrow when the details card is fully visible and the down arrow when the details card is hidden, which is contrary to the usual expectation

### Device name

OnePlus Nord CE 2 Lite 5G

### Android version

Android 12

### Commons app version

4.2.1-debug-main~9a52e7f

### Would you like to work on the issue?

Yes

**Comment by madhurgupta10** [comment]
@ShashwatKedia Thanks for reporting, feel free to work on this issue :)

**Comment by rohit9625** [comment]
Issue seems to be resolved. I would suggest to make the sliding animation smooth as we are improving the app.
