### ISSUE TITLE
More places where we need to move away from Mapbox maps?

### ISSUE THREAD

**Issue by sivaraam** [commons-app/apps-android-commons#5414]
I happened to use the app today with the changes for #5372. The Nearby screen appears not be using Mapbox tiles anymore. The other maps that are present in the app still seem to Mapbox tiles. This includes the following screen (as far as I've checked):

1. Explore -> Map
2. The edit location screen that appears when tapping on the map icon in first page of the upload flow.
3. Anything else?

Though they would have relatively fewer requests compared to the Nearby screen, they don't show appropriate Mapbox attribution now. So, we should either switch to OSM tiles in those screens or give appropriate Mapbox attribution.

PS: We ultimately need to start using Wikimedia maps tiles. That's the topic for #1002, though.

**Comment by nicolas-raoul** [comment]
You are right that most requests come from Nearby, so it was the most urgent.
Sorry I missed the attribution change in the other maps!

**Comment by nicolas-raoul** [comment]
@kanahia1 Great! Looking forward to your PR. :-)

**Comment by kanahia1** [comment]
Hi @nicolas-raoul, I am working on Explore -> Map. I was testing the map around my location but wasn't able to get any information, always `null` is returned. I tested it with Mapbox version(beta) it also returned `null`. 

https://github.com/commons-app/apps-android-commons/assets/114223204/e1101433-a1d2-477a-9630-e4815edb9c5e

But It worked at `(0.0,0.0)` . Can you please share me any location where I test OSMDroid.
![WhatsApp Image 2024-01-19 at 12 57 19_df41f00a](https://github.com/commons-app/apps-android-commons/assets/114223204/b3f3d261-1651-42d3-99f7-b0be5c2b8473)

**Comment by nicolas-raoul** [comment]
@kanahia1 Interesting, the map seems to work for me. Can you use FakeGPS to check at the center of a big city like Lima? Also, can you create a new issue about replacing MapBox in Explore? Thanks! 🙂
![Screenshot_20240119-171043.png](https://github.com/commons-app/apps-android-commons/assets/99590/c30fb15e-f4b4-4e60-9dda-8ccc8a62aca4)

**Comment by nicolas-raoul** [comment]
@kanahia1 Also, can you create a new issue about this `Attempt to read from null` error? At least the error message should be made more useful and user-friendly.
