### ISSUE TITLE
Shared 15 pictures from gallery, but only 1 uploaded

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#5416]
Despite filling metadata details for all.
The contributions activity then showed several ongoing uploads, and I turned the phone's screen off.
When I turned the screen on again the next day, I could only see 1 uploaded picture in Contributions.
The Commons website shows that all pictures were overwritten to one:
![Screenshot_20240103-080130.png](https://github.com/commons-app/apps-android-commons/assets/99590/b3e0e0b4-ef16-4c49-aaa5-88f667b48dcc)
https://commons.m.wikimedia.org/wiki/File:%E4%B8%87%E4%B8%96%E5%A4%A7%E8%B7%AF_trail-_entrance_at_%E7%80%A7%E5%B2%A9%E4%B8%8A%E6%A9%8B.jpg

That might be because of the `:` character I wrote as the caption for all files:

 万世大路 trail: entrance at 瀧岩上橋 

The `:` gets replaced with `-` by the Commons server when uploading.
The app is supposed to add a number suffix if the file already exists on the Commons server, but I suspect that it does not check what the actual filename (after upload) is.

**Comment by rohit9625** [comment]
Hey @nicolas-raoul, I am confused. How can I
 reproduce this bug?

**Comment by RitikaPahwa4444** [comment]
Hi @rohit9625, I'm able to reproduce this by following these steps:
1. Tap on the `+` button in the Contributions tab.
2. Initiate a multi-upload by choosing 2 or more images using the normal or custom selector (the two options other than the one with a camera icon)
3. Enter a caption that has a colon (`:`) 
4. Tap `Copy to Subsequent Media` to use the same caption for all the files
5. Continue with the upload. Once the progress bars appear for the uploads in the Contributions tab, turn the screen off.

After all the images get uploaded, only one image appears in the Contributions tab. Actually, the same file gets overwritten (I check my uploads [here](https://commons.wikimedia.org/w/index.php?title=Special:ListFiles/RitikaPahwa4444&ilshowall=1), you can replace the username to check yours 🙂) . This does not happen with files that do not have a colon in their caption. 

Hope this helps!

**Comment by rohit9625** [comment]
Thank you @RitikaPahwa4444 
These steps help me identify the error. Are you working on this issue or not?

**Comment by rohit9625** [comment]
There is one more thing when I try to delete this image that I uploaded with the steps above. The scroll bar keeps loading with no error handling on the client side. But on the server side it keep sending request for deletion like this :
`
{
    "batchcomplete": true,
    "query": {
        "normalized": [
            {
                "fromencoded": false,
                "from": "Commons:Deletion_requests/File:India- plants images.jpg",
                "to": "Commons:Deletion requests/File:India- plants images.jpg"
            }
        ],
        "pages": [
            {
                "ns": 4,
                "title": "Commons:Deletion requests/File:India- plants images.jpg",
                "missing": true
            }
        ]
    }
}
`

And as a reponse getting this :
`
{
    "batchcomplete": true,
    "query": {
        "pages": [
            {
                "title": "File%3AIndia-%20plants%20images.jpg",
                "invalidreason": "The requested page title contains invalid characters: \"%3A\".",
                "invalid": true
            }
        ]
    }
}
`
Is this due to invalid name or any other thing?
@RitikaPahwa4444 @nicolas-raoul

**Comment by nicolas-raoul** [comment]
The bug when trying to delete will probably be solved by solving the issue described initially.

**Comment by rohit9625** [comment]
Yes you are right Mr. @nicolas-raoul 
I am working on this.

**Comment by RitikaPahwa4444** [comment]
> Are you working on this issue or not?

No, I'm not working on it right now, thank you for looking into it! :)

**Comment by rohit9625** [comment]
When the file was uploading while the progress was shown in the contributions, then our app sent a request to Wikimedia API, and in response, we are getting this error :
`
{
  "errors": [
    {
      "code": "illegal-filename",
      "text": "The filename is not allowed.",
      "module": "upload"
    }
  ],
  "docref": "See https://commons.wikimedia.beta.wmflabs.org/w/api.php for API usage. Subscribe to the mediawiki-api-announce mailing list at &lt;https://lists.wikimedia.org/postorius/lists/mediawiki-api-announce.lists.wikimedia.org/&gt; for notice of API deprecations and breaking changes.",
  "servedby": "deployment-mediawiki11"
}
`
That means the server does not allow the file name that was sent.

**Comment by rohit9625** [comment]
@RitikaPahwa4444 @nicolas-raoul 
Should we implement the logic to sanitize file_name before sending.
Also when we click on the image which we was trying to upload, we receives an object 
`
{
    "batchcomplete": true,
    "query": {
        "pages": [
            {
                "title": "india%3A%20street.heic",
                "invalidreason": {
                    "code": "title-invalid-characters",
                    "text": "The requested page title contains invalid characters: \"%3A\"."
                },
                "invalid": true
            }
        ]
    }
}
`
Here the title contains `"%3A" to represent the colon. So we must remove the characters that are not allowed.

**Comment by nicolas-raoul** [comment]
Sanitizing before sending sounds like a valid strategy. I think we already sanitize a bit, you may want to search the code for `anitiz` or similar.

**Comment by rohit9625** [comment]
I found this method for sanitizing but I guess this method is not used anywhere except for unit tests.

`
    public static String sanitizeText(@NonNull String selectedText) {
        return selectedText.replaceAll("\\[\\d+\\]", "") // [1]
                // https://en.wikipedia.org/wiki/Phonetic_symbols_in_Unicode
                .replaceAll("\\s*/[^/]+/;?\\s*", "")
                .replaceAll("\\(\\s*;\\s*", "\\(") // (; -> (    hacky way for IPA remnants
                .replaceAll("\\s{2,}", " ")
                .trim();
    }
`

**Comment by nicolas-raoul** [comment]
@rohit9625 If you remove that method and its unit tests, does the app still build? If yes, please send a pull request. :-)

**Comment by rohit9625** [comment]
Is it necessary?
Because we were focusing on the colon issue?

**Comment by rohit9625** [comment]
And yeah the app still builds successfully. Also, there are more functions in the file - `StringUtil.java`, which has no implementation yet.
@nicolas-raoul

**Comment by nicolas-raoul** [comment]
I guess this method was used to prevent such issues, but was forgotten during a code rewrite.
The problem is probably not only with `:` but also with the characters in that method, so it could be good to call it. You may want to check out a version of the app from 2 years ago (for instance) and check where/how the method was called.

**Comment by rohit9625** [comment]
@nicolas-raoul 
I checked several versions of commons. There is a folder **<data-client>** inside which file **<StringUtils.java>** is placed and the sanitize method is too inside this file. But this folder doesn't even exist in the versions < **v3.0**. 
And for versions later, there is no implementation of this method `sanitizeText()`.
File location in current version - `apps-android-commons\data-client\src\main\java\org\wikipedia\util\StringUtil.java`
I think we should call this method from an appropriate place before sending the file name to the Wikimedia **API**.

The thoughts I have in my mind: -
1. Do we allow the user to upload the file with `: ` in caption.
    -If not then, we can call this method there, just like the title extracted from the caption, replacing colon`: ` with `-`.
    
![WhatsApp Image 2024-01-12 at 14 55 26_fc947204](https://github.com/commons-app/apps-android-commons/assets/101377978/c3f577fa-2e04-44cd-9594-5195e464ebab)

2. If we allow the user to upload the image with caption having `: `, then we can send the sanitized file name to the **API**.

**Comment by nicolas-raoul** [comment]
Here is the class that performs sanitization:

https://github.com/commons-app/apps-android-commons/blob/main/app/src/main/java/fr/free/nrw/commons/upload/UploadMediaDetailInputFilter.java

Please first create a new unit test for `:` at https://github.com/commons-app/apps-android-commons/blob/main/app/src/test/kotlin/fr/free/nrw/commons/upload/UploadMediaDetailInputFilterTest.kt

Thanks! :-)

**Comment by nicolas-raoul** [comment]
@rohit9625 That sounds very promising! Looking forward to your pull request. 🙂

**Comment by rohit9625** [comment]
Hey Mr. @nicolas-raoul
After the changes I made, it's not allowing me to write `: ` in the caption. See the video:

https://github.com/commons-app/apps-android-commons/assets/101377978/829dec0d-8f13-4986-9e1f-5280cb341bce

Is this the required behavior?

**Comment by rohit9625** [comment]
Okay then, after manual testing I will create a PR for sure :)
