### ISSUE TITLE
Bulk translation fixes

### ISSUE THREAD

**Issue by domdomegg** [commons-app/apps-android-commons#542]
All the occurrences of
```
https://github.com/wikimedia/
```
should be replaced by
```
https://github.com/commons-app/
```

All the occurrences of
```
u00A0
```
should be replaced by
```
 
```
(a space)

All the occurrences of
```
...
```
should be replaced by
```
…
```
(an ellipsis character)

Saw an example a recent commit by translatewiki that this had been done individually - is there a way to do a simple find and replace (e.g. 66 occurrences) without breaking translatewiki?

https://github.com/commons-app/apps-android-commons/commit/fe470d64a9db37d84b3cbcd93c01e54023439c5a#diff-e4b5bf4dab53932e7bda5f0aed5aef7bR67

**Comment by whym** [comment]
Changing strings in this repository will trigger FuzzyBot to reflect it on translatewiki.net in a couple of days, I believe. (See #490)

To start with, I would suggest changing two or three of them to test.

**Comment by whym** [comment]
Looking at #597 I noticed that there are a few more replacements to do:

 https://github.com/nicolas-raoul/apps-android-commons/
 https://github.com/commons-app/apps-android-commons/

 https://github.com/commons-app/android-commons/
 https://github.com/commons-app/apps-android-commons/

**Comment by whym** [comment]
Just noting that the last change worked:

https://translatewiki.net/w/i.php?title=Wikimedia:Commons-android-strings-about_improve/nds-nl&diff=prev&oldid=7380121
https://translatewiki.net/w/i.php?title=Wikimedia:Commons-android-strings-about_license/sk&diff=prev&oldid=7380070

**Comment by domdomegg** [comment]
Will proceed with other bulk translation fixes soon

**Comment by nicolas-raoul** [comment]
I guess this is fixed?
