### ISSUE TITLE
Button to thank the uploader, in Media Details

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#5421]
Unless the user is the uploader.

The code to thank the person who uploaded an image has been implemented already, in Peer Review, it can be reused.

The button could be similar to the Copy Wikitext button, and placed directly below it:
![Screenshot_20240108-173704.png](https://github.com/commons-app/apps-android-commons/assets/99590/24202144-2eb0-4d4e-872c-ee592fa4ee7a)

**Comment by srishti-R** [comment]
@nicolas-raoul would you be able to paste the link of the PR where this thank author logic is coded?

**Comment by nicolas-raoul** [comment]
@srishti-R Sorry not sure about the PR, but the code is called by this button in "Review":
![Screenshot_20240108-223401.png](https://github.com/commons-app/apps-android-commons/assets/99590/4967604e-97bc-4d84-9fcb-88ce140ca169)

**Comment by awanishyadav967** [comment]
Hi @nicolas-raoul ,I see this issue is still open ,May I work on this?

**Comment by nicolas-raoul** [comment]
@awanishyadav967 This one is fixed, sorry for the delay in merging! Would you mind choosing another? :-)
