### ISSUE TITLE
Nearby pins hard to see in dark mode

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#5438]
Maybe another color set would work better?
The same color should be used and clearly visible in light mode too.

![Screenshot_20240115-165748.png](https://github.com/commons-app/apps-android-commons/assets/99590/ba3c2e3c-a858-4b1d-9734-3f710eb7d309)

**Comment by rohit9625** [comment]
I have some color ideas to apply. So, may I take this issue?

**Comment by rohit9625** [comment]
I had this color in my mind and now it seems to be visible for both themes.

**Light Mode**
![WhatsApp Image 2024-01-15 at 14 42 11_9fa183fa](https://github.com/commons-app/apps-android-commons/assets/101377978/78789451-7bf2-43ed-bfcb-69f163606c81)

**Dark Mode**
![WhatsApp Image 2024-01-15 at 14 42 11_d628f5c6](https://github.com/commons-app/apps-android-commons/assets/101377978/6950cb80-c355-4ff5-a88e-3fb2c23e4434)


Please share your thoughts about this color, i.e., `Light Sea Green`.

**Comment by nicolas-raoul** [comment]
Looks good to me! :-)

**Comment by rohit9625** [comment]
Should I create a PR or wait for more suggestions?

**Comment by nicolas-raoul** [comment]
Yes, please create a PR. :-)
