### ISSUE TITLE
Update nearest location distance as user moves towards it, in home nearby banner

### ISSUE THREAD

**Issue by ShashwatKedia** [commons-app/apps-android-commons#5444]
### Anything else you would like to add?

Adding a compass to the home banner was a great addon, but I believe adding a feature to update the user's distance from the nearby location is required. Updating the user's distance from the nearby location will keep the user informed and encourage them to move to the nearest location since they wouldn't have to keep closing the app and opening it (or some other manual way to refresh it) to get the updated distance.

**Comment by nicolas-raoul** [comment]
I was thinking the same yesterday! :-)
Feel free to take it if you want when you are done with current assignments.

**Comment by ShashwatKedia** [comment]
Sure! I'll take it :)
