### ISSUE TITLE
Highliting nearest location on nearby map, when user clicks on home banner

### ISSUE THREAD

**Issue by ShashwatKedia** [commons-app/apps-android-commons#5445]
### Anything else you would like to add?

Clicking on the nearby home banner opens the nearby map but doesn't display/highlight the nearest location, which the user would expect when he clicks. It will also help them know the name of the place since the name is usually cut short in the home banner. Also after clicking on the banner, it disappears when we go back to contributions fragment, which shouldn't happen.

**Comment by ShashwatKedia** [comment]
Sure! I'll start to work on it then :)

**Comment by ShashwatKedia** [comment]
I am able to highlight the nearest item when the user clicks on the banner by changing the marker to a different colour and also showing the bottom sheet details of the item. I am wondering whether we should always keep the nearest place marker with a different colour, or should it be changed only when the user clicks on the banner(and will revert back to normal after moving to another fragment). @nicolas-raoul what are your views on this?

**Comment by nicolas-raoul** [comment]
@ShashwatKedia No strong opinion on this, feel free to choose the behavior you prefer, or the one which is easiest to implement/maintain. 🙂
