### ISSUE TITLE
Nearby banner: Show item with no image

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#5448]
The Nearby banner currently shows the nearest Wikidata item.

Instead, I think it should show the nearest Wikidata item **with no image**.

Merits:
- Get users to take the most needed pictures
- After the user uploads the item, the banner will start showing a different item, rather than still showing the same one which is uninteresting.

**Comment by shashankiitbhu** [comment]
I believe I can work on this issue, can you assign this to me?

**Comment by shashankiitbhu** [comment]
@nicolas-raoul Please Review #5468

**Comment by nicolas-raoul** [comment]
Ah, sorry for not mentioning this at first, but would you mind also ignoring **items that do not exist**? Bonus if you can reuse the logic found behind the Nearby activity "Exists" checkbox.

**Comment by shashankiitbhu** [comment]
Sure, will make these changes in the next commit
