### ISSUE TITLE
Banner compass does not change directly even after I walk past the place

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#5455]
The banner compass indicates the right direction (for instance North) at first, but then as I go around the place (because there are other buildings around it), the compass continues to show the same direction (North), even though the place is now actually in another direction (West).

It would be great if the compass direction could update based on my position and the position of the place.

This otherwise great feature was introduced via https://github.com/commons-app/apps-android-commons/pull/5433.

**Comment by ShashwatKedia** [comment]
I don't think this should happen, but I will still test this and resolve this bug. This might also be solved when I do a PR for resolving #5444 because updating the banner as the user moves will automatically update the direction of the compass as well ;)

**Comment by ShashwatKedia** [comment]
@nicolas-raoul I think this issue can also be marked as completed, as it was resolved via #5459. What do you think?

**Comment by nicolas-raoul** [comment]
Yes thanks! :-)
