### ISSUE TITLE
[Bug]: Attempt to read from null error in Explore -> Map fragment

### ISSUE THREAD

**Issue by kanahia1** [commons-app/apps-android-commons#5457]
### Summary

This issue is caused when there are no elements in `mediaList` Maybe the issue caused when there are no media (images) available at specific coordinate.

### Steps to reproduce

1. Open Explore -> Map Fragment in App
2. Go to Bihta, Patna, India or Coordinates = 25.5303740, 84.8597150 in map 

### Expected behaviour

Place's images should appear on the map.

### Actual behaviour

Toast message `Error fetching nearby places. Attempt to read from null... `

### Device name

Samsung S21

### Android version

Android 14

### Commons app version

4.2.1-debug-HEAD~9be8df3

### Device logs

`java.lang.NullPointerException: Attempt to read from null array
                                                                                                    	at fr.free.nrw.commons.explore.map.ExploreMapPresenter.getLatLngBounds(ExploreMapPresenter.java:223)
                                                                                                    	at fr.free.nrw.commons.explore.map.ExploreMapPresenter.updateMapMarkers(ExploreMapPresenter.java:193)
                                                                                                    	at fr.free.nrw.commons.explore.map.ExploreMapFragment.updateMapMarkers(ExploreMapFragment.java:433)
                                                                                                    	at fr.free.nrw.commons.explore.map.ExploreMapFragment.lambda$populatePlaces$5$fr-free-nrw-commons-explore-map-ExploreMapFragment(ExploreMapFragment.java:413)`

### Screen-shots

https://github.com/commons-app/apps-android-commons/assets/114223204/3babe197-7160-4de2-8760-7035c0676d56

### Would you like to work on the issue?

Yes

**Comment by ShashwatKedia** [comment]
@kanahia1 this might happen because you are using the betaDebug variant, as was the case here https://github.com/commons-app/apps-android-commons/issues/5255#issuecomment-1890995267, pointed out by @nicolas-raoul here: https://github.com/commons-app/apps-android-commons/issues/5255#issuecomment-1891572569. Does the issue persist in prodDebug variant as well?

**Comment by kanahia1** [comment]
Thanks @ShashwatKedia it worked! on production server. But we will need to handle it since there can be a place on earth where are no images in that case there will be this error. So, we can show some dialog at that place to make user experience better.

**Comment by nicolas-raoul** [comment]
Indeed, I just tried with prodDebug in Siberia and get the same error:
![Screenshot_20240120-071808.png](https://github.com/commons-app/apps-android-commons/assets/99590/23a91953-7fec-4f3a-a5fd-610a67705cfa)

**Comment by rohit9625** [comment]
Using dialogues can be interrupting for users. Instead, we should use `Snackbars`  with proper error messages. Concisely, this is what I mean :
![WhatsApp Image 2024-01-21 at 17 55 05_0bcf6fa8](https://github.com/commons-app/apps-android-commons/assets/101377978/1acdbbe9-6306-4214-a4db-95c02d2e9ff1)


Although, we can move from `Toasts` to `Snackbars`. What do you say?
@nicolas-raoul @kanahia1

**Comment by nicolas-raoul** [comment]
Yes snackbar is good.

I think we should try to convey the real problem to the user, though.

Here, the real problem is that there are no Wikidata items in that area, right?

**Comment by rohit9625** [comment]
No problem, I am adding a new string in the resource. This will be displayed to the user.
Can you provide a well-formatted message to be displayed to the user?

**Comment by nicolas-raoul** [comment]
How about `No Wikidata items in this area`? :-)

**Comment by rohit9625** [comment]
Well, this seems to be a good response we can provide. I am placing it in the resources. 
Although, I have a question, i.e., I created a method to display the `snackbar` in the same file where `showToasts()` method is defined.
Do I need to create any UI test for `snackbar`.

**Comment by rohit9625** [comment]
After making changes, these are the results:

**Light Mode**
![WhatsApp Image 2024-01-21 at 19 49 21_32bd796a](https://github.com/commons-app/apps-android-commons/assets/101377978/ca8ac4b3-e8dc-4072-8768-9e89b2976357)

**Dark Mode**
![WhatsApp Image 2024-01-21 at 19 49 21_8a749ca6](https://github.com/commons-app/apps-android-commons/assets/101377978/4660ecba-4213-4c55-885c-8419299563c4)


However, there was a resource already string like this:
`<string name="no_nearby_places_around">No nearby places around</string>`
But the text provided by you seems much better.

**Comment by nicolas-raoul** [comment]
Ah, no_nearby_places_around is great, thanks for finding it! 🙂

**Comment by nicolas-raoul** [comment]
Ah wait, I was totally forgetting the context since yesterday, I am so sorry! 😱

Please use "No pictures in this area".

Thanks! 🙂

**Comment by rohit9625** [comment]
**Done** 👍
![WhatsApp Image 2024-01-22 at 20 49 19_c86f5d85](https://github.com/commons-app/apps-android-commons/assets/101377978/a159121b-abbd-429e-a774-5902c9d70ebd)

Please express your thoughts about the colors and action button for the `**Snackbars**` because I am considering replacing all the toasts with a beautiful `**Snackbar**`.
What do you think?

**Comment by kanahia1** [comment]
Hey @rohit9625, 
I think we cannot replace all the Toasts with Snackbars since Toasts usually are used to display text related with system or some background services since Toasts are shown even if Activity is finished. So replacing all the Toasts with SnackBars can cause disturbance in User Experience.

---
References
https://m2.material.io/components/snackbars#usage
https://stackoverflow.com/questions/34432339/android-snackbar-vs-toast-usage-and-difference

**Comment by rohit9625** [comment]
Oh, my bad!😅
Yeah, you are right Mr. @kanahia1. We can't replace all the toasts but some toasts should be replaced I guess.

**Comment by nicolas-raoul** [comment]
@rohit9625 Your screenshot looks great! 🙂

**Comment by kanahia1** [comment]
Hey @rohit9625, I have added TODO for snackbar in https://github.com/commons-app/apps-android-commons/pull/5475, you can add code for snackbar and share a pull request. 🙌

**Comment by rohit9625** [comment]
Showing will work after solving this issue #5487 
Have a look @kanahia1

**Comment by kanahia1** [comment]
Sure @rohit9625 I will look into #5487

**Comment by rohit9625** [comment]
Done Mr. @kanahia1 👍

**Comment by rohit9625** [comment]
Hello @nicolas-raoul 
Can you please look at the PR that solves this issue? 
I don't know why the previous PR closed. I am creating a new PR.
