### ISSUE TITLE
Title in the Contributions tab says "No uploads..." despite having many

### ISSUE THREAD

**Issue by RitikaPahwa4444** [commons-app/apps-android-commons#5462]
### Summary

Earlier, the exact number of uploads used to show up at the top, but now it says "No uploads...". The images appear as usual, though.

### Steps to reproduce

1. Open the Contribution tab
2. Check the upload count at the top.

### Expected behaviour

The title should display the user's upload count.

### Actual behaviour

The title says "No uploads..."

### Device name

Redmi 5A

### Android version

8.1.0

### Commons app version

main and prodDebug

### Screen-shots

| Earlier | Now |
| --- | --- |
| ![image](https://github.com/commons-app/apps-android-commons/assets/83745993/5cc20a32-ca2c-4216-a14c-3c787c8bcadf) | ![contributions_fragment](https://github.com/commons-app/apps-android-commons/assets/83745993/3b31c055-c8a7-49a4-9c06-8a30693f9a75) |

PS: Not sure if [this](https://github.com/commons-app/apps-android-commons/issues/5287#issuecomment-1902591415) is the reason behind this issue too.
### Would you like to work on the issue?

None

**Comment by rohit9625** [comment]
I can reproduce this issue as well on my device 👍

**Comment by psh** [comment]
When I debug the app, I see that its making a request to `https://tools.wmflabs.org/urbanecmbot/commonsmisc/uploadsbyuser.py` passing my userId as a "user" parameter.  The HTTP response is a **503** (service unavailable) error.

**Comment by ShashwatKedia** [comment]
Yup, I get the same. It is also the reason the user level is not loading for everyone in the achievements section. The user achievement level cannot be calculated and shows that error because the number of images uploaded, reverted, etc., is not obtained.

**Comment by RitikaPahwa4444** [comment]
Thank you, @psh for checking this. Hopefully, it will be back with the achievements🙂

**Comment by sivaraam** [comment]
@urbanecm It appears as if the production version of the app is still dependent on the commonsmisc available via urbanecmbot for showing the upload count and achievements screen. Is it possible for you to bring it up?

We could explore completely switching to the other commons-android-app instance and let you know once that's released. 

For those unaware some related discussion related to both the tools in the following issue: #5197

**Comment by RitikaPahwa4444** [comment]
Is this issue back? :(

![contributions_screen](https://github.com/commons-app/apps-android-commons/assets/83745993/295c5910-fdd2-46e2-a8fc-6fdefd8f2a7d)
![achievements_screen](https://github.com/commons-app/apps-android-commons/assets/83745993/1830600c-b467-45bd-bcd5-3120d167d634)

Tested the latest main branch on API level 34.

**Comment by sivaraam** [comment]
Yeah. Seems like it. The tool URL is throwing a 500 now. Need to check what's wrong.

https://commons-android-app.toolforge.org/tool-commons-android-app/uploadsbyuser.py?user=syced

@whym Could you take a look at this?

**Comment by whym** [comment]
error.log indicates that the issue started since March 18, after the web service automatically restarted. The automatic restart might have been incomplete somehow. Today I manually restarted it and the problem seems to go away.

**Comment by rohit9625** [comment]
We should store data that are required by the fragments, displayed in the screenshots, to let users see their achievements and no. of contributions even when the URL returns with 500.

**Comment by nicolas-raoul** [comment]
@rohit9625: None of these stats are vitally important, so I would say better leave the problem be apparent rather than use cached numbers. But since server error are relatively frequent, we might want to make the app show "Contributions (error fetching number)" rather than "No uploads..."

Also, maybe an email alert could be implemented? It would check the URL like once a day, and if failed send an email to someone who has the right to restart the server.

**Comment by sivaraam** [comment]
> error.log indicates that the issue started since March 18, after the web service automatically restarted. The automatic restart might have been incomplete somehow. Today I manually restarted it and the problem seems to go away.

Thank you for quickly fixing this, @whym! I could confirm that it works fine.

**Comment by rohit9625** [comment]
> Also, maybe an email alert could be implemented? It would check the URL like once a day, and if failed send an email to someone who has the right to restart the server.

Yeah, right. Doing this will be a pretty nice approach if these stats are not that important. We should indicate to the user that this is a server error and you should try again after some time.

**Comment by RitikaPahwa4444** [comment]
It's working now, thank you, @whym!

**Comment by RitikaPahwa4444** [comment]
Might not be related, but I remember the app used to show the number of thanks received (I do have some)🤔
![Screenshot_20240322-194331](https://github.com/commons-app/apps-android-commons/assets/83745993/4bb3a3e1-412c-4719-aefe-6aa1a4ffd3cc)

**Comment by sivaraam** [comment]
> Might not be related, but I remember the app used to show the number of thanks received (I do have some)🤔 ![Screenshot_20240322-194331](https://private-user-images.githubusercontent.com/83745993/316049719-4bb3a3e1-412c-4719-aefe-6aa1a4ffd3cc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExMTcyNTAsIm5iZiI6MTcxMTExNjk1MCwicGF0aCI6Ii84Mzc0NTk5My8zMTYwNDk3MTktNGJiM2EzZTEtNDEyYy00NzE5LWFlZmUtNmFhMWE0ZmZkM2NjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIyVDE0MTU1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhMjQxNTJhNmUzMjFmMzlmZjliZTY0OGFkZGZjMzE2YWFhM2U4MGMxMzVlMjhmZTM2OWExMTE4YzU1ZjRjMDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fG_uBaNn-Yntpm9Py_0pBoLwswUCFAMQIsskx3H-H_Q)

Feel free to open a separate issue for this. We  cam investigate it.

**Comment by sivaraam** [comment]
> > Also, maybe an email alert could be implemented? It would check the URL like once a day, and if failed send an email to someone who has the right to restart the server.
> 
> Yeah, right. Doing this will be a pretty nice approach if these stats are not that important. We should indicate to the user that this is a server error and you should try again after some time.

Yeah. The ideas js nice. Feel free to propose the same in a separate issue.

**Comment by rohit9625** [comment]
Right, it should display 0 in my case but its empty.
