### ISSUE TITLE
Show Details About Icon Labels when long pressed

### ISSUE THREAD

**Issue by shashankiitbhu** [commons-app/apps-android-commons#5470]
### What is the user problem or growth opportunity you want to see solved?

In the Nearby Page when we click on a Place we see multiple Icons in the bottom sheet like Wikipedia and Bookmark but to a new user it not be clear which Icon means what and it's quite confusing. In general it's a good practice in Android Development to show more context for icons and buttons.

### How do you know that this problem exists today? Why is this important?

I want to Implement a feature that when these Icons are Pressed for long then a Toast should appear Indicating the label of the Icon giving user Information about what clicking on Icon will do

### Who will benefit from it?

Users will benefit from this as it will Improve User Experience

### Anything else you would like to add?

I have implemented this on one of the Icons to showcase the Impact of this

https://github.com/commons-app/apps-android-commons/assets/126143257/5e6af6f9-8d39-41f5-8dbb-77d3463f2b55

I would like to add context like this on Icons in the app which might be confusing to users.

**Comment by shashankiitbhu** [comment]
@nicolas-raoul what do you think about this enhancement? can you please review it and tell me if we can do this then I'll be happy to make the PR

**Comment by nicolas-raoul** [comment]
Yes good idea! 🙂

**Comment by shashankiitbhu** [comment]
@nicolas-raoul Please Review above PR and close this issue, thanks

**Comment by nicolas-raoul** [comment]
Thanks a lot!

Do you think it would be helpful to imrlement the same on these buttons? The bottom two are especially ambiguous.
![Screenshot_20240129-170612~2.png](https://github.com/commons-app/apps-android-commons/assets/99590/293f7bd8-a874-4ea3-bb09-0d602c7977ba)

**Comment by shashankiitbhu** [comment]
Yes I think it would definitely help , I'll create a new PR (or should I create a new issue?) for them. Also if you have more suggestions then please mention in this conversation I'll implement them too

**Comment by nicolas-raoul** [comment]
Just new PR is fine 🙂
Thanks a lot!

**Comment by shashankiitbhu** [comment]
@nicolas-raoul Please Review the above PR, thanks
