### ISSUE TITLE
[Bug]: App Crashes when Switched Between Dark/Light Mode in Location Picker Activity

### ISSUE THREAD

**Issue by shashankiitbhu** [commons-app/apps-android-commons#5474]
### Summary

The App Crashes when you switch between Light/Dark mode on your device in the Location Picker Activity. I believe it will crash in any Configuration change on your device, Like changing Font-size Similar to issue #5437 opened by @nicolas-raoul , I think we need to handle configuration change for this activity , I will be doing that in my next PR

### Steps to reproduce

1. Open the App
2. Go to any of your Contributions
3. Select Edit Location Icom
4. Switch Between Light/Dark Mode on your Device

### Expected behaviour

App Should not Crash

### Actual behaviour

App Crashes

### Device name

Xaomi 11 Lite NE

### Android version

13

### Commons app version

4.2.1-debug-main

### Screen-shots

https://github.com/commons-app/apps-android-commons/assets/126143257/f2015614-6b4c-4b30-a5bf-dbcda5f4eea0

### Would you like to work on the issue?

Yes

**Comment by rohit9625** [comment]
Yes you are right. It's crashing.

**Comment by geektan123** [comment]
Assign #5474

**Comment by shashankiitbhu** [comment]
I am already working on this as Indicated in OP, @nicolas-raoul can you look at this bug and assign it to me, thanks

**Comment by shashankiitbhu** [comment]
@nicolas-raoul Please Review the above PR, thanks
