### ISSUE TITLE
When editing an already uploaded picture's depictions, depiction search does not find anything

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#5485]
Does not find the "cat" Wikidata item, which exists:

https://github.com/commons-app/apps-android-commons/assets/99590/34ad8fbe-ad2a-4b37-82f0-32b7ad9730d9

Also, there should not be a "Next" button. It seems sort of mixed with the Upload Wizard.

**Comment by rohit9625** [comment]
Is this happening due to a recent PR?

**Comment by rohit9625** [comment]
Issue occurred after this PR #5466 and I find out the fix. Creating a PR :)
