### ISSUE TITLE
[Bug]: Explore Map crashing when location permission not given and not working as intended

### ISSUE THREAD

**Issue by ShashwatKedia** [commons-app/apps-android-commons#5490]
### Summary

The explore map fragment crashes when location permission is denied. Also, a Toast message saying "nearby might not work properly, location not available" keeps getting displayed. On reopening the app and denying permission again, it doesn't behave correctly. It should show the nearby images, even when the location is unavailable, but the fragment behaves similarly to #5461. Similar to the nearby fragment, the explore fragment doesn't show nearby images, the progress bar keeps loading and the 'Search This Area' button never loads when there is no location access to the app. The app behaves similarly even when the location access is granted but the location services are off. I think this behaviour is due to the recent migration to OSMDroid.

### Steps to reproduce

1. Freshly install and open the app
2. Open the map tab of the explore fragment
3. Deny permission for location, when prompted

### Expected behaviour

The app should display the nearby images of the default location, even when location permission is denied or location services are off.

### Actual behaviour

The app crashes unexpectedly when location permission is denied. When opened again, the progress bar of the explore fragment keeps loading and nearby images are not shown.

### Device name

OnePlus Nord CE 2 Lite

### Android version

Android 12

### Commons app version

main and prodDebug

### Screen-shots

App crashing on location permission denied:
https://drive.google.com/file/d/170P_A_AOlb9EzjDkI_cUMApHjFdlXBHr/view?usp=sharing

Explore not working intendedly even when location permission is there, but location services are off:
https://drive.google.com/file/d/1YFQqr4X0oIbQiZHUdQRVpeqVqHWbDXWO/view?usp=sharing

### Would you like to work on the issue?

Yes

**Comment by sivaraam** [comment]
Closing this as #5494 has been merged.

Feel free to reopen if I missed something that's left to be done. 🙂
