### ISSUE TITLE
Fix failing instrumentation tests

### ISSUE THREAD

**Issue by sivaraam** [commons-app/apps-android-commons#5498]
Our instrumentation have been failing for a while now [[ref](https://github.com/commons-app/apps-android-commons/actions/runs/7695703574/job/20969160677)]. The following is the trace of the first failure:

```
 fr.free.nrw.commons.UploadCancelledTest > uploadCancelledAfterLocationPickedTest[test(AVD) - 7.0] FAILED 
	androidx.test.espresso.NoMatchingViewException: No views in hierarchy found matching: (view.getId() is <2131296401/fr.free.nrw.commons.beta:id/caption_item_edit_text> and Child at position 0 in parent Child at position 0 in parent view.getId() is <2131296402> and (view has effective visibility <VISIBLE> and view.getGlobalVisibleRect() to return non-empty rectangle))
```

Another failing test case

```
fr.free.nrw.commons.WelcomeActivityTest > testBetaSkipButton[test(AVD) - 7.0] FAILED 
	java.lang.AssertionError: Assertion failed
	at fr.free.nrw.commons.WelcomeActivityTest.testBetaSkipButton(WelcomeActivityTest.kt:64)
Tests on test(AVD) - 7.0 failed: There was 2 failure(s).
```

We need to narrow down and identify the actual cause of these failures.

See also related issues: #4958 / #5245

**Comment by sivaraam** [comment]
> Well, I think in this PR #5408 these failing tests are being fixed by someone. 

I'm kind of unsure that issue is related to this one. It seems like that's focusing around fixing the failing unit tests (that are presently ignored). This issue is about fixing the instrumentation tests. So, both are different.

> Although, after fixing the instrumentation test, there will be more failing tests in `Unified Coverage`. 

Could you elaborate about this?

> Read this [post](https://stackoverflow.com/questions/77894864/build-failing-with-an-exception-in-kaptbetadebugkotlin) about the error details.

It's interesting you wanted to seek help regarding that issue in SO. Anyways, you might need to include more context as requested there for you to be able to receive any helpful response. For instance, you might need to clarify which project you're trying to build, the exact reason of faikure etc. 🙂

**Comment by rohit9625** [comment]
Okay, I'll provide more details about the build in SO.

**Comment by RitikaPahwa4444** [comment]
Is this same as #5355? I shared my observations there. `testBetaSkipButton` is running on my device, so it might be device-dependent or related to #3463. There's a PR for #5461, I'll try running `uploadCancelledAfterLocationPickedTest` again.

**Comment by sivaraam** [comment]
> Is this same as #5355?

Indeed. This does seem like a duplicate of that one. Thanks for catching!

> I shared my observations there. `testBetaSkipButton` is running on my device, so it might be device-dependent or related to #3463. There's a PR for #5461, I'll try running `uploadCancelledAfterLocationPickedTest` again.

Great points. Thanks for helping sort out the instrumentation tests that have long been unattended! 🙂

**Comment by sivaraam** [comment]
Duplicate of #5355
