### ISSUE TITLE
[Bug]: Switching languages doesn't seem to work properly

### ISSUE THREAD

**Issue by chenhuicui** [commons-app/apps-android-commons#5501]
### Summary

Switching languages doesn't seem to work properly. After clicking on the language setting item on the settings page, change the language to Simplified Chinese and return to the main page with the text still in English.

### Steps to reproduce

1. install the app from f-droid, version 4.2.1
2. open the app without login
3. go to the setting page
4. change the language from English to Chinese [zh-hans]
5. back to main page

### Expected behaviour

app UI language should be Chinese

### Actual behaviour

In English

### Device name

huawei nova 5 pro

### Android version

android 10

### Commons app version

4.2.1

### Would you like to work on the issue?

None

**Comment by nicolas-raoul** [comment]
You are right, I have noticed that too.
Do you know any app where such a setting works immediately? Ideally open source so that we can see how they do, but otherwise is good to, to assure feasibility.
Thanks!

**Comment by rohit9625** [comment]
This behavior is the same for all languages. The UI is not being populated with the new set **Language**.
Well, how long have you been facing this problem @chenhuicui?
I would like to work on it, @nicolas-raoul : )

**Comment by chenhuicui** [comment]
I'm sorry, I am a tester and not a professional Android developer, so I am unsure how to proceed. I discovered the issue during the automation testing process of the application. Thank you for your reply, and I wish you all the best. @nicolas-raoul @rohit9625

**Comment by rohit9625** [comment]
I found out that, when we change the language of the App, then some of the parts are not translated to the selected language but still some parts get easily translated. This behavior seems to be for some languages only. And for the Chinese, most of the App's language is not translated.

You can see this screenshot. Here word `Explorer` is not translated but the other words translated well for the language `Franais[fr]`.

![WhatsApp Image 2024-01-31 at 14 37 14_b513d69b](https://github.com/commons-app/apps-android-commons/assets/101377978/febedca1-d03e-40bc-9aa3-a51776cd72aa)

**I tried with several languages and the behavior is the same as above.**

**Comment by nicolas-raoul** [comment]
@geektan123 Sorry Rohit asked first, but there are many other issues for you to choose from. 🙂

**Comment by rohit9625** [comment]
Thank you so much for this reference👍

**Comment by rohit9625** [comment]
Hello!!
Mr. @nicolas-raoul please have a look at the linked PR and tell me if any other changes are required :)
