### ISSUE TITLE
Show number of satellites and Circular error probable in Nearby

### ISSUE THREAD

**Issue by tobias47n9e** [commons-app/apps-android-commons#551]
I think it is important to show the user how accurate the current position is while looking at the Nearby view. There are two important measures:

* Number of visible satellites (Stepping away from a wall can sometimes get you way more satellites). So a low number has a lot of meaning for experienced users.
* Circular error probable (https://en.wikipedia.org/wiki/Circular_error_probable). Most hiking GPS give 50% accuracy. I would prefer to give the 95 % accuracy value. This is usually displayed as +- 100m, which means that your true position is within a 100m radius with a probability of 95%

**Comment by tobias47n9e** [comment]
This would be one place where this information could be shown, but there might not be enough space on smaller phones.

![screenshot from 2017-05-15 20-13-18](https://cloud.githubusercontent.com/assets/6953323/26072942/92bcf45a-39ad-11e7-9a05-ff1e34c3ee9e.png)

The first numbers shows the connected satellites (which could be visible, connected or both) and the lower number shows the accuracy of the determined position. Maybe the numbers could be greyed out if there is no connection to at least 4 satellites to show that the phone is still looking for the position.

**Comment by nicolas-raoul** [comment]
Many other GPS map apps express precision with a circle, not sure how
usable it would be in our case.

Space does not seem to be such a problem yet, especially if it is made to
overflow first.

**Comment by tobias47n9e** [comment]
On the map we are now displaying the accuracy circle. 2 x the accuracy of the location provider should guarantee that the user is within this circle with a probability of 95 %.

The number of satellites and fixed satellites can also be retrieved rather easy:

https://stackoverflow.com/questions/6580603/getting-the-number-of-satellites-from-location-object

Thinking of just adding that as a floating element to the map.

**Comment by soldierinwhite** [comment]
Thinking of implementing a floating satellite number on the map, but is this something we really need or is it a little redundant if we already have the accuracy circle?

**Comment by nicolas-raoul** [comment]
In my opinion, the circle is enough and we don't need the number of satellites.
We target travelers and normal people in the street, they have low IT literacy, and might not even know that  satellites are involved in showing their position on the map.
@tobias47n9e are you OK with closing this? :-)

**Comment by mebr1416** [comment]
@tobias47n9e
@nicolas-raoul
Is this closed?

**Comment by nicolas-raoul** [comment]
The probable error circle is implemented indeed, thanks for noticing!
Number of satellites is not shown, but I have never felt the need for it, the circle is doing its job greatly in my opinion, so I will close this issue. Anyone please feel free to open a new issue if there are problems with this feature.
