### ISSUE TITLE
Problems with UploadMediaDetails flow and UX

### ISSUE THREAD

**Issue by ShashwatKedia** [commons-app/apps-android-commons#5511]
While uploading images I found some prominent bugs in the upload details flow:
1. While uploading an image, if the image has both a duplicate caption and some quality issue (is too dark or downloaded from the internet, etc.) then, 2 dialogs pop up. The one on top conveys the problems found in the image and the other (behind it) tells that the filename is duplicate. Clicking 'Cancel' in the problems dialog removes the image from the upload queue, but the dialog of duplicate name stays (which is now redundant and should not be there). Also the next image is not highlighted (in the thumbnail at top) when the current image is removed:
https://drive.google.com/file/d/1gJeGpHdmCUxj17sjVBD76imN7prFYP5F/view?usp=share_link

2. While uploading multiple images, if I cancel the upload of any image (even if I cancel the last one), then the app makes me go through the location comparison again (I am referring to that dialog which asks if the current photo and the previously uploaded photo with location, were taken at the same place), even though I went through it the first time:
https://drive.google.com/file/d/1gZwY4Wvm0GtBJ49SqelTADVJRN_mgj3N/view?usp=share_link

3. While uploading an image, if my caption of the image is duplicate, and I check the 'Don't ask again' in the duplicate dialog, then the no location found dialog is shown twice:
https://drive.google.com/file/d/1gRfqVYiTRcFM4ZKSIAtdwe-GGifFfhmi/view?usp=share_link

4. In the media details, when I zoom the photo, the up/down arrow (used to expand/collapse the details) flickers and sets to the wrong orientation of down instead of up:
https://drive.google.com/file/d/1g8cLYNUgYhDvaYM9LIZRVIGLoKeqyG_q/view?usp=share_link

This issue is related to #4704, which requests to change the flow of UploadMediaDetails and this points to the bugs already present in the flow.
Also while testing the uploadMediaDetailsFragment, sometimes the app crashed, which has no specific steps to reproduce, but I have got the recording of one here:
https://drive.google.com/file/d/1gMg1uiioJ7DIW72paA5EKXLO_94Cxt3g/view?usp=sharing

**Comment by ShashwatKedia** [comment]
@nicolas-raoul @sivaraam @RitikaPahwa4444, could either of you confirm that each of these behaviours is a bug and I have not interpreted a correct behaviour as a bug since I have started working on solving them :)

**Comment by ShashwatKedia** [comment]
@nicolas-raoul, could you please take a look at this issue and the above PR? :-)

**Comment by nicolas-raoul** [comment]
Sorry for the delay! All seem to be bugs indeed. 🙂

**Comment by ShashwatKedia** [comment]
> Sorry for the delay! All seem to be bugs indeed. 🙂

@nicolas-raoul Thanks for confirming. I have resolved these issues, could please you take a look at the above PR :)
