### ISSUE TITLE
[Bug]: Uploading feedback via app does not work

### ISSUE THREAD

**Issue by OpenGreenStreet** [commons-app/apps-android-commons#5514]
### Summary

It is currently not possible to upload feedback via the app, but uploading images works (see also: https://commons.wikimedia.org/wiki/Commons:Mobile_app/Feedback#Feedback_from_Molgreen_for_version_4.2.1~14b6c455b_2)

### Steps to reproduce

yes

### Expected behaviour

upload works

### Actual behaviour

upload fails with error

### Device name

Pixel 7 Pro

### Android version

Android 14

### Commons app version

4.2.1~14b6c455b

### Screen-shots

https://commons.wikimedia.org/wiki/File:20240203_xl_0911-CommonsApp_Screenshot.png

### Would you like to work on the issue?

None

**Comment by nicolas-raoul** [comment]
Strangely it is working for me with the latest branch: https://commons.wikimedia.org/wiki/Commons:Mobile_app/Feedback#Feedback_from_Syced_for_version_4.2.1-debug-psh-psh/data-client-simplification~98b42a52e

This might be due to a language-dependent bug (I am using English locale) or some other environment difference.

**Comment by OpenGreenStreet** [comment]
I have just rebooted the smartphone again and searched the Play Store for a more up-to-date version (none available). The error occurs "reliably" for me.

**Comment by nicolas-raoul** [comment]
If you momentarily switch the OS and app language to English, does it work?
The information will tell us whether this is language-related. Thanks a lot! 🙂

**Comment by OpenGreenStreet** [comment]
I have set inface language and description language to English. The error still occurs for me.
see screenshots that I uploaded with the Commons app:
* https://commons.wikimedia.org/wiki/File:20240205_xl_0611-error_while_sending_feedback_2.png
* https://commons.wikimedia.org/wiki/File:20240205_xl_0611-error_while_sending_feedback.png

Thank you for your effort

**Comment by nicolas-raoul** [comment]
Thanks!
Would you be able to record a **logcat**, by any chance? Or anyone who can reproduce.

**Comment by OpenGreenStreet** [comment]
If you tell me what a "logcat" is, how I can create a "logcat" and how I can then send it to you.

I have just sent (exactly at 7:00) a CommonsAppLogs.zip by e-mail. Is that what you need?

**Comment by OpenGreenStreet** [comment]
On 02/05/2024 at 7:00 AM, I have sent CommonsAppLogs.zip by e-mail (to "commons-app-X...X-P...P @ G...G.com")

**Comment by OpenGreenStreet** [comment]
Yes, please. I don't want to see the data on the Internet

**Comment by OpenGreenStreet** [comment]
By the way: I have uploaded several hundred pictures. I can currently upload pictures. Only the statistics function is not working.

**Comment by rohit9625** [comment]
Okay, I got it :)
We'll definitely look into it.

**Comment by OpenGreenStreet** [comment]
great

**Comment by OpenGreenStreet** [comment]
* https://github.com/commons-app/apps-android-commons/issues/5515

**Comment by OpenGreenStreet** [comment]
Very nice, it's working again. Thank you very much

**Comment by nicolas-raoul** [comment]
Thanks for the feedback! :-)
