### ISSUE TITLE
[Bug]: Statistic function does not work

### ISSUE THREAD

**Issue by OpenGreenStreet** [commons-app/apps-android-commons#5515]
### Summary

Statistic function does not work

### Steps to reproduce

have completely closed the app several times

### Expected behaviour

Display of statistical values

### Actual behaviour

No statistical values are displayed

### Device name

Pixel 7 Pro

### Android version

Android 14

### Commons app version

4.2.1~14b6c455b

### Would you like to work on the issue?

None

**Comment by OpenGreenStreet** [comment]
screen shots:
* https://commons.wikimedia.org/wiki/File:20240128_xl_1956-Commons-Error-Screenshot.png
* https://commons.wikimedia.org/wiki/File:20240128_xl_1956-Commons-Error-Screenshot_2.png

**Comment by nicolas-raoul** [comment]
The first was fixed recently: https://github.com/commons-app/apps-android-commons/issues/5462 :-)

The second has been reported previously here: https://github.com/commons-app/apps-android-commons/issues/5287
