### ISSUE TITLE
Show total number of uploads

### ISSUE THREAD

**Issue by jwsl85** [commons-app/apps-android-commons#552]
Currently, when you log into the uploader, it will list around 500 of your total uploads under the My uploads heading, even if you have a lot more than that.

It would be really good if this could be changed to say something like 'Showing 500 of 2540 total uploads' so that you can easily see how many files you have uploaded in total. This is not a feature that is easy to find on Commons itself, so it would be a nice feature which might encourage more people to use the app.

**Comment by tobias47n9e** [comment]
Related ticket on Phab: https://phabricator.wikimedia.org/T136534

**Comment by sandarumk** [comment]
Since there is no way (as per the phabricator issue), we can query the count of my total uploads, hence I suggest we rename the Activity as "My Recent Uploads" instead of "My Uploads". The number can range from (0-500) and can be added as a setting.

**Comment by misaochan** [comment]
I posted in the Phab ticket, hopefully it gets fixed in the future.

**Comment by ShashwatKedia** [comment]
@nicolas-raoul I think this issue can be closed, as the app now does show the total number of uploads of the user, both on the Main screen and on the Achievements section

**Comment by nicolas-raoul** [comment]
Indeed, thanks @ShashwatKedia for spotting this!
