### ISSUE TITLE
[Bug]: Methods Usage Incompatible with Android API Level 21 (Target SDK Version)

### ISSUE THREAD

**Issue by shashankiitbhu** [commons-app/apps-android-commons#5521]
This is an issue because using methods unavailable in the target Android API level (In our project -  **API level 21**) can lead to compatibility issues and potential runtime errors on devices running versions below the specified API level. It violates the principle of maintaining backward compatibility, which ensures that an Android application runs smoothly on a wide range of devices.

Currently, I have found 2 Issues like this in this Project :

1. In the ```UploadMediaDetailAdapter``` the ``` removeDescription()``` Method uses ```stream()``` , ```filter``` , ```count``` methods which requires **API Level 24** 
<img width="868" alt="Screenshot 2024-02-06 at 11 18 09 AM" src="https://github.com/commons-app/apps-android-commons/assets/126143257/22dbb3ff-06f4-4699-b8cb-32c8680ab780">

2. In the ```CommonsDateUtil``` the ```getIso8601DateFormatTimestamp()``` uses Pattern which also requires **API Level 24**
<img width="969" alt="Screenshot 2024-02-06 at 11 17 53 AM" src="https://github.com/commons-app/apps-android-commons/assets/126143257/7e530a9a-9c49-490c-a52e-b2ad5e93b510">

In Both of these cases, alternative solutions can be used that will give the same results and will also be compatible with our Target SDK Version (21).

I am willing to work on this solution and I will fix these in my next PR

**Comment by nicolas-raoul** [comment]
Great catches, thanks! :-)
