### ISSUE TITLE
Change line break behaviour of description template

### ISSUE THREAD

**Issue by Speravir** [commons-app/apps-android-commons#5523]
### Description

_Caveat:_ I’m not a Commons app user and so do not know it at all. Hence I may make some wrong assumptions.

I frequently work in the source of file descriptions and noticed a strange behaviour regarding a line break in a place I wouldn’t set it. Instead, I miss a line break, where I’ve expected one. These (missing) line breaks do not any harm for the output, so this is not urgent, but should anyway be easy to fix. Look at source of example file [File:20240128 xl 1147-Treffpunkt Freizeit.jpg](https://commons.wikimedia.org/wiki/File:20240128_xl_1147-Treffpunkt_Freizeit.jpg). It looks like this (stripped last lines and most values from template parameters):

```mediawiki
== {{int:filedesc}} ==
{{Information
|description={{de|1=$CONTENT}}

|source={{own}}
|author=$AUTHOR
|date=$DATE
}}
{{Location|$COORDINATES}}
== {{int:license-header}} ==
{{self|cc-by-sa-4.0}}
```
Between the parameters `|description` and `|source` there is a spurious line I’d love to be removed. But then after the `{{Location}}` template and before the header for the license section I miss a line break.

I noticed this a while ago, but recently asked @OpenGreenStreet for the reason and he pointed my to the App as cause of this.

Also ping @nicolas-raoul who, as well, recommended opening an issue for this. Here is an example file uploaded by him with the same source appearance: [File:2004 Commons Android app - Metadata selection.png](https://commons.wikimedia.org/wiki/File:2004_Commons_Android_app_-_Metadata_selection.png). This has, of course, no Location template, and therefore the license header follows straight after the information template.

**Comment by nicolas-raoul** [comment]
Just to be clear, you'd like the wikicode to be like below, right?
```
== {{int:filedesc}} ==
{{Information
|description={{de|1=$CONTENT}}
|source={{own}}
|author=$AUTHOR
|date=$DATE
}}
{{Location|$COORDINATES}}

== {{int:license-header}} ==
{{self|cc-by-sa-4.0}}
```

**Comment by ivanacha** [comment]
Hey! I'm an open-source newbie, and I'd love to take up this issue.

**Comment by nicolas-raoul** [comment]
@ivanacha It is yours, thanks! 🙂

**Comment by ivanacha** [comment]
👍Working on it right now

> @ivanacha It is yours, thanks! 🙂

**Comment by nicolas-raoul** [comment]
@Speravir Thanks to Ivan's contribution the issue seems fixed now:

```
== {{int:filedesc}} ==
{{Information
|description=
|source={{own}}
|author=[[User:Syced|Syced]]
|date={{According to Exif data|2024-02-24}}
}}
{{Location|35.44607222222222|139.63065555555556}}

== {{int:license-header}} ==
{{self|cc-zero}}

{{Uploaded from Mobile|platform=Android|version=4.2.1-debug-main~47aac53ac}}

[[Category:Yokohama]]
[[Category:Shopping streets in Japan]]
```

https://commons.wikimedia.org/wiki/File:Harmonica_Yokocho_4.jpg

**Comment by OpenGreenStreet** [comment]
I would assume the same. I currently still have version 4.2.1~14b6c455b and there are currently no updates for me in the Play Store.
@Speravir If no update is required, here is a file that I uploaded yesterday: https://commons.wikimedia.org/wiki/File:20240225_xl_0919-Zuwegung_zu_Bahnhof_Waren_(M%C3%BCritz).jpg
