### ISSUE TITLE
[Bug]: Unable to upload DNG / RAW images

### ISSUE THREAD

**Issue by sivaraam** [commons-app/apps-android-commons#5537]
### Summary

The app allows users to choose DNG /RAW images but uploading fails after the users enters all the information such as description / caption etc.

Initially reported by Molgreen [here](https://commons.wikimedia.org/wiki/Commons:Mobile_app/Feedback#c-Molgreen-20230819191200-Feedback_from_Molgreen_for_version_4.1.0~1649d1e2c_6)

### Steps to reproduce

1. Open the app
2. Choose a DNG / RAW image in the upload screen
3. Enter the details in the various steps and initiate the upload

### Expected behaviour

The upload completes (or) if DNG / RAW is an unsupported format the user should have been intimated about the same.

### Actual behaviour

The upload fails immediately after initiating it.

### Device name

Pixel 7 Pro

### Android version

13

### Commons app version

4.1.0 (also occurs in 4.2.1)

### Would you like to work on the issue?

None

**Comment by OpenGreenStreet** [comment]
@sivaraam Thank you for creating this issue

**Comment by shashankiitbhu** [comment]
@sivaraam I tried it on 4.2.1-debug-main and got the following logs which suggest that .dmg or RAW is an unsupported file type and the Ideal Response that we should Provide to the user is that this file type isn't supported after they upload. Alternatively, We can restrict users to select only supported formats (like .jpg and .png)
```
java.io.IOException: {"errors":[{"code":"illegal-filename","text":"The filename is not allowed.","module":"upload"}],"docref":"See https://commons.wikimedia.beta.wmflabs.org/w/api.php for API usage. Subscribe to the mediawiki-api-announce mailing list at &lt;https://lists.wikimedia.org/postorius/lists/mediawiki-api-announce.lists.wikimedia.org/&gt; for notice of API deprecations and breaking changes.","servedby":"deployment-mediawiki11"}
                                                                                                    	at fr.free.nrw.commons.OkHttpConnectionFactory$UnsuccessfulResponseInterceptor.intercept(OkHttpConnectionFactory.java:99)
                                                                                                    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
                                                                                                    	at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.kt:221)
                                                                                                    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
                                                                                                    	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
                                                                                                    	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154) ......
 ```

**Comment by OpenGreenStreet** [comment]
Thank You @sivaraam
Personally, I would prefer the second option: limiting users to only being able to select supported formats (such as .jpg and .png).

That way the user doesn't even get the idea of trying something impossible

**Comment by shashankiitbhu** [comment]
@OpenGreenStreet exactly, and this option will be more intuitive to user

**Comment by OpenGreenStreet** [comment]
There is something else: When I select images via the Commons app with the current Google Android 14, JPG and DNG/RAW files are displayed. If DNG/RAW files were no longer displayed in future, this would improve clarity.

**Comment by shashankiitbhu** [comment]
@OpenGreenStreet Yes that is achievable in the sense that Non-Supported Images will not be selectable (it will be displayed but the user won't be able to select it and it will look different too), attaching examples below :

**Example of Gallery Picker (Unrestricted) :**
![WhatsApp Image 2024-02-11 at 6 26 04 PM (1)](https://github.com/commons-app/apps-android-commons/assets/126143257/9d34f693-b9b9-46e4-a95c-017ac9cd2349)

**Example of Gallery Picker (When Certain MIME Types are Restricted like jpeg - for example )**
![WhatsApp Image 2024-02-11 at 6 26 04 PM (1)](https://github.com/commons-app/apps-android-commons/assets/126143257/bf3ed502-ab23-4d76-af65-207ab15fbddd)

**Comment by OpenGreenStreet** [comment]
I would find it even better if the invalid file formats were not displayed at all. (But if that's not possible, then I think it's already a big step forward). Thank you!

**Comment by sivaraam** [comment]
> limiting users to only being able to select supported formats (such as .jpg and .png).
> 
> That way the user doesn't even get the idea of trying something impossible

This sounds like a good approach. We could certainly try this. The list of all image formats supported  by Wikimedia Commons is available [here](https://commons.wikimedia.org/wiki/Commons:File_types). This could be a good source to identify the formats which we should support.

**Comment by shashankiitbhu** [comment]
@sivaraam That's Great, I already did some setting up for MIME types to showcase the above Example, I'll just need to add all the MIME types mentioned and it'll be done. Can I add a PR here for this?

**Comment by sivaraam** [comment]
Sure, @shashankiitbhu 

That would be helpful 🙂

**Comment by shashankiitbhu** [comment]
@sivaraam @nicolas-raoul  Please Review the above PR and close this issue if the changes are satisfactory, thanks :)

**Comment by OpenGreenStreet** [comment]
@nicolas-raoul @shashankiitbhu @shashankiitbhu @prtksxna @whym Thanks to you all
