### ISSUE TITLE
Archive function for feedback page

### ISSUE THREAD

**Issue by OpenGreenStreet** [commons-app/apps-android-commons#5542]
### What is the user problem or growth opportunity you want to see solved?

I would like to suggest activating the archive function on the page ( https://commons.wikimedia.org/wiki/Commons:Mobile_app/Feedback ).

### How do you know that this problem exists today? Why is this important?

All messages that have either been resolved or transferred to GitHub should be archived.

An example of this would be the message ( https://commons.wikimedia.org/wiki/Commons:Mobile_app/Feedback#c-Kaartic-20240211050800-Molgreen-20230819191200 ) for which a GitHub issue has been created.

### Who will benefit from it?

This will make the page much clearer.

### Anything else you would like to add?

@shashankiitbh

**Comment by OpenGreenStreet** [comment]
@nicolas-raoul
I would like only things that are marked as completed to be archived.

Would it be right to add the following code? (https://commons.wikimedia.org/wiki/Commons:Mobile_app/Feedback)

  {{User:MiszaBot/config
  | archive       = Commons:Mobile app/Feedback/Archives/%(year)d/%
  }}
  {{archive box|auto=yes}}

If so, should I do this or would you do it?

**Comment by OpenGreenStreet** [comment]
I mean: {{section resolved|1=~~~~}}

**Comment by nicolas-raoul** [comment]
Sorry for the delay!
Yes, it would be great if you could do it, thanks a lot for contributing :-)

**Comment by OpenGreenStreet** [comment]
@nicolas-raoul : Okay, I'll give it a try. Since I don't want to damage anything, I've made a request first : https://commons.wikimedia.org/wiki/Commons:Forum#Quelltextfrage:_Archivfunktion_nur_f%C3%BCr_%E2%80%9Eerledigt%E2%80%9C

**Comment by OpenGreenStreet** [comment]
@nicolas-raoul Good morning, could you please take a look here: https://commons.wikimedia.org/wiki/User_talk:Syced#Hinweis_auf_m%C3%B6gliche_L%C3%B6schung

**Comment by nicolas-raoul** [comment]
Sorry I am super busy with various projects and GSoC, but me or another core developer will come back to this as soon as possible. :-)

**Comment by sivaraam** [comment]
As per the on-wiki discussions on this topic [ [ref](https://commons.wikimedia.org/wiki/Commons_talk:Mobile_app/Feedback#c-Speravir-20240524225000-Archive_resolved_sections) ], we should explore on changing the app logic to post new sections at the bottom rather than at the top. The API we use seems to support this very well. This is necessary for auto-archiving to work properly.

To address the case where we could quickly notice the new sections added on the wiki page, we could explore if there's a way to invert the ToC. That should give us a balanced solution, I believe.

**Comment by sivaraam** [comment]
Thnak you for this tip, @Speravir !

> I assume here that in the mobile app a skin change is possible.
> 
> This CCS has to inserted in/by the app, because you cannot expect users to apply custom user styles.

Sadly, the app can't help much here. It only takes care of posting the feedback. It doesn't yet support viewing/replying to the feedback page in-app. 

Is it not possible to have this as a page level CSS styling? Is that possible? If so, would that be disruptive?

**Comment by nicolas-raoul** [comment]
@Speravir Sorry for being late to the party, I unfortunately still do not have much time for this due to GSoC and other projects. Please do not hesitate to modify https://commons.wikimedia.org/wiki/Commons:Mobile_app/Feedback and add Commons:Mobile app/Feedback/styles.css etc as needed. :-)

**Comment by sivaraam** [comment]
Indeed. I've raised #5753 to change the app's logic such that feedback is appended as a new section. A section added using that logic could be found [here](https://commons.wikimedia.org/wiki/Commons:Mobile_app/Feedback#Feedback_from_Kaartic_for_version_5.0.1-debug-feedback-append~8fdfb8e6d).

Let's see if we could get archiving to start working soon 🙂

**Comment by sivaraam** [comment]
Just FYI. I just pushed out the v5.0.2 for beta testing. It contains the change needed for the feedback to appear at the end of the page.

**Comment by sivaraam** [comment]
I suppose we're done with the things needed for this issue here. So, closing this. Feel free to reopen if I missed something.
