### ISSUE TITLE
[Bug]: App Crashes after clicking on Explore in bottom Navigation

### ISSUE THREAD

**Issue by shashankiitbhu** [commons-app/apps-android-commons#5547]
### Summary

 App Crashes after clicking on "Explore" in the bottom Navigation Bar

### Steps to reproduce

1. Open App
2. Click on the "Explore" Navigation Item

### Expected behaviour

Explore Tab Opens

### Actual behaviour

App Crashes

### Device name

Xaomi 11 Lite NE

### Android version

13

### Commons app version

4.2.1-debug-main

### Screen-shots

https://github.com/commons-app/apps-android-commons/assets/126143257/d78f2eae-51f0-4022-ad99-70d58ce48c09

### Would you like to work on the issue?

Yes

**Comment by shashankiitbhu** [comment]
Seems like the Issue arose due to one of the recent commits, performing ```git bisect``` to find out more

**Comment by kanahia1** [comment]
Hey @shashankiitbhu, I think it is caused by https://github.com/commons-app/apps-android-commons/pull/5546/files#diff-c3e9d0acd2bc44a047fc23500518a5914f2b129d9e79de699cbe42802734cd9b

Hopefully code seems good to me, idk what is causing an issue.

Changing the code in `PageableMediaFragment.kt` helped me fix crashing but the screen keeps on loading. Can you please look into it.

```
override fun onCreateView(
        inflater: LayoutInflater,
        container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View {
        super.onCreateView(inflater, container, savedInstanceState) // Add this line
        _binding = FragmentSearchPaginatedBinding.inflate(inflater, container, false)
        return binding.root
    }
```

https://github.com/commons-app/apps-android-commons/assets/114223204/e04fbbcf-9aa3-4c73-beec-671650c22657

**Comment by shashankiitbhu** [comment]
Hi @kanahia1 thanks for taking the time on this , I already found out that it was caused by #5546 yesterday (as I mentioned this in the duplicate closed issue) ,I am currently fixing this, what I have understand till now is that this issue was caused particularly due to binding not loading (in BasePagerFragment ) , will give an update soon on this one, thanks 👍

**Comment by shashankiitbhu** [comment]
@kanahia1 

> Changing the code in PageableMediaFragment.kt helped me fix crashing but the screen keeps on loading. Can you please look into it.

That is not fixing the issue , it's just calling the onCreateView() of superclass (```BasePagingFragment``` in this case) which is not really needed here , it is merely escaping the issue (the core problem with binding still remains ).

This same result can be achieved by shifting the code below from ```onViewCreated()``` to ```onCreateView()``` like below:

```
binding.paginatedSearchResultsList.apply {
            layoutManager = GridLayoutManager(context, if (isPortrait) 1 else 2)
            adapter = mergeAdapter
        }
        injectedPresenter.listFooterData.observe(
            viewLifecycleOwner,
            Observer(loadingAdapter::submitList)
        )
```
These changes are not fixing the core problem which is with binding.

I am working on fixing that and will update soon

**Comment by shashankiitbhu** [comment]
> Changing the code in `PageableMediaFragment.kt` helped me fix crashing but the screen keeps on loading. Can you please look into it.

@kanahia1 That is not fixing the issue, it's just calling the ```onCreateView()``` of the superclass (BasePagingFragment in this case) which is not really needed here, it is merely escaping the issue (the core problem with binding still remains ). That Same result can be achieved in other ways too but that won't fix the issue at all, which is with the binding. Our goal here is not find stop the crashing but to fix the core problem with the binding so that compose binding migration is successful.

I am pretty close to fixing the issue and have come to a possible solution, I will be adding a PR soon regarding this, thanks 👍🏼

**Comment by kanahia1** [comment]
Ah!, I got it

Best of luck @shashankiitbhu

**Comment by shashankiitbhu** [comment]
@nicolas-raoul Please Review the above PR and merge so that this crucial Crash can be resolved soon, thanks
