### ISSUE TITLE
Remove MAPBOX_ACCESS_TOKEN

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#5554]
The app's source code still contains MAPBOX_ACCESS_TOKEN:

https://github.com/commons-app/apps-android-commons/blob/main/gradle.properties#L42

I believe it can be removed, because we switched to osmdroid.

Task:
- Remove it
- Test whether the app still works fine without it (in particular the parts that show maps)

**Comment by kanahia1** [comment]
Hey @nicolas-raoul, I have removed ACCESS TOKEN https://github.com/commons-app/apps-android-commons/pull/5555 and will remove MapBox Imports and Dependencies as soon as https://github.com/commons-app/apps-android-commons/pull/5536 gets merged. 🙂

**Comment by shashankiitbhu** [comment]
@kanahia1 This issue was meant for newcomers, also you should wait to get an issue assigned first, especially with tags-good first issue

**Comment by kanahia1** [comment]
@shashankiitbhu 😟

**Comment by nicolas-raoul** [comment]
Indeed please request to be assigned, next time. Thanks both for improving the app! :-)
