### ISSUE TITLE
[Bug]: Set Wallpaper Not Working Correctly

### ISSUE THREAD

**Issue by shashankiitbhu** [commons-app/apps-android-commons#5556]
### Summary

The Set Wallpaper feature in the contributions page does not inform the user that it has failed to set wallpaper. Also, I am unable to abort this dialog.

The issue is not that set wallpaper is failing to set the Image as wallpaper but that it is **NOT Informing** the user that it has failed and dialog is still appearing on the screen which the user cannot close.

Also, we should make the "set as wallpaper"  a background task that does not block the UI Thread as sometimes this can take long ( it is pretty similar to download ) 

### Steps to reproduce

1. Open the app
2. Open any Contribution in Explore or your contribution
3. Click "Set as Wallpaper"

### Expected behaviour

Sets the wallpaper or if it fails then the dialog ends and the user is informed

### Actual behaviour

set wallpaper keeps on going

### Device name

Xiaomi 11 Lite NE

### Android version

Android 13

### Commons app version

4.2.1-debug-main

### Device logs

``` 
HTTP FAILED: java.io.IOException: Canceled
2024-02-16 20:52:02.709 16877-17104 OkHttp                  fr.free.nrw.commons.beta             V  --> GET https://upload.wikimedia.beta.wmflabs.org/wikipedia/commons/thumb/6/6f/Sea_View.jpg/640px-Sea_View.jpg
2024-02-16 20:52:02.709 16877-17104 OkHttp                  fr.free.nrw.commons.beta             V  Cache-Control: no-store
2024-02-16 20:52:02.709 16877-17104 OkHttp                  fr.free.nrw.commons.beta             V  --> END GET
```

### Screen-shots

https://github.com/commons-app/apps-android-commons/assets/126143257/b7ce8dfb-9482-48b7-ae7c-004cac5ca137

### Would you like to work on the issue?

Yes

**Comment by ShashwatKedia** [comment]
Hey @shashankiitbhu, it seems the issue is with the beta server, as I was able to set wallpaper successfully using  prodDebug [Screencast](https://github.com/commons-app/apps-android-commons/assets/142137555/7fc7ba26-4b93-4449-95b8-59fc4aad0da0)

**Comment by shashankiitbhu** [comment]
@ShashwatKedia no that's not the issue, if you read the summary again I have mentioned that failing is not the problem, but dialog still appearing after failing is l

**Comment by rohit9625** [comment]
Strange in my case the wallpaper is set successfully in `milliseconds`. However, this is about handling the case when the process is failed, right?

**Comment by shashankiitbhu** [comment]
> However, this is about handling the case when the process is failed, right?

Yes

**Comment by rohit9625** [comment]
Well, I just faced the same with `betaDebug` flavor😅

**Comment by neeldoshii** [comment]
If you don't mind can I work on this as I was digging it up recently and found the exact solution which is causing the bug and fix? Can I work on it if you wish or can we collaborate?

**Comment by neeldoshii** [comment]
This is how I solved it.  @shashankiitbhu @nicolas-raoul 

## Root cause of issue. 

Currently code handles the issue when the url is not present it handles the failures. But what if we have a url but receive error from the API side this could include (Wrong URL, server high time in response, xyz issues from server side), this is not handled in our API side.

## Currently 

I checked the if the url threw the error dismiss the progressdialog and show toast, which solves the issue somewhat but not optimal.

## Working Video
    
https://github.com/commons-app/apps-android-commons/assets/60827173/235e8c9e-b684-4498-9a8b-b241c088a48f

## Additional Improvements 

Add Failure mechanism directly at the API level (calling api).(if org approves I can work on it)

For example I have worked similarly on one of my project like this. 
```
    fun parseFailedResponse(t: Throwable): String {
        return when (t) {
            is SocketTimeoutException -> {
                "Connection Lost, please try again - ${t::class.java.simpleName}"
            }
            is MalformedJsonException,
            is JsonSyntaxException -> {
                t.printStackTrace()
                "SERVER sent invalid response - ${t::class.java.simpleName}"
            }
            else -> {
                t.printStackTrace()
                "Could not connect to SERVER - ${t::class.java.simpleName}"
            }
        }
    }
    
   ```

**Comment by shashankiitbhu** [comment]
> If you don't mind can I work on this as I was digging it up recently and found the exact solution which is causing the bug and fix? Can I work on it if you wish or can we collaborate? 

I have already worked on it and presented a solution, I was waiting for mentors approval to make the PR and take inputs for changes

**Comment by neeldoshii** [comment]
> > If you don't mind can I work on this as I was digging it up recently and found the exact solution which is causing the bug and fix? Can I work on it if you wish or can we collaborate?
> 
> I have already worked on it and presented a solution, I was waiting for mentors approval to make the PR and take inputs for changes

Sure, no problem ;)

**Comment by nicolas-raoul** [comment]
@shashankiitbhu Sorry do you still need anything from us? If yes would you mind summarizing or posting a link here? Thanks :-)

**Comment by neeldoshii** [comment]
> @shashankiitbhu Sorry do you still need anything from us? If yes would you mind summarizing or posting a link here? Thanks :-)

If this issue is stale then I would like to take it as I have already fixed the issue locally. Since @shashankiitbhu is currently assigned to it, I have refrained from submitting a pull request. However, I can offer a patch fix for the changes. You can easily apply the patch by copying from clipboard from Android Studio

**Comment by shashankiitbhu** [comment]
> @shashankiitbhu Sorry do you still need anything from us? If yes would you mind summarizing or posting a link here? Thanks :-)

Actually, as mentioned above I was waiting for your confirmation on whether I should Implement the enhancement or not , whether it's worth doing or not according to you.

**Comment by shashankiitbhu** [comment]
> The issue is not that set wallpaper is failing to set the Image as wallpaper but that it is NOT Informing the user that it has failed and dialog is still appearing on the screen which the user cannot close.\n\nAlso, we should make the \"set as wallpaper\" a background task that does not block the UI Thread as sometimes this can take long ( it is pretty similar to download )

@nicolas-raoul This is the enhancement I have suggested

**Comment by neeldoshii** [comment]
Based on this issue, it also made me remind that Progress Dialog is deprecated. I guess the better approach would be to remove the Progress dialog. Google  [Deprecated Progress Dialog](https://developer.android.com/reference/android/app/ProgressDialog)

According to Google
> This class was deprecated in API level 26.
> ProgressDialog is a modal dialog, which prevents the user from interacting with the app. Instead of using this class, you should use a progress indicator like [ProgressBar](https://developer.android.com/reference/android/widget/ProgressBar), which can be embedded in your app's UI. Alternatively, you can use a [notification](https://developer.android.com/guide/topics/ui/notifiers/notifications) to inform the user of the task's progress.

The better approach according to me would be to handle it like this.
![image](https://github.com/commons-app/apps-android-commons/assets/60827173/946e5c82-1c42-4a66-8667-09a8d0fd49f2)

> Additional Improvements
> Add Failure mechanism directly at the API level (calling api).(if org approves I can work on it)
> 
> For example I have worked similarly on one of my project like this.

Also CC : @psh as mentioned in https://github.com/commons-app/apps-android-commons/issues/5556#issuecomment-1978977703 can we add a failure mechanism to our api level

**Comment by nicolas-raoul** [comment]
@shashankiitbhu Sounds good! 🙂

**Comment by shashankiitbhu** [comment]
@nicolas-raoul Added the PR for this enhancement above, Please Review
