### ISSUE TITLE
[Bug]:  Contributions not loading Properly 

### ISSUE THREAD

**Issue by shashankiitbhu** [commons-app/apps-android-commons#5557]
### Summary

Contribution data (like contribution image) is not loading (unable to fetch it seems)

An additional Possible Improvement that should be made here is that we should Inform the user in a better way an error like this occurs due to whatever reason  it is failing to load (at least a toast message)

### Steps to reproduce

1. Open any contribution

### Expected behaviour

Contribution information (like Image should appear)

### Actual behaviour

Images are not fetching , it's not visible, leading to multiple issues like it is not downloading and user is unable to set it as wallpaper

### Device name

Xaomi 11 Lite NE

### Android version

Android 13

### Commons app version

4.2.1-debug-main

### Would you like to work on the issue?

Yes

**Comment by kanahia1** [comment]
I am also facing this issue on `beta` Server.

**Comment by shashankiitbhu** [comment]
I am looking into this issue

**Comment by shashankiitbhu** [comment]
seems like the issue is with wikimedia servers

```
{"error":{"code":"missingtitle","info":"The page you specified doesn't exist.","*":"See https://commons.wikimedia.beta.wmflabs.org/w/api.php for API usage. Subscribe to the mediawiki-api-announce mailing list at &lt;https://lists.wikimedia.org/postorius/lists/mediawiki-api-announce.lists.wikimedia.org/&gt; for notice of API deprecations and breaking changes."},"servedby":"deployment-mediawiki11"}
```

**Comment by rohit9625** [comment]
The issue has been here for a while. Maybe this is what should be happening in the betaDebug flavor. 
That's why we are advised to use **prodDebug** flavor for issues related to **Contributions, Uploads, etc.**

**Comment by shashankiitbhu** [comment]
Yes, Indeed

**Comment by shashankiitbhu** [comment]
Yes Indeed
