### ISSUE TITLE
Custom image selector: Do not reload everything after marking a picture as not for upload

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#5558]
How to reproduce the issue:

0. In the custom image selector, mark your first 100 pictures as not for upload, then disable "Show already actioned pictures".
1. (screencast below starts at this step) In the custom image selector, tap one picture.
2. Tap "Mark as not for upload"

Expected: Only the selected picture diapsears from the screen. The remaining pictures move up a bit, one additional picture gets shown at the bottom.
 
Actually: All pictures disappear from the screen, the activity gets reloaded fully which takes a lot of time (about 20 seconds in the screencast below).

https://github.com/commons-app/apps-android-commons/assets/99590/3c17a3ef-c13a-4852-8c73-21e63c65c921

**Comment by shashankiitbhu** [comment]
I would like to work on this @nicolas-raoul

**Comment by nicolas-raoul** [comment]
Thanks @shashankiitbhu! Do not hesitate to ask if anything is unclear.

**Comment by shashankiitbhu** [comment]
Hi @nicolas-raoul I have solved this issue but I am waiting for #5571 to get fixed (which I have solved locally and can make a separate PR to fix it as I have already asked in the discussion going on there)

https://github.com/commons-app/apps-android-commons/assets/126143257/029b5fe1-eb6d-4d0c-ab3e-332bdf4dedf4

**Comment by shashankiitbhu** [comment]
@nicolas-raoul Added the above PR to fix this issue, please review, thanks
