### ISSUE TITLE
Refactor `curlatLng` to `currentLatLng`

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#5559]

**Comment by aahlad2000** [comment]
Hi @nicolas-raoul, I'm a newbie to open source and I would like to work on this. Hope it is okay

**Comment by nicolas-raoul** [comment]
@aahlad2000 Of course, that's a perfect task to begin. :-)

**Comment by krishnathakuralen** [comment]
hi @nicolas-raoul I am new to open source community, I am not sure how it works, can I still take this task, or do I move on to next task?

**Comment by aahlad2000** [comment]
HI @krishnathakuralen, I have already picked this up. Can you please pick another task up, thanks.

**Comment by krishnathakuralen** [comment]
ok sure :)

**Comment by aahlad2000** [comment]
@nicolas-raoul raise a new PR for this:
Refactor curlatLng to currentLatLng #5646

Please help to review and approve this PR.
