### ISSUE TITLE
Feedback subject should contain date and time

### ISSUE THREAD

**Issue by OpenGreenStreet** [commons-app/apps-android-commons#5564]
### What is the user problem or growth opportunity you want to see solved?

Feedback subject should contain date and time.

### How do you know that this problem exists today? Why is this important?

If a user submits multiple feedback with the same version of the Commons app, these cannot be distinguished in the overview.

### Who will benefit from it?

all users

### Anything else you would like to add?

see here: https://commons.wikimedia.org/wiki/File:20240218_xl_171823-Commons_App-Feedback.jpg

https://commons.wikimedia.org/wiki/Commons:Mobile_app/Feedback

**Comment by nicolas-raoul** [comment]
@protonpluss It is yours, thanks! :-)

If possible, please make the wiki generate the datetime by inserting just `~~~~~`. That way, the user's timezone will not introduce a discrepancy with the datetime in the signature.

**Comment by protonpluss** [comment]
> If possible, please make the wiki generate the datetime by inserting just `~~~~~`. That way, the user's timezone will not introduce a discrepancy with the datetime in the signature.

sure, I'll make it to generate default date and time by inserting `~~~~~`.

**Comment by protonpluss** [comment]
Hi @nicolas-raoul, Sorry for the delay. I have added the feature, can you Please take a look!

**Comment by OpenGreenStreet** [comment]
someone aks me: "If a user submits multiple feedback with the same version of the Commons app, these cannot be distinguished in the overview. - Where can I see this. . . ."

you can see it here:
https://commons.wikimedia.org/wiki/File:20240218_xl_171823-Commons_App-Feedback.jpg

**Comment by ujjwal2900** [comment]
Hi @nicolas-raoul, if this issue is still open and not yet resolved, can i take this up ?

**Comment by nicolas-raoul** [comment]
@ujjwal2900 Any progress to share maybe? :-)

**Comment by ujjwal2900** [comment]
Hi @nicolas-raoul , I have created a PR - #5797 for this issue. Can u pls review it and suggest if there are any more changes required.
Thanks

**Comment by OpenGreenStreet** [comment]
Thank you very much
