### ISSUE TITLE
Remove the Mapbox-related imports in Java/Kotlin/Gradle

### ISSUE THREAD

**Issue by kanahia1** [commons-app/apps-android-commons#5566]
### Description

Since we have successfully removed MapBox-related functionality (as I believe) after the https://github.com/commons-app/apps-android-commons/pull/5536, there still remains a fraction of code that is using MapBox. How about removing all traces of MapBox code as discussed in https://github.com/commons-app/apps-android-commons/issues/5458#issuecomment-1900210371?

**Comment by rohit9625** [comment]
Okay then, from where we should start?

**Comment by kanahia1** [comment]
@rohit9625 
In some code, removing the imports will not create an effect since there are many unused functions. So, we can remove them. There are places such as `LocationPickerActivity.java` their we may need to replace `com.mapbox.mapboxsdk.geometry.LatLng` with `fr.free.nrw.commons.location.LatLng` by changing the code accordingly. Also, there are places such as `ExploreMapPresenter.java` their we may need to replace `com.mapbox.mapboxsdk.annotations.Marker`

How about starting with removing unused code ?

**Comment by kanahia1** [comment]
@nicolas-raoul, Shall we work on it ?

**Comment by rohit9625** [comment]
Is this process big enough to work two persons on it? If yes, then I would go with the task `removing unused Mapbox imports and dependencies` and you can work on the other task. 
What do you think @kanahia1?

**Comment by kanahia1** [comment]
I don't feel this is big enough, but surely we can split up things to achieve this issue ASAP ☺️

**Comment by rohit9625** [comment]
Sure :)

**Comment by rohit9625** [comment]
Well I found a file `NearbyParentFragmentUnitTest` file also has some Mapbox usages as you can see in this screenshot:

![image](https://github.com/commons-app/apps-android-commons/assets/101377978/4b47221a-0420-4670-a495-4c596e1b7634)

Can you please also specify with which imports we will replace these Mapbox imports?
