### ISSUE TITLE
Too many duplicate images uploaded 

### ISSUE THREAD

**Issue by RitikaPahwa4444** [commons-app/apps-android-commons#5572]
### Description

Yesterday, too many duplicates were uploaded via the app. Most of them were the images [I uploaded in 2023](https://commons.wikimedia.org/wiki/Commons:Administrators%27_noticeboard/User_problems#c-The_Squirrel_Conspiracy-20240224103100-Krorokeroro-20240224094900). I checked a few uploads that still exist on Commons. They are using branches like:
- `4.2.1-debug-main~e7b15b116`
- `4.2.0-debug-retain-image-issue-fresco~b0065935b`
- `4.2.1-debug-mapbox_token~9a11c22df`
- `4.2.1-debug-test~c8be8885c`

Is anyone testing?

**Comment by nicolas-raoul** [comment]
@srishti-R FYI

I believe this will not happen anymore now. :-)

**Comment by srishti-R** [comment]
@RitikaPahwa4444 @nicolas-raoul so sorry for this 🙉 , I was testing and got blocked also.

**Comment by RitikaPahwa4444** [comment]
Thanks Nicolas for checking this :)
