### ISSUE TITLE
My website-uploaded pictures do not appear in Contributions

### ISSUE THREAD

**Issue by Laserlicht** [commons-app/apps-android-commons#5579]
### Summary

I've have many contributions (images/videos) > 4500. But the contributions page don't show up the new images (last images are a few month old).

I also had this behavior with my old device since over a year.

Sometime it updates the list (I was able to trigger this update once if I scroll down a few hundreds pictures).

### Steps to reproduce

Open "Contributions" tab

### Expected behaviour

Show last image on top

### Actual behaviour

It shows old images as last images.

### Device name

Samsung S23 & Huawei P30

### Android version

Android 14 & Android 10

### Commons app version

4.2.1

### Would you like to work on the issue?

Prefer not

**Comment by nicolas-raoul** [comment]
Would you mind posting a screenshot, and letting us know your wiki username?

**Comment by Laserlicht** [comment]
Yes of course

https://commons.wikimedia.org/w/index.php?title=Special:ListFiles/Laserlicht&ilshowall=1

Screenshot: I'm currently not able to upload the image due Github bug.

But the top image in my contributions list is: https://commons.wikimedia.org/wiki/File:Regenrückhaltebacken_Stetten_i.R.jpg (from November).

**Comment by nicolas-raoul** [comment]
By any chance, was Regenrückhaltebacken_Stetten_i.R.jpg the last file you uploaded before installing the Android app?

I don't think the app updates your contributions unless you upload _from_ the app.

Is it what is happening here? If yes, that's a good improvement idea.

**Comment by Laserlicht** [comment]
Maybe this was the last image before installing the app.

But it is totally unclear to me, when it is updating the list.

I tested it again. I scrolled a few hundreds pictures down to the bottom of the list and up again. And now it's refreshed. And the newest entry in the app is now the newest entry on commons.

But it's nothing self explanatory...

**Comment by Dr-Mx** [comment]
I have the same behaviour with contributions made through the web-app not refreshing on the mobile-app with latest uploads. Maybe by pulling down on the contributions page could force a refresh?

**Comment by Laserlicht** [comment]
Yes, this thing should implemented: https://developer.android.com/develop/ui/views/touch-and-input/swipe

**Comment by nicolas-raoul** [comment]
We could both implement swipe refresh, and poll the server about once a day.

**Comment by mnalis** [comment]
see also https://github.com/commons-app/apps-android-commons/issues/5689, https://github.com/commons-app/apps-android-commons/issues/5131#issuecomment-1368408843

**Comment by nicolas-raoul** [comment]
Let's focus the discussion at #5689
