### ISSUE TITLE
[Bug]: Dialog Scroll Issue When Keyboard is Shown on Android 9

### ISSUE THREAD

**Issue by neeldoshii** [commons-app/apps-android-commons#5581]
### Summary

**This issue arises only on Android Version 9.** It works well on Android 14. 

## About Issue

When you click on edit-text the keyboard appears, but there is no way to scroll the dialog and reach to the submit button. 
Thus, making it unavailable to submit the valuable feedback by the user.

I have fixed this issue locally its one line fix. 

```
Objects.requireNonNull(getWindow()).setSoftInputMode(LayoutParams.SOFT_INPUT_ADJUST_RESIZE);
```

### Steps to reproduce

1. Open the app.
2. Click on the more from the bottom Navigation
3. From the bottomSheet click on Feedback
4. Scroll (Make sure you are on Android 9, it works properly on Android 13,14)

### Expected behaviour

Allow the user to scroll when the keyboard is shown.

### Actual behaviour

Doesn't lets the user to scroll, hide keyboard. Thus has only one option which is dismiss the dialog.

### Android version

Android 9

### Commons app version

4.2.1-debug

### Device logs

API level: 28
Android version: 9
Device manufacturer: OPPO
Device model: CPH1859
Device: CPH1859
Network type: wifi
App version name: 4.2.1-debug
User name: null

### Screen-shots

https://github.com/commons-app/apps-android-commons/assets/60827173/57480466-d4cf-4205-b64b-416ee5ef6fc7

### Would you like to work on the issue?

Yes

**Comment by neeldoshii** [comment]
I have fixed this issue locally. If this issue is considered valid I will release the PR .

Before

https://github.com/commons-app/apps-android-commons/assets/60827173/57480466-d4cf-4205-b64b-416ee5ef6fc7

After

https://github.com/commons-app/apps-android-commons/assets/60827173/ae0c6542-29d2-4059-9275-b018d6ebba8f

**Comment by nicolas-raoul** [comment]
Good improvement thanks! Feel free to send a PR :-)

**Comment by neeldoshii** [comment]
Added the PR for fix @nicolas-raoul
