### ISSUE TITLE
Enhancement: Migrate from Views to Compose

### ISSUE THREAD

**Issue by AbdhilahiRWabwire** [commons-app/apps-android-commons#5582]
### What is the user problem or growth opportunity you want to see solved?

There are Views in this application. Users of Views should migrate to Compose.

### How do you know that this problem exists today? Why is this important?

There are Views that I would like to migrate to Compose. Migration to KSP complete. 

### Who will benefit from it?

The entire team and application. 

### Anything else you would like to add?

Jetpack Compose is the migration that is recommended by the Android and Kotlin teams.

**Comment by psh** [comment]
Compose is really nice, but I think we need to get through the current migration away from _Butterknife_ and _synthetic imports_ before taking on a large refactor like that.  Also, how well do those tools play with a (mostly) Java codebase like this app has?

**Comment by AbdhilahiRWabwire** [comment]
Well migrating from Views to compose can be done 1 View at a time but it has to be a collective effort. Also Compose will allow us to remove Dagger/Hilt, KAPT/KSP and RX and use State Hoisting and onCreate injection. This will simplify the code base beyond belief. I have done this before and am currently looking to implement this not only here but across the ecosystem (I am dedicated to this effort because we live in strange times that require it).

**Comment by AbdhilahiRWabwire** [comment]
I see the Jetpack Compose Migration has begun.
