### ISSUE TITLE
[Discussion] Upload Queue Management UI/UX

### ISSUE THREAD

**Issue by kanahia1** [commons-app/apps-android-commons#5583]
![Frame 51](https://github.com/commons-app/apps-android-commons/assets/114223204/7ae884c0-61eb-4689-9535-9e8799eb1a1a)

![Frame 52](https://github.com/commons-app/apps-android-commons/assets/114223204/7d3bf8fd-844f-4362-84dc-f40ff16ae304)

I have developed the UI for the upload queue management, thought that best possible User Experience Design can only be developed by collecting the data from other contributors. So I have made it open to discussion. 

For suggestions, just comment down 🙂

**Comment by ShashwatKedia** [comment]
Hey Kanahia, just saw your developed design, and it looks awesome. 
Features I really liked:
1. An overall pause and cancel button.
2. Different colours for different states of upload (though they might need to be adjusted for light theme as well)

Some points I would like clarification on:
1. The ContributionsFragment, already has a lot of buttons, banners and menus, don't you think that adding another banner will clutter the already full screen?
2. A banner as complex as the one designed here and with all those pause, cancel, etc buttons so close to each other (vertically), the user may get intimidated and inevitably click any incorrect button, ruining the user experience (and even cancelling uploads if they press yes in the alert dialog which would follow).
3. Assuming, that the campaigns and nearby banner both are visible, it will leave very little screen space left for the user to see past contributions. If the limited connections mode is also turned on, it would make matters worse :(
4. The image thumbnail in the progress banner, seems very small to me. Let's assume, someone uploads images of the same item in 20 different angles. Now, if for some reason, they want to cancel the upload of one or more angles, they would find it very difficult to make out which one they want to cancel.
5. In the last frame, the upload fails and the Progress list shows "1 Upload Failed". Could you explain what the progress list would show if 1 upload has failed, but some others are still going on? Also, do you think of having an overall retry button even when some uploads are going on while some have failed?
6. Not related to the pending uploads design, but in your screenshots the RandomTest1 is placed on top of RandomTest2. Assuming that you would have uploaded RandomTest2 after RandomTest1, it should be kept at the top of the contributions list, when it gets removed from the progress list.

**Comment by kanahia1** [comment]
Thanks @ShashwatKedia for the suggestions

**Comment by kanahia1** [comment]
![Frame 53](https://github.com/commons-app/apps-android-commons/assets/114223204/c4fd22a8-f031-4c17-a070-4fffeee3122c)


Thanks all for suggestions, here's improvised design. 
Looking forward for more suggestions, Just comment down ☺️

**Comment by shashankiitbhu** [comment]
Hi @kanahia1 can you explain the flow for your Improved Design Above? How a user will get to this screen? I was thinking maybe having a single banner at top just Showing the use " N Uploads in Progress" and clicking on it will take you to the Pending Uploads Activity, something like you have presented above - It will be quite straightforward and intuitive for the user.

**Comment by kanahia1** [comment]
Thanks @shashankiitbhu for the suggestions

![Frame 53](https://github.com/commons-app/apps-android-commons/assets/114223204/5f53b005-1bfe-458f-9aa5-91de45b3f78d)

Single banner will create clutter since there's already too much on the screen. So I have followed a similar approach used by web browsers for downloads.

**Comment by nicolas-raoul** [comment]
Looks good to me! :-)

About the top progress bar: Let's say I launch a 20-pics multiupload, and when the top progress bar shows "18/20 uploaded" I launch aother 20-pics multiupload. Will it now show "18/40 uploaded"? With the denominator being reset only once all pictures have bee uploaded?

**Comment by kanahia1** [comment]
Yup! Denomanator will show the total uploading right now, if 20 more are uploaded 20 will add up.

**Comment by nicolas-raoul** [comment]
I guess the first upload will be re-tried if it fails.

What if all retries fail for some reason?
Should there be a different tab for such permanent errors?

**Comment by kanahia1** [comment]
Here's something I have came up with for handling errors. But surely we may need some new tab for permanent errors. I am trying to incorporate it in this design.

![Frame 53](https://github.com/commons-app/apps-android-commons/assets/114223204/16223d47-3115-4ed0-a4a5-c66382bec525)

**Comment by nicolas-raoul** [comment]
Looking forward to seeing the Errors tab/page. :-)

There is a design choice to make on when/how to show errors in the home activity.

By the way, there are automatic retries. Tapping "retry" manually often does not work better.

**Comment by kanahia1** [comment]
Here is something I was thinking of similar to Linkedin do while uploading posts but they show only uploading progress.

![Frame 57](https://github.com/commons-app/apps-android-commons/assets/114223204/52229b58-3de1-448d-9910-400af5ff3ce6)

**Comment by kanahia1** [comment]
This seems better. I have kept both in the tabs so that on clicking an icon on home activity user should be able to see both pending and errors. Are we keeping automatic retry on each time user opens the app ?

![Frame 58](https://github.com/commons-app/apps-android-commons/assets/114223204/627d994c-f25a-4f0f-8908-03226eb21a3c)

**Comment by nicolas-raoul** [comment]
Yes I think each failure is retried every time the app is launched. That can potentially be modified during this GSoC if needed.

Minor detail: The "Failed" tab too could have delete buttons. For instance there may be bugs where a picture is actually uploaded but considered as failed.

**Comment by kanahia1** [comment]
Sure done!
![Frame 58](https://github.com/commons-app/apps-android-commons/assets/114223204/9f8035d2-2e21-4136-9937-cc24d97a32d3)
