### ISSUE TITLE
[Bug]: Rejecting Permission Leads to Continious Dialog Creation and app freezes

### ISSUE THREAD

**Issue by neeldoshii** [commons-app/apps-android-commons#5584]
### Summary

I was working on conversion of Toast to Snackbar I found this high priority bug.
When you open app (first time opened) and go to nearby. It will ask for location permission. 
If the permission is granted it shows you nearby. 
If the permission is declined it will ask for permission forcefully from the user even if the user wishes not to share location. (This is not good for user to forcefully accept the permission)
If the user wishes not to ask permission dialog again then the app will get freeze. 

### Steps to reproduce

1. Open the app first time. 
2. Go to Nearby.
3. It will ask for permission (location)
4. Decline.
5. It will ask again and again.

### Expected behaviour

Ask once. 
1. If the user declines dont't ask again and agian. Call the permission again when the user is trying to access location feature.
2. The app should not be freezed if the user has location permission off

### Actual behaviour

App freezed and constant dialog creation

### Android version

Android 14

### Commons app version

4.2.1-debug

### Screen-shots

The following video shows the issue and proposed solution from google maps.

https://github.com/commons-app/apps-android-commons/assets/60827173/74315a2d-f2e6-4831-8edc-f359291dc647

### Would you like to work on the issue?

Yes

**Comment by ShashwatKedia** [comment]
Hey @neeldoshii, this issue is already noted and is solved in #5494. Changes will be visible once it is merged with the main branch :)

**Comment by neeldoshii** [comment]
Closing this issue as it is duplicate.
