### ISSUE TITLE
Discussion : Upload Queue Management New Design Proposal

### ISSUE THREAD

**Issue by neeldoshii** [commons-app/apps-android-commons#5602]
# New Design Proposal: Upload Queue Management

## Description 

Currently the upload queue can be seen on the contributor screen. But lets take an example an user has uploaded has 100 images and at the contributor screen the user will need to perform a large scroll seeing the progress of the upload progress? Also there is no way to know a count how much actually got uploaded(count), how much actually failed(count), how much is getting uploaded(count).

## Design Documents / Mockups
<p align="center">
  <img src="https://github.com/commons-app/apps-android-commons/assets/60827173/6bbd9f32-9b52-4ac0-80be-cc8144d40fe8" width="60%" height="60%"/>
</p>

FigJam : 
Refer to the Figjam link which shows a details proposed changed why the things have been implemented with ease.
[Figjam Link](https://www.figma.com/file/PJ0cJevz6WFcgHXWLIaWCl/FigJam-Commons-App-GSOC?type=whiteboard&node-id=4%3A344&t=PrL3YROsGiJABYFR-1)

Figma link to refer the design assets.
Figma : 
[Figma Link](https://www.figma.com/file/kOU21VCLQ2ebSG8pGsh9ic/Commons-App-GSOC?type=design&node-id=0%3A1&mode=design&t=mQmbPhUWblTMGyyT-1)

## Why considered this 
Figjam Proposed details changed Image

![image](https://github.com/commons-app/apps-android-commons/assets/60827173/92ab7335-34a0-4cde-9c14-190122a9011b)

**Note to Reviewers**: Please provide constructive feedback and suggestions to help improve this proposal. Your expertise and insights are valuable to making this feature as effective as possible.

Thank you for your time.

**Comment by neeldoshii** [comment]
cc ping : @nicolas-raoul @RitikaPahwa4444

**Comment by nicolas-raoul** [comment]
Nice idea :-)
