### ISSUE TITLE
Two duplicates among 400 uploads

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#5608]
I uploaded 400 pictures in a few successios of 20-pics multi-uploads, using the custom picker.
Two of the uploads were duplicated:

![Screenshot_20240305-232301.png](https://github.com/commons-app/apps-android-commons/assets/99590/28474581-0989-4e7e-aee3-47766f0b1e5d)

![Screenshot_20240305-232429.png](https://github.com/commons-app/apps-android-commons/assets/99590/453ca7b2-3c18-4134-b510-669dff264497)

**Comment by rohit9625** [comment]
May I get to an access to the account where these duplicate uploads are visible?

**Comment by nicolas-raoul** [comment]
Sure: https://commons.m.wikimedia.org/wiki/Special:ListFiles/Syced

**Comment by nicolas-raoul** [comment]
![Screenshot_20240306-150941.png](https://github.com/commons-app/apps-android-commons/assets/99590/345f7fee-e73d-4078-95a7-dbdac5c544ed)

**Comment by nicolas-raoul** [comment]
This is probably best kept for GSoC itself.

**Comment by ShashwatKedia** [comment]
Hey, I also saw that some of my uploads have been duplicated, though I didn't upload a quantity as huge as @nicolas-raoul did and from what I remember, while the items were being uploaded it was showing only one item, but as soon as it got uploaded successfully, it showed 2 images :(
![Screenshot_2024-03-06-11-40-39-30_d5db3f3edc380047609fe9c266f7c566.jpg](https://github.com/commons-app/apps-android-commons/assets/142137555/d410685f-9319-42d3-900b-eb1ad1642e5e)

![Screenshot_2024-03-06-11-40-58-68_d5db3f3edc380047609fe9c266f7c566.jpg](https://github.com/commons-app/apps-android-commons/assets/142137555/1af905e0-3787-4877-96f0-446d44faf455)

**Comment by rohit9625** [comment]
> This is probably best kept for GSoC itself.

Yeah right.

**Comment by ShashwatKedia** [comment]
> This is probably best kept for GSoC itself.

@nicolas-raoul, This means it should be added to our proposals as well as to the Phabricator [issue](https://phabricator.wikimedia.org/T356237), stating the task for this year's GSoC, right?

**Comment by nicolas-raoul** [comment]
@ShashwatKedia I indeed forgot that, thanks a lot for pointing it out!

**Comment by kanahia1** [comment]
Hi @ShashwatKedia, If possible, can you please some details. I am also trying to reproduce this issue.

**Comment by kanahia1** [comment]
I was able to reproduce by chance, but did not found any specific reason. Looking into it...

![WhatsApp Image 2024-06-24 at 23 05 58_80764f37](https://github.com/commons-app/apps-android-commons/assets/114223204/ed1155f4-ef0d-4048-8191-4c9e90a0572f)

![WhatsApp Image 2024-06-24 at 23 05 59_92ed9710](https://github.com/commons-app/apps-android-commons/assets/114223204/ba636d51-2f10-4faa-a0de-6416964df946)

![WhatsApp Image 2024-06-24 at 23 06 00_dd95d6b9](https://github.com/commons-app/apps-android-commons/assets/114223204/3163c60f-8be5-44ec-8637-1a208fc6bce8)

**Comment by ShashwatKedia** [comment]
> Hi @ShashwatKedia, If possible, can you please some details. I am also trying to reproduce this issue.

Hey, as done by you, even I was able to reproduce it by chance only, not very sure how exactly :(

**Comment by chrisdebian** [comment]
Hi, all. Is this still an issue?

Thanks,

Chris.

**Comment by nicolas-raoul** [comment]
I haven't noticed this in a while, though it might have happened without me being aware of it.
I will close for now, but if anyone observe this issue with the latest version please reopen. Thanks!
