### ISSUE TITLE
Remove Mapbox from CREDITS

### ISSUE THREAD

**Issue by kanahia1** [commons-app/apps-android-commons#5611]
Since we have successfully replaced MapBox. Should we also remove it from CREDITS ?
https://github.com/commons-app/apps-android-commons/blob/main/CREDITS

_If yes, label : good first issue_

**Comment by 0x11110** [comment]
May I?

**Comment by whym** [comment]
I didn't follow the transition closely, but it looks like there is still some mapbox code in the repository?  [Searching "mapbox"](https://github.com/search?q=repo%3Acommons-app%2Fapps-android-commons%20mapbox&type=code) gives me 30 hits (files).
