### ISSUE TITLE
I have been blocked from wikimedia during testing.

### ISSUE THREAD

**Issue by neeldoshii** [commons-app/apps-android-commons#5614]
As said by @nicolas-raoul in https://github.com/commons-app/apps-android-commons/issues/5605#issuecomment-1982221024

Here is the reason for being blocked. 
Username : ** Devanonymous**
<img width="1512" alt="Screenshot 2024-03-08 at 8 11 06 PM" src="https://github.com/commons-app/apps-android-commons/assets/60827173/b3ffb921-c097-48b2-ad26-75b038b6f49e">

I'm also keen to learn more about how we can effectively test certain features, like nominations for deletion, directly on the proddebug environment. This is particularly important for functionalities that aren't accessible in the beta version. Since testing on production might risk uploading non-encyclopedic images, I'm curious if there's a recommended approach to ensure we maintain the integrity of the content while still being able to thoroughly test the app's features.

Thanks

**Comment by nicolas-raoul** [comment]
infinite is harsh... I would recommend focussing on non-upload features for now.

**Comment by nicolas-raoul** [comment]
User link for convenience:
https://commons.m.wikimedia.org/wiki/Special:Contributions/Devanonymous

**Comment by whym** [comment]
Here are some things you can do in future:

- Use beta flavor and upload to https://commons.wikimedia.beta.wmflabs.org/ instead of commons.wikimedia.org.
- When you use commons.wikimedia.org, add "Test images" to categories so that admins know that they can delete images you have uploaded at anytime.
- Don't ask to delete too many images using the app's feature - admins take time to review nominated files. Instead, use the "Test images" category mentioned above.

**Comment by neeldoshii** [comment]
> Here are some things you can do in future:
> 
> * Use beta flavor and upload to https://commons.wikimedia.beta.wmflabs.org/ instead of commons.wikimedia.org.
> * When you use commons.wikimedia.org, add "Test images" to categories so that admins know that they can delete images you have uploaded at anytime.
> * Don't ask to delete too many images using the app's feature - admins take time to review nominated files. Instead, use the "Test images" category mentioned above.

Noted.

> User link for convenience:
> https://commons.m.wikimedia.org/wiki/Special:Contributions/Devanonymous

Now what's the process I can perform to get unbanned?

**Comment by whym** [comment]
@neeldoshii You are supposed to do what the message says ({{unblock|your reasons...}}). An admin will review it.

I would suggest starting to upload test images to commons.wikimedia.beta.wmflabs.org, and prove that you are not going to repeat the same thing before doing an unblock request. That way the request would be more convincing (and you need to convince an admin to unblock you).

**Comment by neeldoshii** [comment]
@nicolas-raoul @RitikaPahwa4444 

Just a friendly ping, given the situation of my account ban, will I be able to participate for GSOC this year since my account is banned and major task this year relies on uploading queue. I have taken the steps provided by whym to get unblocked.

Thank You

**Comment by whym** [comment]
@neeldoshii I think you have been unblocked a few hours ago.
https://commons.m.wikimedia.org/w/index.php?title=User_talk:Devanonymous&diff=prev&oldid=861383099&title=User_talk%3ADevanonymous&diffonly=1
They say that some of the images you uploaded were copyright violation (which is indeed a reason for an immediate block) - that's another thing to keep in mind. Test uploads need to be either public domain or photographs you have taken.

**Comment by nicolas-raoul** [comment]
I added instructions to avoid such problems in the future: https://github.com/commons-app/commons-app-documentation/blob/master/android/Volunteers-welcome!.md#developers

Another tip: Write an intro/bio on your user page https://commons.wikimedia.org/wiki/User:Devanonymous saying what are your hobbies, skills, what kinds of photographs you like. Wikimedians tend to trust people with a profile more.

**Comment by neeldoshii** [comment]
> If you must upload pictures to the production server, please only upload encyclopedia-worthy pictures you took by yourself. You can also ask [Nicolas Raoul](https://nicolasraoul.github.io/) to provide encyclopedia-worthy pictures for you to upload.

Can I get encyclopedia-worthy pictures for testing? 

Also closing this as the account is unbanned.
Thank you all.
