### ISSUE TITLE
[Bug]: Sub Categories and Parent Categories should be shown if available

### ISSUE THREAD

**Issue by rohit9625** [commons-app/apps-android-commons#5626]
### Summary

When I browse the category on a details page of an upload, I see the blank **sub-categories** and **parent categories** page. For some categories, there are no sub and parent-categories available. So in that case, we should display a message(e.g. using `Snackbar` or maybe just showing text in the middle of the screen). Also, the screen is still blank for some categories despite having sub-categories available on the category page.

### Steps to reproduce

1. Open any image(self uploaded or from the Explore tab) details page 
2. Click on any category from the Categories section
3. Switch to sub-categories tab
4. You'll see a blank screen even sub-categories are available on the category page

### Expected behaviour

There should be a message similar to this `No sub-categories available`, if not available. And should show the sub-categories list if available.

### Actual behaviour

The screen is blank with no response message.

### Device name

SAMSUNG A14

### Android version

ANDROID 14

### Commons app version

4.2.1

### Screen-shots

![WhatsApp Image 2024-03-16 at 09 12 43_a5f2568e](https://github.com/commons-app/apps-android-commons/assets/101377978/551f45c1-86b4-43ac-8092-160a0d86bf60)
![WhatsApp Image 2024-03-16 at 09 12 43_a418479e](https://github.com/commons-app/apps-android-commons/assets/101377978/cfe1543c-6aec-45f4-92d6-6a6457cf41b4)

**Category Page**
![WhatsApp Image 2024-03-16 at 09 12 42_f5c05f2b](https://github.com/commons-app/apps-android-commons/assets/101377978/0db93e20-d653-496b-8dd9-29440027e37d)

### Would you like to work on the issue?

Yes

**Comment by nicolas-raoul** [comment]
I would say showing text in the middle of the screen is the best, rather than a snackbar :-)

**Comment by nicolas-raoul** [comment]
Somehow category search isn't even working for me.

**Comment by nicolas-raoul** [comment]
Thanks for discovering this bug!
I will close in favor of #5758, thanks for your understanding.
