### ISSUE TITLE
Custom picker: thumbnails sometimes blank

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#5627]
Introduced by pull request https://github.com/commons-app/apps-android-commons/pull/5576

Examples:

![Screenshot_20240303-151913.png](https://github.com/commons-app/apps-android-commons/assets/99590/3443600f-6871-4227-9814-ad34da9b3fa3)

![Screenshot_20240303-151822.png](https://github.com/commons-app/apps-android-commons/assets/99590/1d73c410-bf70-480a-b178-336bad5c515b)

**Comment by rohit9625** [comment]
For how long this remains blank?

**Comment by shashankiitbhu** [comment]
@nicolas-raoul As I have explained this in my original PR that this is because how we process thumbnails and with slight modifications to that we can achieve a fast and consistent loading for all the thumbnails , I'll be working to solve this ASAP, please assign it to me

**Comment by shashankiitbhu** [comment]
@nicolas-raoul I Added the PR to fix this, Please Review and Merge, thanks
