### ISSUE TITLE
Option to Remove Specific Images from Upload Wizard

### ISSUE THREAD

**Issue by shashankiitbhu** [commons-app/apps-android-commons#5630]
### What is the user problem or growth opportunity you want to see solved?

Currently When Choosing to Upload Multiple Images at once you have to Upload All Images that You have selected but Let's Consider a case where I have Selected 1 Wrong Image without realizing that is in the Middle, In this case, all My Changes Will be lost If Chose to Not Upload this Image.

### How do you know that this problem exists today? Why is this important?

Upload Multiple Images in this app is very common and it's also common to make mistakes while selecting Images but users should not have to reselect all the Images in order to remove that Image.

### Who will benefit from it?

All Commons App Users

### Anything else you would like to add?

To Solve this, There should be a Cross Icon at the Top Right corner of each Image That Will allow us to remove that Image without affecting the rest. 

![WhatsApp Image 2024-03-18 at 5 24 30 PM](https://github.com/commons-app/apps-android-commons/assets/126143257/009dd4c6-52cc-4711-8b7e-7b0d14ad0609)

I have some interesting mockups to Improve this Overall Process of Removing Specific Images from Upload Queue, will be showing them soon in the discussion

I am working on this

**Comment by nicolas-raoul** [comment]
oops I clicked the wrong button

**Comment by shashankiitbhu** [comment]
>  Currently I proceed with the upload anyway then try to quickly cancel the uploads I want to remove before they finish.

Exactly, this seems very Inefficient and Flow isn't standard at all. 

If we Implement the suggested enhancement we can not only save users a lot of time and extra trouble but also avoid incorrect contributions to the platform

**Comment by kanahia1** [comment]
@nicolas-raoul @shashankiitbhu Can I work on this issue ?

**Comment by shashankiitbhu** [comment]
@kanahia1 Sorry I am already working on this as I mentioned in this Issue description, you can try other issues and enhancements

**Comment by shashankiitbhu** [comment]
@nicolas-raoul Here is how I have Implemented it, If this change seems satisfactory then I will go ahead with completing it. As you can see in the screenshot below I have added a cross Icon at each thumbnail which will provide a way for users to remove these Images from upload stack.
![WhatsApp Image 2024-03-21 at 11 33 36 PM](https://github.com/commons-app/apps-android-commons/assets/126143257/6ac54061-9207-4b83-b985-f808472c96f3)

**Comment by kanahia1** [comment]
Hey @shashankiitbhu, how about moving cross button to top right Since due to utilization of technology we are trained look for cross button in top right corner in every place.

References
https://www.marketpath.com/blog/button-ui-design#:~:text=consider%20as%20standard%3A-,Close%20Button%20Dialog,ever%20opened%20to%20do%20so.

https://community.uxmastery.com/t/location-of-the-close-button-in-a-modal-window/5459/6

**Comment by shashankiitbhu** [comment]
@kanahia1 Makes Sense , Still Doing Brainstorming on better UX for this Enhancement so will add some updates soon.
