### ISSUE TITLE
Emphasize that depictions/categories apply to all pictures of a multi-upload

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#5633]
Some users are selecting multiple unrelated pictures then uploading them as a set (multi-upload).
The problem is that the depictions/categories apply to all pictures in the set, leading to irrelevant depictions/categories being applied.
For instance a user uploaded a picture of a light and a picture of a dam, and now both pictures have depictions "dam":
<img width="823" alt="Screenshot 2024-03-20 at 16 23 55" src="https://github.com/commons-app/apps-android-commons/assets/99590/8412169e-9ebf-408c-ae37-83f85bacfb3b">

We should find what parts of the UI could be improved to avoid such problems.

First one: "Nearby Place Found" should say `Are these pictures of ___?` instead of `Is this`:
![Screenshot_20240320-161944.png](https://github.com/commons-app/apps-android-commons/assets/99590/66c5c297-306a-42cb-8e5a-4dc65c8f3b54)

**Comment by shashankiitbhu** [comment]
@nicolas-raoul In Multi Upload we should instruct users that all of the pictures that they are uploading should be of same depiction, maybe we should show Dialog After user selects multiple uploads in Upload Wizard. 

In case the user selected something that is not under the same depiction then they can remove that selection , and that feature will be provided by #5630

**Comment by nicolas-raoul** [comment]
> Suppose I want to upload 12 pictures in which, 3 pictures are of a building, 5 are sign boards and 4 are flower images

In that case you should perform 3 different multi-uploads, each for a specific category of pictures. The app is built on this assumption, but we may need to convey it better. :-)

**Comment by karyotakisg** [comment]
Can i get assigned for that?

**Comment by karyotakisg** [comment]
Furthermore, please assign it to @vtalos too.

**Comment by vtalos** [comment]
> Can I get assigned for that with @vtalos ?

I would really like to work on this with @karyotakisg!

**Comment by vtalos** [comment]
> First one: "Nearby Place Found" should say `Are these pictures of ___?` instead of `Is this`:
>

Is this necessary? I mean what if someone uploads two different pictures of two different police stations in different locations and sets the depiction-category to "Police Station"?

Or should it be the same one in both photos?
If yes, the user should be urged to set one location for the whole set (and not for each photo of the set).

**Comment by nicolas-raoul** [comment]
If there is a Wikidata items for each of these police stations, we want the user to use the Upload Wizard twice (once for each police station). This honestly saves time, as the Upload Wizard will pre-fill everything.

> the user should be urged to set one location for the whole set (and not for each photo of the set).

That's actually a very good idea! We could first get the location of all pictures of the set, ask the user whether these are pictures of XXX ("or YYY or ZZZ" ideally), and only then proceed with the caption/description of each. It would be particularly beneficial when the first pictures do not have EXIF location (for instance because the GPS was slow to start, that happens on DSLRs). The only drawback is more time lost waiting at the beginning.
