### ISSUE TITLE
[Bug]: App stopped working on Mi8

### ISSUE THREAD

**Issue by alcpp** [commons-app/apps-android-commons#5637]
### Summary

App stopped working on Mi8. It was working before

### Steps to reproduce

1. Start app
2. Observe start screen
3. Nothing happens

### Expected behaviour

App should open

### Actual behaviour

Start screen is showing and nothing happens

### Device name

Mi8

### Android version

10

### Commons app version

4.2.1

### Would you like to work on the issue?

None

**Comment by alcpp** [comment]
Close. I didn't understood interface

**Comment by nicolas-raoul** [comment]
Would it help if we add a call to action on the first empty screen?

For instance "Welcome to Commons! Upload your first picture by tarpini the + sign"

**Comment by ShashwatKedia** [comment]
> Would it help if we add a call to action on the first empty screen?
> 
> For instance "Welcome to Commons! Upload your first picture by tarpini the + sign"

@nicolas-raoul Yeah I think that enhancement is long pending. Some discussion was already going on [here](https://github.com/commons-app/apps-android-commons/issues/1363) and [these](https://github.com/commons-app/apps-android-commons/issues/1363#issuecomment-379157168) designs seem to be good enough to be implemented. What are your thoughts?
