### ISSUE TITLE
Nearby export: Pins not all around me

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#5650]
Ideally pins should form a square or circle around my position, rather than using my position as a corner:

![Screenshot_20240325-231850.png](https://github.com/commons-app/apps-android-commons/assets/99590/5ab91f14-cb29-43fc-b2db-30a26598ab0c)

**Comment by nicolas-raoul** [comment]
Rectangle is probably easier to implement for now.
How about 10 kilometers North/South/East/West?
A few years ago I originally said 100 km but there are many more points now so it would take too long.

**Comment by kanahia1** [comment]
Thanks for providing information. I will work on it!

**Comment by kanahia1** [comment]
Hey @nicolas-raoul, I have added to code to give coordinates for 10Km North-East and South-West. I have used 0.008 as it is approximately 1Km. [Reference](https://stackoverflow.com/questions/5217348/how-do-i-convert-kilometres-to-degrees-in-geodjango-geos)

```
    public static LatLng calculateNorthEast(double latitude, double longitude, double distance) {
        double lat1 = Math.toRadians(latitude);
        double deltaLat = distance * 0.008;
        double deltaLon = distance / Math.cos(lat1)*0.008;
        double lat2 = latitude + deltaLat;
        double lon2 = longitude + deltaLon;

        return new LatLng(lat2, lon2, 0);
    }

    public static LatLng calculateSouthWest(double latitude, double longitude, double distance) {
        double lat1 = Math.toRadians(latitude);
        double deltaLat = distance * 0.008;
        double deltaLon = distance / Math.cos(lat1)*0.008;
        double lat2 = latitude - deltaLat;
        double lon2 = longitude - deltaLon;

        return new LatLng(lat2, lon2, 0);
    }
```

Can you please have a look at PR https://github.com/commons-app/apps-android-commons/pull/5658, Since I am getting same problem.

**Comment by nicolas-raoul** [comment]
Can you run in debug mode, note down the result of each function, and draw these two points on the map above?

**Comment by kanahia1** [comment]
I have tested and these are the points `(25.523992142085177,85.04935220271054)` and `(25.683992142085174,85.22677465886173)`

I have plotted them on the map and are marked with (heart). 
![WhatsApp Image 2024-03-26 at 20 00 21_a42f38e4](https://github.com/commons-app/apps-android-commons/assets/114223204/1ed4efdc-0213-48f1-9fda-c708a23e850b)

**Comment by nicolas-raoul** [comment]
The points seem correctly positioned.

**Comment by kanahia1** [comment]
I am looking into it and will share an update in 2 days (currently I am out of station)
