### ISSUE TITLE
Transform the achievement page's "statistics" section into a "badges" section

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#5661]
Similar to GitHub, with for instance a `x3` to say that for instance 3 thanks were received:

<img width="268" alt="Screenshot 2024-03-27 at 16 45 44" src="https://github.com/commons-app/apps-android-commons/assets/99590/5069370c-31c5-449c-84e3-ad30ef69e105">

Tapping each badge would reveal what the badge means.

Badges with zero could be greyed out to generate interest without the negativity of a `0`.

Currently it looks like this:
<img width="502" alt="Screenshot 2024-03-27 at 16 49 38" src="https://github.com/commons-app/apps-android-commons/assets/99590/5eca89f2-24b1-4390-b13d-94a185333412">

**Comment by neeldoshii** [comment]
Taking this up while working with #5655

**Comment by shashankiitbhu** [comment]
> Taking this up while working with #5565

I think you mentioned an Incorrect pull request

**Comment by PetitPotiron** [comment]
I don't see why we should replace the current statistics page (even if it's buggy). It's really good and we don't really need to have the same appearance than GitHub.

**Comment by nicolas-raoul** [comment]
@PetitPotiron Currently most people see many zeroes, it is discouraging. Badges are more positive, and less boring than lines of statistics.

**Comment by nicolas-raoul** [comment]
@neeldoshii Any progress on your pull request? :-)

**Comment by nicolas-raoul** [comment]
@neeldoshii  I unassign for now, but if you are you still working on this, please let us know. If no answer, someone else may be assigned to it. Thanks a lot. :-)

**Comment by neeldoshii** [comment]
> @neeldoshii  I unassign for now, but if you are you still working on this, please let us know. If no answer, someone else may be assigned to it. Thanks a lot. :-)

Sure 😊

**Comment by PetitPotiron** [comment]
Hello @nicolas-raoul 
This issue interests me, but I have never done any android development before  Anyways, if no one wants to be assigned, I would be glad to be assigned at the beginning of September.
Thanks

**Comment by nicolas-raoul** [comment]
@PetitPotiron It is yours, thanks! I believe it is a good issue to start Android development. :-)

**Comment by YujingZHG** [comment]
Hi! I noticed there hasn’t been any recent progress on this issue. I am a beginner and may I try working on it? and I plan to do like this:
<img width="379" alt="image" src="https://github.com/user-attachments/assets/caa02e3d-3aca-4d59-afd9-3591220c3d89">

**Comment by PetitPotiron** [comment]
Thank you.

**Comment by nicolas-raoul** [comment]
@YujingZHG did most of the work, anyone willing to continue? Just pull [Yujing's pull request](https://github.com/commons-app/apps-android-commons/pull/5917) branch into your own branch. Thanks all! :-)

**Comment by neeldoshii** [comment]
I would like to take this issue again by next week. 

Approach:
1. Convert the achievement screen from `java`to `kt` since I believe its gonna be much class rewrite as per https://github.com/commons-app/apps-android-commons/pull/5666
2. I liked the approach of @YujingZHG but I believe its better to move it with Material 3 and `kt` for a safer transition to compose in future. https://m3.material.io/components/badges/overview

Would be continuing with my old PR #5666 which is fixing 3 issues together.
