### ISSUE TITLE
Nearby: Load pins as I move the screen, cache pins, remove "search this area" button

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#5664]
Currently, when you move the map in Nearby, you have to tap "search this area" to load the pins in the area you moved the map to.

It would be more user friendly to automatically load the pins ([like Wikishootme does](https://wikishootme.toolforge.org/#lat=-22.87782590541157&lng=-43.245078921318054&zoom=17&layers=wikidata_image,wikidata_no_image)).

Our queries take more time than Wikishootme because we load more information about each point. To avoid losing the already loaded pins (which probably are close to where I am, and thus will probably be shown in the map again shortly afterwards), each pin should be cached in the local database, with its attributes (label, class, latitude/longitude, Wikipedia URL, needs photo or not, exists or not, etc) and also the timestamp it were fetched.

Cache invalidation:
- Once a day, the cached pins whose timestamp is more than 7 days in the past should be removed from the cache.
- Every time the user initiates an upload from Nearby, the pin it came from should be removed from cache (no need to wait for the upload to finish if that makes implementation complex).

**Comment by shashankiitbhu** [comment]
@nicolas-raoul this will greatly enhance the Nearby feature, I am currently working on Nearby, I would love to take this task as well, can I work on this?

**Comment by kanahia1** [comment]
Hey @shashankiitbhu, I think we should work on https://github.com/commons-app/apps-android-commons/issues/4560 first than working on this issue. Otherwise this issue will make things much expensive. Also this issue is now part of GSoC project.

**Comment by shashankiitbhu** [comment]
> Hey @shashankiitbhu, I think we should work on https://github.com/commons-app/apps-android-commons/issues/4560 first than working on this issue. Otherwise this issue will make things much expensive. Also this issue is now part of GSoC project. How about leaving this for GSoC ?

Sorry , Just Checked it on Phabricator, Leaving it For GSOC

**Comment by shashankiitbhu** [comment]
@kanahia1 It's better do both together in a GSOC , I agree that the mentioned task should be done first

**Comment by ShashwatKedia** [comment]
@nicolas-raoul, would we want to cache the pins only within a specific radius around the user or cache all loaded pins?
Also, shouldn't we invalidate the cached pins if the current user location changes by a significant distance (for ex, before and after giving location permission, the location changes from default to the current location)?

**Comment by nicolas-raoul** [comment]
I think we should cache everything, irrespective of distance. The data is light, I don't think it will ever go over 10 MB.
