### ISSUE TITLE
Add location button UI not being updated when user clicks yes in similar image dialog

### ISSUE THREAD

**Issue by ShashwatKedia** [commons-app/apps-android-commons#5669]
### Summary

The app currently has a feature where the user can copy the location of a recently uploaded image to the new set of images being uploaded. The current image's 'Add location' button should change to 'Edit location' when the user clicks yes in the aforesaid dialog.

### Steps to reproduce

1. Start upload of an image having EXIF data
2. Cancel its upload and start upload of another set of images without EXIF data within two minutes
3. Tap "Yes" in the similar image dialog

### Expected behaviour

The current image's 'Add location' button should change to 'Remove location' with the icon also changing accordingly, as the image now has location data, which can be verified by tapping the button.

### Actual behaviour

The current image's 'Add location' button UI stays the same.

### Device name

OnePlus Nord CE 2 Lite 5G

### Android version

Android 12

### Commons app version

master

### Screen-shots

Screencast:

https://github.com/commons-app/apps-android-commons/assets/142137555/196aae8e-9be6-4f6b-b8dd-854adae2a4c5

### Would you like to work on the issue?

None

**Comment by ShashwatKedia** [comment]
@nicolas-raoul, could this issue be labelled as a 'good first issue' for newcomers to try?

**Comment by nicolas-raoul** [comment]
Thanks for spotting this bug! OK done :-)

**Comment by alxmartin01** [comment]
I would like to work on this! Can I be assigned?

**Comment by nicolas-raoul** [comment]
@alxmartin01 It is yours, thanks! 🙂

**Comment by AMANISPEACE** [comment]
Hey, Could you please assign me this issue, Would like to work on that.

**Comment by nicolas-raoul** [comment]
@alxmartin01 Any progress to share? Are you still working on this? :-)

**Comment by nishit2003** [comment]
Can I work on it?

**Comment by nicolas-raoul** [comment]
@AMANISPEACE and @nishit2003 Please use the "unassigned bugs" link at https://github.com/commons-app/commons-app-documentation/blob/master/android/Volunteers-welcome!.md to find other tasks that are waiting for someone to take care of them, thanks :-)

**Comment by AdamTWEnglish** [comment]
Hi, there hasn't been any recent activity on this issue, can I be assigned to it? I am new to this project and think this would be a great issue to work on!

**Comment by nicolas-raoul** [comment]
No news from alxmartin01 so it is yours @AdamTWEnglish thanks! :-)

**Comment by nicolas-raoul** [comment]
I believe this is fixed. :-)
