### ISSUE TITLE
Nearby -> System picker: Only allow 1 picture to be selected

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#5677]
I think we can specify whether we want 1 file or several, when we call the system picker intent.

Similar to https://github.com/commons-app/apps-android-commons/issues/5674

**Comment by rohit9625** [comment]
Hello, Mr. Nicolas :)
I made a minor change to prevent multiple selections of pictures in `System Picker`. This is what it behaves like now:

https://github.com/commons-app/apps-android-commons/assets/101377978/6e890110-34c3-40fe-a0e4-25b107102beb

Is this the required behavior, please explain if I misunderstood.
But for Custom Picker It would require a complete implementation to achieve this and I will start working towards it soon.

**Comment by nicolas-raoul** [comment]
Looks perfect! Do you want to submit a PR?
You are right, it will require some custom code for the custom picker. And passing an argument when calling it.

**Comment by rohit9625** [comment]
Yes for now, I am submitting PR for this one.

**Comment by rohit9625** [comment]
Here when passing `binding.nearbyFilter.chipView.choiceChipWlm.isChecked()` to the function **initiateGalleryOick**:
![image](https://github.com/commons-app/apps-android-commons/assets/101377978/2868d44c-f2e7-46be-9214-dd3dfd399eca)

**I wonder why the check `WLM` is not shown in the Nearby filters?** I need to pass false for the required behavior.

**Comment by nicolas-raoul** [comment]
WLM only happens at certain times of year I believe, there might be a check for that. Don't worry too much about WLM for now.

**Comment by rohit9625** [comment]
Okay then, I got it what to do now :)
