### ISSUE TITLE
Create welcome screen

### ISSUE THREAD

**Issue by tobias47n9e** [commons-app/apps-android-commons#568]
A welcome screen would be a nice addition rather than loading the upload view directly. This screen could show various things about the user and what is going on on Commons. Some proposals from the Prague hackathon:

- Picture of the day on Commons
- Ongoing campaigns
- Badges
- Most recent uploads by the user
- Some contribution statistics

**Comment by whym** [comment]
I think this is related to https://github.com/commons-app/apps-android-commons/issues/629

**Comment by chrisdebian** [comment]
@tobias47n9e @whym Hi, guys. This proposal is really old. Has it been implemented, now?

Thanks,

Chris.
