### ISSUE TITLE
When editing pic's location, default to the picture's currently set location

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#5686]
1. In Media Details of any picture, tap the pencil icon.
2. Problem: The pin is set to user's current location.

I think it would make more sense to default to the picture's currently set location if there is one. Because most often that location is close to the real one, whereas the user might be very far away.

https://github.com/commons-app/apps-android-commons/assets/99590/eae151b4-a9c8-4a4b-87b5-675dc5aa80b4

**Comment by ShashwatKedia** [comment]
@nicolas-raoul I tried to reproduce this bug on main, but the pin correctly sets to the location set in the image only, not that of the user [[Screencast]](https://drive.google.com/file/d/14X_jpPi9gfvVFFFgWLOgAP3HWYVKtNT6/view?usp=share_link)

**Comment by nicolas-raoul** [comment]
@ShashwatKedia Thanks a lot for the feedback! Sorry I really should have said that it happened on branch https://github.com/commons-app/apps-android-commons/pull/5494 I assumed it was happening on main too.
Does the problem happen for you on that branch, or not?
Thanks! :-)

**Comment by ShashwatKedia** [comment]
> Does the problem happen for you on that branch, or not?

Yes, it does happen on that branch. Looking into it :)

**Comment by ShashwatKedia** [comment]
@nicolas-raoul I have solved this in my latest commit. Could you please test and confirm the same? Thanks :)

**Comment by nicolas-raoul** [comment]
Fantastic it works now! :-)
