### ISSUE TITLE
[Bug]:  values-yue-hant preventing build

### ISSUE THREAD

**Issue by RedAuburn** [commons-app/apps-android-commons#5688]
Previous issue: https://github.com/commons-app/apps-android-commons/issues/5571

somehow, yue-hant strings have been uploaded in https://github.com/commons-app/apps-android-commons/commit/8ce7485153c4e9b5aea6b07d582c683e2ca34861, preventing build and causing CI tests to fail

**Comment by rohit9625** [comment]
I also faced that even though I added the codemap for yue-hant in the Gerrit. I don't know why the build is failing again.

**Comment by nicolas-raoul** [comment]
Strange indeed.

Can someone spot any difference with how this other locale was successfully handled?
https://github.com/commons-app/apps-android-commons/pull/5040
https://gerrit.wikimedia.org/r/c/translatewiki/+/826587

**Comment by sivaraam** [comment]
> Can someone spot any difference with how this other locale was successfully handled? #5040 https://gerrit.wikimedia.org/r/c/translatewiki/+/826587

It seems to me like the change for the `yue-hant` language code was actually done in the Wikipedia Android app's configuration file rather than in the Commons Android app's configuration file. I've moved that change over to the Commons Android app's configuration file in the following changeset:

https://gerrit.wikimedia.org/r/c/translatewiki/+/1022508

**Comment by rohit9625** [comment]
My bad, you are right. I thought that was the configuration file for the commons app also and didn't find the specific one at that time.

**Comment by sivaraam** [comment]
No worries. Let's hope it get fixed this time around 🙂

**Comment by rohit9625** [comment]
It definitely will :)

**Comment by sivaraam** [comment]
I'm closing this given that both translatewiki MR and #5702 have been merged. Let's re-open if we face this problem again 🙂
