### ISSUE TITLE
[Bug]: Commons app not showing pictures uploaded via web

### ISSUE THREAD

**Issue by mnalis** [commons-app/apps-android-commons#5689]
### Summary

I mostly upload images via Commons app, but sometimes I do it via web interface on my desktop via this webpage: https://commons.wikimedia.org/wiki/Special:UploadWizard

However, Commons app does not seem to show those uploads (on main page, or via Hamburger menu / Username / Contributions), instead of only showing the pictures uploaded via Commons app.  Even when I try to "swipe down" to try to refresh the list of pictures, or enable/disable limited connection mode in attempt to get list of contributions to "sync".

That is, needless to say, highly confusing, as then I imagine I did not upload that pictures at all...

Note: I'm lately also experiencing:
- https://github.com/commons-app/apps-android-commons/issues/5287
- https://github.com/commons-app/apps-android-commons/issues/5462

if that might be related? I'm note 100% sure, but I think that  it updated automatically correctly few months back (at least I still seem to see some older pictures in the Commons app that were uploaded e.g. in November 2023 via web interface. But the new ones in last week or two do not seem to get into the app)

### Steps to reproduce

1. Be logged in the Commons app
2. Have some pics uploaded via Commons app
3. note the list of Contributions on main screen in Commons app
4. upload some pictures to commons via https://commons.wikimedia.org/wiki/Special:UploadWizard
5. open Commons app again and check list of contributions -- it didn't change; i.e. it does not show new contributions even if app is restarted or one tries to refresh...

### Expected behaviour

after I upload some pictures to commons via https://commons.wikimedia.org/wiki/Special:UploadWizard, they should be visible in Commons app too (at least after app restart / refresh).

### Actual behaviour

pictures to commons via https://commons.wikimedia.org/wiki/Special:UploadWizard are not visible in Commons app.

### Device name

Samsung Galaxy S23+

### Android version

Android 14

### Commons app version

4.2.1~14b6c455b (latest F-droid)

### Device logs

[CommonsAppLogs2.zip](https://github.com/commons-app/apps-android-commons/files/14968834/CommonsAppLogs2.zip)

### Screen-shots

note that that yellow circle pic (`Turning marker on Jarun.jpg`) is missing in Commons app display, while it is visible on my commons web page.

https://github.com/commons-app/apps-android-commons/assets/156656/8f54ce13-45f7-4653-8061-5b0fa811da6f

### Would you like to work on the issue?

Prefer not

**Comment by RitikaPahwa4444** [comment]
I'm not sure if this has started happening recently, I remember seeing some requests in the Play Store reviews as well. For instance, this is from March 2023 (this was for tablets, but I we use the same logic I believe):

_When I upload a file from computer, I can't see the updated file from here._

**Comment by RitikaPahwa4444** [comment]
Also, does some sort of workaround like the one suggested [here](https://github.com/commons-app/apps-android-commons/issues/5131#issuecomment-1368408843) work? Some observations like the ones shared [here](https://github.com/commons-app/apps-android-commons/issues/5131#issuecomment-1520733102) might help in fixing this bug too.

**Comment by mnalis** [comment]
> Also, does some sort of workaround like the one suggested https://github.com/commons-app/apps-android-commons/issues/5131#issuecomment-1368408843 work?

Yes: logging out, and then logging back in makes the web contributions appear in the Commons app.

**Comment by mnalis** [comment]
I can confirm that bug is still present in latest f-droid release (`5.0.1~af028cbdd`) on Android 14 (OneUI 6.1), Samsung Galaxy S23+

**Comment by RitikaPahwa4444** [comment]
While signing out and then signing in again helps load the images from web, interestingly, Commons treats the images uploaded via web and app wizard differently. Even though I'd uploaded [this picture](https://commons.wikimedia.org/wiki/File:TakaneshimaWeb.jpg) via web, I didn't get any warning that the picture exists already while uploading from the app (it shows up in my contributions list on the app because of the workaround I'd followed). The picture got [uploaded again](https://commons.wikimedia.org/wiki/File:Takaneshima_66.jpg), and is still not showing as a duplicate.

**Comment by mnalis** [comment]
> I didn't get any warning that the picture exists already while uploading from the app

@RitikaPahwa4444 you should probably best open that as a **separate issue** (mentioning this one) as it seems a different problem entirely. Without looking at the source, I'd guess that either:
-  app might keep hashes of file that **it** has uploaded, but doesn't have hashes of other files on the Commons, or 
-  the **hash** of the **same file** shared via **different ways** actually has **changed** - i.e. Android 10+ will silently modifies images on sharing depending on permissions of the app the image has been shared to - see e.g. https://github.com/marcosdiez/shareviahttp/issues/84 and https://github.com/nextcloud/android/issues/6248#issuecomment-1147167524)

**Comment by rohit9625** [comment]
I tried uploading a picture from `Web Upload Wizard` and the images updated successfully on the app. However, I uploaded it from the mobile browser rather than my computer. Do you still have this issue @mnalis?

**Comment by chrisdebian** [comment]
> I tried uploading a picture from `Web Upload Wizard` and the images updated successfully on the app. However, I uploaded it from the mobile browser rather than my computer. Are you still facing the same issue @mnalis?

This is encouraging; can anyone confirm whether the functionality is now working correctly?

Thanks,

Chris.

**Comment by savsch** [comment]
> it does not show new contributions even if app is restarted...

For me, on the latest F-Droid release (5.1.0), the contributions made on the [web upload wizard](https://commons.wikimedia.org/wiki/Special:UploadWizard) appear after the app is restarted (by first removing it from the recents screen).

> or one tries to refresh

There doesn't seem to be any _pull-to-refresh_ gesture (as attempted in the attached screen recording). Implementing one is fairly straightforward. If it isn't seen as introducing unnecessary complexity, I can take it on.

**Comment by nicolas-raoul** [comment]
I just merged https://github.com/commons-app/apps-android-commons/pull/6041 which fixes this. 🙂

**Comment by mnalis** [comment]
I can confirm that with with 5.1.2 from F-droid this works, although with slight delay (which does not show that anything is happening):

- open commons app and look at a list of pictures
- upload picture to common on different device (laptop) using `Special:Uploadwizard` web page
- look at the commons app; nothing seems to change
- wait a few seconds, and then do a "drag down" gesture in hopes of refresh; nothing seems to change
- wait a few seconds, and then do a "drag down" gesture in hopes of refresh; nothing seems to change
- wait a few seconds, and then do a "drag down" gesture in hopes of refresh; nothing seems to change
- wait a dozen more seconds
- image uploaded via other device appears automagically in Commons app on mobile!

So, it works now. It is not very intuitive as there is no indicator that anything is happening in the background; but that is not really important, as I usually won't even be searching for other pictures uploaded via other device so soon (it more often happens after days or weeks when I'm searching for something I've uploaded before)
