### ISSUE TITLE
Change `Unknown` on pointer click to ... (Nearby Activity)

### ISSUE THREAD

**Issue by kanahia1** [commons-app/apps-android-commons#5690]
Since on the pointer click in the Nearby Activity shows description as Unknown which is pretty confusing, We should probably change it to something else. Suggestions are welcome :-)

![WhatsApp Image 2024-04-14 at 11 38 03_c902a97b](https://github.com/commons-app/apps-android-commons/assets/114223204/3c65202a-5f3c-49be-96a7-42a9fca7c51a)

**Comment by RitikaPahwa4444** [comment]
Something like `No description available` would indeed provide more context about what we're trying to portray here.

**Comment by kanahia1** [comment]
Hey @RitikaPahwa4444, Description is hardcoded to null that's why it showing Unknown for every pointer. I am looking for suggestions to change the hardcoded string to something else.

https://github.com/commons-app/apps-android-commons/blob/8ce7485153c4e9b5aea6b07d582c683e2ca34861/app/src/main/java/fr/free/nrw/commons/nearby/fragments/NearbyParentFragment.java#L1803C5-L1814C10

**Comment by RitikaPahwa4444** [comment]
Got it, thanks for clarifying! I thought it's just happening for the cases when we don't have any description.

**Comment by nicolas-raoul** [comment]
I circled in red info that might be useful to display instead of "Unknown":

![Screenshot_20240416-162416.png](https://github.com/commons-app/apps-android-commons/assets/99590/ce8d55a6-7773-4daf-8680-e890f596d136)

How about the bottom one? (Wikidata description)

**Comment by kanahia1** [comment]
Wikidata description seems great 👍 I will share a Pull Request asap
