### ISSUE TITLE
Nearby: Pins overlapping place name 

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#5692]
Place name should appear above the pins, not under:

![Screenshot_20240415-101208.png](https://github.com/commons-app/apps-android-commons/assets/99590/09701136-aeef-4dd5-b237-39ea3db7ba74)

**Comment by mnalis** [comment]
As a little bit of _"Where's Waldo?"_ in the picture above, I've found one :smile: - just a tiny bit North-West of GPS location (blue circle), there seems to be **one** pin that is actually rendered  **below** the green box with place name (so only lower half of the pin is visible) - all the other pins indeed seem to be **above** it as the bug report describes.

Might perhaps indicate that the pin priorities are not all the same? (Or indicate some other, perhaps unrelated, issue with the rendering library)
