### ISSUE TITLE
Profile is not working

### ISSUE THREAD

**Issue by kemel49** [commons-app/apps-android-commons#5703]
### Description

<!DOCTYPE html>
<html>
<body>
<p>I am not able to see my profile section and achivements in common mobile app.Even thou I can open profile of others from leaderboard but not able to open mine.
</p>
</body>
</html>

**Comment by RitikaPahwa4444** [comment]
Hi @kemel49, are you running v4.2.1 available on the playstore? Is [this](https://github.com/commons-app/apps-android-commons/issues/5528#issuecomment-2019362355) report similar? The issue has been fixed and the team is planning a release soon. :)

**Comment by kemel49** [comment]
@RitikaPahwa4444   Yes I am using the v4.2.1 from Play Store.and my issue is same also like [this](https://github.com/commons-app/apps-android-commons/issues/5528#issuecomment-2019362355) one.

**Comment by sivaraam** [comment]
This should be fixed with the v5.0.1 that has just been released to Play store (beta). It should be live in production once the testing phase goes on successfully.

Closing this issue for now. Feel free to reopen if v5.0.1 does not fix this for you.
