### ISSUE TITLE
App should provide some feedback (spinner) while waiting for data to load

### ISSUE THREAD

**Issue by mnalis** [commons-app/apps-android-commons#5714]
### Feedback

Here is example, look e.g. at `00:00:06` there is missing picture and no indication that app is loading it, and it is isn't until `00:00:15` (and that is on the fast wifi!) until picture is loaded and the user is left wondering in the meantime what is happening.

https://github.com/commons-app/apps-android-commons/assets/156656/949ce642-17f8-4fce-b199-b1be464b0a41

Another situation is e.g. waiting for categories (see https://github.com/commons-app/apps-android-commons/issues/5316)

In general, procedure when app tries to do some user-initiated (i.e. UI thread) potentially-time-consuming-task (e.g. network-oriented) should be:
- show the _"loading..."_ spinner image (nicer if animated, but not a requirement, can be simple _"Please wait..."_ text on the middle of the screen too)
- start the (network, or other potentially time consuming) task
- wait for task to finish
- remove the spinner

### Wiki username

Mnalis

### Device name

Samsung Galaxy S23+

### Android version

Android 14 (OneUI 6.1)

### Commons app version

5.0.1~af028cbdd (latest F-droid)

**Comment by vtalos** [comment]
I would like to work on this with @karyotakisg. Could we get assigned?

**Comment by nicolas-raoul** [comment]
@vtalos @karyotakisg It is yours, thanks! :-)
