### ISSUE TITLE
Peer review: both Yes and No disabled

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#5718]
happens rarely

![Screenshot_20240509-102431.png](https://github.com/commons-app/apps-android-commons/assets/99590/66044d5f-1bb5-4904-91df-2006702d0bad)

**Comment by RitikaPahwa4444** [comment]
Is this similar to #4898?

**Comment by nicolas-raoul** [comment]
Ah yes thanks! 🙂
