### ISSUE TITLE
[Bug]: Editing depicts clears every other structured data associated with the image

### ISSUE THREAD

**Issue by sivaraam** [commons-app/apps-android-commons#5728]
### Summary

Our editing of depicts seems to cause a bit more harm than good now. When trying to edit the depictions, the depictions are changed but all other structured data associated with the image such as the "caption", "creator" etc. are totally removed. We should make sure such a thing doesn't happen.

Sample edits that demonstrate this issue: [[edit 1](https://commons.wikimedia.org/w/index.php?title=File:Paraglide_and_Cesta_tower_-_San_Marino_-_GT_06_-_2024_04_30.jpg&diff=prev&oldid=875938326)] [[edit 2](https://commons.wikimedia.org/w/index.php?title=File:Feria_del_Libro_2023_de_Aguascalientes_en_la_Casa_de_la_Cultura_48.jpg&diff=prev&oldid=876003593)]

This one feels a bit serious and it is not even easy to revert such edits due to some abuse filter blocking such reverts [[ref](https://commons.wikimedia.org/wiki/Commons_talk:Abuse_filter#c-Kaartic-20240512140600-Report_by_Kaartic)]. Can we just disable editing of depictions as a temporary measure until this one's fixed? If trivial, it would be great to just fix the core issue, of course 🙂 

### Steps to reproduce

1. Login to the app
2. Open an already uploaded image
3. Try to edit the depiction for the image
4. Check the edit history of that image on the website

### Expected behaviour

Only the list of depictions of the structured data get modified as a consequence of the edit.

### Actual behaviour

The edit results in all other structured data associated with the image being removed and only the new set of depicts being retained.

### Device name

OnePlus Nord

### Android version

12

### Commons app version

5.0.1

### Would you like to work on the issue?

None

**Comment by rohit9625** [comment]
How long has this problem been here? Can I get any class reference to the related code?

**Comment by sivaraam** [comment]
This might be a good place to start: https://github.com/commons-app/apps-android-commons/blob/main/app/src/main/java/fr/free/nrw/commons/wikidata/WikidataEditService.java#L108

**Comment by sivaraam** [comment]
The clear=1 in [the linked line](https://github.com/commons-app/apps-android-commons/blame/main/app/src/main/java/fr/free/nrw/commons/upload/WikiBaseInterface.kt#L37) looks suspicious. It's worth exploring if toggling that helps.
Ref: https://www.wikidata.org/w/api.php?action=help&modules=wbeditentity

**Comment by rohit9625** [comment]
Yes, you're right. This request is being sent to the server when updating depicts:
![image](https://github.com/commons-app/apps-android-commons/assets/101377978/411e57c0-ce89-41d3-a926-4ed5460cb85e)

As referenced, when the clear flag is set, i.e., 1 or true, it clears the entity which is shown here in the history:
![image](https://github.com/commons-app/apps-android-commons/assets/101377978/0029c99e-477a-4768-90c9-467bf121cae4)

After deleting the `clear=1` the entity is not considered to be cleared rather it changes the entity:
![image](https://github.com/commons-app/apps-android-commons/assets/101377978/a2580661-c1a9-40ba-a66b-d9f8ee2f44b6)


However, the depictions are passed by the Commons App, are appended to the previous ones even one depiction was already there. 
![image](https://github.com/commons-app/apps-android-commons/assets/101377978/bf846f57-8920-46ca-9213-bbb7efebe3d1)

**Comment by sivaraam** [comment]
> 
> After deleting the `clear=1` the entity is not considered to be cleared rather it changes the entity:
> 

Ah. That's an interesting observation.

> However, the depictions are passed by the Commons App, are appended to the previous ones even one depiction was already there.

Got it. So, it seems like the `clear=1` was there for a reason. But at least are the other structured data information retained when the clear is dropped? If so, we could explore other possible parameters / endpoints that'll help us ensure only a specific property is cleared.

**Comment by rohit9625** [comment]
Yes, the other data information is retained. One more thing I noticed in the docs, i.e., the clear flag should be set like `clear=true` but in our codebase, it was `clear=1`. Well, it is the same thing in computers but does the API know that?

**Comment by sivaraam** [comment]
> Yes, the other data information is retained. One more thing I noticed in the docs, i.e., the clear flag should be set like `clear=true` but in our codebase, it was `clear=1`. Well, it is the same thing in computers but does the API know that?

I don't think we have to worry about that discrepancy since the clearing was happening without any doubt. The examples in `wbeditentity` API page showcase how the `data` could be tweaked to remove something. It would be worth exploring it to see of we could tweak the structure of the `data` parameter we send such only the depictions are cleared/updated with the new ones.

**Comment by rohit9625** [comment]
We have to pass the whole structured data so that the entity gets updated with previous data as well as edited data. Currently, we are passing only depicted item's IDs, that's why only that gets updated and other data is cleared out due to a clear flag.

**Comment by rohit9625** [comment]
@sivaraam 
The bots keep adding the structured data even if it was completely deleted by our application. So, is this a feature or was it always like this?

**Comment by sivaraam** [comment]
> @sivaraam The bots keep adding the structured data even if it was completely deleted by our application. So, is this a feature or was it always like this?

Yeah. Those are friendly bots that run in Commons just doing their job. No issues about that :-)

**Comment by sivaraam** [comment]
> What are your thoughts about this?

You are confusing category edit and depictions edit. Both are different and even use different APIs. Categories exist in commons. Depictions has to do with structured data. You could check [this article](https://commons.m.wikimedia.org/wiki/Commons:Structured_data) for reference.

Hope that clears your confusion.

**Comment by rohit9625** [comment]
Hello Sivaraam,

I want to read about these terms(like mainsnak and snaktype) shown in the screenshot. I found another action that can help with the desired behaviour but I am unsure about the parameters.
![image](https://github.com/commons-app/apps-android-commons/assets/101377978/6668b17d-cc13-4080-9280-c6deee3e7664)

**Comment by rohit9625** [comment]
Hey @sivaraam, I solved the issue but, the whole task is being done on two phases:-
1. Deleting all depictions
2. Updating depictions with the new data.

See [history](https://commons.wikimedia.org/w/index.php?title=File:A_phone_holder.jpg&action=history)

Although, after so much research and debugging the second way I can see is, set clear flag, it'll delete the whole entity and then send updated depictions along with other related data that was deleted.

I hope I was helpful :)
