### ISSUE TITLE
[Bug]: Voice input text vanishes in alternate inputs

### ISSUE THREAD

**Issue by sivaraam** [commons-app/apps-android-commons#5729]
### Summary

When I enter the caption followed by the description using voice input, both of the fields seem to disappear. I don't think we clear the text as a subsequent voice input brings both of them back. For some strange reason they just vanish in alternate turns.

### Steps to reproduce

1. Initiate an upload using the app
2. Use voice input to enter the caption
3. Use voice input to enter a description

### Expected behaviour

Both of the voice inputs should be shown so that the user could see what they've entered

### Actual behaviour

Both caption and description seem to vanish together when we use the voice input feature twice (or any multiple of 2 for that matter).

### Device name

OnePlus Nord

### Android version

12

### Commons app version

5.0.1

### Screen-shots

Check this recording: https://drive.google.com/file/d/1U2gEafHbvf7urnO306gLxqFmEoNMTAxz/view?usp=drive_link

### Would you like to work on the issue?

Prefer not

**Comment by vtalos** [comment]
I can fix this with @karyotakisg.
