### ISSUE TITLE
[Bug]: „Allow only 1 picture to be selected by System Picker through Nearby“ can be bypassed

### ISSUE THREAD

**Issue by OpenGreenStreet** [commons-app/apps-android-commons#5733]
### Summary

„Allow only 1 picture to be selected by System Picker through Nearby“ can be bypassed

### Steps to reproduce

I will upload corresponding screenshots 

### Expected behaviour

Allow only 1 picture to be selected by System Picker through Nearby

### Actual behaviour

„Allow only 1 picture to be selected by System Picker through Nearby“ can be bypassed

### Device name

Google Pixel 7 Pro

### Android version

Android 14

### Commons app version

5.0.1~da0b2c28e

### Would you like to work on the issue?

None

**Comment by OpenGreenStreet** [comment]
![Screenshot_20240520-065330~2](https://github.com/commons-app/apps-android-commons/assets/76477269/10fbb8fe-1c35-4610-a77c-a32d7e869425)
![Screenshot_20240520-065141](https://github.com/commons-app/apps-android-commons/assets/76477269/4f703420-faee-4e83-b699-2f002ad0d7b1)
![Screenshot_20240520-065217](https://github.com/commons-app/apps-android-commons/assets/76477269/40ee8836-097f-4c02-9d1a-6967bff872e7)

**Comment by OpenGreenStreet** [comment]
See also:

* https://commons.wikimedia.org/wiki/Commons:Mobile_app/Feedback?markasread=72272510&markasreadwiki=commonswiki#Feedback_from_Molgreen_for_version_5.0.1~da0b2c28e

* „Nearby -> System picker: Only allow 1 picture to be selected #5677“

* „Allow only 1 picture to be selected by System Picker through Nearby #5680“

**Comment by nicolas-raoul** [comment]
I think this is the same as https://github.com/commons-app/apps-android-commons/issues/5674 no? :-)

**Comment by sivaraam** [comment]
Nope. I think the description may cause confusion as to this issue being a duplicate of #5674. The reality is not it is not. The source of this issue is [this feedback](https://commons.wikimedia.org/wiki/Commons:Mobile_app/Feedback#c-Molgreen-20240510123000-Feedback_from_Molgreen_for_version_5.0.1~da0b2c28e). Here's the translation of the same:

> Unlike before, you can no longer select multiple images for “nearby”. Is it wanted like that?

So, @OpenGreenStreet has opened this issue asking to make it optionally possible to upload multiple pictures via Nearby normal picker (and ensure the same for custom picker too).

**Comment by sivaraam** [comment]
Rather tha limiting uploads to 1 image. We could consider asking user to choose one image for the P18 property.for the rwst we could just associate the depicts as mentioned [here](https://github.com/commons-app/apps-android-commons/issues/5674#issuecomment-2028082972).
