### ISSUE TITLE
[Bug]: No feedback possible

### ISSUE THREAD

**Issue by OpenGreenStreet** [commons-app/apps-android-commons#5737]
### Summary

I have tried several times to send feedback via the app. The app keeps crashing

### Steps to reproduce

I type in the feedback and tap send, then the app crashes and wants to send an email

### Expected behaviour

I can send feedback via the app

### Actual behaviour

The app keeps crashing

### Device name

Google Pixel 7 Pro

### Android version

14

### Commons app version

5.0.1~da0b2c28e

### Would you like to work on the issue?

None

**Comment by nicolas-raoul** [comment]
@sivaraam I would say that's high priority, as it might prevent us from knowing about other problems (and it loses the user's input).

**Comment by OpenGreenStreet** [comment]
@nicolas-raoul Thanks: see "fr.free.nrw.commons Crash Report": via e-mail: 20.05.2024 - 14:56

**Comment by OpenGreenStreet** [comment]
![Screenshot_20240520-155922](https://github.com/commons-app/apps-android-commons/assets/76477269/783122a9-2187-45fd-86d5-da67add84d31)
![Screenshot_20240520-155935](https://github.com/commons-app/apps-android-commons/assets/76477269/546078a9-cc61-46bb-99b9-c6b467a99e71)
![Screenshot_20240520-155955](https://github.com/commons-app/apps-android-commons/assets/76477269/50700dd6-443e-4684-9e91-686c87040da3)
![Screenshot_20240520-160010](https://github.com/commons-app/apps-android-commons/assets/76477269/7bfcace2-114d-48cc-a49f-577ae8160356)

**Comment by sivaraam** [comment]
> @sivaraam I would say that's high priority, as it might prevent us from knowing about other problems (and it loses the user's input).

Makes sense but it actually works fone for me. There are also a few other feedback entries reportrd for v5.0.1. So, I don't think it's completely broken.

**Comment by sivaraam** [comment]
> @nicolas-raoul Thanks: see "fr.free.nrw.commons Crash Report": via e-mail: 20.05.2024 - 14:56

Thanks. The logs seem to mention that you're somehow in a logged out state. Are you able to upload images without issues? Did you possibly change your password of late?

**Comment by OpenGreenStreet** [comment]
![Screenshot_20240522-063727](https://github.com/commons-app/apps-android-commons/assets/76477269/50112481-3a41-4eb3-8f49-d91df5bdeae6)
![Screenshot_20240522-063709](https://github.com/commons-app/apps-android-commons/assets/76477269/91862a54-0f36-492b-8338-39a5ca4b982f)
![Screenshot_20240522-063651](https://github.com/commons-app/apps-android-commons/assets/76477269/849ea027-b844-4724-93df-ffd3b5c499fb)

**Comment by OpenGreenStreet** [comment]
Yes, I can upload (without logging in again)

**Comment by OpenGreenStreet** [comment]
I have not changed my password since the last time I successfully posted feedback

**Comment by OpenGreenStreet** [comment]
@sivaraam 
I was just able to send feedback without logging out and logging in again
I have no idea what is different now
