### ISSUE TITLE
[Bug]: Colors of existing / not existing pins are very similar

### ISSUE THREAD

**Issue by JAnDud** [commons-app/apps-android-commons#5742]
### Summary

In previous version there were green pins for objects with photo and blue ones for items without photo.
![image](https://github.com/commons-app/apps-android-commons/assets/19319822/a3415b3c-ffdf-46c6-a512-51aea28fe9fe)

In 5.0.1 are both colors almost similar and harder to recognize
![image](https://github.com/commons-app/apps-android-commons/assets/19319822/029a63dc-fbc6-428f-915b-3be5d60a067c)

### Steps to reproduce

use app map

### Expected behaviour

colors should be more different / customizable

### Actual behaviour

colors are very similar and only dot in the middle can help

### Device name

Motorola

### Android version

Android 45

### Commons app version

5.0.1

### Would you like to work on the issue?

None

**Comment by rohit9625** [comment]
We changed the blue color to this new one for better visibility because that dark blue was hardly visible on the dark theme.

Now, it seems like we should choose another color or some other shades of blue to improve visibility on the dark theme.

**Comment by nicolas-raoul** [comment]
How about having different pin colors for each theme?

**Comment by karyotakisg** [comment]
Can i work on it with @vtalos ?
