### ISSUE TITLE
Factorize methods addMarkerToMap and addMarkersToMap

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#5780]
The code of these two methods is very similar.

It looks like addMarkersToMap could be a loop calling addMarkerToMap.

In NearbyParentFragment.java

**Comment by ujjwal2900** [comment]
Hi I would like to work on this issue. Can you please assign it to me ?

**Comment by nicolas-raoul** [comment]
@ujjwal2900 It is yours, thanks! :-)

**Comment by ujjwal2900** [comment]
Hi @nicolas-raoul, I have changed the code for addMarkersToMap method and raised a PR. Can u please review it.

**Comment by nicolas-raoul** [comment]
Thanks @ujjwal2900 for fixing this! :-)
