### ISSUE TITLE
[Bug]: Uploading feedback via app does not work 2024-08-03

### ISSUE THREAD

**Issue by OpenGreenStreet** [commons-app/apps-android-commons#5781]
### Summary

App crashed

### Steps to reproduce

Try to send a feedback test

### Expected behaviour

Send feedback 

### Actual behaviour

The app crashes

### Device name

Google Pixel 7 pro

### Android version

Android 14 (July 2024)

### Commons app version

5.0.2~05ffd123e

### Device logs

See crash reports

### Would you like to work on the issue?

None

**Comment by OpenGreenStreet** [comment]
https://commons.wikimedia.org/wiki/Commons:Mobile_app/Feedback#Manual_feedback:_the_app_crashes_5.0.2~05ffd123e

**Comment by sivaraam** [comment]
Thanks for opening this issue @OpenGreenStreet . If I understand correctly. you are facing issues when submitting feedback from the app. Is that the case?

If so could you kindly point out the email address from which you submitted the crash report or the specific timestamp? I'm finding it difficult to locate your specific crash report amongst the others. It's fine if you could share the crash log in this issue too.

**Comment by OpenGreenStreet** [comment]
@sivaraam : 

* Gesendet: Samstag, 03. August 2024 um 05:58 Uhr
* Gesendet: Samstag, 03. August 2024 um 06:02 Uhr

see also wiki email

best wishes

**Comment by OpenGreenStreet** [comment]
@sivaraam Yes, it was exactly the same: I tried to send feedback as a test (after changing @Speravir ). Immediately after sending it, it crashed (I made two attempts).

**Comment by OpenGreenStreet** [comment]
@sivaraam I have just tested for the third time (18:20) and sent the log file shortly afterwards.

**Comment by sivaraam** [comment]
Thank you for your inputs. From the log, it seems like a problem with your login token. Did you happen to change the password recently? Also, are you unable to submit feedback alone or are you unable to upload images too?

**Comment by OpenGreenStreet** [comment]
@sivaraam 

My last password change was "some time" ago. Uploaded yesterday evening and this morning:

• https://commons.wikimedia.org/wiki/File:20240803_xl_1851-Ladestion_am_SOWI_in_Strausberg.jpg
• https://commons.wikimedia.org/wiki/File:20240803_xl_1909-Dr._Gertrud_Rossner_Haus_in_Strausberg.jpg

**Comment by sivaraam** [comment]
It's strange that you are able to upload but you face a problem when trying to submit feedback. 🤔

**Comment by sivaraam** [comment]
Kindly observe and let us know if you happen to notice such a crash or odd behaviour when doing other operations in the app.

**Comment by OpenGreenStreet** [comment]
Thanks, I'll let you know if I notice anything

**Comment by sivaraam** [comment]
@OpenGreenStreet I'm closing this issue for now. Feel free to reopen if you face this issue again.

**Comment by OpenGreenStreet** [comment]
@sivaraam 
I'm sorry, I've just tested it on two different smartphones. Both came up with the message: “Oops, something went wrong.”

**Comment by nicolas-raoul** [comment]
@OpenGreenStreet With what version of the app?

**Comment by OpenGreenStreet** [comment]
5.1.0~707997bd1
5.2.0~05ffd123e

**Comment by OpenGreenStreet** [comment]
See Crash Reports
