### ISSUE TITLE
Remove deprecated circular progress bar

### ISSUE THREAD

**Issue by rohit9625** [commons-app/apps-android-commons#5787]
### Summary

Recently I tried to build the app after a while and the build was failing while downloading `implementation 'com.dinuscxj:circleprogressbar:1.1.1'` dependency.
The library is shut down as discussed [here](https://github.com/commons-app/apps-android-commons/issues/5770#issuecomment-2303980998) and we need to replace this progress bar with a new one.
Two files use this progress bar, i.e., `activity_quiz_result.xml` and `fragment_achievements.xml`

### Steps to reproduce

Just start fresh by cloning and opening the repo into Android Studio and building the project.

### Expected behaviour

None

### Actual behaviour

None

### Android version

Android 14

### Commons app version

main and betaDebug

### Would you like to work on the issue?

None

**Comment by nicolas-raoul** [comment]
The UI using CircleProgressBar will hopefully be revamped soon, so a temporary fix/hack is OK for that library.

The GSoC branch has one.

**Comment by rohit9625** [comment]
What about commenting out the usage and dependency for now?
