### ISSUE TITLE
Unit test broken: WikidataEditServiceTest.testUpdateDepictsProperty

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#5793]
```
fr.free.nrw.commons.wikidata.WikidataEditServiceTest > testUpdateDepictsProperty FAILED
    java.lang.NullPointerException at WikidataEditServiceTest.kt:59
```

**Comment by nicolas-raoul** [comment]
Great thanks! :-)

**Comment by rohit9625** [comment]
The test has been fixed now. What about I create a PR with this fix including circular progress indicator? I'll do that by cherry-picking the commit from that branch `upgrade` branch and committing it to the main branch. 

To prevent multiple writes, I have to revert the [commit](https://github.com/commons-app/apps-android-commons/pull/5790/commits/2223e6de3e679487d42b1668018fa9c02dc4bfff). What would be the best approach?

**Comment by nicolas-raoul** [comment]
Sure, feel free to cherry-pick. :-)
