### ISSUE TITLE
Nearby: "Refresh" button to clear the cache and reload the Nearby map

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#5806]
It would be good to have a "Refresh" icon button in the title bar of Nearby.
Tapping on it would:

1. Empty the Nearby local cache. Context: Pins are saved in a cache so that Nearby loads faster. Even if another user adds a picture for that pin, the pin does not change color.
2. Reload the Nearby map. It would not strictly necessary if all things were perfect, but Nearby is a fast-moving feature which often (always?) has some bugs, so I very often find myself restarting the app just to reload this map (for instance because the blue dot does not follow me).

**Comment by OpenGreenStreet** [comment]
From my point of view, this function would be extremely helpful in many cases

**Comment by noahvendrig** [comment]
Hi, I'm looking to solve this issue. Could you please assign me?

**Comment by kanahia1** [comment]
Hi @noahvendrig, I had worked on the implementation of the caching, incase you need any help/information to it you can message me on the Zulip :)

**Comment by OpenGreenStreet** [comment]
Thank you for the implementation. I am looking forward to the implementation . . .
When and with which version number will this be published?
