### ISSUE TITLE
Commons app option: switch off dark mode in the commons app, but leave dark mode active for the smartphone (in general)

### ISSUE THREAD

**Issue by OpenGreenStreet** [commons-app/apps-android-commons#5813]
### What is the user problem or growth opportunity you want to see solved?

I have activated dark mode on my smartphone. (Among other things to reduce the power consumption of my smartphone).

However, the display of maps (“nearby”) is not easily recognizable for me in the commons app in dark mode.

That's why I would like a commons app option to change color schemes in the commons app. I would like to switch off the dark mode in the commons app. However, dark mode should remain active for the smartphone in general.

### How do you know that this problem exists today? Why is this important?

the display of maps (“nearby”) is not easily recognizable for me in the commons app in dark mode.

### Who will benefit from it?

All users who have activated dark mode on their smartphone

**Comment by nicolas-raoul** [comment]
Have you tried Settings>Theme ?

**Comment by OpenGreenStreet** [comment]
@nicolas-raoul Oh no, thank you! You can close the ticket...
