### ISSUE TITLE
Rotated pictures shown as failed to upload, actually uploaded successfully

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#5814]
Steps to reproduce:

1. Select a picture for upload (see for instance the blue dress in the screenshots below).
2. Within the app's Upload Wizard, rotate the picture.
3. Submit the upload.
4. Problem 1: Notice that in "Pending uploads" the picture has no label.

![Screenshot_20240903-201741.png](https://github.com/user-attachments/assets/9ce51b0b-a6cc-4a06-96e6-bbdf54d32607)

5. Problem 2: The upload is shown as failed:

![Screenshot_20240904-204234.png](https://github.com/user-attachments/assets/6af8448c-4a69-436e-9e25-18817a64e7d2)

Actually, the picture has been uploaded successfully, moreover correctly rotated:

![Screenshot_20240904-204605.png](https://github.com/user-attachments/assets/60ef8b28-a024-4d0f-bbc3-8af2c5768b83)

It can also be seen as a duplicate entry in the app's contributions list, with incorrect rotation.

**Comment by QUIETTTTTTTTTT** [comment]
Can I get assigned to this bug? Expected to complete the repair within two days

**Comment by nicolas-raoul** [comment]
@QUIETTTTTTTTTT Fantastic, it is yours! :-)

**Comment by QUIETTTTTTTTTT** [comment]
Fixed.

**Comment by nicolas-raoul** [comment]
Actually I am not able to reproduce this on the main branch. I tried 1-pic upload, and a 5-pics upload including 2 rotations and 3 non-rotations.

I will close for now, but if anyone can reproduce the issue please comment here, thanks!

**Comment by nicolas-raoul** [comment]
Last week I again successfully uploaded with rotation.
