### ISSUE TITLE
Pins as “temporary personal pins” (up to 15 pieces) (marker/favorite) 

### ISSUE THREAD

**Issue by OpenGreenStreet** [commons-app/apps-android-commons#5816]
### What is the user problem or growth opportunity you want to see solved?

If I'm looking for a photo (“nearby”), I usually take it once or twice.

I then look at the photos at home, edit them if necessary and upload them at my leisure.

### How do you know that this problem exists today? Why is this important?

Unfortunately, it has often happened to me that I have then been unable to find pins again: either I have not been able to find the location or the Pin was - for whatever reason - no longer displayed. (That was annoying).

So my suggestion: if I have taken a picture of a Pin on site, I mark the pin as a “temporary personal pin” (the name, location and time are also saved)

Once I have selected and edited the right picture at home, I can then upload it via the “temporary personal pin” - assuming nobody else has done it in the meantime.

### Who will benefit from it?

All users

**Comment by OpenGreenStreet** [comment]
@nicolas-raoul ,
Good morning and thank you very much, yes that's exactly it.

**Comment by OpenGreenStreet** [comment]
@nicolas-raoul ,

Something else occurs to me: is it/would it be possible to manually add the time of my own recording as a note in the favorites.

**Comment by nicolas-raoul** [comment]
Good idea, could you create a new enhancement request about this?
