### ISSUE TITLE
Independence of the category search from capitalization

### ISSUE THREAD

**Issue by OpenGreenStreet** [commons-app/apps-android-commons#5820]
### What is the user problem or growth opportunity you want to see solved?

If I search in the Commons app without regard to capitalization, the category I am looking for is not found.

### How do you know that this problem exists today? Why is this important?

It would be nice if category searches were not (!) case-sensitive.

### Who will benefit from it?

all users

### Anything else you would like to add?

* https://commons.wikimedia.org/wiki/File:20240906_xl_2025-Commons_Android_App_screenshots,_Case-sensitive_search_for_Commons_categories.png
* https://commons.wikimedia.org/wiki/File:20240906_xl_2025-Commons_Android_App_screenshots,_Case-sensitive_search_for_Commons_categories_2.png

**Comment by nicolas-raoul** [comment]
See https://github.com/commons-app/apps-android-commons/issues/3179 :-)
