### ISSUE TITLE
When coming from nearby banner, Nearby pin details of other pins get modified

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#5827]
Step 1: Wait for Nearby notification banner to appear (you have to be near a Wikidata item with no picture, use FakeGPS app if needed).

![Screenshot_20240913-115650~2.png](https://github.com/user-attachments/assets/de8a3925-093c-44b4-8013-a7305045ab03)

Step 2: Tap that banner. You are lead to the Nearby activity where the element's pin appears in purple.

Step 3: Tap any other pin. Its details appear: 

![Screenshot_20240913-121821.png](https://github.com/user-attachments/assets/8a0147e1-8665-448b-8fb9-d772e088e250)

Problem: After a few seconds, the details get replaced with the details of the notification's element.

Screencast showing all steps:

https://github.com/user-attachments/assets/bcf0b58b-7744-4131-9a27-047592b16b97

I guess it is because of the new way to load pins (turning them from grey to red/green) little by little rather than in one go. This happened to me with a WLM pin but I don't think WLM is a root cause.

**Comment by ErenratZeng** [comment]
That's weird, I was following up your step, but I did not implement the bug. Using **Galaxy S20 Android 13**

**Comment by ErenratZeng** [comment]
Oh, I should put myself into as much as pins. I Implement that. I think it might be some memory issue or internet issue. Caz when u on a small number of pins, this issue will not happen.

**Comment by nicolas-raoul** [comment]
I just tried at another place and indeed no problem there...

If anyone can reproduce reliably, please let us know, thanks!

**Comment by rohit9625** [comment]
I can reproduce this issue consistently. Looking for a fix. Please assign me.

**Comment by rohit9625** [comment]
Someone wrote this comment, that says it should highlight the nearest place when we arrive on the `Nearby` screen through the banner. Is this a bug or a feature?
![image](https://github.com/user-attachments/assets/befa9b80-1769-4938-89ff-fa8e2f9dc6d8)

**Comment by rohit9625** [comment]
I tried the steps you mentioned and found that the details of the bottom card are only replaced by the notification element when I move the screen a little bit. This means the map refreshes and then details get updated.
