### ISSUE TITLE
refactoring opportunity - duplicated code

### ISSUE THREAD

**Issue by tristan81** [commons-app/apps-android-commons#5836]
Duplicated onscroll event code for Nearby and Explore map viewers, could be refactored to remove duplication.

**ExploreMapFragment**
<img width="641" alt="image" src="https://github.com/user-attachments/assets/d92f2cc3-c49a-4750-a01d-ae4b41ce549a">

**NearbyParentFragment**
<img width="622" alt="image" src="https://github.com/user-attachments/assets/f4ff9ef3-9290-4c48-88f4-540a990ebff0">

**Comment by RitikaPahwa4444** [comment]
Thanks for spotting this! Linking an older issue for anyone planning to take this one up as previous attempts to remove redundant code didn't turn out as intended: https://github.com/commons-app/apps-android-commons/issues/5256.

**Comment by tristan81** [comment]
the code between Explore and Nearby has diverged now so the duplicate code displayed no longer exists

**Comment by nicolas-raoul** [comment]
@tristan81 has the code diverged recently? If the changes can benefit both nearby and explore, then it would still make sense to de-duplicate. 🙂

**Comment by tristan81** [comment]
The changes to refresh Nearby OnScroll without any distance thresholds mean this example of duplication no longer exists in the code.

**Comment by nicolas-raoul** [comment]
The changes to refresh Nearby OnScroll without any distance thresholds, should ideally be implemented in all maps of the app.

Deduplicating would allow all maps to benefit from such improvements. 🙂
