### ISSUE TITLE
Custom picker shows only first image after entering then leaving fullscreen

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#5840]
With `Show actioned pictures` disabled.

https://github.com/user-attachments/assets/01590dd6-395b-4d90-ae6c-8bc9d729acd5

**Comment by LachlanMajor** [comment]
Can I please be assigned this issue.

**Comment by nicolas-raoul** [comment]
Actually, somehow in main I do not this issue anymore. Even when using a commit from when I created this issue, so it is not a change in the code, rather it is probably a change in the number and state of my pictures and uploads.

Anyhow, I still observe a problem, which I unfortunately also observe using the branch of LachlanMajor's pull request above. The problem I see now is that after entering then leaving fullscreen, I am scrolled to a different place in my roll of pictures:
