### ISSUE TITLE
[Bug]: The app does not show categories in the search results

### ISSUE THREAD

**Issue by prototyperspective** [commons-app/apps-android-commons#5844]
### Summary

One can't view categories in the app. When entering something in the search like "cosmology" and then going to the categories tab the page is blank.

Likewise, when opening a category from a file page by taping onto one of its categories and then going to the subcategories tab the page is also blank (same for parent categories).

Categories are very useful and a main point of the platform as this enables you to browse the site and or search the well-organized for files about something in particular.

### Steps to reproduce

1. Have the app open and tap onto the search
2. Entering something like "cosmology"
3. Open the categories page

### Expected behaviour

 It should show the category of the same name as well similar named categories (like on the website).

### Actual behaviour

It shows a blank page

### Android version

Android 11

### Commons app version

5.0.2

### Would you like to work on the issue?

Prefer not

**Comment by nicolas-raoul** [comment]
Seems fixed in the main branch:

![Screenshot_20241001-175245.png](https://github.com/user-attachments/assets/b6897261-2f24-440a-afd5-d8d45038fbc8)

I will close for now, but if that still happens in the next release please let us know! 🙂

**Comment by prototyperspective** [comment]
@nicolas-raoul Great to hear but it's still not working in the app because there hasn't been a new release – when is the next release going to be deployed? I think this is a major bug fix that should be fixed in the app asap and it's apparently over 30 days now since this has been fixed without the fix being available.
