### ISSUE TITLE
After uploading via Nearby, I am sent back to Nearby, where I am mislead into thinking that I must upload again

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#5846]
I see three possible solutions, in order from best to less ideal:
1. Remove the pin.
2. Mark the pin as being uploaded currently.
3. Direct the user to the Uploads activity.

Feel free to propose other solutions. 🙂

https://github.com/user-attachments/assets/17d10144-20dc-44c4-b738-e5f64a64a51a

**Comment by whe128** [comment]
I would like to take this issue, could you please assign this to me?

**Comment by ErenratZeng** [comment]
I think after you upload a picture, there will be a progress bar pop-up on notification showing in progress

**Comment by whe128** [comment]
I have finished this issue, I chose the third approach:
go to the upload activity after successful submit.

https://github.com/user-attachments/assets/376ef05c-c1af-495d-8340-5501dae37f9b

**Comment by whe128** [comment]
why not use approach 1 and 2, because there are two place that can submit the photo, [**contribution fragment**] [**nearby fragment**]
in the **contribution fragment**, there is no pin to remove or mark down.
![contributionSubmit](https://github.com/user-attachments/assets/5cd7a29b-90b0-4c9f-bd4c-b2fc52a86672)

**Comment by whe128** [comment]
why not use approach 1 and 2, because there are two place that can submit the photo, [contribution fragment] [nearby fragment].
In the contribution fragment, there is no pin to remove or mark down.
![contributionSubmit](https://github.com/user-attachments/assets/9fdc8bd9-2f0b-400a-8bf3-c192b71af29c)
![pinSubmit](https://github.com/user-attachments/assets/7b534db5-63da-422d-a8f9-75c03ed8a4b3)

**Comment by whe128** [comment]
on the previouse state, when we submit from the contribution fragment, we just return to the contribution fragment, also don't clear whether the submission is successful or not.
https://github.com/user-attachments/assets/93123fb4-eb68-4002-9db6-bb7d3b9b7c1b

**Comment by whe128** [comment]
on the previouse state, when we submit from the contribution fragment, we just return to the contribution fragment, also don't clear whether the submission is successful or not.
https://github.com/user-attachments/assets/4d5c8cf2-a0cd-44e9-9c41-2fc52544aab0

**Comment by nicolas-raoul** [comment]
> I have finished this issue, I chose the third approach: go to the upload activity after successful submit.

That screencast looks good :-)

**Comment by whe128** [comment]
hello sorry to bother you , I accident click the button of "**unassigned me"** and loss the assigned role of this issue, could you **assign the issue to me again**. 
This is our school assignment, I sincerely ask you to help me.
Thank you !

by the way, I have made the **pull request,** you can review the code in the PR.
![image](https://github.com/user-attachments/assets/f48f2eef-3d55-4d48-bdd6-a04029068c0a)

**Comment by whe128** [comment]
Hello, nicolas, 
I want to ask whether my pull request process is correct or not, 
I created the PR, and found that the PR has no linked issue, 

And what should I do or I just wait for merge.
This is the Pull request link:
https://github.com/commons-app/apps-android-commons/pull/5874

**Comment by whe128** [comment]
> Hello, nicolas, I want to ask whether my pull request process is correct or not, I created the PR, and found that the PR has no linked issue,
> 
> And what should I do or I just wait for merge. This is the Pull request link: #5874

Solved: have linked the issue. PR process is fine.
