### ISSUE TITLE
Tapping a "... sent you an email" notification has no effect

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#5853]
Should open web browser on relevant URL.
Currently it just marks as read.

https://github.com/user-attachments/assets/50a641e7-2315-4e14-ac09-4665d31dd55d

**Comment by ErenratZeng** [comment]
Can I take this issue? But I wonder how can we send emails to another account.

**Comment by nicolas-raoul** [comment]
I just realized that on the Commons website clicking that notification does nothing either haha.
And there is no page showing received emails, users just have to check their real email mailbox.
So when tapped I suggest just showing this snack: `Check your email inbox.`

Here is how to send a message, you may need to create a second account to use it:
![Screenshot 2024-10-15 at 17 24 56](https://github.com/user-attachments/assets/e0181630-8be6-423f-8e81-e19953ffddf2)
