### ISSUE TITLE
SPARQL: Item label does not seem to follow configured language, "en" hard-coded

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#5855]
https://github.com/commons-app/apps-android-commons/blob/main/app/src/main/resources/queries/query_for_item.rq#L21

Problem: `"en"` is hard-coded for item label

Replacing with `"${LANG}"` might be enough to fix the issue.

**Comment by ChristoJobyAntony** [comment]
Could I have a go at this ?

**Comment by nicolas-raoul** [comment]
After replacing, please test with various languages and post screenshots showing Nearby with a famous Wikidata item selected, for instance https://www.wikidata.org/wiki/Q243

Thanks!

**Comment by ChristoJobyAntony** [comment]
I have been able to implement the required changes. But I would like to clarify the expected behaviour for testing.  My understanding of the test is  to select a famous Wikidata item in the nearby page and ensure that the tags with the native language is given preference. Is this correct ?

**Comment by ChristoJobyAntony** [comment]
Couple more tests were done with the Bust of Gustave Eiffel [link](https://www.wikidata.org/wiki/Q2928782), The langages tested were, French, Armenian, Arabic & Turkish. Before each screenshot was taken, language preference was updated and then the item was located in Nearby.

P.S: I tried real hard to locate and retrieve info about Eiffel Tower however, despite mocking the exact co-ordinates of its location, I was unable to locate / retrieve its details. 

<img src="https://github.com/user-attachments/assets/9814caee-c1b4-437f-a8d7-6b08f410717b"  width=200 />
<img src="https://github.com/user-attachments/assets/495c1a8c-2590-4134-b67f-35a8cf25123d"  width=200 />
<img src="https://github.com/user-attachments/assets/3609814b-e0ce-499e-b020-91b6f2fd4cad"  width=200 />
<img src="https://github.com/user-attachments/assets/3497e917-3e0d-4aba-964f-3484a7aa5651"  width=200 />

**Comment by nicolas-raoul** [comment]
Looks great!
Would you mind sending a pull request?
