### ISSUE TITLE
[Bug]: Unchanged / inconsistent username in different pages

### ISSUE THREAD

**Issue by TengyiZhang** [commons-app/apps-android-commons#5856]
### Summary

After changing the username, the user can see the changed name in contributions page.
However, in explore section, the username hasn't changed in their post.

For example, user changed the name from Haonan11123 to Haonan, which can be seen in contribution page.
![image](https://github.com/user-attachments/assets/a0cee1af-1534-48c4-b05c-8b1f6b594d98)

In explore page, the username was still Haonan11123
<img width="674" alt="image" src="https://github.com/user-attachments/assets/3da429e1-8e0b-43fc-b874-1fbcc25f658e">

https://github.com/user-attachments/assets/782fc81d-6602-4c56-a1e5-ee89ff7d3a6f

### Steps to reproduce

1. upload and post a picture
2. change the user name
3. set "use custom author name" in setting 
4. check username in explore page and contribution page

### Expected behaviour

When turning on the "use custom author name" button, we expected the **custom username** edited by user should be shown in every page. In other words, the username should be consistent.

### Actual behaviour

The username in explore page hasn't been changed.

### Android version

Android 12 

### Commons app version

5.0.2

### Would you like to work on the issue?

None

**Comment by nicolas-raoul** [comment]
Thanks for checking this! :-)

"use custom author name" is not retroactive.
It is meant to set the name for any future upload.

What happens if you do this?

1. Enable "use custom author name" in settings, enter a custom user name
2. upload and post a picture
3. check username in explore page and contribution page and https://commons.wikimedia.org

**Comment by TengyiZhang** [comment]
> Thanks for checking this! :-)
> 
> "use custom author name" is not retroactive. It is meant to set the name for any future upload.
> 
> What happens if you do this?
> 
> 1. Enable "use custom author name" in settings, enter a custom user name
> 2. upload and post a picture
> 3. check username in explore page and contribution page and https://commons.wikimedia.org

Thanks for your reply!

After a user changes their custom name and posts, the username for **the same post** appears **differently** on the explore and contributions pages. Should we expected the name to be the same on one post?

i.e.
<img width="1359" alt="image" src="https://github.com/user-attachments/assets/9e53dfb8-eafa-430f-bd98-e7a85b4c97e6">

**Comment by nicolas-raoul** [comment]
This screenshot was taken for a file uploaded **after** changing the username from Haonan11123 to Haonan, right?

If yes, then I guess Explore is faulty indeed.

**Comment by TengyiZhang** [comment]
> This screenshot was taken for a file uploaded **after** changing the username from Haonan11123 to Haonan, right?
> 
> If yes, then I guess Explore is faulty indeed.

Yes, this screenshot was taken after the username was changed from Haonan11123 to Haonan. So I agree that Explore is indeed faulty

**Comment by lzh12311** [comment]
Can I please be assigned this issue？

**Comment by nicolas-raoul** [comment]
@TengyiZhang I see you wrote `Would you like to work on the issue? None` so I assume this issue can be assigned to someone else. If not, please let us know withing an hour, thanks a lot!

@lzh12311 Feel free to start investigating, thanks! :-)

**Comment by TengyiZhang** [comment]
> @TengyiZhang I see you wrote `Would you like to work on the issue? None` so I assume this issue can be assigned to someone else. If not, please let us know withing an hour, thanks a lot!
> 
> @lzh12311 Feel free to start investigating, thanks! :-)

Thanks for telling me! I would appreciate if you could assign it to others :)
