### ISSUE TITLE
Automate UI testing with Espresso

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#586]
Would save time in the future if we could set up UI tests with Espresso: 

https://developer.android.com/training/testing/ui-testing/espresso-testing.html
https://google.github.io/android-testing-support-library/docs/espresso/index.html

**Comment by whym** [comment]
Like https://github.com/commons-app/apps-android-commons/blob/master/app/src/androidTest/java/fr/free/nrw/commons/SettingsActivityTest.java ?

I agree we want more of them to reduce the chance of regression and accidental breakage. Most Activities and Fragments are not covered yet - ShareActivity, NearbyActivity, etc.

**Comment by misaochan** [comment]
We probably need to whittle down the number of tasks remaining for the hackathon (since we only have 1.5 days left til the showcase on Sunday), so unless anyone wants to take this on personally, I'll remove the label.

**Comment by domdomegg** [comment]
There's now a fair few good espresso tests :tada:

Can always add more but there are other issues for that.
