### ISSUE TITLE
Custom selector showing actioned pictures: After entering then leaving fullscreen, scrolls to a different place

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#5873]
With `Show actioned pictures` enabled.

After entering then leaving fullscreen, I am scrolled to a different place in my roll of pictures:

https://github.com/user-attachments/assets/98574a21-3cc4-423f-8b66-46edb8ff688d

**Comment by whe128** [comment]
I have found the reason
1. 
![image](https://github.com/user-attachments/assets/03f1759d-6bfd-4543-8730-99716cfef389)
2.
![image](https://github.com/user-attachments/assets/b8b64264-1982-42d8-a0dd-738a2dd1abb5)

**Comment by whe128** [comment]
can you assign this issue to me?

**Comment by lzhan0121** [comment]
Can you reassign this issue to me? Me and whe128 are in the same team for fix issues.
