### ISSUE TITLE
"Read article" shows Wikidata page about the class, instead of page about the item itself

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#588]
For instance, here is the article that gets open when I click the point of the famous "SQUARE BUILDING" in Roppongi:

![screenshot_20170515-221656](https://cloud.githubusercontent.com/assets/99590/26059325/5a945fe6-39bc-11e7-9787-e1e354668c0a.png)

Instead, it should show https://www.wikidata.org/wiki/Q11311478

**Comment by maskaravivek** [comment]
@nicolas-raoul Am working on it. :)

**Comment by misaochan** [comment]
We are currently having "Read article" direct the user to the Wikipedia article, and then add an overflow button for the user to check out Wikidata. Not sure if this issue will still occur there ( @maskaravivek says he thinks it might be fixed), but at least it will be easier to debug/test.

**Comment by misaochan** [comment]
May I close?

**Comment by nicolas-raoul** [comment]
It is fixed, thanks :-)
