### ISSUE TITLE
Add `io.mockk` dependency for static/object mocking for testing of files written in kotlin

### ISSUE THREAD

**Issue by parneet-guraya** [commons-app/apps-android-commons#5886]
While working on a PR, I saw tests were failing, reason? I had converted a file to kotlin and a method that test invokes makes a call to a static method. When tests failed, turns out it couldn't mock the static method. Because `powermock` doesn't support mocking  kotlin objects. Now, I could have made a hacky solution by having a common interface and making both actual and test wrapper class implement it. So that, I can pass a stubbed method by overriding. But there is more than one place where we need static mocks.

For eg. `CommonsApplication.getInstance()`. Now, when testing we need to stub it. Currently we're using `powermock` to mock static methods and stub it. But this only works for `.java` files. If we convert `CommonsApplication.java` to kotlin the tests would fail because `powermock` cannot mock kotllin objects and in this case `getInstance` would be null leads failed tests.

Not for the purpose of solving just single issue that I'm working on but we will have other files converted to kotlin eventually anyways. We need to have a solution to mock kotlin objects. On my research I found this is the best we can have [mockk](https://github.com/mockk/mockk), supports mocking kotlin objects. It is fairly active and stable library. So, I propose adding it as a dependency. Mocking kotlin objects would be same as we are doing with `powermock`.

It takes `~400Kb` space when I analyzed the .apk , so size shouldn't be an issue.
![Screenshot from 2024-10-24 06-28-05](https://github.com/user-attachments/assets/c7a6a45b-5209-441c-9c93-a91fe1e4e65b)

Will appreciate any input :)

P.S: I also found out, it is discouraged to make static calls (for eg. a method making static call in it's impl.) but rather have something as a dependency so it gets easier to test. Otherwise it leads to tight coupling. Maybe we can also fix this in our testing impl, in future.

**Comment by parneet-guraya** [comment]
If it looks good, shall I work on it?

**Comment by nicolas-raoul** [comment]
Yes thanks! :-)
