### ISSUE TITLE
Use WMF map servers instead of Mapbox

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#590]
For privacy reasons.
Mapbox currently gets the user's IP address.

**Comment by maskaravivek** [comment]
@nicolas-raoul Can we have a bit more discussion on whether we want to move away from Mapbox. Wikipedia app also uses Mapbox.

**Comment by nicolas-raoul** [comment]
I am quite surprised that the Wikipedia app uses Mapbox.
Since I signed a contract with WMF about privacy for our users, I will ask the WMF and close this if using Mapbox is no problem.

**Comment by misaochan** [comment]
Sounds like everything is OK with Mapbox (until we reach 50,000 active users/mth anyway).

**Comment by nicolas-raoul** [comment]
A person from the WMF legal team just wrote this:

> the Wikipedia app doesn't use MapBox. The Android app uses maps.wikimedia.org, which runs a Wikimedia-made maps service called Kartographer (more info [here](https://www.mediawiki.org/wiki/Maps)), and the iOS app uses the device's built-in map.

So we should indeed do the same, because it is a privacy problem.
Or does anyone have a proof that the Wikipedia app in fact still uses MapBox?

**Comment by neslihanturan** [comment]
If there is a privacy problem, I think yes we should do. However, according to [here](https://gerrit.wikimedia.org/r/#/q/project:apps/android/wikipedia+mapbox) wikipedia app still uses mapbox. Am I missing something?

**Comment by misaochan** [comment]
I think Aeryn mentioned MapBox just to ensure that we include mention of it in our privacy policy? AFAIK he did not say we needed to switch to using something else.

If I recall correctly, when we first implemented the map of nearby places, we wrote to Legal and got their consent to use MapBox?

**Comment by misaochan** [comment]
Quoting @dbrant on this issue:

> - Our app uses Mapbox (the SDK) in the sense that we use it to render the map, the markers, the user's location, etc. on the screen. This is perfectly fine, since the SDK is open-source.
> 
> - However, we do not use Mapbox (the corporation) for providing the tile data. Instead, we [configure](https://github.com/wikimedia/apps-android-wikipedia/blob/master/app/src/main/assets/mapstyle.json) the SDK to fetch the tiles from our own tile server. This way, none of the users' data or requests are sent to Mapbox (the corporation)'s servers.

I think that in this case, we may want to consider doing the switch to the Wikipedia tile server instead of Mapbox, in the near future. We could possibly tag it on to the end of our grant (I could ask for a budget extension if needed), and we could hopefully use the Wikipedia app's implementation to guide us. Thoughts, anyone? @maskaravivek @neslihanturan

**Comment by nicolas-raoul** [comment]
I believe this is fixed.
