### ISSUE TITLE
Nearby: Refreshing map moves the map to the place I am in physically

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#5906]
Map should not move, as the user has scrolled to that place presumably for a reason.

https://github.com/user-attachments/assets/76cd2cad-4ce3-4048-91d8-83c048e3eb18

**Comment by rohit9625** [comment]
What is the purpose of that refresh button? We generally don't have such a button on Maps.

**Comment by nicolas-raoul** [comment]
@rohit9625 It clears the cache for the pin colors. Getting pin colors from Wikidata takes a lot of time and server resources. If someone adds a P18 for a pin on desktop, the app will not know and continue to show it red.

**Comment by savsch** [comment]
I'd like to work on this.

**Comment by nicolas-raoul** [comment]
@savsch Thanks! 🙂
