### ISSUE TITLE
Better string formatting in OkHttpJsonApiClient.java (easy)

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#5912]
Please change `Timber.d("CUSTOM_SPARQL%s", String.valueOf(customQuery != null));` to `Timber.d("CUSTOM_SPARQL: %s", String.valueOf(customQuery != null));`

... in two places in the code of OkHttpJsonApiClient.java

Notice the `: ` added.

Best leave this task to a beginner.

**Comment by sikehish** [comment]
I'd like to take this up :)
