### ISSUE TITLE
[Bug]:  Don't show edit category and edit depicts for logged out user

### ISSUE THREAD

**Issue by sivaraam** [commons-app/apps-android-commons#5918]
### Summary

This is a follow-up of #5726. We're showing the edit category and edit depicts buttons to the logged out users.

### Steps to reproduce

1. Open the app using the "Skip login" option
1. Open an image from the "Explore" screen
1. Observe the edit category and edit depicts buttons shown for the image.

### Expected behaviour

It should not be possible for users who are not logged in to click the edit category and edit depicts buttons shown for the image.

### Actual behaviour

We show the edit depicts buttons but it won't work. Trying to edit the image results in a indefinite spinning loader that then shows the edit screen but redirects to login page when the "Submit" button is clicked.

### Device name

OnePlus Nord

### Android version

Android 12

### Commons app version

main

### Would you like to work on the issue?

None

**Comment by Saifuddin53** [comment]
Hello @sivaraam can I work upon this issue ?
