### ISSUE TITLE
Bookmarking categories

### ISSUE THREAD

**Issue by prototyperspective** [commons-app/apps-android-commons#5922]
### What is the user problem or growth opportunity you want to see solved?

It seems like with the release that's just out and will probably soon be available in the PlayStore, the category search [will work again](https://github.com/commons-app/apps-android-commons/pull/5830) in the app. Once category support is back it would be really great if one could also [bookmark](https://commons.wikimedia.org/wiki/File:20240529_xl_09-Commons_Android_App_screenshots_user_interface_5.0.1~da0b2c28e_May_2024.png) categories, not just files.

I think it would be far more useful than bookmarking files. For example, I'd like to bookmark [this category](https://commons.wikimedia.org/wiki/Category:Spoken_Wikipedia_articles_using_English-language_speech_synthesis) so I can use the app to quickly and conveniently and with dark mode browse through spoken Wikipedia audios to download into my podcast player app (support for playing audio files is a separate issue at #5915)

### How do you know that this problem exists today? Why is this important?

It would be very useful to bookmark categories. One could bookmark all sorts of categories one is interested in. Maybe one could even include some of the bookmarked categories into some Home explore feed, e.g. showing the most recent or a few random items for a few categories bookmarked and added to the Feed. If needed I could list more examples of how people find bookmarking categories useful.

### Who will benefit from it?

People who use the app to explore, discover, search and consume media.

### Anything else you would like to add?

In the bookmarks page at some point there could be two tabs: one for bookmarked files and one for bookmarked categories. It's not necessary to include in the initial version, e.g. I don't bookmark any files but would bookmark several categories. If one has bookmarked many files accessing the bookmarked categories quickly which is one key thing the bookmarks would be good for would diminish as one has to first scroll and search long which is why having a separate tab would be good for people who bookmark both types of pages.

**Comment by nicolas-raoul** [comment]
Great idea!
In the Upload Wizard, we could also always suggest the bookmarked categories (just like we always suggest bookmarked depictions).

**Comment by parneet-guraya** [comment]
<p float="center">
  <img src="https://github.com/user-attachments/assets/6011f63b-8839-4cda-a589-402e3c4f927e" width="250" />
  <img src="https://github.com/user-attachments/assets/b067b007-9c7e-4e0c-b6bf-4075268e5ab3" width="250"/>
  <img src="https://github.com/user-attachments/assets/fce80e52-0e2d-4357-a327-21c69bbf5730" width="250" />
</p>

So, basically we want to be able to bookmark a category (category screen in img 2) just as we bookmark a file/image (img 1). Then, those should be listed in the bookmarks screen (img 3) under a `Tab` (may not be good to have another tab since already have 3, so perhaps something else?)

Like to try this one :hand:  :)

**Comment by nicolas-raoul** [comment]
Your understanding is correct! :-)
New tab is probably fine, I would say.

**Comment by parneet-guraya** [comment]
I'm sorry if I sound dumb :sweat_smile: but what is `Depict` ? I'm guessing it represent some of sort of data?

**Comment by nicolas-raoul** [comment]
As you may know, Wikidata aims to have one "item" for each concept in the world, for instance cat, dog, rabbit,etc.

A picture "depicts" a rabbit if a rabbit can be seen in the picture. 🙂

**Comment by parneet-guraya** [comment]
Understood :)
