### ISSUE TITLE
[Bug]: Currently the category selection does not seem to work reliably

### ISSUE THREAD

**Issue by OpenGreenStreet** [commons-app/apps-android-commons#5929]
### Summary

Sometimes:

No selection possible at all
Selection is only possible after closing and restarting the app
the category of the “searched image” is stored, but no additional category can be selected
sometimes everything is as usual/as expected

### Steps to reproduce

The problem does not always occur 

See https://commons.wikimedia.org/wiki/Commons:Mobile_app/Feedback#Feedback_from_Molgreen_for_version_5.1.0~707997bd1_on_2024/11/14_16:51:33

### Expected behaviour

Stable behavior 

### Actual behaviour

Non-stable behavior

### Device name

Pixel 7 Pro

### Android version

Android 15

### Commons app version

5.1.0~707997bd1

### Would you like to work on the issue?

None

**Comment by nicolas-raoul** [comment]
Are the symptoms different from https://github.com/commons-app/apps-android-commons/issues/5910 ?

**Comment by OpenGreenStreet** [comment]
@nicolas-raoul 

No, I think it's the same symptoms.

I only know the problem in the current version and the strange thing is that the problem does not always occur. After "closing" and restarting the app, it works at least once.

**Comment by nicolas-raoul** [comment]
Interesting!
To keep the discussion in the same place, let's merge to https://github.com/commons-app/apps-android-commons/issues/5910 would you mind copy-pasting your findings there? Thanks!
