### ISSUE TITLE
Migration of util module to kotlin

### ISSUE THREAD

**Issue by Saifuddin53** [commons-app/apps-android-commons#5934]
### Description

**Parent Ticket**: #5928  

I am working on migrating the following files in util module to Kotlin:
- AbstractTextWatcher 
- ActivityUtils
- CommonsDateUtil
- DateUtil
- DeviceInfoUtil
- ExecutorUtils
- FragmentUtils

**Comment by Saifuddin53** [comment]
@nicolas-raoul can I use this same ticket to migrate the remaining files in util module?

**Comment by nicolas-raoul** [comment]
Sure! :-)

If not ready for merging, I suggest marking it as draft.

**Comment by Saifuddin53** [comment]
Okay sir will take care 🙂
