### ISSUE TITLE
[Bug]: Error if I try to select more than 1 image

### ISSUE THREAD

**Issue by ivanbranco** [commons-app/apps-android-commons#5953]
### Summary

Since when I select a pin, it makes me choose only one picture, I used to select more pictures in "free mode" and then categorize them in the proper tab. After the latest updates, I can't do it anymore and I get an error. 

### Steps to reproduce

1. Go to the "Contributions" tab
2. click the "+" icon
3. choose the second icon
4. select two pictures and then I click in the upper-right corner "Select"
5. an error says: "An error occurred while selecting the images" (I'm roughly translating since my UI is in Italian).

### Expected behaviour

Let me upload more pictures like it used to be

### Actual behaviour

It works only with one picture at the time.

### Device name

Google Pixel 6

### Android version

Android 14

### Commons app version

5.1.0

### Would you like to work on the issue?

Prefer not

**Comment by ivanbranco** [comment]
Seems like I can upload more picture if at step 3 I choose the third icon and not the second.

**Comment by nicolas-raoul** [comment]
Unfortunately I can't reproduce the issue, I just uploaded successfully a set of two pictures using the second button.

Would you mind sending a screenshot of your settings, at the "Uploads" section?

**Comment by savsch** [comment]
I could trivially reproduce the issue on my phone as well as on a virtual device running API level 34

> Would you mind sending a screenshot of your settings, at the "Uploads" section?

![image](https://github.com/user-attachments/assets/2d928d99-34ba-46c1-bfe5-4453da8d1eef)

-----------

https://github.com/user-attachments/assets/22c17ca9-2899-44f1-9e89-2589e420e09d

**Comment by nicolas-raoul** [comment]
Ah yes I can reproduce now, thanks a lot! 🙂

**Comment by savsch** [comment]
The issue appears because of improper handling of the result data when documents based photo picker is used. The other cases (camera, gallery and custom selector) are properly handled.

I'd like to work on this.
