### ISSUE TITLE
Clicking on My Rank at Leaderboard will take minutes to reach your rank

### ISSUE THREAD

**Issue by neeldoshii** [commons-app/apps-android-commons#6019]
Steps to reproduce:
1. Go to achievements
2. Leaderboard
3. Click on my rank, it will auto scroll towards down until it reaches towards your rank

But since if you rank is in some thousands it will constantly get auto scrolled.

https://github.com/user-attachments/assets/b6fab24c-497a-4ff7-b8cf-8219e4f71969

Proposed Idea instead of my rank button show user his rank like this 

![image](https://github.com/user-attachments/assets/d1361a96-fe39-4b03-9611-4be5f54709b1)

Would like to take this issue.

**Comment by RitikaPahwa4444** [comment]
Is it similar to https://github.com/commons-app/apps-android-commons/issues/5768?

**Comment by neeldoshii** [comment]
Yes seems duplicate. Thanks
