### ISSUE TITLE
Different builds for Fdroid and Google Play

### ISSUE THREAD

**Issue by sandarumk** [commons-app/apps-android-commons#602]
Wikipedia Mobile app uses two flavors for the Google Play and FDroid users. It also allows you to have different flavors for beta, etc. It would be nice to have it here as well.  

`productFlavors {
        dev {
            versionName computeVersionName('dev')
            applicationIdSuffix 'dev'
            signingConfig signingConfigs.debug
            testInstrumentationRunner 'org.wikipedia.test.AndroidTestRunner'
        }
        prod {
            versionName computeVersionName('r')
            signingConfig signingConfigs.prod
        }
        releasesprod {
            versionName computeVersionName('releasesprod')
            signingConfig signingConfigs.prod
        }
        alpha {
            versionName computeVersionName('alpha')
            applicationIdSuffix 'alpha'
            signingConfig signingConfigs.debug
            testInstrumentationRunner 'org.wikipedia.test.AndroidTestRunner'
        }
        beta {
            versionName computeVersionName('beta')
            applicationIdSuffix 'beta'
            signingConfig signingConfigs.prod
        }
        amazon {
            versionName computeVersionName('amazon')
            signingConfig signingConfigs.prod
        }
        fdroid {
            versionName computeVersionName('fdroid')
            signingConfig signingConfigs.prod
        }`

**Comment by nicolas-raoul** [comment]
Is it not simpler to only have as few flavours as possible?
What problem(s) would the above solve?
Thanks :-)
