### ISSUE TITLE
Nearby: Race condition in the asynchronous loading of pin details

### ISSUE THREAD

**Issue by savsch** [commons-app/apps-android-commons#6037]
### Summary

Found this while looking for various factors that might be causing the Nearby screen to lag.

From my understanding, the Nearby section loads pins in the following manner:
1. when scrolling (or moving) to a new place, the items are queried (for just their P625) in the location, and added as grey pins to the map.
2. Once part one finishes, the other details for each pin are loaded sequentially in batches, and rendered on the map.

However, if step 1 is called again when part 2 is still in progress, the latter should stop altogether, and relaunched with the new places (for the current location). This is currently achieved in part by a static volatile boolean `stopQuery`.

However, it is prone to race conditions under the current implementation, where the asynchronous sequential loading of pin details (i.e. step 2) for the previous location does not stop when the same is started for the current location.

This has the additional side effect of the pins on the map alternating between _updated pins from the current location_ as well as _the updated pins from the previous location(s)_.

### Steps to reproduce

This is going to be slightly tricky.

On the main branch,
1. At the beginning of `NearbyParentFragment`'s `processBatchesSequentially` method, add a line to log that the method got called, with the starting index. (Like in the attached video).
2. Launch the app and scroll around (preferably with more than 30ish pins in the area so that the effect is more apparent).
3. In the logcat, you can see that the earlier places is still being processed while the new places have been loaded. For instance, in the attached video, atleast three instances are running: one around starting indices 9,12... and another around 18,21... and yet another around 30,33... .

---

It can be clearly seen in the attached video (note that I have intentionally throttled the rendering of pins onto the map by unrelated modifications to the code, to prevent lag when playing around):

https://github.com/user-attachments/assets/45707c9d-4720-4809-82cc-dc42397f34b3

### Expected behaviour

The details should be loaded only for pins on the current location. (i.e., only at most one instance of step 2 should be active at any given time).

### Actual behaviour

Multiple instances of step 2 are active.

### Device name

Samsung Galaxy S20FE, and a virtual device too.

### Android version

13,14 respectively

### Commons app version

main branch betaDebug

### Screen-shots

See the "steps to reproduce" section

### Would you like to work on the issue?

Yes

**Comment by savsch** [comment]
**On an unrelated note**, currently in the code, markers are added individually to the mapview's getOverlays() using the .add method.
The problem being, getOverlays() returns what extends the CopyOnWriteArrayList, so an add operation is deceptively expensive.
For instance, adding 1000 pins (the worst case) one by one takes over half a million iterations (takes a quadratic time (tight bound) to be precise). 
This part currently done on the main thread.
This can easily be replaced by a .addAll call, which will take only linear time for processing.

**However, this isn't a bottleneck and merely fixing this won't cause any noticeable improvements** on any recent device (found this from my testing).

---

I am wondering a separate ticket should be created for this. And whether this begs an umbrella/parent issue (related to fixing Nearby performance).

**Comment by savsch** [comment]
**On an unrelated note**, currently in the code, markers are added individually to the mapview's getOverlays() using the .add method.
The problem being, getOverlays() returns what extends the CopyOnWriteArrayList, so an add operation is deceptively expensive.
For instance, adding 1000 pins (the worst case) one by one takes over half a million iterations (takes a quadratic time (tight bound) to be precise). 
This part currently done on the main thread.
This can easily be replaced by a .addAll call, which will take only linear time for processing.

**However, this isn't a bottleneck and merely fixing this won't cause any noticeable improvements** on any recent device (found this from my testing).

---

I wonder whether a separate ticket should be created for this. And whether this begs an umbrella/parent issue (related to fixing Nearby performance).

**Comment by nicolas-raoul** [comment]
Fantastic, thanks for finding the race condition!

Would you mind making the addAll idea a different issue? And tag it with "nearby".
