### ISSUE TITLE
Nearby: Use addAll instead of add for adding multiple markers (overlays) to MapView

### ISSUE THREAD

**Issue by savsch** [commons-app/apps-android-commons#6040]
### Summary

Currently in the code, markers are added individually to the mapview's `getOverlays()` using the `.add` method.
The problem being, `getOverlays()` returns what extends the `CopyOnWriteArrayList`, so an add operation is deceptively expensive.
For instance, adding 1000 pins (the worst case) one by one takes over half a million iterations (takes a quadratic time (tight bound) to be precise).
This part currently done on the main thread.
This can easily be replaced by a `.addAll` call, which will take only linear time for processing.

**Comment by nicolas-raoul** [comment]
Thanks! Do you want to be assigned? :-)

**Comment by savsch** [comment]
> Thanks! Do you want to be assigned? :-)

Yes

I plan on improving the overlay management logic entirely, and maybe make the fixes along with #6037.
