### ISSUE TITLE
Nearby: Flawed initial loading of pins.

### ISSUE THREAD

**Issue by savsch** [commons-app/apps-android-commons#6044]
Currently, in nearby, when a user scrolls (which also includes resizing) to a new position in the map), a query is made for items in the rectangular geographical area. Although the query is lightweight (made for only P625), it goes on endlessly until timeout for large enough areas.

When a user zooms out enough, the initial query is made for a large area, so the query takes a long time only to end up in a timeout. When the user then zooms in, a second query should be initiated (discarding the first), but it never happens as per the current logic, which ideally shouldn't happen.
This part is easy to fix (by ignoring currently running query after a shorter timeout).

But ideally, the expensive query should never be made in the first place. Reason:
Say, the area is small enough for the query to return (but still large enough for it to return much greater than 1000 items).
Then the resulting items are sorted in-app (by their distance from the map centre), and only the nearest 1000 items are actually utilized.

A workaround would be to first query for the items count. If it's much greater than 1000, then query on a smaller square bound centered on the user (in the same manner as a _binary search_). Do it till the number of items in the queried area is under $`1000 \times \frac{4}{\pi}`$.

Here's an example:
- [The initial query in its current form](https://query.wikidata.org/sparql?query=SELECT%0A%20%20%3Fitem%0A%20%20%28SAMPLE%28%3Flocation%29%20as%20%3Flocation%29%0AWHERE%20%7B%0A%20%20%23%20Around%20given%20location%0A%20%20SERVICE%20wikibase%3Abox%20%7B%0A%20%20%20%20%3Fitem%20wdt%3AP625%20%3Flocation.%0A%20%20%20%20%20bd%3AserviceParam%20wikibase%3AcornerWest%20%22Point%282.3321%2048.8376%29%22%5E%5Egeo%3AwktLiteral.%0A%20%20%20%20%20bd%3AserviceParam%20wikibase%3AcornerEast%20%22Point%282.3545%2048.8625%29%22%5E%5Egeo%3AwktLiteral.%0A%20%20%7D%0A%0A%7D%0AGROUP%20BY%20%3Fitem%0A&format=json)
- [The proposed initial query (which returns only the count)](https://query.wikidata.org/sparql?query=SELECT%20(COUNT(DISTINCT%20%3fitem)%20AS%20%3fcount)%0d%0aWHERE%20%7b%0d%0a%20%20SERVICE%20wikibase%3abox%20%7b%0d%0a%20%20%20%20%3fitem%20wdt%3aP625%20%3flocation.%0d%0a%20%20%20%20bd%3aserviceParam%20wikibase%3acornerWest%20%22Point(2.3321%2048.8376)%22%5e%5egeo%3awktLiteral.%0d%0a%20%20%20%20bd%3aserviceParam%20wikibase%3acornerEast%20%22Point(2.3545%2048.8625)%22%5e%5egeo%3awktLiteral.%0d%0a%20%20%7d%0d%0a%7d%0d%0a&format=json)

Also, if the area is absurdly big, then even the count-binary-search queries (proposed above) can be dropped and a simple overlay saying "zoom in to display pins" can be shown (maybe similar to how chromium based browsers show "No Internet Connection").

**Comment by nicolas-raoul** [comment]
Great ideas! I totally agree with all of this.
Do you want to be assigned? (please mention it when creating issues)
