### ISSUE TITLE
Nearby: Map moves by itself after scrolling if a list item has previously been clicked. 

### ISSUE THREAD

**Issue by savsch** [commons-app/apps-android-commons#6046]
### Summary

In nearby, upon clicking an item in the list (which can be opened using the list icon at the top right), the map moves itself so that the item is centered on the map, which is intended.

After this, whenever the user moves the map to another location, then, once the pins load, the map _moves by itself_, to center itself to a random pin. This keeps on happening every time new pins (or pin details) are loaded, until the app is restarted.

### Steps to reproduce

1. Open the app, go to the nearby section.
2. Click on the list button on the top right.
3. Click on one of the places displayed in the list. The map moves itself to center the place as intended.
4. In the map, move to a new place. Wait for the pins to load. When (and while) they load, the map moves by itself.

### Expected behaviour

The map doesn't move at random without user interaction.

### Actual behaviour

The map moves by itself.

### Device name

Samsung Galaxy S20 FE

### Android version

Android 13

### Commons app version

5.1.0 F-Droid release, and also the current main branch

### Would you like to work on the issue?

Yes

**Comment by nicolas-raoul** [comment]
I cannot reproduce on 5.0.2-debug-nearby/performance-experiments~bacc4b367 am I doing it wrong or is it fixed already? 🙂

https://github.com/user-attachments/assets/4ab8fad7-239b-4e60-8c40-de709e880cfa

**Comment by savsch** [comment]
> am I doing it wrong or is it fixed already? 🙂

It has not been fixed. I believe it is more likely to occur when the clicked item is at/near the top of the list.

https://github.com/user-attachments/assets/c27af341-25fd-4314-bb54-b6190b2c8ef0
