### ISSUE TITLE
Nearby pins sometimes start loading from a corner rather from the center of the screen

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#6049]
https://github.com/user-attachments/assets/8b26d191-6654-497f-9188-afc77f963226

Seems like the app lost track of what is the center of the map, it is still considering where the app was earlier.

**Comment by savsch** [comment]
Is the following the intended behavior?
- If the map has moved slightly, then continue loading pins from where the map was earlier
- Otherwise, load pins from the map center (currently, the app seems to often not follow this one)

**Comment by savsch** [comment]
> I would say that always loading pins from the map center is the best. I don't think it has a big performance impact, as cached pins will reappear quickly.

Thanks for the feedback! Could you please check whether #6047 always loads pins from the center?
