### ISSUE TITLE
Nearby: show cached pins even when internet unavailable

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#6051]
Users without a mobile plan will appreciate.

Currently, if there is no internet then Nearby does not load any pins, even those that I know exist in cache, and just shows "Internet unavailable":

![Screenshot_20241221-003856.png](https://github.com/user-attachments/assets/4dad71f3-62ec-4d6a-a5bd-aa320cd8d7b8)

It will probably require adding coordinates to the cache.

**Comment by savsch** [comment]
Cool idea. I'm eager to work on it.

Should the grey pins also be made available offline?

**Comment by savsch** [comment]
I am excited to work on this. Can I be assigned?

This will require changing the schema a tiny bit (should be limited to simply making Place.location `@Embedded`), so that the coordinates get stored as floating point values, to support the required query.
