### ISSUE TITLE
[Bug]: 'App UI Language' and 'Default Description Language' menus do not close on pressing back button

### ISSUE THREAD

**Issue by sonalyadav1** [commons-app/apps-android-commons#6066]
### Summary

This issue affects usability, especially if a user wants to back out of the language selection menu without making a selection.

### Steps to reproduce

1-Open the app and navigate to the Settings section
2-Tap on either App UI Language or Default Description Language.
3-When the language list menu opens, press the device's Back button without selecting or changing the language.

### Expected behaviour

The language selection menu should close, and the app should navigate back to the previous screen.

### Actual behaviour

The language selection menu does not close, and the user is forced to select a language to proceed.

### Device name

Vivo V25

### Android version

Android 14

### Commons app version

5.0.2

https://github.com/user-attachments/assets/e6b13f6c-5853-48ed-a151-916ae2799bb3

### Would you like to work on the issue?

Yes

**Comment by nicolas-raoul** [comment]
Indeed that's frustrating, thanks! :-)

**Comment by parneet-guraya** [comment]
Fixed :-)
