### ISSUE TITLE
Prevent running out of memory for older and slower devices

### ISSUE THREAD

**Issue by Poyekhali** [commons-app/apps-android-commons#607]
Related issue: #510

Although the latest update has now limited the number of uploads displayed in the screen, and that the user can adjust the limit to their choice, it seems that this didn't helped some older and slower devices, particularly the Samsung Galaxy S3, which is what I am using. I set the limit to 5, but I am still running out of memory. It is obviously a memory leak (again).

**Comment by Pokefan95** [comment]
@dbrant at #510 says that this is not a memory leak, but that the software is loading the highest resolution for each upload. That's why I am running out of memory.

**Comment by whym** [comment]
What happens when it's running out of memory? Does the app crash?

In my case after loading 100 pictures it consumes 30MB of memory.

![memory](https://cloud.githubusercontent.com/assets/10674/26153810/0a150092-3b48-11e7-9717-99535bb533d2.png)

On the other hand, just showing the login screen it consumes ~25MB.
![memory2](https://cloud.githubusercontent.com/assets/10674/26154023/d478816a-3b48-11e7-9e46-ce43fc34c40f.png)

This is on Android 6.0.1, API 23, Nexus 5.

**Comment by Pokefan95** [comment]
@whym Yes it crashes.

**Comment by whym** [comment]
What does it say when it crashes? A screenshot would help investigation, if possible.

By the way, a workaround might be to use a memory cleaner/janitor app.

**Comment by Poyekhali** [comment]
![screenshot_2017-05-18-19-22-53](https://cloud.githubusercontent.com/assets/22285330/26200268/4ec9bab4-3c08-11e7-938e-5777e2c723b5.png)
It shows a message that it crashed, and prompts me to send a report via email. I used a memory cleaner app, and it didn't helped. The recent upload limit is 5. That workaround also don't work.

**Comment by Poyekhali** [comment]
This is the screenshot before the crash. It contains one PNG file, and the rest are ogv videos. Actually, setting the recent upload limit to 0 works, but how about users who want to make use of it but have a slower and older device like me?
![screenshot_2017-05-18-19-29-43](https://cloud.githubusercontent.com/assets/22285330/26200539/86f18b8c-3c09-11e7-90d3-8ba7865ba0c5.png)

**Comment by Poyekhali** [comment]
BTW, it took me some time to find a memory cleaner app which has no special permissions. Luckily I found two. But I will be uninstalling them later because they are proprietary software, and I believe most of them are malware.

**Comment by whym** [comment]
I found your crash report - apologies for not finding this earlier.
https://groups.google.com/d/msg/commons-app-android-private/oHJ8biLgNgU/Dm_Ntz7DCQAJ (for those who have access)

> and the rest are ogv videos.

This may be the cause, at least it looks suspicious to me.

E.g. does the current implementation try to retrieve full size video files for showing the list?

**Comment by Poyekhali** [comment]
I don't know, but @dbrant at #510 says that when the app fails to load the thumbnail of a file, it loads the highest resolution of it, meaning the original. And maybe the app is trying to load the whole video (not a thumbnail), that's why I ran out of memory.

**Comment by whym** [comment]
@Poyekhali a quick way to narrow down the cause might be to upload 4 or 5 (not too large) images, and try launching the screen with the limit of 5 uploads.

**Comment by Poyekhali** [comment]
...I am under a long wikibreak on Commons.. (I am not blocked, I really took a break, because I just screwed up there)

**Comment by Poyekhali** [comment]
But ok I will upload some images then.

**Comment by Poyekhali** [comment]
Ok here it is. I uploaded 5 1600x1200 images, all of them are dark. The app didn't crashed.

**Comment by Poyekhali** [comment]
![screenshot_2017-05-19-19-20-28](https://cloud.githubusercontent.com/assets/22285330/26245922/85bdec56-3cd1-11e7-968e-44d30dd392ac.png)

**Comment by misaochan** [comment]
Thanks @Poyekhali ! We think we might be well on the way towards fixing that. :)

**Comment by Poyekhali** [comment]
Great, the new update fixed this issue. I set the recent upload limit to 50 and the app didn't crashed. It also loads thumbnails of videos now.

**Comment by whym** [comment]
Just for the record, Poyekhali's crash reports contains volley's methods, so I assume this and #94 were the same issue and fixed together.
