### ISSUE TITLE
[Bug]: Crash when editing depicts

### ISSUE THREAD

**Issue by parneet-guraya** [commons-app/apps-android-commons#6072]
Open any media's detail. Try click on edit button. App will crash

https://github.com/user-attachments/assets/22072e0d-793d-4a96-9eec-36888703ae77

### Would you like to work on the issue?
Yes

**Comment by nicolas-raoul** [comment]
You are right, I can reproduce this. Thanks! 🙂

**Comment by parneet-guraya** [comment]
Fixed :-)
