### ISSUE TITLE
All dialogs should have atleast one button

### ISSUE THREAD

**Issue by parneet-guraya** [commons-app/apps-android-commons#6076]
In some dialogs there's neither positive nor negative button available since dialogs are modal (non dismissable) it blocks the app. So, solution is to keep the dialogs modal but add atleast cancel or dismiss button.

https://github.com/user-attachments/assets/da37a322-aeed-4aca-acb3-5b99f7128edd

### Do you want to work on this?
Yes

**Comment by sonalyadav1** [comment]
@parneet-guraya Yes, I completely agree with you. It can be quite frustrating at times to have to reopen the app.
I had solve some part of this issue in PR #6067

**Comment by parneet-guraya** [comment]
> I had solve some part of this issue in PR #6067

@sonalyadav1 
Yes, about that, actually we made the attempt to make dialogs non dismissable (here #6015) so that was intended. Ideally what we can do is provide a button in case user don't want to do any action (which will be solved with this issue fixed). 

Big reason of making them modal was if user touched outside accidentally when dialog was shown, it led to user missing the dialog (You can see it in the PR's fixed issue). Hope that makes sense :-)

P.S: Little tip for you, whenever trying to work on some part/feature/bug try to find related issue or why it was done the way it is, sometimes it is intended. So, this will also avoid unintentional rejections as well as lead you to write better solutions.

For eg. the solution that you pushed fixed the problem no doubt, but if you did find that it was intentionally kept (non dismissable) you could have covered more such dialogs that were also needed the fix (same as I done in this PR #6078 .

**Comment by sonalyadav1** [comment]
@parneet-guraya  Thank you for the explanation and the helpful tip! I understand now why the dialogs were made non-dismissible and will ensure to check related issues and PRs more thoroughly in the future. I’ll review PR #6078 for reference and strive to align my solutions better with the project’s intent. Thanks again for the guidance! 😊

**Comment by parneet-guraya** [comment]
I realize I have been spelling `dismissible` wrong 😅

**Comment by nicolas-raoul** [comment]
Good catch about the "report violation" popup! 🙂
