### ISSUE TITLE
Image detail view: Back icon opens nav drawer

### ISSUE THREAD

**Issue by tobias47n9e** [commons-app/apps-android-commons#616]
Currently the back button in the image detail view opens the nav-drawer. Would be good to either replace the icon with a hamburger or go back to the gallery. Can anyone else reproduce this with current master?

![screenshot from 2017-05-16 21-28-01](https://cloud.githubusercontent.com/assets/6953323/26124458/c351b6d8-3a7e-11e7-99ce-f44ce2c5b5c7.png)

**Comment by maskaravivek** [comment]
Fixed in #633.
