### ISSUE TITLE
If an item that doesn't exist anymore, indicate that

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#618]
This building was destroyed in 2007, as tipped by its Wikidata "end time": https://www.wikidata.org/wiki/Q11311478

We should hide such items, or maybe at least display "Does not exist anymore" or "Past object" or something similar.

The current Wikidata consensus seems to be that if no ancient picture/painting is available, then a picture of nowadays ruins is OK, but a totally-changed nowadays place picture is not OK:
https://www.wikidata.org/wiki/Property_talk:P18#Destroyed_building:_Is_a_picture_of_the_current_place_nowadays_OK.3F

In case of an ancient battle, there might be a plaque, but there is another property for plaque image: https://www.wikidata.org/wiki/Property:P1801

**Comment by tobias47n9e** [comment]
I think the places should be kept. People could set "no value" for P18 if there is really no existing image of the object. If the building was torn down recently a person could still be motivated to look in their family photo album for the picture.

**Comment by nicolas-raoul** [comment]
Local people indeed have higher chances to possess such old pictures.

How about mentioning that the building does not exist anymore? That would save people's effort for places that actually exist.

We could even have a checkbox in the app to "mark" a place as "ended", if they went there and saw that there is nothing to take a picture of.

**Comment by nicolas-raoul** [comment]
I think we should show the pin in a different color, as it makes me walk a lot for nothing haha.
Another property to check:
https://www.wikidata.org/wiki/Property:P576 dissolved, abolished or demolished

**Comment by Ahoerstemeier** [comment]
Around my home 50% of the items suggested are no longer existing parts of the former city wall, so its difficult to notice those places which need attention. As there may be users who want to see the places no longer existing, so to avoid filling the view for the general user - why not add an optional filter? A different color doesn't help when there are many no longer existing items cluttering the view.

**Comment by nicolas-raoul** [comment]
Mapbox seems to have something like filters:
![screenshot_20180410-204045](https://user-images.githubusercontent.com/99590/38555140-085be29c-3d00-11e8-935f-fdb985252dd4.png)

**Comment by nicolas-raoul** [comment]
This has been implemented :-)
If you notice any Wikidata item that is displayed (not in black) despite not existing, please create a new issue linking to the item. Thanks!
