### ISSUE TITLE
Set up localization crowdsourcing platforms

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#62]
For users/anybody to localize the app into languages they know.

Asked at https://translatewiki.net/wiki/Support#Former_WMF_app_now_community-maintained,_where_to_crowdsource_localization?_49961 , answers:

> If the repository is active, the project can certainly be re-enabled here. These days are quite busy, you may want to send a patch against the "translatewiki" repository in gerrit yourself. --Nemo
> It doesn't matter whether the app is community maintained or not. What is important that the translations end up in front of the users, i.e. for mobile apps there needs to be regular releases. --Nike

Seems like we need to mimick what Vicuña for instance is doing here: https://git.wikimedia.org/tree/translatewiki.git/master/groups

**Comment by jayvdb** [comment]
I did a bit of analysis at #217 .
So far the best looks like https://github.com/nijel/weblate / https://hosted.weblate.org/ which has tight GitHub integration.  i.e. i18n/l10n edits made in the webapp become real GitHub activity , which is a path towards becoming more involved in the project.

**Comment by nicolas-raoul** [comment]
Sounds great! Can we use hosted.weblate.org for free?

**Comment by Airon90** [comment]
Yes: https://weblate.org/it/hosting/#free

**Comment by nicolas-raoul** [comment]
@Airon90 Thanks for getting involved! If you have time, would you mind contacting weblate and providing them with the information they need? You can contact them as a member of the Commons team.

**Comment by Airon90** [comment]
I do it now :)

**Comment by Airon90** [comment]
Sent. I will tell you their answer ASAP ;)

**Comment by jayvdb** [comment]
Have we checked that all localisations in translatewiki.net have been imported?
Otherwise we'll be asking people to redo the same translations again.
A once-off check/import from translatewiki.net shouldnt be too difficult to do, e.g. using pywikibot.

**Comment by nicolas-raoul** [comment]
I believe the localization files in our Github are more up-to-date than translatewiki.net because:
- The UI has changed, introducing many new strings and modifying some
- We have modified the localization XML files manually

**Comment by nicolas-raoul** [comment]
@Airon90 What are your conclusions about the usability of weblate?

I suggest giving up on translatewiki, since after 10 month they haven't managed to set up our project.

**Comment by jayvdb** [comment]
First of all, note that there are not yet any weblate changes in [app/src/main/res](https://github.com/commons-app/apps-android-commons/commits/master/app/src/main/res).

Of the 12 pages of https://hosted.weblate.org/changes/ , 7 pages are [af](https://hosted.weblate.org/changes/?lang=af&project=commons-app&subproject=strings) "New source string", which I assume is how it reports a new language being added / or existing outdated language being updated.  I would love to know more about that; it seems a very noisy way to report this.  Only one `af` action is "Resource update".  I raised an issue https://github.com/nijel/weblate/issues/1274 about the weblate history not being very useful for 'following' what changed.

Then there are a lot of "Resource update" changes, one to each language I believe, and **only** one attributed set of changes,  to the Japanese translation by @naofum , translating 100% of messages with 5 messages with 'errors' (they are not really serious errors; some are differences in full stops and exclamation marks, and I dont know Japanese well enough to determine if this is a bug in weblate).

I think due to the way [lazy-commits](https://docs.weblate.org/en/latest/admin/continuous.html#lazy-commit) work, @naofum 's changes are not merged yet.  Perhaps @whym could review these translations, and make one improvement, which will force the translations to be committed.

**Comment by misaochan** [comment]
There was a recent response on the thread:

> Hi there! I may be able to help. It looks like the app was disabled with this changeset. If we restore it but change the repositories, we should be able to make it work, I think. I will take a look, but we will still depend on User:Nike or another TWN committer to review and merge the change.
> 
> Parent
> More
> Eloquence (talk)‎21:13, 29 October 2016

**Comment by misaochan** [comment]
I don't have permission to edit the thread even after signing up for an account.. but should we inform them that the canonical repo is now https://github.com/commons-app/apps-android-commons instead?

**Comment by jayvdb** [comment]
[Done](https://translatewiki.net/wiki/Thread:Support/Former_WMF_app_now_community-maintained,_where_to_crowdsource_localization%3F/reply_(21))

**Comment by whym** [comment]
> Perhaps @whym could review these translations, and make one improvement, which will force the translations to be committed.

I have done this last week. The translations are not yet coming.

**Comment by whym** [comment]
> Perhaps @whym could review these translations, and make one improvement, which will force the translations to be committed.

I have done this last week. The translations are not coming to GitHub yet.

**Comment by misaochan** [comment]
Yay, progress appears to have been made! :) 

> A changeset is now in progress here: https://gerrit.wikimedia.org/r/#/c/325776/
> 
> Provided we resolve any outstanding issues, we should be able to restore translation functionality soon.

**Comment by eloquence** [comment]
We'll need your input on this changeset, see the comment here: https://gerrit.wikimedia.org/r/#/c/325776/3/groups/Wikimedia/CommonsAndroid.yaml ; specifically the question whether some of the more unusual language code mappings like "be-tarask ->  b+be+tarask" are going to cause problems for you given the goal of Honeycomb compatibility.

**Comment by misaochan** [comment]
I would not be against raising the minimum SDK to 14, given that according to our stats less than 0.12% of our users are using versions below that. Anyone else have thoughts on this?

**Comment by misaochan** [comment]
Bumping min SDK to Android 4.0.3 Ice Cream Sandwich (API level 15) as suggested by @eloquence on gerrit.

**Comment by misaochan** [comment]
Seems like we are on translatewiki now? :)

**Comment by nicolas-raoul** [comment]
Looking at https://github.com/commons-app/apps-android-commons/tree/master/app/src/main/res/values* it seems that we don't get translations pushed to us yet? What is left to do?

**Comment by misaochan** [comment]
Oh, I thought the PRs we were getting in the past few minutes were done via translatewiki. Was I mistaken?

**Comment by eloquence** [comment]
If there are no remaining issues, localisation updates will arrive intermittently (typically 1-2 times/week) and are made directly as commits by @Nikerabbit and @siebrand, not as pull requests.

**Comment by nicolas-raoul** [comment]
The recent PRs come from an experimented Github user.
Translatewiki should push directly (no PRs) using one of the accounts we have explicitly authorized for them (see project settings > collaborators). Most are still "waiting for approval" though.

**Comment by misaochan** [comment]
I see, thanks for the clarification!

**Comment by Nikerabbit** [comment]
Per schedule, first export from translatewiki.net is expected to land on Monday.

**Comment by misaochan** [comment]
Awesome, thanks @Nikerabbit !

**Comment by misaochan** [comment]
The Travis-CI build is failing due to issues with the directories being pushed to. Anyone know if this is okay, or otherwise what can be done to fix it?

**Comment by whym** [comment]
See https://gerrit.wikimedia.org/r/#/c/328333/ - it looks like there needs to be additional language code mappings.

**Comment by misaochan** [comment]
Thanks @whym - I'm away for Christmas til next Monday, but will check when I can. Alternatively, please feel free to make whatever changes are deemed best. :)

**Comment by whym** [comment]
So the TranslateWiki side should be fixed by the patch above. Now we need to rename the resource files in this codebase: #349

**Comment by whym** [comment]
The [last patch](https://gerrit.wikimedia.org/r/#/c/328333/) should have mapped 'ug-arab' to 'ug' - it's now duplicated as '[ug](https://github.com/commons-app/apps-android-commons/blob/41355e9a28a3ae41384514d29ce9dd48b905056f/app/src/main/res/values-ug/strings.xml)' and '[x-invalidLanguageCode](https://github.com/commons-app/apps-android-commons/blob/88eec03892c15a646af66c7ee10c61f13a1fa14e/app/src/main/res/values-x-invalidLanguageCode/strings.xml)'. The latter directory name makes builds fail (https://github.com/commons-app/apps-android-commons/pull/350).

Would @Nikerabbit or @Siebrand be able to help finding how to solve this? Maybe we should try reaching out them after the holidays.

**Comment by Nikerabbit** [comment]
I'll try to figure this out by Thursday when I do the next export. If you are in hurry, x-invalidLanguageCode can be deleted immediately. Thanks for being patient.

**Comment by Nikerabbit** [comment]
How about now? There should not be x-invalidLanguageCode anymore.

**Comment by whym** [comment]
Looks it's fixed now! CI is green, and it builds for me locally, too.

**Comment by Nikerabbit** [comment]
FYI: I have set up https://github.com/translatewiki account. Still testing, but if it works well, we will start doing commits via it and start asking permissions for it.

**Comment by misaochan** [comment]
Works for me too, thanks @Nikerabbit ! Let us know when you want to switch to the translatewiki GitHub account and we'll set the permissions up.

**Comment by misaochan** [comment]
Pushed first release with translations. :) Do we want to close this issue?

**Comment by Nikerabbit** [comment]
So far no problems with @translatewiki so I have now started to go over all GitHub projects to add it.

**Comment by misaochan** [comment]
@Nikerabbit I have invited the account to the commons-app members.

**Comment by misaochan** [comment]
Also, I will be away starting Jan 12th (traveling for a bit, then relocating to Australia), so releases might be a bit scarce until I have managed to get stuff settled (hopefully by the end of Jan). Just letting you guys know so that the translations don't appear to be forgotten - they will definitely be going out to the app community, just not as frequently as usual.

@nicolas-raoul if you would like to do releases in the meantime please feel free.

**Comment by Nikerabbit** [comment]
I just noticed that the membership alone doesn't grant sufficient rights for @translatewiki.
```
  [Symfony\Component\Process\Exception\ProcessFailedException]                                                                                                                                        
  The command "cd /resources/nike/commons-android; git add .; if ! git diff --cached --quiet; then git commit -m 'Localisation updates from https://translatewiki.net.'; git push origin 'master'; f  
  i" failed.                                                                                                                                                                                          
  Exit Code: 128(Invalid exit argument)                                                                                                                                                               
  Working directory: /resources/nike                                                                                                                                                                  
  Output:                                                                                                                                                                                             
  ================                                                                                                                                                                                    
  [master 9602385] Localisation updates from https://translatewiki.net.                                                                                                                               
   19 files changed, 157 insertions(+), 17 deletions(-)                                                                                                                                               
  Error Output:                                                                                                                                                                                       
  ================                                                                                                                                                                                    
  ERROR: Permission to commons-app/apps-android-commons.git denied to translatewiki.                                                                                                                  
  fatal: Could not read from remote repository.                                                                                                                                                       
  Please make sure you have the correct access rights                                                                                                                                                 
  and the repository exists.   
```

**Comment by nicolas-raoul** [comment]
@Nikerabbit What is the full Git URL you are using? Including protocol and username.
It can usually be found at .git/config

**Comment by nicolas-raoul** [comment]
@Nikerabbit I added translatewiki to the project's collaborators, is it better now?

**Comment by Nikerabbit** [comment]
My config is:
```
[core]
        repositoryformatversion = 0
        filemode = true
        bare = false
        logallrefupdates = true
[remote "origin"]
        url = git@github.com:commons-app/apps-android-commons.git
        fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
        remote = origin
        merge = refs/heads/master
[user]
        name = translatewiki.net
        email = l10n-bot@translatewiki.net
```

I'll re-test export now.

**Comment by Nikerabbit** [comment]
...and it worked. Thanks.

**Comment by whym** [comment]
All has been good with TranslateWiki (thanks to everyone) - closing this.
