### ISSUE TITLE
 ‌[Leak Canary] Memory Leak on Login Activity

### ISSUE THREAD

**Issue by sandarumk** [commons-app/apps-android-commons#628]
![screenshot_1495199967](https://cloud.githubusercontent.com/assets/1345681/26249425/c8d60a44-3ca6-11e7-9bec-98873b4dfd62.png)

**Comment by mwoguri** [comment]
@sandarumk could you add your phone's version and steps to reproduce?  I tried logging in/out a few times on and Xperia Z3 running 6.0.1 and was unable to reproduce.

**Comment by maskaravivek** [comment]
Does this still happen. I tried reproducing the leaks 2-3 times but no memory leaks seem to happen. Can someone else test again. @misaochan @neslihanturan 

![no_leaks](https://user-images.githubusercontent.com/3069373/32419805-150cb860-c2a6-11e7-82ce-575d91dceae1.png)

**Comment by misaochan** [comment]
Has not happened to me recently.

**Comment by maskaravivek** [comment]
Closing it task as it doesnt seem to be happening with the current master. Feel free to reopen if anyone notices a leak.
