### ISSUE TITLE
Fix memory leak in ShareActivity.java

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#636]

**Comment by sandarumk** [comment]
![screenshot_1495209932](https://cloud.githubusercontent.com/assets/1345681/26256606/cfe74480-3cbd-11e7-9c8f-5c0154e9ec58.png)

**Comment by misaochan** [comment]
@dbrant has explained that this is due to the activity context being passed into GpsExtractor. java on initiation. We should pass the application context instead if possible, or pass the context directly into the methods that need it.

**Comment by misaochan** [comment]
Has this been fixed by the recent patch?

**Comment by maskaravivek** [comment]
I didn't notice any leaks while uploading a couple of images. It would be great if others could help in testing this. @misaochan @neslihanturan need your help in testing it. :)

**Comment by misaochan** [comment]
I tested (on a real device running 7.0) and don't get these leaks either, we'll see if @neslihanturan does.

**Comment by neslihanturan** [comment]
Tested on a real device 4.2.4, and no leak occurred.

**Comment by maskaravivek** [comment]
Closing the issue then. `ShareActivity` has undergone a lot of changes since the issue was reported. It might have got fixed in the process.
