### ISSUE TITLE
App constantly minimizes after logout

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#642]
After logging out, the app constantly minimizes until reloaded.

**Comment by mwoguri** [comment]
I could not reproduce this on an Xpera Z3 compact running 6.0.1.  When I log out, I am taken to the log in page.  Could you confirm that this still exists, @misaochan, and if so add any details about how to reproduce?

**Comment by misaochan** [comment]
Sorry it took so long for me to get back about this, @mwoguri . I think this issue has been solved, thanks. :)
