### ISSUE TITLE
List or map: remember last used

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#649]
Some people love maps and basically think in maps.
Other people have a lot of trouble understanding maps, and much prefer lists.

The app should use the last one used.

**Comment by sandarumk** [comment]
Should we store the choice in shared preferences? or do we have a better approach than that?

**Comment by maskaravivek** [comment]
@sandarumk  Storing the choice in shared prefs should be good enough. I have a branch with those changes. Will make a PR by tomorrow. :)

**Comment by nicolas-raoul** [comment]
@maskaravivek Did you start working on this? :-)

**Comment by sandarumk** [comment]
if not I can give it a try?

**Comment by mashawan** [comment]
Hi there, I am looking to get involved... this looks like an easy one to start with. I noticed there has been some chat here, but no one is currently assigned.  I'll assign myself, but please shout if you are already on it...

**Comment by nicolas-raoul** [comment]
@sandarumk Sorry for the late reply! Did yo start working on it?
@mashawan Let's wait a few hours for @sandarumk 's reply, sorry about that :-/

**Comment by mashawan** [comment]
No problem, just looking for something to start...

**Comment by sandarumk** [comment]
Sorry for the delay. I did not start and waiting for confirmation. @mashawan  you can start working on it. I won't be able to do it before next week.

**Comment by nicolas-raoul** [comment]
@mashawan: Seeing [@sandarumk's branches](https://github.com/sandarumk/apps-android-commons/branches) and given that 6 hours have passed, you can start working on this.
Cheers!

**Comment by nicolas-raoul** [comment]
Thanks for the reply! OK, assigning to @mashawan :-)

**Comment by mashawan** [comment]
Got a working implementation now, just tidying it up a little.

**Comment by mashawan** [comment]
I think this is done now...
