### ISSUE TITLE
Ask for location permissions at runtime for Nearby Places

### ISSUE THREAD

**Issue by HonzaG** [commons-app/apps-android-commons#650]
While you use Nearby feature in new beta it doesnt show any nearby items; warning "No places nearby is shown instead. GPS on; Android 6.0

![2017-05-20 14 27 55](https://cloud.githubusercontent.com/assets/6265408/26276522/6aec8e8e-3d79-11e7-93dc-87706f78633f.png)

**Comment by tobias47n9e** [comment]
This could be related to this: https://github.com/commons-app/apps-android-commons/issues/674

Moving around might solve the issue because the location is updated. But I am not totally sure how we currently do locations.

**Comment by tobias47n9e** [comment]
I just tested this another time with the Android 7 emulator. For some reason the app ended up not having the location permissions. I had to manually go to the settings and allow the app to access the location. Maybe that is the cause of this issue?

![screenshot from 2017-05-26 22-50-14](https://cloud.githubusercontent.com/assets/6953323/26512273/240df786-4266-11e7-8d68-1a3f782952ff.png)

**Comment by misaochan** [comment]
Interesting. The original implementation did ask for permissions at runtime - was this removed? If so, we definitely need to put permissions back in.

That being said, I don't think that is the sole cause of the issue. I was experiencing it to an extent with my phone in Svet Hub and in Jufa - going outside seemed to fix the problem for me, so I thought that it was just my hardware. But if other people are facing the same problem as well, then we do need to look into it further.

**Comment by misaochan** [comment]
Tested a fresh install again and am experiencing the same issue as you guys - location permissions are not asked.

**Comment by tobias47n9e** [comment]
Probably the same issue: https://github.com/commons-app/apps-android-commons/issues/291
