### ISSUE TITLE
Doubled pics in upload list

### ISSUE THREAD

**Issue by HonzaG** [commons-app/apps-android-commons#651]
While you go through your upload list in some cases (not tested) some of the images appear twice, even if they are uploaded just once (u can check in https://commons.wikimedia.org/wiki/Category:Dobřínsko)

![2017-05-20 14 37 42](https://cloud.githubusercontent.com/assets/6265408/26276635/416a001c-3d7b-11e7-96a0-37639aaa27ad.png)

**Comment by misaochan** [comment]
Does this still happen?

**Comment by nicolas-raoul** [comment]
Not seen in a while.

**Comment by misaochan** [comment]
I will close this for the meantime then, feel free to reopen if the issue persists in beta @HonzaG .
