### ISSUE TITLE
number of uploaded pics in header

### ISSUE THREAD

**Issue by HonzaG** [commons-app/apps-android-commons#654]
there is number of loaded images (minus number of deleted images) in the header of app; there should be number of total uploads to commons; in idle case there should be number of loaded pics/number of total uploads (= 500/1234)

**Comment by HonzaG** [comment]
https://tools.wmflabs.org/urbanecmbot/uploadsbyuser/uploadsbyuser.py?user=Jagro

Thanks to Martin Urbanec!

**Comment by nicolas-raoul** [comment]
@HonzaG : Very useful script, and faster than anything we could develop!
Off-topic, would you happen to know any script that gives the numbers we are looking for at #85? Thanks a lot :-)
