### ISSUE TITLE
graphic of numerical order of uploads

### ISSUE THREAD

**Issue by HonzaG** [commons-app/apps-android-commons#655]
align of numerical order of uploads is not correct, you cant see half of it bcs of transparent banner with filename
![2017-05-20 15 49 08](https://cloud.githubusercontent.com/assets/6265408/26277488/f5ebbe24-3d88-11e7-9001-101a13eb61a9.png)

**Comment by nicolas-raoul** [comment]
Thanks for the feedback!
About the arrow on the right: It is indeed a bit disgracious
About the arrow on the left: I actually quite like how it looks right now, a bit stylish and not difficult to read :-)

**Comment by neslihanturan** [comment]
This seems like solved.
