### ISSUE TITLE
upload/list logic

### ISSUE THREAD

**Issue by HonzaG** [commons-app/apps-android-commons#658]
while you hit UPLOAD button in menu, you are redirected to LIST OF UPLOADS, which is not user friendly.
1, add LIST OF UPLOADS button into the menu, which heads you to LIST OF UPLOADS (todays UPLOAD)
2, change UPLOAD to be more user friendly (call for action is UPLOAD, so it have to be the most visible option); UPLOAD button will:
2, 1, it will leads to LIST OF UPLOADS and automatically open selection (camera/gallery) dialogue
2, 2, it leads to new page with some info about uploads + UPLOAD buttons
2, 3, it leads to LIST OF UPLOADS and instead of first picture there is CAMERA/FILE (see the attachment, sorry for shitty graphics :)

![2017-05-20 16 59 24](https://cloud.githubusercontent.com/assets/6265408/26277779/2d18bcde-3d8f-11e7-94b0-cccf29743c44.png)

**Comment by HonzaG** [comment]
mPOV: start with 2.3 and have 2.2 as nice-to-have bcs we will need a designer for that

**Comment by nicolas-raoul** [comment]
I totally agree with all of that.
The camera/gallery buttons are much too small right now.

**Comment by neslihanturan** [comment]
Now UX looks okay based on this scenario.
