### ISSUE TITLE
Fix the backstack

### ISSUE THREAD

**Issue by sandarumk** [commons-app/apps-android-commons#665]
Steps to reproduce

1. Go to the Home
2. Click Home again in navigation drawer
3. Repeat the above step (2) twice
4. Select Nearby in the navigation drawer
5. click the back button
6. It will leads to the Home
7. Click the back button again
8. It reloads home

The problem is it keeps the same page in the backstack more than once if it is accessed more than once in continuous clicks in the navigation drawer.

**Comment by ujjwalagrawal17** [comment]
I think this issue should be closed now.

**Comment by misaochan** [comment]
Indeed, thanks for letting us know. :)
