### ISSUE TITLE
Localize nearby map

### ISSUE THREAD

**Issue by tobias47n9e** [commons-app/apps-android-commons#669]
Currently the labels of the nearby map are not localized. From what I read, it might not be as simple as just sending the locale along with the other map options. Probably needs some investigation how that is handled with Mapbox.

Some docs:
* https://www.mapbox.com/help/change-language/
* https://stackoverflow.com/questions/42476708/mapbox-gl-js-all-labels-language

**Comment by misaochan** [comment]
Is this still possible now that we are using the Wikimedia tile server?

**Comment by misaochan** [comment]
@VojtechDostal or anyone else who runs a different language on their phone - are the Nearby map labels localized for you currently?

**Comment by VojtechDostal** [comment]
Everything seems to be perfectly localized now. Both labels and descriptions are in Czech even for items when an English label is available.

**Comment by misaochan** [comment]
Great! Will close this for now then. :)
