### ISSUE TITLE
Use of "article" for Commons and Wikidata

### ISSUE THREAD

**Issue by sjoerddebruin** [commons-app/apps-android-commons#670]
Both projects don't use articles. Wikidata uses items and Commons gives a gallery or category. Should we just use the project names or is there a good word to use for the Commons situation?

**Comment by nicolas-raoul** [comment]
Hi!
What is the problem?
Do we use the word article in the app's user interface?
Or in the source code?

**Comment by tobias47n9e** [comment]
@nicolas-raoul You might not have seen this menu in git master yet:

![screenshot from 2017-05-25 10-52-37](https://cloud.githubusercontent.com/assets/6953323/26443380/665e4d18-4138-11e7-949c-0acd4a9c4100.png)

We should probably change that to Wikidata item instead.

**Comment by simon04** [comment]
The `commons:` interwiki link is set inconsistently to either a Commons category or a Commons gallery page. What about switching to `P373` (Commons category) and labelling the entry "Commons category" instead?

**Comment by misaochan** [comment]
I'd vote for "Commons category" (assuming we make the changes @simon04 suggested) and "WikiData items".

**Comment by sjoerddebruin** [comment]
"Wikidata item", the D shouldn't be capitalized and it is pointing to a single item.

**Comment by misaochan** [comment]
@sjoerddebruin good point, thanks!

**Comment by simon04** [comment]
To fetch the Commons category from Wikidata: https://github.com/commons-app/apps-android-commons/compare/master...simon04:fetch-commons

**Comment by Vanethos** [comment]
I tried to make this my first contribution to an open source project 💃 https://github.com/commons-app/apps-android-commons/pull/715

**Comment by misaochan** [comment]
Nice work, welcome @Vanethos ! :)
