### ISSUE TITLE
Make tutorial/guidelines/welcome screen accessible again at any time

### ISSUE THREAD

**Issue by antonv6** [commons-app/apps-android-commons#671]
I've found #274 and #501, they are somewhat similar, but don't include the simplest option, which I'd like to suggest in this issue: let's allow users to review the welcome screen again whenever they please. I think it could be another menu item, for example.

**Comment by misaochan** [comment]
I agree, this would be good.

**Comment by sandarumk** [comment]
Can this be a navigation drawer item? Is someone working on this?

**Comment by maskaravivek** [comment]
@sandarumk I am working on it. Yes, adding it as a drawer item. :)
