### ISSUE TITLE
Show my real-time position on Nearby map

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#686]

**Comment by tobias47n9e** [comment]
I made a version with a marker and a circular polygon for the location accuracy: https://github.com/commons-app/apps-android-commons/pull/692

**Comment by tobias47n9e** [comment]
Maybe a live location marker would be better, because people can also use this map for navigating.

**Comment by nicolas-raoul** [comment]
Thanks a lot!
Knowing the position I was at at the time of the request is nice, but knowing my real-time position as I try to walk to the items, showing my position moving (am I going the right way or not, did I go too far, etc) would be even nicer indeed :-)
Also, if it is easy, showing the compass or direction of my movement would be wonderful, but that can be a separate enhancement idea ^^

**Comment by tobias47n9e** [comment]
@maskaravivek @neslihanturan I looked at this example (https://www.mapbox.com/android-sdk/examples/user-location/) today, but did not manage to get it to work with our NearbyFragment. Maybe one of you has time to look at it at some point.

**Comment by misaochan** [comment]
I think we would probably need to fix the way we are updating the user's location ( #674 ) before we attempt this
