### ISSUE TITLE
The messages "Commons Article" and "WikiData Article" may need improvement

### ISSUE THREAD

**Issue by amire80** [commons-app/apps-android-commons#690]
The word "article" is appropriate for Wikipedia, but not for Commons and Wikidata.

If "Commons Article" refers to a file description page in Wikimedia Commons, then it should say "Commons file page" or "Commons description page", or "File description page in Commons".

If "WikiData Article" refers to an item page in Wikidata, then it should say "Wikidata item" or "Wikidata item page". (And of course, "Wikidata" is not CamelCase.)

Both messages also need message documentation (qqq). The easiest way to fix this is to edit the qqq pages in translatewiki.net and write the explanations there:

* https://translatewiki.net/w/i.php?title=Wikimedia:Commons-android-strings-nearby_info_menu_commons_article/qqq&action=edit
* https://translatewiki.net/w/i.php?title=Wikimedia:Commons-android-strings-nearby_info_menu_wikidata_article/qqq&action=edit

**Comment by tobias47n9e** [comment]
Related issue: https://github.com/commons-app/apps-android-commons/issues/670

**Comment by misaochan** [comment]
Wikidata is done. Would anyone like to do Commons file page? :)

**Comment by jorgecasariego** [comment]
Hey everybody, doing my first pull request and my first contribution to **apps-android-commons** in #795

**Comment by misaochan** [comment]
Thanks @jorgecasariego ! I think we can close the issue now. :)
