### ISSUE TITLE
IEG renewal proposal

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#694]
After this IEG round is over (basically, just the final publicity step and the final report left), I intend to apply for a renewal. 

**UPDATE: The final draft is available at https://meta.wikimedia.org/wiki/Grants:Project/Improve_%27Upload_to_Commons%27_Android_App/Renewal . I am no longer updating the opening post.**

# Tasks

Please bear in mind that the time estimates below are not just for development, but also for testing, getting user feedback and fixing any issues with implementations 

'Nearby places that need pictures' enhancements: (1.5 mths)
 * When user selects an item on the nearby list or map, there could be an option for them to upload a picture for that item. They can choose camera or gallery to take the picture.  #252 
 * After a picture has been taken or selected, they could be taken to title/desc screen. Title/desc screen could have an option for "use suggested title and description" which would fill in the fields with the title and description of the Wikidata item
 * Category suggestions could be offered based on the categories associated with the Wikidata item (in addition to other category suggestions)
* After a successfully uploaded picture, the app should add the image to the Wikidata item via editing the P18 property (needs to be monitored at the start to make sure we are doing it right)
* [unsure] After a successfully uploaded picture, the user could be asked if they would like to edit the corresponding Wikipedia article (if one exists) - either via the Wikipedia app (if installed) or Web View
 * User could be notified of places near them without photos.  Clicking notification should take them to the item in the nearby list or map #259 
* Show real-time position on Nearby map #686  (after improving how location is updated #674 )
* Tell user what Nearby places actually is and does - either through adding a brief description to the UI or a one - time pop-up

Quality of life improvements: (1 mth)
* Enable 2 factor authentication #328 
* Fix battery drain issue ( #724 )
* Deleted photos should not be shown in contributions list #118 
_* [Not included] Add support for videos? #4 (not sure how much work this would take)_

UI improvements: (1 mth)
* User should be able to select multiple uploads from gallery when initiating the selection from within the app instead of only via "Share"
* Upload and camera buttons should be placed in a more obvious and easy to reach location ( #725 )
* [unsure] Users can view photos that other people have uploaded near them ( #725 )
* Nicer login screen - a few people have said that the current one doesn't look good
* Nicer nav drawer with username and maybe picture of the day displayed

_[Not included] Make app more interactive:_ 
_* [Not included] Badges - I think we want to stay away from pure quantity badges like "200 uploads" so we don't inspire bad uploads. Rather, we could offer badges for quality, like when the user maintains a 90% no deletion rate, or when their pictures are used in articles or selected as picture of the day etc. Also not sure on the feasibility of this as it would require backend storage online #85_
_* [Not included] Add campaign support (not sure if feasible in addition to everything else, might take a lot of work). A "lite" version of this could be just displaying news about ongoing campaigns/competitions #78_ 

Improve user education to improve uploads:deletion ratio:  (1 mths)
https://github.com/commons-app/apps-android-commons/issues?q=is%3Aopen+is%3Aissue+label%3A%22user+education%22
* Display account notifications to user  (e.g. picture has been nominated for deletion). #7 

Various important technical stuff: (1.5 mths)
* Allow dummy uploads 
* Implement upload tests #705 
* Fix overwrites #703 #228 
* Improve event logging #734 
* Fix the top 10 crashes (by number of reports) listed in Google Developer console
* Fix memory leaks (esp. in ShareActivity.java)
* Fix "high priority" bugs

# Metrics of success

* All tasks completed
* Number of uploads from our app that are used in wikipedia articles - we could get this from [wmflabs](https://tools.wmflabs.org/glamtools/glamorous.php?doit=1&category=Uploaded+with+Mobile%2FAndroid&use_globalusage=1&projects%5Bwikipedia%5D=1&projects%5Bwikimedia%5D=1&projects%5Bwikisource%5D=1&projects%5Bwikibooks%5D=1&projects%5Bwikiquote%5D=1&projects%5Bwiktionary%5D=1&projects%5Bwikinews%5D=1&projects%5Bwikivoyage%5D=1&projects%5Bwikispecies%5D=1&projects%5Bmediawiki%5D=1&projects%5Bwikidata%5D=1&projects%5Bwikiversity%5D=1)
* 500 (?) P18 edits in Wikidata (see #252 )
* Uploads:deletion ratio
* [Unsure of] Test coverage?

**Comment by tobias47n9e** [comment]
I think preparing for structured data on Commons could also be part of the proposal: http://structured-commons.wmflabs.org/wiki/File:LighthouseinDublin.jpg

**Comment by misaochan** [comment]
@tobias47n9e good point. Do you know when structured data will actually be live?

**Comment by nicolas-raoul** [comment]
I guess the legacy API will be kept as a transition for a long time,
though? (I could be wrong)
So, probably 2 years before Commons switches to structured data, and like 3
years of legacy, so I would personally feel that the priority is not that
high compared to other features that would bring immediately visible
improvements in terms of incoming data/metadata content :-)

**Comment by misaochan** [comment]
Okay, I think I've finished a (very) rough draft of the tasks. I think structured data could be left for next round in this case, plenty of time left :) 

Would appreciate any comments, both on the tasks themselves and of their feasibility, as well as additional ones that might be good to include. We are assuming 6 months of a total of 40-60 hours per week (split between 3 people). @nicolas-raoul @VojtechDostal @tobias47n9e @neslihanturan @maskaravivek

**Comment by tobias47n9e** [comment]
Code quality in general might be another point. Currently Android Studio points out many classes as unsafe, which might be the reason behind some of the more obscure crashes. Clean code also means more people eager to contribute. Maybe also set a goal for test coverage.

**Comment by misaochan** [comment]
Jordan Adler @jmadler (from Google) sent me this email with feedback and suggestions for our app, and I'm posting them here with his permission. :) It's a little bit old, so we've done a few of them already, but I think the ones we haven't done could be part of the renewal also.

> 
> * If you haven't already, I'd suggest running Play Store Experiments on the listing to find which screenshots and descriptions most meaningfully drives usage.
> * I'm wondering if there are ways to integrate with other photo providers (e.g. Google Photos, Facebook) to identify photos for upload.
> * I think there's some opportunity to gamify contributions here, focusing around impact and usage.  If you haven't already, I'd suggest joining and experiencing the Google Maps Local Contributor Program.  I think something similar for Wikipedia/Wikimedia Commons could be helpful.  Consider an email or push notification letting me know that my contribution was a featured image, used in an article, or hit a threshold of views.  That'd definitely make me feel like my effort was worthwhile, and encourage me to contribute more.
> 
> If you're interested, I'd be happy to request a UI review from my colleague in the Material Design team.  I think there's some low hanging fruit still to address though, so I'd run through the MD spec and identify potential improvements.  For example:
> 
> * The navigation should probably move into a drawer to better align with user expectations (done)
> * The actions should probably move into a FAB 
> * The Settings page needs a back button (done)
> * The Nearby feature is nice and definitely something I'd consider using. I'm wondering if it'd be helpful to inlay links to Wikipedia articles as well, so people could learn more about the place before deciding to snap a photo.  For example, near me is 'Singularity University', which I'm not sure even has a meaningful photo to take :) (done)
> * If the user hasn't uploaded anything, the default activity (My Uploads) is empty.  I'm wondering if it'd be a helpful nudge in that case to have a message encouraging the user to upload their first photo.
>

**Comment by neslihanturan** [comment]
>> I think there's some opportunity to gamify contributions here, focusing
around impact and usage. If you haven't already, I'd suggest joining and
experiencing the Google Maps Local Contributor Program. I think something
similar for Wikipedia/Wikimedia Commons could be helpful. Consider an email
or push notification letting me know that my contribution was a featured
image, used in an article, or hit a threshold of views. That'd definitely
make me feel like my effort was worthwhile, and encourage me to contribute
more.

I think this new feature would be awesome, and it is very fun to design and
implement such thing. On the other hand, such big feature needs to be
designed very carefully , it needs to be able to be enlarged. Thus, I think
we should add this to our future goals but we should start working on it
after we are done with everything else.

**Comment by nicolas-raoul** [comment]
> threshold of views

Minor remark, I don't think you can get an image's number of views. _Anyone please prove me wrong :-)_

**Comment by misaochan** [comment]
It seems that one of the IEGs was renewed for 8 months: https://meta.wikimedia.org/wiki/Grants:IEG/A_graphical_and_interactive_etymology_dictionary_based_on_Wiktionary/Renewal

So it seems like we aren't limited to 6 months renewal after all. Although, it's debatable whether a longer renewal would be beneficial or desired?

**Comment by misaochan** [comment]
Benefits of longer renewal period (9 or 12 months instead of 6):
- Able to implement more of our planned features 
- Less time spent in writing reports (as the major reports required are 2 per grant regardless of length of grant period, and the final report especially takes a LOT of time) and more time to focus on development
- If approved, this would guarantee that our project will be funded for the next 9 or 12 months, instead of only for the next 6 months

Disadvantages of longer renewal period:
- More funds need to be requested up front, so potentially higher chance of application being declined 
- All grantees would need to be able to commit to working on this for the period that we decide on
- Less flexibility in changing strategies or directions, as we would need to adhere relatively closely to the plans we made for the next 9 or 12 months

What do you guys think?

**Comment by nicolas-raoul** [comment]
Difficult decision indeed! It greatly depends on your medium-term life plans, so I don't have much advice to bring.

**Comment by neslihanturan** [comment]
I think we shouldn't set it to 12 months eventually. However 8 or 9 month seems legit to me. I personally guarantee that I will be working on the tasks at least until the time finished. I can arrange my other stuffs accordingly. 
On the other hand are we sure 6 month isn't enough? I think it is enough for the things on  the list at top of the page. Are planning to add extras like gamify so we might need extra time?

**Comment by misaochan** [comment]
@neslihanturan Yeah I think 6 months will be enough for all the tasks that aren't marked 'unsure' (bear in mind that the time needed is not just for development, but also for testing, getting user feedback and fixing any issues with implementations - from my experience this took a lot of my time during the previous grant). 

The main issue here, I guess, is that of "what next?". Every grant can have only one renewal (AFAIK), so after the renewal is over, if work is to continue on this app, either we have to apply for a new Project Grant, or (and this is a VERY long shot, but a pipe dream of mine :) ) for a [Simple Annual Plan Grant](https://meta.wikimedia.org/wiki/Grants:Simple). Regardless of what decision we make, we should ensure that we are able to make enough of an impact with the renewal that we can be considered again for those. (Of course, there is no obligation for anyone else to stay with us after the renewal concludes, if they decide not to).

**Comment by VojtechDostal** [comment]
I agree that a 6-month grant is a good compromise between sufficient duration on one hand and flexibility on the other.

As for Project grants/Simple APG, these tend to be accompanied by a certain amount of administrative work. Because Wikimedia Czech Republic already runs APG grants and is already involved in Wikimedia Commons App, why don't we rather include the budget for 2018 in the WMCZ's APG? Seems like the most reasonable solution to me. I will have to make some inquiries about ways to pay foreign nationals but I think Wikimedia Czech Republic can easily use services like Upwork: https://www.upwork.com/i/how-it-works/client/
Wikimedia Foundation uses these services for some of their freelancers. 

What do you think?

**Comment by VojtechDostal** [comment]
Budget from WMCZ could give us time to consider some long-term options. For easy access to WMF grants, maybe we should consider forming a Wikimedia Commons App Usergroup in 2018:
https://meta.wikimedia.org/wiki/Wikimedia_user_groups
If we decide so, we can include these plans into our grant proposals :-)

**Comment by misaochan** [comment]
@VojtechDostal That would be great if possible! (And less administrative overhead is always a bonus as far as I'm concerned :) ). I'm unfamiliar with Czech Republic laws on employment, but if you are allowed to pay contractors/grantees (and this doesn't conflict with your agreement with WMF) then that sounds like a good plan.

I'm not sure how the timelines will merge, since you mentioned that the WMCZ grant starts in September? Or is the application in September and the actual grant period starts January? 

Will look into forming the usergroup, thanks. :)

**Comment by VojtechDostal** [comment]
The WMCZ grant is going to be Jan-Dec '18. 
September '17 is the deadline for proposals for year 2018 :-)

We don't need to be too specific about what we want to do with these money in the proposal. APG does not require such amount of details the way IEG does. Basically we'd have to have an overall idea of what the structure of the team will be and where we generally want to be in December '18 :-)

**Comment by misaochan** [comment]
Nice! :) 

Let us go with 6 months then. I have revised the opening post accordingly and will be going off of that when I write the renewal proposal (next week hopefully!). In order to make sure that the core tasks are finished, I think we might have to keep the [Not included] tasks for the following round.

I have included rough estimates of the time needed for each of the above components - please let me know what you guys think.

**Comment by maskaravivek** [comment]
Yes, the goals we are setting look achievable to me in 6 months if all of us give our best. :)

Am just not very sure about the notifications bit. It might be tricky as we would need some sort of a webservice that pushes these notifications to the subscribed mobile devices.

**Comment by misaochan** [comment]
@maskaravivek I agree, we probably need to look further into the push notifications. I wonder if it might be a good idea to just display in-app notifications for now (basically, just displaying the nearest Nearby place in the UI of the main screen), and save push notifications for later? Push notifications would be wonderful but we would likely need at least an idea of how we want to implement the server side code before we promise it to users.

**Comment by misaochan** [comment]
An incomplete draft of the renewal proposal is now being worked on at https://meta.wikimedia.org/wiki/Grants:Project/Improve_%27Upload_to_Commons%27_Android_App/Renewal . Please feel free to browse and offer suggestions/feedback on the existing sections if you would like.

As an additional measure of success, I wonder if we should include 'user feedback' as a measure, since many of the improvements in the renewal are aimed at improving the user experience and convenience. We could have a one-time survey (advertised in mailing lists perhaps) at the end of the grant period, and ask questions about whether the user feels that the experience has improved for them over the last 6 months, or how often they use the app to upload photos to Commons, etc. It is quite a subjective measure though, so I am unsure about it.

**Comment by nicolas-raoul** [comment]
For user feedback, a good measure can be the number of stars given on
Google Play.

**Comment by misaochan** [comment]
@nicolas-raoul Hmm. I am hesitant to use Google Play reviews because I think some of them aren't relevant, honestly. There are quite a few 1-star reviews by people who either (1) have a bone to pick with WMF and are taking it out on us, like the guy who was complaining about English Wikipedia, or (2) don't know what the purpose of the app is, like those who are complaining that it doesn't have Photoshop functionality. I was hoping that using a survey sent via mailing lists would at least ensure that the responders are those who are reasonably familiar with our app and Wikimedia projects, which is the target of most of our improvements.

Do you think user feedback in general is a good metric of success though?

**Comment by nicolas-raoul** [comment]
Indeed Google Play review can be pretty tough and random. And people tend
to rate the whole initiative rather than the app itself, for instance
people who get a stinky room with Airbnb might give the app one star, even
if the app was flawless.

But I am not sure how many people would respond on the mailing list, which
does not have many readers I believe.

A link shown to experienced users within the app (once between date and
date+1month) could be an idea, if easy to implement.

**Comment by misaochan** [comment]
Ah, good point. The link within the app sounds like a good plan to me, if feasible. Perhaps I will add it as an 'optional' measure of success, same as how I did with the 10+ new contributors the last time.

**Comment by misaochan** [comment]
Also, I wonder if there is a method for measuring test coverage just for the upload functionality (as that will be our main focus for implementing tests for, for the time being)?

**Comment by misaochan** [comment]
As the proposal is up on meta-wiki and I am no longer editing the opening post, if no one has any objections I will close this to prevent duplication with #696 .

**Comment by misaochan** [comment]
Reopening for discussion re: metrics of success - https://meta.wikimedia.org/wiki/Grants_talk:Project/Improve_%27Upload_to_Commons%27_Android_App/Renewal#Metrics_of_success_-_Google_Play_ratings_vs_survey

**Comment by misaochan** [comment]
This has been approved.
