### ISSUE TITLE
Allow audio recording

### ISSUE THREAD

**Issue by nicolasmaia** [commons-app/apps-android-commons#697]
It would be nice if the app could be used for recording pronunciation of words/sentences.

**Comment by nicolas-raoul** [comment]
Have you tried https://lingualibre.fr ?
Would you mind trying it and letting us know how well it performs for you?
Thanks!

**Comment by picsi** [comment]
My poor understanding of French left me a little confused as to what exactly it is. Is it an app? a WikiProject?

**Comment by tobias47n9e** [comment]
Related to: https://github.com/commons-app/apps-android-commons/issues/3

**Comment by hugolpz** [comment]
Hello. The English UI is planed for late June 17. :)

**Comment by nicolas-raoul** [comment]
I just retried the lingualibre website, it is now available in English is usable on mobile (with only a few glitches).
I will thus close this issue, as lingualibre is the best tool for pronunciation of words/sentences.
Thanks! :-)

**Comment by hugolpz** [comment]
@nicolas-raoul : We also published our recorder script under free license for project willing to do thing locally.
- https://github.com/lingua-libre/LinguaRecorder

**Comment by nicolasmaia** [comment]
I still think it would be valuable for Commons to do this. Most people who know Commons don't know Lingua Libre so if they want to contribute with a recording to Commons and can't do it, they might just give up, not knowing of this other project.

**Comment by nicolas-raoul** [comment]
I don't think we should duplicate the pronunciation feature just in case people do not know the right app.
Adding general audio support would be a good idea though, please feel free to subscribe to that issue: https://github.com/commons-app/apps-android-commons/issues/4208
Thanks for caring! :-)

**Comment by nicolas-raoul** [comment]
I also added a FAQ: https://github.com/commons-app/commons-app-documentation/blob/master/android/Frequently-Asked-Questions.md
