### ISSUE TITLE
Option to "anonymize" pictures

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#70]
Pictures reveal a lot about a person, much more than is visible.
An evil dictator with a small software team could easily compare all EXIF camera serial numbers found on Commons to the serial number of all devices sold in the country.

So, how about an option to remove information which is not really needed by Commons?

What we must leave:
- The image itself
- Latitude/Longitude where the picture was taken
- Date/Time when the picture was taken

What we can delete: All of the rest? In particular:
- File name
- Camera serial number
- Camera manufacturer/model/resolution/software/serial number
- Camera settings such flash/ISO/shutter/focal/quality

**Comment by nicolas-raoul** [comment]
Pretty much all of the image manipulation code seems to be here: 
https://github.com/arpruss/sendreduced/blob/master/src/mobi/omegacentauri/SendReduced/Utils.java#L279

**Comment by misaochan** [comment]
Looks good! I'd like to try and test it, but it doesn't say if the code is released under an open source license? Would that be an issue?

**Comment by nicolas-raoul** [comment]
Here it is: https://github.com/arpruss/sendreduced/blob/master/license.txt

**Comment by misaochan** [comment]
Thanks nicolas!

**Comment by brainwane** [comment]
I would very much appreciate this feature.

**Comment by misaochan** [comment]
Sorry guys, I never quite got around to this. :( Any volunteer who wants to take it on would be very welcome.

**Comment by ilgazer** [comment]
I'm working on this.

**Comment by brainwane** [comment]
Thank you!
