### ISSUE TITLE
It is not clear when one uploads a new photo vs. updates an existing one

### ISSUE THREAD

**Issue by pchampin** [commons-app/apps-android-commons#700]
I uploaded photos 3 times in a row with the same title -- I didn't know the title was actually a unique identifier (this is another issue which I commented in #230).

The issue I want to raise here is that:
* never did the application warn me hat I was updating an existing photo instead of uploading a new one;
* instead, I saw (and still see) 3 entries in the "Recent Upload" screen (see attached screenshot);
* to make things even stranger, the 3 entries all display the *same* photo, which is not even the most up-to-date on the website...

To makes the last point hopefully clearer, I uploaded photo A, then B, then A; so the most up-to-date is A, and still the 3 entries display photo B... This is actually how I realized that something was going wrong...

https://commons.wikimedia.org/wiki/File:The_Pinnacles.jpeg#filehistory

![screenshot_20170530-082711](https://cloud.githubusercontent.com/assets/304612/26570754/75ff3c90-4512-11e7-9686-071ba2228e45.png)

**Comment by ShashwatKedia** [comment]
@nicolas-raoul I think this issue has been resolved, as the app now changes the filename if one's already present and also alerts the user to change it if they want to. Could we close it?
