### ISSUE TITLE
Have 'i' buttons next to various upload fields to describe what it does

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#701]
Similar to what the Upload Wizard does, I think doing this might make it easier for new contributors to learn? For instance the 'i' button next to the Title field says "A unique descriptive title for the file, which will serve as a filename. You may use plain language with spaces. Do not include the file extension.", which could help clear up the title vs filename confusion.

**Comment by mebr1416** [comment]
I'm looking into this.

**Comment by mebr1416** [comment]
Note: the (I) on the right side of the Title field. When the (I) is clicked a message shows at the bottom part for short period and disappears.
![screenshot_1501146435](https://user-images.githubusercontent.com/26868644/28663016-d0005708-72c4-11e7-867b-bb20addb8c5c.png)

**Comment by nicolas-raoul** [comment]
Looks good!

**Comment by mebr1416** [comment]
What message should follow the "Description" field?

**Comment by nicolas-raoul** [comment]
How about something like this? :

Please describe the media as much as possible: Where was it taken? What
does it show? What is the context? Please describe the objects or persons.
Reveal information that can not be easily guessed, for instance the time of
day if it is a landscape. If the media shows something unusual, please
explain what makes it unusual.

**Comment by nicolas-raoul** [comment]
The official doc at
https://commons.wikimedia.org/wiki/Commons:First_steps/Quality_and_description#Good_file_descriptions
does not contain much.

**Comment by mebr1416** [comment]
Title Information

![screenshot_1501152273](https://user-images.githubusercontent.com/26868644/28667020-584279b8-72d2-11e7-90e9-fcaeff949120.png)

Description Information

![screenshot_1501152113](https://user-images.githubusercontent.com/26868644/28666949-1ac67ec2-72d2-11e7-8329-c5e3d58c0829.png)

**Comment by nicolas-raoul** [comment]
The text you have chosen is mostly for people who upload scientific images,
which are very unlikely to be taken with a smartphone.
On the opposite, people with smartphones are much more likely to take
pictures of live events and points of interest.

**Comment by mebr1416** [comment]
I've made the changes to the text according to text @nicolas-raoul posted above.
