### ISSUE TITLE
Prevent overwrites: Ask to change file name before upload process begins

### ISSUE THREAD

**Issue by whym** [commons-app/apps-android-commons#703]
Currently, in order to prevent overwriting, if the filename chosen by the user is not available (=filename is already used), we silently add a numbered suffix to it and proceed uploading.

Instead, as soon as the title is entered, we could say to the user "NAME is already used by another file on Wikimedia Commons, and not available any more. We have tentatively changed it to NAME2. Are you okay with this or do you want to choose something else?" (I'm just trying to describe it, of course the UI has to deliver it in a much more compact way.)

Note that we probably cannot remove the check within the upload process entirely, because someone else might occupy the filename between the pre-upload input and the upload process.

**Comment by misaochan** [comment]
Sounds good to me, and yeah we definitely need to still keep the check during the upload process in addition to this. 

We also need to think about how (or if) we want this to impact those who are sharing multiple files at one time - currently AFAIK the app just quietly accepts them all under one title and adds the suffixes.

**Comment by misaochan** [comment]
This might not be needed now if #228 works, along with #604 which will unite Share uploads with in-app uploads. Will check back on it once 2.8.2 has been out for a while.

**Comment by whym** [comment]
We can drop the "Prevent overwrites" part, but isn't it still worthwhile to provide (with lower priority, perhaps)? Sometimes the user thinks of a too simple name (like "Forest.jpg") which coincides with an existing file. When they are asked for alternative saying "It's used!", it might encourage a more descriptive name.
