### ISSUE TITLE
Implement upload tests

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#705]
As suggested by @tobias47n9e after the 2.4 upload crash fiasco. We probably need lots of other tests too, but these ones should be a higher priority IMO.

**Comment by whym** [comment]
I think #555 will be the first step for that.

**Comment by misaochan** [comment]
@whym agreed. @addshore has mentioned that it isn't merge-ready yet though - could you tell us what is missing at the moment, addshore?

**Comment by psh** [comment]
In the process of refactoring related to networking I introduced a class `ApacheHttpClientMediaWikiApi` and felt the need to at least _smoke test_ to make sure that requests and responses are correctly handled.  I used the `MockWebServer` (from OkHttp) to serve up canned responses and assert that requests are well formed at a unit-test level.

https://github.com/psh/apps-android-commons/blob/master/app/src/androidTest/java/fr/free/nrw/commons/mwapi/ApacheHttpClientMediaWikiApiTest.java

**Comment by whym** [comment]
@psh Thank you for working on that. I like the idea of having a mocked server. While there is #555 which is about using Beta Commons for tests, I believe there is nothing that prevents us from having both kinds of tests.

> The XML that I captured came from the API Sandbox

It might be a good idea to leave some links about it as a comment in ApacheHttpClientMediaWikiApiTest.

**Comment by psh** [comment]
OK.  PR submitted.  Its not the upload tests themselves, its all the work to _set you up for success_ given the more specific knowledge.  :)  

See: https://github.com/commons-app/apps-android-commons/pull/763

**Comment by misaochan** [comment]
We now have the ability to upload to a beta server via the new product flavours #857 , so we can proceed with upload tests. :) This task has been assigned for the IEG renewal.

Question: How/when will we consider this task to be "complete"? What should the target be?

**Comment by maskaravivek** [comment]
Had a discussion with @misaochan. Am updating the scope of this task for further feedback and suggestions: 

(1) write a script that uploads a fake image to the beta server and checks for the result. Ideally we want a test that tests the entire upload process from image selection to checking that the image has been uploaded.
(2) Write unit tests for classes/methods in the "upload" package

**Comment by misaochan** [comment]
Just realized that this should probably wait until #604 has been done, to prevent time being wasted.

**Comment by misaochan** [comment]
This can start after #1091 is closed via #1552 , I think. My previous comment was made before we created #1091 as a subtask of #604 . With that subtask done, we can start writing tests for the single uploads, and then add multiple upload tests when multiple uploads are completed.

**Comment by maskaravivek** [comment]
Will pick up the upload tests after 2.8.0 release tasks are completed. :)
