### ISSUE TITLE
Add brief explanation to Nearby Places UI

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#706]
I think it currently isn't very clear to a lot of users what Nearby Places does, and there isn't space in the action bar to make the title more explicit. Perhaps we could have an additional UI component (like a subtitle) to explain the feature?

**Comment by Bluesir9** [comment]
If the explanation text is short enough, we could fit it below the "Nearby Places" text in the actionbar, just like the number of uploads are shown in the home screen below the "My Recent Uploads" text in the actionbar. 

Or we could use something like a tooltip that would come up only the first time the user ends up on the screen.

**Comment by misaochan** [comment]
Yeah, text under the actionbar sounds feasible to me (it could say just "nearby places that lack photos", perhaps?). But not sure if that is in line with UI design guidelines. Hopefully someone experienced in UI design can chime in?

The first-time tooltip is a viable idea also. :)

**Comment by Bluesir9** [comment]
Just attaching a screenshot for reference as to what it could look like:

![screenshot_1504458459](https://user-images.githubusercontent.com/5329780/30005158-cc67c18c-90f9-11e7-8576-a135e34998c6.png)

I have used [this](https://github.com/sephiroth74/android-target-tooltip) library for the tooltip.

**Comment by psh** [comment]
Given the wide variations in screen sizes, we cant guarantee that the message in the toolbar will be fully visible.  I think the screenshot is an example of this.

If we're shooting for a "first run" type of experience, would it be better to use a library like [MaterialShowcaseView](https://github.com/deano2390/MaterialShowcaseView) and walk the user through the functionality, highlighting that you can switch between map and list views, and what the screen is all about?

**Comment by misaochan** [comment]
Thumbs up from me for MaterialShowcaseView. :) Not sure how time-consuming it is to implement, but it does seem like the ideal solution.

**Comment by Bluesir9** [comment]
MaterialShowcaseView looks neat. We could start by using it for NearbyActivity first and probably implement it for other screens as well in time.
