### ISSUE TITLE
Use different branches for new features?

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#713]
I wonder if, instead of merging everything into master, we should use branches for major new features and only merge them into master later on. It would be easier for people to collaborate on a new feature without worrying about all their PRs being "release ready", and also it would be less messy. We could test feature branches longer while releasing hotfixes more quickly, as they won't be intermingled. 

What do you guys think? I think the UI overhaul that @neslihanturan Is planning could go into a branch of its own on this repo. I don't think we have anything else major enough to warrant its own branch currently, but I could add new branches when needed.

**Comment by nicolas-raoul** [comment]
That makes sense when several people collaborate on a big feature indeed.
Another way to work is to pull from someone else's branch. For instance if
someone has a "thefeature" branch, then just create a "thefeature" branch
in your own repo and run git pull theperson's.git thefeature, then modify
stuff and send a pull request to that person.

**Comment by misaochan** [comment]
Thanks @nicolas-raoul . Would it make sense to have a workflow where only bugfix PRs are submitted to master, small/misc new feature PRs are submitted to a "new-features" branch, and large new feature PRs (that involve multiple collaborators) be submitted to their own new branch (e.g. 'overhaul-ui')? And then we could merge the new feature branches into master when they have been tested sufficiently?

Although I could see potential for some grey area and confusion (e.g. which category do Gradle changes fall under?), it could reduce the chances of bugs with new features making it to release, without having to unnecessarily hold up PRs for a long time.

**Comment by maskaravivek** [comment]
IMO, everything should go to master and for release changes can be cherry picked from master. Lots of projects use a similar workflow. Here's a proposal: 
1. Checkout a new branch(release branch[name it to signify the release version]) from the last stable release. Whenever the master is stable enough to make a release directly, the release branch can be cut directly from the master. 
2. Cherry pick new commits onto the new release branch. 
3. Create a changelog as follows. 
```
git log HEAD...origin/<last-release-branch-name> --format="%h : %s - %an" | pbcopy
```
4. Create a tag(with version number) after the release to the play store. 

Also, its a good practise to have a commit just for version bump. The version bump commit should be merged to master and also cherry picked to the release branch. 

@nicolas-raoul @misaochan

**Comment by misaochan** [comment]
Thanks @maskaravivek , it's good to know what other projects are doing. Maybe we should try your suggested workflow first, and see how it goes. 

I usually do create a commit for the version bump  (and another one for the changelog), which are submitted to master via a PR. Ditto with the tag. Or did you mean something different?

**Comment by maskaravivek** [comment]
The only different approach I was suggesting was the creation of the release branches ie. point 1 and 2. :)

**Comment by neslihanturan** [comment]
This question is answered
