### ISSUE TITLE
There's no way to tell what account I'm logged in with

### ISSUE THREAD

**Issue by jhsoby** [commons-app/apps-android-commons#719]
After downloading the app I tried logging in with my normal account ("Jon Harald Søby"), but presumably because of the 2FA problems, I wasn't able to. So I logged in with an alternate account I have ("Jhsoby"), which worked – but once I was logged in, there was no way of telling which user account I was actually logged in with.

I would suggest solving this by appending the user's username to the "Logout" button (which would then need to be able to wrap to two or more lines as needed to accomodate long usernames), but there are probably other and/or better ways to solve it too.

**Comment by misaochan** [comment]
I agree, this would be useful. We currently have plans for adding this to the UI in the future, I believe? Not right next to the logout button, but in the navigation drawer. @neslihanturan @maskaravivek

**Comment by maskaravivek** [comment]
Yes, we were thinking about adding the profile info in the navigation drawer itself. It should be an easy enough change and a great opportunity for beginners to get started with the project. If no one picks it up, will we do it after a couple of days. :)

**Comment by neslihanturan** [comment]
Yes, we talked about it in Vienna but it was out of my mind currently. I can also add it, after I am done with explore thing. It will be very quick feature, I hope.

**Comment by misaochan** [comment]
Sounds good to me! :)

**Comment by jonas27** [comment]
Hi, I could help with this. I did a mockup for how I would implement it (see attachment). Would that be ok?
![show_current_user_mochup](https://user-images.githubusercontent.com/22886831/26865623-d1309c16-4b5d-11e7-9109-ff2a4c9d0d2e.png)

**Comment by misaochan** [comment]
Hi @jonas27 , that looks great to me. :) I wonder if the Username font should be closer to the font that is already being used for the other text in the nav drawer though?

What picture shall we use for the background?

**Comment by jonas27** [comment]
Yes, I would use the font from the other texts (probably standard android.) I just did the mockup in PS because it is faster ;) I took the daily image from the website and set opacity to 70 (I was wondering if the daily images work though, because for me it only showed the commons logo).

**Comment by nicolas-raoul** [comment]
Cool idea!
https://commons.wikimedia.org/wiki/Commons:Picture_of_the_day/Today

**Comment by misaochan** [comment]
Picture of the day would be really nice if it works. I don't think people would assume they had uploaded it, since it's in the nav drawer and clearly decorative - I personally wouldn't, anyway. But maybe we could add an explanation for where it comes from in About?

**Comment by jonas27** [comment]
I just scrolled through the pictures and they are all in a different formats and cropping them would it some cases look silly. So maybe it is better to take a standard picture for the moment. But any suggestions would be welcome.

**Comment by neslihanturan** [comment]
As far as I remember everybody was agreed about adding pic of the day to app in some point. What about pining the pic of the day as first picture of the explore tab? Plus, I think we should add it to naw bar too. Cropping the picture is a good idea I think. However, displaying the user information has higher priority currently.

**Comment by misaochan** [comment]
I agree that the priority should be to display the username, the picture is secondary. We can just pick a placeholder photo til we figure out how to get pic of the day to work. 

@neslihanturan Having the pic of the day in the explore tab sounds good to me as long as it's clearly labeled (so the user doesn't get confused and think that it is near them). But it might be a bit much if it's in both the nav drawer AND explore tab?

**Comment by jonas27** [comment]
Feeling kind of stupid to ask this, but where is the username stored (is it even stored permanently)?

**Comment by misaochan** [comment]
@jonas27 I'm not 100% sure, but it looks like you could get it from LoginTask.java. You could possibly read and store it in onPostExecute().

**Comment by jonas27** [comment]
@misaochan That's what I did for testing (from LoginTask.java). However, I just stored it as static variable, but it should be stored in a persistent manner (I m thinking SharedPreferences) so that it I can retrieve it after the program shut down. I looked at the AccountManager, in particular at meth"getUserData(Account acc, String key)" but I don't have an Account or key.

**Comment by misaochan** [comment]
Taking the username from LoginTask.java and storing it as a shared preference sounds like a reasonable plan to me, unless anyone else disagrees. :)

**Comment by neslihanturan** [comment]
Hi, is there any improvements about this issue? Is anyone still working on it?

**Comment by abhishekd08** [comment]
Can I work on this issue ?

**Comment by neslihanturan** [comment]
Hi @abhishekd08 , thanks for your interest. Actually there is an almost done work for this issue made by @Nethermane , see #826 . However, it breaks tests somehow. If @Nethermane is not willing to continue to this task, you can pick this issue, I think. Are you planning to continue @Nethermane ?

**Comment by Nethermane** [comment]
I was unsure how to complete this issue without breaking tests and where I should go after that. You are welcome to work on this issue.

**Comment by abhishekd08** [comment]
@Nethermane @neslihanturan  Thanks, I will work on this issue but as I am a complete beginner it may take time. If anyone interested to work on this issue can work.

**Comment by jonas27** [comment]
Sorry for not responding sooner. I would suppose shared preferences are still the way to go but they would need to be implemented before.

**Comment by saurabhmithe** [comment]
I would like to contribute for this issue.

**Comment by nicolas-raoul** [comment]
@abhishekd08 Any progress on this maybe?

@saurabhmithe It has been a month so yes, feel free to write code for this and send us a pull request, thanks a lot! :-)

**Comment by JohnKal** [comment]
I would like to work on this issue.

**Comment by nicolas-raoul** [comment]
@abhishekd08 @saurabhmithe Any progress on this maybe?

@JohnKal It has been about a month so yes, feel free to write code for this and send us a pull request, thanks a lot! :-)

**Comment by maskaravivek** [comment]
This is fixed now. Closing the issue.
