### ISSUE TITLE
Gradle.properties file - access exceeds access rights

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#720]
Android Studio currently complains that some parts of build.gradle (e.g. `project.compileSdkVersion`) exceeds their access rights. 

> "Access to 'project' exceeds its access rights"

These Gradle constants are currently being stored in the gradle.properties file. And the values in gradle.properties don't appear to be read. When I was trying to fix the camera issue at #457 , setting the value of `targetSdkVersion 23` in gradle.properties didn't work, and only hardcoding it in build.gradle worked.

I looked around a bit but couldn't seem to figure out what's causing the issue. Does anyone have an idea?

**Comment by misaochan** [comment]
D'oh. The persistent camera issue was caused by me not cleaning the project in between tries, lol. So the Gradle constants do work, they just throw warnings in Android Studio.

**Comment by execptionerror** [comment]
[[Solved] Access to ‘viewBinding’ exceeds its access rights](https://exerror.com/access-to-viewbinding-exceeds-its-access-rights/)
