### ISSUE TITLE
Remind user in title/desc screen that picture must adhere to Commons policies?

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#721]
There is quite a lot of empty space in ShareActivity.java (the screen where you enter title/desc prior to uploading), so I wondered if it could be used for a good cause. 

The web Upload Wizard requires users to tick a declaration stating that the picture is their own work, etc. While I think it would be excessive to require the user to tick it each time they submit a picture, maybe we could have some text under the form fields saying something like "By submitting this picture, I [username] declare that this is my own work, that it does not contain copyright material or selfies, and otherwise adheres to [link]Commons policies." 

Of course, it won't exactly stop anyone who is determined to upload nonsense, but it could serve as a sort of 'friendly reminder' for those who might just have forgotten or are unaware. This was inspired by glancing through the recent pictures submitted through our app on [PetScan](https://petscan.wmflabs.org/?language=commons&project=wikimedia&categories=Uploaded%20with%20Mobile%2FAndroid&ns%5B6%5D=1&max_age=72&sortby=date&ext_image_data=on&file_usage_data=on&interface_language=en&active_tab=&doit=), where one user submitted about 30 selfies. 🤦‍♀️

**Comment by mebr1416** [comment]
Trying to get up to speed with the project...
See screenshot for a fix to the issue...
 ![screenshot_1500543769](https://user-images.githubusercontent.com/26868644/28411547-b96e0222-6d49-11e7-949f-d9f6f2d693ab.png)

**Comment by misaochan** [comment]
Hi @mebr1416 , thanks for taking this up! I like the screenshot, with the exception that the formatting feels a bit strange to me. The license is left-aligned, whereas the declaration is centre-aligned. However, I am not sure how exactly to remedy that. The simplest solution I can think of is just centre-aligning the license as well. Perhaps else someone has a better suggestion?

**Comment by mebr1416** [comment]
Actually both the license and declaration are centre-aligned according to the layout file. If the license had more text you would see so. 

<-------From the Layout File-------------->
<-----the license------->
<TextView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="@string/share_license_summary"
        android:id="@+id/share_license_summary"
        **android:gravity="center"**
        android:layout_marginTop="16dp"
        />
<-----the declaration------->
    <TextView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:id="@+id/media_upload_policy"
        android:text="@string/media_upload_policy"
        **android:gravity="center"**
        android:layout_marginTop="16dp"
        />

**Comment by misaochan** [comment]
Interesting! I would have thought that the license string would move to the centre when a short license name is selected in that case.

@neslihanturan what do you think, should we keep this formatting, or otherwise what would the most aesthetically-pleasing way be to display this text?

@mebr1416 One more issue that I just noticed, could you please change "the above policies" to "Wikimedia Commons policies", and link that phrase to https://commons.wikimedia.org/wiki/Commons:Policies_and_guidelines ? Thanks!

**Comment by mebr1416** [comment]
*Set the alignment of text to "start" making it left for languages that L to R (e.g. English) and right for languages that are R to L (e.g. Arabic).
*Link included.
![screenshot_1500724157](https://user-images.githubusercontent.com/26868644/28490886-9d1c6190-6eed-11e7-9d85-bd6dc2370120.png)

**Comment by nicolas-raoul** [comment]
Great idea!
Small detail, I would write "copyrighted material" rather than "copyright material".
