### ISSUE TITLE
Cannot login if 2FA is enabled

### ISSUE THREAD

**Issue by Linedwell** [commons-app/apps-android-commons#723]
The application currently doesn't allow the connection of accounts with Two-factor authentication enabled (https://meta.wikimedia.org/wiki/Help:Two-factor_authentication). The authentication is rejected because there is no way to enter the Google Authenticator Token. Is this possible to enable this feature in the further releases ?

**Comment by misaochan** [comment]
Hi @Linedwell ,

Yes, we are definitely planning to enable two-factor authentication as soon as we can (see #328 ) but unfortunately we're encountering a few problems with the implementation. Hopefully we'll manage to do it soon!

**Comment by Linedwell** [comment]
Hi @misaochan,
Thank you for the answer, you can close/merge this issue as duplicate of #328 if you want to (I subscribed to it). 
Regards,

**Comment by tobias47n9e** [comment]
@Linedwell Will close and give the other issue the high priority label.
