### ISSUE TITLE
[Minor issue] GitHub organization logo

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#726]
We're still using the makeshift "Upload" logo for our [GitHub organization](https://github.com/commons-app). Given that we have legal approval to use the Commons logo for our app, would it be okay if we switch to using that for our GitHub organization logo? @nicolas-raoul

**Comment by nicolas-raoul** [comment]
Indeed! :-)

**Comment by misaochan** [comment]
Great! :) Any idea where I can download a logo with appropriate size and res?

**Comment by nicolas-raoul** [comment]
I replaced it. It might need a bit of time to refresh :-)
