### ISSUE TITLE
Q & A with original developer

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#735]
Hi @yuvipanda ,

We have a favour to ask of you. :) A few of us were wondering if it would be possible to talk to you about the original codebase, to understand it better, and to figure out how and why things were implemented the way they were. This would help us a lot in future development work, as we're currently still figuring out a lot about the app.

If you are okay with helping us, we can use any medium you prefer for the chat. My vote would be for IRC purely because it's easier to log and refer to it in the future. But if you would rather do a Google Hangout or anything, that could work too. It's not urgent  - any time in the next month or so would be fine.

Thanks - do let us know! :)

**Comment by yuvipanda** [comment]
Heya! Sure! I'll be busy for a couple of weeks or so tho, but IRC sounds great!

Note that when I wrote this I was doing it to learn native android dev, and it was also many many years ago - so unsure if I can be of much help :) If you think something is stupidly done or n00b code, it very probably is! I didn't really know much about what I was doing when I wrote most of this :D

**Comment by misaochan** [comment]
Sure, no probs. Let us know your available times/days when you're free, and we'll try to arrange something. 

And no worries, we're all learning too. ;)

**Comment by yuvipanda** [comment]
Can you shoot an email to yuvipanda@gmail.com and we can sort out
scheduling? Thanks!
