### ISSUE TITLE
Allowing users to send logs to us

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#736]
Currently, if anyone is having a non-crash issue (like not getting any Nearby results), the best way we can help them is for them to send us logs. Unfortunately, the process of sending non-crash logs is quite convoluted and inconvenient for the user - they have to either install a 3rd party app, or get Android Studio running on their computer, etc.

I wonder if there would be a way to have a function in the app that lets a user send us the last few pages of logs tagged with our app name. So for instance if someone is having issues with Nearby, they can select that, insert a comment like how they do with crash reports, and have it sent to us.

 I don't recall seeing this in any other apps, though, so I'm not sure if this is possible or how other apps get logs from users?

**Comment by misaochan** [comment]
Oh, wow. I'm trying to write a walkthrough on using Android Studio to get logs (for non-technical users). But after we switched to Timber, the logs now only display the class name without the namespace as the Tag, e.g. "NearbyActivity" instead of fr.free.nrw.etc. And it seems that when I debug externally, the Application is always `?`

Does anyone know an easy way we can filter for logs from our app currently (that is teachable to non-technical folks)?

**Comment by Bluesir9** [comment]
Would saving the logs to a text file not work? When reporting an issue, the user could just attach that file. Or is that not a recommended practice?

**Comment by nicolas-raoul** [comment]
I believe an app can access its own logcat.
The app could do this when requested:
https://stackoverflow.com/questions/27957300/read-logcat-programmatically-for-an-application

**Comment by misaochan** [comment]
Interesting! That could definitely be a future enhancement.

**Comment by Bluesir9** [comment]
Cool, will try this out.

**Comment by Bluesir9** [comment]
@misaochan How would this functionality work for the user? Would it build on the "Feedback" option provided in the navigation drawer? Or would a new option be added for example "Report Error" or something which would open the email app with a logs file attached?  Or something entirely else?

**Comment by misaochan** [comment]
We definitely need to discuss this prior to implementation. I can think of a few possible options, each with pros and cons:

1. A setting in Settings. The user could turn it on when they want logs to be sent, perform the activities that they want a log for, and then turn it back off. However, there should probably be a constant indicator of that setting being on, since otherwise someone might forget about it. Not sure where it should be stored and how it should be sent to us.

2. Enhancing the Feedback option by taking the user to an activity where they can choose what gets sent as Feedback, instead of sending them directly to a mail app as we currently do. In that new activity, they could either turn on logging, or type manually into a text field (which would function the same way it currently does), and finally send everything via email at the end.

3. New option in Nav drawer - I would not be in favour of this as it feels like bloat personally. But if Option 1 and 2 are unfeasible for various reasons, I'd be open to this.

**Comment by Bluesir9** [comment]
> New option in Nav drawer - I would not be in favour of this as it feels like bloat personally....

Agreed. Adding a new option just for reporting logs doesn't make sense especially when we already have the "Feedback" option there. 

> A setting in Settings. The user could turn it on when they want logs to be collected, perform the activities that they want a log for, and then turn it back off....

That seems like the most user friendly way of doing it, although I am not sure how it would work UI/UX wise. From the top of my head, it could be something like the Battery Saver mode where as soon as the user turns on the "Collect Logs" setting, the entire app gets surrounded by a thin strip indicating that logs are being collected. The user could turn off the setting to stop the log collection and then be taken to the email app with the logs file attached. I am not even remotely sure how to pull that off however. 

Or we could keep things simple in terms of the UI/UX by using a persistent notification with a cross button indicating that logs are being collected. Tapping on the cross icon on that notification or turning the setting off in the settings menu would then do the same thing as mentioned above. 

> Alternatively, if we only want retroactive logs....

This gives me the Android Studio vibe where they ask every now and then about reporting usage statistics anonymously to Google. You can choose to reject it obviously but then you if you were to accept it, you would forget that there is such a thing. The difference in this case being that we will collect the logs on the device continuously and only send them across when the user wishes to which is good. But of course this should be the easiest to implement, unless I am missing something obvious.

**Comment by nicolas-raoul** [comment]
I would be in favour of keeping development effort low, and the easiest
seems to be to put an action button in the settings menu (even though it is
not a "setting", just like Android shows its version number in the
settings), and make it take a logcat and launch an email activity with that
text.

**Comment by misaochan** [comment]
> I would be in favour of keeping development effort low, and the easiest
> seems to be to put an action button in the settings menu (even though it is
> not a "setting", just like Android shows its version number in the
> settings), and make it take a logcat and launch an email activity with that
> text.

This sounds good to me too. I'm not sure how far back we would want to collect them though, should we get everything from the time the app started? That could be very nonspecific, but probably the simplest way.

> The difference in this case being that we will collect the logs on the device continuously and only send them across when the user wishes to which is good. 

AFAIK the code in the StackOverflow link just pulls the entire logcat history since the time the app started, it doesn't need to "collect continuously".

**Comment by nicolas-raoul** [comment]
Pulling the entire logcat history since the time the app started is perfect, I think.
When users encounter a bug, they will be able to immediately get a log for that bug, rather than having to try and reproduce the bug again.

**Comment by misaochan** [comment]
Oh, yeah, good point. I agree. :)

**Comment by Bluesir9** [comment]
So where are we planning to put this action button to trigger the email?

**Comment by misaochan** [comment]
Possibly just a new item in settings with the title "Send Logs" and the description "Send logs to developers via email"? Clicking on it could trigger the email.

**Comment by janpio** [comment]
Great first iteration.

**Comment by Bluesir9** [comment]
Neat, will get started on this then.
