### ISSUE TITLE
Telegram screenshot used as an example of 'proprietary app'

### ISSUE THREAD

**Issue by Matttter** [commons-app/apps-android-commons#740]
I don't think there's a way to fix this without actually doing what it says we shouldn't do, but still, I don't think Telegram (an app under GPL) is a good representation of a 'proprietary app'

**Comment by neslihanturan** [comment]
Actually, Telegram's server-side software is closed-source and proprietary as far as I know. But I couldn't understand the relation between telegram and commons app. Could you please share more information about this issue?

**Comment by nicolas-raoul** [comment]
Well spotted, but...

The trick here is that if we include a real screenshot of an actual
proprietary app in our open source app, it would be copyright infringement.

So I chose a screenshot of an app that "looks" proprietary, hoping that
most won't notice ^_^

Cheers!

**Comment by Matttter** [comment]
That was what I thought, so this can't really be fixed, except if we maybe do a mockup of some proprietary app? Anyway, this is obviously not a big problem so you can close this if you want to

**Comment by nicolas-raoul** [comment]
Anyone willing to create a mockup?
It has to look like a popular mainstream app, and you need to release the picture as public domain (or GNU-GPL), CC-BY-SA is not enough.

**Comment by misaochan** [comment]
@neslihanturan I think he is referring to us using a Telegram screenshot as a "do not upload" example in our tutorial.

@Matttter Yeah, sorry, it's a bit of a Catch-22 as Nicolas explained. :)

**Comment by domdomegg** [comment]
Here's a quick mockup - released into PD via CC0. It's not perfect, so if someone wants to improve please do - but should be good for the purposes it serves and means we can stop using apps that pride themselves on being open source like Telegram as an example of a proprietary app.

![facebookcross](https://user-images.githubusercontent.com/4953590/27517349-f20adcc6-59c2-11e7-8d04-7ecad1c30e15.png)

SVG: https://commons.wikimedia.org/wiki/File:Social_media_app_mockup_screenshot.svg

**Comment by Matttter** [comment]
Looks great! Just one minor issue, I don't think Alex Jones would be proud to have a trip on an electric bus, global warming being a conspiracy and all :D. Maybe J. Jones?

More serious: Telegram indeed prides itself in being open source, but we shouldn't applaud them for the way they handle it, it's as proprietary of a release habit as you could possibly have on an app that calls itself 'open source'. They routinely violate the GPL by not releasing code but releasing binaries with new features for months at a time. Still better than not free at all apps though obviously

**Comment by misaochan** [comment]
That looks great, @domdomegg ! Would you like to submit a PR replacing the Telegram screenshot with this one? Thanks!

**Comment by domdomegg** [comment]
Uploaded SVG with red x, and fixed so the x is identical size to the no selfie pic

https://commons.wikimedia.org/wiki/File:Social_media_app_mockup_screenshot_rejected.svg

(Also released via CC0)
