### ISSUE TITLE
Title/etc UI does not appear, just the picture fullscreen

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#748]
From time to time (like every 5/10 pictures):

- From Android's gallery I send a picture to Commons
- The usual title/description/license UI does not appear. Only the background image is visible
- Touching the screen has no effect

Swiping the app from the apps list is not enough (the same problem still happens when retrying), only force-stopping from the Android settings and retrying solves the problem.

**Comment by misaochan** [comment]
Wow, 5/10? That's quite a lot. Interestingly, I haven't encountered this problem before.

1. What Android version are you using?
2. Do you mean it happens when you select a picture in the Android gallery and tap "Share" and then select the Commons app? Does it happen to you if you select a picture using the upload button within the app?
3. Could we have some logs if possible please? :)

**Comment by nicolas-raoul** [comment]
Sorry I meant it happens around 10% or 20% of the times I upload a picture.
I am on CyanogenMod 13.0 based on Android 6.0.1 on a Nexus 5.
I will try to get a log.

**Comment by nicolas-raoul** [comment]
Just a screenshot for now, so it is clear what I we are talking about
![screenshot_20170625-173811](https://user-images.githubusercontent.com/99590/27583874-e2f55c5c-5b70-11e7-9587-f88a15d6a84a.png)

**Comment by misaochan** [comment]
Does this only happen if you share via the Android gallery app? Or does it also happen if you go into the app and upload from gallery?

**Comment by nicolas-raoul** [comment]
logcat: https://gist.github.com/nicolas-raoul/b357c04e99af3670c6a2089487bad069
Please note that the "Bitmap too large" message is probably unrelated.

**Comment by nicolas-raoul** [comment]
Tried again immediately afterward without stop-forcing the app: Same problem, with the log below:
```
07-01 19:11:01.588   915  2204 I ActivityManager: START u0 {act=android.intent.action.SEND typ=image/* flg=0x8080001 cmp=fr.free.nrw.commons/.upload.ShareActivity clip={image/* U:content://media/external/images/media/71267} (has extras)} from uid 10053 on display 0
07-01 19:11:01.775   483   483 I AppCompatViewInflater: app:theme is now deprecated. Please move to using android:theme instead.
07-01 19:11:01.805   915   925 I art     : Background partial concurrent mark sweep GC freed 14529(931KB) AllocSpace objects, 2(72KB) LOS objects, 29% free, 37MB/53MB, paused 3.096ms total 201.284ms
07-01 19:11:01.805   483   483 D ShareActivity: Input stream created from content://media/external/images/media/71267
07-01 19:11:01.806 26763 26791 D OpenGLRenderer: endAllStagingAnimators on 0x9e34d580 (RippleDrawable) with handle 0xab416580
07-01 19:11:01.855   483   483 I Utils   : File SHA1: 13f206c3b3d19862bdfbfb01200dc80adb0e7b5b
07-01 19:11:01.856   483   483 D ShareActivity: File SHA1 is: 13f206c3b3d19862bdfbfb01200dc80adb0e7b5b
07-01 19:11:01.857   483   483 D ShareActivity: Uri: content://media/external/images/media/71267
07-01 19:11:01.861   483   483 D ShareActivity: Ext storage dir: /storage/emulated/0
07-01 19:11:01.867   483   483 D ShareActivity: Filepath: /storage/emulated/0/nico/tokyo-wan-hanabi/DSCF5001.JPG
07-01 19:11:01.867   483   483 D ShareActivity: Calling GPSExtractor
07-01 19:11:01.870   483   483 W ExifInterface: Skip the tag entry since tag number is not defined: 34864
07-01 19:11:01.870   483   483 W ExifInterface: Skip the tag entry since tag number is not defined: 2
07-01 19:11:01.871   483   483 W ExifInterface: Skip the tag entry since tag number is not defined: 50341
07-01 19:11:01.875   483   483 D GPSExtractor: EXIF data has no location info
07-01 19:11:01.875   483   483 D GPSExtractor: Gps pref set to: false
07-01 19:11:01.954   915   949 I ActivityManager: Displayed fr.free.nrw.commons/.upload.ShareActivity: +228ms
07-01 19:11:02.489 26763 26763 V StateManager: saveState
07-01 19:11:02.489 26763 26763 V StateManager: saveState class com.android.gallery3d.app.AlbumSetPage
07-01 19:11:02.489 26763 26763 V StateManager: saveState class com.android.gallery3d.app.AlbumPage
07-01 19:11:02.489 26763 26763 V StateManager: saveState class com.android.gallery3d.app.SinglePhotoPage
```

**Comment by nicolas-raoul** [comment]
This always happens after #667.
I guess fixing #667 will fix this as well.

**Comment by tised** [comment]
Hello ! I do think that  [#667](https://github.com/commons-app/apps-android-commons/issues/667) can cause problem.

[This](https://github.com/commons-app/apps-android-commons/blob/master/app/src/main/java/fr/free/nrw/commons/upload/ShareActivity.java) extend [AuthenticatedActivity](https://github.com/commons-app/apps-android-commons/blob/master/app/src/main/java/fr/free/nrw/commons/auth/AuthenticatedActivity.java) which have requestAuthToken method.

If it will not execute properly, we will not call onAuthCookieAcquired method in [ShareActivity](https://github.com/commons-app/apps-android-commons/blob/master/app/src/main/java/fr/free/nrw/commons/upload/ShareActivity.java) which are showing us fragment with title, desc etc

**Comment by tised** [comment]
@misaochan app.getMWApi().setAuthCookie(authCookie);

For what needs this request are sent ? What will be if this request doesn't sent

**Comment by misaochan** [comment]
@tised Sorry, I think that is legacy code that I was not involved in writing... Your guess is as good as mine lol.

**Comment by misaochan** [comment]
Does this still happen for anyone in the current beta release? Seems to be fixed for me.

**Comment by neslihanturan** [comment]
I think since #667 is solved, the (possibly) related issue might be also solved. If someone still experience this, then we should consider them separately.

**Comment by misaochan** [comment]
I agree. FTR I don't experience this issue anymore in the current beta release either. Lets close it, if anyone still has problems they can reopen. :)
