### ISSUE TITLE
Filter out irrelevant categories

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#750]
Here are the patterns I can think of right now (feel free to add more):
- https://commons.wikimedia.org/wiki/Category:Media_needing_categories_as_of_16_June_2017
- https://commons.wikimedia.org/wiki/Category:Photographs_taken_on_2015-11-08

![screenshot from 2017-06-27 20-01-00](https://user-images.githubusercontent.com/99590/27584546-6b771af0-5b73-11e7-8f16-45b082be74a1.png)

Implementation will probably be very similar to the now-implemented #47 so you can get inspiration from it.

**Comment by achalshant** [comment]
I'd like to take this up and I'm fairly new to open source. Could someone guide me though how it works here (in terms of code review and code commit)?

**Comment by nicolas-raoul** [comment]
Hi @achalshant 
Thanks for participating!
It is very simple: Just clone the repository, create a branch named for instance "fix750_irrelevant_categories", fix the code, then send a pull request.
A core developer will then review your pull request and merge :-)

**Comment by misaochan** [comment]
Welcome, @achalshant ! Pretty much what @nicolas-raoul said, except I would add that you should fork the repo first, and then do all the work on your own repo. :) Any reasonable commit styles are fine with us.

**Comment by achalshant** [comment]
Thanks @nicolas-raoul and @misaochan I got the following message before committing my branch:

remote: Permission to commons-app/apps-android-commons.git denied to achalshant.
fatal: unable to access 'https://github.com/commons-app/apps-android-commons.git/': The requested URL returned error: 403


Could I get the permissions necessary?

**Comment by misaochan** [comment]
@achalshant was the branch on your own (forked) repo, or on the upstream (this) repo?

The steps are:
1. Fork this repo
2. Clone the forked repo
3. Create branch on the forked repo
4. Commit to the branch on the forked repo
5. Create pull request to upstream (this) repo from the branch on your (forked) repo

You should not be committing directly to any branch on the upstream repo (I personally almost never do that except for versioning/changelog either).

(I see you have successfully submitted a PR already, so in that case never mind, but just leaving this here if there is still confusion. ;))

**Comment by achalshant** [comment]
Got it. Thanks for clarifying @misaochan  :)

**Comment by misaochan** [comment]
Should be fixed I think.
