### ISSUE TITLE
Allow user to edit some attributes of pictures that they uploaded?

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#765]
This is probably a far- future thing, but I wonder if it would be a good idea to allow users to edit attributes of uploaded pictures within the app itself rather than having to enter the browser? We probably don't need to offer all types of edits, we should mostly just want to edit categories, description etc. Should probably also be restricted to images uploaded by yourself to prevent vandalism. 

Not sure how easy or difficult this will be

**Comment by nicolas-raoul** [comment]
Sounds similar to #161 :-)

**Comment by misaochan** [comment]
Oh yup, sorry!
