### ISSUE TITLE
Prevent uploading duplicate

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#77]
This was commented by Revent in my grant proposal announcement at https://commons.wikimedia.org/wiki/Commons:Village_pump#IEG_proposal:_Improve_Upload_to_Commons_Android_app:

> @Misaochan: I have no idea if it has even been addressed, but a minor issue in the past with the mobile apps was editors (presumably unintentionally) uploading 5, 6, or more duplicates of the same image within a couple of minutes, under a numbered series of filenames. A check, of some type, of if the person has previously uploaded the exact same image would be a good thing. (I can't point at an example offhand, since they get speedied quickly). Reventtalk 22:13, 5 March 2016 (UTC) 

Do you think this could be fixable @nicolas-raoul ?

**Comment by nicolas-raoul** [comment]
I often have the same problems with the desktop uploader as well: I don't remember whether I uploaded that historical picture that I took in 2003, and it is not always easy to find it via categories or upload date.

The best would be to have a API that says whether a picture (identified by its SHA1 hashcode for instance) is already in Commons or not.

Related: http://opendata.stackexchange.com/questions/5279/live-database-of-checksums-of-all-files-on-wikimedia-commons

**Comment by misaochan** [comment]
Oh, that makes sense, thanks! It seems no appropriate API has been found for that yet though?. :( Maybe we could suggest the creation of such an API as a future Outreachy/GSoC project, haha. 

Do you think there is any viable shorter-term fix for this? I was thinking of just checking for filepath, but that would not be good since selecting a file doesn't mean it's uploaded, it will only be uploaded if they pass the title/desc screen.

**Comment by nicolas-raoul** [comment]
Yes, no API found. Asking on Commons would increase the chances of finding, though.

If no API is available, a local persistent database of checksums could be better than nothing.

**Comment by misaochan** [comment]
I'll try to ask at the Village Pump. :)

**Comment by misaochan** [comment]
@nicolas-raoul I received two answers from my post at the village pump https://commons.wikimedia.org/wiki/Commons:Village_pump#March_09 :

1. https://commons.wikimedia.org/w/api.php?action=query&list=allimages&aisha1=801957214aba50cb63bb6eb1b0effa50188900ba
2. https://commons.wikimedia.org/wiki/Commons:User_scripts/File_Analyzer

The first one seems fairly straightforward - we query the API for the hashcode and if it returns null then the picture is original, if it returns a result then the picture is a duplicate, right? What do you think of using the first one?

The second one might be good but I don't know if the browser-based tool can be used via API, I'd have to ask him.

**Comment by misaochan** [comment]
Also, what would be the best response if a duplicate pic is detected? I'm thinking that when they try to proceed from the title/desc screen (upload only starts after you proceed to categorization screen), we warn them that this picture is a duplicate and ask if they want to continue? 

Or should we not give them that option and say "Sorry, this pic already exists, try uploading a different one"? But that would depend on how failsafe the API above is. There might be some false positives, which would prevent uploading of original pics.

**Comment by nicolas-raoul** [comment]
Ideally for time efficiency, we should start checking right after the title/description screen has loaded, and show a popup saying "Sorry this picture has already been uploaded".

There are no false positives.  3.4*10^−39 to be exact.

**Comment by misaochan** [comment]
Ah, okay, so we want to interrupt as soon as we can, then? And the user should only be able to click 'OK' and go back to the main screen?

I think I might alter my proposal draft to include this functionality, do you think 40 hrs is sufficient for it?

**Comment by nicolas-raoul** [comment]
The API already exists and a single toast+activity change are required, so with exception handling (skip the check if any exception happen) and testing 40 hours should be well enough, I think :-)

**Comment by misaochan** [comment]
Great, thanks! :)

**Comment by misaochan** [comment]
Done. I strongly feel that we should use a 'soft warning' first - the user is able to choose to proceed if they really want to. After this feature has been released for a while and there are no bugs found, then maybe we could switch to a 'hard warning' that doesn't allow the user to proceed. But I don't want to do this before it has been live tested for a while, because I worry that there might be bugs that label a file as 'existing' when it doesn't.
