### ISSUE TITLE
One-time popup asking for feedback on renewal proposal?

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#791]
I wonder if it would be a good idea to implement a one-time popup asking for feedback on the IEG renewal proposal? 

Benefits:
- It would be good to get input from existing users on our planed implementations, and many of them don't read mailing lists or the village pump. All users will also have Wikimedia accounts, whereas many don't have github accounts
- Endorsements, haha

Disadvantages:
- People might find it annoying
-  It might feel a bit like an advertisement. However, Wikimedia posts notifications about donations, planned events or community voting etc on Wikipedia, so I imagine it wouldn't be wrong in principle

**Comment by Ainali** [comment]
As a user I would feel included if such a popup came up, since I would feel my input was valued, especially since I have vested interest in the app itself.

**Comment by misaochan** [comment]
@Ainali Thanks for the feedback! In that case I will look further into getting it implemented. :)

@maskaravivek and @neslihanturan what do you guys think?

**Comment by VojtechDostal** [comment]
It's a very good idea, it's a great way to include users into the development. 

I am a bit afraid of the cumbersome editing environment on mobile. If we link users to the IEG page (section Endorsement), we might run into troubles with unexperienced users adding gibberish. Is there an easier way to submit feedback on a mobile phone to wiki pages?

**Comment by misaochan** [comment]
Good point re: inexperienced users, @VojtechDostal . Unfortunately I don't know of an easier way - AFAIK Wikipedia has in-app editing capability but I believe that only works for Wikipedia articles and not meta-wiki. Hmm.

**Comment by VojtechDostal** [comment]
Instead we could 
1/ ask them to give feedback on a special page which is not so vulnerable (https://meta.wikimedia.org/wiki/Grants:Project/Improve_'Upload_to_Commons'_Android_App/Renewal/User_feedback) or 

2/ start a special discussion thread on this via some external service or 

3/ link to a GitHub issue (of course, registration required) or 

4/ create a Flow discussion page somewhere (Flow is more easily editable than wikitext discussions. See https://www.wikidata.org/wiki/User_talk:Frettie for showcase of what it is)

**Comment by janpio** [comment]
Side remark: Maybe adding a temporary link to the Renewal page here on the Github would be useful as well. Probably not much traffic, but the people that see it probably are at least somewhat interested.

**Comment by neslihanturan** [comment]
My vote is for first advise of @VojtechDostal . Additionally, I agree about adding link to the github project short description.

**Comment by misaochan** [comment]
I have modified the Readme, thanks for the suggestion @janpio . :)

@VojtechDostal will the WMF grants committee consider endorsements on external pages or special pages in their decision, or is that mostly just for us to get feedback for ourselves? Even if it's just for us, it could still be worth doing, but in that case perhaps we could just link the Google group forums?

**Comment by VojtechDostal** [comment]
Josephine, this shouldnt be a problem for the committee. They are rather
sensible about this sort of things.

Dne 19. 7. 2017 18:28 napsal uživatel "Josephine Lim" <
notifications@github.com>:

**Comment by neslihanturan** [comment]
If we can describe the scope of the issue, I can work on it very quick. Will it be a time dependent or update dependent pop up screen? 
- When we will display it?
- At where we should display it?
- What should we write on it?
- Will we redirect users to browser view the page via link?
- Is it okay for everyone if we promote our twitter/facebook account on the same pop-up window?

I think we should display it once at on home screen and we should add it as an item to the hamburger menu temporarily. Because user may ignore it accidentally, so we still should provide a channel to go to the link from hamburger menu. 
We can write some text to emphasize importance of their idea for us, instead of just a regular "do you want to join our survey" text. Maybe we can draw a sweet icon (I can do this) and add it to pop up window to take their attention.
I think we should add twitter and facebook pages to same window instead of new annoying pop-up.

**Comment by misaochan** [comment]
I would vote for time-dependent (perhaps until the end of July). We can still take it out during the next update, but at least then we don't HAVE to make a separate update just to take it out when the results have been released for the proposal.

-  It should only be displayed once. That is crucial IMO.
- I don't mind where it is displayed, your suggestion sounds good to me @neslihanturan 
- What to write on it - "We are planning several new features and improvements for the app! Have your say at [link]" perhaps?
- Redirect to browser? - it depends on what page we have chosen to collect the feedback on. 
- I think that is too much information in one dialog window. I would provide one and only one link in that window.

The icon would be nice, if you have the time, otherwise not essential. :)

I agree that we should not have additional popups for announcing our twitter and FB channels. IMO those could be placed permanently in, say, the nav drawer (or the About page) once we have established those channels.

**Comment by misaochan** [comment]
I've been thinking about how best to display this message. If we use a dialog box, we could say "We are planning several new features and improvements for the app! Would you like to view them and have your say? (will open a browser page)", and have the negative action button say "no, and never show again", and the positive action button say "Sure, take me there!"

I'm not sure how we can handle two different links (one for the proposal and one for the feedback page) in a dialog box though. We could still link to the proposal in the text and have the positive action button take users to the feedback page. Or alternatively we can just copy the "scope" section of the proposal to the feedback page I guess.

**Comment by neslihanturan** [comment]
Oops, accidentally deleted your comment @misochan :( I was trying to say that I agree about adding scope to feedback page and giving only feedback page link. And adding social media accounts permanently is also a good idea

**Comment by whym** [comment]
I don't know if there are many enough, but how about showing the notification to the beta testers only? Beta testers are less likely to be surprised/annoyed by such a notification, and more likely to be familiar with wiki-editing and the nature of Meta Wiki.

**Comment by misaochan** [comment]
Wow, thanks @whym, that might actually work! There are 174 beta testers so indeed I think the numbers might be enough to make a significant impact. 

@neslihanturan @VojtechDostal what do you think? We could probably just link the positive action button directly to the proposal in that case. And I guess in the worst case scenario, if we get a few clueless editors still, we can always revert the change? (Though it does reflect poorly on us if such a demonstration of vandalism happens on our own proposal page, heh)

**Comment by neslihanturan** [comment]
I also couldn't find a way to restore your comment, so decided to add it here manually. Quote from @misaochan :

>  I've been thinking about how best to display this message. If we use a dialog box, we could say "We are planning several new features and improvements for the app! Would you like to view them and have your say? (will open a browser page)", and have the negative action button say "no, and never show again", and the positive action button say "Sure, take me there!"
> 
> I'm not sure how we can handle two different links (one for the proposal and one for the feedback page) in a dialog box though. We could still link to the proposal in the text and have the positive action button take users to the feedback page. Or alternatively we can just copy the "scope" section of the proposal to the feedback page I guess.

In reply to previous comment, I think direct link to proposal page can be too much to read for user. We can create a feedback page as @VojtechDostal proposed, and give one link to that page on dialog window. We can write some introduction to encourage them to share ideas and include list of our new features in it. Because, there is several details that users don't care on original proposal page I think.

**Comment by akaita** [comment]
If I might put my 2 cent: I think asking for feedback is OK as long as it is not annoying to the user.

So, when is it annoying and when is it not annoying? 

- Showing multiple times: annoying
- I just downloaded the app and you already ask me for feedback: annoying
- I'm a beta tester and you ask me for feedback: kind of OK, although I would prefer to just have a link I can use whenever I choose to

Summing up, I think adding a link the user can use would make sense. If proactively asking the user, it should be when the user already had a chance to use the app for a bit (after opening it 5-10 times?).

**Comment by misaochan** [comment]
Hi @akaita , thanks for the feedback. We plan on only displaying the popup to users who have signed up for beta testing - the beta version with the popup will never be pushed to production (speaking of which, I need to make a note to remind myself about that....)

Is it common for people to sign up for beta testing without having tried to use the app at least 5 times?

**Comment by akaita** [comment]
I might be missing something here 🤔 
I think that when people takes an action, they expect the result to that action to come first. I mean, when I sign-up to a beta, I expect to get and test the beta; getting a pop-up as soon as I open an app for the first time is always annoying to me, nevermind whether it is a beta or not.

Anyway, I guess there is more flexibility with beta users, so just experimenting to find what works best with this specific population sounds ok.
I'm wondering, would there be a way to know whether this technique worked or not? Maybe set some estimation on the amount of feedback we expect, relative to the feedback received by some other project using a different technique?

**Comment by misaochan** [comment]
Oh, sorry I missed the point, @akaita ! Yeah, there is a possibility that someone might sign up for beta recently and then get the popup before they've had the chance to do much else. Perhaps it might be beneficial to find a way to delay the popup so it isn't the first thing users see. E.g. have it triggered by some action, like a successful upload or when they load, say, the Nearby screen.

It would be interesting to be able to assess this technique, but the amount of feedback expected would vary depending on how long the popup is around IMO.

**Comment by neslihanturan** [comment]
What about adding a notification to top of home page? Seems less annoying to me. If user clicks to the notification, we can display the window?

**Comment by misaochan** [comment]
I am OK with that if there is a way for the user to dismiss that message and not have it show up again. The main concern with UI modifications is that it would take more time (for development and testing) than this task might actually warrant IMO. That is why I think a popup would be easiest.

**Comment by neslihanturan** [comment]
Okay, so last decision:
- removing remind me later option
- displaying the notification on 3rd time starting the app?

**Comment by misaochan** [comment]
Yes and yes IMO.

**Comment by misaochan** [comment]
Final suggestion from my part, if this is not too much trouble - in addition to the popup, add a link to the proposal in the navigation drawer ("Reviews", underneath Feedback).

Then modify `<string name="feedback_popup_description">We are planning several new features and improvements for the app! Have your say.</string>` to `<string name="feedback_popup_description">We are planning several new features and improvements for the app! Would you like to review them and provide feedback? (You can always access this by selecting "Reviews" in the navigation drawer)</string>` 

This is the easiest way for users to be able to say "no" but go back to it if they want to later IMO.

**Comment by neslihanturan** [comment]
@misaochan , could you explain Developer plans addition to navigation drawer deeper? How shoud it look like?

**Comment by misaochan** [comment]
Just an item under "Feedback" and above "Logout" that says "Developer plans" (you choose what icon you want, I'm okay with anything).

**Comment by janpio** [comment]
(Note from a PM-by-day person: The "Developer plans" link in the drawer feels feature creep her and only half thought out. It should probably be discussed and implemented in another issue. [Personally, I would expect something like that in "About"])

**Comment by misaochan** [comment]
Fair point @janpio . @neslihanturan what do you think? Shall we just put in the popup first and then discuss the nav drawer link separately? You can still keep the work you've done (if you've started on that), just move it to a different branch.

**Comment by neslihanturan** [comment]
I added the commits actually, you can see here #808, almost 2 hours ago.

**Comment by misaochan** [comment]
I think the popup has served its purpose by now. :) Would anyone like to remove the popup and nav drawer link? We will have more information about funding soon (I will be talking to the grants admin next Friday), and in the case of funding being approved we might have a release in a few weeks' time, so it would be good for this to be removed by then.
