### ISSUE TITLE
2., 3. and 4. German tutorial screen show "u2022" 

### ISSUE THREAD

**Issue by janpio** [commons-app/apps-android-commons#792]
instead of what should actually be there. (Dots?)

Version 2.4.2, fresh install from Play Store

**Comment by janpio** [comment]
Seems translation is happening on translatewiki.net (maybe add link to projects in README?), will look there further.

**Comment by janpio** [comment]
Found the strings here: https://translatewiki.net/w/i.php?title=Special:Translate&group=commons-android-strings&language=de&filter=&action=translate with filter for "u2022".

Unfortunately I only get "You need translation rights to translate messages. Get permission" as I had to create an account there. No idea what I need to do to get this. ("Get permission" links to a page where I can translate random stuff which I did for >10 keys, but no change - so this isn't a tutorial or anything.)

**Comment by janpio** [comment]
Noticed a "You need to provide more translations to complete your registration." on the homepage of Translatewiki...

**Comment by janpio** [comment]
Aha: "You reached the translation limit for new translators. Our team will verify and upgrade your account soon. Then you will be able to translate without limits." I'll wait then.

**Comment by janpio** [comment]
"Hi Sujan,

Thank you for applying as a translator at translatewiki.net. I regret to inform you that I have rejected your application, because the quality of your translations did not meet the requirements.

If you think that your application was rejected by mistake, please try to apply again as a translator at translatewiki.net. You can sign up here:
https://translatewiki.net/"

Account deleted. 

Always nice to try to work on Wikipedia/Mediawiki projects...

**Comment by janpio** [comment]
Nice guy in IRC helped me out to get the new account approved.

Made the necessary changes to the 3 keys that included wrong content.

Now how to get these commited here? 
Is this done automatically?

**Comment by misaochan** [comment]
@janpio thanks for the changes. I believe the translatewiki team incorporates the changes into commits here twice a week. Those commits then need to be included in a release for them to be available to the public - I haven't had time for frequent releases recently, but I'm hoping to do one at the end of this week or next week. So, hopefully they will be out then! :)

**Comment by janpio** [comment]
Awesome :)

**Comment by janpio** [comment]
I will see that I monitor the commits a bit and close this issue when the changes made there way into the value-files.

**Comment by janpio** [comment]
Latest commit from translatewiki included the changes I did for the DE translation:
https://github.com/commons-app/apps-android-commons/commit/f73a9f15fc39152d99a542eb785894ed6471021d#diff-cdca861e65ab0caf0dac48368b3fa2a6R122
