### ISSUE TITLE
Creating our own social media page?

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#799]
Now that we have a significant userbase and community around the app, I wonder if it might be a good idea to create a social media page for ourselves? Facebook would be easy I think, we don't even need a separate account for the page, so I could create, say, a "Commons app" page and then invite anyone who is interested here to be an admin for that page. Then anyone who wants to get updates from us can just follow our page. Twitter I am not so familiar with, perhaps we would need to set up a separate account, which could be troublesome (perhaps anyone who is familiar with Twitter can verify?).

What do you guys think? I think it might simplify update announcements, and make it easier for those who are currently sharing updates about us on social media (e.g. @VojtechDostal and @tobias47n9e ) because they can just share an existing post instead of having to write their own. And it is easier for some people to browse FB or Twitter than it is to subscribe to mailing lists or to a Google group.

On the other hand, it would take some extra work (one more place that we need to keep updated), so not sure if it would be worth it at this stage?

**Comment by neslihanturan** [comment]
My vote is for Twitter because we can publish our release notes from there. So, rss like environment is much convenient for us. If we can reach enough number of users, we can get feedbacks from there or apply surveys. 

What about adding our Twitter page to the pop up we discuss at #791 ?

**Comment by misaochan** [comment]
Sounds like a great idea to me! However, we don't have a Twitter page yet. :) Would you like to create one?

**Comment by neslihanturan** [comment]
Sure :), but I will wait until this evening to make sure everyone is okay.

**Comment by misaochan** [comment]
Sounds good, we can wait for a couple of days even, no rush.

Do you know how Twitter permissions work? For instance if you create a Twitter page for "Commons app", can only you post under that name, or can others post as well? Sorry, I am very new to Twitter. :)

**Comment by neslihanturan** [comment]
Well, it is not possible by using Twitter web interface. We can share the password between us, however, two factor authentication wouldn't be possible under this case (super unsafe). On the other hand, Twitter servers may have hard times to understand several logins from different parts of the world and may kick us out. 

There is [tweetdeck](https://tweetdeck.twitter.com/) for such managements. Tweetdeck has crew management property, admin can give some permission to other accounts. Without sharing password (as far as I remembered), so even if account of some of us is stolen, no problem admin can fix everything.

**Comment by VojtechDostal** [comment]
I'd still create a Facebook page and at least automatically post from
Twitter. Facebook has a large presence among wikimedians.

Dne 20. 7. 2017 12:43 napsal uživatel "neslihanturan" <
notifications@github.com>:

**Comment by nicolas-raoul** [comment]
Good idea!
Why not both? :-)
And maybe networks followed by photographers of all kinds, such as
Instagram or Pinterest?

Josephine, I suggest you register with the app's name in all of these
network and keep the passwords preciously.
Even if you don't plan to use them immediately.

I manage the accounts for several open source projects and products at my
company, and in my experience it can take quite a lot of time as people
start asking questions and interacting.
So I highly suggest you delegate community management to a trusted
non-developer (similarly to how we recruited people to moderate the mailing
list), and give them the appropriate rights, without sending them your
password of course.

The community managers should be present on the mailing list, ideally
follow recent happenings Github-side (solved issues, beta releases) and
Wiki-side, in order to post news when they see fit. They might be able to
answer simple questions, but for most questions the answer would probably
be "Please ask on the mailing list here" or "Please create a new issue
here".

Cheers!
Nicolas Raoul

**Comment by misaochan** [comment]
Thanks for the input, guys!

@nicolas-raoul Our mailing list is actually moderated by Neslihan, haha. But yes I see your point, and I agree.

I think moving forward from here, I will create the FB account and @neslihanturan will create a Twitter account? I will announce in the Google group forums (and here) that we would like a volunteer to manage the FB community. I don't think any password sending is necessary, I can just add them as an admin. 

Neslihan can handle the Twitter account (by personally posting or by delegation) as she wishes.

**Comment by misaochan** [comment]
Thanks @VojtechDostal for setting up and updating our Facebook page and group! :) If anyone is interested in joining:

Group: https://www.facebook.com/groups/472189063132928/
Page: https://www.facebook.com/WikimediaCommonsApp/

Now that that is done, we should probably publicize the page/group a bit. What do you guys think about adding a link to our website, and perhaps to our nav drawer in the app?

@tobias47n9e @neslihanturan

**Comment by VojtechDostal** [comment]
I am taking all suggestions for Facebook posts guys! :-) I will try to be inventive myself. I plan to post updates on the technical improvements planned and done. I might also post showcases of uploaded pictures. We can also post various reports or blog posts :)

**Comment by VojtechDostal** [comment]
I am happy to create the Twitter account and post automatically from Facebook. I need an e-mail address for that. Do we have one or should I create one for this purpose?

**Comment by misaochan** [comment]
Nope, we don't have an organization email AFAIK. Would be great if you could create one, thanks @VojtechDostal ! :)

**Comment by VojtechDostal** [comment]
I created the following Twitter account: https://twitter.com/wikicommonsapp

If someone wants to use it, please contact me. 

In the meantime, I set up automatic crossposting from Facebook, so anytime our Facebook page posts something, it will be published on Twitter as well.
