### ISSUE TITLE
Option to specify latitude/longitude

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#8]
A "GPS" button could be shown if the picture does not have coordinates info already. Getting the coordinates automatically (with a preference to disable that feature for privacy reason) would be OK too.

A map showing the location would be wonderful, even more so if it allows to touch the real location (GPS is often wrong, or I might want to pinpoint the object itself rather than the location I shot it from)

**Comment by ashishkumar468** [comment]
Seems to be implemented in the latest release, closing this issue, feel free to re-open if I have misunderstood

**Comment by nicolas-raoul** [comment]
This feature is not present in the latest release, I have never seen this being implemented (but I could be wrong so please let me know if this is actually available).
The latest release only contains a feature that opens your map app at the location of the picture. It does not allow to pick a better location.

**Comment by Ayan-10** [comment]
@nicolas-raoul @madhurgupta10 Can I work on this issue?

**Comment by nicolas-raoul** [comment]
@Ayan-10 Yes thanks! :-)

**Comment by Ayan-10** [comment]
Hey @nicolas-raoul @madhurgupta10 , I am done with the "update coordinate feature" part of this feature. I put a dummy latitude and longitude for implementation and testing the coordinate update API calls. You can see this feature working in the video I attached.

https://user-images.githubusercontent.com/71203077/118808134-c4d10480-b8c6-11eb-8568-85e382c75598.mp4

**Comment by Ayan-10** [comment]
@nicolas-raoul @madhurgupta10 Now I was thinking about making a location picker from where user will get their preferable location if they click on the FAB. (Now the app this feature is working on a dummy location). For creating this part of the feature I can use google play-services-location and google maps API key. Should I move forward with this idea of implementation?

If you have any suggestion of creating this part of this feature. You are welcome.
Thanks.

**Comment by nicolas-raoul** [comment]
When I created this issue I mostly had in mind the upload wizard (set the location of the picture you upload), but editing the location of an already uploaded picture is a good feature to have, too. Feel free to switch to developing for the wizard (merit: higher priority), or keep developing for editing (merit: keep the work you have done), as you wish :-)

We want our app to work even on devices where Play Services is not installed. I wonder what would be the best way to proceed here. How about using the same map technology as the Nearby feature is using? https://docs.mapbox.com/android/plugins/examples/place-picker/

**Comment by Ayan-10** [comment]
@nicolas-raoul Ok I understand. I will implement both of the features (upload wizard and edit). As I am almost done implementing this feature, I will make a PR for this. Then I will work on the upload wizrad.

Actually, This is a subtask of my this year's GSoC proposal. My proposal did not get selected for this year. So I decided to implement all of the tasks that I proposed to do in my this year's GSoC proposal.

**Comment by Ayan-10** [comment]
Thanks for sharing this mapbox. This will be a great way to implement the location picker feature.

One more thing. Can you little elaborate me about the upload wizard that you mentioned. You meant that there should be a feature in the app that will allow user to upload location while uploading image. Am I right?

**Comment by nicolas-raoul** [comment]
Wonderful! If you want to focus on editing, feel free. But if you want to try on the upload wizard too, here is how I would suggest to implement that UI part:

Can you see the map icon below (blue squarish button)?
Right now, it opens the location with an intent, which means the default map app opens (for instance Google Maps).
I suggest modifying the UI so that this button opens a Mapbox map showing the location, with two buttons at the bottom:
- "View in map app"
- "Modify location" <- this one lets the user pick the location. Once picked, the button could be hidden and a "Confirm" button shown instead, that would go back to the screen below while remembering the edited location (to be used in the location template and location-based category suggestions).

![adb](https://user-images.githubusercontent.com/99590/118826379-691e6f80-b8f6-11eb-9db9-d1b74fd7b975.png)

Minor detail, I would suggest a pencil icon here rather than the "sight" icon:
<img width="349" alt="Screen Shot 2021-05-19 at 23 12 26" src="https://user-images.githubusercontent.com/99590/118827937-ca930e00-b8f7-11eb-9a14-f45b98ed488f.png">

**Comment by Ayan-10** [comment]
Thanks for guiding @nicolas-raoul . I am fully done with implementing the edit coordinates feature. I want to make PR now. Should I create a separate issue for that because As you said this issue is not about the feature that I implemented. I think creating an issue for this particular feature will be better.

**Comment by nicolas-raoul** [comment]
Wonderful!
Don't worry, it should be fine here to have a single PR for this issue + an extra but very related feature.

**Comment by Ayan-10** [comment]
@nicolas-raoul I made the PR of the edit coordinates feature. Please check out #4418 .

**Comment by Ayan-10** [comment]
@nicolas-raoul I am almost done with implementing this feature. I used the location picker for picking the location. Now, after implementing it. The feature is working like this

1. Click the blue map icon.
2. Show a dialog containing two buttons "View in map app" and "Modify location".
3. "View in map app"  the default map app opens to show the location.
4. "Modify location" Location picker opens with showing the current location (If available) and if the user changes their location and presses the tick button. The location will change. Otherwise, It will remain the same location.

Is it ok? If you want to make me any change here. Please let me know.

**Comment by nicolas-raoul** [comment]
@Ayan-10 Sounds good! 🙂

**Comment by sivaraam** [comment]
If I understand this correctly, @Ayan-10's work right now is to only allow editing the corrdinates of an image which already has location information associated with it. In that case, ...

> "Modify location" Location picker opens with showing the current location (If available

... I feel it might be less helpful for "Modify location" to initially show the current location. It would be better to start with the location coordinates in the image. We could indeed show the "Locate me" bull's eye icon to easily go to the current location if you feel that would be necessary. I'm not sure if it is necessary but let's just not start with the current location, though 🙂

**Comment by Ayan-10** [comment]
@sivaraam Sorry for not being clear. Hereby saying "current location" I mean current image location. What you are proposing me to do I said the same thing in the above comment. Hope now I can express my point correctly.

**Comment by Ayan-10** [comment]
<img src="https://user-images.githubusercontent.com/71203077/122715103-0407c200-d286-11eb-805f-bd84d4d0d773.png" width=300/>

@nicolas-raoul What should I write in the message section?

**Comment by nicolas-raoul** [comment]
Sorry here is what I had in mind, a bit more than a popup:
<img width="250" alt="map" src="https://user-images.githubusercontent.com/99590/122716465-3ecd2280-d2a5-11eb-99b8-fc391b640e7e.png">
Seeing this, the user can decide whether they want to modify the location or not. Ideally it could be the same activity as the edition activity, with the buttons hiding (and other UI dynamic modifications) when needed, so that the user does not lose their zoom/position.
