### ISSUE TITLE
Are photos marked as "own work"?

### ISSUE THREAD

**Issue by neslihanturan** [commons-app/apps-android-commons#800]
As some of you knows, in near past my account had been blocked because of my bunch of test uploads. But one of the notification was "It is not clear that these are your own work, please mark them as your own work". Does our app mark them as "own work" on every upload? If not, I think we should definitely do it. 

And one notification was "Please select a license" where I already choose. I think this might be related with latency of licenses being saved. Do you also experience such situations?

**Comment by misaochan** [comment]
Interesting. I have never experienced such an issue and I upload almost exclusively with the app. If there is indeed an "own work" tag, we should incorporate one in our app, but only after we include the declaration in #721 IMO.

Could you point to a recent picture without a license and create an issue for it please? Thanks!

**Comment by neslihanturan** [comment]
They are removed during block process and I am not planning to upload test pictures in near future:) But I still have my notifications on my user page.

**Comment by nicolas-raoul** [comment]
My pictures are marked as "Own work", at least the last one I uploaded from
the app:
https://commons.wikimedia.org/wiki/File:Lantern_festival_in_Odaiba_on_Marine_Day.jpg

**Comment by misaochan** [comment]
Oh, it is under "Source". Yes, mine are marked as "own work", too.

**Comment by neslihanturan** [comment]
Hmm so they were complaining about pictures inside of pictures. I would request for undeletion if my VPN wouldn't be broken at that time. Thanks for clarifying, so I am closing the issue.

**Comment by nicolas-raoul** [comment]
Maybe they considered that the street art is not your own?

**Comment by whym** [comment]
Right, it would be prudent to exclude street art if freedom of panorama
doesn't apply. In that case it would be new uploads rather than seeking
undeletion.

**Comment by neslihanturan** [comment]
Actually I was sure it was an non-licenced street art but I see, thanks all of you for clarification. I will be much more careful on uploading photos of works of others.
