### ISSUE TITLE
Docs in repository instead of Wiki?

### ISSUE THREAD

**Issue by janpio** [commons-app/apps-android-commons#801]
I am just starting to read through the wiki and repo to get an understanding what is what, what works how, what is stored locally, which APIs are used etc. Derived from the current state I would probably document this in the wiki.

But I think it could be beneficial to have simple .MD files in /docs that could contain all that information instead of the wiki. It would have the advantage of being connected to the code it describes and being versioned in the same way. 

Do you think this is useful and should be done?

(Also it could be used to add a publicy available docs page via Github pages if this is wanted)

**Comment by janpio** [comment]
After having type this, the disadvantage of using files in the repo instead of the wiki of course is that it is much easier and faster to just edit the wiki instead of forking the projects, making your changes, and then sending a pull request.

**Comment by nicolas-raoul** [comment]
How would wikilinks work with .MD files in /docs ?

**Comment by janpio** [comment]
Wikilinks = links between pages? 
Then as usual. .md files are automatically rendered on Github, and links to a `test.md` file link to the correct path automatically.

**Comment by janpio** [comment]
Ah, now that I actually used the Wiki a bit I understand: You can "wikilink" words automatically in Github wikis as well - wasn't aware of that before. In .md files that really would not be possible, you would have to use filenames (relative or absolute) everywhere.
