### ISSUE TITLE
Shrink images in the main screen (contributions list) instead of cropping

### ISSUE THREAD

**Issue by whym** [commons-app/apps-android-commons#804]
Currently sometimes images get cropped out in the main screen. (left in the mock up below) They should be shrunken and centered instead. (right)

![untitled](https://user-images.githubusercontent.com/10674/28487270-31ff81be-6ec8-11e7-9ee3-7832003dca18.png)

This was pointed out at https://github.com/commons-app/apps-android-commons/pull/738#pullrequestreview-46125017 by @misaochan. It sounded like older versions of the app did that shrinking, so chances are that we need to debug something instead of doing something new.

**Comment by gupta-meghna64** [comment]
@whym This can be adjusted by setting the image to ImageView dynamically using the java code by maintaining the aspect ratio of the image. Can I work on this issue ?

**Comment by whym** [comment]
Thank you for your interest. If you are asking if it's up for grabs, yes.

"the image to ImageView dynamically using the java code" - this sounds like
a workable solution. I don't know whether you have to write code for that
or using a library feature is enough, but I do think it has to work
dynamically. i.e. image size should change when the device is rotated.

**Comment by misaochan** [comment]
Hi @gupta-meghna64 , yes, please feel free to work on this issue (or any others that you are interested in). :)

**Comment by akaita** [comment]
I don't understand.
The example on the left is doing `center-crop`: make the image as small as possible, preserving the image ratio and covering the whole space.
That looks like the correct behaviour.

Could you use [this reference](http://www.peachpit.com/articles/article.aspx?p=1846580&seqNum=2) to point what scaling type you are expecting here?

**Comment by whym** [comment]
Using a similar wording to that page, my intention was "Scales the image to fit inside the view, while maintaining the image aspect ratio. The larger axis will exactly match the view, and blank will be added the other axis." The images does not need to always cover the whole space. Not sure if this is identical to one of the types described there.

**Comment by akaita** [comment]
Ok, `blank will be added the other axis evenly` means you are talking about `fitCenter`.

In a list, having that kind of blank space would be very strange.
We could avoid cropping the image and also having blank spaces with:

- make image take whole width
- make image's height adapt to show whole image

Would that sound ok?
