### ISSUE TITLE
Move all developer/contributor documentation to Wiki

### ISSUE THREAD

**Issue by janpio** [commons-app/apps-android-commons#811]
Right now there is developer and contributor documentation in at least two places: README and the repo Wiki. I suggest this should be unified in one location, the Wiki. 

That would mean moving the "Develop with Android Studio or IntelliJ", "Build Manually", "Code Structure", "On-Device Storage" and "Translating the app" paragraphs from README to the wiki. The "Volunteers welcome!" should probably stay, and the new wiki pages should be linked in the README under "Developer documentation" or similar (see that wiki homepage, something like that).

Then it is all in one place and README is a lot shorter and more concise.

What do you think?

**Comment by nicolas-raoul** [comment]
I agree!

**Comment by misaochan** [comment]
I agree with moving the docs into wiki and linking to them from the README.

**Comment by janpio** [comment]
(Please assign this issue to me, I will take care of it)

**Comment by misaochan** [comment]
Assigned, thanks @janpio !
