### ISSUE TITLE
Stetho is enabled for release builds - should be changed to debug-only

### ISSUE THREAD

**Issue by janpio** [commons-app/apps-android-commons#813]
While debugging one of my own apps I noticed that Commons app (still running in the background from earlier) includes Stetho and is therefore debuggable using the Chrome Dev Tools.

The only mentions of this I found were [the PR that added this](https://github.com/commons-app/apps-android-commons/pull/594) and [the wiki](https://github.com/commons-app/apps-android-commons/wiki) Home page:

> Viewing tables and shared preferences via debugging with Stetho: Run in debug mode, go to browser, chrome://inspect/#device, select inspect device, Resources tab.

This seems neat. Can someone explain a bit more about its usage, @maskaravivek maybe?

(I would like to add this to the documentation and expand that one sentence on the Wiki home)

**Comment by akaita** [comment]
I myself don't understand your question. Sounds like you are asking [how to use Stetho](https://github.com/facebook/stetho) in the form of [a tutorial](https://code.tutsplus.com/tutorials/debugging-android-apps-with-facebooks-stetho--cms-24205), which is actually explained in your own question: `Run in debug mode, go to browser, chrome://inspect/#device, select inspect device, Resources tab`

Am I missing something here?

**Comment by janpio** [comment]
I was asking what it is actually used for. 
Is it common that this is in production apps for endusers to use?

**Comment by akaita** [comment]
It is used for development, for debugging. I'm nor sure about the confusing part of this explanation, or even the tutorial I liked to.

No, it is not common to allow enduser to use debugging tool. This app doesn't do it either...

**Comment by janpio** [comment]
> This app doesn't do it either...

You should check that again. v2.4.2 from the Play store does.

![image](https://user-images.githubusercontent.com/183673/28736153-dab35cc0-73e8-11e7-9b13-79bc234b4ed7.png)

That's why I am asking...

**Comment by akaita** [comment]
Ha! Something was going on with my browser and didn't show me anything even in debug.
I stand corrected 🙇 

Stetho is indeed enabled for all build types. Probably not very important, but better disable it IMHO.

**Comment by misaochan** [comment]
Yeah, if Stetho is enabled for release builds, we should definitely change that. Hope you don't mind me modifying the title of the issue, @janpio . :)

**Comment by utkarshmttl** [comment]
I think this issue is resolved in #828

**Comment by whym** [comment]
yes, thanks for spotting!
