### ISSUE TITLE
Add app shortcuts

### ISSUE THREAD

**Issue by psh** [commons-app/apps-android-commons#814]
Android app shortcuts seem like a natural way to launch the app and go directly to 

* Nearby places
* Upload from gallery
* Take a picture

![App Shortcut](https://paul.hawke.io/apps-android-commons/wikimedia-commons-app-shortcuts.png)

It should be a matter of _configuration_ rather than large amounts of code - adding a `shortcuts.xml` and making sure that we can launch directly into the given activities.  I am so-so about "Upload from gallery" and think just taking a photo or going to the nearby list might be the most important.

**Comment by misaochan** [comment]
Cool, I actually had no idea we could do that! What SDK level does that require?

Personally "Upload from gallery" is the option that I use more than 80% of the time in the app, I would be for keeping that in. :)

**Comment by psh** [comment]
If the app targets Android 7.1 (API level 25) or higher you can use app shortcuts.  The `gradle.properties` currently has us set to a minimum of 15, and target of 25, so we are good (though we might want to think about bumping the minimum up as API 15 represents only 0.7% according to Google)

I think one killer feature of app shortcuts is that users can create "pinned shortcuts" - an icon directly on the launcher that jumps directly into the app.  If you use the _upload from gallery_ 80% of the time, this would let you jump there in one tap!

Google have some [pretty specific guidance](https://commondatastorage.googleapis.com/androiddevelopers/shareables/design/app-shortcuts-design-guidelines.pdf) on the icons that should live on the shortcuts.  Someone with more artistic talent that me should create the icons. :-)

Google's documentation - https://developer.android.com/guide/topics/ui/shortcuts.html

**Comment by psh** [comment]
Updated the screenshot - icons and starting point for `shortcuts.xml` are on a branch, should someone else want to pick this up and play around with it - https://github.com/psh/apps-android-commons/tree/app-shortcuts

**Comment by misaochan** [comment]
Sounds great to me. Happy to review if anyone wants to pick this up. :)

**Comment by mebr1416** [comment]
@psh I have cloned your repo twice. Both times, all the changes you have done related to app-shortcuts isn't showing on my Android Studio. Is it somehow protected?

**Comment by mebr1416** [comment]
@psh, looking into this..

**Comment by deepak-thakur** [comment]
how can i contribute ? i am a beginner with few months of experience with android.

**Comment by mebr1416** [comment]
I have left this issue for now.

**Comment by nicolas-raoul** [comment]
@deepak-thakur Feel free to fix this issue, see https://github.com/commons-app/apps-android-commons/wiki/Volunteers-welcome%21 :-)

**Comment by adikul30** [comment]
@nicolas-raoul Can i work on this issue or anyone else has already been assigned ?

**Comment by nicolas-raoul** [comment]
@adikul30 Seems like @deepak-thakur is not around for now, so feel free to give it a try, yes :-)

**Comment by tanvidadu** [comment]
@adikul30 u working on this ? I will like to work on this issue.

**Comment by nicolas-raoul** [comment]
@tanvidadu No progress updates from @addshore so feel free to give it a try, yes :-) Please post progress updates every few days, thanks!

**Comment by tanvidadu** [comment]
@psh i checked your branch for creating apps shortcut. Looks as good starting point. Can I work on your branch ?

**Comment by madhurgupta10** [comment]
@nicolas-raoul Can I take up this issue?

**Comment by nicolas-raoul** [comment]
@tanvidadu Any update on this? By the way, you don't really need permission to merge from people's branches (just acknowledging them is nice though) :-)

**Comment by tanvidadu** [comment]
@madhurgupta10 , sure go ahead !  :+1: 
@nicolas-raoul, I haven't worked on this issue since last year  :/

**Comment by nicolas-raoul** [comment]
@tanvidadu OK thanks!
@madhurgupta10 It is yours :-)
