### ISSUE TITLE
OAuth?

### ISSUE THREAD

**Issue by janpio** [commons-app/apps-android-commons#819]
While working on the inital developer documentation I noticed that the app actually "handles" the username and password of the app users. I was surprised by that.

Does Commons/Mediawiki not support OAuth so the app can use a token based authentication mechanism?

**Comment by misaochan** [comment]
I was indeed wondering about this. The current login mechanism is a slightly-modified version of the legacy code from several years back. It's entirely possible that Commons/Mediawiki might support OAuth now.

**Comment by janpio** [comment]
One data point: Wikipedia for iOS also has an integrated login, not Oauth.

**Comment by tobias47n9e** [comment]
There is a mediawiki extension OAuth that is used by Wikipedia. Perhaps a thing for a library to share with the Wikipedia app? I made one of several python packages to connect with mediawiki and can explain some of the basics.

**Comment by janpio** [comment]
Awesome. Do you know any apps that actually use this? Is this also available on Commons?

**Comment by tobias47n9e** [comment]
The Oauth token works for all projects and you can customize what permissions the consumer needs. Here are the existing clients: https://m.mediawiki.org/wiki/Special:MyLanguage/OAuth/For_Developers

I don't know if there is a Java library, but add it on that page if you find one. The python mwoauth library is very readable and could be a template for a Java implementation.

**Comment by janpio** [comment]
Nice, looking good and pretty straightforward.

Is there a list of apps, websites or projects that are **using** this already somewhere?

**Comment by janpio** [comment]
Last point at https://m.mediawiki.org/wiki/Special:MyLanguage/OAuth/For_Developers#content-collapsible-block-3 might be a problem as well.

**Comment by tobias47n9e** [comment]
Are you mentioning this (The link to the headline does not work for me)?

> The application secret must be kept secret. Submitting it to source control or putting it into user-accessible code (such as mobile app or desktop application; even if it is obfuscated) undermines the security model and will result in admins forcefully disabling the application.

https://www.mediawiki.org/wiki/OAuth/For_Developers#Security_benefits_and_trade-offs

The solution seems to be:

https://stackoverflow.com/questions/4419915/how-to-keep-the-oauth-consumer-secret-safe-and-how-to-react-when-its-compromis

We could set up a web service on tool labs (Which I guess got renamed again and is now Tool forge) that handles the authentification between the app and Wikipedia? I have some practice with that and could help.

**Comment by janpio** [comment]
Yep, that was the one. 
Is this "normal" for OAuth mobile apps?
(Or is this a OAuth 1 vs 2 thing?)

**Comment by tobias47n9e** [comment]
I am not totally sure, but my current understanding is that there always need top be 3 parts involved. The Oauth provider, the consumer and the client. If the mobile app is both consumer and client the security can never work. Maybe that ist why there is no android library?

**Comment by psh** [comment]
No Android Library?

* https://gist.github.com/JakeWharton/f26f19732f0c5907e1ab (OAuth 1.0a)
* https://gist.github.com/alex-shpak/da1e65f52dc916716930
* https://github.com/pakerfeldt/okhttp-signpost
* https://github.com/corcoran/okhttp-oauth2-client

That's a quick sample of code that utilize OkHttp (a transitive dependency that already exists in this app)

Do any of them cover the cases we need here?

**Comment by janpio** [comment]
He meant the list here: https://m.mediawiki.org/wiki/Special:MyLanguage/OAuth/For_Developers#Libraries

If the Mediawiki implementation is standard, any of the ones you posted matching the Mediawiki OAuth version should be fine though.

**Comment by psh** [comment]
Thanks for the correction @janpio, I was barking up the wrong tree on that one!

**Comment by misaochan** [comment]
Adding this as high priority due to a request from Michael Holloway (WMF).

**Comment by maskaravivek** [comment]
I was trying to submit our app's details for OAuth consumer registration but am not sure about the callback URL column as our app is a native Android app. Can anyone help with it? https://meta.wikimedia.org/wiki/Special:OAuthConsumerRegistration/propose

**Comment by misaochan** [comment]
Tagging @whym and @nicolas-raoul :)

**Comment by nicolas-raoul** [comment]
I have always wondered how non-web applications handle OAuth.
From what I read at https://developer.android.com/training/id-auth/authenticate.html it seems that no callback URL is needed?

**Comment by maskaravivek** [comment]
The Callback URL column was mandatory so have put https://commons-app.github.io/ in it. Have been assigned a consumer token and secret token for the app

**Comment by maskaravivek** [comment]
The way ahead isn't very clear to me so i have created a phab task hoping someone could help us with it. https://phabricator.wikimedia.org/T179519

**Comment by maskaravivek** [comment]
Someone replied to my phab task from WMF. 

> OAuth 1.0 does not support clients without a backend component, sadly (as they have no way to keep the consumer secret secret). See #5 of the [[https://meta.wikimedia.org/wiki/OAuth_app_guidelines#Review_guidelines|review guidelines]].
> 
> You can use [[https://www.mediawiki.org/wiki/OAuth/Owner-only_consumers|owner-only OAuth]] to authenticate without passwords, but the setup process is very user-unfriendly at the moment.
> 
> Who did you talk to about WMF login requirements?

Our app doesn't have a backend component as far as I know. Even if we register as a Owner only app, the app will only be able to act in the name of the user who registered them. See **Owner Only apps** section of [OAuth app guidelines](https://meta.wikimedia.org/wiki/OAuth_app_guidelines#Review_guidelines)

@tobias47n9e @nicolas-raoul @misaochan Any insights?

**Comment by maskaravivek** [comment]
Anyways the OAuth Consumer request also got rejected. https://meta.wikimedia.org/wiki/Special:OAuthListConsumers/view/efc15ccf765eb39aad7c6a3c25f73826?markasread=2870231

**Comment by misaochan** [comment]
I will email Corey and Aeryn about it and point them to the Phab task. Don't worry about it for now @maskaravivek

**Comment by maskaravivek** [comment]
We made some progress with the OAuth implementation using oauth library that Corey Floyd from WPF suggested. 

Am now stuck at some E006[1] error. This seems to be related to issues other have run into while using OAuth on mobile[2][3]. My suspicion is that it might have to do something with redirection to mobile version of wiki URL. See WIP PR[4]

Any help with it would be really great. :) @tobias47n9e @nicolas-raoul @whym 

[1] https://www.mediawiki.org/wiki/Help:OAuth/Errors#E006
[2] https://phabricator.wikimedia.org/T74186
[3] https://phabricator.wikimedia.org/T119343
[4] https://github.com/commons-app/apps-android-commons/pull/935

Attached screenshot for ref. 
![e006](https://user-images.githubusercontent.com/3069373/32402899-eff4c840-c153-11e7-81f5-bf3fe787f239.png)

Also attached app logs for more context. 
[app_logs.txt](https://github.com/commons-app/apps-android-commons/files/1442969/app_logs.txt)

**Comment by maskaravivek** [comment]
The discussion is continuing on https://phabricator.wikimedia.org/T179519 for anyone who might be interested.

**Comment by misaochan** [comment]
This has been found to be impossible with WMF's current version of OAuth (see https://phabricator.wikimedia.org/T179519 ), and it has also been discovered that adding the Key to the app will open up the possibility for 3rd parties to impersonate the Commons app.

Consequently the requirement for us to use OAuth has been waived - based on Corey Floyd (WMF)'s email to me. I will close this for now, but feel free to reopen if WMF updates its OAuth version.

**Comment by janpio** [comment]
Good outcome.

**Comment by nicolas-raoul** [comment]
Small info, not sure whether it is useful: I just realized that the OSMTracker for Android app uses Oauth with the OpenStreetMap server. It is a bit awkward as the app opens Firefox at the server's /oauth URL but then you are not sent back to the app after authorizing.
