### ISSUE TITLE
Update F-Droid

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#82]
F-Droid still has the 2013 version:
https://f-droid.org/wiki/page/org.wikimedia.commons

**Comment by nicolas-raoul** [comment]
Request created: https://f-droid.org/forums/topic/upload-to-commons-wikimedia-commons-app/
If someone could write a recipe it would be shipped faster though. I tip about that on the talk page :-)

**Comment by Clonewayx** [comment]
Anyone working on this? On F-droid is still old version [1.0beta13](https://f-droid.org/repository/browse/?fdid=org.wikimedia.commons) - Added on 2013-10-24

**Comment by nicolas-raoul** [comment]
@Clonewayx Noone working on this right now, would you mind investigating and fixing the recipe if needed? Thanks :-)

**Comment by Clonewayx** [comment]
@nicolas-raoul  I'm not programmer so I don't think I'm able to help with it. (But I can try it if will know what to do.)

**Comment by Airon90** [comment]
[Chapters 6 and 7](https://f-droid.org/manual/fdroid.html#Importing-Applications) are revelant to simplify the process. Otherwise you can submit a request on the [submission queue](http://f-droid.org/forums/forum/submission-queue/) and wait to be approved by someone.

**Comment by nicolas-raoul** [comment]
Fixed, now at https://f-droid.org/wiki/page/fr.free.nrw.commons

**Comment by maskaravivek** [comment]
I see the following error on fdroid for our latest release. Anyone here aware of how to fix it. 
<img width="727" alt="screen shot 2018-01-12 at 11 55 19 pm" src="https://user-images.githubusercontent.com/3069373/34889422-e9e91a1a-f7f3-11e7-90c8-cafad1e22aea.png">

**Comment by domdomegg** [comment]
@maskaravivek Has this been resolved now? [F-Droid](https://f-droid.org/en/packages/fr.free.nrw.commons/) seems happy with 2.8.6 to me.

**Comment by licaon-kter** [comment]
@nicolas-raoul Please keep a consistent tag scheme, as F-Droid has:
```
AutoUpdateMode: Version v%v
UpdateCheckMode: Tags
```
...so it expects for versionName `2.12.0` a tag named `v2.12.0`, yet the tag is `v2.12` instead, so it fails to build: https://f-droid.org/wiki/page/fr.free.nrw.commons/lastbuild_508

**Comment by nicolas-raoul** [comment]
@licaon-kter Thanks for the feedback!
@misaochan Maybe try renaming the tag?

**Comment by licaon-kter** [comment]
See the MR link, it's fixed for this version (only), my comment was for...future versions. ;)

**Comment by nicolas-raoul** [comment]
Understood, thanks :-)
