### ISSUE TITLE
Update on the app and grant renewal status - project maintainer taking a temporary break

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#829]
Hi guys, bit of a long post, apologies in advance.

A bit of background: This app is purely community-maintained, and since last year has been funded by a WMF [Individual Engagement Grant](https://meta.wikimedia.org/wiki/Grants:IEG/Improve_%27Upload_to_Commons%27_Android_App). The actual funding has run out some time ago and the past few months have been purely volunteer work.

Unfortunately things are still very nebulous with the grant renewal application. I have not been able to talk to the grants program officer about the renewal, despite multiple attempts at contacting her for the past 4 months. After the [renewal proposal](https://meta.wikimedia.org/wiki/Grants:Project/Improve_%27Upload_to_Commons%27_Android_App/Renewal) was submitted, I also sent information through various other WMF emails and channels and finally received an answer from a grants admin. The email said that we might have to wait until October for a review and then December for the grant renewal to start, although they mentioned that we "might" be considered for an earlier review period. I responded with the reasons why I believe we really need an earlier review period, but I am not sure what their verdict will be, or when the verdict will even come (AFAIK the verdict depends on the grants program officer).

The point of all that text... is that **unfortunately, starting next week, I will need to take a temporary break from maintaining the app, until funding is approved**. I really really love the Commons app and I really want to see it succeed, but it's just not feasible for me to carry on putting 20-30 hrs/week of purely unpaid work into it, as I've been doing for the past 3 months while juggling freelance work on the side, in hopes that the renewal would be approved soon. I am very sorry, but I need to put that time into my personal projects and other streams of income for the time being, until we know when (or if) we can start being funded again. I will still try and check in at least once a week for a couple of hours, but I know that will not be anywhere near enough to cover everything.

I really appreciate all contributors and volunteers here and I hate to do this at a time when the community surrounding the app is so active, but my hands are tied in this matter. I will be back in full force in December if we are funded, or sooner if we receive an earlier review and are approved. There are other collaborators and core developers here who have been absolutely wonderful at helping out in their own ways, and any effort from anyone at keeping things afloat is always appreciated, but bear in mind that the other collaborators are not getting paid either, so they might not always have the time.

In more practical terms:

- **The app will definitely still remain up on the app store, and this repo will definitely still remain**. There is zero chance of anything being pulled off or closed
- It's likely that PRs will take longer to be reviewed, depending on the availability of volunteer collaborators at a particular time
- It is unlikely that there will be any new releases for the time being. If a hotfix is needed for an urgent bug, I will try and release one, but otherwise the regular release schedule will unfortunately not continue (unless Nicolas has the time to do so)
- It is likely that any issues users are experiencing might take longer to be responded to
- It is likely that that any requests for new features will be kept in backlog until we are able to return to working on the app

Thanks for your understanding everyone. ❤

**Comment by nicolas-raoul** [comment]
Sorry to hear about that, I really hope that WMF will give its OK for starting as soon as possible! The grants are a great way to put great energy into new features and strategic tasks.
It is very understandable that you don't spend as much time on the project when doing it purely as a volunteer.
For day-to-day operations, I encourage everyone in their spare time to develop/send PRs and review new bug reports and features requests, and I encourage the core developers to tag issues and review/merge pull requests as they see fit.
Until we have more news, the biggest impact will indeed be the pace of releases, as only @misaochan and me have the permission to upload APKs to Google Play, and I am ashamed to confess I don't even have Android Studio installed on my current computer, as I am working on unrelated projects.
Cheers!

**Comment by psh** [comment]
Couple of questions -

* There is a current milestone [IEG tasks](https://github.com/commons-app/apps-android-commons/milestone/1) open with a single item not finished.  Can we close it?

* Are the issues tagged [High Priority](https://github.com/commons-app/apps-android-commons/issues?q=is%3Aissue+is%3Aopen+label%3A%22high+priority%22) actually the top things to work on right now?

* Would it be good to have a new milestone containing the current top issues that people could focus on, just so we don't lose momentum toward our goal?

* Is there anything we (as volunteers) can do to make things easier to administer?

**Comment by neslihanturan** [comment]
First question : I think we can close it

For the rest, tags are not very well organized currently. I also have hard times to select a task to work on. I can start an issue tomorrow to discuss what can we do until renewal time and accordingly create new issues and organize tags.

**Comment by misaochan** [comment]
Thanks for the support, all! Greatly appreciated. <3

@psh 

1. Thanks for the reminder! I have closed it.

2. I would say they are - I checked on High Priority tasks fairly recently. I did remove one today that appears to no longer exist, but I would say that everything on it now is relevant. #748 is pending discussion about whether it still occurs. #328 is likely to be fairly involved and was planned for the renewal, but if anyone wants to work on that that would be fine too.

3. The issue with such a milestone is that things will keep being added to it, hence the High Priority tag instead. But if people don't mind a frequently-changing milestone, we could certainly do that.

4. Thanks for asking! Something like 40% of my maintenance time is actually spent reviewing, testing and merging PRs. I think it's really important to thoroughly test PRs  - testing the modified feature multiple times in various ways, and also testing that core functionality isn't impaired if the PR spans multiple utility files (even if it doesn't LOOK like it will be affected). The few times I got lazy with this, it came back to bite me in the behind quite badly when it was time for a release. :) All of a sudden there were all these bugs that I hadn't noticed before, and then I had to trace back to which PR caused them.... It would be wonderful if others could help with this (only collaborators can actually do the merge, but testing and review can be done by anyone). 

Responding to users facing problems and new volunteers (like in the Google group forums or in GitHub) is another big one. This would tie in with managing and tidying up issues. People have certainly been helping with all of this which is great and very much appreciated, but there is still a lot to be done.

There are also some things that I do that are unavoidable and just part of the "job description", I guess. As @nicolas-raoul mentioned, releases are one of those (although if the release has been thoroughly tested by someone else, it would dramatically reduce the time needed for me to do a release). Along with responding to enquiries sent to me, or suggestions for new features etc. Certainly a project maintainer who doesn't provide input on any suggestions/issues or the general direction of the app, would be a very terrible one.

Thanks again! I really appreciate it.

**Comment by misaochan** [comment]
Brief update: Apologies again for the absence. I am currently working another job while awaiting the grant application results, and over the past 2 weeks or so, what little time I have for the Commons app has been spent mostly negotiating with WMF to keep the app on their Google Play Store account.

The committee review period for our grant application has finally begun and will conclude on the 25th Sep. The other grantees and I are setting a tentative start date of 16th Oct if we are approved, to allow Neslihan and I to arrange our other jobs around it.

Thanks again for staying with us!
