### ISSUE TITLE
[Wiki] "Volunteers Welcome!" should not only focus on developers

### ISSUE THREAD

**Issue by janpio** [commons-app/apps-android-commons#836]
Right now the "Volunteers Welcome!" documentation is 100% focuesd on developers: https://github.com/commons-app/apps-android-commons/wiki/Volunteers-welcome%21 (formerly in the README)

I think this could be improved to also include translation and other work related to the app that more non-technical people could do. The technical development instructions might also better be placed in a seperate document.

**Comment by janpio** [comment]
What would that be, what a more non-technical person can de besided Translation on Translatewiki?
Testing? 
Moderating images?
Helping with issues?

**Comment by janpio** [comment]
- Write documentation in the wiki

**Comment by whym** [comment]
Yeah, testing the app and moderating images would be great.

To expand, to people who can use Android Studio:
* Compile and test the latest (not yet release) app, and report any issues you encounter

To experienced Commons editors:
* Check lists such as https://commons.wikimedia.org/wiki/User:Didym/Mobile_upload and https://commons.wikimedia.org/wiki/Special:RecentChangesLinked/Category:Uploaded_with_Mobile/Android. Report (if it seems a malfunction on the app's side) and/or fix anomalies such as possible copyright violation, accidental overwrite, inadequate file name, etc.

**Comment by misaochan** [comment]
Everything @whym mentioned, plus:
- Testing the current beta release and reporting any issues with it (for those who don't know how to build from GitHub)
- Moderating our Google group forums (AFAIK @neslihanturan is currently doing that, but a non-technical person could also do that)
- Helping with promotional/marketing stuff - sharing about the app on social media, making educational videos on how to use it, etc
- Custom icons for Nearby places or Nav drawer items, etc (definitely not a necessity, but would be nice)
