### ISSUE TITLE
Please push beta release to F-Droid

### ISSUE THREAD

**Issue by gappleto97** [commons-app/apps-android-commons#845]
The version currently there has a lot of crashes for me. The beta version solves essentially all of these.

**Comment by gappleto97** [comment]
Sorry for the multiple issues. I'm on a very flaky connection and it looked like it didn't go through.

**Comment by misaochan** [comment]
Hi @gappleto97 ,

No worries. I was under the assumption that all of the tagged releases at https://github.com/commons-app/apps-android-commons/releases would automatically be pushed to F-Droid? Or am I mistaken in this?

**Comment by nicolas-raoul** [comment]
F-Droid has a strict rule to not publish beta software.
I have already tried, and had my pull requests refused because the apps I was integrating were still in beta.
Cheers!

**Comment by gappleto97** [comment]
They do have rules to handle betas and the like. And they put their own betas on there. So that confuses me.

**Comment by misaochan** [comment]
Closing this, please feel free to reopen if we have new information about F-Droid accepting betas.

If it helps, in a few weeks' time there will tentatively be a production release with the new fixes, so hopefully you can get it then. :)
