### ISSUE TITLE
Ignore Wikidata statements marked as deprecated

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#849]
Not sure whether this is done right now.
Some items have wrong coordinates that come from a reference database. Since the coordinates come from a reference database, the wrong ones are not deleted but simply marked as deprecated.

**Comment by misaochan** [comment]
Is this similar to #618 ?

**Comment by nicolas-raoul** [comment]
#618 is about a place that used to be something. For instance, there was a battle here.

This issue is about patently false information. For instance, the [GRID](https://www.grid.ac/) is a database of research institutions, they include the approximate location of each but it is not their main purpose so the location is often off. Anyway, the locations are imported into Wikidata regularly because it is better than nothing. If you fix the coordinates, they will be inserted again at the next batch update. So the solution is to mark them as "deprecated". But what it really means is that these coordinates are wrong.

**Comment by misaochan** [comment]
Thanks @nicolas-raoul . Better to completely ignore them, then. I guess this will be a fairly straightforward modification of our query?

**Comment by nicolas-raoul** [comment]
Yes, better ignore them completely.

The change to the request is not obvious to me. Deprecation is not standard SPARQL, I am not sure whether it is an extension or something else.

I believe I saw a discussion recently about making deprecated results not appear if another statement is available, but I am not sure what is the status on this.

**Comment by nicolas-raoul** [comment]
SPARQL does this for us.
