### ISSUE TITLE
Preparing a test server

### ISSUE THREAD

**Issue by neslihanturan** [commons-app/apps-android-commons#853]
Hi everyone,

I was thinking to facilitate our testing process. Maybe we can create a test server that includes emulators and several scenarios we want to test (maybe we can use selenium), and a script to test our PR for several conditions with command line easily. Does any of you used such thing before? Do you have advises for such environment?

**Comment by psh** [comment]
How does this issue relate to PR #555 (WIP Use beta commons site when in debug mode) / Issue #705 ?  

In the comments on #555 @whym suggested using product flavors to allow us to switch where the app is pointing.  I have that partially implemented on a branch (easily pulled out to make it a stand-alone PR if you want)  The one thing I haven't tracked down is what the beta site equivalent of https://tools.wmflabs.org is.  Does anyone know?

**Comment by neslihanturan** [comment]
Thanks for pointing to related issues @psh ! Actually I don't know the equivalent site either. I have read your branch and it looks like what I try to say. What do you think about testing on common emulators on a server to make sure patch is tested for several different devices?

**Comment by whym** [comment]
> The one thing I haven't tracked down is what the beta site equivalent of https://tools.wmflabs.org is.

As far as I know the use of tools.wmflabs.org in this app is read-only, so I suppose we can use the original site regardless it's test mode or not. (=no risk of accidentally destroying something on the server side.)

**Comment by whym** [comment]
@neslihanturan It sounds like Travis-CI covers at least some of what you said - Travis-CI has Android emulators and it runs "gradle connectedCheck" (see .travis.yml) which invoke tests under app/src/androidTest.

**Comment by sivaraam** [comment]
Seems the following resources would be of help,

https://docs.travis-ci.com/user/languages/android/

https://medium.com/@harmittaa/travis-ci-android-example-357f6e632fc4

**Comment by nicolas-raoul** [comment]
Several ideas in this issue and I believe most have been addressed, so let's create new issues for the ideas that are still relevant.
