### ISSUE TITLE
Improve user documentation

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#86]
I wrote a very short user documentation here: https://github.com/nicolas-raoul/apps-android-commons/wiki
We should put something like this on Play Store too

A good thing also would be to create a short YouTube video showing an upload. This video could be embedded in Play Store (there is a field for that).

**Comment by misaochan** [comment]
Will put this into Phase 3 of my IEG proposal.

**Comment by tobias47n9e** [comment]
The problem with the Github wiki, is that it is not very mobile friendly. I think read the docs or something similar would be a better option. It can also be developed in multiple languages. Another option would be to host a small website. It could be hosted on Github in the beginning.

**Comment by nicolas-raoul** [comment]
You're right Tobias, and creating a small Github website is a great idea, that way anyone could send pull requests!

Would you have time to find a nice, responsive design, open source template and use to to build a skeleton of the website? :-)
I created a test page here: https://commons-app.github.io and invited you to the project. That would help a lot, thanks!
https://github.com/commons-app/commons-app.github.io

**Comment by tobias47n9e** [comment]
@nicolas-raoul Sure I can do that. Just not sure how to properly localize a static Github page. But I will worry about that later.

**Comment by nicolas-raoul** [comment]
How about just having the default site in English, with a few links at the top pointing to https://commons-app.github.io/fr for the French version, etc?

**Comment by misaochan** [comment]
Shall I just use this thread for the Youtube video task, or start another? :)

**Comment by misaochan** [comment]
Update: the website has already been created by Tobias and has its own GitHub repo [here](https://github.com/commons-app/commons-app.github.io). 

I'm thinking the remaining tasks should be to:
1. Update Play Store documentation (and potentially screenshots)
2. Create a Youtube video to be placed on Play Store (and maybe on the website?)

The Youtube video is quite an involved task, so I will create a new task for it (#331) and we can use this task for general user documentation.

**Comment by misaochan** [comment]
I'm thinking of revamping the screenshots. Instead of just a basic screenshot, I figure we could use something like http://www.appscreenshot.me/ to generate framed screenshots with a short description each. Thoughts?

**Comment by misaochan** [comment]
An example screenshot below. I'll add more for categorization, nearby, media details etc, but wanted to get input on whether or not the style is appropriate before making more.

![android-ratio-16 9](https://cloud.githubusercontent.com/assets/3611199/23744663/cc328da8-0500-11e7-9392-f123e311379a.png)

**Comment by nicolas-raoul** [comment]
Note: I remember that Google recommends against including frames and phone representations around the actual screenshots because:
- They get old very quickly (even though there are easy to replace, screenshots are typically not renewed more than every few years.
- They don't provide value and make the actual valuable part of the image smaller.
I can't find the page again though.

**Comment by misaochan** [comment]
Ah, okay. I was just going based on what I saw the editor - recommended apps doing, but if goggle has recommended against it then we should probably follow that. 

I'll just upload updated screenshots then? Since our app has changed quite a bit since the last ones.

**Comment by misaochan** [comment]
@nicolas-raoul Do you mind if I remove your screenshots to add new ones? The app interface has changed quite a bit since then, and I think there is a limit to # of screenshots (so I can't add new ones without removing).

**Comment by nicolas-raoul** [comment]
Ah, of course! :-)

**Comment by misaochan** [comment]
Screenshots and app store listing updated. Feel free to reopen if anyone would like to propose further changes.
