### ISSUE TITLE
Overhaul media details view pane

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#873]
The current media details view pane feels rather clunky, and would be difficult to implement new features such as #161 . I'm not sure exactly what sort of redesign I have in mind yet (perhaps someone with a better design eye or familiarity with other photography apps can chime in?), but preferably it should be able to pave the way for #161 .

**Comment by psh** [comment]
Using the current design, users are used to pulling the footer up to reveal more details

![cardinals-baseball-detail-01](https://user-images.githubusercontent.com/407647/30229410-6db01084-94a7-11e7-9de4-e6285fb3af20.png) ![cardinals-baseball-detail-02](https://user-images.githubusercontent.com/407647/30229417-75c4f744-94a7-11e7-8f43-b64323cada3d.png)

Much like in Google Maps except that Google Maps automatically opens the whole way.  

![google-maps-info-footer](https://user-images.githubusercontent.com/407647/30229489-cc95b69e-94a7-11e7-8fb1-2e97a338168a.png) ![google-maps-info-fullscreen](https://user-images.githubusercontent.com/407647/30229495-d17a33a6-94a7-11e7-977b-e911c4a6e2e4.png)

There's a slightly different maps view that I find interesting when there's only a limited amount of information

![google-maps-info-card](https://user-images.githubusercontent.com/407647/30229541-f9aaa068-94a7-11e7-8a37-32f47b013688.png)

We currently display

* Title
* Description
* License
* Coordinates
* Categories
* Date

It feels like the card view is sufficient to display what we have.  For instance, we (as programmers) like to label fields when simply a bold+text size picks out the difference between a title and a description.  If fields have no data ('no coordinates found', or no categories that still show up as just a label) we don't really need to show them.

* Would it be worth a quick spike to try a floating card view without all the field labels?
* Would it work to show a tappable map pin if there are coordinates, that bounces to a map if tapped?
* Where Google Maps has a "read more" we could have an "edit" button to show a full-screen editable form.

**Comment by psh** [comment]
One thing I notice about the media details view that we have is that it doesnt respect the portrait / landscape nature of the image.  For example, [this picture](https://commons.wikimedia.org/wiki/File:Cardinals_baseball_stadium.jpg) was taken landscape.  

Looks good when my phone is in landscape

![device-2017-09-10-120103](https://user-images.githubusercontent.com/407647/30251199-76c09b6a-9620-11e7-812f-5b9a234682f2.png)

As I rotate my phone the details view does nothing to imply the original orientation, it just truncates the picture.  Since this is the _normal_ orientation for a phone, we truncate by default:

![device-2017-09-10-120131](https://user-images.githubusercontent.com/407647/30251198-7486a8c6-9620-11e7-8e25-ada447f98222.png)

Google Photos does the right thing - it shrinks to fit and letterboxes the image - making it clear what the original orientation was.

**Comment by psh** [comment]
There are 3 operations available on the detail view right now and it sounds like we're talking about adding a 4th

- Share
- Download
- View in Browser
- Edit (coming soon?)

Google Photos also offers 4 actions on a bottom navigation (share, edit, info, delete), and a bunch of others in an overflow menu.  The detailed picture information is on its own full-screen view.  The bottom navigation definitely cleans things up.

Google Photos does have a nice feature where an image tagged with a location will show a map view on the (full-screen) image info screen.

**Comment by psh** [comment]
I was playing with the main Wikipedia app today - particularly around how it handles photos:

![wikipedia-app](https://user-images.githubusercontent.com/407647/30790701-1f37835a-a173-11e7-87f8-026b4f993113.png)

The details are minimal (as you would expect - the focus isnt on pictures) but it does highlight the idea of letterboxing photos in landscape mode.  They also do a nice job of presenting content in card views on the main screen too.  I like how they did their bottom navigation view on the main screen too.

**Comment by psh** [comment]
New bug logged - #894 (Media details lost on device rotation)

If we are overhauling the media details screen we might want to fix the bug, or at least make sure we dont cause a regression and re-introduce it.

**Comment by nicolas-raoul** [comment]
Featured pictures are meant to be enjoyed as much as the screen allows, and currently the media details activity is indeed far from optimal:
![2015-07-27_20-51-30_macroglossum-stellatarum](https://user-images.githubusercontent.com/99590/40055848-51a192fe-5884-11e8-88dd-2cb1e7c232a0.jpg) https://upload.wikimedia.org/wikipedia/commons/c/c0/2015-07-27_20-51-30_Macroglossum-stellatarum.jpg -> ![screenshot_20180515-203907](https://user-images.githubusercontent.com/99590/40055789-1b31a04c-5884-11e8-9b64-3521434aef0b.png)

**Comment by nicolas-raoul** [comment]
I think this can be considered solved, even category edition seems to have found its place.
