### ISSUE TITLE
Missing location template for bulk uploads

### ISSUE THREAD

**Issue by Aschroet** [commons-app/apps-android-commons#874]
When uploading photos by "send to" Commons app the location template is not added although the GPS coordinates are contained in Exif. An example are my latest uploads i made into this category:
https://commons.wikimedia.org/wiki/Category:Kriegerdenkmal_auf_dem_Sperlingsberg_(Kapellendorf)

**Comment by oe-bayram** [comment]
Should be closed :)

**Comment by nicolas-raoul** [comment]
Is this problem still happening?

**Comment by misaochan** [comment]
@Aschroet This should have been fixed in 2.10. Please do let us know if you are still encountering problems.
