### ISSUE TITLE
Tech-improvement:  JSON based Wikimedia API 

### ISSUE THREAD

**Issue by psh** [commons-app/apps-android-commons#885]
Move to the [JSON based WIkimedia API](https://www.mediawiki.org/wiki/API:Data_formats) as XML is officially deprecated by Wikimedia as a format. We already include OkHttp and GSON in the build, so no new libraries would be needed.

**Comment by kerenpas** [comment]
I start working on this

**Comment by psh** [comment]
Something to consider as you are working on this -

* The app uses several different networking libraries, some of which are _obsolete_.  This is our chance to clean up and consolidate around a single (modern) network stack
* I called out [OkHttp](http://square.github.io/okhttp/) as I believe that to be the best way forward for us
* The main Wikipedia app uses the awesome [Retrofit](http://square.github.io/retrofit/) library which sits as a layer over OkHttp to encode/decode http parameters on REST calls. I'm not sure how much utility it brings to our API though.
* Some of the Wikimedia services we call are reporting that they are deprecated & our new implementation should switch (eg getting "edit tokens")

I have extensive experience with OkHttp & Retrofit (and have done a bit of research on the migration effort) if you have any questions, always happy to help!

**Comment by kerenpas** [comment]
Hi Paul ,
I have no experience with OkHttp, but found it very friendly to learn and to used.
I will use the OkHttp lib.
I let you know how it goes.
Thanks for your help!

**Comment by kerenpas** [comment]
hi,
Sorry for the delay to commit my changes...
I have question regarding the test. In the project there is a ApacheHttpClientMediaWikiApiTest, I want to add OkHttpClientMediaWikiApiTest. How do I preform testing?
Thanks!

**Comment by psh** [comment]
@kerenpas - How're things going with this issue?  Have you been able to make any progress?

**Comment by kerenpas** [comment]
Hi,
Sorry I been busy and put it aside...  I will finish it teal Wednesday
next week, thanks for the reminder!

**Comment by kerenpas** [comment]
Hi Paul,
I having some problem to test the LogEvens
<https://commons.wikimedia.beta.wmflabs.org/w/api.php?action=help&modules=query%2Blogevents>
API. I need an example for logEvents response that contains the field "
lestart".
All the request that I made do not contain this field here is a link
<https://commons.wikimedia.beta.wmflabs.org/w/api.php?action=query&list=logevents>
to example response.
I just want to make sure that I extract this field from the JSON response
correctly.
Thanks,
Keren

**Comment by kerenpas** [comment]
Hi Again,
I figure out what was the problem... I have not pass the lestart parm at
the get query string...
Thanks,
Keren

**Comment by kerenpas** [comment]
Hi Paul,
I getting Server Error... (Our servers are currently under maintenance or
experiencing a technical problem. Please try again
<https://codebeautify.org/htmlviewer/>in a few minutes.)
I am waiting for this issue to be solved, so I may be late for commit my
code.
Thanks,
Keren

**Comment by dbrant** [comment]
This will be handled via #1092
