### ISSUE TITLE
Tech-improvement: Use Glide for image loading / caching

### ISSUE THREAD

**Issue by psh** [commons-app/apps-android-commons#889]
Use [Glide library](http://bumptech.github.io/glide/) instead of asynctask load of images. Glide already developed for loading images, and its support different paths for imageview (URI, URL, file path at SD card and etc). Simple use, simple result.

**Comment by joe94** [comment]
@psh Were you thinking of something like this: https://github.com/bumptech/glide/blob/master/samples/flickr/src/main/java/com/bumptech/glide/samples/flickr/FlickrSearchActivity.java#L313 ? 

 Also for clarification, the app uses an asynctask to fetch the image url (https://github.com/commons-app/apps-android-commons/blob/master/app/src/main/java/fr/free/nrw/commons/MediaThumbnailFetchTask.java#L19) and not to load the image url per se, correct? Although I do understand that in the onPostExecute() of the asyncTask, we do use the resulting url on the SimpleDraweeView.

**Comment by Moseco** [comment]
I would like to get started on this.

**Comment by Moseco** [comment]
@psh I made an implementation of Glide but it is inefficient due to a bug I reported in issue #1169 

If that bug can get solved the Glide solution would be much better

**Comment by neeldoshii** [comment]
Hi @psh 

Does this also mean replacing Fresco to Glide?

**Comment by psh** [comment]
I appreciate your interest in this issue, but if you check the date on it - `Sep 22, 2017` - you'll see it's old.  I cant find any reference to "asynctask" any more, which leads me to think it's best to close this one as _obsolete_
