### ISSUE TITLE
Tech-improvement: Introduce dependency injection using Dagger2

### ISSUE THREAD

**Issue by psh** [commons-app/apps-android-commons#890]
Dagger2 is dependency injection library which will help to remove many initializations of some utils/loaders/api workers and etc. For example in current project it will help to initialize SharedPreferences client once for using in many parts of app. _(the runtime for Dagger is tiny, it's mostly compile-time annotation processing)_

**Comment by maskaravivek** [comment]
@psh my PR has been merged now. Can this issue be closed now?

**Comment by psh** [comment]
No, but building on your good work to introduce dagger, I've submitted #956 that "completes the swing" to fully embrace dependency injection.  Basically, no-one is now reaching back into the `CommonsApplication` and dependencies are being resolved using Dagger throughout.

**Comment by maskaravivek** [comment]
Great work @psh!. Am trying to review your PR. :)
