### ISSUE TITLE
Actions needed to keep app on WMF Google Play Store account

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#891]
WMF has been talking to me about the actions needed in order to keep our app on their Google Play Store account. The list of actions we have agreed upon is as follows:

- [x] Nicolas, myself, and anyone with access to the crash reports forum will have to sign NDAs. If anyone wishes to relinquish crash report forum access instead of signing the NDA, that's fine too.

- [x] Modify disclaimer for app store listing - I will do this shortly based on Aeryn (WMF lawyer)'s recommendations

- [x] Modify disclaimer for About page in app - we will need to do a release for this to be effective

- [x] Finish drafting new privacy policy - https://github.com/commons-app/apps-android-commons/wiki/Privacy-policy (must mention Mapbox). #520 could be useful here.

- [x] Implement OAuth for login #819 - waived

- [x] Release modifications to production, inform WMF that everything on our side is complete

- Security reviews - the WMF Android team will be reviewing our app for security concerns shortly, and will schedule further reviews in the future, but there is nothing we need to do on that point currently.

**Comment by misaochan** [comment]
Disclaimer for app store listing (drafted by Aeryn with my input):

> [Name of App] is an open-source app created and maintained by grantees and volunteers of the Wikimedia community to allow the Wikimedia community to contribute content to Wikimedia Commons. Wikimedia Commons, along with the other Wikimedia projects, is hosted by the Wikimedia Foundation. The Wikimedia Foundation is pleased to support community developers by offering the app here, but the Foundation did not create and does not maintain this app. For information about the app, including its privacy policy, see the information at the bottom of this page. For information about the Wikimedia Foundation, visit us at wikimediafoundation.org. 

Disclaimer for About page in app:

> [Name of App] is an open-source app created and maintained by grantees and volunteers of the Wikimedia community. The Wikimedia Foundation is not involved in the creation, development, or maintenance of the app.

**Comment by misaochan** [comment]
@nicolas-raoul , any idea how we can draft a proper privacy policy without legal assistance?

**Comment by nicolas-raoul** [comment]
My idea is to just take the WMF one, replace the name and nature of the
project, then remove the many irrelevant parts.

**Comment by misaochan** [comment]
Yeah, I think that should be OK as long as we mention Mapbox as well?

Where should we host our privacy policy once we have drafted it? Is the GitHub wiki sufficient?

**Comment by nicolas-raoul** [comment]
Yes, Github Wiki is good enough I think, and it is the most flexible option.
Once things settle down we can think of moving it to the official website.

**Comment by misaochan** [comment]
Sounds good to me!

**Comment by misaochan** [comment]
I've been reading up on how other apps handle their privacy policies - what do you guys think about using guidelines similar to https://www.iubenda.com/blog/privacy-policy-for-android-app/ and https://www.iubenda.com/blog/warning-google-play-developer-policy-violation-action-required-policy-issue/ for writing ours? I wonder if that may be an option, as the WMF one looks rather long and convoluted and it's hard to know which parts pertain to us. 

I'm also somewhat surprised that the [Wikipedia app](https://play.google.com/store/apps/details?id=org.wikipedia&hl=en) doesn't appear to have its own privacy policy on the Play Store and just uses the [standard Wikimedia one](https://wikimediafoundation.org/wiki/Privacy_policy). I would have thought that they would have needed to disclose the Android-specific sensitive permissions, etc.

**Comment by misaochan** [comment]
I have updated the privacy page of the wiki using the template provided at https://gist.github.com/alphamu/c42f6c3fce530ca5e804e672fed70d78#file-android-privacy-policy-template , and will be modifying it in the next week to suit our app. If anyone finds this template unsuitable, please let me know ASAP. :)

**Comment by misaochan** [comment]
I have completed the final draft of the privacy policy - https://github.com/commons-app/apps-android-commons/wiki/Privacy-policy . Please feel free to comment and provide feedback - if there are no issues, I will be sending Aeryn (WMF) this copy at the end of the week.

@nicolas-raoul @whym

**Comment by misaochan** [comment]
> 1. I have the feeling that "SERVICE" is a kind of placeholder intended to
> be replaced, but I am not sure. Maybe replace it with "application"? As we
> only provide an application that allows usage of WMF's service.
> 
> 2. "The information that we request is retained on your device and is not
> collected by us in any way." is not accurate I believe, as we actually
> upload that information. How about just saying that the app makes this
> information public, and that thus people should not upload thing they don't
> want to be public?
> 
Will do, thanks!

> 3. I believe log data is not sent without explicit agreement from the user?
> If yes, then it is worth writing.

I think the crash logs sent via the Google Play developer console (not to the google group forum) are not optional? Or is there a way to turn that off?

> 4. Do we really use cookies? Does Mapbox really do?

We don't, but I don't know if the 3rd party libraries or websites we link to do. So I thought it would be safer to leave that statement in. I know Mapbox mentioned that their website does use cookies, but don't think their map server does.

**Comment by misaochan** [comment]
Should be done, closing this unless I hear otherwise from WMF.
