### ISSUE TITLE
Media details lost on device rotation

### ISSUE THREAD

**Issue by psh** [commons-app/apps-android-commons#894]
I happened to be testing the app on a tablet (real hardware) and rotated the screen.  I then verified and it also occurs on a phone (emulator) - 

![media-details-landscape](https://user-images.githubusercontent.com/407647/31046801-1690a3ac-a5c5-11e7-9c1a-b750a64b1444.png)

![config-change-bug](https://user-images.githubusercontent.com/407647/31046802-1918bc9a-a5c5-11e7-82c9-f51ef0f14756.png)

This is a bug that is present on current _master_ but not present in the released version in the Google Play Store.

**Comment by psh** [comment]
Looking into things a little more: each of the media pager adapter fragments reach back to the `ContributionsActivity` for data.  After rotation, the adapter in `contributionsList` is null.

```java
@Override
public Media getMediaAtPosition(int i) {
    if (contributionsList.getAdapter() == null) {
        // not yet ready to return data
        return null;
    } else {
        return Contribution.fromCursor((Cursor) contributionsList.getAdapter().getItem(i));
    }
}
```

**Comment by JohnKal** [comment]
I am working to fix this issue.

**Comment by misaochan** [comment]
@JohnKal great, thanks! :)

**Comment by neslihanturan** [comment]
This bug seems solved.
