### ISSUE TITLE
Travis CI failure related - String resources format

### ISSUE THREAD

**Issue by joe94** [commons-app/apps-android-commons#895]
After cloning the repo and attempting to build the app using `./gradlew assembleDebug`, I got this error: 
```
Error:(56) Multiple substitutions specified in non-positional format; did you mean to add the formatted="false" attribute?
Error:(56) Unexpected end tag string
Error:(56) Multiple substitutions specified in non-positional format; did you mean to add the formatted="false" attribute?
Error:(56) Unexpected end tag string
```

A quick google search led me to this: https://stackoverflow.com/questions/4414389/android-xml-percent-symbol

Escaping the %-symbols with a `%` in https://github.com/commons-app/apps-android-commons/blob/master/app/src/main/res/values-hi/strings.xml#L57 seems to silence the issue and the build completes successfully. However, it would be good to have someone more familiar with the project double check whether or not this is an actually an issue and if it is, whether this really solves the problem.

**Comment by joe94** [comment]
The build failure seems to be related: https://travis-ci.org/commons-app/apps-android-commons

**Comment by maskaravivek** [comment]
Am able to build the current master successfully using `./gradlew assembleDebug`

**Comment by joe94** [comment]
This has been solved.
