### ISSUE TITLE
GPS info isn't transferred from exif to description when a group of pictures is being uploaded 

### ISSUE THREAD

**Issue by VDK** [commons-app/apps-android-commons#896]
This picture https://commons.wikimedia.org/wiki/File:United_States_Custom_House_(Baltimore,_Maryland)_-_24.jpg
And others like it that I uploaded with the mobile app don't have the GPS data that is in the exif data included in the description.

**Comment by tobias47n9e** [comment]
Thanks for opening this issue. That seems quite critical.

**Comment by misaochan** [comment]
Thanks for reporting this @VDK . To clarify, this only happens when you upload by selecting multiple pictures in your gallery, then tapping "Share" and then selecting the Commons app, right?

**Comment by VDK** [comment]
Affirmative

**Comment by Bluesir9** [comment]
Would like to take this up if nobody else has.

**Comment by nicolas-raoul** [comment]
@Bluesir9 : Feel free, thanks! :-)

**Comment by Bluesir9** [comment]
Looks like this and #874 are the same.

**Comment by neslihanturan** [comment]
This one is solved, proviously
