### ISSUE TITLE
UI improvement - login screen

### ISSUE THREAD

**Issue by psh** [commons-app/apps-android-commons#899]
There has been a lot of talk about improving the user interface recently, so I started thinking about how to freshen up the login screen.

The code is basically ready to go as a  PR but I wanted to solicit feedback on the look+feel since this is one of the first screens seen by a user.  Any thoughts?

## Phone

![login-phone-01](https://user-images.githubusercontent.com/407647/31312033-1dac6922-ab7f-11e7-9dc0-e6f0a4528939.png)

#### Keyboard up, button still disabled

![login-phone-02](https://user-images.githubusercontent.com/407647/31312034-29822f7a-ab7f-11e7-8446-11b3f907f41c.png)

#### All data ready to go, button enabled

![login-phone-03](https://user-images.githubusercontent.com/407647/31312036-34560836-ab7f-11e7-96ed-5ef2f07e1ab6.png)

#### Improved error messaging (replaces the `Toast` used by the current code)

![login-phone-04](https://user-images.githubusercontent.com/407647/31312037-38a5ea64-ab7f-11e7-8233-733819a936aa.png)

#### Works in landscape

![login-phone-05](https://user-images.githubusercontent.com/407647/31312047-4c1239fe-ab7f-11e7-896d-7c9fd9978520.png)

#### Keyboard up

![login-tablet-01](https://user-images.githubusercontent.com/407647/31312052-5a18457a-ab7f-11e7-81cd-c918041ce094.png)

#### Works in landscape

![login-tablet-06](https://user-images.githubusercontent.com/407647/31312054-7152867e-ab7f-11e7-872e-a0f18c075dce.png)

#### Also shows errors

![login-tablet-03](https://user-images.githubusercontent.com/407647/31312053-628c6b14-ab7f-11e7-9dbe-f714ff8d17de.png)

**Comment by thedeadline** [comment]
I would make the background of the logo white so it stands out more from the background of the page. Also, whatever line the error message refers to should be red to indicate visually quickly that it needs attention. 

Consider also changing the text to white for readability (but screenshot is small, so I can't say for certain it's not the size).

**Comment by misaochan** [comment]
Personally I love the screenshots! Especially the new error display replacing Toasts. :)

My only concern is that the login box appears rather small relative to the size of the screen in tablets. 

> Also, whatever line the error message refers to should be red to indicate visually quickly that it needs attention.

This would be a nice addition, but not essential IMO.

**Comment by neslihanturan** [comment]
I know this issue is closed but login screen looks great, I wanted to share my impression. Thanks @psh !
