### ISSUE TITLE
Error 504 when updating

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#90]
A user has reported on the google group forums that he receives an error 504 when he tries to update the app in the Play Store.

![screenshot_20160323-075922](https://cloud.githubusercontent.com/assets/3611199/14008835/92043fca-f1ea-11e5-9393-92b90bb69486.png)

**Comment by nicolas-raoul** [comment]
Does not sound like a bug of the app: http://android.stackexchange.com/questions/35062/error-504-when-downloading-apps-from-play-store
If we get many such reports it might be worth looking further though.

**Comment by nicolas-raoul** [comment]
Actually I might be wrong, the second answer on that page is probably more on point: http://android.stackexchange.com/a/131584/501
What version of Android?

**Comment by misaochan** [comment]
Android 6.

His post on google group translates to:

> Hi, every time I try to download the update I get the error 504. The application sometimes crashes. I have a Nexus 6 and Android 6

**Comment by misaochan** [comment]
Hm. From reading the page you linked, it seems that this problem is probably isolated to our previous app version that was targeting API 22? Should be okay now that it is targeting API 23, right?

**Comment by misaochan** [comment]
Closing this - has not been replicated since July.
