### ISSUE TITLE
Current master build failing - translation issues

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#902]
Hi @Nikerabbit ,

It seems that some of the recent translations are causing the master build to fail?

```
C:\Code\GitHub\apps-android-commons\app\build\intermediates\res\merged\beta\debug\values-hi\values-hi.xml
Error:(56) Multiple substitutions specified in non-positional format; did you mean to add the formatted="false" attribute?
Error:(56) Unexpected end tag string
Error:(56) Multiple substitutions specified in non-positional format; did you mean to add the formatted="false" attribute?
Error:(56) Unexpected end tag string
```

Thanks!

**Comment by Nikerabbit** [comment]
I fixed one string that looked incorrect, but I have no if that string is causing the problem.

**Comment by crud3** [comment]
I can confirm the problem, the build also fails for me.

The problematic string is in the `app/src/main/res/values-hi/strings.xml` file

`<string name="contributions_subtitle">{{PLURAL | शून्य = @ स्ट्रिंग / योगदान_उपशीर्षक_शुन्य | एक =% d अपलोड |% d अपलोड्स}}</string>`

If I change the value of that string to something else like `foo`, the build passes.

**Comment by Nikerabbit** [comment]
That's the one I modified too.

**Comment by misaochan** [comment]
@Nikerabbit Is it okay for us to add the `formatted="false"` fix before your commits go through? As AFAIK we would have to wait 2-3 days more for those?

**Comment by Nikerabbit** [comment]
Yeah go ahead.
