### ISSUE TITLE
IEG renewal approved - updates and progress (and new assistant project maintainer)

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#918]
Hi all,

Our IEG renewal application has just been [approved](https://meta.wikimedia.org/wiki/Grants_talk:Project/Improve_%27Upload_to_Commons%27_Android_App/Renewal#Renewal_approved). :) We (Vivek, Neslihan and myself) plan on starting on 23rd Oct if we receive our agreements by then. 

I will be updating this with a timeline and the measures of success shortly, and we can use this thread to track IEG updates and progress. We will also be tidying up the issues soon, assigning the IEG-related issues to grantees and filling up https://github.com/commons-app/apps-android-commons/projects/3

Also, we would like to welcome @neslihanturan as the new assistant project maintainer. :) She will be responsible for testing and merging PRs, organizing issues, supporting volunteers and new contributors, and generally keeping the repo in good shape. 

Many thanks to all the volunteers and contributors who have stayed with us through the past few months! We hope to make lots of progress on the app soon.

**Comment by misaochan** [comment]
Estimated timeline:

[IEG_2017_gantt_chart.pdf](https://github.com/commons-app/apps-android-commons/files/1409598/IEG_2017_gantt_chart.pdf)

**Comment by maskaravivek** [comment]
Closing this task as it was for IEG 2017.
