### ISSUE TITLE
10 different pictures uploaded under the same title, overwriting all but the last one

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#919]
https://commons.wikimedia.org/wiki/File:Small_branded_swift.jpeg#filehistory

[Discussion about that incident at Commons](https://commons.wikimedia.org/wiki/Commons:History_merging_and_splitting/Requests#File:Small_branded_swift.jpeg_.E2.86.92_File:Small_branded_swift_01.jpeg.2C_File:Small_branded_swift_02.jpeg.2C_File:Small_branded_swift_03.jpeg.2C_File:Small_branded_swift_04.jpeg.2C_File:Small_branded_swift_05.jpeg.2C_File:Small_branded_swift_06.jpeg.2C_File:Small_branded_swift_07.jpeg.2C_File:Small_branded_swift_08.jpeg.2C_File:Small_branded_swift_09.jpeg.2C_File:Small_branded_swift_10.jpeg)

Not sure what version of the app the user has... is there a way to know?

By the way, these graphs shows we still have occasional overwrites, could be people using old versions of the app: http://tools.wmflabs.org/commons-app-stats/

**Comment by misaochan** [comment]
It says "uploaded via Mobile 2.4.2 Android.". Oh dear. :/

Hopefully our planned improvements to prevent overwrites will fix this in the near future.

**Comment by oe-bayram** [comment]
Does ist have something to do with issue #228 which is also open?

**Comment by neslihanturan** [comment]
This should be fixed
