### ISSUE TITLE
Travis Fails

### ISSUE THREAD

**Issue by neslihanturan** [commons-app/apps-android-commons#924]
Travis fails by my last merges, however I am pretty sure these merges are not the reason for this. If you look at the PRs list, you will notice our latest pull requests are always failed with Travis. This log may be meaningful:

```
FAILURE: Build failed with an exception.
* What went wrong:
A problem occurred configuring project ':app'.
You have not accepted the license agreements of the following SDK components:
[Android SDK Platform 26].
Before building your project, you need to accept the license agreements and complete the installation of the missing components using the Android Studio SDK Manager.
```
Do you have any idea about how to accept license agreements?

**Comment by misaochan** [comment]
Interesting, I re-ran the build after @psh submitted the Travis commit hoping it'd fix it, but it doesn't seem to be the case.

**Comment by misaochan** [comment]
Hmmm, seems like it works actually? Build passes now.

**Comment by whym** [comment]
The first idea I wrote here (adding explicit acceptance) didn't work, another attempt (adding "android-26") seemed to work. The PR has both.

**Comment by misaochan** [comment]
Cool, thanks. :)

**Comment by misaochan** [comment]
PR #932 fails Travis with the same error - license agreement

**Comment by maskaravivek** [comment]
We can probably close this issue for now and monitor failures on travis. I will try to make sure that any failures on travis are addressed.

**Comment by misaochan** [comment]
Great, thanks @maskaravivek !

**Comment by neslihanturan** [comment]
Travis on master fails again :/

**Comment by whym** [comment]
Does it (still) fail? Latest build seems to have passed (January 2). https://travis-ci.org/commons-app/apps-android-commons/builds

I think [this](https://travis-ci.org/commons-app/apps-android-commons/builds/323803637) was a problem with the particular patch (which seems to have been fixed already).

**Comment by neslihanturan** [comment]
Yes, I am re-closing this issue
