### ISSUE TITLE
Memory leak in Contributions Activity

### ISSUE THREAD

**Issue by maskaravivek** [commons-app/apps-android-commons#938]
It leaks `ContributionsActivity` instance. 

![contributions_activity_leak](https://user-images.githubusercontent.com/3069373/32420013-529fadaa-c2aa-11e7-9c74-8cb7c5f631f6.png)

**Comment by maskaravivek** [comment]
Closing this as the PR is now merged.

**Comment by maskaravivek** [comment]
Closing this as the PR is now merged.

**Comment by neslihanturan** [comment]
Here is new leak:
![device-2017-11-21-002635](https://user-images.githubusercontent.com/3127881/33042401-cc86bf06-ce52-11e7-8af2-0230163beb43.png)
