### ISSUE TITLE
Crash when showing user's (big) uploads

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#94]
The user has uploaded about 3000 files, recently one of them being 58 MB.
https://groups.google.com/forum/#!topic/commons-app-android/4TKcnLCSEMo

```
USER_COMMENT=it crashed while loading/showing my uploads. i guess that the problem is that i have too many and too big already uploaded files.
ANDROID_VERSION=4.4.2
APP_VERSION_NAME=1.12
BRAND=samsung
PHONE_MODEL=GT-I9195
CUSTOM_DATA=
STACK_TRACE=java.lang.OutOfMemoryError
at java.io.ByteArrayOutputStream.toByteArray(ByteArrayOutputStream.java:122)
at com.android.volley.toolbox.BasicNetwork.entityToBytes(BasicNetwork.java:215)
at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:104)
at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:105)
```

**Comment by misaochan** [comment]
I've been thinking about how we should fix this. Do we want to try and make it possible to display large files, or do we want to fix this in a more indirect manner by not displaying large files on the main screen to begin with?

**Comment by nicolas-raoul** [comment]
Do we download the whole files now?
We should download the previews (or even thumbnails) that are conveniently generated by Mediawiki.

For instance for the image described at https://commons.wikimedia.org/wiki/File:Eaglefairy_hst_big.jpg 

- Original file: 37 MB https://upload.wikimedia.org/wikipedia/commons/c/c9/Eaglefairy_hst_big.jpg
- Preview: 60 KB https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Eaglefairy_hst_big.jpg/1200px-Eaglefairy_hst_big.jpg
- Thumbnail: 3 KB https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Eaglefairy_hst_big.jpg/120px-Eaglefairy_hst_big.jpg

Other resolutions available: 320 × 158 pixels | 640 × 316 pixels | 1,024 × 506 pixels | 1,280 × 633 pixels | 7,804 × 3,857 pixels (if the picture is big enough in the first place)

**Comment by misaochan** [comment]
I looked into it, and as far as I can see we are downloading thumbnails, the 640x316 pixels one (when downloading the image is necessary). In ContributionsListAdapter.java, it uses the same process as the one used to display individual contributions (that we were talking about yesterday).

`String actualUrl = (contribution.getLocalUri() != null && !TextUtils.isEmpty(contribution.getLocalUri().toString())) ? contribution.getLocalUri().toString() : contribution.getThumbnailUrl(640);
`

So if the image exists on the device storage, it loads from device storage, and if image doesn't exist on device storage, it downloads the 640x316 pixel file from the internet.

Is it possible that 3000 is just too many?

**Comment by nicolas-raoul** [comment]
To reproduce and debug the crash, you could hardcode this particular user's URL I guess? And see what happens.

I guess most of this user's images are not on device storage.

**Comment by misaochan** [comment]
Did the user ever get back to you about what his Commons username was? I looked through the google groups thread and couldn't seem to find his reply.

**Comment by whym** [comment]
I believe we can close this in favor of #607 which was fixed.
