### ISSUE TITLE
Memory leak in NearbyActivity

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#941]
Happened after getting an empty Nearby list.

![screenshot_20171107-021752](https://user-images.githubusercontent.com/3611199/32452727-1b169b16-c366-11e7-82a5-7c18c74ef5a3.png)

**Comment by maskaravivek** [comment]
Am working on fixing the above fix. Found another leak in `NearbyActivity`
![nearby_leak](https://user-images.githubusercontent.com/3069373/32456807-e8e84554-c34c-11e7-8ada-1944011db530.png)

**Comment by maskaravivek** [comment]
Closing this as the PR is now merged.

**Comment by neslihanturan** [comment]
Here is new leak:
![device-2017-11-21-002652](https://user-images.githubusercontent.com/3127881/33042465-0192e954-ce53-11e7-89aa-fa0ae0ca12fb.png)
