### ISSUE TITLE
Miles or km in Nearby Places

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#943]
This came to the mailing list:

> Should add toggle to display miles or km on Nearby Places

Rather than creating another setting/toggle, getting that from the phone's locale would be better I guess. Maybe it is done already, please someone check, thanks!

**Comment by tobias47n9e** [comment]
Using "en_us" to mean non-metric units is a pretty annoying assumption a lot of software makes. I am in favour of not implementing any of this. Any person using the app will know what meters are, and the purpose of the measurements is just to give a rough distance. Anything else is done better in dedicated routing apps.

**Comment by nicolas-raoul** [comment]
@tobias47n9e So you mean kilometers for all?
While I usually don't like to compromise on localization, I have to agree to not making our code more complex in order to accommodate what could be considered an archaism lol.
