### ISSUE TITLE
A single activity is instantiated multiple times - Back Stack

### ISSUE THREAD

**Issue by neslihanturan** [commons-app/apps-android-commons#944]
I couldn't find a relevant issue, so created new one. If you switch between home and nearby multiple times, you can see all instances of activities by pressing back button. We shouldn't let multiple instances of same activity.

**Comment by ramarajesh2112** [comment]
This is because the finish() method is not being called upon the current activity which is leading to have it running in the background when we switch to a new activity. Fixed this is this PR https://github.com/commons-app/apps-android-commons/pull/949. 
Please review and share any feedback.

**Comment by maskaravivek** [comment]
@misaochan Can this issue be closed?

**Comment by misaochan** [comment]
Yup, thanks all!
