### ISSUE TITLE
Implement upload button to allow the user to select Camera or Gallery

### ISSUE THREAD

**Issue by maskaravivek** [commons-app/apps-android-commons#950]
Making a sub task from #252. 
Implement upload button, making sure to check for necessary permissions and to allow the user to select Camera or Gallery. The scope of the task is to to refactor the upload interactions. 

Instead of having two buttons on the `ContributionsActivity` there can be a single upload button and on clicking it, a dialog will open which would look similar to: 

![choose_image](https://user-images.githubusercontent.com/3069373/32692111-469c32f2-c738-11e7-90ab-ed6118b178f2.png)

This refactoring will help in continuing the flow from #922. From the mocks, it looks that we will have a single button for uploading in the `NearbyActivity` and there too the same code can be reusing for choosing and attaching the image. 

Another advantage will be the extensibility it would offer. It will be very easy to add other file types like PDF, audio and video later.

**Comment by neslihanturan** [comment]
Since we decided to use FABs on #725 I am closing this issue.
