### ISSUE TITLE
Zooming does not work when pinching with the finger on the same horizontal line (on Nearby map)

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#957]
Zooming/unzooming depends on where your two fingers are placed.

It is a bit difficult to explain, but if you think of an analog clock:
- Fingers at 12 and 6: Zooming works
- Fingers at 3 and 9: Zooming does not work

**Comment by misaochan** [comment]
This refers to the Nearby map, right?

**Comment by Bluesir9** [comment]
Wouldn't zooming in and out be part of the Mapbox sdk itself?

**Comment by nicolas-raoul** [comment]
@misaochan : Yes, sorry for not precising.
@Bluesir9 : Indeed the bug is reproducible in the Mapbox demo app. Apparently there is a related bug currently https://github.com/mapbox/mapbox-gl-native/issues/10101 so let's wait until they fix things and then update, since it is not a critical bug.

**Comment by neslihanturan** [comment]
This seems like fixed from their side.
