### ISSUE TITLE
In edition screens, allow to view pic full size

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#96]
Often I take a pic of a local building, for instance the local chamber of commerce, then later in the day I send it to the app, and when I start typing a name I realize I don't really know the exact name that is written on the front of the building.

Was it "Chamber of Commerce of Uttar Pradesh" or "Lucknow Chamber of Commerce" or a slightly different name?

The name can be seen in the pic, but the Gallery app is busy with the UploadToCommons activity. The image is also in the background, but darkened and covered by UI elements.

My workaround in such cases is to use a different gallery app to view the pic full screen. This is a hassle, and most people don't have a second gallery app. The same problem happens in other scenarios, I often want to zoom into a detail of the picture to add the right tag or description.

So, it would be great to be able to see the pic full-screen from the title/description and the categorization screens.

**Comment by neslihanturan** [comment]
Currently we can move on photo on title/description screen, so one part of this enhancement is already done.
- We can not see the image on category screen though, but we can always come back to previous screen to see the picture again. 

The current implementation satisfies me in terms of seeing details. What do you think @nicolas-raoul ? Should we close this issue?

**Comment by nicolas-raoul** [comment]
Ah, yes this is solved indeed, thanks for noticing :-)
