### ISSUE TITLE
Create screenshots for YOURLANGUAGE

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#960]
_(Only for Google Code-in)_

Requirement: "YOURLANGUAGE" must be a language that you can read and write very well, typically your native language. For instance, if your native language is Telugu and you can write in Telugu, then follow the instructions below and write the pictures names/descriptions in Telugu.

# A. Context
- Commons is a big repository of images that are used in Wikipedia.
- Commons Mobile App is an Android app that allows volunteers to upload pictures taken with their phones.
- Screenshots are one of the main ways for new users to learn what the app is, its goal, and to understand how it works.
- The app's description page currently only has screenshots in English, which is unfortunate for people whose native language is not English.
- So, we want screenshots of the app in many other languages.
- These screenshots will be examples for the users, so they must be of high quality, the instructions below will lead you in this process.

# B. Preparation
1. Get or borrow an Android phone (not a tablet).
2. Set it to portrait mode (not landscape).
3. Install the [latest version of the app](https://play.google.com/store/apps/details?id=fr.free.nrw.commons).
4. Start the app and create an account. Your username will be visible to everyone on the Internet, so choose something not too personal and not offensive, for instance `Pablo8374` is OK.
5. In your phone's camera app, [enable GPS](https://www.phonearena.com/news/How-to-turn-GPS-location-tags-on-and-off-for-your-photos-on-Android_id64932) to store location.
6. The next step will be taking pictures. Please understand these rules for pictures:
- It must be pictures that you have taken. Not pictures taken by other people. Not pictures downloaded from the web. ([more info](https://commons.wikimedia.org/wiki/Commons:First_steps/Contributing))
- The pictures must not be too dark, so it is better to take them in a bright place, during the day, outside.
- The pictures must not be blurry. Hold the camera firm when taking each picture.
7. So, take three pictures:
  a. One picture of a school's main building ([example](https://commons.wikimedia.org/wiki/File:CD_Girls_Inter_College.JPG)), please also note the exact name of the school, and the name of the building if it has a name.
  b. One picture of a car ([example](https://commons.wikimedia.org/wiki/File:Audi_80_V1_restylee_2.JPG)), please also note the car's brand and model, and the name of the street or neighborhood. If you are in a place with no cars at all, a picture of another vehicle (such as a truck/tractor/motorbike/bicycle) is acceptable too.
  c. One picture of a restaurant ([example](https://commons.wikimedia.org/wiki/File:2012_Cairo_7381841634.jpg)), please also note what kind of food the restaurant serves, and the name of the street or neighborhood.
7. [Switch your phone's language](https://www.wikihow.tech/Change-the-Language-in-Android) to YOURLANGUAGE, if not done already. For example, if you want to create screenshots in the Telugu language, then change your phone's language to Telugu.

# C. Take screenshots

## Nearby
1. Start Google Maps or another app that uses the GPS, and make sure the GPS can see where you are. You might need to go to the window to get GPS signal. You must be in a place with an Internet connection, though.
2. Start the Commons Android app.
3. In the side menu, tap "Nearby".
4. Let the page load, it should take less than a minute.
  - If you get a message like "No nearby places found", it most probably means that the app failed to catch a GPS signal in time, so go outside to a place with a good view of the sky, restart your phone so that everything is clean, start Google Maps or another GPS app to make sure you have a GPS signal, then start Commons and try again.
  - If it still does not work, or if you don't have an Internet connection outside, install https://play.google.com/store/apps/details?id=com.lexa.fakegps then restart your phone, start Fake GPS, set the location to a city near your place, press the green button, then start Commons and try again. It should work in any case.
5. Zoom a bit so that the blue markers are a bit everywhere.
6. Swipe away all notifications, to make the screenshots cleaner.
7. [Take a screenshot](http://www.makeuseof.com/tag/6-ways-to-take-screenshots-on-android/).
![nearby-map](https://user-images.githubusercontent.com/99590/32837980-e02be742-ca52-11e7-9fec-bf406a4a49d6.png)
8. Press the "list" icon in the upper right.
9. Swipe away all notifications, then take a screenshot.
![nearby-list](https://user-images.githubusercontent.com/99590/47553200-64ad9800-d941-11e8-9879-de5b9c663bb0.jpg)

## School
1. Go back to the main screen of the Commons Android app.
2. Tap the "Picture" button, which is the most top-right button (on the right of the "Camera" button).
3. Select the school picture.
4. Enter as a name `Main building of the school ABC in DEF`. Replace `ABC` with the school's exact name and `DEF` with the street or neighborhood name, and translate to YOURLANGUAGE, for instance Telugu.
5. Enter as a description `This school teaches students from level GHI to JKL`. Replace `GHI` and `JKL` with the appropriate levels, and translate to YOURLANGUAGE.
6. Before going to the next step, swipe away all notifications, then take a screenshot.
![school-description](https://user-images.githubusercontent.com/99590/32838000-ebef718e-ca52-11e7-8710-b3ab640cf1e8.png)
7. Press the "Send " icon in the upper-right. 
8. You will now have to select the most appropriate categories for the picture. If you took the school picture in Dhaka then the most appropriate category is [Schools in Dhaka](https://commons.wikimedia.org/wiki/Category:Schools_in_Dhaka). Categories are all in English. Try to find a category called `Schools in MNO` (replace MNO with your town or state or country name). If you can't find, choose the category `Schools` and the category for the school's town or state, for instance `Dhaka`. [This page](https://commons.wikimedia.org/wiki/Category:Schools_by_country) may help you find the exact name of the best category. Then select the category by tapping the check symbol on the right of the category so that it turns green.
9. With the category name visible in the search bar but the keyboard hidden (you may need to press Back once to hide the keyboard), swipe away all notifications, then take a screenshot.
![school-categories](https://user-images.githubusercontent.com/99590/32838014-f7609232-ca52-11e7-9ac5-1f2ea13286b1.png)
10. Press the "Save" icon in the upper-right.
11. The image should have appeared in the app's main activity. Click on it to reveal the details activity.
12. Swipe up a bit to reveal the image's information. Still let a little bit of the image visible at the top so that viewers understand what it is about.
13. Swipe away all notifications, then take a screenshot.
![school-details](https://user-images.githubusercontent.com/99590/32838024-ff211460-ca52-11e7-8725-1d0945929a65.png)

## Car
Repeat the same steps (two screenshots) with the following:
- Name: `Car by maker ABC, model DEF`. Replace `ABC` and `DEF` with the car's maker (example: `Toyota`) and model (example: `NS4`), and translate to YOURLANGUAGE, for instance Telugu.
- Description: `Picture shot in GHI`. Replace `GHI` with the street or neighborhood name, and translate to YOURLANGUAGE.
![car-description](https://user-images.githubusercontent.com/99590/32838062-21c1bf92-ca53-11e7-8636-b1c24dd81e76.png)
- Category: Look for a category called `JKL vehicles`. Replace `JKL` with the maker's name, for instance [Toyota vehicles](https://commons.wikimedia.org/wiki/Category:Toyota_vehicles). [This page](https://commons.wikimedia.org/wiki/Category:Schools_by_country) may help you.
![car-categories](https://user-images.githubusercontent.com/99590/32838079-311ed182-ca53-11e7-972b-623177a03bb1.png)
![car-details](https://user-images.githubusercontent.com/99590/32838083-339ca844-ca53-11e7-935a-4d4a781f310b.png)

## Restaurant
Repeat the same steps (three screenshots: description, categories, details) with the following:
- Name: `Restaurant in ABC`. Replace `ABC` with the street or neighborhood name, and translate to YOURLANGUAGE.
- Description: `This restaurant serves DEF`. Replace `DEF` with the kind of food the restaurant serves, and translate to YOURLANGUAGE.
![restaurant-description](https://user-images.githubusercontent.com/99590/32838166-65bea3d6-ca53-11e7-9e4f-632f35d55f2c.png)
- Category: Look for a category called `Restaurants in GHI`. Replace `GHI` with the town or state's name, for instance [Restaurants in Quito](https://commons.wikimedia.org/wiki/Category:Restaurants_in_Quito) [This page](https://commons.wikimedia.org/wiki/Category:Restaurants_by_country) may help you.
![restaurant-categories](https://user-images.githubusercontent.com/99590/32838172-6bde9e92-ca53-11e7-9462-ebe0dac33814.png)
![restaurant-details](https://user-images.githubusercontent.com/99590/32838176-6e281fde-ca53-11e7-8019-f84bc9471745.png)

## Gallery
1. Go the app's main activity. It shows all of your uploaded pictures.
2. Swipe away all notifications, then take a screenshot.
![gallery](https://user-images.githubusercontent.com/99590/32838188-772e8320-ca53-11e7-9b49-864c7e988881.png)
3. Swipe from the left to make the left panel appear
4. Swipe away all notifications, then take a screenshot.
![menu](https://user-images.githubusercontent.com/99590/32838196-7f548e82-ca53-11e7-9888-7c808838e86b.png)

## Gather the files
1. Put all screenshots into a folder and rename them according to what they are:
  - nearby-map.png
  - nearby-list.png
  - school-description.png
  - school-categories.png
  - school-details.png
  - car-description.png
  - car-categories.png
  - car-details.png
  - restaurant-description.png
  - restaurant-categories.png
  - restaurant-details.png
  - gallery.png
  - drawer.png
2. Check again that you have all 13 files above.
3. If you want, you can add more screenshots of things you found interesting.

# D. Send a pull request
1. Find a desktop computer.
2. Create a [Github](https://github.com) account if you don't have one already.
3. Install [GitHub Desktop](https://desktop.github.com/) (if you are familiar with Git, feel free to use your favorite Git tool instead).
4. [Fork](https://help.github.com/articles/fork-a-repo/) the [Commons Mobile App's marketing repository](https://github.com/commons-app/marketing).
5. [Clone](https://help.github.com/en/desktop/contributing-to-projects/cloning-a-repository-from-github-desktop) your forked repository. Be sure to clone YOUR own repository, not ours.
6. Find the folder `marketing` folder on your computer, then inside it `screenshots`.
7. Within the `screenshots` folder, create a new folder with the name of YOURLANGUAGE and its code and your nickname, for instance `Telugu te-IN Pablo8374`.
8. Within that folder that you created, put all of the screenshots.
9. [Select and commit the files](https://help.github.com/desktop/guides/contributing-to-projects/committing-and-reviewing-changes-to-your-project/#2-selecting-changes-to-include-in-a-commit) with the commit message `Added screenshots for YOURLANGUAGE` (replace with your language), then push.
10. Go to https://github.com/commons-app/marketing/pulls and click the button "New pull request", then submit the pull request to us ([tutorial about pull requests](https://help.github.com/articles/creating-a-pull-request-from-a-fork/)).
11. We will review your contribution, merge it into our repository, and award you the task :-)

_If you have trouble with this section, please search on the web for a Git tutorial, and try again. If after really trying hard you still don't manage to get it right, then you can also send us the files in a ZIP by email to nicolas.raoul@gmail.com mentioning the language and why you had problems with Git._

**Comment by ardovic** [comment]
I was about to make screenshots in Russian, yet got a problem with installed Beta. The "Nearby" doesn't work anymore, tried with GPS on and on several devices, will debug later this week.

**Comment by nicolas-raoul** [comment]
@ardovic: Thanks for your feedback! It seems that beta has some problems indeed, so please use the app from Google Play. I will fix the instructions, thanks for letting us know :-)

**Comment by divadsn** [comment]
@nicolas-raoul how about using the demo mode which is available in the Developer Options since 6.0 Marshmallow? This will make the creation of screenshots much more easier and they will look more clean and consistent when swiping them.

**Comment by nicolas-raoul** [comment]
@divadsn Yes that's a great idea! Thanks!

Everyone who is comfortable enough with enabling Developer Options, please use Demo Mode as explained by @divadsn

**Comment by ch3nkula** [comment]
Imported as: https://codein.withgoogle.com/dashboard/tasks/4631530673537024/. 👍
