### ISSUE TITLE
Number of uploads not updating

### ISSUE THREAD

**Issue by abhi472** [commons-app/apps-android-commons#961]
even after uploading two images the toolbar's subtitle shows 0 uploads
![screenshot_20171115_153608](https://user-images.githubusercontent.com/17140215/32830611-c4fcc504-ca1b-11e7-976b-dcf12eae3b1a.jpg)

**Comment by neslihanturan** [comment]
Thanks for report @abhi472 , I experienced same issue on 4.2.4 device. Can you share your Android vesrion?

**Comment by abhi472** [comment]
sorry to have not mentioned it in the issue itself, 
i checked this on a v6.0.1 device

**Comment by maskaravivek** [comment]
@abhi472 Is this happening on the beta build? We have a known issue where the upload count doesn't reflect correctly on beta/debug builds as it uses the beta commons.

**Comment by abhi472** [comment]
@maskaravivek yes it happened in betaDebug

**Comment by maskaravivek** [comment]
We depend on a https://tools.wmflabs.org/ API to get the upload count. They don't have an equivalent API for commons beta. So with the current approach this issue cannot be resolved. 

It would be great if we are able to explore an API that supports both commons and beta commons

**Comment by misaochan** [comment]
Yeah, this is a known issue with our beta product flavours sadly, but as beta is only used for testing (and will never be released to users), it isn't a high-priority problem IMO.

**Comment by neslihanturan** [comment]
Actually it happens to me on product too:/

**Comment by janpio** [comment]
Anybody talked to the person offering the API on  tools.wmflabs.org if he could create a variante for the beta host?

**Comment by misaochan** [comment]
@neslihanturan Oof, really? Which version of the app are you experiencing this issue with - Google Play beta, Google Play production, or master?

@janpio My memory might not be accurate, but if I recall correctly the person who implemented the wmflans tool for us was @urbamecm ? Hi Martin, can you confirm? :)

**Comment by urbanecm** [comment]
Hello Josephine, yeah, I was the one who created the wmflabs tool. Should I do anythin with this issue?

**Comment by janpio** [comment]
Nice, hi @urbanecm :)

There now exists a beta/debug version of the app that uses a different host - so that test uploads don't land on production Commons and get deleted and make people unhappy. It would be neat if the wmflabs tool would also exist for that host, so it could be used to display the correct number.

@misaochan can probably provide the correct host the beta/debug version uses.

**Comment by urbanecm** [comment]
If we're talking about the beta cluster (https://commons.wikimedia.beta.wmflabs.org/wiki/Main_Page), it seems to be almost impossible to create similar api as for the prod one. I depend on Tool Labs replicas and as beta cluster contains just some random gibberish, it isn't replicated. I may try to precalculate number of uploads and create similar API which will serve such pre-calculated numbers. 

As the test version of the app should never be propagated to the users, my question is: Is it really needed to be fixed? What about just some notification: „The numbers of uploads doesn't work correctly in the testing version for technical reasons“? 

Let me know if I should look into it. 

By the way by reading through the whole issue I can see that @neslihanturan expierenced this issue at prod version too. If that's true I kindly ask they to give me their on-wiki username so I can investigate futher.

**Comment by janpio** [comment]
If it is not "yeah, I can deploy the same code again with another hostname configured" for you (which I hoped...) then it indeed probably isn't worth the effort.

**Comment by misaochan** [comment]
Hi @urbanecm , thanks for dropping by! :) Yeah, I don't think it is a high priority fix, so if it will be difficult then it won't be worth it IMO. Although @neslihanturan did mention something about it not working for her on prod as well, can you confirm this Neslihan?

**Comment by neslihanturan** [comment]
Yes, I can confirm @misaochan :/
![device-2017-11-20-234837](https://user-images.githubusercontent.com/3127881/33040858-6f49d594-ce4d-11e7-90fa-62088fdb32c0.png)

**Comment by urbanecm** [comment]
I will be happy to investigate but I really do need your on-wiki username for it. Can you give it to me please? Thanks!

**Comment by neslihanturan** [comment]
Yes, it is my prod account. Actually I was aware of this issue before we have beta flavors, but I have never thought it is not reported. My username is "Neslihan Turan" thanks @urbanecm !

**Comment by urbanecm** [comment]
Ok, that's caused by the spaces. I thought that I will be requested with URL like "https://tools.wmflabs.org/urbanecmbot/uploadsbyuser/uploadsbyuser.py?user=Neslihan%20Turan" (URL encoded space) but the URL was "https://tools.wmflabs.org/urbanecmbot/uploadsbyuser/uploadsbyuser.py?user=Neslihan_Turan" (underscore instead of a space). 

As underscore is an illegal char in username (It's converted to space automatically by MediaWiki), the API should give same results for both URLs listed above. 

Can you try it again @neslihanturan ? If the app do no caching, it should work right now. 

Best, 
Martin

**Comment by neslihanturan** [comment]
It works now @urbanecm , thanks a lot!

**Comment by janpio** [comment]
Maybe not use the API on betaDebug then but just display a ? to avoid confusion?

**Comment by urbanecm** [comment]
You're welcome @neslihanturan. 

@janpio Agree with you.
