### ISSUE TITLE
same image is being uploaded

### ISSUE THREAD

**Issue by abhi472** [commons-app/apps-android-commons#962]
while uploading a new image if the recent upload is failed and then restarted,
another image is being uploaded
this "other image" is basically the very first image that was uploaded so the image from the bottom of the stack is being picked up.

![screenshot_20171115_155056](https://user-images.githubusercontent.com/17140215/32831135-56a871dc-ca1d-11e7-9af3-bce226e3760b.jpg)

here the bottom image was my first upload and the image which is second from bottom was my second upload but i interrupted it by disconnecting wifi,
upon resuming the upload the image was uploaded instead of the image which was picked from the camera

**Comment by neslihanturan** [comment]
Hmm, I think the reason can be match of file name. I experienced a similar issue, I have uploaded files named "test" previously, and nominated them to be deleted. After they are deleted, black cells in the grid of contributions list has remained still. And whenever someone upload a picture with same file name, I can see them in my upload list in place of my deleted test files.

**Comment by maskaravivek** [comment]
This is fixed now. Closing the issue.
