### ISSUE TITLE
Remove suggestion to skip categories

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#963]
The categories screen says:

> Tap this message (or hit back) to skip this step.

I believe categories should never be skipped. Pictures with no categories have much less values and give a bad name to the app. I think this sentence should be removed.

**Comment by juniaziz** [comment]
I started working on it and found where it is coming from in the code...How should I handle this? Just remove the .isEmpty condition and display the No categories matched text? Any ideas? 

`if (categoriesAdapter.getItemCount() == selectedCategories.size()) {
                                // There are no suggestions
                                if (TextUtils.isEmpty(filter)) {
                                    // Allow to send image with no categories
                                    categoriesSkip.setVisibility(View.VISIBLE);
                                } else {
                                    // Inform the user that the searched term matches  no category
                                    categoriesNotFoundView.setText(getString(R.string.categories_not_found, filter));
                                    categoriesNotFoundView.setVisibility(View.VISIBLE);
                                }
                            }`

**Comment by nicolas-raoul** [comment]
I don't think it is the right place.
To begin, please try to replace the text `Tap this message (or hit back) to skip this step.` with the text `Hello`.

**Comment by pawan92** [comment]
Hey I would like to fix this but wanted to verify it was just deleting that line of code? Please let me know.

**Comment by nicolas-raoul** [comment]
@pawan92 What line of code are you talking about?
But yes, it is probably as easy as removing a line of code.
Please include a screenshot in your pull request, thanks :-)

**Comment by pawan92** [comment]
I have been trying to find the correct file where it outputs that message ("Tap this message (or hit back) to skip this step.") but have been unsuccessful. any suggestions? or am i going about this the wrong way?

**Comment by gokberksahin** [comment]
I made a PR for this, why it hasn't been merged?

**Comment by misaochan** [comment]
So sorry for the mixup guys. :/ This should have at least have been tagged as "assigned" after that PR was submitted, even if we didn't have time to test and merge it yet. @neslihanturan could you please test #964 and see if it solves the issue? If it does we can close this. Apologies again.
