### ISSUE TITLE
Report that Nearby item is not at specified location

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#965]
Sometimes Nearby makes me go to a place, and I realize that there is nothing, for instance it was supposed to be a museum but it is just fields. This probably happens to any regular Nearby user.

This leads to frustration, and if nothing is done the point stays on the Nearby map, and another person (or forgetful me) might be tricked by it again.
But this could be turned into a very positive experience that benefits Wikidata: Let the user report the point.

Implementation could be a "Report" button that proposes:
- The item is not found around that point
- The point is a bit further
- The item does not exist anymore at that place

Feedback could be appended to a particular Wikidata maintenance article such as https://www.wikidata.org/wiki/User:Syced/Commons_Mobile_App

**Comment by janpio** [comment]
How is such "maintenance" done in Commons itself, outside the context of the app?

**Comment by nicolas-raoul** [comment]
commons.wikimedia.org does not even have a Nearby feature, actually.
This is Wikidata maintenance rather than Commons maintenance, within the purpose of adding missing content to Commons.
The same concept could probably be used for OpenStreetMap points, though.

**Comment by janpio** [comment]
Yeah right, I was wondering how they normally do the "Oh, I noticed this data/entry is wrong, let's fix it" process.

**Comment by misaochan** [comment]
@nicolas-raoul Sounds good, but if we do that we probably need someone to consistently check that article and make the necessary modifications, otherwise they may get even more frustrated. :) I don't think the regular Commons/Wikidata volunteers will be willing to do it.

**Comment by nicolas-raoul** [comment]
@misaochan I volunteer to monitor that page, fix what I can, and announce the rest on Wikidata's project chat :-)
I guess it will not be more than 50 reports a month anyway, even when the app becomes very popular.

**Comment by misaochan** [comment]
Thanks @nicolas-raoul ! :) So implementation-wise, we are really just talking about a link that takes the user to https://www.wikidata.org/wiki/User:Syced/Commons_Mobile_App , right?

**Comment by nicolas-raoul** [comment]
Actually, I was thinking about a UI with radio buttons letting the user choose what the problem is.
This UI would automatically post a message on the wiki page above in the user's name, including the item's identifier and the selected problem.
That forces the user to include the reason of the problem (some users would just say "It does not work").
Another advantage is that it writes reports in English. The UI would ideally be translated to the users' languages.

**Comment by Rishavgupta12345** [comment]
@nicolas-raoul @4D17Y4  According to https://github.com/commons-app/commons-app-documentation/blob/master/android/Students.md can i consider this project to work on in GSOC 2022 ?

**Comment by nicolas-raoul** [comment]
@Rishavgupta12345 If for any reason you are strongly motivated by (https://github.com/commons-app/apps-android-commons/issues/953 + https://github.com/commons-app/apps-android-commons/issues/965), you can choose it. But otherwise I would suggest #4764.

**Comment by nicolas-raoul** [comment]
Duplicate of https://github.com/commons-app/apps-android-commons/issues/2425
