### ISSUE TITLE
Adding history to nav bar

### ISSUE THREAD

**Issue by neslihanturan** [commons-app/apps-android-commons#970]
Since we plan to add edit function, what about adding display history too? We can display edits, uploads, nominations for deletion, adding a photo to a nearby place with P18, sending us a feedback etc.

**Comment by madhurgupta10** [comment]
@neslihanturan Its been a long time since this issue was opened, I would like to work on it if it is still needed to be solved :)

**Comment by neslihanturan** [comment]
It seems like nobody is interested. So better not to implement this one and close this issue.
