### ISSUE TITLE
Failing UI test for NearbyActivity

### ISSUE THREAD

**Issue by maskaravivek** [commons-app/apps-android-commons#978]
Recently one of the tests started failing. Heres the build stackstrace.

```
fr.free.nrw.commons.NearbyActivityTest > testActivityLaunch[test(AVD) - 5.1.1] FAILED 
	java.lang.RuntimeException: Could not launch intent Intent { act=android.intent.action.MAIN flg=0x14000000 cmp=fr.free.nrw.commons/.nearby.NearbyActivity } within 45 seconds. Perhaps the main thread has not gone idle within a reasonable amount of time? There could be an animation or something constantly repainting the screen. Or the activity is doing network calls on creation? See the threaddump logs. For your reference the last time the event queue was idle before your activity launch request was 1511464601042 and now the last time the queue went idle was: 1511464601042. If these numbers are the same your activity might be hogging the event queue.
	at android.support.test.runner.MonitoringInstrumentation.startActivitySync(MonitoringInstrumentation.java:419)
:app:connectedBetaDebugAndroidTest FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:connectedBetaDebugAndroidTest'.
```

When I run the task `:app:connectedBetaDebugAndroidTest` locally, it succeeds for me. 

Can anyone help with this issue. @whym @psh

**Comment by whym** [comment]
For me it was locally reproducible. It appears that NearbyActivity gets stuck with https://github.com/commons-app/apps-android-commons/commit/a61124a5802060338819b22c33a20ca475c8e582 when run with "gradle connectedCheck -Dtest.single=fr.free.nrw.commons.NearbyActivityTest"

With https://github.com/commons-app/apps-android-commons/commit/21f08ae9862c5d3386de3ffaeffafce7e258365b it went through. (I needed to respond to the request for location permission manually.)

So probably it has to do with #975?

**Comment by psh** [comment]
I moved the test and switched it over to a *Robolectric* based unit test.  I believe this issue can be closed now.

**Comment by maskaravivek** [comment]
thanks @psh
