### ISSUE TITLE
Remove option to load from CSV for Nearby

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#979]
The "load from CSV" option is a relic of our initial Nearby prototype before we switched to using Wikidata queries. Personally, I think Wikidata is superior in all aspects and I have never used the CSV option after Wikidata implementation because the CSV takes about 5 minutes to load each time. Nobody that I have talked to currently uses the CSV either.

We were discussing removing the CSV entirely at #291 , and some were supportive of it. Benefits of removing the option in my opinion:
- Simplifies the implementation of further Nearby enhancements (e.g. direct uploads)
- Allows us to close all issues caused by the CSV without wasting developer time solving them
- Prevents potential cases of a user accidentally tapping that option in Settings and then wondering why Nearby takes forever to load for him
- Simplifies testing

What do you guys think? Is there anyone here who would prefer we keep the CSV option?

**Comment by tobias47n9e** [comment]
I agree with removing the CSV option.

**Comment by misaochan** [comment]
All done. :)
