### ISSUE TITLE
Rename? GitHub will help potential first-time contributors discover issues labeled with "help wanted" or "good first issue"

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#980]
> Now, GitHub will help potential first-time contributors discover issues labeled with "help wanted" or "good first issue"

Should we rename our existing "beginner friendly" label?

Also, would it make sense to use the "help wanted" label?
I guess all of our non-discussion issues would have it, so I have doubts.

We would have to modify our up-for-grabs.net configuration too.

**Comment by chrisdebian** [comment]
Nicolas, this sounds like a good idea. I've also learned that "up-for-grabs.net" exists :-)
