### ISSUE TITLE
Optional Permissions in Nearby Places activity?

### ISSUE THREAD

**Issue by maskaravivek** [commons-app/apps-android-commons#982]
On opening `NearbyActivity` when location is disabled, the alert dialog shows the following permission. The text is somehow misleading as its not possible to show nearby places without location permissions in `NearbyActivity`. 

![optional_permissions](https://user-images.githubusercontent.com/3069373/33229158-3e7158e8-d1ef-11e7-9b12-80ae573ca759.png)

IMO it makes more sense to ask for location permissions, mandatorily in `NearbyActivity`. 
- If the user grants location permissions, load nearby places
- Else finish the activity. 

Comments, @nicolas-raoul @misaochan

**Comment by nicolas-raoul** [comment]
Sounds reasonable!

**Comment by misaochan** [comment]
I agree, the text is misleading, your suggestion sounds good to me.
