### ISSUE TITLE
Testing Release build?

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#988]
After the current fiasco, I realized that we should probably be testing the Release build (as opposed to just the Debug build) before uploading a new version to the Play Store, lol. The main problem is that testing that build requires the APK to be signed, and the inbuilt "sign APK" UI option in Android Studio just hardcodes the key passwords etc into the gradle file, clearly not an option for an open-source app.

I found several options mentioned at https://stackoverflow.com/questions/18328730/how-to-create-a-release-signed-apk-file-using-gradle and am wondering which is the best one to use (since all of them would require some form of gradle file modification). I am leaning towards Gal Bracha's suggestion for ease of use, but I don't see how it allows other people without the key to test the build, as he mentioned.

**Comment by janpio** [comment]
Aside: Do you really need a signed "Release" build, or just a development build of the code and settings that would end up in a signed build?

**Comment by psh** [comment]
I (personally) got around the issue by using environment variables on my machine - in my `build.gradle` I have
```groovy
def env = System.getenv()
ext.keystore = env.APP_KEYSTORE ?: 'unsigned'
ext.password = env.APP_KEYSTORE_PASSWORD ?: 'unsigned'
```
and then later on
```groovy
signingConfigs {
    release {
        storeFile file(keystore)
        keyAlias 'my_key_alias'
        storePassword password
        keyPassword password
    }
}
```
And that way the passwords are not embedded in my git repo, but I also have the convenience of not typing a huge command line when I want to release - I just set the "APP_KEYSTORE" and "APP_KEYSTORE_PASSWORD" environment variables on my build server.

**Comment by nicolas-raoul** [comment]
Yes, environment variables is how I do for my apps, it works well :-)

**Comment by misaochan** [comment]
Thanks guys! Do those methods allow others to test the Release build as well, though? I would still need to send the keystore to whomever needs to test the Release build, I figure?

**Comment by nicolas-raoul** [comment]
@misaochan You don't need (and should probably not :-) ) send the keys to everyone.
Everyone can sign using their own keys, using the exact same code and Gradle files.

**Comment by misaochan** [comment]
Oh, so the "signed" release doesn't actually have to be signed with the exact key that we use for the Play Store! (as long as we don't intend to upload to it on that build)

Cool, thanks @nicolas-raoul . I had no idea, haha.

**Comment by nicolas-raoul** [comment]
Yes, for instance the F-Droid maintainer signs all apps (including Commons) with his own key (we never gave our keystore/keys to him), and people can use the app normally, it behaves normally regardless of who signed it. The signature is only checked by Google Play (when uploading the APK).
