### ISSUE TITLE
Salt usernames when logging

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#994]
> The app sends data to several eventlogging schemas (owned by WMF) for tracking user behavior in various parts of the app. In these schemas, I noticed that the actual username of the current user is transmitted and stored, unhashed and unsalted.  Ideally the username should be hashed with salt, so that the event logging can be as anonymous as possible.  For comparison, the Wikipedia app generates and stores a random UUID, which it sends in place of the username. This way, we can still track events from the "same" user, but it's completely anonymous.

**Comment by janpio** [comment]
Event logging is per user, not per installation?

**Comment by deydebaditya** [comment]
I can implement hashing with salt using BCrypt (Blowfish algorithm), as I've done this previously too. As I am new, please do refer me to the activity file and the java class which refers to the above functionality, I'd implement the patch right away.

**Comment by nicolas-raoul** [comment]
Sorry for keeping this open, we removed this kind of logging altogether: https://github.com/commons-app/apps-android-commons/commit/da82466a170a0a6df67423b39292e8fcfab85fe2
